### ISSUE TITLE
Can one message is both an order message and transactional message?

### ISSUE THREAD

**Issue by gaboolic** [apache/rocketmq#1036]
Version: rocketmq 4.3.0
I read the GUIDE :http://rocketmq.apache.org/docs/transaction-example/
And I read the code in TransactionMQProducer.java
But I don't know how to make a transactional message to be an order message at the same time？
So my question is Can one message is both an order message and transactional message?

**Comment by gaboolic** [comment]
事务消息可以是顺序消息吗？

**Comment by fantasygg** [comment]
我看到之前有关于这个的issue，[https://github.com/apache/rocketmq/issues/505](url) 
你可以参考一下
