### ISSUE TITLE
consume message Hang

### ISSUE THREAD

**Issue by xiaoyanghapi** [apache/rocketmq#1037]
1. 问题描述
一个消费者订阅多个topic，刚上线时消息消费一切正常，过一段时间之后（时间不确定多长），消费位点会出现不提交的情况，但是消息是在正常消费的，通过vkmq-admin查询消费位点的情况，消息一直在堆积。

**Comment by ssssssnake** [comment]
查看是否有消费超时发生（会有重试消息）

**Comment by xiaoyanghapi** [comment]
> 查看是否有消费超时发生（会有重试消息）

存在重试消息，但是消费者还是不能正常消费，一直卡在产生重试消息的那个时间点

**Comment by Ah39** [comment]
看消费线程是否一直block住了，如果有一条消息，消费没有返回，就会导致消费offset不会前进

**Comment by xiaoyanghapi** [comment]
> 看消费线程是否一直block住了，如果有一条消息，消费没有返回，就会导致消费offset不会前进

怎么才能避免这种情况

**Comment by Ah39** [comment]
这个是有些问题，目前就会有。如果做的好一些，就是这个队列长时间被block住，server端得释放当前当前队列，让别的client可以消费

**Comment by gaoyf** [comment]
@xiaoyanghapi  一个订阅组只能订阅一个topic，[参考](https://blog.csdn.net/a417930422/article/details/50663639)。
