### ISSUE TITLE
Does RocketMQ-4.x.x support master/slave change role automaticly

### ISSUE THREAD

**Issue by ChesterZheng** [apache/rocketmq#1043]
Hello, all
I have a question.
Does RocketMQ-4.x.x support master/slave to change role automaticly when master crashed?

**Comment by ChesterZheng** [comment]
Hello, all
I have a question.
Does RocketMQ-4.x.x support master/slave to change role automaticly when master crashed?

**Comment by ymwneu** [comment]
The released 4.x.x versions are not support role change automatically.
But it will be supported soon, the branch "develop" is already supported by using dledger.
Quick start of deldger: https://github.com/apache/rocketmq/blob/develop/docs/cn/dledger/quick_start.md

**Comment by ChesterZheng** [comment]
> 
> 
> The released 4.x.x versions are not support role change automatically.
> But it will be supported soon, the branch "develop" is already supported by using dledger.
> Quick start of deldger: https://github.com/apache/rocketmq/blob/develop/docs/cn/dledger/quick_start.md

**Comment by ChesterZheng** [comment]
Thanks bro.
