### ISSUE TITLE
slave instance can not synchronize data from master

### ISSUE THREAD

**Issue by dut-xiayuan** [apache/rocketmq#1057]
**BUG REPORT**

1. Please describe the issue you observed:
- What did you do (The steps to reproduce)?
- What did you expect to see?
- What did you see instead?

Hi, when I add rocketmq slave instance to a 2m-noslave cluster, the added slave instance does not synchronize data from master which has the same broker name as expected. 

I found that the master instance got a private IP address(docker0) as haServerAddr and the slave could not reach.

2. Please tell us about your environment:

Apache rocketmq version: **4.3.1**

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

I think there should be a more comprehensive approach in below method to private address filtering to avoid such confusing issues

**RemotingUtil.getLocalAddress()**
![image](https://user-images.githubusercontent.com/5948633/53935844-d8776280-40e2-11e9-89e1-44a8b0ad624a.png)

**Comment by ymwneu** [comment]
In this situation, you can use mqadmin command "updateBrokerConfig" to update the  brokerIP2 property.
