### ISSUE TITLE
HA housekeeping failure, master close the connection frequently

### ISSUE THREAD

**Issue by zhanguohuang** [apache/rocketmq#1082]
#The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
Start a master and slave in the default way. And then do not send any messages.

- What did you expect to see?
Whether or not a message is sent, the master will not disconnect from the slave unless there is an exception.

- What did you see instead?
The log will be found on master‘s storing logs every 20 seconds. This log is as follows:
**ha housekeeping, found this connection[ip:port] expired, 200xx**
At the same time, the log is as follows will be found on slave's storing logs:
**HAClient, processReadEvent read socket < 0**

2. Please tell us about your environment:
rocketmq version: 4.3.2
jdk version:  1.8.0_101

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
When the connection was just established,, the WriteSocketService.run() blocks waiting for the slave to escalate the offset (default 5 seconds), and if a message is sent in at this point, and master's mode for disk flush is SYNC_MASTER, the time-consuming of CommitLog.handleHA(args) will be affected, causing the **producer send message timeout.**

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zhanguohuang** [comment]
I have solved this problem. #1083

**Comment by chengqipeng** [comment]
zhanguohuang您好，请问下有解决上面问题吗，现在用rocketmq双主双从，经常出现org.apache.rocketmq.remoting.exception.RemotingTimeoutException: wait response on the channel <10.111.xxx.xxx:10911> timeout, 3000(ms)

**Comment by zhanguohuang** [comment]
如果你确认问题跟我描述的完全一样，就可以参考以下两种方案：
1.调整slave中的参数haSendHeartbeatInterval从5000调到4000，master不需要改，用mqadmin updateBrokerConfig即可，不需要重启(推荐使用此方案)
2.查看我提的pr #1083 ，需求修改源码打包部署到slave机器上，而且需要重启。 @chengqipeng 

补充：我提的另一个issue也会导致你说的这个问题 #1108 ，及它的解决方案 #1109
