### ISSUE TITLE
Ordered message with same shardingKey may parallel consume when it's repeat

### ISSUE THREAD

**Issue by hankchan101** [apache/rocketmq#1084]
As the tittle said, In our business scene, I using the uniqueId as shardingKey to send Order Message.

When the Consumer start, the processing is as follow:
"select uniqueId from bussiness Database", if Not exist, INSERT, else UPDATE

but, I found that the same uniqueId has double INSERT...

So, after checking bussiness code, I guess Ordered message with same shardingKey may parallel consume when it's repeat

**Comment by dut-xiayuan** [comment]
Maybe because you are consuming messages in concurrently mode
