### ISSUE TITLE
消息生产成功后，消息者端1小时后才收到

### ISSUE THREAD

**Issue by vacheli** [apache/rocketmq#1091]
新建的topic在晚上23:10使用同步的方式生产4条消息均成功。但是消息者端1时后才收到消息。使用console和mqadmin只能查看到消息的生产时间与消息的内容，而且cpu、内存、磁盘io均正常。
有什么办法可以排查这种问题吗？

补充：
topic被创建在broker-a上，4个队列。

版本信息：
rocketmq 版本 4.2.0
客户端      版本 4.2.0

配置：
双nameserver
broker-a 主从之间为同步，异步刷盘。
broker-b 主从之间为同步，异步刷盘。

**Comment by duhenglucky** [comment]
@vacheli 具体的可以看下日志，看下客户端的rebalance的日志同时结合消息的borntime以及storetime进行排查，咨询的话尽量在邮件列表发起讨论：https://rocketmq.apache.org/about/contact/，会有很多小伙伴帮助解答的。
