### ISSUE TITLE
HA机制，master长时间宕机重启后产生重复消费

### ISSUE THREAD

**Issue by beijixiongzzj** [apache/rocketmq#1094]
master停机5分钟期间slave开始承接正常业务，客户端正常消费。
5分钟后master重启，slave的syncAll()机制，从master复制了一份5分钟前的消费偏移量数据，覆盖掉了最新的偏移量信息。
导致client消费到的重复的消息。

希望提供官方的master重启机制。
建议后期添加节点内broker同步数据以offset最大为主，和master与slave反向同步的机制。
或者在重启服务前，节点要完全下线，slave下线不提供服务，master重启前，从slave最大偏移量线下拷贝consumeOffset.json文件。

**Comment by duhenglucky** [comment]
@beijixiongzzj 这一块的确可以优化，但是反向复制的话会增加系统的复杂度，当然，拷贝位点文件也是个不错的做法，如果这块有想法的话，可以在邮件列表里面发起一个讨论：https://rocketmq.apache.org/about/contact/，很多小伙伴会一期参与讨论的。

**Comment by beijixiongzzj** [comment]
我后来又仔细想了一下，这个问题的解决之道，在于运维方式，应该是在master上线前，将这个节点下的所有slave全部下线，脱离集群后，从所有slave中找到一个最大的offset然后，将offset文件手工覆盖到master的offset文件后再将所有的broker重启加入到namesrv中。我觉得像这样的问题必须在官网上重点指明，不然一些生产环境出现这些问题的用户会有损失

**Comment by jinyanhui2008** [comment]
其实我也发现这个问题了,很坑,应该有个解决方案来处理,或者给一个补偿方案,而且我现在不光是主节点挡掉从节点挡掉也会有类似的问题出现.我觉得至少补偿方案应该将宕机的Node集群停掉,手工将文件同步后,再将集群拉起来,,不知道是否可行.
