### ISSUE TITLE
client与broker网络不一致情况下,findConsumerIdList机制是否合理

### ISSUE THREAD

**Issue by beijixiongzzj** [apache/rocketmq#1095]
rocketmq使用的客户端负载均衡，hash算法是在客户端实现。
该算法使用的是数据来源为 namesrv提供的broker集合，和随机到一台broker上获取findConsumerIdList的集合。
改机制可靠性成立的两个关键核心是，broker与namesrv之间的网络可靠性必须一致，和client与broker之间的网络可靠性必须一致。
一旦发生局部网络不一致则有概率产生，两个client计算出统一个MessageQueue，这样commit操作是自相冲突的。会产生重复消费。

**Comment by duhenglucky** [comment]
@beijixiongzzj 在网络出现问题或者是系统抖动的情况下确实有可能导致这些情况，所以rocketmq客户端有定时获取元数据做rebalance的机制，而且出现上述问题后，最大的可能在于重复消息，而不会丢失消息，我们认为这个是可以接受的，感谢评论，如果有诸如此类的咨询问题的话麻烦在我们的邮件列表里面讨论：https://rocketmq.apache.org/about/contact/，issue用于feature request 以及bug report。
