### ISSUE TITLE
Concurrent problems with client-side connection creation

### ISSUE THREAD

**Issue by zhanguohuang** [apache/rocketmq#1108]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
Send two messages at the same time. When the producer needs to create a new connection with the broker, one message will fail because the connection is disconnected.

- What did you expect to see?
Both messages were sent successfully

- What did you see instead?
From the producer, we can see from the log.
```
2019-03-20 17:07:35,911 INFO test1-send2mq-thread-1 NettyRemotingClient createChannel: remote host[192.168.0.2:10909] success, DefaultChannelPromise@2c99850(success)
2019-03-20 17:07:35,912 INFO test2-send2mq-thread-2 NettyRemotingClient createChannel: remote host[192.168.0.2:10909] success, DefaultChannelPromise@5a0a54b3(success)
```

From the broker, we can see it from the remoteing.log.
```
2019-03-20 17:07:35 INFO NettyServerCodecThread_1 - Netty Sever PIPELINE: channelRegistered 192.168.0.1:41548
2019-03-20 17:07:35 INFO NettyServerCodecThread_1 - Netty Sever PIPELINE: channelActive 192.168.0.1:41548
2019-03-20 17:07:35 INFO NettyServerCodecThread_1 - Netty Sever PIPELINE: channelInactive 192.168.0.1:41548
2019-03-20 17:07:35 INFO NettyServerCodecThread_1 - Netty Sever PIPELINE: channelUnregistered 192.168.0.1:41548
2019-03-20 17:07:35 INFO NettyServerCodecThread_1 - Netty Sever PIPELINE: channelRegistered 192.168.0.1:41659
2019-03-20 17:07:35 INFO NettyServerCodecThread_1 - Netty Sever PIPELINE: channelActive 192.168.0.1:41659
```

2. Please tell us about your environment:
rocketmq version: 4.3.2
jdk version: 1.8.0_101

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zhanguohuang** [comment]
I have fixed this problem. #1109

**Comment by duhenglucky** [comment]
@zhanguohuang Good catch, It seems that it's indeed a bug in creating remoting channel.

**Comment by zhanguohuang** [comment]
@duhenglucky  Thanks.

**Comment by zongtanghu** [comment]
This issue has already been resolved by link:https://github.com/apache/rocketmq/pull/1109

**Comment by lwclover** [comment]
this is my fix:
private Channel createChannel(final String addr) throws InterruptedException {
        ChannelWrapper cw = this.channelTables.get(addr);
        if (cw != null && cw.isOK()) {
            return cw.getChannel();
        }

        if (this.lockChannelTables.tryLock(LOCK_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)) {
            try {
                cw = this.channelTables.get(addr);
                if (cw == null) {
                    ChannelFuture channelFuture = this.bootstrap.connect(RemotingHelper.string2SocketAddress(addr));
                    log.info("createChannel: begin to connect remote host[{}] asynchronously", addr);
                    cw = new ChannelWrapper(channelFuture);
                    this.channelTables.put(addr, cw);
                }
            } catch (Exception e) {
                log.error("createChannel: create channel exception", e);
            } finally {
                this.lockChannelTables.unlock();
            }
        } else {
            log.warn("createChannel: try to lock channel table, but timeout, {}ms", LOCK_TIMEOUT_MILLIS);
        }

        if (cw != null) {
            ChannelFuture channelFuture = cw.getChannelFuture();
            if (channelFuture.awaitUninterruptibly(this.nettyClientConfig.getConnectTimeoutMillis())) {
                if (cw.isOK()) {
                    log.info("createChannel: connect remote host[{}] success, {}", addr, channelFuture.toString());
                    return cw.getChannel();
                } else {
                    log.warn("createChannel: connect remote host[" + addr + "] failed, " + channelFuture.toString(), channelFuture.cause());
                }
            } else {
                log.warn("createChannel: connect remote host[{}] timeout {}ms, {}", addr, this.nettyClientConfig.getConnectTimeoutMillis(),
                    channelFuture.toString());
            }
        }

        return null;
    }

**Comment by lwclover** [comment]
private Channel createChannel(final String addr) throws InterruptedException {
        ChannelWrapper cw = this.channelTables.get(addr);
        if (cw != null && cw.isOK()) {
            return cw.getChannel();
        }

        if (this.lockChannelTables.tryLock(LOCK_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)) {
            try {
                cw = this.channelTables.get(addr);
                if (cw == null) {
                    ChannelFuture channelFuture = this.bootstrap.connect(RemotingHelper.string2SocketAddress(addr));
                    log.info("createChannel: begin to connect remote host[{}] asynchronously", addr);
                    cw = new ChannelWrapper(channelFuture);
                    this.channelTables.put(addr, cw);
                }
            } catch (Exception e) {
                log.error("createChannel: create channel exception", e);
            } finally {
                this.lockChannelTables.unlock();
            }
        } else {
            log.warn("createChannel: try to lock channel table, but timeout, {}ms", LOCK_TIMEOUT_MILLIS);
        }

        if (cw != null) {
            ChannelFuture channelFuture = cw.getChannelFuture();
            if (channelFuture.awaitUninterruptibly(this.nettyClientConfig.getConnectTimeoutMillis())) {
                if (cw.isOK()) {
                    log.info("createChannel: connect remote host[{}] success, {}", addr, channelFuture.toString());
                    return cw.getChannel();
                } else {
                    log.warn("createChannel: connect remote host[" + addr + "] failed, " + channelFuture.toString(), channelFuture.cause());
                }
            } else {
                log.warn("createChannel: connect remote host[{}] timeout {}ms, {}", addr, this.nettyClientConfig.getConnectTimeoutMillis(),
                    channelFuture.toString());
            }
        }

        return null;
    }
