### ISSUE TITLE
It takes an excessively long period of time to send the first message

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#1113]
1. Please describe the issue you observed:
DefaultMQProucers takes an excessively long period( > 5 seconds) to send the very first message if not timeout.
- What did you do (The steps to reproduce)?
Time the elapsed time when sending messages.
- What did you expect to see?
Sending a single message should be completed within a few milliseconds.
- What did you see instead?
A long period of time working, more than 5 seconds are required for the first one.
2. Please tell us about your environment:
N/A

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
A pull request has been prepared.

**Comment by yuz10** [comment]
I will close the issue for duplication with #3288
