### ISSUE TITLE
消费消息的时候为何把消费逻辑命名为ConsumeRequest

### ISSUE THREAD

**Issue by reenWYJ** [apache/rocketmq#1115]
按照常规理解,Request代表remoting request,即跨实例的网络交互
而rocketmq的ConsumeRequest在同一进程内进行传递

这样命名有什么好处呢?谢谢指教

**Comment by ShannonDing** [comment]
非常感谢反馈，如果有咨询类的问题的话麻烦在开发者群里或者我们的邮件列表里面讨论：https://rocketmq.apache.org/about/contact/，issue用于feature request 以及bug report。
