### ISSUE TITLE
set run property storePathRootDir , then you will not startup

### ISSUE THREAD

**Issue by 18575531337** [apache/rocketmq#1119]
environment : windows
version:4.4.0
i set a list of startup properties,as shown below
listenPort=10912
brokerName=Fernandes_broker_A
brokerClusterName=Fernandes_broker_cluster
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

storePathRootDir=C:\Users\xx\Desktop\rocketmq-all-4.4.0-bin-release\info (if set this,can not start)
storePathCommitLog=C:\Users\xx\Desktop\rocketmq-all-4.4.0-bin-release\broker_a_master_info\logs
storePathConsumerQueue=C:\Users\xx\Desktop\rocketmq-all-4.4.0-bin-release\broker_a_master_info\queues 

so set storePathRootDir , can not start

**Comment by duhenglucky** [comment]
@18575531337 same with other the latest [issue](https://github.com/apache/rocketmq/issues/1715)
