### ISSUE TITLE
Add new feature: support namespace

### ISSUE THREAD

**Issue by lollipopjin** [apache/rocketmq#1120]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Support namespace for RocketMQ，the same topic with different namespaces represent different topics in RocketMQ Namesrv/Broker. Changes will be hold in the rocketmq-client module.

2. Provide any additional detail on your proposed use case for this feature.
If you have three environments called daily/pre-online/online, you may only want to change the endpoint or the namespace in your configs to send messages to the different topics in different environments.

**Comment by Shellbye** [comment]
关于 `namespace` 这个特性，有其他的资料吗？
