### ISSUE TITLE
关于新增broker后topic的队列分布问题

### ISSUE THREAD

**Issue by objcoding** [apache/rocketmq#1130]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
假设我现在有两个master broker分别为b1和b2组成了一个集群，我选择手动创建topic1，此时topic的路由信息会发送到b1和b2，同时b1和b2会将路由信息注册到nameserver，发送topic1的消息时，会从nameserver获取topic1的路由信息，然后进行负载均衡平均分发到b1和b2。
以上是前提，如果此时topic1的消息量剧增，b1和b2负载过高，集群这时加了b3和b4两个master broker节点，但此时b3和b4并没有topic1的路由信息，也就是topic1此时从nameserver获取到的broker信息只有b1和b2，因此虽然加了b3和b4，但topic1的消息并不会路由到b3和b4去，即达不到负载均衡的效果。

- What did you expect to see?
我期望增加节点后，topic的消息发送依然能够做到负载均衡的效果。

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ShannonDing** [comment]
You should use admin tools to create the same topic on the new broker3 and broker4, and then the topic router will be updated in the name server.
And more, it is better, IMO, to discuss these kinds of question about the code in the [develop mail list](http://rocketmq.apache.org/about/contact/).

**Comment by objcoding** [comment]
@ShannonDing Thanks to Mr. Ding's answer, this issue is that I saw the rocketmq topic creation mechanism, and some thoughts were drawn. I also wrote an article specifically: https://mp.weixin.qq.com/s/aMmLiMkt82S729BIp8B75Q
I hope that rocketmq is getting better and better!
