### ISSUE TITLE
nameServer 在处理needRegister后为什么回传dataVersion

### ISSUE THREAD

**Issue by buptlsy** [apache/rocketmq#1131]
看代码,nameserver在处理QUERY_DATA_VERSION(needRegister)时,会判断dataVersion是否改变过,并修改changed的值.判断完后为什么还需要将dataVersion回传给broker,让broker再做次判断呢?

**Comment by ShannonDing** [comment]
It is better, IMO, to discuss these kinds of question about the code in the [develop mail list](http://rocketmq.apache.org/about/contact).
