### ISSUE TITLE
  When we consume the topic of RocketMQ4.4.0,it is often cpu down to 0

### ISSUE THREAD

**Issue by qianzhiheilv** [apache/rocketmq#1133]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:
  When we consume the topic of RocketMQ4.4.0,it is often cpu down to 0
- What did you do (The steps to reproduce)?
  we start an server to consume the message of rocketmq,in first several minutes,server is ok,cpu about 80% and memory is enough(8g/64g),suddenly cpu down to 0 and after several seconds,cpu  up to 80% and every thing is ok
- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:
   RocketMQ4.4.0
   SpringBoot2.0
   Push Consumer to consume message
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by qianzhiheilv** [comment]
And there is some error like:
2019-04-01 15:57:55,055 WARN RocketmqClient - updateTopicRouteInfoFromNameServer Exception
org.apache.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: iot41-broker-to-broker-topic
See http://rocketmq.apache.org/docs/faq/ for further details.
We have set auto create topic ,server version and client version are all 4.4.0

**Comment by RongtongJin** [comment]
Pls refer to #504
