### ISSUE TITLE
The problem of new consumer with  'CONSUME_FROM_LAST_OFFSET' model

### ISSUE THREAD

**Issue by baomingyu** [apache/rocketmq#1135]
&emsp;&emsp;When  i create consumer using  a new consumer group with  'CONSUME_FROM_LAST_OFFSET'  
model and subscribe a topic that has been created and has contained messages  ,it will   
consumer all  exit messages  rather than begin from last offset.

&emsp;&emsp; I have found this problem is here .RebalancePushImpl.java -- > computePullFromWhere  
   ```
      case CONSUME_FROM_LAST_OFFSET
   ```
&emsp;&emsp;when user new consumer group the result will be 0 rather than last offset or max offset ,  
because broker will allways not do return -1 .   
&emsp;&emsp;so it will be modified with such way
   ```
      if (lastOffset > 0) {
                    result = lastOffset;
                }
                // First start,no offset
                else if (0 == lastOffset) {
                ...
   ```

**Comment by solomon4github** [comment]
one guy found the reason in 2016, https://blog.csdn.net/scutshuxue/article/details/51694334#commentBox

now the latest version is 4.5.1 and we could found the code in org.apache.rocketmq.broker.processor.ConsumerManageProcessor.class

```java
     if (offset >= 0) {
            responseHeader.setOffset(offset);
            response.setCode(ResponseCode.SUCCESS);
            response.setRemark(null);
        } else {
            long minOffset =
                this.brokerController.getMessageStore().getMinOffsetInQueue(requestHeader.getTopic(),
                    requestHeader.getQueueId());
            if (minOffset <= 0
                && !this.brokerController.getMessageStore().checkInDiskByConsumeOffset(
                requestHeader.getTopic(), requestHeader.getQueueId(), 0)) {
                responseHeader.setOffset(0L);
                response.setCode(ResponseCode.SUCCESS);
                response.setRemark(null);
            } else {
                response.setCode(ResponseCode.QUERY_NOT_FOUND);
                response.setRemark("Not found, V3_0_6_SNAPSHOT maybe this group consumer boot first");
            }
        }
```

if  minOffset <= 0 ,always return 0.

it make ‘ConsumeFromWhere’ not work.

It's confusing to me  ， and hope somebody can help solve this.
