### ISSUE TITLE
The problem of selectOneMessageQueue when send message

### ISSUE THREAD

**Issue by baomingyu** [apache/rocketmq#1136]
&emsp;&emsp;When there are three or more borkers in one topic's routeinfo ---   
 TopicPublishInfo, for example broker-001,broker-002,broker-003,Some times the   
selected messagequeue list may be broker-001 broker-002 broker-001,rather than   
broker-001 broker-002 broker-003.   

&emsp;&emsp;When sending message to broker-001\broker-002 is timeout or other problem     the send result will always be failed，and lose one chance  to send broker-003.  because it is   
not set selected pos to sendWhichQueue's ThreadLocalIndex.

**Comment by xiangwangcheng** [comment]
Maybe broker-003 couldn't send heartbeat to namsrv because the connection lost.
Can you reproducer this problem?
