### ISSUE TITLE
dledger快速部署 broker-n0/n1/n2增加aclEnable=true，启动报错

### ISSUE THREAD

**Issue by anutaisland** [apache/rocketmq#1143]
dledger快速部署 broker-n0/n1/n2增加aclEnable=true，启动报错

**Comment by zongtanghu** [comment]
When you put forward a issue about rocketmq,please follow the issue's format! @anutaisland

**Comment by zongtanghu** [comment]
I have alreay put forward a issue.The issue's link is:https://github.com/apache/rocketmq/issues/1147! You can see this one.
