### ISSUE TITLE
slave broker not set checkpoint's  physicMsgTimestamp

### ISSUE THREAD

**Issue by reachfish** [apache/rocketmq#1153]
slave broker always don't set checkpoint's physicMsgTimestamp.  so when the slave broker restart,  it need recover all the commit log map files, so it startup slowly when there are lots of commit file. 

on the contrary, master broker set checkpoint's physicMsgTimestamp. so when it restarts, it only need recover the last commit log map file.

why slave broker don't set checkpoint's physicMsgTimestamp.  is it for safety reason, or just a bug ?

**Comment by reachfish** [comment]
for slave broker:
  CommitLog.appendData(long startOffset, byte[] data)  => MappFile.appendMessage(final byte[] data), then MappedFile.storeTimestamp is always 0, ...,  finally, checkpoint's physicMsgTimestamp is always 0.

**Comment by reachfish** [comment]
for slave broker:
CommitLog.appendData(long startOffset, byte[] data) => MappFile.appendMessage(final byte[] data)
then 
 MappedFile.storeTimestamp is always 0 => MappedFileQueue's storeTimestamp is always 0 
 => checkpoint's physicMsgTimestamp is always 0.

**Comment by reachfish** [comment]
for slave broker:
CommitLog.appendData(long startOffset, byte[] data) => MappFile.appendMessage(final byte[] data)
then
MappedFile.storeTimestamp is always 0 => MappedFileQueue's storeTimestamp is always 0
=> checkpoint's physicMsgTimestamp is always 0.

maybe in function MappFile.appendMessage(final byte[] data) ,   we can set storeTimestamp = Math.max(storeTimestamp,   System.currentTimeMillis() - 30 * 1000).   something like this ?

**Comment by duhenglucky** [comment]
this issue has been resolved in this [pr](https://github.com/apache/rocketmq/pulls?q=is%3Apr+is%3Aclosed)
