### ISSUE TITLE
[Enhancement-Request] new mqadmin API for ACL configuration  

### ISSUE THREAD

**Issue by walking98** [apache/rocketmq#1156]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Current ACL configuration is to modify the yaml file directly on broker local, it needs mqadmin to provide the ability to query or modify the config remotely. The simplest way for the mqadmin API is download and upload the whole config file; the fine-grained API is to query/modify by different section, e.g. global config, individual ak/sk.  

2. Provide any additional detail on your proposed use case for this feature.

If the mqadmin has this sort of API, the other third-party can easily manage the ACL configuration in remote. e.g. RocketMQ-Console.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by luqufei456** [comment]
Can acl best practices be implemented for rocketmq4.4?

**Comment by zongtanghu** [comment]
Hi @walking98,the plain_acl.yml file of rocketmq is a structure file,so users can use mqadmin API to config which acl attributes?And I think the accesskey represents a usename,it is a unique one.So,it can't be changed.So,we can dissucss which attributes can be changed?

**Comment by walking98** [comment]
Hi @zongtanghu 
accounts:
- accessKey: RocketMQ
  secretKey: 12345678
  whiteRemoteAddress: 192.168.0.*
  admin: false
  defaultTopicPerm: DENY
  defaultGroupPerm: SUB
  topicPerms:
  - topicA=DENY
  - topicB=PUB|SUB
  - topicC=SUB
  groupPerms:
  # the group should convert to retry topic
  - groupA=DENY
  - groupB=SUB
  - groupC=SUB

I feel the rmqadmin API can operate the following attributes remotely:
1.  Add/Remove  account (ak). ak is the unique key of an account, so it can not be changed but  the account can be removed.
2. Adjust whitelist/permit groups/permit topics for a specific account

**Comment by walking98** [comment]
**FEATURE REQUEST 2**

About HA

I understand the current ACL impl needs the plain-acl.yml keep an identical copy for each broker in a RMQ cluster. The rest of yml files in different brokers should sync into the same content if anyone (leader) file is changed.

It will be a challenge for a remote management tool (i.e. mqadmin) to perform this data consistent among these yml files.

So we need to consider the High Availability situation. How to decide leader yml file and how other files follow it if the file has any change.

**Comment by zongtanghu** [comment]
@walking98 The problem of HA is much more complex to design.We need a authority service to provide some api to outer system,such as broker component.So,we can discuss this topic deeply.

**Comment by zongtanghu** [comment]
@walking98  As current acl design in rocketmq,I think the simple way to query and upate the acl configuration is adding the some parameters in the mqadmin command,such as broker ip and port.This way is the same as some mqadmin command for updating Broker Config,such as "sh mqadmin updateBrokerConfig -k connectTimeoutMillis -v 5000 -n XX.XX.XX.XX:9876 -b XX.XX.XX.XX:10911"

**Comment by walking98** [comment]
Yes, we can refer to the mqadmin updateTopic command implementation, which can support operate Topic in cluster level or individual broker level.

**Comment by zongtanghu** [comment]
> Yes, we can refer to the mqadmin updateTopic command implementation, which can support operate Topic in cluster level or individual broker level.

Okay,do someone else has other idea or suggestion? @vongosling @duhenglucky @dongeforever @wlliqipeng @ShannonDing

**Comment by zongtanghu** [comment]
This issue will be implement in this pr,the link is: https://github.com/apache/rocketmq/pull/1217

**Comment by zongtanghu** [comment]
This feature request has already been finish by this pr.The pr link is:https://github.com/apache/rocketmq/pull/1257
