### ISSUE TITLE
How to use startfsrv.sh in rocketmq4.5?

### ISSUE THREAD

**Issue by offSwitch** [apache/rocketmq#1182]
org.apache.rocketmq.filtersrv.FiltersrvStartup not include in rocketmq 4.5
./startfsrv.sh
only get Exception
Error: Could not find or load main class org.apache.rocketmq.filtersrv.FiltersrvStartup

**Comment by guixincui** [comment]
the filtersrv has been removed

**Comment by free--bird** [comment]
那么请问
在4.5版本中如果想使用 subscribe(String topic, String fullClassName, String filterClassSource) 的方式使用自定义的方式过滤消息是不是不会起作用，如果是有替代方案么？
谢谢

**Comment by vongosling** [comment]
用SQL过滤试试，之前的filter机制很不安全考虑到，很多不完备的地方，所以删除。后续基于事件过滤，会有新的解决方案替代，也欢迎加入到社区与我们共建。
