### ISSUE TITLE
checkLocalTransaction不断循环回查

### ISSUE THREAD

**Issue by zjw2011** [apache/rocketmq#1183]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- 消费端生成了1000条事务消息，消费端也成功消费了这1000个消息，有的消息消费端没有消费成功，进行了重试。但是过了一段时间，broker就不断的循环回查本地事务的状态。明明返回
COMMIT_MESSAGE了，但是还是一直在回查
- MQ服务端和消费端都是调用的4.4.0版本
![20190428155641](https://user-images.githubusercontent.com/5782008/56860917-3d0dba00-69ce-11e9-8667-abfb10c17a2d.jpg)

![20190428190606](https://user-images.githubusercontent.com/5782008/56863421-b6b2a180-69e8-11e9-9450-72443bd06cf5.jpg)

**Comment by liurenjin** [comment]
请问是怎么解决的？我这边也有遇到，同4.4.0版本

**Comment by duhenglucky** [comment]
@liurenjin no relation with this issue, but may be caused by the large size message, and [4.6.0](https://dist.apache.org/repos/dist/dev/rocketmq/4.6.0-rc1/) has been fixed，[release note](https://rocketmq.apache.org/release_notes/release-notes-4.6.0/).

**Comment by liurenjin** [comment]
@duhenglucky thanks, I saw the related issue fixed [commitlog broken](https://github.com/apache/rocketmq/issues/1568)

**Comment by 542928492** [comment]
我broker 已经升级到4.6.0 了。还是出现此现象。broker就不断的循环回查本地事务的状态。明明返回
COMMIT_MESSAGE了，但是还是一直在回查。
nameserver 使用4.2.0 ，broker 版本4.6.0

**Comment by loveship00** [comment]
？？解决了？

**Comment by 2259289435** [comment]
不晓得是不是同一个问题，有个bug是消费的时候失败设置了延迟，导致延迟加顺序一起引发了循环回查，这个不晓得有没有修复，我是本地改客户端直接修复的，消费失败发消息的时候加了个延迟，你直接清掉消费的时候的事务属性即可。




2259289435@qq.com
 
发件人： yyyyyyyyyyyy
发送时间： 2020-03-04 11:41
收件人： apache/rocketmq
抄送： Subscribed
主题： Re: [apache/rocketmq] checkLocalTransaction不断循环回查 (#1183)
？？解决了？

**Comment by duhenglucky** [comment]
> 不晓得是不是同一个问题，有个bug是消费的时候失败设置了延迟，导致延迟加顺序一起引发了循环回查，这个不晓得有没有修复，我是本地改客户端直接修复的，消费失败发消息的时候加了个延迟，你直接清掉消费的时候的事务属性即可。 2259289435@qq.com 发件人： yyyyyyyyyyyy 发送时间： 2020-03-04 11:41 收件人： apache/rocketmq 抄送： Subscribed 主题： Re: [apache/rocketmq] checkLocalTransaction不断循环回查 (#1183) ？？解决了？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的，是有这个问题，已经在4.6.1版本里面解决了
