### ISSUE TITLE
请问怎么删除一个消息

### ISSUE THREAD

**Issue by FJCDrome** [apache/rocketmq#1185]
某个第三方框架集成了RocketMq,会反序列化消息内容. 现在我在测试的时候,手动发了内容不符合的消息,结果这条消息一直反序列化失败. 请问在不清空数据的情况下, 有办法删除指定的消息吗

**Comment by xiangwangcheng** [comment]
Do u mean the message consumption continues to fail?
You can just wait because this message will be put into DLQ after trying16 times(By default), and no long to be consumed.

There is no way to delete a certain message in RokcetMQ .

**Comment by xiao-ma-nong** [comment]
举个例子
我生成这个链接30分钟有效，
如果我点击我就想要把这个消息删掉
如果没有点击那就30分钟后删调
这个怎么实现》》？？？
