### ISSUE TITLE
Tracer start failed when starting multiple MqProducer  in one  process

### ISSUE THREAD

**Issue by kangjiabang** [apache/rocketmq#1188]
i  want to use trace feature in 4.4.0.
when i  init  two  defaultMQProducer ， use  new DefaultMQProducer(producerId,true);
then i  start to send  message to test trace， trace not  work well。

i find  when producer start with trace on，it will  produce new  AsyncTraceDispatcher，in  AsyncTraceDispatcher, it will invoke getAndCreateTraceProducer method.  

`private DefaultMQProducer getAndCreateTraceProducer(RPCHook rpcHook) {
        DefaultMQProducer traceProducerInstance = this.traceProducer;
        if (traceProducerInstance == null) {
            traceProducerInstance = new DefaultMQProducer(rpcHook);
            traceProducerInstance.setProducerGroup(TraceConstants.GROUP_NAME);
            traceProducerInstance.setSendMsgTimeout(5000);
            traceProducerInstance.setVipChannelEnabled(false);
            // The max size of message is 128K
            traceProducerInstance.setMaxMessageSize(maxMsgSize - 10 * 1000);
        }
        return traceProducerInstance;
    }`
but the ProducerGroup  is same for all trace Producer . when i start two MQProducer  ,i will report error  like following .
`throw new MQClientException("The producer group[" + this.defaultMQProducer.getProducerGroup()
                        + "] has been created before, specify another name please." + FAQUrl.suggestTodo(FAQUrl.GROUP_NAME_DUPLICATE_URL),
                        null);`

**Comment by ChaosYjh** [comment]
I think it is a bug too, but it seems that no one cares about this problem.@duhenglucky ,can you look at this question? Thanks~~

**Comment by duhenglucky** [comment]
@ChaosYjh try to setInstanceName when create producer

**Comment by zongtanghu** [comment]
@ChaosYjh @kangjiabang  We will check this issue in our local enviroment.

**Comment by ChaosYjh** [comment]
> polish

It has noting to do with instanceName,because producerGroup always be TraceConstants.GROUP_NAME.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/27771595/59734474-22e0b180-9284-11e9-81f8-5b514fe0342e.png">

And if you ensure this is a bug,I will commit a PR later.@zongtanghu @duhenglucky.
Thanks !

**Comment by ChaosYjh** [comment]
> @ChaosYjh try to setInstanceName when creating producer，and recommend to create one producer to send different topic messages, and it would be nice if you can proposal a PR to polish this issue.
Set instanceName can resolve this problem,but it will create double tcp connection at least.
In our users, there are many application system use producer and consumer both ,and there are three or four consumerGroup,may be more.So I hope they use one clientInstance in common to create tcp connection as little as possible and save resource.
In AsyncTraceDispatcher,traceProducer specified producerGroup by TraceConstants.GROUP_NAME  always, so I think can we specify a different producerGroup for each traceProducer and use one instanceName in common?
<img width="561" alt="image" src="https://user-images.githubusercontent.com/27771595/59737030-a7383200-928e-11e9-95c8-ae5504b593a9.png">

**Comment by ahuazhu** [comment]
@ChaosYjh Thanks, Set different ProducerGroups for consumer/producer will resolve the problem. I will create a PR to fix the bug.
https://github.com/apache/rocketmq/pull/1275

**Comment by lnfdxwl** [comment]
@ahuazhu hi，when make release ，thanks

**Comment by duhenglucky** [comment]
fixed in the 4.6.1
