### ISSUE TITLE
duplicate message id?

### ISSUE THREAD

**Issue by zjw2011** [apache/rocketmq#1192]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

I found duplicate message id when use rocketMq 4.4.0
![20190430181433](https://user-images.githubusercontent.com/5782008/56955471-1ab5a100-6b74-11e9-81c1-beb36fee256f.jpg)

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

Java8 macOSX

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by llb520** [comment]
Why does this happen and how to fix it
