### ISSUE TITLE
Subscription group not deleting

### ISSUE THREAD

**Issue by jothipandiyanjp** [apache/rocketmq#1193]
I am trying to delete a subscription group from the broker using the following command. 
 ./mqadmin  deleteSubGroup  -b serverip:10911 -c DefaultCluster -g c15d8027-3775-4511-bf16-24ea6c5890b7-Sessions-Consumer -n serverip:9876

But while deleting in a broker logs it prints as follow:
deleteSubscriptionGroup called by ****
2019-05-03 19:08:38 WARN AdminBrokerThread_5 - delete subscription group failed, subscription groupName: c15d8027-3775-4511-bf16-24ea6c5890b7-Sessions-Consumer not exist

![image](https://user-images.githubusercontent.com/20284584/57133880-e46d6100-6dc1-11e9-8483-8c840e18f4da.png)

![image](https://user-images.githubusercontent.com/20284584/57133960-1d0d3a80-6dc2-11e9-83f9-6a0ad2db353d.png)

How to solve this issue?
Is any suggestion to delete a subscription group from the broker?

**Comment by duhenglucky** [comment]
@jothipandiyanjp Please confirm whether the deletion operation is successful. You can open the file ‘subscriptionGroup. Json ’to confirm. It looks like it's been deleted
