### ISSUE TITLE
About dLeger Config dLegerPeers address No doubts and doubts

### ISSUE THREAD

**Issue by Liberxue** [apache/rocketmq#1194]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

Why can't dLegerPeers address be designed to be obtained directly from namersrv?

https://github.com/apache/rocketmq/blob/971fa8ed8b209b39bdfe41c57cd64576d244e6bd/store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java#L148

https://github.com/apache/rocketmq/blob/971fa8ed8b209b39bdfe41c57cd64576d244e6bd/store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java#L682

https://github.com/apache/rocketmq/blob/971fa8ed8b209b39bdfe41c57cd64576d244e6bd/store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java#L687

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zongtanghu** [comment]
@Liberxue You can do some deep research into the openmessaging dledger wiki,the link is:https://github.com/openmessaging/openmessaging-storage-dledger/blob/master/docs/cn/introduction_dledger.md

**Comment by Liberxue** [comment]
@zongtanghu 
Thanks, I mean why you should configure it manually in the configuration file.
```dLegerPeers=n0-127.0.0.1:40911;n1-127.0.0.1:40912;n2-127.0.0.1:40913```

- Instead of getting ``dLegerPeers`` automatically from ``nameSrv``?
- What was the original intention of manually configuring this design?
- Can I modify it?

**Comment by Liberxue** [comment]
Can I change the dLeger source code to automatically register dLegerPeers according to dLegerSelfId?
Now this way, the new node and the kicking node are very troublesome (can not dynamically add and delete nodes), this one is now responsible for no, if not, how do I receive the task card?
```shell
dLegerPeers=n0-127.0.0.1:40911;n1-127.0.0.1:40912;n2-127.0 .0.1:40913
```
@zongtanghu
