### ISSUE TITLE
Polish message trace default topic config 

### ISSUE THREAD

**Issue by duhenglucky** [apache/rocketmq#1200]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
In order to support regionId used in broker, so it will be better if we can use this setting to build the default trace topic.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

**Comment by zongtanghu** [comment]
This issue have been released in the 4.5.1 version of RocketMQ.So I close this issue.
