### ISSUE TITLE
mqadmin topicList cmd/API need identify system topic

### ISSUE THREAD

**Issue by walking98** [apache/rocketmq#1203]
**BUG REPORT**

1. Please describe the issue you observed:

sh mqamin topicList -n XXX:9876 
This cmd will return all topic list in nameserver, it can identify RETRY，DLQ by “%*” prefix，but it can not tell a system topic. 

need a way to identify system topic, e.g. with "%SYS%"; 
or specific api:  sh mqamin sysTopicList -n xxx

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

**Comment by walking98** [comment]
A workaround API is through the Producer. i.e.
DefaultMQProducer producer = ...
producer.start();
producer.getDefaultMQProducerImpl().getmQClientFactory().getMQClientAPIImpl().getSystemTopicList(20000L);

**Comment by walking98** [comment]
BTW,  topic 'RMQ_SYS_TRANS_HALF_TOPIC' should be System topic

**Comment by duhenglucky** [comment]
RocketMQ system topic began with "RMQ_SYS" or "rmq_sys".
