### ISSUE TITLE
Alibaba Summer of Code 2019

### ISSUE THREAD

**Issue by wlliqipeng** [apache/rocketmq#1204]
2019 Alibaba Summer of Code
---
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience software development in the real world. Alibaba Summer of code will begin between June 28th and September 20th. Students can use the summertime to participate in the open source project and work with the core members of the project.

What you can get?
---
On this exclusive developer journey, students will have the opportunity to:

Participate in the top projects of the International Open Source Foundation;
Get a scholarship from Alibaba;
Obtain an open source contributor certificate;
Get a fast pass of Alibaba Internship/recruitment;
Get your code adopted and used by the open source project！

Our Mentor
---
liqipeng
GitHub ID: wlliqipeng
Apache RocketMQ China Community Initiator & Committer

duheng
github：duheng
Apache RocketMQ PMC member/Committer，Linux OpenMessaging TSC member

Apply Now!
---
You can click on this link to apply directly:
https://github.com/apache/rocketmq-externals/issues/274
https://github.com/apache/rocketmq-externals/issues/273
full list of Alibaba Summer of Code Projects：

https://developer.aliyun.com/summerofcode2019

Timeline⏳
---
![image](https://user-images.githubusercontent.com/31427177/57502321-ce115900-731d-11e9-9730-0d58da5ea682.png)

Contact us!
---
Email Address: aliopensource@alibabacloud.com

**Comment by vongosling** [comment]
@wlliqipeng could you retweet your post in dev and user mail list firstly? It would be helpful if you could give more eyes on how to build community as the Apache RocketMQ Community done before(such as apache way.).

**Comment by nisarg1499** [comment]
@wlliqipeng @duhengforever 
I would like to get some more information regarding the Apache RocketMQ projects(features) for SoC19. Basically I am interested in participating in SoC19 and would like to work on RocketMQ Projects.

**Comment by duhenglucky** [comment]
@nisarg1499 Thanks for your attention，very glad that you are interested in the SoC19, so could you leave your email in here? We will keep you informed on further developments, and also, information and docs will be updated in this issue.

**Comment by nisarg1499** [comment]
Hi,
I am Nisarg Shah currently pursuing B.Tech(2nd year completed) in Information and Communication Technology from Ahmedabad University. I came along with Alibaba Summer of Code website and I think I am interested in rocketmq project.

I am proficient in C,C++ and Java. And I have also started some contributions to Jenkins Project. I have started solving few bugs and issues and currently working on few more bugs too. In a short period of time I will also start contributions to OpenGenus Foundation Open Source Projects. Actually I love coding and explore new technologies. I am good in data structures and algorithms and currently exploring advanced algorithms. I am very much interested in contributing to Open Source Projects and learn new things. I also practice competitive programming on various platforms like codechef, hackerrank.

If you can provide me some material by which I can start then it would be a great help. Few materials which can help me understand the projects in a detailed manner, and few tutorials and materials or some thing which a contributor should know beforehand would be helpful.
And do you have any gitter room or any means of communication where details of these projects are discussed ?

I did not saw particular projects list for RocketMQ. Can you just share me some project ideas for SoC19. I would like to choose a project which involves problem solving and writing code in Java as a main language. If you could help me selecting the project.

Waiting for your reply.

Thanks and regards,
Nisarg Shah
