### ISSUE TITLE
Previous offset doesn't need to be checked again

### ISSUE THREAD

**Issue by sanzado** [apache/rocketmq#1206]
When client update offset, previous offset is discarded and doesn't need to be checked again.

**Comment by duhenglucky** [comment]
@sanzado Could you give more details？ and issue only used for bug report and feature request，If you have some questions, please use our mailing list(https://rocketmq.apache.org/about/contact/) there are many users will help you.

**Comment by sanzado** [comment]
Thanks for your reply. Sorry for the wrong operation. It's my first pulling request. Not a bug, just a simple code optimization.
