### ISSUE TITLE
Springboot发布到外部tomcat，启动报错The consumer group has been created before, specify another name please

### ISSUE THREAD

**Issue by gavinWithGu** [apache/rocketmq#1208]
改造spring boot工程发布到外部tomcat，启动时报错

```
Caused by: com.alibaba.rocketmq.client.exception.MQClientException: The consumer group[..] has been created before, specify another name please.
See http://docs.aliyun.com/cn#/pub/ons/faq/exceptions&group_duplicate for further details.
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.start(DefaultMQPushConsumerImpl.java:584)
	at com.alibaba.rocketmq.client.consumer.DefaultMQPushConsumer.start(DefaultMQPushConsumer.java:374)
```

程序中没显示启动consumer两次，请问是什么问题？

**Comment by walking98** [comment]
@gavinWithGu 

https://github.com/apache/rocketmq-spring/blob/master/rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/StringConsumerNewNS.java

如果你的consumerlistener使用默认的nameserver (即， application.properties中属性rocketmq.nameServer定义的值)，则不需要再@RocketMQMessageListener中指定nameServer属性； 如果一定要指定这个属性， 则这个属性值必须要与默认的nameserver取值不同。

另外，建议这个issue在 https://github.com/apache/rocketmq-spring 子项目中提出，可能会帮助更多的朋友。

**Comment by gavinWithGu** [comment]
@walking98  我们项目中是使用了
`DefaultMQPushConsumer.registerMessageListener(new MessageListenerOrderly()...  `
这种方式启动消费监听的，在init方法中会显示设置namesrvAddr，其他地方没有创建消费者监听的代码。

**Comment by ShannonDing** [comment]
@gavinWithGu Please move this issue to  https://github.com/apache/rocketmq-spring , thanks.
