### ISSUE TITLE
latest code on branch master not correct

### ISSUE THREAD

**Issue by CoderLan0668** [apache/rocketmq#1211]
while creating or updating topic on rocketmq console, the step is:

1、the console will request the broker to create or update topic, look the class AdminBrokerProcessor  in broker

![image](https://user-images.githubusercontent.com/50652021/57796205-5e1a2d00-777a-11e9-9e51-7b3b1253ac01.png)

the broker will try to registerIncrementBrokerData to namesrv,  go ahead ,i found the code of sending remote command to namesrv, it is in BrokerOuterApi:

![image](https://user-images.githubusercontent.com/50652021/57796470-eb5d8180-777a-11e9-8bff-4b5a6c9e8bc3.png)

**note: the data that broker sent to namesrv is json format string( actually byte array) of The Class RegisterBrokerBody**

2、the namesrv receive the command sent by broker, namesrv try to deserialize, look the code below

![image](https://user-images.githubusercontent.com/50652021/57796838-a7b74780-777b-11e9-99d2-2cddb35c9ad7.png)

**note: namesrv deserialze as TopicConfigSerializeWrapper, but not RegisterBrokerBody**

finally, the console told me that it is success to create or update topic, but actually it take no effect.

**Comment by duhenglucky** [comment]
@CoderLan0668 It seems that there's a bug in RocketMQ console,  could you help to resolve this issue by pull a request to RocketMQ console, we will help you to complete this PR.

**Comment by CoderLan0668** [comment]
@duhenglucky  there is nothing to do with The RocketMQ console. Actually, the broker receive the topic config data correctly, the broker serialize the data as Class RegisterBrokerBody (by json format)， and send to the name server. But the name server deserialize the data as Class  TopicConfigSerializeWrapper(by json format),  the error happens.

**Comment by CoderLan0668** [comment]
finally i found it is not a bug. the name server process the broker register cmd as old version. because i run the brokerlocally by sources, and The rocketmq.remoting.version not set to the env.

![image](https://user-images.githubusercontent.com/50652021/58247118-7518da80-7d8b-11e9-97fe-be877b3ef4bb.png)


but i think this is a bad design.
