### ISSUE TITLE
NettyRemotingClient.java's line 144 why mod 999 twice?

### ISSUE THREAD

**Issue by yiwuxia** [apache/rocketmq#1212]
the code is follow:
 ```
private static int initValueIndex() {
        Random r = new Random();

        return Math.abs(r.nextInt() % 999) % 999;
    }
```
the result  Math.abs(r.nextInt() % 999)  is always equal   Math.abs(r.nextInt() % 999) % 999?
so why do you write this code ?  necessary?

**Comment by duhenglucky** [comment]
@yiwuxia It seems to be redundant here, this code is not very elegant, and can be polished, the issue only used for the bug report and feature request，If you have some questions, please use our mailing list(https://rocketmq.apache.org/about/contact/) there are many users will help you.
I will close this issue, please feel free to reopen it if you have more question.
