### ISSUE TITLE
MVN Build ERROR

### ISSUE THREAD

**Issue by jackwener** [apache/rocketmq#1220]
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rocketmq-logging

**Comment by duhenglucky** [comment]
@jackwener please upgrade your jdk to 1.7 or later, and issue only used for bug report and feature request，If you have some questions, please use our mailing list(https://rocketmq.apache.org/about/contact/) there are many users will help you.
I will close this issue, and if you think this a bug, please feel free to reopen it.

**Comment by jackwener** [comment]
> @jackwener请将你的jdk升级到1.7或更高版本，并且只用于bug报告和功能请求，如果你有一些问题，请使用我们的邮件列表（https://rocketmq.apache.org/about/contact/）有很多用户会帮助你。
> 我将关闭此问题，如果您认为这是一个错误，请随时重新打开它。

~/rocketmq-rocketmq-all-4.4.0 java -version                          14:20:40
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**Comment by jackwener** [comment]
> @jackwener please upgrade your jdk to 1.7 or later, and issue only used for bug report and feature request，If you have some questions, please use our mailing list(https://rocketmq.apache.org/about/contact/) there are many users will help you.
> I will close this issue, and if you think this a bug, please feel free to reopen it.

but .....my jdk is 1.8
~/rocketmq-rocketmq-all-4.4.0 java -version                          14:20:40
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
