### ISSUE TITLE
RocketMQ support from Dledger pattern degrading to master/slave. 

### ISSUE THREAD

**Issue by zongtanghu** [apache/rocketmq#1222]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Rocketmq needs to support from Dledger pattern degrading to master/slave when one node fails if there are only two nodes in current cluster.

2. Provide any additional detail on your proposed use case for this feature.
XXX;

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
XXX;

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by RongtongJin** [comment]
If one node fails in three nodes group, rocketmq on dledger will re-elect a leader as master, another node will be slave, the process of replication is similar to master-slave synchronous replication.

**Comment by vongosling** [comment]
@zongtanghu Is that problem what you're talking about? I will close the pr for now. rocketmq on dledger will be polished in the latest 4.6.0 version, any problem we could use this thread to followup.
