### ISSUE TITLE
 DLQ Topics should have read permission by default

### ISSUE THREAD

**Issue by Allen-zhu** [apache/rocketmq#1223]
1. Please describe the issue you observed:
    **I have to change the DLQ topic perm to 6 one by one，before I query message from it.**
- What did you do (The steps to reproduce)?
   **forexample： query the DLQ message on rocket-console** 
- What did you expect to see?
   **The detail message  in DLQ topics.**
- What did you see instead?
     **an error occurred
    "org.apache.rocketmq.client.exception.MQClientException: Can not find Message Queue for this topic, %DLQ%XXXXXXXXXX Namesrv return empty"**
2. Please tell us about your environment:
    **CentOS release 6.5 (Final), JDK1.8.0_121**
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
    **In my eyes,  add the read permission  to the DLQTopic when create it in SendMessageProcessor class has  no effect on the software,**  
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
    **add the read permission  to the DLQTopic** 
2. Provide any additional detail on your proposed use case for this feature.
    **something like problem location or dlq message load  and record** 
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
    **should-have.
    we change the source code and rebuilt it.**
4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

**Comment by duhenglucky** [comment]
@Allen-zhu DLQ is the last safeguard for consumed failed messages, so be as cautious as possible. There are many different views on this issue, so it's would be better to discuss it in the dev@rocketmq.apache.org mailing list first
