### ISSUE TITLE
maybe a bug in HaService

### ISSUE THREAD

**Issue by jiayeee** [apache/rocketmq#1227]
The issue comes from my code review, not a practical operation

in java class org.apache.rocketmq.store.ha.HAService.GroupTransferService#doWaitTransfer, there is `waitForRunning` between the `requestsRead`, so elder request will encounter a long delay more than 5 * 1000 millis? is it a bug?

**Comment by ahuazhu** [comment]
If the slave is hanged, the request will take more than 5 seconds. In more cases, master-slave synchronization will be fast, so this problem does not occur.
