### ISSUE TITLE
Why not use AbstractBatchDecode？

### ISSUE THREAD

**Issue by 3EDCKenneth** [apache/rocketmq#1230]
关于消息传输，不采用AbstractBatchDecode是出于什么考虑呢？

**Comment by duhenglucky** [comment]
@3EDCKenneth AbstractBatchDecode似乎确实拥有更高的性能，但是最好是能够提供一个可以量化的对比，欢迎做个测试，然后大家一起讨论一下：），相关的讨论最好在dev@rocketmq.apache.org邮件列表里面，毕竟大家对remoting层相关对改动都非常关心
