### ISSUE TITLE
how to set the dlq queue back to be consumed怎样把死信队列中的消息放回队列重新消费

### ISSUE THREAD

**Issue by KobeWangBeabloo** [apache/rocketmq#1236]
as every one knows how to read the DLQ messages, but we can not find any ways to send the messages back to the normal queue so that the messages can be consumed again.

如题，我们可以通过更新死信topic的perm为6，然后在console中查看到死信队列中的消息，但是怎样才能把死信队列中的消息重新发送到队列中让它重新消费呢?

**Comment by duhenglucky** [comment]
@KobeWangBeabloo 目前开源版本暂时没有提供导出功能，如果有兴趣的话，可以提个PR，为社区用户提供此功能，我们会帮助你完成这个PR。另外，issue只用于bug 报告以及新特性申请，如果有什么需要帮助的，麻烦在邮件列表（https://rocketmq.apache.org/about/contact/）里面咨询，很多小伙伴会帮助你的。
