### ISSUE TITLE
求助一个业务场景问题

### ISSUE THREAD

**Issue by cookiejoo** [apache/rocketmq#1239]
各位好！
我有一个业务场景的使用问题是这样的：
消息提供者只有一个主题，主要就是消费者这边需要设计为集群消费，但是没一个阶段需要消费两次相同的消息，类似于单节点广播消费。因为单节点要消费两次做Master和Slave写数据。
有这种模式吗？
求指导

**Comment by duhenglucky** [comment]
@cookiejoo 这种情况下可以设置为不同点consumer group，不同consumer group是类似于广播消费短，issue只用于bug 报告以及新特性申请，如果有什么需要帮助的，麻烦在邮件列表（https://rocketmq.apache.org/about/contact/）里面咨询，很多小伙伴会帮助你的。
