### ISSUE TITLE
Suggestion about the third part dependency of the RocketMQ client.

### ISSUE THREAD

**Issue by ChaosYjh** [apache/rocketmq#1241]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
我认为rocketmq应该尽量减少客户端不必要的包引用以降低包冲突的风险。如下图一，客户端在添加acl支持的时候，所引用的guava包，仅仅在org.apache.rocketmq.srvutil.FileWatchService#FileWatchService里被用来做字符串的空判断（图二），其实完全可以用common模块所引用的commons-lang3包里的StringUtils.isNotEmpty来替代，并把guava包的引用放到filter模块里。这样用户在使用rocketmq客户端的时候就减少了不必要的guava依赖
<img width="858" alt="屏幕快照 2019-06-03 08 57 19" src="https://user-images.githubusercontent.com/27771595/58770014-c7a19480-85de-11e9-93c5-9bcad17f01d1.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/27771595/58770094-675f2280-85df-11e9-8d78-2fa219d244e8.png">

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
**blocker**
4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zongtanghu** [comment]
Firstly,thanks for your suggestion for rocketmq client issue.And then,can you describe your issue in English? @ChaosYjh

**Comment by zongtanghu** [comment]
Your suggestion is correct.We can disscuss here for this issue. @ShannonDing @duhenglucky

**Comment by ChaosYjh** [comment]
Thank you for your reply!


I will describe my issue first.


I think rocketmq should minimize unnecessary client package references to reduce the risk of package conflicts. It is also very helpful for users to select or update RocketMQ.


Actually，there are quite a few application systems using Alibaba-rocketmq version under 3.5.8.For this users, they just only referenced fastjson,netty-all,slf4j-api.And it is difficult to let they to update rocketmq client, but acl and message trace is necessary.For those who is using ant, it will be impossible...


Other than，even if the version used by the user is 4.x, the three-party package referenced by the client is not controlled. It will be difficult to convince users to update the version.


Here is the dependency of rocketmq-client 3.2.6.
、


And here is the dependency of rocketmq-client4.5.1 with all.



eg guava:I think is it unnecessary to only used to judge string is not empty.
eg commons-codec:It can be replaced with javax.xml.bind.DatatypeConverter#pars​eBase64Binary
eg snake​yaml:It was not used in client at all.


Thank you.
From ChaosYjh
------------------ 原始邮件 ------------------
发件人: "Hu Zongtang"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 晚上10:50
收件人: "apache/rocketmq"<rocketmq@noreply.github.com>;
抄送: "苑俊辉"<763900954@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [apache/rocketmq] Suggestion about the third part dependency ofthe RocketMQ client. (#1241)




Your suggestion is correct.We can disscuss here for this issue. @ShannonDing @duhenglucky
