### ISSUE TITLE
why MQPullConsumerScheduleService only use two queue consume the msg default?

### ISSUE THREAD

**Issue by czj940548563** [apache/rocketmq#1243]
when I use MQPullConsumerScheduleService to consume msg from default producer,I saw only  two queue work ,but other two queue msgs were losted ,how can I use default four queue to consume all msgs?

**Comment by duhenglucky** [comment]
@czj940548563 it seems that you didn't properly resolve the result of rebalanceListener when you started more that one consumer. and if you can use the DefaultPullConsumer instead to have more control in this scene.
The issue only used for a bug report or feature request, if you have some questions, please subscribe our [mailing list](https://rocketmq.apache.org/about/contact/) and send your question by email, so I will close this issue, but please feel free to reopen it if you have more questions.
