### ISSUE TITLE
Return FLUSH_SLAVE_TIMEOUT while message is sent successfully

### ISSUE THREAD

**Issue by suiyuzeng** [apache/rocketmq#1244]
Config:
broker:
master broker role:SYNC_MASTER
sendMessageThreadPoolNums=4
topic:
Topic_A: qps:3w,  WaitStoreMsgOK:false
Topic_B: qps:100, WaitStoreMsgOK:true

  Producer of Topic_B get code FLUSH_SLAVE_TIMEOUT when send messages to the two topic at the same time. The time cost do not exceed the timeout. There is no problem about the synchronization between master and slave. The cause is the wakeup of the GroupCommitRequest in org.apache.rocketmq.store.ha.HAService.GroupTransferService#doWaitTransfer.
 for (int i = 0; !transferOK && i < 5; i++) {
     this.notifyTransferObject.waitForRunning(1000);
     transferOK = HAService.this.push2SlaveMaxOffset.get() >= req.getNextOffset();
  }

  As the qps of Topic_A is much higher than Topic_B and the config sendMessageThreadPoolNums is set to 4, the Topic_A will trigger waitForRunning for 5 times before the synchronization of Topic_B is completed.  
  In org.apache.rocketmq.store.CommitLog#handleHA, the GroupCommitRequest is added to ha service and wait unit timeout. In doWaitTransfer, how about check if the request is expire? Add expire timestamp to GroupCommitRequest and check if expire, such as follow:
     while (!transferOK && defaultMessageStore.getSystemClock().now() < req.getExpireTimestamp()) {
		this.notifyTransferObject.waitForRunning(1000);
		transferOK = HAService.this.push2SlaveMaxOffset.get() >= req.getNextOffset();
	}

**Comment by davidpdw** [comment]
消息比较大的情况下haTransferBatchSize设置太小就容易出现这个异常

**Comment by suiyuzeng** [comment]
> 消息比较大的情况下haTransferBatchSize设置太小就容易出现这个异常

嗯，haTransferBatchSize太小会增加slave reportSlaveMaxOffset的频率，也会提前触发doWaitTransfer中的waitForRunning 5次，然后导致返回FLUSH_SLAVE_TIMEOUT

**Comment by duhenglucky** [comment]
@suiyuzeng 检查主从之间的gap是否差距较大，以及适当增加haTransferBatchSize，还有就是提交频率以及page都可以适当调整下。
另外，看起来你已经解决这个问题了，由于issue只用于bug report跟feature request，所以咨询类的问题尽量走邮件列表: https://rocketmq.apache.org/about/contact/, 这样可以沉淀下来，并且被检索到方便其他遇到同样疑问的小伙伴，所以我先暂时关掉这个issue，有问题的话，随时重新打开
