### ISSUE TITLE
rocketmq can not send messages to more than one cluster

### ISSUE THREAD

**Issue by yangfanchuhai** [apache/rocketmq#1247]
When I create two Producer with different name server,but I can only send message to a single cluster,read relative code,find that it will always use one client instance!

**Comment by davidpdw** [comment]
两个生产者使用不同的instanceName就可以了

**Comment by ahuazhu** [comment]
Maybe nameserver should be a part of the _default instanceName_.

**Comment by duhenglucky** [comment]
as @davidpdw said , you can set different instanceName to resolve this issue.
The issue only used for a bug report or feature request, if you have some questions, please subscribe our [mailing list](https://rocketmq.apache.org/about/contact/) and send your question by email, so I will close this issue, but please feel free to reopen it if you have more questions.
