### ISSUE TITLE
unnecessary code in LatencyFaultToleranceImpl at latest version

### ISSUE THREAD

**Issue by sunxin1993** [apache/rocketmq#1248]
`  @Override
    public String pickOneAtLeast() {
        final Enumeration<FaultItem> elements = this.faultItemTable.elements();
        List<FaultItem> tmpList = new LinkedList<FaultItem>();
        while (elements.hasMoreElements()) {
            final FaultItem faultItem = elements.nextElement();
            tmpList.add(faultItem);
        }

        if (!tmpList.isEmpty()) {

            Collections.shuffle(tmpList);

            Collections.sort(tmpList);

            final int half = tmpList.size() / 2;
            if (half <= 0) {
                return tmpList.get(0).getName();
            } else {
                final int i = this.whichItemWorst.getAndIncrement() % half;
                return tmpList.get(i).getName();
            }
        }

        return null;
    }`

i think there is no need to use Collections.shuffle(tmpList) before  Collections.sort(tmpList). i think you can delete it.

**Comment by intSpark** [comment]
+1
I also don't understand why it's a shuffle before calling sort, looks the shuffle is redundant.

**Comment by duhenglucky** [comment]
@intSpark @sunxin1993 IMHO, in java, Collection.sort() used a stable sort algorithm, so shuffle() before sort() will make the selection algorithm fairer. Looking forward to your sounds about these issue.
But the issue only used for a bug report or feature request, if you have some questions, please subscribe our [mailing list](https://rocketmq.apache.org/about/contact/.) and send your question by email.
