### ISSUE TITLE
请问在rocket mq中如何监听死信队列？

### ISSUE THREAD

**Issue by amberamberer** [apache/rocketmq#1255]
consumer消费消息失败达到设定次数后会进入死信队列，现在我们想监听死信队列中的信息，并对其进行处理应该如何做呢？

**Comment by amberamberer** [comment]
How could I monitor the dead letter queue after consumer failed to consume the message?

**Comment by duhenglucky** [comment]
@amberamberer 死信队列作为最后一个保证，目前没有开放导出或者重放功能，如果有兴趣的话，可以一起提个PR来优化此功能，比如说重放该消息. 另外，如果有什么需要帮助的，麻烦在邮件列表（https://rocketmq.apache.org/about/contact/）里面咨询，很多小伙伴会帮助你的。
