### ISSUE TITLE
when the commitLog is overlarge，the broker startup very very very slow，eg. 10 minutes

### ISSUE THREAD

**Issue by iNanos** [apache/rocketmq#1258]
when the commitLog is overlarge，the broker startup very very very slow，eg. 10 minutes 。 

spend 10 minutes on load commitLog

<img width="234" alt="企业微信截图_20190614151549" src="https://user-images.githubusercontent.com/1085564/59490680-e8f46180-8eb7-11e9-9685-d1eccae5ab02.png">

![企业微信截图_20190614151203](https://user-images.githubusercontent.com/1085564/59490750-0d503e00-8eb8-11e9-847e-2eeb5e39eba2.png)

has other ways to solve this problem except reduce the message accumulation？

**Comment by duhenglucky** [comment]
@iNanos what's your version of rocketmq, and this restart rocketmq is master or slave? could you provide more information about this issue?
