### ISSUE TITLE
Question about consuming message in docker.

### ISSUE THREAD

**Issue by fenghaichun** [apache/rocketmq#1261]
部署环境：单机docker
部署方式：2个nameServer、2个Master、2个slave

操作步骤：
1. 创建一个生产者，队列数量采用默认的4个，代码如下：
```
public static void main(String[] args) throws Exception {
        //Instantiate with a producer group name.
        DefaultMQProducer producer = new DefaultMQProducer("group_test");
        // Specify name server addresses.
        producer.setNamesrvAddr("192.168.1.6:9876:192.168.1.6:9877");
        //Launch the instance.
        producer.start();
       int i = 0;
        while (true)
        {
            //Create a message instance, specifying topic, tag and message body.
            Message msg = new Message("TopicTestL" /* Topic */,
                    "TagA" /* Tag */,
                    ("Hello RocketMQ " + i).getBytes(RemotingHelper.DEFAULT_CHARSET) /* Message body */
            );
            //Call send message to deliver message to one of brokers.
            SendResult sendResult = producer.send(msg);
            System.out.printf("%s%n", sendResult);
            Thread.sleep(1000);
        }
        //Shut down once the producer instance is not longer in use.
        //producer.shutdown();
    }
```
2. 创建两个消费者，代码如下：

```
private static void consume(String instanceName) throws MQClientException {
        // Instantiate with specified consumer group name.
        DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("group_test");
        // Specify name server addresses.
        consumer.setNamesrvAddr("192.168.1.6:9876:192.168.1.6:9877");
        consumer.setInstanceName(instanceName);
        // Subscribe one more more topics to consume.
        consumer.subscribe("TopicTestL", "*");
        consumer.setConsumerGroup("group_test");
        // Register callback to execute on arrival of messages fetched from brokers.
        consumer.registerMessageListener(new MessageListenerConcurrently() {
            @Override
            public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                                                            ConsumeConcurrentlyContext context) {
                for (MessageExt m: msgs)
                {
                    System.out.println("consume:" + instanceName + ",QueueId:" + m.getQueueId());
                }
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            }
        });
        //Launch the consumer instance.
        consumer.start();
        System.out.printf("Consumer Started.%n");
    }
```

两个消费者分别从不同的进程或者线程启动，看到打印的消费记录如下：
```

consume:consume1,QueueId:0
consume:consume1,QueueId:1
consume:consume1,QueueId:2
consume:consume1,QueueId:3
consume:consume2,QueueId:0
consume:consume2,QueueId:1
consume:consume2,QueueId:2
consume:consume2,QueueId:3
```

问题：为什么每个消费者会消费到每个队列，或者说为什么一个消息队列会被多个消费者消费。（注意：消息本身是没有被重复消费），我期望的是每个消费者只消费一部分队列，每个消费队列一段时间只被一个消费者消费，是否我操作有误，还是设计如此？求解答，谢谢。

**Comment by fenghaichun** [comment]
刚刚测试了下，如果关掉一个master broker，就是正常的。。。

**Comment by ShannonDing** [comment]
Did you create 4 queues in every broker and a total of 8 queues?  Maybe you should print the broker name and then have a look at the rebalance result.  
IMO, for the case of question, it is better for you to ask the contributors in our community with DingTalk.

**Comment by fenghaichun** [comment]
> Did you create 4 queues in every broker and a total of 8 queues? Maybe you should print the broker name and then have a look at the rebalance result.
> IMO, for the case of question, it is better for you to ask the contributors in our community with DingTalk.

谢谢你的回复。

我debug查看了生产者、消费端负载均衡的情况，发现负载均衡的粒度是queueId + brokerId，而不是queueId，因此，默认的并发消费模式下情况似乎确实是这样。

另外我想请教下：如果要保证一个队列的消息完全顺序，是不是必须要做到这两点：
1. 在发送端指定queueId + brokerId
2. 消费端采用顺序消费

是否有别的方案？

**Comment by ahuazhu** [comment]
@fenghaichun 
Setting the queue number of the topic to 1 ensure that messages are consumed in strict order.

Setting key (e.g. OrderId) to message and using the MessageListenerOrderly ensure that messages are consumption is partially ordered.

**Comment by fenghaichun** [comment]
> @fenghaichun
> Setting the queue number of the topic to 1 ensure that messages are consumed in strict order.
> 
> Setting key (e.g. OrderId) to message and using the MessageListenerOrderly ensure that messages are consumption is partially ordered.

I have tried this way: 
1. Set the number of queues for topic to 1 
2. Message consumer uses MessageListenerOrderly 

PS： my deployment: two master brokers

but i found that there is still a problem, the message is not consumed in order, such as the output below：
queue0,/broker1,Hello RocketMQ 1
queue0,/broker1,Hello RocketMQ 3
queue0,/broker1,Hello RocketMQ 5
queue0,/broker1,Hello RocketMQ 7
queue0,/broker1,Hello RocketMQ 9
queue0,/broker2,Hello RocketMQ 0
queue0,/broker2:10933,Hello RocketMQ 2
queue0,/broker2:10933,Hello RocketMQ 4
queue0,/broker2:10933,Hello RocketMQ 6
queue0,/broker2:10933,Hello RocketMQ 8

as mentioned above, for a queue, in the case of two brokers, if no broker is specified in producer, the consumer client seems to see two queues, which are queue 0 stored on broker1 and queue 0 stored on broker2. then consumers will pull messages from these two queues when they consume, if the broker2 network delay or load is too high, the above output will occur.

it seems that only when the producer specifies a queue, a broker, and the consumer uses messagelistenerorderly to ensure that the messages are consumed sequentially.

please tell me what i understand, right?
