### ISSUE TITLE
Question about ACL.

### ISSUE THREAD

**Issue by dankes** [apache/rocketmq#1265]
rocket mq4.4版本支持ACL，好像不支持对ProducerGroup进行权限限制，不知道有没有解决方案。阿里云上的MQ服务，是支持对ProducerGroup、ComsumerGroup进行权限控制。

**Comment by zongtanghu** [comment]
> rocket mq4.4版本支持ACL，好像不支持对ProducerGroup进行权限限制，不知道有没有解决方案。阿里云上的MQ服务，是支持对ProducerGroup、ComsumerGroup进行权限控制。

Your issue is not correct standard.Please describe your issue in English.

**Comment by ShannonDing** [comment]
See #1268 , maybe it  will help you.
