### ISSUE TITLE
How to connect broker using AK and SK?

### ISSUE THREAD

**Issue by amberamberer** [apache/rocketmq#1268]
How to use accesskey&secretkey in Rocket MQ 4.5.1? Is there any interface or function?

**Comment by ShannonDing** [comment]
1. DefaultMQProducer producer = new DefaultMQProducer("GID-xxx", new AclClientRPCHook(new SessionCredentials(ACL_ACCESS_KEY,ACL_SECRET_KEY)));
2.DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("GID-xxx", new AclClientRPCHook(new SessionCredentials(ACL_ACCESS_KEY,ACL_SECRET_KEY)), new AllocateMessageQueueAveragely());

Hope it may help you.

**Comment by amberamberer** [comment]
> 1. DefaultMQProducer producer = new DefaultMQProducer("GID-xxx", new AclClientRPCHook(new SessionCredentials(ACL_ACCESS_KEY,ACL_SECRET_KEY)));
> 2. DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("GID-xxx", new AclClientRPCHook(new SessionCredentials(ACL_ACCESS_KEY,ACL_SECRET_KEY)), new AllocateMessageQueueAveragely());
> 
> Hope it may help you.
Thx!
