### ISSUE TITLE
CreateORUpdateTopic TopicName validation Safety bug

### ISSUE THREAD

**Issue by Liberxue** [apache/rocketmq#1271]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:
```zsh 
 sh bin/mqadmin updateTopic -n 127.0.0.1:9876  -o false -p 6 -r 16 -w 16 -c RaftCluster  -t 44334≈≈∂ç√ß
```
- What did you do (The steps to reproduce)?

![image](https://user-images.githubusercontent.com/5831248/59608117-40f4c780-9147-11e9-9165-77703197fd15.png)
![image](https://user-images.githubusercontent.com/5831248/59608143-4a7e2f80-9147-11e9-958b-381fbc4ed9d3.png)
- What did you expect to see?
  CreateORUpdateTopic topic length validation and validation Safety
- What did you see instead?

2. Please tell us about your environment:

```zsh
  rocketmq 4.5.1 master last commit 40c255d6b55b03fbff8cd7c1d78af6f5edcab5fa
```

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by Liberxue** [comment]
Discuss topic length and special symbol limits, I will mention pr to deal with this [issue](https://github.com/apache/rocketmq/issues/1271)

**Comment by happyer** [comment]
that is bug ？

**Comment by duhenglucky** [comment]
@Liberxue good catch, you can pull a request to add some limit of the topic name.

**Comment by happyer** [comment]
topic name is too length ?

**Comment by Liberxue** [comment]
have to deal with [Pull requests](https://github.com/apache/rocketmq/pull/1321)

**Comment by duhenglucky** [comment]
this issue has been fixed due to the security report.
