### ISSUE TITLE
example OpenMessaging MQClientException No name server address, please set it.

### ISSUE THREAD

**Issue by Liberxue** [apache/rocketmq#1272]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
![image](https://user-images.githubusercontent.com/5831248/59659027-d50e6f80-91d7-11e9-8edd-21263fe718b0.png)

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zongtanghu** [comment]
@Liberxue Please describe you issue details.

**Comment by Liberxue** [comment]
![image](https://user-images.githubusercontent.com/5831248/59671662-9df88800-91f0-11e9-8529-fc67c98b0462.png)
dLegerConf +on aclEnable 
```
brokerClusterName = RaftCluster
brokerName=RaftNode00
listenPort=30911
namesrvAddr=127.0.0.1:9876
storePathRootDir=/tmp/rmqstore/node00
storePathCommitLog=/tmp/rmqstore/node00/commitlog
enableDLegerCommitLog=true
dLegerGroup=RaftNode00
dLegerPeers=n0-127.0.0.1:40911;n1-127.0.0.1:40912;n2-127.0.0.1:40913
aclEnable=true
## must be unique
dLegerSelfId=n0
brokerIP1=127.0.0.1
sendMessageThreadPoolNums=16
```

**Comment by xiangwangcheng** [comment]
@Liberxue  By setting environment variables like below, namesrv addresses can be registered into DefaultMQProducer. Hope this can help u.

![image](https://user-images.githubusercontent.com/8049014/61607073-a88abf00-ac7f-11e9-9ca0-6a6cf94e08b4.png)

**Comment by Liberxue** [comment]
@xiangwangcheng  ok ☆⌒(*＾-゜)v THX ，I have already done，forgot the close issue

**Comment by wl1092212424** [comment]
The reason is this, look at the source code
`PushConsumerImpl`类的 `if ("true".equalsIgnoreCase(System.getenv("OMS_RMQ_DIRECT_NAME_SRV")))`
```java
public PushConsumerImpl(final KeyValue properties) {
  this.rocketmqPushConsumer = new DefaultMQPushConsumer();
  this.properties = properties;
  this.clientConfig = BeanUtils.populate(properties, ClientConfig.class);
  if ("true".equalsIgnoreCase(System.getenv("OMS_RMQ_DIRECT_NAME_SRV"))) {
    String accessPoints = clientConfig.getAccessPoints();
    if (accessPoints == null || accessPoints.isEmpty()) {
      throw new OMSRuntimeException("-1", "OMS AccessPoints is null or empty.");
    }
    this.rocketmqPushConsumer.setNamesrvAddr(accessPoints.replace(',', ';'));
  }
  String consumerGroup = clientConfig.getConsumerId();
  if (null == consumerGroup || consumerGroup.isEmpty()) {
    throw new OMSRuntimeException("-1", "Consumer Group is necessary for RocketMQ, please set it.");
  }
  this.rocketmqPushConsumer.setConsumerGroup(consumerGroup);
  this.rocketmqPushConsumer.setMaxReconsumeTimes(clientConfig.getRmqMaxRedeliveryTimes());
  this.rocketmqPushConsumer.setConsumeTimeout(clientConfig.getRmqMessageConsumeTimeout());
  this.rocketmqPushConsumer.setConsumeThreadMax(clientConfig.getRmqMaxConsumeThreadNums());
  this.rocketmqPushConsumer.setConsumeThreadMin(clientConfig.getRmqMinConsumeThreadNums());
  String consumerId = OMSUtil.buildInstanceName();
  this.rocketmqPushConsumer.setInstanceName(consumerId);
  properties.put(OMSBuiltinKeys.CONSUMER_ID, consumerId);
  this.rocketmqPushConsumer.setLanguage(LanguageCode.OMS);
  this.rocketmqPushConsumer.registerMessageListener(new MessageListenerImpl());
}
```
