### ISSUE TITLE
Question about HA.

### ISSUE THREAD

**Issue by aaron1989041** [apache/rocketmq#1278]
集群架构（使用双主双从sync_master模式和sync_flush刷盘策略）：
     10.82.12.68：
            broker-a-master
            broker-b-slave
     10.82.12.69：
            broker-b-master
            broker-a-slave
     版本都是4.4.0.
异常情况：
     向broker-a写数据正常，向broker-b写时报错“SLAVE_NOT_AVAILABLE”。但是此时broker-b-maser的offset一直在增长，并没有拒绝写入。

**Comment by happyer** [comment]
会不会 配置的slave 与master 他们之间的差值太大了

**Comment by EastWolf666** [comment]
我的是因为brokerIP2没有设置，你可以试一下

**Comment by ShannonDing** [comment]
你好，issue 只用于bug报告以及新特性提出，大家可以在邮件列表里面讨论问题呀（https://rocketmq.apache.org/about/contact/)  很多小伙伴会及时回复的。
