### ISSUE TITLE
why nameserver not have acl ? 

### ISSUE THREAD

**Issue by forfuns** [apache/rocketmq#1279]
when sometime I need nameserver expose outside network , but without acl feature,that mean anyone can add un safe broker to rocketmq ? 

or just need a token something to checkout broker identity ？

**Comment by happyer** [comment]
you can do same ons  of aliyun

**Comment by forfuns** [comment]
I just want to know that rocketmq nameserver without acl feature is good for security ?

or just I misunderstand it work ？

**Comment by forfuns** [comment]
yd when I create a test network with aliyun ECS,will expose rocketmq service to debug,I should pay attention to mq safety?

**Comment by happyer** [comment]
you should save ak as

**Comment by happyer** [comment]
https://github.com/apache/rocketmq/issues/403
there is about acl

**Comment by zongtanghu** [comment]
> when sometime I need nameserver expose outside network , but without acl feature,that mean anyone can add un safe broker to rocketmq ?
> 
> or just need a token something to checkout broker identity ？

Actually,in rocketmq cloud enviroment or cases,your using namesrv to expose outside network is not a better choice.
