### ISSUE TITLE
Question about shutdown consumer unnormally.

### ISSUE THREAD

**Issue by bean326** [apache/rocketmq#1282]
我们在应用中加了钩子来监控进程停止，并且及时关闭消费者,但有些情况是进入不了钩子方法的，比如直接杀进程或者kill -9之类的，这种情况再重启服务器，启动消费者后就会导致消费不了消息或者要等很久才能消费消息，上次提了一次回复说是有个什么MessageQueue的队列要释放，但是需要时间，这算不算是rocketmq的一个不友好的地方?或者说有没有另外一种方式，就是在启动消费者的时候可以提供一个方法，获取上一次还没有释放的，然后手动释放后再重启新的消费者，这种方式感觉是最友好的，算不算是rocketmq的另外一个小BUG?

**Comment by duhenglucky** [comment]
@bean326 这个是一个非常好的一个涉及，尤其是在顺序消息里面，服务端可以通过设置系统变量rocketmq.broker.rebalance.lockMaxLiveTime这个值来减少锁的时间。另外，issue 只用于bug报告以及新特性提出，希望可以在邮件列表里面讨论问题呀（https://rocketmq.apache.org/about/contact/），很多小伙伴会及时回复的。
