### ISSUE TITLE
If set BROADCASTING and order , will not consumer any message!

### ISSUE THREAD

**Issue by YuShanMuGong** [apache/rocketmq#1286]
when I set `MessageModel.BROADCASTING` and `register MessageListenerOrderly`，then I can not get any message！ because the processQueue can not lock! 

I find the problem on the Internet ! then I know this usage is not right！

Why not check this config when start the consumer ? If set config like this , throw a Exception may be better。Just we said `Fail First`。

**Comment by duhenglucky** [comment]
@YuShanMuGong this PR(https://github.com/apache/rocketmq/pull/561) can resolve your issue, and could you help to review this PR and give us your verification result?
