### ISSUE TITLE
Consume failed with different system time between producer and consumer.

### ISSUE THREAD

**Issue by bean326** [apache/rocketmq#1288]
场景如下:
namesrv和broker部署在172.16.1.158上面
consumer运行在172.16.1.70(以下简称70)上
producer运行在172.16.1.144(以下简称144)上
同时还有一个producer运行在172.16.1.70上
144和158的系统时间是一样的，70的系统时间手动修改过用于测试
现在异常情况就是，70上面的producer发消息给consumer能正常消费,
但是144发出的消息consumer一条都收不到
看过源代码好像是有个什么时间设置，但具体的忘记了，
想问下这个有什么办法解决么还是说可以手动设置什么参数来优化

**Comment by xiangwangcheng** [comment]
@bean326 I'd love to reproduce and explore it, would u please give more info such as how much the time difference is between producer machine and consumer machine? Are there error messages printed when can not be consumed normally?

**Comment by bean326** [comment]
> @ bean326我很想重现和探索它，请你提供更多信息，例如生产者机器和消费者机器之间的时差是多少？无法正常消耗时是否打印错误消息？

应该是时差超过1分钟还是3分钟以上就没法收消息了

**Comment by ganpanlin** [comment]
应该是只要服务器时间大于客户端时间，就会收不到消息

**Comment by bean326** [comment]
这个有什么方法可以优化吗




在 2019-10-19 15:10:16，"ganpanlin" <notifications@github.com> 写道：


应该是只要服务器时间大于客户端时间，就会收不到消息
