### ISSUE TITLE
【Rocketmq-ProducerGroup】How can i createProducerGroup use mqadmin command or other API?

### ISSUE THREAD

**Issue by jenvenson** [apache/rocketmq#1291]
版本：
4.5.1 
描述：
怎么生产者组，有没有接口或mqadmin命令创建，我查阅mqadmin只能创建订阅组，好像不能创建生产者组。阿里云MQ是通过GroupID来管理生产者组和消费者组，开源MQ有没有类似的接口呢？

**Comment by happyer** [comment]
ons 应该在外层做了一个包装,他只是为了一个资源的隔离 但是目前的ons 也么有生产组这样的概念了,可以自行搞一个 acl 的验证如果非常需要的话

**Comment by jenvenson** [comment]
是的，特别是多个产品线使用的话，必须得控制生产组。
我也考虑使用acl，但是目前acl 还没有mqadmin的命令行支持，维护管理很麻烦。
但是我有个疑问，为什么订阅组都有接口命令行支持，为什么生产组不支持呢？ 当然设计者咋考虑的？

**Comment by happyer** [comment]
因为 mq 本身设计的时候,他需要管理consumer,比如consumer 的顺序 consumer负载,语义的保证但是对于producer 本身不关新这些顺序负载 这情况

**Comment by jonnxu** [comment]
producer不涉及到负载均衡等，涉及到的纯粹是一个生产者的标识，broker其实是不太关心的，group管理起来估计也就是统计的需要，所以broker管理起来是不是也不是那么必要？

**Comment by duhenglucky** [comment]
开源版本没有做限制，所以可以自己封装一下，另外，issue 只用于bug报告以及新特性提出，希望可以在邮件列表里面讨论问题呀（https://rocketmq.apache.org/about/contact/），很多小伙伴会及时回复的。
