### ISSUE TITLE
【rocketmq-updateTopic】updateTopic functions

### ISSUE THREAD

**Issue by jenvenson** [apache/rocketmq#1292]
版本：
4.5.1

描述：
`命令：mqadminupdateTopic -n $nameserver -c $cluster -t $topic`
如果topic不存在，以上命令会创建新topic；
如果topic存在，以上命令会更新当前topic。
当topic存在，执行以上命令时，不执行更新或提示已存在？

**Comment by duhenglucky** [comment]
@jenvenson it would be nice if you can describe your question in detail？

**Comment by vongosling** [comment]
@jenvenson looking forward to your detailed description of the problem。
