### ISSUE TITLE
区分读队列和写队列的意义是什么?既然队列区分读写,那topic的246权限起什么作用?

### ISSUE THREAD

**Issue by aaron1989041** [apache/rocketmq#1296]
问题1:在创建topic的时候设置写队列数量为1,读队列数量为2,无报错.查看这个topic后发现,实际只创建了1个队列.而并非二者中的较大值,也并非二者之和.那读队列可以设置成数量大于写队列的意义何在?
问题2:在创建topic时将权限设置成4,根据命令行的帮助信息可以得知4对应的是只读权限.但是topic创建完成后仍然可以正常写入.这是bug么?

**Comment by JerryChin** [comment]
我查遍互联网也没能搞清除什么是读队列什么又是写队列。

**Comment by duhenglucky** [comment]
@aaron1989041 读写队列是逻辑上的概念，队列创建的时候会以写为准，你可以尝试着去设置不同的读写队列，看下producer以及consumer的表现。这个功能尤其是在系统收缩的时候非常有用，比如说现在有8个队列，我把写队列设置为4，那么其中的4个队列就不再写入，只需要在另外4个队列全部消费成功后下掉即可。另外，issue 只用于bug报告以及新特性提出，希望可以在邮件列表里面讨论问题呀（https://rocketmq.apache.org/about/contact/），很多小伙伴会及时回复的。
