### ISSUE TITLE
Can I delete TOOLS_CONSUMER, SELF_TEST_C_GROUP, FILTERSRV_CONSUMER

### ISSUE THREAD

**Issue by LiZhenNet** [apache/rocketmq#1298]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
 Can I delete TOOLS_CONSUMER, SELF_TEST_C_GROUP, FILTERSRV_CONSUMER?

- What did you expect to see?
- What did you see instead?

2. Please tell us about your environment:

   version: V3_2_6

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: %RETRY%SELF_TEST_C_GROUP
See https://github.com/alibaba/RocketMQ/issues/38 for further details.

**Comment by duhenglucky** [comment]
@it would be better if you can upgrade your rocketmq version to 4.x or higher, and we do not recommend to delete system config topic or consumer group. 
And issue only used be bug report and feature request, so, it would be nice if we can discuss these question in our mailing list(https://rocketmq.apache.org/about/contact/), so I will close this issue firstly, but please feel free to reopen it.
