### ISSUE TITLE
castRunnable exception in BrokerControllerScheduledThread

### ISSUE THREAD

**Issue by wangfcdl** [apache/rocketmq#1299]
I got many errors like below in the server log:
ERROR BrokerControllerScheduledThread1 - castRunnable exception, com.alibaba.rocketmq.broker.latency.FutureTaskExt
java.lang.ClassCastException: com.alibaba.rocketmq.broker.processor.PullMessageProcessor$2 cannot be cast to com.alibaba.rocketmq.remoting.netty.RequestTask

But it seems the provider and consumer works as expected. What caused this error?

**Comment by happyer** [comment]
uesd aliyun ons ？

**Comment by wangfcdl** [comment]
no，just the open source version installed on a linux server


 
---Original---

**Comment by happyer** [comment]
what's your version

**Comment by wangfcdl** [comment]
3.5.8


 
---Original---

**Comment by duhenglucky** [comment]
@wangfcdl cloud you upgrade your client version to 4.5.1?

**Comment by wangfcdl** [comment]
ok,let me try




------------------ 原始邮件 ------------------
发件人: "Heng Du"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 下午5:03
收件人: "apache/rocketmq"<rocketmq@noreply.github.com>;
抄送: "1253114017"<1253114017@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [apache/rocketmq] castRunnable exception inBrokerControllerScheduledThread (#1299)




@wangfcdl cloud you upgrade your client version to 4.5.1?
