### ISSUE TITLE
MQFaultStrategy#selectOneMessageQueue Question 

### ISSUE THREAD

**Issue by mushanshitiancai** [apache/rocketmq#1302]
```java
public MessageQueue selectOneMessageQueue(final TopicPublishInfo tpInfo, final String lastBrokerName) {
    if (this.sendLatencyFaultEnable) {
        try {
            int index = tpInfo.getSendWhichQueue().getAndIncrement();
            for (int i = 0; i < tpInfo.getMessageQueueList().size(); i++) {
                int pos = Math.abs(index++) % tpInfo.getMessageQueueList().size();
                if (pos < 0)
                    pos = 0;
                MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
                if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
                    if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
                        return mq;
                }
            }
    ...
```

```java
if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName)) return mq;
```

shoud be:

```java
if (null == lastBrokerName || !mq.getBrokerName().equals(lastBrokerName)) return mq;
```

if Broker is avaliable, then determine if it is the first choice(`null == lastBrokerName`),if is first choose, then return mq, if not , it shoud use new mq but not lastBrokerName(`!mq.getBrokerName().equals(lastBrokerName)`), because lastBrokerName is fail Broker name. so I think the current code is not correct.

Reference code(TopicPublishInfo#selectOneMessageQueue)：
![image](https://user-images.githubusercontent.com/4251771/60395320-4d741980-9b64-11e9-99c2-7f6263adc2b3.png)

**Comment by dut-xiayuan** [comment]
I think this is a fast-fail design. By doing this, it can prevent other requests from being blocked by the failed broker

**Comment by duhenglucky** [comment]
@mushanshitiancai this strategy allows the producer to prioritize the available brokers. and RocketMQ also provide config(sendLatencyFaultEnable) to do more with it. 
And issue only used be bug report and feature request, so, it would be nice if we can discuss these question in our mailing list(https://rocketmq.apache.org/about/contact/), so I will close this issue firstly, but please feel free to reopen it.
