### ISSUE TITLE
rocketmq-4.5.1 dledger sendBatchMessage error 

### ISSUE THREAD

**Issue by wendyxiao** [apache/rocketmq#1304]
1. Please describe the issue you observed:
     When I sendBatchMessage , it throw a exception : the message is illegal, maybe msg body or properties length not matched. msg body length limit 128k, msg properties length limit 32k; 

because the method putMessage throw a exception . 
eg : 
    @Override
    public PutMessageResult putMessages(final MessageExtBatch messageExtBatch) {
        return new PutMessageResult(PutMessageStatus.MESSAGE_ILLEGAL, null);
    }

2. Can I  ask the reason , why the dledger don't implement the method ？ Is there any difficulty or risk ?  I want to try to implement the method.

**Comment by duhenglucky** [comment]
@wangjuneng as you mentioned, the batch message hasn't been supported in RocketMQ on dleger mode. so cloud you pull a request to implement it? we will help you to complete this PR.

**Comment by wendyxiao** [comment]
I commit the code . If you are ok , please help me to check them.thanks~
