### ISSUE TITLE
the word “fearture” on official website is wrong,right one is "feature"

### ISSUE THREAD

**Issue by TaXueWWL** [apache/rocketmq#1305]
**BUG REPORT**

1. Please describe the issue you observed:
I just find some new feature on official website,then I find that the word feature at all pages is wrong.
the correct one is "feature" not "fearture" which means horror.

such as

 [http://rocketmq.apache.org/release_notes/release-notes-4.5.1/](http://rocketmq.apache.org/release_notes/release-notes-4.5.1/)

> NEW FEARTURE

[http://rocketmq.apache.org/release_notes/release-notes-4.4.0/](http://rocketmq.apache.org/release_notes/release-notes-4.4.0/)

> NEW FEARTURE

......

please update to "feature"

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by duhenglucky** [comment]
@TaXueWWL it would be nice if you can pull a request to fix it. :)

**Comment by ShannonDing** [comment]
fixed in https://github.com/apache/rocketmq-site/commit/854fe867901874639c92eb65118a65f46936c6a3
