### ISSUE TITLE
Some incorrect spelling appeared on the method name.

### ISSUE THREAD

**Issue by kinoko1996** [apache/rocketmq#1308]
Hello, I found some spelling errors when I read RocketMq's source code. I think it's necessary to fix it, so I raised this issue and provided a PR to fix it.

Util.computeEclipseTimeMilliseconds must be a error about spelling, according to the meaning of the method name, it must be 'computeElapsedTimeMilliseconds ' or rigght ?

Also  the word 'comput' may be 'compute'.

Thanks.

**Comment by liuruiyiyang** [comment]
I reviewed your PR #1307 and it is OK, but if you could rename the ```computPullFromWhichFilterServer``` in PullAPIWrapper to ```computePullFromWhichFilterServer``` by the way, all the "comput" misspell will be fixed.
Thank you :)
