### ISSUE TITLE
Can we optimize SystemLock just like alibaba/sentinel-core

### ISSUE THREAD

**Issue by lazyfighter** [apache/rocketmq#1310]
```java
public class SystemClock {
    public long now() {
        return System.currentTimeMillis();
    }
}


public final class TimeUtil {

    private static volatile long currentTimeMillis;

    static {
        currentTimeMillis = System.currentTimeMillis();
        Thread daemon = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    currentTimeMillis = System.currentTimeMillis();
                    try {
                        TimeUnit.MILLISECONDS.sleep(1);
                    } catch (Throwable e) {

                    }
                }
            }
        });
        daemon.setDaemon(true);
        daemon.setName("sentinel-time-tick-thread");
        daemon.start();
    }

    public static long currentTimeMillis() {
        return currentTimeMillis;
    }
}

```

**Comment by kinoko1996** [comment]
i found these problem too, haha.
The overhead of creating objects in milliseconds of the current system and requiring two function calls is not worth it. The sentinel scenario does work well with a volatile variable and an asynchronous thread.

**Comment by duhenglucky** [comment]
@lazyfighter Up to now, the above code of RocketMQ has not encountered bottlenecks. Of course, the above sentinel code optimizes the number of system calls, but it also causes the complexity of the code to rise. Of course, RocketMQ may optimize this part of the code in the future. and issue only used be bug report and feature request, so, it would be nice if we can discuss these question in our mailing list(https://rocketmq.apache.org/about/contact/)
