### ISSUE TITLE
rocketmq-dledger model : ExpiredFile are  not deleted byTime 

### ISSUE THREAD

**Issue by wendyxiao** [apache/rocketmq#1324]
**BUG REPORT**

1. Please describe the issue you observed:
   the ScheduleTask of cleanFilesPeriodically failed :  disk space will be full soon, but delete file failed when change to dledger model 

- What did you do (The steps to reproduce)?
    the broker config file eg : 
   storePathRootDir=../store
   storePathCommitLog=../store/commitlog
    dLegerSelfId=n1
    enableDLegerCommitLog=true

- What did you expect to see? What did you see instead?
   the commitlog file will be the path of "../store/commitlog", but actually the commitlog file in the path  of "../store/dledger-n1/data/ . so  the ScheduleTask of cleanFilesPeriodically delete the files fails . 

    the config of storePathCommitLog is not used .

**Comment by wendyxiao** [comment]
@duhenglucky  hi , I add " dledgerConfig.setDataStorePath(defaultMessageStore.getMessageStoreConfig.getStorePathCommitlog()) to  DLedgerCommitlog Constructor Method . 
it can fix the bug . About the  index path , I must change openmessage-Dledger's code.

**Comment by RongtongJin** [comment]
DLedger lack the logic to delete the index file by now. Welcome to submit the relevant PR to [OpenMessaging DLedger](https://github.com/openmessaging/openmessaging-storage-dledger/pulls).
