### ISSUE TITLE
RocketMQ Document Typesetting Errors Issue

### ISSUE THREAD

**Issue by zongtanghu** [apache/rocketmq#1325]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
I will fix RocketMQ Document Typesetting Errors Issue.

- What did you expect to see?
I will fix RocketMQ Document Typesetting Errors Issue.

- What did you see instead?
I have found there are some RocketMQ Document Typesetting Errors Issues.

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by vongosling** [comment]
@zongtanghu Could you help to polish the distribution package rocketmq-all to a more user-friendly name in the 4.5.2 version?
