### ISSUE TITLE
Support Consistent Hash with bounds allocate strategy

### ISSUE THREAD

**Issue by Jaskey** [apache/rocketmq#1333]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

As we know, when numbers of consume instances are changed, a 

2. Provide any additional detail on your proposed use case for this feature.

As we know, the default AllocateMessageQueueStrategy is averaging strategy which allocate queue to consumer as evenly as possible. But whenever queues numbers or consumer numbers changed, say a new consumer starts or an old consumer shutdowns, a rehashing will be triggered then almost all consumer suffered from this that they will rebalance to drop old queues and get new queues.

And that will cause

message latency from producer to consumer increases at the moment when consumer/queue numbers change, even when they scale up.

messages will be duplicated significantly since the offset may not be persisted to broker and that queue is assigned to another consumer to pull messages from.

This is especially significant when they have tens of consumer instances and scale-up or deployment is often. https://github.com/apache/rocketmq/pull/67 has provide a Consistent Hash strategy, which is a a good choice for these users. 

But ConsistentHash is not able to guarantee that the consumer can get an average queue numbers, Maybe we can implement a strategy of Consistent Hash with bounds that can reduce duplication as much as possible as well as ensuring the consumer have the same queues

**Comment by liuruiyiyang** [comment]
IMHO, making the number of the queue even is not necessarily effective to the balance or to reduce the duplication because different queues may have different workloads. We need to discuss it thoroughly.
Anyway, it is always welcome to propose a RIP and PR if you have any ideas.
