### ISSUE TITLE
Does RocketMQ console supports DLQ?

### ISSUE THREAD

**Issue by eacdy** [apache/rocketmq#1334]
我看到 `https://github.com/apache/rocketmq/blob/master/docs/cn/features.md` 有写：

> 在RocketMQ中，可以通过使用console控制台对死信队列中的消息进行重发来使得消费者实例再次进行消费。

但是在RocketMQ console中，没有找到如何操作。即使把DLQ的perm设成6，依然没有地方设置重发啊……
请问：
1. console是否支持对死信队列的消息进行重发？如果支持，如何操作？
2. 如果不支持，我应该如何实现重发？

**Comment by eacdy** [comment]
@zhouxinyu @dongeforever @vongosling

**Comment by lazyfighter** [comment]
maybe you can start a new consumer subscribe %DLQ%+consumerGroup

**Comment by eacdy** [comment]
OK. Thanks a lot.
