### ISSUE TITLE
Strange consumer not work in spring +rocketmq xml configuration, only work like java APP client

### ISSUE THREAD

**Issue by tyshan** [apache/rocketmq#1340]
I import rocketmq in a spring project with latest 4.5.1 version.
But when I run a test consumer but it can't read message , which is generated by producer.
Codes looks like
Spring configure
```
<bean id="rocketmqConsumer" class="org.apache.rocketmq.client.consumer.DefaultMQPushConsumer" init-method="start" destroy-method="shutdown">
    	<property name="consumerGroup" value="concurrent_consumer"/>
    	<property name="namesrvAddr" value="localhost:9876"/>
    	<property name="messageListener" ref="consumerTestImpl"/>
    	<property name="subscription">
        	<map>
            	<entry key="TopicTest" value="*"/>
        	</map>
    	</property>
	</bean>
```
consumerTestImpl links to 

public class ConsumerTestImpl implements MessageListenerConcurrently {
    public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs, ConsumeConcurrentlyContext context) {
        System.out.println(Thread.currentThread().getName() + " Receive New Messages: " + msgs);
        //返回消费状态
        //CONSUME_SUCCESS 消费成功
        //RECONSUME_LATER 消费失败，需要稍后重新消费
        MessageExt msg=msgs.get(0);
        System.out.println("msg content "+new String(msg.getBody()));
        return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
    }
}
When I run spring web app, NO consume message outputs, which is generated by a java producer app client;

Producer 
public static void main(String[] args) throws Exception{
		DefaultMQProducer producer = new DefaultMQProducer("finance");
		// Specify name server addresses.
		producer.setNamesrvAddr("localhost:9876");

//		producer.setVipChannelEnabled(false);
		// Launch the instance.
		producer.start();
		for (int i = 0; i < 2; i++) {
			// Create a message instance, specifying topic, tag and message body.
			Message msg = new Message("TopicTest" /* Topic */, "TagA" /* Tag */, ("Hello RocketMQ " + i).getBytes("UTF-8") /* Message body */
			);
			// Call send message to deliver message to one of brokers.
			SendResult sendResult = producer.send(msg);
			System.out.printf("%s%n", sendResult);
		}
		// Shut down once the producer instance is not longer in use.
		producer.shutdown();
	}

But a java app will work
public static void main(String[] args) throws Exception{
		DefaultMQPushConsumer consumer= new DefaultMQPushConsumer("BatchConsumer");
	        consumer.setNamesrvAddr("localhost:9876");
	        consumer.subscribe("TopicTest", "*");
	        consumer.registerMessageListener(new MessageListenerConcurrently() {

	            public ConsumeConcurrentlyStatus consumeMessage(final List<MessageExt> msgs,
	                    final ConsumeConcurrentlyContext context) {
	                for(int i=0; i<msgs.size(); i++) {
	                    MessageExt msg = msgs.get(i);
	                    String str = new String(msg.getBody());
	                    System.out.println("===" + str);
	                }
	                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
	            }
	        });
	        consumer.start();

	        System.out.printf("Consumer Started.%n");

	}

I can get consume messages from console
Consumer Started.
===Hello RocketMQ 0
===Hello RocketMQ 1

**Comment by duhenglucky** [comment]
if you want to integrate rocketmq with spring, there's official support in https://github.com/apache/rocketmq-spring.

**Comment by vongosling** [comment]
@tyshan you could find the consumer thread is always running. We strongly recommend you use the rocketmq-spring project which maintained by communities.

**Comment by tyshan** [comment]
> if you want to integrate rocketmq with spring, there's official support in https://github.com/apache/rocketmq-spring.

No, I don't use rocketmq-spring, because it seems use spring boot, my project is an old spring project, which used spring xml configuration.
It still doesn't work when rocket consume TopicTest in spring container, which is send by a producer. But if I use 2 java application a consumer +a producer without spring,   it worked.

Strange?
