### ISSUE TITLE
Cannot open file /dev/shm/rmq_srv_gc.log due to No such file or directory on MacOS

### ISSUE THREAD

**Issue by liuruiyiyang** [apache/rocketmq#1344]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
Start the name service or broker on my MacOS
```> sh bin/mqnamesrv```
```> sh bin/mqbroker -n localhost:9876```

- What did you expect to see?
The output has no warning of 
```Cannot open file /dev/shm/rmq_srv_gc.log due to No such file or directory```

- What did you see instead?
Output warning: ```Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file /dev/shm/rmq_srv_gc.log due to No such file or directory```

2. Please tell us about your environment:
OS: 
```
Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

JAVA: 
```java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
PR#1035 has mentioned this problem
Related history issues: 
https://issues.apache.org/jira/browse/ROCKETMQ-31
https://issues.apache.org/jira/browse/ROCKETMQ-36

**Comment by duhenglucky** [comment]
@liuruiyiyang thanks for your contribution, closed for this issue has been resolved.
