### ISSUE TITLE
why nameserver cannot have funcation of switch role of broker?

### ISSUE THREAD

**Issue by eagle2016** [apache/rocketmq#1348]
why nameserver cannot have funcation of switch role of broker?  
If I do not use deleger solution.  If deleger, the throughput of rocketmq will go down.

now if nameserver have its storage(for example  H2  or  sqlite) , can nameserver knows all roles of broker,  if master boker is down, and nameserver can switch other slave broker to master.
and I think this solution will  deliver performance than deleger solution..

**Comment by duhenglucky** [comment]
@eagle2016 good question, up to now, the name server is an AP solution for service discovery, it brings a lot of conveniences, but it will also cause consistency problems（Of course, this doesn't seem to be a problem in this scenario）, so we can't use this to solve the switching problem temporarily.
But as you described deleger mode will bring a large performance loss, do you have relevant data to prove this problem? we can optimize this problem together, dledger is a very good high availability and consistent solution in messaging middleware.

**Comment by eagle2016** [comment]
ok， I understand it,I have know the commercial rockemq ， and It use zookeeper switch the role of broker. now why nameserver cannot actor as this role?

**Comment by eagle2016** [comment]
now， I design  three nameservers， and brokers can register themselves to it, and it can switch the role of borkers smoothy.
