### ISSUE TITLE
Each ConsumeMessageThread should have different thread name

### ISSUE THREAD

**Issue by ahuazhu** [apache/rocketmq#1355]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
   I am looking for a feature of `ConsumeMessageThread` for different `Consumer` has different ThreadName.

2. Provide any additional detail on your proposed use case for this feature.
For example, when two PushConsumer started in the same process, the client will create two ThreadPool for message consumption.  But Threads in the two pools share the same thread names, thus cause confusion and increase the complexity of resolving problems.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
Nice to have. Not any workarounds.

**Comment by ahuazhu** [comment]
What about if modifying the code in `ConsumeMessageConcurrentlyService.java` 
from
```
            this.consumeExecutor = new ThreadPoolExecutor(
            this.defaultMQPushConsumer.getConsumeThreadMin(),
            this.defaultMQPushConsumer.getConsumeThreadMax(),
            1000 * 60,
            TimeUnit.MILLISECONDS,
            this.consumeRequestQueue,
            new ThreadFactoryImpl("ConsumeMessageThread_"));

        this.scheduledExecutorService = Executors.newSingleThreadScheduledExecutor(new ThreadFactoryImpl("ConsumeMessageScheduledThread_"));
        this.cleanExpireMsgExecutors = Executors.newSingleThreadScheduledExecutor(new ThreadFactoryImpl("CleanExpireMsgScheduledThread_"));
```

to

```
            this.consumeExecutor = new ThreadPoolExecutor(
            this.defaultMQPushConsumer.getConsumeThreadMin(),
            this.defaultMQPushConsumer.getConsumeThreadMax(),
            1000 * 60,
            TimeUnit.MILLISECONDS,
            this.consumeRequestQueue,
            new ThreadFactoryImpl("ConsumeMessageThread_" + this.consumerGroup + "_"));

        this.scheduledExecutorService = Executors.newSingleThreadScheduledExecutor(new ThreadFactoryImpl("ConsumeMessageScheduledThread_" + this.consumerGroup + "_"));
        this.cleanExpireMsgExecutors = Executors.newSingleThreadScheduledExecutor(new ThreadFactoryImpl("CleanExpireMsgScheduledThread_" + this.consumerGroup + "_"));
```

**Comment by duhenglucky** [comment]
@ahuazhu it seems that if you created more than one consumer in a process,  you will be confused by so many similar scenes, so how about subscribe multiple topics in a consumer instead of creating multi consumers in one process? or maybe we should think about a relative unite resolve plan to resolve this issue(instance name or group?). looking forward to your voice.

**Comment by ahuazhu** [comment]
@duhenglucky Thanks for your reply.
In some scenarios, it's necessary to create multi consumers. For example, suppose we have messages in two topics. One contains fewer messages, but each one takes a long consumption time, and the other is the opposite. In such a situation,  subscribing these topics in one consumer maybe not a good choice. Because the few but heavy messages may block all ConsumeThreads, which leads to the another topic consumption latency. Here we need two isolated thread pools (consumer) for these two topics.
For your second question, I think `ConsumerGroup` as a part of` ConsumeThread` name is more intuitive than  `instance`.

**Comment by biuabiu** [comment]
@ahuazhu  hi , I also expect consumer thread names to support extensions

**Comment by zxy1994** [comment]
I also encountered this problem, and I agreed to your opinion. The stitching consumer group in the thread name is a good solution

**Comment by lizhanhui** [comment]
To facilitate diagnosis, it makes sense to prefix all thread-pool naming patterns with instance-name of the client

**Comment by lizhanhui** [comment]
> I think ConsumerGroup as a part of ConsumeThread name is more intuitive than instance

ConsumerGroup looks good in general. But what if you have multiple instances of the same ConsumerGroup?

**Comment by zxy1994** [comment]
> > I think ConsumerGroup as a part of ConsumeThread name is more intuitive than instance
> 
> ConsumerGroup looks good in general. But what if you have multiple instances of the same ConsumerGroup?

一般分析线程栈时，只需要拿一个实例的线程栈啊。您这边的多实例是指消费者部署多节点吗？

**Comment by lizhanhui** [comment]
@zxy1994 Yes... I am wondering if the prefix ConsumerGroup is general enough to meet all potential use cases. Some users may have multiple consumer objects of the same group within the same process. Then they would not able to differentiate them again.
