### ISSUE TITLE
About any message lost....Please help me... 

### ISSUE THREAD

**Issue by tyhqiushen** [apache/rocketmq#1356]
我使用的是RocketMQ4.4，双主双从集群，两个消费者实例。消费过程中，发现有几条消息完全不见了，而且集中在某一个时间点。如果消费失败，我一定会有日志，但是没有。MQ控制台可以看到这条消息。我非常怀疑BROKER未将这几条消息推送给我。是否有这种情况？

I am using RocketMQ 4.4, a dual master dual slave cluster, and two consumer instances. During the consumption process, several messages were found to be completely gone, and they were concentrated at a certain point in time. If the consumption fails, I will have a log, but no. The MQ console can see this message. I very much doubt that BROKER did not push these messages to me. Is this the case?

**Comment by duhenglucky** [comment]
@tyhqiushen 能不能提供多一点的日志以供分析，或者这几条消息是不是有什么比较特别的地方，理论上rocketmq是不存在丢失消息的可能的。

**Comment by vongosling** [comment]
@tyhqiushen ping

**Comment by DanielPei** [comment]
@tyhqiushen 你好，是否有找到问题的原因？ 遇到了相同的问题
