### ISSUE TITLE
关于remoting模块NettyRemotingAbstract的一个问题

### ISSUE THREAD

**Issue by baihezhuo** [apache/rocketmq#1357]
请教一下关于org.apache.rocketmq.remoting.netty.NettyRemotingAbstract#processRequestCommand方法的Oneway响应的一个问题，在pair对象为空时为什么会执行后创建RemotingCommand response对象写回呢？我理解Oneway就是单向通信，发送方没有返回值接收或者判断。是不是应该加上条件判断，如果是Oneway方式则不写回客户端。代码如下：
```
       if (pair != null) {
                      // ...
        } else {
        	
        	// issue: isOnewayRPC send error message ?
            String error = " request type " + cmd.getCode() + " not supported";
            final RemotingCommand response =
                RemotingCommand.createResponseCommand(RemotingSysResponseCode.REQUEST_CODE_NOT_SUPPORTED, error);
            response.setOpaque(opaque);
            ctx.writeAndFlush(response);
            log.error(RemotingHelper.parseChannelRemoteAddr(ctx.channel()) + error);
        }
```

**Comment by duhenglucky** [comment]
@baihezhuo oneway 表示不等待服务端的业务处理响应，并不意味着不去检查相关业务逻辑是否正确。 
由于issue只用于bug report跟feature request，所以咨询类的问题尽量走邮件列表: https://rocketmq.apache.org/about/contact/, 这样可以沉淀下来，并且被检索到方便其他遇到同样疑问的小伙伴，所以我先暂时关掉这个issue，有问题的话，随时重新打开。
