### ISSUE TITLE
NettyRemotingAbstract#invokeSyncImpl countdown.await block

### ISSUE THREAD

**Issue by liucyu** [apache/rocketmq#1360]
In the `NettyRemotingAbstract` class the method `invokeSyncImpl`'s code `RemotingCommand responseCommand = responseFuture.waitResponse(timeoutMillis);` Will cause a bug that the thread pool cannot invoke countdown due to some reason, it will block a long time. 
And the bug can solve just  add a `releaseResponse` method in `responseFuture`  because you can invoke it during scheduled task invoke `ResponseFuture.isTimeout` method

**Comment by duhenglucky** [comment]
@liucyu Thanks for your report, and could you describe this issue in detail or pull a request to describe it directly？

**Comment by liucyu** [comment]
the core question is that `countDownLatch.await(timeout)` will block more than timeout that you set,but this phenomenon only appears when system  is under heavy load. And the solution to this problem is to manually execute `countDownLatch.countDown()`.

**Comment by carlo-z** [comment]
If the msg is send success, it return. the countDownLatch is not be countDown.  it will block until timeout.  is it bug? @duhenglucky 
![](https://imagehome.oss-cn-beijing.aliyuncs.com/20200112192530.png)
