### ISSUE TITLE
In the case of disk tension, there will be problems that  consumers can not consume data

### ISSUE THREAD

**Issue by jiangxinlingdu** [apache/rocketmq#1367]
![2019080637053](https://user-images.githubusercontent.com/6373972/62538650-e6920080-b885-11e9-8759-42f2329665db.png)
如果磁盘紧张，那么把最小的文件删除了，就会出现集群生产者发消息正常,消费者消费不到数据的问题。
![2019080612141](https://user-images.githubusercontent.com/6373972/62538707-088b8300-b886-11e9-8e53-9d7174640e5b.png)

详细内容可以查看：[详情](http://www.jiangxinlingdu.com/rocketmq/2019/08/06/noconsumer.html)

**Comment by jiangxinlingdu** [comment]
![image](https://user-images.githubusercontent.com/6373972/62605671-2d870100-b92d-11e9-9343-117136419929.png)
今天又出现这种问题了，
![image](https://user-images.githubusercontent.com/6373972/62605717-42fc2b00-b92d-11e9-814a-fa0f75cc4531.png)
麻烦确认处理下，谢谢！！！

**Comment by duhenglucky** [comment]
@jiangxinlingdu as discussed offline, we will continue to pay attention to this issue, welcome to provide more information about it.

**Comment by jiangxinlingdu** [comment]
@duhenglucky If you need any information，you can ask for me！
