### ISSUE TITLE
pushConsumer的方式，某些队列数据不拉取

### ISSUE THREAD

**Issue by wuangKKK** [apache/rocketmq#1370]
![image](https://user-images.githubusercontent.com/25049492/62607156-2f9e8f00-b930-11e9-8462-de1ffabef11e.png)

就会 出现这种情况，一些队列的 数据 消费 的很快，另外一些 队列完全不消费 ，我 查看 了服务端 的 消费日志 并不是消费慢造成的 。   我在k8s上扩容 设置缩减消费实例 都会瞬间拉取 消息 消费，慢慢的就又变成这样了。

**Comment by duhenglucky** [comment]
@wuangKKK 有一种可能就是你没有设置instanceName，但是在容器中很有可能你的ip是重复的，导致consumer rebalance出现问题，先从这个角度去查一下吧, 可以参考这个[issue](https://github.com/apache/rocketmq/issues/667)。
