### ISSUE TITLE
tempBuffer的pid的值会不会被地址值覆盖掉？

### ISSUE THREAD

**Issue by yuanx1** [apache/rocketmq#1371]
![image](https://user-images.githubusercontent.com/3263162/62642643-c2631c00-b978-11e9-8031-709b462ea22d.png)
ip地址的长度明显长于2，占4位～！

**Comment by duhenglucky** [comment]
@yuanx1 不会，pid用两个字节就够了，issue用于bug报告，以及新特性讨论，如果有问题的话尽量现在邮件列表（https://rocketmq.apache.org/about/contact/）讨论，这样的话是可以被检索到的，也方便沉淀下来。我先暂时关了这个issue，如果有问题的话，随时reopen。
