### ISSUE TITLE
wipeWritePerm not take effect

### ISSUE THREAD

**Issue by kofkyobsa** [apache/rocketmq#1377]
1. Please describe the issue you observed:
wipeWritePerm not take effect

- What did you do (The steps to reproduce)?
I used wipeWritePerm command like this :
sh /alidata/server/rocketmq-all-4.2.0-bin-release/bin/mqadmin wipewriteperm  -b broker-a -n "172.16.18.141:9876;172.16.18.142:9876"
show this:"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
wipe write perm of broker[broker-a] in name server[172.16.18.142:9876] OK, 1121
wipe write perm of broker[broker-a] in name server[172.16.18.141:9876] OK, 1121"
- What did you expect to see?
broker-a's write tps become to 0, no write request to broker-a
- What did you see instead?
broker-a still receive write request;
console shows :
broker-a | 0(master) | 172.16.18.139:10911 | V4_2_0_SNAPSHOT | 25.79 | 0.00 | 1769550 | 515897 | 578320 | 8368 | 状态 配置
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
broker-a | 1(slave) | 172.16.18.142:10911 | V4_2_0_SNAPSHOT | 25.79 | 0.00 | 1769550 | 0 | 578320 | 0

2. Please tell us about your environment:
   i used version 4.2.0 ; aliyun ecs;

**Comment by duhenglucky** [comment]
@kofkyobsa Is there any other error when executing the above command?

**Comment by zongtanghu** [comment]
You can look at this pr(https://github.com/apache/rocketmq/pull/1430).This pr will resolve your issue.

**Comment by duhenglucky** [comment]
fix in this [PR](https://github.com/apache/rocketmq/pull/1430)
