### ISSUE TITLE
ACL exist a bug

### ISSUE THREAD

**Issue by lance12138** [apache/rocketmq#1379]
plain_acl.yml 配置文件中如果accessKey命名为admin相关的，且admin参数为true，broker无法启动，且报错：
java.lang.ClassCastException: java.lang.Class cannot be cast to org.apache.rocketmq.acl.AccessValidator
        at org.apache.rocketmq.broker.BrokerController.initialAcl(BrokerController.java:503)
        at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:470)
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:218)
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)

报错的配置如下：
`globalWhiteRemoteAddresses:

accounts:
- accessKey: rocketmq1
  secretKey: 12345667778
  whiteRemoteAddress:
  admin: false
  defaultTopicPerm: DENY
  defaultGroupPerm: SUB
  topicPerms:
  - topicB=PUB|SUB
  - topicC=SUB
  groupPerms:
  - groupA=DENY
  - groupB=PUB|SUB
  - groupC=SUB

- accessKey: admin
  secretKey: 12345678
  whiteRemoteAddress: 192.168.1.*
  admin: true
`

亲测有问题，只要accessKey改掉就可以成功启动

**Comment by duhenglucky** [comment]
@lance12138 感谢反馈，你能帮忙提个pr改下这个问题吗？

**Comment by ph3636** [comment]
The accessKey=%s and secretKey=%s cannot be null and length should longer than 6

**Comment by ph3636** [comment]
@lance12138 @duhenglucky

**Comment by zongtanghu** [comment]
You can change your acl's accessKey to more than 6 length. @lance12138

**Comment by zongtanghu** [comment]
And also I will report the useful information for acl config length limite issue.

**Comment by lance12138** [comment]
> And also I will report the useful information for acl config length limite issue.

"java.lang.ClassCastException: java.lang.Class cannot be cast" this info is inaccurate. suggestion to correct this info
