### ISSUE TITLE
Slave crash break HA of transaction message

### ISSUE THREAD

**Issue by areyouok** [apache/rocketmq#1390]
Setup a cluster with 4 brokers: (master1/slave1), (master2/slave2)

Kill master1, RocketMQ producer client will send all message to master2 after a while. The cluster is still available.

Kill slave1, RocketMQ producer client still send 50% message to master1 and get sendStatus=SLAVE_NOT_AVAILABLE, the message is not committed. So there are 50% messages will fail and the cluster never recover. To solve this problem we need 2 slaves for each master.

Is there any setting to change this behavior?

**Comment by RongtongJin** [comment]
When slave not available is returned, the message has been committed.
