### ISSUE TITLE
subscription group [_MONITOR_CONSUMER] does not exist

### ISSUE THREAD

**Issue by gaoyf** [apache/rocketmq#1398]
1. Please describe the issue you observed:
Rocketmq client log has many error log, like below:
`14:22:04.005 [NettyClientPublicExecutor_1] WARN RocketmqClient-130 execute the pull request exception
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 26 DESC: subscription group [_MONITOR_CONSUMER] does not exist,
See http://rocketmq.apache.org/docs/faq/ for further details.`

2. Please tell us about your environment:
Broker's boot config has item: `autoCreateSubscriptionGroup=false`.

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
Fix it: create `_MONITOR_CONSUMER` when [SubscriptionGroupManager](https://github.com/apache/rocketmq/blob/master/broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java)'s init method invoked.

**Comment by duhenglucky** [comment]
@gaoyf Please check if your subscription information is consistent.

**Comment by gaoyf** [comment]
Yes, I should have created the subscription `_MONITOR_CONSUMER` manually when I setted `autoCreateSubscriptionGroup` to false.
But I think it's better to create `MixAll.MONITOR_CONSUMER_GROUP` at the starting of broker, because it's supposed to be a system  subscriptionGroup.
