### ISSUE TITLE
create helm chart for rocketmq

### ISSUE THREAD

**Issue by wonderflow** [apache/rocketmq#1406]
It would be nice if we had a [helm chart](https://github.com/helm/charts) for installing rocketmq. Users will be more convenient to install and try rocketmq.

**Comment by grumpyAmber** [comment]
cool. Kafka already has a [helm chart](https://hub.helm.sh/charts/incubator/kafka)

**Comment by duhenglucky** [comment]
@wonderflow @grumpyAmber Good suggestion, and rocketmq community is also improving related  
project with k8s, include operator, helm etc. So it would be nice if you can also involved in those projects, welcome to contact me and participate in it.

**Comment by wonderflow** [comment]
I find in README.md that docker image is supported, can you share Dockerfile so that it could be easy to community members help to create a chart

**Comment by liuruiyiyang** [comment]
@wonderflow You may check out this repo https://github.com/apache/rocketmq-docker :)

**Comment by vongosling** [comment]
Any update for this issue? RocketMQ operator and docker image are ready for a long time. Does it meet your guy's needs?

**Comment by wonderflow** [comment]
Where's the operator?

**Comment by liuruiyiyang** [comment]
> Where's the operator?

@wonderflow The github repository address of RocketMQ Operator is https://github.com/apache/rocketmq-operator

**Comment by innerpeacez** [comment]
I've done the rocketmq helm chart writing, but I'm now wondering which repo I should commit to? @wonderflow

**Comment by ShannonDing** [comment]
> 
Operator：https://github.com/apache/rocketmq-operator
DockerImage：https://github.com/apache/rocketmq-docker

**Comment by innerpeacez** [comment]
Is it possible to have a rocketmq-helm repository @ShannonDing @wonderflow

**Comment by iutx** [comment]
Agreed, it would be more convenient to use Helm, even for Chart with only the rocketmq-operator.

**Comment by caigy** [comment]
@innerpeacez Sounds great. Maybe a new rocketmq-helm repository should be created. IMO you may launch a dicuss by send email to `dev@rocketmq.apache.org` and `users@rocketmq.apache.org` and show your design.

**Comment by innerpeacez** [comment]
> @innerpeacez Sounds great. Maybe a new rocketmq-helm repository should be created. IMO you may launch a discuss by sending email to `dev@rocketmq.apache.org` and `users@rocketmq.apache.org` and show your design.

email has been sent.

> Recently, I tried to deploy rocketmq in the k8s cluster, but I didn't find the helm-related deployment solution, so I implemented it myself and wanted to push it to the rocketmq official. but I only found rocketmq-docker and rocketmq-operator two repository, I I think it is more appropriate to put helm in two repository : 1, main repository, 2 independent helm repository. I found that the main repository does not currently hold other content, so I propose to create a rocketmq-helm repository.
> 
> Currently implemented:
> - sts master broker
> - sts slave broker
> - deployment namesrv
> - deployment dashboard
> 
> I'll work on it until it's created.
> 

@caigy thx for ur reply. I don't know all the configuration about rocketmq, so I may need official help to review the configuration related content.

**Comment by iutx** [comment]
> Currently implemented:
> 
> * sts master broker
> * sts slave broker
> * deployment namesrv
> * deployment dashboard

Some ideas, maybe can impl with operator and custom resources.

structure e.g.
- _helpers
- operator-deployment
- operator rbac
- configmap Broker
- resource Kind NameService
- resource Kind Broker
- resource Kind Console

**Comment by innerpeacez** [comment]
>  Some ideas, maybe can impl with operator and custom resources.

@iutx Why do pure charts need rocketmq crd?

**Comment by iutx** [comment]
> > Some ideas, maybe can impl with operator and custom resources.
> 
> @iutx Why do pure charts need rocketmq crd?

Use rocketmq-operator will make Deploy and O&M rocketmq component more easily.  Component structure、storage、hpa... have been abstracted in rocketmq CRD.

Charts just contains operator、cr、and some extra configuration enough.

**Comment by chuxiangfeng** [comment]
Is there a concrete implementation now? Also looking for rocketmq's helm chart.

**Comment by innerpeacez** [comment]
It seems that the community is not very interested in this matter. I just implemented it simply, and if you need it, I can make it public in my own repository. @chuxiangfeng

**Comment by ShadowySpirits** [comment]
There is already a helm chart for rocketmq 5.x in [rocketmq-docker](https://github.com/apache/rocketmq-docker/tree/master/rocketmq-k8s-helm) repo.

**Comment by innerpeacez** [comment]
Sorry, I seem to have missed something.
