### ISSUE TITLE
Some QA about dledger config when put into kubernetes cluster

### ISSUE THREAD

**Issue by hepyu** [apache/rocketmq#1407]
![image](https://user-images.githubusercontent.com/3917749/63485033-749bf700-c4d4-11e9-9ec8-7a7473a7fe41.png)

Right now, I am woking for put rocketmq4.5.2 into k8s cluster.Then I have some question like above image:

Q1.What rule about the:

dLegerPeers=n0-127.0.0.1:40911;n1-127.0.0.1:40912;n2-127.0.0.1:40913

how about I write like this using domain rather than using ip：

```
dLegerPeers=n0-rocketmq-c3-namesrv-prod-server-0.rocketmq-c3-namesrv-prod-server.coohua.svc.cluster.local:40911;rocketmq-c3-namesrv-prod-server-1.rocketmq-c3-namesrv-prod-server.coohua.svc.cluster.local-127.0.0.1:40912;n2-rocketmq-c3-namesrv-prod-server-2.rocketmq-c3-namesrv-prod-server.coohua.svc.cluster.local:40913
```

because when pod restart, ip will must be changed. I can't use ip, or these just a flag, not real using as ip?

Q2.about port

dLegerPeers=n0-127.0.0.1:40911;n1-127.0.0.1:40912;n2-127.0.0.1:40913

I can't find where config using the port 40911, 40912, 40913, are these port could be specified any port?

**Comment by duhenglucky** [comment]
@hepyu rocketmq community is also improving the related
project with k8s, include operator, helm, etc. So it would be nice if you can also be involved in those projects, welcome to contact me and participate in it.

**Comment by hepyu** [comment]
@duhenglucky 
yeah, I had read the project rocketmq-docker, and follow the step by step, but the yaml config about broker-dledger mode is not  fitable in k8s if i want to use it on the product.

by the way, where is helm install, is it for product? I had found in the offical helm/charts and rocketmq related project in the github, not found it.

so I decide to complete the product/online config yaml by myself, using the rocketmq-broker-dledger mode.

then I want to know the answer for the above QAs, it will help me save time and avoid mistakes.

**Comment by hepyu** [comment]
@duhenglucky 

btw, how can I connect you? dingding? or wechat, or something else?

**Comment by duhenglucky** [comment]
@hepyu you can send your Wechat or DingTalk to this email: duhengforever@apache.org.
