### ISSUE TITLE
rocketmq tools queryMsgByKey may have bug！

### ISSUE THREAD

**Issue by honglouleiyan** [apache/rocketmq#1409]
when I close acl(aclEnable=false), execute the command:sh mqadmin queryMsgByKey -n 127.0.0.1:9876 -t topicH -k 12345678 ,I am able to get the correct result！
but I open the acl(aclEnable=true),execute the command:sh mqadmin queryMsgByKey -n 127.0.0.1:9876 -t topicH -k 12345678,the error:(Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 208  DESC: query message by key finished, but no message.)

The same situation，when use the DefaultMQProducer queryMessage,the java code eg：
producer.queryMessage("topicH","12345678",60,System.currentTimeMillis()-1000*60*10,System.currentTimeMillis())
close acl  ，the result is ok!
but open acl,the error:（CODE: 208  DESC: query message by key finished, but no message.）
I don't know if I am using the error or the program has a bug.

thanks!

**Comment by duhenglucky** [comment]
@honglouleiyan it seems that indeed something went wrong in your situation, could you pull a request to fix or polish it?

**Comment by ShannonDing** [comment]
@zongtanghu

**Comment by Shellbye** [comment]
Not just `queryMsgByKey`, looks like there is other thing went wrong in `Mqadmin` when `broker` enables `acl`.

I got `org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: No acl config for rocketmq2, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:375)
` when run `clusterList`.

Looks like `Mqadmin` need a place to config `acl` info.

**Comment by zongtanghu** [comment]
When users' rocketmq acl enabled,users need to config your own admin in user's tools.yml which is in the distribution/conf/tools.yml



huzongtang@cmss.chinamobile.com
 
发件人： shellbye
发送时间： 2019-08-29 11:37
收件人： apache/rocketmq
抄送： Hu Zongtang; Mention
主题： Re: [apache/rocketmq] rocketmq tools queryMsgByKey may have bug！ (#1409)
Not just queryMsgByKey, looks like there is other thing went wrong in Mqadmin when broker enables acl.
I got org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: No acl config for rocketmq2, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:375) when run clusterList.
Looks like Mqadmin need a place to config acl info.

**Comment by Shellbye** [comment]
@zongtanghu Thanks.

**Comment by Shellbye** [comment]
@duhenglucky The bug still exist, mine is different.

**Comment by duhenglucky** [comment]
@Shellbye ok, I will reopen this issue, @zongtanghu could you help this guy to resolve this issue?

**Comment by zongtanghu** [comment]
@Shellbye You can compare the tools.yml file to plain_acl.yml file.The admin accessKey and secretKey must be the same value.

**Comment by Shellbye** [comment]
@zongtanghu My problem is solved, but not the original.

**Comment by ShannonDing** [comment]
> @zongtanghu My problem is solved, but not the original.
Could you please check the origin issue again and give more detail issue info here? 
and a PR to fix it is warmly welcome.

**Comment by honglouleiyan** [comment]
> @honglouleiyan it seems that indeed something went wrong in your situation, could you pull a request to fix or polish it?

sorry,I've been busy lately.now, Do I still need to pull a request to fix it?

**Comment by ShannonDing** [comment]
> > @honglouleiyan it seems that indeed something went wrong in your situation, could you pull a request to fix or polish it?
> 
> sorry,I've been busy lately.now, Do I still need to pull a request to fix it?

welcome if you can create a PR to fix it.

**Comment by rushsky518** [comment]
is this problem solved? i want to have a try
