### ISSUE TITLE
the openmessaging-api

### ISSUE THREAD

**Issue by zhouyijiaren** [apache/rocketmq#1414]
https://github.com/apache/rocketmq/blob/master/openmessaging/src/main/java/io/openmessaging/rocketmq/domain/NonStandardKeys.java

why I can't find it in the openmessaging-api.0.1.0.jar. this is the official example

**Comment by duhenglucky** [comment]
@zhouyijiaren the latest version of openmessaging-java dependency is 0.3.1-alpha, and you can try with the latest version rocketmq client. 
and the issue only used for a bug report or feature request, if you have some questions, please subscribe our mailing list and send your question by email: https://rocketmq.apache.org/about/contact/, so I will close this issue, but please feel free to reopen it if you have more questions.

**Comment by zhouyijiaren** [comment]
thank you



---Original---
