### ISSUE TITLE
deleteSubGroup bug

### ISSUE THREAD

**Issue by RongNanNan** [apache/rocketmq#1416]
删除订阅组后, consumeOffset.json里的topic下的该消费组的消费位点还在,这个是不是有点问题
那如果后续又启动了一个这个名称的消费组,会不会莫名奇妙的从之前的消费位点消费,而不是自己配置的

**Comment by duhenglucky** [comment]
@RongNanNan 看怎么看待这个问题了，不过也确实需要一个彻底清理的方法，在保持原有逻辑兼容的情况下，如果你愿意，确实可以提一个pr来实现彻底删除：）。

**Comment by Liberxue** [comment]
@dalaoyang

**Comment by Liberxue** [comment]
> @RongNanNan 看怎么看待这个问题了，不过也确实需要一个彻底清理的方法，在保持原有逻辑兼容的情况下，如果你愿意，确实可以提一个pr来实现彻底删除：）。

I'm dealing with this question, solve it as soon as possible, and give it to me.

**Comment by Liberxue** [comment]
@RongNanNan  @duhenglucky  Resolved [PR](https://github.com/apache/rocketmq/pull/1417)

**Comment by 821320945** [comment]
> 
> 
> @RongNanNan @duhenglucky Resolved [PR](https://github.com/apache/rocketmq/pull/1417)

兄弟  你确定new ConsumerOffsetManager()好使吗   new出来的对象offsetTable难道不是空的吗

**Comment by Liberxue** [comment]
> > @RongNanNan @duhenglucky Resolved [PR](https://github.com/apache/rocketmq/pull/1417)
> 
> 兄弟 你确定new ConsumerOffsetManager()好使吗 new出来的对象offsetTable难道不是空的吗

Oh Yes of course
This Is have some problems....I haven't finished yet
I didn't consider before the cleanup that the client deleted the group from broker or namerSrv. 
Recently make some changes and deal with it ...
THX for U attention, welcome U to join.

**Comment by Liberxue** [comment]
> @RongNanNan 看怎么看待这个问题了，不过也确实需要一个彻底清理的方法，在保持原有逻辑兼容的情况下，如果你愿意，确实可以提一个pr来实现彻底删除：）。

1. When the `deleteSubGroup` time, the ConsumerGroup is running, is it forced to offline the current ConsumerGroup or the prompt cannot be deleted?
2. Does the ConsumerGroup delete the ConsumerOffestList immediately? 
3. What do you think about this issue? Or manually execute `cleanConsumerOffsetList`?

 Please add as a discussion @duhenglucky

**Comment by 821320945** [comment]
> 
> 
> > > @RongNanNan @duhenglucky Resolved [PR](https://github.com/apache/rocketmq/pull/1417)
> > 
> > 
> > 兄弟 你确定new ConsumerOffsetManager()好使吗 new出来的对象offsetTable难道不是空的吗
> 
> Oh Yes of course
> This Is have some problems....I haven't finished yet
> I didn't consider before the cleanup that the client deleted the group from broker or namerSrv.
> Recently make some changes and deal with it ...
> THX for U attention, welcome U to join.
可以尝试下这么写， 从broker中获取ConsumerOffsetManager
  ConsumerOffsetManager clean = brokerController.getConsumerOffsetManager();

**Comment by guixincui** [comment]
is there any progress ?

**Comment by Jaskey** [comment]
还有另外一个问题也类似：

消费者C1组原本监听 A B topic，由于历史原因，后面不再监听B了，假设目前消费进度X。转而让消费者组C2监听了。

这时候B的消息一直进来，但是C1对于B的消费进度是记录了的X的，这时候消息如果进度去到Y。这里有两个问题：

1.实际上，RMQ会认为C1对于topic B是有堆积的（但是实例在线的时候不会显示，实例断线就显示了）
2.假设A后面又觉得还是需要重新监听topic B，这时候就惨了。一堆堆积的历史消费都会再次消费，而且consumer_from_where并不生效，因为你曾经听过。

建议在更新订阅关系的同时，对于consumer group offset也进行更新

**Comment by guixincui** [comment]
提了个MR，默认保持现状不自动删除，增加broker的配置项：https://github.com/apache/rocketmq/pull/2185

**Comment by wz2cool** [comment]
emm... it's a long story. any update about this issue.

**Comment by shadowofmoo** [comment]
any update ?
