### ISSUE TITLE
[RIP-16]add "request-response" support

### ISSUE THREAD

**Issue by qqeasonchen** [apache/rocketmq#1421]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
support "request-response" model

2. Provide any additional detail on your proposed use case for this feature.
see [RIP-16] for more information.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
support request-response

**Comment by vongosling** [comment]
RIP could not create the related issue.
