### ISSUE TITLE
[BUG] Performance Test Consumer in Example not setting the NameServer Addr

### ISSUE THREAD

**Issue by liheyuan** [apache/rocketmq#1425]
**BUG REPORT**

1. Please describe the issue you observed:

org.apache.rocketmq.example.benchmark.Consumer is not setting the NameServer as the Example Producer does.

Which would cause consume failed if not seting nameserver in ENV variable.

2. Please tell us about your environment:

Rocket MQ 4.5.1

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

I'll make a PR to solve the problem.

**Comment by duhenglucky** [comment]
@liheyuan It's recommended to use ENV variable to manage Name server address. 

The issue only used for a bug report or feature request, if you have some questions, please subscribe our mailing list and send your question by email: https://rocketmq.apache.org/about/contact/, so I will close this issue, but please feel free to reopen it if you have more questions.
