### ISSUE TITLE
Update Broker's Topic Read or Write Perm failed

### ISSUE THREAD

**Issue by zongtanghu** [apache/rocketmq#1429]
**BUG REPORT**

1. Please describe the issue you observed:
User use UpdateTopicPermSubCommand command to update broker's topic read or write perm but failed.

2. Please tell us about your environment:
I have tried in our enviroment,such as cluster and single broker.

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
We have already fixed this issue in our own rocketmq branch.

**Comment by zongtanghu** [comment]
This issue will be resolve by this pr(https://github.com/apache/rocketmq/pull/1430)

**Comment by duhenglucky** [comment]
repeat with this [issue](https://github.com/apache/rocketmq/issues/1377)
