### ISSUE TITLE
[Doc] The sub command getConsumerStatus not exist

### ISSUE THREAD

**Issue by liuruiyiyang** [apache/rocketmq#1435]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
In the document https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
```getConsumerStatus ``` is introduced but this command has been discarded in current version. 

When using mqadmin script 
```
./mqadmin getConsumerStatus
```

Maybe the document should be updated.

- What did you expect to see?
The command run normally.

- What did you see instead?
```The sub command getConsumerStatus not exist.```

**Comment by ShannonDing** [comment]
close due to #1460
