### ISSUE TITLE
Broker重启后重复消费消息

### ISSUE THREAD

**Issue by wenfei4** [apache/rocketmq#1440]
**BUG REPORT**

在主从模式下，将主从角色调换后，消费者消费到了历史消息（12小时之前的）。
* 版本：4.2.0
* 部署模式: 集群模式，共4台服务器b1-b4:
    * Broker A: MasterA(b1), SlaveA(b2)
    * Broker B: MasterB(b3), SlaveB(b4)

- What did you do (The steps to reproduce)?

1. shutdown MasterA(b1)
2. wait for 30 minutes
3. shutdown SlaveA(b2)
4. modify b2 set brokerId=0
5. restart b2(as Master)
6. everything be ok
7. after 12 hours, modify b1 set  brokerId=1 and startup b1(as Slave)
8. after b1 sync data from b2, shutdown b2
9. wait for 5 minutes
10. shutdown b1
11. modify b1 set  brokerId=0 and startup b1(as Master)
12. then all consumers are consuming history messages(about 12 hours ago),and a lot of pressure on b1

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by wenfei4** [comment]
验证过commitLog，没有损坏

**Comment by duhenglucky** [comment]
@wenfei4 麻烦确认在你不停的重启恢复的过程中，请确认每次consumer offset是否同步完成；第二个，在你服务端出现问题的时候，consumer有没有进行重启？另外issue只用于bug report或者feature request，如果有更多疑问，可以通过邮件列表来咨询（订阅方式： https://rocketmq.apache.org/about/contact/），所以我先关了这个issue，有问题的话也可以reopen。关于主从切换恢复的问题还是挺有意义的，欢迎在邮件列表（users，dev）发起讨论，有好的想法也欢迎分享给社区其他同学，

**Comment by wenfei4** [comment]
@duhenglucky 
不断的重启是因为我们切了一次机房，将服务从机房1迁移到机房2，而后又迁移回机房1。
在不断的重启过程中 consumer没有重启；
如何确认consumer offset是否同步完成呢？
我理解是不是因为consumer offset没有同步完成，导致consumer在切换broker后拉取消息时，request offset > broker.maxOffset了，所以出现了问题？

**Comment by wenfei4** [comment]
@duhenglucky 另外发现一个现象，将主从角色切换后，在控制台中Consumer页面看到的消息delay数会变成负数，这个是什么原因？对消息收发是没有影响的吧？
