### ISSUE TITLE
消费者订阅不到消息记录

### ISSUE THREAD

**Issue by daixilong** [apache/rocketmq#1441]
![Uploading image.png…]()

**Comment by duhenglucky** [comment]
@daixilong 图片好像挂了，看不到，大概率是你的同一个group的订阅信息不一致，另外issue只用于bug report或者feature request，如果有更多疑问，可以通过邮件列表来咨询（订阅方式： https://rocketmq.apache.org/about/contact/），我先关了这个issue，有问题的话也可以reopen。
