### ISSUE TITLE
BrokerDatas is illegal json

### ISSUE THREAD

**Issue by turtleDeng** [apache/rocketmq#1445]
When calling a GET_ROUTEINTO_BY_TOPIC request, the returned brokerDatas is an illegal json
```
{
	"brokerDatas": [{
		"brokerAddrs": {
			0: "172.168.0.104:10911"
		},
		"brokerName": "yinchongyuandeMacBook-Pro.local",
		"cluster": "DefaultCluster"
	}],
	"filterServerTable": {},
	"queueDatas": [{
		"brokerName": "yinchongyuandeMacBook-Pro.local",
		"perm": 6,
		"readQueueNums": 4,
		"topicSynFlag": 0,
		"writeQueueNums": 4
	}]
}
```

```
"brokerAddrs": {
			0: "172.168.0.104:10911"
		},
```

**Comment by gnocuohz** [comment]
https://github.com/alibaba/fastjson/pull/2698

**Comment by turtleDeng** [comment]
Sorry, we are using other programming languages, we can't use fastjson, its json library in other languages is defined as an illegal json, other json libraries including java can't be parsed, which makes your RocketMQ only in the java ecosystem. Use, can't support more platforms

**Comment by tianyi19970120** [comment]
recommend rocketmq use standardized JSON. but when you use it, I learned that you can also set up non-standardized JSON transformations,  such as jackson(ALLOW_UNQUOTED_FIELD_NAMES)

**Comment by vongosling** [comment]
@turtleDeng you are correct, RocketMQ loves every platform. we will polish here in the latest version.
