### ISSUE TITLE
set ConsumeMessageBatchMaxSize 100 ,but size of message is 1 

### ISSUE THREAD

**Issue by zhanfffmmm** [apache/rocketmq#1446]
集群模式下，消息端我设置了ConsumeMessageBatchMaxSize 100，但是每次消息的大小输出是1，是否还需要配置其他参数？

**Comment by zhanfffmmm** [comment]
生产端和消费端都试过先启动，不过还是显示1，rocketmq版本是apache rocketmq-client-4.1.0

**Comment by Liberxue** [comment]
UpdateTopic ReadQueueNums 100 How's that？

Bin <notifications@github.com> 于2019年9月6日周五 上午10:01写道：

**Comment by zhanfffmmm** [comment]
@Liberxue  thanks, i try it.
 it work when I update readQueueNums in the rocketmq console.
i want the tps up and Delay down when  I update readQueueNums in the rocketmq console.
ps(TPS is 20 and Delay 100, that is normal?)
