### ISSUE TITLE
Please delete old releases from mirroring system

### ISSUE THREAD

**Issue by sebbASF** [apache/rocketmq#1454]
To reduce the load on the ASF mirrors, projects are required to delete old releases [1] from the mirrors.  Please can you remove all non-current releases?

Note: you can still link to older releases if necessary, but the links should point to the archive server.

AFAICT only 4.5.2 is still current, so all the other versions need to be removed from [2].

Where there are links from the website, either remove the link; or change the link to use the archive server.

Then delete the entries from [2]

It's a good idea to update the project release documentation to remind the release manager to tidy up old releases once the new release has been announced.

Thanks!

[1] http://www.apache.org/dev/release.html#when-to-archive
[2] https://dist.apache.org/repos/dist/release/rocketmq/

**Comment by duhenglucky** [comment]
@sebbASF ok，we will clean up the historical version of RocketMQ in the near future.

**Comment by sebbASF** [comment]
Why was this closed?
There are still lots of old releases on dist.a.o

**Comment by duhenglucky** [comment]
@sebbASF  will clean the dist after 4.6.0 release.

**Comment by sebbASF** [comment]
Why not clean it now?

**Comment by duhenglucky** [comment]
> Why not clean it now?
@sebbASF Perhaps we need to discuss it in the community first, after all, many companies still use the old version, what's your opinion?

**Comment by sebbASF** [comment]
As I already wrote, you can still link to old versions on the archive server.

The 3rd party mirrors give their services for free.
It's not fair to burden them with carrying historic releases.

This is a policy matter, not something for discussion by the project:
http://www.apache.org/legal/release-policy.html#when-to-archive

**Comment by ShannonDing** [comment]
done! all the old releases have been removed from [1].
[1]https://dist.apache.org/repos/dist/release/rocketmq/

**Comment by sebbASF** [comment]
Thanks!

Please ensure any release documentation includes a step to purge old releases.

This is best done just after the announce mail has been sent.
