### ISSUE TITLE
Updating broker config of namesrvAddr is not effective

### ISSUE THREAD

**Issue by liuruiyiyang** [apache/rocketmq#1457]
**BUG REPORT**

1. Please describe the issue you observed:
When use ```mqadmin updateBrokerConfig -c clusterName``` to update namesrvAddr config.  The new parameter is not effective.

- What did you do (The steps to reproduce)?
Use ```mqadmin updateBrokerConfig -c clusterName -n oldNameServerList -k namesrvAddr -v newNameServerList ``` to update namesrvAddr config of a cluster

- What did you expect to see?
All brokers in the cluster changed their namesrvAddr and also the new namesrvAddr is effective by registering to new name server. namesrv log showing like ```register broker[0]to name server newAddress:9876 OK```

- What did you see instead?
The new namesrvAddr is not effective.

2. Please tell us about your environment:
MacOS and Linux

**Comment by CodeIngL** [comment]
Mq can't recognize whether your behavior should let us register, here is a special key:brokerPermission to trigger。 try it

**Comment by zhaoyansheng163** [comment]
This bug is also existed.
I  test version 4.7.1 and 4.9.1。
Use mqadmin updateBrokerConfig -c clusterName -n oldNameServerList -k namesrvAddr -v newNameServerList to update namesrvAddr config of a cluster
is  not effective

**Comment by BrightHao** [comment]
> This bug is also existed. I test version 4.7.1 and 4.9.1。 Use mqadmin updateBrokerConfig -c clusterName -n oldNameServerList -k namesrvAddr -v newNameServerList to update namesrvAddr config of a cluster is not effective

I test version 4.7.0 on linux.
Use mqadmin updateBrokerConfig -c clusterName -n oldNameServerList -k namesrvAddr -v newNameServerList to update namesrvAddr config of a cluster
is also not effective
