### ISSUE TITLE
orderly message,stop master broker,slave broker did not distribute message

### ISSUE THREAD

**Issue by ticsmtc6** [apache/rocketmq#1459]
What did i do (The steps to reproduce)?
1.send some messages to broker
2.stop one master broker
3.start orderly consumer

What did i see?
the stoped master broker's slave node did not distribute orderly message to consumer

Please tell us about your environment:
Java: 1.8
RocketMQ: 4.2.0

purpose:
I want upgrade rocketmq from 4.2.0 to 4.5.1
My thought is add 1m&1s 4.5.1 broker,recreate all topic,stop V4.2.0's master broker,consumer pull message from V4.2.0 slave broker,stop slave broker when this broker's all message are consumed
Is there any way to avoid this problem?  Or other better way to accomplish upgrade?

**Comment by duhenglucky** [comment]
@ticsmtc6 RocketMQ MessageListenerOrderly service does not support consumption from slave server, because this may lead messages to out of order.
