### ISSUE TITLE
日志数据删除时间问题

### ISSUE THREAD

**Issue by jinyanhui2008** [apache/rocketmq#1469]
| mapedFileSizeCommitLog     | 1024 * 1024 * 1024(1G) | commit log 的映射文件大小                                       |​ 
| deleteWhen     | 04 | 在每天的什么时间删除已经超过文件保留时间的 commit log                                        |​ 
| fileReserverdTime     | 72 | 以小时计算的文件保留时间                                        |​ 
如上几个参数我都没有配置,按我理解应该使用的是默认配置,我通过RocketMQ控制台进行查询时甚至能查询到十几二十几天以后的message消息, 之前我尝试重启过rocketmq集群会造成重新消费所有消息的问题, 我通过手工排重进行处理了,现在就有个疑问了,如果每次重启都造成大量消息都重新消费而且历史消息一直没有清理过,重启会造成系统压力过大.
所有想问一下, 消息是在系统中保留多长时间?或者重启mq怎么才能避免重复消费?

**Comment by duhenglucky** [comment]
@jinyanhui2008 mapedFileSizeCommitLog跟保留时间没有直接关系，但是在你的情况中可能是连一个commitlog都没有写满，其余的两个参数建议配置还是一下,[参考中文文档](http://rocketmq.cloud/zh-cn/docs/bestpractice-broker.html)，是否重复消费跟消费端的配置也有关系，比如是否是新的consumer group，包括消费起始位置等，RocketMQ即使在新的consumer group的情况下，如果消息量不大尚在内存中，也会从头消费，用以避免消息丢失。
Issue一般用来做bug report以及feature request，所以有问题还是希望在邮件列表里面搜索提问，[邮件列表地址](https://rocketmq.apache.org/about/contact/)，所以我先关掉这个issue，有问题的话也可以再打开。

**Comment by jinyanhui2008** [comment]
我没有有新增订阅,还是原来的订阅组,之前出过一次事故是我的一个master节点重启了,然后造成这个master上的消息全部被重新消费了一遍,我的整个消费端没有手工调整过偏移量.
然后我的commitlog确实好几天才会写满一个 ,我现在是想知道怎么处理才能保证mq集群重启不会造成重复消费,或者只重复消费一段时间的数据,现在重启可能会重复消费好久之前的数据.

**Comment by duhenglucky** [comment]
@jinyanhui2008 你是用的广播模式还是集群模式，广播模式的话要本地记录offset，集群模式的话看下服务端的consumerOffset.json 是否有更新或者是否出现损坏。

**Comment by jinyanhui2008** [comment]
> @jinyanhui2008 你是用的广播模式还是集群模式，广播模式的话要本地记录offset，集群模式的话看下服务端的consumerOffset.json 是否有更新或者是否出现损坏。

我用的是集群模式, 下次重启的时候我检查一下这个问题.
另外广播模式需要本地记录偏移量, 如果我消费端程序重启了会造成全量消息重新消费吗,我设置的都是默认位置开始消费,不应该从最后开始消费?
