### ISSUE TITLE
RECONSUME_LATER only retry once

### ISSUE THREAD

**Issue by lastboy1228** [apache/rocketmq#1472]
I trace the MQClientAPIImpl.consumerSendMessageBack function, and found it works correctly in client, when renturning ConsumeConcurrentlyStatus.RECONSUME_LATER. But the message do not enter %RETRY%ConsumerGroup topic. Sometimes the message enter the retry topic once, but it just disappear even when the client throw RECONSUME_LATER again.

The problem cluster version is 4.3.1. Another cluster having almost same configs and version do not have the problem.

So, I can not find a clue.

**Comment by lastboy1228** [comment]
I found the broker in the problem cluster has broken consumequeue/SCHEDULE_TOPIC_XXXX strucure, how can I fix it?

![image](https://user-images.githubusercontent.com/10094929/65337339-88816880-dbfa-11e9-9435-39c354473158.png)

**Comment by lastboy1228** [comment]
The current ScheduleMessageOffset_4 is invalidly larger then the max ScheduleMessageOffset_4, After I sent enough msg to this delay level, the problem gone.

**Comment by duhenglucky** [comment]
@lastboy1228 could you provide more information about this issue, you can describe it in Chinese.

**Comment by lastboy1228** [comment]
> @lastboy1228 could you provide more information about this issue, you can describe it in Chinese.

用“mqadmin brokerStatus”命令，看到各个scheduleMessageOffset_X里，“已处理offset” 大于 “已接收的offset”。（可能是转生产时，拷贝了测试集群的store/consumequeue文件夹）
在我贴的图里，scheduleMessageOffset_4的已处理记录是6012，已接收记录是395；第二次消费失败的消息，进入scheduleMessageOffset_4后就不再被broker处理和投递了。

我手动生成大量各个延迟级别的消息，使得“已处理offset” 小于 “已接收的offset”后，新的延迟消息就开始被正常投递了。问题已解决
