### ISSUE TITLE
trace message`s clientHost was wrong

### ISSUE THREAD

**Issue by ChaosYjh** [apache/rocketmq#1473]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
When TraceDataEncoder encrypts/decrypts tracedata, there is no client information. The default data is used when decrypts tracedata, which is wrong.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/27771595/65366794-0aa17980-dc5b-11e9-9881-bd06000fcaa6.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/27771595/65366798-1db44980-dc5b-11e9-9bef-b77eda87347d.png">
- What did you expect to see?
The correct clientHost should be clientId

**Comment by gaoyf** [comment]
其实没必要，因为每条消息本身有bornHost，这个就是客户端ip，没必要在trace信息里再加上。
仅仅是展示trace数据的时候，把消息的bornHost赋给TraceBean的clientHost就行了。

**Comment by ChaosYjh** [comment]
我们实际在做消息轨迹的展示的时候不会多余的再去调用一遍queryMessageById的接口。所有trace消息的数据来源都是trace消息本身的内容。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gaoyf"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 下午5:07
收件人:&nbsp;"apache/rocketmq"<rocketmq@noreply.github.com&gt;;
抄送:&nbsp;"苑俊辉"<763900954@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/rocketmq] trace message`s clientHost was wrong (#1473)




其实没必要，因为每条消息本身有bornHost，这个就是客户端ip，没必要在trace信息里再加上。
 仅仅是展示trace数据的时候，把消息的bornHost赋给TraceBean的clientHost就行了。

**Comment by gaoyf** [comment]
你没明白我说啥，给你[代码](https://github.com/sohutv/mqcloud/blob/master/mq-cloud/src/main/java/com/sohu/tv/mq/cloud/service/MessageService.java#L828)自己看吧

**Comment by gaoyf** [comment]
再说明白点，pub类型的trace消息的bornHost就是客户端生产者的ip，sub类型的trace消息的bornHost就是客户端消费者的ip。

**Comment by ChaosYjh** [comment]
> 再说明白点，pub类型的trace消息的bornHost就是客户端生产者的ip，sub类型的trace消息的bornHost就是客户端消费者的ip。

抱歉这么晚才回复你，目前的bug是这样的：客户端a发送的消息，客户端b消费的消息，但是通过运维端c去查询消息轨迹的时候显示的c的ip地址。实际应该生产方显示a的ip地址，消费放显示b的ip地址。
