### ISSUE TITLE
One server can be deployed 2m-2s-async in ? version 4.5.2

### ISSUE THREAD

**Issue by lexingrensheng** [apache/rocketmq#1476]
**broker-a.properties**

`
brokerClusterName=RocketMQCluster

brokerName=broker-a

brokerId=0

brokerRole=ASYNC_MASTER

flushDiskType=ASYNC_FLUSH

listenPort=10911

namesrvAddr=XXX.XXX.XXX.217:9876

brokerIP1=XXX.XXX.XXX.217

defaultTopicQueueNums=4

autoCreateTopicEnable=true

autoCreateSubscriptionGroup=true

storePathRootDir=/opt/rocketmq-4.5.2/dataAmaster/store

storePathCommitLog=/opt/rocketmq-4.5.2/dataAmaster/store/commitlog

storePathConsumerQueue=/opt/rocketmq-4.5.2/dataAmaster/store/consumequeue

storePathIndex=/opt/rocketmq-4.5.2/dataAmaster/store/index

storeCheckpoint=/opt/rocketmq-4.5.2/dataAmaster/store/checkpoint

abortFile=/opt/rocketmq-4.5.2/dataAmaster/store/abort

deleteWhen=04

fileReservedTime=120

mapedFileSizeCommitLog=1073741824

mapedFileSizeConsumeQueue=300000
`

**broker-a-s.properties**

`
brokerClusterName=RocketMQCluster

brokerName=broker-a

brokerId=1

listenPort=10921

brokerRole=SLAVE

flushDiskType=ASYNC_FLUSH

namesrvAddr=XXX.XXX.XXX.217:9876

brokerIP1=XXX.XXX.XXX.217

defaultTopicQueueNums=4

autoCreateTopicEnable=true

autoCreateSubscriptionGroup=true

storePathRootDir=/opt/rocketmq-4.5.2/dataAslave/store

storePathCommitLog=/opt/rocketmq-4.5.2/dataAslave/store/commitlog

storePathConsumerQueue=/opt/rocketmq-4.5.2/dataAslave/store/consumequeue

storePathIndex=/opt/rocketmq-4.5.2/dataAslave/store/index

storeCheckpoint=/opt/rocketmq-4.5.2/dataAslave/store/checkpoint

abortFile=/opt/rocketmq-4.5.2/dataAslave/store/abort

maxMessageSize=65536

deleteWhen=04

fileReservedTime=120

mapedFileSizeCommitLog=1073741824

mapedFileSizeConsumeQueue=300000

`

**broker-b.properties**

`
brokerClusterName=RocketMQCluster

brokerName=broker-b

brokerId=0

brokerRole=ASYNC_MASTER

listenPort=10909

flushDiskType=ASYNC_FLUSH

namesrvAddr=XXX.XXX.XXX.217:9876

brokerIP1=XXX.XXX.XXX.217

defaultTopicQueueNums=4

autoCreateTopicEnable=true

autoCreateSubscriptionGroup=true

storePathRootDir=/opt/rocketmq-4.5.2/dataBmaster/store

storePathCommitLog=/opt/rocketmq-4.5.2/dataBmaster/store/commitlog

storePathConsumerQueue=/opt/rocketmq-4.5.2/dataBmaster/store/consumequeue

storePathIndex=/opt/rocketmq-4.5.2/dataBmaster/store/index

storeCheckpoint=/opt/rocketmq-4.5.2/dataBmaster/store/checkpoint

abortFile=/opt/rocketmq-4.5.2/dataBmaster/store/abort

maxMessageSize=65536

deleteWhen=04

fileReservedTime=120

mapedFileSizeCommitLog=1073741824

mapedFileSizeConsumeQueue=300000

`

**broker-b-s.properties**

`
brokerClusterName=RocketMQCluster

brokerName=broker-b

brokerId=1

brokerRole=SLAVE

flushDiskType=ASYNC_FLUSH

listenPort=10919

namesrvAddr=XXX.XXX.XXX.217:9876

brokerIP1=XXX.XXX.XXX.217

defaultTopicQueueNums=4

autoCreateTopicEnable=true

autoCreateSubscriptionGroup=true

storePathRootDir=/opt/rocketmq-4.5.2/dataBslave/store

storePathCommitLog=/opt/rocketmq-4.5.2/dataBslave/store/commitlog

storePathConsumerQueue=/opt/rocketmq-4.5.2/dataBslave/store/consumequeue

storePathIndex=/opt/rocketmq-4.5.2/dataBslave/store/index

storeCheckpoint=/opt/rocketmq-4.5.2/dataBslave/store/checkpoint

abortFile=/opt/rocketmq-4.5.2/dataBslave/store/abort

deleteWhen=04

fileReservedTime=120

mapedFileSizeCommitLog=1073741824

mapedFileSizeConsumeQueue=300000
`

start step 
1.namesrv 
2.broker-a,
3.broker-b,
4.broker-a-s,
5.broker-b-s

when start step 4 or 5 is error 
`
nohup: ignoring input

java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.apache.rocketmq.store.ha.HAService$AcceptSocketService.beginAccept(HAService.java:177)
	at org.apache.rocketmq.store.ha.HAService.start(HAService.java:109)
	at org.apache.rocketmq.store.DefaultMessageStore.start(DefaultMessageStore.java:275)
	at org.apache.rocketmq.broker.BrokerController.start(BrokerController.java:826)
	at org.apache.rocketmq.broker.BrokerStartup.start(BrokerStartup.java:64)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)
`
**what is use ip or port ,how can I config**

**Comment by duhenglucky** [comment]
@lexingrensheng you used the same port in one sever.
