### ISSUE TITLE
loginfo is ambiguity when visiting namesrv

### ISSUE THREAD

**Issue by keranbingaa** [apache/rocketmq#1477]
**BUG REPORT**

1. Please describe the issue you observed:
When client wants to get some info such as topicinfo from namesrv,  it call invokeSync in NettyRemotingClient.java, and the parameter addr is null. When some exception occur, the log which contains the parameter addr will be "the channel [null]", it's ambiguity and misleading.

2. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
don't use the parameter addr in log.

**Comment by duhenglucky** [comment]
@keranbingaa address seems more clear than the channel, IMHO, print all channel info isn't a good choice in here.
