### ISSUE TITLE
The sample delay message seems to have a problem.

### ISSUE THREAD

**Issue by harvies** [apache/rocketmq#1480]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
https://github.com/apache/rocketmq/blob/master/docs/cn/RocketMQ_Example.md Delay message sample "message.getStoreTimestamp()“ is error,should be ”message.getBornTimestamp()“.
- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:
rocketmq:4.5.2
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by duhenglucky** [comment]
@harvies read  org.apache.rocketmq.store.schedule.ScheduleMessageService.DeliverDelayedMessageTimerTask#executeOnTimeup for more detail :).
