### ISSUE TITLE
4.5.2 版本 logging 包代码多余

### ISSUE THREAD

**Issue by mickey0524** [apache/rocketmq#1481]
4.5.2 版本中，logging/src/main/java/org/apache/rocketmq/logging/InnerLoggerFactory.java 文件中 284 行的判断是多余的，如果前面的 for 循环结束，说明 len == argArray.length，或者直接在 for 循环内就 return 了，因此此处没有必要使用 if
<img width="775" alt="rocketmq-log" src="https://user-images.githubusercontent.com/22164927/65502296-1c05b280-def5-11e9-9b9b-4cb6b1f19f08.png">

**Comment by duhenglucky** [comment]
@mickey0524 纯粹是一种defense-in-depth代码，不知道后面还有谁还会动这段代码。Issue一般用来做bug report以及feature request，所以有问题还是希望在邮件列表里面搜索提问，[邮件列表地址](https://rocketmq.apache.org/about/contact/)，所以我先关掉这个issue，有问题的话也可以再打开。
