### ISSUE TITLE
QueryMsgByIdSubCommand print OffsetID twice

### ISSUE THREAD

**Issue by ChaosYjh** [apache/rocketmq#1483]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
QueryMsgByIdSubCommand print OffsetID twice
<img width="710" alt="image" src="https://user-images.githubusercontent.com/27771595/65588733-9b10ee80-dfba-11e9-8b29-be6e5189f6e8.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/27771595/65588750-a6fcb080-dfba-11e9-8dcb-33e1d8299008.png">

- What did you expect to see?
QueryMsgByIdSubCommand print OffsetID once
2. Please tell us about your environment:
rocketmq4.5.2

**Comment by duhenglucky** [comment]
@ good catch

**Comment by duhenglucky** [comment]
merged
