### ISSUE TITLE
Is there a plan for "RocketMQ dledger version"  to support batch msg?

### ISSUE THREAD

**Issue by lahahana** [apache/rocketmq#1485]
In RocketMQ 4.5.0 dledger version, batch msg is  not supported, may i ask what's the plan and release timepoint?
![image](https://user-images.githubusercontent.com/17375141/65654827-af9dc700-e04c-11e9-8b3c-b9af57aecf22.png)

**Comment by duhenglucky** [comment]
@lahahana yes, the community is working on this part of work and will be released in the near future.

**Comment by lahahana** [comment]
> @lahahana yes, the community is working on this part of work and will be released in the near future.

**Comment by lahahana** [comment]
> @lahahana yes, the community is working on this part of work and will be released in the near future.

may I known what's impaction that batch msg will cause if "4.5.0 dledger version" take it in?
