### ISSUE TITLE
Service startup report disk error

### ISSUE THREAD

**Issue by qianketian** [apache/rocketmq#1493]
Hello:
    I have been reporting errors after I deployed the rocketmq broker service.
![image](https://user-images.githubusercontent.com/10296101/65784816-892f7700-e185-11e9-9237-e927dcb69d85.png)
   Prompt that my disk capacity is insufficient, but the disk usage in my system is only 10%.
![image](https://user-images.githubusercontent.com/10296101/65784922-d1e73000-e185-11e9-8321-08914724d665.png)

My command to run the service is this
```
nohup ./mqbroker -c ../conf/2m-2s-sync/broker-a.properties -n 10.0.20.52:9876 &
```
I looked at a lot of information, but there was no gain.
Ask for your help

My test environment:
    Rocketmq Version: 4.5.1
    System Version: CentOS 7.5
    Disk capacity: 200G

Attachment is a log file.
[rocketlogs.tar.gz](https://github.com/apache/rocketmq/files/3663724/rocketlogs.tar.gz)

**Comment by wqliang** [comment]
This may because of the directory of 'USER_HOME/store/commitlog' not exist. The directory will be created when you send first message to this broker.

**Comment by qianketian** [comment]
Is it possible to create this directory manually?
