### ISSUE TITLE
unit test in DefaultLitePullConsumerTest sometimes fail

### ISSUE THREAD

**Issue by wqliang** [apache/rocketmq#1495]
**BUG REPORT**

1. Please describe the issue you observed:
`testSeek_SeekOffsetSuccess` in DefaultLitePullConsumerTest sometimes failed.

Failed tests: 
DefaultLitePullConsumerTest.testSeek_SeekOffsetSuccess:188 expected:<-1> but was:<123>

- What did you do (The steps to reproduce)?
1\open a pull request then trigger CI;
2\just run unit test of DefaultLitePullConsumerTest 

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
I added some log where `seekOffset ` was set and found that the value was set to 123 by thread `main `and then set to -1 by `PullMsgThread-`.

**Comment by duhenglucky** [comment]
this issue has been fixed in this [PR](https://github.com/apache/rocketmq/pull/1461)
