### ISSUE TITLE
 load delayOffset.json error

### ISSUE THREAD

**Issue by mengshuai85** [apache/rocketmq#1498]
System: Windows 2012

when system down or restart，mq can't start,
ERROR main - load c:/rocketmq/store\config\delayOffset.json failed, and try to load backup file
com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0, fastjson-version 1.2.51

beacuse the file is not json format，and the reason we don't kown。

服务器重启之后，MQ就不能启动了，原因是 delayOffset.json 变成了乱码，不能解析了
但是 具体原因，不知道，现在只能每次出了问题 覆盖这个文件，对运维压力很大

**Comment by duhenglucky** [comment]
@mengshuai85 你的Windows机器的编码是什么？能不能选择其他的编码格式试下。

**Comment by liangyuanpeng** [comment]
可以提供更多详细信息以供一起查找问题，
例如：
windows版本: e.g.:server 10
RocketMq 版本
windows机器默认编码

**Comment by mengshuai85** [comment]
> 可以提供更多详细信息以供一起查找问题，
> 例如：
> windows版本:  server 2012
> RocketMq 版本:4.5.1
> windows机器默认编码: 936，(GBK简体中文)

部署的是 单机环境，只有1个主，没有从

第一场景：
原来 在broker.conf 配置文件中配置如下：
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
# brokerRole = ASYNC_MASTER      （最开始未注释掉，服务器断电后就乱码）
flushDiskType = ASYNC_FLUSH

场景2：当注释掉brokerRole后，
# brokerRole = ASYNC_MASTER      

未推送消息时，服务器断电重启 OK，可以正常启动

当推送消息后，服务器断电重启 NG，还是 乱码

**Comment by duhenglucky** [comment]
@mengshuai85 推送消息后，会更新当前的offset，默认为utf-8格式，所以你改成utf-8编码来试下。

**Comment by sem-wong** [comment]
> @mengshuai85 推送消息后，会更新当前的offset，默认为utf-8格式，所以你改成utf-8编码来试下。
也遇到同样问题，"改为UTF-8试下"请问是指将什么改为UTF-8?

**Comment by ljywit** [comment]
我的rocketmq版本是4.2.0，服务器掉电，很容易出现delayOffset.json乱码，导致broker启动失败。还望求解。
1，操作系统windows server 2012

**Comment by mengshuai85** [comment]
忘了这个issue了，我们当时改源码解决了
由于 我们是单机环境，也不需要同步和delay，所以把写文件这块 注释掉了，重新打包，替换 应用中jar包，这样解决的

修改代码如下图：

![image](https://user-images.githubusercontent.com/5234760/90202449-54b1c180-de10-11ea-99dd-3223ae709cf6.png)

**Comment by mengshuai85** [comment]
这边去年底临时解决了这个问题，在issue上回复了


| |
孟帅
|
|
mengshuai85@163.com
|
签名由网易邮箱大师定制
On 8/14/2020 08:17，ljywit<notifications@github.com> wrote：

我的rocketmq版本是4.2.0，服务器掉电，很容易出现delayOffset.json乱码，导致broker启动失败。还望求解。
1，操作系统windows server 2012

**Comment by ljywit** [comment]
> 忘了这个issue了，我们当时改源码解决了
> 由于 我们是单机环境，也不需要同步和delay，所以把写文件这块 注释掉了，重新打包，替换 应用中jar包，这样解决的
> 
> 修改代码如下图：
> 
> ![image](https://user-images.githubusercontent.com/5234760/90202449-54b1c180-de10-11ea-99dd-3223ae709cf6.png)
您好，这个图片路径好像打不开，能否贴一下具体代码吗？谢谢。
