### ISSUE TITLE
Split Message in sample code

### ISSUE THREAD

**Issue by maoz123** [apache/rocketmq#1505]
![image](https://user-images.githubusercontent.com/33593433/66270992-c1247180-e88b-11e9-9073-2f353f1d2ed9.png)

If current message size is larger than the maximum size(4M). The message should be abandoned. 
If only self-increase nextIndex, there will be "nextIndex=currIndex+1". Later, when subList method is called,  messages[currIndex] will be kept.  As this message can not be sent, maybe the message should be abondoned here.  
My question is "does self-increase both nextIndex and currIndex work here ? In this way, the message that has exceed the maximum size will be abondoned。

**Comment by MountainOne** [comment]
> My question is "does self-increase both nextIndex and currIndex work here ?

It's not working here. If you do this, `next()` will return a` List` which does not contain any messages. This situation needs to be avoided as we always want a valid return value when we call `next()` in an iterator. The operation to abandon an invalid message  should be implemented in the inner iterator
