### ISSUE TITLE
MQPullConsumerScheduleService.registerPullTaskCallback() handle namespace imperfect

### ISSUE THREAD

**Issue by geektao** [apache/rocketmq#1512]
MQPullConsumerScheduleService.registerPullTaskCallback source  as follows :

`    public void registerPullTaskCallback(final String topic, final PullTaskCallback callback) {
        this.callbackTable.put(topic, callback);
        this.defaultMQPullConsumer.registerMessageQueueListener(topic, null);
    }
`

in method registerPullTaskCallback,  'this.callbackTable.put(topic, callback)' handle topic without namespace . but next line ' this.defaultMQPullConsumer.registerMessageQueueListener(topic, null)' handle  topic with namespace .

And when broker has namespace ,will cause can not find topic’s PullTaskCallback 。

**Comment by duhenglucky** [comment]
@geektao RocketMQ provided a [litePullconsumer](https://github.com/apache/rocketmq/pull/1386) to replace previous pull implementation, could you give more advice about it?
