### ISSUE TITLE
unit test of DefaultMQProducer has some problems when send async messages

### ISSUE THREAD

**Issue by keranbingaa** [apache/rocketmq#1528]
**BUG REPORT**

1. Please describe the issue you observed:
in DefaultMQProducerTest, the async mode test doesn't execute as expected. 
For example, the testSendMessageAsync_Success function call send function, which is expected to excute callback function onSuccess, but when I debug, I find it calls onException.

2. Please tell us about your environment:
rocketMQ 4.5

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
when producer get the topicrouteinfo, it returns null, which causes this problem. So if the producer get right topicrouteinfo and call sendback function, it canbe excuted as we expected.

**Comment by duhenglucky** [comment]
merged, thanks for your contribution.
