### ISSUE TITLE
官网文档 Simple Example 章节异步的代码案例运行会出异常

### ISSUE THREAD

**Issue by qingmg** [apache/rocketmq#1537]
如题意，在 http://rocketmq.apache.org/docs/simple-example/ 中 2.2 的代码案例，在循环结束后，会直接 shutdown 其中的 producer 实例，并没有等待消息先发出去，导致异常。
而在源码中，是实例化了一个 CountDownLatch 对象，执行了其中的 await 方法。

希望有空的话可以更新下官网中的文档。

**Comment by duhenglucky** [comment]
@qingmg 欢迎提个pr哈
