### ISSUE TITLE
Some questions about the location of consumers and the automatic deletion of messages

### ISSUE THREAD

**Issue by YngJian** [apache/rocketmq#1542]
您好，有两个疑问请问一下，搭建的rocketMq是采用双主双从的配置。
1.创建的消费者消费的位置设定为CONSUME_FROM_FIRST_OFFSET，新建的消费者消费的起始位置是按什么位置算的起始位。
2.默认的配置文件消息清理是在每天四点，清理的消息是存储在本地磁盘上的消息吗？

Hello, there are two questions I would like to ask,The built rocketMq is a dual-master dual-slave configuration.
1. The location of the created consumer consumption is set to CONSUME_FROM_FIRST_OFFSET, and the starting position of the newly created consumer consumption is the starting position according to the position.
2. The default profile message cleanup is at four o'clock every day. Is the cleaned up message a message stored on the local disk?

**Comment by duhenglucky** [comment]
1、按照CQ的最小位点开始消费。
2、是的，。
对RocketMQ有兴趣的话，最好在[邮件列表](https://rocketmq.apache.org/about/contact/)里面讨论，这个issue一般用于bug report跟feature request，

**Comment by YngJian** [comment]
谢谢了，还有一个问题就是，我消费者定义的是广播模式，消息发送成功，有时候会出现消费迟迟没有成功，而且出现的次数不少，但是上管理台看死信队列又没有这条消息，这是会因为什么原因。
