### ISSUE TITLE
Docker环境下三台机器，rocketmq部分队列没有消费者消费消息

### ISSUE THREAD

**Issue by ByteDanceWYQ** [apache/rocketmq#1547]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:
    docker环境三台机器消费mq消息，运行一段时间之后，部分队列没有消费者连接，

    查看消费者详细信息，三台机器的clientAddr地址不一样，但是有个clientId是一样。

    怀疑clientId重复，影响rebalance

2. Please tell us about your environment:
broker版本：V4_5_1
生产者版本：V4_5_1
消费者版本：V4_5_1
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

ClientId             | ClientAddr              | Language | Version
172.17.0.1@173 | 10.31.79.112:59606 | JAVA | V4_5_1
172.17.0.1@170 | 10.31.79.717:48864 | JAVA | V4_5_1
172.17.0.1@170 | 10.31.79.710:52994 | JAVA | V4_5_1

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ByteDanceWYQ** [comment]
> @ByteDanceWYQ it seems that you have the same issue with #667

how to resolve it ?

**Comment by duhenglucky** [comment]
> create a unique instanceName for each consumer instance ?

yes

**Comment by duhenglucky** [comment]
@ByteDanceWYQ we can continue to discuss this issue in this issue: https://github.com/apache/rocketmq/issues/667, and I will close this issue first, please feel free if you have other questions.

**Comment by Orange-apples** [comment]
consumer的instanceName默认是....DefaultRocketMQListenerContainer_X ，这个要怎么改
