### ISSUE TITLE
misspelt words

### ISSUE THREAD

**Issue by huangzhike** [apache/rocketmq#1549]
hi,
I happened to find that there are some misspelt words in the code, like

`ProcessQueue#makeMessageToCosumeAgain`, which should be `ProcessQueue#makeMessageToConsumeAgain`, 

and `ProcessQueue#takeMessags`, which should be `ProcessQueue#takeMessages`,

and `LocalTransactionState.UNKNOW`,  which I believe should be `LocalTransactionState.UNKNOWN`.

RocketMQ version: 4.5.2, current master branch.

**Comment by duhenglucky** [comment]
@huangzhike some spelling mistakes can correct as some functions only just be used in rocketmq inner, but some spelling mistakes cannot be corrected just because it exposed to users, thus there will be compatibility issues after correct.
