### ISSUE TITLE
Is the 'http://rocketmq.cloud' stopped for maintenance?

### ISSUE THREAD

**Issue by wxisme** [apache/rocketmq#1552]
[http://rocketmq.cloud](http://rocketmq.cloud )不能正常访问了，是不维护了吗？还是故障了？这个wiki对于中国开发者来说还是挺友好的，如果是故障了，希望关注一下。感谢。

**Comment by duhenglucky** [comment]
@wxisme all docs  maintain in here: https://github.com/apache/rocketmq/tree/master/docs/cn
