### ISSUE TITLE
Can NOT found main Class    org.apache.rocketmq.namesrv.NamesrvStartup

### ISSUE THREAD

**Issue by luyuanwan** [apache/rocketmq#1555]
### Environment
JDK  1.8.0_101
Branch master

### Description
I build  the project with JDK8  and cd to  distribution/bin, but I got ERROR like  Can NOT found main Class    org.apache.rocketmq.namesrv.NamesrvStartup, operation just like this

```shell

  man clean package
  cd distribution/bin
  sh mqnamesrv
```

ERROR just like this
```
Java HotSpot(TM) 64-Bit Server VM warning: Using the DefNew young collector with the CMS collector is deprecated and will likely be removed in a future release
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
错误: 找不到或无法加载主类 org.apache.rocketmq.namesrv.NamesrvStartup
```

**Comment by xiangwangcheng** [comment]
Maybe you have the ROCKETMQ_HOME configured wrong. I may be  xxxx\distribution.

**Comment by luyuanwan** [comment]
Thanks,I know what 's wrong.

**Comment by xiangwangcheng** [comment]
@luyuanwan It would be great if you can share the solution with others.

**Comment by luyuanwan** [comment]
@xiangwangcheng   

use 
```java
mvn -Prelease-all -DskipTests clean install -U 
```
rather than
```shell
 man clean package
```
