### ISSUE TITLE
The Produce Count not equal to Consume Count. Why?

### ISSUE THREAD

**Issue by tyhqiushen** [apache/rocketmq#1557]
Yesterday Produce Count | Yesterday Consume Count

6401445 | 3920193

Today Produce Count | Today Consume Count

2168858 | 1323910

The Produce Count not equal to Consume Count. Why?

为什么我的生产消息数量和消费消息数量每天的都对不上呢？
没有什么特殊设置，消费端就是CLUSTERING模式，感觉也并没有丢消息。

**Comment by luyuanwan** [comment]
因为存在重试的情况，所以两者的次数遇见的相等

**Comment by tyhqiushen** [comment]
> 因为存在重试的情况，所以两者的次数不一定相等

@luyuanwan 感谢大佬回答，但是这差距也太大了。一天差200多万。就怕丢消息啊。我现在是同步刷盘，同步复制，按理不应该发生有在不知情下消息没了的情况。

**Comment by luyuanwan** [comment]
建议在消费消息的地方捕获异常，并判断如果重试次数大于某个值，就将这个信息记录到日志库中，不再让MQ重试，否则的话，MQ会一直重试，直到达到最大重试次数才会停止(我记得是15次吧)，记录日志数据库的目的是方便后期排查，否则这个问题一直找不到原因

**Comment by tyhqiushen** [comment]
> 建议在消费消息的地方捕获异常，并判断如果重试次数大于某个值，就将这个信息记录到日志库中，不再让MQ重试，否则的话，MQ会一直重试，直到达到最大重试次数才会停止(我记得是15次吧)，记录日志数据库的目的是方便后期排查，否则这个问题一直找不到原因

@luyuanwan 谢谢大佬。我这里讲生产客户端重试设置为1次了，外面也捕获了异常以及判断返回的SendResult结果，如果出现未成功的情况，我都将结果写到一个补偿文件中，并且通过监控埋点进行报警通知。但目前从未接到过报警情况。我感觉应该已经保证了SDK外部调用的数据的可靠性。

生产端应该是没有丢过数据，只是目前两个数对不上，而且差异太大了，感觉有些奇怪。

**Comment by YuShanMuGong** [comment]
> 建议在消费消息的地方捕获异常，并判断如果重试次数大于某个值，就将这个信息记录到日志库中，不再让MQ重试，否则的话，MQ会一直重试，直到达到最大重试次数才会停止(我记得是15次吧)，记录日志数据库的目的是方便后期排查，否则这个问题一直找不到原因

集群消费模式下，会无限重试消费消息。。

**Comment by xiangzilv123** [comment]
大佬发现一样的，问题，有解释吗

**Comment by popo706** [comment]
> > 建议在消费消息的地方捕获异常，并判断如果重试次数大于某个值，就将这个信息记录到日志库中，不再让MQ重试，否则的话，MQ会一直重试，直到达到最大重试次数才会停止(我记得是15次吧)，记录日志数据库的目的是方便后期排查，否则这个问题一直找不到原因
> 
> @luyuanwan 谢谢大佬。我这里讲生产客户端重试设置为1次了，外面也捕获了异常以及判断返回的SendResult结果，如果出现未成功的情况，我都将结果写到一个补偿文件中，并且通过监控埋点进行报警通知。但目前从未接到过报警情况。我感觉应该已经保证了SDK外部调用的数据的可靠性。
> 
> 生产端应该是没有丢过数据，只是目前两个数对不上，而且差异太大了，感觉有些奇怪。
 you may have opened the message trace

**Comment by xu42** [comment]
> Yesterday Produce Count | Yesterday Consume Count
> 
> 6401445 | 3920193
> 
> Today Produce Count | Today Consume Count
> 
> 2168858 | 1323910
> 
> The Produce Count not equal to Consume Count. Why?
> 
> 为什么我的生产消息数量和消费消息数量每天的都对不上呢？
> 没有什么特殊设置，消费端就是CLUSTERING模式，感觉也并没有丢消息。

你好，请问下这个问题后面有解决么？我这边也是同样的情况

**Comment by popo706** [comment]
看一下是否打开了消息轨迹，消息轨迹会额外的生产消息

**Comment by xu42** [comment]
> 看一下是否打开了消息轨迹，消息轨迹会额外的生产消息

确实是打开了的，非常感谢。
