### ISSUE TITLE
Whether module `acl` can compatible with 1.6 as same as module `client`

### ISSUE THREAD

**Issue by geektao** [apache/rocketmq#1558]
when use client with acl to connect broker, it will throw compatibility exception，as follows：
`java.lang.UnsupportedClassVersionError: org/apache/rocketmq/acl/common/AclClientRPCHook : Unsupported major.minor version 52.0`.
I read the latest(4.5.2) client version's pom.xml,it compile with 1.6 . but module ‘acl’ inherit parent java version is 1.8.  

Whether module `acl` can compatible with 1.6 as same as module `client`?

**Comment by duhenglucky** [comment]
@geektao good question, would you like to pull a request to change the ACL client dependency to 1.6? add the maven property in pom.xml 
       <maven.compiler.source>1.6</maven.compiler.source>
        <maven.compiler.target>1.6</maven.compiler.target> 

and modify relative errors led by this change, more errors maybe the Map or List definition.
