### ISSUE TITLE
bug ：PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS no effect

### ISSUE THREAD

**Issue by 2259289435** [apache/rocketmq#1565]
Please describe the issue you observed:
PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS No effect
What did you do (The steps to reproduce)?
msg.putUserProperty(MessageConst.PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS, "1");
What did you expect to see?
after 1s execute checkLocalTransaction
What did you see instead?
checkLocalTransaction after 10-20s 
Please tell us about your environment:
rocketmq 4.5.2 
Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by duhenglucky** [comment]
@2259289435 PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS not only depends on the customer value in this property but also depends on the transactionCheckInterval config in the broker.

**Comment by 2259289435** [comment]
> @2259289435 PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS not only depends on the customer value in this property but also depends on the transactionCheckInterval config in the broker.

Do I understand the mistake?
Is there an example of using this property?
https://rocketmq.apache.org/docs/transaction-example/
(3) A transactional message will be checked after a certain period of time that determined by parameter “transactionTimeout” in the configuration of the broker. And users also can change this limit by set user property “CHECK_IMMUNITY_TIME_IN_SECONDS” when sending transactional message, this parameter takes precedence over the “transactionMsgTimeout” parameter.

**Comment by duhenglucky** [comment]
@2259289435 actually, RocketMQ check to see if there are half messages that need to be checked back at regular intervals(determined by the 'transactionCheckInterval', default is one minute), so the 'PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS' should larger than this interval at least, the document on the website should be described more clearly.

**Comment by 2259289435** [comment]
> @2259289435 actually, RocketMQ check to see if there are half messages that need to be checked back at regular intervals(determined by the 'transactionCheckInterval', default is one minute), so the 'PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS' should larger than this interval at least, the document on the website should be described more clearly.

thank you，Is there a way for the client to set the first checkback time?
Now I am using hack to manually submit to speed up the time.

**Comment by duhenglucky** [comment]
@2259289435 eh, rocketmq didn't provide the precise time control of the first check back up to now, but if you have some optimization design, welcome to pull a request to polish it.
