### ISSUE TITLE
bug executeLocalTransaction fail

### ISSUE THREAD

**Issue by 2259289435** [apache/rocketmq#1566]
1. Please describe the issue you observed:
method executeLocalTransaction always return commit, but still triggered method checkLocalTransaction 
- What did you do (The steps to reproduce)?
@Override
	public LocalTransactionState executeLocalTransaction(Message msg, Object arg) {
		return LocalTransactionState.COMMIT_MESSAGE;
	}
- What did you expect to see?
do not trigger checkLocalTransaction
- What did you see instead?

2. Please tell us about your environment:
4.5.2 default
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by duhenglucky** [comment]
@2259289435 maybe you used older client, it would be better if you can upgrade your client to 4.5.2. and you can also verify that if these checkback messages are messages you committed, maybe uncommitted messages of other producers sent in the same producer group.
hope you can provide more question and if you can send your code and logs to my email if not convenient：duhengforever@apache.org

**Comment by 2259289435** [comment]
> @2259289435 maybe you used older client, it would be better if you can upgrade your client to 4.5.2. and you can also verify that if these checkback messages are messages you committed, maybe uncommitted messages of other producers sent in the same producer group.
> hope you can provide more question and if you can send your code and logs to my email if not convenient：[duhengforever@apache.org](mailto:duhengforever@apache.org)

ok，email 。 my client，server version all 4.5.2
