### ISSUE TITLE
kill one rocketMq master broker and slave broker CPU is much higher than before

### ISSUE THREAD

**Issue by walterhong** [apache/rocketmq#1573]
![截图2](https://user-images.githubusercontent.com/16216936/68191734-25e9fd80-ffeb-11e9-96b5-28e1016fee85.PNG)
after killing one rocketmq master broker, the cpu of machine which slave broker is running on become much higher than before. I use top -Hp slave broker process to find which thread cpu is the highest and use jstack to see what the thread that has the highest cpu is doing, then I get following pictures
![截图22](https://user-images.githubusercontent.com/16216936/68192530-68f8a080-ffec-11e9-8ec3-fed588eaf6b4.PNG)
![截图211](https://user-images.githubusercontent.com/16216936/68192544-6dbd5480-ffec-11e9-9c37-a4526f74f70f.PNG)
as shown in the above pictures, asyncappender-worker-thread has the highest CPU, why does this situation happens?How can I solve this question? Can I solve this question by changing parameters of rocketMq?

**Comment by walterhong** [comment]
@WillemJiang @justinmclean @jimjag @ke4qqq 大佬帮帮忙，我们非功能测试不知道为什么Kill掉其中一台机器的master broker，slave broker的CPU就飙涨

**Comment by duhenglucky** [comment]
@walterhong I will try with your description and if you have other useful detailed information, please comment it in here, but as your picture shows, the thread that occupies the highest CPU is 10227, it's hexadecimal representation is 27f3, so maybe you should list more information here,

**Comment by walterhong** [comment]
@duhenglucky I use top -Hp 10227, and I get the thread PID that has the highest CPU in process 10227, and then I use ‘printf %x\n to transform this thread PID into its hexadecimal representation,0x2889,and at last I use jstack 10277|grep 0x2889 -A 30, and I find the one of the highest CPU thread name in process 10277 is Async-appended-worker, and the other threads in process 10277 which have as high CPU as Async-appended-worker are  Netty threads such as nettyserverthread, nettyNIOthread, and nettycodecthrrad.

**Comment by duhenglucky** [comment]
@walterhong What you said seems makes sense. It is recommended to check the relevant configuration of sysctl, especially the related configuration in os.sh. In addition, it is recommended to execute os.sh before service started, which optimizes the default values of some os kernels parameters.

**Comment by walterhong** [comment]
@duhenglucky 
I have ran os.sh on every machine that broker is running, but when I killed the master broker, the slave broker cpu was still high. I configure master slave syncronizing mode to async, flushing disk mode to sync. The threads that has high cpu can be categorized into two types, one is nettynioselectorthread, the other is nettyservercodecthread. What the nettyservercodecthread is doing is showing in the following pictures:
![image](https://user-images.githubusercontent.com/16216936/70308123-9338ba80-1845-11ea-9384-8e2ff3b3eb7c.png)
![image](https://user-images.githubusercontent.com/16216936/70308133-96cc4180-1845-11ea-9dcc-72fbc29a0343.png)
![image](https://user-images.githubusercontent.com/16216936/70308140-9b90f580-1845-11ea-8fda-aacb321dbd46.png)
the pictures are content of slave broker process in jstack. I find that when master broker is down, slave broker is trying to do something very fast in org.apache.rocketmq.remoting model, which makes the cpu high.

**Comment by walterhong** [comment]
@duhenglucky 
I remote debug slave broker that has high cpu,and find that request code of the highest thread in slave broker process is get_broker_runtime_info

**Comment by duhenglucky** [comment]
@walterhong   did you used the rocketmq-console？and this  page will frequently call this interface and will lead to highest CPU usage.

**Comment by walterhong** [comment]
@duhenglucky 
I kill rocketmq-console when slave broker CPU is high, but the CPU does not fall down

**Comment by duhenglucky** [comment]
> @duhenglucky
> I kill rocketmq-console when slave broker CPU is high, but the CPU does not fall down

ok, could you provide more information, or you can connect with me by Dingtalk:juicehenry
