### ISSUE TITLE
Why add @Deprecated in DefaultMQProducer#getDefaultMQProducerImpl

### ISSUE THREAD

**Issue by Switch-vov** [apache/rocketmq#1578]
The code in line 878 of `DefaultMQProducer`.

``` java
    @Deprecated
    public DefaultMQProducerImpl getDefaultMQProducerImpl() {
        return defaultMQProducerImpl;
    }
```

If it's ok, please add some comment.

@duhenglucky

**Comment by duhenglucky** [comment]
@Switch-vov just because we hope that users can directly use the externally exposed interface instead of directly using the underlying implementation or even modifying it. This will make it difficult for users to upgrade.
