### ISSUE TITLE
Unable to boot rocketmq, crash the computer

### ISSUE THREAD

**Issue by X-ration** [apache/rocketmq#1582]
I was following the quickstart doc, when i try to start the broker
```
  > nohup sh bin/mqbroker -n localhost:9876 &
  > tail -f ~/logs/rocketmqlogs/broker.log 
```
My computer stucks and stops to respond.

Ubuntu 18.04, rocketmq 4.4.0/4.2.0

**Comment by X-ration** [comment]
please add some explanation to make a better guidance.
the initial config, with namesrv 4g heap, and broker 8g heap, along with metaspace size, not every pc has such memory, and that can cause consequences.

**Comment by duhenglucky** [comment]
@X-ration thanks for your suggestion, this start script gives a more common configuration. Would you like to propose a PR to add this question to Q&A?

**Comment by X-ration** [comment]
> @X-ration thanks for your suggestion, this start script gives a more common configuration. Would you like to propose a PR to add this question to Q&A?

I could not fully understand it, so what is a PR and how can I propose a PR to add the question to Q&A?
