### ISSUE TITLE
how to delete delayqueue message

### ISSUE THREAD

**Issue by TangsengCoder** [apache/rocketmq#1583]
What should I do when I want to delete messages that have not expired！

the message is in the delay queue

**Comment by MountainOne** [comment]
RocketMQ has an expired file deletion mechanism. If the non-currently written commitlog file is not updated again within a certain time interval, it is considered an expired file and RocketMQ will automatically delete it.
By default, each file has an expiration time of 72 hours, and the expiration time is modified by setting `fileReservedTime` in the Broker configuration file.

RocketMQ 有过期文件删除机制，非当前写的 commitlog 文件在一定时间间隔内没有再次被更新，则被认为是过期文件，RocketMQ 会自动删除。
默认每个文件的过期时间为 72 个小时，通过在 Broker 配置文件中设置`fileReservedTime`来修改过期时间，单位为小时。

**Comment by duhenglucky** [comment]
@TangsengCoder so sorry that RocketMQ does not support cleaning data in the topic dimension currently.

**Comment by mali-nuist** [comment]
@duhenglucky Hope to have way to clean the queue like the rabbitmq : 
         rabbitmqctl purge_queue queue_name

**Comment by shrinidhi111** [comment]
> RocketMQ has an expired file deletion mechanism. If the non-currently written commitlog file is not updated again within a certain time interval, it is considered an expired file and RocketMQ will automatically delete it.
> By default, each file has an expiration time of 72 hours, and the expiration time is modified by setting `fileReservedTime` in the Broker configuration file.
> 
> RocketMQ 有过期文件删除机制，非当前写的 commitlog 文件在一定时间间隔内没有再次被更新，则被认为是过期文件，RocketMQ 会自动删除。
> 默认每个文件的过期时间为 72 个小时，通过在 Broker 配置文件中设置`fileReservedTime`来修改过期时间，单位为小时。

Is there a way I can reduce the time to 5 minutes?

I tried fileReservedTime of 0.1 (roughly 6 min) but consumer still got the messages after 10 mins.

What does deleteWhen do? 

Is it an interval or time of the day?

**Comment by handongopqwe** [comment]
did latest version have support  delete delayqueue message ？
