### ISSUE TITLE
rocketmq不能正常消费，连续排查36小时，都没有效果！！

### ISSUE THREAD

**Issue by duofu** [apache/rocketmq#1586]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
线上使用正常，将线上的应用程序、rocketmq包、配置文件和数据库表导到本地部署环境。

- What did you expect to see?
应用程序正常消费消息。

- What did you see instead?
系统启动后几秒内能正常消费，之后Consumer stop掉线，除非重启否则不会消费消息，重启->依旧如此->重启->依旧如此->..........
检查过MQ配置、系统代码版本、服务器网络、MQ版本、Linux版本、JDK版本等，也试过应用系统和MQ部署同一台服务器等方法（因为部署环境也是线上，客户只提供两台，不能换），都证明无效。

2. Please tell us about your environment:
机器配置：8vCPUs  | 16GB | 500G
Linux配置：CentOS 7.6
![image](https://user-images.githubusercontent.com/8102301/68579491-31d43480-04af-11ea-97c0-7c6e2a9f93c9.png)

**Comment by duhenglucky** [comment]
@duofu 能不能发一下日志，看下不同consumer的订阅信息是否一致。
