### ISSUE TITLE
commitlog文件名称生成错乱

### ISSUE THREAD

**Issue by zhuqingzhen** [apache/rocketmq#1587]
你好请看我们的commitlog文件名称和生成时间，貌似没有按照规则来啊，感觉非常困惑，这是不是bug?
[work@10-15-154-253 commitlog]$ ll -t
total 3918696
-rw-rw-r-- 1 work work 1073741824 Nov 12 02:34 00000000034359738368
-rw-rw-r-- 1 work work 1073741824 Nov 10 12:15 00000000033285996544
-rw-rw-r-- 1 work work 1073741824 Nov 10 12:15 00000000035433480192
-rw-rw-r-- 1 work work 1073741824 Nov  7 09:52 00000000032212254720
-rw-rw-r-- 1 work work 1073741824 Nov  4 10:02 00000000031138512896

**Comment by duhenglucky** [comment]
没有问题，上面的是修改时间，还有创建commitlog的时候会预先同时多创建一个，另外，issue用作bug report以及feature request，对于一些咨询类的问题尽量在[邮件列表](https://rocketmq.apache.org/about/contact/)里面讨论，这样可以沉淀下来，后续也能搜索，不过有其他问题的话，可以随时重新打开这个issue。

**Comment by zhuqingzhen** [comment]
好的，非常感谢。
