### ISSUE TITLE
MQFaultStrategy is not work

### ISSUE THREAD

**Issue by MountainOne** [apache/rocketmq#1592]
**BUG REPORT**

1. Please describe the issue you observed:
There are no unit tests about `MQFaultStrategy` here. Inspired by #1576 , I decided to check whether `MQFaultStrategy` is working, so I write some unit tests about it.
I mocked a `topicPublishInfo`, which contains three brokers that tested normal conditions, one broker is unavailable, two brokers are unavailable, and all are unavailable. It was found that the original `MQFaultStrategy` failed to pass the unit test after the `sendLatencyFaultEnable` was true.

- What did you do (The steps to reproduce)?
I write some unit tests to verify the logic of MQFaultStrategy.

- What did you expect to see?
The MQFaultStrategy could pass all the tests and return the expected message queue.

- What did you see instead?
The message queue return on a broker is always randomly chosen instead of the logical return expected by the MQSFaultStrategy.

2. Please tell us about your environment:
macOS 10.13.6 

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
I refer to #1576 to modify the logic of MQFaultStrategy#selectOneMessageQueue and pass the unit tests rightly.

**Comment by duhenglucky** [comment]
repeat with this [issue](https://github.com/apache/rocketmq/issues/1576)
