### ISSUE TITLE
Message consumption takes more than 15 minutes, it is possible to generate two identical messages in the retry topic

### ISSUE THREAD

**Issue by panzhi33** [apache/rocketmq#1600]
Message consumption takes more than 15 minutes, it is possible to generate two identical messages in the retry topic。

When the message is consumed for more than 15 minutes, then
org.apache.rocketmq.client.impl.consumer.ProcessQueue#cleanExpiredMsg this method scans and finds，will send this message to the retry topic and delete it from the cache.

but this message is still consumer . finally, in org.apache.rocketmq.client.consumer.listener.MessageListenerConcurrently#consumeMessage this method, this message will be consumed more than once if the return is successful or failed.

**Comment by MountainOne** [comment]
RocketMQ guarantees that the message will be delivered without loss, but there is no guarantee that the message will not be duplicated. RocketMQ handed over the work of resolving the message to the user.
There are two main ways to solve the message duplication: the first method is to ensure the idempotency of the consumption logic (multiple calls and the same call); the other method is to maintain a record of the message that has been consumed, and check the message whether have been consumed before the query.

RocketMQ保证了消息一定投递且不丢失，但不保证消息不会重复。RocketMQ把解决消息重复的工作交给了用户。
解决消息重复主要有两种方法：第一种方法是保证消费逻辑的幂等性（多次调用和一次调用相同）；另一种方法是维护一个已经消费消息的记录，消费前查询这个消息是否被消费过。
