### ISSUE TITLE
TIMEOUT_CLEAN_QUEUE, org.apache.rocketmq.store.ha.HAConnection.ReadSocketService#run this.selector.select(1000) cost 5000+ms

### ISSUE THREAD

**Issue by ticsmtc6** [apache/rocketmq#1602]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
4 master 4 slave scale out to 10 master 10 slave, i found many TIMEOUT_CLEAN_QUEUE exception, in store.log i found a lot of master-slave sync error(do sync transfer other node, wait return, but failed, topic:).  so i added a log around of HAConnection.ReadSocketService#run this.selector.select(1000) as follow:

**Long beginTime = System.currentTimeMillis();
this.selector.select(1000);
log.info("[ADD DEBUG LOG] master read socket service select eclipse: " + (System.currentTimeMillis() - beginTime));**

then i found a lot of log shows this line cost exceed 5000ms

- What did you expect to see?
Selector.select(1000) method shoud block at most 1000ms

- What did you see instead?
A lot of times Selector.select(1000) method cost exceeds 5000ms

2. Please tell us about your environment:
rocketmq version:4.2.0
Aliyun 16C64G 10m-10s

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
Only new added 6m-6s report this exception.
When TIMEOUT_CLEAN_QUEUE exception occurs, I found some TCP retransmission，Is there a connection between the two？

**Comment by ticsmtc6** [comment]
master:
brokerRole=SYNC_MASTER
flushDiskType=ASYNC_FLUSH
slave:
brokerRole=SLAVE
flushDiskType=ASYNC_FLUSH

jvm  parameter add:-XX:+PrintSafepointStatistics  -XX:PrintSafepointStatisticsCount=1

safepoint log as follow:

         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
1656.618: PrintThreads                     [     192          0              0    ]      [     0     0     0     0  5962    ]  0   

**Why "PrintThreads" vmop causing long vm pause?
Does the master slave network problem cause this pause?**
@duhengforever

**Comment by duhenglucky** [comment]
@ticsmtc6 could you give us more information about your environment? such as JDK version, os version, your JVM start configuration, some GC log such as: Total time for which application threads were stopped ****, etc.. Something wrong in connection(connect, retry, slow) seems can cause this issue, and you can refer:
https://stackoverflow.com/questions/29536473/why-is-printthreads-vm-op-causing-long-vm-pauses-in-the-application

**Comment by RongtongJin** [comment]
Here is a [PR](https://github.com/apache/rocketmq/pull/1083) about slave miscalculate the report time.

**Comment by ticsmtc6** [comment]
@duhengforever  
java -version
java version "1.8.0_151"

uname  -a
Linux pro-ecs-rocketmq-3-66 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

jvm confiuration:
 -Xms26g -Xmx26g -Xmn14g -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -verbose:gc -Xloggc:/dev/shm/mq_gc_%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=50g -XX:-UseLargePages -XX:-UseBiasedLocking -XX:+PrintSafepointStatistics -XX:PrintSafepointStatisticsCount=1

gc log:
2019-11-21T18:05:00.909+0800: 1655.004: Total time for which application threads were stopped: 0.0006644 seconds, Stopping threads took: 0.0001931 seconds
2019-11-21T18:05:08.486+0800: 1662.581: Total time for which application threads were stopped: 5.9630721 seconds, Stopping threads took: 0.0001196 seconds
2019-11-21T18:05:08.487+0800: 1662.582: Total time for which application threads were stopped: 0.0006973 seconds, Stopping threads took: 0.0001753 seconds
2019-11-21T18:05:08.487+0800: 1662.582: Total time for which application threads were stopped: 0.0005689 seconds, Stopping threads took: 0.0001733 seconds
2019-11-21T18:05:08.510+0800: 1662.606: [GC pause (G1 Evacuation Pause) (young) 1662.606: [G1Ergonomics (CSet Construction) start choosing CSet, _pending_cards: 0, predicted base time: 10.72 ms, remaining time: 189.28 ms, target pause time: 200.00 ms]
 1662.606: [G1Ergonomics (CSet Construction) add young regions to CSet, eden: 893 regions, survivors: 3 regions, predicted young region time: 8427.79 ms]
 1662.606: [G1Ergonomics (CSet Construction) finish choosing CSet, eden: 893 regions, survivors: 3 regions, old: 0 regions, predicted pause time: 8438.51 ms, target pause time: 200.00 ms]
 1662.636: [G1Ergonomics (Mixed GCs) do not start mixed GCs, reason: candidate old regions not available]
, 0.0305605 secs]
   [Parallel Time: 23.1 ms, GC Workers: 8]
      [GC Worker Start (ms): Min: 1662606.0, Avg: 1662610.2, Max: 1662625.2, Diff: 19.2]
      [Ext Root Scanning (ms): Min: 0.0, Avg: 0.6, Max: 1.9, Diff: 1.8, Sum: 4.9]
      [Update RS (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
         [Processed Buffers: Min: 0, Avg: 0.0, Max: 0, Diff: 0, Sum: 0]
      [Scan RS (ms): Min: 0.1, Avg: 0.2, Max: 0.5, Diff: 0.4, Sum: 1.6]
      [Code Root Scanning (ms): Min: 0.0, Avg: 0.8, Max: 5.9, Diff: 5.9, Sum: 6.4]
      [Object Copy (ms): Min: 1.1, Avg: 15.0, Max: 21.2, Diff: 20.1, Sum: 119.7]
      [Termination (ms): Min: 0.0, Avg: 2.1, Max: 2.4, Diff: 2.4, Sum: 16.9]
         [Termination Attempts: Min: 1, Avg: 2.1, Max: 3, Diff: 2, Sum: 17]
      [GC Worker Other (ms): Min: 0.0, Avg: 0.0, Max: 0.1, Diff: 0.0, Sum: 0.3]
      [GC Worker Total (ms): Min: 3.7, Avg: 18.7, Max: 22.9, Diff: 19.2, Sum: 149.8]
      [GC Worker End (ms): Min: 1662628.9, Avg: 1662628.9, Max: 1662629.0, Diff: 0.1]
   [Code Root Fixup: 1.7 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 1.2 ms]
   [Other: 4.5 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 2.3 ms]
      [Ref Enq: 0.1 ms]
      [Redirty Cards: 0.2 ms]
      [Humongous Register: 0.1 ms]
      [Humongous Reclaim: 0.0 ms]
      [Free CSet: 1.3 ms]
   [Eden: 14.0G(14.0G)->0.0B(13.9G) Survivors: 48.0M->80.0M Heap: 14.0G(26.0G)->67.6M(26.0G)]
 [Times: user=0.16 sys=0.00, real=0.03 secs] 
2019-11-21T18:05:08.541+0800: 1662.636: Total time for which application threads were stopped: 0.0319419 seconds, Stopping threads took: 0.0007202 seconds

Corresponding safepoint log:
1655.004: no vm operation                  [     192          0              0    ]      [     0     0     0     0     0    ]  0   
         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
1656.618: PrintThreads                     [     192          0              0    ]      [     0     0     0     0  5962    ]  0   
         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
1662.581: PrintJNI                         [     192          0              0    ]      [     0     0     0     0     0    ]  0   
         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
1662.582: FindDeadlocks                    [     192          0              1    ]      [     0     0     0     0     0    ]  0   
         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
1662.604: G1IncCollectionPause             [     192          2              1    ]      [     0     0     0     0    30    ]  1

**Comment by ticsmtc6** [comment]
Add some personal guesses

safepoint log as follow:
27123.445: PrintThreads                     [     232          0              0    ]      [     0     0     0     0  1303    ]  0  
27183.285: PrintThreads                     [     232          0              0    ]      [     0     0     0     0  1555    ]  0   
27243.350: PrintThreads                     [     232          0              0    ]      [     0     0     0     0  1776    ]  0   
27303.652: PrintThreads                     [     232          0              0    ]      [     0     0     0     0  2002    ]  0   
27363.195: PrintThreads                     [     232          0              0    ]      [     0     0     0     0  2259    ]  0   
27423.006: PrintThreads                     [     232          0              0    ]      [     0     0     0     0  2537    ]  0  

I found that every two PrintThreads is exactly 60s,So I wonder if there's a scheduled task,
Otherwise I can't understand why all the two PrintThreads are exactly 60s between them.
@duhenglucky Could you give some advice or guess?
