### ISSUE TITLE
bug trace enable

### ISSUE THREAD

**Issue by 2259289435** [apache/rocketmq#1608]
4.5.2 release
AsyncTraceDispatcher start use same name，one start，other throw exception。 DefaultMQPushConsumer eat。
![图片](https://user-images.githubusercontent.com/23507198/69405899-c9514700-0d3b-11ea-8031-1c2072c65a9e.png)
![图片](https://user-images.githubusercontent.com/23507198/69405937-e4bc5200-0d3b-11ea-8c89-599601edf346.png)
![图片](https://user-images.githubusercontent.com/23507198/69405985-f867b880-0d3b-11ea-9fab-403d63a183c6.png)
boom！！

**Comment by duhenglucky** [comment]
@2259289435 could you help to review and verify this [PR](https://github.com/apache/rocketmq/pull/1303), it seems that this PR will resolve your issue.
