### ISSUE TITLE
Is it neccessary that use lock per message queue where orderly comsuming?

### ISSUE THREAD

**Issue by liyiwen3** [apache/rocketmq#1610]
Is it neccessary that use lock per message queue where orderly comsuming?

顺序消费的时候，为每个消息队列分配一把锁，这个是有必要的吗？
 final Object objLock = messageQueueLock.fetchLockObject(this.messageQueue);
            synchronized (objLock) {
在ConsumeMessageOrderlyService的420和421行，对同一个队列的消息的拉取本身是串行的了，
且由于ProcessQueue的consuming状态位的存在，对同一个队列的消费已经可以保证是串行了，
所以在消费的时候，为每个消息队列分配一把锁，这个是有必要的吗？

**Comment by RongtongJin** [comment]
有必要。队列锁能保证同一个队列的ConsumeRequest在线程池被消费不会是乱序的，ProcessQueue的consuming状态位无法代替锁的作用。

**Comment by liyiwen3** [comment]
> 有必要。队列锁能保证同一个队列的ConsumeRequest在线程池被消费不会是乱序的，ProcessQueue的consuming状态位无法代替锁的作用。

由于对消息的拉取是串行的，所以用ProcessQueue的consuming状态可以保证，同一个时间不会有两个ConsumeRequest，对同一个队列进行顺序消费。所以我觉得队列锁还是没有必要的。您的回答不能解决我的疑惑，如果可以的话进一步解答我的疑惑，万分感谢。
