### ISSUE TITLE
How to Get topic consumption data

### ISSUE THREAD

**Issue by xiaoyan999** [apache/rocketmq#1618]
How to Get topic consumption data?Please help me!

**Comment by xiaoyan999** [comment]
How to Get topic consumption data?Please help me!

**Comment by duhenglucky** [comment]
> How to Get topic consumption data?Please help me!

It is recommended to monitor stats.log to get topic related or consume related data, or use mqadmin tools to gather metrics data, more information can be refered inn https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md.
