### ISSUE TITLE
use two DefaultMQPushConsumer listen two topics, only one topic can get message trace

### ISSUE THREAD

**Issue by leoxchang** [apache/rocketmq#1619]
I used two DefaultMQPushConsumer listen two topics, that from one "nameSrv";only one topic can get message trace. I debug the rocketmq client source,I see that "AsyncTraceDispatcher.start" method throws MQClientException,because the traceProducer has bean created,the "MQ-AsyncTraceDispatcher-Thread-" thread can not start. so one DefaultMQPushConsumer can not send trace message.

当使用两个”DefaultMQPushConsumer“ 监听同一个服务地址的topic时，只有其中的一个topic是可以查询到消息轨迹的，我debug源码发现"AsyncTraceDispatcher.start"这个方法抛出了MQClientException，原因是traceProducer 已经被创建过了，所以"MQ-AsyncTraceDispatcher-Thread" 线程没有被启动，导致其中的一个DefaultMQPushConsumer没法发送trace消息。

**Comment by duhenglucky** [comment]
@leoxchang 这个问题社区正在进行修复，最近会有一个优化，另外还有一个[PR](https://github.com/apache/rocketmq/pull/1303) 在解决这个问题，您可以验证一下，用来暂时解决你的问题。
