### ISSUE TITLE
mqadmin command line tools args spell error

### ISSUE THREAD

**Issue by martianzhang** [apache/rocketmq#1620]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
```bash
./mqadmin clusterRT -h
./mqadmin checkMsgSendRT -h
```
- What did you expect to see?
```bash
-a,--amount <arg>          message amount | default 100
```
- What did you see instead?
```bash
-a,--amout <arg>          message amout | default 100
```
2. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
tools/src/main/java/org/apache/rocketmq/tools/command/cluster/CLusterSendMsgRTCommand.java
![image](https://user-images.githubusercontent.com/1827047/69707661-23d01600-1135-11ea-9edd-c6e24e7ddb73.png)

**Comment by duhenglucky** [comment]
@martianzhang could you pull a request to fix it?

**Comment by martianzhang** [comment]
> @martianzhang could you pull a request to fix it?

@duhenglucky #1629 take look please
