### ISSUE TITLE
mqadmin stdout print with warning info

### ISSUE THREAD

**Issue by martianzhang** [apache/rocketmq#1621]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
mqadmin command output with WARNING info, which is so annoying.
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
RocketMQLog:WARN Please initialize the logger system properly.

![image](https://user-images.githubusercontent.com/1827047/69707937-a78a0280-1135-11ea-93df-9d77b64ddf7d.png)

2. Provide any additional detail on your proposed use case for this feature.
Can I do some log config to disable this annoying WARN info?

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
nice-to-hive

**Comment by zongtanghu** [comment]
This issue can be assigned to me!
