### ISSUE TITLE
New API to create topic ?

### ISSUE THREAD

**Issue by intodream** [apache/rocketmq#1622]
DefaultMQProducer.createTopic is Deprecated.

This method will be removed in a certain version after April 5, 2020, so please do not use this method.

What's the alternative?

**Comment by duhenglucky** [comment]
@intodream recommend using AdminTools to create the topic, exposing the createTopic interface to users will bring huge risks.

**Comment by intodream** [comment]
What version has AdminTools ?

**Comment by intodream** [comment]
@duhenglucky CTL Admin Tool

 command bash mqadmin ?

**Comment by duhenglucky** [comment]
@intodream org.apache.rocketmq.tools.admin.DefaultMQAdminExt
