### ISSUE TITLE
Why can not  ip of the broker listens start with "127.0" and "192.168"?If you want to get non-private address, ip that starts with "10." is private address

### ISSUE THREAD

**Issue by liyiwen3** [apache/rocketmq#1630]
why can not  ip that the broker listens start with "127.0" and "192.168"?  If you want to get non-private address, ip that starts with "10."  is private address. 

code in RemotingUtil
`public static String getLocalAddress() {
        try {
            // Traversal Network interface to get the first non-loopback and non-private address
            Enumeration<NetworkInterface> enumeration = NetworkInterface.getNetworkInterfaces();
            ArrayList<String> ipv4Result = new ArrayList<String>();
            ArrayList<String> ipv6Result = new ArrayList<String>();
            while (enumeration.hasMoreElements()) {
                final NetworkInterface networkInterface = enumeration.nextElement();
                final Enumeration<InetAddress> en = networkInterface.getInetAddresses();
                while (en.hasMoreElements()) {
                    final InetAddress address = en.nextElement();
                    if (!address.isLoopbackAddress()) {
                        if (address instanceof Inet6Address) {
                            ipv6Result.add(normalizeHostAddress(address));
                        } else {
                            ipv4Result.add(normalizeHostAddress(address));
                        }
                    }
                }
            }

            // prefer ipv4
            if (!ipv4Result.isEmpty()) {
                for (String ip : ipv4Result) {
                    if (ip.startsWith("127.0") || ip.startsWith("192.168")) {
                        continue;
                    }

                    return ip;
                }

                return ipv4Result.get(ipv4Result.size() - 1);
            } else if (!ipv6Result.isEmpty()) {
                return ipv6Result.get(0);
            }
            //If failed to find,fall back to localhost
            final InetAddress localHost = InetAddress.getLocalHost();
            return normalizeHostAddress(localHost);
        } catch (Exception e) {
            log.error("Failed to obtain local address", e);
        }

        return null;
    }`

**Comment by sufeng** [comment]
docker swarm集群容器内有多个网卡  按照目前的逻辑 返回的客户端IP不是我想要的结果 是否可以考虑添加参数可以忽略某些网段

**Comment by duhenglucky** [comment]
@sufeng @liyiwen3 在多网卡选择的过程中，可以参考这个issue，自己定制一些IP的选择策略。
