### ISSUE TITLE
What kind of consideration is it based on that one MQ client only has one connection to the broker?

### ISSUE THREAD

**Issue by liyiwen3** [apache/rocketmq#1631]
What kind of consideration is it based on that one MQ client has only at most one connection to the broker?

**Comment by xiangwangcheng** [comment]
If the "MQ client" means MQClientInstance, yes, one MQClientInstance maintains one connection to one broker(but it maintains the connections with all brokers in the cluster).
And you can create producers/consumers in any numbers in your client-side, each holds one MQClientInstance.

**Comment by liyiwen3** [comment]
Do you mean use&nbsp;unitName in ClientConfig.class?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"程向往"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 上午8:59
收件人:&nbsp;"apache/rocketmq"<rocketmq@noreply.github.com&gt;;
抄送:&nbsp;"915071628"<915071628@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/rocketmq] What kind of consideration is it based on that one MQ client only has one connection to the broker? (#1631)




If the "MQ client" means MQClientInstance, yes, one MQClientInstance maintains one connection to one broker(but it maintains the connections with all brokers in the cluster).
 And you can create producers/consumers in any numbers in your client-side, each holds one MQClientInstance.

**Comment by xiangwangcheng** [comment]
Sorry, there is one mistake in previous comment. 
 If you have more than one producer or consumer in one process, they will share one MQClientInstance, which means share one connection to a particular broker.
If you have more than one producer or consumer in different processes,  MQClientInstance wont be shared and so is the connection.
