### ISSUE TITLE
消费的客户端IP获取有问题

### ISSUE THREAD

**Issue by sufeng** [apache/rocketmq#1634]
docker swarm集群容器内有多个网卡 按照目前的逻辑 返回的客户端IP不是我想要的结果 是否可以考虑添加参数可以忽略某些网段
![image](https://user-images.githubusercontent.com/481930/69943966-1219b480-1521-11ea-84e3-1a6e3e25721f.png)
后面10网段才是我想要的IP  现在返回的结果是172的网段

**Comment by duhenglucky** [comment]
@sufeng 这个确实是个问题，但是你可以在启动的时候通过     
   consumer.setClientIP("xxxx");
自己注入IP，这样就可以将你的过滤逻辑放在你的应用中，放到RocketMQ中会显得非常繁琐。
