### ISSUE TITLE
rocketmq rejectrequest system busy

### ISSUE THREAD

**Issue by Michael754267513** [apache/rocketmq#1635]
rocketmq修改磁盘刷盘模式， 原为同步刷盘应用正常发送消息，后改为异步刷盘，应用出现rejectrequest system busy。在修改为同步刷盘应用正常。  

1. 异步刷盘应该性能比同步更好，为什么在修改刷盘模式后应用出现问题 拒绝了改请求。

**Comment by LoveVsLike** [comment]
能提供一下详细的日志信息吗

**Comment by francisoliverlee** [comment]
> rocketmq修改磁盘刷盘模式， 原为同步刷盘应用正常发送消息，后改为异步刷盘，应用出现rejectrequest system busy。在修改为同步刷盘应用正常。
> 
> 1. 异步刷盘应该性能比同步更好，为什么在修改刷盘模式后应用出现问题 拒绝了改请求。

@Michael754267513 
show  ur broker config, jvm config and total memory size
