### ISSUE TITLE
A directory traversal vulnerability exists in RocketMQ's automatic topic creation

### ISSUE THREAD

**Issue by coffeehb** [apache/rocketmq#1637]
Hello, 
I found a security vulnerability. A directory traversal vulnerability exists when RocketMQ automatically creates a topic.

Test environmental conditions:
 - RocketMQ4.6.0  The latest version
 - autoCreateTopicEnable=true  default setting

my computer：
 - Windows7 pro  x64
 - JDK1.8.0_181 x64

The design of storage path is mentioned in the overall architecture of message storage,
 the specific storage path is $HOME/store/consumequeue/{topic}/{queueId }/{fileName}. 

when the client constructs the topic as ../../../fuzz2019, the directory can be successfully created by traversing the directory under the C drive.
like this:
![image](https://user-images.githubusercontent.com/5829776/70145516-391be600-16db-11ea-84d6-b94890c584e6.png)

![image](https://user-images.githubusercontent.com/5829776/70145531-3faa5d80-16db-11ea-9f8b-0c30957dc302.png)

**Comment by feng3** [comment]
666

**Comment by duhenglucky** [comment]
@coffeehb it would be better to add some filtering logic on the topic name when creating a topic.

**Comment by coffeehb** [comment]
> @coffeehb it would be better to add some filtering logic on the topic name when creating a topic.
Yes, without filtering logic, an attacker can fill up any arbitrary directory on the system. Please note that this issue may exist other versions of the rocketmq, not only 4.6.0 or Windows systems.

**Comment by duhenglucky** [comment]
> > @coffeehb it would be better to add some filtering logic on the topic name when creating a topic.
> > @duhenglucky
> > Yes, without filtering logic, an attacker can fill up any arbitrary directory on the system. Please note that this issue may exist other versions of the rocketmq, not only 4.6.0 or Windows systems.

thanks for your reminder, and could you submit a PR to fix it?

**Comment by coffeehb** [comment]
> > > @coffeehb it would be better to add some filtering logic on the topic name when creating a topic.
> > > @duhenglucky
> > > Yes, without filtering logic, an attacker can fill up any arbitrary directory on the system. Please note that this issue may exist other versions of the rocketmq, not only 4.6.0 or Windows systems.
> 
> thanks for your reminder, and could you submit a PR to fix it?

@duhenglucky 

Hello, I'm sorry I can't submit a PR, but you can modify this file to fix it. ```/broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java```
Modify the function named **createTopicInSendMessageBackMethod,createTopicInSendMessageMethod**, and add logic to check special topics.
allowing only **^ [% | a-zA-Z0-9 _-] + $**

**Comment by coffeehb** [comment]
Hello, is there a repair plan for this vulnerability?  A large number of rocketmq users are affected by this security bug. @duhenglucky

**Comment by vongosling** [comment]
@coffeehb Thanks for your report, especially for your request for a CVE ID. For some reason, we can keep a private letter for communication. According to the relevant regulations, I must close it. For the further process of the problem, please refer to the latest commits history. Thanks again for your submission:-)
