### ISSUE TITLE
How to get cosnumer mq max offset in java?

### ISSUE THREAD

**Issue by sourcesnow** [apache/rocketmq#1650]
I want to get the consumer max offset status with the purpose of checking  wether message is overstock in java.I check the source code ,just could not get the right class,can anybody help me ,please!!!

**Comment by RongtongJin** [comment]
RocketMQ-spring is not suitable for this.  If you want check consumer offset, you can use rocketmq [admin tool](http://rocketmq.apache.org/docs/cli-admin-tool/) or rocketmq [console](https://github.com/apache/rocketmq-externals/tree/master/rocketmq-console)

**Comment by RongtongJin** [comment]
Currently, rocketmq-spring only supports getting the message queue max offset or min offset before the consumer start.

**Comment by RongtongJin** [comment]
The following APIs may help you
```
consumer.fetchSubscribeMessageQueues()
consumer.getOffsetStore().readOffset();
consumer.maxOffset()
```
