### ISSUE TITLE
The stats data could be inaccurate of first minute/hour/day

### ISSUE THREAD

**Issue by xiangwangcheng** [apache/rocketmq#1656]
For a particular topic, the StatsItem won't be created and put into `statsItemTable` table until it is first used(sending message). As a result, we don't have an initial state(stats value is 0) of each snapshot list.
And since the stats data are computed by calculating the difference between the last and the first value in snapshot value, we could get wrong results at the first minute/hours/day.

Just like the picture below:
![image](https://user-images.githubusercontent.com/8049014/70962324-b2dea700-20bf-11ea-96ad-e86aae37ab93.png)

The 100 messages seem like miscounted. 

对于一个topic，只有在使用它收发消息时才会创建一个对应的StatsItem对象并放入statsItemTable中。所以，snapshot list里面没有初始化记录（统计数据为0的记录）。因为我们是将snapshot list的最后一个和第一个记录相减，像图中所示，可能出现统计数据错误。对用户来说，过去一分钟明明发了100条消息，得到的统计数据却为0。

**Comment by Aaron-He** [comment]
Before we add the first real CallSnapshot, we should initialize a snapshot with a timestamp ahead of one sampling period, values of 0, and put it in the first.
在我们添加第一次实际采样snapshot之前，应该先初始化这样一个snapshot: 它的时间戳比前者提前一个采样周期，状态值（time & value)是0，并将它放在snapshot list 的第一个位置。

**Comment by Aaron-He** [comment]
Before we add the first real CallSnapshot, we should initialize a snapshot with a timestamp ahead of one sampling period, values of 0, and put it in the first.
在我们添加第一次实际采样snapshot之前，应该先初始化这样一个snapshot: 它的时间戳比前者提前一个采样周期，状态值（time & value)是0，并将它放在snapshot list 的第一个位置。

**Comment by duhenglucky** [comment]
fixed in this [PR](https://github.com/apache/rocketmq/pull/1704)
