### ISSUE TITLE
When to implement openmessaing api version 1.0.0+

### ISSUE THREAD

**Issue by wangzhanxu** [apache/rocketmq#1664]
It's not a bug.

I want to use rocketmq in openmessaging mode. I see the openmessaing-api changed much between v0.3.1 and v1.0.0, so I wonder that when will you implement v1.0.0+ api. Thanks!

**Comment by duhenglucky** [comment]
@wangzhanxu good question, actually the community has been implemented the latest version: https://github.com/apache/rocketmq/issues/1653. could you help to review this PR and leave your comments? thanks.
