### ISSUE TITLE
queue consumer lost

### ISSUE THREAD

**Issue by fangyinhuitc** [apache/rocketmq#1668]
mq运行一段时间后，topic下的queue会有部分无法被消费，集群：2主2从，每个broker16个queue，重启能正常发送和消费，消费一段时间后，部分queue无法被消费。[http://fangyinhui.online/img/topic.png](http://fangyinhui.online/img/topic.png)

1、初步定为大概原因：有两个集群（brokera和brokerb一个集群，brokerc和brokerd一个集群）公用一个nameserver，改topic建在brokerc和brokerd上面，但是consumerGroup监听了4个broker的所有节点，org.apache.rocketmq.client.consumer.rebalance.AllocateMessageQueueAveragely#allocate 该方法返回的brokerc 只能返回前12个队列

**Comment by duhenglucky** [comment]
@fangyinhuitc 确定下有没有重复的clientId，另外最好可以提供客户端的日志来看下

**Comment by vongosling** [comment]
片段偏残缺，长时间无下文，我先关闭。如果需要协助，请发邮件列表。另外，推荐4.5.2以后的基于DLedger的多副本版本，社区做了大量优化。再次感谢你的提问：-）
