### ISSUE TITLE
configure rocketmq_client.log

### ISSUE THREAD

**Issue by tony3154** [apache/rocketmq#1670]
rocketmq-exporter没有版本号
rocketmq-4.5.2
路径无法修改/root/logs/rocketmqlogs/rocketmq_client.log
我修改了所有rocketmq的client/src/main/java/org/apache/rocketmq/client/log/ClientLogger.java中
        String clientLogRoot = System.getProperty(CLIENT_LOG_ROOT, System.getProperty("/data") + "/logs/rocketmqlogs");
重新编译，路径无效，
然后我继续修改rocketmq的client/src/main/java/org/apache/rocketmq/client/log/ClientLogger.java中两个项目
        CLIENT_USE_SLF4J = Boolean.parseBoolean(System.getProperty(CLIENT_LOG_USESLF4J, "true"));
        String clientLogRoot = System.getProperty(CLIENT_LOG_ROOT, System.getProperty("/data") + "/logs/rocketmqlogs");
重新编译后也无效
通过lsof我发现创建这个文件的是rocketmq-exporter的进程
root      28380      1  0 16:16 ?        00:00:17 java -jar /data/rocketmq-exporter/target/rocketmq-exporter-0.0.1-SNAPSHOT.jar --rocketmq.config.namesrvAddr=127.0.0.1:5432
但是我并没在他的源码中找到修改路径的地方，我不是java程序员，所以只能用路径来查找

**Comment by tony3154** [comment]
请问这个路径应该怎么修改？

**Comment by vongosling** [comment]
从现象上看，你已经修改了client可能的配置路径。试试exporter启动加上-Drocketmq.client.logRoot，如果还有问题，独立启动下exporter进程确认是否exporter导致。
