### ISSUE TITLE
how to configuration plain_acl when enable msg trace

### ISSUE THREAD

**Issue by chenyx7** [apache/rocketmq#1672]
If we need msgtrace function and acl function opened together, i need to give every account msgtrace topic sub permission, is there any way to configure the topic whitelist?

如果同时开启消息轨迹和acl鉴权功能, 需要对每个开启消息轨迹的账户都配置对应的内部topic的发布权限, 有没有topic级别的白名单配置呢

**Comment by duhenglucky** [comment]
@chenyx7 当前还没有topic维度的白名单

**Comment by zongtanghu** [comment]
Okay, I will implement this enhancement feature.

**Comment by chenyx7** [comment]
thx @duhenglucky @zongtanghu

**Comment by zongtanghu** [comment]
This enhancement feature will be released in the 4.7 version.
