### ISSUE TITLE
Why there is a pullMessageService in Producer ?

### ISSUE THREAD

**Issue by weavernet** [apache/rocketmq#1673]
I've found there is a `pullMessageService` start process when a `Producer` starts. I think the `pullMessageService` is used for pulling message from broker. It seem's like `Producer` doesn't need to pull any message from broker.
So, what does the `pullMessageService` do in `Producer`?  Thank you.

**Comment by xiangwangcheng** [comment]
You have got the answer yourself :)
The `pullMessageService` is used for pulling messages from the broker, and that is how producer exactly works. In other words, `Producer` uses `pullMessageService` to pull messages from the brokers

**Comment by weavernet** [comment]
> You have got the answer yourself :)
> The `pullMessageService` is used for pulling messages from the broker, and that is how producer exactly works. In other words, `Producer` uses `pullMessageService` to pull messages from the brokers

I think `Producer` is pushing message to `Broker`, not pulling message from `Broker`. 
If `Producer` pull message from `Broker`,  what does the broker do with the message?

**Comment by xiangwangcheng** [comment]
@weavernet  Sorry, now I get you. Both the producer and consumer have the MQClientInstance object as a property. Now the truth is either a producer of a consumer is created, A MQClientInstance attached with a pullMessageService is inited. Indeed, when it is a producer, the pullMessageService is useless. 
But if we both have consumer and producer in one process(they share one MQClientInstance instance),
the pullMessageService is used for consumer, pulling messages. 
So IMO, init a pullMessageService in MQClientInstance is a rough, simple but useful way, for it is kind of difficult to know whether the client is a producer or consumer, or both of them.
