### ISSUE TITLE
请问这种offset为负数的日志代表什么？

### ISSUE THREAD

**Issue by ntysdd** [apache/rocketmq#1675]
我们在使用过程中看到这样的日志
12-23 15:54:11 INFO BrokerControllerScheduledThread1 - Slave fall behind master: -7955368551255983524 bytes

另外有频繁的这样的警告
2019-12-23 15:54:53 WARN ConsumerManageThread_5 - [NOTIFYME]update consumer offset less than store

我们在使用过程中，发现某些TOPIC缺少rocketmq_producer_tps监控，有一台broker的rocketmq_broker_qps参数经常突然跌到很低，然后又暴涨。（这台broker所在机器使用的是SSD，内存也很大）
分析日志和查看代码都找不到问题原因。
版本是4.1

**Comment by duhenglucky** [comment]
@ntysdd 第一个问题能不能同时提供下ms的store日志，按道理slave在这种情况下应该还是在继续同步数据的，不会影响系统，如果是这样的话，可以暂时忽略这个问题。
第二个问题，一般发生在consumer group被删掉后又重新上线或者是持续的rebalance过程中，但是应该不会持续发生很多，会逐渐稳定。
第三个的话，看下store.log, storeerror.log 相关的日志是否存在问题，有没有发生锁占用很长的情况。
Issue一般用来做bug report以及feature request，所以有问题还是希望在[邮件列表](https://rocketmq.apache.org/about/contact/)里面搜索提问，邮件列表地址，所以我先关掉这个issue，有问题的话也可以再打开。
上面的日志如果涉及到一些隐私，可以加我钉钉：juicehenry。

**Comment by gaoyf** [comment]
@ntysdd  第一个问题[参考](https://blog.csdn.net/a417930422/article/details/103489994)。

**Comment by ntysdd** [comment]
感谢你的回复


gaoyf <notifications@github.com> 于2019年12月26日周四 上午11:36写道：

**Comment by ntysdd** [comment]
@duhenglucky 
明白了，我去邮件列表或者钉钉。
日志我现在还拿不到，我也不太确定以后允许不允许。

请问邮件列表我应该subscribe拿一个？users还是dev？
