### ISSUE TITLE
Does this cause concurrency issues?

### ISSUE THREAD

**Issue by fengbo4213** [apache/rocketmq#1678]
![image](https://user-images.githubusercontent.com/8640917/71476538-7ed25700-2820-11ea-9d20-997d98c2aa92.png)
定时注册Broker到NameServer时registerBrokerResultList不是线程安全的吧？虽然这个结果没有被使用，但是还是会造成困惑。

**Comment by zhangjidi2016** [comment]
If use ArrayList in multiple threads, there will be concurrency issues，a ConcurrentModificationException may occur. I will submit a PR to solve this issue later.
