### ISSUE TITLE
Default configuration, consumption fails, why is it retried every second? Retry tens of thousands of times! !! !! !!

### ISSUE THREAD

**Issue by Like-Girl** [apache/rocketmq#1679]
![20191227000351](https://user-images.githubusercontent.com/22993292/71482243-86075e00-283c-11ea-8b7c-b2b88db62e8c.png)
![20191227000431](https://user-images.githubusercontent.com/22993292/71482251-8a337b80-283c-11ea-8bd3-7ee923d0bbd1.png)

4.6.0 默认配置，消费失败，为什么会每秒重试一次？重试上万次

**Comment by duhenglucky** [comment]
@Like-Girl 是不是顺序消息？顺序消息的话，消费失败不会发回到服务端，会在本地进行重试，重试上限是Integer.Max
