### ISSUE TITLE
offsets.json and  offsets.json.bak  error

### ISSUE THREAD

**Issue by romantictravel** [apache/rocketmq#1687]
1.evn: win10  ,rocketmq client :4.5.2
  offsets.json.bak  and offsets.json  error

 
![image](https://user-images.githubusercontent.com/11863666/71566961-9ba7ac80-2af6-11ea-86c3-5947b0427b70.png)

**Comment by xiangwangcheng** [comment]
similar to #1498 , may help you.

**Comment by duhenglucky** [comment]
repeat issue, could you do more tests with UTF-8?
