### ISSUE TITLE
The latest release version(4.6.0) couldn't normally run on java 11

### ISSUE THREAD

**Issue by hpugjm** [apache/rocketmq#1688]
There seems to be something wrong with the startup configuration.I try to run RocketMQ(4.6.0) on java 11 and get the exception:
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCMSCompactAtFullCollection'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by zhshuixian** [comment]
Please Using JDK 1.8!

**Comment by duhenglucky** [comment]
@hpugjm RocketMQ indeed hasn't tested with JDK 11, would you like to pull a request to do this work?

**Comment by Aaron-He** [comment]
There are some [differences of vm options between HotSpot VM Versions](https://chriswhocodes.com/hotspot_option_differences.html).  The RocketMQ deployer  should change vm options appropriately according to the runtime environment.

**Comment by kuchaguangjie** [comment]
Latest release `4.9.0` also can't start on Java 11.
