### ISSUE TITLE
StatsItem not remove after group or topic be removed

### ISSUE THREAD

**Issue by wqliang** [apache/rocketmq#1689]
**BUG REPORT**

1. Please describe the issue you observed:
BrokerStatsThread at broker side will make some statistic on group level and topic level. After a subscription group or topic be removed, the corresponding stats item not be removed untill broker restart. 
I need to create new group frequently and each group will be removed after finish it's sonsumption task. 

The StatsItem of nonexistent group would never be removed which may cause oom.

I have already add such interface and remove StatsItem when group or topic be removed. 

Maybe create and remove a group frequently is not a good idea, but can BrokerStatsManager provide a interface to remove unused statsItem?

**Comment by zongtanghu** [comment]
This issue we can put forward a pr for this enhancement.

**Comment by zongtanghu** [comment]
@fortrueme

**Comment by zongtanghu** [comment]
> @fortrueme
