### ISSUE TITLE
All the configuration of the broker is written to broker.conf after use updateBrokerConfig command

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#1692]
**Improvement**

1. Please describe the issue you observed:
With the updateBrokerConfig command, all broker configurations are written to the configuration file specified when the broker was started. If the next time several commonly used configurations were reconfigured to start the broker, it would be inconvenient to look for the entire broker configuration in the file.

- What did you do (The steps to reproduce)?
sh mqbroker -c ../conf/broker.conf 
sh mqadmin updateBrokerConfig -k connectTimeoutMillis -v 5000 -n 10.154.0.59:9876 -b 10.154.0.59:10911
the original broker.conf
![image](https://user-images.githubusercontent.com/18254437/71703421-5abdd980-2e0f-11ea-984a-15b604c80a47.png)

- What did you expect to see?
Only the updated configuration is written to broker.conf
![image](https://user-images.githubusercontent.com/18254437/71703443-71fcc700-2e0f-11ea-956b-29f9ce49c48e.png)

- What did you see instead?
All the configuration of the broker is written to broker.conf
![image](https://user-images.githubusercontent.com/18254437/71703309-e8e59000-2e0e-11ea-8e6a-de83fb362170.png)

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zhangjidi2016** [comment]
I will implement this enhancement. @duhenglucky

**Comment by zongtanghu** [comment]
Can you put forward a pr to support updating the broker configuration partly? @zhangjidi2016

**Comment by francisoliverlee** [comment]
> This issue can assign to me and I will implement this enhancement. @duhenglucky

@zhangjidi2016 
what's config file name when starting the broker ?

**Comment by zhangjidi2016** [comment]
> > This issue can assign to me and I will implement this enhancement. @duhenglucky
> 
> @zhangjidi2016
> what's config file name when starting the broker ?

broker.conf
