### ISSUE TITLE
Whether the message trace function can be enhanced？

### ISSUE THREAD

**Issue by stateIs0** [apache/rocketmq#1708]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

enhanced msg consumer trace;

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

当前 RockeMQ client 不支持消费 ip 记录，可否在 hook 里记录更详细的 ip ？
根据我的实践，只需要在 TraceDataEncoder.Java 中添加 3 行代码即可，append clientHost 即可；然后控制台再进行解析； 

一个简单的实践：https://www.jianshu.com/p/6ef78d18076b

**Comment by duhenglucky** [comment]
@stateIs0 could you pull a request to enhance it?

**Comment by zongtanghu** [comment]
This question has been implemented by another pr before. @duhenglucky
