### ISSUE TITLE
checkTransaction一直循环回查版本4.6.0

### ISSUE THREAD

**Issue by 542928492** [apache/rocketmq#1725]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,

-生产一条消息消息一直在RMQ_SYS_TRANS_HALF_TOPIC  中 ，无法正常推送。使用arthas查看已经返回
COMMIT_MESSAGE了，但是还是一直在回查
MQ服务端4.6.0版本 namerserver 4.2.0 。

然后 我使用 MQ服务端4.5.1版本 namerserver 4.2.0 。进行测试也是出现一样的问题。

![image](https://user-images.githubusercontent.com/25193123/72338403-5cd14380-36ff-11ea-8048-4b3e924e3035.png)

![image](https://user-images.githubusercontent.com/25193123/72338115-c2710000-36fe-11ea-8707-eba65a5ac377.png)

**Comment by 542928492** [comment]
我使用的集群是mq451和mq460混合的版本。使用同一个注册中心。使用如下步骤操作，
最终是可以解决问题：
 1. 启动所有新版本 new-broker-460  
 2.迁移topic 到new-broker 
 3.关闭所有old-broker-451

**Comment by xyz327** [comment]
最终是切换到4.6.0解决的问题吗？我这边4.4.0遇到类似的问题，回查返回commit/rollback后还是会继续回查

**Comment by duhenglucky** [comment]
> 最终是切换到4.6.0解决的问题吗？我这边4.4.0遇到类似的问题，回查返回commit/rollback后还是会继续回查

建议升级，有些corner case在4.6.0之后统一修复了。
