### ISSUE TITLE
**BUG REPORT**ReqResp timeout execute N time

### ISSUE THREAD

**Issue by 2259289435** [apache/rocketmq#1727]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:
ReqResp timeout execute N time
- What did you do (The steps to reproduce)?
1. producer start request(x,callback,3000ttl)
2. timeout callback on exception execute 2 time

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:
4.6.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.
DefaultMQProducerImpl.start(){
...
this.timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                try {
                    RequestFutureTable.scanExpiredRequest();
                } catch (Throwable e) {
                    log.error("scan RequestFutureTable exception", e);
                }
            }
        }, 1000 * 3, 1000);
...
remove this code,
change to
DefaultMQProducerImpl
static {
private static final Timer timer = new Timer("RequestHouseKeepingService", true);
timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                try {
                    RequestFutureTable.scanExpiredRequest();
                } catch (Throwable e) {
                    log.error("scan RequestFutureTable exception", e);
                }
            }
        }, 1000 * 3, 1000);
}
}
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by wqliang** [comment]
@2259289435 Could you give more detail how to reproduce it ? What do you mean change `timer `to static ?

**Comment by 2259289435** [comment]
Could you give more detail how to reproduce it ?
1.producer.request(requestMessage, new RequestCallback() {
            @Override
            public void onSuccess(Message message) {
                log.info("reply body : {}", new String(message.getBody()));
            }
            
            @Override
            public void onException(Throwable e) {
                log.error("request error : {}, correlationId : {}", requestMessage.getProperty(MessageConst.PROPERTY_CORRELATION_ID), e.getMessage());
            }
        }, 3000L);
2.on timeout，onException execute 2 times。
producer.impl have timer ，producer.impl.instance.defaultmqproducer.impl have timer.

What do you mean change timer to static ?
try to fixbug

![image](https://user-images.githubusercontent.com/23507198/72674429-4afdf080-3ab1-11ea-831d-04851c200e7d.png)

**Comment by 2259289435** [comment]
> @2259289435 Could you give more detail how to reproduce it ? What do you mean change `timer `to static ?

Could you give more detail how to reproduce it ?
1.producer.request(requestMessage, new RequestCallback() {
            @Override
            public void onSuccess(Message message) {
                log.info("reply body : {}", new String(message.getBody()));
            }
            
            @Override
            public void onException(Throwable e) {
                log.error("request error : {}, correlationId : {}", requestMessage.getProperty(MessageConst.PROPERTY_CORRELATION_ID), e.getMessage());
            }
        }, 3000L);
2.on timeout，onException execute 2 times。
producer.impl have timer ，producer.impl.instance.defaultmqproducer.impl have timer.

What do you mean change timer to static ?
try to fixbug

![image](https://user-images.githubusercontent.com/23507198/72674429-4afdf080-3ab1-11ea-831d-04851c200e7d.png)

**Comment by xtechlife** [comment]
request reply调用，我也遇到很多超时的情况，使用的版本是4.6.0，这个问题是已经修复了吗？

**Comment by lialatdd** [comment]
> request reply调用，我也遇到很多超时的情况，使用的版本是4.6.0，这个问题是已经修复了吗？
4.7.1版本还有这个问题，我试着自己解决了，在RequestResponseFuture中增加AtomicBoolean类型属性markRemoved，将RequestFutureTable#scanExpiredRequest方法中的if(rep.isTimeout())替换为(rep.isTimeout() && rep.getMarkRemoved().compareAndSet(false, true))  可以解决这个问题，亲测有效

**Comment by xtechlife** [comment]
这样直接修改源码，后续升级是不是比较麻烦，你是否可以把这个方法提交给官方，获得认可后，官方把这个代码加上。

lialatdd <notifications@github.com> 于2020年10月24日周六 下午3:58写道：
