### ISSUE TITLE
about broker sends response

### ISSUE THREAD

**Issue by rushsky518** [apache/rocketmq#1728]
when broker receives a put message request, after putting the message onto disk, it directly 
calls `AbstractSendMessageProcessor#doResponse` 
in  `SendMessageProcessor#handlePutMessageResult`, 
rather than return a normal response, and send response in `NettyRemotingAbstract#processRequestCommand`
why?

**Comment by RongtongJin** [comment]
IMO, returning a normal response is ok, but the code in hook also need be changed.
