### ISSUE TITLE
There is something wrong in our website...

### ISSUE THREAD

**Issue by chendifan** [apache/rocketmq#1729]
![Image 2](https://user-images.githubusercontent.com/22953986/72597472-d4de7a00-3948-11ea-85a3-61cf670d1baf.png)

should be "SLAVE", not "SLVAE"

**Comment by RongtongJin** [comment]
Could you help submit a PR to fix this issue in [rocketmq-site repo](https://github.com/apache/rocketmq-site)?

**Comment by zhangjidi2016** [comment]
I have submitted a PR to fix the issue in [rocketmq-site repo](https://github.com/apache/rocketmq-site)， please help to review it.@RongtongJin

**Comment by RongtongJin** [comment]
merged
