### ISSUE TITLE
为甚么要拉取的消息大于内存的40%，就说消息是在磁盘上了，这个是如何做到的？

### ISSUE THREAD

**Issue by liyiwen3** [apache/rocketmq#1730]
代码在DefaultMessageStore的DefaultMessageStore的558行
`boolean isInDisk = checkInDiskByCommitOffset(offsetPy, maxOffsetPy);`

**Comment by medusar** [comment]
我之前阅读过源码，这部分有些简单的注释，可以参考一下[这里](https://github.com/medusar/rocketmq-comment/blob/3aead0098b1e63e8e22250a377aac4e3c94fed54/rocketmq-store/src/main/java/com/alibaba/rocketmq/store/DefaultMessageStore.java#L584)

**Comment by liyiwen3** [comment]
我也认为这个40%是“认为的”，如果大于40%也不一定消息是在磁盘上了。因为程序上并看不到哪里有做这样的设计。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JasonWong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月19日(星期天) 上午10:58
收件人:&nbsp;"apache/rocketmq"<rocketmq@noreply.github.com&gt;;
抄送:&nbsp;"915071628"<915071628@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/rocketmq] 为甚么要拉取的消息大于内存的40%，就说消息是在磁盘上了，这个是如何做到的？ (#1730)




我之前阅读过源码，这部分有些简单的注释，可以参考一下这里
