### ISSUE TITLE
OrderProducer send ordered message throw defaultMQProducer send order exception, not inevitable appearance

### ISSUE THREAD

**Issue by qq31715879** [apache/rocketmq#1733]
用OrderProducer发送顺序消息

偶发不是必现出现defaultMQProducer send order exception异常

且rocketmq自己有重试机制, 一共3次

又是偶发重试有的时候能重发成功, 有的三次尝试之后就彻底失败

**Comment by RongtongJin** [comment]
Could you provide some logs to find out reasons？

**Comment by qq31715879** [comment]
> Could you provide some logs to find out reasons？

because rocketmq throw new ONSClientException("defaultMQProducer send order exception", e);
we only catch Exception and print "defaultMQProducer send order exception", 
next version we reprint detailed log later, 
hope to continue to pay attention.
