### ISSUE TITLE
How to use message trace function

### ISSUE THREAD

**Issue by rushsky518** [apache/rocketmq#1744]
```` java
DefaultMQProducer(final String producerGroup, boolean enableMsgTrace)
````
````java
DefaultMQPushConsumer(final String consumerGroup, boolean enableMsgTrace)
````
When enableMsgTrace is true, the trace data is collected. But how to get the trace data?

**Comment by RongtongJin** [comment]
You can use [rocketmq-console](https://github.com/apache/rocketmq-externals/tree/master/rocketmq-console) to get trace data.
![image](https://user-images.githubusercontent.com/21963954/73176177-bcd7d900-4146-11ea-9ed8-b7479d4262d6.png)
