### ISSUE TITLE
ResetOffsetByTimeCommand supports specified queue

### ISSUE THREAD

**Issue by rushsky518** [apache/rocketmq#1745]
ResetOffsetByTimeCommand can reset offsets, and it takes effect on the whole topic for a consumer group. Is it necessary to support reset offsets for some specified queues of a topic?

**Comment by RongtongJin** [comment]
IMO some scenarios may have such requirements. Welcome to submit a PR to make a enhancement.

**Comment by rushsky518** [comment]
OK! I will submit a PR soon
