### ISSUE TITLE
单机broker是否能支持到百万的topic同时发送消息呢？

### ISSUE THREAD

**Issue by huangyinqi** [apache/rocketmq#1759]
broker单机8核，64G的情况下，目前测试2w个topic同时收发，每个topic一条消息，broker内存占用很高，进程死掉。想问下是否有能力支持到百万个topic同时收发呢

**Comment by duhenglucky** [comment]
@huangyinqi 百万级别的topic确实需要优化，跟每个topic的队列数也有关系，内存占用高并不是坏事，rocketmq会尽可能使用内存，至于进程死掉的原因要具体的查下原因。
