### ISSUE TITLE
message trace detail 消息轨迹查询报错

### ISSUE THREAD

**Issue by nonhung** [apache/rocketmq#1763]
org.apache.rocketmq.client.exception.MQClientException: CODE: 208 DESC: query message by key finished, but no message. For more information, please visit the url, http://rocketmq.apache.org/docs/faq/

解决方案？

**Comment by duhenglucky** [comment]
@nonhung https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md 参考下queryMsgByKey命令，并且保证消息轨迹功能是打开的，另外在查询的时候需要topic设置为消息轨迹的内部topic再试下，如果还不能解决或者提供下更多的信息，可以参考上面的文档。
Issue一般用来做bug report以及feature request，所以有问题还是希望在[邮件列表](https://rocketmq.apache.org/about/contact/)里面搜索提问，邮件列表地址，所以我先关掉这个issue，有问题的话也可以再打开：）。
