### ISSUE TITLE
Empty poll in haClient when it is master node

### ISSUE THREAD

**Issue by Edisonboy** [apache/rocketmq#1769]
Excuse me, i have a question in code where in the class of HaClient.
If it will be empty polling when the master broker run it?

`

        public void run() {

            log.info(this.getServiceName() + " service started");
            while (!this.isStopped()) {
                try {
                    if (this.connectMaster()) {
                            ................
                    } else {
                        this.waitForRunning(1000 * 5);
                    }
                } catch (Exception e) {
                    log.warn(this.getServiceName() + " service has exception. ", e);
                    this.waitForRunning(1000 * 5);
                }
            }

            log.info(this.getServiceName() + " service end");
        }
`

**Comment by RongtongJin** [comment]
Yep, but  it doesn't affect performance much beacuse it will sleep 5s every time.
