### ISSUE TITLE
Question about org.apache.rocketmq.store.MappedFile#destroy

### ISSUE THREAD

**Issue by kexianjun** [apache/rocketmq#1777]
When transientStorePoolEnable is set to true,the MappedFile may borrow Buffer from TransientStorePool and  assigned it to writeBuffer,but when a MappedFile is destroied,the writeBuffer is not returned to TransientStorePool,dose it necessary?

**Comment by RongtongJin** [comment]
It is not necessary to return writeBuffer. MappedFile reepresents the file on disk , writeBuffer in TransientStorePool is direct buffer to temporary writing, when all the content in writeBuffer commit to file, the writterBuffer will be returned (org.apache.rocketmq.store.MappedFile#commit). So when MappedFile is destroyed, the writeBuffer should already be returned.
