### ISSUE TITLE
修改server.contextPath后登陆请求及成功后跳转路径不会改变

### ISSUE THREAD

**Issue by yuanboy91** [apache/rocketmq#1782]
修改server.contextPath后登陆请求地址始终为/login/check.query，不会追加server.contextPath的路径；登陆成功后的跳转页面也是有此问题。

**Comment by duhenglucky** [comment]
@yuanboy91 你好，请问指是指的console么？可以到这里https://github.com/apache/rocketmq-externals去提issue。
