### ISSUE TITLE
sometimes checkLocalTransaction method not work for me？

### ISSUE THREAD

**Issue by zhutaoos** [apache/rocketmq#1789]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

i use a table store pre transaction msg , like follow image

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/26874523/75230844-5d292800-57ef-11ea-8820-e3b6c523e739.png">

but sometimes rocketmq checkLocalTransaction method do not work for me
i can see it retry query until maxRetryTimes（15）

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/26874523/75231514-88604700-57f0-11ea-8612-748fb7b981d4.png">

- What did you do (The steps to reproduce)?

- What did you expect to see?
mq should call checkLocalTransaction method ,and query transaction status,but i can not find any query log in my service.log file

- What did you see instead?

2. Please tell us about your environment:
rocketmq 4.6.0
JDK1.8

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by duhenglucky** [comment]
@zhutaoos if you committed the message during the execute the local process, rocketmq won't check back.  And if you didn't submit it but still have no check back, it would be better if you can check that there are other producers in the same group, or add some logs to help locate the issue.

**Comment by zhutaoos** [comment]
> @zhutaoos if you committed the message during the execute the local process, rocketmq won't check back. And if you didn't submit it but still have no check back, it would be better if you can check that there are other producers in the same group, or add some logs to help locate the issue.

thank for reply

i can sure just return LocalTransactionState.UNKNOW when execute the local process

we have two producer in the same group, is that mean the two producer should not in the same group?

**Comment by zhutaoos** [comment]
broker.properties 

transactionCheckInterval=500
transactionTimeOut=1000

**Comment by duhenglucky** [comment]
> > @zhutaoos if you committed the message during the execute the local process, rocketmq won't check back. And if you didn't submit it but still have no check back, it would be better if you can check that there are other producers in the same group, or add some logs to help locate the issue.
> 
> thank for reply
> 
> i can sure just return LocalTransactionState.UNKNOW when execute the local process
> 
> we have two producer in the same group, is that mean the two producer should not in the same group?

yep, in order to avoid the crash of the original producer, RocketMQ will randomly select a producer in the same group to check back, so it would better if you can check whether the check message was sent to other producers.

**Comment by duhenglucky** [comment]
@zhutaos ping
