### ISSUE TITLE
broker crashed with exception "java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code"

### ISSUE THREAD

**Issue by leonirvanel** [apache/rocketmq#1790]
**BUG REPORT**

1. Please describe the issue you observed:
    broker crashed with exception "java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code"
    
![image](https://user-images.githubusercontent.com/1066849/75317714-9f13a600-58a3-11ea-8a95-29c4c419feb6.png)

2. Please tell us about your environment:
    jdk 1.8
    rocketmq-4.5.2

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by leonirvanel** [comment]
[hs_err_pid15797.zip](https://github.com/apache/rocketmq/files/4253774/hs_err_pid15797.zip)

**Comment by leonirvanel** [comment]
[hs_err_pid15797.log](https://github.com/apache/rocketmq/files/4253783/hs_err_pid15797.log)

**Comment by duhenglucky** [comment]
@leonirvanel you can try to solve this problem by executing the os.sh script below the bin dir  and try to get the coredump file by executing ‘ulimit -c unlimited’ as prompted above.
