### ISSUE TITLE
在阿里云ECI上，消息消费异常，部分queue消息堆积无法消费

### ISSUE THREAD

**Issue by CoderLan0668** [apache/rocketmq#1791]
clientId由ip和pid组成，在阿里云ECI环境下，获取到的ip可能是ECI上的虚拟ip，而不是容器的ip，导致很多消费者实例获取到的ip是一样的，pid都是1，多个消费者实例的clientId是一样的，经过rebalance之后，所有的消费者都只能消费相同的一部分queue的消息，其他部分因为没有消费者，导致消息堆积。

**Comment by CoderLan0668** [comment]
@duhenglucky

**Comment by duhenglucky** [comment]
@CoderLan0668 可以通过两个方式来解决这个问题：
（1）通过org.apache.rocketmq.client.ClientConfig#setClientIP 这个方法来自己注入IP。
（2）可以通过org.apache.rocketmq.client.ClientConfig#setInstanceName来给每个consumer来设置特有的instance，在构建clientId的时候会用到的。

**Comment by CoderLan0668** [comment]
@duhenglucky 

更倾向从ip这里解决问题，因为在console上的consumer列表中如果看到不正确的ip会很困惑。

问题是在容器上为啥会获取到不属于这个容器的ip呢？有没有特征可以过滤？

**Comment by duhenglucky** [comment]
@CoderLan0668 当然也有同学在提pr去优化，比如说这个：https://github.com/apache/rocketmq/pull/1792，可以帮忙验证并且comment一下，大家一起来改进。
