### ISSUE TITLE
当消费一批消息时如20条，中间的第5条出现问题，直接返回ConsumeConcurrentlyStatus.RECONSUME_LATER，设置ackIndex为4后，还是会收到全部的20条消息进行重试，为什么不是收到acdIndex后面的消息？

### ISSUE THREAD

**Issue by wuqinghai** [apache/rocketmq#1815]
消费者 code:
consumer.registerMessageListener(new MessageListenerConcurrently() {
            @Override
            public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                                                            ConsumeConcurrentlyContext context) {
                System.out.println("接收新消息的线程: "+ Thread.currentThread().getName() +"，消息数: "+msgs.size());
                for (int i = 0; i < msgs.size(); i++) {
                    MessageExt ext = msgs.get(i);
                    if (i ==5) {
                        System.out.println("第"+(i)+"条消息消费失败，需要重试");
                        context.setAckIndex(i);
                        return ConsumeConcurrentlyStatus.RECONSUME_LATER;
                    }
                    System.out.println("第"+(i)+"条消息消费成功，"+ ext.getTopic()+":"+new String(ext.getBody(), Charset.forName("utf-8")));
                }
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            }
        });

分割线 ---------------------------------------------------------------------------------------------

源码中为啥要把RECONSUME_LATER情况下的，ackIndex重置为-1？这样消费者代码中的设置不就无效了？？？
org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService#processConsumeResult
switch (status) {
            case CONSUME_SUCCESS:
                if (ackIndex >= consumeRequest.getMsgs().size()) {
                    ackIndex = consumeRequest.getMsgs().size() - 1;
                }
                int ok = ackIndex + 1;
                int failed = consumeRequest.getMsgs().size() - ok;
                this.getConsumerStatsManager().incConsumeOKTPS(consumerGroup, consumeRequest.getMessageQueue().getTopic(), ok);
                this.getConsumerStatsManager().incConsumeFailedTPS(consumerGroup, consumeRequest.getMessageQueue().getTopic(), failed);
                break;
            case RECONSUME_LATER:
                ackIndex = -1;
                this.getConsumerStatsManager().incConsumeFailedTPS(consumerGroup, consumeRequest.getMessageQueue().getTopic(),
                    consumeRequest.getMsgs().size());
                break;
            default:
                break;
        }

**Comment by duhenglucky** [comment]
@wuqinghai 还是希望降低用户的使用门槛，返回一个值就够了，大部分时候，在没有消费堆积的情况下，每一批的量是很少的。
issue一般用作bug fix或者是feature request，相关的讨论最好还是在邮件列表里面，这样能够沉淀下来，而且被搜索到:)，可以订阅一下：https://rocketmq.apache.org/about/contact/
