### ISSUE TITLE
Mq Filtering tag

### ISSUE THREAD

**Issue by Su1024** [apache/rocketmq#1818]
When we send a message to MQ, the specified tag value is a dynamic value. I hope to filter out the value of a certain tag when the MQ client pulls data.

**Comment by xujianhai666** [comment]
@Su1024 so, u just specify the tag value on subsribe, there is no problem.  Even the tag value of message is diverse.

**Comment by duhenglucky** [comment]
@Su1024 RocketMQ does not support dynamic update of tag subscription information for the time being, it is necessary to strictly ensure the consistency of the same group.
