### ISSUE TITLE
如何获取MessageQueue的maxOffset

### ISSUE THREAD

**Issue by wxiaohui** [apache/rocketmq#1827]
判断是否发生消息堆积时官方例子用到了 Message.PROPERTY_MAX_OFFSET 这个常量
但是 Message 类中没有这个常量啊？

**Comment by duhenglucky** [comment]
@wxiaohui rocketmq 客户端中可以调用maxOffset方法来获取，在Message的properties里面才有这个属性。

**Comment by wxiaohui** [comment]
Thanks
