### ISSUE TITLE
an idea about the performance improvement

### ISSUE THREAD

**Issue by zhangyixin1222** [apache/rocketmq#1837]
Combine with the work practice,in my own opinion,the mq need append a function to invoke some slave mq broker to remember store the specified time span(or may be the offset) messages,which can improve the performance when some receiver need to use the message in special time or after some lag problem of the receiver.The nameserver may be use to schedule the  concrete details which is config by the user flexibly or changable or  when the laged-message receiver append to the mq.In the k8s situation ,also can combine the pods expand peculiarity when use metric tool to add new broker to pass the lagged message to the later receiver.Or can flexible change the connect after the receiver catch with latest message and shut down the redundant broker.If some problems in the design,welcome to communicate me in private.
Ulteriorly,we can separate the brokens use to receive and send the message,when the broker memory if full,the sender can change the destination broker,and the previous broker also handle the request from the receiver,when most/all of the receiver handle the messages,the broker can clear the memory and reday to receive the message in next round,when the receiver handled the message in this broker,the new connection with the newer message broker can be estiblished to consume the newer message.

**Comment by duhenglucky** [comment]
@zhangyixin1222 I thought you had some very good suggestions, and It would be nice if you can write a more detailed design and send it to the [dev](dev@rocketmq.apache.org) mailing list for the discussion.
