### ISSUE TITLE
[tools]UpdateAccessConfigSubCommand will broke the consistency of master and slave

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#1839]
**BUG REPORT**
the UpdateAccessConfigSubCommand in tools only update acl config in master broker,but if master broker offline, consumer will continue consume msgs from slave.it failed because the acl config is not update when use this command.

**Comment by duhenglucky** [comment]
@coder-zzzz Would you like to submit a PR to this repo to fix this issue？

**Comment by coder-zzzz** [comment]
> @coder-zzzz Would you like to submit a PR to this repo to fix this issue？

ok，I'will submit a pr

**Comment by yuz10** [comment]
Already fixed in #3184
