### ISSUE TITLE
producer send message to  retry topic will panic because maxReconsumeTimes is null 

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq#1843]
**BUG REPORT**

1. Please describe the issue you observed:
producer send message to retry group topic actively, but encounter panic, because maxReconsumeTimes  is null, which is set when consumer send back. 

- What did you do (The steps to reproduce)?
produer send message to %RETRY%group

- What did you expect to see?
producer should send success and consumer consume that message

- What did you see instead?
producer receive response: broker panic info 

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by xiangwangcheng** [comment]
I wonder why `maxReconsumeTimes ` is null. When the consumer consumes msg failed and sends the msg back to the broker,  `maxReconsumeTimes` should be set (default is 16).

**Comment by xujianhai666** [comment]
> I wonder why `maxReconsumeTimes ` is null. When the consumer consumes msg failed and sends the msg back to the broker, `maxReconsumeTimes` should be set (default is 16).

这个不是consumer的问题，是producer 主动发送消息到 group retry topic 的时候发生的

**Comment by yuz10** [comment]
#1844
