### ISSUE TITLE
schema support for rocketmq producer & consumer

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq#1849]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
cosumer know nothing about message when consuming, programmer just  decodes message by convention, when message changed, consumer will failed fast and may crash.  

2. Provide any additional detail on your proposed use case for this feature.
support schema descriptor info about message, producer add schema id on message, cosnumer get schema based schema id on meesage.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by xiangwangcheng** [comment]
Actually, the implementation of RMQ now is more common because it is based on bytes.  The serialization and deserialization are handed to the business layer.
But yeah, schema like pulsar can make it easier to use.

**Comment by xiangwangcheng** [comment]
BTW, rocketmq-spring offered a similar feature. You can specify a user-designed object when produce/consume msgs.

**Comment by wlliqipeng** [comment]
Apache RocketMQ has plans to support  schema in the year, which is expected to be released before August.

**Comment by wlliqipeng** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues. Issues are generally used for bug reports and feature requests, so it is recommended to discuss questions on the mailing list first, the mailing list address [https://rocketmq.apache.org/about/contact/],
