### ISSUE TITLE
message CONSUMED_BUT_FILTERED change to CONSUMED

### ISSUE THREAD

**Issue by niejian** [apache/rocketmq#1855]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
I send messge use Tag1, and then, consumer subscription the same topic use expression Tag2, and consumer didn't receive messgae and the message status change to `CONSUMED_BUT_FILTERED`. later, I change consumer tag to Tag1, console didn't display consumer log, but the message status has changed to `CONSUMED`. So I want to know how the message changed

- What did you expect to see?
console display consumer log and message status has changed to `CONSUMED`
- What did you see instead?
console didn't display consumer log, but the message status has changed to `CONSUMED`
2. Please tell us about your environment:
mac os
jdk 1.8
rocketmq：4.1.6
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
use springboot 2.1.7.

**Comment by wlliqipeng** [comment]
If the message is delivered but filtered, the status of the message is CONSUMED_BUT_FILTERED. So your observation is as expected.
