### ISSUE TITLE
Can I safely change the type of flushing disk

### ISSUE THREAD

**Issue by icearith** [apache/rocketmq#1856]
if I have a production cluster, which has already spun up for weeks and got massive message accumulated. 

is it safe to change FlushDiskType from `ASYNC_FLUSH` to `SYNC_FLUSH` with a broker reboot?

**Comment by RongtongJin** [comment]
IMO, it is safe.
Issues are generally used for bug reports and feature requests, so it is recommended to discuss on the mailing list first, the mailing list address [https://rocketmq.apache.org/about/contact/], so I will close the Issue first, but please feel free to reopen it if you have any other issues.
