### ISSUE TITLE
 Tiny error in  document about transaction message

### ISSUE THREAD

**Issue by 9526xu** [apache/rocketmq#1866]
**BUG REPORT**

Tiny error in  document about transaction message

![image](https://user-images.githubusercontent.com/15943801/76965244-ecdd7480-695e-11ea-9c0c-9d3b5b9865ee.png)

doc-en and doc-cn has same error。

fix：

`AbstractTransactionCheckListener`---->`AbstractTransactionalMessageCheckListener`

`transactionMsgTimeout`------>`transactionTimeout`

**Comment by 9526xu** [comment]
I will pull a request to fix it。

**Comment by superleo-cn** [comment]
I just submitted a PR in the following link: https://github.com/apache/rocketmq/pull/1885
