### ISSUE TITLE
Help,  failed to set filereserverdime = 720.

### ISSUE THREAD

**Issue by jinyanhui2008** [apache/rocketmq#1868]
版本号, 4.5.1, 因为有业务需求有数千万数据需要进行消费, 运算复杂特意将超时时间修改为720小时, 但是我的文件还是在72小时候被删除了, 请帮忙看看是什么原因啊.

**Comment by jinyanhui2008** [comment]
订正一下, 发现是说明文档写的有问题, 实际是 fileReservedTime, 请修复一下文档吧.

**Comment by wlliqipeng** [comment]
This parameter needs to be modified by the mqadmin tool. Any questions please go to the mailing list.
