### ISSUE TITLE
Can different Consumer instances within the same subscription group subscribe to different topic consumption

### ISSUE THREAD

**Issue by Bruce2jiang** [apache/rocketmq#1873]
Can different Consumer instances within the same subscription group subscribe to different topic consumption

**Comment by wlliqipeng** [comment]
Consumer Instances in the same consumer group can only subscribe to the same topic. If you subscribe to different topics, it will easily lead to topic confusion when reblanced.

Issues are generally used for bug reports and feature requests, so it is recommended to discuss on the mailing list first, the mailing list address [https://rocketmq.apache.org/about/contact/], so I will close the Issue first, but please feel free to reopen it if you have any other issues.
