### ISSUE TITLE
support metadata on runningInfo of client

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq#1875]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
we have some info on client, when get runningInfo, we want consumer could report that info. we use proxy for client to consume rockemtmq, with thought of python multiProcess model, we want to share consumer among python process, but if do that, we could see one ip of proxy client instead of more python client ip, so if we suuport metadata, we could report more info

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by RongtongJin** [comment]
Could you please  describe in more detail what kind of metadata needs to be reported？

**Comment by RongtongJin** [comment]
@xujianhai666 Currently, RocketMQ does not support proxy so this issue does not seem to be urgent . I will close the Issue first, but please feel free to reopen it if you have any other issues.
