### ISSUE TITLE
Broker flush when END_OF_FILE

### ISSUE THREAD

**Issue by Crearns** [apache/rocketmq#1876]
in CommitLog.java 
when `msgLen + END_FILE_MIN_BLANK_LENGTH) > maxBlank`, it will put the totalsize, magiccode to mark the blank
```java

if ((msgLen + END_FILE_MIN_BLANK_LENGTH) > maxBlank) {
                this.resetByteBuffer(this.msgStoreItemMemory, maxBlank);
                // 1 TOTALSIZE
                this.msgStoreItemMemory.putInt(maxBlank);
                // 2 MAGICCODE
                this.msgStoreItemMemory.putInt(CommitLog.BLANK_MAGIC_CODE);
                // 3 The remaining space may be any value
                // Here the length of the specially set maxBlank
                final long beginTimeMills = CommitLog.this.defaultMessageStore.now();
                byteBuffer.put(this.msgStoreItemMemory.array(), 0, maxBlank);
                return new AppendMessageResult(AppendMessageStatus.END_OF_FILE, wroteOffset, maxBlank, msgId, msgInner.getStoreTimestamp(),
                    queueOffset, CommitLog.this.defaultMessageStore.now() - beginTimeMills);
}
```

when parse the result 
```java
case END_OF_FILE:
         unlockMappedFile = mappedFile;
         // Create a new file, re-write the message
        mappedFile = this.mappedFileQueue.getLastMappedFile(0);
        if (null == mappedFile) {
        // XXX: warn and notify me
        log.error("create mapped file2 error, topic: " + msg.getTopic() + " clientAddr: " + msg.getBornHostString());
        beginTimeInLock = 0;
                return new PutMessageResult(PutMessageStatus.CREATE_MAPEDFILE_FAILED, result);
        }
        result = mappedFile.appendMessage(msg, this.appendMessageCallback);
        break;
```
it will create a new file, put the message and flush it, but the data that mark the blank will not flush, how to deal with it?

**Comment by RongtongJin** [comment]
AppendMessage method only write messages to memory (usually pagecache, but if transientStorePoolEnable is true, write to direct buffer), and other threads flush data to disk, so the data that mark the blank will be flushed finally.
In addition, issues are generally used for bug reports and feature requests, so it is recommended to discuss questions on the mailing list first, the [mailing list address] (https://rocketmq.apache.org/about/contact/), so I will close the Issue first, but please feel free to reopen it if you have any other issues.

**Comment by Crearns** [comment]
Thanks for your reply, but sorry i am newbie, I can not understand it, I retell my understanding.

when ```(msgLen + END_FILE_MIN_BLANK_LENGTH) > maxBlank```
it will mark some data to mark the blank and return an END_OF_FILE result
```java
if ((msgLen + END_FILE_MIN_BLANK_LENGTH) > maxBlank) {
                this.resetByteBuffer(this.msgStoreItemMemory, maxBlank);
                // 1 TOTALSIZE
                this.msgStoreItemMemory.putInt(maxBlank);
                // 2 MAGICCODE
                this.msgStoreItemMemory.putInt(CommitLog.BLANK_MAGIC_CODE);
                // 3 The remaining space may be any value
                // Here the length of the specially set maxBlank
                final long beginTimeMills = CommitLog.this.defaultMessageStore.now();
                byteBuffer.put(this.msgStoreItemMemory.array(), 0, maxBlank);
                return new AppendMessageResult(AppendMessageStatus.END_OF_FILE, wroteOffset, maxBlank, msgId, msgInner.getStoreTimestamp(),
                    queueOffset, CommitLog.this.defaultMessageStore.now() - beginTimeMills);
}
```
and in the switch statement

```java
case END_OF_FILE:
    unlockMappedFile = mappedFile;
    // Create a new file, re-write the message
    mappedFile = this.mappedFileQueue.getLastMappedFile(0);
    if (null == mappedFile) {
        // XXX: warn and notify me
        log.error("create mapped file2 error, topic: " + msg.getTopic() + " clientAddr: " + msg.getBornHostString());
        beginTimeInLock = 0;
        return new PutMessageResult(PutMessageStatus.CREATE_MAPEDFILE_FAILED, result);
    }
    result = mappedFile.appendMessage(msg, this.appendMessageCallback);
    break;
```
when the result is END_OF_FILE, it will call ```result = mappedFile.appendMessage(msg, this.appendMessageCallback);``` to put the message to a new file, it will return a new result and break.Still in memory so far, and it will call ```handleDiskFlush(result, putMessageResult, msg);``` to flush, but it only flush the new file data, the old data that mark the blank can not flush

Don't know if i'm right

**Comment by RongtongJin** [comment]
Hi @Crearns ,  There are some properties like flushedWhere and committedWhere at MappedFileQueue, which determine whether data has been flushed to disk.  You can take a closer look at the codes of MappedFileQueue, FlushRealTimeService, etc.

**Comment by Crearns** [comment]
OK! I will do it, thank you for your patience
