### ISSUE TITLE
StatsAllSubCommand  bug

### ISSUE THREAD

**Issue by RongNanNan** [apache/rocketmq#1880]
广播模式消费组的消息堆积数数据错误，应该是-1，却计算按照queue里的消息数量来的

**Comment by RongtongJin** [comment]
@RongNanNan Since the consume offset of broadcast mode are recorded locally and not uploaded to the broker, message‘s accumulation displayed by statsAllSubCommand is equal to the total number of messages.

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.
