### ISSUE TITLE
support ringbuffer mode for consumer 

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq#1889]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
rocketmq consmer has two mode: concurrent and orderly, but sometimes we don`t need strict order mode, for example, IM has lots of conversation on one rocketmq queue, but we just need conversation order instead of queue order to ensure each IM record is orderly, so we could seperate conversation to different thread to deal with conversation id, Espesically, we need order model for one conversaiton, we must deal with one by one and commit, so we could use ringbuffer instead of processqueue to store message and ack

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by RongtongJin** [comment]
Hi @ xujianhai666 , Could you provide a more detailed description of this PR？For example, detailed design and the issue to be solved. if the change is relatively large, you can submit a [RIP](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal).

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other ideas.
