### ISSUE TITLE
运行一段时间之后有消息堆积；把消费者重启之后就解决了

### ISSUE THREAD

**Issue by Yangjianbin** [apache/rocketmq#1890]
运行一段时间之后有消息堆积；把消费者重启之后就解决了；发现好几次了；但是找不到问题

**Comment by duhenglucky** [comment]
@Yangjianbin  确定位点是否正常提交。
另外可以看下消费线程状态
jstack -l pid > /tmp/pid.jstack，
cat /tmp/pid.jstack|grep ConsumeMessageThread -A 10 --color。

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to     reopen it if you have any other issues.
