### ISSUE TITLE
Broker can be hacked through HAService Port

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#1893]
If someone knows the master's ha service ip and port , he can disguise himself as a slave broker, then he can sync the msgs from master even through there is acl exists in master. 

 One simple way to fix it:  add iptables limit the ha port connections.
I didn't see anyword about it, So if it is the goal of rocketmq, then i think it is better to write on best_practices or somewhere else. Or it can use the acl  together.

**Comment by ShannonDing** [comment]
@zongtanghu Could you please help to check the ACL about HA service?

**Comment by ShannonDing** [comment]
link #1842

**Comment by coder-zzzz** [comment]
> link #1842

I think it is a independent issue beyond #1842 , i can use some tool to find out master's ip and port.

**Comment by zongtanghu** [comment]
@ShannonDing Okay I will review this pr next week.

**Comment by coder-zzzz** [comment]
@ShannonDing @RongtongJin @zongtanghu Hi，I think this proble is very important, could you check this asap?
