### ISSUE TITLE
Create reply message fail because property[CLUSTER] is null

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq#1901]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

Use rocketmq 4.7.0 broker to send request/reply message

link [rocketmq-spring#245](https://github.com/apache/rocketmq-spring/issues/245)
link [rocketmq-spring#243](https://github.com/apache/rocketmq-spring/issues/243)

- What did you expect to see?

send success

- What did you see instead?

CODE: 10007 DESC: create reply message fail, requestMessage error, property[CLUSTER] is null

2. Please tell us about your environment:

macos

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

how to fix : add cluster property to msgInner in asyncSendMessage method

**Comment by allankin** [comment]
@ShannonDing  my pom contains below , and it does not work ,bug still exist !!!!!!!!!!!!!!!
<dependency>
			<groupId>org.apache.rocketmq</groupId>
			<artifactId>rocketmq-spring-boot-starter</artifactId>
			<version>2.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.rocketmq</groupId>
			<artifactId>rocketmq-broker</artifactId>
			<version>4.7.1</version>
		</dependency>

**Comment by allankin** [comment]
> @ShannonDing my pom contains below , and it does not work ,bug still exist !!!!!!!!!!!!!!! can you reopen this bug pls !!
> 
> ![image](https://user-images.githubusercontent.com/1314055/99629611-401a4080-2a73-11eb-9d9b-7132fe076d44.png)
> 
> **error log:**
> 
> ReplyMessageConsumer message: hello-1605766759845
> 2020-11-19 14:26:13.407 WARN 20320 --- [essageThread_15] a.r.s.s.DefaultRocketMQListenerContainer : consume message failed. messageExt:MessageExt [brokerName=broker-a, queueId=0, storeSize=524, queueOffset=123, sysFlag=0, bornTimestamp=1605766759846, bornHost=/172.16.27.28:63121, storeTimestamp=1605767173594, storeHost=/192.168.5.87:10911, msgId=C0A8055700002A9F000000000FAB8155, commitLogOffset=262898005, bodyCRC=1356135967, reconsumeTimes=5, preparedTransactionOffset=0, toString()=Message{topic='kim-test-topic', flag=0, properties={CONSUME_START_TIME=1605767173406, TTL=3000, MIN_OFFSET=0, REAL_TOPIC=%RETRY%greeting-group, REPLY_TO_CLIENT=172.16.27.28@1752, ORIGIN_MESSAGE_ID=C0A8055700002A9F000000000FAB0A49, RETRY_TOPIC=kim-test-topic, MAX_OFFSET=124, id=65a41aff-2fec-e790-edfb-0d2fb22be6ec, UNIQ_KEY=AC101B1C06D81F89AB835FC535A60009, WAIT=false, contentType=text/plain;charset=UTF-8, DELAY=7, TAGS=greeting, timestamp=1605766759845, CORRELATION_ID=83c8c44d-88b3-49a5-b983-293c01c0070f, REAL_QID=0}, body=[104, 101, 108, 108, 111, 45, 49, 54, 48, 53, 55, 54, 54, 55, 53, 57, 56, 52, 53], transactionId='null'}], error:{}
> 
> org.apache.rocketmq.client.exception.MQClientException: CODE: 10007 DESC: create reply message fail, requestMessage error, property[CLUSTER] is null.
> For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
> at org.apache.rocketmq.client.utils.MessageUtil.createReplyMessage(MessageUtil.java:46) ~[rocketmq-client-4.7.1.jar:4.7.1]
> at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.handleMessage(DefaultRocketMQListenerContainer.java:399) ~[rocketmq-spring-boot-2.1.1.jar:2.1.1]
> at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.access$100(DefaultRocketMQListenerContainer.java:70) ~[rocketmq-spring-boot-2.1.1.jar:2.1.1]
> at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:354) ~[rocketmq-spring-boot-2.1.1.jar:2.1.1]
> at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:412) ~[rocketmq-client-4.7.1.jar:4.7.1]
> at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
> at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
> at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

@RongtongJin  could you help me ,reopen the bug or tell me how to fix it , I have no idea to fix it and feel very upset , thanks very much
