### ISSUE TITLE
Optimization for transactional message

### ISSUE THREAD

**Issue by zhenchuan9r** [apache/rocketmq#1907]
In Rocket 4.2, when commiting a transactional message, the prepared message must firstly be read from message store. However, it looks like that this process may be blocked by the disk flushing thread and significantly increase the consuming time (I have not proved it yet). It this theory is corrected, I think it is better to buffer prepared messages by another mechanism.
在rocket4.2中，提交事务消息的时候，预提交的消息需要先读取出来，但是看起来读取预提交消息的过程可能被刷盘线程阻塞并显著提高提交过程的所需时间（我还没有去证实）。如果该推测是正确的，那么采用另一种机制来缓存预提交消息是需要的。

**Comment by ShannonDing** [comment]
hello, great discussion point.
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). 
I will close the Issue first, but please feel free to reopen it if you have any other issues.
