### ISSUE TITLE
rocketmq环境隔离

### ISSUE THREAD

**Issue by gagado** [apache/rocketmq#1915]
rockemtq可以支持环境隔离的功能吗？ 类似与rabbitmq的virtual host的功能。可以在多个测试环境只用部署一套环境就可以。

**Comment by ShannonDing** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
