### ISSUE TITLE
flushResultFuture.thenCombine and SendMessageProcessor#handlePutMessageResult are invoked in GroupCommitService thread

### ISSUE THREAD

**Issue by rushsky518** [apache/rocketmq#1917]
````flushResultFuture.thenCombine```` and ````SendMessageProcessor#handlePutMessageResult```` 
are invoked in GroupCommitService thread

**Comment by duhenglucky** [comment]
@rushsky518 would you like help to review this [PR](https://github.com/apache/rocketmq/pull/1881/files) first and keep improving your work based on this?
