### ISSUE TITLE
setNamesrvAddr  the domain name

### ISSUE THREAD

**Issue by CarryLing** [apache/rocketmq#1922]
if the  DefaultMQProducer   setNamesrvAddr Method can use the domain name not the ip +port

**Comment by duhenglucky** [comment]
@CarryLing setNamesrvAddr support set with domain(xxxxx:9876).

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to     reopen it if you have any other issues.
