### ISSUE TITLE
rocketmq-logging 4.7.0 build fail

### ISSUE THREAD

**Issue by landon30** [apache/rocketmq#1925]
# 环境
- rocketmq-logging 4.7.0
- mac 10.15.4 
- jdk 1.8.0_241
- maven 3.6.3

# 问题描述
- 使用mvn -Prelease-all -DskipTests clean install -U执行编译
- 出错信息
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project rocketmq-logging: Compilation failure: Compilation failure: 
[ERROR] 不再支持源选项 6。请使用 7 或更高版本。
[ERROR] 不再支持目标选项 6。请使用 7 或更高版本。
```

# 期望编译成功

**Comment by landon30** [comment]
修正部分模块pom.xml编译版本为1.8即修复
```
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
```

**Comment by xiangwangcheng** [comment]
I tried 1.6 and there is no problem. 
But change to 1.8 is a good point.

**Comment by landon30** [comment]
> I tried 1.6 and there is no problem.
> But change to 1.8 is a good point.

应该是maven版本问题
