### ISSUE TITLE
Call doAfterRpcHooks() repeatedly in  NettyRemotingAbstract#processRequestCommand

### ISSUE THREAD

**Issue by yessimida** [apache/rocketmq#1931]
## environment
4.7.0

Call doAfterRpcHooks() repeatedly in  NettyRemotingAbstract#processRequestCommand
![image](https://user-images.githubusercontent.com/17608759/79039589-c97faf80-7c14-11ea-9342-1c77619747e8.png)

**Comment by francisoliverlee** [comment]
@yessimida do u have any idea to fix it ?
