### ISSUE TITLE
LitePullConsumer Ack

### ISSUE THREAD

**Issue by mali-nuist** [apache/rocketmq#1932]
The example code shows how to use DefaultLitePullConsumer to pull data from rocketmq:
https://github.com/apache/rocketmq/blob/8ef01a6c635f6972847c40d5540b1945180d7cbd/example/src/main/java/org/apache/rocketmq/example/simple/LitePullConsumerSubscribe.java#L35
But i noticed that unlike the push mode( return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;), there is no code to reply an ack to the rocketmq for the pull consumer. So the question is : To ensure the data are correctly pulled,  what should i do to manually reply an ack to the rockemq when using DefaultLitePullConsumer?
thanks~

**Comment by wlliqipeng** [comment]
you can reply ack  to broker by commitSync()

**Comment by wlliqipeng** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to     reopen it if you have any other issues.
