### ISSUE TITLE
By dledger, when master node changed, chedule CQ offset invalid.

### ISSUE THREAD

**Issue by Erzhoumu** [apache/rocketmq#1934]
hi, we managed the brokers by dledger  and  we found that：
when the master node is changed, the errors appear ”ERROR ScheduleMessageTimerThread - schedule CQ offset invalid.“ and the delay message will be resend by the broker.

the version of the mq is 4.5.2

**Comment by Erzhoumu** [comment]
how is it now？

**Comment by Erzhoumu** [comment]
And we found the leader node is alive, but leader node and the slave node changed, if we can modify some config to avoid the unable transfer？

**Comment by RongtongJin** [comment]
Fixed in #2518
