### ISSUE TITLE
Push Consumer doc error

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#1942]
There is some mistake about push Consumer:

## 8 推动式消费（Push Consumer）
原文如下：
Consumer消费的一种类型，该模式下Broker收到数据后会主动推送给消费端，该消费模式一般实时性较高。
## 8 Push Consumer
A type of Consumer, Under this high real-time performance mode, it will push the message to the consumer actively when the Broker receives the data.   

建议修改：
Broker不会主动推送，而是Consumer定时拉取，只是在用户层面不需要主动调用拉取方法，对用户层面来说像是broker把消息推送过来的
Recommand Modify:
Broker will not push message to consumer, instead consumers pull messages by interval 0 delay,In Users's sence, it looks like broker push message, but it dosen't

If this is a error , I'll push a pr to fix it

**Comment by coder-zzzz** [comment]
https://github.com/apache/rocketmq/pull/1944
已经提交一个Pr，但github没有关联起来，不确定是不是github延迟

**Comment by zongtanghu** [comment]
@coder-zzzz  please describe the content of issues and pr by writing English.

**Comment by coder-zzzz** [comment]
> @coder-zzzz please describe the content of issues and pr by writing English.
Done
