### ISSUE TITLE
When the number of topic queues and the number of consumers cannot be divisible, there is a tilt in the balance strategy

### ISSUE THREAD

**Issue by airbaby** [apache/rocketmq#1945]
RebalanceImpl.rebalanceByTopic();
consumer的(clientId)消费费多个topic队列时，存在排序靠前的ClientId可能消费队列较多(负载大)，是否Collections.sort()可以采用shuffle机制，确保可以随机平均；

**Comment by coder-zzzz** [comment]
AllocateMessageQueueAveragely这个策略？
按我的理解，queue=5,consumer=2，则consumer1会消费queue0-2(3个queue)，consumer2会消费queue3-4(两个queue)。不能整除的情况下，肯定会有某个consumer要多干点活

**Comment by airbaby** [comment]
AllocateMessageQueueAveragely策略，如果有n个(queue=5,consumer=2)，则会存在consumer1消费n*3个queue(queue0-2)，consumer2消费n*2个queue(queue3-4)；客户端消费单个topic无所谓，客户端消费n个topic时候干活就有可能很不平均了。

**Comment by RongtongJin** [comment]
This issue does exist. But RocketMQ rebalance needs to ensure that every consumer has the same view (ie the same order of queues and the same order of client id),  so if every consumer shuffles in its own process, it will cause inconsistency of views.

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to     reopen it if you have any other issues.
