### ISSUE TITLE
when DefaultMQProducerImpl shutdown didn't shutdown some demon thread. 

### ISSUE THREAD

**Issue by lilylei013** [apache/rocketmq#1950]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
   start a DefaultMQProducer producer , after send message , then shutdown it, but the main thread is not finish.

- What did you expect to see?
    I want all the MQ producer relative threads is finished. 
- What did you see instead?
  there is still some demon threads left there .
     RequestHouseKeepingService , and AsyncAppender-Dispatcher-Thread-3,4,6

2. Please tell us about your environment:
     windows 64bit  eclipse 
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
     for the RequestHouseKeepingService , there is because timer is not shutdown
     for the AsyncAppender-Dispatcher-Thread , I didn't found it now

**Comment by RongtongJin** [comment]
Hi @lilylei013 What version are you using? I used the latest version and there seems to be no such issue.

**Comment by lilylei013** [comment]
I checked 4.7.0 version, it's not fix. It's the timertask which is not cancel

**Comment by coder-zzzz** [comment]
I found this issue #1957  today, but didn't find this issue #1950.I already commit a pr #1958  to fix #1957

**Comment by coder-zzzz** [comment]
I think the AsyncAppender-Dispatcher-Thread is used by log, so it is usefull , can not shutdown when producer shutdown

**Comment by lilylei013** [comment]
Just cancle the timer when producer shutdown it's okay
