### ISSUE TITLE
consumer return  RECONSUME_LATER but not get retry message

### ISSUE THREAD

**Issue by garnett10330** [apache/rocketmq#1951]
![image](https://user-images.githubusercontent.com/28726464/79772896-445a7000-8363-11ea-8f76-aa5765701314.png)
![image](https://user-images.githubusercontent.com/28726464/79772979-62c06b80-8363-11ea-9173-cfee986c7af6.png)
![image](https://user-images.githubusercontent.com/28726464/79773055-82f02a80-8363-11ea-8c05-f282c7580432.png)
![image](https://user-images.githubusercontent.com/28726464/79773149-a2875300-8363-11ea-9003-b5b489c9591e.png)
![image](https://user-images.githubusercontent.com/28726464/79773625-43760e00-8364-11ea-81ea-5a0c01eace57.png)

QAQ help me Why my consumer return  RECONSUME_LATER but no  get retry message;
but same code in my friend's computer can get retry message

**Comment by RongtongJin** [comment]
Could you tell me which version you are using, it seems there is no issue with the latest version in my environment.

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.

**Comment by garnett10330** [comment]
V4_3_0 and V4_7_0 all have this question

**Comment by garnett10330** [comment]
Have any properties can control  not  retry message ?  
In my computer I try 3 version all have this question
but in my friend's computer can retry 
his computer's rocketmq   version is same as me 
why?

**Comment by spiritsx** [comment]
we encounter this question too，the rocketmq version is 4.5.1。
But when we install the version  to another server，the question goes away，interesting。

**Comment by spiritsx** [comment]
> we encounter this question too，the rocketmq version is 4.5.1。
> But when we install the version to another server，the question goes away，interesting。
> Did you slove it?

After two day later, we sloved it。
The question is about delayOffset.json。As you know，the broker process persist SCHEDULE_TOPIC_XXXX offset to delayOffset.json。When we drop the store folder，we didn't noticed it generate a store/config folder automatic by broker。Whereafter，we reset broker，but the offset from delayOffset not matched the offset from SCHEDULE_TOPIC_XXXX，so the message in SCHEDULE_TOPIC_XXXX cannot enter %RETRY% topic。

**Comment by garnett10330** [comment]
Thank for your explanation
I do not slove it
How can i do to sloved the problem
Drop store folder and Reinstall rocketMq?

**Comment by spiritsx** [comment]
No need to reinstall, just to stop broker, drop store folder, and then start broker。Actually, you can check the rocketmq log, find that are there warn log like "Offset not matched. Request offset"。The relevant logic you can find from&nbsp;ScheduleMessageService 271 line。
Wish it helpful to you&nbsp;

**Comment by joytom0591** [comment]
I just encounter this question, but I'm not sure if they are the same question: 
1、consumeGroup=ORDER-CONFIRM receive A Message TOPIC = "TDTP" key = "5279213024614400", After  consume fail, the code "return ConsumeConcurrentlyStatus.RECONSUME_LATER;", but not receive retry any more.
2、on the MQ console, use condition TOPIC = "RETRY%ORDER-CONFIRM" and key = "5279213024614400"  , can't find this message
3、on the MQ console, use condition TOPIC = "TDTP" and key = "5279213024614400", find this message, and this message was marked "CONSUMED"

before encounter this question, I upgrade rocketmq 4.1.x to 4.3.2, 
1、 I install rocketmq-4.3.2 to anther directory, 
2、 stop old  rocketmq-4.1.x 
3、move rocketmq-4.1.x/store to rocketmq-4.3.2/store(the path configured in broker-x.properties)
4、start rocketmq-4.3.2

Are they the same question?

**Comment by spiritsx** [comment]
sounds the same question, you can check the rocketmq log, find that are there warn log like "Offset not matched. Request offset".

**Comment by joytom0591** [comment]
> question

Yes, there are many log like this, and at the same time the message consume fail, the rocketmq had one log:
"storeerror.log:2021-02-06 16:26:28 WARN FlushConsumeQueueService - Offset not matched. Request offset: 354000000, firstOffset: 348000000, lastOffset: 354000000, mappedFileSize: 6000000, mappedFiles count: 1"

How to solve this problem without loss of messages (do not drop store folder),  upgrade to newest version? @spiritsx

**Comment by spiritsx** [comment]
maybe you could modify the delayOffset.json in store/config

**Comment by joytom0591** [comment]
> maybe you could modify the delayOffset.json in store/config

@spiritsx 
How to modify the delayOffset.json file? Leave it blank object like this?
{
	"offsetTable":{}
}

**Comment by spiritsx** [comment]
I think it is ok，but I suggest you can try it in no prod environment. Leveling it blank will lead to reconsume all consume failed message, it seems like a simple way to slove it if you donot care repeat consume.

**Comment by joytom0591** [comment]
> I think it is ok，but I suggest you can try it in no prod environment. Leveling it blank will lead to reconsume all consume failed message, it seems like a simple way to slove it if you donot care repeat consume.

thanks, I'll try it.
