### ISSUE TITLE
golang客户端消费者订阅时写的模式和页面客户端上显示的不一致

### ISSUE THREAD

**Issue by DandelionJR** [apache/rocketmq#1952]
我在测试rocketmq时，消费者订阅采用的是BROADCASTING，页面上却显示为CLUSTERING。我在源码中仔细查找，发现写死CLUSTERING，如下所示：
`c.consumerMap.Range(func(key, value interface{}) bool {
		consumer := value.(InnerConsumer)
		cData := consumerData{
			GroupName:         key.(string),
			CType:             "PUSH",
			MessageModel:      "CLUSTERING",
			Where:             "CONSUME_FROM_FIRST_OFFSET",
			UnitMode:          consumer.IsUnitMode(),
			SubscriptionDatas: consumer.SubscriptionDataList(),
		}
		hbData.ConsumerDatas.Add(cData)
		return true
	})`
这段代码在internal.client.go的SendHeartbeatToAllBrokerWithLock中，当我改变MessageModel的值为BROADCASTING时，页面上显示为BROADCASTING，请问这是bug还是我自己测试错误

**Comment by coder-zzzz** [comment]
You should open an issue in https://github.com/apache/rocketmq-client-go. 
Not here

**Comment by DandelionJR** [comment]
ok, thanks
