### ISSUE TITLE
Unable to access MQ service

### ISSUE THREAD

**Issue by AndyLue** [apache/rocketmq#1953]
在阿里云服务两个机子中，分别部署NAMESRV和BROKER，BROKER启动时，配置文件指定NAMESRV机子公网地址。NAMESRV机子开放HTTP协议的端口。但是一直请求不通。是因为必须是TCP协议的原因吗？？？？？我部署了一个MQCONSOLE，指定的是NAMESRV内网地址，这个CONSOLE公网访问后，可以正常发送消息

**Comment by RongtongJin** [comment]
默认情况下，nameserver的端口号是9876，用的是TCP协议。开启HTTP协议端口是无法访问的
