### ISSUE TITLE
DefaultMQProducer didn't shutdown completely

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#1957]
**BUG REPORT**
class DefaultMQProducerImpl 
when new a DefaultMQProducerImpl instance, it will create a timer to scanExpireRequest at the same time.But didn't cancle the timer when this instance is shutdown.
If somebody create a lot of producers then shutdown them, there are a lot RequestHouseKeepingService threads status TIMED_WAITING.It will cause CPU usage and other resources.
![image](https://user-images.githubusercontent.com/62043001/79953424-690f2e80-84ae-11ea-8f91-957e047c9914.png)

**Comment by RongtongJin** [comment]
It is a repeated issue. I will close this issue first. We can discusss in this [thread](https://github.com/apache/rocketmq/issues/1950).
