### ISSUE TITLE
TopicStatusSubCommand get min offset is  inaccurate

### ISSUE THREAD

**Issue by panzhi33** [apache/rocketmq#1960]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

I want to get the offset information of dead letter topic through this command，
get the details of the message and the total number of messages through offset.
but I found that the min offset is generally inaccurate, and the corresponding message cannot be obtained，because the message was deleted.by looking at the source code, the new version also has this problem

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:
CentOS RocketMQ 4.4
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by imaffe** [comment]
Does this bug apply to all topics or just the dead letter topic ?

Because I noticed when the scheduled service clears commitLogs periodically, it will actually update the minOffset in corresponding consume queues as well. 
```
        this.scheduledExecutorService.scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                DefaultMessageStore.this.cleanFilesPeriodically();
            }
        }, 1000 * 60, this.messageStoreConfig.getCleanResourceInterval(), TimeUnit.MILLISECONDS);

... 

        this.cleanCommitLogService.run();
        this.cleanConsumeQueueService.run();

```
If it turns out this bug was caused by existing logic we might just find out what's going on in previous logic.

I might get this wrong so I would appreciate much if you could provide more details on this, thanks ~

**Comment by panzhi33** [comment]
sorry，I did n’t consider the code in this place, I ’m looking at it

**Comment by imaffe** [comment]
> sorry，I did n’t consider the code in this place, I ’m looking at it

Huh no need to sorry LOL, it's ok~
