### ISSUE TITLE
how to sync the plain_acl.ymal when i execute "mqadmin updateAclConfig "?

### ISSUE THREAD

**Issue by mars-he** [apache/rocketmq#1966]
hi ,
    my rocket mq verison is 4.5.2 , and the architecture is 3m-3s ， and enable the DLedger  and acl.
   now, i execute the command  "mqadmin updateAclConfig" to modify the acl config , but this command only modify the master configure file ——plain_acl.ymal ,  the slave plain_acl.ymal is not modififed ,  so when i swithover the master to slave  ,because of the plain_acl.ymal  is not consistent    , so the user can't connect to rocketmq ..
  the question is how to sync the plain_acl.ymal when i execute "mqadmin updateAclConfig "?

**Comment by coder-zzzz** [comment]
#1839 
the same question

**Comment by ShannonDing** [comment]
Hi, @mars-he, Could you pls have a focus on @1839, this issue will be closed first. and pls feel free to reopen it if you still have other questions.
,
