### ISSUE TITLE
why clean the code in method ConsumeMessageConcurrentlyService#incCorePoolSize/decCorePoolSize

### ISSUE THREAD

**Issue by WintererOoO** [apache/rocketmq#1969]
just a question ,not a bug report

VERSION:4.7.0

DESC:
we found that `ConsumeMessageConcurrentlyService#consumeExecutor` use a nearly
infinite blocking queue,so the corePoolSize will always be `this.defaultMQPushConsumer.getConsumeThreadMin()`,is `this.defaultMQPushConsumer.getConsumeThreadMax()` a useless parameter? and we also find the method `incCorePoolSize` and `decCorePoolSize` which use to adjust corePoolSize , but it is commented out ,could you tell me why?

**Comment by ShannonDing** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
