### ISSUE TITLE
事务消息回查

### ISSUE THREAD

**Issue by xiebin2015** [apache/rocketmq#1974]
rocketmq 4.6.0的版本
在写事务消息的demo时发现几个问题，求解答
1、producer发送几条pre消息，本地事务返回unknown的情况下 ，只有部分消息进行了回查的回调
2、同一事务消息下，checkLocalTransaction模拟返回unkonw的情况下 ，没有再次进行事务消息的回查调用，默认不是15次吗？

**Comment by duhenglucky** [comment]
@xiebin2015 首先确定是不是同一个group启动了客户端；其次可以根据服务端transaction.log的日志看下是不是发送了回查请求。最好是能够提供更多的信息，来一起看下这个问题。

**Comment by xiebin2015** [comment]
你好 ，我是在一个jvm里面同时有producer和comsumer，就一个demo项目，本地事务处理模拟未决事务返回unkown，设置是10秒回查一次 ，第一次进行回查进入到check的方法了，在check方法里面也模拟未决事务返回unkown，此时没有再进行回查。transaction.log日志中也没看到有 回查的日志具体如下&nbsp;

brocker端每10秒有检查 ，但从日志上看 ，没有prepare message


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Heng Du"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午8:48
收件人:&nbsp;"apache/rocketmq"<rocketmq@noreply.github.com&gt;;
抄送:&nbsp;"一页书"<407708958@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/rocketmq] 事务消息回查 (#1974)





 
@xiebin2015 首先确定是不是同一个group启动了客户端；其次可以根据服务端transaction.log的日志看下是不是发送了回查请求。最好是能够提供更多的信息，来一起看下这个问题。

**Comment by xiebin2015** [comment]
你好 ，我补充了详细的日志信息 如下：
总共检查了两次 ，第一次是因为本地事务返回unkown进行检查回调check方法，在check方法里面继续返回unkown，确实也检查了一次 ，但是这次检查直接回滚了事务消息&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Heng Du"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午8:48
收件人:&nbsp;"apache/rocketmq"<rocketmq@noreply.github.com&gt;;
抄送:&nbsp;"一页书"<407708958@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/rocketmq] 事务消息回查 (#1974)





 
Closed #1974.

**Comment by duhenglucky** [comment]
> 总共检查了两次 ，第一次是因为本地事务返回unkown进行检查回调check方法，在check方法里面继续返回unkown，确实也检查了一次 ，但是这次检查直接回滚了事务消息&nbsp;&nbsp;

可以看下代码吗？或者使用不同group，确定一下在其他地方没有rollback的操作。

**Comment by xiebin2015** [comment]
生产者

消费者

本地事务

本地事务回查



消息生产者和消费者都在同一个项目里面，生产者和消费者都只有一个
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Heng Du"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午10:21
收件人:&nbsp;"apache/rocketmq"<rocketmq@noreply.github.com&gt;;
抄送:&nbsp;"一页书"<407708958@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/rocketmq] 事务消息回查 (#1974)





  
总共检查了两次 ，第一次是因为本地事务返回unkown进行检查回调check方法，在check方法里面继续返回unkown，确实也检查了一次 ，但是这次检查直接回滚了事务消息&nbsp;&nbsp;
  
可以看下代码吗？或者使用不同group，确定一下在其他地方没有rollback的操作。

**Comment by xiebin2015** [comment]
您好 ，我发现我修改了生产组的组名，以及topic名称之后，能达到我的预期结果了，这其中有什么关键因素吗？

**Comment by duhenglucky** [comment]
> 您好 ，我发现我修改了生产组的组名，以及topic名称之后，能达到我的预期结果了，这其中有什么关键因素吗？

使用独立的组名，避免回查到其他非事务客户端

**Comment by xiebin2015** [comment]
应该是没有重名的组名




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Heng Du"<notifications@github.com&gt;; 
发送时间: 2020年5月9日(星期六) 下午3:20
收件人: "apache/rocketmq"<rocketmq@noreply.github.com&gt;; 
抄送: "一页书"<407708958@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [apache/rocketmq] 事务消息回查 (#1974)





  
您好 ，我发现我修改了生产组的组名，以及topic名称之后，能达到我的预期结果了，这其中有什么关键因素吗？
  
使用独立的组名，避免回查到其他非事务客户端

**Comment by Garlichead** [comment]
@xiebin2015  感觉您如果可以复现之前的情况 push出transaction.log文件 这样更好分析您出现的问题了

**Comment by Garlichead** [comment]
🧐

**Comment by MnameHZJ** [comment]
我也遇到过类似的问题。分析源码后，发现其实是transientStorePoolEnable配置为true对事务消息的判断有影响。希望对你排查这个问题有帮助。
