### ISSUE TITLE
can not update messageDelay correctly with mqadmin updateBrokerConfig command

### ISSUE THREAD

**Issue by saltyx** [apache/rocketmq#1988]
example:
mqadmin updateBrokerConfig -k messageDelayLevel -v 1s 5s 10s

it always sets the messageDelayLevel to 1s

**Comment by RongtongJin** [comment]
You can try to write as this `mqadmin updateBrokerConfig -k messageDelayLevel -v '1s 5s 10s'` ?

**Comment by saltyx** [comment]
> You can try to write as this `mqadmin updateBrokerConfig -k messageDelayLevel -v '1s 5s 10s'

same result

**Comment by RongtongJin** [comment]
It is indeed a bug.

**Comment by saltyx** [comment]
> It is indeed a bug.

it is more like CommandLineParser bug

**Comment by saltyx** [comment]
> It is indeed a bug.

`$@` in `mqadmin`  script splits `'1s 5s'` into `'1s` and `5s'`, which causes the wrong subargs

the `mqadmin.cmd` works fine in the windows system
