### ISSUE TITLE
namesrv not unregister broker when update BrokerName with mqadmin updateBrokerConfig command

### ISSUE THREAD

**Issue by saltyx** [apache/rocketmq#1989]
i update broker name with mqadmin tool ,  then i found that there are 2 broker( one is before updating the name and the other is after the update)  with one address in the cluster

**Comment by RongtongJin** [comment]
Can you describe your issue in more detail? I can not understand it.

**Comment by saltyx** [comment]
> Can you describe your issue in more detail? I can not understand it.

是这样的。
原先这个mq cluster有两个broker，一主一从，broker-a, broker-a-1

我用 mqadmin updateBrokerConfig -bxxxxx -k brokerName -vbroker-a 修改了从节点 Broker的名称。

然后，我发现rocketmq-console的cluster页面上有三个broker，分别为broker-a,broker-a,broker-a-1，其中两个的broker addr是一样的。

我用arthas工具看了下RouteInfoManager#getAllClusterInfo的结果，发现clusterAddrTable变量mqcluster对应了三个broker

**Comment by RongtongJin** [comment]
> > Can you describe your issue in more detail? I can not understand it.
> 
> 是这样的。
> 原先这个mq cluster有两个broker，一主一从，broker-a, broker-a-1
> 
> 我用 mqadmin updateBrokerConfig -bxxxxx -k brokerName -vbroker-a 修改了从节点 Broker的名称。
> 
> 然后，我发现rocketmq-console的cluster页面上有三个broker，分别为broker-a,broker-a,broker-a-1，其中两个的broker addr是一样的。
> 
> 我用arthas工具看了下RouteInfoManager#getAllClusterInfo的结果，发现clusterAddrTable变量mqcluster对应了三个broker

确实存在这样的问题。更改brokerName之后，RouteInfoManager之前的brokerName信息并没有删除。欢迎提交PR来解决这个问题，比如可以通过ip:port来删除旧信息。

**Comment by saltyx** [comment]
#2001 提交了哈

**Comment by lebron374** [comment]
> RouteInfoManager#getAllClusterInfo

想请教下arthas怎么查看非静态方法的

**Comment by saltyx** [comment]
> > RouteInfoManager#getAllClusterInfo
> 
> 想请教下arthas怎么查看非静态方法的

[我用的是这个watch的方法](https://alibaba.github.io/arthas/watch.html)

**Comment by lebron374** [comment]
> > > RouteInfoManager#getAllClusterInfo
> > 
> > 
> > 想请教下arthas怎么查看非静态方法的
> 
> [我用的是这个watch的方法](https://alibaba.github.io/arthas/watch.html)

ok,如果这么说我就懂了，我发现watch org.apache.rocketmq.namesrv.routeinfo.RouteInfoManager getAllClusterInfo 'target' 这种就可以看到当前对象里面的属性
