### ISSUE TITLE
AbstractSendMessageProcessor.java doesn't need to implement NettyRequestProcessor

### ISSUE THREAD

**Issue by shendongsd** [apache/rocketmq#2013]
'AbstractSendMessageProcessor extends AsyncNettyRequestProcessor' and 'AsyncNettyRequestProcessor  implements NettyRequestProcessor' , so I think AbstractSendMessageProcessor doesn't need to implement NettyRequestProcessor
![image](https://user-images.githubusercontent.com/23067207/82321108-e757e580-9a06-11ea-9eac-ed59502e56e7.png)
![image](https://user-images.githubusercontent.com/23067207/82321502-8086fc00-9a07-11ea-9a70-beb1f7127caa.png)

**Comment by imaffe** [comment]
https://softwareengineering.stackexchange.com/questions/316445/should-i-implement-same-interface-in-derived-class  ，IMO，not sure what is the coding style guide here, probably there are other places which also used this style, we might just keep it as it is since it does no harm to the code.
