### ISSUE TITLE
Apache RocketMQ 4.7.0 support master-slave switching?

### ISSUE THREAD

**Issue by dlliuy** [apache/rocketmq#2022]
RocketMQ v4.7.0 support master-slave switching?

**Comment by RongtongJin** [comment]
You can refer to [dledger mode](https://github.com/apache/rocketmq/tree/master/docs/cn/dledger). In addition, issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to     reopen it if you have any other issues.
