### ISSUE TITLE
rocketmq 消息消费延时问题

### ISSUE THREAD

**Issue by xiebin2015** [apache/rocketmq#2031]
您好，我用的rokcetmq4.6.0，在使用过程中会出现消息延迟消费的问题
说明：
   生产者通过异步的方式发送一条消息，回调打印消息发送成功的日志信息，但是消费端要间隔比较长的时间才进行消费，间隔时间有时候甚至间隔几个小时，往能帮忙解答，万分感谢

**Comment by coder-zzzz** [comment]
你可以通过mqadmin查看consumer是否连接正常，或者通过命令行直接发送一条消息测试测试

**Comment by lebron374** [comment]
可以通过mqadmin追踪下消息的写入和消费时间，确认是不是本身消费端的问题

**Comment by duhenglucky** [comment]
@xiebin2015 除了上面两位同学的意见，看下consumer有多少在线，是否有订阅信息不一致的情况。
