### ISSUE TITLE
doAfterResponse double executed for NettyRequestProcessor???

### ISSUE THREAD

**Issue by lgrui1988** [apache/rocketmq#2045]
Hi, I a freshmen in Github and I am not quite sure how to raise up an issue or a potential issue.
[https://github.com/apache/rocketmq/blob/master/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java](url) line:229
`NettyRequestProcessor processor = pair.getObject1();
                            RemotingCommand response = processor.processRequest(ctx, cmd);
                           doAfterRpcHooks(RemotingHelper.parseChannelRemoteAddr(ctx.channel()), cmd, response);
                            callback.callback(response);`

For NettyRequestProcessor, the method, doAfterRpcHooks(), will be executed the second time in callback.

It may not have any practical impact and i am just wondering if that part is intended or a typo or something.

**Comment by lizhiboo** [comment]
> Hi, I a freshmen in Github and I am not quite sure how to raise up an issue or a potential issue.
> [https://github.com/apache/rocketmq/blob/master/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java](url) line:229
> `NettyRequestProcessor processor = pair.getObject1(); RemotingCommand response = processor.processRequest(ctx, cmd); doAfterRpcHooks(RemotingHelper.parseChannelRemoteAddr(ctx.channel()), cmd, response); callback.callback(response);`
> 
> For NettyRequestProcessor, the method, doAfterRpcHooks(), will be executed the second time in callback.
> 
> It may not have any practical impact and i am just wondering if that part is intended or a typo or something.

I agree with you, customer's rpc callback would be called twice, it makes something wrong.

**Comment by francisoliverlee** [comment]
@lizhiboo duplicate with https://github.com/apache/rocketmq/issues/1931

**Comment by lizhiboo** [comment]
> @lizhiboo do u have any idea to fix it ?
> duplicate with #1931

sure, glad to do it.

**Comment by francisoliverlee** [comment]
@lizhiboo when finished it , reply with PR id

**Comment by lizhiboo** [comment]
> @lizhiboo when finished it , reply with PR id

done, PR id #2057
