### ISSUE TITLE
selectOneMessageQueue must select lastFailBroker

### ISSUE THREAD

**Issue by HaoTianZhao** [apache/rocketmq#2046]
branch 4.7.0
class MQFaultStrategy
row 68
if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
it should be:
if (null == lastBrokerName || !mq.getBrokerName().equals(lastBrokerName))

**Comment by HaoTianZhao** [comment]
selectOneMessageQueue must select lastFailBroker

**Comment by lizhiboo** [comment]
> branch 4.7.0
> class MQFaultStrategy
> row 68
> if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
> it should be:
> if (null == lastBrokerName || !mq.getBrokerName().equals(lastBrokerName))

As you say, if lastBrokerName is null, it will select one MessageQueue, assuming MessageQueue-a. If it occurs some exception while producing to MessageQueue-a, it will always select MessageQueue-a since then. Can you submit a pr to fix it?

**Comment by HaoTianZhao** [comment]
> > branch 4.7.0
> > class MQFaultStrategy
> > row 68
> > if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
> > it should be:
> > if (null == lastBrokerName || !mq.getBrokerName().equals(lastBrokerName))
> 
> As you say, if lastBrokerName is null, it will select one MessageQueue, assuming MessageQueue-a. If it occurs some exception while producing to MessageQueue-a, it will always select MessageQueue-a since then. Can you submit a pr to fix it?

of course

**Comment by ifplusor** [comment]
Same as #1576

**Comment by ifplusor** [comment]
See #1607

**Comment by ifplusor** [comment]
```latencyFaultTolerance.isAvailable(mq.getBrokerName())``` has checked the availability of the mq. ```null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName)``` is redundant, and cause a bug.
