### ISSUE TITLE
pull方式消费，应用集群、mq集群如何管理offset

### ISSUE THREAD

**Issue by githubyangxd** [apache/rocketmq#2049]
pull模式，应用集群，mq集群，怎么处理offset比较好，初步了解到使用RemoteBrokerOffsetStore，但是疑惑存储在本地的偏移量，因为应用是集群环境导致“各个本地”存储的offset乱套了。

**Comment by lizhiboo** [comment]
> pull模式，应用集群，mq集群，怎么处理offset比较好，初步了解到使用RemoteBrokerOffsetStore，但是疑惑存储在本地的偏移量，因为应用是集群环境导致“各个本地”存储的offset乱套了。

Use LocalFileOffsetStore or RemoteBrokerOffsetStore depends on consumer's MessageModel. If BROADCASTING, use LocalFileOffsetStore, if CLUSTERING, use RemoteBrokerOffsetStore.

**Comment by githubyangxd** [comment]
和网上云云一样，回答不到点上

**Comment by githubyangxd** [comment]
是否有案例，不需要分布式锁吗

**Comment by githubyangxd** [comment]
> 
> 
> > pull模式，应用集群，mq集群，怎么处理offset比较好，初步了解到使用RemoteBrokerOffsetStore，但是疑惑存储在本地的偏移量，因为应用是集群环境导致“各个本地”存储的offset乱套了。
> 
> Use LocalFileOffsetStore or RemoteBrokerOffsetStore depends on consumer's MessageModel. If BROADCASTING, use LocalFileOffsetStore, if CLUSTERING, use RemoteBrokerOffsetStore.

是否有案例，不需要分布式锁吗
