### ISSUE TITLE
建议新增特殊主题及特殊权限的消息用于实现对broker配置信息的集体变更与维护

### ISSUE THREAD

**Issue by zhangyixin1222** [apache/rocketmq#2051]
通过新增具有特殊权限及特殊主题的消息以实现灵活变更nameserver/broker的对消息生产/消费的acl权限的灵活变更问题及其他各类broker/nameserver配置信息的变更，broker/nameserver在收到此类特殊消息后根据消息内容结合集群间的内部通信实现配置信息的变更，避免多机器下相关配置变更的频繁手工操作，可将配置信息记录到nameserver机器对应的文件或客户配置的db中，并以此实现新增broker配置相关配置信息从运行集群中自动同步，以及通过特殊权限通过访问nameserver而获取到集群的所有配置信息

**Comment by vongosling** [comment]
This is a great suggestion for meta configuration. In fact, the community has discussed the in this rip(https://github.com/apache/rocketmq/wiki/RIP-18-Metadata-management-architecture-upgrade).
