### ISSUE TITLE
any good practice to deal with multi test environment in RocketMq

### ISSUE THREAD

**Issue by lebron374** [apache/rocketmq#2052]
in our company，use rocketMq to process message，but sometimes we need message only consume in particular server。

we modify the consume rebalance policy to let one server to consume all messages。
but i want know any best practice in community？

**Comment by lizhiboo** [comment]
> in our company，use rocketMq to process message，but sometimes we need message only consume in particular server。
> 
> we modify the consume rebalance policy to let one server to consume all messages。
> but i want know any best practice in community？

Try to use the following method, business layer make sure only the particular server start consume task by using a lock.
`        consumer.setMessageModel(MessageModel.BROADCASTING);
`

**Comment by Jaskey** [comment]
1.The most convenient way would be:  set up different rocketmq broker cluster with separate name  server cluster for different test env

2.Another way could be use the same cluster , but set up a env flag to your topic, while your consumer or producer start to work, always use the topic of that test env.
