### ISSUE TITLE
Rocketmq 4.7.0 import eclipse ch.qos.logback.classic.joran.JoranConfigurator file does not support

### ISSUE THREAD

**Issue by lovegang** [apache/rocketmq#2063]
![image](https://user-images.githubusercontent.com/35051600/83425689-a3ca9600-a460-11ea-81b5-05d510ac6592.png)

logback-classic pom  The version of the file that needs to be upgraded is a little higher 

Such as 1.2.3

**Comment by RongtongJin** [comment]
@lovegang It is welcomed to submit a PR to upgrade the version of logback.
