### ISSUE TITLE
org.apache.rocketmq.client.impl.factory.MQClientInstance#LOCK_TIMEOUT_MILLIS is too small

### ISSUE THREAD

**Issue by manfrid** [apache/rocketmq#2068]
我的程序启动的时候，线程很多，都发message。
获取TopicRouteInfo的时候，在执行到
org.apache.rocketmq.client.impl.factory.MQClientInstance#updateTopicRouteInfoFromNameServer(java.lang.String, boolean, org.apache.rocketmq.client.producer.DefaultMQProducer)
的时候，都去排队等待获取TopicRouteInfo。很多会获取锁超时

能否灵活的这个参数设置成可以设置的

![image](https://user-images.githubusercontent.com/4531962/83611461-93770000-a5b3-11ea-9142-a85fd6891a6b.png)

**Comment by imaffe** [comment]
This parameter is defined as static final and hardcoded in source code in TopicConfigManager. Would be nice if you wish to help making this timeout configurable. 
However we are not sure if this aligns with our current configuration diagram. If we currently don't support configure XXXManager, we might need to create a RIP to update all the hard-coded configuration to stay consistent.
