### ISSUE TITLE
请问bin文件夹中的sh命令的参数解释在文档哪里啊？比如-n代表什么意思

### ISSUE THREAD

**Issue by startjava** [apache/rocketmq#2076]
我在官方文档中没有找到，请给URL！感谢！

**Comment by ifplusor** [comment]
https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md

**Comment by yejiahao** [comment]
**Thanks**

**Comment by yejiahao** [comment]
> https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md

**Thanks**
