### ISSUE TITLE
rocketmq java client可以在日志中输出执行的命令吗？？

### ISSUE THREAD

**Issue by startjava** [apache/rocketmq#2077]
rocketmq java client可以在日志中输出执行的命令吗？？

**Comment by duhenglucky** [comment]
@startjava 暂时不可以，不知道您说的指令是不是指所有的Request请求之类的，这个量有点大，不过可以通过RPCHook进行扩展。

**Comment by startjava** [comment]
这个场景还是比较常用啊，，大多数学习MQ的人基本不怎么学习sh的使用，上来基本就是用java client api进行开发，常常需要查看java client api执行后对应的sh命令啊，，使java代码和sh有对应的关系。

**Comment by ifplusor** [comment]
不使用mqadmin不会有对应sh命令。admin也可以看MQAdmin相关的参数定义，-h也可以输出帮助信息
