### ISSUE TITLE
HmacSHA1 not avaliable when use openjdk

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#2078]
`Caused by: org.apache.rocketmq.acl.common.AclException: [10015:signature-failed] unable to calculate a request signature. error=Algorithm HmacSHA1 not available
`
There is an error when use openjdk-1.8.0, because there is no jre dir under $JAVA_HOME when install by yum or other tools.

So it will better to add $JAVA_HOME/lib/ext to the runbroker.sh

**Comment by duhenglucky** [comment]
@coder-zzzz would you like submit a PR to polish it?

**Comment by coder-zzzz** [comment]
> @coder-zzzz would you like to submit a PR to polish it?
ok

**Comment by ShannonDing** [comment]
close due to PR merged.
