### ISSUE TITLE
Message should better support empty property

### ISSUE THREAD

**Issue by binzhaomobile** [apache/rocketmq#2079]
In Message#putUserProperty, emply property value is not allowed. If an empty value is set, QocketMQ will throw IllegalArgumentException"The name or value of property can not be null or blank string!"
In some cases, empty value makes business sense. Empty property shoud better be supported.

Source Code:
public void putUserProperty(String name, String value) {
    if (MessageConst.STRING_HASH_SET.contains(name)) {
        throw new RuntimeException(String.format("The Property<%s> is used by system, input another please", name));
    } else if (value != null && !value.trim().isEmpty() && name != null && !name.trim().isEmpty()) {
        this.putProperty(name, value);
    } else {
        throw new IllegalArgumentException("The name or value of property can not be null or blank string!");
    }
}

**Comment by lizhiboo** [comment]
Developer should carefully conduct value , if Null value allowed. It maybe cause NPE and other exceptions. The loss outweights the gain. Developer can use special string in business layer to support this case.
