### ISSUE TITLE
StringBuffer or StringBuilder

### ISSUE THREAD

**Issue by yejiahao** [apache/rocketmq#2082]
I have seen the source code
**NamespaceUtil#wrapNamespace**
```java
public static String wrapNamespace(String namespace, String resourceWithOutNamespace) {
	// ...
	StringBuffer strBuffer = new StringBuffer();

	if (isRetryTopic(resourceWithOutNamespace)) {
		strBuffer.append(MixAll.RETRY_GROUP_TOPIC_PREFIX);
	}

	if (isDLQTopic(resourceWithOutNamespace)) {
		strBuffer.append(MixAll.DLQ_GROUP_TOPIC_PREFIX);
	}

	return strBuffer.append(namespace).append(NAMESPACE_SEPARATOR).append(resourceWithoutRetryAndDLQ).toString();

}
```
Maybe use ```StringBuilder``` is better because I think it is local variable level and obj doesn't "escape" from this method.

Feel free to reply for studying, thanks.

**Comment by lizhiboo** [comment]
> I have seen the source code
> **NamespaceUtil#wrapNamespace**
> 
> ```java
> public static String wrapNamespace(String namespace, String resourceWithOutNamespace) {
> 	// ...
> 	StringBuffer strBuffer = new StringBuffer();
> 
> 	if (isRetryTopic(resourceWithOutNamespace)) {
> 		strBuffer.append(MixAll.RETRY_GROUP_TOPIC_PREFIX);
> 	}
> 
> 	if (isDLQTopic(resourceWithOutNamespace)) {
> 		strBuffer.append(MixAll.DLQ_GROUP_TOPIC_PREFIX);
> 	}
> 
> 	return strBuffer.append(namespace).append(NAMESPACE_SEPARATOR).append(resourceWithoutRetryAndDLQ).toString();
> 
> }
> ```
> 
> Maybe use `StringBuilder` is better because I think it is local variable level and obj doesn't "escape" from this method.
> 
> Feel free to reply for studying, thanks.

yep, StringBuilder performs better in this case.

**Comment by RosaDreaming** [comment]
> > I have seen the source code
> > **NamespaceUtil#wrapNamespace**
> > ```java
> > public static String wrapNamespace(String namespace, String resourceWithOutNamespace) {
> > 	// ...
> > 	StringBuffer strBuffer = new StringBuffer();
> > 
> > 	if (isRetryTopic(resourceWithOutNamespace)) {
> > 		strBuffer.append(MixAll.RETRY_GROUP_TOPIC_PREFIX);
> > 	}
> > 
> > 	if (isDLQTopic(resourceWithOutNamespace)) {
> > 		strBuffer.append(MixAll.DLQ_GROUP_TOPIC_PREFIX);
> > 	}
> > 
> > 	return strBuffer.append(namespace).append(NAMESPACE_SEPARATOR).append(resourceWithoutRetryAndDLQ).toString();
> > 
> > }
> > ```
> > 
> > 
> > Maybe use `StringBuilder` is better because I think it is local variable level and obj doesn't "escape" from this method.
> > Feel free to reply for studying, thanks.
> 
> yep, StringBuilder performs better in this case.

i can create a new pr to solve this problem.

**Comment by lebron374** [comment]
> > > I have seen the source code
> > > **NamespaceUtil#wrapNamespace**
> > > ```java
> > > public static String wrapNamespace(String namespace, String resourceWithOutNamespace) {
> > > 	// ...
> > > 	StringBuffer strBuffer = new StringBuffer();
> > > 
> > > 	if (isRetryTopic(resourceWithOutNamespace)) {
> > > 		strBuffer.append(MixAll.RETRY_GROUP_TOPIC_PREFIX);
> > > 	}
> > > 
> > > 	if (isDLQTopic(resourceWithOutNamespace)) {
> > > 		strBuffer.append(MixAll.DLQ_GROUP_TOPIC_PREFIX);
> > > 	}
> > > 
> > > 	return strBuffer.append(namespace).append(NAMESPACE_SEPARATOR).append(resourceWithoutRetryAndDLQ).toString();
> > > 
> > > }
> > > ```
> > > 
> > > 
> > > Maybe use `StringBuilder` is better because I think it is local variable level and obj doesn't "escape" from this method.
> > > Feel free to reply for studying, thanks.
> > 
> > 
> > yep, StringBuilder performs better in this case.
> 
> i can create a new pr to solve this problem.

good job
