### ISSUE TITLE
Support graceful shutdown for push consumer

### ISSUE THREAD

**Issue by Jaskey** [apache/rocketmq#2085]
**FEATURE REQUEST**

For now, RocketMQ does not support a graceful shutdown for push consumer, which means that when a user shutdown a push consumer, the threadpool will shutdown but rocketmq client will not wait for the existing task to be completed, which may cause

1. Error is found when shutdown. Since the application since application may shutdown some external source like datasource when application shutdowns, so the existing task may fail.

2. Message duplication. Even though the task can be completed, since rocketmq will update consumer offset after the shutdown method returns, so the latest consumer offset should be updated after the remaining tasks are completed

A feature to let user to shutdown consumer gracefully will help to build a more stable application!

**Comment by ShannonDing** [comment]
close due to PR merged.
