### ISSUE TITLE
rocketmq client's stats of RT does not make sense

### ISSUE THREAD

**Issue by Jaskey** [apache/rocketmq#2088]
**BUG REPORT**

### What did you do (The steps to reproduce)?
Start a cousumer, and continue to consume message, after one minute, check the client log.

### Please describe the issue you observed:

For RT, we care about average RT and max RT in a sampling period. 

But now we will see current log :

```
[CONSUME_RT] [topic_xxxx@xxxx-consumer] Stats In One Minute, SUM: 256807 TPS: 4280.12 AVGPT: 812.68
```

The value TPS does not make any sense. And neither for the the value 4280.12. In the current logic, tps is the sum_value/time_period.

The AVGPT make no sense eight, the value 812.68 should be called the avg rt
```
    private static StatsSnapshot computeStatsData(final LinkedList<CallSnapshot> csList) {
        StatsSnapshot statsSnapshot = new StatsSnapshot();
        synchronized (csList) {
            double tps = 0;
            double avgpt = 0;
            long sum = 0;
            if (!csList.isEmpty()) {
                CallSnapshot first = csList.getFirst();
                CallSnapshot last = csList.getLast();
                sum = last.getValue() - first.getValue();
                tps = (sum * 1000.0d) / (last.getTimestamp() - first.getTimestamp());

                long timesDiff = last.getTimes() - first.getTimes();
                if (timesDiff > 0) {
                    avgpt = (sum * 1.0d) / timesDiff;
                }
            }

            statsSnapshot.setSum(sum);
            statsSnapshot.setTps(tps);
            statsSnapshot.setAvgpt(avgpt);
        }

        return statsSnapshot;
    }
```
### What did you expect to see?

 For RT, we should care about sum_value/count_period. And the text should be AVG_RT , and MAX_RT rather than TPS and AVGPT

**Comment by imaffe** [comment]
Would you be interested in submitting a PR to enhance this (add new metrics, rename some metrics) ? Thanks~

**Comment by Jaskey** [comment]
@ShannonDing @imaffe please help review the pr https://github.com/apache/rocketmq/pull/2103
