### ISSUE TITLE
one consumer group subscribe multiple topic, some messages not consumed

### ISSUE THREAD

**Issue by henrypoter** [apache/rocketmq#2089]
1. Please describe the issue you observed:

I have a consumer group, it include 3 instances,  it subscribes 3 topics using CLUSTER mode, each topic have 16 queues.
I expect the consumer group consumes all the messages in the 3 topics.
When I check the  consumer of each topic, I find that some queues have not assigned to the consumers.
It seems that the consumer group should be unique in broker level. 

2. Please tell us about your environment:
4.6.0 dleager mode cluster

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by ShannonDing** [comment]
The subscription relationship must be consistent among all consumers in the consumer group.

**Comment by lebron374** [comment]
please check subscription in all topic exist in all broker

**Comment by henrypoter** [comment]
> The subscription relationship must be consistent among all consumers in the consumer group.

Do you mean only support one consumer group subscribes one topic ?
Don't support one consumer group subscribes three topics at the same time ?

**Comment by ShannonDing** [comment]
The first thing you should be aware of is that different Consumer Group can consume the same topic independently, and each of them will have their own consuming offsets. Of course, the consumers in the same consumer group can also consume multiple topics at the same time. Please make sure each Consumer within the same Group to subscribe to the same topics.

**Comment by henrypoter** [comment]
I got it.

Thanks
