### ISSUE TITLE
It seems like that the images on the document were all hung up

### ISSUE THREAD

**Issue by JOJO0527** [apache/rocketmq#2096]
Sry, I can not upload the images which were hung up
Would u plz help me fix the problems about the images on document? 
WHICH is really important for me to realize the  design thoughtof Rocketmq.

**Comment by imaffe** [comment]
Hi, could you please provide more information like which files/document were not working properly, or give use a link/links to the error page?  Thanks so much!

**Comment by RongtongJin** [comment]
@JOJO0527 You can git clone the project and read document locally.
