### ISSUE TITLE
send message with empty Body cause NullPointerException

### ISSUE THREAD

**Issue by wangshaojie4039** [apache/rocketmq#2102]
**BUG REPORT**

1. when client receive empty body message from broker,consumeService throw NullPointerException

![image](https://user-images.githubusercontent.com/22910636/84847630-2029bf80-b084-11ea-983b-66ae88b62c6f.png)

**Comment by imaffe** [comment]
Hi, can you please provide more information on how to reproduce this problem, including

- which version rocketmq-client/rocketmq you are using (because we need to locate which line caused the problem, but different version has different line numbers)
- ...

Thanks so much and we will follow up~

**Comment by wangshaojie4039** [comment]
> Hi, can you please provide more information on how to reproduce this problem, including
> 
> * which version rocketmq-client/rocketmq you are using (because we need to locate which line caused the problem, but different version has different line numbers)
> * ...
> 
> Thanks so much and we will follow up~

rocketmq version is 4.5.1

**Comment by zongtanghu** [comment]
I think it's necessary to add the empty Body limination logical codes for messages on broker. @ShannonDing @wangshaojie4039 @RongtongJin

**Comment by coder-zzzz** [comment]
IMO,empty body should be allowed, sometimes mq just used to notify clients about sth change with no message.
I think should fix the client's problem instead of add limit on broker

**Comment by Jaskey** [comment]
@wangshaojie4039  how do you produce this message to producer? Since the producer api should check if the body is null

**Comment by coder-zzzz** [comment]
@Jaskey maybe he use other client instead of java client

**Comment by zongtanghu** [comment]
@Jaskey  In java sdk of rocketmq, it check the message body exactly.But our members use other language rocektmq sdk, such as rocektmq-go sdk. I also put forward a issue. https://github.com/apache/rocketmq-client-go/issues/501

**Comment by Jaskey** [comment]
@zongtanghu Thx, would you please help to review the bug fix pr https://github.com/apache/rocketmq/pull/2104 ?
