### ISSUE TITLE
Can not understand the documentation

### ISSUE THREAD

**Issue by startjava** [apache/rocketmq#2107]
消费者在向Master拉取消息时，Master服务器会根据拉取偏移量与最大偏移量的距离（判断是否读老消息，产生读I/O），以及从服务器是否可读等因素建议下一次是从Master还是Slave拉取。

---------------------------
是什么考虑下，建议下一次是从Master还是Slave拉取，，这个没有看懂，感谢指点。

**Comment by imaffe** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to     reopen it if you have any other issues.
