### ISSUE TITLE
LitePullConsumerSubscribe testcase not work [4.6.0]

### ISSUE THREAD

**Issue by henrypoter** [apache/rocketmq#2110]
**BUG REPORT**

1. Please describe the issue you observed:
 
I run the example below, but it doesn't work when the consumer group subscribe the topic the first time(I mean the consumer group have never consumed the topic). The consumer can not consume any message, include old messages and new messages.

 testcase file:
https://github.com/apache/rocketmq/blob/rocketmq-all-4.6.0/example/src/main/java/org/apache/rocketmq/example/simple/LitePullConsumerSubscribe.java

If the consumer group have consumed some messages before , (may be consumed by DefaultPushConsumer), then the testcase works.

2. Please tell us about your environment:
rocketmq 4.6.0

**Comment by RongtongJin** [comment]
Can you try if the same issue still exists in the latest version ？

**Comment by henrypoter** [comment]
4.7.0  still not work
