### ISSUE TITLE
RocketMQ Support Protobuf and GRPC

### ISSUE THREAD

**Issue by zongtanghu** [apache/rocketmq#2113]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Now, RocketMQ don't support Protobuf and GPRC.But, If RocketMQ supports protobuf and GPRC, there are at least some advantages as below:
(1).Protocol Buffers is platform-neutral, extensible mechanism for serializing structured data.It can provide more performance serialize/deserialize remoting communication data than some json lib. 
(2).GPRC is a kind of A high-performance, open-source universal RPC framework.If rocketmq support gprc, it can help to intergrate with other opensource system, such nacos, seata, and others.

2. Provide any additional detail on your proposed use case for this feature.
(1)Support protobuf in rpc remoting module.
(2)Support GPRC in rpc remoting module.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zongtanghu** [comment]
I think supporting protobuf and GPRC is much more important.We can discuss together. @vongosling @duhenglucky @RongtongJin @xujianhai666 @wenfengwang @zhouxinyu @xiangwangcheng

**Comment by vongosling** [comment]
@zongtanghu This feature changes a lot and is more suitable for RIP. I will close it first and look forward to seeing the new RIP proposal :-)
