### ISSUE TITLE
Asynchronous master-slave replication problem

### ISSUE THREAD

**Issue by c1ayton** [apache/rocketmq#2114]
The document says synchronize double write slave will not automatically switch to master.
Can slave asynchronously copy automatically become master after master down.
Whether the continued consumption will also continue to produce

**Comment by lebron374** [comment]
in master-slave cluster model，master/slave will not automatically，you can refer https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md

in Dledger cluster model，you can ref
https://github.com/apache/rocketmq/blob/master/docs/cn/dledger/deploy_guide.md

**Comment by c1ayton** [comment]
> in master-slave cluster model，master/slave will not automatically，you can refer https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
> 
> in Dledger cluster model，you can ref
> https://github.com/apache/rocketmq/blob/master/docs/cn/dledger/deploy_guide.md
https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md 
If this link is deployed asynchronously, can Slave continue to produce and consume when master goes down
