### ISSUE TITLE
mqadmin should provide subscriptionGroup check command

### ISSUE THREAD

**Issue by lebron374** [apache/rocketmq#2120]
mqadmin should provide subscriptionGroup check command

we meet some problem that some broker message can't be consume because subscription not exist in broker

so i think we need mqadmin to provide this function

**Comment by duhenglucky** [comment]
@lebron374 you can use updateSubGroup command to update or create the subscription, but maybe topicList -c(Listed subscription) command will give more help in this case.

**Comment by lebron374** [comment]
> @lebron374 you can use updateSubGroup command to update or create the subscription, but maybe topicList -c(Listed subscription) command will give more help in this case.

topicList only can help to provider topic info
but in my case we just need subscription.
