### ISSUE TITLE
To support the versioned message routing

### ISSUE THREAD

**Issue by yanglifan** [apache/rocketmq#2123]
In the test environment, messages of one topic may have different versions. And consumers of this topic are same too, also have different versions. And the message should be send to the consumer which has the same version.

**e.g., the message v1 of the topic A should be send to the consumer v1 if it existed in some of consumer groups, or any consumer can process the versioned message if there is no versioned consumer of some consumer groups.**

We already has an internal mechanism to support this requirement based on the message selection/allocation, but I hope to have a discussion to create a common solve this issue.

**Comment by lizhiboo** [comment]
IMO, implements this feature would modify producer's route and consumer's rebalance mechanism. Consumer holds a partition by rebalance. Let versioned consumer consume the corresponding versioned message,  producer will produce versioned message to specific versioned partition. Besides, consumer should hold its specific versioned partition.

**Comment by yanglifan** [comment]
@lizhiboo currently RMQ producer's and consumer's routing mechanism are both based on the client side extension (`MessageQueueSelector`/`AllocateMessageQueueStrategy`). So the versioned message routing can be also implemented in the same way. But the downside is that producers and consumers have to be configured in the same approach, so routing in the broker side may be a good choice to support the feature like the versioned message routing.

**Comment by lizhiboo** [comment]
> @lizhiboo currently RMQ producer's and consumer's routing mechanism are both based on the client side extension (`MessageQueueSelector`/`AllocateMessageQueueStrategy`). So the versioned message routing can be also implemented in the same way. But the downside is that producers and consumers have to be configured in the same approach, so routing in the broker side may be a good choice to support the feature like the versioned message routing.

I agree with u, moving rebalance mechanism to broker is a good choice. Client will be light.
