### ISSUE TITLE
When will version 4.7.1 be officially released?

### ISSUE THREAD

**Issue by andyhewenhui** [apache/rocketmq#2125]
When will version 4.7.1 be officially released? Because [ISSUE-1950] has a great impact on us, we hope to release 4.7.1 ASAP。What day is it exactly?

**Comment by RongtongJin** [comment]
Tomorrow. Voting has ended.

**Comment by andyhewenhui** [comment]
https://mvnrepository.com/   
It hasn't been updated yet.

**Comment by RongtongJin** [comment]
> https://mvnrepository.com/
> It hasn't been updated yet.

It can now be obtained from the maven repository.
