### ISSUE TITLE
LitePullConsumer not work

### ISSUE THREAD

**Issue by henrypoter** [apache/rocketmq#2127]
The LitePullConsumer can not poll any messages from broker, if we set the messageQueueListener before poll() .

**Comment by duhenglucky** [comment]
@henrypoter would you like to provide more information(logs, env, etc.) about this issue？Did you turn off the automatic creation of topics and subscriptions? If yes, did you manually create it first?

**Comment by henrypoter** [comment]
> @henrypoter would you like to provide more information(logs, env, etc.) about this issue？Did you turn off the automatic creation of topics and subscriptions? If yes, did you manually create it first?

I have turn off the automatic creation of topics, and I created the topic manually.  I confirmed that the consumer group have been created automaticly. The subscription  state is ok.

It may be the offset table is empty caused the issue. 

## env
broker 4.6.0 dleger mode
client 4.6.0,4.6.1,4.7.0 

## broker log when running the litePullConsumer 

`
==> broker.log <==
2020-06-30 10:49:44 INFO HeartbeatThread_3 - auto create a subscription group, SubscriptionGroupConfig [groupName=middleware-topic1-dr-group, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2020-06-30 10:49:44 INFO HeartbeatThread_3 - create new topic TopicConfig [topicName=%RETRY%middleware-topic1-dr-group, readQueueNums=1, writeQueueNums=1, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2020-06-30 10:49:44 INFO brokerOutApi_thread_3 - register broker[0]to name server 192.168.11.182:9876 OK
2020-06-30 10:49:44 INFO brokerOutApi_thread_4 - register broker[0]to name server 192.168.11.181:9876 OK
2020-06-30 10:49:44 INFO brokerOutApi_thread_2 - register broker[0]to name server 192.168.11.180:9876 OK
2020-06-30 10:49:44 INFO HeartbeatThread_3 - new consumer connected, group: middleware-topic1-dr-group CONSUME_ACTIVELY CLUSTERING channel: ClientChannelInfo [channel=[id: 0x6f069b95, L:/192.168.11.181:30911 - R:/192.168.11.123:58139], clientId=10.88.0.50@23332, language=JAVA, version=335, lastUpdateTimestamp=1593485384567]
2020-06-30 10:49:44 INFO HeartbeatThread_3 - subscription changed, add new topic, group: middleware-topic1-dr-group SubscriptionData [classFilterMode=false, topic=middleware-topic, subString=*, tagsSet=[], codeSet=[], subVersion=1593485358956, expressionType=TAG]
2020-06-30 10:49:44 INFO HeartbeatThread_3 - registerConsumer info changed ConsumerData [groupName=middleware-topic1-dr-group, consumeType=CONSUME_ACTIVELY, messageModel=CLUSTERING, consumeFromWhere=CONSUME_FROM_LAST_OFFSET, unitMode=false, subscriptionDataSet=[SubscriptionData [classFilterMode=false, topic=middleware-topic, subString=*, tagsSet=[], codeSet=[], subVersion=1593485358956, expressionType=TAG]]] 192.168.11.123:58139`

##The litePullConsumer can not poll any messages, there are some messages in the topic:

`List<MessageExt> messageExts = litePullConsumer.poll(30000);`
                    
##The litePullConsumer offset table is empty:
` OffsetStore offsetStore = litePullConsumer.getOffsetStore();
Map<MessageQueue, Long>  queueOffsetMap =  offsetStore.cloneOffsetTable(topic);`

## if is use the push consumer with the same consumer group name subscribe the topic, it consumes normally.
Then I kill the push consumer, run the litePullConsumer again, it works.

**Comment by henrypoter** [comment]
[1.log](https://github.com/apache/rocketmq/files/4851265/1.log)

**Comment by lebron374** [comment]
@henrypoter when you first run litePullConsumer, do you check the file conf/subscriptionGroup.json.
maybe subscriptionGroup not exist will not consume message

**Comment by henrypoter** [comment]
> @henrypoter when you first run litePullConsumer, do you check the file config/subscriptionGroup.json.
> maybe subscriptionGroup not exist will not consume message

subscriptionGroup exist.

` "middleware-topic1-dr-group":{
                        "brokerId":0,
                        "consumeBroadcastEnable":true,
                        "consumeEnable":true,
                        "consumeFromMinEnable":true,
                        "groupName":"middleware-topic1-dr-group",
                        "notifyConsumerIdsChangedEnable":true,
                        "retryMaxTimes":16,
                        "retryQueueNums":1,
                        "whichBrokerWhenConsumeSlowly":1
  }`

**Comment by henrypoter** [comment]
Testcase to reproduce the problem 
[LitePullConsumerSubscribe3.java.txt](https://github.com/apache/rocketmq/files/4856365/LitePullConsumerSubscribe3.java.txt)


When we call litePullConsumer.setMessageQueueListener(mql)  the consumer cannot poll( ) messages from broker.

**Comment by lebron374** [comment]
> Testcase to reproduce the problem
> [LitePullConsumerSubscribe3.java.txt](https://github.com/apache/rocketmq/files/4856365/LitePullConsumerSubscribe3.java.txt)
> 
> When we call litePullConsumer.setMessageQueueListener(mql) the consumer cannot poll( ) messages from broker.

3q for provide consumer code, if you can provide topic info , i can try to debug .

**Comment by lebron374** [comment]
> litePullConsumer

litePullConsumer.start() should after litePullConsumer.setMessageQueueListener(mql)???

**Comment by henrypoter** [comment]
> > litePullConsumer
> 
> litePullConsumer.start() should after litePullConsumer.setMessageQueueListener(mql)???

Both not work

**Comment by lebron374** [comment]
> > > litePullConsumer
> > 
> > 
> > litePullConsumer.start() should after litePullConsumer.setMessageQueueListener(mql)???
> 
> Both not work.
> Below is the workaround:
> `consumer.subscribe(topic, "*"); consumer.start(); consumer.poll(); consumer.setMessageQueueListener(mql);`

@Override
        public void messageQueueChanged(String topic, Set<MessageQueue> mqAll, Set<MessageQueue> mqDivided) {
            MessageModel messageModel = defaultLitePullConsumer.getMessageModel();
            switch (messageModel) {
                case BROADCASTING:
                    updateAssignedMessageQueue(topic, mqAll);
                    updatePullTask(topic, mqAll);
                    break;
                case CLUSTERING:
                    updateAssignedMessageQueue(topic, mqDivided);
                    updatePullTask(topic, mqDivided);
                    break;
                default:
                    break;
            }
        }

**Comment by lebron374** [comment]
> > > litePullConsumer
> > 
> > 
> > litePullConsumer.start() should after litePullConsumer.setMessageQueueListener(mql)???
> 
> Both not work.
> Below is the workaround:
> `consumer.subscribe(topic, "*"); consumer.start(); consumer.poll(); consumer.setMessageQueueListener(mql);`

```
org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl.MessageQueueListenerImpl

    class MessageQueueListenerImpl implements MessageQueueListener {
        @Override
        public void messageQueueChanged(String topic, Set<MessageQueue> mqAll, Set<MessageQueue> mqDivided) {
            MessageModel messageModel = defaultLitePullConsumer.getMessageModel();
            switch (messageModel) {
                case BROADCASTING:
                    updateAssignedMessageQueue(topic, mqAll);
                    updatePullTask(topic, mqAll);
                    break;
                case CLUSTERING:
                    updateAssignedMessageQueue(topic, mqDivided);
                    updatePullTask(topic, mqDivided);
                    break;
                default:
                    break;
            }
        }
    }
```

**Comment by henrypoter** [comment]
> > > > litePullConsumer
> > > 
> > > 
> > > litePullConsumer.start() should after litePullConsumer.setMessageQueueListener(mql)???
> > 
> > 
> > Both not work.
> > Below is the workaround:
> > `consumer.subscribe(topic, "*"); consumer.start(); consumer.poll(); consumer.setMessageQueueListener(mql);`
> 
> the default MessageQueueListenerImpl like this,can you find some difference
> 
> ```
> org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl.MessageQueueListenerImpl
> 
>     class MessageQueueListenerImpl implements MessageQueueListener {
>         @Override
>         public void messageQueueChanged(String topic, Set<MessageQueue> mqAll, Set<MessageQueue> mqDivided) {
>             MessageModel messageModel = defaultLitePullConsumer.getMessageModel();
>             switch (messageModel) {
>                 case BROADCASTING:
>                     updateAssignedMessageQueue(topic, mqAll);
>                     updatePullTask(topic, mqAll);
>                     break;
>                 case CLUSTERING:
>                     updateAssignedMessageQueue(topic, mqDivided);
>                     updatePullTask(topic, mqDivided);
>                     break;
>                 default:
>                     break;
>             }
>         }
>     }
> ```

I custom the MessageQueueListener to monitor the consumer rebalance and reset offset of queues by myself.
From the client code, the consumer will will use the default MessageQueueListenerImpl.
```
 public synchronized void subscribe(String topic, String subExpression) throws MQClientException {
        try {
            if (topic == null || topic.equals("")) {
                throw new IllegalArgumentException("Topic can not be null or empty.");
            }
            setSubscriptionType(SubscriptionType.SUBSCRIBE);
            SubscriptionData subscriptionData = FilterAPI.buildSubscriptionData(defaultLitePullConsumer.getConsumerGroup(),
                topic, subExpression);
            this.rebalanceImpl.getSubscriptionInner().put(topic, subscriptionData);
            this.defaultLitePullConsumer.setMessageQueueListener(new MessageQueueListenerImpl());
            assignedMessageQueue.setRebalanceImpl(this.rebalanceImpl);
            if (serviceState == ServiceState.RUNNING) {
                this.mQClientFactory.sendHeartbeatToAllBrokerWithLock();
                updateTopicSubscribeInfoWhenSubscriptionChanged();
            }
        } catch (Exception e) {
            throw new MQClientException("subscribe exception", e);
        }
    }
```

**Comment by lebron374** [comment]
in your example,with you own define MessageQueueListener, may be you consumer will not get any MessageQueue。

just some tips for help

```
try {
            MessageQueueListener mql = new MessageQueueListener() {
                @Override
                public void messageQueueChanged(String topic, Set<MessageQueue> mqAll, Set<MessageQueue> mqDivided) {
                    System.out.printf("=============messageQueueChanged topic:%s q:%s %n",topic,JSON.toJSONString(mqDivided));

                    System.out.printf("queue assigned to consumer[%s] are: %n", litePullConsumer.getInstanceName());
                    for(MessageQueue q: mqDivided){
                        System.out.printf("%d ",q.getQueueId());
                    }
                    System.out.printf("%nmqAll:%s %n",JSON.toJSONString(mqAll));
                    //litePullConsumer.assign(mqDivided);
                }
            };
            //当设置了messageQueueListener后，可能再也收不到消息了。。
            //不设置messageQueueListener，可以正常收消息
            //litePullConsumer.setMessageQueueListener(mql);
}
```

**Comment by duhenglucky** [comment]
> Testcase to reproduce the problem
> [LitePullConsumerSubscribe3.java.txt](https://github.com/apache/rocketmq/files/4856365/LitePullConsumerSubscribe3.java.txt)
> 
> When we call litePullConsumer.setMessageQueueListener(mql) the consumer cannot poll( ) messages from broker.

Thanks for your details about this issue, and I read your code listed above, Rocketmq's subscribe() mode does not support custom MessageQueueListener, because in subscribe mode, pull consumer will automatically do load balancing. If you change this, it will not work. If you don't want rocketmq to manage load balancing, assign() mode will be a better choice.

But this setMessageQueueListener() is really best to be hidden from users, are you willing to submit a PR to optimize it?

**Comment by henrypoter** [comment]
> > Testcase to reproduce the problem
> > [LitePullConsumerSubscribe3.java.txt](https://github.com/apache/rocketmq/files/4856365/LitePullConsumerSubscribe3.java.txt)
> > When we call litePullConsumer.setMessageQueueListener(mql) the consumer cannot poll( ) messages from broker.
> 
> Thanks for your details about this issue, and I read your code listed above, Rocketmq's subscribe() mode does not support custom MessageQueueListener, because in subscribe mode, pull consumer will automatically do load balancing. If you change this, it will not work. If you don't want rocketmq to manage load balancing, assign() mode will be a better choice.
> 
> But this setMessageQueueListener() is really best to be hidden from users, are you willing to submit a PR to optimize it?

I think the MessageQueueListener should be expose to the application developer.
I don't want to manage queue rebalance, but I want to know the queue rebalance event.
