### ISSUE TITLE
Rocketmq client supports the reactive API based on Reactor . the feature of reactor has planned support?

### ISSUE THREAD

**Issue by bxvs888** [apache/rocketmq#2131]
see title.

**Comment by francisoliverlee** [comment]
what 's reactive API , restful api or rpc api ?

**Comment by vongosling** [comment]
Frankly speaking, we have no such intention. If you have some actual business concerns, open a discussion on the Dev mailing list. What benefit does that for your business? Maybe there are a handful of voices in the community.

**Comment by ShawshankLin** [comment]
@francisoliverlee @vongosling https://github.com/reactor/reactor-kafka
