### ISSUE TITLE
rocketmq-all-4.7.1-bin-release may has a memory-leak BUG

### ISSUE THREAD

**Issue by telephone6** [apache/rocketmq#2135]
when I run the command 'sh broker' of rocketmq-all-4.7.1-bin-release/bin, I find the memory usage is more and more bigger.A moments later ,the console shows ：

Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 805306368, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 805306368 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/luoxw/rocketmq-all-4.7.1-bin-release/bin/hs_err_pid3509.log

But the version 4.3.2 of RocketMQ has no such problem.
So the latest version of RocketMQ may has something wrong with a memory-leak BUG.
Hope to find and solve it quickly if u can see the issue.

**Comment by lizhiboo** [comment]
> when I run the command 'sh broker' of rocketmq-all-4.7.1-bin-release/bin, I find the memory usage is more and more bigger.A moments later ,the console shows ：
> 
> Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 805306368, 0) failed; error='Cannot allocate memory' (errno=12)
> 
> # There is insufficient memory for the Java Runtime Environment to continue.
> # Native memory allocation (mmap) failed to map 805306368 bytes for committing reserved memory.
> # An error report file with more information is saved as:
> # /home/luoxw/rocketmq-all-4.7.1-bin-release/bin/hs_err_pid3509.log
> But the version 4.3.2 of RocketMQ has no such problem.
> So the latest version of RocketMQ may has something wrong with a memory-leak BUG.
> Hope to find and solve it quickly if u can see the issue.

Running environment is windows or *nux? Is the broker or namesrv OOM? Do you get some hints from heap dump?

**Comment by telephone6** [comment]
> Running environment is windows or *nux? Is the broker or namesrv OOM? Do you get some hints from heap dump?

Thanks for your reply.Running in CentOS 7.4_x64.The namesrv is in a normal running.
![image](https://user-images.githubusercontent.com/36781346/86535334-2dfb9380-bf12-11ea-9735-77acd3f3f885.png)
I retried to running it and get some info from dump.

"VM Arguments:
jvm_args: -Xms8g -Xmx8g -Xmn4g -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -verbose:gc -Xloggc:/dev/shm/rmq_broker_gc_%p_%t.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=15g -XX:-UseLargePages -XX:-UseBiasedLocking -Djava.ext.dirs=/usr/local/java/jdk1.8.0_181/jre/lib/ext:/home/luoxw/rocketmq-all-4.7.1-bin-release/bin/../lib:/usr/local/java/jdk1.8.0_181/lib/ext
java_command: org.apache.rocketmq.broker.BrokerStartup
java_class_path (initial): .:/home/luoxw/rocketmq-all-4.7.1-bin-release/bin/../conf:.:%JAVA_HOME%/lib/dt.jar:%JAVA_HOME%/lib/tools.jar
Launcher Type: SUN_STANDARD"

I think the memory which I allocated is only 8G is the cause of the problem.It may not has enough memory to run the Broker.But older version don't need such a big memory.And here has some unnormal from dump.Maybe the unknown thread use a lot of Memory.
"
Current thread (0x00007f8390008f50):  JavaThread "Unknown thread" [_thread_in_vm, id=17296, stack(0x00007f8399d5b000,0x00007f8399e5b000)]

Stack: [0x00007f8399d5b000,0x00007f8399e5b000],  sp=0x00007f8399e58e10,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xad21aa]  VMError::report_and_die()+0x2ba
V  [libjvm.so+0x5022db]  report_vm_out_of_memory(char const*, int, unsigned long, VMErrorType, char const*)+0x8b
V  [libjvm.so+0x92fe33]  os::Linux::commit_memory_impl(char*, unsigned long, bool)+0x123
V  [libjvm.so+0x92ffa5]  os::pd_commit_memory_or_exit(char*, unsigned long, unsigned long, bool, char const*)+0x35
V  [libjvm.so+0x927ca6]  os::commit_memory_or_exit(char*, unsigned long, unsigned long, bool, char const*)+0x26
V  [libjvm.so+0x5ca13f]  G1PageBasedVirtualSpace::commit_internal(unsigned long, unsigned long)+0xbf
V  [libjvm.so+0x5ca3cc]  G1PageBasedVirtualSpace::commit(unsigned long, unsigned long)+0x11c
V  [libjvm.so+0x5cd0b0]  G1RegionsLargerThanCommitSizeMapper::commit_regions(unsigned int, unsigned long)+0x40
V  [libjvm.so+0x631047]  HeapRegionManager::commit_regions(unsigned int, unsigned long)+0x77
V  [libjvm.so+0x6322e1]  HeapRegionManager::make_regions_available(unsigned int, unsigned int)+0x31
V  [libjvm.so+0x632860]  HeapRegionManager::expand_by(unsigned int)+0xb0
V  [libjvm.so+0x5a12b9]  G1CollectedHeap::expand(unsigned long)+0x199
V  [libjvm.so+0x5a75b5]  G1CollectedHeap::initialize()+0x895
V  [libjvm.so+0xa9a1e3]  Universe::initialize_heap()+0xf3
V  [libjvm.so+0xa9a74e]  universe_init()+0x3e
V  [libjvm.so+0x644875]  init_globals()+0x65
V  [libjvm.so+0xa7eefe]  Threads::create_vm(JavaVMInitArgs*, bool*)+0x23e
V  [libjvm.so+0x6d8d74]  JNI_CreateJavaVM+0x74
C  [libjli.so+0x797e]  JavaMain+0x9e
C  [libpthread.so.0+0x7e25]  start_thread+0xc5


---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )

Other Threads:

=>0x00007f8390008f50 (exited) JavaThread "Unknown thread" [_thread_in_vm, id=17296, stack(0x00007f8399d5b000,0x00007f8399e5b000)]

VM state:not at safepoint (not fully initialized)
"
