### ISSUE TITLE
Why DefaultMQPushConsumerImpl#start() is synchronized,but DefaultMQProducerImpl#start() is not  synchronized?

### ISSUE THREAD

**Issue by xujian01** [apache/rocketmq#2137]
Why DefaultMQPushConsumerImpl#start() is synchronized,but DefaultMQProducerImpl#start() is not  synchronized?

Please!!!

**Comment by imaffe** [comment]
Since there is no direct documentation about this,I would assume DefaultMQProducerImpl#start() should be synchronized.

**Comment by francisoliverlee** [comment]
a producer can send messages for all topics in the cluster. mostly ONE producer enough, but there can be a lot of CONSUMERs to consuming topics. thread-safe-start or non-thread-safe-start must be thought. synchronize-start or non-synchronize-start is so import for them.

**Comment by xujian01** [comment]
> Since there is no direct documentation about this,I would assume DefaultMQProducerImpl#start() should be synchronized.

thanks
