### ISSUE TITLE
error:CODE: 14  DESC: service not available now, maybe disk full, CL:  0.92 CQ:  0.92 INDEX:  0.92, maybe your broker machine memory too small. For more information, please visit the url, http://rocketmq.apache.org/docs/faq/

### ISSUE THREAD

**Issue by cielswift** [apache/rocketmq#2138]
240g disk 20g remaining 
How to modify?
Can be used normally

**Comment by imaffe** [comment]
It seems that your disk is out of space. Usually for performance considerations we wouldn't allow the disk usage goes beyond 90% (actually we would suffer significant performance loss once the disk usage is above 60%, depends on your disk type). One workaround is using a more aggressive compaction/retention policy so your disk gets cleaned up more often.

**Comment by cielswift** [comment]
Is this a design mistake? Only one half of a hard drive is allowed to use it?
