### ISSUE TITLE
Is it possible for rocketmq to delete commitlog randomly

### ISSUE THREAD

**Issue by lajiaox** [apache/rocketmq#2141]
I just noticed that the message could not be consumed. because one of the commitlog is missing. What is the reason?

the commitlog file has three file

        // 1   00000000104152956928
        // 2   00000000105226698752
        // 3   00000000106300440576

the second file （00000000105226698752）is deleted，but I don't know who delete it？

The message could not be consumed, If I delete the first or third or delete all file, I can consume

We don't delete files artificially，The phenomenon before this problem occurs is that the server load is too high

So does rocketmq delete it？

**Comment by lebron374** [comment]
the commitLog delete policy base on your retain time.will not delete randomly.

**Comment by lajiaox** [comment]
> the commitLog delete policy base on your retain time.will not delete randomly.

But the fact is that it has been deleted. What I mainly mean is not random deletion, but why it was deleted

**Comment by imaffe** [comment]
Hello, we need more information  for us to investigate why it was deleted. Usually commitLog will only be deleted automatically by the compaction/retention mechanism. It might be possible that someone deleted the second file by mistake, and you can verify this by Linux auditing tools (like find out the commands executed, other logging info). If it is not human error then we might  you need to reproduce this bug before we can dig further into it.

**Comment by lajiaox** [comment]
> Hello, we need more information for us to investigate why it was deleted. Usually commitLog will only be deleted automatically by the compaction/retention mechanism. It might be possible that someone deleted the second file by mistake, and you can verify this by Linux auditing tools (like find out the commands executed, other logging info). If it is not human error then we might need you to reproduce this bug before we can dig further into it.

We don't delete it artificially. Is it when the system load is high? The jar version we used is 1.2.2.2, which is older
