### ISSUE TITLE
rocketmq4.7.1双主双从broker-b发送消息返回状态码全是 SLAVE_NOT_AVAILABLE, broker-a完全没有问题

### ISSUE THREAD

**Issue by zhangyangx** [apache/rocketmq#2143]
SendResult [sendStatus=SEND_OK, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C244C0000, offsetMsgId=C0A83A8000002A9F000000000000BBEA, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-a, queueId=3], queueOffset=55]
SendResult [sendStatus=SLAVE_NOT_AVAILABLE, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C245D0001, offsetMsgId=C0A83A8200002A9F0000000000008E89, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-b, queueId=0], queueOffset=42]
SendResult [sendStatus=SLAVE_NOT_AVAILABLE, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C246F0002, offsetMsgId=C0A83A8200002A9F0000000000008F6C, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-b, queueId=1], queueOffset=39]
SendResult [sendStatus=SLAVE_NOT_AVAILABLE, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C24750003, offsetMsgId=C0A83A8200002A9F000000000000904F, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-b, queueId=2], queueOffset=38]
SendResult [sendStatus=SLAVE_NOT_AVAILABLE, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C24780004, offsetMsgId=C0A83A8200002A9F0000000000009132, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-b, queueId=3], queueOffset=42]
SendResult [sendStatus=SEND_OK, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C247A0005, offsetMsgId=C0A83A8000002A9F000000000000BCCD, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-a, queueId=0], queueOffset=53]
SendResult [sendStatus=SEND_OK, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C247D0006, offsetMsgId=C0A83A8000002A9F000000000000BDB0, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-a, queueId=1], queueOffset=50]
SendResult [sendStatus=SEND_OK, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C24810007, offsetMsgId=C0A83A8000002A9F000000000000BE93, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-a, queueId=2], queueOffset=50]
SendResult [sendStatus=SEND_OK, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C24840008, offsetMsgId=C0A83A8000002A9F000000000000BF76, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-a, queueId=3], queueOffset=56]
SendResult [sendStatus=SLAVE_NOT_AVAILABLE, msgId=24098A620124F2C09C116C7CA0E63739025418B4AAC2273C24870009, offsetMsgId=C0A83A8200002A9F0000000000009215, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-b, queueId=0], queueOffset=43]

**Comment by zhangyangx** [comment]
![image](https://user-images.githubusercontent.com/48794630/86887775-a8533000-c12b-11ea-8848-a495b0462602.png)

**Comment by xiangwangcheng** [comment]
Could you please paste more infos like boker's configuration, broker's log?
Is there sync or async mode between master and slave? Are u sure that slave is running correctly?

**Comment by imaffe** [comment]
Hi, It seems like the slave cannot connect with the master or the cluster properly. However this can have a lot of possible causes. You can verify if the slave is connected with network analysis tools, and verify if they both registered in the namesrv, if there is configuration typos... etc. If you already tried these, can you provide us a full guide to reproduce the bug like cluster settings, runtime environment, network settings and so on? Thanks

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.
