### ISSUE TITLE
Benchmark enhancement

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq#2146]
Recently, we are using benchmark code to test our cluster which deployed on DLedger mode.
I found some minor enhancement which cloud make the process of benchmark clear and convenient.
-  add shutdown script
- more info print as a result of benchmark
- add thread count option for consumer

If anyone think it make sense, I'm glad to submit a related PR.

**Comment by imaffe** [comment]
Hi, you're welcomed to submit a PR and we will review it. Also the community is proposing a new plugin mechanism and lifecycle hook mechanism that enables developers to customize their benchmark options by integrating with these lifecycle hooks. I think the RIP is coming out soon and if you are interested feel free to join the RIP.

**Comment by maixiaohai** [comment]
> Hi, you're welcomed to submit a PR and we will review it. Also the community is proposing a new plugin mechanism and lifecycle hook mechanism that enables developers to customize their benchmark options by integrating with these lifecycle hooks. I think the RIP is coming out soon and if you are interested feel free to join the RIP.

Hi, I've submitted a PR and very glad to make contribution to community.
