### ISSUE TITLE
Why does RocketMQ pick "PUSH" model to implement HA?

### ISSUE THREAD

**Issue by Hao1296** [apache/rocketmq#2147]
Why not PULL?

**Comment by imaffe** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to   reopen it if you have any other issues.
