### ISSUE TITLE
Is it slaveReadEnable not work When cluster deployed on DLedger mode?

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq#2157]
When I set slaveReadEnable=true and isSuggestPullingFromSlave is true, I noticed consumer still pull messages from leader node. The variable whichBrokerWhenConsumeSlowly=1 seems not work?

**Comment by imaffe** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to     reopen it if you have any other issues.

**Comment by maixiaohai** [comment]
ok. I've found the solution
