### ISSUE TITLE
mqadmin getBrokerConfig help info is wrong

### ISSUE THREAD

**Issue by Aaron-He** [apache/rocketmq#2162]
1. Please describe the issue you observed:

Go into the ROCKETMQ_HOME directory, run this command: `./bin/mqadmin help getBrokerConfig`

Correct help info should be displayed.

But  help info on the specific command getBrokerConfig is displayed like this:

![getBrokerConfig](https://user-images.githubusercontent.com/21126659/87521320-ccc48480-c6b6-11ea-8ca5-85162c62ca4f.jpg)

2. Please tell us about your environment:

RocketMQ 4.7.1 

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

Previous versions also had this problem.

The description should be like:
> get brokerConfig by special broker
get brokerConfig by cluster

or

> get which broker
get which cluster

**Comment by imaffe** [comment]
Cool, I saw you already submitted a commit for this issue.  Would you like to submit a PR for us to review ? Thanks ~
