### ISSUE TITLE
slaveReadEnable=true not work When cluster deployed on DLedger mode sometimes[Followed #2157]

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq#2165]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
Start cluster deployed on DLedger mode and broker config slaveReadEnable=true.

- What did you expect to see?
When I started consumer to consume some history record which should be suggest consume from slave,
I think the consumer will pull messages from follower node.
- What did you see instead?
I found consumer still pull messages from leader node.
2. Please tell us about your environment:
env
```
version:4.7.0
jdk 8
centos 7
```
some broker conf
```
listenPort=30911
brokerClusterName=c4tst-rocketmq-fusion
enableDLegerCommitLog=true
sendMessageThreadPoolNums=128
slaveReadEnable=true
useReentrantLockWhenPutMessage=true
transferMsgByHeap=true
```
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
**the root cause is brokerId 1 not exist when node n0 is voted as leader. The broker id will be 0, 2, 3.**
- read from slave case, left is a follower(n0) and right is the leader(n1)
![image](https://user-images.githubusercontent.com/3734319/87654702-e387db80-c789-11ea-979e-3e86f4f1e2db.png)

- read from master case,left is a leader(n0) and right is the follower(n1)
![image](https://user-images.githubusercontent.com/3734319/87656176-b9371d80-c78b-11ea-8c19-5abba94a2987.png)

- When I fixed the bug, read from slave case,left is a leader(n0) and right is the follower(n1)
![image](https://user-images.githubusercontent.com/3734319/87655622-167e9f00-c78b-11ea-8266-ca7f65a885df.png)

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by RongtongJin** [comment]
Good catch! It is indeed a bug.

**Comment by zhishengzhang** [comment]
In which version was this bug fixed?


> Good catch! It is indeed a bug.
