### ISSUE TITLE
双主双从集群环境，新的订阅组设置 CONSUME_FROM_LAST_OFFSET 无效

### ISSUE THREAD

**Issue by writegull** [apache/rocketmq#2166]
按照文档描述：一个新的订阅组第一次启动从队列的最后位置开始消费，后续再启动接着上次消费的进度开始消费,即跳过历史消息。

实验环境1：RocketMQ4.2 双主双从集群
实验效果：第一次启动从队列的最前位置开始消费了，并没有跳过历史消息

实验环境2：RocketMQ4.2 单主
实验效果：如文档描述跳过了历史消息，和希望的一样。

tips：使用的是相同的consumer代码

疑问：想实现 CONSUME_FROM_LAST_OFFSET 在双主双从集群环境有什么特殊要求吗？

**Comment by duhenglucky** [comment]
@writegull 上述设置对于一个新的订阅组才会起作用，当然如果对应topic消息比较少，都在内存中，为了尽最大努力消费，也会从头开始的，最好还是通过[邮件列表](https://rocketmq.apache.org/about/contact/)的方式来提问

**Comment by illiqiang** [comment]
这个问题什么情况啊？没处理？
