### ISSUE TITLE
单机版部署启动broker的时候未生成commitlog

### ISSUE THREAD

**Issue by kakuTong** [apache/rocketmq#2179]
RocketMQ版本：4.7.0
操作系统：linux
java 版本：8
如题：启动nameserver已经提示成功，然后启动broker也提示成功，但是未生成commitlog文件夹，如图，只生成了这些文件
![image](https://user-images.githubusercontent.com/33883926/88051572-6c888380-cb8b-11ea-8897-588f24a0e1a8.png)，查看了store日志显示
![image](https://user-images.githubusercontent.com/33883926/88051702-98a40480-cb8b-11ea-92e8-5a322197bfaf.png)，这个应该就是没有找到commitlog引起的，求助。。。。

**Comment by maixiaohai** [comment]
应该是没有写入数据导致的吧

**Comment by kakuTong** [comment]
可能是跟机器环境有关系，本来我部署的是集群，这台机器也能加入到集群中，只是这台机器无论作为master还是slave都无法写入数据，其余机器都正常

**Comment by maxiaodong58** [comment]
rocketmq 是不是现在只能用Java 8

**Comment by francisoliverlee** [comment]
> RocketMQ版本：4.7.0
> 操作系统：linux
> java 版本：8
> 如题：启动nameserver已经提示成功，然后启动broker也提示成功，但是未生成commitlog文件夹，如图，只生成了这些文件
> ![image](https://user-images.githubusercontent.com/33883926/88051572-6c888380-cb8b-11ea-8897-588f24a0e1a8.png)，查看了store日志显示
> ![image](https://user-images.githubusercontent.com/33883926/88051702-98a40480-cb8b-11ea-92e8-5a322197bfaf.png)，这个应该就是没有找到commitlog引起的，求助。。。。

the log WARNING says the disk will be full soon.  increase disk size and try again

**Comment by kakuTong** [comment]
> > RocketMQ版本：4.7.0
> > 操作系统：linux
> > java 版本：8
> > 如题：启动nameserver已经提示成功，然后启动broker也提示成功，但是未生成commitlog文件夹，如图，只生成了这些文件
> > ![image](https://user-images.githubusercontent.com/33883926/88051572-6c888380-cb8b-11ea-8897-588f24a0e1a8.png)，查看了store日志显示
> > ![image](https://user-images.githubusercontent.com/33883926/88051702-98a40480-cb8b-11ea-92e8-5a322197bfaf.png)，这个应该就是没有找到commitlog引起的，求助。。。。
> 
> the log WARNING says the disk will be full soon. increase disk size and try again

硬盘空间足够，是因为没有创建commitlog才导致store日志打印 disk full的

**Comment by fantow** [comment]
> > > RocketMQ版本：4.7.0
> > > 操作系统：linux
> > > java 版本：8
> > > 如题：启动nameserver已经提示成功，然后启动broker也提示成功，但是未生成commitlog文件夹，如图，只生成了这些文件
> > > ![image](https://user-images.githubusercontent.com/33883926/88051572-6c888380-cb8b-11ea-8897-588f24a0e1a8.png)，查看了store日志显示
> > > ![image](https://user-images.githubusercontent.com/33883926/88051702-98a40480-cb8b-11ea-92e8-5a322197bfaf.png)，这个应该就是没有找到commitlog引起的，求助。。。。
> > 
> > 
> > the log WARNING says the disk will be full soon. increase disk size and try again
> 
> 硬盘空间足够，是因为没有创建commitlog才导致store日志打印 disk full的

Halo,can you provide your JVM configurations in the bin/runserver.sh and bin/runbroker.sh?It might be caused by inappropriate configurations.

**Comment by kakuTong** [comment]
commitlog文件夹没有自动创建导致的，手动创建该文件夹后重启broker后已经正常了，多谢各位

**Comment by zhouwentong1993** [comment]
我跟你的问题一致，但我手动创建文件夹后仍未生成具体的文件。但在另外的 Mac 上没有这个问题，很奇怪。

**Comment by Git-Yang** [comment]
> 我跟你的问题一致，但我手动创建文件夹后仍未生成具体的文件。但在另外的 Mac 上没有这个问题，很奇怪。

请问使用的版本是多少？服务启动打印日志提示文件路径不存在这个问题已经在PR #3278 中已经修复了。
另外，你说的没有生成具体的文件是指commitlog数据文件吧，这个有数据写入会自动创建。

**Comment by zhouwentong1993** [comment]
> 

多谢解答。
4.9.2 版本。我本地的代码比这个 PR 要早，所以这个问题在我这还存在。
我刚 debug 了一下，发现是网络问题导致 producer 无法访问到 broker，导致没有生成文件。
