### ISSUE TITLE
Start mqnamesrv error whth java version 11.01

### ISSUE THREAD

**Issue by maxiaodong58** [apache/rocketmq#2180]
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCMSCompactAtFullCollection'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by francisoliverlee** [comment]
@maxiaodong58 
what's version of rmq?

**Comment by maxiaodong58** [comment]
> @maxiaodong58
> what's version of rmq?

rmq version 4.7.1

**Comment by maxiaodong58** [comment]
@francisoliverlee 
rmq version 4.7.1

**Comment by maxiaodong58** [comment]
信息补充：win10 系统。在网址：https://rocketmq.apache.org/dowloading/releases/ 下载的二进制文件。然后执行命令：start mqnamesrv.cmd 出现如上错误提示信息。

**Comment by maixiaohai** [comment]
NameSrv启动的时候默认的GC方式是标记清除法，你的jdk版本太高了。降低jdk版本或者修改GC方式

**Comment by maixiaohai** [comment]
Hi, I submit a PR to fix this issue.

**Comment by daanhan** [comment]
报错了！！启动nameserver报错，脚本里使用sed，不能使用-E参数。麻烦修正😂
与本issue相关，所以在此留言了

sed：无效选项 -- E
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

OS: SUSE Linux Enterprise Server 11 (x86_64)
rocketmq version: 4.8.0
sed version: 4.1.5
