### ISSUE TITLE
retryTimesWhenSendAsyncFailed does not work

### ISSUE THREAD

**Issue by jaroky** [apache/rocketmq#2198]
I have three brokers in a cluster. In the process of sending data, I killed one broker. The producer did not try to send data again.

Below is my configuration：
        `producer.setRetryAnotherBrokerWhenNotStoreOK(true);`
        `producer.setRetryTimesWhenSendAsyncFailed(3);`
        `producer.setHeartbeatBrokerInterval(2000);`
        `producer.setPollNameServerInterval(2000);`

**Comment by Aaron-He** [comment]
There are two levels of retries when sending asynchronously. The 'retryTime' in the outer layer is 1, and the 'retryTime' in the inner layer is retryTimesWhenSendAsyncFailed.
When the broker is down, the producer cannot go to the inner retry logic, so the retryTimesWhenSendAsyncFaild does not work.

**Comment by jaroky** [comment]
Yes, I saw it. So when the producer is sending messages asynchronously, if a broker is killed, the configuration retryAnotherBrokerWhenNotStoreOK and retryTimesWhenSendAsyncFailed will be not work?

**Comment by tuobuxie** [comment]
yes you are right.
