### ISSUE TITLE
[FEATURE]DLQ topic should have write and read perm

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#2199]
Msgs in the DLQ should be read by mqadmin or console, So it can be judge what's wrong with it .But I found the topic only have the PERM_WRITE. 
I wonder if there are sth special to limit the perm of DLQ?

If not , I think it is a feature that DLQ have write and read PERM.

**Comment by francisoliverlee** [comment]
you can change the dlq topic's config to update PERM by RocketMQ console or admin command.
as your wish!
![image](https://user-images.githubusercontent.com/5908412/88624948-786bcc80-d0da-11ea-86a3-6b1b0ac14725.png)

**Comment by coder-zzzz** [comment]
> you can change the dlq topic's config to update PERM by RocketMQ console or admin command.
> as your wish!
> ![image](https://user-images.githubusercontent.com/5908412/88624948-786bcc80-d0da-11ea-86a3-6b1b0ac14725.png)

I know these two ways to update Perm, but why the DLQ can not have read perm default?

**Comment by francisoliverlee** [comment]
maybe it's a warning: messages in DLQ means bad logic happended in consuming code, **SOMEONE** needed to fix this, not some codes.

**Comment by coder-zzzz** [comment]
> maybe it's a warning: messages in DLQ means bad logic happended in consuming code, **SOMEONE** needed to fix this, not some codes.

Tks for your reply, So it is just because the DLQ's msgs should be process by person instead of application
