### ISSUE TITLE
mqadmin topiclist 查询显示不完整

### ISSUE THREAD

**Issue by superfenv** [apache/rocketmq#2201]
创建topic显示succeed. 但是去查看或者grep时候显示的topic名称是不完整的。请问有什么方式可以显示完整呢？

**Comment by lebron374** [comment]
more detail for help？

**Comment by maixiaohai** [comment]
这个主要是客户端打印时有长度限制导致的

**Comment by superfenv** [comment]
感谢回复，请问怎么设置它打印长度呢？

张旭 <notifications@github.com> 于2020年7月24日周五 下午5:45写道：

**Comment by francisoliverlee** [comment]
you can check the topic exist or not using [RocketMQ console](https://github.com/apache/rocketmq-externals/tree/master/rocketmq-console) or getTopicConfig command

**Comment by superfenv** [comment]
@francisoliverlee @maixiaohai @lebron374  I have another scenario like this. I need to create all topics in another rokcetmq cluster, but their names are incomplete. Through mqadmin topicList, the rocketmq-console page can only display 10 items. I can only copy incomplete topics to The rocketmq-console query can display the complete topic name, which is very laborious to operate. Is there any way or api that allows me to get a list of all topics?

**Comment by maixiaohai** [comment]
> @francisoliverlee @maixiaohai @lebron374 I have another scenario like this. I need to create all topics in another rokcetmq cluster, but their names are incomplete. Through mqadmin topicList, the rocketmq-console page can only display 10 items. I can only copy incomplete topics to The rocketmq-console query can display the complete topic name, which is very laborious to operate. Is there any way or api that allows me to get a list of all topics?

Every Broker has a config about topic named **topics.json** at dir **${storePathRootDir}/config/**.
Maybe that's what u want.

**Comment by superfenv** [comment]
Thank you for your reply, but it seems to be troublesome and requires
deduplication and filtering.
[image: image.png]

张旭 <notifications@github.com> 于2020年8月17日周一 下午4:03写道：
