### ISSUE TITLE
[Logic Error] There is a logical error in MQFaultStrategy when user use the Broker latency fault mechanism

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq#2204]
**BUG REPORT**

1. Please describe the issue you observed:
**I think there is a logical error in Producer,when user use the Broker latency fault mechanism**

- What did you do (The steps to reproduce)?
**You can find this error in org.apache.rocketmq.client.latency.MQFaultStrategy.selectOneMessageQueue(final TopicPublishInfo tpInfo, final String lastBrokerName)**
![rocketmq22](https://user-images.githubusercontent.com/18530950/88472985-8808db00-cf4b-11ea-9319-f7d2d8e98765.png)

  **First we should judge the mq is available by the method isAvailable(String brokerName)
  Second, we should judge this mq wheather a mq belongs to the same Broker which may be fault.
  So the right logic is choosing the mq does not belong to the same Broker**

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:
JDK1.8
RocketMQ 4.7.1

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
If you think this is an error, may I sumbit a PR to fix it?

**Comment by francisoliverlee** [comment]
from what i can see, best broker is always the first choice, if not exist, the second best is ok

**Comment by fantow** [comment]
> from what i can see, best broker is always the first choice, if not exist, the second best is ok

I agree with your option about choosing the right broker.But when we talk about Broker latency fault mechanism,I think we should avoid choosing the new messagequeue in the same Broker which occur something wrong.So I think the right logic is “!my.getBrokerName().equals(lastBrokerName)”

**Comment by RongtongJin** [comment]
Same as #2048, #2046, #1946, #1938, #1592, #1576, #1302. We will fix the issue ASAP.
