### ISSUE TITLE
[Logic confusion] The problem about [issues66] is not be solved

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq#2205]
BUG REPORT

    Please describe the issue you observed:

**Now,we do not fix this [#issue](https://github.com/apache/rocketmq-externals/issues/66)**
![RocketMQ1](https://user-images.githubusercontent.com/18530950/88475636-5ea87900-cf64-11ea-891c-8452a4c1d9b4.png)

**There is a logical confusion about msg and tmpMessage.
Even if it does not a necessory bug,we should clean up the wrong disturbing code.**

    What did you do (The steps to reproduce)?

    What did you expect to see?

    What did you see instead?

    Please tell us about your environment:

    Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
May I sumbit a PR to fix it?

**Comment by francisoliverlee** [comment]
of course
