### ISSUE TITLE
There is a bug will cause program can not throw the right exception

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq#2206]
BUG REPORT

    Please describe the issue you observed:
**org.apache.rocketmq.remoting.protocol.SerializeType.valueOf(byte code) can not throw the IllegalArgumentException .We can not locate the mistake when there are something wrong in SerializeType.**

![RocketMQ_1](https://user-images.githubusercontent.com/18530950/88481150-62e88c80-cf8c-11ea-9af4-497d238fe8ac.png)
![RocketMQ_2](https://user-images.githubusercontent.com/18530950/88481156-68de6d80-cf8c-11ea-9c2f-be490e8d6e5e.png)

    What did you do (The steps to reproduce)?

    What did you expect to see?

    What did you see instead?

    Please tell us about your environment:

    Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
May I submit a PR to fix it?

**Comment by francisoliverlee** [comment]
of course
