### ISSUE TITLE
brokerIP1 bug

### ISSUE THREAD

**Issue by pxm7459** [apache/rocketmq#2211]
when i start the rocketmq, the rocketmq get the sever public ip hava a bug. now the rocketmq get the ip is intranet IP. i need to set the server public ip in the conf/broker.conf ,add brokerIP1=my server public ip, when i start ,i use like this  nohup sh mqbroker -n my-public-ip:9876 -c ../conf/broker.conf  &   tail -f ~/logs/rocketmqlogs/broker.log 。now start successfully！

**Comment by francisoliverlee** [comment]
that's why brokerIP1 exist
