### ISSUE TITLE
DefaultMessageStore.start() question？

### ISSUE THREAD

**Issue by yankun2** [apache/rocketmq#2214]
DefaultMessageStore.start()  启动时 ，初始化reputFromOffset,这段注释是否永远不会发生呢，观察代码，maxPhysicalPosInLogicQueue 一直大于 this.commitLog.getMinOffset()，

![image](https://user-images.githubusercontent.com/37324363/88770645-b804e800-d1b0-11ea-928f-f250b6b3a520.png)

看了一下commit记录，上个版本存在配置项，如果为了获取最大offset，是否应该调用的是getMaxOffset()呢

![image](https://user-images.githubusercontent.com/37324363/88771937-9147b100-d1b2-11ea-9bba-d89ae586bfe9.png)

**Comment by RongtongJin** [comment]
This happens in following conditions:
1. If someone removes all the consumequeue files or the disk get damaged.
2. Launch a new broker, and copy the commitlog from other brokers.

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to  reopen it if you have any other issues.
