### ISSUE TITLE
阿里云的one-client与apache下的rockemq客户端是否通用

### ISSUE THREAD

**Issue by Liesport758** [apache/rocketmq#2215]
如题

**Comment by RongtongJin** [comment]
Apache RocketMQ clients can connect to Ali Cloud message queues.

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
