### ISSUE TITLE
Rocketmq takes up too much buff/cache

### ISSUE THREAD

**Issue by intriguing** [apache/rocketmq#2216]
rocketmq中每台broker的tps流量在30左右，峰值也差不多在80左右，数据很少。

![8E6E5868-B086-4D15-B287-4A09DEB8FC72](https://user-images.githubusercontent.com/9035629/88927959-cdf6d380-d2aa-11ea-8ed9-aaccea1b3ab7.png)

一台机器只部署了rocketmq的nameserver broker-master broker-slave  总共内存顶多90G内存(不存在其他服务)
![82C2A2D5-EAD7-4D87-83BC-59F4B7B18AE2](https://user-images.githubusercontent.com/9035629/88928968-09de6880-d2ac-11ea-9e17-5875027035de.png)

实际内存消耗内存 142G，剩余内存只有42G，随着时间增长buffer会越来越高

![D1A41292-A2C8-435C-989A-328006542CC8](https://user-images.githubusercontent.com/9035629/88928672-a9e7c200-d2ab-11ea-9a25-e1ac2d9929f5.png)

如果一台大内存的机器上混合部署多个服务，rocketmq可能会吃掉过多内存，影响其他服务

请开源社区的大牛吧，一起看下这个问题，定位下rocketmq在数据量很少的情况下为啥占用过多buff/cache

**Comment by RongtongJin** [comment]
It is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
