### ISSUE TITLE
Why batch send not provide an API for asynchronous send

### ISSUE THREAD

**Issue by MarvinLeu** [apache/rocketmq#2219]
Why does RocketMQ batch send not provide an API for asynchronous send? I tried to obtain a batch(List) Message from the outer layer before making an asynchronous API call, which returned send_OK normally.
请问rocketmq批量发送为什么没有提供异步发送的api?我尝试在外层先进行batch(list)获得一个Message，再进行异步发送的api调用，是能正常返回send_ok的结果。

![image](https://user-images.githubusercontent.com/46811237/89117286-2efef100-d4cf-11ea-9d79-ca80c95cad9a.png)
![image](https://user-images.githubusercontent.com/46811237/89117400-0cb9a300-d4d0-11ea-8397-eb4f228a6e65.png)

**Comment by RongtongJin** [comment]
IMO, we can provide asynchronous API for batch messages.

**Comment by zongtanghu** [comment]
Can you help to fix this issue? @zhangjidi2016

**Comment by zhangjidi2016** [comment]
OK
