### ISSUE TITLE
[May Be A Bug]May cause NPE because we do not examine the ChannelWrapper

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq#2220]
BUG REPORT

Please describe the issue you observed:
What did you do (The steps to reproduce)?
**There is a mistake may cause NPE because we do not examine the ChannelWrapper.**

What did you expect to see?

What did you see instead?
**I think we should examine whether channelWrapper is a null value.**
![RocketMQ_1](https://user-images.githubusercontent.com/18530950/89137742-bd28b500-d56b-11ea-8cc5-a0c53f1d85a4.png)

Please tell us about your environment:

Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
If it need to be fixed,may I submit a PR to fix it?

**Comment by RongtongJin** [comment]
Since channelTables is a ConcurrentHashMap, ConcurrentHashMap cannot be put into a null value otherwise it will cause NPE, so NPE will not happen here.

**Comment by fantow** [comment]
> Since channelTables is a ConcurrentHashMap, ConcurrentHashMap cannot be put into a null value otherwise it will cause NPE, so NPE will not happen here.

Thx for your answer,I mix HashMap and ConcurrentHashMap
