### ISSUE TITLE
consumerOffset is too large

### ISSUE THREAD

**Issue by chenpeihai1026** [apache/rocketmq#2225]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce):rocketmq console ng,the delay of the conmsumer model is too large 
 
- What did you expect to see? the delay is normal,such as 0

- What did you see instead?the delay is 928803233967072000
<img width="960" alt="微信图片_20200804181945" src="https://user-images.githubusercontent.com/30650528/89283077-1fbea580-d67f-11ea-8b94-50a980b7ed28.png">
<img width="767" alt="微信图片_20200804182049" src="https://user-images.githubusercontent.com/30650528/89283200-52689e00-d67f-11ea-86ac-851d3cc54584.png">
<img width="756" alt="微信图片_20200804182123" src="https://user-images.githubusercontent.com/30650528/89283213-58f71580-d67f-11ea-83ba-eba154b4efd1.png">

- ...

**Comment by imaffe** [comment]
This two message all have a timestamp : 1970-01-01 08:00:00, maybe it's something wrong with the message itself (or it triggered some weird logic) that caused this problem. Can you give us more detail on the message? Thanks so much

**Comment by chenpeihai1026** [comment]
hi,imafee
the messages body was ok when the producer client  send messages to the broker,but it was very weird in the rocketmq server and consumer client, maybe this was the cause. attach is the rocket client and message body
<img width="325" alt="微信图片_20200805115048" src="https://user-images.githubusercontent.com/30650528/89369964-1f231f00-d712-11ea-9963-d130ba9e6161.png">
<img width="594" alt="微信图片_20200805115206" src="https://user-images.githubusercontent.com/30650528/89369969-20ece280-d712-11ea-9585-9d2d837c7b30.png">

**Comment by francisoliverlee** [comment]
@chenpeihai1026 what is weird?
