### ISSUE TITLE
Cloud Server No route info for this topic Problem

### ISSUE THREAD

**Issue by EE6** [apache/rocketmq#2228]
cloud server install rocketmq-3.3.2。Configure one master and one slave on server A and server B with intranet IP。 namesrv , broker  Registration and startup are normal，The firewall is also stop，autoCreateTopicEnable=true，fastjson jar 1.2.44, Microservices are deployed on server C，Whether the topic is manually added in advance or automatically created, an error is reported ：
caused by: com.alibaba.rocketmq.client.exception.MQClientException: No route info for this topic, ***
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/64
https://github.com/alibaba/RocketMQ/issues/64 The page opens to 404
Problem unable to solve, ask the the idea of next step  or who know the same cause , please advise~

**Comment by RongtongJin** [comment]
Plz refer to this [issue](https://github.com/apache/rocketmq/issues/504) or [article](http://rocketmq.apache.org/docs/faq/).
I will close the Issue first, but please feel free to reopen it if you have any other issues.
