### ISSUE TITLE
消费者队列的brokerName被修改

### ISSUE THREAD

**Issue by MnameHZJ** [apache/rocketmq#2229]
部署情况：mq部署了broker-a，broker-a-s，broker-b，broker-b-s，双主双从，主从同步双写方式部署。
出现的问题：
	一开始消费者正常消费broker-a和broker-b的消息，停止broker-a和broker-b-s，停一段时间后，重启broker-a和broker-b-s。消费者无法消费broker-b的消息。
	打印内存镜像出来查看mq的队列信息，只有broker-a队列，没有broker-b的队列。OffsetStore的offsetTable对象，其中的队列信息的brokerName被修改了，broker-b被改为了broker-a。
offsetTable中的队列的brokerName为何会被修改呢？有什么场景下，队列的brokerName会被修改？

（队列信息的brokerName被修改，是个推测的结果，offsetTable中存在两个内容相同的队列，然而两个队列的brokerName对象却是不同的，推测出队列是被放入offsetTable后，队列的brokerName才被修改的。）

![Snipaste_2020-08-05_21-13-21](https://user-images.githubusercontent.com/9431670/89427900-59baa500-d76e-11ea-82ee-98cf012d0497.png)

版本：4.5.2

**Comment by duhenglucky** [comment]
@MnameHZJ rocketmq 中没有修改brokerName 的逻辑，建议关注下org.apache.rocketmq.client.consumer.DefaultMQPullConsumer#fetchSubscribeMessageQueues 方法，该方法传入的是topic的名称。
