### ISSUE TITLE
Why create a new SystemClock class to get the time ？

### ISSUE THREAD

**Issue by SpinSi** [apache/rocketmq#2235]
最近在看源码，发现org.apache.rocketmq.common.SystemClock 
只有这个功能，为啥要新创建个SystemClock类呢？
package org.apache.rocketmq.common;

public class SystemClock {
    public long now() {
        return System.currentTimeMillis();
    }
}

**Comment by RongtongJin** [comment]
IMO, it is not necessary but does not affect normal functions.
