### ISSUE TITLE
[Logic confusion] There is a wrong logic processing about timeout ResponseFuture in method scanResponseTable

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq#2237]
BUG REPORT

Please describe the issue you observed:
What did you do (The steps to reproduce)?
  **In the class NettyRemotingAbstract,there is a method to process the timeout ResponseFuture in responseTable named scanResponseTable().
  Now,this method's processing steps are:
    1.scan the responseTable and find the responseFuture which are not timeout.
    2.remove this responseFuture which in responseTable and put them in a new List named rfList 
    3.then we will scan rfList and execute them callback function which are not timeout.**

**I think the logic is wrong.
    1.Is it a necessory that we should keep the timeout ResponseFuture?
    2.From the method name and annotation,this method is used to scan and expire deprecated request,it should choose the timeout ResponseFuture and remove it.**

![RocketMQ1](https://user-images.githubusercontent.com/18530950/89706965-dc28ac00-d99c-11ea-9599-b4dfdd18c543.png)

What did you expect to see?

What did you see instead?

Please tell us about your environment:
JDK 1.8
RocketMQ 4.7.1

Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
**May I submit a PR to fix it?**

**Comment by RongtongJin** [comment]
I agree with you. Welcome to submit relevant PR.

**Comment by imaffe** [comment]
this if statement
```
(rep.getBeginTimestamp() + rep.getTimeoutMillis() + 1000) <= System.currentTimeMillis()
```
It looks to me that this if statement is checking if a response is timeout ? because if currentTimeMillis >= rep.getBeginTimestamp() + rep.getTimeoutMillis() then means this rep is timeout 

so in your description
 > 1. scan the responseTable and find the responseFuture which are not timeout.


I think what it did here is scan the responseTable and find the responseFuture which ARE timeout.
