### ISSUE TITLE
Source option 6 is no longer supported

### ISSUE THREAD

**Issue by caoshuyubx** [apache/rocketmq#2238]
2020-07-30 提交pox文件中修改了dledger的版本，从0.1更改为0.2所引起的，如果发现这个问题可以考虑将版本回滚到2020-07-29的版本，版本号为83cc99ad13f8f12ceedb373d072483602be9b77e，回滚后可以正常编译

**Comment by RongtongJin** [comment]
I can compile successfully in my environment, could you provide more detailed information to help us locate the issue?

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.
