### ISSUE TITLE
About running Producer demo

### ISSUE THREAD

**Issue by smipo** [apache/rocketmq#2239]
第一次运行Producer，过了几秒 提示 java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to null failed的错误，很懵逼，百度了下才发现需要设置 producer.setNamesrvAddr("127.0.0.1:9876")，这个参数是必须的，但是又不是构造函数强制构造的，且运行几秒后才给提示connect to null failed，对于新手非常懵逼。

**Comment by RongtongJin** [comment]
The nameserver can be set through environment variables, codes, etc. Therefore, it is not mandatory to set the nameserver in the demo, but there will be related comments in the demo of quick start example.

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.

**Comment by RongtongJin** [comment]
close the issue
