### ISSUE TITLE
org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendDefaultImpl call timeout

### ISSUE THREAD

**Issue by wujnju** [apache/rocketmq#2240]
我把rocketmq4.4.0版本放在阿里云服务器上，一个使用rocklmq的springboot程序运行在本机上
我在/conf/broker.conf添加了：
namesrvAddr=服务器公网ip:9876
brokerIP1=服务器公网ip
我启动rocketmq的命令如下：
`
nohup ./bin/mqnamesrv -n 服务器公网ip:9876 &

nohup sh bin/mqbroker -n 服务器公网ip8:9876 -c conf/broker.conf autoCreateTopicEnable=true &
`
运行程序后报错：
org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendDefaultImpl call timeout

请问我该怎么做？
>Springboot是2.0.5版本，导入rocketmq依赖是4.3.0版本

**Comment by wujnju** [comment]
> 我把rocketmq4.4.0版本放在阿里云服务器上，一个使用rocklmq的springboot程序运行在本机上
> 我在/conf/broker.conf添加了：
> namesrvAddr=服务器公网ip:9876
> brokerIP1=服务器公网ip
> 我启动rocketmq的命令如下：
> `nohup ./bin/mqnamesrv -n 服务器公网ip:9876 &
 nohup sh bin/mqbroker -n 服务器公网ip8:9876 -c conf/broker.conf autoCreateTopicEnable=true &`
> 运行程序后报错：
> org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendDefaultImpl call timeout
> 
> 请问我该怎么做？
> 
> > Springboot是2.0.5版本，导入rocketmq依赖是4.3.0版本

**Comment by francisoliverlee** [comment]
how many namesrvs and brokers?
more stack error in client needed and pls show the client config

**Comment by imaffe** [comment]
Have you verified the security group allows your local machine to that aliyun host port ? If it is call time out then it might be your local machine cannot visit the rocketmq port. (port 9876 and 10911 )

Seems like this is an stale issue, I'll close it for now, but feel free to reopen it you have further questions, thanks :)
