### ISSUE TITLE
the picture of docs is not found

### ISSUE THREAD

**Issue by huey2672** [apache/rocketmq#2244]
I  can't find the pictures in the docs, such as [this article](https://github.com/apache/rocketmq/blob/master/docs/en/design.md#51-the-process-of-rocketmq-transactional-message).
there is a sentence 'The picture above shows the overall...', but I can't see any pictures.
Please upload those pictures, it will help readers to understand the guides.

**Comment by RongtongJin** [comment]
I can see the picture. 
![image](https://user-images.githubusercontent.com/21963954/89972144-a121c380-dc8f-11ea-9f7d-2801cb3f96e0.png)
It may be a issue with github.
