### ISSUE TITLE
Expose pull method for DefaultLitePullConsumer and replace at QueryMsgByOffsetSubCommand

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq#2247]
**BUG REPORT**

1. Please describe the issue you observed:
In the deprecated class DefaultMQPullConsumer, we could use 
```PullResult pullResult = defaultMQPullConsumer.pull(mq, "*", Long.parseLong(offset), 1);```
to query message by offset.
While DefaultLitePullConsumer doesn't expose this method, and has compitable problem.

2. Please tell us about your environment:
rmq 4.7.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
Some kind of like issue https://github.com/apache/rocketmq/issues/2245.
BTW, I'am wondering if the community has plan about class **DefaultLitePullConsumer** and **DefaultMQPullConsumer**.

**Comment by RongtongJin** [comment]
There is no plan for DefaultLitePullConsumer to provide a method to query messages by offset. But we can still accomplish the same function through other methods such as using mqadmin tool. And the  community hopes that DefaultLitePullConsumer can replace DefaultMQPullConsumer in the future

**Comment by maixiaohai** [comment]
Got it. It helps a lot. Thanks!

**Comment by manyhelp** [comment]
using mqadmin tool ? Can you provide examples? @RongtongJin
