### ISSUE TITLE
I'd like to config the client worker threads

### ISSUE THREAD

**Issue by guixincui** [apache/rocketmq#2248]
I'd like to config the client worker threads, But this config is written dead as 4

```
package org.apache.rocketmq.remoting.netty;

public class NettyClientConfig {
    /**
     * Worker thread number
     */
    private int clientWorkerThreads = 4;
   ...
}
```

![image](https://user-images.githubusercontent.com/3414503/90104564-14eacb80-dd77-11ea-87b3-b874c0999bf9.png)

**Comment by RongtongJin** [comment]
IMO, Exposing netty parameters on the client is not very good, and it will cause confusion to users.

**Comment by imaffe** [comment]
Multiple consumer/producer can use a single NettyClient. In this case a single consumer/prodcuer should not be able to modify the netty client settings as it might affect other consumer/producers. In some way Consumer/Producer config and NettyClient config are in different scope. Currently we hide nettyclient configs from users, but if we want to expose them, we need to probably design an extra config mechanism and make sure users understand that a netty config is global to all consumers/producers(with same instanceName). And that is why we cannot simply add this configuration in ConsumerConfigs.

It would be nice if we can work out a graceful solution for NettyClient config.

**Comment by imaffe** [comment]
I'm closing this issue due to lack of further discussion, but feel free to reopen it if you have other questions or new ideas related to this issue~

**Comment by guixincui** [comment]
@imaffe  each producer or consumer has each config
