### ISSUE TITLE
ipv6 support?

### ISSUE THREAD

**Issue by 191474639** [apache/rocketmq#2252]
支持ipv6吗

**Comment by RongtongJin** [comment]
RocketMQ support ipv6. https://github.com/apache/rocketmq/wiki/RIP-15-RocketMQ-IPv6-Support-Project

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
