### ISSUE TITLE
Add broker JvmManager to expose jvm info

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq#2257]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
**Add a JvmManager to collect broker jvm info and expose through admin tools**
2. Provide any additional detail on your proposed use case for this feature.
**This feature provides  common users with commands to directly obtain JVM metrics, and they do not need to perform additional development work
Futuremore, jvm data could be provided to other external monitoring systems.**
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
**In the production environment, it is necessary to monitor the performance metrics of the JVM.
Also through command to get info about important jvm info at one time is cool.
Because rmq not support it currently, everyone who cares about  the JVM data need to do some work about it.**

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,

**Comment by imaffe** [comment]
> for developer use
https://juejin.im/post/6844903655456374792 


> for exporting metrics to monitoring systems
https://www.datadoghq.com/blog/java-runtime-monitoring-with-jvm-metrics/
https://segmentfault.com/a/1190000016791460

If we just need JVM metrics, we can export JVM metrics without making any modifications to the code (and we shouldn't. Apparently JVM metrics should be available for every Java application, and it would be so awkward if we need to write metrics code for every java application if we want to export metrics). 


However, if we want to add some Rocketmq-specific metrics via  JMX, this would be ok. We can create some metrics beans to JMX agent and other monitoring tools like datadog or Prometheus would create their own JMX exporters to collect metrics.


In your case I think you can collect JVM metrics already, either by using j-something command line tools (which is pretty much the standard way to monitor JVM) or using some monitoring tool like  dd or prometheus.

**Comment by maixiaohai** [comment]
> > for developer use
> > https://juejin.im/post/6844903655456374792
> 
> > for exporting metrics to monitoring systems
> > https://www.datadoghq.com/blog/java-runtime-monitoring-with-jvm-metrics/
> > https://segmentfault.com/a/1190000016791460
> 
> If we just need JVM metrics, we can export JVM metrics without making any modifications to the code (and we shouldn't. Apparently JVM metrics should be available for every Java application, and it would be so awkward if we need to write metrics code for every java application if we want to export metrics).
> 
> However, if we want to add some Rocketmq-specific metrics via JMX, this would be ok. We can create some metrics beans to JMX agent and other monitoring tools like datadog or Prometheus would create their own JMX exporters to collect metrics.
> 
> In your case I think you can collect JVM metrics already, either by using j-something command line tools (which is pretty much the standard way to monitor JVM) or using some monitoring tool like dd or prometheus.

Thanks for you reply. It help a lot.
Actually, we found jmx_exporter is very useful.
