### ISSUE TITLE
scheduleMessageService use old delayOffset info

### ISSUE THREAD

**Issue by lynfwyz** [apache/rocketmq#2259]
In my current understanding, slave fetches the latest delayOffset from master and puts it into file only, without putting it into offsetTable inside the scheduleMessageService. When slave changes to master, it startes scheduleMessageService using offsetTable in memory, which just containes old delayOffset info. May it lead to message repeation?

**Comment by RongtongJin** [comment]
IMO, there is such an issue, but even if we put it into offsetTable inside the scheduleMessageService,  it still can’t avoid message repeation.

**Comment by absolute8511** [comment]
I found a fix in https://github.com/apache/rocketmq/commit/cad0cfcecef88958b103059aea7b98395850226a , which will reload from file using `this.brokerController.getScheduleMessageService().load();`
