### ISSUE TITLE
commitlog is not deleted, commitlog has tried out the disk

### ISSUE THREAD

**Issue by yangsanlang999** [apache/rocketmq#2260]
Configuration information:

brokerClusterName=DefaultCluster
brokerName=mdserver-2
brokerId=0
brokerIP1=13.170.1.14
brokerIP2=13.170.1.14
deleteWhen=04
fileReservedTime=6
namesrvAddr=13.170.1.13:55003
defaultTopicQueueNums=12
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
mapedFileSizeCommitLog=1073741824
mapedFileSizeConsumeQueue=300000

flushCommitLogLeastPages=6400
flushConsumeQueueLeastPages=3200
flushCommitLogThoroughInterval=120000
flushConsumeQueueThoroughInterval=120000

maxCommitLogFilesNumber=100
diskMaxUsedSpaceRatio=75
storePathRootDir=/mnt/syncdata/store
storePathCommitLog=/mnt/syncdata/store/commitlog
storePathConsumeQueue=/mnt/syncdata/store/consumequeue
storePathIndex=/mnt/syncdata/store/index
storeCheckpoint=/mnt/syncdata/store/checkpoint
abortFile=/mnt/syncdata/store/abort
maxMessageSize=5242880
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
sendMessageThreadPoolNums=128
pullMessageThreadPoolNums=128
listenPort=55100

**Comment by imaffe** [comment]
Here is a Chinese version explaining disk cleanup mechanism, it might help: https://jaskey.github.io/blog/2017/02/16/rocketmq-clean-commitlog/

For other debugging purposes, can you please provide some error log (like if any exception was thrown during clean up) and other useful debugging material you find useful ? Thanks a lot ~

**Comment by yangsanlang999** [comment]
> Here is a Chinese version explaining disk cleanup mechanism, it might help: https://jaskey.github.io/blog/2017/02/16/rocketmq-clean-commitlog/
> 
> For other debugging purposes, can you please provide some error log (like if any exception was thrown during clean up) and other useful debugging material you find useful ? Thanks a lot ~
Is there any requirement for commitlog file path, currently my path is configured randomly，storePathCommitLog=/mnt/syncdata/store/commitlog

**Comment by imaffe** [comment]
As long as the rocketmq user has write access to that location, then I think it should be fine. However I do want to know how did you find out that the disk is full. If the disk usage is above 75% the log should have some records. Can you find any logging related to this problem ?

**Comment by yangsanlang999** [comment]
> As long as the rocketmq user has write access to that location, then I think it should be fine. However I do want to know how did you find out that the disk is full. If the disk usage is above 75% the log should have some records. Can you find any logging related to this problem ?

Use commands to query results

df -h

Filesystem  Size     Used Avail Use% Mounted on
/dev/sda2   493G  492G   0     100% /mnt/syncdata 


du -sh /mnt/syncdata/store/*

479G  /mnt/syncdata/store/commitlog 

------------------------------------------
View the source code, the path is hard-coded, and no setting is found
; org.apache.rocketmq.store.config.MessageStoreConfig,

@ImportantField
    private String storePathCommitLog = System.getProperty("user.home") + File.separator + "store"
        + File.separator + "commitlog";

**Comment by yangsanlang999** [comment]
> As long as the rocketmq user has write access to that location, then I think it should be fine. However I do want to know how did you find out that the disk is full. If the disk usage is above 75% the log should have some records. Can you find any logging related to this problem ?

**Comment by fancyfei** [comment]
结果是如何处理的？
我也遇到同样的问题。commitlog没有被自动清理，结果硬盘空间不足引起一次生产事故。
