### ISSUE TITLE
commitlog is not deleted, commitlog has tried out the disk

### ISSUE THREAD

**Issue by yangsanlang999** [apache/rocketmq#2264]
Use commands to query results

df -h

Filesystem Size Used Avail Use% Mounted on
/dev/sda2 493G 492G 0 100% /mnt/syncdata

du -sh /mnt/syncdata/store/*

479G /mnt/syncdata/store/commitlog

View the source code, the path is hard-coded, and no setting is found
; org.apache.rocketmq.store.config.MessageStoreConfig,

@ImportantField
private String storePathCommitLog = System.getProperty("user.home") + File.separator + "store"
+ File.separator + "commitlog";

So, if you customize the commitlog file path, do you want to modify the source code?

**Comment by francisoliverlee** [comment]
hard-coded for default. you can change it by set config like 
```java
storePathCommitLog=/data/rocketmq/commitlog
```

**Comment by yangsanlang999** [comment]
> hard-coded for default. you can change it by set config like

This is my configuration, but commitlog is not deleted, commitlog has tried out the disk：
brokerClusterName=DefaultCluster
brokerName=mdserver-2
brokerId=0
brokerIP1=13.170.1.14
brokerIP2=13.170.1.14
deleteWhen=04
fileReservedTime=6
namesrvAddr=13.170.1.13:55003
defaultTopicQueueNums=12
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
mapedFileSizeCommitLog=1073741824
mapedFileSizeConsumeQueue=300000

flushCommitLogLeastPages=6400
flushConsumeQueueLeastPages=3200
flushCommitLogThoroughInterval=120000
flushConsumeQueueThoroughInterval=120000

maxCommitLogFilesNumber=100
diskMaxUsedSpaceRatio=75
storePathRootDir=/mnt/syncdata/store
storePathCommitLog=/mnt/syncdata/store/commitlog
storePathConsumeQueue=/mnt/syncdata/store/consumequeue
storePathIndex=/mnt/syncdata/store/index
storeCheckpoint=/mnt/syncdata/store/checkpoint
abortFile=/mnt/syncdata/store/abort
maxMessageSize=5242880
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
sendMessageThreadPoolNums=128
pullMessageThreadPoolNums=128
listenPort=55100

**Comment by francisoliverlee** [comment]
@yangsanlang999 check broker log in /$(user_home)/logs, take out some error log detail

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.
