### ISSUE TITLE
Uneven consumption on the consumer side

### ISSUE THREAD

**Issue by farsunset** [apache/rocketmq#2266]
4台服务集群使用同一个groupId。但是由canal发送的消息 总是被其中一台消费，其余3台基本是没有接收到过消息
MQ是用的阿里云服务，在订阅关系里面可以看到4台机器，canal机器配置如下
就是普通的消息，我们是在canal里面配置的MQ发出去的，配置如下见机密配置
消费端的GID和这里canal.mq.producerGroup配置的是同一个值GID_MQ_CANAL
canal.mq.servers = xxxxxxx.cn-xxx.mq-internal.aliyuncs.com:8080
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 100
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
canal.mq.properties. =
canal.mq.producerGroup = GID_MQ_CANAL
canal.mq.accessChannel = cloud
canal.aliyun.accessKey = xxxxxxx
canal.aliyun.secretKey = xxxxxxxxx
canal.mq.namespace = MQ_I**_**********************
canal.mq.topic= GID_MQ_CANAL_MESSAGE

**Comment by RongtongJin** [comment]
用的是java的客户端吗？重平衡算法是什么？重平衡后的每台机器被分配到的队列可以通过日志查看到吗？

**Comment by farsunset** [comment]
是java客户端 版本4.5  其实是通过canal 发的MQ，配置参数
#canal.mq.partition=1
canal.mq.partitionsNum=4
canal.mq.partitionHash=.*\\..*:id
我提了issues，他们说让我在rocketMQ社区问

**Comment by farsunset** [comment]
> 用的是java的客户端吗？重平衡算法是什么？重平衡后的每台机器被分配到的队列可以通过日志查看到吗？

是java客户端 版本4.5 其实是通过canal 发的MQ，配置参数
#canal.mq.partition=1
canal.mq.partitionsNum=4
canal.mq.partitionHash=.\..:id
我提了issues，他们说让我在rocketMQ社区问
