### ISSUE TITLE
[NEW FEATURE REQ] Skip some message of messageQueue

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#2267]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Skip some message by tools or other ways to avoid app error without exception catch.

2. Provide any additional detail on your proposed use case for this feature.
Sometimes producer send error msgs to topic, it will be block the consumer's consume because the consumer didn't try catch this exception(like json format error)

There are there ways to fix skip the error msgs:
1.  skip to the latest msg's offset(already offered)
2.  skip to sometime(already offered)
3.  make a hotfix to skip the msgs(programing by users)

**Comment by francisoliverlee** [comment]
how about reset consume offset?

**Comment by coder-zzzz** [comment]
> how about reset consume offset?
> @coder-zzzz

Ok. I will push a pr laterly. Provided in tools

**Comment by francisoliverlee** [comment]
@coder-zzzz that would be very nice of you  😊
