### ISSUE TITLE
Rocktmq is not friendly to cloud native.

### ISSUE THREAD

**Issue by win5do** [apache/rocketmq#2268]
I want deploy rocketmq  on kubernetes, but I ran into many problems.

# Feature request

## dLegerPeers config

The config `dLegerPeers=n0-rocketmq-broker-01:40911;n1-rocketmq-broker-02:40911;n2-rocketmq-broker-03:40911` get `index out of range` exception,  because the code use `-` separator. 

For valid dns consider refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names.

It seems that the dependency has been fixed, but it has not been updated: https://github.com/openmessaging/openmessaging-storage-dledger/commit/1cef542b7b631fe0dd66df14a1fd8d37eeeda867

## advertised port

Some port is hard code, can't modify by config. And don't have config such as `advertised.listeners` in Kafka.
  https://github.com/apache/rocketmq/blob/9f95a972e10e0681bc3f2d00e9957aa212e897b5/broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java#L266
    
 
https://github.com/apache/rocketmq/blob/d1b4e47c26576cf4fa543bbdd8c6f09643220bed/broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java#L185

Accessing from outside k8s is very troublesome, the client get `host:port` from Nameserver, but it is the inner container `svc:port`. 

The office operator (https://github.com/apache/rocketmq-operator) also not did this well. 

So we must config `hostPort/nodePort == containerPort == listenPort(in config)`. Same for the vipChannel port `listPort-2`.

So `advertised.listeners` is needed.

Is there  plan for improvement ?

**Comment by RongtongJin** [comment]
You can submit related issues to the rocketmq-operator project. Also welcome to submit relevant code to help rocketmq embrace cloud native.

Issues are generally used for bug reports and feature requests, so if you have any questions about  Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
