### ISSUE TITLE
[BUG] RequestHouseKeepingService has not been cleaned after DefaultMQProducerImpl shutdown

### ISSUE THREAD

**Issue by cytnju** [apache/rocketmq#2269]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- 1.run this demo
```java
public staic void main(String[] args) {
     DefaultMQProducer producer;
     for(int i = 0; i < 99999; i++) {
          producer = new DefaultMQProducer("group");
          producer.start();
          producer.shutdown();
     }
    // this case will throw OOM
}
```
- 2. thread dump and grep "RequestHouseKeepingService"
![image](https://user-images.githubusercontent.com/23069836/91526629-a9882880-e936-11ea-88dc-875884e089cf.png)

- What did you expect to see?
RequestHouseKeepingService will be cleaned after producer shut down.

- What did you see instead?
![image](https://user-images.githubusercontent.com/23069836/91526629-a9882880-e936-11ea-88dc-875884e089cf.png)

2. Please tell us about your environment:
```shell
jre : 1.8
os: mac os
rocketmq-version : 4.7.0
```
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
```RequestHouseKeepingService``` timer construction in ```DefaultMQProducerImpl```
![image](https://user-images.githubusercontent.com/23069836/91527526-852d4b80-e938-11ea-9a47-b24bed4c77b2.png)

```timer``` will sehcdule in fixed rate after producer start.
![image](https://user-images.githubusercontent.com/23069836/91527475-6d55c780-e938-11ea-9cec-e6e8d45557fa.png)

```timer``` does not shutdown when shutting down the producer.
![image](https://user-images.githubusercontent.com/23069836/91527065-93c73300-e937-11ea-8dc4-8b65485f4965.png)

**Comment by RongtongJin** [comment]
If I remember correctly, 4.7.1 has fixed the issue, could you help me verify it?

**Comment by RongtongJin** [comment]
Same issue #1950 #1957

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if the same issue still exists in version 4.7.1.
