### ISSUE TITLE
Consumer threadpool didn't expand automatically

### ISSUE THREAD

**Issue by d4ksn** [apache/rocketmq#2271]
```
        this.consumeRequestQueue = new LinkedBlockingQueue<Runnable>();

        this.consumeExecutor = new ThreadPoolExecutor(
            this.defaultMQPushConsumer.getConsumeThreadMin(),
            this.defaultMQPushConsumer.getConsumeThreadMax(),
            1000 * 60,
            TimeUnit.MILLISECONDS,
            this.consumeRequestQueue,
            new ThreadFactoryImpl("ConsumeMessageThread_"));
```

When I digged into the code, I found that the `ThreadPoolExecutor` in `ConsumeMessageConcurrentlyService`/`ConsumeMessageOrderlyService` was constructed with a `LinkedBlockingQueue` with unlimited capacity.
I think this consumer thread pool will never expand automatically, and the thread count always keep at `consumeThreadMin`. So the `consumeThreadMax` parameter is actually meaningless...

**Comment by francisoliverlee** [comment]
@d4ksn 
do u like to fix it ?

**Comment by d4ksn** [comment]
> @d4ksn
> do u like to fix it ?

How should I fix it?
Should I use a fixed thread pool, or a queue with limited capacity (and with configurable queueSize parameter) ?

**Comment by francisoliverlee** [comment]
@d4ksn what's your idea?

**Comment by d4ksn** [comment]
@francisoliverlee Personally, maybe I'd like to use a fixed thread pool, and just remove the `consumeThreadMax` parameter. Because it looks much easier. ☺

**Comment by francisoliverlee** [comment]
if the thread-pool can adjust itself by messages, that would be save memories and cpus

**Comment by d4ksn** [comment]
@francisoliverlee If it uses a BlockingQueue with limited capacity, it has to handle the situation of RejectedExecutionException, and I think this will lead to backward-compatibility issue.
If it just uses a fixed thread pool, I think it will be actually no different from the current logic, and just removes a meaningless parameter.

**Comment by d4ksn** [comment]
Dubbo also uses a fixed thread pool by default

**Comment by francisoliverlee** [comment]
dont know about dubbo, can you show how dubbo use fixed thread pool in some situations

**Comment by d4ksn** [comment]
http://dubbo.apache.org/en-us/docs/user/references/xml/dubbo-protocol.html
The default value for `threadpool` is `fixed`, and with 200 `threads`.

**Comment by zongtanghu** [comment]
Any progress?

**Comment by medusar** [comment]
IMO, it will better if we allow users to specify a size for the BlockingQueue, and we can set a small size by default because there is also a ScheduledExecutorService which will resubmit the task later if it is rejected.

**Comment by coder-zzzz** [comment]
How about set param pullThresholdForQueue's value as the queue size?
PullThresholdForQueue default is 1000, means the max message will be pull from broker
