### ISSUE TITLE
Spelling mistakes in makeMessageToCosumeAgain method

### ISSUE THREAD

**Issue by ZingBug** [apache/rocketmq#2272]
在org.apache.rocketmq.client.impl.consumer.ProcessQueue#makeMessageToCosumeAgain函数中，表示重新消费该批消息，但应该是consume吧，少了一个n。

**Comment by francisoliverlee** [comment]
@ZingBug 
can you fix it ?

**Comment by RongtongJin** [comment]
When submitting PR, you need to pay attention to whether there are compatibility problems
