### ISSUE TITLE
rocketmq dledger storePathCommitLog is invalid

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#2277]
**BUG REPORT**

1. I find  only storePathRootDir is vallid when enableDLegerCommitLog=true,even I set storePathCommitLog in other directory ,the commitlog is 
 still   $storePathRootDir/commitlog.

**Comment by imaffe** [comment]
Could you describe this bug in more detail like what do you expect to happen ? Thanks ~

**Comment by iamqq23ue** [comment]
> Could you describe this bug in more detail like what do you expect to happen ? Thanks ~

For example，  I set storePathRootDir = /apath/   and storePathCommitLog = /apath/commitlog in broker-n0.conf.

But in fact the real cmmitlog file will appear in the /apath/dledger-n0/data directory, and there is no file in the /apath/commitlog directory

**Comment by maixiaohai** [comment]
@iamqq23ue the same problem？https://github.com/apache/rocketmq/issues/2280

**Comment by iamqq23ue** [comment]
> @iamqq23ue the same problem？#2280

yes

**Comment by maixiaohai** [comment]
> > @iamqq23ue the same problem？#2280
> 
> yes

I've submitted a pr to fix it. You can check if it solve your problem.

**Comment by iamqq23ue** [comment]
> > > @iamqq23ue the same problem？#2280
> > 
> > 
> > yes
> 
> I've submitted a pr to fix it. You can check if it solve your problem.

ok ,thanks
