### ISSUE TITLE
 Poor performance of rocketmq dledger

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#2278]
**BUG REPORT**

1. In my test, I found that with the same test server , the tps of master-slave can reach more than 100,000, but the maximum tps of dleder is only 13,000. I hope it can be optimized.
2. Please tell us about your environment:

16c 32g virtual machine。 master-slave use 2 machine ，dledger use 3 machine. 
Sync replication, sync flush

**Comment by RongtongJin** [comment]
DLedger will improve performance in 4.8.0 through [pipeline mode](https://github.com/apache/rocketmq/pull/1847) and batch replication (DLedger version 0.2.0).
