### ISSUE TITLE
scheduleMessageOffset overflow

### ISSUE THREAD

**Issue by yejiahao** [apache/rocketmq#2279]
In my case, a strange phenomenon happens reported by ***tester engineer***:
**comsumer scheduleMessageOffset > producer scheduleMessageOffset**

- RocketMQ version is **V4.5.2** (Both client API and Server)

- broker status
```
sh /home/rocketMQ/rocketmq-4.5.2/bin/mqadmin brokerStatus -b <IP:PORT>
...
bootTimestamp                   : 1598590974120
brokerVersion                   : 317
brokerVersionDesc               : V4_5_2
commitLogDirCapacity            : Total : 258.2 GiB, Free : 130.9 GiB.
...
runtime                         : [ 2 days, 23 hours, 56 minutes, 36 seconds ]
scheduleMessageOffset_1         : 138699,447
scheduleMessageOffset_16        : 2,0
scheduleMessageOffset_2         : 5559,28
scheduleMessageOffset_3         : 538,4
scheduleMessageOffset_4         : 3,0
...
```

- producer client sample
```java
Message msg = new Message("topic", "tag", "body".getBytes(RemotingHelper.DEFAULT_CHARSET));
// 设置延迟消费级别
msg.setDelayTimeLevel(1);
// 等待存储完成后返回
msg.setWaitStoreMsgOK(true);
SendResult sendResult = producer.send(msg);
```

### Tester have restarted producer, consumer and rocketmq processor several times.

Because of scheduleMessageOffset overflow (@see mqadmin result), all of the producer which has **setDelayTimeLevel** cannot produce message in target topic, unless delay queue offset equals, e.g. ```scheduleMessageOffset_1         : 200,200```

Please feel free to contact. Thanks for your information.

**Comment by francisoliverlee** [comment]
can u reproduce it always ?

**Comment by yejiahao** [comment]
> can u reproduce it always ?

produce is ok but "topic" topic consume failed because of msg was stored in ```scheduleMessageOffset_'x'``` (x represents delayTimeLevel), it just change the offset like this

```
scheduleMessageOffset_1         : 138699,447
->
scheduleMessageOffset_1         : 138699,448
```
when it occurs
```
scheduleMessageOffset_1         : 138699,138699 (maybe 138700?)
```
the target topic consumer works normally and previous msgs also can be consumed

**Comment by francisoliverlee** [comment]
try
```
msg.setWaitStoreMsgOK(false);
```

**Comment by yejiahao** [comment]
hehe

**Comment by RongtongJin** [comment]
@yejiahao I'm sorry I closed your issue. Could you provide more detailed information such as how to reproduce this issue？
