### ISSUE TITLE
rocketmq  INFO closeChannel: close the connection to remote address[192.168.8.185:30911] result: true

### ISSUE THREAD

**Issue by wangyingdong** [apache/rocketmq#2285]
**BUG REPORT**
version：rocketmq-all-4.7.1-bin-release  dledger、rocketmq-console-ng-2.0.0.jar 、java8

**broker-n*:**
---------------------

brokerClusterName = RaftCluster
brokerName=RaftNode00
listenPort=30911
namesrvAddr=192.168.8.185:9876;192.168.8.190:9876
storePathRootDir=/tmp/rmqstore/node00
storePathCommitLog=/tmp/rmqstore/node00/commitlog
enableDLegerCommitLog=true
dLegerGroup=RaftNode00
dLegerPeers=n0-192.168.8.185:40911;n1-192.168.8.185:40912;n2-192.168.8.185:40913
dLegerSelfId=n0
sendMessageThreadPoolNums=16
brokerIP1=192.168.8.185

-----------------------

The cluster can be started，After successful startup, why does the console keep printing INFO closeChannel: 
close the connection to remote address [192.168.8.190:30931] result: true
close the connection to remote address [192.168.8.185:9876] result: true
*
*
*
close the connection to remote address [192.168.8.190:30911] result: true

thanks

**Comment by wangyingdong** [comment]
I modified the " rocketmq-console-ng-2.0.0.jar Dlogging.level.root=WARN", after startup, "close the connection to remote address [192.168.8.185:9876] result: true" did not keep printing Up. But there is a message in the log "ERROR Exception caught: mqAdminExt get broker stats data TOPIC_PUT_NUMS failed"，How can I solve this? thanks

**Comment by zongtanghu** [comment]
Any progress?

**Comment by zongtanghu** [comment]
Can you help to fix this issue? @zhangjidi2016

**Comment by zhangjidi2016** [comment]
ok

**Comment by zhangjidi2016** [comment]
1、There is a section in MQAdminExtImpl, which will shutdown MqAdminInstance and then close the channel connection after each invocation of RPC interface. The call chain is:
MQAdminInstance.destroyMQAdminInstance()->mqAdminExt.shutdown()->mqClientInstance.shutdown()->mQClientAPIImpl.shutdown()->mQClientAPIImpl.shutdown()->RemotingUtil.closeChannel(channel).
2、The reason for the "ERROR Exception caught: mqAdminExt get broker stats data TOPIC_PUT_NUMS failed"  is that the system topic was not filtered out while console dashbord was making statistics. I will submit a PR to slove this problem in rocketmq-externals.

**Comment by zongtanghu** [comment]
@zhangjidi2016  Can you put forward a pr to fix this issue? According to our discussion.

**Comment by mark4z** [comment]
> @zhangjidi2016 Can you put forward a pr to fix this issue? According to our discussion.

Maybe I can fix it.

**Comment by ConnorLH** [comment]
still there? anyone know how to fix it?

**Comment by vge-R** [comment]
一个bug 4年都没有解决办法吗

**Comment by alwyngo** [comment]
解决了吗？ 命名一直在从nameserver 更新信息，为什么会空闲超时呢？
