### ISSUE TITLE
wait response timeout 0ms

### ISSUE THREAD

**Issue by bitoceango** [apache/rocketmq#2287]
hello，Can someone help me？
When I producer message to Broker fast，i get below exception:
```
org.apache.rocketmq.client.exception.MQClientException: wait response timeout 0ms
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
  at org.apache.rocketmq.client.impl.MQClientAPIImpl$1.operationComplete(MQClientAPIImpl.java:416)
  at org.apache.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:51)
  at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:286)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

I read the source code, but did not find the reason, why is the timeout 0ms? I did not set the timeout time separately, the timeout time should be the default 3000ms.

my producer config is :

```
public class MessageProducer  {
    private DefaultMQProducer producer = new DefaultMQProducer();
    public MessageProducer() {
        producer.setNamesrvAddr("xxxxxx");
        producer.setProducerGroup("yxshi-request-copy-Group");
        try {
            producer.start();
            log.info("mq producer start success");
        } catch (MQClientException e) {
            log.error("", e);
        }
        producer.setRetryTimesWhenSendAsyncFailed(1);
    }
    public void send( Message message) {
        try {
               producer.send(message, new SendCallback() {
                @Override
                public void onSuccess(SendResult sendResult) {
                    log.info("消息发送成功,{}", sendResult);
                }
                @Override
                public void onException(Throwable e) {
                    log.error("消息发送失败,{}", e);
                }
            });
        } catch (Exception e) {
            log.error("消息发送失败", e);
        }
    }
    @PreDestroy
    public  void shutdown()throws Exception{
        producer.shutdown();
    }
}

```
Can anyone give some advice？thanks

**Comment by francisoliverlee** [comment]
@tiyxing can u do it recurrence always and how many clusters with different namesrvs ?

**Comment by tiyxing** [comment]
This exception does not necessarily occur

i have three namesrvs: 172.21.x.x:9876;rocketmq-nameserver-01-ptest.chj.cloud:9876;rocketmq-nameserver-02-ptest.chj.cloud:9876

my topic config 6 broker and every broker has 16 queue

when i config every broker  32 queue，the exception Disappeared

So I still don’t know why

**Comment by francisoliverlee** [comment]
can u show your broker config

**Comment by tiyxing** [comment]
##broker配置文件
#所属集群名字 ##变量传入，整个平台需要唯一
brokerClusterName=rocketmq-cluster-ptest
#broker名字，注意此处不同的配置文件填写的不一样##变量传入，整个集群需要唯一，
brokerName=broker-16
#0 表示 Master，>0 表示 Slave
brokerId=0
#nameServer地址，分号分割
namesrvAddr=xxxx
#在发送消息时，自动创建服务器不存在的topic，默认创建的队列数
defaultTopicQueueNums=4
#是否允许 Broker 自动创建Topic，建议线下开启，线上关闭
autoCreateTopicEnable=false
#是否允许 Broker 自动创建订阅组，建议线下开启，线上关闭
autoCreateSubscriptionGroup=true
#Broker 对外服务的监听端口
listenPort=10911
#删除文件时间点，默认凌晨 4点
deleteWhen=04
#文件保留时间，默认 48 小时
fileReservedTime=168
#commitLog每个文件的大小默认1G
mapedFileSizeCommitLog=1073741824
#ConsumeQueue每个文件默认存30W条，根据业务情况调整
#mapedFileSizeConsumeQueue=300000
#4.5.2改成了这个参数
mappedFileSizeConsumeQueue=300000
#destroyMapedFileIntervalForcibly=120000
#redeleteHangedFileInterval=120000
#检测物理文件磁盘空间
diskMaxUsedSpaceRatio=88
#存储路径
storePathRootDir=xxx
#commitLog 存储路径
storePathCommitLog=xxx
#消费队列存储路径存储路径
storePathConsumeQueue=xxxx
#消息索引存储路径
storePathIndex=xxxx
#checkpoint 文件存储路径
storeCheckpoint=xxxx
#abort 文件存储路径
abortFile=xxxxx
#限制的消息大小
maxMessageSize=1048576

#flushCommitLogLeastPages=4
#flushConsumeQueueLeastPages=2
#flushCommitLogThoroughInterval=10000
#flushConsumeQueueThoroughInterval=60000
#Broker 的角色 #变量传入，当broker类型为“同步复制/同步刷盘” 时为SYNC_MASTER；当broker类型为“异步复制/异步刷盘” 时为ASYNC_MASTER
#- ASYNC_MASTER 异步复制Master
#- SYNC_MASTER 同步双写Master
#- SLAVE
brokerRole=ASYNC_MASTER

#刷盘方式
#- ASYNC_FLUSH 异步刷盘
#- SYNC_FLUSH 同步刷盘
#变量传入，当broker类型为“同步复制/同步刷盘” 时为SYNC_FLUSH；当broker类型为“异步复制/异步刷盘”时为：ASYNC_FLUSH
flushDiskType=ASYNC_FLUSH
#checkTransactionMessageEnable=false
#发消息线程池数量
#sendMessageThreadPoolNums=128
#拉消息线程池数量
pullMessageThreadPoolNums=128

sendThreadPoolQueueCapacity = 100000
waitTimeMillsInSendQueue  = 2000
osPageCacheBusyTimeOutMills=2000
#只对异步刷盘生效
#transientStorePoolEnable=False
transientStorePoolEnable=True
transientStorePoolSize=5

#磁盘IO调优
#slaveReadEnable =true
deleteCommitLogFilesInterval = 100
deleteConsumeQueueFilesInterval=100

**Comment by lomoye** [comment]
4.3以后超时时间是动态算的了（每次会减掉中间代码的消耗时间），建议看一下源码
