### ISSUE TITLE
The question about the logic of CONSUME_FROM_TIMESTAMP

### ISSUE THREAD

**Issue by yidaimi** [apache/rocketmq#2292]
使用CONSUME_FROM_TIMESTAMP的时候遇到了相关问题，详情见：https://github.com/apache/rocketmq/issues/2286

感谢大佬回复，根据大佬给的链接，我仔细研究了一下。我理解CONSUM_FROM_TIMESTAMP的逻辑是：
1.先找当前consumergroup在这个queue上的最新offset
2.如果没找到就去找这个queue当前的最早offset(这个offset就是consumerqueue文件组中最早的那个文件的第一个offset，也就是在磁盘上这个queue中最早的那个offset)
3.要是以上都没有再去按照timestamp去定位到哪个consumequeue文件，再在这个文件中通过折半查找去定位到匹配的timestamp的offset。
但是这个逻辑似乎是不是永远都走不到3？因为2的consumequeue文件应该永远都会有的吧？另外，要是没consumequeue文件的话，3也没有意义呀？请问什么情况才能走到3呢？

另外，我看链接中的解决方案也是通过cloneoffset方法，让新的consumergroup从其他consumergroup中把offset拷贝过来。让它最终能走1.
请问什么时候才能真正走到根据timestamp去查找offset的第3步呢？

谢谢！

_Originally posted by @yidaimi in https://github.com/apache/rocketmq/issues/2286#issuecomment-688567779_

**Comment by francisoliverlee** [comment]
@yidaimi do you have ideas to make it right ❓

**Comment by yidaimi** [comment]
In my opion, should we remove step 2 to fix it?
The new steps should be like this:
1. try to get the offset in consumequeue group.
2.if not, try to get the first offset in the consumequeue. (remove this step)
3.if not, just search the offset timestamp by binary search.
So I think it will work correctly.

**Comment by francisoliverlee** [comment]
what if no any offset from timestamp, such as file broken

**Comment by EZLippi** [comment]
> what if no any offset from timestamp, such as file broken

then searchOffSet will return 0
1. get offset from ConsumerOffsetManager, if >=0 , return to client
2. return -1 to client if no offset exist
3. client search offset by timestamp, if exist return offset, if not return 0

so there is no lost by removing step 2

**Comment by illiqiang** [comment]
这个设计太不友好了

**Comment by wz2cool** [comment]
emmm... meet the same problem , need a way to set offset to get latest messages.
@RongtongJin could you help to have a look

**Comment by wz2cool** [comment]
@yidaimi  this link may help you https://www.jianshu.com/p/1e9cb83e47a3,

**Comment by Git-Yang** [comment]
There is no the logic to return minOffset.（In the second step you gave）
