### ISSUE TITLE
vm.extra_free_kbytes 和 warmMapedFileEnable 问题

### ISSUE THREAD

**Issue by RongNanNan** [apache/rocketmq#2296]
服务异常出现busy问题，报错：cost in lock ...

**Comment by RongNanNan** [comment]
该部分代码就是写pagecache，为啥这么慢
目前有2个方向：
1. 可用内存过小，突然的大内存申请，导致后台内存回收，慢导致延迟，调整vm.extra_free_kbytes能否解决？
2. 提前锁定内存warmMapedFileEnable 开启，是否能解决问题？

**Comment by RongtongJin** [comment]
You can execute the distribution/bin/os.sh Script to optimize the operating system configuration, but the specific tuning parameters still depend on the specific machine configuration.

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
