### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by wushaolin1020** [apache/rocketmq#2304]
I'm new developer, how to learn

**Comment by RongtongJin** [comment]
Welcome to the RocketMQ community. You can start by reading the [document](https://github.com/apache/rocketmq/tree/master/docs) or starting with quick start on the [official website](http://rocketmq.apache.org/docs/quick-start/).

In addition, Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
