### ISSUE TITLE
Dynamically configure  broker configuration parameters without restarting the broker

### ISSUE THREAD

**Issue by trntaken** [apache/rocketmq#2305]
1. Please describe the feature you are requesting.
   
 Dynamically configure  broker configuration parameters without restarting the broker,sush as threadpool num, queue capacity,flush disk type and so on.  We can register dynamically parameters to namesrv，We can modify the dynamically parameters in namesrv，The broker will periodically pull dynamic parameters from namesrv，If the broker finds that the parameters have changed, then it will modify its own parameters.

2. Provide any additional detail on your proposed use case for this feature.

No need to restart, we can dynamically adjust broker parameters，This is very helpful for our testing and production verification.

**Comment by RongtongJin** [comment]
You can use updateBrokerConfig command with admin tool.
