### ISSUE TITLE
Broker does not support initiating registration to a newly created nameserver

### ISSUE THREAD

**Issue by stheart** [apache/rocketmq#2310]
**Question**

we use rocketmq-operator to deploy in k8s,found that when up-scale name server cluster,broker will restart one by one.

I check the broker code, it seems that broker can't refresh name server address list automatic when add new name server pod, so operator has to restart all broker.

**FEATURE REQUEST**

broker support reload name server address when add name server pod.

for example
1.broker provide api  to  refresh name server address
2.we can custom the rocketmq-operator , push the new name server address to broker api  when add new nameserver pod.

**Comment by RongtongJin** [comment]
Hi @stheart,  please open an issue in the RocketMQ Operator repository. 

I will close the Issue first, but please feel free to reopen it if you have any other issues.
