### ISSUE TITLE
CONSUME_FROM_TIMESTAMP support 

### ISSUE THREAD

**Issue by GauravVect** [apache/rocketmq#2313]
I am using cpp client of rocketMQ  and want to use the feature CONSUME_FROM_TIMESTAMP.
So,I want to know how to pass the timestamp to the consumer object and also should it be in secs or milli seconds.

**Comment by imaffe** [comment]
For general questions, we suggest using the dev maillist instead. Issues are used to record bugs and enhancements only, so feel free to raise questions in dev list and I'll close this issue for now~

**Comment by vongosling** [comment]
Paste from my reply for you.

CONSUME_FROM_TIMESTAMP does not work in cpp client.  Enabling this parameter brings heavy risks in case of some abuse
