### ISSUE TITLE
viewMessage error when broker IP changed

### ISSUE THREAD

**Issue by 8da2k** [apache/rocketmq#2317]
Our services are deployed in containers, broker IP will change after docker restart. An exception occurs when we query for old messages. Is there a good solution for this problem?

**Comment by RongtongJin** [comment]
You can configure a VIP for the broker container and specify it in brokerIP1 / broker P2. Or query nameserver every time to get the current IP address of the broker.

**Comment by RongtongJin** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
