### ISSUE TITLE
rocketmq中如何序列化LocalDateTime

### ISSUE THREAD

**Issue by handsight** [apache/rocketmq#2318]
“xxxx”:{
        "month":"SEPTEMBER",
        "year":2020,
        "dayOfMonth":26,
        "hour":11,
        "minute":13,
        "monthValue":9,
        "nano":190000000,
        "second":57,
        "dayOfWeek":"SATURDAY",
        "dayOfYear":270,
        "chronology":{
            "id":"ISO",
            "calendarType":"iso8601"
        }
    }

**Comment by handsight** [comment]
rocketmq发送一个实体类消息，实体类里面某个字段包含LocalDateTime    消息到了消息服务器以后就变成上面这种了

**Comment by handsight** [comment]
rocketmq 版本号4.5.2

**Comment by zzq0324** [comment]
请教下怎么解决的？我这边也出现了

**Comment by HK-hub** [comment]
升级版本依赖，官方已经解决了
