### ISSUE TITLE
rocketmq  -XX:MaxDirectMemorySize is invalid

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#2321]
rocketmq version:4.7.1   system :linux    16C 32G。

I set -XX:MaxDirectMemorySize =3g in runbroker.sh，but The memory occupied by rocketmq continues to increase until it occupies most of the system memory。

Use the top command to see that the SHR is much larger than 3g.

**Comment by RongtongJin** [comment]
-XX:MaxDirectMemorySize can not restrict RocketMQ from using page cache, but can only restrict the use of direct memory. For example, when  transientStorePoolEnable is true in broker's config, this parameter will limit the size of direct memory.
