### ISSUE TITLE
why the list type is different ,is this a bug ?

### ISSUE THREAD

**Issue by rookieBirdOne** [apache/rocketmq#2325]
![image](https://user-images.githubusercontent.com/18139807/94386730-edab5a80-017a-11eb-87fe-8383be491a80.png)
![image](https://user-images.githubusercontent.com/18139807/94386713-e84e1000-017a-11eb-9a5f-96873f3ac932.png)
![image](https://user-images.githubusercontent.com/18139807/94386740-f0a64b00-017a-11eb-9ae7-6cf6045a9134.png)

class :BrokerOuterAPI
method:registerBrokerAll. vs.  needRegister

question: is it safe when method:registerBrokerAll invoke ?

**Comment by medusar** [comment]
It is not thread safe, it is a bug.

**Comment by RongtongJin** [comment]
Could you submit a PR to fix it?  I am willing to follow it.

**Comment by medusar** [comment]
I have created [a PR](https://github.com/apache/rocketmq/pull/2326) for this.
