### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by ankuo** [apache/rocketmq#2331]
hello，Will adding and removing a consumer be considered in future releases

**Comment by RongtongJin** [comment]
I can't understand what you mean.

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
