### ISSUE TITLE
logback error

### ISSUE THREAD

**Issue by hachihub** [apache/rocketmq#2332]
help,I get exception:

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.apache.rocketmq.client.log.ClientLogger
	at org.apache.rocketmq.client.producer.DefaultMQProducer.<init>(DefaultMQProducer.java:63)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.<init>(DefaultMQProducer.java:145)
	at com.maoge.demo.ProducerDemo.main(ProducerDemo.java:9)

logback.xml:

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="mqAppender1" class="org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender">
        <tag>TagA</tag>
        <topic>01_test</topic>
        <producerGroup>group1</producerGroup>
        <nameServerAddress>127.0.0.1:9876</nameServerAddress>
        <layout>
            <pattern>%date %p %t - %m%n</pattern>
        </layout>
    </appender>
    <appender name="mqAsyncAppender1" class="ch.qos.logback.classic.AsyncAppender">
        <queueSize>1024</queueSize>
        <discardingThreshold>80</discardingThreshold>
        <maxFlushTime>2000</maxFlushTime>
        <neverBlock>true</neverBlock>
        <appender-ref ref="mqAppender1"/>
    </appender>
    <root>
        <level value="debug"/>
        <appender-ref ref="mqAppender1"/>
    </root>
    <logger name="testLogger" level="debug" additivity="true">
        <appender-ref ref="mqAppender1"/>
    </logger>
</configuration>

**Comment by RongtongJin** [comment]
Please check if it is due to maven dependency
