### ISSUE TITLE
The parameter commitLeastPages is never used

### ISSUE THREAD

**Issue by spiritsx** [apache/rocketmq#2338]
The method 'commit0' of class 'MappedFile' have a parameter 'commitLeastPages'，but it never used from version 4.5.1(we used) to 4.7.1(the latest)。
I guess the paramter is used for judge whether to commit that depends on the result 'writePos - this.committedPosition.get()'，maybe it looks like ‘writePos - this.committedPosition.get() > commitLeastPages ’。Now the code is 'writePos - this.committedPosition.get() > 0'。
By the way，I think the local variable lastCommittedPosition can replace 'this.committedPosition.get()' In the above inequality。
Do you think so?
![issue](https://user-images.githubusercontent.com/30772323/95434824-4f8e7000-0984-11eb-9507-800689e1f637.png)

**Comment by RongtongJin** [comment]
I think you are right. You can submit a pr to fix the issue.

**Comment by spiritsx** [comment]
> I think you are right. You can submit a pr to fix the issue.

Thanks for your affirmation。The pr was created。

**Comment by CleverZiv** [comment]
Hello, I have a question about this:
commitLeastPages and writePos - lastCommittedPosition are two-dimensional variables，why this judgment can achieve the purpose that determine whether to commit or not?
by the way, the method MappedFile#isAbleToCommit has similar logic, the code:

        int flush = this.committedPosition.get();
        int write = this.wrotePosition.get();
        ...
        if (commitLeastPages > 0) {
            return ((write / OS_PAGE_SIZE) - (flush / OS_PAGE_SIZE)) >= commitLeastPages;
        }
I mean write / OS_PAGE_SIZE and commitLeastPages are the same dimensional variables
Looking forward to your reply， thank you~
