### ISSUE TITLE
消费者不主动消费信息，之只能通过控制台手动点击消费才可以

### ISSUE THREAD

**Issue by YAGAMIL** [apache/rocketmq#2339]
我的一个spring-boot应用需要消费两个topic，其中一个需要广播，另一个topic则负载均衡即可，如图所示。
![image](https://user-images.githubusercontent.com/16757285/95534639-ef95d900-0a18-11eb-9a44-dcff8971e540.png)
我有三个消费者组，每一个消费者组都对应一个单独的topic，分别如下
DemoMqListener：
![image](https://user-images.githubusercontent.com/16757285/95534704-118f5b80-0a19-11eb-8496-fe9b8bd51e72.png)
Topic4SingleMeddleConsumerTopic4SingleMeddleConsumer：
![image](https://user-images.githubusercontent.com/16757285/95534740-2c61d000-0a19-11eb-91f1-e89f5f948ff4.png)

Topic4SingleRunConsumer
![image](https://user-images.githubusercontent.com/16757285/95534790-4bf8f880-0a19-11eb-941b-ac16a4071716.png)

但是当消息发送成功后，该springboot应用并不能主动消费消息，而在rocketMQ的控制台中，则可以看到
![image](https://user-images.githubusercontent.com/16757285/95534877-8ebad080-0a19-11eb-9ba2-972402025935.png)
点开消息详情后，我可以通过点击“resend Message”来手动消费，这样的话我的springboot应用就可以消费到该消息，但还有一点奇怪的是，名称为“consumer-group”的消费者组是我的测试消费，它只订阅了test-topic，但它却可以消费到topic-task:all-single这条topic的信息，如果同样混乱，但TASK_MEDDLE_CONSUMER_GROUP_NAME的消费者组却不能消费到topic-task的信息，这让我很迷惑，而且我的所有应用都没有接收到消息，但控制台已经提示应该resend了，但我手动点击resend的时候，我的应用才真正接收到了消息

**Comment by YAGAMIL** [comment]
我找到问题了，当我把Topic4SingleRunConsumer类中的注解改为字符串而非常量的时候，启动后就可以主动消费到信息了，如下所示：
![image](https://user-images.githubusercontent.com/16757285/95539507-2243cf80-0a21-11eb-8436-192bd1cfa309.png)
而原本是这样
![image](https://user-images.githubusercontent.com/16757285/95539542-3b4c8080-0a21-11eb-8622-55cbb8d89947.png)
这样的话可以消费到，但问题是，这两个内容完全一样，出了一个使用了常量名一个直接用字符串值，没有任何区别，其次，如果他们两个不等同，那么我用常量名赋值的时候，虽然不能主动消费到信息，但我在控制台中resend Message却可以手动消费到，重发消息后收到消息的也确实是Topic4SingleRunConsumer类，这也太奇怪了吧

**Comment by vongosling** [comment]
Maybe the annotation processor problem. BTW, you should use the community maintained RocketMQ Spring(https://github.com/apache/rocketmq-spring), while not do it by yourself. If the problem still exists, please issue it in its issue parts(https://github.com/apache/rocketmq-spring/issues).

p.s please notice your issue topic, do not use non-English.
