### ISSUE TITLE
Could you provide some logs to find out reasons？

### ISSUE THREAD

**Issue by yliml** [apache/rocketmq#2340]
Could you provide some logs to find out reasons？

_Originally posted by @RongtongJin in https://github.com/apache/rocketmq/issue_comments/576231572_

**Comment by vongosling** [comment]
I could not find your issue link.

**Comment by yliml** [comment]
<img width="829" alt="mqerror" src="https://user-images.githubusercontent.com/29296892/95536724-40f49700-0a1e-11eb-9e94-cb7b05b3dd25.png">




> I could not find your issue link.

**Comment by yliml** [comment]
@vongosling @RongtongJin 请看下，也是偶发现象，但是这样消息就不可靠了

**Comment by yliml** [comment]
> I could not find your issue link.

问题已补充完整，如有问题建议，请大神回复下

**Comment by CoderMudy** [comment]
这解决了吗就close了
