### ISSUE TITLE
DefaultMQProducerImpl request response timeout

### ISSUE THREAD

**Issue by xtechlife** [apache/rocketmq#2348]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:
call DefaultMQProducerImpl.request method, execute DefaultMQProducerImpl.waitResponse throw 
org.apache.rocketmq.client.exception.RequestTimeoutException:

org.apache.rocketmq.client.exception.RequestTimeoutException: CODE: 10006  DESC: send request message to <xxxxxxx> OK, but wait reply message timeout, 10000 ms.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.waitResponse(DefaultMQProducerImpl.java:1495)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.request(DefaultMQProducerImpl.java:1371)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.request(DefaultMQProducer.java:589)

2. Please tell us about your environment:
server: 4.6.0
client: 4.7.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by RongtongJin** [comment]
Have you tried to upgrade the version of the rocketmq broker and reproduce the same issue ？
