### ISSUE TITLE
OrderProducer send ordered message throw defaultMQProducer send order exception

### ISSUE THREAD

**Issue by yliml** [apache/rocketmq#2349]
_Originally posted in https://github.com/apache/rocketmq/issues/2340
具体原因如图：
<img width="829" alt="mqerror" src="https://user-images.githubusercontent.com/29296892/95536724-40f49700-0a1e-11eb-9e94-cb7b05b3dd25.png">

**Comment by RongtongJin** [comment]
我发现你提交了多次issue，但这些日志信息无法断定具体原因的。remoting 层的 timeout有很多原因，特别是偶发的情况，有可能是网络存在问题，有可能是broker端响应慢，具体需要对日志进行检查，用工具对网络等原因进行排查。

**Comment by yliml** [comment]
> 我发现你提交了多次issue，但这些日志信息无法断定具体原因的。remoting 层的 timeout有很多原因，特别是偶发的情况，有可能是网络存在问题，有可能是broker端响应慢，具体需要对日志进行检查，用工具对网络等原因进行排查。

之前提交是因为我原因还没编辑完，就被关闭了，你看我之前的issue看的到。
这个问题是偶发的，但是这个问题却是致命的，不是高可用的

**Comment by vongosling** [comment]
This is a cloud-managed service, you could open a ticket in a cloud provider to check the service.
