### ISSUE TITLE
[enhancement]support different topic in a messageBatch

### ISSUE THREAD

**Issue by xianyouQ** [apache/rocketmq#2352]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
support different topic in a messageBatch

we are using [ddmq](https://github.com/didi/DDMQ) as a rocketmq proxy to manager topic and sub relationships, but now we find ddmq needs rocketmq to support multiple topic in a messagebatch(of course you must have noticed than didi changed rocketmq source code to support this feature). is there any plan to support this?

**Comment by RongtongJin** [comment]
There is no such plan for the time being

**Comment by vongosling** [comment]
It is not a good practice tor union many topics in one message batch operation.
