### ISSUE TITLE
The issue of repeated consumption of brokers under different domain names

### ISSUE THREAD

**Issue by cookiejoo** [apache/rocketmq#2353]
你好！
我们这有个场景是：
目前MQ有两个域名的nameServer，域名A下有A/B/C三个broker；域名B下有D/E/F三个broker. 是机房不同的原因要分两个域名。
应用也是连接这两个nameServer，使用也是正常的。由于机房不稳定的原因，决定要应用在A 、 B机房各个应用连各的集群下nameServer，所以得做变更。
变更方式是在A机房的应用连接A域名的nameServer，在B机房的连接B域名的nameServer。
我们决定找几个应用各选一台A B集群的机器换掉nameServer试试看，是否能正常消费正常发送。
xxx-app应用有8台机器，4台在A集群 4台在B集群，各选A&B一台机器把nameServer改成各自连各自的（原本是A-1和B-1机器配置nameServerd=域名A;域名B，现在是A-1机器配置nameServerd= 域名A；B-1机器配置nameServerd=域名B）。

现在发现一个问题是A-1和B-1机器在同一个时间有消费重复问题，一条消息在A-1中消费了2次。发现问题后切回去原来的连接A&B集群这个重复消费又没有发生了。

我们已经有用一个应用来测试全部机器都切换重启则没有发现重复消费问题。

怀疑是client端对域名解析的nameServer检测出存在不同的连接解析，具体的也没想出个原因来。

所有问一下这个情况是否存在问题，还是说必须要一起切换才行？而不是只切换某台机器？
盼回复解惑，感谢！

**Comment by gaoyf** [comment]
你的描述看起来比较混乱，建议梳理一下：
1. 有几个broker集群？
2. broker的配置是怎么样的？
3. broker所属的nameser集群是怎样的？
4. 出问题的topic建在哪个集群上？
5. 客户端连接的是哪个集群或者客户端配置？
