### ISSUE TITLE
Are the message dealyed in the Console-NG?

### ISSUE THREAD

**Issue by andyhewenhui** [apache/rocketmq#2356]
We used poll mode and  function that is litePullConsumer.poll()  in rocketmq 4.7.1.   The Console-NG was showed delay from 85 to 200 by amount.  We don't confirm whether  they  were  correct or issue.

**Comment by RongtongJin** [comment]
So is there really an accumulation of message？ 85 to 200 doesn't seem to be a lot.

**Comment by andyhewenhui** [comment]
OK，we will keep checking some problems.
