### ISSUE TITLE
在依赖netty的时候，由于rocketmq里面用的是netty-all，建议使用netty-common等

### ISSUE THREAD

**Issue by cnhans** [apache/rocketmq#236]
原因：
1、使用了netty-all后，直接把项目绑定在了netty-all的jar依赖
2、项目里面是有了es时，es依赖的netty是netty-common等这样的分散式依赖，按需加载的方式，直接产生了一个集成问题，双方的netty的jar不一致，会引发同一个类，使用的jar不一样，即使你把netty-all去除了，rocketmq同样不能使用netty-common里面的类，比如：java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1
3、最后只能对rocketmq的common或者client，all进行重新自行打包，这个体验非常不好
4、或者采用其他类似的mq进行使用。

谢谢！

**Comment by zhouxinyu** [comment]
Please **respect** our [issue template](https://github.com/apache/rocketmq/blob/master/.github/ISSUE_TEMPLATE.md) and remember the issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**Comment by perist** [comment]
怎么解决呢？最后只能对rocketmq的common或者client，all进行重新自行打包，这个体验非常不好？自行打包吗，还是把netty-all给干掉，手动引入netty-common等包
