### ISSUE TITLE
RocketMQLog:WARN Please initialize the logger system properly.

### ISSUE THREAD

**Issue by Shanbw** [apache/rocketmq#2363]
![image](https://user-images.githubusercontent.com/44198215/96549199-bfd0b600-12e1-11eb-8e7d-d90c969c07ae.png)
想问下这个提示是什么意思，对我们有什么影响，要怎么解决？谢谢
版本是4.7.1，我们之前使用4.3.2版本没有这个提示

**Comment by RongtongJin** [comment]
没有任何影响。就是IDE找不到log的配置文件。我将先关闭这个issue，issue主要是用来跟踪bug和feature的。你可以再邮件列表提问，感谢。

**Comment by wodegyk** [comment]
所以这个是怎么配置呢

**Comment by YuHangZM** [comment]
大哥，怎么解决？别一句话就把人打发了

**Comment by liangliangoo** [comment]
如何解决呢？

**Comment by eat-the-red-pill** [comment]
https://github.com/apache/rocketmq/pull/4001
