### ISSUE TITLE
Some classes need to be introduced when the client SDK uses ACL

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#2365]
When the client SDK is introduced, the SessionCredentials and AclClientRPCHook class is required. Since SessionCredentials and AclClientRPCHook class is in the common directory of the rocketmq-acl module, the rocketmq-acl module needs to be introduced again.
![image](https://user-images.githubusercontent.com/30995057/96575160-fd920680-1302-11eb-88b9-dfe69c68997e.png)

May I be allowed to move SessionCredentials and AclClientRPCHook class to rocketmq-common module? 
Or add rocketmq-acl module in rocketmq-client pom file.

**Comment by RongtongJin** [comment]
Why not introduce rocketmq-acl module and rocketmq-client module together in your project?

**Comment by Git-Yang** [comment]
> Why not introduce rocketmq-acl module and rocketmq-client module together in your project?

ACL is more commonly used in the rocketmq-client module, so it is more convenient to put these two classes into the rocketmq-common module or introduce the rocketmq-client module to the rocketmq-client module.
