### ISSUE TITLE
[Consumer] There is a non-thread-safe operating when RocketMQ send expired message

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq#2369]
**BUG REPORT**

1. Please describe the issue you observed:
**I think this is a non-thread-safe operationg.Because the collection is shared by multiThread,In this case,we use read-lock to make sure we get a thread-safe object reference,but we do not supply thread-safe for send operating.**

![RocketMQ_1](https://user-images.githubusercontent.com/18530950/96678999-67fb8300-13a5-11eb-8b7f-95cd820c1267.png)

**If this is a issue,may I submit a PR to fix it?**

**Comment by shenhui0509** [comment]
The `sendMessageBack` method is indeed thread-safe

**Comment by lizhiboo** [comment]
> **BUG REPORT**
> 
> 1. Please describe the issue you observed:
>    **I think this is a non-thread-safe operationg.Because the collection is shared by multiThread,In this case,we use read-lock to make sure we get a thread-safe object reference,but we do not supply thread-safe for send operating.**
> 
> ![RocketMQ_1](https://user-images.githubusercontent.com/18530950/96678999-67fb8300-13a5-11eb-8b7f-95cd820c1267.png)
> 
> **If this is a issue,may I submit a PR to fix it?**

Which collection is shared? If it only read by multi thread, i think it does matter.
