### ISSUE TITLE
safe question

### ISSUE THREAD

**Issue by SecLoop** [apache/rocketmq#2371]
```
First of all

    url  -->http://ip/#/producer

Secondly

      choose on Topic

Next step

Enter <script>alert("XSS")</script> characters in the ProducerGroup function
``` 

![image](https://user-images.githubusercontent.com/15940596/96705231-97bb8280-13c7-11eb-92dd-b43f77fb8354.png)

**Comment by RongtongJin** [comment]
Could you submit a issue to [console poject](https://github.com/apache/rocketmq-externals/issues) and submit a pr to fix the issue?

**Comment by RongtongJin** [comment]
I will close the issue first in rocketmq main repo.
