### ISSUE TITLE
 [Consumer] There is a wrong spell in MQClientAPIImpl

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq#2372]
1. Please describe the issue you observed:
   I think it shoule be a  method called **"sendHeartbeat"** 
![rocketMQ_2](https://user-images.githubusercontent.com/18530950/96804429-8dd66580-1441-11eb-8bf3-068da41f014c.png)

If this is an issue,may I sumbit a PR to fix it?

**Comment by RongtongJin** [comment]
Of course.
