### ISSUE TITLE
remove unnecessary parameter dataTopic  for method AsyncTraceDispatcher.sendTraceDataByMQ 

### ISSUE THREAD

**Issue by chenliuyang1989** [apache/rocketmq#2375]
1. we have defined the traceTopicName In the construction method
   
![image](https://user-images.githubusercontent.com/4150132/96994956-0895a280-1560-11eb-86cf-99fd3be8c19b.png)

2. no need to pass unused param dataTopic again at AsyncTraceDispatcher.sendTraceDataByMQ 
 
![image](https://user-images.githubusercontent.com/4150132/96995104-409ce580-1560-11eb-9460-1b8f53aa86f7.png)

can i remove this unused param？

**Comment by duhenglucky** [comment]
@chenliuyang1989 thanks for your advice, but actually maybe this function and this parameter has been used by other users.
but a discussion is welcome.

**Comment by chenliuyang1989** [comment]
![image](https://user-images.githubusercontent.com/4150132/98344959-f41cd400-204e-11eb-8bc7-ed0684d6f502.png)

Please find my screenshot，the traceTopic is not defined by dataTopic，so dataTopic is not used anymore in method sendTraceDataByMQ，i think we can remove this param

**Comment by chenliuyang1989** [comment]
no response
