### ISSUE TITLE
IS that tps is OK?

### ISSUE THREAD

**Issue by caijianying** [apache/rocketmq#2379]
#Topic                            #Consumer Group                  #Accumulation      #InTPS     #OutTPS   #InMsg24Hour  #OutMsg24Hour
TopicTest                         _MQ_CONSUMER_                              13                75.42       75.42         118959         118959

Is the value of ROCketMQ TPS for sending and receiving messages at 100 megabytes of bandwidth normal?

**Comment by RongtongJin** [comment]
Is it normal to rely on many situations.

Issues are generally used for bug reports and feature requests, so if you have any questions about Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
