### ISSUE TITLE
[bug]Data loss found during data writing

### ISSUE THREAD

**Issue by MrYueQ** [apache/rocketmq#2382]
### environment

| 序号 | 组件名称 | 组件版本 |
| :---: | :--- | :--- |
| 1 | canal | canal.deployer-1.1.4
| 2 | mysql |  5.6.40-log MySQL Community Server (GPL)
| 3| rocketmq | V4_2_0_SNAPSHOT
| 4 | system |  3.10.0-862.14.4.el7.x86_64 

### question
For the convenience of description, the abnormal topic is named *A*. The normal topic is named *b*。 
Use the same data source, consumed by two canal instances into two topics，At a certain point in time, operating the database produced 23 records. In the rocketmq control interface, you can see that *A* has received 3 messages. *B* 23 messages received.

- *A* is the topic just created
- *B* is has been running for a while

**Comment by RongtongJin** [comment]
What consumption model is used? It may be related to the setting of the initial consume offset. In addition, it is recommended to upgrade to the latest version of rocketmq.
