### ISSUE TITLE
rocketmq4.7.1   gc time is very long

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#2387]
version ：rocketmq 4.7.1
JVM parameters ：default

I found that occasionally a very long time gc，like this：
2020-10-29T17:07:57.508+0800: 871.963: Total time for which application threads were stopped: 37.5596741 seconds, Stopping threads took: 37.5579624 seconds
2020-10-29T17:08:12.697+0800: 887.152: Total time for which application threads were stopped: 14.1885502 seconds, Stopping threads took: 14.1863841 seconds

**Comment by RongtongJin** [comment]
Could you provide more detailed information and description?

**Comment by zhaohai1299002788** [comment]
Can you provide detailed gc logs and dump files ？

**Comment by iamqq23ue** [comment]
2020-10-29T17:07:57.508+0800: 871.963: Total time for which application threads were stopped: 37.5596741 seconds, Stopping threads took: 37.5579624 seconds
2020-10-29T17:08:12.697+0800: 887.152: Total time for which application threads were stopped: 14.1885502 seconds, Stopping threads took: 14.1863841 seconds




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] rocketmq4.7.1   gc time is very long (#2387)





 
Can you provide detailed gc logs and dump files ？

**Comment by yzezzm** [comment]
@iamqq23ue maybe a long time pagefault cause this! related to  gc safepoint!
http://mail-archives.apache.org/mod_mbox/cassandra-user/201610.mbox/%3CCACr06N0_DEVK54wkiCa-onoCHGsex+RkXBrDNAmJtsuHUDXGEA@mail.gmail.com%3E

**Comment by vongosling** [comment]
You seem to have encountered an interesting question. Is it related to Cassandra? Welcome to summarize and contact us, contribute to the RocketMQ WeChat official account.

**Comment by iamqq23ue** [comment]
How to contact the rocketmq wechat official account？


For this problem, I suspect usereentrantlockwhenputmessage = true works. After I set this parameter, I don't encounter a long time GC.

**Comment by duhenglucky** [comment]
> How to contact the rocketmq wechat official account？ For this problem, I suspect usereentrantlockwhenputmessage = true works. After I set this parameter, I don't encounter a long time GC. Message ID: ***@***.***&gt;

Welcome to add WeChat ID：rocketmq666
