### ISSUE TITLE
Determine the return value with sending result of the transaction message

### ISSUE THREAD

**Issue by dasonXu** [apache/rocketmq#2388]
The working mode of the  transaction message is：

1.producer.sendMessageInTransaction()
2.transactionListener.executeLocalTransaction()
3.then base the result of transactionListener.executeLocalTransaction() do commit or rollback.

but now, when i execute producer.sendMessageInTransaction(), i want to know the result of transactionListener.executeLocalTransaction() to return interface caller success or not.is there any good implement ？

**Comment by lizhiboo** [comment]
> sendMessageInTransaction

IMO, try to use transactionListener.checkLocalTransaction() to get result.
