### ISSUE TITLE
In org.apache.rocketmq.store.ConsumeQueue, we can use only log.warn(...) or LOG_ERROR.warn(...) to record warning messages 

### ISSUE THREAD

**Issue by em010272** [apache/rocketmq#2393]
package org.apache.rocketmq.store;
public class ConsumeQueue {
......
    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);
    private static final Logger LOG_ERROR = LoggerFactory.getLogger(LoggerName.STORE_ERROR_LOGGER_NAME);
    private boolean putMessagePositionInfo(final long offset, final int size, final long tagsCode,
		   final long cqOffset) {
		if (cqOffset != 0) {
			long currentLogicOffset = mappedFile.getWrotePosition() + mappedFile.getFileFromOffset();

			if (expectLogicOffset < currentLogicOffset) {
				log.warn("Build  consume queue repeatedly, expectLogicOffset: {} currentLogicOffset: {} Topic: {} QID: {} Diff: {}",
					expectLogicOffset, currentLogicOffset, this.topic, this.queueId, expectLogicOffset - currentLogicOffset);
				return true;
			}

			if (expectLogicOffset != currentLogicOffset) {
				LOG_ERROR.warn(
					"[BUG]logic queue order maybe wrong, expectLogicOffset: {} currentLogicOffset: {} Topic: {} QID: {} Diff: {}",
					expectLogicOffset,
					currentLogicOffset,
					this.topic,
					this.queueId,
					expectLogicOffset - currentLogicOffset
				);
			}
		}
......
    }		
There are log.warn(...) and LOG_ERROR.warn(...) recording warning messages.
We can only log.warn(...) or LOG_ERROR.warn(...) to record warning messages

**Comment by RongtongJin** [comment]
log.warn will write to ~/logs/rocketmqlogs/store.log and LOG_ERROR.warn will write to ~/logs//rocketmqlogs/storeeroor.log. Separating two logs can help with troubleshooting.
