### ISSUE TITLE
Cannot run RocketMQ 4.7.1: Unrecognized VM option 'UseConcMarkSweepGC'

### ISSUE THREAD

**Issue by jahio** [apache/rocketmq#2395]
**BUG REPORT**

1. Please describe the issue you observed:

I downloaded the built release of RocketMQ 4.7.1 from https://rocketmq.apache.org/docs/quick-start/ and tried to start it according to the docs at the same page. Instead of the `mqnamesrv` program running, it exits and `nohup.txt` claims there's an unrecognized java option: `Unrecognized VM option 'UseConcMarkSweepGC'`

- What did you do (The steps to reproduce)?

```
$ pwd
/Users/jah/Downloads/rocketmq-all-4.7.1-bin-release
$ nohup bin/mqnamesrv &
[1] 9273
appending output to nohup.out
[1]  + 9273 exit 1     nohup bin/mqnamesrv
$ cat nohup.out
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

- What did you expect to see?
Something indicating the server started successfully.

- What did you see instead?
Unrecognized VM option: 'UseConcMarkSweepGC'

2. Please tell us about your environment:

```
$ java -version
java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home
$ uname -a
Darwin nova.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

I tried "hacking" the bin/runserver.sh script to just remove the unrecognized option (I don't need this working in prod, just for local development) but additional unrecognized options were found, so I kept removing them until eventually the program just plain wouldn't start and gave me some weird fatal error in a file I've since deleted. Apparently hacking away at the unknown options is _not_ the way to fix it, who knew ;P

**Comment by RongtongJin** [comment]
@jahio You are right.  There are some problems when using scripts to start rocketmq with jdk15.  At present, it is better to use jdk8.

**Comment by minhhungit** [comment]
getting this issue with jdk-18.0.1

**Comment by JaspreetKaur0410** [comment]
I am getting the same issue with java version "17.0.1"
