### ISSUE TITLE
rocketmq_architecture_3.png Error on producer cluster

### ISSUE THREAD

**Issue by fyeeme** [apache/rocketmq#2396]
![alt 属性文本](https://github.com/apache/rocketmq/blob/master/docs/cn/image/rocketmq_architecture_3.png?raw=true)

**BUG REPORT**

1.  producer cluster in this picture is error draw. 
of of the cluster should be producer, but the third one is consumer

**Comment by RongtongJin** [comment]
Good catch! We will fix it ASAP. Or could you submit a pr to fix it?

**Comment by ShannonDing** [comment]
link new PR #2688
