### ISSUE TITLE
When DefaultMQProducer is initialized, there is a risk of thread exhaustion in high concurrency situations

### ISSUE THREAD

**Issue by wangchongyang007** [apache/rocketmq#2397]
When the same groupName of  DefaultMQProducer are initialized multiple times, Even if it fails, and three threads are still generated.

Tread1: ClientHouseKeepingService (It is  a daemon)
Tread2: AsyncAppender-Dispatcher-Thread
Tread3: RequestHouseKeepingService

And they will never be destroyed.

Developers should be reminded that thread-safe and single-instance use of it. Or fix it.

Scene recurrence:

    public static void main(String[] args) {

        ThreadPoolExecutor asyncSenderExecutor = new ThreadPoolExecutor(
                10, 10, 1000 * 60, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(500000),
                new ThreadFactory() {
                    private AtomicInteger threadIndex = new AtomicInteger(0);

                    @Override
                    public Thread newThread(Runnable r) {
                        return new Thread(r, "test111" + this.threadIndex.incrementAndGet());
                    }
                });

        for (int i = 0; i < 50; i++) {
            asyncSenderExecutor.submit(new Runnable() {
                @Override
                public void run() {
                    createMqProducer();
                }
            });
        }
        try {
            Thread.sleep(20000000000L);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    public static DefaultMQProducer createMqProducer() {
        DefaultMQProducer producer = new DefaultMQProducer("w222");
        producer.setNamesrvAddr("192.168.0.22:9876");
        producer.setRetryTimesWhenSendAsyncFailed(2);
        producer.setSendMsgTimeout(50000);

        ThreadPoolExecutor asyncSenderExecutor = new ThreadPoolExecutor(
                8, 8, 1000 * 60, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(500000),
                new ThreadFactory() {
                    private AtomicInteger threadIndex = new AtomicInteger(0);

                    @Override
                    public Thread newThread(Runnable r) {
                        return new Thread(r, "aaaAsyncSenderExecutor_" + this.threadIndex.incrementAndGet());
                    }
                });
        producer.setAsyncSenderExecutor(asyncSenderExecutor);
        producer.setRetryAnotherBrokerWhenNotStoreOK(true);
        try {
            producer.start();
            return producer;
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                producer.shutdown();
            } finally {
                producer = null;
            }
        }
        return null;
    }

![image](https://user-images.githubusercontent.com/16188008/97858751-93ce1f80-1d3a-11eb-9288-2dbffe211eec.png)
![image](https://user-images.githubusercontent.com/16188008/97858825-b06a5780-1d3a-11eb-9e0f-3a505ee7f965.png)
![image](https://user-images.githubusercontent.com/16188008/97858862-be1fdd00-1d3a-11eb-93e4-0dd6d182574c.png)

**Comment by lizhiboo** [comment]
> When the same groupName of DefaultMQProducer are initialized multiple times, Even if it fails, and three threads are still generated.
> 
> Tread1: ClientHouseKeepingService (It is a daemon)
> Tread2: AsyncAppender-Dispatcher-Thread
> Tread3: RequestHouseKeepingService
> 
> And they will never be destroyed.
> 
> Developers should be reminded that thread-safe and single-instance use of it. Or fix it.
> 
> Scene recurrence:
> 
> ```
> public static void main(String[] args) {
> 
>     ThreadPoolExecutor asyncSenderExecutor = new ThreadPoolExecutor(
>             10, 10, 1000 * 60, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(500000),
>             new ThreadFactory() {
>                 private AtomicInteger threadIndex = new AtomicInteger(0);
> 
>                 @Override
>                 public Thread newThread(Runnable r) {
>                     return new Thread(r, "test111" + this.threadIndex.incrementAndGet());
>                 }
>             });
> 
>     for (int i = 0; i < 50; i++) {
>         asyncSenderExecutor.submit(new Runnable() {
>             @Override
>             public void run() {
>                 createMqProducer();
>             }
>         });
>     }
>     try {
>         Thread.sleep(20000000000L);
>     } catch (InterruptedException e) {
>         e.printStackTrace();
>     }
> }
> 
> 
> public static DefaultMQProducer createMqProducer() {
>     DefaultMQProducer producer = new DefaultMQProducer("w222");
>     producer.setNamesrvAddr("192.168.0.22:9876");
>     producer.setRetryTimesWhenSendAsyncFailed(2);
>     producer.setSendMsgTimeout(50000);
> 
>     ThreadPoolExecutor asyncSenderExecutor = new ThreadPoolExecutor(
>             8, 8, 1000 * 60, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(500000),
>             new ThreadFactory() {
>                 private AtomicInteger threadIndex = new AtomicInteger(0);
> 
>                 @Override
>                 public Thread newThread(Runnable r) {
>                     return new Thread(r, "aaaAsyncSenderExecutor_" + this.threadIndex.incrementAndGet());
>                 }
>             });
>     producer.setAsyncSenderExecutor(asyncSenderExecutor);
>     producer.setRetryAnotherBrokerWhenNotStoreOK(true);
>     try {
>         producer.start();
>         return producer;
>     } catch (Exception e) {
>         e.printStackTrace();
>     } finally {
>         try {
>             producer.shutdown();
>         } finally {
>             producer = null;
>         }
>     }
>     return null;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/16188008/97858751-93ce1f80-1d3a-11eb-9288-2dbffe211eec.png)
> ![image](https://user-images.githubusercontent.com/16188008/97858825-b06a5780-1d3a-11eb-9e0f-3a505ee7f965.png)
> ![image](https://user-images.githubusercontent.com/16188008/97858862-be1fdd00-1d3a-11eb-93e4-0dd6d182574c.png)

In RocketMQ 4.8.0, thread RequestHouseKeepingService is daemon. Can u supply the detailed version in ur environment?

**Comment by maixiaohai** [comment]
issue #1957 fixed this problem?
