### ISSUE TITLE
consume queue can not write

### ISSUE THREAD

**Issue by 8da2k** [apache/rocketmq#2398]
RocketMQ 4.2.0, The disk was full before and restored by migrating data to other place. But there are some error, it looks like the queue is unwritable.
client log: service not available now, maybe disk full
server log:
![image](https://user-images.githubusercontent.com/8790163/97867318-96d00c80-1d48-11eb-90dc-3d6ea78a52ea.png)

**Comment by duhenglucky** [comment]
@dalaoyang Did you clean up the data manually? It is not recommended to do so. It is recommended to clean up the data by modifying the “fileReservedTime” and “diskMaxUsedSpaceRatio”.

**Comment by 8da2k** [comment]
No, just remove some other application's data.

**Comment by tianyangyang427** [comment]
Have you solved the problem?

**Comment by 8da2k** [comment]
> Have you solved the problem?

We restart the brokers.
