### ISSUE TITLE
More detailed documentation?

### ISSUE THREAD

**Issue by xhsky** [apache/rocketmq#2405]
The documents provided on the official website are too brief and outdated.
Have more detailed documents, such as those that introduce specific configurations？

**Comment by RongtongJin** [comment]
There are some detailed documents in [GitHub repository](https://github.com/apache/rocketmq/tree/master/docs). Any other detailed documents are welcomed to submit to [rocketmq-site](https://github.com/apache/rocketmq-site) repository.
