### ISSUE TITLE
Consume the latest message but continue commit the same old offset

### ISSUE THREAD

**Issue by zhangzhencx** [apache/rocketmq#2422]
From the logs ,can know as this. 
the consume client can consume the latest message ,like queueid = 3 offset = 18305, but commited offset is stopped at 17448.

2020-11-12 08:27:37,037 INFO RocketmqClient - [persistAll] Group: CrawlVideoAsyncEventConsumer1 ClientId: 172.18.0.1@104940 updateConsumeOffsetToBroker MessageQueue [topic=TempDetectionOfVideo, brokerName=broker-a, queueId=3] 17448

 the consume client print "**grab msg queueId = 3 offset = 18305"

 public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                                                                ConsumeConcurrentlyContext context) {
  for (int i = 0; i < msgs.size(); i++) {
                            log.info("grab msg queueId = " + msgs.get(i).getQueueId()+" offset = "+msgs.get(i).getQueueOffset());}

**Comment by zhangzhencx** [comment]
重启消费客户端，可以看到积压的消息很快就被消费掉了，位点也慢慢的被提交到最新了

**Comment by maixiaohai** [comment]
Could you provide more details, such as rocketmq version, broker conf.

**Comment by zhangzhencx** [comment]
version 4.4.0，six brokers,broker abc(master),abc(slave) . broker b conf as shown below.

serverSelectorThreads | 3
-- | --
brokerRole | ASYNC_MASTER
serverSocketRcvBufSize | 131072
osPageCacheBusyTimeOutMills | 1000
shortPollingTimeMills | 1000
clientSocketRcvBufSize | 131072
clusterTopicEnable | true
brokerTopicEnable | true
autoCreateTopicEnable | false
maxErrorRateOfBloomFilter | 20
maxMsgsNumBatch | 64
cleanResourceInterval | 10000
commercialBaseCount | 1
maxTransferCountOnMessageInMemory | 32
brokerFastFailureEnable | true
brokerClusterName | chinastory-rocketmq-cluster
flushDiskType | ASYNC_FLUSH
commercialBigCount | 1
mapedFileSizeCommitLog | 1073741824
consumerFallbehindThreshold | 17179869184
autoCreateSubscriptionGroup | false
transientStorePoolEnable | false
flushConsumerOffsetInterval | 5000
waitTimeMillsInHeartbeatQueue | 31000
diskMaxUsedSpaceRatio | 75
cleanFileForciblyEnable | true
slaveReadEnable | false
flushCommitLogLeastPages | 4
msgTraceTopicName | RMQ_SYS_TRACE_TOPIC
expectConsumerNumUseFilter | 32
traceTopicEnable | true
useEpollNativeSelector | false
enablePropertyFilter | false
messageDelayLevel | 1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h
deleteCommitLogFilesInterval | 100
brokerName | broker-b
maxTransferBytesOnMessageInDisk | 65536
mapedFileSizeConsumeQueue | 6000000
listenPort | 10911
flushConsumeQueueLeastPages | 2
pullMessageThreadPoolNums | 112
useReentrantLockWhenPutMessage | false
flushIntervalConsumeQueue | 1000
sendThreadPoolQueueCapacity | 10000
debugLockEnable | false
haHousekeepingInterval | 20000
diskFallRecorded | true
messageIndexEnable | true
clientAsyncSemaphoreValue | 65535
clientCallbackExecutorThreads | 48
putMsgIndexHightWater | 600000
sendMessageThreadPoolNums | 1
clientManagerThreadPoolQueueCapacity | 1000000
serverSocketSndBufSize | 131072
maxDelayTime | 40
clientSocketSndBufSize | 131072
namesrvAddr | 10.10.160.79:9876;10.10.160.80:9876;10.10.160.81:9876
commercialEnable | true
maxHashSlotNum | 5000000
heartbeatThreadPoolNums | 32
transactionTimeOut | 6000
maxMessageSize | 4194304
adminBrokerThreadPoolNums | 16
defaultQueryMaxNum | 32
forceRegister | true
maxTransferBytesOnMessageInMemory | 262144
enableConsumeQueueExt | false
longPollingEnable | true
serverWorkerThreads | 8
messageIndexSafe | false
deleteConsumeQueueFilesInterval | 100
haSlaveFallbehindMax | 268435456
serverCallbackExecutorThreads | 0
flushCommitLogThoroughInterval | 10000
commercialTimerCount | 1
useTLS | false
redeleteHangedFileInterval | 120000
flushIntervalCommitLog | 500
rocketmqHome | /application/search/rocketmq-all-4.4.0-bin-release
queryMessageThreadPoolNums | 56
messageStorePlugIn |  
serverChannelMaxIdleTimeSeconds | 120
maxIndexNum | 20000000
filterDataCleanTimeSpan | 86400000
filterServerNums | 0
commitCommitLogLeastPages | 4
waitTimeMillsInPullQueue | 5000
haSendHeartbeatInterval | 5000
clientChannelMaxIdleTimeSeconds | 120
filterSupportRetry | false
flushDelayOffsetInterval | 10000
duplicationEnable | false
offsetCheckInSlave | false
clientCloseSocketIfTimeout | false
transientStorePoolSize | 5
waitTimeMillsInSendQueue | 200
warmMapedFileEnable | false
endTransactionThreadPoolNums | 104
flushCommitLogTimed | false
flushLeastPagesWhenWarmMapedFile | 4096
clientWorkerThreads | 4
endTransactionPoolQueueCapacity | 100000
registerNameServerPeriod | 30000
registerBrokerTimeoutMills | 6000
accessMessageInMemoryMaxRatio | 40
highSpeedMode | false
transactionCheckMax | 15
checkCRCOnRecover | true
destroyMapedFileIntervalForcibly | 120000
brokerIP2 | 172.17.0.1
brokerIP1 | 10.10.160.80
commitIntervalCommitLog | 200
clientOnewaySemaphoreValue | 65535
traceOn | true
clientManageThreadPoolNums | 32
channelNotActiveInterval | 60000
mappedFileSizeConsumeQueueExt | 50331648
consumerManagerThreadPoolQueueCapacity | 1000000
serverOnewaySemaphoreValue | 256
haListenPort | 10912
enableCalcFilterBitMap | false
clientPooledByteBufAllocatorEnable | false
aclEnable | false
storePathRootDir | /data0/search/rocketmq-data/2m2s-a
syncFlushTimeout | 5000
rejectTransactionMessage | false
commitCommitLogThoroughInterval | 200
connectTimeoutMillis | 3000
queryThreadPoolQueueCapacity | 20000
regionId | DefaultRegion
consumerManageThreadPoolNums | 32
disableConsumeIfConsumerReadSlowly | false
flushConsumerOffsetHistoryInterval | 60000
fetchNamesrvAddrByAddressServer | false
haTransferBatchSize | 32768
compressedRegister | false
storePathCommitLog | /data0/search/rocketmq-data/2m2s-a/commitlog
commercialTransCount | 1
transactionCheckInterval | 60000
startAcceptSendRequestTimeStamp | 0
serverPooledByteBufAllocatorEnable | true
serverAsyncSemaphoreValue | 64
heartbeatThreadPoolQueueCapacity | 50000
waitTimeMillsInTransactionQueue | 3000
deleteWhen | 04
bitMapLengthConsumeQueueExt | 112
fastFailIfNoBufferInStorePool | false
defaultTopicQueueNums | 8
notifyConsumerIdsChangedEnable | true
flushConsumeQueueThoroughInterval | 60000
fileReservedTime | 24
brokerPermission | 6
transferMsgByHeap | true
pullThreadPoolQueueCapacity | 100000
brokerId | 0
maxTransferCountOnMessageInDisk | 8

**Comment by zhangzhencx** [comment]
> Could you provide more details, such as rocketmq version, broker conf.

The broker conf is provided
