### ISSUE TITLE
defaultTopicQueueNums is invalid

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#2423]
My cluster has a master and a slave.
I set DefaultTopicQueueNums=32, restarted the broker, and executed the java code, but the automatically created topic only has 4 queues.

**Comment by songxiao-hui** [comment]
you can paste your's broker config properties

**Comment by iamqq23ue** [comment]
> you can paste your's broker config properties

brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=SYNC_MASTER
flushDiskType=SYNC_FLUSH
traceTopicEnable=true
defaultTopicQueueNums=32

**Comment by songxiao-hui** [comment]
it's will be compare the default topic(TBW102) config's queue num and  you config topic queue num then choose the min number

**Comment by iamqq23ue** [comment]
> it's will be compare the default topic(TBW102) config's queue num and you config topic queue num then choose the min number


Thanks。I have checked TBW102, the number of queues is 32, which is the same as the defaultTopicQueueNums I set.

**Comment by songxiao-hui** [comment]
> > it's will be compare the default topic(TBW102) config's queue num and you config topic queue num then choose the min number
> 
> Thanks。I have checked TBW102, the number of queues is 32, which is the same as the defaultTopicQueueNums I set.

sry，可能上次没描述清楚，这个配置指的是producer端的配置 DefaultMQProducer. defaultTopicQueueNums  默认是4，可以通过producer.setDefaultTopicQueueNums()改变， 在broker创建新topic时，会比较TBW102的队列数(你broker端配置的) 和 DefaultMQProducer. defaultTopicQueueNums 然后取其较小者，可查看源码 TopicConfigManager#createTopicInSendMessageMethod() 方法

**Comment by iamqq23ue** [comment]
Thanks, i get it
