### ISSUE TITLE
is it possiable to get a RejectedExecutionException for a unlimited LinkedBlockingQueue

### ISSUE THREAD

**Issue by EZLippi** [apache/rocketmq#2426]
![image](https://user-images.githubusercontent.com/5326814/99044966-91d24f00-25cb-11eb-9ec7-53bba4dd4a26.png)
may be this is a useless code for retry later
![image](https://user-images.githubusercontent.com/5326814/99045072-bc240c80-25cb-11eb-987d-7f7492cdd7ce.png)

**Comment by RongtongJin** [comment]
It seems difficult to get a RejectedExecutionException,  but the code doesn't cause any errors.

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
