### ISSUE TITLE
How to use rocketmq cross different environments?

### ISSUE THREAD

**Issue by HoneWong** [apache/rocketmq#2432]
I have a problem in using MQ in base&feaure environments.
For instance, service "A" is a producer, service "B" is a consumer. They are running in a so called "base environment"(marked "BASE"). The two services use topic "topic_AB" to send & consume messages.
When the service "A" has a new feature to develop, I run an "A1" in a so called "feature environment 1"(marked "F1"), and hope that "A1" sends a message, "B" consumes it. 
Then both services have another feature to develop, I run an "A2" and a "B2" in a so called "feature environment 2"(marked "F2"), and hope that "A2" sends a message, only "B2" consumes it.
Does the RocketMQ have some features to help me achieve this goal?

I think the point is how the consumers find the environments change? A way is, I build a service to listen and save the relationships across topics and groups. The producers&consumers choose the right router to send&listen topics dynamically.

Do you have another idea?

**Comment by zhaohai1299002788** [comment]
If only different consumers consume messages, message filtering can be used to satisfy the consumption of messages in different environments.
