### ISSUE TITLE
The amount of messages in and out of a cluster

### ISSUE THREAD

**Issue by liumaomaoqwer** [apache/rocketmq#2433]
1. Please describe the feature you are requesting.
how can i know the amount of messages in and out of a cluster?
how can i know the amount of bytes in and out of a cluster?
how can i know the amount of failed messages in and out of a cluster?
how can i know the amount of failed bytes in and out of a cluster?
2. Provide any additional detail on your proposed use case for this feature.
kafka can get those infomation by jmx so how can i get those infomation from rocketmq?

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
yes. this is very import to me.

**Comment by RongtongJin** [comment]
You can use mqadmin tool, eg: `sh ${rocketmq_home}/bin/mqadmin statsAll` or get the info from stats.log. You can also get the info by installing rocketmq-console.

**Comment by liumaomaoqwer** [comment]
i know the mqadmin tools. but this can not resolve my problem.
the data what i want is like this 
![image](https://user-images.githubusercontent.com/73278486/99242019-99972b00-2839-11eb-9ebd-c639cb86373b.png)
but mqadmin can only get total amount of messages can get bytes and can get failed messages and bytes.
