### ISSUE TITLE
[Documents] Wrong slot count in 'Slot Table'

### ISSUE THREAD

**Issue by ypren** [apache/rocketmq#2450]
In the Design document 6.2 https://github.com/apache/rocketmq/blob/master/docs/cn/design.md

The 'Slot Table' in the picture flag from 0 to 500w, if it should be 0 to (500w-1) or 1 to 500w?

**Comment by starboyate** [comment]
@ypren 1 to 500w

**Comment by ypren** [comment]
> @ypren 0 to 499w
