### ISSUE TITLE
Does support multi-tag?

### ISSUE THREAD

**Issue by liugh6** [apache/rocketmq#2453]
**FEATURE REQUEST**

1.发送消息能否支持多tag？
设置tag方法命名也是期望有多tag的，为什么没有实现？你们有何考量？
com.alibaba.rocketmq.common.message.Message#setTags

**Comment by Jaskey** [comment]
不支持，因为目前Tag的存储设计是定长的，多Tag导致Tag的存储是可变的。

如果有类似需求，建议使用Property的sql filter，功能更强大
