### ISSUE TITLE
Supports multiple tag sends the message

### ISSUE THREAD

**Issue by liugh6** [apache/rocketmq#2454]
**FEATURE REQUEST**

1. can you support multiple tags when send message? com.alibaba.rocketmq.common.message.Message#setTags,this method named setTags,but only one tag can set,is there any problem?

2. i have set tag for message when send message,but i need more tags for one message now. we need more tags just like keys

**Comment by Jaskey** [comment]
This issue has been discussed before, if you need to use multiple tags on one message, please try using property filters, you can wrote some expression like sql to filter messages
