### ISSUE TITLE
Inconsistency of permission code

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#2455]
When I was using ths ACL, I found that the Permission code was inconsistent. Can I remove 'Permision.ANY' to make it consistent with the permission code in tools?

rocketmq-acl module
![image](https://user-images.githubusercontent.com/30995057/100072619-71ca4780-2e77-11eb-9770-d54fa91abf10.png)

rocketmq-tools module
![image](https://user-images.githubusercontent.com/30995057/100072793-a6d69a00-2e77-11eb-9b4c-9516daf3c9f9.png)

topic.json
![image](https://user-images.githubusercontent.com/30995057/100073026-ea310880-2e77-11eb-9a16-4228d65c10ff.png)

**Comment by lizhiboo** [comment]
IMO, class Permission is used for client, class UpdateTopicPermSubCommand is used for server.
