### ISSUE TITLE
[DOC]best_practice describe sendAsyncFailed error

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#2459]
the https://github.com/apache/rocketmq/blob/master/docs/cn/best_practice.md said 
1.2 消息发送失败处理方式
Producer的send方法本身支持内部重试，重试逻辑如下：

至多重试2次（同步发送为2次，异步发送为0次）。

but https://github.com/apache/rocketmq/blob/734834cb560a341dd03f1c738974bc5656e04c87/docs/cn/client/java/API_Reference_DefaultMQProducer.md with retryTimesWhenSendFailed (default 2) 

and the code also show it will resend message when send failed by async mode

**Comment by duhenglucky** [comment]
@coder-zzzz Would you like to pull a request to fix this doc?

**Comment by coder-zzzz** [comment]
> @coder-zzzz Would you like to pull a request to fix this doc?

ok
