### ISSUE TITLE
delete the unused feature that monitor pull invalid offset

### ISSUE THREAD

**Issue by fuyou001** [apache/rocketmq#246]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
delete the unused feature that monitor pull invalid offset
2. Provide any additional detail on your proposed use case for this feature.
delete the unused feature that monitor pull invalid offset
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have
4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
delete some code

**Comment by vongosling** [comment]
I can not figure out what do you want to do in your issue description, am I missing something?
