### ISSUE TITLE
rocketMQ删除某个消息

### ISSUE THREAD

**Issue by xiao-ma-nong** [apache/rocketmq#2461]
有个例子
我生成这个链接30分钟有效，
如果我点击我就想要把这个消息删除掉
如果没有点击那就30分钟后减少调
这个怎么实现》》 ？？？

**Comment by xiao-ma-nong** [comment]
我还有个思路就是消费的时候判断一下数据是已经修改了？？
各位老哥有啥建议的

**Comment by duhenglucky** [comment]
@xiao-ma-nong 可以通过重置位点的方式来实现这个消息，不过通过消息属性标记也是一个不错的想法，当然这需要客户端配合，最好还是在邮件列表里面讨论一下，看大家对这个功能是否感兴趣，：）

**Comment by xiao-ma-nong** [comment]
> @ xiao-ma-nong可以通过重置位点的方式来实现这个消息，不过通过消息属性标记也是一个不错的想法，当然这需要客户端配合，最好还是在邮件列表里面讨论一下，看大家对这个功能是否奖学金，：）

我觉得吧，这样也可行，也避免不了不想要的东西也去消费，没必要的

**Comment by liqiang181** [comment]
> 

连接点击了就不再去消费了这条消息了，位点重置和属性标记能实现？怎么实现
