### ISSUE TITLE
MappedFile 中 MappedByteBuffer 和 TransientStorePool 中的ByteBuffer的区别

### ISSUE THREAD

**Issue by BenXiangYangGuang** [apache/rocketmq#2466]
您好，正在学习 RocketMQ 源码，有几个问题请教一下:

MappedByteBuffer 和 ByteBuffer 都是堆外内存（直接内存）；
![image](https://user-images.githubusercontent.com/20946227/100720068-6d160e00-33f8-11eb-891c-a83e3b02755b.png)

引入 TransientStorePool 的目的是什么呢？或者他和 MappedByteBuffer 有那里更高效的地方。
ByteBuffer 有内存锁定功能，还有其他区别吗？

然后MappedByteBuffer、ByteBuffer 的数据落盘和数据查询，和 PageCache 有是什么关系，ByteBuffer 数据落盘的时候，还用经过 PageCahe 吗？

谢谢！

**Comment by duhenglucky** [comment]
@BenXiangYangGuang TransientStorePool 相当于在内存层面做了读写分离，写走内存吃，读走pagecache，同时最大程度消除了page cache的锁竞争，降低了毛刺，咨询类的这种问题建议走[邮件列表](https://rocketmq.apache.org/about/contact/)：），这样能够沉淀下来哈。

**Comment by BenXiangYangGuang** [comment]
ok，已订阅，谢谢
