### ISSUE TITLE
sometimes cause: MQBrokerException  CODE: 2 DESC:[TIMEOUT_CLEAN_QUEUE]

### ISSUE THREAD

**Issue by lwclover** [apache/rocketmq#2471]
**BUG REPORT**

1. sometimes cause: 
MQBrokerException  CODE: 2 DESC:[TIMEOUT_CLEAN_QUEUE] broker busy, start flow control for a while, period in queue: 207ms, size of queue 0.

2. Please tell us about your environment:
centos6
rocketmq 4.5.2, the cluster is syn double write, async flush disk.

3. Other information:
G1 gc max pause time is very low, less than 20ms.
BrokerFastFailure.start method start a thread to clean Expired Request in every 10 millseconds.
One of the thread job is to check SendThreadPoolQueue, If there is a message more than 200 milliseconds(default waitTimeMillsInSendQueue=200) in queue, the message will be removed.
In SendMessageProccessor the handleHA method the syncFlushTimeout is 5000.
This is a **terrible** default parameter.

additional: sendMessageExecutor default only has one thread

4.My ideal
default param is 
syncFlushTimeout=5000
waitTimeMillsInSendQueue=5000
client jar remove 
`long costTime = beginTimestampPrev - beginTimestampFirst;
                        if (timeout < costTime) {
                            callTimeout = true;
                            break;
                        }
`
that means the param sendmessagetimeout means one send action timeout value is 3000,

**Comment by duhenglucky** [comment]
@lwclover It is recommended to increase the number of _sendMessageThreadPoolNums_ and _waitTimeMillsInSendQueue_ In addition, you can test 4.7.1  which has a performance improvement of about ten times.
