### ISSUE TITLE
在启动rocketmq后，生产者先生产100条消息，之后未开启消费者，但是控制台显示今日消费数异常

### ISSUE THREAD

**Issue by 418545106** [apache/rocketmq#2483]
![image](https://user-images.githubusercontent.com/29942834/101110343-bf7f4680-3613-11eb-9287-9d6ac914811e.png)
在设置master-slave后，生产的100条消息会在主从上都有，这是正确的吗，然后就是，我还未开启消费端，但是消费数已经有300了，是否不正确

**Comment by duhenglucky** [comment]
@418545106 控制台显示的并不准确哈，因为有些内部的topic，消息流转，另外如果是多个consumer  group 是可能会这样的，生产的消息主从上都有是正确的，因为要主从同步呀，建议关注～/logs/rocketmqlogs/stats.log 里面的metrics 数据，这个是相对准备的。

**Comment by francisoliverlee** [comment]
300 here means Transfered-Message-Count, when one message get-from commitlog, it would be updated
