### ISSUE TITLE
请问在顺序消费（MessageListenerOrderly）时主broker下线，从broker不会继续发送消息吗

### ISSUE THREAD

**Issue by 418545106** [apache/rocketmq#2485]
请问在顺序消费（MessageListenerOrderly）时主broker下线，从broker不会继续发送消息吗
（请原谅孩子能力不行，不会用订阅邮件）

**Comment by RongtongJin** [comment]
对的，顺序消息在消费Queue时需要加锁，当前只能在Master节点上加锁
