### ISSUE TITLE
rockmq的事务消息

### ISSUE THREAD

**Issue by djkdeveloper** [apache/rocketmq#2497]
正常流程是 
(1) 发送消息（half消息）。

(2) 服务端响应消息写入结果。

(3) 根据发送结果执行本地事务（如果写入失败，此时half消息对业务不可见，本地逻辑不执行）。

(4) 根据本地事务状态执行Commit或者Rollback（Commit操作生成消息索引，消息对消费者可见）

我现在的场景是 在第四部  本地事务提交 但是 hafl消息我想改 因为我的哦hafl消息是依赖本地消息的 只有本地消息处理完成了才能得到完整的hafl消息

**Comment by francisoliverlee** [comment]
what's your prolem exactly

**Comment by djkdeveloper** [comment]
新增商品后通知es服务 进行商品索引
按照rocketmq的流程
1. 发送消息给mq  
2. mq回调  商品服务器执行本地事务（新增商品和商品的一些关联信息）
3.mq 发送half消息给 es服务进行索引 

问题在：
第一步发送给mq的时候商品的部分数据是拿不到的比如 商品的id
导致发送给mq的half消息里面的商品信息是不完整的商品信息

**Comment by djkdeveloper** [comment]
> what's your prolem exactly

新增商品后通知es服务 进行商品索引
按照rocketmq的流程

发送消息给mq
mq回调 商品服务器执行本地事务（新增商品和商品的一些关联信息）
3.mq 发送half消息给 es服务进行索引
问题在：
第一步发送给mq的时候商品的部分数据是拿不到的比如 商品的id
导致发送给mq的half消息里面的商品信息是不完整的商品信息

**Comment by mgljava** [comment]
怎么感觉这个和事务消息没多大关系呢 哈哈

**Comment by djkdeveloper** [comment]
有关系啊 事务消息是相当于先发送half消息的啊 但是有可能我这个half消息里面的信息有部分是需要经过执行本地事务才知道结果的啊

**Comment by djkdeveloper** [comment]
> 怎么感觉这个和事务消息没多大关系呢 哈哈

有关系啊 事务消息是相当于先发送half消息的啊 但是有可能我这个half消息里面的信息有部分是需要经过执行本地事务才知道结果的啊

**Comment by mgljava** [comment]
> > 怎么感觉这个和事务消息没多大关系呢 哈哈
> 
> 有关系啊 事务消息是相当于先发送half消息的啊 但是有可能我这个half消息里面的信息有部分是需要经过执行本地事务才知道结果的啊

我的意思是能不能先执行商品存储，然后就能得到商品的完整信息（包括商品ID），再把该消息发送到MQ，然后ES进行消费建立索引。相当于这个场景就不太适用发送事务消息，是不是发送一般的消息就行了

**Comment by djkdeveloper** [comment]
> > > 怎么感觉这个和事务消息没多大关系呢 哈哈
> > 
> > 
> > 有关系啊 事务消息是相当于先发送half消息的啊 但是有可能我这个half消息里面的信息有部分是需要经过执行本地事务才知道结果的啊
> 
> 我的意思是能不能先执行商品存储，然后就能得到商品的完整信息（包括商品ID），再把该消息发送到MQ，然后ES进行消费建立索引。相当于这个场景就不太适用发送事务消息，是不是发送一般的消息就行了

恩 这也是我最后没办法的方。。。。我也只是好奇 如果真是遇到我那种必须要确保同一个事务的场景怎么办

**Comment by francisoliverlee** [comment]
@djkdeveloper 
save first, then notice es, that's a good idea. i would close the issue, feel free to reopen it if you still have any question

try logic code like this  
```java
ProductInfo productInfo = save(productVO);//success: return product object with uniq id, fail: return null
if(productInfo!=null){
    sendMQToES(productInfo);// not transactional msg would be ok
}else{
    return "save product fail";
}
```

**Comment by jacentsao** [comment]
> @djkdeveloper
> save first, then notice es, that's a good idea. i would close the issue, feel free to reopen it if you still have any question
> 
> try logic code like this
> 
> ```java
> ProductInfo productInfo = save(productVO);//success: return product object with uniq id, fail: return null
> if(productInfo!=null){
>     sendMQToES(productInfo);// not transactional msg would be ok
> }else{
>     return "save product fail";
> }
> ```

Message may lost
