### ISSUE TITLE
Producer 必须指定 Tag 么？

### ISSUE THREAD

**Issue by mysunnyshine** [apache/rocketmq#2498]
场景：
        有两个不同的 consumer group，但是都想消费同一个 topic 的消息。目前可以通过在发送端，将同一个消息，通过指定不同的tag，进行发送。 我看了其它 issue，producer 不支持多tag，是处于存储长度的考虑。那么为什么不支持 如果 producer 不指定tag，那么该 topic 下的所有 consumer 都能收到消息？ 这个是处于什么考虑。

举个例子：
        直播场景，用户送礼，发送了 礼物消息。那么榜单服务会消费这个消息，同时 数据统计的一些其它服务也期望收到这个消息。除了在发送方，通过指定不同的tag 发送多次，还有其它的解决办法么？

**Comment by maixiaohai** [comment]
Tag is not necessary, and you can find lots of examples in https://github.com/apache/rocketmq/blob/master/docs/cn/RocketMQ_Example.md
IMO, In your case some tags maybe useful which will give consumers more choices.

**Comment by mysunnyshine** [comment]
> Tag is not necessary, and you can find lots of examples in https://github.com/apache/rocketmq/blob/master/docs/cn/RocketMQ_Example.md
> IMO, In your case some tags maybe useful which will give consumers more choices.

但是如果producer 不指定tag， consumer 只有不指定 tag 的 consuemr 才能收到。 貌似 RocketMQ 没办法像 NSQ 那样，一条消息，能被该 topic 下所有的 consumer 收到

**Comment by francisoliverlee** [comment]
> > Tag is not necessary, and you can find lots of examples in https://github.com/apache/rocketmq/blob/master/docs/cn/RocketMQ_Example.md
> > IMO, In your case some tags maybe useful which will give consumers more choices.
> 
> 但是如果producer 不指定tag， consumer 只有不指定 tag 的 consuemr 才能收到。 貌似 RocketMQ 没办法像 NSQ 那样，一条消息，能被该 topic 下所有的 consumer 收到

set messageModel =  BROADCASTING, this means every consumer will consme all meesgaes in the topic
