### ISSUE TITLE
rocketmq-console :The stats <TOPIC_PUT_NUMS> <DefaultCluster> not exist

### ISSUE THREAD

**Issue by wyxinlx** [apache/rocketmq#2499]
suppose a topic has never been written, rocketmq-console will get system_error code when it try to exec view-broker-stats-data. Code in RemotingSysResponseCode can not make a precise description of the case as above. Another new code should be added to tell error/no-data apart ?

**Comment by francisoliverlee** [comment]
@wyxinlx 
it would be solved here
https://github.com/apache/rocketmq-externals/issues/610
