### ISSUE TITLE
Unable to find a good .NET client

### ISSUE THREAD

**Issue by maobiwen** [apache/rocketmq#2500]
没有能用的好用的.net客户端吗？
你们用.net语言消费和生产消息都用哪个客户端啊。求求求

**Comment by ifplusor** [comment]
封装c++客户端

**Comment by maobiwen** [comment]
> 封装c++客户端

有现成的吗？

**Comment by ifplusor** [comment]
@ShannonDing

**Comment by RongtongJin** [comment]
If I remember correctly, the community does not currently support .net clients.

Issues are generally used for bug reports and feature requests, so if you have any questions about  Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
