### ISSUE TITLE
setNameSvr question

### ISSUE THREAD

**Issue by reallinxu** [apache/rocketmq#2501]
setNameSvr method has the following notes： 
Domain name mode access way does not support the delimiter(;), and only one domain name can be set.

How to set two domain names？

**Comment by francisoliverlee** [comment]
why need two domains?

**Comment by reallinxu** [comment]
> why need two domains?

I need to use the nameserver cluster

**Comment by dongeforever** [comment]
@reallinxu you could submit an pr to enhance it. I could help a  review.

**Comment by francisoliverlee** [comment]
> > why need two domains?
> 
> I need to use the nameserver cluster

my misunderstanding,  i thougt namesrv domain as ws address that where brokers fetch namesrvs dynamicly
