### ISSUE TITLE
what is tls?

### ISSUE THREAD

**Issue by liumaomaoqwer** [apache/rocketmq#2505]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
i don't know what is tls?
when i see the code in class NamesrvController and we look at the method initialize(),so you will see a judgement "if (TlsSystemConfig.tlsMode != TlsMode.DISABLED) ",so i don't 
understand what is TLS.

2. Provide any additional detail on your proposed use case for this feature.
the rocketmq source code version is 4.7.1

**Comment by RongtongJin** [comment]
https://en.wikipedia.org/wiki/Transport_Layer_Security
RocketMQ can turn on TLS to increase data transfer security.

Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address](https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
