### ISSUE TITLE
事务消息 发送预消息

### ISSUE THREAD

**Issue by djkdeveloper** [apache/rocketmq#2507]
事务消息第一步发送预消息后执行本地事务 
![image](https://user-images.githubusercontent.com/16333920/102438080-9bc9f080-4056-11eb-8fb7-d83ae0f07ec4.png)
返回的是RocketMQLocalTransactionState  所以发送预消息的时候 只能知道本地事务是执行成功还是失败了 但是如果失败了 则不能知道具体是什么失败 失败的原因有多种 比如 下单预存款不足等等 能否在执行本地事务返回的时候 加个返回码 啊

**Comment by RongtongJin** [comment]
执行本地事务失败（ROLLBACK）还是成功（COMMIT）是返回给RocketMQ 事务消息逻辑而不是业务端的，业务端具体是哪一种失败需要自己去记录。
