### ISSUE TITLE
java.lang.ClassCastException: java.lang.Class cannot be cast to org.apache.rocketmq.acl.AccessValidator

### ISSUE THREAD

**Issue by power522** [apache/rocketmq#2508]
brockerIP1=172.30.1.196
brokerClusterName = testCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
listenPort=10931
storePathRootDir=/data/admin/rocketmqtest/data
storePathCommitLog=/data/admin/rocketmqtest/log

aclEnable=true

启动acl后报类强转异常 4.6.* 和4.7.1都是

![image](https://user-images.githubusercontent.com/38269154/102491983-f5a8d580-40ab-11eb-8d9d-6bca9a7a380e.png)

**Comment by cuizhongqiang** [comment]
这个问题解决了吗？

**Comment by cuizhongqiang** [comment]
如果解决了，能把解决方案分享一下吗？

**Comment by ZXingg** [comment]
用户名密码长度必须大于6位

**Comment by Huwei1993** [comment]
> 如果解决了，能把解决方案分享一下吗？

有解决吗 ？

**Comment by maixiaohai** [comment]
检查一下对应的权限配置文件，写入的权限数据格式有问题
本质原因是权限文件初始化失败导致broker启动失败

**Comment by maixiaohai** [comment]
here is a related fix issue
 https://github.com/apache/rocketmq/issues/2328

**Comment by power522** [comment]
已经解决
发自网易邮箱大师
在2021年04月06日 17:16，Huwei1993 写道：

如果解决了，能把解决方案分享一下吗？

有解决吗 ？
