### ISSUE TITLE
cant start broker.sh

### ISSUE THREAD

**Issue by 1061235166** [apache/rocketmq#251]
version：4.2.0
enviroment：centos7 at vmAware
memory size：2G
can start namesvr，but cant start broker.sh，there is log
---------------------------
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005c0000000, 8589934592, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 8589934592 bytes for committing reserved memory.

**Comment by vongosling** [comment]
This is not an issue, if you have any question, please ask the question in the user email list. http://rocketmq.apache.org/about/contact/
