### ISSUE TITLE
事务消息的templte

### ISSUE THREAD

**Issue by djkdeveloper** [apache/rocketmq#2510]
事务消息的RocketMQTemplate
场景是这样的 我有订单模块 里面可能有多个事务消息 比如 下单会有一个事务消息  然后核销订单也会有一个事务消息 
现在的问题是 发送事务消息RocketMQTemplate的选择 
方案1:
2个人发送事务消息的时候 都用各自的RocketMQTemplate  就是写自己的template 继承RocketMQTemplate 然后RocketMQTemplate
优点：发送事务消息的时候 执行本地事务的时候 都是各自的本地事务listern 业务清晰 
疑问：不知道生成多个RocketMQTemplate会不会有什么性能上的弊端
方案2:
2个人发送事务消息的时候用同一个RocketMQTemplate
缺点:如果用同一个RocketMQTemplate那么用的就是同一个listern来执行本地事务，那么因为多个因为用了同一个lister来执行本地事务那么这个listern里面就会有很多不同业务的分支判断
优点：不知道用同一个RocketMQTemplate 会不会性能上好点

**Comment by RongtongJin** [comment]
如你所说，多个RocketMQTemplate会产生多个producer，性能上会有很轻微的损失，但不同事务消息的producer进行了隔离，代码逻辑更加清晰。具体使用哪一种方案，需要业务自己去权衡。
