### ISSUE TITLE
How to keep the offset for broker cluster way

### ISSUE THREAD

**Issue by xu-weize** [apache/rocketmq#2513]
When consumer client pull message from Broker   should to choice a broke (May be master or slave) by findBrokerAddressInSubscribe method. and use MQClientInstance.this.persistAllConsumerOffset() method persist offset to broker.But broker server never synchronized offset value  to others with same brokerName .My question is that we support consume client connect a  master to consume,the next time the client may choice to connect the slave broker  ,how to get know the master offset(the offset never synchronized to othes)

**Comment by RongtongJin** [comment]
RocketMQ currently has the capability of master to slave consumer offset synchronization (via SlaveSynchronize), but there is no reverse path to save to master synchronization.
