### ISSUE TITLE
brokerRole=SYNC_MASTER is invalid

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#2528]
When I set brokerRole=SYNC_MASTER, send_ok should be returned after both master and slave have written. But if I start the master first, send messages for a long time, and then start the slave, it will take a while for the master to synchronize. I can still send messages successfully when the master and slave are out of sync. why?

**Comment by RongtongJin** [comment]
In this case, there is a big gap between the master and slave, and the client can still send, but it will return slave_ NOT_ AVAILABLE.

**Comment by iamqq23ue** [comment]
> In this case, there is a big gap between the master and slave, and the client can still send, but it will return slave_ NOT_ AVAILABLE.

Since no matter whether you configure async_master or sync_master, you can send successfully（even return slave_ NOT_ AVAILABLE.）  without waiting for the completion of slave synchronization, so what is the use of setting sync_master?
