### ISSUE TITLE
[Remoting] There is a redundant waiting for response when request send fail in sync mode.

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq#2530]
**BUG REPORT**

1. Please describe the issue you observed:
  **There is a redundant wait for response when request send fail in sync mode.
  In my opinion,we should just throw a sendFail Exception rather than waiting until overtime because when request send fail.
  Obviously,it can not get it's response.**

  U can find this code in org.apache.rocketmq.remoting.netty.NettyRemotingAbstract#invokeSyncImpl.
  
![RocketMQ1](https://user-images.githubusercontent.com/18530950/103290059-a061b200-4a23-11eb-8ee8-d3e868316a1b.png)

  If this is an issue,may I submit a PR to fix it?

**Comment by lizhiboo** [comment]
> **BUG REPORT**
> 
> 1. Please describe the issue you observed:
>    **There is a redundant wait for response when request send fail in sync mode.
>    In my opinion,we should just throw a sendFail Exception rather than waiting until overtime because when request send fail.
>    Obviously,it can not get it's response.**
> 
> U can find this code in org.apache.rocketmq.remoting.netty.NettyRemotingAbstract#invokeSyncImpl.
> 
> ![RocketMQ1](https://user-images.githubusercontent.com/18530950/103290059-a061b200-4a23-11eb-8ee8-d3e868316a1b.png)
> 
> If this is an issue,may I submit a PR to fix it?

can u describe the concrete version and list the code ?

**Comment by fantow** [comment]
> > **BUG REPORT**
> > 
> > 1. Please describe the issue you observed:
> >    **There is a redundant wait for response when request send fail in sync mode.
> >    In my opinion,we should just throw a sendFail Exception rather than waiting until overtime because when request send fail.
> >    Obviously,it can not get it's response.**
> > 
> > U can find this code in org.apache.rocketmq.remoting.netty.NettyRemotingAbstract#invokeSyncImpl.
> > ![RocketMQ1](https://user-images.githubusercontent.com/18530950/103290059-a061b200-4a23-11eb-8ee8-d3e868316a1b.png)
> > If this is an issue,may I submit a PR to fix it?
> 
> can u describe the concrete version and list the code ?

U can find this code in the latest version.

**Comment by RongtongJin** [comment]
If the send fails the operationComplete method will be executed immediately and the call to responseFuture.putResponse will execute countdown, so the following responseFuture.waitResponse will be returned immediately without waiting.

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.
