### ISSUE TITLE
org.springframework.messaging.MessagingException: Can not found MQProducer 'order_operate_history_group' in cache! please define @RocketMQLocalTransactionListener class or invoke createOrGetStartedTransactionMQProducer() to create it firstly

### ISSUE THREAD

**Issue by tinarooot** [apache/rocketmq#2540]
I used to send rocketmq transaction messages and reported the following error(我使用发送rocketmq事务消息，
报以下错误)

````org.springframework.messaging.MessagingException: Can not found MQProducer 'order_operate_history_group' in cache! please define @RocketMQLocalTransactionListener class or invoke createOrGetStartedTransactionMQProducer() to create it firstly````

    /**
     * 
     * Send transaction message(发送事务消息)
     *
     * @param topic
     * @param tag
     * @param body
     * @throws Exception
     */
    public void sendMessageInTransaction(String group, String topic, String tag, String body) throws Exception {
        log.info("【发送消息】：{}", body);
        org.springframework.messaging.Message message = MessageBuilder.withPayload(body).build();
        TransactionSendResult result = rocketMQTemplate.sendMessageInTransaction(group, topic, message, tag);
        log.info("result->{}", result);
    }

Has anyone encountered it? ? ?(有人遇到过吗？？？)

**Comment by RongtongJin** [comment]
可以升级到最新的rocketmq-spring版本再试一下。

**Comment by xiao-ma-nong** [comment]
> 可以升级到最新的rocketmq-spring版本再试一下。

我用的是springboot 版本2.3.4.RELEASE

**Comment by xiao-ma-nong** [comment]
> 可以升级到最新的rocketmq-spring版本再试一下。
我点进去看这个源码版本是

rocketmq springboot版本是 

    <parent>
        <groupId>org.apache.rocketmq</groupId>
        <artifactId>rocketmq-spring-boot-parent</artifactId>
        <version>2.0.3</version>
        <relativePath>../rocketmq-spring-boot-parent/pom.xml</relativePath>
    </parent>


我再接着点进去发现这个all版本就是4.5.2
  <parent>
        <groupId>org.apache.rocketmq</groupId>
        <artifactId>rocketmq-all</artifactId>
        <version>4.5.1</version>
    </parent>


我实在找不出问题所在

**Comment by xiao-ma-nong** [comment]
我的rocketmq版本

rocketmq-all-4.7.0-bin-release

**Comment by RongtongJin** [comment]
> 我的rocketmq版本
> 
> rocketmq-all-4.7.0-bin-release

换rocketmq-spring的版本，2.0.3可以升级到2.1.1。

**Comment by xiao-ma-nong** [comment]
java.lang.NoSuchMethodError: org.apache.rocketmq.spring.core.RocketMQTemplate.sendMessageInTransaction(Ljava/lang/String;Lorg/springframework/messaging/Message;Ljava/lang/Object;)Lorg/apache/rocketmq/client/producer/TransactionSendResult;
	at com.cainaer.common.rocketmq.utils.RocketMqUtil.sendMessageInTransaction(RocketMqUtil.java:74)
	at com.cainaer.netty.service.impl.NettyServiceImpl.shopRejectOrders(NettyServiceImpl.java:143)
	at com.cainaer.netty.config.ChatHandler.typeHandle(ChatHandler.java:80)
	at com.cainaer.netty.config.ChatHandler.channelRead0(ChatHandler.java:44)
	at com.cainaer.netty.config.ChatHandler.channelRead0(ChatHandler.java:25)



换了之后，把全部的工作都做了，还是就报以上的错误

**Comment by RongtongJin** [comment]
> java.lang.NoSuchMethodError: org.apache.rocketmq.spring.core.RocketMQTemplate.sendMessageInTransaction(Ljava/lang/String;Lorg/springframework/messaging/Message;Ljava/lang/Object;)Lorg/apache/rocketmq/client/producer/TransactionSendResult;
> at com.cainaer.common.rocketmq.utils.RocketMqUtil.sendMessageInTransaction(RocketMqUtil.java:74)
> at com.cainaer.netty.service.impl.NettyServiceImpl.shopRejectOrders(NettyServiceImpl.java:143)
> at com.cainaer.netty.config.ChatHandler.typeHandle(ChatHandler.java:80)
> at com.cainaer.netty.config.ChatHandler.channelRead0(ChatHandler.java:44)
> at com.cainaer.netty.config.ChatHandler.channelRead0(ChatHandler.java:25)
> 
> 换了之后，把全部的工作都做了，还是就报以上的错误

像是pom依赖的问题。另外最早的错误应该定义了@RocketMQLocalTransactionListener方法吧

**Comment by xiao-ma-nong** [comment]
> > java.lang.NoSuchMethodError: org.apache.rocketmq.spring.core.RocketMQTemplate.sendMessageInTransaction(Ljava/lang/String;Lorg/springframework/messaging/Message;Ljava/lang/Object;)Lorg/apache/rocketmq/client/producer/TransactionSendResult;
> > at com.cainaer.common.rocketmq.utils.RocketMqUtil.sendMessageInTransaction(RocketMqUtil.java:74)
> > at com.cainaer.netty.service.impl.NettyServiceImpl.shopRejectOrders(NettyServiceImpl.java:143)
> > at com.cainaer.netty.config.ChatHandler.typeHandle(ChatHandler.java:80)
> > at com.cainaer.netty.config.ChatHandler.channelRead0(ChatHandler.java:44)
> > at com.cainaer.netty.config.ChatHandler.channelRead0(ChatHandler.java:25)
> > 换了之后，把全部的工作都做了，还是就报以上的错误
> 
> 像是pom依赖的问题。另外最早的错误应该定义了@RocketMQLocalTransactionListener方法吧

这个监听 是有了注解

**发送 事务方法**
 TransactionSendResult sendResult = rocketMQTemplate.sendMessageInTransaction(topic, message, tag);


**事务监听**
@RocketMQTransactionListener(txProducerGroup = "xxx")
public class RejectOrdersMqListener implements RocketMQLocalTransactionListener {
}


我找了源码，也没有找到帮助

**Comment by zheng987006406** [comment]
兄弟，你解决了吗，我也遇到了这个问题

**Comment by xiao-ma-nong** [comment]
> 兄弟，你解决了吗，我也遇到了这个问题

巧了，没有

**Comment by zheng987006406** [comment]
老兄，我知道问题的所在了，你是不是没有在`@RocketMQMessageListener`这个注解里面定义你说的这个group的名称，即`@RocketMQMessageListener(txProducerGroup="order_operate_history_group")`,你试试这样看行不行
