### ISSUE TITLE
rocketmq client exception：system busy & broker busy

### ISSUE THREAD

**Issue by sunxiaoning90** [apache/rocketmq#2546]
rocketmq 发送时异常：system busy 和 broker busy

**Comment by francisoliverlee** [comment]
more details it needed. 
- rocketmq version
- sending exception stack
- does it always happen

**Comment by duhenglucky** [comment]
@sunxiaoning90 https://yq.aliyun.com/articles/716568 这篇文章不知是否可以解决你的问题，可以针对文章中的描述，做些针对性调优。

**Comment by jiqingsuiyue** [comment]
https://yq.aliyun.com/articles/716568 why I can not find this article?
