### ISSUE TITLE
[Code Quality] Remove useless method MessageDecoder.decodeMessageId invoke.

### ISSUE THREAD

**Issue by horizonzy** [apache/rocketmq#2549]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Some method invoke is useless about `MessageDecoder.decodeMessageId(uniqKey)`.
Such as follow:
```
    public MessageExt viewMessage(String topic,
        String uniqKey) throws RemotingException, MQBrokerException, InterruptedException, MQClientException {
        try {
            MessageDecoder.decodeMessageId(uniqKey);
            return this.viewMessage(uniqKey);
        } catch (Exception e) {
            // Ignore
        }
        return this.defaultMQPullConsumerImpl.queryMessageByUniqKey(withNamespace(topic), uniqKey);
    }
```
It can be removed

**Comment by yuz10** [comment]
I guess, if message is a "offset" message id, then decodeMessageId will throw an exception, then goto "queryMessageByUniqKey", otherwise goto "viewMessage", thus that is not useless
