### ISSUE TITLE
openjdk11 mq4.8. mqnamesrv error

### ISSUE THREAD

**Issue by chensun2020** [apache/rocketmq#2553]
-Djava.ext.dirs=/jre/lib/ext:/usr/rocketmq/rocketmq-all-4.8.0-bin-release/bin/../lib:/lib/ext is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by francisoliverlee** [comment]
try it on oracle jdk

**Comment by chensun2020** [comment]
> try it on oracle jdk, not sure open jdk

I use oracle jdk 11, reduce the operating parameters of the JVM, and still report the same error

**Comment by chensun2020** [comment]
> > try it on oracle jdk, not sure open jdk
> 
> I use oracle jdk 11, reduce the operating parameters of the JVM, and still report the same error

-Djava.ext.dirs=/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/jre/lib/ext:/usr/local/rocketmq/rocketmq-all-4.8.0-bin-release/bin/../lib:/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/lib/ext is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by sicklife** [comment]
+1

**Comment by angelyouyou** [comment]
> +1

+2

**Comment by willseeyou** [comment]
+1



/mnt/i/rocketmq/rocketmq-all-4.8.0-bin-release/bin/runserver.sh: 70: [[: not found
-Djava.ext.dirs=/jre/lib/ext:/mnt/i/rocketmq/rocketmq-all-4.8.0-bin-release/bin/../lib:/lib/ext is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
➜  rocketmq-all-4.8.0-bin-release  java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by zhangbobo131415** [comment]
i use --class-path replace -Djava.ext.dirs,but anthor error occures 
Error: Could not find or load main class org.apache.rocketmq.namesrv.NamesrvStartup
Caused by: java.lang.ClassNotFoundException: org.apache.rocketmq.namesrv.NamesrvStartup

**Comment by smiletrl** [comment]
This [article](https://chowdera.com/2021/01/20210107122409152h.html) might be helpful for JDK 1.9+. To make it simple, I just used jdk 1.8. Then it works fine. The two commands are also required to make it start successfully.

```
mkdir -p ~/store/commitlog/
mkdir -p ~/store/consumequeue/ 
```

**Comment by bufanyun** [comment]
+3
