### ISSUE TITLE
RocketMq MessageSelector seems not to work right？

### ISSUE THREAD

**Issue by maketubo** [apache/rocketmq#2559]
1. 版本 4.7.1
2. bug描述：
    按sample写一个java服务： 包含对同一个topic的消费者和生产者。
    生产者生产消息时会putUserProperty比如2
    当设置messageSelector为"*"时，发送一条消息，消费正常，listener成功触发。 设置的伪代码如下：
```
consumer.subscribe(topic, MessageSelector.bySql(filterSql));

```
   当修改为FilterSql案例并重启，发送一条消息，listener没有被触发。设置的伪代码如下：
```
consumer.subscribe("TopicTest", MessageSelector.bySql("a between 0 and 3");
```
  consumer的listener没有被触发但是在控制台中看到消息已经是consumed状态，此时点击resume，listener成功被触发。
3. 把消费者和生产者放在不同的服务上也是相同的结果。(rocketMQ/consumer/producer都启动在localhost)
3. 请问这个行为是否符合rocketMQ的预期？ :(

**Comment by shenhui0509** [comment]
这个应该是因为修改之前消费成功了，消息的offset已经提交。重启之后不会再消费。你可以换consumer group或者重置消费offset尝试一下
