### ISSUE TITLE
There's a block of code that never use

### ISSUE THREAD

**Issue by csdm001** [apache/rocketmq#2561]
in `org.apache.rocketmq.broker.BrokerStartup#createBrokerController ` method:

final MessageStoreConfig messageStoreConfig = new MessageStoreConfig();
if (BrokerRole.SLAVE == messageStoreConfig.getBrokerRole()) {
    int ratio = messageStoreConfig.getAccessMessageInMemoryMaxRatio() - 10;
    messageStoreConfig.setAccessMessageInMemoryMaxRatio(ratio);
}
MessageStoreConfig#brokerRole default value is BrokerRole.ASYNC_MASTER , so I think that  the  if branch code is never executed

**Comment by githublaohu** [comment]
Some data sensitive businesses will use synchronization.Modify configuration to synchronize
一些对数据比较敏感的业务，会使用同步。修改配置为同步

**Comment by csdm001** [comment]
> Some data sensitive businesses will use synchronization.Modify configuration to synchronize
> 一些对数据比较敏感的业务，会使用同步。修改配置为同步
MessageStoreConfig object is newly created and its property brokerRole default value is  ASYNC_MASTER. The code in if will never be executed! 

messageStoreConfig 对象是创建的，默认值是ASYNC_MASTER ，感觉if里的代码永远得不到执行！

**Comment by csdm001** [comment]
> Some data sensitive businesses will use synchronization.Modify configuration to synchronize
> 一些对数据比较敏感的业务，会使用同步。修改配置为同步

MessageStoreConfig object is newly created and its property brokerRole default value is ASYNC_MASTER. The code in if will never be executed!

messageStoreConfig 对象是创建的，默认值是ASYNC_MASTER ，感觉if里的代码永远得不到执行！

**Comment by csdm001** [comment]
> Some data sensitive businesses will use synchronization.Modify configuration to synchronize
> 一些对数据比较敏感的业务，会使用同步。修改配置为同步

MessageStoreConfig object is newly created and its property brokerRole default value is ASYNC_MASTER. The code in if will never be executed!

messageStoreConfig 对象是刚刚创建的，默认值是ASYNC_MASTER ，感觉if里的代码永远得不到执行！

**Comment by githublaohu** [comment]
Yes, it should be on line 142
是的，应该放到142行
