### ISSUE TITLE
[Bug] The judge logic maybe exist problem in org.apache.rocketmq.store.MappedFile#commit0

### ISSUE THREAD

**Issue by horizonzy** [apache/rocketmq#2563]
**BUG REPORT**

1. Please describe the issue you observed:
The code as follow:
```
    protected void commit0(final int commitLeastPages) {
        int writePos = this.wrotePosition.get();
        int lastCommittedPosition = this.committedPosition.get();

        if (writePos - lastCommittedPosition > commitLeastPages) {
            try {
                ByteBuffer byteBuffer = writeBuffer.slice();
                byteBuffer.position(lastCommittedPosition);
                byteBuffer.limit(writePos);
                this.fileChannel.position(lastCommittedPosition);
                this.fileChannel.write(byteBuffer);
                this.committedPosition.set(writePos);
            } catch (Throwable e) {
                log.error("Error occurred when commit data to FileChannel.", e);
            }
        }
    }
```
` if (writePos - lastCommittedPosition > commitLeastPages)` should be 
`if (writePos - lastCommittedPosition > commitLeastPages * OS_PAGE_SIZE)`

**Comment by githublaohu** [comment]
大佬，commitLeastPages每次flush完，都会加上flush的大小，所以不需要OS_PAGE_SIZE。

**Comment by horizonzy** [comment]
感谢回复。
我看这里的逻辑判断应该是去校验有没有达到最小缓存页的数据吧。
现在的比较`if (writePos - lastCommittedPosition > commitLeastPages)`. writePos - lastCommittedPosition这个结果是还没有提交的byte长度，后面commitLeastPages单位是页数，这两个来判断的单位都不是同一个吧。

这个commitLeastPages的值有可能有两种，要么是0，要么是messageStore的`commitCommitLogLeastPages`参数，默认为4嘛。0的话倒是无所谓，但是如果是4的话，那里commit比较的单位都是不一致的。

![image](https://user-images.githubusercontent.com/22524871/104262856-684a7c80-54c3-11eb-82b0-d98d780a13d0.png)

**Comment by CleverZiv** [comment]
> 感谢回复。
> 我看这里的逻辑判断应该是去校验有没有达到最小缓存页的数据吧。
> 现在的比较`if (writePos - lastCommittedPosition > commitLeastPages)`. writePos - lastCommittedPosition这个结果是还没有提交的byte长度，后面commitLeastPages单位是页数，这两个来判断的单位都不是同一个吧。
> 
> 这个commitLeastPages的值有可能有两种，要么是0，要么是messageStore的`commitCommitLogLeastPages`参数，默认为4嘛。0的话倒是无所谓，但是如果是4的话，那里commit比较的单位都是不一致的。
> 
> ![image](https://user-images.githubusercontent.com/22524871/104262856-684a7c80-54c3-11eb-82b0-d98d780a13d0.png)

赞同你的观点。不过这行代码还是有人提了bug之后的修改，可以看看这个 issue: https://github.com/apache/rocketmq/pull/2346

**Comment by horizonzy** [comment]
嗯，从语义来说，那里的单位都不一致，比较是有问题的。
