### ISSUE TITLE
ASYNC_MASTER not supported with dledger?

### ISSUE THREAD

**Issue by HiwayChe** [apache/rocketmq#2583]
does dledger supports ASYNC_MASTER? I use rocketmq 4.8, one leader and two followers, after leader selected, the leader brokerRole is changed to `SYNC_MASTER` showed in rocketmq-console webpage, not `ASYNC_MASTER` I configured in conf/dledger/broker-nx.properties.

**Comment by HiwayChe** [comment]
As each node can be selected as leader, I configured different brokerId for each node, same brokerRole=`ASYNC_MASTER ` in conf/dledger/broker-nx.properties.

**Comment by RongtongJin** [comment]
When using Dledger mode, replication depends on the Raft protocol, so configuring ASYNC_MASTER has no effect.
