### ISSUE TITLE
Which method can consume a message with a message ID

### ISSUE THREAD

**Issue by allnameshasbeensignup** [apache/rocketmq#2584]
we found some msgIDs actually has been executed.but tractType is NOT_CONSUME_YET.
we want to consume them with msgIDs.
thanks very much

**Comment by francisoliverlee** [comment]
@allnameshasbeensignup 
1. when consuming, message id is in MessageExt, check the code bellow:
https://github.com/apache/rocketmq/blob/39bb9386f10d5d8dfe81183c172a3a86f6d313bd/common/src/main/java/org/apache/rocketmq/common/message/MessageExt.java#L27-L48

2. it seems the ways of consuming is not right. 
check following 2 options
  - make sure all consumer instances must substribe the same topics with tags.  [reference aliyun doc](https://help.aliyun.com/document_detail/43523.html?spm=5176.10695662.1996646101.searchclickresult.485c273bEDTfai)
eg: a consumer group named consumerGroupA subscribe topicA, and the app with consumerGroupA deployed on 4 server: s1, s2, s3, s4.

RIGHT Subscription:
```
s1: consumerGroupA sub topicA
s2: consumerGroupA sub topicA
s3: consumerGroupA sub topicA
s4: consumerGroupA sub topicA
```

WRONG Subscription:
```
s1: consumerGroupA sub topicA, tagA
s2: consumerGroupA sub topicA
s3: consumerGroupA sub topicA
s4: consumerGroupA sub topicA
```

  - if run in Docker, make sure every consumer instance has different instance name

**Comment by allnameshasbeensignup** [comment]
I used right method to sub them and consumed them,their's trackType is NOT_COMSUME_YET.

I had known messagids ,I want to change their's  trackType   to CONSUMED from NOT_CONSUME_YET directly. avoid rocketmq resend them to consumers。

use which method?

**Comment by francisoliverlee** [comment]
@allnameshasbeensignup 
it would be messy for queue-asign if not sub right.  
the follwing demo subscription would be not right.  make sure your subscriptions right for one consumer group on every server
```
consumer.subscribe(topicA) on server1;
consumer.subscribe(topicB) on server2;
```
