### ISSUE TITLE
rocketmq-client v4.7 rocketmq.client.logFileMaxSize invalid

### ISSUE THREAD

**Issue by lppppppf** [apache/rocketmq#2592]
settings size is 64MB:
-Drocketmq.client.logRoot=logs/rocketmqlogs -Drocketmq.client.logFileMaxSize=67108864

but log file size also exceed it:
-rw-r--r--    1 root     root      108.2M Jan 13 07:46 rocketmq_client.log

**Comment by duhenglucky** [comment]
@lppppppf FYI. https://mp.weixin.qq.com/s/rXWl5-1QyFiv7b4M-2MFpA, would you like do some tests and submit the test results to this repo?
