### ISSUE TITLE
Alibaba RocketMQ 3.2.6 WARN DispatchMessageService - [BUG]logic queue order maybe wrong?

### ISSUE THREAD

**Issue by zxj058** [apache/rocketmq#2593]
DispatchMessageService - [BUG]logic queue order maybe wrong, expectLogicOffset: 59196310420 currentLogicOffset: 59196310380 Topic: topic_test QID: 1 Diff: 40

Why does this happen？

**Comment by duhenglucky** [comment]
@zxj this issue seems had been fixed in the latest version, Why not try the latest version：）
