### ISSUE TITLE
why that the message filter module has been deleted, why do you need to start the filterServer?

### ISSUE THREAD

**Issue by javaChain** [apache/rocketmq#2601]
https://github.com/apache/rocketmq/issues/452
4.7.1 brokerstartup will createFilterServer,but org.apache.rocketmq.filtersrv.FiltersrvStartup is deleted?
```
public void start() {

        this.scheduledExecutorService.scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                try {
                    FilterServerManager.this.createFilterServer();
                } catch (Exception e) {
                    log.error("", e);
                }
            }
        }, 1000 * 5, 1000 * 30, TimeUnit.MILLISECONDS);
    }
```
this code is not work!

**Comment by githublaohu** [comment]
Provide more powerful functions, hope to provide SPI and hot loading, I guess

**Comment by Jaskey** [comment]
good insights! @duhenglucky would you please help to answer?

**Comment by duhenglucky** [comment]
@javaChain @Jaskey Actully，the filterserver-related functions are replaced by TAG and SQL filtering, which brings better security and also provides better execution performance. The relevant code above should not be cleaned up yet.
