### ISSUE TITLE
Hope there is 'good for new' tag for new guys

### ISSUE THREAD

**Issue by honganan** [apache/rocketmq#2603]
As the title says(Hope there is 'good for new' tag for new guys)

**Comment by githublaohu** [comment]
What do you need this label for?
你需要这个标签的目的是什么？

**Comment by honganan** [comment]
I mean 'good first issue' tag, which tag issues that good for beginners

**Comment by duhenglucky** [comment]
@honganan Good advice, no doubt, ping @RongtongJin @ShannonDing @zongtanghu @vongosling

**Comment by vongosling** [comment]
IMO, it is not easy to define what's right for those guys, what's is not for the newbie. You could carefully check the using labels to find out what the community is dealing with recently, such as wip like this https://github.com/apache/rocketmq-externals/issues/673.


BTW, to learn a complex open source project, you could start with more documents and more tests.
