### ISSUE TITLE
Send heartbeat to brokers in need

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#2605]
Client instances send heartbeat requests to brokers to keep them alive status on the broker side, which is helpful to load balancing.

In case some broker nodes do not work as expected, we wipe read/write permissions of topics from these nodes. After permissions erased, clients should stop sending heartbeat requests to them.

However, clients, at present, still send heartbeat requests to brokers to maintain connection alive, which yields exceptions on the client-side when bringing these brokers offline.

Clients should stop sending keep-alive heartbeat requests to brokers when all topics, which clients have an interest in, have 0 read/write queue number or read/write permissions erased.

**Comment by githublaohu** [comment]
What if the broker is only temporarily invalid? The current mechanism can solve this problem.

Heartbeat doesn't consume much performance, can it be ignor

如果broker只是临时的无效，这样情况怎么办？目前的机制可以解决这种问题。
心跳没有多少性能消耗，可以忽略不计吧

**Comment by lizhimins** [comment]
在迁移或者查看消费者运行状态的情况下，客户端会连接到读写队列为0的Broker，此时管控侧需要再根据路由修改查询方式，这个实现较为麻烦，如果客户端不连接到“无效”的Broker会更好。

Clients should stop sending keep-alive heartbeat requests to brokers when all topics, which clients have an interest in, have 0 read/write queue number or read/write permissions erased.
