### ISSUE TITLE
rocketmq ACL权限控制到底怎么处理？按照中英文文档设置没效果呀

### ISSUE THREAD

**Issue by caiwenlong1989** [apache/rocketmq#2606]
rocketmq版本4.7.1，JDK8，Win10环境
设置${RMQ_HOME}/conf/broker.conf，添加aclEnable=true
acl配置文件没动，用的默认的，用户RocketMQ的topicA和groupA都是DENY权限
启动namesrv，启动broker
编写producer，设置AclRPCHook（“RocketMQ”，“12345678”），发消息到topicA，居然成功了，不是应该没权限吗？
编写consumer，设置AclRPCHook（“groupA”，“RocketMQ”，“12345678”），订阅topicA，居然也成功了

**Comment by duhenglucky** [comment]
@caiwenlong1989 具体ACL 的设置，包括开启可以参考这个文档：https://github.com/apache/rocketmq/blob/master/docs/cn/acl/user_guide.md

**Comment by qiuhuanhen** [comment]
请问最后解决了吗？开启aclEnable=true 但是使用 mqbroker -m命令查看 它就是false ，不知道为什么没加载进去，应该是没加载进去 所以消费者任意用户都可以消费
