### ISSUE TITLE
Set benchmark`s consumer isSuffixEnable defautl false and update help info

### ISSUE THREAD

**Issue by xxd763795151** [apache/rocketmq#2607]
**BUG REPORT**

class: org.apache.rocketmq.example.benchmark.Consumer

question 1: the default value of isSuffixEnable should be false, then it is more friendly. But it`s true now.
question 2: the help info about isSuffixEnable is wrong, as follow:
```
"group prefix enable", true, "Consumer group name, Default: false"
```

**Comment by duhenglucky** [comment]
@xxd763795151 would you like submit a PR to fix it?

**Comment by xxd763795151** [comment]
> @xxd763795151 would you like submit a PR to fix it?

@duhenglucky Yeah. I just submitted it.   https://github.com/apache/rocketmq/pull/2608

**Comment by jack5505** [comment]
Hello guys I'm new in this project. I want to be contributor of thi project very interesting

**Comment by duhenglucky** [comment]
@jack5505 thanks for your contribution, this PR merged, hope to see more contributions from you：）
