### ISSUE TITLE
请教下RocketMq延迟消息可以自定义延迟消费的时间吗？

### ISSUE THREAD

**Issue by leafmirror** [apache/rocketmq#2610]
请教下RocketMq延迟消息可以自定义延迟消费的时间吗？

**Comment by November22** [comment]
![image](https://user-images.githubusercontent.com/26109828/105014156-0b2e6800-5a7b-11eb-9a99-31a39415bb15.png)

**Comment by November22** [comment]
可以，features.md里面有说明，目录8，定时消息。
