### ISSUE TITLE
set haslavefallbehindmax = 26843545600 is unsuccessful

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#2611]
I want to increase haslavefallbehindmax to 26743545600, thereby reducing slave_not_available. But even though I set haslavefallbehindmax=26843545600 in broker.conf, I actually see 268435456 on the console.
You can see the following information in broker.log：
2021-01-19 19:58:46 INFO AdminBrokerThread_2 - Replace, key: haSlaveFallbehindMax, value: 26843545600 -> 268435456

version：4.8.0

**Comment by maixiaohai** [comment]
```  private int haSlaveFallbehindMax = 1024 * 1024 * 256;```
it's a int number @iamqq23ue

**Comment by iamqq23ue** [comment]
> ` private int haSlaveFallbehindMax = 1024 * 1024 * 256;`
> it's a int number @iamqq23ue

thank you.
