### ISSUE TITLE
Avoid unnecessary data copy

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#2614]
This is an improvement issue.

When we deserialize network data back to RemotingCommand, we always array-copy the body part.

```java
 public static RemotingCommand decode(final ByteBuffer byteBuffer) {
        int length = byteBuffer.limit();
        int oriHeaderLen = byteBuffer.getInt();
        int headerLength = getHeaderLength(oriHeaderLen);

        byte[] headerData = new byte[headerLength];
        byteBuffer.get(headerData);

        RemotingCommand cmd = headerDecode(headerData, getProtocolType(oriHeaderLen));

        int bodyLength = length - 4 - headerLength;
        byte[] bodyData = null;
        if (bodyLength > 0) {
            bodyData = new byte[bodyLength];
            byteBuffer.get(bodyData);
        }
        cmd.body = bodyData;

        return cmd;
    }
```

For messages with a large body, this brings in significant overhead.  

Instead of immediately copying data from direct ByteBuf to heap array, we should keep referencing the sliced frame and release it after use.

This case holds valid for many request code, message sending, pull message(for the client)...

**Comment by lizhiboo** [comment]
> ```java
> headerDecode
> ```

IMO, decode operation can not avoid. Even if use sliced frame and deliver to next processor, decode also needed finally. Sliced frame and increase ref maybe used for gateway scene.
