### ISSUE TITLE
benchmark`s producer do not support to specify the quantity of send messages

### ISSUE THREAD

**Issue by xxd763795151** [apache/rocketmq#2615]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
benchmark`s producer do not support to specify the quantity of send messages

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by githublaohu** [comment]
That benchmark？

**Comment by xxd763795151** [comment]
> That benchmark？

@githublaohu 我用benchmark的prodcuer压测开启消息轨迹的场景，同时想要知道轨迹消息是否出现丢失，所以添加了个属性，可以指定发送多少条消息就测试结束（像jmeter指定请求数一样），比如1亿条等，不会持续运行需要其它方式中止，这样我也方便查看消息轨迹的数量，如果不指定属性，就还是原有执行方式。我猜测可能会有其它同学有相似场景，就顺便提了个pr，如果觉得意义不大，可以关闭这个pr.：https://github.com/apache/rocketmq/pull/2617

**Comment by duhenglucky** [comment]
@xxd763795151 挺好的一个优化

**Comment by lizhimins** [comment]
很棒，目前Benchmark和demo有很多不完善的地方，这些细节都很值得改进

**Comment by duhenglucky** [comment]
merged
