### ISSUE TITLE
A question about Rocketmq4.5.2 ScheduleMessageService

### ISSUE THREAD

**Issue by suntianji123** [apache/rocketmq#2620]
/**
         * 正确的到期时间
         * @param now 当前时间
         * @param deliverTimestamp 延时消息的截止时间
         * @return
         */
        private long correctDeliverTimestamp(final long now, final long deliverTimestamp) {
            //延时消息的截止时间
            long result = deliverTimestamp;

            long maxTimestamp = now + ScheduleMessageService.this.delayLevelTable.get(this.delayLevel);
            if (deliverTimestamp > maxTimestamp) {//这里应该改为maxTimestamp > deliverTimestamp
                result = now;
            }

            return result;
        }

**Comment by RongtongJin** [comment]
这应该不是一个bug，我认为deliverTimestamp > maxTimestamp是合理的
