### ISSUE TITLE
Cache NetworkInterfaces to reduce the time taken to access network card information

### ISSUE THREAD

**Issue by wangkaish** [apache/rocketmq#2633]
This is an improvement issue.

`java.net.NetworkInterface.getNetworkInterfaces()` is a heavyweight operation, this pull request will cache NetworkInterfaces to reduce the time taken to access network card information

**Comment by wangkaish** [comment]
@ShannonDing  Can anyone merge this request?

**Comment by Git-Yang** [comment]
> @ShannonDing Can anyone merge this request?

Please create a PR.

**Comment by wangkaish** [comment]
> 
Hi, I created a PR #2634, but the code that Travis CI runs is not my code, can you help me find out why?

**Comment by wangkaish** [comment]
> > @ShannonDing Can anyone merge this request?
> 
> Please create a PR.

Hi, I created a PR #2634, but the code that Travis CI runs is not my code, can you help me find out why?

**Comment by wangkaish** [comment]
> > @ShannonDing Can anyone merge this request?
> 
> Please create a PR.

Hi, Travis CI check fixed.
