### ISSUE TITLE
[Enhance] Remove unnecessary property(REAL_TOPIC and REAL_QID) when save real schedule msg.

### ISSUE THREAD

**Issue by horizonzy** [apache/rocketmq#2639]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Send a delay msg to broker, it first put to schduleTopic, when schduleMessageService will revert it to origin, after revert, the msg will contains 'REAL_TOPIC' and 'REAL_QID' property. These properties is unnecessary I think, remove it to reduce byte length.

![image](https://user-images.githubusercontent.com/22524871/105988662-f2592e80-60da-11eb-92e6-ed1f749255b5.png)

**Comment by githublaohu** [comment]
不建议删除。两个字符串key，加qid，tpicic也就那写空间，保留肯定有它的价值。比如方便数据的追溯等。
扩展应该优先于所谓的干净。

**Comment by horizonzy** [comment]
> 不建议删除。两个字符串key，加qid，tpicic也就那写空间，保留肯定有它的价值。比如方便数据的追溯等。
> 扩展应该优先于所谓的干净。

如果需要溯源的话也应该只保留delay。表明这个msg是从哪个schedule queue来的。现在这两个信息，在msg的属性中已经有了，是冗余的。
