### ISSUE TITLE
ConsumeMessageOrderlyService  can use ReentrantLock 

### ISSUE THREAD

**Issue by zangyk** [apache/rocketmq#264]
The ConsumeRequest class code is :
final Object objLock = messageQueueLock.fetchLockObject(this.messageQueue);
 synchronized (objLock) {
     ......
  }
it will block the  messageQueue and other messageQueue  to process 
we can use ReentrantLock.tryLock()

**Comment by zangyk** [comment]
ReentrantLock objLock = messageQueueLock.fetchLockObject(this.messageQueue);
if(objLock.tryLock())
{
  .....
}else
{
 ConsumeMessageOrderlyService.this.submitConsumeRequestLater(this.messageQueue,this.processQueu,10);
}

**Comment by zangyk** [comment]
Other question is messageQueueLock class  should have "consumerGroupName" param

**Comment by vongosling** [comment]
This is not Q & A channel, please read our issue template carefully.

**Comment by zangyk** [comment]
I think it is a question,it has low operating efficiency
