### ISSUE TITLE
rocketmq消息发送到集群的master上,消费者只能消费一个master上消息是什么原因？

### ISSUE THREAD

**Issue by wangyanan0629** [apache/rocketmq#2649]
![image](https://img-ask.csdnimg.cn/upload/1612178727541.png)
![image](https://img-ask.csdnimg.cn/upload/1612178789480.png)
![image](https://img-ask.csdnimg.cn/upload/1612179194685.png)
采用的是默认的集群消息策略，其中4条消息发送到了broker2，broker1的可以正常消费，分发到broker2的消息为什么不能被消费呢？

**Comment by duhenglucky** [comment]
@wangyanan0629 可以发一些rocketmq_client.log 看下哈，除此以外，通过mqadmin 的consumerStatus，以及consumeProgress查看下消费状态，上面的图片挂了。

**Comment by wangyanan0629** [comment]
@duhenglucky  我把图片补充了一下能看到吗？
