### ISSUE TITLE
为什么topic和group 名字要限制只能包含这些字符 VALID_PATTERN_STR = "^[%|a-zA-Z0-9_-]+$"

### ISSUE THREAD

**Issue by uptop** [apache/rocketmq#265]
创建topic 名字里面包含. 但订阅时候抛错，看了一下是name 限定在这些字符 VALID_PATTERN_STR = "^[%|a-zA-Z0-9_-]+$" 请问这么做是出于什么考虑 为什么topic 和group 名字里面不能包含"." 既然创建时候不做限制，为什么订阅时候要做限制呢

**Comment by vongosling** [comment]
This is not Q & A channel, please read our issue template carefully.

**Comment by uptop** [comment]
对不起 搞错了 不过感觉这更像一个隐蔽的bug呢 创建topic不做限制，只有发送消息时候才检测topic是否符合规范

**Comment by uptop** [comment]
麻烦给个Q&A的链接 刚才看了一圈 没找到 @vongosling

**Comment by vongosling** [comment]
http://rocketmq.apache.org/about/contact/

**Comment by uptop** [comment]
方便简单解释下为什么RocketMQ会做这个限制吗？比如构建索引或者存储时候有什么特殊的情况需要考虑，才做了这个限制吗。 @vongosling
