### ISSUE TITLE
rocketmq 4.1升级4.7,  4.7的broker的数据存储目录可以使用4.1的目录吗？

### ISSUE THREAD

**Issue by November22** [apache/rocketmq#2651]
4.1升级到4.7, Broker存储数据的格式是否有变化，没有变化的话，4.7的Broker是否可以正常读取4.1的数据，如commitlog,topic信息等

**Comment by duhenglucky** [comment]
@November22 HA主从模式架构没有变化的，可以直接升级，如果想升级到raft 多副本架构，可以参考：https://github.com/apache/rocketmq/blob/master/docs/cn/dledger/deploy_guide.md
