### ISSUE TITLE
RocketMQ messages are sent to two nodes in the cluster. What is the reason that the consumer can only consume data on one node? 

### ISSUE THREAD

**Issue by dawang1024** [apache/rocketmq#2653]
![image](https://user-images.githubusercontent.com/67535305/106684768-0d0f3400-6602-11eb-8b73-e529bc6dafb4.png)
![image](https://user-images.githubusercontent.com/67535305/106684804-22845e00-6602-11eb-83b3-ef44acd7d7d1.png)
![image](https://user-images.githubusercontent.com/67535305/106684844-3334d400-6602-11eb-8260-cfe83a83dd0c.png)

Why can messages on Broker2 be distributed to Broker2 and not consumed by subscribing？
--------------------------------------------------------------
为什么broker2上的消息可以分发到上边而不能被订阅消费？

**Comment by lizhimins** [comment]
从第二个截图来看 确实发送到两台broker上了，可以排查下消费者是否能连到 broker2 上

**Comment by wangyanan0629** [comment]
只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息

**Comment by RongtongJin** [comment]
> 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息

消费者只启动了单台吗？是以容器的方式启动的吗？

**Comment by wangyanan0629** [comment]
> > 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息
> 
> 消费者只启动了单台吗？是以容器的方式启动的吗？

用的是docker容器启动的集群

**Comment by RongtongJin** [comment]
> > > 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息
> > 
> > 
> > 消费者只启动了单台吗？是以容器的方式启动的吗？
> 
> 用的是docker容器启动的集群

是同一台机器上有多个docker容器吗？是不是instanceName相同导致的，可以consumer强制setInstanceName，保证每一个consumer的instanceName都独一无二试试

**Comment by wangyanan0629** [comment]
> instanceName



> > > > 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息
> > > 
> > > 
> > > 消费者只启动了单台吗？是以容器的方式启动的吗？
> > 
> > 
> > 用的是docker容器启动的集群
> 
> 是同一台机器上有多个docker容器吗？是不是instanceName相同导致的，可以consumer强制setInstanceName，保证每一个consumer的instanceName都独一无二试试

是通过docker-compose搭建的单机集群，集群架构是2nameServer+2master+2salve

**Comment by wangyanan0629** [comment]
> > > > 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息
> > > 
> > > 
> > > 消费者只启动了单台吗？是以容器的方式启动的吗？
> > 
> > 
> > 用的是docker容器启动的集群
> 
> 是同一台机器上有多个docker容器吗？是不是instanceName相同导致的，可以consumer强制setInstanceName，保证每一个consumer的instanceName都独一无二试试
这个是docker-compose的配置
`version: '3.5'
services:
  namesrv1:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: namesrv1
    ports:
      - 9876:9876
    volumes:
      - /opt/rocketmq/namesrv1/log:/opt/logs
      - /opt/rocketmq/namesrv1/data:/opt/store
    command: sh mqnamesrv
    networks:
      rocketmq:
        aliases:
          - namesrv1
  namesrv2:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: namesrv2
    ports:
      - 9877:9876
    volumes:
      - /opt/rocketmq/namesrv2/log:/opt/logs
      - /opt/rocketmq/namesrv2/data:/opt/store
    command: sh mqnamesrv
    networks:
      rocketmq:
        aliases:
          - namesrv2
  broker-m-1:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: broker-m-1
    links:
      - namesrv1:namesrv1
      - namesrv2:namesrv2
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "namesrv1:9876"
      JAVA_OPTS: "-Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
    volumes:
      - /opt/rocketmq/broker-m-1/log:/opt/logs
      - /opt/rocketmq/broker-m-1/data:/opt/store
      - /opt/rocketmq/broker-m-1/conf/broker-m-1.conf:/opt/rocketmq-4.3.0/conf/broker-m-1.conf
    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker-m-1.conf autoCreateTopicEnable=true &
    networks:
      rocketmq:
        aliases:
          - broker-m-1
  broker-s-1:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: broker-s-1
    links:
      - namesrv1:namesrv1
      - namesrv2:namesrv2
    ports:
      - 11909:10909
      - 11911:11911
      - 11912:10912
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "namesrv1:9876"
      JAVA_OPTS: "-Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
    volumes:
      - /opt/rocketmq/broker-s-1/log:/opt/logs
      - /opt/rocketmq/broker-s-1/data:/opt/store
      - /opt/rocketmq/broker-s-1/conf/broker-s-1.conf:/opt/rocketmq-4.3.0/conf/broker-s-1.conf
    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker-s-1.conf autoCreateTopicEnable=true &
    networks:
      rocketmq:
        aliases:
          - broker-s-1
  broker-m-2:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: broker-m-2
    links:
      - namesrv1:namesrv1
      - namesrv2:namesrv1
    ports:
      - 12909:10909
      - 12911:12911
      - 12912:10912
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "namesrv1:9876"
      JAVA_OPTS: "-Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
    volumes:
      - /opt/rocketmq/broker-m-2/log:/opt/logs
      - /opt/rocketmq/broker-m-2/data:/opt/store
      - /opt/rocketmq/broker-m-2/conf/broker-m-2.conf:/opt/rocketmq-4.3.0/conf/broker-m-2.conf
    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker-m-2.conf autoCreateTopicEnable=true &
    networks:
      rocketmq:
        aliases:
          - broker-m-2
  broker-s-2:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: broker-s-2
    links:
      - namesrv1:namesrv1
      - namesrv2:namesrv2
    ports:
      - 13909:10909
      - 13911:13911
      - 13912:10912
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "namesrv1:9876"
      JAVA_OPTS: "-Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
    volumes:
      - /opt/rocketmq/broker-s-2/log:/opt/logs
      - /opt/rocketmq/broker-s-2/data:/opt/store
      - /opt/rocketmq/broker-s-2/conf/broker-s-2.conf:/opt/rocketmq-4.3.0/conf/broker-s-2.conf
    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker-s-2.conf autoCreateTopicEnable=true &
    networks:
      rocketmq:
        aliases:
          - broker-s-2
  rocketmq-console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console
    ports:
      - 8090:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=namesrv1:9876;namesrv2:9877 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
      rocketmq:
        aliases:
          - rocketmq-console
networks:
  rocketmq:
    name: rocketmq
    driver: bridge`

**Comment by wangyanan0629** [comment]
> > instanceName
> 
> > > > > 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息
> > > > 
> > > > 
> > > > 消费者只启动了单台吗？是以容器的方式启动的吗？
> > > 
> > > 
> > > 用的是docker容器启动的集群
> > 
> > 
> > 是同一台机器上有多个docker容器吗？是不是instanceName相同导致的，可以consumer强制setInstanceName，保证每一个consumer的instanceName都独一无二试试
> 
> 是通过docker-compose搭建的单机集群，集群架构是2nameServer+2master+2salve
这个是docker-compose的配置文件
[docker-compose.txt](https://github.com/apache/rocketmq/files/6002156/docker-compose.txt)

**Comment by wangyanan0629** [comment]
> > > instanceName
> > 
> > 
> > > > > > 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息
> > > > > 
> > > > > 
> > > > > 消费者只启动了单台吗？是以容器的方式启动的吗？
> > > > 
> > > > 
> > > > 用的是docker容器启动的集群
> > > 
> > > 
> > > 是同一台机器上有多个docker容器吗？是不是instanceName相同导致的，可以consumer强制setInstanceName，保证每一个consumer的instanceName都独一无二试试
> > 
> > 
> > 是通过docker-compose搭建的单机集群，集群架构是2nameServer+2master+2salve
> > 这个是docker-compose的配置文件
> > [docker-compose.txt](https://github.com/apache/rocketmq/files/6002156/docker-compose.txt)

设置强制消费也测试过，不起作用

**Comment by dujinsong** [comment]
> > > > instanceName
> > > 
> > > 
> > > > > > > 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息
> > > > > > 
> > > > > > 
> > > > > > 消费者只启动了单台吗？是以容器的方式启动的吗？
> > > > > 
> > > > > 
> > > > > 用的是docker容器启动的集群
> > > > 
> > > > 
> > > > 是同一台机器上有多个docker容器吗？是不是instanceName相同导致的，可以consumer强制setInstanceName，保证每一个consumer的instanceName都独一无二试试
> > > 
> > > 
> > > 是通过docker-compose搭建的单机集群，集群架构是2nameServer+2master+2salve
> > > 这个是docker-compose的配置文件
> > > [docker-compose.txt](https://github.com/apache/rocketmq/files/6002156/docker-compose.txt)
> 
> 设置强制消费也测试过，不起作用

哈喽，我遇到过此情况，不知道能否解决你的问题。先启动一个broker集群，正常收发消息，后面扩容了一个broker集群，扩容的集群能发送消息，但是没有消费，我通过console将topic以及消费组添加到新集群中后能够消费消息。扩容broker集群提前将plain_acl.yml、topics.json 以及subscriptionGroup.json文件拷贝到新集群的相应目录下能够避免此问题。消费组添加到新集群中后能够消费消息。扩容broker集群提前将plain_acl.yml、topics.json 以及subscriptionGroup.json文件拷贝到新集群的相应目录下能够避免此问题。

**Comment by dujinsong** [comment]
> > > > instanceName
> > > 
> > > 
> > > > > > > 只有在广播模式的时候可以连上broker2,集群模式的时候只能消费broker1上的消息
> > > > > > 
> > > > > > 
> > > > > > 消费者只启动了单台吗？是以容器的方式启动的吗？
> > > > > 
> > > > > 
> > > > > 用的是docker容器启动的集群
> > > > 
> > > > 
> > > > 是同一台机器上有多个docker容器吗？是不是instanceName相同导致的，可以consumer强制setInstanceName，保证每一个consumer的instanceName都独一无二试试
> > > 
> > > 
> > > 是通过docker-compose搭建的单机集群，集群架构是2nameServer+2master+2salve
> > > 这个是docker-compose的配置文件
> > > [docker-compose.txt](https://github.com/apache/rocketmq/files/6002156/docker-compose.txt)
> 
> 设置强制消费也测试过，不起作用

哈喽，我遇到过此情况，不知道能否解决你的问题。先启动一个broker集群，正常收发消息，后面扩容了一个broker集群，扩容的集群能发送消息，但是没有消费，我通过console将topic以及消费组添加到新集群中后能够消费消息。扩容broker集群提前将plain_acl.yml、topics.json 以及subscriptionGroup.json文件拷贝到新集群的相应目录下能够避免此问题。
