### ISSUE TITLE
[Feature-Requiring] Consumer group should have its auth-secret.

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq#2658]
Consumer group is accidentally interrupted by another app, causing consumes message incorrectly.

It's easily detected how many consumer app  nodes in a consumer group, but It's really hard to tell whether some of nodes(only ip:port is shown) are acturally correct app nodes. Some of your teammate might start another app which should have different consumer group name but incorrectly use a same one.

In my opinion, my consumer group should have my own auth ensurance, in this case ,another  app should join consumer group failed if auth secret is not correct.!

**Comment by coder-zzzz** [comment]
you can use acl to limit the illegal consumer connect to mq

**Comment by RongtongJin** [comment]
ACL mechanism can be used.
