### ISSUE TITLE
Why did you create another DefaultMQProducer class in MQClientInstance class?

### ISSUE THREAD

**Issue by chenchencc** [apache/rocketmq#266]
hi,
  i am very interest in RocketMQ,so i decided to learn it's code,but i found the DefaultMQProducer class also created in MQClientInstance class,i don't understant(i just learn it ),thank you!

**Comment by chenchencc** [comment]
![image](https://user-images.githubusercontent.com/15829785/38133447-d8de87ac-3441-11e8-8439-8901850a3ce5.png)

**Comment by zhouxinyu** [comment]
The issue tracker is **ONLY** used for bug report and feature request.
Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/)
