### ISSUE TITLE
Question about executeLocalTransaction method

### ISSUE THREAD

**Issue by crossdawn** [apache/rocketmq#2665]
发送事务消息时 executeLocalTransaction 方法和本地业务绑定在一个事务中，无法确定事务的状态。此时，只能返回UNKNOWN，通过checkLocalTransaction来检查本地事务，但是checkLocalTransaction是延迟执行的。
想问一下是我理解有问题还是确实这样设计的？

**Comment by RongtongJin** [comment]
为什么无法确定事务的状态？executeLocalTransaction 方法是执行本地事务，执行完成后就知道是否成功，从而返回commit或rollback。

**Comment by crossdawn** [comment]
> 为什么无法确定事务的状态？executeLocalTransaction 方法是执行本地事务，执行完成后就知道是否成功，从而返回commit或rollback。

我是在两个数据库操作中执行的发事务消息操作，所以发消息时候，整个事务没有执行完毕，无法确定。sendMessageInTransaction在sendOk后就开始executeLocalTransaction这个方法，应该在这里面要写全部业务？这样的话理解起来像是发了消息再执行业务，而不是执行完业务发了条消息。
