### ISSUE TITLE
deploy 2m-2s-sync rocketmq cluster,but run benchmark error?

### ISSUE THREAD

**Issue by wangzy0327** [apache/rocketmq#2666]
2m-2s-sync cluser is running normal
when i try to run benchmark,The Error is
 java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to [=10.18.127.5:9876] failed

**Comment by lizhimins** [comment]
It looks like a network problem

**Comment by RongtongJin** [comment]
It looks like it's not connected to the nameserver

**Comment by wangzy0327** [comment]
I solve the problem by deleting store directory , then restart successfully




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lizhimins"<notifications@github.com&gt;; 
发送时间: 2021年2月8日(星期一) 中午1:26
收件人: "apache/rocketmq"<rocketmq@noreply.github.com&gt;; 
抄送: "笑傲江湖"<wangzy0327@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/rocketmq] deploy 2m-2s-sync rocketmq cluster,but run benchmark error? (#2666)





 
It looks like a network problem
