### ISSUE TITLE
DLeger模式下broker.log 一直抛出 Error when measuring disk space usage, file doesn't exist on this path: /root/store/commitlog

### ISSUE THREAD

**Issue by Anthony-Dong** [apache/rocketmq#2667]
software version: rocket-mq 4.8.0
java code version: rocket-mq 4.8.0
部署模式：DLeger模式 1broker3node 2name-server
broker机器的日志一直抛出 下面的Error异常
```shell
### ...
2021-02-07 17:10:55 INFO main - enableDLegerCommitLog=true
2021-02-07 17:10:55 INFO main - dLegerGroup=RaftNode00
2021-02-07 17:10:55 INFO main - dLegerPeers=n0-broker-01:40911;n1-broker-02:40911;n2-broker-03:40911
### ...
2021-02-07 17:10:55 INFO main - storePathCommitLog=/root/store/commitlog
### ...
2021-02-07 17:10:59 INFO main - Try to start service thread:PullRequestHoldService started:false lastThread:null
2021-02-07 17:10:59 INFO FileWatchService - FileWatchService service started
2021-02-07 17:10:59 INFO PullRequestHoldService - PullRequestHoldService service started
2021-02-07 17:10:59 INFO main - The broker[RaftNode00, 172.15.64.10:10913] boot success. serializeType=JSON and name server is nameserver-01:9876;nameserver-02:9876
2021-02-07 17:11:00 ERROR DiskCheckScheduledThread1 - Error when measuring disk space usage, file doesn't exist on this path: /root/store/commitlog
### ....
2021-02-07 17:13:09 INFO brokerOutApi_thread_1 - register broker[0]to name server nameserver-01:9876 OK
2021-02-07 17:13:09 INFO brokerOutApi_thread_2 - register broker[0]to name server nameserver-02:9876 OK
2021-02-07 17:13:10 ERROR DiskCheckScheduledThread1 - Error when measuring disk space usage, file doesn't exist on this path: /root/store/commitlog
2021-02-07 17:13:20 ERROR DiskCheckScheduledThread1 - Error when measuring disk space usage, file doesn't exist on this path: /root/store/commitlog
2021-02-07 17:13:30 ERROR DiskCheckScheduledThread1 - Error when measuring disk space usage, file doesn't exist on this path: /root/store/commitlog
```

看了看源码问题是没有兼容DLeger模式，不知道影响在哪
[org.apache.rocketmq.store.DefaultMessageStore#diskCheckScheduledExecutorService](https://github.com/apache/rocketmq/blob/release-4.8.0/store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java#L1346)
```java
        this.diskCheckScheduledExecutorService.scheduleAtFixedRate(new Runnable() {
            public void run() {
                DefaultMessageStore.this.cleanCommitLogService.isSpaceFull();
            }
        }, 1000L, 10000L, TimeUnit.MILLISECONDS);
```
这里的#isSpaceFull 方法
```java
        public boolean isSpaceFull() {
// 直接获取默认的getStorePathCommitLog日志,导致调用getDiskPartitionSpaceUsedPercent异常日志
            String storePathPhysic = DefaultMessageStore.this.getMessageStoreConfig().getStorePathCommitLog();
            double physicRatio = UtilAll.getDiskPartitionSpaceUsedPercent(storePathPhysic);
  }
```
正确获取`storePathPhysic`是
```java
    private String getStorePathPhysic() {
        String storePathPhysic = "";
        if (DefaultMessageStore.this.getMessageStoreConfig().isEnableDLegerCommitLog()) {
            storePathPhysic = ((DLedgerCommitLog)DefaultMessageStore.this.getCommitLog()).getdLedgerServer().getdLedgerConfig().getDataStorePath();
        } else {
            storePathPhysic = DefaultMessageStore.this.getMessageStoreConfig().getStorePathCommitLog();
        }
        return storePathPhysic;
    }

```

问题是：
这个方法的影响应该是检测磁盘的使用空间问题，获取分区内的空闲大小，影响是无法提示磁盘空间的占用情况。虽然现在机器都有磁盘监控报警，但是这块代码确实有问题。
其实对于新的 `DLeger`模式来说，这个配置是没有用的`storePathCommitLog=/root/store/commitlog`

**Comment by maixiaohai** [comment]
@Anthony-Dong https://github.com/apache/rocketmq/issues/2663 上午也碰到了同样的问题，已经提了pr修复

**Comment by RongtongJin** [comment]
Fixed it #2664

**Comment by Yangstatus** [comment]
请问这个问题解决了吗？ 我也遇到类似问题。

**Comment by maixiaohai** [comment]
> 请问这个问题解决了吗？ 我也遇到类似问题。

上面的pr #2664 修复了

**Comment by kuchaguangjie** [comment]
4.9.0 还是一样报错, 要手工 创建文件夹.

**Comment by maixiaohai** [comment]
> `4.9.0` 还是一样报错, 要手工 创建文件夹, 这种问题 发布前不会 简单 测下么, 而且 需要 几个月来修复么 ...

用的 DLedger 模式部署吗？可以发下详细日志吗？

**Comment by kuchaguangjie** [comment]
@maixiaohai 就是按照 官方文档 步骤来的:

**Comment by maixiaohai** [comment]
> @maixiaohai 就是按照 官方文档 步骤来的:
> https://rocketmq.apache.org/docs/quick-start/
> 
> 启动 broker 前 需要 手工创建 2个目录 才能 不 一直 报错:
> 
> ```
> mkdir -p ~/store/commitlog/
> mkdir -p ~/store/consumequeue/
> ```
> 
> 如果 实际步骤 和 文档 不符, 请 更新 文档 说明.

我本地测试了一下，这个报错不影响使用，程序默认会创建目录；
另外，官方文档里直接启动的不是 DLedger 的部署模式

**Comment by kuchaguangjie** [comment]
> > @maixiaohai 就是按照 官方文档 步骤来的:
> > https://rocketmq.apache.org/docs/quick-start/
> > 启动 broker 前 需要 手工创建 2个目录 才能 不 一直 报错:
> > ```
> > mkdir -p ~/store/commitlog/
> > mkdir -p ~/store/consumequeue/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果 实际步骤 和 文档 不符, 请 更新 文档 说明.
> 
> 我本地测试了一下，这个报错不影响使用，程序默认会创建目录；
> 另外，官方文档里直接启动的不是 DLedger 的部署模式

我不知道 什么是 DLedger 模式, 按照 文档 启动就会报错, 也并没有 创建 相应 目录, 必须 手工 创建 才不报错. 报错就 无法启动成功, 也无法正常使用.

**Comment by gaochengyidlmu** [comment]
> > @maixiaohai 就是按照 官方文档 步骤来的:
> > https://rocketmq.apache.org/docs/quick-start/
> > 启动 broker 前 需要 手工创建 2个目录 才能 不 一直 报错:
> > ```
> > mkdir -p ~/store/commitlog/
> > mkdir -p ~/store/consumequeue/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果 实际步骤 和 文档 不符, 请 更新 文档 说明.
> 
> 我本地测试了一下，这个报错不影响使用，程序默认会创建目录；
> 另外，官方文档里直接启动的不是 DLedger 的部署模式

Java version: java 8
OS: mac 
没有默认创建目录，然后一直报错，确实需要手动创建两个目录才会停止报错

**Comment by Git-Yang** [comment]
> > > @maixiaohai 就是按照 官方文档 步骤来的:
> > > https://rocketmq.apache.org/docs/quick-start/
> > > 启动 broker 前 需要 手工创建 2个目录 才能 不 一直 报错:
> > > ```
> > > mkdir -p ~/store/commitlog/
> > > mkdir -p ~/store/consumequeue/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果 实际步骤 和 文档 不符, 请 更新 文档 说明.
> > 
> > 
> > 我本地测试了一下，这个报错不影响使用，程序默认会创建目录；
> > 另外，官方文档里直接启动的不是 DLedger 的部署模式
> 
> Java version: java 8
> OS: mac
> 没有默认创建目录，然后一直报错，确实需要手动创建两个目录才会停止报错

Fixed this issue in PR#3278

**Comment by Slideee** [comment]
这个问题似乎还没有修复，在4.9.2版本下还是存在问题。原因是这里拿commitlog路径的时候没去区分是不是dledger模式。正确的应该改成，String commitLogStorePath = getStorePathPhysic();

![image](https://user-images.githubusercontent.com/48793283/155452249-be62aa95-4699-4439-9214-807fdcfd67ba.png)
