### ISSUE TITLE
RocketMq with PinPoint

### ISSUE THREAD

**Issue by zhangJingTao** [apache/rocketmq#267]
Our Project has made extensive use of rocketmq. Now we want to use pinponit to monitor link call tracking. How can we put the tracepoint's traceId into the rocketmq message body without modifying the contents of the message? Is there extra extension parameter available?

thx!!!!

**Comment by zhouxinyu** [comment]
How about using the message header?

BTW, please use our [mailing lists](http://rocketmq.apache.org/about/contact/) to consult a question.
