### ISSUE TITLE
`N/A` appears when there's no `-s true`  in command ConsumerProgress

### ISSUE THREAD

**Issue by zwillim** [apache/rocketmq#2670]
**improvement issue**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
 
  ./mqadmin ComsumerProgress -n XXXX:9876 -g XXXX

  (no `-s true` option)
- What did you expect to see?
no `Client IP` column
- What did you see instead?
`N/A`s in `Client IP` column

When there is no `-s true` in command ConsumerProgress,  the `N/A`s may make people confused.
 `Client IP` should be hided when there's no `-s true` in command `ConsumerProgress`.

https://github.com/apache/rocketmq/pull/2671

**Comment by zwillim** [comment]
[https://github.com/apache/rocketmq/pull/2671](url)

**Comment by zwillim** [comment]
https://github.com/apache/rocketmq/pull/2671#issue-570130650

**Comment by zwillim** [comment]
https://github.com/apache/rocketmq/pull/2671

**Comment by RongtongJin** [comment]
Merged
