### ISSUE TITLE
Can't Start Name Server on Ubuntu 

### ISSUE THREAD

**Issue by qiaofeng1227** [apache/rocketmq#2689]
**BUG REPORT**

1. Please describe the issue you observed:

steps:
download the rocketmq-all-4.8.0-source-release.zip  
execute the following commands to unpack 4.8.0 source release  
Start Name Server on shell "nohup sh bin/mqnamesrv &"

mqnamesrv  can't start!

Error executing the following script：
`sh ${ROCKETMQ_HOME}/bin/runserver.sh`

2. Please tell us about your environment:
OS:Ubuntu20.04
JDK:1.8
RocketMQ:4.8.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

Our Solution:
Edit file /rocketmq/bin/mqnamesrv,  ` sh ${ROCKETMQ_HOME}/bin/runserver.sh org.apache.rocketmq.namesrv.NamesrvStartup $@` Replace with `bash ${ROCKETMQ_HOME}/bin/runserver.sh org.apache.rocketmq.namesrv.NamesrvStartup $@`

**Comment by fengyiluo** [comment]
Can you provide more error info?

**Comment by lizhiboo** [comment]
> **BUG REPORT**
> 
> 1. Please describe the issue you observed:
> 
> steps:
> download the rocketmq-all-4.8.0-source-release.zip
> execute the following commands to unpack 4.8.0 source release
> Start Name Server on shell "nohup sh bin/mqnamesrv &"
> 
> mqnamesrv can't start!
> 
> Error executing the following script：
> `sh ${ROCKETMQ_HOME}/bin/runserver.sh`
> 
> 1. Please tell us about your environment:
>    OS:Ubuntu20.04
>    JDK:1.8
>    RocketMQ:4.8.0
> 2. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
> 
> Our Solution:
> Edit file /rocketmq/bin/mqnamesrv, ` sh ${ROCKETMQ_HOME}/bin/runserver.sh org.apache.rocketmq.namesrv.NamesrvStartup $@` Replace with `bash ${ROCKETMQ_HOME}/bin/runserver.sh org.apache.rocketmq.namesrv.NamesrvStartup $@`

According to ur solution, is it can not execute sh command on Ubuntu?

**Comment by ShannonDing** [comment]
any more error information?

**Comment by vxinv** [comment]
yes I also encountered the same problem
info --------------------------------------
/server/rocketmq-all-4.8.0-bin-release/bin/runserver.sh: 70: /server/rocketmq-all-4.8.0-bin-release/bin/runserver.sh: [[: not found
Unrecognized option: -Xlog:gc*:file=/dev/shm/rmq_srv_gc_%p_%t.log:time,tags:filecount=5,filesize=30M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by afewnotes** [comment]
same problem here, and just change `sh` to `bash` 

FYI [Difference between single and double square brackets in Bash
](https://stackoverflow.com/questions/13542832/difference-between-single-and-double-square-brackets-in-bash)

**Comment by wenchun** [comment]
I same too:
/opt/develop/rocketmq-all-4.8.0/bin/runserver.sh: 70: /opt/develop/rocketmq-all-4.8.0/bin/runserver.sh: [[: not found
Unrecognized option: -Xlog:gc*:file=/dev/shm/rmq_srv_gc_%p_%t.log:time,tags:filecount=5,filesize=30M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
---------------------------------------------------------------------
what is /opt/develop/rocketmq-all-4.8.0/bin/runserver.sh: 70: /opt/develop/rocketmq-all-4.8.0/bin/runserver.sh: [[: not found ??
if [[ "$JAVA_MAJOR_VERSION" -lt "9" ]] ; then
chang to:
if [ "$JAVA_MAJOR_VERSION" -lt "9" ] ; then
rocketmq-all-4.71/bin/runserver.sh:70 is same above.
