### ISSUE TITLE
Support Ruby SDK

### ISSUE THREAD

**Issue by bigyShot** [apache/rocketmq#2690]
I truly wish you guys can have ruby-cli.

**Comment by bigyShot** [comment]
With more languages supports,rocketmq can get  larger market,
Rocket is so excellent that other languages also want it

**Comment by fengyiluo** [comment]
It's a good idea.

**Comment by ShannonDing** [comment]
At present, the community has no plans for ruby ​​language and welcomed to join the community incubator to strengthen the muti language eco If you are willing to develop ruby ​​client together.
https://github.com/apache/rocketmq-externals

**Comment by vongosling** [comment]
The plan always comes with the needs of the community. Nowadays, I've seen some guys start talking about PHP, NodeJS, even Ruby in this issue. Let's open this request for a long while and hear the feedback from the community :-)

**Comment by lizhimins** [comment]
It is very meaningful to develop multi language client

**Comment by SZMOFEI** [comment]
It is very meaningful to develop multi language client , such as php

**Comment by aaron-ai** [comment]
Aha, welcome to be involved in the development of [rocketmq-clients](https://github.com/apache/rocketmq-clients).
