### ISSUE TITLE
Build error for version 4.7.1

### ISSUE THREAD

**Issue by November22** [apache/rocketmq#2696]
4.7.1根据说明文档打包异常：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (process-resource-bundles) on project rocketmq-all: Ex
ecution process-resource-bundles of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process failed: A required class was missing while e
xecuting org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process: org/apache/commons/collections/ExtendedProperties

maven版本：3.2.5
jdk：1.8
环境：win10 64位

**Comment by vongosling** [comment]
It seems that you could not pull all dependencies from your network. Would you like to paste more info?
