### ISSUE TITLE
Console showed NOT_CONSUME_YET, but no consume actually?

### ISSUE THREAD

**Issue by linkypi** [apache/rocketmq#2697]
rocketmq 4.8.0 单点部署在docker容器中，其中broker的配置文件中已配置brokerIP1 ，配置的是域名，而非实际IP地址：
``` 
brokerIP1=rmqbroker
```
如此配置就会导致问题的出现，若配置的是实际的IP则MQ消息状态正常。通过调试源码发现 rocketmq-tools 在判断消息是否已消费时未对域名进行解析导致。**源码位置： org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java 中的 consumed 方法(linenum: 861)**
![image](https://user-images.githubusercontent.com/4386639/109244141-211d0e80-7819-11eb-9ccb-79de5323f676.png)

修复后：
![image](https://user-images.githubusercontent.com/4386639/109244722-26c72400-781a-11eb-8b56-0244a0c1768f.png)
源码：
``` java
  while (it.hasNext()) {
       Entry<MessageQueue, OffsetWrapper> next = it.next();
       MessageQueue mq = next.getKey();
       if (mq.getTopic().equals(msg.getTopic()) && mq.getQueueId() == msg.getQueueId()) {
           BrokerData brokerData = ci.getBrokerAddrTable().get(mq.getBrokerName());
           if (brokerData != null) {
               final String msgStoreHost = RemotingUtil.socketAddress2String(msg.getStoreHost());
               final String brokerHost = getBrokerIpFromCluster(brokerData);
               log.info("============= msgHostIp: {}, msg.getStoreHost(): {} =============", msgStoreHost, brokerHost);

               if (msgStoreHost.equals(brokerHost)) {
                   log.info("next.getValue().getConsumerOffset(): {}, msg.getQueueOffset(): {}",
                           next.getValue().getConsumerOffset(), msg.getQueueOffset());
                   if (next.getValue().getConsumerOffset() > msg.getQueueOffset()) {
                       return true;
                   }
               }
           }
       }
   }

  private String getBrokerIpFromCluster(BrokerData brokerData ) throws UnknownHostException {
        String addr = brokerData.getBrokerAddrs().get(MixAll.MASTER_ID);
        final String[] arr = addr.split(":");
        final String host = arr[0];
        final String brokerIp = InetAddress.getAllByName(host)[0].getHostAddress() + ":" + arr[1];
        return brokerIp;
    }
```
希望尽早修复改问题。

此外还遇到另外一个问题，同样在docker环境下，消息中的 storeHost 是宿主机IP，而 brokerHost 却是容器IP，也会导致该问题，具体原因还在排查，暂时没找到原因.

**Comment by fengyiluo** [comment]
Mention a pull request by yourself and associate this issue.

**Comment by vongosling** [comment]
Thanks for your opt. you could make a pr as fengyihui suggested. BTW, we must keep in mind that InetAddress.getByName() implementation is blocking and standard Java libraries lack any non-blocking implementations.

**Comment by xhrg** [comment]
If rocketmq use docker or multiple network cards, rocketmq should initiate a UDP request to an external IP, and then get the IP address of the current server. rocketmq cannot use the system call of InetAddress API。It's just my idea

**Comment by ahaha-vip** [comment]
遇到同样的问题，请问这是只是console显示有误，还是也会影响消息的正常消费？

**Comment by linkypi** [comment]
> 遇到同样的问题，请问这是只是 console 显示有误，还是也会影响消息的正常消费？

Message consumption is normal, but the console display is incorrect.
