### ISSUE TITLE
TopicRouteSubCommand enhancement

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq#2698]
当前版本下命令行工具对路由查询结果返回直接输出了Json格式，在节点较多的情况下不易查看和进一步分析，例如

![image](https://user-images.githubusercontent.com/22487634/109374590-73c9f980-78f1-11eb-8239-0f7d1e470b69.png)

通过添加 -l 参数，让命令行工具和 consumerProgress 等其他命令一样以表格的形式返回，效果如下

![image](https://user-images.githubusercontent.com/22487634/109374613-965c1280-78f1-11eb-95b4-44500c9e147a.png)

**Comment by vongosling** [comment]
Good improvement, will you make a pr?
