### ISSUE TITLE
DefaultMessageStore#shutdown duplicate flush

### ISSUE THREAD

**Issue by jiangshifu** [apache/rocketmq#2703]
class DefaultMessageStore{    
   public void shutdown() {
            this.storeCheckpoint.flush();
            this.storeCheckpoint.shutdown();
    }
 }

class StoreCheckpoint{
    public void shutdown() {
        this.flush();
    }
}

**Comment by lizhiboo** [comment]
> class DefaultMessageStore{
> public void shutdown() {
> this.storeCheckpoint.flush();
> this.storeCheckpoint.shutdown();
> }
> }
> 
> class StoreCheckpoint{
> public void shutdown() {
> this.flush();
> }
> }

In which version?
