### ISSUE TITLE
duplication when network fail (re-consume from min offset)

### ISSUE THREAD

**Issue by shunbenben** [apache/rocketmq#2705]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
wipewriteperm and then disable the network(shutdown access switch) for about 1 hour of broker-a in a 3m3s cluster.

- What did you expect to see?
Duplicate consumption of messages within few minutes or no duplicate consumption
- What did you see instead?
broker-a: duplicate consumption of messages within 3 days;  large TPS ; consumer get message from min offset
broker-b/broker-c: normal;
2. Please tell us about your environment:
redhat 6.8; rocketmq v3.1.8; Cluster mode consumption; 3m3s;
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
consumer get message from LAST offset;  no much duplicate consumption.
2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
must-have
4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by francisoliverlee** [comment]
give it a try with version 4.X.X. version 3.x.x too old

**Comment by duhenglucky** [comment]
duplicated with https://github.com/apache/rocketmq/issues/2708, more this discussion can be found in issue 2708
