### ISSUE TITLE
SEND_OK will still be returned when the storage is abnormal  ，which may cause message loss

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#2706]
when the flush is abnormal ，SEND_OK will still be returned 。It will cause possible message loss .

I have submitted  a pull request #2707 to fix it. 

RocketMQ version 4.8.0 ,SYNC_FLUSH.

error code show as below ：

You can see that if there is an error, a try catch will be performed .Then   log.error("Error occurred when force data to disk.", e);
But there is no error code returned to the client, and the client still thinks that the send is successful. 

public int flush(final int flushLeastPages) {
    if (this.isAbleToFlush(flushLeastPages)) {
        if (this.hold()) {
            int value = getReadPosition();
            try {
                //We only append data to fileChannel or mappedByteBuffer, never both.
                if (writeBuffer != null || this.fileChannel.position() != 0) {
                    this.fileChannel.force(false);
                } else {
                    this.mappedByteBuffer.force();
                }
            } catch (Throwable e) {
                log.error("Error occurred when force data to disk.", e);
            }

            this.flushedPosition.set(value);
            this.release();
        } else {
            log.warn("in flush, hold failed, flush offset = " + this.flushedPosition.get());
            this.flushedPosition.set(getReadPosition());
        }
    }
    return this.getFlushedPosition();
}

**Comment by francisoliverlee** [comment]
can you give out a description for how to lost message ?

**Comment by iamqq23ue** [comment]
> can you give out a description for how to lost message ?

For example, when the disk read only and flush fails, the actual message is not written to the disk.
In order to solve read only, the server must be restarted, and then the message will be lost.

**Comment by iamqq23ue** [comment]
#2707

**Comment by lizhiboo** [comment]
> when the flush is abnormal ，SEND_OK will still be returned 。It will cause possible message loss .
> 
> I will submit a PR to fix it
> 
> code show as below ：
> 
> ```java
> public int flush(final int flushLeastPages) {
>     if (this.isAbleToFlush(flushLeastPages)) {
>         if (this.hold()) {
>             int value = getReadPosition();
> 
>             try {
>                 //We only append data to fileChannel or mappedByteBuffer, never both.
>                 if (writeBuffer != null || this.fileChannel.position() != 0) {
>                     this.fileChannel.force(false);
>                 } else {
>                     this.mappedByteBuffer.force();
>                 }
>             } catch (Throwable e) {
>                 log.error("Error occurred when force data to disk.", e);
>             }
> 
>             this.flushedPosition.set(value);
>             this.release();
>         } else {
>             log.warn("in flush, hold failed, flush offset = " + this.flushedPosition.get());
>             this.flushedPosition.set(getReadPosition());
>         }
>     }
>     return this.getFlushedPosition();
> }
> ```

Can u details the situation, such as rmq version, and replicas setting?

**Comment by iamqq23ue** [comment]
> > when the flush is abnormal ，SEND_OK will still be returned 。It will cause possible message loss .
> > I will submit a PR to fix it
> > code show as below ：
> > ```java
> > public int flush(final int flushLeastPages) {
> >     if (this.isAbleToFlush(flushLeastPages)) {
> >         if (this.hold()) {
> >             int value = getReadPosition();
> > 
> >             try {
> >                 //We only append data to fileChannel or mappedByteBuffer, never both.
> >                 if (writeBuffer != null || this.fileChannel.position() != 0) {
> >                     this.fileChannel.force(false);
> >                 } else {
> >                     this.mappedByteBuffer.force();
> >                 }
> >             } catch (Throwable e) {
> >                 log.error("Error occurred when force data to disk.", e);
> >             }
> > 
> >             this.flushedPosition.set(value);
> >             this.release();
> >         } else {
> >             log.warn("in flush, hold failed, flush offset = " + this.flushedPosition.get());
> >             this.flushedPosition.set(getReadPosition());
> >         }
> >     }
> >     return this.getFlushedPosition();
> > }
> > ```
> 
> Can u details the situation, such as rmq version, and replicas setting?

RocketMQ version 4.8.0 ,SYCH_FLUSH.I have added a description of the code error.

**Comment by iamqq23ue** [comment]
> > when the flush is abnormal ，SEND_OK will still be returned 。It will cause possible message loss .
> > I will submit a PR to fix it
> > code show as below ：
> > ```java
> > public int flush(final int flushLeastPages) {
> >     if (this.isAbleToFlush(flushLeastPages)) {
> >         if (this.hold()) {
> >             int value = getReadPosition();
> > 
> >             try {
> >                 //We only append data to fileChannel or mappedByteBuffer, never both.
> >                 if (writeBuffer != null || this.fileChannel.position() != 0) {
> >                     this.fileChannel.force(false);
> >                 } else {
> >                     this.mappedByteBuffer.force();
> >                 }
> >             } catch (Throwable e) {
> >                 log.error("Error occurred when force data to disk.", e);
> >             }
> > 
> >             this.flushedPosition.set(value);
> >             this.release();
> >         } else {
> >             log.warn("in flush, hold failed, flush offset = " + this.flushedPosition.get());
> >             this.flushedPosition.set(getReadPosition());
> >         }
> >     }
> >     return this.getFlushedPosition();
> > }
> > ```
> 
> Can u details the situation, such as rmq version, and replicas setting?

You can see that if there is an error, a try catch will be performed .Then log.error("Error occurred when force data to disk.", e);
But there is no error code returned to the client, and the client still thinks that the send is successful.

**Comment by panzhi33** [comment]
> > > when the flush is abnormal ，SEND_OK will still be returned 。It will cause possible message loss .
> > > I will submit a PR to fix it
> > > code show as below ：
> > > ```java
> > > public int flush(final int flushLeastPages) {
> > >     if (this.isAbleToFlush(flushLeastPages)) {
> > >         if (this.hold()) {
> > >             int value = getReadPosition();
> > > 
> > >             try {
> > >                 //We only append data to fileChannel or mappedByteBuffer, never both.
> > >                 if (writeBuffer != null || this.fileChannel.position() != 0) {
> > >                     this.fileChannel.force(false);
> > >                 } else {
> > >                     this.mappedByteBuffer.force();
> > >                 }
> > >             } catch (Throwable e) {
> > >                 log.error("Error occurred when force data to disk.", e);
> > >             }
> > > 
> > >             this.flushedPosition.set(value);
> > >             this.release();
> > >         } else {
> > >             log.warn("in flush, hold failed, flush offset = " + this.flushedPosition.get());
> > >             this.flushedPosition.set(getReadPosition());
> > >         }
> > >     }
> > >     return this.getFlushedPosition();
> > > }
> > > ```
> > 
> > 
> > Can u details the situation, such as rmq version, and replicas setting?
> 
> You can see that if there is an error, a try catch will be performed .Then log.error("Error occurred when force data to disk.", e);
> But there is no error code returned to the client, and the client still thinks that the send is successful.

org.apache.rocketmq.store.CommitLog.GroupCommitService#doCommit
You can see this method，if flush failed，the flushedWhere offset will not change。Then the value of PutMessageStatus will be FLUSH_DISK_TIMEOUT

**Comment by iamqq23ue** [comment]
> > > > when the flush is abnormal ，SEND_OK will still be returned 。It will cause possible message loss .
> > > > I will submit a PR to fix it
> > > > code show as below ：
> > > > ```java
> > > > public int flush(final int flushLeastPages) {
> > > >     if (this.isAbleToFlush(flushLeastPages)) {
> > > >         if (this.hold()) {
> > > >             int value = getReadPosition();
> > > > 
> > > >             try {
> > > >                 //We only append data to fileChannel or mappedByteBuffer, never both.
> > > >                 if (writeBuffer != null || this.fileChannel.position() != 0) {
> > > >                     this.fileChannel.force(false);
> > > >                 } else {
> > > >                     this.mappedByteBuffer.force();
> > > >                 }
> > > >             } catch (Throwable e) {
> > > >                 log.error("Error occurred when force data to disk.", e);
> > > >             }
> > > > 
> > > >             this.flushedPosition.set(value);
> > > >             this.release();
> > > >         } else {
> > > >             log.warn("in flush, hold failed, flush offset = " + this.flushedPosition.get());
> > > >             this.flushedPosition.set(getReadPosition());
> > > >         }
> > > >     }
> > > >     return this.getFlushedPosition();
> > > > }
> > > > ```
> > > 
> > > 
> > > Can u details the situation, such as rmq version, and replicas setting?
> > 
> > 
> > You can see that if there is an error, a try catch will be performed .Then log.error("Error occurred when force data to disk.", e);
> > But there is no error code returned to the client, and the client still thinks that the send is successful.
> 
> org.apache.rocketmq.store.CommitLog.GroupCommitService#doCommit
> You can see this method，if flush failed，the flushedWhere offset will not change。Then the value of PutMessageStatus will be FLUSH_DISK_TIMEOUT

I do not think so.
First of all, I can reproduce the problem. If the flush fails, it will still return SEND_OK. And after modifying the code, the problem is solved.So there must be a problem

From the code analysis, even if the flush fails, docommit does not know. this.flushedPosition.set(value) will be executed no matter what。

**Comment by panzhi33** [comment]
> > > > > when the flush is abnormal ，SEND_OK will still be returned 。It will cause possible message loss .
> > > > > I will submit a PR to fix it
> > > > > code show as below ：
> > > > > ```java
> > > > > public int flush(final int flushLeastPages) {
> > > > >     if (this.isAbleToFlush(flushLeastPages)) {
> > > > >         if (this.hold()) {
> > > > >             int value = getReadPosition();
> > > > > 
> > > > >             try {
> > > > >                 //We only append data to fileChannel or mappedByteBuffer, never both.
> > > > >                 if (writeBuffer != null || this.fileChannel.position() != 0) {
> > > > >                     this.fileChannel.force(false);
> > > > >                 } else {
> > > > >                     this.mappedByteBuffer.force();
> > > > >                 }
> > > > >             } catch (Throwable e) {
> > > > >                 log.error("Error occurred when force data to disk.", e);
> > > > >             }
> > > > > 
> > > > >             this.flushedPosition.set(value);
> > > > >             this.release();
> > > > >         } else {
> > > > >             log.warn("in flush, hold failed, flush offset = " + this.flushedPosition.get());
> > > > >             this.flushedPosition.set(getReadPosition());
> > > > >         }
> > > > >     }
> > > > >     return this.getFlushedPosition();
> > > > > }
> > > > > ```
> > > > 
> > > > 
> > > > Can u details the situation, such as rmq version, and replicas setting?
> > > 
> > > 
> > > You can see that if there is an error, a try catch will be performed .Then log.error("Error occurred when force data to disk.", e);
> > > But there is no error code returned to the client, and the client still thinks that the send is successful.
> > 
> > 
> > org.apache.rocketmq.store.CommitLog.GroupCommitService#doCommit
> > You can see this method，if flush failed，the flushedWhere offset will not change。Then the value of PutMessageStatus will be FLUSH_DISK_TIMEOUT
> 
> I do not think so.
> First of all, I can reproduce the problem. If the flush fails, it will still return SEND_OK. And after modifying the code, the problem is solved.So there must be a problem
> 
> From the code analysis, even if the flush fails, docommit does not know. this.flushedPosition.set(value) will be executed no matter what。
> 
> You can try to make the file system read-only, and then you can reproduce the problem

测试过，如果在运行过程中，将文件改为只读，是可以强刷的。启动前改为只读，会报异常。您是怎么测试的呀

**Comment by iamqq23ue** [comment]
Start RocketMQ first, then set the file system to read only。file system！Not&nbsp; file。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] SEND_OK will still be returned when the storage is abnormal  ，which may cause message loss (#2706)





      
when the flush is abnormal ，SEND_OK will still be returned 。It will cause possible message loss .
 I will submit a PR to fix it
 code show as below ：
 public int flush(final int flushLeastPages) {     if (this.isAbleToFlush(flushLeastPages)) {         if (this.hold()) {             int value = getReadPosition();             try {                 //We only append data to fileChannel or mappedByteBuffer, never both.                 if (writeBuffer != null || this.fileChannel.position() != 0) {                     this.fileChannel.force(false);                 } else {                     this.mappedByteBuffer.force();                 }             } catch (Throwable e) {                 log.error("Error occurred when force data to disk.", e);             }             this.flushedPosition.set(value);             this.release();         } else {             log.warn("in flush, hold failed, flush offset = " + this.flushedPosition.get());             this.flushedPosition.set(getReadPosition());         }     }     return this.getFlushedPosition(); }
  
Can u details the situation, such as rmq version, and replicas setting?
  
You can see that if there is an error, a try catch will be performed .Then log.error("Error occurred when force data to disk.", e);
 But there is no error code returned to the client, and the client still thinks that the send is successful.
  
org.apache.rocketmq.store.CommitLog.GroupCommitService#doCommit
 You can see this method，if flush failed，the flushedWhere offset will not change。Then the value of PutMessageStatus will be FLUSH_DISK_TIMEOUT
  
I do not think so.
 First of all, I can reproduce the problem. If the flush fails, it will still return SEND_OK. And after modifying the code, the problem is solved.So there must be a problem
 
From the code analysis, even if the flush fails, docommit does not know. this.flushedPosition.set(value) will be executed no matter what。
 
You can try to make the file system read-only, and then you can reproduce the problem
  
测试过，如果在运行过程中，将文件改为只读，是可以强刷的。启动前改为只读，会报异常。您是怎么测试的呀

**Comment by iamqq23ue** [comment]
> 测试过，如果在运行过程中，将文件改为只读，是可以强刷的。启动前改为只读，会报异常。您是怎么测试的呀

如果改文件权限的方式，确实可以写入。我估计是程序已经打开了文件，再改权限没用了。我模拟的是文件系统read only，一般是存储故障造成的。其实代码能看出来，try catch以后没处理，自然传给其他方法的结果还是成功的。
