### ISSUE TITLE
How to fix [PCBUSY_CLEAN_QUEUE]broker busy

### ISSUE THREAD

**Issue by wz2cool** [apache/rocketmq#2709]
**BUG REPORT**

1. Please describe the issue you observed:
We mee the problem ' [PCBUSY_CLEAN_QUEUE]broker busy' , but we have no idea to fix it. We have tried lots of 
eg:
-  open  transientStorePoolEnable == true
- increate timeout 

currently, we use Rocketmq 4.8.0, could someone help us and give us some advice.

![image](https://user-images.githubusercontent.com/11556152/109904311-ff6bcd80-7cd7-11eb-8157-0324319abfe7.png)

**Comment by maixiaohai** [comment]
config sendThreadPoolQueueCapacity, the default value is 10000
the message show your config is 4 
```
rt.returnResponse(RemotingSysResponseCode.SYSTEM_BUSY, String.format("[PCBUSY_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: %sms, size of queue: %d", System.currentTimeMillis() - rt.getCreateTimestamp(), this.brokerController.getSendThreadPoolQueue().size()));

```

**Comment by duhenglucky** [comment]
@wz2cool FYI： https://blog.csdn.net/prestigeding/article/details/92800672

**Comment by wz2cool** [comment]
> config sendThreadPoolQueueCapacity, the default value is 10000
> the message show your config is 4
> 
> ```
> rt.returnResponse(RemotingSysResponseCode.SYSTEM_BUSY, String.format("[PCBUSY_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: %sms, size of queue: %d", System.currentTimeMillis() - rt.getCreateTimestamp(), this.brokerController.getSendThreadPoolQueue().size()));
> ```

thank you for your quick response. Actually, we don't change this property in config and it show 4 queues not queue capacity. Will try to set useReentrantLockWhenPutMessage to true to avoid this issue.

**Comment by liuxuzxx** [comment]
> config sendThreadPoolQueueCapacity, the default value is 10000 the message show your config is 4
> 
> ```
> rt.returnResponse(RemotingSysResponseCode.SYSTEM_BUSY, String.format("[PCBUSY_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: %sms, size of queue: %d", System.currentTimeMillis() - rt.getCreateTimestamp(), this.brokerController.getSendThreadPoolQueue().size()));
> ```

No ,the  this.brokerController.getSendThreadPoolQueue().size() return the sendThreadPoolQueue actually size ,not the config length!

this.brokerController.getSendThreadPoolQueue().size()的大小是sendThreadPoolQueue队列元素的个数，不是他的size不是capacity！ 所以这个4只是说当前这个sendThreadPoolQueue队列当中含有4个元素，并不是说他的capacity(容量)是4
