### ISSUE TITLE
Delete unused parameters

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq#2710]
The buildSubscriptionData function in FilterAPI. java is used to build the SubscriptionData object, and the parameter of this function contains the ConsumerGroup, Topic and Substring. But the SubscriptionData does not have the ConsumerGroup property, and this parameter is not used in this function, so I deleted this parameter and changed the place where the buildSubscriptionData function is called

**Comment by RongtongJin** [comment]
Merged
