### ISSUE TITLE
master write-only and slave read-only

### ISSUE THREAD

**Issue by wz2cool** [apache/rocketmq#2711]
We meet system busy & broker busy  recent days. Rocketmq won't retry if system busy & broker busy #1196 
After reading some articles, I know the main issue is page cache busy. 
We don't want to use transientstorepoolenable because it isn't reliable.
So, can rocketmq support master  write-only and slave read-only?
I think it's good for master to reduce pressure  (put / pull)  because master only put message.

**Comment by RongtongJin** [comment]
If master write-only and slave read-only will have problems that do not conform to the semantics of read-your-writes and monotonic reads. For now, when the broker config slaveReadEnable is true, and when the consumer reads cold data, consumer will read from the slave.

**Comment by RongtongJin** [comment]
IMO, this is a very good discussion. We could discuss it on the mailing list. I will close this issue first.
