### ISSUE TITLE
save sending messages in client side

### ISSUE THREAD

**Issue by wz2cool** [apache/rocketmq#2714]
i know this idea is a lot crazy. but it may useful.
let me describe the detail.
1. save messages to tiny local mq and get position instead of sending messages to server directly.
2. after that, read messages from tiny local mq by position and send messages to rocketmq (server side).
3. position will not change if meet any exception (eg: network error/broker busy/system busy)
4. The tiny local mq should be implemented by mmap and restore messages if client restart.

I don't know whether this idea can be implemented in DefaultMQProducerImpl.

**Comment by lizhimins** [comment]
Allowing caching on the client side means allowing data loss and unreliability, which may be very useful in some special network scenarios, or to send OneWay messages while collecting logs, without server confirmation.

**Comment by wz2cool** [comment]
> Allowing caching on the client side means allowing data loss and unreliability, which may be very useful in some special network scenarios, or to send OneWay messages while collecting logs, without server confirmation.

so, the tiny local mq should be implemented by mmap (like rocketmq) and restore messages if client restart. 
data will not loss since data can be save in file (mmap)

**Comment by lizhimins** [comment]
It will greatly increase the complexity of the client, and most business systems hope to use a lightweight SDK in the production environment. Client may runs in non-persistent container

**Comment by wz2cool** [comment]
it can be a optional config in client side. I think many people will like this function beacuse it's a way to help them to solve exception.

We can mount a phyical disk for non-persistent container (eg: docker) to save data. 

It will greatly increase the complexity of the client, but it's useful.

**Comment by lizhiboo** [comment]
This function exists in metaq, it's indeed useful in some cases, such as log report and some data insensitive cases.

**Comment by felayman** [comment]
In the production environment，some cases are that first expand then shrink, the client consumer will be replaced, Is this meant to be loss more msgs？
