### ISSUE TITLE
NettyClientConfig clientCloseSocketIfTimeout can not be configured from outside

### ISSUE THREAD

**Issue by EZLippi** [apache/rocketmq#2715]
NettyClientConfig has a property `clientCloseSocketIfTimeout ` to set whether to close socket if invoke timeout, but no where to use and can not be configured from Producer or Consumer api.
![image](https://user-images.githubusercontent.com/5326814/110268727-29393300-7ffd-11eb-9b4b-e80dee6978a9.png)

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

clientCloseSocketIfTimeout property can be set from ClientConfig

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

**Comment by RongtongJin** [comment]
This is a good issue on how to expose netty parameters. In addition, I think clientCloseSocketIfTimeout should be true by default. Could you submit a PR to modify it？

**Comment by EZLippi** [comment]
> This is a good issue on how to expose netty parameters. In addition, I think clientCloseSocketIfTimeout should be true by default. Could you submit a PR to modify it？

ok, i will sumbit a PR to modify it, some properties in NettyClientConfig are exposed by System Property, i will change other properties the same

**Comment by felayman** [comment]
The config class(NettyClientConfig) has more  properties are not exposed

**Comment by maixiaohai** [comment]
+1
