### ISSUE TITLE
need a boolean method to know if system busy

### ISSUE THREAD

**Issue by wz2cool** [apache/rocketmq#2718]
Rocketmq won't retry if system busy according to PR #1196
We also want to know what we can do if meet system busy. #2713  the answer tell us that retrying may aggravate this situation, but it's impossible for us to do nothing or throw message.

Could rocketmq provide a boolean method to indicate whether system busy in server side. 
We need to know when we can send messages and it's ok for us to wait until server is available

**Comment by lizhiboo** [comment]
> Rocketmq won't retry if system busy according to PR #1196
> We also want to know what we can do if meet system busy. #2713 the answer tell us that retrying may aggravate this situation, but it's impossible for us to do nothing or throw message.
> 
> Could rocketmq provide a boolean method to indicate whether system busy in server side.
> We need to know when we can send messages and it's ok for us to wait until server is available

It's difficult to judge system is really busy, sometime momentary pressure can cause busy, then decline quickly.
