### ISSUE TITLE
benchmark consumer tools can not read accumulated msg when producer stop sending msg

### ISSUE THREAD

**Issue by jeffchanjunwei** [apache/rocketmq#2725]
When I use the benchmark tool to test the performence of dledger cluster v4.8.0, I find that the consumer can not read accumulated msg when producer doesn't send msg. But if producer and consumer work at the same time, consumer can read msg.

here is my step:
1. ./benchmark/Producer.sh -n xxxxx     
2. ./shutdown.sh producer                   //accumulate some msg
3. ./benchmark/Consumer.sh -n xxxx     //can not read msg
Current Time: 1615453556761 TPS: 0 FAIL: 0 AVG(B2C) RT(ms):     NaN AVG(S2C) RT(ms):     NaN MAX(B2C) RT(ms): 0 MAX(S2C) RT(ms): 0
Current Time: 1615453566761 TPS: 0 FAIL: 0 AVG(B2C) RT(ms):     NaN AVG(S2C) RT(ms):     NaN MAX(B2C) RT(ms): 0 MAX(S2C) RT(ms): 0
Current Time: 1615453576760 TPS: 0 FAIL: 0 AVG(B2C) RT(ms):     NaN AVG(S2C) RT(ms):     NaN MAX(B2C) RT(ms): 0 MAX(S2C) RT(ms): 0

But if I run the producer and consumer at the sametime, consumer can read msg. I alse find some log in mq server as follow:

```
2021-03-11 17:43:12 ERROR NettyServerNIOSelector_3_2 - RemotingCommand [code=24, language=JAVA, version=373, opaque=13351, flag(B)=1, remark=the consumer's group info not exist
See http://rocketmq.apache.org/docs/faq/ for further details., extFields=null, serializeTypeCurrentRPC=JSON]
2021-03-11 17:43:12 ERROR NettyServerNIOSelector_3_2 - processRequestWrapper response to /172.21.69.138:21304 failed
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]

```

**Comment by maixiaohai** [comment]
@jeffchanjunwei 你消费的应该是最新的消息，可以通过控制台确认一下

**Comment by jeffchanjunwei** [comment]
> @jeffchanjunwei 你消费的应该是最新的消息，可以通过控制台确认一下

benchmark工具中consumer对累积的消息是消费不了的么？

**Comment by maixiaohai** [comment]
> > @jeffchanjunwei 你消费的应该是最新的消息，可以通过控制台确认一下
> 
> benchmark工具中consumer对累积的消息是消费不了的么？主要我再另一个集群里consumer好像是可以消费到累积消息的，这个集群有问题，目前找不到问题在哪

和你的消费组有关，如果启动的时候使用了一个已经存在的消费组会从存的位点（旧位点）开始消费，即消费了堆积消息

**Comment by jeffchanjunwei** [comment]
> > > @jeffchanjunwei 你消费的应该是最新的消息，可以通过控制台确认一下
> > 
> > 
> > benchmark工具中consumer对累积的消息是消费不了的么？主要我再另一个集群里consumer好像是可以消费到累积消息的，这个集群有问题，目前找不到问题在哪
> 
> 和你的消费组有关，如果启动的时候使用了一个已经存在的消费组会从存的位点（旧位点）开始消费，即消费了堆积消息

好的，感谢。
