### ISSUE TITLE
最新的rocketmq4.2版本现在有没有支持事物消息？

### ISSUE THREAD

**Issue by ylh23y** [apache/rocketmq#273]
最新的rocketmq4.2版本现在有没有支持事物消息？

**Comment by lizhanhui** [comment]
Will support in the future release soon.

**Comment by ylh23y** [comment]
这个有没有支持事物消息确认的时间点？

**Comment by xingfudeshi** [comment]
@lizhanhui hey,guy,i gotta tell you that  the transactional message feature has already merged to the develop branch.i guess you can use it in next release version 4.3.pls refer this [https://github.com/apache/rocketmq/pull/358](url).we should should thank those who contributed.

**Comment by xingfudeshi** [comment]
by the way,if you wanna try the new feature out,pls clone the code from the develop branch.and refer the doc to get start.enjoy it! [https://rocketmq.apache.org/docs/transaction-example/](url)
