### ISSUE TITLE
Multiple instances in the same application share MQClientInstance

### ISSUE THREAD

**Issue by panzhi33** [apache/rocketmq#2730]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by duhenglucky** [comment]
merged[https://github.com/apache/rocketmq/pull/2731](url)

**Comment by zcsh0721** [comment]
@duhenglucky 我有个疑问, 多个应用共享一个 MQClientInstance 所带来的的影响是什么? 如果有影响的话, 用这个解决方法是否也带来了另一个问题? 例如: 在一个应用里面创建 DefaultMQProducer 和 DefaultMQPushConsumer (毕竟 producer 通常也是 consumer) , 会创建两个 MQClientInstance , 那么所创建的线程也是两份了吧? 资源不是重复利用了吗;
![image](https://user-images.githubusercontent.com/43027219/112101187-36e7de80-8be1-11eb-9678-5e32b3fe986f.png)

**Comment by ifplusor** [comment]
@zcsh0721 Producer 和 Consumer 共享 MQClientInstance 会有，如果 Producer 先刷新了一个 topic 的 TopicRouteData，则 Consumer 启动的时候再刷新该 topic 的 TopicRouteData，因为 TopicRouteData 与本地缓存一致，不会触发 Consumer 的 rebalance 过程，导致 Consumer 无法消费。

**Comment by ifplusor** [comment]
多个 DefaultMQPushConsumer 共享 MQClientInstance，并订阅相同 topic 也有同样的问题。这里应该优化代码逻辑。

**Comment by zcsh0721** [comment]
@ifplusor  有两个问题
1. 我刚刚试了一下, `instanceName=UtilAll.getPid()` 版本的代码, 手动刷新了 Producer 的 TopicRouteData , 然后在启动 consumer , 并没有发现无法消费的问题,,可以提示我一下,影响无法消费的代码在哪里吗, 谢谢~
2. 如果有你说的问题, 那么用随机 instanceName 的方式解决, 所带来的线程几乎翻倍的问题, 怎么处理? 这种处理方式会不会太粗暴了一点...

**Comment by ifplusor** [comment]
@zcsh0721 你是怎么手动刷的，调用的fetchPublishMessageQueues吗？这各方式不行，要用send发消息。

**Comment by ifplusor** [comment]
对这个问题，可以优化consumer启动时更新TopicRouteData的逻辑，优先从本地缓存里获取。比如这样：https://github.com/apache/rocketmq-client-cpp/commit/f3a9097f612acf6db90c6f62e1a2fe87277e5e81

**Comment by zcsh0721** [comment]
@if
 `ConcurrentMap<String, TopicRouteData> table = producer.getDefaultMQProducerImpl().getmQClientFactory().getTopicRouteTable();` 
这样可以吧 , 而且 我也发送消息了
完整测试代码 
```
    public static void main(String[] args) throws InterruptedException, MQClientException {


        DefaultMQProducer producer = new DefaultMQProducer("please_rename_unique_group_name");
        producer.setNamesrvAddr("127.0.0.1:9876");

        for (int i = 0; i < 1000; i++) {
            try {
                Message msg = new Message("TopicTest" /* Topic */,
                    "TagA" /* Tag */,
                    ("Hello RocketMQ " + i).getBytes(RemotingHelper.DEFAULT_CHARSET) /* Message body */
                );
                SendResult sendResult = producer.send(msg);
            } catch (Exception e) {
                e.printStackTrace();
                Thread.sleep(1000);
            }
        }

//        producer.shutdown();

        ConcurrentMap<String, TopicRouteData> table = producer.getDefaultMQProducerImpl().getmQClientFactory().getTopicRouteTable();
        System.out.println(table);
        Thread.sleep(10000L);
        System.out.println("*************************************************************");
        
        DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("please_rename_unique_group_name_4");
        consumer.setNamesrvAddr("127.0.0.1:9876");
        consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_FIRST_OFFSET);
        consumer.subscribe("TopicTest", "*");
        consumer.registerMessageListener(new MessageListenerConcurrently() {

            @Override
            public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                ConsumeConcurrentlyContext context) {
                System.out.printf("%s Receive New Messages: %s %n", Thread.currentThread().getName(), msgs);
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            }
        });
        consumer.start();

        System.out.printf("Consumer Started.%n");
    }
```
 
 我把 `ClientConfig.changeInstanceNameToPID()`改为如下
```
    public void changeInstanceNameToPID() {
        if (this.instanceName.equals("DEFAULT")) {
            this.instanceName = UtilAll.getPid() +"";
            System.out.println("instanceName=" + instanceName);
        }
    }
```

**Comment by ifplusor** [comment]
@zcsh0721 producer 没有 start

**Comment by zcsh0721** [comment]
@ifplusor  呃呃 是我贴代码的时候, 删注释的时候删掉了,,; 我测试的时候 producer 在 for循环前 start 了

**Comment by zcsh0721** [comment]
```
    public static void main(String[] args) throws InterruptedException, MQClientException {


        DefaultMQProducer producer = new DefaultMQProducer("please_rename_unique_group_name");

        producer.setNamesrvAddr("127.0.0.1:9876");
        producer.start();

        for (int i = 0; i < 5; i++) {
            try {
                Message msg = new Message("TopicTest" /* Topic */,
                    "TagA" /* Tag */,
                    ("Hello RocketMQ " + i).getBytes(RemotingHelper.DEFAULT_CHARSET) /* Message body */
                );

                SendResult sendResult = producer.send(msg);
                System.out.printf("%s%n", sendResult);
            } catch (Exception e) {
                e.printStackTrace();
                Thread.sleep(1000);
            }
        }

//        producer.shutdown();

        ConcurrentMap<String, TopicRouteData> table = producer.getDefaultMQProducerImpl().getmQClientFactory().getTopicRouteTable();
        Thread.sleep(10000L);

        System.out.println("*************************************************************");

        DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("please_rename_unique_group_name_4");
        consumer.setNamesrvAddr("127.0.0.1:9876");
        consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_FIRST_OFFSET);
        consumer.subscribe("TopicTest", "*");
        consumer.registerMessageListener(new MessageListenerConcurrently() {

            @Override
            public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                ConsumeConcurrentlyContext context) {
                System.out.printf("%s Receive New Messages: %s %n", Thread.currentThread().getName(), msgs);
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            }
        });

        consumer.start();

        System.out.printf("Consumer Started.%n");
    }
```
![image](https://user-images.githubusercontent.com/43027219/112806807-c857c480-90a9-11eb-9538-778a044f09f5.png)

**Comment by ifplusor** [comment]
@zcsh0721 我又跟了一下代码，MQClientInstance::updateTopicRouteInfoFromNameServer里在changed为false时还有一个isNeedUpdateTopicRouteInfo的逻辑，是我看漏了。

还有个问题是 rpc 超时会断开连接，共享 MQClientInstance 会产生全局影响。这是个权衡问题。

**Comment by zcsh0721** [comment]
@ifplusor  还有别的原因吗,这个原因感觉不是很有说服. 毕竟这个改变对客户端来说变化还挺大的.  但是想不清楚,因为什么而做的这种改变;

**Comment by ifplusor** [comment]
@zcsh0721 我和其他同学交流了一下，这个变更的目的是应对容器化部署环境下pid冲突的情况。想复用MQClientInstance可以手动设置instanceName。

**Comment by zcsh0721** [comment]
@ifplusor  ok,  这就很合理了; 我刚刚也看到了可以手动设置 instanceName 的方法; 
谢谢细心解答~

**Comment by Aaron-TangCode** [comment]
> @zcsh0721 我和其他同学交流了一下，这个变更的目的是应对容器化部署环境下pid冲突的情况。想复用MQClientInstance可以手动设置instanceName。

糟糕，我没看懂：“这个变更的目的是应对容器化部署环境下pid冲突的情况”。
我目前知道的点是：同一个JVM下的生产者和消费者是同一个进程id。但不清楚为什么这么设计？
clientid 由 ip 和 进程Id组成。如果在容器化部署的环境下，IP应该也是不同的吧。应该没错吧。
所以“这个变更的目的是应对容器化部署环境下pid冲突的情况”，这个句话，我没看懂，望解答。

**Comment by zcsh0721** [comment]
@Aaron-TangCode 容器化部署是可能存在 ip 相同的情况的,, 如果多个人在本地使用 docker 来启动客户端服务 并连接同一个 rocketmq , 那么多个人本地启动 docker 的 ip 相互之间是有可能重复的.

**Comment by caimofei** [comment]
> @zcsh0721 我和其他同学交流了一下，这个变更的目的是应对容器化部署环境下pid冲突的情况。想复用MQClientInstance可以手动设置instanceName。

有点疑问
1. 您描述这个问题就是造成MQClientInstance对象 clientId重复.并且是在不同的JVM进程中。不同JVM进程中有相同的clientId的MQClientInstance对象有什么问题？还是说在服务端需要要求这个clientId不重复？
2. 如果说服务端需要要求clinetId不重复。那么如果想复用MQClientInstance对象，手动设置instanceName的情况下，不是同样造成clientId的重复吗？好像又回到了问题的源头
