### ISSUE TITLE
Questions about warmmappedfile

### ISSUE THREAD

**Issue by renxinlin** [apache/rocketmq#2734]
AllocateMappedFileService.mmapOperation  在创建映射文件进行内存预热的时候
byteBuffer.put(i, (byte) 0);
为什么put的值是0，可不可以是1，或者其他值;
一直不太理解，求赐教

**Comment by RongtongJin** [comment]
我觉得可以，把内存占住就可以了

**Comment by renxinlin** [comment]
> 我觉得可以，把内存占住就可以了

我个人的理解是不管0还是1或者其他值都会完成物理内存页的分配，只是0并没有改变原先bytebuffer的内容，同时达到分配物理内存的效果;希望有人帮助解惑
