### ISSUE TITLE
Graceful shutdown for consumers

### ISSUE THREAD

**Issue by xiangyang-gao** [apache/rocketmq#2737]
如题：
1.defaultMQPushConsumer.start();
2.defaultMQPushConsumer.shutdown();
3.defaultMQPushConsumer.start();
如果我将1，2，3连续执行。
1 成功，2成功  3失败了

请问下这个3 我这里需要执行成功，有什么办法吗？

如果我做优雅上下线，会有些问题。
使用场景类似dubbo的 qos on/off。

**Comment by xiangyang-gao** [comment]
失败日志如下：The PushConsumer service state not OK, maybe started once, SHUTDOWN_ALREADY
See http://rocketmq.apache.org/docs/faq/ for further details.

**Comment by xiangyang-gao** [comment]
是否可以再提供一个停止消费方法
defaultMQPushConsumer.stop()

**Comment by crazy-pizza** [comment]
> 是否可以再提供一个停止消费方法
> defaultMQPushConsumer.stop()

看一下这个两个函数 defaultMQPushConsumer.suspend. defaultMQPushConsumer.resume

**Comment by xiangyang-gao** [comment]
> > 是否可以再提供一个停止消费方法
> > defaultMQPushConsumer.stop()
> 
> 看一下这个两个函数 defaultMQPushConsumer.suspend. defaultMQPushConsumer.resume

这个是悬挂思路，链接还在。。。

**Comment by maixiaohai** [comment]
@xiangyang-gao try **unsubscribe()** method

**Comment by zcsh0721** [comment]
@maixiaohai 在 consume 是集群模式下, 执行 `unsubscribe()`,  会导致本来由该 consume 消费的队列,不消费了,且其他同 consumeGroup 下的 consume 也不会消费这个队列; 例如:
 topic 有 4 个队列; 一个 consumeGroup  ,两个消费者 consumeA  consumeB;
consumeA 消费队列 0,1;
consumeB 消费队列 2,3;
当 consumeA 执行 `unsubscribe()`时, 虽然 consumeA 不消费了,但是 consumeB 也消费不了 2,3;  因为集群模式下,消费者的消费队列策略是根据 topic 和 consumeGroup 来分配的,  不论你有没有订阅相同主题,都会占着相同的位置;

所以 `unsubscribe()` 可以解决客户端压力过大,停止消费, 但是会带来相应队列没有其他 consume 处理的问题;

**Comment by zcsh0721** [comment]
@xiangyang-gao 如果链接都不想要了,那么 rocketmq 的 client 也相当于停止了,  为什么不重新 `new DefaultMQPushConsumer()` 呢? 线程不存在了, 任务其实已经算停止了吧;

**Comment by xiangyang-gao** [comment]
> 吧
我上个悬挂的思路表达有误。链接在没关系

悬挂拉取消息的请求,去延时去拉取

> @xiangyang-gao 如果链接都不想要了,那么 rocketmq 的 client 也相当于停止了, 为什么不重新 `new DefaultMQPushConsumer()` 呢? 线程不存在了, 任务其实已经算停止了吧;

你说的思路是没问题的。
我这里场景有停服/不停服，进行上线，下线。
比如我在容器里实例化好的对象new DefaultMQPushConsumer()，如果有可能采用stop。
从api角度上来讲 更简单些，更实用。

**Comment by xiangyang-gao** [comment]
> 那么

**Comment by xiangyang-gao** [comment]
> > 吧
> > 我上个悬挂的思路表达有误。链接在没关系
> 
> 悬挂拉取消息的请求,去延时去拉取
> 
> > @xiangyang-gao 如果链接都不想要了,那么 rocketmq 的 client 也相当于停止了, 为什么不重新 `new DefaultMQPushConsumer()` 呢? 线程不存在了, 任务其实已经算停止了吧;
> 
> 你说的思路是没问题的。
> 我这里场景有停服/不停服，进行上线，下线。
> 比如我在容器里实例化好的对象new DefaultMQPushConsumer()，如果有可能采用stop。
> 从api角度上来讲 更简单些，更实用。
