### ISSUE TITLE
mqadmin consumerProgress consumerOffset is  bigger than brokerOffset and diffTotal is negative

### ISSUE THREAD

**Issue by falcondance** [apache/rocketmq#2743]
RocketMQ version: 4.8.0

Cluster
3 NameServer
1 Dleager（3 Broker）

We use canal for sending mysql binlog message to rocketmq，have a consumer consume message from broker .

We use command to monitor consume diff command:./mqadmin consumerProgress -n XXX:XX -g xxx The diff is negative (eg: -647260483) .

![image](https://user-images.githubusercontent.com/20810423/111968129-cdf65d00-8b33-11eb-95bb-f6ea23ac609a.png)

**Comment by panzhi33** [comment]
maybe your consumerId was delete and rebuild

**Comment by falcondance** [comment]
how can i reset value?

**Comment by panzhi33** [comment]
This does not affect the use of，you can use this command resetOffsetByTime
