### ISSUE TITLE
Request-Reply docs

### ISSUE THREAD

**Issue by lionhuo** [apache/rocketmq#2745]
Request-Reply模式从4.6.0版本开始支持，文档里是4.7.0，可能会对有版本要求的同学造成困惑，请修改，谢谢！

![image](https://user-images.githubusercontent.com/3981349/112018928-f26d2c00-8b69-11eb-9971-f81d8918a3fe.png)

**Comment by duhenglucky** [comment]
@lionhuo 欢迎提个 PR 修改一下呀。
