### ISSUE TITLE
When I sending a message by async, sometimes throw ConcurrentModificationException

### ISSUE THREAD

**Issue by yangjie9212** [apache/rocketmq#2754]
I'm just sending a string, I don't know why this is happening。
client-version:  4.5.2
server-version: 4.5.2

hope somebody can help me !

![b99b9146dd754b6090da41ef5488231d](https://user-images.githubusercontent.com/24838422/112642058-e3de8780-8e7d-11eb-9ca8-833127923148.jpg)
![dd8f712f69b648b8b94bc3d1a13f3844](https://user-images.githubusercontent.com/24838422/112642070-e640e180-8e7d-11eb-9e7b-48a84b9f6296.jpg)

**Comment by maixiaohai** [comment]
Hi @yangjie9212, you can update to version 4.8 and have a try.

**Comment by francisoliverlee** [comment]
@yangjie9212 can you replay it by hand ?

**Comment by dujingsong** [comment]
@maixiaohai i have the same problem, can you tell me why，or  can you show me  where is the fixed code ,thanks so mush!
