### ISSUE TITLE
延时队列

### ISSUE THREAD

**Issue by RongXiong2016** [apache/rocketmq#2759]
目前项目中用的是商业版，对于 msg.setStartDeliverTime() 有些疑问
 1.官方文档显示可以支持 40 天以内的任意时间
![image](https://user-images.githubusercontent.com/18466554/112789430-a5201b80-908f-11eb-9484-d379f6d8ba77.png)

2.ons 源码注释中显示只有 7 天

![image](https://user-images.githubusercontent.com/18466554/112789498-cf71d900-908f-11eb-933c-45f0d5beee84.png)

请问该以哪个为准

**Comment by ifplusor** [comment]
阿里云商业版的问题去提工单吧，社区不支持商业产品。
