### ISSUE TITLE
Consumer get same ClientId when running in docker container

### ISSUE THREAD

**Issue by deanisty** [apache/rocketmq#2760]
Assume I have a consumer listeners subscribe to topic A and in group G1, and two broker named "broker-a" and "broker-b",  then I start consumer instance in 2 docker container separetely, after they started, they got same clientId [172.17.0.1@1], according to rebalance logic, they will only get these message queues from broker-a, message queues on "broker-b" will never be took care of,  is this normal ?

**Comment by panzhi33** [comment]
This is because the ip and process number obtained by the two containers are the same. You can set different instanceName attributes for each container.

**Comment by deanisty** [comment]
> This is because the ip and process number obtained by the two containers are the same. You can set different instanceName attributes for each container.

Got it, tks !
