### ISSUE TITLE
4.8.0-bin-release 在 win10 环境中 mqbroker.cmd 文件启动错误

### ISSUE THREAD

**Issue by MyAuntIsPost90s** [apache/rocketmq#2761]
您好，window 在使用过程中发现一个启动配置的问题，烦请处理。
rocketmq 版本：4.8.0
系统版本：win10
错误描述：在已经配置好 java 环境变量 “CLASSPATH” 后执行 mqbroker.cmd 报错如下：
![image](https://user-images.githubusercontent.com/22209885/112807405-72375100-90aa-11eb-8858-f61ec0e97b9f.png)
将 runbroker.cmd 中修改如下后，则执行成功。
![image](https://user-images.githubusercontent.com/22209885/112807520-96932d80-90aa-11eb-98a6-7e1443453690.png)
![image](https://user-images.githubusercontent.com/22209885/112807537-9bf07800-90aa-11eb-9bb6-b9c93d9911a1.png)

**Comment by wangtaicheng** [comment]
可能与
![image](https://user-images.githubusercontent.com/6257526/113231007-d6395f80-92cc-11eb-8d69-beba3c554fac.png)空格有关
