### ISSUE TITLE
After the MQ shutdown, the client crazy brush log

### ISSUE THREAD

**Issue by lveex** [apache/rocketmq#2770]
![image](https://user-images.githubusercontent.com/22068396/112970054-63bb6900-9180-11eb-9001-51ee31a243b2.png)

After the MQ shutdown, the client crazy brush log, an hour about more than 10 G

**Comment by duhenglucky** [comment]
> ![image](https://user-images.githubusercontent.com/22068396/112970054-63bb6900-9180-11eb-9001-51ee31a243b2.png)
> 
> After the MQ shutdown, the client crazy brush log, an hour about more than 10 G

这个是上报位点的日志，为避免客户端会定时向服务端定时更新位点，先看下broker 宕机后，分配给他的队列里面是否还会有宕机后的broker 的队列

**Comment by lizhimins** [comment]
Broker 关闭之后，NameServer 上的路由信息会被异步删除，这里会有一小段时间间隔，此时客户端还认为这个 Broker 在线并尝试提交位点。

**Comment by felayman** [comment]
可以调整如下两个参数：
persistConsumerOffsetInterval -> consumer定时将当前消费组的消费点上报给broker, 默认每5秒上报一次
heartbeatBrokerInterval -> consumer定期清除下线的broker, 默认30s

consumer在上报消费点的时候会在本地缓存维护的brokerAddrTable中判断上报的broker是否存在，上报的时候可能还未清除下线的broker。
