### ISSUE TITLE
能不能整合进nacos,利用nacos进行水平扩展

### ISSUE THREAD

**Issue by licheng1013** [apache/rocketmq#2778]

**Comment by francisoliverlee** [comment]
@licheng1013 do 'u have a detail solution?

**Comment by duhenglucky** [comment]
@licheng1013 现在nameserver 也是可以水平扩展的，基本上对于单个集群来说，topic 相关的路由信息不会成为瓶颈，压力一般是连接数，nameserver 的运维压力较低，且目前没有强一致性的需求
