### ISSUE TITLE
Why does BROADCASTING consumer use different MQClientInstance than CLUSTERING consumer

### ISSUE THREAD

**Issue by crazy-pizza** [apache/rocketmq#2782]
Here is the source code for MQ
```
if (this.defaultMQPushConsumer.getMessageModel() == MessageModel.CLUSTERING) {
     this.defaultMQPushConsumer.changeInstanceNameToPID();
 }
```

**Comment by panzhi33** [comment]
InstanceName is used to splice clientId，the broadcast mode does not require consumer rebalance, and there is no need to ensure that the ClientId is different.

**Comment by crazy-pizza** [comment]
> InstanceName is used to splice clientId，the broadcast mode does not require consumer rebalance, and there is no need to ensure that the ClientId is different.

我明白你的意思，你是站着集群模式消费的角度考虑的。
但是我想说的是，如果广播消费的instanceName也使用PID，就可以在一个进程内与集群消费共享网络连接。

并且由于广播消费的消费进度存储在本地，位置在: 
```
this.storePath = LOCAL_OFFSET_STORE_DIR + File.separator +
            this.mQClientFactory.getClientId() + File.separator +
            this.groupName + File.separator +
            "offsets.json";
```
如果广播消费的instanceName固定是DEFAULT的话，那么将不能在一台机器上启动两个相同组的消费组，否则Offset存储会发生冲突

**Comment by panzhi33** [comment]
重启服务的话，pid是会改变的，也就改变了消费进度的存储位置，这两个是矛盾的。
广播模式消费进度是存储再本地的，同一台机器的话，还是建议客户端修改存储位置LOCAL_OFFSET_STORE_DIR
你说的也是对的，我们可以想想其它的标识符，来解决这个问题
