### ISSUE TITLE
ServerBootstrap 中的解码器org.apache.rocketmq.remoting.netty.NettyDecoder 为什么不用共享实例？

### ISSUE THREAD

**Issue by November22** [apache/rocketmq#2786]
RocketMQ 版本：4.7.1
![image](https://user-images.githubusercontent.com/26109828/113957048-20808a80-9851-11eb-804b-3dfc01cca088.png)
org.apache.rocketmq.remoting.netty.NettyDecoder的内部属性FRAME_MAX_LENGTH 在程序启动后，是不可变的吧，这样NettyDecoder不持有任何状态。按照个人理解，这样就可以将NettyDecoder安全的用于多个Channel。

**Comment by shenshaoming** [comment]
你少看了个继承吧，NettyDecorder继承自LengthFieldBasedFrameDecoder，在LengthFieldBasedFrameDecoder里是有很多不可复用的属性的

**Comment by felayman** [comment]
> 你少看了个继承吧，NettyDecorder继承自LengthFieldBasedFrameDecoder，在LengthFieldBasedFrameDecoder里是有很多不可复用的属性的

目前看来就一个com.rocketmq.remoting.frameMaxLength是可能不复用的, 我理解NettyDecoder是可以复用于多个channel的

**Comment by duhenglucky** [comment]
@felayman FYI，https://github.com/apache/rocketmq/pull/635/files
