### ISSUE TITLE
Unable to start nameserver using 4.8.0 package

### ISSUE THREAD

**Issue by hhive** [apache/rocketmq#2787]
提示：
/app/rocketmq-all-4.8.0-bin-release/bin/runserver.sh: 70: [[: not found
Unrecognized option: -Xlog:gc*:file=/dev/shm/rmq_srv_gc_%p_%t.log:time,tags:filecount=5,filesize=30M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

将runserver.sh的70行if [[ "$JAVA_MAJOR_VERSION" -lt "9" ]]  改成 if [ "$JAVA_MAJOR_VERSION" -lt "9" ]后可以执行

Linux-Ubuntu20.04，Jdk1.8_281

**Comment by panzhi33** [comment]
[[]] is bash syntax，however, the runserver.sh script has been declared as sh
![image](https://user-images.githubusercontent.com/29321745/113999767-e8973880-988c-11eb-80fb-91a7482cae11.png)

Could you submit a PR to fix it？

**Comment by hhive** [comment]
> [[]] is bash syntax，however, the runserver.sh script has been declared as sh
> ![image](https://user-images.githubusercontent.com/29321745/113999767-e8973880-988c-11eb-80fb-91a7482cae11.png)
> 
> Could you submit a PR to fix it？

ok

**Comment by hhive** [comment]
develop分支已经改好了，if [ -z "$JAVA_MAJOR_VERSION" ] || [ "$JAVA_MAJOR_VERSION" -lt "9" ] ;

**Comment by RongtongJin** [comment]
Same as #2689
