### ISSUE TITLE
singleton RocketMQLocalTransactionListener，what can i do for two transcation

### ISSUE THREAD

**Issue by zhaoyy0513** [apache/rocketmq#2791]
My version is 4.8.0。
  I found the RocketMQTransactionConfiguration class have one function afterSingletonsInstantiated()，it make springboot can only have one RocketMQLocalTransactionListener bean。
  but if i want to have two transcation i can't do this;
rocketMQTemplate.sendMessageInTransaction() only have 3 paremeters，and **@RocketMQTransactionListener** delete **txProducerGroup** parameter 
How to find the matching transaction listener?
Please do me a favor, thank you

**Comment by RongtongJin** [comment]
Hi @zhaoyy0513，you can use extra rocketmqtemplate to send transactional messages, refer to [rocketmq-spring wiki FAQ article 11](https://github.com/apache/rocketmq-spring/wiki/FAQ).

**Comment by RongtongJin** [comment]
I will close the issue first, Plz feel free to reopen it if you have other questions.
