### ISSUE TITLE
What circumstances will messages not be consumed or delay consumed?

### ISSUE THREAD

**Issue by VAEAZE** [apache/rocketmq#2794]
I have more than five hundred topic in one cluster with six  nodes, I create the topic like this : 

> ./mqadmin updateTopic -c MyCluster -n 192.168.1.100:9876 -r 16 -w 16 -t topic1;
> ./mqadmin updateTopic -c MyCluster -n 192.168.1.100:9876 -r 16 -w 16 -t topic2;
...
> ./mqadmin updateTopic -c MyCluster -n 192.168.1.100:9876 -r 16 -w 16 -t topic500;
I can send the message  without delay  ,but I find sometime that  the client can not consume the message because the broker do not have consume client.How to fix this bug?
![image](https://user-images.githubusercontent.com/5530411/114261082-3934a000-9a0b-11eb-96ac-0d3cf949fd82.png)

**Comment by maixiaohai** [comment]
Hi @VAEAZE , refer to this issue https://github.com/apache/rocketmq-spring/issues/339
set different instance name can fix it.

**Comment by VAEAZE** [comment]
@maixiaohai ,at first ,I start two instance,when I find that may be the reason,I have stop all of them.Ant then start one of the instance,but when the topic is create more  and more,the problem still happen,

**Comment by Dr-wgy** [comment]
https://heapdump.cn/article/5003784
