### ISSUE TITLE
Pictures are missing in this document.

### ISSUE THREAD

**Issue by htf1129** [apache/rocketmq#2795]
https://github.com/apache/rocketmq/blob/master/docs/cn/design.md
Pictures are missing in this document.
I really hope there are pictures in this document for us to understand.

**Comment by francisoliverlee** [comment]
@htf1129 there is pictures as bellow, maybe network problems.
![image](https://user-images.githubusercontent.com/5908412/114314426-27e3b480-9b2d-11eb-9722-5c6465f71c5e.png)

**Comment by htf1129** [comment]
I'm sorry. It's my fault that the image is missing due to my browser plugin.
