### ISSUE TITLE
./mqadmin sendMsgStatus 参数描述错误

### ISSUE THREAD

**Issue by hzhxxx** [apache/rocketmq#2799]
# ./mqadmin sendMsgStatus
usage: mqadmin sendMsgStatus -b <arg> [-c <arg>] [-h] [-n <arg>] [-s <arg>]
 -b,--brokerName <arg>    Broker Name
 -c,--count <arg>         send message count, Default: 50
 -h,--help                Print help
 -n,--namesrvAddr <arg>   Name server address list, eg: 192.168.0.1:9876;192.168.0.2:9876
 -s,--messageSize <arg>   Message Size, Default: 128

参数   -b,--brokerName <arg>    Broker Name 实际上应该是 -t topic
./mqadmin sendMsgStatus -b testTopic -n "10.7.30.121:9876;10.7.30.122:9876"

**Comment by panzhi33** [comment]
这个是因为mq已经在每个broker里面创建了一个和brokerName相同的topic，他的描述就是 给broker发送消息。可以理解为这个命令是为了检查每台broker发消息是否正常
