### ISSUE TITLE
remove redundant separator

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#2806]
In the test program `MappedFileQueueTest`, the `storePath` last slash is redundant when passing `storePath` to the `MappedFileQueue` constructor, because after defining the MappedFileQueue object, and then call `mappedFileQueue.getLastMappedFile(0)` method, this method inside will be joining the `File.separator`(slash)

**Comment by RongtongJin** [comment]
IMO, this pull request is not very helpful to the project, so I will close it first. Plz feel free to reopen it if you have another question.
