### ISSUE TITLE
The client config consumeThreadMax doesn't work

### ISSUE THREAD

**Issue by tastypinenut** [apache/rocketmq#281]
The issue tracker is **ONLY** used for bug report and feature request. Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

```
this.consumeRequestQueue = new LinkedBlockingQueue<Runnable>();

this.consumeExecutor = new ThreadPoolExecutor(
          this.defaultMQPushConsumer.getConsumeThreadMin(),
          this.defaultMQPushConsumer.getConsumeThreadMax(),
          1000 * 60,
          TimeUnit.MILLISECONDS,
          this.consumeRequestQueue,
          new ThreadFactoryImpl("ConsumeMessageThread_"));
```
The `consumeRequestQueue` is a LinkedBlockingQueue with a capacity of Integer#MAX_VALUE, which means the thread of executor `consumeExecutor` won't expand until the queue meets the limit while it's not impossible.

- What did you do (The steps to reproduce)?

Sets the ConsumeThreadMax a larger value than ConsumeThreadMin, then you will find the thread number of consumeExecutor always stay unchanged.

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by zhouxinyu** [comment]
Hi, I changed the title and content following our issue template, please notice that in your future report.
Thanks.

**Comment by vongosling** [comment]
This is not a bug. Please read the issue template carefully, If you have any question furthermore, please ask for our user email list. http://rocketmq.apache.org/about/contact/

**Comment by shepherdviolet** [comment]
> This is not a bug. Please read the issue template carefully, If you have any question furthermore, please ask for our user email list. http://rocketmq.apache.org/about/contact/

Hello, can you tell me why isn't this a bug? The config 'consumeThreadMax' is useless in this case, and can cause misunderstandings.

Especially when using 'rocketmq-spring-boot-starter', the annotation @RocketMQMessageListener can only set the 'consumeThreadMax', This means we have no way to configure the number of threads......
