### ISSUE TITLE
The wrong topic was consumed in the DefaultMessageStoreTest test program

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#2811]
![image](https://user-images.githubusercontent.com/43363120/114822059-15e76780-9df4-11eb-9df3-a863172d27e9.png)
![image](https://user-images.githubusercontent.com/43363120/114822054-13850d80-9df4-11eb-91bf-dbd110e402d9.png)

The putMessage uses the `FooBar` topic, but getMessage gets the message from the `TOPIC_A` topic

**Comment by duhenglucky** [comment]
@BurningCN Would you like submit a PR to fix it?

**Comment by BurningCN** [comment]
> @BurningCN Would you like submit a PR to fix it?

Okay, no problem
