### ISSUE TITLE
fix messageArrivingListener NPE 

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#2816]
In the `HATest#testHandleHA` test program, in the `buildMessageStore` method, the DefaultMessageStore object that is constructed for master and slave is passed the `messageArrivingListener` parameter is null. `ReputMessageService` does not determine whether it is null, resulting in the occurrence of NPE.

The screenshot below：

![image](https://user-images.githubusercontent.com/43363120/114962928-3b30b000-9e9e-11eb-84a3-3b26e3be334e.png)

![image](https://user-images.githubusercontent.com/43363120/114962903-2f44ee00-9e9e-11eb-9b47-0a1c35dc65c2.png)

**Comment by duhenglucky** [comment]
merged
