### ISSUE TITLE
The logic of the the broker's handling of RequestCode.QUERY_DATA_VERSION responses needs to be modified

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq#2817]
When a broker registers routing information with a cluster of nameservers, the broker needs to decide whether it is necessary to register routing information with a cluster of nameservers, by sending requests to the cluster to compare whether they have the same version of data. 
Nameserver cluster receives a request, and after comparing the versions of the data, it will give feedback on the changed property of the header in the response. This value must not be null, so the broker only needs to decode the changed property of the response message.
So, I think the method needRegister(..) of BrokerOuterAPI.java can delete the code that decode the body of the response. In addition，the return value of the method needRegister(...) of BrokerController.java can depend on whether the size of the changedList is greater than 0

**Comment by panzhi33** [comment]
double check。if not change，But there is topic update on the broker side, so you need to wait for the next time to update namesrv

**Comment by sunxi92** [comment]
two problems:
(1)when broker receives namesrv's response, there is no need to decode the body of the response
(2) in the reponse that the namesrv returns, changed will not be null, it's true or false 
![image](https://user-images.githubusercontent.com/25401190/114971421-db8ed080-9eae-11eb-861f-f17bca4441ea.png)

Since the changedList only obatain the value of Boolean.TRUE, so we only judge whether the size of changedList is greater than 0 instead of loop the list
![image](https://user-images.githubusercontent.com/25401190/114971892-e1d17c80-9eaf-11eb-96b2-a97ccbe3d2d5.png)
