### ISSUE TITLE
The channel used by slave to request synchronous metadata information from master is different

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq#2819]
The channel used by slave to request synchronous metadata information from master is different：
port 10909 is used to synchronous the topic configuration information and port 10911 is used for the rest of the information
Is there a problem with that?

![未命名3](https://user-images.githubusercontent.com/25401190/114966872-045e9800-9ea6-11eb-8f81-439e6d936096.png)

**Comment by lizhiboo** [comment]
> The channel used by slave to request synchronous metadata information from master is different：
> port 10909 is used to synchronous the topic configuration information and port 10911 is used for the rest of the information
> Is there a problem with that?
> 
> ![未命名3](https://user-images.githubusercontent.com/25401190/114966872-045e9800-9ea6-11eb-8f81-439e6d936096.png)

IMO, metadata sync is only used for inner, it no need to expose to user, so use another port.

**Comment by sunxi92** [comment]
The port 10909 is used to synchronous the topic.json, but the port 10911 is used to synchronous consumerOffset.json、delayOffset.json and subscriptionGroup.json.
Why the rest three metadata use 10911 instead of 10909.Is there a problem with that?
![image](https://user-images.githubusercontent.com/25401190/115245178-3e09fa00-a157-11eb-8d6d-d35ba308eb20.png)
![image](https://user-images.githubusercontent.com/25401190/115245282-59750500-a157-11eb-801d-b61f696294db.png)
![image](https://user-images.githubusercontent.com/25401190/115245403-76113d00-a157-11eb-8591-7f9446dc0b7e.png)

**Comment by sunxi92** [comment]
@duhenglucky if you can confirm this problem, I can fix it

**Comment by absolute8511** [comment]
@lizhiboo Any fix plan here?
