### ISSUE TITLE
Shutdown issue about HAClient

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#2821]
In `HATest#testSemiSyncReplica` the test program, when `slaveMessageStore.shutdown()`-->`haService.shutdown()`-->`haClient.shutdown()`, This `haClient.shutdown()` method should be overridden with a call to `closeMaster` method after `super.shutdown() `, to let the master know early that salve initiated the shutdown.

**Comment by RongtongJin** [comment]
Merged
