### ISSUE TITLE
The warnings in PerName.java

### ISSUE THREAD

**Issue by shenshaoming** [apache/rocketmq#2826]
I found two warnings in org.apache.rocketmq.common.constant.PerName，and the second warnings is more important.

1. useless bit operation
`public static final int PERM_INHERIT = 0x1 << 0;`
2. useless StringBuffer
In method perm2String(final int perm), create a SpringBuffer obj inside this method, which means it can't be puzzled by thread safe.Should use StringBuilder instead.
```
    public static String perm2String(final int perm) {
        final StringBuffer sb = new StringBuffer("---");
        if (isReadable(perm)) {
            sb.replace(0, 1, "R");
        }

        if (isWriteable(perm)) {
            sb.replace(1, 2, "W");
        }

        if (isInherited(perm)) {
            sb.replace(2, 3, "X");
        }

        return sb.toString();
    }
```

**Comment by lizhimins** [comment]
OK

**Comment by hill007299** [comment]
@shenshaoming would you like submit a PR to fix it?

**Comment by lwclover** [comment]
jvm会有锁消除机制
