### ISSUE TITLE
One consumer group can't subscribe with diffrent tag

### ISSUE THREAD

**Issue by 8da2k** [apache/rocketmq#2836]
One consumer group can't subscribe with diffrent tag.
producer send message with tag "abc"; consumer 1 subscribe a topic with tag "a"; consumer 2 subscribe a topic with tag "*".
2 consumers can't receive any message.

**Comment by panzhi33** [comment]
Inconsistent subscription relationship。https://blog.csdn.net/zchdjb/article/details/97722500

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.
