### ISSUE TITLE
Multiple consumer will be assigned the same consumequeue because of delay and other reasons?

### ISSUE THREAD

**Issue by ChenYilei2016** [apache/rocketmq#2837]
rocketmq 多个consumer  rebalnce 是自己进行的不和其他 consumer 交互.
这样 会不会因为延迟原因啥的,  同时消费一个consumeQueue ,  我看到顺序消费者会在 rebalance的时候 进行一个lock操作, 为什么并发消费者不弄一个lock呢

**Comment by panzhi33** [comment]
顺序消息要保证每个queue里面的消息被顺序消费，因此需要保证增加或减少消费者实例时，需要重新负载均衡时，只能有一个消费者实例分配到这个queue。并发消费不需要保证顺序性，因此不需要lock

**Comment by ChenYilei2016** [comment]
> 顺序消息要保证每个queue里面的消息被顺序消费，因此需要保证增加或减少消费者实例时，需要重新负载均衡时，只能有一个消费者实例分配到这个queue。并发消费不需要保证顺序性，因此不需要lock

也就是说 会存在多个consumer 同时消费一个queue的情况吧?

**Comment by panzhi33** [comment]
> > 顺序消息要保证每个queue里面的消息被顺序消费，因此需要保证增加或减少消费者实例时，需要重新负载均衡时，只能有一个消费者实例分配到这个queue。并发消费不需要保证顺序性，因此不需要lock
> 
> 也就是说 会存在多个ConcurrentConsumer 同时消费一个queue的情况吧
> 虽然ConcurrentConsumer 不用保证顺序性, 但加上lock 也可以减少重复消费吧?

加了lock就会损耗掉一些性能的，同时消费者上下线期间重新负载均衡时，这段时间有可能不能消费。为了保证高性能消费，因此需要牺牲消息的重复消费

**Comment by ChenYilei2016** [comment]
> > > 顺序消息要保证每个queue里面的消息被顺序消费，因此需要保证增加或减少消费者实例时，需要重新负载均衡时，只能有一个消费者实例分配到这个queue。并发消费不需要保证顺序性，因此不需要lock
> > 
> > 
> > 也就是说 会存在多个ConcurrentConsumer 同时消费一个queue的情况吧
> > 虽然ConcurrentConsumer 不用保证顺序性, 但加上lock 也可以减少重复消费吧?
> 
> 加了lock就会损耗掉一些性能的，同时消费者上下线期间重新负载均衡时，这段时间有可能不能消费。为了保证高性能消费，因此需要牺牲消息的重复消费

Thanks♪(･ω･)ﾉ
