### ISSUE TITLE
Transaction message small loss problem

### ISSUE THREAD

**Issue by 309283175** [apache/rocketmq#2840]
RocketMQ版本：4.4.0
executeLocalTransaction 程序日志文件表明已经本地事务返回 LocalTransactionState.COMMIT_MESSAGE
现象：业务部门反馈数据丢失。
现状：1.通过业务数据key查询RMQ_SYS_TRANS_HALF_TOPIC主题中可以查到预消息。但是在实际的主题中的确是查不到该消息。
2.由于数据量大，服务端transaction.log基本5分钟就会压缩一个日志包，10个包最多只能保留不到1小时的日志，丢失的这条消息在预主题中产生的时间为下午13:30左右，下午3点钟左右业务部门反馈数据丢失。日志已经刷没了。

**Comment by yuz10** [comment]
本地事务返回COMMIT，不能保证commit消息送到，要依赖回查机制，请确保checkLocalTransaction回调函数也返回了COMMIT

**Comment by hill007299** [comment]
@309283175 建议升级到4.7.0后的版本，针对事务消息做了很多优化。
