### ISSUE TITLE
Because checkstyle's xml dtds path is invalid, the mvn operation cannot be successful.

### ISSUE THREAD

**Issue by andotorg** [apache/rocketmq#2841]
该地址已经失效
http://www.puppycrawl.com/dtds/configuration_1_3.dtd
直接访问则是404

**Comment by panzhi33** [comment]
你是用的那个分支，使用的打包命令是啥呀，我试下

**Comment by vongosling** [comment]
You are correct. Would you like to pr it ? Maybe you need to update the Maven plug-in[1].

[1] https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml

**Comment by andotorg** [comment]
> 你是用的那个分支，使用的打包命令是啥呀，我试下

mvn -Prelease-all -DskipTests clean install -U  这个命令我试了下，没有报错

**Comment by andotorg** [comment]
我在注释掉
`<plugin>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
                <executions>
                    <execution>
                        <id>verify</id>
                        <phase>verify</phase>
                        <configuration>
                            <configLocation>style/rmq_checkstyle.xml</configLocation>
                            <encoding>UTF-8</encoding>
                            <consoleOutput>true</consoleOutput>
                            <failsOnError>true</failsOnError>
                            <includeTestSourceDirectory>false</includeTestSourceDirectory>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`
mvn -Prelease-all -DskipTests clean install -U
就可以正常成功的

**Comment by andotorg** [comment]
我在注释掉
`<plugin>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
                <executions>
                    <execution>
                        <id>verify</id>
                        <phase>verify</phase>
                        <configuration>
                            <configLocation>style/rmq_checkstyle.xml</configLocation>
                            <encoding>UTF-8</encoding>
                            <consoleOutput>true</consoleOutput>
                            <failsOnError>true</failsOnError>
                            <includeTestSourceDirectory>false</includeTestSourceDirectory>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`
mvn -Prelease-all -DskipTests clean install -U
就可以正常成功的
