### ISSUE TITLE
how to query messages with rocketmq-v4.8.0

### ISSUE THREAD

**Issue by xdandyx** [apache/rocketmq#2844]
`producer.queryMessage` has been deprecated, then how to query messages in rocketmq. I found an API called  `MQAdmin.queryMessage`, but i don't know how to use it. could you give an example.

**Comment by panzhi33** [comment]
org.apache.rocketmq.tools.command.message.QueryMsgByUniqueKeySubCommand

**Comment by xdandyx** [comment]
> org.apache.rocketmq.tools.command.message.QueryMsgByUniqueKeySubCommand
> org.apache.rocketmq.tools.command.message.QueryMsgByKeySubCommand
> You can look at these two class

Ok,thank you.  Finally,  I found an API called DefaultMQAdminExt.queryMessage which is just what i want , and i know  the API is based on tools.command.
