### ISSUE TITLE
start mqnamesrv error in OS SUSE 11

### ISSUE THREAD

**Issue by daanhan** [apache/rocketmq#2846]
报错了！！启动nameserver报错，脚本里使用了sed，不能使用-E参数。麻烦修正😂

位置：runserver.sh line 69

报错内容：
sed：无效选项 -- E
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

OS: SUSE Linux Enterprise Server 11 (x86_64)
rocketmq version: 4.8.0
sed version: 4.1.5
java version: 1.8.0_192

**Comment by panzhi33** [comment]
你将-E 替换成-r 试下

**Comment by daanhan** [comment]
换成-r可以！
