### ISSUE TITLE
About a reject request bug

### ISSUE THREAD

**Issue by aluomaidi** [apache/rocketmq#285]
A error occured while send a message,the following request will be rejected by server and throw an  exception:[REJECTREQUEST]system busy, start flow control for a while.

- I saw the source code and find the error occured in mappedFile.appendMessage() within commitLog.putMessage()
- commitLog.putMessage() exit without reset the member variable beginTimeInLock,so DefaultMessageStore.isOSPageCacheBusy() will return true
- the method NettyRemotingAbstract.processRequestCommand() will revoke SendMessageProcessor.rejectRequest() and return true 
- the method NettyRemotingAbstract.processRequestCommand()  return response with "[REJECTREQUEST]system busy, start flow control for a while"

SO, I think it is a bug.The member variable beginTimeInLock should be reset to be 0 at finally block.

**Comment by iamzhoug37** [comment]
It's not a bug. The purpose of doing this is to reduce produce latency.

**Comment by aluomaidi** [comment]
How does it reduce produce latency? In other words, why reset beginTimeInLock at finally block like release putlock will increase produce latency?

**Comment by vongosling** [comment]
Please read the issue template carefully, If you have any question furthermore, please ask for our user email list. http://rocketmq.apache.org/about/contact/
