### ISSUE TITLE
Remove code duplication in CommitLog putMessage ayncPutMessage methods

### ISSUE THREAD

**Issue by andsel** [apache/rocketmq#2853]
The methods `asycPutMessage` and `putMessage` in class `CommitLog` shares a lot of code:

https://github.com/apache/rocketmq/blob/b4240d5cea8d001c21b9c0d73f5aa700fcd0d568/store/src/main/java/org/apache/rocketmq/store/CommitLog.java#L559-L662

https://github.com/apache/rocketmq/blob/b4240d5cea8d001c21b9c0d73f5aa700fcd0d568/store/src/main/java/org/apache/rocketmq/store/CommitLog.java#L788-L902

removing duplication simplify the code base.

**Comment by duhenglucky** [comment]
@andsel would you like to submit a PR to polish it?

**Comment by andsel** [comment]
@duhenglucky the PR #2854 solves this, missed to link it here
