### ISSUE TITLE
How to update topic's router?

### ISSUE THREAD

**Issue by hjl2015** [apache/rocketmq#286]
有2个broker，分别是173,174组成双master集群，如果173 shutdown，那么新创建的topic只会路由到174的broker，即使173后面重新开启，topic也不会自动更新路由信息，导致问题：
1.topic没有负载均衡
2.如果174 shutdown，那么这个topic将无法生产和消费
所以要怎样更新topic的路由信息？谢谢！

I have 2 broker,173 and 174 use 2master-noslave,If 173 shutdown, The new topic only has 174's router info, Even if 173 restart,The topic's router could't update,so has 2 questions:
1.the topic not load balancing
2.if 174 shutdown,the topic can not produce and consume
So how to update topic's router? Thinks!

**Comment by lizhanhui** [comment]
Does your broker 173 use the same name server address after restart? Please check broker.log to verify your broker 173 connects and heartbeats normally to the name server instances.

**Comment by hjl2015** [comment]
Yes,Use the same name server address!
The question can also describe by "How to add a new broker?"
When start a new broker,The old topic should update router info include the new broker!

**Comment by vongosling** [comment]
Please read the issue template carefully, If you have any question furthermore, please ask for our user email list. http://rocketmq.apache.org/about/contact/
