### ISSUE TITLE
producer and cunsumer support opentracing 

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#2860]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
producer and cunsumer support opentracing , see opentracing for kafka client: https://github.com/opentracing-contrib/java-kafka-client
2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
nice-to-have

**Comment by vongosling** [comment]
Thanks for your request. But if we want to built-in this feature in the core. I don't think we could do the same wrapper like other MQ :-)
