### ISSUE TITLE
Potential NPE in ACL plain

### ISSUE THREAD

**Issue by ErrReporter** [apache/rocketmq#2863]
**BUG REPORT**

1. Please describe the issue you observed:

Our code analyses found the following potential NPE:

- Return null to caller
https://github.com/apache/rocketmq/blob/b4240d5cea8d001c21b9c0d73f5aa700fcd0d568/acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java#L276

- Function getYamlDataObject executes and returns
https://github.com/apache/rocketmq/blob/b4240d5cea8d001c21b9c0d73f5aa700fcd0d568/acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java#L134

- aclAccessConfigMap is passed as the this pointer to function java.util.Map.get (aclAccessConfigMap can be null)
https://github.com/apache/rocketmq/blob/b4240d5cea8d001c21b9c0d73f5aa700fcd0d568/acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java#L137

Commit: b4240d5cea8d001c21b9c0d73f5aa700fcd0d568

2. Please tell us about your environment:
N/A

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by shendongsd** [comment]
Does anyone solve this problem，could I submit a PR to fix it?

**Comment by shendongsd** [comment]
> would you like to submit a PR to fix it?

Does anyone solve this problem  now，could I submit a PR to fix it?

**Comment by ErrReporter** [comment]
> > would you like to submit a PR to fix it?
> 
> Does anyone solve this problem now，could I submit a PR to fix it?

Not yet. Would you please submit the PR? Thanks.

**Comment by shendongsd** [comment]
> > > would you like to submit a PR to fix it?
> > 
> > 
> > Does anyone solve this problem now，could I submit a PR to fix it?
> 
> Not yet. Would you please submit the PR? Thanks.
OK
