### ISSUE TITLE
producer auto create topic , defaultTopicQueueNums not work  。the queueNums always smaller then    defaultTopicConfig

### ISSUE THREAD

**Issue by hYuang** [apache/rocketmq#2864]
**broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java**

 public TopicConfig createTopicInSendMessageMethod(final String topic, final String defaultTopic,
        final String remoteAddress, final int clientDefaultTopicQueueNums, final int topicSysFlag) {
        TopicConfig topicConfig = null;
        boolean createNew = false;

        try {
            if (this.lockTopicConfigTable.tryLock(LOCK_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)) {
                try {
                    topicConfig = this.topicConfigTable.get(topic);
                    if (topicConfig != null)
                        return topicConfig;

                    TopicConfig defaultTopicConfig = this.topicConfigTable.get(defaultTopic);
                    if (defaultTopicConfig != null) {
                        if (defaultTopic.equals(TopicValidator.AUTO_CREATE_TOPIC_KEY_TOPIC)) {
                            if (!this.brokerController.getBrokerConfig().isAutoCreateTopicEnable()) {
                                defaultTopicConfig.setPerm(PermName.PERM_READ | PermName.PERM_WRITE);
                            }
                        }

                        if (PermName.isInherited(defaultTopicConfig.getPerm())) {
                            topicConfig = new TopicConfig(topic);

                           

 _**int queueNums =
                                clientDefaultTopicQueueNums > defaultTopicConfig.getWriteQueueNums() ? defaultTopicConfig
                                    .getWriteQueueNums() : clientDefaultTopicQueueNums;**_ 

                            if (queueNums < 0) {
                                queueNums = 0;
                            }

                            topicConfig.setReadQueueNums(queueNums);
                            topicConfig.setWriteQueueNums(queueNums);
                            int perm = defaultTopicConfig.getPerm();
                            perm &= ~PermName.PERM_INHERIT;
                            topicConfig.setPerm(perm);
                            topicConfig.setTopicSysFlag(topicSysFlag);
                            topicConfig.setTopicFilterType(defaultTopicConfig.getTopicFilterType());
                        } else {
                            log.warn("Create new topic failed, because the default topic[{}] has no perm [{}] producer:[{}]",
                                defaultTopic, defaultTopicConfig.getPerm(), remoteAddress);
                        }
                  

    }

**Comment by panzhi33** [comment]
The number of queues in defaultTopicConfig is determined by the defaultTopicQueueNums in the broker.conf configuration file. Generally, it should not be larger than this number. If you need to modify it, you can use the updateTopic operation and maintenance command to modify it.
Also, it is not recommended to turn on the autoCreateTopicEnable switch

**Comment by hYuang** [comment]
> The number of queues in defaultTopicConfig is determined by the defaultTopicQueueNums in the broker.conf configuration file. Generally, it should not be larger than this number. If you need to modify it, you can use the updateTopic operation and maintenance command to modify it.
> Also, it is not recommended to turn on the autoCreateTopicEnable switch

thank you
