### ISSUE TITLE
fix some problems in sending msg

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq#2870]
1.Repeatedly call the checkMessage(Message msg, DefaultMQProducer defaultMQProducer) to  check the msg and topic in the sync sending msg
![image](https://user-images.githubusercontent.com/25401190/117928717-866ba080-b32e-11eb-832b-94c5e5800f99.png)
![image](https://user-images.githubusercontent.com/25401190/117928805-a4d19c00-b32e-11eb-8eaa-dca4b51e0abc.png)

2.When select a message queue,  the list of faultItem is shuffled before sorted. I think the shuffle operation is redundant
![image](https://user-images.githubusercontent.com/25401190/117930265-5c1ae280-b330-11eb-99a8-d2ace825a067.png)

3.In the following methods， msg and topic(the method of Validators.checkMessage(...))checks are missing:
![image](https://user-images.githubusercontent.com/25401190/117930597-c469c400-b330-11eb-930b-d37992584692.png)
![image](https://user-images.githubusercontent.com/25401190/117930728-eebb8180-b330-11eb-9fe6-6d5193f9ddc1.png)

**Comment by Git-Yang** [comment]
link https://github.com/apache/rocketmq/issues/2831

**Comment by yuz10** [comment]
#2080
