### ISSUE TITLE
mutiple master cluster, delete topic on one broker, but  topic route not update on namesrv

### ISSUE THREAD

**Issue by liyangbing** [apache/rocketmq#288]
version  rocketmq  3.2.6

we  distribute topic A on broker-a and broker-b,
then call MQAdminExt.deleteTopicInBroker delete topic A on broker-a
But find the namesrv topicRoute not update,  restart namersrv, topicRoute update
do we have any other method? but restart namesrv

**Comment by zhouxinyu** [comment]
You can execute `mqadmin deleteTopic` command that will update the route info to name server as well.

**Comment by liyangbing** [comment]
mqadmin deleteTopic command  delete topic A  from cluster,
but we need topic A on broker-b

**Comment by liyangbing** [comment]
@zhouxinyu 
i view the namesrv code,advise add removeDeletedTopicQueueData code

RouteInfoMansger.registerBroker()

if (tcTable != null) {
for (String topic : tcTable.keySet()) {
TopicConfig topicConfig = tcTable.get(topic);
this.createAndUpdateQueueData(brokerName, topicConfig);
}
}

//add code
removeDeletedTopicQueueData(brokerName, tcTable);

// add code
private void removeDeletedTopicQueueData(String brokerName,
ConcurrentHashMap<String, TopicConfig> tcTable) {
Iterator<Entry<String, List<QueueData>>> itMap =
this.topicQueueTable.entrySet().iterator();
while (itMap.hasNext()) {
Entry<String, List<QueueData>> entry = itMap.next();

String topic = entry.getKey();
List<QueueData> queueDataList = entry.getValue();
Iterator<QueueData> it = queueDataList.iterator();
while (it.hasNext()) {
QueueData qd = it.next();
if (qd.getBrokerName().equals(brokerName)) {
if (!tcTable.contains(topic)) {
log.info("removeDeletedTopic, remove one broker's
topic {} {}", topic, qd);
it.remove();
}
}
}
}
}
