### ISSUE TITLE
WARN ReputMessageService - found a illegal magic code 0x

### ISSUE THREAD

**Issue by liyangbing** [apache/rocketmq#289]
version
rocketmq 3.2.6

master broker crash, then slave broker print following warn

WARN ReputMessageService - found a illegal magic code 0x696e4d73
then restart slave, error disappear

the error appear when commit log damage
i have two questions?
1. what conditions happen the error？
2. why error disapper after restart broker?

**Comment by zhouxinyu** [comment]
Please provide the detailed log info and send your questions to user or dev mailing lists.

**Comment by usstcpf** [comment]
I also encountered this problem. How to solve this problem? @liyangbing @zhouxinyu

**Comment by gaoyf** [comment]
refer https://blog.csdn.net/a417930422/article/details/124838463
