### ISSUE TITLE
kafka已经祛除zk了，rocketmq以后会把nameserver砍掉吧，多部署一个就增加一些麻烦

### ISSUE THREAD

**Issue by z5614036** [apache/rocketmq#2894]
kafka已经祛除zk了，rocketmq能跟进吗？

**Comment by duhenglucky** [comment]
@z5614036 这个建议涉及到的架构改动比较大，所以最好咱们再dev@rocketmq.apache.org，users@rocketmq.apache.org 里面先讨论下。这里面有个前提就是先搜集下nameserver 是不是真的给运维带来了很大负担，或者去掉zk 后的运维负担是不是更重？毕竟 name server 是很轻的，不同于zk。

**Comment by vongosling** [comment]
Why we would follow others' action? RocketMQ has its own design philosophy, if you follow the latest RIP about architecture updates, you could have a better understanding of the fact that we have better and more tangible improvements in data management.
