### ISSUE TITLE
阶段性并发消费

### ISSUE THREAD

**Issue by dragon-zhang** [apache/rocketmq#2896]
比如电商搞活动，前10笔订单可以额外获得一台笔记本电脑，前10-30笔订单可以额外获得一台平板电脑，前30-100笔订单可以额外获得一台手机，而在100笔之后订单则没有额外的奖励。

    将1-10的区间称为阶段1；
    将10-30的区间称为阶段2；
    将30-100的区间称为阶段3；
    将100+的区间称为阶段4；

由于每个阶段的奖励都相同，因此只需要阶段之间保证顺序(阶段2必须在阶段1后面)即可，而阶段内可以乱序(比如阶段1的10条消息可以并发消费)，MessageListenerPeriodicConcurrently为此类场景而生。

PR here: https://github.com/apache/rocketmq/pull/2895

**Comment by duhenglucky** [comment]
这是个批量顺序消息的特性？挺好的建议，能不能先在邮件列表发个讨论邮件，前面挺多人提过批量消息的特性（批量发，批量收）
