### ISSUE TITLE
根据时间戳设置消息进度的时候不生效？消息回溯

### ISSUE THREAD

**Issue by crossdawn** [apache/rocketmq#290]
命令如下：
resetOffsetByTime -s now -g groupname -t topicname -n nameserver:port
使用场景：新的消费者组 关注了老的topic，但是不想处理老的消息，希望从设置的时间开始消费
操作步骤：停掉了新的消费者组的consumer，然后执行了上述命令，然后启动消费者，发现还是消费了停掉之前的消息

**Comment by zhouxinyu** [comment]
Hi,

Follow the below steps to find the reason:

1. Execute `mqadmin topicStatus`, find the current message offset of the specific topic.
2. Execute `mqadmin consumerProgress`, find the current consumed offset of the specific consumer group.
3. Execute `mqadmin resetOffsetByTime`, watch the result to check whether the new offset is the max offset of the topic.
4. Execute `mqadmin consumerProgress`, watch the new offset.

Collect this command outputs and send an email to our user mailing list for help.

And please respect our issue template for your future reports.
