### ISSUE TITLE
Producer should not need to start scheduledtask persistallconsumeroffset to reduce the use of producer server resources

### ISSUE THREAD

**Issue by yang930329** [apache/rocketmq#2916]
一、Producer should not need to start scheduledtask persistallconsumeroffset
![1621482517(1)](https://user-images.githubusercontent.com/43202958/118916358-5d1bc780-b961-11eb-8fc0-2e31a751ae1b.jpg)

![image](https://user-images.githubusercontent.com/43202958/118916455-95bba100-b961-11eb-9581-4e516cd3cfab.png)

![image](https://user-images.githubusercontent.com/43202958/118916502-a9670780-b961-11eb-9daa-9c907e8b2161.png)

**Comment by lizhimins** [comment]
Thanks for your report, and could you make a pr to fix it?
