### ISSUE TITLE
How to modify broker port?

### ISSUE THREAD

**Issue by longforfreedom** [apache/rocketmq#293]
broker用到三个端口，只有listenPort在配置文件中有配置项，另外两个端口直接引用listenPort+2和listenPort-1，没有办法修改？

**Comment by lizhanhui** [comment]
Any reasonable rationale to modify them?

**Comment by vongosling** [comment]
If you have any question furthermore,  please ask for user mail list to help. http://rocketmq.apache.org/about/contact/

**Comment by longforfreedom** [comment]
@lizhanhui Environment is limited,only specified port can be used.

**Comment by ran-coder** [comment]
+1

**Comment by ran-coder** [comment]
强迫症
