### ISSUE TITLE
send request to <xx.xx.xx.xx:10911> failed 

### ISSUE THREAD

**Issue by liuqingshuai** [apache/rocketmq#2933]
broker使用外网ip之后就一直报错，连接不上这个broker的监听端口，端口已经确认是对外开放的

**Comment by lizhimins** [comment]
Thanks for your report, and could you describe this issue in detail？

**Comment by duhenglucky** [comment]
确认下broker 上报的ip 是本机器IP，还是外网IP，如果是本机IP，建议在broker 的配置文件中增加 brokerIP1 = 外网IP 的配置
