### ISSUE TITLE
Client may submit wrong offset when network instability

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq#2944]
1. When the network is unstable and clients establish connections repeatedly, there may be loss offset.
2. Client submit wrong offset -1
3. Broker fix offset to broker min offset
4. Client reconsume all message in specific queues

https://github.com/apache/rocketmq/issues/2708

**Comment by francisoliverlee** [comment]
same with https://github.com/apache/rocketmq/issues/2708
