### ISSUE TITLE
broker busy or system busy

### ISSUE THREAD

**Issue by jiqingsuiyue** [apache/rocketmq#2945]
where I send message，the rocketmq report broker busy or system busy
E.g:
  CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 200ms, size of queue: 12 
my rocketmq config:
brokerName=Lifekh_Broker1
brokerClusterName=Lifekh_Cluster
brokerId=0
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
rejectTransactionMessage=false
fetchNamesrvAddrByAddressServer=false
storePathRootDir=/data/rocketmq_lifekh/store
storePathCommitLog=/data/rocketmq_lifekh/store/commitlog
storePathConsumeQueue=/data/rocketmq_lifekh/store/consumequeue
storePathIndex=/data/rocketmq_lifekh/store/index
storeCheckpoint=/data/rocketmq_lifekh/store/checkpoint
abortFile=/data/rocketmq_lifekh/store/abort
flushIntervalCommitLog=1000
flushCommitLogTimed=false
deleteWhen=04
fileReservedTime=72
mapedFileSizeCommitLog=1073741824
maxMessageSize=65536
mapedFileSizeConsumeQueue=300000
maxTransferBytesOnMessageInMemory=262144
maxTransferCountOnMessageInMemory=32
maxTransferBytesOnMessageInDisk=65536
maxTransferCountOnMessageInDisk=8
accessMessageInMemoryMaxRatio=40
messageIndexEnable=true
messageIndexSafe=false
haMasterAddress=
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
cleanFileForciblyEnable=true
#发消息线程池数量
sendMessageThreadPoolNums=8
#发送消息是否使用可重入锁
useReentrantLockWhenPutMessage=true

rocketmq version: 4.5
Can anyone help？thank you！

**Comment by duhenglucky** [comment]
@jiqingsuiyue FYI. https://github.com/apache/rocketmq/issues/2546

**Comment by jiqingsuiyue** [comment]
https://yq.aliyun.com/articles/716568 why I can not find this article?

**Comment by jiqingsuiyue** [comment]
> @jiqingsuiyue FYI. #2546
https://yq.aliyun.com/articles/716568 why I can not find this article?
