### ISSUE TITLE
Can the multi-master mode achieve high data availability?

### ISSUE THREAD

**Issue by xhsky** [apache/rocketmq#2946]
This document(https://github.com/apache/rocketmq/blob/master/docs/en/operation.md#12-multi-master-mode ) says that if a single machine goes down, the messages on the machine that went down will be unavailable before recovery. If a topic is created on multiple masters, does the same message exist on multiple masters? Then during a downtime, the unconsumed messages can be consumed on other masters

**Comment by panzhi33** [comment]
No, the message will only exist in this group of brokers。you can quickly repair the master broker, or manually switch the slave broker to the master

**Comment by vongosling** [comment]
You could switch to DLedger mode
