### ISSUE TITLE
Operation doc mistake

### ISSUE THREAD

**Issue by WuZhiMing2** [apache/rocketmq#2947]
关于《运维管理》的文档内容有错误
文档地址
[https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md](url)
`
### 启动Broker
$ nohup sh bin/mqbroker -n localhost:9876 &

### 验证Name Server 是否启动成功，例如Broker的IP为：192.168.1.2，且名称为broker-a
$ tail -f ~/logs/rocketmqlogs/Broker.log 
The broker[broker-a, 192.169.1.2:10911] boot success...
`
查看broker的命令写错了，应该是
`
$ tail -f ~/logs/rocketmqlogs/broker.log 
`

**Comment by duhenglucky** [comment]
@WuZhiMing2 Welcome to submit a PR to fix it
