### ISSUE TITLE
In ScheduleMessageService, the function of the  DeliverDelayedMessageTimerTask is to deliver msg to commitlog, is it  a redundant operation to correct deliverTimestamp?

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq#2949]
In ScheduleMessageService, the function of the DeliverDelayedMessageTimerTask is to deliver msg to commitlog. Before send the msg, DeliverDelayedMessageTimerTask will check whether it's time to send msg. The deliverTimestamp is stored in the tagsCode，I think we can compute the time difference between the current time and deliverTimestamp, but the implementation in the source code，it will call the method of correctDeliverTimestamp to correct the deliverTimestamp. I don't understand the method of correctDeliverTimestamp. Trouble everybody to help explain the reason.
![image](https://user-images.githubusercontent.com/25401190/119628076-5ac4dc00-be3f-11eb-87a8-739efbf67fb6.png)

I don't understand the meaning of the comparison in the picture below.
![image](https://user-images.githubusercontent.com/25401190/119628214-792ad780-be3f-11eb-8844-06f3f0905e6a.png)

**Comment by Feijianjun** [comment]
Under normal logic, it is impossible to get inside this method. I think this is just to deal with the extreme case of server failure causing the fetch time to be out of order, and there is no performance impact in this area.
