### ISSUE TITLE
Anyone can tell me how to configure the log path?

### ISSUE THREAD

**Issue by rrfeng** [apache/rocketmq#295]
why it always write log to $HOME ? by design ?

**Comment by vongosling** [comment]
@lindzh

**Comment by lindzh** [comment]
If you are using 4.2.0 or lower version,Please see https://github.com/apache/rocketmq/tree/master/client/src/main/resources for more detail and https://github.com/apache/rocketmq/blob/master/client/src/main/java/org/apache/rocketmq/client/log/ClientLogger.java. RocketMQ client is using {user.home}/logs/rocketmq_client.log as it's default log file.If you want to change maxLogFileCount and logpath you can set system properties like rocketmq.client.logRoot,rocketmq.client.logFileMaxIndex,rocketmq.client.logLevel. If you want to change other option just overwrite config file.

**Comment by vongosling** [comment]
Please read issue template carefully, If you have any question furthermore, please ask for our user email list. http://rocketmq.apache.org/about/contact/
