### ISSUE TITLE
Some questions about clusters

### ISSUE THREAD

**Issue by xhsky** [apache/rocketmq#2950]
1. The relationship between master and salve is defined by brokerName and brokerid. Is the relationship between multiple masters defined by brokerClusterName and namesrvAddr?
2. In multi-master mode, how are messages stored and distributed on multiple brokers? Is the smallest individual stored a message?
3. Parameters in Dledger mode: The configuration format of "dLegerPeers" is dLegerSelfId:ip:port?
4. After Dledger is started, 3 ports will be generated. Are the functions of the two ports 30911 and 30909 the same as those of 10911 and 10909 in the broker? What is the purpose of another port of 40911 and how to customize the port. Will there be other ports?
5. When the broker or hedger mode is started, some directories will be created automatically, but some directories must be created manually (eg: data, index, consumequeue, etc.). Is this normal? Why not create them all automatically?
6. In the Dledger mode, it takes about 10 seconds for the leader to switch. Can this time be customized? How to configure?

**Comment by francisoliverlee** [comment]
in my options, 
### 1 
- definition for master and slave is brokerId, see BrokerConfig as bellow:
https://github.com/apache/rocketmq/blob/aaa92a2e53d773c7f1d9e9f25e41709f6948fa83/common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java#L43

- distinguish multiple masters by brokerName
### 2
- messages  distributed in queues.  queues in one topic are distributed on brokers
- dont understand

### 3. dLegerSelfId-ip:port

### 4. you can easily find it in source codes

### 5.  user must know where some important dirs are, so need to mkdir mannally; some not

**Comment by xhsky** [comment]
2. Assuming that a queue is defined and this queue exists on each master, what strategy is used to allocate messages entering the queue to each master? Random or rotation?

4. I'm not a java developer, can you talk about it in detail?
