### ISSUE TITLE
Not found the consumer group consume stats, because return offset table is empty, maybe the consumer not consume any message

### ISSUE THREAD

**Issue by dutyu** [apache/rocketmq#296]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
 当我配置一个BROADCASTING的消费者时，消息被正确的消费，但是通过shell命令查看消息状态（`sh mqadmin consumerProgress -n XXX -g XXX`）时报错如下：
![image](https://user-images.githubusercontent.com/5926365/39182876-d1872456-47f0-11e8-8904-2beebeb8ef59.png)
我确定消息是被正确的消费了，并且consumer返回了正确状态值(ConsumeConcurrentlyStatus.CONSUME_SUCCESS)。
 但是当我把messageModel改成CLUSTERING时却不会有这样的问题,。
![image](https://user-images.githubusercontent.com/5926365/39182882-d6adcb24-47f0-11e8-9085-6600bd327372.png)
我想知道这个是不是rocketMQ的bug。
- What did you expect to see?

- What did you see instead?
我现在需要使用rocketMQ广播消费的特性，并且需要对消息的情况做监控，所以需要查看消息的状态。
2. Please tell us about your environment:
CentOS release 6.2
服务端版本： 4.1.0-incubating
客户端版本：4.1.0-incubating
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by suclogger** [comment]
I've been encountering the same problem while try to trace consume status of broadcast messages.
As is shown in the source code `DefaultMQPushConsumerImpl`:

```java
...
if (MessageModel.CLUSTERING == this.defaultMQPushConsumer.getMessageModel()) {
            commitOffsetValue = this.offsetStore.readOffset(pullRequest.getMessageQueue(), ReadOffsetType.READ_FROM_MEMORY);
            if (commitOffsetValue > 0) {
                commitOffsetEnable = true;
            }
        }
...
        int sysFlag = PullSysFlag.buildSysFlag(
            commitOffsetEnable, // commitOffset
            true, // suspend
            subExpression != null, // subscription
            classFilter // class filter
        );
...
```
When consumeMode is set to broadcast, commit log is not recorded and so not submit to the broker, so if you can't find consume status afterward.

I assume that this is a design failure.

Originally offset is recorded by consumer-group in broker, but under broadcast mode, every client within the same consumer-group has it's own offset. And that makes it impossible to record consume status for broadcast message.

Would @vongosling explain the design and if it is planed to be fixed?

**Comment by vongosling** [comment]
Offsets are stored in client-side In broadcast mode. If you have any question furthermore, please ask for our user email list. http://rocketmq.apache.org/about/contact/

**Comment by alisanguo** [comment]
我也碰到了相同的问题，小伙伴们有解决吗？
I have the same question, do you have any solution?

**Comment by bill-wangbiao** [comment]
我也遇到了这个问题  现在有解决方案了吗

**Comment by RongtongJin** [comment]
> 我也遇到了这个问题 现在有解决方案了吗

这是一个设计问题。RocketMQ客户端在广播模式下将消费进度记录在本地，而不是broker端。而admin tool查询的是broker端。因此获取不到消费进度。
如果需要获取广播模式的消费进度，默认在客户端机器的`主目录/.rocketmq_offsets/${clientId}/${groupName}/offsets.json`中。

**Comment by Adonis-D-Gogh** [comment]
Does the new version solve this problem?I'm also having a problem with the monitoring panel not being able to read local location points in broadcast mode.
