### ISSUE TITLE
MQ message cannot be consumed

### ISSUE THREAD

**Issue by jgswp** [apache/rocketmq#2968]
I send messages through the console and code. It's sent normally, but consumers can't consume it

The system version is CentOS 7.5
Rocketmq version is 4.8.0

brocker log
<img width="1274" alt="图片" src="https://user-images.githubusercontent.com/35256326/120574908-b4866100-c452-11eb-9f81-3597d10a9532.png">
acl is started 
<img width="1397" alt="图片" src="https://user-images.githubusercontent.com/35256326/120575015-e4cdff80-c452-11eb-95dd-5b310cf6774f.png">

**Comment by jgswp** [comment]
![Uploading 图片.png…]()

**Comment by jgswp** [comment]
![Uploading 图片.png…]()

**Comment by duhenglucky** [comment]
@githublaohu @zongtanghu ping
