### ISSUE TITLE
错误: 找不到或无法加载主类 Files\java\jdk1.8\lib;C:\Program

### ISSUE THREAD

**Issue by qinshouzhi** [apache/rocketmq#297]
at windows 7 
\apache-rocketmq\bin>mqbroker
错误: 找不到或无法加载主类 Files\java\jdk1.8\lib;C:\Program

How to do?

**Comment by zhouxinyu** [comment]
Follow the quick start please: http://rocketmq.apache.org/docs/quick-start/
