### ISSUE TITLE
How to send multi transaction message at same biz 

### ISSUE THREAD

**Issue by jacentsao** [apache/rocketmq#2971]
How to send multi transaction message at same biz ,  not found in example.  Any help is thanked

**Comment by duhenglucky** [comment]
@jacentsao RocketMQ does not support this form of transaction messages temporarily

**Comment by francisoliverlee** [comment]
why do this, can u show a work flow and make a description

**Comment by jacentsao** [comment]
> why do this, can u show a work flow and make a description

Show as below picture,  in our product environment has more biz to notify. 

![](https://raw.githubusercontent.com/jacentsao/picbed/master/img/20210607194556.png)

We currently use seata to handle global transaction, but it's performance cannot met requirement, so we want to separate global transaction into different local transaction.

**Comment by jacentsao** [comment]
@francisoliverlee @duhenglucky Thanks for your reply.

**Comment by francisoliverlee** [comment]
it's very difficult to make sure Atomicity (A for ACID) in message queues,  all meesgaes processed asynchronously,
it seems you need others to solve global transaction problems,

RocketMQ could do Final-Consistency, hope it can help u
