### ISSUE TITLE
how the syncflush run?

### ISSUE THREAD

**Issue by Feijianjun** [apache/rocketmq#2974]
in 4.8version,class SendMessageProcessor.class is extend AbstractSendMessageProcessor.class,so,never run in processRequest method,and the method org.apache.rocketmq.broker.processor.SendMessageProcessor#sendMessage is never used,

so,how the syncflush run?
![image](https://user-images.githubusercontent.com/22761447/120593782-8dd82280-c472-11eb-9e23-9883b4a6ba93.png)
![image](https://user-images.githubusercontent.com/22761447/120593820-9df00200-c472-11eb-80e9-613782dbf2dd.png)

**Comment by Feijianjun** [comment]
IMO,here should be modify like this:
if(FlushDiskType.ASYNC_FLUSH == getFlushDiskType())
![image](https://user-images.githubusercontent.com/22761447/120594244-3edebd00-c473-11eb-98e1-3026aa3b7835.png)

**Comment by yglovewms** [comment]
![image](https://user-images.githubusercontent.com/52808040/120615481-e7e4e200-c48a-11eb-9fb8-a31c0b239fe4.png)
 just like this

**Comment by yglovewms** [comment]
Recommend a book for you。《RocketMq》技术内幕

**Comment by Feijianjun** [comment]
书里面说这里唤醒了发送线程，可是，发送线程在哪里等待的呢？
![image](https://user-images.githubusercontent.com/22761447/120624625-765d6180-c493-11eb-9f15-f268692d3860.png)

**Comment by panzhi33** [comment]
org.apache.rocketmq.store.CommitLog#asyncPutMessage

**Comment by Feijianjun** [comment]
submitFlushRequest方法里面并没有看到阻塞啊
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/22761447/120638941-63eb2400-c4a3-11eb-9a4f-737911db10f2.png">

**Comment by panzhi33** [comment]
> submitFlushRequest方法里面并没有看到阻塞啊
> <img alt="image" width="1167" src="https://user-images.githubusercontent.com/22761447/120638941-63eb2400-c4a3-11eb-9a4f-737911db10f2.png">

这里用到了jdk8的异步调用，这个就是等待，这是最近几个版本做的更新。如果你想看到书中那样的主动唤醒，需要看之前老版本的源码，比如4.4
