### ISSUE TITLE
in sync flush process,is here a bug?

### ISSUE THREAD

**Issue by Feijianjun** [apache/rocketmq#2976]
in sync flush process,here dont call get method to block?

is here a bug?

![image](https://user-images.githubusercontent.com/22761447/120627328-22a04780-c496-11eb-9cea-0b4c555318e8.png)

**Comment by panzhi33** [comment]
![image](https://user-images.githubusercontent.com/29321745/120736864-9dfa0b80-c51f-11eb-8c53-7c6db13c5f21.png)
同步刷盘和主备同步复制状态下，需要将两个方法的结果进行聚会才能来判断消息是否成功，都是利用的jdk8的新特性
