### ISSUE TITLE
[RIP-24]Feature Request: Support gRPC protocol

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#2978]
This issue is base on the fact below:

1. gRPC has been the standard protocol in Cloud Native, service mesh would be easily applied if gRPC is enabled.
2. The communication layer would be simplified radically If gRPC is applied.
3. Rocketmq's protocol depends on fastJson, which makes it difficult to adapt for other language. 

I noticed that pop consumer has been merged in the latest version, we can implement new SDK based on gRPC and pop, which is easier to maintain.

**Comment by aaron-ai** [comment]
@duhenglucky  @ShannonDing @RongtongJin

**Comment by zongtanghu** [comment]
@aaron-ai Yes, I agree with your opinion, actually I put forward the same ideas last year!Do you want to develop this big features?

**Comment by aaron-ai** [comment]
Yes, I would start a new pull request about this RIP recently.

________________________________
发件人: Hu Zongtang ***@***.***>
发送时间: 2021年6月11日 6:00
收件人: apache/rocketmq ***@***.***>
抄送: aaron ai ***@***.***>; Mention ***@***.***>
主题: Re: [apache/rocketmq] Feature Request: Support gRPC protocol (#2978)


@aaron-ai<https://github.com/aaron-ai> Yes, I agree with your opinion, actually I put forward the same ideas last year!Do you want to develop this big features?

―

**Comment by lizhimins** [comment]
Stateless and lightweight clients are very attractive
