### ISSUE TITLE
mq can not start

### ISSUE THREAD

**Issue by jgswp** [apache/rocketmq#2979]
<img width="1063" alt="图片" src="https://user-images.githubusercontent.com/35256326/120747405-888edc80-c533-11eb-977a-8c84a5520c57.png">
 store.log 的日志在这里，
启动后一直有这个异常，消息是可以正常发送的，但是无法消费，麻烦看下

**Comment by jgswp** [comment]
<img width="673" alt="图片" src="https://user-images.githubusercontent.com/35256326/120747572-cdb30e80-c533-11eb-87bd-5d1a03a47157.png">

**Comment by panzhi33** [comment]
日志已经很明显了呀
![image](https://user-images.githubusercontent.com/29321745/120769799-111b7600-c550-11eb-88d2-50e7b8662710.png)

**Comment by jgswp** [comment]
我配置的3g的堆 ，一条消息都没发  起不起来吗

**Comment by panzhi33** [comment]
> 我配置的3g的堆 ，一条消息都没发 起不起来吗

![image](https://user-images.githubusercontent.com/29321745/120773967-62c5ff80-c554-11eb-956f-3d942224e524.png)
堆外内存太少了

**Comment by panzhi33** [comment]
free 看下

**Comment by jgswp** [comment]
<img width="637" alt="图片" src="https://user-images.githubusercontent.com/35256326/120878811-6f4c6580-c5f1-11eb-91e1-cd793f34953e.png">

**Comment by jgswp** [comment]
<img width="1041" alt="图片" src="https://user-images.githubusercontent.com/35256326/120878817-7a9f9100-c5f1-11eb-9b14-0f0b22ff5be7.png">

**Comment by jgswp** [comment]
<img width="1330" alt="图片" src="https://user-images.githubusercontent.com/35256326/120878832-930fab80-c5f1-11eb-9a63-c45fb43fcc66.png">

**Comment by jgswp** [comment]
是可以启动的，但是发消息 后台日志就会报错，一条消息没发，启动就要10多个g的内存还内存溢出是有点奇怪呢，

**Comment by jgswp** [comment]
版本是4.8.0  操作系统是centos7.5

**Comment by duhenglucky** [comment]
@jgswp 建议先执行一下bin下面的os.sh 脚本，然后看下ulimit -v 的设置

**Comment by francisoliverlee** [comment]
try
1. exec bin/os.sh
2. another dir, not in /home
3. check java -version.

**Comment by jgswp** [comment]
another dir, not in /home 这是为啥呢
