### ISSUE TITLE
Exception log in storeerror.log

### ISSUE THREAD

**Issue by smthing** [apache/rocketmq#298]
```
2018-04-27 11:11:00 WARN PullMessageThread_12 - Offset for /alidata/store/committ
log/00000000001073741824 not matched. Request offset: 7858421, index: -1, mappedd
FileSize: 1073741824, mappedFiles count: 1
2018-04-27 11:11:00 WARN PullMessageThread_21 - findMappedFileByOffset failure.
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.jaa
va:387) ~[na:1.8.0_45]
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.jaa
va:396) ~[na:1.8.0_45]
        at org.apache.rocketmq.store.MappedFileQueue.findMappedFileByOffset(Mappp
edFileQueue.java:478) ~[rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.CommitLog.getMessage(CommitLog.java:817) [rr
ocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.DefaultMessageStore.getMessage(DefaultMessaa
geStore.java:538) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.broker.processor.PullMessageProcessor.processRequu
est(PullMessageProcessor.java:236) [rocketmq-broker-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.broker.processor.PullMessageProcessor.processRequu
est(PullMessageProcessor.java:81) [rocketmq-broker-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$1.run(NettyRR
emotingAbstract.java:178) [rocketmq-remoting-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:88
0) [rocketmq-remoting-4.2.0.jar:4.2.0]
```

**Comment by vongosling** [comment]
This is not a question channel. If you have any question furthermore, please ask for our user email list. http://rocketmq.apache.org/about/contact/.

**Comment by CoderLan0668** [comment]
> ```
> 2018-04-27 11:11:00 WARN PullMessageThread_12 - Offset for /alidata/store/committ
> log/00000000001073741824 not matched. Request offset: 7858421, index: -1, mappedd
> FileSize: 1073741824, mappedFiles count: 1
> 2018-04-27 11:11:00 WARN PullMessageThread_21 - findMappedFileByOffset failure.
> java.lang.ArrayIndexOutOfBoundsException: -1
>         at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.jaa
> va:387) ~[na:1.8.0_45]
>         at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.jaa
> va:396) ~[na:1.8.0_45]
>         at org.apache.rocketmq.store.MappedFileQueue.findMappedFileByOffset(Mappp
> edFileQueue.java:478) ~[rocketmq-store-4.2.0.jar:4.2.0]
>         at org.apache.rocketmq.store.CommitLog.getMessage(CommitLog.java:817) [rr
> ocketmq-store-4.2.0.jar:4.2.0]
>         at org.apache.rocketmq.store.DefaultMessageStore.getMessage(DefaultMessaa
> geStore.java:538) [rocketmq-store-4.2.0.jar:4.2.0]
>         at org.apache.rocketmq.broker.processor.PullMessageProcessor.processRequu
> est(PullMessageProcessor.java:236) [rocketmq-broker-4.2.0.jar:4.2.0]
>         at org.apache.rocketmq.broker.processor.PullMessageProcessor.processRequu
> est(PullMessageProcessor.java:81) [rocketmq-broker-4.2.0.jar:4.2.0]
>         at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$1.run(NettyRR
> emotingAbstract.java:178) [rocketmq-remoting-4.2.0.jar:4.2.0]
>         at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:88
> 0) [rocketmq-remoting-4.2.0.jar:4.2.0]
> ```

i have the same problem , does it sovled? @smthing
