### ISSUE TITLE
a question about topic's consumer manager

### ISSUE THREAD

**Issue by LittleBoy18** [apache/rocketmq#2980]
I have deleted my consumer group 'jack_group', but I can still see related information in my topic 'jack_test'.I want to know where the consumer group information is stored or how topic gets consumer group information.

1、 delete consumer group 'jack_group',

![consumer_group](https://user-images.githubusercontent.com/18388649/120791858-4da69c00-c567-11eb-8089-52f99a7a7036.png)

2、 the consumer group information is still in topic 
> 
![topic](https://user-images.githubusercontent.com/18388649/120791742-28199280-c567-11eb-89b4-aefa13015714.png)

I'm confused

**Comment by maixiaohai** [comment]
there is a related pr https://github.com/apache/rocketmq/pull/2185

**Comment by LittleBoy18** [comment]
@maixiaohai thank you for you reply!
