### ISSUE TITLE
consumer restart after shutfown

### ISSUE THREAD

**Issue by dumyjob** [apache/rocketmq#2985]
For ConsumerImpl api, it's support start/shutdown operation.    Can the restart operation be support after shutdown?  why the restart operation not support ?

**Comment by francisoliverlee** [comment]
try run case : https://github.com/apache/rocketmq/blob/aaa92a2e53d773c7f1d9e9f25e41709f6948fa83/client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java#L94

**Comment by dumyjob** [comment]
I want implement operations start/shutdown and then restart for consumer, what can i do ?

**Comment by dumyjob** [comment]
I know
