### ISSUE TITLE
The number of message queues returned in MessageQueueSelector#select  is wrong

### ISSUE THREAD

**Issue by DC-Joney** [apache/rocketmq#2987]
### Java code

```

 producer.send(message, new MessageQueueSelector() {
                @Override
                public MessageQueue select(List<MessageQueue> mqs, Message msg, Object arg) {
                    System.out.println("mqs_size:" + mqs.size());
                    int index = (int) arg;
                    return mqs.get(index % mqs.size());
                }
            }, i);

```

### Console Print

```
mqs_size:4

```

### MQ Setting Info
![image](https://user-images.githubusercontent.com/16465910/121157431-25c37b00-c87c-11eb-863b-30c988086de9.png)

### Question

Why I have set the number of the message queue to 1, but 4 is returned?

**Comment by francisoliverlee** [comment]
can u show details how to reproduce it . i checked on 4.8, it turns out OK
