### ISSUE TITLE
If the latest CLIENT(4.2) support rocketMQ  SERVER 3.5.9? 

### ISSUE THREAD

**Issue by xiukongtiao** [apache/rocketmq#299]
Our rokcetMQ server is 3.5.9,  now we are tring to upgrade our client to 4.2,  we hope know:
Is it possible?
Is it risky?

Could you give us some suggestion about that,  thank you very much!

**Comment by vongosling** [comment]
The package is renamed from com.alibaba to org.apache.* since 4.0.0. Besides it, some other parts will upgrade smoothly. BTW, if you have any question about the upgrade, please resort to user email list. This is just a bug report place.
