### ISSUE TITLE
Add message tracing switch in sendMessage command of mqadmin

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#2990]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
add message tracing switch in sendMessage command of mqadmin
2. Provide any additional detail on your proposed use case for this feature.
 for using message tracing 
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
nice-to-have

**Comment by francisoliverlee** [comment]
pls add some doc about how to use it. you can check it in the PR.

**Comment by yuz10** [comment]
@francisoliverlee can I add document in operation.md?  
https://github.com/apache/rocketmq/blob/master/docs/en/operation.md
