### ISSUE TITLE
RocketMQ Async Producer sample Polish

### ISSUE THREAD

**Issue by zyh-future** [apache/rocketmq#2994]
问题地址:https://github.com/apache/rocketmq/blob/master/docs/cn/RocketMQ_Example.md#2%E5%8F%91%E9%80%81%E5%BC%82%E6%AD%A5%E6%B6%88%E6%81%AF

这里定义了一个CountDownLatch2 但是没有发现有减数操作,看到这里用是countDownLatch.await(5, TimeUnit.SECONDS);如果初衷只是休眠5秒,我想您应该会用TimeUnit.SECONDS.sleep(5);这样更简洁明了的操作吧,所以这里大胆猜测您是为了更好的满足性能,使消息发布完毕的第一时间唤醒主线程,您这里是不是缺少了减数操作呢?

**Comment by francisoliverlee** [comment]
you can try it, check result

**Comment by duhenglucky** [comment]
@916669644 非常好的建议，欢迎提PR优化一下这个example，不仅仅是文档，也包括example 里面的代码

**Comment by zongtanghu** [comment]
@zyh-future  You can put forward a pr to fix this issues, and look forward you pr!

**Comment by zplovekq** [comment]
hello , i check the doc. 
the English version http://rocketmq.apache.org/docs/simple-example/ , at the `onsuccess()` method, you can see
`countDownLatch.countDown();`
but the chinese version you see before has not , missing that line of code.
I will push a pr for it sooner...

**Comment by zyh-future** [comment]
OK, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 晚上7:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] RocketMQ Async Producer sample Polish (#2994)





 
hello , i check the doc.
 the English version http://rocketmq.apache.org/docs/simple-example/ , at the onsuccess() method, you can see
 countDownLatch.countDown();
 but the chinese version you see before has not , missing that line of code.
 I will push a pr for it sooner...

**Comment by zyh-future** [comment]
作为一个刚毕业一年的毕业生本身对提pr比较抗拒，因为总觉得大佬被我这样的小兵子提意见不好，所以只是提了个issues没下一步了。但是后面 @duhenglucky @zongtanghu  都让我提个pr。现在也被采纳合并了，太感谢你们了，这让我这个小兵感觉技术圈真的很open，这让我超级开心 ！谢谢！
