### ISSUE TITLE
Ablout public network  security 

### ISSUE THREAD

**Issue by Hisen158** [apache/rocketmq#300]
As i need  deploy Mq  in public network,such as the mq port 9876 is exposure to public networks.
Ouch! This is not safe.
Some hacker can  use  [java -jar rocketmq-console-ng-1.0.0.jar --server.port=12581 --rocketmq.config.namesrvAddr=114.*.*.*:9876  ] commnd   or other Analytical tools  destroy  my  Mq !
 Is Mq has any solution  about deploy  in  public network  ?

**Comment by lizhanhui** [comment]
Yes, it's not safe and should not deploy RocketMQ without applying security protocols. Thankfully, we have already provided transmission tier security enforcement. If you need to deploy your RocketMQ cluster in public network, you're urged to activate 2-way TLS certificate authentication.

If you need fine-grained permission check and control besides transmission encryption, you may implement your own Hook interfaces, say RPCHook interface or SendMessageHook etc. These hooks allow you to enforce checks and validations at various level.

**Comment by lizhanhui** [comment]
In case you need administrative instructions that set up a secure cluster, your welcome to write our user mailing list.
