### ISSUE TITLE
Does increasing the write queue improve write performance?

### ISSUE THREAD

**Issue by November22** [apache/rocketmq#3007]
Broker writes CommitLog sequentially. Increasing the number of write queues while increasing the number of read queues can improve the performance of consumption, but the efficiency of writing does not improve. Is my understanding correct?
——————中文如下————————
Broker 对CommitLog是顺序写，增加写队列的数量 同时 增加读队列数量 可以提升消费的性能，但是对写的效率并没有提升。我的理解正确吗？

**Comment by RongtongJin** [comment]
基本正确，但队列数增加并不意味着消费性能一定会提升，这还与消费客户端的数量、消费处理等相关。
