### ISSUE TITLE
broker startup fail if JAVA_HOME have space

### ISSUE THREAD

**Issue by MiluDeer** [apache/rocketmq#301]
My JAVA_HOME is D:\Program Files\Java\jdk1.8.0_101. When i run mqbroker, java fail to load main class.

I checked file  runbroker.cmd, it   miss " at line 41

**Comment by vongosling** [comment]
Thanks @MiluDeer This bug has been fixed in master

**Comment by MiluDeer** [comment]
bug still exist,  version 4.3.0
