### ISSUE TITLE
Fixed bug with batch-sent message statistics

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#3019]
1. Please describe the issue you observed:
The number of messages sent in batches is inconsistent with the actual number of messages.

2. Please tell us about your environment:
version:4.8.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
In BrokerStatsManager, msgNums defaults to 1. When sending in batches, msgNums should be msgs size.

**Comment by odbozhou** [comment]
Merged
