### ISSUE TITLE
client sdk for nodejs

### ISSUE THREAD

**Issue by rayeaster** [apache/rocketmq#302]
is there any chance for official team to provide client sdk for nodejs?

**Comment by vongosling** [comment]
Yes, A new developed SDKs are on the road, we will consider support Nodejs :-) BTW, if you have any question, please email to rocketMQ user email list.

**Comment by ilaipi** [comment]
any process for the nodejs client sdk?

**Comment by eriklynd** [comment]
Is there any update for this one?

**Comment by ifplusor** [comment]
@eriklynd see https://github.com/apache/rocketmq-client-nodejs
