### ISSUE TITLE
PutMessageDistributeTime statistics are inconsistent.

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#3023]
1. Please describe the issue you observed:
The PutMessageDistributeTime statistics result will be printed to store.log, or it can be obtained through mqadmin (sh mqadmin brokerStatus). It is found that the two statistical results are inconsistent.
![image](https://user-images.githubusercontent.com/30995057/122752479-9a0e0d80-d2c3-11eb-8002-6bb165c8f9ef.png)

After confirmation, it is found that the statistical data obtained through sh mqadmin brokerStatus is actually less than 1s.

2. Please tell us about your environment:
version:4.8.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
I will fix this question later.

**Comment by duhenglucky** [comment]
merged
