### ISSUE TITLE
-Xmn is not suggest used in G1

### ISSUE THREAD

**Issue by crazy-pizza** [apache/rocketmq#3030]
> When you evaluate and fine-tune G1 GC, keep the following recommendations in mind:
>
> Young Generation Size: Avoid explicitly setting young generation size with the -Xmn option or any or other related option such as -XX:NewRatio. Fixing the size of the young generation overrides the target pause-time goal.

rocketmq/distribution/bin/runbroker.sh sourecode
```
JAVA_OPT="${JAVA_OPT} -server -Xms8g -Xmx8g -Xmn4g"
JAVA_OPT="${JAVA_OPT} -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0"

```

**Comment by caigy** [comment]
@crazy-pizza Could you submit a PR to tune related scprits so that they are adaptive to diffent JDK version and memory?

**Comment by zongtanghu** [comment]
@zhangjidi2016 Can you submit a PR for this issues?

**Comment by zhangjidi2016** [comment]
Please help to review this PR. @zongtanghu @crazy-pizza @duhenglucky

**Comment by odbozhou** [comment]
Merged
