### ISSUE TITLE
关于SubscriptionGroupConfig.consumeBroadcastEnable

### ISSUE THREAD

**Issue by FinnCode** [apache/rocketmq#305]
你好:
       关于 SubscriptionGroupConfig.consumeBroadcastEnable ，RocketMQ为什么要使用这个字段来控制一个group的广播权限？是为了解决其他问题吗？

**Comment by vongosling** [comment]
请仔细阅读issue 模板，这里不提供客户支持，如有问题请发邮件到user 邮件列表。
