### ISSUE TITLE
rocketmq版本4.7.1，推的消费模式在哪里加限流

### ISSUE THREAD

**Issue by sunwuxiang** [apache/rocketmq#3067]
rocketmq推的消费模式是否可以加限流控制（sentinal）

虽然rocketmq的推也是拉，但是我们之前的mq都是推的消费模式，再修改起来比较麻烦，而且担心推的改成拉的之后，没有队列预期效率会降低

rocketmq推的消费模式是都支持加限流，在哪里加？

**Comment by duhenglucky** [comment]
如果非要加限流，可以参考下https://github.com/apache/rocketmq-externals/tree/master/rocketmq-sentinel

**Comment by vongosling** [comment]
@sunwuxiang Currently, the community does not support this feature natively. You are welcome to design and implement it.
