### ISSUE TITLE
A question about autoCreateSubscriptionGroup . What if the topic expanded  but the autoCreateSubscriptionGroup is false ??

### ISSUE THREAD

**Issue by Ah39** [apache/rocketmq#307]
if the broker set  autoCreateSubscriptionGroup false .That mean must create subscriptionGroup by shell ??
**But if the topic have expanded （ from A,B to A,B,C three broker ) That mean the subscriptionGroup must expand the same ( from A,B To A,B,C three Server ) ???**

**Comment by Ah39** [comment]
### topic expanded to a new Broker , the subsriptionGroup is need expanded to the same new broker too ??

**Comment by vongosling** [comment]
This is not a correct place for your question, please subscribe and email user email list.
