### ISSUE TITLE
请问提多少个pr才可以成为contributer呀，对消息队列这块很感兴趣

### ISSUE THREAD

**Issue by yglovewms** [apache/rocketmq#3071]
请问提多少个pr才可以成为contributer呀，对消息队列这块很感兴趣

**Comment by duhenglucky** [comment]
@yglovewms 合入一个就可以的，加油！！

**Comment by yglovewms** [comment]
修修补补那些算吗，还是要完整的一个功能点呀

**Comment by yglovewms** [comment]
> @yglovewms 合入一个就可以的，加油！！

修修补补那些算吗，还是要完整的一个功能点呀
