### ISSUE TITLE
创建了新文件提交pr要做什么特殊处理吗，为什么老是通不过测试

### ISSUE THREAD

**Issue by yglovewms** [apache/rocketmq#3075]
创建了新文件提交pr要做什么特殊处理吗，为什么老是通不过测试

**Comment by panzhi33** [comment]
加上开头的一段apache license 的注释

**Comment by yglovewms** [comment]
> 加上开头的一段apache license 的注释

哪一段呀

**Comment by panzhi33** [comment]
> > 加上开头的一段apache license 的注释
> 
> 哪一段呀

https://github.com/apache/rocketmq/issues/3075#issuecomment-868173959

**Comment by panzhi33** [comment]
https://github.com/apache/rocketmq/issues/3075#issuecomment-868173959
