### ISSUE TITLE
When the production environment sends delay messages, the master node will restart every other period of time

### ISSUE THREAD

**Issue by bobosmile1170556238** [apache/rocketmq#3077]
======================================
-Duser.home=/home/rocketmq -Duser.timezone=GMT+0800 -server -Xms8192M -Xmx8192M -Xmn2048M -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -verbose:gc -Xloggc:/dev/shm/mq_gc_%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=8192M -XX:-UseLargePages -XX:-UseBiasedLocking -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre/lib/ext:/home/rocketmq/rocketmq-4.8.0/bin/../lib -server -Xms10240M -Xmx10240M -Xmn4096M -cp .:/home/rocketmq/rocketmq-4.8.0/bin/../conf:
The broker[galaxy-broker-a, xx.xxx.xx.11:3032] boot success. serializeType=JSON and name server is xx.xxx.xx.11:3032;xx.xxx.xx.12:3032;xx.xxx.xx..13:3032

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f8371c2235e, pid=29, tid=0x00007f6bc8692700

JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-b01)
Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
Problematic frame:
J 3052  sun.nio.ch.EPollArrayWrapper.epollWait(JIJI)I (0 bytes) @ 0x00007f8371c2235e [0x00007f8371c22280+0xde]

Core dump written. Default location: /home/rocketmq/rocketmq-4.8.0/bin/core or core.29

An error report file with more information is saved as:
/home/rocketmq/rocketmq-4.8.0/bin/hs_err_pid29.log

If you would like to submit a bug report, please visit:
https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=java-1.8.0-openjdk

/home/rocketmq/rocketmq-4.8.0/bin/runbroker.sh: line 158:    29 Aborted                 (core dumped) $JAVA ${JAVA_OPT} $@

**Comment by francisoliverlee** [comment]
can you leave the hs_err_pid29.log and core file ?

**Comment by toyangdon** [comment]
i meet the same problem。
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=28, tid=0x0000fffca814faa0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:44:26 UTC 2019)
# Core dump written. Default location: /root/rocketmq/broker/bin/core or core.28
#
# An error report file with more information is saved as:
# /root/rocketmq/broker/bin/hs_err_pid28.log
#
# Compiler replay data is saved as:
# /root/rocketmq/broker/bin/replay_pid28.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
Aborted (core dumped)
