### ISSUE TITLE
RocketMQ 4.2 代码版本及依赖问题

### ISSUE THREAD

**Issue by Antergone** [apache/rocketmq#308]
# Bug Report

## Env
- CentOS 7 64bit
- JDK1.8
- RocketMQ 4.2 Release
## 问题复现步骤

1. 下载Apache RocketMQ源码和Binary包
http://rocketmq.apache.org/release_notes/release-notes-4.2.0/

2. 启动RocketMQ和RocketMQ Console
版本错误: V4_2_0_SNAPSHOT 
观察到`Github`已经修改为Release版本，但`Apache`依然是`SNAPSHOT`

3. 从4.2开始 RocketMQ Binary 依赖问题
Jar包: `netty-tcnative-1.1.33.Fork22-osx-x86_64`
如果是Linux/Windows环境是否应该为对应arch的包？能否提供多个系统的jar包，在启动shell里动态替换, 自编译不是长久之计。

**Comment by lizhanhui** [comment]
This indeed is a distribution issue. As explained in the netty-tcnative project page [here](https://netty.io/wiki/forked-tomcat-native.html), we'd better choose the static linked boring-ssl which contains multiple 64bit native libraries. 

[This commit](https://github.com/apache/rocketmq/commit/07b5858ea896155509209bb8ec76f284bcf6f192) resolves this issue.
