### ISSUE TITLE
There is a repeated build error in the construction process of the consumption queue and index

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#3086]
1. Please describe the issue you observed:
If DuplicationEnable is true, repeated construction is allowed, so there is no need to judge that reputFromOffset is greater than comfirmOffset.
If DuplicationEnable is false, repeated construction is not allowed, so it is necessary to judge whether reputFromOffset is less than comfirmOffset.
![image](https://user-images.githubusercontent.com/30995057/123376149-94af0c80-d5bc-11eb-8dec-0b68b209d332.png)

2. Same as above.
![image](https://user-images.githubusercontent.com/30995057/123376264-cc1db900-d5bc-11eb-81e2-697c1f938821.png)

2. Please tell us about your environment:
- RocketMQ 4.8.0

**Comment by francisoliverlee** [comment]
if DuplicationEnable is true, 
- no judge : maybe a lot of reput io would do, that's a resource waste 
- do judge : no waste
