### ISSUE TITLE
The broker listen port is fixed to 10911

### ISSUE THREAD

**Issue by aiooly** [apache/rocketmq#309]
https://github.com/apache/rocketmq/blob/a8ef6d61149457088e55d9c260d7e5d5f5b1dd3a/broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java#L107

how to change the listenPort when start a broker?

**Comment by aiooly** [comment]
sorry i found how to config it!

**Comment by xgj1988** [comment]
@aiooly  how to config it .

**Comment by aiooly** [comment]
@xgj1988  you can change the config via broker.conf
```
...
listenPort=11911
...
```
Below code will mix the config
https://github.com/apache/rocketmq/blob/a8ef6d61149457088e55d9c260d7e5d5f5b1dd3a/broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java#L125
