### ISSUE TITLE
How long will the code be merged after creating a pr？And will the reason be given if the pr is rejected?

### ISSUE THREAD

**Issue by yglovewms** [apache/rocketmq#3093]
How long will the code be merged after creating a pr？And will the reason be given if the pr is rejected?

**Comment by francisoliverlee** [comment]
- 1. most of us is parttime,  difficult to give out a accuracy when-to-merge
- 2. yes

**Comment by yglovewms** [comment]
> 
> 
>     * 1. most of us is parttime,  difficult to give out a accuracy when-to-merge
> 
>     * 1. yes

thanks

**Comment by ltamber** [comment]
Do you have any other question, or should we close this issue now ?  @yglovewms
