### ISSUE TITLE
How to delete the SubscriptionGroup？

### ISSUE THREAD

**Issue by lanyuange** [apache/rocketmq#3094]
![image](https://user-images.githubusercontent.com/19629949/123567772-813ab600-d7f5-11eb-9091-39f6c89c707b.png)

**Comment by RongtongJin** [comment]
Use admin tool by deleteSubGroup command, you can refer to https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md

**Comment by trdmm** [comment]
> Use admin tool by deleteSubGroup command, you can refer to https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md

Not work.
In stand-alone mode,excute below common:
`./mqadmin deleteSubGroup -n localhost:9876 -g data-adapter -b localhost:10911 -c DefaultCluster`
Return:
`delete subscription group [data-adapter] from broker [localhost:10911] success.`
But, excute `./mqadmin statsAll -n localhost:9876` ,the column "**#Consumer Group**" can still see it.

**Comment by maixiaohai** [comment]
> > Use admin tool by deleteSubGroup command, you can refer to https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
> 
> Not work.
> In stand-alone mode,excute below common:
> `./mqadmin deleteSubGroup -n localhost:9876 -g data-adapter -b localhost:10911 -c DefaultCluster`
> Return:
> `delete subscription group [data-adapter] from broker [localhost:10911] success.`
> But, excute `./mqadmin statsAll -n localhost:9876` ,the column "**#Consumer Group**" can still see it.

If your related consumer  closed？

**Comment by lanyuange** [comment]
How can it be solved? Alarm due to prometheus monitoring delay

**Comment by Gui052** [comment]
> Hi bro, did you solve this problem？

**Comment by Gui052** [comment]
> 

Hi bro, did you solve this problem?
