### ISSUE TITLE
How to deal with rocketmq message accumulation and message delay

### ISSUE THREAD

**Issue by lanyuange** [apache/rocketmq#3095]

**Comment by codersfarm** [comment]
In kafka use  "time wheel".  Set delay message in time wheel and shedule scan it , then send

**Comment by lanyuange** [comment]
I don't understand

**Comment by lanyuange** [comment]
I deleted the subscription group, but the delayed message still exists
![image](https://user-images.githubusercontent.com/19629949/123724963-d511d180-d8bf-11eb-89c2-0e7f71c82f5a.png)

**Comment by codersfarm** [comment]
Delay messages were sent to the special default  topic . Scheduled thread scan the topic , if time arrived , the thread send message to the "real-time" topic. Only delete the subscripton goup, cannot delete the delay message.

**Comment by ltamber** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list is [address](https://rocketmq.apache.org/about/contact).

**Comment by odbozhou** [comment]
1. Increase the number of consumer applications (same consumer group)
2. Optimize the consumption process
3. Increase consumption thread
4. If the message backlog is serious and the message can be lost, you can reset the consumer offset to the latest  consumer offset
5. Reduce the sending rate of the producer
