### ISSUE TITLE
Why conf/broker.conf property storePathConsumerQueue not work?

### ISSUE THREAD

**Issue by trdmm** [apache/rocketmq#3097]
RocketMQ version is 4.9.0.

[`Best Practice`](https://github.com/apache/rocketmq/blob/master/docs/cn/best_practice.md) show `storePathConsumerQueue `default is `$HOME/store/consumequeue/`

I edit it in `conf/broker.conf`, set the value to other folder which has read and write permissions.

But not work, and `$HOME/logs/rocketmqlogs/broker.log` is also not show the storePathConsumerQueue property.

I can only solve the problem in disguise by setting the storePathRootDir property.

**Comment by odbozhou** [comment]
You found a documentation bug, can you submit a pr fix
