### ISSUE TITLE
The jedgment 'writePos - lastCommittedPosition > commitLeastPages' in the method 'commit0' of class 'MappedFile' is meaningless

### ISSUE THREAD

**Issue by xiaoyaofawai** [apache/rocketmq#3099]
I think the jedgment '**writePos - lastCommittedPosition > commitLeastPages**'  in the method 'commit0' of class 'MappedFile' is meaningless in the version 4.8.0.
![image](https://user-images.githubusercontent.com/12688996/118827344-dd551500-b8ee-11eb-8a71-6772ef8435a0.png)
As you can see. 'writePos - lastCommittedPosition' represents the amount of data that has not been committed, it's in byte. but  commitLeastPages represents the least pages(OS_PAGE) should be committed. 'commitLeastPages ' has been determined in method ‘isAbleToCommit’ whether it meets the condition. so '**writePos - lastCommittedPosition > commitLeastPages**'  is meaningless, although this expression does not cause errors.
I think this expression should be 'writePos - lastCommittedPosition > 0', it used to determine whether there is uncommitted data. Do you think so?

**Comment by caigy** [comment]
I think that it should be 'writePos - lastCommittedPosition > commitLeastPages * OS_PAGE_SIZE'

**Comment by xiaoyaofawai** [comment]
I don't think so,  as you see in the method  'isAbleToCommit(final int commitLeastPages)':
![image](https://user-images.githubusercontent.com/12688996/124201317-4d6bd300-db0a-11eb-82be-cde208642a1f.png)
if this mappedFile is full, it should be commit although uncommited data is less then commitLeastPages. And this function return 'true'. But in the method 'commit0(final int commitLeastPages)', it will cause data can't be commit, if this mappedFile is full and the jedgment is changed to  'writePos - lastCommittedPosition > commitLeastPages * OS_PAGE_SIZE'. Do you think so?

**Comment by caigy** [comment]
@xiaoyaofawai You're corret. commit0() should do committing work directly, and the input parameter `commitLeastPages` is trival.

**Comment by odbozhou** [comment]
> I think the jedgment '**writePos - lastCommittedPosition > commitLeastPages**' in the method 'commit0' of class 'MappedFile' is meaningless in the version 4.8.0.
> ![image](https://user-images.githubusercontent.com/12688996/118827344-dd551500-b8ee-11eb-8a71-6772ef8435a0.png)
> As you can see. 'writePos - lastCommittedPosition' represents the amount of data that has not been committed, it's in byte. but commitLeastPages represents the least pages(OS_PAGE) should be committed. 'commitLeastPages ' has been determined in method ‘isAbleToCommit’ whether it meets the condition. so '**writePos - lastCommittedPosition > commitLeastPages**' is meaningless, although this expression does not cause errors.
> I think this expression should be 'writePos - lastCommittedPosition > 0', it used to determine whether there is uncommitted data. Do you think so?

I agree with you very much, can you submit a pr to solve this problem? @xiaoyaofawai

**Comment by xiaoyaofawai** [comment]
@odbozhou ok

**Comment by odbozhou** [comment]
merged
