### ISSUE TITLE
sql98 cannot support at rocketmq 4.2.0

### ISSUE THREAD

**Issue by xgj1988** [apache/rocketmq#310]
There is a error . Exception in thread "main" org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: The broker does not support consumer to filter message by SQL92

But I see the code source,I cannot set  enablePropertyFilter = true in broker.conf 。There is not  API to modify the property .

**Comment by xgj1988** [comment]
@dominicqi  是这样配置撒。。
 在broker.conf里面增加  enablePropertyFilter = true  ，true 应该是大小写都如所谓撒。（应该是broker.conf里面加吧。。中间有空格吧）。其实关键是我看他的源代码，BrokerConfig.java 里面 调用setPropertyFilter地方木有啊（只有 IntegrationTestBase 这里面调用了。）。

**Comment by dominicqi** [comment]
@xgj1988 
`  MixAll.properties2Object(properties, brokerConfig);`
你可以看下BrokerStartup.java中的启动流程。这部分配置是通过反射实现的.

**Comment by vsair** [comment]
Hi, you could add `enablePropertyFilter=true` to broker's config file, or you could use tool `mqadmin` to update this property dynamic.
