### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by ighack** [apache/rocketmq#3103]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

nohup sh bin/mqbroker -n 10.3.87.24:9876;10.3.87.25:9876 -c conf/2m-2s-sync/broker-a.properties &

I get "-bash: 10.3.87.27:9876: command not found"

I only can run nohup sh bin/mqbroker -n 10.3.87.24:9876 -c conf/2m-2s-sync/broker-a.properties &

2. Please tell us about your environment:

CentOS 7.8

**Comment by caigy** [comment]
When the shell sees a semicolon (;) on a command line, it's treated as a command separator, you should try to put it in single quotes, like `nohup sh bin/mqbroker -n '10.3.87.24:9876;10.3.87.25:9876' -c conf/2m-2s-sync/broker-a.properties &`
