### ISSUE TITLE
对于顺序消费的疑问

### ISSUE THREAD

**Issue by SpriderMan** [apache/rocketmq#3114]
例如顺序消费也是多线程处理，对于同一个topic 同一个队列，如果第二次的响应比第一次的请求响应更快的话，即使锁定具体队列，也是第二次的响应结果先消费，那也做不到顺序消费了吧？

![image](https://user-images.githubusercontent.com/18304842/124050721-b04b6480-da4d-11eb-9c1c-a9fde94ef27d.png)
![image](https://user-images.githubusercontent.com/18304842/124050729-b5a8af00-da4d-11eb-93c0-42c4d7ec2565.png)

**Comment by duhenglucky** [comment]
顺序消息是单线程的，应用消费逻辑层面也要保证能够顺序消息提交

**Comment by your-boy** [comment]
> 顺序消息是单线程的，应用消费逻辑层面也要保证能够顺序消息提交

请问消费逻辑层面怎么保证能够顺序消息提交
