### ISSUE TITLE
When sending a message, it may result in uneven message to queue

### ISSUE THREAD

**Issue by kingjames223** [apache/rocketmq#3131]
Select queue when sending message,if Math. Abs() returns a negative number,it may result in uneven message to queue.
![image](https://user-images.githubusercontent.com/41317369/124576736-2cdfa800-de7f-11eb-921a-cbfd8d921b1b.png)
![image](https://user-images.githubusercontent.com/41317369/124576748-2fda9880-de7f-11eb-9415-94aac45d084f.png)

**Comment by panzhi33** [comment]
The new version has fixed this problem。
https://github.com/apache/rocketmq/pull/2785

**Comment by kingjames223** [comment]
Yes, my version is 4.8.0
