### ISSUE TITLE
When a cluster(2m-2s-async)  fails, the client thread cannot execute periodically。

### ISSUE THREAD

**Issue by ozw999** [apache/rocketmq#3138]
**前提**
使用rocketmq4.4.0版本。在双主双从集群中，我通过修改broker和namesrv的定时线程执行频率以及心跳超时时间，使得rocketmq在发生一主一从掉线时，namesrv能够在短时间内（大约10s）剔除故障的broker。

**在consumer进行rebalance时遇到的问题**
1、有概率会出现DefaultMQPushConsumerImpl.doRebalance()不会按照waitInterval(20s)执行，两次消息打印间隔>90s。我增加了打印信息，if条件始终成立。在容灾发生前和发生几分钟后，rebalance执行间隔恢复正常。
【RebalanceService】
```
    @Override
    public void run() {
        log.info(this.getServiceName() + " service started");

        while (!this.isStopped()) {
            this.waitForRunning(waitInterval);
            this.mqClientFactory.doRebalance();
        }

        log.info(this.getServiceName() + " service end");
    }
```
【DefaultMQPushConsumerImpl】
```
   @Override
    public void doRebalance() {
        if (!this.pause) {
            this.rebalanceImpl.doRebalance(this.isConsumeOrderly());
        }
    }
```
2、有概率出现MQClientInstance的单线程池定时任务未按照设定时间执行，比如updateTopicRouteInfoFromNameServer两次消息打印间隔>60s。同问题1也是在容灾前后一切正常，容灾发生时线程不执行：
【MQClientInstance】
```
private final ScheduledExecutorService scheduledExecutorService = Executors.newSingleThreadScheduledExecutor(new ThreadFactory() {
        @Override
        public Thread newThread(Runnable r) {
            return new Thread(r, "MQClientFactoryScheduledThread");
        }
    });
```
```
this.scheduledExecutorService.scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                try {
                    MQClientInstance.this.updateTopicRouteInfoFromNameServer();
                } catch (Exception e) {
                    log.error("ScheduledTask updateTopicRouteInfoFromNameServer exception", e);
                }
            }
        }, 10, this.clientConfig.getPollNameServerInterval(), TimeUnit.MILLISECONDS);
```

**Comment by ltamber** [comment]
can you use `jstack -l $pid` to dump client thread stack trace info please ?

**Comment by caigy** [comment]
Can you reproduce this problem? If so, you could dump the client thread stack for further investigation.

**Comment by ozw999** [comment]
* the client version you used (is it also 4.4.0?);
YES
* the configurations you changed;
changList ：
> * [NettyClientConfig]
`private boolean clientCloseSocketIfTimeout = true;`
> * [consumer]
>```
>consumer.setPollNameServerInterval(5000);
>consumer.setHeartbeatBrokerInterval(10000);
>```
> * and i reduce some ScheduledExecutorService period, i think this is about the server client , nothing to do with this issue.
such as :
>```
>ClientHousekeepingService.this.scanExceptionChannel();
>NamesrvController.this.routeInfoManager.scanNotActiveBroker();
>```

* how often the problem occurs
About fifty percent
