### ISSUE TITLE
The message is successfully produced, but the messages cannot be viewed or consumed

### ISSUE THREAD

**Issue by wangwei1996** [apache/rocketmq#3150]
生产者的SendStatus是SEND_OK,但是控制台查看不到该消息，消费者也消费不到

**Comment by ltamber** [comment]
@wangwei1996 please provide more information about this issue. including:
- the version of your client and server
- the configuration of your producer and consumer
- the environment you use (os, java version ...)
- the steps to reproduce this issue

**Comment by RongtongJin** [comment]
> 生产者的SendStatus是SEND_OK,但是控制台查看不到该消息，消费者也消费不到

可以用mqadmin tool根据msgId查是否存在消息。

**Comment by wangwei1996** [comment]
问题产生原因：
   在项目中配置了两个DefaultMQProducer且两个DefaultMQProducer的nameServer不一致，导致mq消息发送的位置错误。

**Comment by wangwei1996** [comment]
> 问题产生原因：
> 在项目中配置了两个DefaultMQProducer且两个DefaultMQProducer的nameServer不一致，导致mq消息发送的位置错误。配置文件如下：
> # 由Spring管理的DefaultMQProducer
> rocket-mq:
>    namesrv-addr: namesrv1
>    groupName:
>    topic:
> # 使用new的方式创建DefaultMQProducer类型的实例
> dingTalk-log:
>     nameServer: namesrv2
>     retryTimesWhenSendAsyncFailed:
>     groupName:
>     topic:

通过Debug可以发现，是MqclientFactory和clientId的关系所导致的，具体的原因可以看一下源代码
