### ISSUE TITLE
question about subscriptiongroup

### ISSUE THREAD

**Issue by LittleBoy18** [apache/rocketmq#3151]
![image](https://user-images.githubusercontent.com/18388649/125782918-bdccc00b-050a-4684-a265-13ddebe9c046.png)

A broker id will be selected when creating a consumer group.Does this mean that consumers in the consumer group only consume data on the selected broker?

**Comment by panzhi33** [comment]
no，only when you turn on slaveReadEnable and other configurations will you pull messages from the configured whichBrokerWhenConsumeSlowly and brokerId
