### ISSUE TITLE
消息推送成功，但是消费获取不到

### ISSUE THREAD

**Issue by leomond** [apache/rocketmq#3160]
rocketmq集群是两主四从，模式是SYNC_MASTER，ASYNC_FLUSH，经常出现消息推送RocketMQ成功，并返回msgId，根据返回的msgId也可以查询到消息，但是通过pull模式的客户端消费时，获取的消息队列中不存在该条消息

**Comment by panzhi33** [comment]
是不是被tag过滤了，或者检查下订阅关系是否一致。
