### ISSUE TITLE
WARN WriteSocketService - findMapedFileByOffset offset not matched, request Offset

### ISSUE THREAD

**Issue by wanghanyuLv** [apache/rocketmq#3161]
### Please describe the issue you observed:
In the storemirror.log file, there is always an error message that offset does not match. It outputs a log every second. Cause our server disk alarm.
${storePathCommitLog} directory setting from '/home/rocketmq/store'

### Please tell us about your environment:
Java: 1.8
RocketMQ: 3.5.8

### Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
 WARN WriteSocketService - findMapedFileByOffset offset not matched, request Offset: 56706266126, index: 525, mapedFileSize: 1073741824, mapedFiles count: 1, StackTrace:
    java.lang.Thread.getStackTrace(Thread.java:1589)
    com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:63)
    com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
    com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:156)
    com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:150)
    com.alibaba.rocketmq.store.DefaultMessageStore.getCommitLogData(DefaultMessageStore.java:818)
    com.alibaba.rocketmq.store.ha.HAConnection$WriteSocketService.run(HAConnection.java:334)
    java.lang.Thread.run(Thread.java:745)

**Comment by panzhi33** [comment]
是否做过主备切换呀，这个应该是从节点的存储位点已经超过了主节点的，导致同步消息一直失败

**Comment by caigy** [comment]
@wanghanyuLv 3.5.8 is too old and you can upgrade to the latest version to resolve the problem.

**Comment by yanhuahayi** [comment]
@wanghanyuLv   我也遇到了这个问题，请问您最终是怎么处理的啊，升级版本吗
