### ISSUE TITLE
add msgTraceEnable config in transaction producer benchmark

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#3162]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

add msgTraceEnable config in transaction producer benchmark

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

nice-to-have

**Comment by duhenglucky** [comment]
merged
