### ISSUE TITLE
When packaging locally, checkStyle cannot pass, resulting in an install failure

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#3164]
![image](https://user-images.githubusercontent.com/18254437/126088211-00f5c113-d698-4baf-9521-5926abf6d6ca.png)
![image](https://user-images.githubusercontent.com/18254437/126088235-d6c9987b-47c6-4e08-8dec-87b0fb6aa93e.png)

**Comment by duhenglucky** [comment]
merged
