### ISSUE TITLE
slaveReadEnable has no effect,when aclEnable=true

### ISSUE THREAD

**Issue by LittleBoy18** [apache/rocketmq#3166]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
1、deploy rocketmq 4.5.0 master-slave mode,and set aclEnable=true 
2、master broker and slave broker both create plain_acl.yml
3、use console creat consumer group,and set brokerid=1 whichBrokerWhenConsumeSlowly=1
![image](https://user-images.githubusercontent.com/18388649/126134979-99ee5f1a-6dfc-4e69-a080-bfe457b5e3a5.png)

- What did you expect to see?
can consume data from slave broker

- What did you see instead?
slave broker has error
![image](https://user-images.githubusercontent.com/18388649/126135409-9e22588a-2745-48e1-8fab-1b2f91a71a95.png)

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
i want to verification slaveReadEnable when use acl

- ...

**Comment by maixiaohai** [comment]
you can check if whitelist are added for data sync

**Comment by LittleBoy18** [comment]
@maixiaohai thank you for your reply. It may be that my docker image compiled by myself has problem. I changed the apacherocketmq/rocketmq-broker:4.5.0-alpine image of the docker hub and did not reproduce this problem. i will recompile the code and test.
