### ISSUE TITLE
How to use the dLegerPeers parameter in k8s

### ISSUE THREAD

**Issue by LittleBoy18** [apache/rocketmq#3167]
![image](https://user-images.githubusercontent.com/18388649/126269814-7c339a1e-5e48-487f-aa79-5d25950beffd.png)

1、only use node ip?
2、can any port be specified?

Has anyone deployed on k8s? Please give me some suggestions

**Comment by zhaohai1299002788** [comment]
k8s由于ip默认是动态变化的，可以固定ip+ 端口号。这个端口应该这个服务对外提供，建议使用这个默认端口。

**Comment by caigy** [comment]
You can use headless-services[https://kubernetes.io/docs/concepts/services-networking/service/#headless-services]

**Comment by duhenglucky** [comment]
https://github.com/apache/rocketmq-operator is recommended
