### ISSUE TITLE
Dledger mode broker status abnormal

### ISSUE THREAD

**Issue by LittleBoy18** [apache/rocketmq#3168]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
1、deploy rocketmq 4.8.0 use Dledger mode in k8s
![image](https://user-images.githubusercontent.com/18388649/126459070-4ad7c392-99cc-4266-868a-a267b3502440.png)
![image](https://user-images.githubusercontent.com/18388649/126459200-58b357ca-c195-460c-a68c-40e914f9af91.png)
2.broker config
![image](https://user-images.githubusercontent.com/18388649/126459756-d6d1dd9a-1220-4090-92ac-f1baab72c443.png)

3、console status
![image](https://user-images.githubusercontent.com/18388649/126459880-03f9fe98-7ece-4593-b8c3-a23b454ed2b9.png)

- What did you see instead?
broker 10.168.145.91 is both master and slave
- ...

**Comment by RongtongJin** [comment]
What is the result of executing "sh bin/mqadmin clusterList -n xxxxx:9876"?

**Comment by LittleBoy18** [comment]
@RongtongJin 
![image](https://user-images.githubusercontent.com/18388649/126462174-81dacf1d-c82f-48f3-848a-193580791242.png)

my nameserver'version is 4.1.0,not sure if it has an impact

**Comment by odbozhou** [comment]
Under what operating conditions can this problem be repeated?

**Comment by LittleBoy18** [comment]
@odbozhou 
![image](https://user-images.githubusercontent.com/18388649/126578285-a135a76d-c16e-4ff3-84f1-f7b4eb40c695.png)

only deploy  dledger rocketmq  cluster by my operator,and do nothing.Now there will be a Number of -1.I am going to check if there is a problem with my config.

**Comment by LittleBoy18** [comment]
![image](https://user-images.githubusercontent.com/18388649/126582543-a977aba2-bab6-41ba-8687-8973e1c6982c.png)
@odbozhou I found that I did not configure the broker id and broker role,now cluster is normal.But i repeate one broker both master and slave ,When I verify the master-slave switch.
my steps:
1、delete master pod
![image](https://user-images.githubusercontent.com/18388649/126582978-dfa62cd3-97bb-4ef5-80de-61ae534691eb.png)

2、console status 
![image](https://user-images.githubusercontent.com/18388649/126583119-1623b7a1-fc69-4e69-8778-8fcec9fba12b.png)

my confusion:
I observed that the broker id displayed on the console is not the same as in my config.
E.g：10.168.145.74
config broker id:
![image](https://user-images.githubusercontent.com/18388649/126583451-b3ed3cd3-15cb-4d64-973d-fb059f5f23c2.png)
console broker id:
![image](https://user-images.githubusercontent.com/18388649/126583535-5d1defe2-eeb5-4fdd-8f75-ca771ac72ce8.png)

**Comment by LittleBoy18** [comment]
I think it may be that after a slave is re-elected as the leader, the previous data is not unregistered on the nameserver
