### ISSUE TITLE
[TIMEOUT_CLEAN_QUEUE]broker busy

### ISSUE THREAD

**Issue by susonglin** [apache/rocketmq#3169]
error: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 1001ms, size of queue: 265

version: 4.5.0. Multi Master Multi Slave mode

os: centos7

brokerRole=SYNC_MASTER
flushDiskType=ASYNC_FLUSH
useReentrantLockWhenPutMessage=true
sendMessageThreadPoolNums=32
waitTimeMillsInSendQueue=1000
transientStorePoolEnable=true
transferMsgByHeap=false
warmMapedFileEnable=false

We want to upgrade rocketmq disk without stopping, And adjust the brush strategy. from SYNC_FLUSH to ASYNC_FLUSH.

We shut down the write traffic of the old cluster through wipewriteperm.

There is no exception before upgrade, but after upgrade, this exception is thrown frequently.

I'm confused

**Comment by francisoliverlee** [comment]
check some ref bellow:
https://github.com/apache/rocketmq/issues/2132
https://github.com/apache/rocketmq/issues/2471
https://www.jianshu.com/p/dd0469a326b6

**Comment by susonglin** [comment]
> 检查一些参考波纹管：
> [#2132 ](https://github.com/apache/rocketmq/issues/2132)
> [#2471 ](https://github.com/apache/rocketmq/issues/2471)
> https://www.jianshu.com/p/dd0469a326b6

thanks，I changed to these configurations, and there was no exception. I'll follow up the reason

brokerRole=SYNC_MASTER
flushDiskType=SYNC_FLUSH
useReentrantLockWhenPutMessage=true
sendMessageThreadPoolNums=32
waitTimeMillsInSendQueue=500
