### ISSUE TITLE
Isolate Broker logs when multiple Broker services are deployed on the same machine

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#3173]
In most cases, multiple broker services are deployed on the same machine, so all the related logs generated by all broker nodes are stored in the same file, such as broker.log, which can be inconvenient if we need to search through the entire log file to view a broker's logs.

we can add a folder to the front of the broker logs and place the logs generated by the same broker in the same folder to isolate the logs generated by different brokers.When a broker service has a problem, the log can be quickly found in the corresponding folder.

**Comment by francisoliverlee** [comment]
you can change broker log dir :
https://github.com/apache/rocketmq/blob/a20f31bb3de242756542c552d7212a7a40000ba4/distribution/conf/logback_broker.xml

namesrv log dir
https://github.com/apache/rocketmq/blob/master/distribution/conf/logback_namesrv.xml

**Comment by zhangjidi2016** [comment]
> you can change broker log dir :
> https://github.com/apache/rocketmq/blob/a20f31bb3de242756542c552d7212a7a40000ba4/distribution/conf/logback_broker.xml
> 
> namesrv log dir
> https://github.com/apache/rocketmq/blob/master/distribution/conf/logback_namesrv.xml

**Comment by zhangjidi2016** [comment]
Yes, for this [PR](https://github.com/apache/rocketmq/pull/3174) I have added a folder to the front of the broker log to distinguish the different brokers on the same machine. The folder name is generated based on brokerName and brokerId. Users can simply use the "sh mqbroker -c broker. Properties "command to start multiple brokers without any indication of where to save the broker logs

**Comment by odbozhou** [comment]
It is not recommended to deploy multiple brokers on one machine. It is sufficient to modify logback to test different brokers.

**Comment by zhangjidi2016** [comment]
Yes, but as a practical matter, most of them have a mixed deployment of master and slave nodes from different broker-group on the same machine. Even for testing, I think it would be cumbersome to change the logback_broker.xml every time you start the broker.
