### ISSUE TITLE
Should we sync acl config from master to slave

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#3177]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
  I created acl config using  `mqadmin updateAclConfig  -c RaftCluster -a aaaaaaaaak -s ssssssssk`
  but the command only updates master broker,  if master is changed, the acl config will be missing.
  should we add sync acl config from master to slave, or modify the command to update all brokers?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by vongosling** [comment]
Good catch~

**Comment by zongtanghu** [comment]
Good Suggestion!

**Comment by zongtanghu** [comment]
@zhangjidi2016  Can you put forward a PR to solve this issues?

**Comment by zhangjidi2016** [comment]
> @zhangjidi2016 Can you put forward a PR to solve this issues?

ok
