### ISSUE TITLE
RocketMQ deleted the topic and subscription group, but prometheus still has related alarm information

### ISSUE THREAD

**Issue by lanyuange** [apache/rocketmq#3181]
![image](https://user-images.githubusercontent.com/19629949/127088648-2a0e97ae-363c-4964-b26b-cbd63d51bbbc.png)
![image](https://user-images.githubusercontent.com/19629949/127088712-bea800ee-058a-48e3-b88a-4c2ca394b592.png)
![image](https://user-images.githubusercontent.com/19629949/127088784-e706269c-d22f-47cb-991f-d3b5944d5f5a.png)

**Comment by maixiaohai** [comment]
@lanyuange you can submit issue at https://github.com/apache/rocketmq-exporter.
and it's a bug, welcome to sumbit a pr to fix it.
