### ISSUE TITLE
There is a question about consumer？

### ISSUE THREAD

**Issue by SpriderMan** [apache/rocketmq#3189]
如果从broker拉去10条消息，但是消费的时候一次只消费5条，如果没有生产者生产消息的话，那ProcessQueue 的msgTreeMap剩下的5条消息是不是永远不会被消费？除了拉取，拥有新消息触发消息消费的地方，没有找到其他触发消费的地方。
![image](https://user-images.githubusercontent.com/18304842/127418806-133cd56e-41fa-444e-9a0d-01729c7cf059.png)

**Comment by panzhi33** [comment]
![image](https://user-images.githubusercontent.com/29321745/127439449-92c72066-5300-425a-abfe-b12112751be5.png)
你拉取到了10条消息就会把10条消息全部推送给客户端的

**Comment by SpriderMan** [comment]
> ![image](https://user-images.githubusercontent.com/29321745/127439449-92c72066-5300-425a-abfe-b12112751be5.png)
> 你拉取到了10条消息就会把10条消息全部推送给客户端的

虽然全部推给客户端，例如顺序消费，他只是一次消费了配置的消费数，剩下的是不是客户端就没办法再次消费了？
![image](https://user-images.githubusercontent.com/18304842/127443964-1af97521-9845-496d-a62d-9f14b412997f.png)

**Comment by odbozhou** [comment]
顺序消息有for循环从processQueue的treeMap中取数据。会把treeMap取完循环才会结束
![image](https://user-images.githubusercontent.com/14222167/127445129-d64df967-fc16-4db6-87a2-a3d96465fa7d.png)

**Comment by SpriderMan** [comment]
> 顺序消息有for循环从processQueue的treeMap中取数据。会把treeMap取完循环才会结束
> ![image](https://user-images.githubusercontent.com/14222167/127445129-d64df967-fc16-4db6-87a2-a3d96465fa7d.png)

好的 谢谢
