### ISSUE TITLE
RuntimeInfo commitLogDirCapacity not accurate

### ISSUE THREAD

**Issue by makabakaboom** [apache/rocketmq#3192]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

1、send message to cluster
2、df -lh in node Avail:7.7G
3、call AdminBrokerProcessor.GET_BROKER_RUNTIME_INFO return value  Free : 8.3 GiB

- What did you expect to see?

return value  Free : 7.7 GiB

- What did you see instead?

return value  Free : 8.3 GiB

2. Please tell us about your environment:

Latest environment

**Comment by RongtongJin** [comment]
Merged
