### ISSUE TITLE
what meaning of  'TOPIC_PUT_ NUMS,TOPIC_ PUT_ SIZE，SNDBCK_PUT_NUMS' in the stats.log

### ISSUE THREAD

**Issue by wuyuan0717** [apache/rocketmq#3197]
`TOPIC_PUT_ NUMS，
TOPIC_ PUT_ SIZE，
SNDBCK_PUT_NUMS，
BROKER_PUT_NUMS，
GROUP_GET_NUMS，
GROUP_GET_SIZE `
What do they mean？Is there any information to understand them？

**Comment by panzhi33** [comment]
TOPIC_PUT_ NUMS how many messages were sent for this topic
TOPIC_ PUT_ SIZE the total size of messages sent by this topic
SNDBCK_PUT_NUMS Number of messages resent after consumer failed
BROKER_PUT_NUMS The number of messages received by this broker
GROUP_GET_NUMS the total number of messages consumer by this group
GROUP_GET_SIZE   the total size of messages consumer by this group
![image](https://user-images.githubusercontent.com/29321745/127612715-006538d4-5036-4e37-b04b-df10cdeb265e.png)

**Comment by wuyuan0717** [comment]
thanks a lot , `GROUP_GET_FALL_TIME，GROUP_GET_FALL_SIZE `  What do they mean？
they are my last two statistical latitudes

**Comment by wuyuan0717** [comment]
> TOPIC_PUT_ NUMS how many messages were sent for this topic
> TOPIC_ PUT_ SIZE the total size of messages sent by this topic
> SNDBCK_PUT_NUMS Number of messages resent after consumer failed
> BROKER_PUT_NUMS The number of messages received by this broker
> GROUP_GET_NUMS the total number of messages consumer by this group
> GROUP_GET_SIZE the total size of messages consumer by this group
> ![image](https://user-images.githubusercontent.com/29321745/127612715-006538d4-5036-4e37-b04b-df10cdeb265e.png)

请问一下，GROUP_GET_FALL_TIME，GROUP_GET_FALL_SIZE ，GROUP_GET_LATENCY 这几个是什么意思呢？上面的能用中文在解释一下吗？

**Comment by wuyuan0717** [comment]
你好，感谢你在github rocketmq回复我的issue，但是赶回家使用的是英文理教的好像有偏差，麻烦你一下，在咨询下面这几个统计纬度是什么意思呀？中文的，谢谢啦
TOPIC_PUT_NUMS  
TOPIC_PUT_SIZE  
GROUP_GET_NUMS
GROUP_GET_SIZE
SNDBCK_PUT_NUMS
BROKER_PUT_NUMS
BROKER_GET_NUMS
GROUP_GET_FALL_SIZE  
GROUP_GET_FALL_TIME


On 7/30/2021 ***@***.***> wrote：

TOPIC_PUT_ NUMS how many messages were sent for this topic
TOPIC_ PUT_ SIZE the total size of messages sent by this topic
SNDBCK_PUT_NUMS Number of messages resent after consumer failed
BROKER_PUT_NUMS The number of messages received by this broker
GROUP_GET_NUMS the total number of messages consumer by this group
GROUP_GET_SIZE the total size of messages consumer by this group

**Comment by panzhi33** [comment]
TOPIC_PUT_ NUMS 当前topic发送的消息总条数
TOPIC_ PUT_ SIZE 当前topic发送消息的总大小
SNDBCK_PUT_NUMS 消费失败重发的消息的总条数
BROKER_PUT_NUMS 当前broker收到消息总条数
GROUP_GET_NUMS 当前group消费消息的总条数
GROUP_GET_SIZE 当前group消费消息的总大小
GROUP_GET_FALL_TIME 当前group拉取消息的存储时间和当前时间的差值
GROUP_GET_FALL_SIZE 当前group拉取消息的存储位置和broker最大的存储位置的差值
