### ISSUE TITLE
I have a question about consumer offset

### ISSUE THREAD

**Issue by SpriderMan** [apache/rocketmq#3198]
针对consumer group queue，如果当前本地offset是1的话，2到10都被消费了，定时将offset同步给broker，那consumer到broker拉取消息的话 是从1开始拉取，2到10还会被拉取吗？

![image](https://user-images.githubusercontent.com/18304842/127617871-07526160-5f9c-47e2-91e0-f2cb5f2e3404.png)

**Comment by panzhi33** [comment]
会的
