### ISSUE TITLE
Fix the issue of code style in client and broker modules.  

### ISSUE THREAD

**Issue by zongtanghu** [apache/rocketmq#3205]
**BUG REPORT**

1. Please describe the issue you observed:

There exists in apache rocketmq's broker and client modules.

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by duhenglucky** [comment]
merged
