### ISSUE TITLE
Leader transfer leads to repeated consumption in the dledger mode

### ISSUE THREAD

**Issue by jeffchanjunwei** [apache/rocketmq#3210]
4.8.0 dleger 集群开启preferleader功能，来回主从切换后导致消费位点进度不同步。问题重现步骤如下：

step1.  1主（node0）2从（node1和node2）搭建dledger，消息生产者和消费者同时向该集群生产和消费消息，开启preferleader配置选择node0为主；

step2. 模拟断连node0的网络，node1成为新主节点，node2为从，消息生产和消费者继续生产和发送消息；

step3. node0网络断连1d，恢复node0网络，node0成为新主，消息消费者产生“大量重复消息消费”；

产生“大量重复消息消费”的问题是否为dledger功能的bug？

**Comment by duhenglucky** [comment]
这个问题可能是客户端的bug 导致的，目前已经修复了：https://github.com/apache/rocketmq/pull/2948/files，不过也要看下raft 模式下的服务端的日志再确认一下，可以提供一下服务端的broker 相关的日志么？

**Comment by jeffchanjunwei** [comment]
> 这个问题可能是客户端的bug 导致的，目前已经修复了：[https://github.com/apache/rocketmq/pull/2948/files，不过也要看下raft](https://github.com/apache/rocketmq/pull/2948/files%EF%BC%8C%E4%B8%8D%E8%BF%87%E4%B9%9F%E8%A6%81%E7%9C%8B%E4%B8%8Braft) 模式下的服务端的日志再确认一下，可以提供一下服务端的broker 相关的日志么？

本地复现的时候服务端没有明显异常的日志，这个fix已经合并到4.9.0的版本了？

**Comment by RongtongJin** [comment]
https://github.com/apache/rocketmq/pull/2518 
如果是延迟消息或者重试消息重复，可能是该问题造成，在4.9.0修复
