### ISSUE TITLE
A question about cleanExpiredMsg?

### ISSUE THREAD

**Issue by SpriderMan** [apache/rocketmq#3211]
![image](https://user-images.githubusercontent.com/18304842/127942056-668367d4-6eda-4142-9320-42e918aa2f33.png)

如果发送失败，这个消息是不是就丢失了？

**Comment by RongtongJin** [comment]
发送失败的话不会removeMessage，直接异常被捕获，下次还是会 cleanExpiredMsg

**Comment by SpriderMan** [comment]
> 发送失败的话不会removeMessage，直接异常被捕获，下次还是会 cleanExpiredMsg

好的 3q
