### ISSUE TITLE
message not load to normal topic ,still stored in the 'SCHEDULE_TOPIC_XXXX' after 12 hours

### ISSUE THREAD

**Issue by xuxiping2014** [apache/rocketmq#3212]
**BUG REPORT**
I send a schedule message to the topic A which is set scheduled after 32min and expected the message to be consume.It  was still stored in the topic 'SCHEDULE_TOPIC_XXXX'  after 12h, not loaded to topic A.The broker service、namesrv、consumer client work well and are't been restarted. Schedule message always works well,it's first time to happened.
below is information  got from store.log
`2021-08-03 08:57:20 INFO pool-1-thread-1 -  MessageExt:MessageExt [queueId=1, storeSize=693, queueOffset=346354, sysFlag=0, bornTimestamp=1627952240718, bornHost=/17.168.16.18:26936, storeTimestamp=1627952240719, storeHost=/17.168.17.57:10911, msgId=11A8113900002A9F00000003C8C16C2A, commitLogOffset=16253021226, bodyCRC=52349613, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='SCHEDULE_TOPIC_XXXX', flag=0, properties={traceId=4cb7e5d847fdff2ff9c8ebe0d31c13cf, REAL_TOPIC=ZCY_ZEUS_AUTO_OPEN_DECRYPT_MESSAGE_prod-shanxi, KEYS=6820553202238516087, __STARTDELIVERTIME=__STARTDELIVERTIME_ZMQ, UNIQ_KEY=0A652219000149C2FAAE0C38AC4E004C, DELAY=1959, WAIT=false, TAGS=null, REAL_QID=5}, body=[**message body **], transactionId='null'}], startIndex:346355,phyOffset:16253021226,bufferSize:693`

query from the topic 'SCHEDULE_TOPIC_XXXX' at 2021-08-03 20:28 by queryMsgById
![image](https://user-images.githubusercontent.com/8576687/128116383-abb97743-35d1-4572-b2be-1cc85d185f09.png)
query from the topic 'A' at 2021-08-03 20:30 by queryMsgByUniqueKey
![image](https://user-images.githubusercontent.com/8576687/128116523-d3b71d93-b9d7-4fec-8616-33cf738dcd65.png)

version:4.5.0

**Comment by panzhi33** [comment]
你们是有改过messageDelayLevel延迟策略嘛，能延迟32分钟并且在SCHEDULE_TOPIC_XXXX的队列1里面
同时也可以看下store.log里面是否有ScheduleMessageService相关的异常日志信息

**Comment by xuxiping2014** [comment]
> 你们是有改过messageDelayLevel延迟策略嘛，能延迟32分钟并且在SCHEDULE_TOPIC_XXXX的队列1里面
> 同时也可以看下store.log里面是否有ScheduleMessageService相关的异常日志信息

是的，做过延时的改造，客户端的messageDelayLevel当成了秒来传入的。昨天晚上发送时间和调度时间都看了下，没有错误日志，告警日志也与这个不相关。
另外，你咋知道我是Chinese

**Comment by panzhi33** [comment]
> > 你们是有改过messageDelayLevel延迟策略嘛，能延迟32分钟并且在SCHEDULE_TOPIC_XXXX的队列1里面
> > 同时也可以看下store.log里面是否有ScheduleMessageService相关的异常日志信息
> 
> 是的，做过延时的改造，客户端的messageDelayLevel当成了秒来传入的。昨天晚上发送时间和调度时间都看了下，没有错误日志，告警日志也与这个不相关。
> 另外，你咋知道我是Chinese

根据msgkey也查询不到吗
你的简介里面有中文

**Comment by xuxiping2014** [comment]
> > > 你们是有改过messageDelayLevel延迟策略嘛，能延迟32分钟并且在SCHEDULE_TOPIC_XXXX的队列1里面
> > > 同时也可以看下store.log里面是否有ScheduleMessageService相关的异常日志信息
> > 
> > 
> > 是的，做过延时的改造，客户端的messageDelayLevel当成了秒来传入的。昨天晚上发送时间和调度时间都看了下，没有错误日志，告警日志也与这个不相关。
> > 另外，你咋知道我是Chinese
> 
> 根据msgkey也查询不到吗
> 你的简介里面有中文

No,I can't find the message with the  method 'queryMsgByKey' in the topic 'A'. It appeared the message to be store in the  topic 'SCHEDULE_TOPIC_XXXX' only, not loaded to the topic  'A'.

**Comment by panzhi33** [comment]
can see how many queues there are in the topic SCHEDULE_TOPIC_XXXX，and value of messageDelayLevel

**Comment by xuxiping2014** [comment]
> can see how many queues there are in the topic SCHEDULE_TOPIC_XXXX，and value of messageDelayLevel

How? I find two positions, "/opt/rocketmq-all-4.5.0-bin-release/data/config/delayOffset.json" and "/opt/rocketmq-all-4.5.0-bin-release/data/consumequeue/SCHEDULE_TOPIC_XXXX/1" are both binary files.I can't read it by "cat" directly.How can i read the queue number of the topic "SCHEDULE_TOPIC_XXXX"?
