### ISSUE TITLE
The rocketmq cluster sends messages to broker a, but broker a has no message content

### ISSUE THREAD

**Issue by authorXiao** [apache/rocketmq#3218]
bug: The rocketmq cluster sends messages to broker a, but broker a has no message content
version:4.5.2  Multi Master Multi Slave mode
The rocketmq cluster sends messages to broker a and broker B to achieve high availability

**Comment by odbozhou** [comment]
Please provide more detailed information, how to reproduce this problem?

**Comment by zhaohai1299002788** [comment]
Please confirm whether broker a is added to the cluster. And confirm whether the cluster status is normal.

**Comment by authorXiao** [comment]
> 请确认集群中是否添加了broker a。并确认集群状态是否正常。

![1628495527(1)](https://user-images.githubusercontent.com/17737254/128674814-93efdc1d-328e-4c8c-8162-0cd9ba19bbbc.png)

**Comment by authorXiao** [comment]
> Please provide more detailed information, how to reproduce this problem?

Canal connects to the rocketmq cluster mode and uses partitionhash to deliver binlog data to broker a,is not  to broker b
