### ISSUE TITLE
Batch send message optimization

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#3221]
At present, rocketmq supports sending messages in batches, but the restriction must be the same topic and sent to the same queue. There may be obstacles to some more advanced usage. For example, when implementing high-precision delayed messages, whether plug-in or built-in delayed message components, when the message needs to be reproduced at the point of arrival, the messages of multiple topics / queues cannot be processed in batch at one time, resulting in low throughput. 

Can this restriction be removed? Messages sent in a batch contain data from multiple topics and queues.

**Comment by lizhiboo** [comment]
> At present, rocketmq supports sending messages in batches, but the restriction must be the same topic and sent to the same queue. There may be obstacles to some more advanced usage. For example, when implementing high-precision delayed messages, whether plug-in or built-in delayed message components, when the message needs to be reproduced at the point of arrival, the messages of multiple topics / queues cannot be processed in batch at one time, resulting in low throughput.
> 
> Can this restriction be removed? Messages sent in a batch contain data from multiple topics and queues.

Finding topic route info is a challenge in multi topics case. If these topics have not been created on the same broker, it will failed.
