### ISSUE TITLE
[question] Meaning of stats.log log output

### ISSUE THREAD

**Issue by wuyuan0717** [apache/rocketmq#3222]
stats.log中的每条日志输出，例如：`2021-07-29 15:10:27 INFO - [TOPIC_PUT_SIZE] [TOPIC_ACCOUNTS_LOAN_RESULT_UAT] Stats In One Minute, SUM: 574 TPS: 9.57 AVGPT: 574.00`  这段日志是不是意味着，`一分钟`内`TOPIC_ACCOUNTS_LOAN_RESULT_UAT` 发送了`574条`消息，平均每秒发送`9.57条`消息

`TOPIC_PUT_NUMS 当前topic发送的消息总条数`：把当天日志中所有的`TOPIC_PUT_NUMS`类型的输出的`sum`相加，得到的结果是不是意味着统计的就是`当天所有topic发送的消息总条数`

`BROKER_PUT_NUMS 当前broker收到消息总条数`：把当天日志中所有的`BROKER_PUT_NUMS`类型的输出的`sum`相加，得到的结果是不是意味着统计的就是`当天这个broker收到的消息总条数`

`BROKER_GET_NUMS 当前broker消费消息总条数`：把当天日志中所有的`BROKER_GET_NUMS`类型的输出的`sum`相加，得到的结果是不是意味着统计的就是`当天这个broker消费的消息总条数`

**Comment by panzhi33** [comment]
对的。不过你需要当天所有topic发送的消息总条数的话，可以通过brokerStatus命令看下，这里面有这个数据的

**Comment by wuyuan0717** [comment]
<img width="944" alt="1628216658(1)" src="https://user-images.githubusercontent.com/14838846/128446484-dc179ef4-947f-4bc0-b701-f2d4ceea4156.png">
<img width="884" alt="1628216674(1)" src="https://user-images.githubusercontent.com/14838846/128446516-f7abfd61-db0a-4fbc-a9d4-a1a0531e739d.png">
我在`rocketmq-console 控制台`查看到昨天集群发送的消息总条数为`26317`，而通过统计stats.log中类型为`BROKER_PUT_NUMS`得到的昨天broker发送的消息总条数为`76137` ,

**Comment by panzhi33** [comment]
控制台上面的值是准确的，昨天一天的消息发送量。BROKER_PUT_NUMS你是用接口查询的嘛，如果是的话，那他是以当前时间为基础，向前推24个小时来算的。是相对的

**Comment by wuyuan0717** [comment]
> 控制台上面的值是准确的，昨天一天的消息发送量。BROKER_PUT_NUMS你是用接口查询的嘛，如果是的话，那他是以当前时间为基础，向前推24个小时来算的。是相对的

`BROKER_PUT_NUM`是`rocketmq` 中`stats.log` 日志文件里面的获取的，在stats.log日志中统计昨天的所有输出样式为`2021-07-29 15:11:27 INFO - [BROKER_PUT_NUMS] [RaftCluster] Stats In One Minute, SUM: 4 TPS: 0.07 AVGPT: 0.00`的日志，获取提前每条中`sum`值进行相加，得到的结果为`76137`这个数值

**Comment by wuyuan0717** [comment]
> 对的。不过你需要当天所有topic发送的消息总条数的话，可以通过brokerStatus命令看下，这里面有这个数据的

`BROKER_PUT_NUM`是`rocketmq` 中`stats.log` 日志文件里面的获取的，在stats.log日志中统计昨天的所有输出样式为`2021-07-29 15:11:27 INFO - [BROKER_PUT_NUMS] [RaftCluster] Stats In One Minute, SUM: 4 TPS: 0.07 AVGPT: 0.00`的日志，获取提前每条中`sum`值进行相加，得到的结果为`76137`这个数值

**Comment by panzhi33** [comment]
> > 对的。不过你需要当天所有topic发送的消息总条数的话，可以通过brokerStatus命令看下，这里面有这个数据的
> 
> `BROKER_PUT_NUM`是`rocketmq` 中`stats.log` 日志文件里面的获取的，在stats.log日志中统计昨天的所有输出样式为`2021-07-29 15:11:27 INFO - [BROKER_PUT_NUMS] [RaftCluster] Stats In One Minute, SUM: 4 TPS: 0.07 AVGPT: 0.00`的日志，获取其中每条中`sum`值进行相加，得到的结果为`76137`这个数值，现在这个统计出来的数量是错误的，那这样的话，我如何从stats.log日志中获取昨天broker接收的消息总条数呢？

你这样算的是总数呀，到目前为止发送了多少条。昨天的数据就是控制台的算法，从brokerStatus里面，得到两个值，然后相减msgPutTotalTodayMorning-msgPutTotalYesterdayMorning

**Comment by wuyuan0717** [comment]
> > > 对的。不过你需要当天所有topic发送的消息总条数的话，可以通过brokerStatus命令看下，这里面有这个数据的
> > 
> > 
> > `BROKER_PUT_NUM`是`rocketmq` 中`stats.log` 日志文件里面的获取的，在stats.log日志中统计昨天的所有输出样式为`2021-07-29 15:11:27 INFO - [BROKER_PUT_NUMS] [RaftCluster] Stats In One Minute, SUM: 4 TPS: 0.07 AVGPT: 0.00`的日志，获取其中每条中`sum`值进行相加，得到的结果为`76137`这个数值，现在这个统计出来的数量是错误的，那这样的话，我如何从stats.log日志中获取昨天broker接收的消息总条数呢？
> 
> 你这样算是错误的。昨天的数据就是控制台的算法，从brokerStatus里面，得到两个值，然后相减msgPutTotalTodayMorning-msgPutTotalYesterdayMorning

也就是从stats.log中统计出来的broker消费的数量，接收的数量都是错误的，那这样的话stats.log日志还有其他的统计纬度吗？我可以从哪个纬度来做统计从日志中统计出一天的量呢？

**Comment by panzhi33** [comment]
> > > > 对的。不过你需要当天所有topic发送的消息总条数的话，可以通过brokerStatus命令看下，这里面有这个数据的
> > > 
> > > 
> > > `BROKER_PUT_NUM`是`rocketmq` 中`stats.log` 日志文件里面的获取的，在stats.log日志中统计昨天的所有输出样式为`2021-07-29 15:11:27 INFO - [BROKER_PUT_NUMS] [RaftCluster] Stats In One Minute, SUM: 4 TPS: 0.07 AVGPT: 0.00`的日志，获取其中每条中`sum`值进行相加，得到的结果为`76137`这个数值，现在这个统计出来的数量是错误的，那这样的话，我如何从stats.log日志中获取昨天broker接收的消息总条数呢？
> > 
> > 
> > 你这样算是错误的。昨天的数据就是控制台的算法，从brokerStatus里面，得到两个值，然后相减msgPutTotalTodayMorning-msgPutTotalYesterdayMorning
> 
> 也就是从stats.log中统计出来的broker消费的数量，接收的数量都是错误的，那这样的话stats.log日志还有其他的统计维度吗？我可以从哪个维度来做统计从日志中统计出一天的量呢？是准确的数据的

stats.log的数据是正确的。截取日志时，Stats In One Minute你们有区分这个字段嘛，这个字段有三种，你们前面是不是也把Stats In One Hour和Stats In One Day也算进去了，所以导致有误差。要取一天的，直接看Stats In One Day的日志就行

**Comment by wuyuan0717** [comment]
> > > > > 对的。不过你需要当天所有topic发送的消息总条数的话，可以通过brokerStatus命令看下，这里面有这个数据的
> > > > 
> > > > 
> > > > `BROKER_PUT_NUM`是`rocketmq` 中`stats.log` 日志文件里面的获取的，在stats.log日志中统计昨天的所有输出样式为`2021-07-29 15:11:27 INFO - [BROKER_PUT_NUMS] [RaftCluster] Stats In One Minute, SUM: 4 TPS: 0.07 AVGPT: 0.00`的日志，获取其中每条中`sum`值进行相加，得到的结果为`76137`这个数值，现在这个统计出来的数量是错误的，那这样的话，我如何从stats.log日志中获取昨天broker接收的消息总条数呢？
> > > 
> > > 
> > > 你这样算是错误的。昨天的数据就是控制台的算法，从brokerStatus里面，得到两个值，然后相减msgPutTotalTodayMorning-msgPutTotalYesterdayMorning
> > 
> > 
> > 也就是从stats.log中统计出来的broker消费的数量，接收的数量都是错误的，那这样的话stats.log日志还有其他的统计维度吗？我可以从哪个维度来做统计从日志中统计出一天的量呢？是准确的数据的
> 
> stats.log的数据是正确的。截取日志时，Stats In One Minute你们有区分这个字段嘛，这个字段有三种，你们前面是不是也把Stats In One Hour和Stats In One Day也算进去了，所以导致有误差。要取一天的，直接看Stats In One Day的日志就行

恩恩，谢谢，我试一下

**Comment by wuyuan0717** [comment]
> 控制台上面的值是准确的，昨天一天的消息发送量。`BROKER_PUT_NUMS`你是用接口查询的嘛，如果是的话，那他是以当前时间为基础，过去24个小时的。是相对的
