### ISSUE TITLE
support start namesrv/broker using higher version jdk

### ISSUE THREAD

**Issue by ltamber** [apache/rocketmq#3223]
Currently we can not start broker due to Java 9 have deprecated -Djava.ext.dirs options.

**Comment by vongosling** [comment]
I think we should request the latest LTS version JDK 11, while not java9, right?

**Comment by coolc4** [comment]
if the rocketmq-4.9.0 was compiled in the openjdk-8 environment 

and it  runs in the environment of openjdk-11

the mqbroker process that comes with the example will report an exception when calling mqshutdown normally: 

java .lang.IllegalStateException: java.lang.reflect.InaccessibleObjectException:
Unable to make public void jdk.internal.ref.Cleaner.clean() accessible: module java.base does not "exports jdk.internal.ref" to unnamed module



We can shield this exception by modifying the startup parameters in runbroker.sh
Add JAVA_OPT="${JAVA_OPT} --add-exports java.base/jdk.internal.ref=ALL-UNNAMED"
[0001-fix-fixed-the-broker-example-will-report-an-exceptio.txt](https://github.com/apache/rocketmq/files/7126140/0001-fix-fixed-the-broker-example-will-report-an-exceptio.txt)

**Comment by yiding-he** [comment]
我想劝各位发布类似开源项目的时候，脚本里面不要带上一大堆的 -XX: 调优参数，这些应该交给用户自己去调整，因为你不知道用户用的是什么 JVM，你不要强行帮用户去“优化”，只要留个口子就行了。
