### ISSUE TITLE
on Dledger  community recommendation

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#3234]
In Dledger mode, the official recommended version is 4.? .
Is there an official stress test report under Dledger?

在Dledger 模式下的，官方推荐版本是4.几。
官方有  Dledger 下的压测报告吗。

**Comment by RongtongJin** [comment]
推荐最新的版本，暂时没有压测报告。

**Comment by vongosling** [comment]
The report has not opened now. IMO, there are many others who do the same thing in the community, let's call for help if anyone sees this issue.
