### ISSUE TITLE
Why is the reading time from consumerQueue O(1)

### ISSUE THREAD

**Issue by 88888-IT** [apache/rocketmq#3240]
Why is the reading time from consumerQueue O(1)

**Comment by francisoliverlee** [comment]
don't get you. can you give more informations

**Comment by xiaoyaofawai** [comment]
ConsumeQueue support read data by message index, as you see:
![image](https://user-images.githubusercontent.com/12688996/128805753-a9f1e64d-edc6-4120-96b1-c17984d901fc.png)
ConsumeQueue read data relay on MappedFileQueue, data offset can be calculated by 'startIndex' . the index of MappedFile in MappedFileQueue and the offset of data in MappedFile can be calculated by data offset.The time complexity of these processes is O(1), so the time complexity of reading data by startIndex from ConsumeQueue is O(1)

**Comment by 88888-IT** [comment]
> ConsumeQueue support read data by message index, as you see:

First of all, thank you. Then, I have a question. For example, if the consumer subscribing to the Topic is test and the Tag is one, how does he know the startIndex when he pulls the message

**Comment by 88888-IT** [comment]
> don't get you. can you give more informations

Why is the time complexity O(1) when the consumer looks for an entry in the consumeQueue?
