### ISSUE TITLE
use the StringBuilder another method can reduce impact on array copy performance

### ISSUE THREAD

**Issue by gylang** [apache/rocketmq#3243]
i think use the StringBuilder another method can reduce impact on array copy performance
![image](https://user-images.githubusercontent.com/41338363/128875256-900f6316-f17a-4957-ae7d-53ce2a8e9828.png)

**Comment by zhaohai1299002788** [comment]
Please give an example of the specific code.

**Comment by gylang** [comment]
![image](https://user-images.githubusercontent.com/41338363/128970167-20cbf379-396f-4724-9e2b-354d017b6476.png)

**Comment by lizhiboo** [comment]
@gylang  Good catch, can u submit a pr to optimize it？

**Comment by caigy** [comment]
@gylang The call to`messagePattern.substring()` is redundant, could you submit a PR to fix it?
