### ISSUE TITLE
Utils#getDiskPartitionSpaceUsedPercent could not indicate the real disk used ratio.

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#3245]
Actually some disk space is free but not usable, which cause the result is smaller than the actual value. we could use algorithm of linux 'df' to get the actual used ratio.

**Comment by RongtongJin** [comment]
Merged

**Comment by WonderMing13** [comment]
@aaron-ai What is the variable roundNum mean? Is the variable entireSpace can replace  variable totalSpace? 
I don't understand this code, can you give me some pointers?

**Comment by Git-Yang** [comment]
> @aaron-ai What is the variable roundNum mean? Is the variable entireSpace can replace variable totalSpace? I don't understand this code, can you give me some pointers?

The roundNum is used to round up.
For why not use totalSpace, you need to understand the difference between File.getFreeSpace() and File.getUsableSpace(), refer to: https://stackoverflow.com/questions/21439596/difference-between-getfreespace-and-getusablespace-of-file

**Comment by WonderMing13** [comment]
> > @aaron-ai What is the variable roundNum mean? Is the variable entireSpace can replace variable totalSpace? I don't understand this code, can you give me some pointers?
> 
> The roundNum is used to round up. For why not use totalSpace, you need to understand the difference between File.getFreeSpace() and File.getUsableSpace(), refer to: https://stackoverflow.com/questions/21439596/difference-between-getfreespace-and-getusablespace-of-file

Thank you very much for figuring it out according to your instructions.
