### ISSUE TITLE
RocketMq is currently designed to have one or more consumequeues for each topic. Why not one or more consumequeues for each topic and tag

### ISSUE THREAD

**Issue by 88888-IT** [apache/rocketmq#3250]
RocketMq is currently designed to have one or more consumequeues for each topic. Why not one or more consumequeues for each topic and tag

**Comment by 88888-IT** [comment]
> tag is decided by user, broker can not control how many tags users use. if we design consume queues by tag, that is a disaster for broker stability.

What if the user defines the tag and creates it in the broker

**Comment by ni-ze** [comment]
> > tag is decided by user, broker can not control how many tags users use. if we design consume queues by tag, that is a disaster for broker stability.
> 
> What if the user defines the tag and creates it in the broker
You can not do that. Tag is define by user when send a message  in producer.

**Comment by 88888-IT** [comment]
> What if the user defines the tag and creates it in the broker
> You can not do that. Tag is define by user when send a message in producer.

我的意思是如果生产者提前在broker中创建好tag再去使用，这个时候是不是就可以根据tag来区分consumequeue

**Comment by ni-ze** [comment]
why you need distinguish consumer queue by tag? It is topic dimension right now.

**Comment by 88888-IT** [comment]
> why you need distinguish consumer queue by tag? It is topic dimension right now.

If the consumer subscribes to the tag under the topic, the consumer needs to traverse the queue and compare the tagHashCode to fetch the item

**Comment by francisoliverlee** [comment]
interesting idea and how do you want to do this ?

**Comment by 88888-IT** [comment]
> interesting idea and how do you want to do this ?

If the producer registers the topic and tag with the broker before sending messages, the broker can create four queues for the topic and tag. Is it possible to load balance a queue when a producer sends a message and then send the message to it? I don't know if that's feasible

**Comment by caigy** [comment]
@88888-IT Do you mean 'grouping' queues by subscription relationship?  You can provide more detailed design so that more people can join the discussion.

**Comment by caigy** [comment]
If there're many tags, will performance be affected by the great number of queue files?

**Comment by Git-Yang** [comment]
> > tag is decided by user, broker can not control how many tags users use. if we design consume queues by tag, that is a disaster for broker stability.
> 
> What if the user defines the tag and creates it in the broker

Maybe you can write the required ‘topic+tag’ to a separate topic based on business needs.
