### ISSUE TITLE
the rocketmq_client.log file spent too much cache/buffer memory

### ISSUE THREAD

**Issue by zhxjdwh** [apache/rocketmq#3252]
**BUG REPORT**
the rocketmq_client.log file spent too much cache/buffer !!!!!!!!!
These log files really consume too much cache/buffer. The jvm memory usage of my container is only 500M, but the log buffer/cache of Rocketmq consumes 2G of memory.

Rocketmq_client.log occupies memory I can barely understand,
But why the log files rocketmq_client.log.1 and rocketmq_client.log.2 after rollOver also occupy so much memory, these two files have no read or write anymore

rocketmq_client日志文件实在消耗了太多cache/buffer了，我容器的jvm内存使用才500M，但是rocketmq的日志buffer/cache就消耗了2G的内存.
rocketmq_client.log占用内存我勉强还可以理解，
但是为什么rollOver后的日志文件rocketmq_client.log.1，rocketmq_client.log.2 也占用了那么多内存，这两个文件已经没有任何读写了

**1. rocketmq_client.log   100%    cached/buffered in memory
2. rocketmq_client.log.1   100%    cached/buffered in memory
3. rocketmq_client.log.2    45.9%   cached/buffered in memory**

```


[root@node135 f91415]# /usr/local/bin/vmtouch ./diff/root/logs/rocketmqlogs/rocketmq_client.log
           Files: 1
     Directories: 0
  Resident Pages: 198301/198301  774M/774M  100% 
         Elapsed: 0.03113 seconds
[root@node135 f91415]# /usr/local/bin/vmtouch ./diff/root/logs/rocketmqlogs/rocketmq_client.log.1
           Files: 1
     Directories: 0
  Resident Pages: 262145/262145  1G/1G  100%   
         Elapsed: 0.042067 seconds
[root@node135 f91415]# /usr/local/bin/vmtouch ./diff/root/logs/rocketmqlogs/rocketmq_client.log.2
           Files: 1
     Directories: 0
  Resident Pages: 120207/262145  469M/1G  45.9%
         Elapsed: 0.020819 seconds
```

```
echo 1 > /proc/sys/vm/drop_caches;
```
If I manually clear the cache, it will be back to normal, but the same problem will still occur after a long time，The cache will continue to grow without any decrease
如果我手动清除cache，那就恢复正常了，但是时间久了还是会出现同样的问题 ，cache还是会一直增长，不会有任何减少

**FEATURE REQUEST**
Reduce the buffer/cache memory usage of log files
减少log文件的buffer/cache内存占用

**Version**
docker jdk image  :   openjdk:8
rocketmq-client  :    4.3.2
os:  centos7  linux-4.4

**Comment by zhxjdwh** [comment]
@ni-ze

**Comment by zhaohai1299002788** [comment]
If it is a log file, you can write a timer to delete the old log file.

**Comment by ni-ze** [comment]
here cache/buffer has nothing to do with your jvm, it manage by os use it to to accelerate read/write. It would not affect rocketmq client work. Just ignore it.

**Comment by zhxjdwh** [comment]
@ni-ze  
I have 400 jvm processes running in k8s, and each pod that uses Rocketmq consumes 2-6 times more memory than other pods (k8s counts buffer/cache into the used memory), and excessive memory consumption leads to frequent pods Killed by k8s.
I can only adjust logLevel to ERROR, so that it consumes less memory

我有400个jvm进程运行在k8s,每个有用到rocketmq的pod都会比其他pod多消耗2-6倍的内存(k8s把buffer/cache算到已用内存里面),内存消耗过多导致pod频繁被k8s杀死。
我现在只能把logLevel调整为ERROR，这样消耗内存就会少一点
