### ISSUE TITLE
生产关闭消息轨迹无效,

### ISSUE THREAD

**Issue by Phoebus888** [apache/rocketmq#3258]
traceTopicEnable=false
traceOn=false
上面两个值我都改为false了,但是产生的主题RMQ_SYS_TRACE_TOPIC还是会产生大量消息造成集群压力负载

**Comment by pirateskipper** [comment]
Please describe the version and related environment.

**Comment by Phoebus888** [comment]
版本为V4_7_1
集群是双主双从   RMQ_SYS_TRACE_TOPIC路由到了一个节点上去,自动创建的
![image](https://user-images.githubusercontent.com/45359605/129308856-97bf3e90-ef45-41a2-8321-b485acbf041a.png)

**Comment by Phoebus888** [comment]
> Please describe the version and related environment.

现在消息轨迹产生的tps很高  影响了生产环境了

**Comment by Phoebus888** [comment]
./mqadmin updateBrokerConfig -b 10.44.1.251:11011 -k traceOn -v false   使用这个命令把所有节点都关闭了

**Comment by duhenglucky** [comment]
> ./mqadmin updateBrokerConfig -b 10.44.1.251:11011 -k traceOn -v false 使用这个命令把所有节点都关闭了

除了这个方法外，直接禁写这个topic 也可以，但是有客户端的报错

**Comment by Phoebus888** [comment]
咋禁用

**Comment by Phoebus888** [comment]
> > ./mqadmin updateBrokerConfig -b 10.44.1.251:11011 -k traceOn -v false 使用这个命令把所有节点都关闭了
> 
> 除了这个方法外，直接禁写这个话题也可以，但是有客户端的报错
咋禁用

**Comment by Phoebus888** [comment]
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
RocketMQLog:WARN Please initialize the logger system properly.
org.apache.rocketmq.tools.command.SubCommandException: UpdateTopicPermSubCommand command failed
	at org.apache.rocketmq.tools.command.topic.UpdateTopicPermSubCommand.execute(UpdateTopicPermSubCommand.java:162)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:139)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:90)
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: The topic[RMQ_SYS_TRACE_TOPIC] is conflict with system topic.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.createTopic(MQClientAPIImpl.java:295)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.createAndUpdateTopicConfig(DefaultMQAdminExtImpl.java:182)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.createAndUpdateTopicConfig(DefaultMQAdminExt.java:163)
	at org.apache.rocketmq.tools.command.topic.UpdateTopicPermSubCommand.execute(UpdateTopicPermSubCommand.java:155)
	... 2 more

这个权限修改不了啊

**Comment by duhenglucky** [comment]
> RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
> RocketMQLog:WARN Please initialize the logger system properly.
> org.apache.rocketmq.tools.command.SubCommandException: UpdateTopicPermSubCommand command failed
> at org.apache.rocketmq.tools.command.topic.UpdateTopicPermSubCommand.execute(UpdateTopicPermSubCommand.java:162)
> at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:139)
> at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:90)
> Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1 DESC: The topic[RMQ_SYS_TRACE_TOPIC] is conflict with system topic.
> For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
> at org.apache.rocketmq.client.impl.MQClientAPIImpl.createTopic(MQClientAPIImpl.java:295)
> at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.createAndUpdateTopicConfig(DefaultMQAdminExtImpl.java:182)
> at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.createAndUpdateTopicConfig(DefaultMQAdminExt.java:163)
> at org.apache.rocketmq.tools.command.topic.UpdateTopicPermSubCommand.execute(UpdateTopicPermSubCommand.java:155)
> ... 2 more
> 
> 这个权限修改不了啊
社区同学正在进行关于系统topic 权限更改是否允许放开的讨论，我个人觉得还是有必要的，另外可以提供下你的客户端版本吗？如果执行./mqadmin updateBrokerConfig -b 10.44.1.251:11011 -k traceOn -v false  不成功的话
