### ISSUE TITLE
After the Topic subscription service goes offline, the console sees that the Consumer group message DiffTotal continues to increase

### ISSUE THREAD

**Issue by dream-sir** [apache/rocketmq#3261]
![image](https://user-images.githubusercontent.com/29668781/129330592-fe8e1351-c4e4-47e7-87b5-6fd0777568e7.png)
如图，客户端下线后，并且客户端不在使用。但是消费组依然存在，并且代理者位点次序递增，差值也持续递增

**Comment by chenzlalvin** [comment]
It is reasonable for consumers to accumulate accumulated consumption after they are offline. However, when the client cancels the subscription, the relevant accumulation point data should be cleared.
