### ISSUE TITLE
Rocketmq-spring-boot-starter connection whether mq can turn off message trails

### ISSUE THREAD

**Issue by Phoebus888** [apache/rocketmq#3262]
服务端关闭消息轨迹还是会产生消息,这种方法无效,
代理里面是否可以关闭消息轨迹,不保存生产和消费的消息

**Comment by francisoliverlee** [comment]
which rocketmq-spring-boot-starter you are using, leave a github repo url here

**Comment by RongtongJin** [comment]
Same issue as https://github.com/apache/rocketmq-spring/issues/380
