### ISSUE TITLE
Use Executors to create a thread pool, there is a risk of resource exhaustion.

### ISSUE THREAD

**Issue by zhaohai666** [apache/rocketmq#3264]
Use Executors to create a thread pool, there is a risk of resource exhaustion.
![Uploading 111.jpg…]()

**Comment by zhaohai1299002788** [comment]
#3263

**Comment by ni-ze** [comment]
can not read your picture, and how to prove that is a risk.

**Comment by zhaohai1299002788** [comment]
![image](https://user-images.githubusercontent.com/33314633/129675745-9356e052-489a-4969-8e24-74a49c4d8966.png)
This way of creating a thread pool will cause resource exhaustion.

**Comment by ni-ze** [comment]
can you repeat how the resource exhaustion?

**Comment by zhaohai1299002788** [comment]
newFixedThreadPool is a fixed number of threads, using an infinite queue.

**Comment by caigy** [comment]
@zhaohai1299002788 Could you submit a PR to fix it?
