### ISSUE TITLE
we need a solution for the consumer to use filter

### ISSUE THREAD

**Issue by 970263611** [apache/rocketmq#3267]
**BUG REPORT**

1. Please describe the issue you observed:

    neither tag nor SQL can implement our scenario,And I can't find the **org.apache.rocketmq.filtersrv.filtersrvstartup** class in rocketmq 4.8.0

2. Please tell us about your environment:

        RocketMQ4.8.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

    we need a solution for the consumer to use filter,because we need to specify some consumers on the sender,Using TAG requires the receiver to modify a lot of code,The in field cannot be used dynamically in SQL.

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

     please add the lower version of filter back or provide another method to solve this problem.

**Comment by ni-ze** [comment]
4.8.0still have MessageSelector.bySql and MessageSelector.byTag, maybe you can use them. also you can create a new topic to only send messages you want, in this way, your consumer can not use any filter to select message.All messages is exactly what you want.
Filtersrvstartup would not be add in the last version.

**Comment by 970263611** [comment]
thank you for your reply,We have considered the scheme of adding new topic,But because the producer needs to maintain too many topics, so we gave up.We built our client based on the client module.Using filter can reduce the complexity of our client,It is more flexible and easier to transform.We think this is a common scheme,Therefore, we hope the official can consider adding filter again in subsequent versions

**Comment by francisoliverlee** [comment]
same scenario we met.  we made a Enhance-DefaultPushConsumer, doing your filter logic in it.
