### ISSUE TITLE
when i compile rocketmq-logging ,why it goes wrong ? 

### ISSUE THREAD

**Issue by SpriderMan** [apache/rocketmq#3270]
![image](https://user-images.githubusercontent.com/18304842/129543904-fdf6257b-8a33-4d9a-9be0-0932c58fa413.png)

大佬 帮忙看看。

**Comment by RongtongJin** [comment]
用的什么rocketmq版本以及java版本？

**Comment by SpriderMan** [comment]
> 用的什么rocketmq版本以及java版本？

rocketmq版本：release-4.9.0      java：jdk8

**Comment by RongtongJin** [comment]
> > 用的什么rocketmq版本以及java版本？
> 
> rocketmq版本：release-4.9.0 java：jdk8

我本地试了一下是可以编译通过的。也是上面的版本。

**Comment by duhenglucky** [comment]
mvn clean install 一下，或者看下你的maven 版本是多少？

**Comment by zhaohai1299002788** [comment]
You can change the maven version (such as 3.6.3), or change the remote warehouse to Alibaba Cloud.

**Comment by SpriderMan** [comment]
> mvn clean install 一下，或者看下你的maven 版本是多少？

已经解决了！
