### ISSUE TITLE
192.168.1.1:9876;192.161.2:9876 is wrong

### ISSUE THREAD

**Issue by lgd8069465** [apache/rocketmq#3275]
https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
如上启动命令是在单个NameServer情况下使用的。对于多个NameServer的集群，Broker启动命令中-n后面的地址列表用分号隔开即可，例如 192.168.1.1:9876;192.161.2:9876。
``` bash
[root@docker ~]# sh /opt/rocketmq-all-4.9.0-bin-release/bin/mqadmin clusterList -n 192.168.2.184:9876;192.168.2.15:9876;192.168.2.217:9876;192.168.2.222:9876
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
RocketMQLog:WARN Please initialize the logger system properly.
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
DefaultCluster    broker-a                0     192.168.2.184:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9079
DefaultCluster    broker-a                1     192.168.2.217:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9595
DefaultCluster    broker-b                0     192.168.2.15:10911     V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 -1.0000
DefaultCluster    broker-b                1     192.168.2.222:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.1785
-bash: 192.168.2.15:9876: command not found
-bash: 192.168.2.217:9876: command not found
-bash: 192.168.2.222:9876: command not found
[root@docker ~]#
```
command not found ?

**Comment by duhenglucky** [comment]
> https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
> 如上启动命令是在单个NameServer情况下使用的。对于多个NameServer的集群，Broker启动命令中-n后面的地址列表用分号隔开即可，例如 192.168.1.1:9876;192.161.2:9876。
> 
> ```shell
> [root@docker ~]# sh /opt/rocketmq-all-4.9.0-bin-release/bin/mqadmin clusterList -n 192.168.2.184:9876;192.168.2.15:9876;192.168.2.217:9876;192.168.2.222:9876
> RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
> RocketMQLog:WARN Please initialize the logger system properly.
> #Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
> DefaultCluster    broker-a                0     192.168.2.184:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9079
> DefaultCluster    broker-a                1     192.168.2.217:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9595
> DefaultCluster    broker-b                0     192.168.2.15:10911     V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 -1.0000
> DefaultCluster    broker-b                1     192.168.2.222:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.1785
> -bash: 192.168.2.15:9876: command not found
> -bash: 192.168.2.217:9876: command not found
> -bash: 192.168.2.222:9876: command not found
> [root@docker ~]#
> ```
> 
> command not found ?

admin tools 指定一个nameserver 就可以了，不同nameserver 的元数据是一致的，上面多个nameserver 拼接常用于producer,nameserver

**Comment by lgd8069465** [comment]
> > https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
> > 如上启动命令是在单个NameServer情况下使用的。对于多个NameServer的集群，Broker启动命令中-n后面的地址列表用分号隔开即可，例如 192.168.1.1:9876;192.161.2:9876。
> > ```shell
> > [root@docker ~]# sh /opt/rocketmq-all-4.9.0-bin-release/bin/mqadmin clusterList -n 192.168.2.184:9876;192.168.2.15:9876;192.168.2.217:9876;192.168.2.222:9876
> > RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
> > RocketMQLog:WARN Please initialize the logger system properly.
> > #Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
> > DefaultCluster    broker-a                0     192.168.2.184:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9079
> > DefaultCluster    broker-a                1     192.168.2.217:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9595
> > DefaultCluster    broker-b                0     192.168.2.15:10911     V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 -1.0000
> > DefaultCluster    broker-b                1     192.168.2.222:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.1785
> > -bash: 192.168.2.15:9876: command not found
> > -bash: 192.168.2.217:9876: command not found
> > -bash: 192.168.2.222:9876: command not found
> > [root@docker ~]#
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > command not found ?
> 
> admin tools 指定一个nameserver 就可以了，不同nameserver 的元数据是一致的，上面多个nameserver 拼接常用于producer,nameserver

一个nameserver宕机了是不是代表全完了？

**Comment by duhenglucky** [comment]
> > > https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
> > > 如上启动命令是在单个NameServer情况下使用的。对于多个NameServer的集群，Broker启动命令中-n后面的地址列表用分号隔开即可，例如 192.168.1.1:9876;192.161.2:9876。
> > > ```shell
> > > [root@docker ~]# sh /opt/rocketmq-all-4.9.0-bin-release/bin/mqadmin clusterList -n 192.168.2.184:9876;192.168.2.15:9876;192.168.2.217:9876;192.168.2.222:9876
> > > RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
> > > RocketMQLog:WARN Please initialize the logger system properly.
> > > #Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
> > > DefaultCluster    broker-a                0     192.168.2.184:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9079
> > > DefaultCluster    broker-a                1     192.168.2.217:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9595
> > > DefaultCluster    broker-b                0     192.168.2.15:10911     V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 -1.0000
> > > DefaultCluster    broker-b                1     192.168.2.222:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.1785
> > > -bash: 192.168.2.15:9876: command not found
> > > -bash: 192.168.2.217:9876: command not found
> > > -bash: 192.168.2.222:9876: command not found
> > > [root@docker ~]#
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > command not found ?
> > 
> > 
> > admin tools 指定一个nameserver 就可以了，不同nameserver 的元数据是一致的，上面多个nameserver 拼接常用于producer,nameserver
> 
> 一个nameserver宕机了是不是代表全完了？

不会的，ns 是无状态的且有全量数据的，会使用活着的继续提供服务。

**Comment by lgd8069465** [comment]
> > > > https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
> > > > 如上启动命令是在单个NameServer情况下使用的。对于多个NameServer的集群，Broker启动命令中-n后面的地址列表用分号隔开即可，例如 192.168.1.1:9876;192.161.2:9876。
> > > > ```shell
> > > > [root@docker ~]# sh /opt/rocketmq-all-4.9.0-bin-release/bin/mqadmin clusterList -n 192.168.2.184:9876;192.168.2.15:9876;192.168.2.217:9876;192.168.2.222:9876
> > > > RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
> > > > RocketMQLog:WARN Please initialize the logger system properly.
> > > > #Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
> > > > DefaultCluster    broker-a                0     192.168.2.184:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9079
> > > > DefaultCluster    broker-a                1     192.168.2.217:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.9595
> > > > DefaultCluster    broker-b                0     192.168.2.15:10911     V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 -1.0000
> > > > DefaultCluster    broker-b                1     192.168.2.222:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.70 0.1785
> > > > -bash: 192.168.2.15:9876: command not found
> > > > -bash: 192.168.2.217:9876: command not found
> > > > -bash: 192.168.2.222:9876: command not found
> > > > [root@docker ~]#
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > command not found ?
> > > 
> > > 
> > > admin tools 指定一个nameserver 就可以了，不同nameserver 的元数据是一致的，上面多个nameserver 拼接常用于producer,nameserver
> > 
> > 
> > 一个nameserver宕机了是不是代表全完了？
> 
> 不会的，ns 是无状态的且有全量数据的，会使用活着的继续提供服务。

``` bash
[root@docker opt]# nohup sh /opt/rocketmq-all-4.9.0-bin-release/bin/mqbroker -n 192.168.2.184:9876;192.168.2.15:9876;192.168.2.217:9876;192.168.2.222:9876 -c /opt/rocketmq-all-4.9.0-bin-release/conf/2m-2s-sync/broker-a.properties &
nohup: ignoring input and appending output to ‘nohup.out’

[root@docker ~]# sh /opt/rocketmq-all-4.9.0-bin-release/bin/mqadmin clusterList -n 192.168.2.184:9876
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
RocketMQLog:WARN Please initialize the logger system properly.
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
DefaultCluster    deploy                  0     192.168.2.222:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.82 0.1785
DefaultCluster    docker                  0     192.168.2.184:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.82 0.9083
DefaultCluster    kibana                  0     192.168.2.15:10911     V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.82 -1.0000
DefaultCluster    kubernetes              0     192.168.2.217:10911    V4_9_0                   0.00(0,0ms)         0.00(0,0ms)          0 452594.82 0.9595
[root@docker ~]#
[root@docker ~]# sh /opt/rocketmq-all-4.9.0-bin-release/bin/mqadmin clusterList -n 192.168.2.15:9876
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
RocketMQLog:WARN Please initialize the logger system properly.
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
[root@docker ~]#
```
NameServer只有184有信息，Broker Name也不对
