### ISSUE TITLE
OOM under the aarch64 architecture

### ISSUE THREAD

**Issue by ledefe** [apache/rocketmq#3277]
OOM is caused by too many consumerManageExecutor task

By looking at the source code, I learned that consumerManagerThreadPoolQueueCapacity has settings but is not used. As shown below.....

```java
this.consumerManagerThreadPoolQueue = new LinkedBlockingQueue<Runnable>(this.brokerConfig.getConsumerManagerThreadPoolQueueCapacity());
....
 this.consumerManageExecutor =
                    Executors.newFixedThreadPool(this.brokerConfig.getConsumerManageThreadPoolNums(), new ThreadFactoryImpl(
                            "ConsumerManageThread_"));
````

 I want to know why unbounded queues are used .Is there any special design?

By the way, this problem occurs under the aarch64 architecture. There is no such problem under AMD architecture.

JVM:

```java
-XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -verbose:gc -Xloggc:/dev/shm/mq_gc_%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=1073741824 -XX:-UseLargePages -XX:-UseBiasedLocking -Djava.ext.dirs=/opt/jre/jre/lib/ext:/opt/rocketmq/bin/../lib -Xms2g -Xmx2g -Xmn1g -Drocketmq.broker.rebalance.lockMaxLiveTime=7000 -cp .:/opt/rocketmq/bin/../conf: org.apache.rocketmq.broker.BrokerStartup -c /opt/rocketmq/conf/broker.conf
```

**Comment by francisoliverlee** [comment]
oom log pls

**Comment by ledefe** [comment]
UPDATE_CONSUMER_OFFSET request is very much.

**Comment by ni-ze** [comment]
> UPDATE_CONSUMER_OFFSET request is very much.
are you sure it's UPDATE_CONSUMER_OFFSET request  cause too much task in unbounded queues, and eventually lead to OOM?

UPDATE_CONSUMER_OFFSET is send by tool mqadmin， It is almost impossible send by client duration consume message. You can check the code in version 4.9.0 release
