### ISSUE TITLE
 Producer always fails while sending first message.

### ISSUE THREAD

**Issue by loyili** [apache/rocketmq#3288]
**BUG REPORT**

1. Please describe the issue you observed:
    Producer always fails while sending first message.

2. How to reproduce it :
    Running  the official examples:
    ``
    .\bin\tools.sh  org.apache.rocketmq.example.quickstart.Producer
    ``
2. Please tell us about your environment:
- java version 1.8.0_271
- macos 10.13.1
- rocketmq 4.9.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
I noticed that there has been several issues linked to this bug: [#1113](https://github.com/apache/rocketmq/issues/1113) , [#1651](https://github.com/apache/rocketmq/issues/1651). However, i have a simple sulution to solve them. As we know, MessageClientIDSetter would call **UtilAll.getPid** in class loading, that's the main reason producer timeouts.  Actually,  **producer.start**  have already called **UtilAll.getPid** , we could cache the result to avoid duplicate calls.

```
public class UtilAll {
    .......
    .......
    final static String HOST_NAME = ManagementFactory.getRuntimeMXBean().getName(); // format: "pid@hostname"
   
    public static int getPid() {
        try {
            return Integer.parseInt(HOST_NAME.substring(0, HOST_NAME.indexOf('@')));
        } catch (Exception e) {
            return -1;
        }
    }
}
```
I have test it , and it works well.

**Comment by lizhiboo** [comment]
> **BUG REPORT**
> 
> 1. Please describe the issue you observed:
>    Producer always fails while sending first message.
> 2. How to reproduce it :
>    Running  the official examples:
>    `.\bin\tools.sh  org.apache.rocketmq.example.quickstart.Producer`
> 3. Please tell us about your environment:
> 
> * java version 1.8.0_271
> * macos 10.13.1
> * rocketmq 4.9.0
> 
> 1. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
>    I noticed that there has been several issues linked to this bug: [#1113](https://github.com/apache/rocketmq/issues/1113) , [#1651](https://github.com/apache/rocketmq/issues/1651). However, i have a simple sulution to solve them. As we know, MessageClientIDSetter would call **UtilAll.getPid** in class loading, that's the main reason producer timeouts.  Actually,  **producer.start**  have already called **UtilAll.getPid** , we could cache the result to avoid duplicate calls.
> 
> ```
> public class UtilAll {
>     .......
>     .......
>     final static String HOST_NAME = ManagementFactory.getRuntimeMXBean().getName(); // format: "pid@hostname"
>    
>     public static int getPid() {
>         try {
>             return Integer.parseInt(HOST_NAME.substring(0, HOST_NAME.indexOf('@')));
>         } catch (Exception e) {
>             return -1;
>         }
>     }
> }
> ```
> 
> I have test it , and it works well.

Is the error timeout ?

**Comment by vongosling** [comment]
https://github.com/apache/rocketmq/issues/1113 @lizhiboo

**Comment by loyili** [comment]
@vongosling Yes, below is the stack trace:
```
2021-08-24 14:31:26,182 WARN RocketmqClient - sendKernelImpl exception, resend at once, InvokeID: 8782646440420463667, RT: 5017ms, Broker: MessageQueue [topic=TopicTest, brokerName=bot.local, queueId=2]
org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendKernelImpl call timeout
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:861)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:593)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1384)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1328)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:330)
        at org.apache.rocketmq.example.quickstart.Producer.main(Producer.java:68)
```

**Comment by kim709394** [comment]
and ... how should i reslove this problem?

**Comment by yuz10** [comment]
@loyili perfect solution, could you submit a pr to resolve the problem?

**Comment by loyili** [comment]
Yes, i will submit it later.  @yuz10

**Comment by siyuzhiyue** [comment]
I still run into this issue at rocketmq 4.9.4
