### ISSUE TITLE
How should I test if the connection is available?

### ISSUE THREAD

**Issue by KevinBlandy** [apache/rocketmq#3293]
I want to determine at the beginning of the program whether the MQ service is working or not.

I constructed an error address message and called the `start()` method, but no exception was thrown and there was no hint. Everything seems to be fine.

```java
import org.apache.rocketmq.client.exception.MQClientException;
import org.apache.rocketmq.client.producer.DefaultMQProducer;

public class MQTest {
	
	public static void main(String[] args) throws MQClientException {
		
		DefaultMQProducer producer = new DefaultMQProducer("default");
		producer.setNamesrvAddr("undefinde:-1");
		
		producer.start();		
		
	}
}

```

I didn't find any other methods like `ping()`, `createConn()` either.

The current solution is to try to send a message to a Topic that does not exist and then determine if the service is available based on the exception message.

But this doesn't seem elegant enough, is there a good solution?

**Comment by maixiaohai** [comment]
you can check the client log at dir `~/logs/rocketmqlogs/rocketmq_client.log`
