### ISSUE TITLE
为什么rocketMQ默认情况下没有将一个JVM内的所有的生产者和消费者都放置在同一个MQClientInstance下？

### ISSUE THREAD

**Issue by ZJRui** [apache/rocketmq#3297]
问题描述：版本是4.3.   代码就是 创建一个Consumer一个Producer，两者都是使用了默认的属性，仅指定topic，group nameServer必要属性。 这个时候发现 consumer的clientId是  localIp@Pid@NameServerAddr ,而producer的clientId是localIp@Default@nameServerAddr。 由于clientId不同 rocketMQ内部会创建两个MQClientInstance

Q1： 为什么默认情况下 （也就是 创建consumer和Producer仅指定必要信息，其他属性信息都使用默认值）同一个JVM内的consumer和producer 没有共用同一个MQClientInstance？ 毕竟每启动一个MQClientInstance，MQClientInstance会启动一些其他定时任务与nameServer进行同步数据。

Q2：某书中 提到 “ 在一个 JVM中的所有消费者、生产者持有同一个 MQClientlnstance, MQClientlnstance 只会启动一次。” 感觉这个描述好像不太对呀

**Comment by Git-Yang** [comment]
First of all, it is recommended to use the version later than 4.7.
In version 4.7 and above, the clientId generation rules of consumer and producer are the same, which can ensure that the same MQClientInstance is used by default in the same process.

**Comment by ZJRui** [comment]
> First of all, it is recommended to use the version later than 4.7.
> In version 4.7 and above, the clientId generation rules of consumer and producer are the same, which can ensure that the same MQClientInstance is used by default in the same process.

我看了下4.8.0的代码 ，好像并不是像你说的这样。
4.8.0的代码中 对于DefaultMQPullConsumerImpl的start方法中  会判断MessageModel如果为集群模式，则将instanceName改为Pid
`   if (this.defaultMQPullConsumer.getMessageModel() == MessageModel.CLUSTERING) {
                    this.defaultMQPullConsumer.changeInstanceNameToPID();
                }

`
但是在DefaultMQProducerImpl的start方法中 ,只有当ProducerGroup为指定的group时才会将instanceName改为pid
`    if (!this.defaultMQProducer.getProducerGroup().equals(MixAll.CLIENT_INNER_PRODUCER_GROUP)) {
                    this.defaultMQProducer.changeInstanceNameToPID();
                }`

也就是说这样会导致 Consumer和Producer的InstanceName 不同，从而构建的clientId不同，最终导致创建两个MQClientInstance对象。
