### ISSUE TITLE
client 端jdk是否存在降级的可能性

### ISSUE THREAD

**Issue by qinshouzhi** [apache/rocketmq#330]
client 端jdk是否存在降级的可能性，比如降到jdk1.5或者1.6

**Comment by vongosling** [comment]
具体参考这里http://rocketmq.apache.org/dowloading/releases/。顺带说下，本模块只限bug report和new features（请仔细阅读issue模板），如果有问题咨询，请订阅官方邮件user邮件列表并提问，下不为例奥！

**Comment by vongosling** [comment]
具体参考这里http://rocketmq.apache.org/dowloading/releases/。顺带说下，本模块只限bug report和new features（请仔细阅读issue模板），如果有问题咨询，请订阅官方邮件user邮件列表并提问，下不为例奥！
