### ISSUE TITLE
indexFile need to flush?

### ISSUE THREAD

**Issue by SpriderMan** [apache/rocketmq#3301]
![image](https://user-images.githubusercontent.com/18304842/131272914-2cdf76e8-8df5-4799-a867-4f151bdfe4d0.png)

commitlog文件有flush到磁盘的操作，indexfile需要吗？

**Comment by panzhi33** [comment]
只有indexFile写满了，才会强制刷盘。其他时候，都是等待操作系统来刷的。commitlog如果不是SYNC_FLUSH，也是等待操作系统来刷的。indexfile文件就算丢失了，broker也可以通过commitlog来重建的。

**Comment by SpriderMan** [comment]
> 只有indexFile写满了，才会强制刷盘。其他时候，都是等待操作系统来刷的。commitlog如果不是SYNC_FLUSH，也是等待操作系统来刷的。indexfile文件就算丢失了，broker也可以通过commitlog来重建的。

好的 谢谢
