### ISSUE TITLE
Add rocketmq's custom span attributes to openTelemetry official specification.

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#3309]
Since openCensus and openTracing has been merged into openTelemetry, and kafka/rabbitMQ has added their custom span attributes to openTelemetry official specification.

Base on the fact above, I think rocketmq could also custom its own span attribute and contribute it to the openTelemetry official specification.

related issue: https://github.com/open-telemetry/opentelemetry-specification/issues/1900

**Comment by lizhanhui** [comment]
Good idea. Excited to see RocketMQ with tracing capabiblity.
