### ISSUE TITLE
How to migrate data to another mq cluster

### ISSUE THREAD

**Issue by lastboy1228** [apache/rocketmq#331]
First,  I sync a master broker data to a slave and stop the master. Then, I restart the slave as master and register it to a new namesvr.

Finally, when I search old message from the new cluster, it fails of  connecting to old master broker.

**Comment by lollipopjin** [comment]
With the purpose of migrating data to another cluster, you can do as what you described. If you start a consumer, it can receive messages from the new master successfully.

But if you want to printMsg by using `sh ./mqadmin queryMsgById -i {msgId}` commond, it will decode the msgId and connect to the original broker.

**Comment by vongosling** [comment]
@lastboy1228 Issue is not the right place for your question, please read issue template elaborately. If you have any question, please send to our user mail list. Note: Subscribe it before send an email.
