### ISSUE TITLE
Question about onChannelDestroy() in the RouteInfoManager

### ISSUE THREAD

**Issue by A-Zee029** [apache/rocketmq#3310]
![image](https://user-images.githubusercontent.com/52849969/131650655-e2911ac6-1150-4131-86f8-775d5510ec07.png)

In the scanNotActiveBroker(), the inactive broker record was removed in the brokerLiveTable, then call onChannelDestroy().
**But in the onChannelDestroy(), it re-get the brokerAddr according to the channel,** and it confused me.
Can anyone explain me why it do this

**Comment by RongtongJin** [comment]
![image](https://user-images.githubusercontent.com/21963954/132080601-76530ff1-1034-465c-a244-0abfe4cb4269.png)

Even if it is not found in BrokerLiveTable, remoteAddr will be used to clear the relevant data structure.

**Comment by A-Zee029** [comment]
> ![image](https://user-images.githubusercontent.com/21963954/132080601-76530ff1-1034-465c-a244-0abfe4cb4269.png)
> 
> Even if it is not found� in BrokerLiveTable, remoteAddr will be used to clear the relevant data structure.
感谢回复，但这里我不明白的是scanNotActiveBroker时已经获取到了“不活跃”的broker地址和channel，并且从brokerLiveTable中删除了，为什么还需要在onChannelDestroy中再遍历一次brokerLiveTable来获取broker的地址，而不是直接用之前已经拿到的broker地址，所以想请教下这个是基于什么考虑的，或者说在什么场景下需要再做一次这个检查

**Comment by odbozhou** [comment]
onChannelDestroy is not only used in RouteInfoManager but also called by BrokerHousekeepingService

**Comment by RongtongJin** [comment]
> > ![image](https://user-images.githubusercontent.com/21963954/132080601-76530ff1-1034-465c-a244-0abfe4cb4269.png)
> > Even if it is not found� in BrokerLiveTable, remoteAddr will be used to clear the relevant data structure.
> > 感谢回复，但这里我不明白的是scanNotActiveBroker时已经获取到了“不活跃”的broker地址和channel，并且从brokerLiveTable中删除了，为什么还需要在onChannelDestroy中再遍历一次brokerLiveTable来获取broker的地址，而不是直接用之前已经拿到的broker地址，所以想请教下这个是基于什么考虑的，或者说在什么场景下需要再做一次这个检查

遍历的时候首先是根据channel是否相等来判断是否要删除的，这里应该是其他函数也会调用。当然这部分也确实可以进行优化。
