### ISSUE TITLE
bug：In the openjdk-11 environment, the broker example will report an exception when exiting from mqshutdown normally

### ISSUE THREAD

**Issue by coolc4** [apache/rocketmq#3321]
When I use the example that comes with rocketmq, I found that if the application compiled in the openjdk-8 environment is run in the environment of openjdk-11, the mqbroker process that comes with the example will report an exception when calling mqshutdown normally: java .lang.IllegalStateException: java.lang.reflect.InaccessibleObjectException:
Unable to make public void jdk.internal.ref.Cleaner.clean() accessible: module java.base does not "exports jdk.internal.ref" to unnamed module

**Comment by coolc4** [comment]
We can shield this exception by modifying the startup parameters in runbroker.sh
Add JAVA_OPT="${JAVA_OPT} --add-exports java.base/jdk.internal.ref=ALL-UNNAMED"
[0001-fix-fixed-the-broker-example-will-report-an-exceptio.txt](https://github.com/apache/rocketmq/files/7115801/0001-fix-fixed-the-broker-example-will-report-an-exceptio.txt)

**Comment by odbozhou** [comment]
What version are you using ?

**Comment by odbozhou** [comment]
https://github.com/apache/rocketmq/issues/3223

**Comment by odbozhou** [comment]
For the support of the higher  java version, please refer to this issue（https://github.com/apache/rocketmq/issues/3223） . If you are interested, you can participate together, such as verifying or reviewing this pr

**Comment by odbozhou** [comment]
For the support of the higher java version, please refer to this issue  https://github.com/apache/rocketmq/issues/3223  . If you are interested, you can participate together, such as verifying or reviewing this pr

**Comment by coolc4** [comment]
I have compiled the rocketmq 4.9.0 in openjdk-8 env
and then it throws the exception when i try to run the broker example in openjdk-11 env
