### ISSUE TITLE
Consumer group have irrelavant messages delay.

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq#3323]
Asume topicA has many tags producing, if consumerA only subscribes <topicA, tag1>, once there is <topicA, tag2> and no consumer to consume it, then <topicA tag2> will count as a delay to consumerA in backend. It shows like:

<html>
<body>

default%consumerA | 1 | V4_5_2 | CONSUME_PASSIVELY | CLUSTERING | 0 | 1
-- | -- | -- | -- | -- | -- | --

</body>
</html>

topic: topicA
tag: tag2

default%consumerA | NOT_ONLINE | RESEND MESSAGE

**Comment by odbozhou** [comment]
The consume offset is the dimension of the consumer group, not the tag dimension

**Comment by fwhezfwhez** [comment]
@odbozhou That's the point. My consumer group is a new one, and subscribed tag is sucessfually consumed. But unsubcribed tag is still shown not consume yet. 

I mean info `not consume yet` should not be shown in this new consumer group but it shows and increase delay.

**Comment by lizhiboo** [comment]
@fwhezfwhez If new messages with tagA tagB appends continuously, it will looks wells. Is there any good solution to this problem.
