### ISSUE TITLE
send trace fail if broker set tls.server.mode=enforcing 

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#3326]
**BUG REPORT**

1. Please describe the issue you observed:
  
- What did you do (The steps to reproduce)?
 first broker set    `tls.server.mode=enforcing` to enable TLS mode, and plain-text requests are forbidden.
 and then procuder and consumer set tracing on

```
        DefaultMQProducer producer = new DefaultMQProducer("ProducerGroupName",true);
        producer.setNamesrvAddr("xxx:9876");
        producer.setUseTLS(true);
        producer.start();
        Message msg = new Message("TopicTest1",
                        "TagA",
                        "OrderID188",
                        "Hello world".getBytes(RemotingHelper.DEFAULT_CHARSET));
       SendResult sendResult = producer.send(msg);
       System.out.printf("%s%n", sendResult);
       producer.shutdown();
```

- What did you expect to see?
   message trace is sent normally using TLS mode.

- What did you see instead?
    message trace is sent fail, TLS mode of trace producer is off.

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by leikang123** [comment]
What is the error message log?
