### ISSUE TITLE
Add read permissions to a DLQ topic

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#3327]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
  
   After messages fail to consume and retry, then enter the dead-letter queue. After solving the problem on the consumer side, I want to query these dead-letter messages and resend them for consumers to consume again in rocketmq-dashboard.

- What did you expect to see?
  
   The dead-letter message was queried through %DLQ%dlq_group

- What did you see instead?

    ![image](https://user-images.githubusercontent.com/18254437/132298051-e642a0b5-96fa-4842-989c-c252e7436e74.png)

2. Please tell us about your environment:

    rocketmq：4.9.1
    rocketmq-dashboard：2.0.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by maixiaohai** [comment]
@zongtanghu @zhangjidi2016 I've submited a related issue and pr https://github.com/apache/rocketmq/issues/2436

**Comment by zongtanghu** [comment]
@maixiaohai @zhangjidi2016  Okay, then I close this issues firstly!
