### ISSUE TITLE
启动broker失败

### ISSUE THREAD

**Issue by liuqingshuai** [apache/rocketmq#3329]
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to xx.xx.xx.xx:9526 failed，
nameser已经启动成功，但是启动broker时死活连不上nameserver,broker.log日志里只报这个错误，不知道去哪里看这个问题的详细日志

**Comment by lizhiboo** [comment]
it seems namesrvaddr have not configured correctly, check namesraddr config in broker.conf.

**Comment by liuqingshuai** [comment]
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
aclEnable = true
listenPort = 9535
brokerIP1=xx.xx.xx.xx
namesrvAddr =xx.xx.xx.xx:9526
我配置的是这样的

**Comment by ltamber** [comment]
you can check if the port `9526` is listening in the namesrv use `netstat` , and check if the connection is normal in the broker machine use `telnet xx.xx.xx.xx 9526`
