### ISSUE TITLE
PullMessageService 是否可以用多个线程拉取消息？

### ISSUE THREAD

**Issue by zangyk** [apache/rocketmq#333]
PullMessageService 是否可以用多个线程拉取消息？

**Comment by vongosling** [comment]
可以。顺带说下，本模块只限bug report和new features（请仔细阅读issue模板），如果有问题咨询，请订阅官方user邮件列表并提问，下不为例奥！

**Comment by zangyk** [comment]
这种问题要发到哪个邮箱里面？ 这个issues-subscribe@rocketmq.apache.org吗？

**Comment by vongosling** [comment]
先订阅这个邮件列表，然后在发:-)

**Comment by lizhanhui** [comment]
CC from dev mailing list:
Your question is: Can PullMessageService make most of multi-thread while pulling messages from brokers?

The answer is: No multi-thread is needed. Pulling message from brokers is completely asynchronous, therefore, introducing multi-thread does not make sense here.
