### ISSUE TITLE
CONSUME_FROM_LAST_OFFSET not work for new consumer group

### ISSUE THREAD

**Issue by francisoliverlee** [apache/rocketmq#334]
![Uploading QQ截图20180608134446.png…]()
env: name srv=2, broker=2m,2s,  centos
config: CONSUME_FROM_LAST_OFFSET  is set
description:
one topic has created for a few days and produced more than 2000K messages. it has one consumer (call it A) already. when we put another new consumer (call it B)online, B don't consume as the [doc](http://rocketmq.apache.org/docs/best-practice-consumer/) said.
it consume all messages in the history.
expect: run as the doc said
 

> ConsumeFromWhere
When **a new Consumer Group is established**, it will need to decide whether it needs to consume the historical messages which had already existed in the Broker. CONSUME_FROM_LAST_OFFSET will **ignore the historical messages, and consume anything produced after that**. CONSUME_FROM_FIRST_OFFSET will consume every message existed in the Broker. You can also use CONSUME_FROM_TIMESTAMP to consume messages produced after the specified timestamp

**Comment by flackyang** [comment]
为什么新的Consumer Group  设置ConsumeFromWhere 不生效呢？
不管是CONSUME_FROM_LAST_OFFSET还是CONSUME_FROM_TIMESTAMP都会消费全部的历史消息
