### ISSUE TITLE
issue #2706 is still exists in version 4.9.1

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#3349]
This problem may not only cause the loss of messages, but also cause the master and slave to be out of sync。
Because I found that if the master lags behind the slave, the synchronization between the master and the slave fails, and the return code is still SEND_OK.

**Comment by duhenglucky** [comment]
https://github.com/apache/rocketmq/pull/2707

**Comment by ShannonDing** [comment]
@RongtongJin @zongtanghu

**Comment by iamqq23ue** [comment]
> @RongtongJin @zongtanghu

The new pull request is #3382。The code is basically unchanged, slightly adjusted according to the new version 。

**Comment by iamqq23ue** [comment]
@duhenglucky @RongtongJin @zongtanghu @francisoliverlee
Does the community have any plans to solve this issue?
