### ISSUE TITLE
how many rules do rocketmq tags have?

### ISSUE THREAD

**Issue by kobezhangjian** [apache/rocketmq#3352]
do rocketmq tags have funcing like rabbitmq
 (like    * for one word
 (          # for one or more word?

**Comment by RongtongJin** [comment]
Plz refer https://github.com/apache/rocketmq/blob/master/docs/cn/RocketMQ_Example.md#5-%E8%BF%87%E6%BB%A4%E6%B6%88%E6%81%AF%E6%A0%B7%E4%BE%8B
