### ISSUE TITLE
What is the use of lockConsume in process queue？

### ISSUE THREAD

**Issue by Mutouboy** [apache/rocketmq#3356]
看到在rebalance中removeUnnecessaryMessageQueue()方法会去竞争这把锁，竞争到锁后才会去unlock MessageQueue。
这个锁的必要性体现在哪里呢？

**Comment by RongtongJin** [comment]
顺序消息时会锁队列，保证重平衡时不会有多个consumer分配到同一个队列，并且同一个队列不会被并发消费
