### ISSUE TITLE
how to setDelayTimeLevel?

### ISSUE THREAD

**Issue by uliian** [apache/rocketmq#336]
Because I used ROCKETMQ for the first time, I was very puzzled about the setdelaytimelevel function when I used the delay function, it took a lot of time to find the solution, so I wanted to add an enum to more intuitively Setdelaytimelevel

**Comment by dongeforever** [comment]
The delay level is determined by the configuration named 'messageDelayLevel' in broker. So it is not easy to define a enum in the client side.
In fact, I am developing a new evolutional timer message. And It will show in the near future.

**Comment by vongosling** [comment]
I think the question has been well solved, close it. @uliian BTW, if you have any further question, please send email to our user email list, issue part is not a good place to answer your question, just for your bug report or new feature request.
