### ISSUE TITLE
Optimize DefaultMQProducer constructor implementation

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#3361]
DefaultMQProducer's constructor can call the overloaded constructor without repeating the implementation.

DefaultMQProducer(producerGroup, rpcHook, enableMsgTrace, customizedTraceTopic) ->DefaultMQProducer(namespace, producerGroup, rpcHook, enableMsgTrace, customizedTraceTopic) {

**Comment by RongtongJin** [comment]
Merged
