### ISSUE TITLE
nacos upgrade check result false

### ISSUE THREAD

**Issue by cielswift** [apache/rocketmq#3363]
nacos version 2.0.3

![image](https://user-images.githubusercontent.com/42295829/133925365-f442eb11-c2f0-4b32-acd1-3dd11009faf4.png)

The nacos cluster has a local area network id, which was not added by me

![image](https://user-images.githubusercontent.com/42295829/133925407-5f9cc5e1-5436-4b1a-8ff5-a24f3e77a3fc.png)

Cause the service upgrade to fail

**Comment by duhenglucky** [comment]
Rocketmq has no dependency with NACOS
