### ISSUE TITLE
about preferredLeaderId

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#3367]
If i preferredLeaderId = n1,It does work。but if n1 downtime，when n1 start up n1 still will be leader .
Where did the messages written during this time go? it is synchronize  n1.Will the message be discarded？

如果设置n1为preferredLeaderId ，当它宕机了一段时间后重启依然会变成leader。我想知道在此期间写入到新leader的消息会被正确同步到n1吗。当n1再次选为ldaer时会有全部写入的消息吗。如果一直在写入这个重新选举的过程会导致服务一段时间不可用吗

**Comment by maixiaohai** [comment]
n1重启后，不会立刻开始成为主节点，而是先会同步当前主节点的消息；当追到一个接近的位点后，会进行主节点转移
