### ISSUE TITLE
[pop consuming] Some enhancement and bugfix when test pop consuming mode

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq#3371]
**BUG REPORT**

1. Please describe the issue you observed:

- [x] #3387

```
Exception in thread "main" org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: java.lang.StackOverflowError, com.google.gson.stream.JsonWriter.beforeName(JsonWriter.java:617)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
  at org.apache.rocketmq.client.impl.MQClientAPIImpl.setMessageRequestMode(MQClientAPIImpl.java:2536)
  at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.setMessageRequestMode(DefaultMQAdminExtImpl.java:1062)
  at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.setMessageRequestMode(DefaultMQAdminExt.java:566)
  at org.apache.rocketmq.example.simple.PopPushConsumer.switchPop(PopPushConsumer.java:46)
  at org.apache.rocketmq.example.simple.PopPushConsumer.main(PopPushConsumer.java:53)
```

- [ ] **Part B** when change the consumer group mode to pop and start a consumer, we could not see detail about the pop_retry_topic on the console, only push_retry_topic display.

![image](https://user-images.githubusercontent.com/3734319/134628058-013ba408-66e9-4b98-ac68-bc2aa736245e.png)

- [ ] **Part C** messageRequestMode.json config file should be synced from master to slave in case of a new leader is elected.

- [ ] **Part D** ak & ck message nums are not measurable when writen into system shedule topic

2. Please tell us about your environment:
rmq version 4.8 deployed on DLedger mode, backport all the pop consuming patches.

3. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ShannonDing** [comment]
because of brokercontroller?

**Comment by maixiaohai** [comment]
> because of brokercontroller?

`transient` make brokerController filed not invovled into serializazion.

**Comment by maixiaohai** [comment]
Part B may be caused by following code
<img width="1050" alt="截屏2021-09-24 下午5 44 22" src="https://user-images.githubusercontent.com/3734319/134654822-c67ebfa4-0b6c-4e74-ab37-63a61ede6810.png">
@odbozhou

**Comment by odbozhou** [comment]
> Part B may be caused by following code
> <img alt="截屏2021-09-24 下午5 44 22" width="1050" src="https://user-images.githubusercontent.com/3734319/134654822-c67ebfa4-0b6c-4e74-ab37-63a61ede6810.png">
> @odbozhou

I will follow the above questions.

**Comment by odbozhou** [comment]
> > Part B may be caused by following code
> > <img alt="截屏2021-09-24 下午5 44 22" width="1050" src="https://user-images.githubusercontent.com/3734319/134654822-c67ebfa4-0b6c-4e74-ab37-63a61ede6810.png">
> > @odbozhou
> 
> I will follow the above questions.

@maixiaohai    

The retry topic processing methods of pop and push modes are completely different. The retry topic of push is consumed through client subscription. Therefore, SubscriptionData has a retry topic of push. The consumption of retry topic of pop is processed on the server side. There is a certain probability of consumption at the end, so when switching to pop mode, SubscriptionData will not have a retry topic
