### ISSUE TITLE
can we use single thread to doAppend msg to DefaultMappedFile？

### ISSUE THREAD

**Issue by BiggerBrain** [apache/rocketmq#3377]

**Comment by RongtongJin** [comment]
Although there are multiple threads doAppend msg to DefaultMappedFile, but because of putMessageLock, there is only one thread writing at the same time.

**Comment by ShannonDing** [comment]
yes, if you want, single thread works because of lock.

**Comment by BiggerBrain** [comment]
thank you very much!

**Comment by BiggerBrain** [comment]
I mean multi-threaded submission of writing tasks, the operation of writing the commit log is written by one thread
