### ISSUE TITLE
Is it risky to run with jdk 11  ?

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#3378]
I run rocket 4.9.1 with jdk 11 zgc.
No problem with simple test.Is it risky to run with jdk 11 ?

**Comment by Jason918** [comment]
As far as I know, some test case fails in JDK11. 
You can try run `mvn clean install -DskipITs` in branch "release-4.9.1"

Here is related log, run with AdoptOpenJDK 11.0.11 on mac os 10.15.7

> Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 4.67 sec <<< FAILURE! - in org.apache.rocketmq.store.BatchPutMessageTest
> testPutMessages(org.apache.rocketmq.store.BatchPutMessageTest)  Time elapsed: 4.589 sec  <<< ERROR!
> java.lang.IllegalStateException: java.lang.reflect.InaccessibleObjectException: Unable to make public void jdk.internal.ref.Cleaner.clean() accessible: module java.base does not "exports jdk.internal.ref" to unnamed module @7dc7cbad
>         at org.apache.rocketmq.store.BatchPutMessageTest.destory(BatchPutMessageTest.java:63)
> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public void jdk.internal.ref.Cleaner.clean() accessible: module java.base does not "exports jdk.internal.ref" to unnamed module @7dc7cbad
>         at org.apache.rocketmq.store.BatchPutMessageTest.destory(BatchPutMessageTest.java:63)
>

**Comment by Cczzzz** [comment]
I have run it in a test environment.

**Comment by drpmma** [comment]
rocketmq is completely compatible with jdk11, and we are already running it with jdk11 in production.

**Comment by Jason918** [comment]
> rocketmq  server is completely compatible with jdk11, and we have already run it with jdk11 in production.

Can you help run the unit test above?
I am not sure if it's my local settings causing the errors.
