### ISSUE TITLE
BUG , when role change  but not register again

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#3381]
I run rocket with 

#版本号的方式注册
forceRegister=false
#预先设定好的leader
preferredLeaderId=n0

if i kill the  leader， n0 will become again leader.

but n0's brokerId = 1,not 0.
Because role change  will not  register again 

 
![image](https://user-images.githubusercontent.com/32947555/134804262-4de63d00-8d30-41cf-88a2-a5cdee596bb2.png)

BrokerOuterAPI # 281 ，only compare topicConfigWrapper.getDataVersion.

  switch (response.getCode()) {
                                case ResponseCode.SUCCESS: {
                                    QueryDataVersionResponseHeader queryDataVersionResponseHeader =
                                        (QueryDataVersionResponseHeader) response.decodeCommandCustomHeader(QueryDataVersionResponseHeader.class);
                                    changed = queryDataVersionResponseHeader.getChanged();
                                    byte[] body = response.getBody();
                                    if (body != null) {
                                        nameServerDataVersion = DataVersion.decode(body, DataVersion.class);
                                        if (!topicConfigWrapper.getDataVersion().equals(nameServerDataVersion)) {
                                            changed = true;
                                        }
                                    }
                                    if (changed == null || changed) {
                                        changedList.add(Boolean.TRUE);
                                    }
                                }
                                default:
                                    break;
                            }

**Comment by RongtongJin** [comment]
Good catch, I think forceRegister should be forced to true in here. Could you submit a pull request to fix it？

**Comment by Cczzzz** [comment]
Maybe the version number should be increased when role change

**Comment by RongtongJin** [comment]
Merged
