### ISSUE TITLE
[statistics] SCHEDULE_TOPIC_XXXX statistics are missing SendBack messages

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#3384]
⁣Associated patch： https://github.com/apache/rocketmq/issues/3296

1. Please describe the issue you observed:
- SCHEDULE_TOPIC_XXXX statistics are missing SendBack messages

2. Please tell us about your environment:
rmq version 4.8 , backport #3302.

**Comment by odbozhou** [comment]
merged
