### ISSUE TITLE
The json-style of body in the message is illegal, because of the default settings for fastjson

### ISSUE THREAD

**Issue by Frodez** [apache/rocketmq#3389]
I have tried to implement some functions for [rocketmq-client-go](https://github.com/apache/rocketmq-client-go), and I got a illgal json-style body for the response of broker with type [TopicStatsTable](https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/admin/TopicStatsTable.java). The string converted from the body looks like this:
```
{"offsetTable":{{"brokerName":"rocketmq-broker-a","queueId":2,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":3,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":0,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":1,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":6,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":7,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":4,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":5,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0}}}
```

And the [json.Unmarshal](https://pkg.go.dev/encoding/json#Unmarshal) method reports an error:
```
invalid character '{' looking for beginning of object key string
```

Simply, the problem is the serialized key of the response should be not an object but a string. And I got that the serialization library for the [rocketmq](https://github.com/apache/rocketmq) is [fastjson](https://github.com/alibaba/fastjson), and there is a reference of this problem in the issue [1.2.58，toJSONString(Object)生成了非标准JSON](https://github.com/alibaba/fastjson/issues/2526). Someone reports that the default settings for fastjson has changed after the version 1.2.36 released, and illegal json string can be serialized. However, the [RemotingSerializable.toJson](https://github.com/apache/rocketmq/blob/fb8bc64e2a2551e76da24cb6af0fb3e5f986f8b3/remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingSerializable.java#L33) method is using the default settings.

And I can give a simple bugfix:

Previous:
```java
public static String toJson(final Object obj, boolean prettyFormat) {
    return JSON.toJSONString(obj, prettyFormat);
}
```
After:
```java
public static String toJson(final Object obj, boolean prettyFormat) {
    if (prettyFormat) {
        return JSON.toJSONString(obj, SerializerFeature.WriteNonStringKeyAsString, SerializerFeature.PrettyFormat);
    } else {
        return JSON.toJSONString(obj, SerializerFeature.WriteNonStringKeyAsString);
    }
}
```

**Comment by panzhi33** [comment]
Someone has already mentioned related pr https://github.com/apache/rocketmq/pull/3386

**Comment by liuxuzxx** [comment]
> I have tried to implement some functions for [rocketmq-client-go](https://github.com/apache/rocketmq-client-go), and I got a illgal json-style body for the response of broker with type [TopicStatsTable](https://github.com/apache/rocketmq/blob/master/common/src/main/java/org/apache/rocketmq/common/admin/TopicStatsTable.java). The string converted from the body looks like this:
> ```
> {"offsetTable":{{"brokerName":"rocketmq-broker-a","queueId":2,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":3,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":0,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":1,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":6,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":7,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":4,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0},{"brokerName":"rocketmq-broker-a","queueId":5,"topic":"test"}:{"lastUpdateTimestamp":0,"maxOffset":0,"minOffset":0}}}
> ```
> 
> And the [json.Unmarshal](https://pkg.go.dev/encoding/json#Unmarshal) method reports an error:
> ```
> invalid character '{' looking for beginning of object key string
> ```
> 
> Simply, the problem is the serialized key of the response should be not an object but a string. And I got that the serialization library for the [rocketmq](https://github.com/apache/rocketmq) is [fastjson](https://github.com/alibaba/fastjson), and there is a reference of this problem in the issue [1.2.58，toJSONString(Object)生成了非标准JSON](https://github.com/alibaba/fastjson/issues/2526). Someone reports that the default settings for fastjson has changed after the version 1.2.36 released, and illegal json string can be serialized. However, the [RemotingSerializable.toJson](https://github.com/apache/rocketmq/blob/fb8bc64e2a2551e76da24cb6af0fb3e5f986f8b3/remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingSerializable.java#L33) method is using the default settings.
> 
> And I can give a simple bugfix:
> 
> Previous:
> ```java
> public static String toJson(final Object obj, boolean prettyFormat) {
>     return JSON.toJSONString(obj, prettyFormat);
> }
> ```
> After:
> ```java
> public static String toJson(final Object obj, boolean prettyFormat) {
>     if (prettyFormat) {
>         return JSON.toJSONString(obj, SerializerFeature.WriteNonStringKeyAsString, SerializerFeature.PrettyFormat);
>     } else {
>         return JSON.toJSONString(obj, SerializerFeature.WriteNonStringKeyAsString);
>     }
> }
> ```
> 
> 

这个出现的地方有点多，获取broker信息的时候，会出现json的key是纯数字问题，或者map<复杂对象，xxx>，这种key也会产生不加双引号的情况，目前探查到三种会出现！

**Comment by liuxuzxx** [comment]
如果你在toJSON的时候，加入了SerializerFeature.WriteNonStringKeyAsString，那么你也需要在parsexxx系列方法加上这个配置，否则可能会出现问题！

**Comment by Frodez** [comment]
> 如果你在toJSON的时候，加入了SerializerFeature.WriteNonStringKeyAsString，那么你也需要在parsexxx系列方法加上这个配置，否则可能会出现问题！

Besides, I believe that it is the best solution that is fastjson deprecated and jackson imported.

**Comment by Jason918** [comment]
> Besides, I believe that it is the best solution that is fastjson deprecated and jackson imported.

IMHO, Replacing fastjson with jackson will introduce some extra problems with compatibility during upgrading.

On the other hand, as security breaches in fastjson lately does causing some painful work, maybe it's better we could provide optional json lib dependency, configurable or pluggable.
