### ISSUE TITLE
I want to participate in the development of 5.0

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#3390]
I want to participate in the development of 5.0.What should i do

**Comment by maixiaohai** [comment]
Welcome~ @Cczzzz

**Comment by zhouxinyu** [comment]
We have some discussions about the RIPs of RocketMQ 5.0, welcome subscribe to our mailing lists(https://rocketmq.apache.org/about/contact/) for more details. We are looking forward to your voice.

BTW, any kind of contributions are  welcome, such as docs, features, bug fixes, etc

**Comment by duhenglucky** [comment]
The community is planning to establish a 5.0 SIG. This SIG will not be as focused as other SIGs, but will help everyone find their areas of interest and participate in the development of 5.0. You can join the WeChat group discussion: 
![image](https://user-images.githubusercontent.com/7938968/135697036-525cf194-b335-4620-a70f-9d7b21af82ff.png)

**Comment by Cczzzz** [comment]
> 社区正计划建立一个 5.0 SIG。这个 SIG 不会像其他 SIG 那样专注，而是会帮助每个人找到自己感兴趣的领域并参与 5.0 的开发。可以加入微信群讨论： ![图片](https://user-images.githubusercontent.com/7938968/135697036-525cf194-b335-4620-a70f-9d7b21af82ff.png)

the QR code expired ，Can you resend
