### ISSUE TITLE
Probably,LatencyFaultToleranceImpl#pickOneAtLeast result isn't first one When latency items size great to 3.

### ISSUE THREAD

**Issue by soci166** [apache/rocketmq#3391]
**BUG REPORT**
Probably,LatencyFaultToleranceImpl#pickOneAtLeast result isn't first one When latency items size great to 3.
![image](https://user-images.githubusercontent.com/26709123/135385264-3569b07f-d1f4-42e2-91a7-1bdd3f8f1221.png)
![image](https://user-images.githubusercontent.com/26709123/135385449-cc83aa2a-eaf0-4868-a248-916f503d1425.png)

**Comment by panzhi33** [comment]
![image](https://user-images.githubusercontent.com/29321745/135398182-675e84fa-1a3c-4ce6-b620-1d01c4f9b04f.png)
polling algorithm, and only get from the first half，this is expected

**Comment by soci166** [comment]
![image](https://user-images.githubusercontent.com/26709123/135405686-cd33cd82-1ae0-45cd-827b-51381c524c72.png)
the earliest start time item will be last execution is expected?

**Comment by panzhi33** [comment]
![image](https://user-images.githubusercontent.com/29321745/135421089-5f7ddd9a-8fc0-4fe7-aaed-364fb3d0aeb9.png)
这个测试用例是一个个往map里面put的值的，half这个值是会变的，所以导致现在看到这个效果。this.whichItemWorst.incrementAndGet() 这个值最开始是随机的，在实际应用当中，你说的那种情况也有可能发生，

**Comment by soci166** [comment]
![image](https://user-images.githubusercontent.com/26709123/135425230-32cc29ad-a6bd-43b3-88b0-bcb2021a564c.png)

我的理解是错误重试机制在已经分配了权重的情况下应该要按照权重的顺序来执行而不应该保留这种随机性

**Comment by panzhi33** [comment]
> ![image](https://user-images.githubusercontent.com/26709123/135425230-32cc29ad-a6bd-43b3-88b0-bcb2021a564c.png)
> 
> 我的理解是错误重试机制在已经分配了权重的情况下应该要按照权重的顺序来执行而不应该保留这种随机性

只是最开始的那个值是随机的，后面就是轮询了

**Comment by soci166** [comment]
在重试量足够大而且数量变动频繁的情况下该算法没有办法保证执行的顺序

**Comment by panzhi33** [comment]
> 在重试量足够大而且数量变动频繁的情况下该算法没有办法保证执行的顺序

他是以broker来统计的，除非发生扩容缩容等一些情况，所以整个faultItemTable的数量是固定的，但是每个FaultItem里面的变量在每一次发完消息后就会更新，因此无法做到顺序。不建议打开这个策略
