### ISSUE TITLE
namesrv服务中NamesrvController保存的configuration有问题

### ISSUE THREAD

**Issue by xpyzh** [apache/rocketmq#340]
分支:master
看了下namesrv启动这部分的代码，加载顺序如下:
step1.args中解析-c参数，读取属性文件，并覆盖NamesrvConfig和NettyServerConfig类的默认属性
step2.args中解析其他参数，如果包含NamesrvConfig类中的属性，则将其覆盖
step3.根据NamesrvConfig和NettyServerConfig初始化NamesrvController类(这时候应该是最终的配置文件)
step4.用step1中读取的属性文件去覆盖NamesrvController类中的属性，保存在configuration变量中

> step4中的覆盖行为保存的其实并不是namesrv最终生效的配置。有问题的代码如下:
//todo:这个地方的覆盖了实际最终生效的配置
controller.getConfiguration().registerConfig(properties);

**Comment by vongosling** [comment]
你好，如果有问题，麻烦发到我们的用户邮件列表http://rocketmq.apache.org/about/contact/，这里只提供issue report 和new feature request。
