### ISSUE TITLE
delayOffset.json and consumerOffset were corrupted when windows system crashes unexpectedly

### ISSUE THREAD

**Issue by charlieDJ** [apache/rocketmq#3401]
OS: Windows Server 2008 R2
RocketMQ release version: 4.9.1

This happens from time to time. I restart my PC and I can't start the broker after windows system crashes unexpectedly. Then I checked the broker logs. It shows that delayOffset.json and consumerOffset.json were corrupted. Human cannot read the text. Then I delete all the characters and rewrite the json data. I restart the broker, it works. 

But all the offsets were lost, the messages were recomsumed. I'm not sure whethere is it a bug. The problem haunts me for a long time. Can you provide a good reason to explain it.

**Comment by panzhi33** [comment]
The json data format is wrong, is there less closing brace?

**Comment by charlieDJ** [comment]
> The json data format is wrong, is there less closing brace?

ALL the data represented in other encoding. Characters look like XXXX. I can't find the corrupted file for the time being because I didn't make a backup.

**Comment by charlieDJ** [comment]
> > > The json data format is wrong, is there less closing brace?
> > 
> > 
> > ALL the data represented in other encoding. Characters look like XXXX. I can't find the corrupted file for the time being because I didn't make a backup.
> 
> Is there topics.json.bak file in this directory?

It remained correct.

**Comment by charlieDJ** [comment]
> > It shows that delayOffset.json and consumerOffset.json were corrupted.
> 
> It's better that you can attach these corrupted files.
> 
> You track the implementation of persisting "consumerOffset.json" file in `org.apache.rocketmq.common.ConfigManager#persist`.

well, I'll keep oberserving.

**Comment by charlieDJ** [comment]
> > It shows that delayOffset.json and consumerOffset.json were corrupted.
> 
> It's better that you can attach these corrupted files.
> 
> You track the implementation of persisting "consumerOffset.json" file in `org.apache.rocketmq.common.ConfigManager#persist`.

The power went out last night. I restart my VM now and find that the delayOffset.json file is corrupted. The offsetTable seems clearing out in consumerOffset.json file.

delayOffset.json file:
                                                                                                                                             
It looks like blank empty. It represents multiple NUL in Ansi encoding by default.

consumerOffset.json file:
{
	"offsetTable":{}
}

**Comment by Jason918** [comment]
The persistence procedure of these meta data does not check checksum of the data. 
I think we can optimize it by adding checksum of the data file, and revert to backup file if the checksum does not match.
