### ISSUE TITLE
When the broker registers with the nameserver, does it support specifying the LocalAddress?

### ISSUE THREAD

**Issue by liruishan** [apache/rocketmq#3405]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

My broker is deployed in a container and has multiple network interfaces. When the broker registers with the nameserver, the broker's ip address is not the expected one，isn't it possible to specify LocalAddress?

I think this is unreasonable.

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
I browsed the code and found that LocalAddress was randomly selected：
![image](https://user-images.githubusercontent.com/41253645/136878357-b7155bf8-99d1-4b27-b0fe-b33341666087.png)

**Comment by panzhi33** [comment]
have you set brokerIP1？

**Comment by liruishan** [comment]
> > > > have you set brokerIP1？
> > > 
> > > 
> > > Can brokerIP1 be set? I did not find a way to set brokerIP1
> > 
> > 
> > Configuration inside broker.peroperties，like brokerIP1=127.0.0.1 https://github.com/apache/rocketmq/blob/master/docs/cn/best_practice.md#33-broker-%E9%85%8D%E7%BD%AE

I have another question. If the IP address is not a specific value, but a range, such as an address in 172.31.0.0/16, how should I configure it?
