### ISSUE TITLE
[store] nextBeginOffset is greater than maxOffset problem

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#3412]
1. Please describe the issue you observed:
Background:
There is only one file in a consumeQueue, and part of the data has expired. As follows：
![image](https://user-images.githubusercontent.com/30995057/137322246-a7bb327a-1b1c-44c1-b3ff-0a95b014db30.png)
- minOffset=0, maxOffset=851686, nextBeginOffset=30000
![image](https://user-images.githubusercontent.com/30995057/137322780-30ec5821-3b7e-40d6-a252-5e73f57ef33f.png)
![image](https://user-images.githubusercontent.com/30995057/137322871-69b06e2c-683e-493f-b469-35e5753ef004.png)

- Use Go SDK to consume
<img width="1432" alt="WechatIMG132" src="https://user-images.githubusercontent.com/30995057/137344758-8fd2e291-4cca-4a30-ada6-f476b0aa6a23.png">

2. Please tell us about your environment:
- RocketMQ 4.8
- Go SDK 2.1.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
- RocketMQ:
![image](https://user-images.githubusercontent.com/30995057/137323747-0f590bd0-110e-468a-882d-7b8b260e857c.png)
- Go SDK:
ISSUE: https://github.com/apache/rocketmq-client-go/issues/731

**Comment by Git-Yang** [comment]
> Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0

<img width="1409" alt="WechatIMG133" src="https://user-images.githubusercontent.com/30995057/137345808-fa4812cd-b4de-4e0d-90ad-6d53c6b8a9d7.png">

**Comment by Git-Yang** [comment]
> > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > 
> > 
> > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> 
> minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。

Can you point out where you said the input parameter check is?

**Comment by Git-Yang** [comment]
> > > > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > > > 
> > > > 
> > > > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> > > 
> > > 
> > > minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。
> > 
> > 
> > Can you point out where you said the input parameter check is? I see that the following part of the check does not detect the offset=0 situation. <img alt="WechatIMG141" width="1017" src="https://user-images.githubusercontent.com/30995057/137371211-61eb55f2-8f45-4cff-90e1-c6ac67a5a8ea.png">
> 
> > > > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > > > 
> > > > 
> > > > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> > > 
> > > 
> > > minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。
> > 
> > 
> > Can you point out where you said the input parameter check is? I see that the following part of the check does not detect the offset=0 situation. <img alt="WechatIMG141" width="1017" src="https://user-images.githubusercontent.com/30995057/137371211-61eb55f2-8f45-4cff-90e1-c6ac67a5a8ea.png">
> 
> Look at the information printed in the log, offset=0 ![image](https://user-images.githubusercontent.com/29321745/137417514-81826a24-b303-4a00-9675-eff930f7664d.png)

This is because of the problem mentioned in the question (https://github.com/apache/rocketmq-client-go/pull/732). Go SDK did not start consumption from nextBeginOffset, so the offset is always 0. I think this does not mean that offset=0 has been checked, but because the data corresponding to offset=0 has expired, resulting in log exceptions.

**Comment by panzhi33** [comment]
> > > > > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > > > > 
> > > > > 
> > > > > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> > > > 
> > > > 
> > > > minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。
> > > 
> > > 
> > > Can you point out where you said the input parameter check is? I see that the following part of the check does not detect the offset=0 situation. <img alt="WechatIMG141" width="1017" src="https://user-images.githubusercontent.com/30995057/137371211-61eb55f2-8f45-4cff-90e1-c6ac67a5a8ea.png">
> > 
> > 
> > > > > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > > > > 
> > > > > 
> > > > > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> > > > 
> > > > 
> > > > minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。
> > > 
> > > 
> > > Can you point out where you said the input parameter check is? I see that the following part of the check does not detect the offset=0 situation. <img alt="WechatIMG141" width="1017" src="https://user-images.githubusercontent.com/30995057/137371211-61eb55f2-8f45-4cff-90e1-c6ac67a5a8ea.png">
> > 
> > 
> > Look at the information printed in the log, offset=0 ![image](https://user-images.githubusercontent.com/29321745/137417514-81826a24-b303-4a00-9675-eff930f7664d.png)
> 
> This is because of the problem mentioned in the question ([apache/rocketmq-client-go#732](https://github.com/apache/rocketmq-client-go/pull/732)). Go SDK did not start consumption from nextBeginOffset, so the offset is always 0. I think this does not mean that offset=0 has been checked, but because the data corresponding to offset=0 has expired, resulting in log exceptions.

Regarding the state OFFSET_FOUND_NULL, my understanding is that the first offset is 0, then nextBeginOffset is corrected to 300000, the next time org.apache.rocketmq.store.DefaultMessageStore#getMessage enters the parameter offset is 300000, and then nextBeginOffset is corrected to 600000...Finally, The correct offset will be found. I think the problem is in the go client. Don't know if my understanding is correct

**Comment by Git-Yang** [comment]
> > > > > > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > > > > > 
> > > > > > 
> > > > > > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> > > > > 
> > > > > 
> > > > > minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。
> > > > 
> > > > 
> > > > Can you point out where you said the input parameter check is? I see that the following part of the check does not detect the offset=0 situation. <img alt="WechatIMG141" width="1017" src="https://user-images.githubusercontent.com/30995057/137371211-61eb55f2-8f45-4cff-90e1-c6ac67a5a8ea.png">
> > > 
> > > 
> > > > > > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > > > > > 
> > > > > > 
> > > > > > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> > > > > 
> > > > > 
> > > > > minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。
> > > > 
> > > > 
> > > > Can you point out where you said the input parameter check is? I see that the following part of the check does not detect the offset=0 situation. <img alt="WechatIMG141" width="1017" src="https://user-images.githubusercontent.com/30995057/137371211-61eb55f2-8f45-4cff-90e1-c6ac67a5a8ea.png">
> > > 
> > > 
> > > Look at the information printed in the log, offset=0 ![image](https://user-images.githubusercontent.com/29321745/137417514-81826a24-b303-4a00-9675-eff930f7664d.png)
> > 
> > 
> > This is because of the problem mentioned in the question ([apache/rocketmq-client-go#732](https://github.com/apache/rocketmq-client-go/pull/732)). Go SDK did not start consumption from nextBeginOffset, so the offset is always 0. I think this does not mean that offset=0 has been checked, but because the data corresponding to offset=0 has expired, resulting in log exceptions.
> 
> Regarding the state OFFSET_FOUND_NULL, my understanding is that the first offset is 0, then nextBeginOffset is corrected to 300000, the next time org.apache.rocketmq.store.DefaultMessageStore#getMessage enters the parameter offset is 300000, and then nextBeginOffset is corrected to 600000...Finally, The correct offset will be found. I think the problem is in the go client. Don't know if my understanding is correct

Yes. According to the normal processing, the offset will continue to find the next file. This problem should be manifested in the java sdk, but because OFFSET_FOUND_NULL will not be processed in the GO SDK, the query will continue from offset=0 next time. I fixed this problem in ISSUE [#732](https://github.com/apache/rocketmq-client-go/pull/732).

**Comment by panzhi33** [comment]
> > > > > > > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > > > > > > 
> > > > > > > 
> > > > > > > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> > > > > > 
> > > > > > 
> > > > > > minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。
> > > > > 
> > > > > 
> > > > > Can you point out where you said the input parameter check is? I see that the following part of the check does not detect the offset=0 situation. <img alt="WechatIMG141" width="1017" src="https://user-images.githubusercontent.com/30995057/137371211-61eb55f2-8f45-4cff-90e1-c6ac67a5a8ea.png">
> > > > 
> > > > 
> > > > > > > > Is the topic directory wrong? It is inconsistent with the topic in the log. And according to the consumeQueue file, minOffset should not be 0
> > > > > > > 
> > > > > > > 
> > > > > > > The wrong topic has been cut, and this problem has appeared on multiple topics at the same time. I will take a break later. There is only one consumeQueue file from start to finish. Due to slow production, some data has expired and been deleted. But minOffset is the actual offset of the smallest file of the current consumeQueue.
> > > > > > 
> > > > > > 
> > > > > > minOffset=0, maxOffset=851686, nextBeginOffset=300000 maxOffset > nextBeginOffset public long rollNextFile(final long index) { int mappedFileSize = this.mappedFileSize; int totalUnitsInFile = mappedFileSize / CQ_STORE_UNIT_SIZE; return index + totalUnitsInFile - index % totalUnitsInFile; } org.apache.rocketmq.store.DefaultMessageStore#getMessage will check the input parameter offset before, so the nextBeginOffset calculated by this method will not be greater than maxOffset。
> > > > > 
> > > > > 
> > > > > Can you point out where you said the input parameter check is? I see that the following part of the check does not detect the offset=0 situation. <img alt="WechatIMG141" width="1017" src="https://user-images.githubusercontent.com/30995057/137371211-61eb55f2-8f45-4cff-90e1-c6ac67a5a8ea.png">
> > > > 
> > > > 
> > > > Look at the information printed in the log, offset=0 ![image](https://user-images.githubusercontent.com/29321745/137417514-81826a24-b303-4a00-9675-eff930f7664d.png)
> > > 
> > > 
> > > This is because of the problem mentioned in the question ([apache/rocketmq-client-go#732](https://github.com/apache/rocketmq-client-go/pull/732)). Go SDK did not start consumption from nextBeginOffset, so the offset is always 0. I think this does not mean that offset=0 has been checked, but because the data corresponding to offset=0 has expired, resulting in log exceptions.
> > 
> > 
> > Regarding the state OFFSET_FOUND_NULL, my understanding is that the first offset is 0, then nextBeginOffset is corrected to 300000, the next time org.apache.rocketmq.store.DefaultMessageStore#getMessage enters the parameter offset is 300000, and then nextBeginOffset is corrected to 600000...Finally, The correct offset will be found. I think the problem is in the go client. Don't know if my understanding is correct
> 
> Yes. According to the normal processing, the offset will continue to find the next file. This problem should be manifested in the java sdk, but because OFFSET_FOUND_NULL will not be processed in the GO SDK, the query will continue from offset=0 next time. I fixed this problem in ISSUE [#732](https://github.com/apache/rocketmq-client-go/pull/732).

![image](https://user-images.githubusercontent.com/29321745/137432680-d47dae3a-27c5-4ad7-b415-76b419720fee.png)
I think there is no need to judge here, nextBeginOffset must be less than maxOffset
