### ISSUE TITLE
[RIP-25]Simplifying Producer and Consumer APIs

### ISSUE THREAD

**Issue by caigy** [apache/rocketmq#3417]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Currently, RocketMQ's client API is a bit complex so it's time to simply Producer and Consumer APIs. 
For example: 
-  There are about 20 methods for sending messages in `MQProducer,` some of which requires `timeout` parameter, and it is so rare to set timeout for every sending operation.
- Clients like `DefaultMQProuder`, `DefaultMQPushConsumer`, `DefaultLitePullConsumer` provide several constructors and setters, user may feel difficult to use them correctly.
-  `MQProducer` and `MQConsumer` extends `MQAdmin` which makes them provide too many methods that are not related to message sending and consuming.

2. Provide any additional detail on your proposed use case for this feature.
Producer and Consumer should provide APIs that are easy to use:
- easy to create Producer and Consumer clients
- easy to send and consume messages

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have. Currently users may frequently check the documentation to confirm that they use the API correctly, sometimes people create some util code to wrap client APIs to make them easier to use.

**Comment by aaron-ai** [comment]
RocketMQ 5.0 would release lite client based on gRPC, which would integrate with new API, look forward to more constructive opinions.

**Comment by lizhanhui** [comment]
> This is a topic worth discussing.
> 
> > * Clients like `DefaultMQProuder`, `DefaultMQPushConsumer`, `DefaultLitePullConsumer` provide several constructors and setters, user may feel difficult to use them correctly.
> 
> For this, I think we can create all kinds of producers, consumers and admins through a single 'Client' instance.
> 
> > * `MQProducer` and `MQConsumer` extends `MQAdmin` which makes them provide too many methods that are not related to message sending and consuming.
> 
> > * There are about 20 methods for sending messages in `MQProducer,` some of which requires `timeout` parameter, and it is so rare to set timeout for every sending operation.
> 
> For these two, We could polish the interfaces in like 'MQProducer', or create a new one to provide all kinds of necessary operations. An instance of MQProducer can be returned by the `Client.newProducer()`,and user should not consider the implementation underlying, like it's an object of 'DefaultMQProuder' .

To allow further configuration, how about `Client.newProducerBuilder().withXXX().withYYY().build()`
