### ISSUE TITLE
Replace the logging module by shaded logback.

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#3423]
A shaded logback could easily prevent the clash of configuration file, thus maybe it is a better choice to replace the logging module by a shaded logback.

Here is a simple demo to shade logback. :)
https://github.com/aaron-ai/rocketmq-logback

**Comment by Jason918** [comment]
Can you please add more detail about "the clash of configuration file" ?

**Comment by aaron-ai** [comment]
> Can you please add more detail about "the clash of configuration file" ?

If official logback is introduced directly in rocketmq, and some users of rocketmq may using slf4j/logback as its logging system too, the related configuration file and system properties may clash with each other. e.g. config file: `logback.xml` and system property: `logback.configurationFile`

**Comment by lizhanhui** [comment]
Nice proposal...  Looking forward to the actual pull request.

**Comment by aaron-ai** [comment]
> A shaded logback could easily prevent the clash of configuration file, thus maybe it is a better choice to replace the logging module by a shaded logback.
> 
> Here is a simple demo to shade logback. :) https://github.com/aaron-ai/rocketmq-logback

New project is release, refer to : https://github.com/aliyun-mq/rocketmq-logging, next up is to embed it by actual pull request. @duhenglucky

**Comment by aaron-ai** [comment]
> > > Can you please add more detail about "the clash of configuration file" ?
> > 
> > 
> > If official logback is introduced directly in rocketmq, and some users of rocketmq may use slf4j/logback as its logging system too, the related configuration file and system properties may clash with each other. e.g. config file: `logback.xml` and system property: `logback.configurationFile`
> 
> Dependency conflicts are a problem for developers, and it seems we should build a new module for RocketMQ's own dependent shade to resolve the conflict of the following commonly used JAR packages, not just logback.

Well, I think a shade module is essential, but maybe it is another scope, should we focus on the logging module in current issue?
