### ISSUE TITLE
Update(Close) UnitSubFlag is useless

### ISSUE THREAD

**Issue by lushilin** [apache/rocketmq#3424]
update topic UnitSubFlag has bug, if close unitSubFlag is not useful.
![image](https://user-images.githubusercontent.com/17663472/138229219-61c0f676-bc2d-4abf-8dc1-4522a6683d65.png)
when close unitSubFlag, do not have else logic to close it.

**Comment by lizhanhui** [comment]
+1 to clean the dead code.

**Comment by lushilin** [comment]
Yes, i think so. 
How about this @lizhanhui
