### ISSUE TITLE
Can we use different SCHEDULE_TOPIC_XXXX for delay msg and retry msg?

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq#3425]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
- current situation: The retry message depends on the delayed message, which causes the performance of the delayed message to become very poor when there are a large number of retry messages. If we use different topic for delay and retry msg, it will solve this problem.

2. Provide any additional detail on your proposed use case for this feature.
- suggestion: use different SCHEDULE_TOPIC_XXXX for delay msg and retry msg.
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

**Comment by XiaoyiPeng** [comment]
> 

+1, 
Can we add feature that support send message with arbitrary latency ?

**Comment by lizhanhui** [comment]
@XiaoyiPeng A potential solution is to build this feature following hierarchy timing wheels: http://www.cs.columbia.edu/~nahum/w6998/papers/sosp87-timing-wheels.pdf

**Comment by fuyou001** [comment]
@cserwen  the new delay  message  feature is  coming soon.

**Comment by cserwen** [comment]
> @cserwen the new delay message feature will coming soon.

Yes, I already got this message, so closed this issue. 😁
