### ISSUE TITLE
After deleting mqAdminExt subscriptionGroup,Again Automatically creating same Group

### ISSUE THREAD

**Issue by CP-Ram** [apache/rocketmq#343]
I'm using RocketMQ with c#. After deleteSubscriptionGroup from mqAdminExt, again automatically creating the group with the same name whatever I deleted.
Here is the code:
 ```
public class Test {
  public DefaultMQProducer _producer;
  public DefaultMQAdminExt rocketMqAdmin;
  public DefaultMQPushConsumer _consumer;
  public WebSocket websocket;

  string tag = "4-0-00-00-000-0000-456";
  string NameServeruri = "localhost:9876";
  string consumerId = tag + "-Sessions-Consumer";

  onServicStart() {

   var adminId = this.Context.NodeContext.NodeName + "-rocketmqAdmin";
   rocketMqAdmin = new DefaultMQAdminExt(adminId);
   rocketMqAdmin.start();

   var producerId = this.GetType().Name.ToString() + "-" + this.Context.NodeContext.NodeName + "-Producer";
   _producer = new DefaultMQProducer(producerId);
   _producer.setNamesrvAddr(RocketMQBaseURL);
   _producer.start();

  }

  consumer() {
   _consumer = new DefaultMQPushConsumer(consumerId);
   _consumer.setNamesrvAddr(NameServeruri);
   _consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_LAST_OFFSET);
   _consumer.subscribe(topic, tag);

   MQMessageListener listener = new MQMessageListener(websocket, tag);
   _consumer.registerMessageListener(listener);
   _consumer.start();
  }

  remove() {
   DefaultMQPushConsumer consumer = _consumer;
   consumer.shutdown();

   var id = tag + "-Sessions-Consumer";
   rocketMqAdmin.deleteSubscriptionGroup(RocketMQBrokerURL, id);
  }
 }
```

below are the broker logs:

> 2018-06-20 13:38:11 INFO BrokerControllerScheduledThread1 - register broker to name server localhost:9876 OK
> 2018-06-20 13:38:41 INFO BrokerControllerScheduledThread1 - register broker to name server localhost:9876 OK
> 2018-06-20 13:38:58 INFO ClientManageThread_6 - auto create a subscription group, SubscriptionGroupConfig [groupName=4-46e7-911f-913ec76bdb17-Sessions-Consumer, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
> 2018-06-20 13:38:58 INFO ClientManageThread_6 - create new topic TopicConfig [topicName=%RETRY%4-46e7-911f-913ec76bdb17-Sessions-Consumer, readQueueNums=1, writeQueueNums=1, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
> 2018-06-20 13:38:58 INFO ClientManageThread_6 - register broker to name server localhost:9876 OK
> 2018-06-20 13:38:58 INFO ClientManageThread_6 - new consumer connected, group: 4-46e7-911f-913ec76bdb17-Sessions-Consumer CONSUME_PASSIVELY CLUSTERING channel: ClientChannelInfo [channel=[id: 0x2aa59625, L:/192.168.1.30:10911 - R:/192.168.1.30:63488], clientId=169.254.184.73@30892, language=JAVA, version=252, lastUpdateTimestamp=1529473138639]
> 2018-06-20 13:38:58 INFO ClientManageThread_6 - subscription changed, add new topic, group: 4-46e7-911f-913ec76bdb17-Sessions-Consumer SubscriptionData [classFilterMode=false, topic=%RETRY%4-46e7-911f-913ec76bdb17-Sessions-Consumer, subString=*, tagsSet=[], codeSet=[], subVersion=1529473138565, expressionType=null]
> 2018-06-20 13:38:58 INFO ClientManageThread_6 - subscription changed, add new topic, group: 4-46e7-911f-913ec76bdb17-Sessions-Consumer SubscriptionData [classFilterMode=false, topic=251122b1-fec6-491d-969a-44a87138fc21, subString=4-46e7-911f-913ec76bdb17, tagsSet=[4-46e7-911f-913ec76bdb17], codeSet=[-487735314], subVersion=1529473138531, expressionType=null]
> 2018-06-20 13:38:58 INFO ClientManageThread_6 - registerConsumer info changed ConsumerData [groupName=4-46e7-911f-913ec76bdb17-Sessions-Consumer, consumeType=CONSUME_PASSIVELY, messageModel=CLUSTERING, consumeFromWhere=CONSUME_FROM_LAST_OFFSET, unitMode=false, subscriptionDataSet=[SubscriptionData [classFilterMode=false, topic=%RETRY%4-46e7-911f-913ec76bdb17-Sessions-Consumer, subString=*, tagsSet=[], codeSet=[], subVersion=1529473138565, expressionType=null], SubscriptionData [classFilterMode=false, topic=251122b1-fec6-491d-969a-44a87138fc21, subString=4-46e7-911f-913ec76bdb17, tagsSet=[4-46e7-911f-913ec76bdb17], codeSet=[-487735314], subVersion=1529473138531, expressionType=null]]] 192.168.1.30:63488
> 2018-06-20 13:38:58 INFO ClientManageThread_7 - subscription changed, group: 4-46e7-911f-913ec76bdb17-Sessions-Consumer OLD: SubscriptionData [classFilterMode=false, topic=%RETRY%4-46e7-911f-913ec76bdb17-Sessions-Consumer, subString=*, tagsSet=[], codeSet=[], subVersion=1529473138565, expressionType=null] NEW: SubscriptionData [classFilterMode=false, topic=%RETRY%4-46e7-911f-913ec76bdb17-Sessions-Consumer, subString=*, tagsSet=[], codeSet=[], subVersion=1529473138787, expressionType=null]
> 2018-06-20 13:39:10 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 0 bytes
> 2018-06-20 13:39:10 INFO BrokerControllerScheduledThread1 - Slave fall behind master: 0 bytes
> 2018-06-20 13:39:11 INFO BrokerControllerScheduledThread1 - register broker to name server localhost:9876 OK
> 2018-06-20 13:39:41 INFO BrokerControllerScheduledThread1 - register broker to name server localhost:9876 OK
> 2018-06-20 13:40:07 INFO ClientManageThread_22 - unregister a consumer[4-46e7-911f-913ec76bdb17-Sessions-Consumer] from consumerGroupInfo ClientChannelInfo [channel=[id: 0x2aa59625, L:/192.168.1.30:10911 - R:/192.168.1.30:63488], clientId=169.254.184.73@30892, language=JAVA, version=252, lastUpdateTimestamp=1529473204921]
> 2018-06-20 13:40:07 INFO ClientManageThread_22 - unregister consumer ok, no any connection, and remove consumer group, 4-46e7-911f-913ec76bdb17-Sessions-Consumer
> 2018-06-20 13:40:07 INFO AdminBrokerThread_8 - deleteSubscriptionGroup called by 127.0.0.1:50735
> **2018-06-20 13:40:07 INFO AdminBrokerThread_8 - delete subscription group OK, subscription** group:SubscriptionGroupConfig [groupName=4-46e7-911f-913ec76bdb17-Sessions-Consumer, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
> 2018-06-20 13:40:10 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 0 bytes
> 2018-06-20 13:40:10 INFO BrokerControllerScheduledThread1 - Slave fall behind master: 0 bytes
> 2018-06-20 13:40:11 INFO BrokerControllerScheduledThread1 - register broker to name server localhost:9876 OK
> ### 2018-06-20 13:40:21 INFO PullMessageThread_8 - auto create a subscription group, SubscriptionGroupConfig [groupName=4-46e7-911f-913ec76bdb17-Sessions-Consumer, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
> 2018-06-20 13:40:21 WARN PullMessageThread_8 - The consumer's group info not exist, group: 4-46e7-911f-913ec76bdb17-Sessions-Consumer

But while deleting from RocketMQ console it working properly and also unregister producer group from channelTableInfo and not calling PullMessageThread auto create.But in case of c# above code AdminExt with PullMessage Thread auto create also calling.

Any help.

**Comment by vongosling** [comment]
@lizhanhui

**Comment by lizhanhui** [comment]
I'd like to help but here are two issues to clarify first.
1) Can you provide the version of C# SDK? Best if you could give a git hash.
2) Your log looks inconsistent with your code.  Can you renew your log output thereafter?

**Comment by CP-Ram** [comment]
1.Actually i am not using .Net SDk for RocketMQ.
I have used IKVM to convert rocketmq-4.2 jars in Dll.
Before i used rocketmq-client-4.2.0-incubating.dll, rocketmq-common-4.2.0-incubating.dll, rocketmq-remoting-4.2.0-incubating.dll for producer and consumer client code.
For delete topics and subscription group, used rocketmq-tools-4.2.0-incubating.dll.
As client and common are present in tools dll, so currently using only remoting and tools dll.
(All dlls were converted from jars. Because i started working on rocketMQ almost 2017 octobar.And that time i faced many issues(some functionality missing) in .Net SDK).
Can you tell me that currently .Net SDk has all the support same as java liabrary? Then i will try with .Net SDK.Because i am facing new issue in .Net core when using IKVM.


2.When **remove()** method is invoke in my code below is the log for that

2018-06-20 13:40:07 INFO ClientManageThread_22 - **unregister a consumer**[4-46e7-911f-913ec76bdb17-Sessions-Consumer] from consumerGroupInfo ClientChannelInfo [channel=[id: 0x2aa59625, L:/192.168.1.30:10911 - R:/192.168.1.30:63488], clientId=169.254.184.73@30892, language=JAVA, version=252, lastUpdateTimestamp=1529473204921]
2018-06-20 13:40:07 INFO ClientManageThread_22 - unregister consumer ok, no any connection, and remove consumer group, 4-46e7-911f-913ec76bdb17-Sessions-Consumer
2018-06-20 13:40:07 INFO AdminBrokerThread_8 - deleteSubscriptionGroup called by 127.0.0.1:50735
2018-06-20 13:40:07 INFO AdminBrokerThread_8 - **delete subscription group OK, subscription** group:SubscriptionGroupConfig [groupName=4-46e7-911f-913ec76bdb17-Sessions-Consumer, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2018-06-20 13:40:10 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 0 bytes
2018-06-20 13:40:10 INFO BrokerControllerScheduledThread1 - Slave fall behind master: 0 bytes
2018-06-20 13:40:11 INFO BrokerControllerScheduledThread1 - register broker to name server localhost:9876 OK

2018-06-20 13:40:21 INFO PullMessageThread_8 - **auto create a subscription group**, SubscriptionGroupConfig [groupName=4-46e7-911f-913ec76bdb17-Sessions-Consumer, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2018-06-20 13:40:21 WARN PullMessageThread_8 - The consumer's group info not exist, group: 4-46e7-911f-913ec76bdb17-Sessions-Consumer

**Comment by lizhanhui** [comment]
From your provided log, the __" auto create a subscription group, "__ is executed by PullMessageThread, aka, PullMessageProcesssor. PullMessageProcessor.java line #106 indeed examines existence of the mentioned subscription group through findSubscriptionGroupConfig(group) as below:
```java
    public SubscriptionGroupConfig findSubscriptionGroupConfig(final String group) {
        SubscriptionGroupConfig subscriptionGroupConfig = this.subscriptionGroupTable.get(group);
        if (null == subscriptionGroupConfig) {
            if (brokerController.getBrokerConfig().isAutoCreateSubscriptionGroup() || MixAll.isSysConsumerGroup(group)) {
                subscriptionGroupConfig = new SubscriptionGroupConfig();
                subscriptionGroupConfig.setGroupName(group);
                SubscriptionGroupConfig preConfig = this.subscriptionGroupTable.putIfAbsent(group, subscriptionGroupConfig);
                if (null == preConfig) {
                    log.info("auto create a subscription group, {}", subscriptionGroupConfig.toString());
                }
                this.dataVersion.nextVersion();
                this.persist();
            }
        }

        return subscriptionGroupConfig;
    }
```
This is the only method that may output such log. Apparently, it should not run into branch of creating new subscription and the follow-up log output confirms this: __The consumer's group info not exist, __.

I am wondering if the conversion tool, IKVM, made some errors such as reorder the log statement out of the if-guard.

**Comment by lizhanhui** [comment]
@CP-Ram Looks the IKVM supports debug https://www.ikvm.net/devguide/concepts.html you may follow instructs there to build a debug version and step into the code I mentioned to figure out the mysterious part.

**Comment by vongosling** [comment]
@CP-Ram ping
