### ISSUE TITLE
Crash when using startup in windows platform

### ISSUE THREAD

**Issue by AnthonyZero** [apache/rocketmq#344]
In the latest version of 4.2.0, if the ROCKETMQ_HOME's windows path has spaces, then mqnamesrv.cmd will start error reporting: unable to find or unable to load the main class.

**Comment by vongosling** [comment]
Thanks for you report, we will verify the problem and fix it in the 4.3.0 version :-)

**Comment by XiaoZYang** [comment]
@AnthonyZero Thank you for the report!

When I try to start `namesrv` by `mqnamesrv.cmd` I can't reproduce the error you mentioned. Would you mind providing more details about your development environment such as java version, maven version, ROCKETMQ_HOME value, etc.

And here are some tips you may help:
- you should set the ROCKETMQ_HOME to the directory where the built package is the default value should be ${ROCKETMQ_PROJECT}/distribution/target/apache-rocketmq
- you may check the ROCKETMQ_HOME value in your cmd shell by `echo %ROCKETMQ_HOME%`
- If you run the script `mqnamesrv.cmd` in the terminal of IDE (e.g. Intellij idea), try to restart the IDE

Wish that can provide some intiutions for you. 
Thank you!

**Comment by AnthonyZero** [comment]
@XiaoZYang  development environment: Os Name: "windows 7" , Java version: 1.8.0_151, Maven version: 3.3.3,  ROCKETMQ_HOME path: D:\Program Files\rocketmq (my path directory contains spaces)

**Comment by xingfudeshi** [comment]
@AnthonyZero hey,the cause of the problem is that there's a space in your path.

**Comment by AnthonyZero** [comment]
yes, I know, but can't the path of windows have space? The directory of windows can have spaces

**Comment by xingfudeshi** [comment]
@AnthonyZero yes,you can't put the rocketmq in the path which contains spaces.for currently release version.you have to put rocketmq in a non-spaces path.sorry for the inconvenience.we will improve it as soon as possible.

**Comment by AnthonyZero** [comment]
OK,thanks

**Comment by XiaoZYang** [comment]
@AnthonyZero Java doesn't support path which contains spaces. So when you have spaces in your project directory which is included to classpath cause this error.

And you are _recommended_ to communicate and ask questions in the maillist, see http://rocketmq.apache.org/about/contact/ for more details about mailllist.

**Comment by xingfudeshi** [comment]
@AnthonyZero you can also change the value of ROCKETMQ_HOME to D:\PROGRA~1\rocketmq,it will solve your problem.but i still suggest you put the rcoketmq in a non-spaces path.

**Comment by vongosling** [comment]
@AnthonyZero If you still have a question, please email your question to our user email list.http://rocketmq.apache.org/about/contact/

**Comment by guoxiaoxu** [comment]
郁闷啊，都产生怀疑了，alibba 就那么菜

**Comment by ChocolateBoy168** [comment]
edit runserver.cmd file
`before`
@REM set "JAVA_OPT=%JAVA_OPT% -Djava.ext.dirs=%BASE_DIR%lib;`%JAVA_HOME%`\jre\lib\ext"
`after`
set "JAVA_OPT=%JAVA_OPT% -Djava.ext.dirs=%BASE_DIR%lib;`^"%JAVA_HOME%^"`\jre\lib\ext"
