### ISSUE TITLE
[POP] PopReviveService will consume reviveTopic repeatedly when use pop model to consume.

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq#3443]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
use consumer to consume msgs by pop model.

- What did you expect to see?
The following log is printed repeatedly which means messages of `reviveTopic` are repeatedly consumed.
```
2021-10-29 15:51:12 INFO PopReviveService_0 - reviveQueueId=0,find ack, offset:142765, raw : {"ackOffset":283798,"consumerGroup":"pop-consumer-1","popTime":1635476075611,"queueId":0,"startOffset":283791,"topic":"%RETRY%pop-consumer-1_-topic"}
```

2. Please tell us about your environment:
Linux

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
- when popReviveService consumes the reviveTopic，it can't commit the consume offset when the msg list doesn't have ck msg. The related code is line 365-371 in `PopReviveService.java`
- Besides，why `newOffset` was decided by ck msg ？ IMO，it should be the real offset which popReviveService consumed. The related code is as follows.
```java
long newOffset = consumeReviveObj.oldOffset;
for (PopCheckPoint popCheckPoint : sortList) {
    if (!checkAndSetMaster()) {
        POP_LOGGER.info("slave skip ck process , revive topic={}, reviveQueueId={}", reviveTopic, queueId);
        break;
    }
    if (consumeReviveObj.endTime - popCheckPoint.getReviveTime() <= (PopAckConstants.ackTimeInterval + PopAckConstants.SECOND)) {
        break;
    }

    // check normal topic, skip ck , if normal topic is not exist
    String normalTopic = KeyBuilder.parseNormalTopic(popCheckPoint.getTopic(), popCheckPoint.getCId());
    if (brokerController.getTopicConfigManager().selectTopicConfig(normalTopic) == null) {
        POP_LOGGER.warn("reviveQueueId={},can not get normal topic {} , then continue ", queueId, popCheckPoint.getTopic());
        newOffset = popCheckPoint.getReviveOffset();   //Is this right? 
        continue;
    }
    if (null == brokerController.getSubscriptionGroupManager().findSubscriptionGroupConfig(popCheckPoint.getCId())) {
        POP_LOGGER.warn("reviveQueueId={},can not get cid {} , then continue ", queueId, popCheckPoint.getCId());
        newOffset = popCheckPoint.getReviveOffset();   
        continue;
    }

    reviveMsgFromCk(popCheckPoint);

    newOffset = popCheckPoint.getReviveOffset();  //and this line
}

```

**Comment by odbozhou** [comment]
In order to prevent the message from being lost. Revive topic queue Offset update needs to pass ck msg. Revive topic contains both ck msg and ack msg. If the offset is updated directly by the number of Revive topic queue messages, there is a possibility of message loss. For example, some ck msgs are not confirmed by ack msg. , And without sending the retry topic, the offset of the receive topic is updated directly.
There is a possibility of repetition of ack msg due to the network or other reasons. The message corresponding to ack has been acked, and ack will be consumed repeatedly, but it has no effect. These ack msg will not be consumed repeatedly when the new ck msg is updated.

**Comment by cserwen** [comment]
> In order to prevent the message from being lost. Revive topic queue Offset update needs to pass ck msg. Revive topic contains both ck msg and ack msg. If the offset is updated directly by the number of Revive topic queue messages, there is a possibility of message loss. For example, some ck msgs are not confirmed by ack msg. , And without sending the retry topic, the offset of the receive topic is updated directly. There is a possibility of repetition of ack msg due to the network or other reasons. The message corresponding to ack has been acked, and ack will be consumed repeatedly, but it has no effect. These ack msg will not be consumed repeatedly when the new ck msg is updated.

@odbozhou Thanks for the explanation, but I have two questions:

- The offset was updated after putting messages into retry topic. Is it possible to fail putting msgs?
- Even if the above example happens, updating the offset by the ck msgs and updating it by the number of Revive topic queue messages are the same, because the ck msgs will be consumed only once. So I think updating the consume offset by the number of msgs directly will be better.
