### ISSUE TITLE
KEYS from https://www.apache.org/dist/rocketmq/KEYS can not VERIFY THE INTEGRITY files with error Can't check signature: No public key

### ISSUE THREAD

**Issue by dyrnq** [apache/rocketmq#3445]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
```bash
wget --progress dot:giga https://www.apache.org/dist/rocketmq/KEYS;
wget https://archive.apache.org/dist/rocketmq/4.9.2/rocketmq-all-4.9.2-bin-release.zip.asc
wget https://archive.apache.org/dist/rocketmq/4.9.2/rocketmq-all-4.9.2-bin-release.zip
gpg --import KEYS
gpg --verify rocketmq-all-4.9.2-bin-release.zip.asc rocketmq-all-4.9.2-bin-release.zip
```
ref ----><https://www.apache.org/dyn/closer.cgi?path=rocketmq/4.9.2/rocketmq-all-4.9.2-bin-release.zip>

- What did you expect to see?
```bash
gpg --batch --verify /usr/local/src/rocketmq-4.8.0.zip.asc /usr/local/src/rocketmq-4.8.0.zip
gpg: Signature made Wed 09 Dec 2020 08:04:21 PM CST
gpg:                using RSA key EC9F268B4C20590138B11FE701420E4292296EAE
gpg: Good signature from "jinrongtong (jinrongtong) <jinrongtong@apache.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

- What did you see instead?
```bash
gpg:                using RSA key 499168E6F32A2D46
gpg: Can't check signature: No public key
```
2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by RongtongJin** [comment]
This [URL](https://dist.apache.org/repos/dist/dev/rocketmq/KEYS) contains 4.9.2 release manager's key, It doesn't seem to have been transferred to the dist directory. We will upload the key to dist directory ASAP.

**Comment by RongtongJin** [comment]
The new KEYS of release manager has been uploaded. You can try again. Thank you for your careful attention to the RocketMQ.
