### ISSUE TITLE
Does rocketmq support mqtt protocol connection?

### ISSUE THREAD

**Issue by beyondyinjl2** [apache/rocketmq#3448]
Does rocketmq support mqtt protocol connection, subscription and publication of data, are there relevant documents and examples?

**Comment by maixiaohai** [comment]
@beyondyinjl2 refer to this issue https://github.com/apache/rocketmq-externals/issues/669

**Comment by vongosling** [comment]
We could transfer all MQTT topics to this thread apache/rocketmq-externals#669
