### ISSUE TITLE
sed: illegal option -- r

### ISSUE THREAD

**Issue by gorden5566** [apache/rocketmq#3450]
When I start nameserver on my Mac by the `mqnamesrv` script

```
sh ./bin/mqnamesrv
```

it raise an error

```
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

which lead to `JAVA_MAJOR_VERSION` always be empty,  in other words, it cannot recognize JDK gt than 1.8

The reason is that `sed` on osx has no `-r` option

We can test if the kernel is `Darwin`, and then decide how to get `JAVA_MAJOR_VERSION` by the result

```
case "`uname`" in
    Darwin)
        JAVA_MAJOR_VERSION=$("$JAVA" -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p')
    ;;
    *)
        JAVA_MAJOR_VERSION=$("$JAVA" -version 2>&1 | sed -r -n 's/.* version "([0-9]*).*$/\1/p')
    ;;
esac
```

What do you guys think?

reference #2848

**Comment by panzhi33** [comment]
https://github.com/Bash-it/bash-it/issues/634  
Can think about whether there are other ways to replace the sed command to obtain JAVA_MAJOR_VERSION

**Comment by gorden5566** [comment]
Good idea. I've read the ISSUE, it seems that the problem remains unsolved

> [Bash-it/bash-it#634](https://github.com/Bash-it/bash-it/issues/634) Can think about whether there are other ways to replace the sed command to obtain JAVA_MAJOR_VERSION

Besides, I've tried to find another command but failed

Maybe we can obtain `JAVA_MAJOR_VERSION` at runtime before start NAMESERVER, however it will introduce new dependencies

**Comment by ltamber** [comment]
Will the following command fulfill your requirement, which is not used option `-r`
`JAVA_MAJOR_VERSION=$("$JAVA" -version 2>&1 | head -1 | cut -d'"' -f2 | sed 's/^1\.//' | cut -d'.' -f1)`

**Comment by gorden5566** [comment]
> Will the following command fulfill your requirement, which is not used option `-r` `JAVA_MAJOR_VERSION=$("$JAVA" -version 2>&1 | head -1 | cut -d'"' -f2 | sed 's/^1\.//' | cut -d'.' -f1)`

I test the script for several java version, it works fine

```
result -> java version

8 -> java version "1.8.0_201"
9 -> java version "9.0.4"
10 -> java version "10" 2018-03-20
10 -> java version "10.0.1" 2018-04-17
17 -> openjdk version "17" 2021-09-14
17 -> openjdk version "17.0.1" 2021-10-19
```

**Comment by ltamber** [comment]
> I test the script for several java version, it works fine
> 
> ```
> result -> java version
> 
> 8 -> java version "1.8.0_201"
> 9 -> java version "9.0.4"
> 10 -> java version "10" 2018-03-20
> 10 -> java version "10.0.1" 2018-04-17
> 17 -> openjdk version "17" 2021-09-14
> 17 -> openjdk version "17.0.1" 2021-10-19
> ```

OK, In this pr #3224, the JAVA_MAJOR_VERSION has also been changed.
