### ISSUE TITLE
Anyone use rocketmq-client-python? A lot of problem

### ISSUE THREAD

**Issue by qpzmtyv** [apache/rocketmq#3455]
有人用rocketmq-client-python这个项目吗？https://github.com/apache/rocketmq-client-python ，包括rocketmq-client-app，好像都没有人维护了，对接4.9的服务端一大堆问题，生产者不能自动重连，也不支持事物回调那些，都没人在用吗？

**Comment by duhenglucky** [comment]
@qpzmtyv 我们针对4.9.x 这版本针对性的测试一下，cpp 的开发者们还在非常活跃的提交代码，可以把遇到的问题整理成issue
