### ISSUE TITLE
Can it be embedded inside Java application ?

### ISSUE THREAD

**Issue by corporatepiyush** [apache/rocketmq#346]

**Comment by aCoder2013** [comment]
what do you mean  "embedded" ? like rocksdb?

**Comment by corporatepiyush** [comment]
Can it be used as Java library ? so that it can be embedded in .jar or .war file along with application using it sharing the same instance of JVM

**Comment by vongosling** [comment]
@corporatepiyush IMHO, it is not a good place for your question, but I will give your answer that you concerned about this time. Any question for Apache RocketMQ, please email to user email list http://rocketmq.apache.org/about/contact/, thanks.

So for your question, all components in RocketMQ exposed the LifeCycle Interface. So, it is very easy to integrate them with your container :-)
