### ISSUE TITLE
Can rocketmq have one master corresponding to two slaves?

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#3461]
version：4.9.1
If a broker sets SYNC_MASTER, corresponding to two slaves, can three nodes write synchronously?

**Comment by iamqq23ue** [comment]
Dledger has some bugs and cannot realize disaster recovery. So I don't plan to choose Dledger yet. 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 晚上9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Can rocketmq have one master corresponding to two slaves? (Issue #3461)





  
version：4.9.1 If a broker sets SYNC_MASTER, corresponding to two slaves, can three nodes write synchronously?
  
Using the DLedger mode will ensure that more than half of the nodes will return immediately if synchronization is successful, so when there are 3 nodes, as long as there is a slave that is successfully synchronized, it will return.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Git-Yang** [comment]
> Dledger has some bugs and cannot realize disaster recovery. So I don't plan to choose Dledger yet.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/rocketmq" ***@***.***&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:49 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apache/rocketmq] Can rocketmq have one master corresponding to two slaves? (Issue #3461) version：4.9.1 If a broker sets SYNC_MASTER, corresponding to two slaves, can three nodes write synchronously? Using the DLedger mode will ensure that more than half of the nodes will return immediately if synchronization is successful, so when there are 3 nodes, as long as there is a slave that is successfully synchronized, it will return. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

If you use HA mode, SYNC_MASTER will only ensure that a slava synchronization is completed, and it will return immediately.
In addition, can you describe in detail the problems encountered when using the DLedger?

**Comment by iamqq23ue** [comment]
ISSUE#2582 still looks unresolved.&nbsp;You also can read my blog。
https://blog.csdn.net/qq23ue/article/details/112764507








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 晚上11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Can rocketmq have one master corresponding to two slaves? (Issue #3461)





  
Dledger has some bugs and cannot realize disaster recovery. So I don't plan to choose Dledger yet.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/rocketmq" @.&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:49 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [apache/rocketmq] Can rocketmq have one master corresponding to two slaves? (Issue #3461) version：4.9.1 If a broker sets SYNC_MASTER, corresponding to two slaves, can three nodes write synchronously? Using the DLedger mode will ensure that more than half of the nodes will return immediately if synchronization is successful, so when there are 3 nodes, as long as there is a slave that is successfully synchronized, it will return. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
If you use HA mode, SYNC_MASTER will only ensure that a slava synchronization is completed, and it will return immediately.
 In addition, can you describe in detail the problems encountered when using the DLedger?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Git-Yang** [comment]
> ISSUE#2582 still looks unresolved.&nbsp;You also can read my blog。 https://blog.csdn.net/qq23ue/article/details/112764507
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/rocketmq" ***@***.***&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上11:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apache/rocketmq] Can rocketmq have one master corresponding to two slaves? (Issue #3461) Dledger has some bugs and cannot realize disaster recovery. So I don't plan to choose Dledger yet. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/rocketmq" @.&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:49 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [apache/rocketmq] Can rocketmq have one master corresponding to two slaves? (Issue #3461) version：4.9.1 If a broker sets SYNC_MASTER, corresponding to two slaves, can three nodes write synchronously? Using the DLedger mode will ensure that more than half of the nodes will return immediately if synchronization is successful, so when there are 3 nodes, as long as there is a slave that is successfully synchronized, it will return. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. If you use HA mode, SYNC_MASTER will only ensure that a slava synchronization is completed, and it will return immediately. In addition, can you describe in detail the problems encountered when using the DLedger? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Okay, I will try to reproduce this problem.

**Comment by dongeforever** [comment]
This is the cold data problem。
For in-sync slave, the master loads data from page cache.
But for out-of-sync slave, the master needs to load data from disk, this will be much slower than page cache.
If the incoming tps is large，the out of sync slave may never have the chance to catch up with the master.

IMO，We may need to polish the cold data sync performance.

**Comment by iamqq23ue** [comment]
thanks for the reply。In addition, I suggest that if only one node exists in the deleger mode, this node can provide read services.
In this way, the requirements of disaster recovery can be met.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Can rocketmq have one master corresponding to two slaves? (Issue #3461)





 
This is the cold data problem。
 For in-sync slave, the master loads data from page cache.
 But for out-of-sync slave, the master needs to load data from disk, this will be much slower than page cache.
 If the incoming tps is large，the out of sync slave may never have the chance to catch up with the master.
 
IMO，We may need to polish the cold data sync performance.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dongeforever** [comment]
The raft consensus considers consistency firstly。
In a 2n+1 group，the failure tolerance is n. If more than n nodes are failed, the left nodes may provide corrupted data.

Anyway, "Read from a slave" can be an option, both in "master-slave mode" and "dledger mode".
but need take care of some cases:
* the max offset in slave may be smaller than the currently committed offset, which may result in an out-of-range exception, then cause the committed offset to be reset.

**Comment by vongosling** [comment]
> Dledger has some bugs and cannot realize disaster recovery. So I don't plan to choose Dledger yet.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/rocketmq" ***@***.***&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:49 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apache/rocketmq] Can rocketmq have one master corresponding to two slaves? (Issue #3461) version：4.9.1 If a broker sets SYNC_MASTER, corresponding to two slaves, can three nodes write synchronously? Using the DLedger mode will ensure that more than half of the nodes will return immediately if synchronization is successful, so when there are 3 nodes, as long as there is a slave that is successfully synchronized, it will return. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I don't understand what your mentioned bug in dledger, this is our state-of-the-art HA implementation. If you point this problem, I will drive the community to opt here. @dongeforever  @RongtongJin  are our mainly dledger authors.
