### ISSUE TITLE
Is this a Dledger bug? Only the master is working

### ISSUE THREAD

**Issue by fsckzy** [apache/rocketmq#3468]
Rocketmq 4.9.1 dledger cluster mode, in the console, only the master has a Consume Count, and the slave is 0.
![image](https://user-images.githubusercontent.com/34021474/140678267-b08a39fc-d9e0-41f0-ba5e-e099259b82d1.png)

The configuration file is as follows:
```yaml
brokerClusterName = RaftCluster
brokerName=RaftNode00
listenPort=30911
namesrvAddr=192.168.69.46:9876;192.168.69.47:9876;192.168.69.48:9876
storePathRootDir=/data/rmqstore/node00
storePathCommitLog=/data/rmqstore/node00/commitlog
enableDLegerCommitLog=true
dLegerGroup=RaftNode00
dLegerPeers=n0-192.168.69.46:40911;n1-192.168.69.47:40912;n2-192.168.69.48:40913
dLegerSelfId=n0
sendMessageThreadPoolNums=8
defaultTopicQueueNums=40
```

**Comment by Git-Yang** [comment]
There is no problem here. Reading from slave is disabled by default. You can enable slave reading by passing slaveReadEnable=true.

**Comment by fsckzy** [comment]
> 这里没有问题。默认情况下禁用从从设备读取。您可以通过传递 slaveReadEnable=true 来启用从站读取。 默认情况下，可以从slave读取内存后面40%的消息，你可以调整accessMessageInMemoryMaxRatio来调整比例。

Thank you for your answer, I have a question:
Why can't all 3 devices be read by default? If only the master provides services by default, will it cause a lot of pressure?

**Comment by Git-Yang** [comment]
> > 这里没有问题。默认情况下禁用从从设备读取。您可以通过传递 slaveReadEnable=true 来启用从站读取。 默认情况下，可以从slave读取内存后面40%的消息，你可以调整accessMessageInMemoryMaxRatio来调整比例。
> 
> Thank you for your answer, I have a question: Why can't all 3 devices be read by default? If only the master provides services by default, will it cause a lot of pressure?

I think ISSUE#3461 can answer your question.
