### ISSUE TITLE
Use RocketMQ4.7.0，the broker thread blocked

### ISSUE THREAD

**Issue by mask616** [apache/rocketmq#3469]
**BUG REPORT**

1. Please describe the issue you observed:
Using the RocketMQ 4.7.0 version of the broker, the broker will hang up after the server is running for about 4-7 days. Through the investigation of the thread stack, it is found that all threads are in the BLOCKED state.
使用RocketMQ 4.7.0版本的broker，在服务器运行大概4 - 7天左右就会出现broker假死的情况，通过排查线程堆栈，发现所有的线程都是BLOCKED状态。

The stack information is as follows：
<img width="781" alt="lQLPDhrZJupl6N3NAZvNBhqwHS_hcv9q7UIBkQZP0gAGAA_1562_411" src="https://user-images.githubusercontent.com/33280931/140688667-a53b41ef-a308-41a6-833c-2f2f40bcd50d.png">

<img width="572" alt="1636342726839_BDC1F26F-ED3D-403a-A79F-75FE59D3CE46" src="https://user-images.githubusercontent.com/33280931/140688686-635aac44-2202-4a66-99a2-1fb1a900ae35.png">

<img width="608" alt="1636342740458_622E83E8-DF4C-480e-9DBF-244E6BECDC8E" src="https://user-images.githubusercontent.com/33280931/140688691-e50d2fd2-64be-43ec-9a9f-92f597185f06.png">

<img width="600" alt="1636342753568_C37076EB-DC09-47a2-922F-5F235DEBDCF8" src="https://user-images.githubusercontent.com/33280931/140688698-543fb870-880e-47b0-bbb8-257f5f4e14bd.png">

**Comment by Git-Yang** [comment]
Can you provide more information? Are there any abnormal behaviors and logs in the broker?

**Comment by mask616** [comment]
> Can you provide more information? Are there any abnormal behaviors and logs in the broker?

The broker log:

![image](https://user-images.githubusercontent.com/33280931/140693852-7a31702b-5c64-43bf-a5cd-0405455debc4.png)

**Comment by Git-Yang** [comment]
> > Can you provide more information? Are there any abnormal behaviors and logs in the broker?
> 
> The broker log:
> 
> ![image](https://user-images.githubusercontent.com/33280931/140693852-7a31702b-5c64-43bf-a5cd-0405455debc4.png)



> > Can you provide more information? Are there any abnormal behaviors and logs in the broker?
> 
> The broker log:
> 
> ![image](https://user-images.githubusercontent.com/33280931/140693852-7a31702b-5c64-43bf-a5cd-0405455debc4.png)
> 
> The broker config: ![image](https://user-images.githubusercontent.com/33280931/140694245-4f64b375-e46c-4c5e-9dc8-3b3991ed2693.png)

The namesrv service response timed out on the 185 machine:
1. You can first judge whether the network is normal.
2. Check the namesrv service log of the 185 machine to see if there is any abnormal log.

**Comment by mask616** [comment]
> > > Can you provide more information? Are there any abnormal behaviors and logs in the broker?
> > 
> > 
> > The broker log:
> > ![image](https://user-images.githubusercontent.com/33280931/140693852-7a31702b-5c64-43bf-a5cd-0405455debc4.png)
> 
> > > Can you provide more information? Are there any abnormal behaviors and logs in the broker?
> > 
> > 
> > The broker log:
> > ![image](https://user-images.githubusercontent.com/33280931/140693852-7a31702b-5c64-43bf-a5cd-0405455debc4.png)
> > The broker config: ![image](https://user-images.githubusercontent.com/33280931/140694245-4f64b375-e46c-4c5e-9dc8-3b3991ed2693.png)
> 
> The namesrv service response timed out on the 185 machine:
> 
> 1. You can first judge whether the network is normal.
> 2. Check the namesrv service log of the 185 machine to see if there is any abnormal log.

1、185 is broker's machine ip, I think the network is OK.
2、From the namesrv log, found that there is no log before 1:00 to 14:00, but no error log。
![image](https://user-images.githubusercontent.com/33280931/140700049-445a0705-c7a7-4983-80f4-c5867c728559.png)

**Comment by ltamber** [comment]
可以把整个堆栈文件上传上来吗？

**Comment by mask616** [comment]
> 可以把整个堆栈文件上传上来吗？
http://oos-cn.ctyunapi.cn/szparking/attach/sbdevice.tdump
