### ISSUE TITLE
console dashboard problem

### ISSUE THREAD

**Issue by shawnlamjj** [apache/rocketmq#3472]
Using the RocketMQ 4.9.2 version of Each time we query the message tag #by topic type, the Today Consume Count in the broker in the cluster tag will be the same increment every time, regardless of the single or cluster deployment.Why does this happen? 

![image](https://user-images.githubusercontent.com/3965258/140898044-10a5df0c-a8ea-4ae0-b3e6-b40f82a397a7.png)
![image](https://user-images.githubusercontent.com/3965258/140898138-8be90c14-263e-44d4-b5d7-c83012b3cf94.png)

**Comment by duhenglucky** [comment]
@shawnlamjj Would you like to check this in ~/logs/rocketmqlogs/stats.log 

`cat stats.log | grep "GROUP_GET_NUMS" -C2 | grep "In One Day" |grep {topic name} ` for further verify?
