### ISSUE TITLE
send batch message with tag, commitlog save tag error

### ISSUE THREAD

**Issue by Bin2020** [apache/rocketmq#3476]
版本4.9.2，发送批量消息，tag设置TagA。commitlog保存的消息TAGS为TagACLUSTER，漏了分隔符。消费者订阅TagA收不到该消息。如果订阅全部类型tag，打印该消息的TAGS为TagACLUSTERDefaultCluster
```
BenchmarkTest mKEYSOrderID002UNIQ_KEY7F000001023818B4AAC23171A8B90001WAITtrueTAGSTagACLUSTERDefaultClusterWAITtrue 
```

**Comment by HScarb** [comment]
https://github.com/apache/rocketmq/pull/2961
this PR modifies `MessageDecoder#messageProperties2String()` may cause this problem, as it deleted last character of the properties string

**Comment by areyouok** [comment]
I have fix it, test finished.

You can pick this commit and build it yourself before 4.9.3 release.

**Comment by RongtongJin** [comment]
Merged

**Comment by wz2cool** [comment]
meet the same problem wait version 4.9.3
