### ISSUE TITLE
pullKernelImpl exception org.apache.rocketmq.client.exception.MQClientException

### ISSUE THREAD

**Issue by Dr-wgy** [apache/rocketmq#3477]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
we use consumer filter message by SQL92

- What did you expect to see?
no exception 
- What did you see instead?

2. Please tell us about your environment:
rocketMq 4.7.1 (client,broker only have master)

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
when our project starting , we encounter the following issue。when our project in running , this exception is disappear
```
pullKernelImpl exception
org.apache.rocketmq.client.exception.MQClientException: The broker[xxx, 0] does not upgrade to support for filter message by SQL92
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.consumer.PullAPIWrapper.pullKernelImpl(PullAPIWrapper.java:173)
	at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.pullMessage(DefaultMQPushConsumerImpl.java:432)
	at org.apache.rocketmq.client.impl.consumer.PullMessageService.pullMessage(PullMessageService.java:83)
	at org.apache.rocketmq.client.impl.consumer.PullMessageService.run(PullMessageService.java:96)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by wuguanyu** [comment]
I see source code carefully 

` if (findBrokerResult != null) {
            {
                // check version
                if (!ExpressionType.isTagType(expressionType)
                    && findBrokerResult.getBrokerVersion() < MQVersion.Version.V4_1_0_SNAPSHOT.ordinal()) {
                    throw new MQClientException("The broker[" + mq.getBrokerName() + ", "
                        + findBrokerResult.getBrokerVersion() + "] does not upgrade to support for filter message by " + expressionType, null);
                }
            }`

findBrokerResult.getBrokerVersion() 
this brokerVersion from local variable  brokerVersionTable 
brokerVersionTable will be init in sendHeartbeatToAllBroker 

I guess  findBrokerResult.getBrokerVersion() should be MQVersion.Version.V4_7_1_SNAPSHOT.ordinal()

but brokerVersion result is 0

**Comment by wuguanyu** [comment]
brokerAddrTable has value 
but brokerVersionTable is empty
![image](https://user-images.githubusercontent.com/24486917/141459708-603f46cb-5cc0-4efe-bc0a-2e2b3cf0a47c.png)

**Comment by wuguanyu** [comment]
if pullMessageService start running before sendHeartbeatToAllBroker (set version table in brokerVersionTable)
