### ISSUE TITLE
[TIMEOUT_CLEAN_QUEUE]broker busy

### ISSUE THREAD

**Issue by guixincui** [apache/rocketmq#348]
CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 204ms, size of queue: 0
 ?

**Comment by aiqing2171** [comment]
I changed broker config( synchronous disk IO flush) as below:
sendMessageThreadPoolNums=16
useReentrantLockWhenPutMessage=true
Tps was improved to be 2400.  should we use reentrantLock instead of spin lock?

**Comment by vongosling** [comment]
Good discussion. I would like to participate the discussion if we could send the question into the email list（http://rocketmq.apache.org/about/contact/）? The issue is not the correct place for community support

**Comment by cxfmichael** [comment]
> I changed broker config( synchronous disk IO flush) as below:
> sendMessageThreadPoolNums=16
> useReentrantLockWhenPutMessage=true
> Tps was improved to be 2400. should we use reentrantLock instead of spin lock?

hi, do u have worked out?

**Comment by cxfmichael** [comment]
> I changed broker config( synchronous disk IO flush) as below:
> sendMessageThreadPoolNums=16
> useReentrantLockWhenPutMessage=true
> Tps was improved to be 2400. should we use reentrantLock instead of spin lock?

maybe help u
http://mail-archives.apache.org/mod_mbox/rocketmq-users/201706.mbox/%3CCANMLrBiA3_YVzYKrW+UAYGEtYmdAmK7GYO+DutEMOMJEZDdrow@mail.gmail.com%3E

**Comment by Kanepan** [comment]
同样问题 tps不到 100
sendMessageThreadPoolNums=64
useReentrantLockWhenPutMessage=true
修改完后， 问题依旧。

**Comment by Force-King** [comment]
I also have the same problem,the above parameters have been adjusted and the JVM has been optimized, the problem has not been solved yet.

**Comment by Force-King** [comment]
> > I changed broker config( synchronous disk IO flush) as below:
> > sendMessageThreadPoolNums=16
> > useReentrantLockWhenPutMessage=true
> > Tps was improved to be 2400. should we use reentrantLock instead of spin lock?
> 
> maybe help u
> http://mail-archives.apache.org/mod_mbox/rocketmq-users/201706.mbox/%3CCANMLrBiA3_YVzYKrW+UAYGEtYmdAmK7GYO+DutEMOMJEZDdrow@mail.gmail.com%3E



> > I changed broker config( synchronous disk IO flush) as below:
> > sendMessageThreadPoolNums=16
> > useReentrantLockWhenPutMessage=true
> > Tps was improved to be 2400. should we use reentrantLock instead of spin lock?
> 
> maybe help u
> http://mail-archives.apache.org/mod_mbox/rocketmq-users/201706.mbox/%3CCANMLrBiA3_YVzYKrW+UAYGEtYmdAmK7GYO+DutEMOMJEZDdrow@mail.gmail.com%3E

I have configured according to the email, but there is still this problem。

**Comment by Force-King** [comment]
> 同样问题 tps不到 100
> sendMessageThreadPoolNums=64
> useReentrantLockWhenPutMessage=true
> 修改完后， 问题依旧。

查看I/O监控吧，这种情况基本上是I/O 波动引起的

**Comment by Kanepan** [comment]
> > 同样问题 tps不到 100
> > sendMessageThreadPoolNums=64
> > useReentrantLockWhenPutMessage=true
> > 修改完后， 问题依旧。
> 
> 查看I/O监控吧，这种情况基本上是I/O 波动引起的

IO 完全正常，写过 脚本 iostat 也查看过阿里云的IO，在出现busy异常的时候IO很正常， 不过这边有个情况是 broker IP是用外网的，是否跟这个有关？

**Comment by hdchen** [comment]
在tps不到100的情况下，还出现serverbusy，你的服务器的配置可能不是很高，sendMessageThreadPoolNums这个值不宜配置这么多，另外lizhanhui大神已经建议过，在同步刷盘模式下，建议把waitTimeMillsInSendQueue适当调整大一点。
可以试试下面的参数
sendMessageThreadPoolNums=16
useReentrantLockWhenPutMessage=true
waitTimeMillsInSendQueue=500

另外，如果想再提高TPS，建议增加下面几个配置
transientStorePoolEnable=true
transientStorePoolSize=2
如果你的服务器内存还比较富余，transientStorePoolSize可以配置到5

如果尝试配置还不能解决你的问题，烦请下次把你broker的所有配置都贴出来！

**Comment by freesky100** [comment]
这个问题主要关注IO和内存。iostat、和store.log中的[NOTIFY]日志，查看内存耗时。io可以使用deadline。最主要还是机器性能，之前由于虚拟问题，io、内存影响特别大。

**Comment by Force-King** [comment]
> 在tps不到100的情况下，还出现serverbusy，你的服务器的配置可能不是很高，sendMessageThreadPoolNums这个值不宜配置这么多，另外lizhanhui大神已经建议过，在同步刷盘模式下，建议把waitTimeMillsInSendQueue适当调整大一点。
> 可以试试下面的参数
> sendMessageThreadPoolNums=16
> useReentrantLockWhenPutMessage=true
> waitTimeMillsInSendQueue=500
> 
> 另外，如果想再提高TPS，建议增加下面几个配置
> transientStorePoolEnable=true
> transientStorePoolSize=2
> 如果你的服务器内存还比较富余，transientStorePoolSize可以配置到5
> 
> 如果尝试配置还不能解决你的问题，烦请下次把你broker的所有配置都贴出来！

你好，我们MQ 机器是 4C 32G 的虚拟机，
JVM 配置：
`-Xmx10G -Xms10G -XX:+UseG1GC ` (这里只列出主要参数)
broker配置：
`brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
sendMessageThreadPoolNums=32
useReentrantLockWhenPutMessage=true
waitTimeMillsInSendQueue=400
transientStorePoolEnable=true`

TPS 300的情况下，偶尔还会报 broker busy 和 system busy。 
报错期间看监控，CPU 和 IO 都不高，请问参数有什么问题吗？ 哪里需要调整？非常感谢

**Comment by Kanepan** [comment]
> > 在tps不到100的情况下，还出现serverbusy，你的服务器的配置可能不是很高，sendMessageThreadPoolNums这个值不宜配置这么多，另外lizhanhui大神已经建议过，在同步刷盘模式下，建议把waitTimeMillsInSendQueue适当调整大一点。
> > 可以试试下面的参数
> > sendMessageThreadPoolNums=16
> > useReentrantLockWhenPutMessage=true
> > waitTimeMillsInSendQueue=500
> > 另外，如果想再提高TPS，建议增加下面几个配置
> > transientStorePoolEnable=true
> > transientStorePoolSize=2
> > 如果你的服务器内存还比较富余，transientStorePoolSize可以配置到5
> > 如果尝试配置还不能解决你的问题，烦请下次把你broker的所有配置都贴出来！
> 
> 你好，我们MQ 机器是 4C 32G 的虚拟机.
> `vm.swappiness=1`
> 
> JVM 配置：
> `-Xmx10G -Xms10G -XX:+UseG1GC `
> (这里只列出主要参数)
> 
> broker配置：
> 
> ```
> brokerRole=ASYNC_MASTER 
> flushDiskType=ASYNC_FLUSH
> sendMessageThreadPoolNums=32
> useReentrantLockWhenPutMessage=true
> waitTimeMillsInSendQueue=400
> transientStorePoolEnable=true
> ```
> 
> TPS 300的情况下，偶尔还会报 broker busy 和 system busy。
> 报错期间看监控，CPU 和 IO 都不高，请问参数有什么问题吗？ 哪里需要调整？非常感谢

waitTimeMillsInSendQueue=6000
osPageCacheBusyTimeOutMills=6000
按这样设置， 普通的云服务器磁盘IO都比较弱， ROKCET官方出厂的设置比较敏感，如果解决问题了麻烦反馈下。

**Comment by Force-King** [comment]
@Kanepan 
目前基本不报错了，我经过多次调整参数，观察对比，最终的调优方案，我做了个总结：[RocketMQ调优心得总结](https://blog.csdn.net/qq_27641935/article/details/106015319)
