### ISSUE TITLE
cannot change to slave

### ISSUE THREAD

**Issue by linjikun** [apache/rocketmq#3482]
1.in the master broker， net card disable 
禁用broker的master节点的服务器的网卡后
2.consume cannot change to slave
客户消费不能从master节点自动切换都slave节点

**Comment by duhenglucky** [comment]
@linjikun Which storage model are you using now? Raft or normal master/slave mode. If it is master/slave mode, after the network card disabled, check whether the master node is still registered with Nameserver? And you need to make sure that the read slave node configuration is enabled

**Comment by linjikun** [comment]
@duhenglucky thank you for your ask,this question is over.we use the normal master/slave mode,and create too many queue in a topic.the broker connection is group by queue,the connection will retry  after the network card disabled,due to delay switch to slave in 6 min

**Comment by vongosling** [comment]
DLedger mode has been verified to be successfully changed within 10 seconds, with our distributed system tools OpenChaos. https://github.com/openmessaging/openchaos

This is recommended mode after Apache RocketMQ 4.5.
