### ISSUE TITLE
批消息用户自定义Property，消费时自定义Property获取出错

### ISSUE THREAD

**Issue by NGLSL** [apache/rocketmq#3486]
**BUG REPORT**

1. Please describe the issue you observed:

发送批消息，在SendMessageHook中添加自定义用户Property

消费消息时，自定义的Property无法拿到，这个Property跑到timestamp中去了

版本：
Spring-rocketmq 2.2.1
Rocketmq 4.9.1

- What did you do (The steps to reproduce)?

发送消息：

```Java
 List<Message<String>> messageList = new ArrayList<>();
  for (int i = 0; i < 3; i++) {
      Message<String> message = MessageBuilder.withPayload("test_" + System.currentTimeMillis()).build();
      messageList.add(message);
  }
  rocketMQTemplate.syncSend("test_topic", messageList);
```

SendMessageHook：

```Java
Message message = context.getMessage();
message.putUserProperty("TestUserProperty", "xxxx");
```

发送消息添加的用户自定义Property

![Snipaste_2021-11-15_11-47-26](https://user-images.githubusercontent.com/40338580/141719311-b3bc3b5a-e4f7-4f40-aac6-04938464902b.png)

消费消息时，拿到的Properties不对

这个Property，跑到了timestamp中去了

![image](https://user-images.githubusercontent.com/40338580/141718922-6ac8609c-ca32-416b-b408-21d7ce112d3f.png)

2. Please tell us about your environment:

windows10

rocketmq 4.9.1

java8

**Comment by Git-Yang** [comment]
Please refer to ISSUE #3476, this issue is being resolved. You can first merge this patch into your test branch to verify it.

**Comment by NGLSL** [comment]
> Please refer to ISSUE #3476, this issue is being resolved. You can first merge this patch into your test branch to verify it.

测试发送批量消息，以及能获取到自定义的Propert😁
