### ISSUE TITLE
[benchmark] Benchmark cannot use custom AK/SK.

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#3487]
1. Please describe the issue you observed:
- Cannot use custom ak/sk, when using benchmark test,

2. Please tell us about your environment:
- rocketmq 4.9.2

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
- Support custom ak/sk parameters.

**Comment by odbozhou** [comment]
merged
