### ISSUE TITLE
[POP] When only consuming but not producing, the pull request may be held by broker

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq#3491]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
Consumers only consume messages and producers don't produce msgs.

- What did you expect to see?
Consumers consume msgs with a normal speed.

- What did you see instead?
 Consumers sometimes consume normally and sometimes are blocked. Consume TPS is less then 200 and obviously there is a problem

2. Please tell us about your environment:
Linux

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
I found that the reason may be related to `QueueLockManager` class.
- Client send `pop-msg` request to broker.
- Sometimes this request can success to get lock for queue, so return msgs immediately. But sometimes it can't get lock successfully，then the request will be put into `pollingMap`.
- The requests in `pollingMap` will be executed when new msgs for this topic arriving or timeout.

So for a topic，If no new msgs are produced, the consumers which subscribe it can't consume normally because their `pop-msg` requests may be held.

**Comment by cserwen** [comment]
I found that the `commitOffset` will also get lock . If I deleted related lines, the consumer can consume normally. Maybe this caused the lock competition to become more serious.
https://github.com/apache/rocketmq/blob/4506f34e24714ec4d6ac37babd8f096632fd6b1c/broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java#L343

**Comment by odbozhou** [comment]
I agree with you, but I think the main function of this lock is to save the offset scene at the time when the offset is rolled back, which is convenient for checking the problem, it does increase the lock competition. Do you have a better way to balance performance and problem site information?

**Comment by cserwen** [comment]
> I agree with you, but I think the main function of this lock is to save the offset scene at the time when the offset is rolled back, which is convenient for checking the problem, it does increase the lock competition. Do you have a better way to balance performance and problem site information?

I don't understand when the offset rollback will happen, so I can't get the effect of this lock.

**Comment by odbozhou** [comment]
org.apache.rocketmq.broker.processor.PopMessageProcessor#popMsgFromQueue   
Offset can also be submitted in this method, so not only the threads of PopBufferMergeService can submit offset.

**Comment by cserwen** [comment]
> org.apache.rocketmq.broker.processor.PopMessageProcessor#popMsgFromQueue Offset can also be submitted in this method, so not only the threads of PopBufferMergeService can submit offset.

Ok, how should we solve this problem?
