### ISSUE TITLE
RPCHook#doAfterRpcHooks  is useless?

### ISSUE THREAD

**Issue by codersfarm** [apache/rocketmq#3510]
1.Please describe the issue you observed:
`AclClientRPCHook`.class and  anonymous Inner Class in `BorokerController`.class implemente the interface `RPCHook`.
But the  implementae method is empty. Why processRequestCommand and invokeSync in  `BorokerController`.class call do afterRpcHooks?

![180409](https://user-images.githubusercontent.com/38873832/142522933-18e7eca6-bfb7-469b-aa6d-0dcdd7b4c139.png)
![180342](https://user-images.githubusercontent.com/38873832/142523018-187a8d0f-a268-46aa-9d11-b7c828850187.png)

2.Please tell us about your environment:
 win10  
rocketmq branch: devlelop

**Comment by Git-Yang** [comment]
It may not be used currently, but an expandable interface is reserved.

**Comment by codersfarm** [comment]
The client api call the method invokeSync in `NettyRemotingClient`class，it's not a good idea keep doAfterRpcHooks method here.
![Uploading 2021-11-19_144639.png…]()

**Comment by RongtongJin** [comment]
> NettyRemotingClient

What's your suggestion？
