### ISSUE TITLE
It is found that a certain broker continues to create a tcp connection and has been rebalanced

### ISSUE THREAD

**Issue by zhengtenghui** [apache/rocketmq#3513]
发现某一个broker一直被动创建tcp链接，导致cpu增长，导致该broker下部分topic的消费者的部分队列的位点被重置为最旧位点，异常日志： send a request command to channel </******> failed.
![企业微信截图_16373063641034](https://user-images.githubusercontent.com/52693968/142581436-8f71ecd2-63ba-4cbc-b946-4e58a3b4facc.png)

**Comment by zhengtenghui** [comment]
tcp链接监控。12点左右我kill掉进程了，所以没在创建链接
![企业微信截图_16373064498897](https://user-images.githubusercontent.com/52693968/142581612-e8da881a-944d-4bbf-8385-9f3af428b03d.png)

**Comment by dongeforever** [comment]
@zhengtenghui Could you provide more info, such as:
1. the broker version
2. the detailed log info from the start of the problem(broker.log, watermark.log)
3. the gc info related to the problem time
4. the stack info if you had run a jstack when found the problem

**Comment by dongeforever** [comment]
@RongtongJin @duhengforever This problem maybe caused by  "notifyConsumerIdsChange" in broker.

And the same time, the client "mqClientApiTimeout" is 3 * 1000 by default, which is too small.
The config  "clientCloseSocketIfTimeout" is true by default.
So the channel may be closed by the client when the client found timeout heartbeat

**Comment by zhengtenghui** [comment]
@dongeforever The broker version is 4.5.0；
broker.log
![企业微信截图_163764909520](https://user-images.githubusercontent.com/52693968/142980030-d31d65f1-3bf3-46be-bbf4-bb5d219f54c9.png)
watermark.log
![企业微信截图_16376492709079](https://user-images.githubusercontent.com/52693968/142980134-05af8af6-0846-4b7a-8686-6ddedddcccb7.png)
gc.log
![企业微信截图_1637649455676](https://user-images.githubusercontent.com/52693968/142980411-f66debb0-589e-4de0-a783-fb925ff7304e.png)
Because this is an online service, it was urgently restored at that time, and there was no stack information.
rocketmq_client.log has been lost

**Comment by zhengtenghui** [comment]
The most unacceptable thing is not the timeout, but the position of some consumer queues is automatically reset to the longest position, and then blocked.

**Comment by Git-Yang** [comment]
> The most unacceptable thing is not the timeout, but the position of some consumer queues is automatically reset to the longest position, and then blocked.

The consumption offset can be specified when the consumer group subscribes for the first time. The default is to start consumption from the latest offset.
![image](https://user-images.githubusercontent.com/30995057/142981659-c0e362df-c1dd-4533-a44a-a76b499eafae.png)

**Comment by zhengtenghui** [comment]
> 
The broker automatically resets those consumers who have started to consume and have been consuming for a long time, and only reset part of the queue.
For example, a consumer has 8 queues in broker a. Queue 5 of broker a is reset and blocked. The other queues are normal.

**Comment by dongeforever** [comment]
@zhengtenghui
 "Queue 5 of broker a is reset and blocked"

what do you mean by saying "blocked"?

Do you mean that queue 5 cannot advance anymore?
or 
do you mean that all msgs in queue 5 is consumed repeatly?
