### ISSUE TITLE
create topic error(Make sure the specified clusterName exists or the name server connected to is correct.TopicConfig)

### ISSUE THREAD

**Issue by Jamesmahaitao** [apache/rocketmq#3515]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:
   when i debug rocketmq,i started the NameserStartup and BrokerStartup,i execute the commond: **./mqadmin updateTopic -c DefaultCluster -n 127.0.0.1:9876 -t TopicTest** because i need run org.apache.rocketmq.example.quickstart.Producer.java to send TopicTest,but it throw an exception:

RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.InternalThreadLocalMap).
RocketMQLog:WARN Please initialize the logger system properly.
[error] Make sure the specified clusterName exists or the name server connected to is correct.TopicConfig [topicName=TopicTest, readQueueNums=8, writeQueueNums=8, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]%  
i am sure clusterName exists(becouse of brokerClusterName = DefaultCluster and broker started),but i don't know how to check whether name server connected to is correct.

- What did you do (The steps to reproduce)?

i see #2344 issue say edit storePathRootDir = D:/rocketmq-4.7.1/stroe,i add "storePathRootDir=****/Downloads/sourceCode/rocketmq-all-4.9.2/store(my rocketmq source code dir/store)",but i doesn't work(execute ./mqadmin updateTopic -c DefaultCluster -n 127.0.0.1:9876 -t TopicTest again)

- What did you expect to see?

create a topic "TopicTest" success

- What did you see instead?
-
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.InternalThreadLocalMap).
RocketMQLog:WARN Please initialize the logger system properly.
[error] Make sure the specified clusterName exists or the name server connected to is correct.TopicConfig [topicName=TopicTest, readQueueNums=8, writeQueueNums=8, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]%  

2. Please tell us about your environment:
MacOS: 11.4(Apple Silicon)
RokcetMQ:rocketmq-all-4.9.2

**Comment by RongtongJin** [comment]
What is the broker config setting of brokerClusterName? It should be DefaultCluster in your test

**Comment by Jamesmahaitao** [comment]
> What is the broker config setting of brokerClusterName? It should be DefaultCluster in your test

**brokerClusterName = DefaultCluster**
DefaultCluster this is default value and my broker.conf also is DefaultCluster

**Comment by Git-Yang** [comment]
> 1. ./mqadmin updateTopic -c DefaultCluster -n 127.0.0.1:9876 -t TopicTest

Check whether namesrv is connected normally through `telnet 127.0.0.1 9876`.

**Comment by Jamesmahaitao** [comment]
> > 1. ./mqadmin updateTopic -c DefaultCluster -n 127.0.0.1:9876 -t TopicTest
> 
> Check whether namesrv is connected normally through `telnet 127.0.0.1 9876`.

telnet 127.0.0.1 9876 is succeed,but when i start MQAdminStartup to run "updateTopic -c DefaultCluster -n 127.0.0.1:9876 -t TopicTest",it sometimes raise up an exception that:

Caused by: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: **send request to <127.0.0.1:9876> failed**
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:440)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:377)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerClusterInfo(MQClientAPIImpl.java:1335)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineBrokerClusterInfo(DefaultMQAdminExtImpl.java:327)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineBrokerClusterInfo(DefaultMQAdminExt.java:258)
	at org.apache.rocketmq.tools.command.CommandUtil.fetchMasterAddrByClusterName(CommandUtil.java:83)
	at org.apache.rocketmq.tools.command.topic.UpdateTopicSubCommand.execute(UpdateTopicSubCommand.java:158)

sometimes print the message:"[error] Make sure the specified clusterName exists or the name server connected to is correct" in console.

very confused.  i guess the connection have problem between broker and name server.

**Comment by Jamesmahaitao** [comment]
i add this line 
`System.setProperty(MixAll.NAMESRV_ADDR_PROPERTY, "127.0.0.1:9876");`
to BrokerStartup#createBrokerController,it works. confirmed my suspicion
