### ISSUE TITLE
4.9.2-realease Producer Demo get a Console bug

### ISSUE THREAD

**Issue by tansuoboy** [apache/rocketmq#3519]
当我使用RocketMQ4.9.2-realease版本依赖的时候，Producer发送同步消息的Demo出现了一些不可预料的问题，消息发送成功，但是IDEA的控制台未关闭，一直有一个线程在那儿，看了一下代码，producer.shutdown()已经调用完成，但是控制台依旧开启。

**Comment by Git-Yang** [comment]
The problem has been fixed in PR https://github.com/apache/rocketmq/pull/3454.
