### ISSUE TITLE
It is better to specify the initialCapacity when initializing a HashMap as a local variable that will not add elements  in the future

### ISSUE THREAD

**Issue by XiaoyiPeng** [apache/rocketmq#3533]
**BUG REPORT**

1. Please describe the issue you observed:
  
   When initializing a HashMap as a local variable that will not add elements  in the future, it is better to specify the `initialCapacity`.  

    The code in class  `org.apache.rocketmq.broker.filter.MessageEvaluationContext#keyValues` shown below is better.

```java
public Map<String, Object> keyValues() {
        if (properties == null) {
            return null;
        }

        Map<String, Object> copy = new HashMap<String, Object>(properties.size(), 1);

        for (String key : properties.keySet()) {
            copy.put(key, properties.get(key));
        }

        return copy;
    }
```

2. Please tell us about your environment:

    Windows10

**Comment by vicya** [comment]
some advices.  If there are for four elements ,the capacity should be larger than four to prevent expansion

**Comment by XiaoyiPeng** [comment]
> some advices. If there are for four elements ,the capacity should be larger than four to prevent expansion

Use the style of the previous code(like` org.apache.rocketmq.broker.filter.MessageEvaluationContext#keyValues()` ), the `loadFactor` of `HashMap` has been set to 1 and will not be expanded.
