### ISSUE TITLE
Can RocketMQ use centralized storage to ensure syncflush?

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#3536]
version:4.9.1

In the discussion of pull request#3382, areyouok mentioned that this.mappedByteBuffer.force() has the following 

limitations:
"If the file does not reside on a local device then no such guarantee is made"
Does this mean that 

RocketMQ can only use local hard drives to ensure syncflush?Can I use centralized storage, such as HDS, EMC, etc.

I understand that the meaning of this sentence should be that if centralized storage is used, the storage 

guarantees the reliability of flush. If centralized storage cannot be used, RocketMQ's architecture choices will 

be very limited.

**Comment by duhenglucky** [comment]
@iamqq23ue I agree with you that if you can strengthen the synchronization flush process, RocketMQ can run on a variety of centralized storage in a single replica mode. While reducing costs, also makes RocketMQ easier to operate and maintain. Looking forward to you more the opinion of this issue.

**Comment by iamqq23ue** [comment]
In fact, I don't quite understand, what does "If the file does not reside on a local device then no such guarantee is made" mentioned in the description of mappedByteBuffer.force() mean?
Have you studied this method?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 晚上8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Can RocketMQ use centralized storage to ensure syncflush? (Issue #3536)





 
@iamqq23ue I agree with you that if you can strengthen the synchronization flush process, RocketMQ can run on a variety of centralized storage in a single replica mode. While reducing costs, also makes RocketMQ easier to operate and maintain. Looking forward to you more the opinion of this issue.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamqq23ue** [comment]
If I use SAN storage instead of local disks, will I get OK before the data is placed on the disk?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 晚上8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Can RocketMQ use centralized storage to ensure syncflush? (Issue #3536)





 
@iamqq23ue I agree with you that if you can strengthen the synchronization flush process, RocketMQ can run on a variety of centralized storage in a single replica mode. While reducing costs, also makes RocketMQ easier to operate and maintain. Looking forward to you more the opinion of this issue.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guyinyou** [comment]
As far as I know, storage methods such as cloud disks provide reliability guarantees. Of course, there is no need to "force"

**Comment by guyinyou** [comment]
This is equivalent to the separation of storage and calculation. Of course, the computing node will be well maintained, but in essence it just transfers the maintenance work to the storage node. But the structure of separation of storage and computing is of course also beneficial, at least it is more decoupled and flexible, and overall maintenance will reduce the problems caused by coupling.

**Comment by guyinyou** [comment]
If I remember correctly, rocketmq5.0 will provide a separate storage and computing deployment method, which may be similar to the centralized storage you mentioned.
