### ISSUE TITLE
fix PullConsumer notes wrong

### ISSUE THREAD

**Issue by mrhbj** [apache/rocketmq#3543]
it is a minor question,I  advise fix it.

            executors.execute(new Runnable() {

                public void doSomething(List<MessageExt> msgs) {
                    //do you business

                }

**Comment by duhenglucky** [comment]
@mrhbj would you like submit a PR to fix it?

**Comment by mrhbj** [comment]
@duhenglucky yes,I have push a pr to fix it #3544
