### ISSUE TITLE
Bootstrap handler  Is it necessary？

### ISSUE THREAD

**Issue by mrhbj** [apache/rocketmq#3545]
NettyRemotingClient.java 
       Bootstrap handler = this.bootstrap.group(this.eventLoopGroupWorker).channel(NioSocketChannel.class)
            .option(ChannelOption.TCP_NODELAY, true)
            .option(ChannelOption.SO_KEEPALIVE, false)
            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, nettyClientConfig.getConnectTimeoutMillis())
            .option(ChannelOption.SO_SNDBUF, nettyClientConfig.getClientSocketSndBufSize())
            .option(ChannelOption.SO_RCVBUF, nettyClientConfig.getClientSocketRcvBufSize())
            .handler(new ChannelInitializer<SocketChannel>() {
                @Override
                public void initChannel(SocketChannel ch) throws Exception {
                    ChannelPipeline pipeline = ch.pipeline();
                    if (nettyClientConfig.isUseTLS()) {
                        if (null != sslContext) {
                            pipeline.addFirst(defaultEventExecutorGroup, "sslHandler", sslContext.newHandler(ch.alloc()));
                            log.info("Prepend SSL handler");
                        } else {
                            log.warn("Connections are insecure as SSLContext is null!");
                        }
                    }
                    pipeline.addLast(
                        defaultEventExecutorGroup,
                        new NettyEncoder(),
                        new NettyDecoder(),
                        new IdleStateHandler(0, 0, nettyClientConfig.getClientChannelMaxIdleTimeSeconds()),
                        new NettyConnectManageHandler(),
                        new NettyClientHandler());
                }
            });
Bootstrap handler  Is it necessary？ because it look like not used this handler name！

**Comment by lizhiboo** [comment]
> ```
>    NettyRemotingClient.java 
>    Bootstrap handler = this.bootstrap.group(this.eventLoopGroupWorker).channel(NioSocketChannel.class)
>         .option(ChannelOption.TCP_NODELAY, true)
>         .option(ChannelOption.SO_KEEPALIVE, false)
>         .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, nettyClientConfig.getConnectTimeoutMillis())
>         .option(ChannelOption.SO_SNDBUF, nettyClientConfig.getClientSocketSndBufSize())
>         .option(ChannelOption.SO_RCVBUF, nettyClientConfig.getClientSocketRcvBufSize())
>         .handler(new ChannelInitializer<SocketChannel>() {
>             @Override
>             public void initChannel(SocketChannel ch) throws Exception {
>                 ChannelPipeline pipeline = ch.pipeline();
>                 if (nettyClientConfig.isUseTLS()) {
>                     if (null != sslContext) {
>                         pipeline.addFirst(defaultEventExecutorGroup, "sslHandler", sslContext.newHandler(ch.alloc()));
>                         log.info("Prepend SSL handler");
>                     } else {
>                         log.warn("Connections are insecure as SSLContext is null!");
>                     }
>                 }
>                 pipeline.addLast(
>                     defaultEventExecutorGroup,
>                     new NettyEncoder(),
>                     new NettyDecoder(),
>                     new IdleStateHandler(0, 0, nettyClientConfig.getClientChannelMaxIdleTimeSeconds()),
>                     new NettyConnectManageHandler(),
>                     new NettyClientHandler());
>             }
>         });
> ```
> 
> Bootstrap handler Is it necessary？ because it look like not used this handler name！

variable handler is not used indeed, but bootstrap is configured after this running this code.

**Comment by mrhbj** [comment]
> > ```
> >    NettyRemotingClient.java 
> >    Bootstrap handler = this.bootstrap.group(this.eventLoopGroupWorker).channel(NioSocketChannel.class)
> >         .option(ChannelOption.TCP_NODELAY, true)
> >         .option(ChannelOption.SO_KEEPALIVE, false)
> >         .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, nettyClientConfig.getConnectTimeoutMillis())
> >         .option(ChannelOption.SO_SNDBUF, nettyClientConfig.getClientSocketSndBufSize())
> >         .option(ChannelOption.SO_RCVBUF, nettyClientConfig.getClientSocketRcvBufSize())
> >         .handler(new ChannelInitializer<SocketChannel>() {
> >             @Override
> >             public void initChannel(SocketChannel ch) throws Exception {
> >                 ChannelPipeline pipeline = ch.pipeline();
> >                 if (nettyClientConfig.isUseTLS()) {
> >                     if (null != sslContext) {
> >                         pipeline.addFirst(defaultEventExecutorGroup, "sslHandler", sslContext.newHandler(ch.alloc()));
> >                         log.info("Prepend SSL handler");
> >                     } else {
> >                         log.warn("Connections are insecure as SSLContext is null!");
> >                     }
> >                 }
> >                 pipeline.addLast(
> >                     defaultEventExecutorGroup,
> >                     new NettyEncoder(),
> >                     new NettyDecoder(),
> >                     new IdleStateHandler(0, 0, nettyClientConfig.getClientChannelMaxIdleTimeSeconds()),
> >                     new NettyConnectManageHandler(),
> >                     new NettyClientHandler());
> >             }
> >         });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Bootstrap handler Is it necessary？ because it look like not used this handler name！
> 
> variable handler is not used indeed, but bootstrap is configured after this running this code.

yes, I agree.

**Comment by mrhbj** [comment]
#3546
