### ISSUE TITLE
a question about MQFaultStrategy

### ISSUE THREAD

**Issue by ZZhongge** [apache/rocketmq#3548]
```
  int writeQueueNums = tpInfo.getQueueIdByBroker(notBestBroker);
  if (writeQueueNums > 0) {
      final MessageQueue mq = tpInfo.selectOneMessageQueue();
      if (notBestBroker != null) {
          mq.setBrokerName(notBestBroker);
          mq.setQueueId(tpInfo.getSendWhichQueue().incrementAndGet() % writeQueueNums);
      }
      return mq;
      } else {
         latencyFaultTolerance.remove(notBestBroker);
}
```
why does it modify the metadata in TopicPublishInfo instead of constructing a new one?
does it influence other thread by selecting an unexpected message queue?

**Comment by ni-ze** [comment]
Actually，It's  purpose is reserve which broker is send this time in topicpublishInfo. It will be compared, using brokerName ,when select MQ next time. so can not construct a new one.

**Comment by ZZhongge** [comment]
Suppose that you have a message queue list like [(brokerA, 0), (brokerA, 1),  (brokerB, 0), (brokerB, 1)], atLeastPickOne return brokerA, and  (brokerB, 1) return from tpInfo.selectOneMessageQueue. In this situation, (brokerB, 1) might be changed to (brokerA, 4 % 2), which result in the total list [(brokerA, 0), (brokerA, 1),  (brokerB, 0), (brokerA, 0)]. It is an extreme case when all brokers are unavaliable and will be corrected by next term of fetching topic info. But it may be confusing.Thanks for your anwser.

**Comment by ni-ze** [comment]
In this situation, (brokerB, 1) might be changed to (brokerA, 4 % 2), which result in the total list [(brokerA, 0), (brokerA, 1), (brokerB, 0), (brokerA, 0)].
------------
(brokerB, 1) changed to (brokerA, $nextInt % 2), it will be (brokerA, 0) or (brokerA, 1) finally. this list record which MQ was used to send message. If not in this list, it mean this MQ  was Not recommended. It is an extreme case, if all MQ is same, it mean only one MQ is available.

**Comment by ZZhongge** [comment]
Thanks for your answer, I have understood the intention of this design. Thank you.
