### ISSUE TITLE
Quick start with docker and k8s

### ISSUE THREAD

**Issue by duhenglucky** [apache/rocketmq#3549]
With the advent of containerization and the k8s era, more and more developers and end-users have begun to use docker or k8s to deliver RocketMQ clusters, but the quickstart on the official website currently only has samples with shell script startup. Therefore, it is necessary to supplement the cluster startup mode with docker and k8s operator.

**Comment by gogodjzhu** [comment]
I am new to commit any change to open source project. Wish to start from rocketmq. Here are some questions about this issue:
1. what kind of docs  should I add or modify. Add a new chapter on `docs/en/README.md` ?
2. what kind of content should I provide. A `docker-compose.yml` for startup with docker?

Wait for your reply and advise for fresh contributor :)

**Comment by duhenglucky** [comment]
> 

@gogodjzhu thanks for your attention,
1. Just add a new chapter on docs/en/README.md and add a doc in the [rocketmq-site ](https://github.com/apache/rocketmq-site)at the same time.
2. Actually RocketMQ docker images have been pushed to [docker hub](https://hub.docker.com/repository/docker/apache/rocketmq), the [docker repo ](https://github.com/apache/rocketmq-docker) and [operator](https://github.com/apache/rocketmq-operator) in here, so just provide docs to describe how to use the operator or docker image to run the rocketmq cluster.

**Comment by gogodjzhu** [comment]
@duhenglucky Then I think I can do this :) Please assign this issue to me.
