### ISSUE TITLE
"ecosytem" seems a typo in Readme file.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#3550]
Versatile big-data and streaming ecosytem integration

**Comment by Allenen** [comment]
I will resolve the problem, could you assign it to me?@ShannonDing

**Comment by ShannonDing** [comment]
> I will resolve the problem, could you assign it to me?@ShannonDing

Welcome, assigned.

**Comment by NAMANIND** [comment]
@Allenen are you working on this or I ask to assign me because I will gonna do it just now.

**Comment by duhenglucky** [comment]
> @Allenen are you working on this or I ask to assign me because I will gonna do it just now.
@NAMANIND Just go ahead，submit a PR to fix it

**Comment by fujian-zfj** [comment]
> > @Allenen are you working on this or I ask to assign me because I will gonna do it just now.
> > @NAMANIND Just go ahead，submit a PR to fix it

I am working on it, a PR is undergoing......
