### ISSUE TITLE
CloneGroupOffsetCommd is not clone consumer offset

### ISSUE THREAD

**Issue by lushilin** [apache/rocketmq#3551]
**BUG REPORT**
Use CloneGroupOffsetCommand to clone offset between two consumerGroup is not helpful
![image](https://user-images.githubusercontent.com/17663472/143996739-67f462d7-21cf-4403-a02e-395438559b61.png)
just clone brokerOffset not consumerOffset

**Comment by lushilin** [comment]
PullRequest link: https://github.com/apache/rocketmq/pull/3552

**Comment by RongtongJin** [comment]
Merged
