### ISSUE TITLE
Clear spelling errors in comments in quickstart.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#3558]
some comments seems typo in example/quickstart/Consumer.java
such as:
 
Specify where to start in case the specified consumer group is a brand new one.

Subscribe one more more topics to consume.
 
Register callback to execute on arrival of messages fetched from brokers.

**Comment by NAMANIND** [comment]
I will do this please assign this work to me.

**Comment by ShannonDing** [comment]
> I will do this please assign this work to me.

Great，welcome.
