### ISSUE TITLE
Make sure the list of message queues is not null before using selecting a queue. in orderly message sending example.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#3559]
in example/ordermessage/producer.java.
make sure message queue is not null before using selecting a queue.
```
SendResult sendResult = producer.send(msg, new MessageQueueSelector() {
       @Override
        public MessageQueue select(List<MessageQueue> mqs, Message msg, Object arg) {
        Integer id = (Integer) arg;
        int index = id % mqs.size();
        return mqs.get(index);
       }
 }, orderId);
```
if the mqs is null, mqs.size() may be crash.

**Comment by clbigdata** [comment]
please assign this work to me.

**Comment by ShannonDing** [comment]
> please assign this work to me.

Welcome. assigned.

**Comment by ShannonDing** [comment]
ping @clbigdata

**Comment by devfat** [comment]
@ShannonDing 
The main process of sending message is in method org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl#sendSelectImpl.

The `topicPublishInfo.ok()` is called before calling MessageQueueSelector#select, what any else situation will cause the empty   message queue list?

**Comment by meateggmilk** [comment]
@devfat you are right

**Comment by acmday** [comment]
So, this issue  can be closed,right?

**Comment by shy-share** [comment]
> So, this issue can be closed,right?

@ShannonDing
