### ISSUE TITLE
Consuming messages with namespace always failed in the example.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#3561]
see: [PushConsumerWithNamespace](https://github.com/apache/rocketmq/blob/master/example/src/main/java/org/apache/rocketmq/example/namespace/PushConsumerWithNamespace.java)
it always return RECONSUME_LATER in the listener.
```

defaultMQPushConsumer.registerMessageListener((MessageListenerConcurrently)(msgs, context) -> {
            msgs.stream().forEach((msg) -> {
                System.out.printf("Msg topic is:%s, MsgId is:%s, reconsumeTimes is:%s%n", msg.getTopic() , msg.getMsgId(), msg.getReconsumeTimes());
            });
            return ConsumeConcurrentlyStatus.RECONSUME_LATER;
        });
```

**Comment by bcat4490** [comment]
Can you assign this to me? Let me know, thanks.

**Comment by bcat4490** [comment]
@ShannonDing Can you assign this to me? Let me know, thanks.

**Comment by ShannonDing** [comment]
> @ShannonDing Can you assign this to me? Let me know, thanks.

yes, welcome.

**Comment by devfat** [comment]
In my option, it return `ConsumeConcurrentlyStatus.CONSUME_SUCCESS` will  not failed, or add `context.setDelayLevelWhenNextConsume`. however, the [commit#3884536c38e06742aec4c12d29a4f9e3e7c5ecbf](https://github.com/apache/rocketmq/commit/3884536c38e06742aec4c12d29a4f9e3e7c5ecbf#diff-b316776549ce0cba494ce6a426d6fdba78f81c6aac58a138246884930806ea72) indicate that the `ConsumeConcurrentlyStatus.RECONSUME_LATER` is especially. 

What are the expected results in the example?
