### ISSUE TITLE
Enclose namesrvAddr in example of mqadmin tool by quotation marks

### ISSUE THREAD

**Issue by caigy** [apache/rocketmq#3564]
The help info of mqadmin (clusterList for example) like this:

> $bash mqadmin help clusterList
> OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
> OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
> usage: mqadmin clusterList [-c <arg>] [-h] [-i <arg>] [-m] [-n <arg>]
>  -c,--clusterName <arg>   which cluster
>  -h,--help                Print help
>  -i,--interval <arg>      specify intervals numbers, it is in seconds
>  -m,--moreStats           Print more stats
>  -n,--namesrvAddr <arg>   Name server address list, **eg: 192.168.0.1:9876;192.168.0.2:9876**

I found that the example of namesrvAddr field is missing quotation marks, so a beginner may encounter such error message:

> $bash mqadmin clusterList 192.168.0.1:9876;192.168.0.2:9876
> bash: 192.168.0.2:9876: command not found

In my option, `namesrvAddr` should be enclosed by `''`, in the help info of mqadmin and [documents](https://rocketmq.apache.org/docs/cli-admin-tool/). That would be more friendly to new beginners.

**Comment by HScarb** [comment]
Can you assign this to me? 
I have created two PRs on rocketmq repository and rocketmq-site repository
