### ISSUE TITLE
Useless class file  MessageFilterImpl

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq#3565]
see: [MessageFilterImpl](https://github.com/apache/rocketmq/blob/5.0.0-alpha/example/src/main/resources/MessageFilterImpl.java)

It is a useless file, it can be removed.
![image](https://user-images.githubusercontent.com/31175234/144180391-53641ad3-a347-4c0d-aebc-d686d27add2e.png)

**Comment by TakshakRamteke** [comment]
hello @duhenglucky,
may i work on this one

**Comment by duhenglucky** [comment]
@TakshakRamteke Welcome，go ahead
