### ISSUE TITLE
关于docs/cn/best_practice.md中对2.1消费过程幂等的描述疑问

### ISSUE THREAD

**Issue by wendell-dev** [apache/rocketmq#3574]
文档中原文：

msgId一定是全局唯一标识符，但是实际使用中，可能会存在相同的消息有两个不同msgId的情况（**消费者主动重发**、因客户端重投机制导致的重复等），这种情况就需要使业务字段进行重复消费。

-----------------------------------------------------------------
这里的 [消费者主动重发] 应该是生产者主动重发吧？

**Comment by panzhi33** [comment]
应该是消费者消费失败进行的重发
