### ISSUE TITLE
Spelling mistake in getter/setter method of mQClientFactory

### ISSUE THREAD

**Issue by ferrirW** [apache/rocketmq#3579]
1. Please describe the issue you observed:

There should be spelling getMqClientFactory or getMQClientFactory

![image](https://user-images.githubusercontent.com/42178996/144743509-c18312e6-5b73-43a4-bb07-e6ca9565981b.png)

2. Please tell us about your environment:
4.9.2

**Comment by ferrirW** [comment]
fix by pr #3581

**Comment by RongtongJin** [comment]
Merge

**Comment by areyouok** [comment]
This method is public and now break compatibility. 

Can we rollback it?

**Comment by areyouok** [comment]
@duhenglucky @RongtongJin

**Comment by RongtongJin** [comment]
> 

It seems that no relevant interface is exposed to the user

**Comment by shuangchengsun** [comment]
![image](https://user-images.githubusercontent.com/33629004/145582633-165b2149-e96f-440b-8091-ad0a07637fcb.png)
no, we use it in our project.

**Comment by ShannonDing** [comment]
it's better to add a new method like ”getClientFactory“  and make the current "getmQClientFactory" deprecated.
