### ISSUE TITLE
搭建多dLegerGroup集群

### ISSUE THREAD

**Issue by seedscoder** [apache/rocketmq#3582]
请问：一个brokerClusterName下是否支持多个dLegerGroup（每个dLegerGroup名称和brokerName相同），如果可以，dLegerPeers中的端口和RocketMQ默认的10911/10912/10909有没有啥关系？

**Comment by duhenglucky** [comment]
@seedscoder 暂时不支持多个group，如果有兴趣的话，可以提个 Proposal

**Comment by vongosling** [comment]
https://github.com/openmessaging/dledger/issues/82
