### ISSUE TITLE
Can RocketMQ be started in read-only mode?

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#3583]
I know that after RocketMQ is started, you can use the mqadmin command to set the readonly permission. But after startup, before executing the mqadmin command, there is no guarantee that no messages will be written.
I would like to ask whether it is possible to directly start RocketMQ in readonly mode?

**Comment by panzhi33** [comment]
Rocketmq can be started in read-only mode

**Comment by iamqq23ue** [comment]
May I ask how to start with readonly mode，thks？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Can RocketMQ be started in read-only mode? (Issue #3583)





 
Rocketmq can be started in read-only mode
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamqq23ue** [comment]
I got it, thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Can RocketMQ be started in read-only mode? (Issue #3583)





 
Rocketmq can be started in read-only mode
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
