### ISSUE TITLE
文档描述设计篇疑问

### ISSUE THREAD

**Issue by EiletXie** [apache/rocketmq#3584]
![image](https://user-images.githubusercontent.com/40811782/144815528-5e5e9f46-e23f-4c8c-a434-c4a33920bf0e.png)

   ConsumeQueue索引存储的就是commitLog的offset，应该是一级索引才对

**Comment by guyinyou** [comment]
Uniquely determine a message through Topic, queueID, and offset. Topic and queueID are determined in the form of filePath, so maybe filePath is the first level index?

**Comment by EiletXie** [comment]
Thank you for your reply!
Can i understand that we get the ConsumerQueue filePath by the topic ,queueID,this is the first level index,
then we use offset to find  the disk location of  commitlog,this is the second level index.
so The meaning of the secondary index here is different from that of the database?

**Comment by guyinyou** [comment]
This is just my understanding, but I think it is very reasonable. After all, it lacks topic and queue information.
