### ISSUE TITLE
Improve performance for 4.9.2

### ISSUE THREAD

**Issue by areyouok** [apache/rocketmq#3585]
We have some performance improvements based on 4.9.2

1. [Part A] eliminate reverse DNS lookup in MessageExt
2. [Part B] Improve header encode/decode performance
3. [Part B] Improve RocketMQSerializable performance with zero-copy
4. [Part C] cache result for parseChannelRemoteAddr()
5. [Part D] improve performance of createUniqID()
6.  [Part E] eliminate duplicated getNamespace() call when where is no namespace
7. [Part F] eliminate regex match in topic/group name check
8. [Part G] [Work in progress] support send batch message with different topic/queue
9. [Part H] eliminate StringBuilder auto resize in PullRequestHoldService.buildKey() when topic length is greater than 14, this method called twice for each message.
10. [Part I] Avoid unnecessary StringBuffer resizing and String Formatting
11. [Part J] Use mmap buffer instead of FileChannel when writing consume queue and slave commit log, which greatly speed up consume tps.
12. [Part K](https://github.com/apache/rocketmq/pull/3659) move execution of notifyMessageArriving() from ReputMessageService thread to PullRequestHoldService thread. 

These commits almost eliminate bad performance methods in the cpu flame graph in producer side.

**Comment by areyouok** [comment]
Part A to F is complete. Unit test fixed.

**Comment by kimmking** [comment]
About Part J:
Actually, mmap is better than fileChannel in small size message case. In large scale size message, fileChannel is more better.
There could be an option to switch mmap/fileChannel.
See https://www.jianshu.com/p/d0b4ac90dbcb
