### ISSUE TITLE
Unnecessary boxing of primitives in org.apache.rocketmq.broker.transaction.queue.TransactionalMessageServiceImpl

### ISSUE THREAD

**Issue by caigy** [apache/rocketmq#3587]
In method `private Long getLong(String s)` and `private Integer getInt(String s)` of  `org.apache.rocketmq.broker.transaction.queue.TransactionalMessageServiceImpl`, a boxed numeric primitive is created from `String`, and then unboxed.

For example, ` v = Integer.valueOf(s)` (`v` is of type `int`), it would be more efficient to use `Integer.parseInt()`, which returns a primitive value directly.

**Comment by zhaohai1299002788** [comment]
#3596

**Comment by ShannonDing** [comment]
done.
