### ISSUE TITLE
Inefficient iteration of Map

### ISSUE THREAD

**Issue by caigy** [apache/rocketmq#3593]
There are several inefficient iterations of Map, in such code, `keySet()` is retrieved from Map firstly, and values are got in each iteration by key.  In my opinion, `entrySet()` should be used, so that keys and values can be fetched in one time.

For example, in `org.apache.rocketmq.common.Configuration#merge`:
>     private void merge(Properties from, Properties to) {
>         for (Object key : from.keySet()) {
>             Object fromObj = from.get(key), toObj = to.get(key);
>             if (toObj != null && !toObj.equals(fromObj)) {
>                 log.info("Replace, key: {}, value: {} -> {}", key, toObj, fromObj);
>             }
>             to.put(key, fromObj);
>         }
>     }

Some other examples: 
- `org.apache.rocketmq.broker.filter.ConsumerFilterManager#unRegister`
- `org.apache.rocketmq.broker.filter.MessageEvaluationContext#keyValues`
- `org.apache.rocketmq.common.Configuration#mergeIfExist`

**Comment by zhaohai1299002788** [comment]
#3595

**Comment by Git-Yang** [comment]
Merged
