### ISSUE TITLE
Dledger Commitlog put batch msgs stats has bug

### ISSUE THREAD

**Issue by Zanglei06** [apache/rocketmq#3601]
dledger commitlog put batch msgs stats is incorrect.

![image](https://user-images.githubusercontent.com/4166897/145161513-dd53bfbf-8f3e-4614-9372-fc5aaa14679c.png)

**Comment by Zanglei06** [comment]
check out this pr #3600 that fix the bug.

**Comment by RongtongJin** [comment]
Merged
