### ISSUE TITLE
公网配置了，如何保证安全，TLS怎么配置，有文档吗？

### ISSUE THREAD

**Issue by jiangxingang** [apache/rocketmq#361]
公网配置了，如何保证安全，TLS怎么配置，有文档吗？

**Comment by lizhanhui** [comment]
Have a look at this page: https://github.com/apache/rocketmq-site/pull/19/files

Alternatively, if you want to implement access-key/secret security, you may implement RPC stub.

**Comment by vongosling** [comment]
@jiangxingang If you have any question, please send your question to user mail list. http://rocketmq.apache.org/about/contact/. Issue is no an appropriate place for your question.

**Comment by Yarollingstone** [comment]
> Have a look at this page: https://github.com/apache/rocketmq-site/pull/19/files
> 
> Alternatively, if you want to implement access-key/secret security, you may implement RPC stub.

我按照您给的方案试着在启动脚本里配置了环境变量，但是在启动日志里，其仍然以默认模式运行。而且读不到我的配置文件。能否可以给出一个完整的案例，因为实际运用中，安全传输是很有必要的。
![image](https://user-images.githubusercontent.com/40456822/60196059-e823de00-986e-11e9-9d38-8f0754b81386.png)
![image](https://user-images.githubusercontent.com/40456822/60196156-19041300-986f-11e9-86bd-9a9872014824.png)
