### ISSUE TITLE
query message by key, expect to see null, but receive one message

### ISSUE THREAD

**Issue by xijiu** [apache/rocketmq#3613]
**BUG REPORT**

issue describe:

- create two topic:`AaTopic`and`BBTopic `, send a message to topic-`AaTopic` with message key `Aa`, and send a message to topic-`BBTopic` with message key `BB`. Then query message by key, topic and key are `AaTopic`-`BB`, expect to see null, but i receive **ONE** message

![image](https://user-images.githubusercontent.com/19780771/145506070-67a21f4b-f0c7-41e2-8759-8637b60c1f9c.png)

environment:

- version 4.9.2

**Comment by xijiu** [comment]
I've fixed it

[PR](https://github.com/apache/rocketmq/pull/3614)

**Comment by HScarb** [comment]
Did you figure out what's the reason of this problem?

**Comment by odbozhou** [comment]
merged
