### ISSUE TITLE
Why does case SLAVE_NOT_AVALIABLE roll back when sending transaction messages

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#3617]
version：4.9.1

An abnormality of the broker slave will cause many messages to fail to be sent.

And because the client does not automatically resend the message, you need to write code to resend the message, so the message may still be sent to the abnormal broker.

**Comment by panzhi33** [comment]
SLAVE_NOT_AVAILABLE is returned, the message is still sent successfully, and the client does not need to reissue

**Comment by iamqq23ue** [comment]
&nbsp;public TransactionSendResult sendMessageInTransaction


&nbsp;case SLAVE_NOT_AVAILABLE:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; localTransactionState = LocalTransactionState.ROLLBACK_MESSAGE;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; break;



According to the above code, the transaction message will be rolled back when SLAVE_NOT_AVAILABLE




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 下午4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Why does case SLAVE_NOT_AVALIABLE roll back when sending transaction messages (Issue #3617)





 
SLAVE_NOT_AVAILABLE is returned, the message is still sent successfully, and the client does not need to reissue
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by panzhi33** [comment]
> public TransactionSendResult sendMessageInTransaction case SLAVE_NOT_AVAILABLE: localTransactionState = LocalTransactionState.ROLLBACK_MESSAGE; break; According to the above code, the transaction message will be rolled back when SLAVE_NOT_AVAILABLE

yes，I didn't look carefully. I feel that the design here is not very reasonable. In org.apache.rocketmq.broker.processor.EndTransactionProcessor#sendFinalMessage, SLAVE_NOT_AVAILABLE is successful. And other message types are also successful by default. I think it needs to be unified here

**Comment by shuangchengsun** [comment]
I also noticed this.  in the issue #1390 this problem has been discussed. However, this issue(#1390 ) did not attract attention at the time. Based on this situation, we fix this problem with a switch which controls the transaction message ignore slave error. maybe I can create a PR to fix it.

**Comment by Git-Yang** [comment]
IMO, for the client, SLAVE_NOT_AVAILABLE is returned when sending a transaction message. At this time, the message has been successfully written to the master, and the client can resend it after ROLLBACK_MESSAGE.
For Broker, after receiving the commit message sent by the client, if SLAVE_NOT_AVAILABLE occurs, the commit message has been written to the master at this time, so it will automatically synchronize after the slave is restored, otherwise it will not make any sense to resend the commit after the return fails. .

**Comment by iamqq23ue** [comment]
I think that when the client receives a SLAVE_NOT_AVAILABLE, the client must resend the message, and it may still be sent to the abnormal broker.
Therefore I think that the message should not be returned when SLAVE_NOT_AVAILABLE.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Why does case SLAVE_NOT_AVALIABLE roll back when sending transaction messages (Issue #3617)





 
IMO, for the client, SLAVE_NOT_AVAILABLE is returned when sending a transaction message. At this time, the message has been successfully written to the master, and the client can resend it after ROLLBACK_MESSAGE.
 For Broker, after receiving the commit message sent by the client, if SLAVE_NOT_AVAILABLE occurs, the commit message has been written to the master at this time, so it will automatically synchronize after the slave is restored, otherwise it will not make any sense to resend the commit after the return fails. .
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
