### ISSUE TITLE
deploy ha cluster: Slave fall behind master: 180 bytes

### ISSUE THREAD

**Issue by shibd** [apache/rocketmq#362]
deploy ha cluster: 1master-1slave-async

master logs broker.log : Slave fall behind master: 180 bytes
send on message, observation slave store nofind commitlog and consumequeue files

master-broker.properties
```
brokerClusterName=m-s-sync
brokerName=208-master
brokerId=0
deleteWhen=04
fileReservedTime=128
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
brokerIP1=10.16.18.208
namesrvAddr=10.16.18.206:9876;10.16.18.208:9876;
```

slave-broker.properties
```
brokerClusterName=m-s-sync
brokerName=206-slave
brokerId=1
deleteWhen=04
fileReservedTime=48
brokerRole=SLAVE
flushDiskType=ASYNC_FLUSH
brokerIP1=10.16.18.206
namesrvAddr=10.16.18.206:9876;10.16.18.208:9876;
```

problem：
rocketmq slave node why nofind store files?  
It should be synchronized from master?

**Comment by lijunyong** [comment]
@shibd 我也遇到了，你怎么解决的
