### ISSUE TITLE
DefaultMQPushConsumerTest.testPullMessage_ExceptionOccursWhenComputePullFromWhere throws RejectedExecution

### ISSUE THREAD

**Issue by haozhijie9527** [apache/rocketmq#3624]
After merge ISSUE #3453 ,DefaultMQPushConsumerTest.testPullMessage_ExceptionOccursWhenComputePullFromWhere throws RejectedExecution
![image](https://user-images.githubusercontent.com/47975723/145589120-0271ce9b-7dd9-4430-a8c7-8e053beaff4f.png)

**Comment by yuz10** [comment]
@panzhi33

**Comment by panzhi33** [comment]
> @panzhi33 Could you take a look please?

ok

**Comment by panzhi33** [comment]
This is because org.apache.rocketmq.client.producer.RequestFutureHolder is a singleton class. If all the test cases are executed together, the thread pool in RequestFutureHolder will be closed after the execution of @After pushConsumer.shutdown() after the completion of the first test case, the following test cases will have this exception, and a single test is normal of. Now I modify @After to @AfterClass

**Comment by haozhijie9527** [comment]
![image](https://user-images.githubusercontent.com/47975723/145778223-04aa8d4b-9923-44cf-9473-a5691443844e.png)

**Comment by areyouok** [comment]
1. create a producer
2. send one message
3. close the producer
4. create the second producer
5. RejectedExecutionException throws

**Comment by panzhi33** [comment]
@haozhijie9527 @areyouok Please help to check again

**Comment by areyouok** [comment]
> @haozhijie9527 @areyouok Please help to check again

The synchronized block in RequestFutureHolder is not saft enough. Concurrent problem still exists.

I sugguest move DefaultMQProducerImpl.startScheduledTask() and 

```
                if (RequestFutureHolder.getInstance().getProducerNum().decrementAndGet() == 0) {
                    RequestFutureHolder.getInstance().getScheduledExecutorService().shutdown();
                }
```

to RequestFutureHolder.

**Comment by panzhi33** [comment]
> > @haozhijie9527 @areyouok Please help to check again
> 
> The synchronized block in RequestFutureHolder is not safe enough. Concurrent problem still exists.
> 
> I sugguest move DefaultMQProducerImpl.startScheduledTask() and
> 
> ```
>                 if (RequestFutureHolder.getInstance().getProducerNum().decrementAndGet() == 0) {
>                     RequestFutureHolder.getInstance().getScheduledExecutorService().shutdown();
>                 }
> ```
> 
> to RequestFutureHolder.

OK, it’s been revised, please take a look

**Comment by areyouok** [comment]
I think there is no problem. 

And I sugguest restore the unit test code to original version.

**Comment by odbozhou** [comment]
merged
