### ISSUE TITLE
when consumer start，the order of “pullMessage” and “rebalance notify brokers” is not strongly controlled，lead to CODE25

### ISSUE THREAD

**Issue by seaHeater** [apache/rocketmq#363]
The issue tracker is **ONLY** used for bug report and feature request. Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
start new consumers
- What did you expect to see?
consumer started and pull message from broker
- What did you see instead?
consumer start failed:CODE: 25 DESC: the consumer's subscription not latest

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
consumer 启动的时候，同样的 warning 出现在 broker.log。
查阅了源码，发现consumer启动的时候，新起了pull service 和 rebalance service 两个线程， rebalance 后会更新subVersion。
猜测是 heartbeat 还没从 consumer 同步到broker， 携带了新subVersion 的 pullMessage 请求就发送到了broker，导致subscriptionData.getSubVersion() < requestHeader.getSubVersion()。
如果是这种情况，为什么在consumer端，不等同步broker完成后，再进行 pullMessage， 这样就可以避免这个报错。
求解疑~

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by savilors** [comment]
I have this problem, too.Only when just started and not for everytime, it throws CODE25, even if there is only one instance in the consumer group.

**Comment by zhuangmg** [comment]
I have the same warning exception almost every time. 
2018-07-17 15:55:14,865 NettyClientPublicExecutor_1 [DefaultMQPushConsumerImpl.java:384] WARN  : [] execute the pull request exception
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 25  DESC: the consumer's subscription not latest
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/

**Comment by sisyphsu** [comment]
**It's wired.**
When I changed the logger of `RocketmqClient` to `slf4j`, and changed the `level` to `WARN`, 
like `<logger name="RocketmqClient" level="WARN"/>`, Everything became chaos.
If the `level` is `INFO`, everything will be OK.

I don't know why, but I guess the issue may be concurrent problem.
When `INFO` log was disabled, possibly some thread run faster, likely 1ms, which make this happen:
```
if (subscriptionData.getSubVersion() < requestHeader.getSubVersion()) {
    log.warn("The broker's subscription is not latest, group: {} {}", requestHeader.getConsumerGroup(),
                    subscriptionData.getSubString());
    response.setCode(ResponseCode.SUBSCRIPTION_NOT_LATEST);
    response.setRemark("the consumer's subscription not latest");
    return response;
}
```

**Comment by ymwneu** [comment]
Pull message and rebalance are running in two separate thread. 
When starting a new consumer,  it may have the warning exception, i think it's nothing, we can ignore this warning.

**Comment by vongosling** [comment]
I would like to appreciate your @ymwneu engagement in the community if you could raise your question in the user email list. The issue is not the correct place for your request, please read the issue template, looking forward to your question in the email list :-)
