### ISSUE TITLE
The demo seems to have some problems

### ISSUE THREAD

**Issue by icankeep** [apache/rocketmq#3633]
hello, I am not sure what is the meaning of this code in this demo?

[link](https://github.com/apache/rocketmq/blob/master/example/src/main/java/org/apache/rocketmq/example/ordermessage/Consumer.java)
![image](https://user-images.githubusercontent.com/39434627/145705516-fe1eff92-1741-46ae-819f-fd6f065389df.png)

`((this.consumeTimes.get() % 4) == 0) `  This condition is unreachable, right? For the simplicity of the demo, I don’t think this should appear in this demo either.

**Comment by icankeep** [comment]
I can optimize this demo if necessary

**Comment by panzhi33** [comment]
https://github.com/apache/rocketmq/pull/3569  somebody has fix it。
