### ISSUE TITLE
too many items in stats.log

### ISSUE THREAD

**Issue by areyouok** [apache/rocketmq#3637]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

setup a cluster with a lot of queue. eg: 100 topic and 10000 queue.

- What did you expect to see?

- What did you see instead?

The stats.log has too many items. and there are too many stat tasks run in the memory.

2. Please tell us about your environment:

version 4.9.2

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by Git-Yang** [comment]
Statistics at the queue level are only for delayed messages.
