### ISSUE TITLE
CreateTopic success but actually some brokers failed

### ISSUE THREAD

**Issue by ferrirW** [apache/rocketmq#3640]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

  call mqAdminImpl.createTopic()

- What did you expect to see?

  The creation failed and I need to know 

- What did you see instead?

  create topic success but some brokers failed

2. Please tell us about your environment:

  version: 4.9.2

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

![image](https://user-images.githubusercontent.com/42178996/145827450-f093fe57-8985-4905-8c97-65ad59314a84.png)

**Comment by ni-ze** [comment]
What is the error message？ how to reproduce?  and I do not understand what the mean of pic.

**Comment by guyinyou** [comment]
Hope to describe in detail

**Comment by ShannonDing** [comment]
createOKAtLeastOnce = true, will not throw exception.
