### ISSUE TITLE
Specific GID and TID cannot be displayed for MQ instance with namespace 

### ISSUE THREAD

**Issue by MatrixHB** [apache/rocketmq#3642]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

After Version 3.8, when troubleshooting using admin command like 'mqadmin consumerProgress' or 'mqadmin statsall', the specific topicID and groupID cannot be displayed for MQ instance with namespace, replaced by the ID of the MQ instance. However, the topic and group for MQ instance without namespace can be displayed normally.

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

It is confirmed that the topicID and groupID for MQ instance with namespace is too long to be truncated, so only the header part of topicID or groupID can be displayed.

{instanceId}%{topic}
e.g.  MQ_INST_138015630679****_BcZwWZ9k%Topic-test

Code involved: org.apache.rocketmq.tools.command.stats.StatsAllSubCommand#printTopicDetail

```
System.out.printf("%-32s  %-32s %12d %11.2f %11.2f %14d %14d%n",
                        UtilAll.frontStringAtLeast(topic, 32),
                        UtilAll.frontStringAtLeast(group, 32),
                        accumulate,
                        inTPS,
                        outTPS,
                        inMsgCntToday,
                        outMsgCntToday
                    );
```

**Comment by Git-Yang** [comment]
Could you submit a PR to resolve it?
