### ISSUE TITLE
a suggestion about the doc of org.apache.rocketmq.common.message.Message#setDelayTimeLevel

### ISSUE THREAD

**Issue by scientificCommunity** [apache/rocketmq#3643]
can you add some documentation for this funcation(`org.apache.rocketmq.common.message.Message#setDelayTimeLevel`)?
I have read your [documentation](https://rocketmq.apache.org/docs/schedule-example/), but I can't really understand the usage of this function by this doc.  finally, I need to check your source code step by step to know the usage of this function.

**Comment by scientificCommunity** [comment]
can `org.apache.rocketmq.common.message.Message` add a function for __STARTDELIVERTIME to specify delay time just like setDelayTimeLevel

**Comment by Git-Yang** [comment]
You can learn about the feature of delayed messages through the documentation, and maybe the usage of setDelayTimeLevel will be clearer.
https://github.com/apache/rocketmq/blob/master/docs/en/Feature.md

**Comment by Git-Yang** [comment]
__STARTDELIVERTIME is not used in the community version.
I will close this issue, and you can reopen it at any time if you have any questions.

**Comment by scientificCommunity** [comment]
> __STARTDELIVERTIME is not used in the community version. I will close this issue, and you can reopen it at any time if you have any questions.

ok, thank you!
