### ISSUE TITLE
How to deal with consumption failure，when I use DefaultLitePullConsumer

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#3653]

**Comment by MatrixHB** [comment]
In 4.6.60 version, add lite pull consumer support for RocketMQ：
(1) Support consume messages in subscribe way with auto rebalance.
(2) Support consume messages in assign way with no auto rebalance support.
(3) Add seek/commit offset for a specified message queue.

DefaultLitePullConsumer can be regarded as improved version of DefaultMQPullConsumer, so it is still message pull mode, and you need to implement consumption retry by yourself. Like using kafka, you can seek specific offset in message queue for retry.

Only DefaultMQPushConsumer in CLUSTERING model providers consumption retry machanism.

**Comment by Git-Yang** [comment]
I will close this issue and open it at any time if there are other issues.
