### ISSUE TITLE
The network delay between master and slave has a great performance impact

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#3664]
version: 4.9.1
I simulate the network delay between master slaves and use the tc command to add 2ms delay.

Test result: No matter how high the server configuration is, the maximum network traffic can only reach about 

27M/s. For example, 10K message, TPS 2700， or  100k ,tps 270.

By zhe way, if there is no network delay, the network traffic of sending messages from the same machine can reach 

300M/s。For example, 10K message, TPS 30000.

According to the test, the 2ms delay has a limited impact on SFTP。Therefore, I speculate that the delay has 

different effects on different application scenarios.

I would like to ask if there are parameters that can reduce the performance impact of network latency？

**Comment by Git-Yang** [comment]
Network latency will inevitably bring performance problems, and it can be changed to async to improve performance, but at the same time it will also reduce consistency.
I will close this ISSUE, if you have any problems, you can reopen it.

**Comment by iamqq23ue** [comment]
> Network latency will inevitably bring performance problems, and it can be changed to async to improve performance, but at the same time it will also reduce consistency. I will close this ISSUE, if you have any problems, you can reopen it.

延时影响性能是预期之内的。但是2ms延时，性能就下降到十分之一，这就不合理了。
我用sftp做实验，2ms延时几乎没有影响。大多数应用也不应该影响这么大。
所以想请教一下，是否有办法优化一下。
