### ISSUE TITLE
Updating the namesrv address with updateBrokerConfig command does not take effect

### ISSUE THREAD

**Issue by lygn128** [apache/rocketmq#3665]
4.3.2 版本，updatebrokerconfig 修改 nameserver 地址，3个改为5个，log 显示成功，配置文件件也已经被修改为 5个，但是 只向老的三个 节点注册，Telnet 新增加的两个也是成功的？ 为什么会出现这个问题？ 同意集群中有的实例是成功的，有的实例不成功，版本都一样的，也没看出有别的错误日志 
2021-12-21 16:30:27 INFO AdminBrokerThread_7 - updateBrokerConfig called by x1:34764
2021-12-21 16:30:27 INFO AdminBrokerThread_7 - updateBrokerConfig, new config: [{namesrvAddr=n1:29876;n2:29876;n3:29876;n4:29876;n5:29876}] client: /
x1:34764
2021-12-21 16:30:27 INFO AdminBrokerThread_7 - Replace, key: namesrvAddr, value: n1:29876;n2:29876;n3:29876 -> n1:29876;n2:29876;n3:29876
;n4:29876;n5:29876
2021-12-21 16:30:29 INFO brokerOutApi_thread_3 - register broker to name server n1:29876 OK
2021-12-21 16:30:29 INFO brokerOutApi_thread_1 - register broker to name server n2:29876 OK
2021-12-21 16:30:29 INFO brokerOutApi_thread_2 - register broker to name server n3:29876 OK

**Comment by Git-Yang** [comment]
When calling updateBrokerConfig to update the namesrvAddr, the configuration is only persisted in the broker config file and will take effect when the broker is restarted.

**Comment by RongtongJin** [comment]
Currently, the broker must be restarted after nameserver addr being updated. link#1485

**Comment by lygn128** [comment]
> When calling updateBrokerConfig to update the namesrvAddr, the configuration is only persisted in the broker config file and will take effect when the broker is restarted.



> When calling updateBrokerConfig to update the namesrvAddr, the configuration is only persisted in the broker config file and will take effect when the broker is restarted.

但是确实有些实例被修改之后就生效了的，我确信没有在通过命令行修改配置之后重启过的

**Comment by lygn128** [comment]
> Currently, the broker must be restarted after nameserver addr being updated. link #1458
但是有的实例确实修改成功了的：
sudo ./mqadmin clusterlist -n x.61:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_c           2     x.61:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
laoliu@bigo:~$ sudo ./mqadmin clusterlist -n x.209:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_a           0     x.61:1911    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_a           2     x.108:2931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_a           3     x.209:2941     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
rocketmq-laoliu  laoliu_b           0     x.108:1921   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_b           1     x.61:1931    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_b           3     x.209:2951     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
rocketmq-laoliu  laoliu_c           0     x.108:1931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_c           2     x:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775

laoliu@bigo:~$ sudo ./mqadmin updatebrokerconfig -c rocketmq-laoliu -k namesrvAddr -v "x.61:8876;x.108:8876;x.209:8876" -s -n x.209:8876 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
update broker config success, x.209:2961
update broker config success, x.209:2951
update broker config success, x.209:2941
update broker config success, x.61:1931
update broker config success, x.61:2951
update broker config success, x.61:1911
update broker config success, x.108:1931
update broker config success, x.108:2931
update broker config success, x.108:1921
laoliu@bigo:~$ sudo ./mqadmin clusterlist -n x.61:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_a           0     x.61:1911    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_a           2     x.108:2931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_a           3     x.209:2941     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776
rocketmq-laoliu  laoliu_b           0     x.108:1921   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_b           1     x.61:1931    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_b           3     x.209:2951     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776
rocketmq-laoliu  laoliu_c           0     x.108:1931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_c           2     x.61:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776_

**Comment by lygn128** [comment]
> Currently, the broker must be restarted after nameserver addr being updated. link #1458

sudo ./mqadmin clusterlist -n x.61:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_c           2     x.61:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
laoliu@bigo:~$ sudo ./mqadmin clusterlist -n x.209:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_a           0     x.61:1911    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_a           2     x.108:2931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_a           3     x.209:2941     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
rocketmq-laoliu  laoliu_b           0     x.108:1921   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_b           1     x.61:1931    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_b           3     x.209:2951     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
rocketmq-laoliu  laoliu_c           0     x.108:1931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_c           2     x:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775

laoliu@bigo:~$ sudo ./mqadmin updatebrokerconfig -c rocketmq-laoliu -k namesrvAddr -v "x.61:8876;x.108:8876;x.209:8876" -s -n x.209:8876 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
update broker config success, x.209:2961
update broker config success, x.209:2951
update broker config success, x.209:2941
update broker config success, x.61:1931
update broker config success, x.61:2951
update broker config success, x.61:1911
update broker config success, x.108:1931
update broker config success, x.108:2931
update broker config success, x.108:1921
laoliu@bigo:~$ sudo ./mqadmin clusterlist -n x.61:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_a           0     x.61:1911    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_a           2     x.108:2931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_a           3     x.209:2941     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776
rocketmq-laoliu  laoliu_b           0     x.108:1921   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_b           1     x.61:1931    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_b           3     x.209:2951     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776
rocketmq-laoliu  laoliu_c           0     x.108:1931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_c           2     x.61:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776

**Comment by lygn128** [comment]
但是有的实例确实是修改成功了的，并且没重启实例
sudo ./mqadmin clusterlist -n x.61:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_c           2     x.61:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
laoliu@bigo:~$ sudo ./mqadmin clusterlist -n x.209:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_a           0     x.61:1911    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_a           2     x.108:2931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_a           3     x.209:2941     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
rocketmq-laoliu  laoliu_b           0     x.108:1921   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_b           1     x.61:1931    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_b           3     x.209:2951     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775
rocketmq-laoliu  laoliu_c           0     x.108:1931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.1169
rocketmq-laoliu  laoliu_c           2     x:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.27 0.0775

laoliu@bigo:~$ sudo ./mqadmin updatebrokerconfig -c rocketmq-laoliu -k namesrvAddr -v "x.61:8876;x.108:8876;x.209:8876" -s -n x.209:8876 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
update broker config success, x.209:2961
update broker config success, x.209:2951
update broker config success, x.209:2941
update broker config success, x.61:1931
update broker config success, x.61:2951
update broker config success, x.61:1911
update broker config success, x.108:1931
update broker config success, x.108:2931
update broker config success, x.108:1921
laoliu@bigo:~$ sudo ./mqadmin clusterlist -n x.61:8876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
rocketmq-laoliu  laoliu_a           0     x.61:1911    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_a           2     x.108:2931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_a           3     x.209:2941     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776
rocketmq-laoliu  laoliu_b           0     x.108:1921   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_b           1     x.61:1931    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_b           3     x.209:2951     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776
rocketmq-laoliu  laoliu_c           0     x.108:1931   V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.1169
rocketmq-laoliu  laoliu_c           2     x.61:2951    V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0016
rocketmq-laoliu  laoliu_c           3     x.209:2961     V4_3_2                   0.00(0,0ms)         0.00(0,0ms)          0 455579.34 0.0776

**Comment by lygn128** [comment]
### the log is get from the broker.log 
2021-12-21 16:30:27 INFO AdminBrokerThread_14 - updateBrokerConfig, new config: [{namesrvAddr=x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876}] client: /x.230:50616 
2021-12-21 16:30:27 INFO AdminBrokerThread_14 - Replace, key: namesrvAddr, value: x.230:29876;x.203:29876;x.114:29876 -> x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876
2021-12-21 16:30:27 INFO brokerOutApi_thread_2 - register broker to name server x.191:29876 OK
2021-12-21 16:30:27 INFO AdminBrokerThread_14 - Set user specified name server address: x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876
2021-12-21 16:30:35 INFO brokerOutApi_thread_3 - register broker to name server x.191:29876 OK
2021-12-21 16:30:57 INFO AdminBrokerThread_10 - updateBrokerConfig, new config: [{namesrvAddr=x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876}] client: /x.230:50886 
2021-12-21 16:30:57 INFO brokerOutApi_thread_2 - register broker to name server x.191:29876 OK
2021-12-21 16:30:57 INFO AdminBrokerThread_10 - Set user specified name server address: x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876
2021-12-21 16:31:05 INFO brokerOutApi_thread_3 - register broker to name server x.191:29876 OK
2021-12-21 16:31:35 INFO brokerOutApi_thread_1 - register broker to name server x.191:29876 OK
2021-12-21 16:32:05 INFO brokerOutApi_thread_4 - register broker to name server x.191:29876 OK
2021-12-21 16:32:21 INFO AdminBrokerThread_16 - updateBrokerConfig, new config: [{namesrvAddr=x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876}] client: /x.230:51496 
2021-12-21 16:32:21 INFO brokerOutApi_thread_1 - register broker to name server x.191:29876 OK
2021-12-21 16:32:21 INFO AdminBrokerThread_16 - Set user specified name server address: x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876
2021-12-21 16:32:35 INFO brokerOutApi_thread_3 - register broker to name server x.191:29876 OK
2021-12-21 16:33:02 INFO AdminBrokerThread_14 - updateBrokerConfig, new config: [{namesrvAddr=x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876}] client: /x.230:51864 
2021-12-21 16:33:02 INFO brokerOutApi_thread_1 - register broker to name server x.191:29876 OK
2021-12-21 16:33:02 INFO AdminBrokerThread_14 - Set user specified name server address: x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876
2021-12-21 16:33:05 INFO brokerOutApi_thread_3 - register broker to name server x.191:29876 OK
2021-12-21 16:33:10 INFO AdminBrokerThread_15 - updateBrokerConfig, new config: [{namesrvAddr=x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876}] client: /x.230:51972 
2021-12-21 16:33:10 INFO brokerOutApi_thread_1 - register broker to name server x.191:29876 OK
2021-12-21 16:33:10 INFO AdminBrokerThread_15 - Set user specified name server address: x.230:29876;x.203:29876;x.114:29876;x.191:29876;x.200:29876

**Comment by lygn128** [comment]
有人修改过代码，线上用的有经过修改的支持动态改变 namesrv 的版本
