### ISSUE TITLE
 [RIP-28]Support light message queue (LMQ) multi-consumeQueue atomic dispatch

### ISSUE THREAD

**Issue by tianliuliu** [apache/rocketmq#3666]
Some messaging scenarios require Light message queue to support a large number of topics, such as MQTT, AMQP protocol, its multi-level topic sending and subscription can be set at will, and the number of multi-level topics is very large, the original RocketMQ topic It is resource-heavy, and it is difficult to support millions or more of lightweight multi-level topics.

Let's define Light message queue as （LMQ）

Light message queue (LMQ) needs to implement multi-dimensional dispatch of a message based on ConsumeQueue, and a message can support multiple lightweight queue consumption。

Light message queue (LMQ) needs to implement multi-level topic management, so topic metadata also needs adaptation management, such as topic verification, data cleaning and so on.

Light message queue (LMQ) needs to implement lightweight queue consumption offset management

**Comment by RongtongJin** [comment]
It seems to be a considerable change. I suggest you open a new RIP to introduce your design. You can refer to [wiki-rip](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal).

**Comment by vongosling** [comment]
I  could not figure out what you want to do from your description. You could arrange your sentences.

**Comment by tianliuliu** [comment]
> I could not figure out what you want to do from your description. You could arrange your sentences.

Some messaging scenarios require light message queue, Such as MQTT multi-level topic or AMQP lightweight queue can be set at will by users when sending and subscription message. Therefore, the implementation of LMQ's queue model is required

**Comment by Git-Yang** [comment]
Looking forward to it very much. We have a big demand scenario here.

**Comment by RongtongJin** [comment]
Merged

**Comment by ShannonDing** [comment]
link #3694 #3753
