### ISSUE TITLE
The network delay between master and slave has a great performance impact

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#3667]
version: 4.9.1
I simulate the network delay between master slaves and use the tc command to add 2ms delay.

Test result: No matter how high the server configuration is, the maximum network traffic can only reach about 

27M/s. For example, 10K message, TPS 2700， or  100k ,tps 270.

By zhe way, if there is no network delay, the network traffic of sending messages from the same machine can reach 

300M/s。For example, 10K message, TPS 30000.

According to the test, the 2ms delay has a limited impact on SFTP。Therefore, I speculate that the delay has 

different effects on different application scenarios.

I would like to ask if there are parameters that can reduce the performance impact of network latency？

说明一下，延时影响性能是预期之内的。但是2ms延时，性能就下降到十分之一，这就不合理了。
我用sftp做实验，2ms延时几乎没有影响。大多数应用也不应该影响这么大。
所以想请教专家，是否有办法优化。
- ...

**Comment by RongtongJin** [comment]
Hi, @iamqq23ue Could you describe the test scenario in more detail？ In addition, IMO it is not accurate for using tc command to simulate the delay between master and slave, because tc command acts on the network card, it will also affect the transmission from the client to the broker.

**Comment by iamqq23ue** [comment]
I use the TC command to add a 2ms delay on the slave server. IMO, I guess the delay from slave to client will not affect the message sending
