### ISSUE TITLE
消息延迟,  并且一次性发过来

### ISSUE THREAD

**Issue by shi1234ww** [apache/rocketmq#3669]
在rocketmq控制台发消息后,  有的时候消费者当时并没有立即收到消息,  而是过一二十分钟左右,  一次性接收到很多消息, 该怎么处理

**Comment by guyinyou** [comment]
Hope to provide more detailed information, I want to reproduce it

**Comment by shi1234ww** [comment]
大佬,      我也不知道怎么复现,  偶尔会出现这种情况,    昨天出现过这种情况, 就是在rocketmq控制台发消息后,   有的时候消费者当时并没有立即收到消息, 而是过一二十分钟左右, 一次性消费到到很多消息, 会导致我数据错乱,  ,今天一天了也都没出现这个情况,

**Comment by guyinyou** [comment]
Does "一次性消费到到很多消息" mean the messages sent on the console?

**Comment by shi1234ww** [comment]
是的,   场景是这样子的,  我在rocketmq控制台上选择topicA 发送消息后,   弹框会提示我发送成功,  一般情况下会直接在消费端直接看到日志开始消费消息了,    但是偶尔会出现弹框已经提示我发送成功, 但是在消费端并没有看到日志开始消费,  然后这个时候我重复点击发送消息,  控制台也重复提示我发送成功,  但是一直在消费端没有看到日志开始消费,   然后我停止操作,    突然过一二十分钟左右,  刚才发送的消息又开始在同一秒内一次性在消费端开始打日志开始消费了,

**Comment by shi1234ww** [comment]
是的,   场景是这样子的,  我在rocketmq控制台上选择topicA 发送消息后,   弹框会提示我发送成功,  一般情况下会直接在消费端直接看到日志开始消费消息了,    但是偶尔会出现弹框已经提示我发送成功, 但是在消费端并没有看到日志开始消费,  然后这个时候我重复点击发送消息,  控制台也重复提示我发送成功,  但是一直在消费端没有看到日志开始消费,   然后我停止操作,    突然过一二十分钟左右,  刚才发送的消息又开始在同一秒内一次性在消费端开始打日志开始消费了,

**Comment by duhenglucky** [comment]
@shi1234ww 使用producer 发送的消息有没有遇到过相同的情况？我们可以在邮件列表里面讨论下这个问题
