### ISSUE TITLE
Why keep printing the persistAll log

### ISSUE THREAD

**Issue by lin-mt** [apache/rocketmq#3675]
version：4.9.2

Why keep printing the persistAll log, even if no more messages are consumed.

org.apache.rocketmq.client.consumer.store.RemoteBrokerOffsetStore#persistAll

```java
log.info("[persistAll] Group: {} ClientId: {} updateConsumeOffsetToBroker {} {}",
    this.groupName,
    this.mQClientFactory.getClientId(),
    mq,
    offset.get());
```

**Comment by duhenglucky** [comment]
@lin-mt Just for the convenience of trouble shooting, can clearly see the offset committing progress in the timed task

**Comment by lin-mt** [comment]
@duhenglucky Is it just troubleshooting? If there is no message consumption, this part of the log will overwrite the early contents of the log file, including the earliest log of the day. Shouldn't it not be printed after there is no message consumption?
