### ISSUE TITLE
Is there a command to check master-slave synchronization?

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#3681]
I know that the master-slave synchronization status can be seen from the log, but is there a command line method 

to obtain the master-slave synchronization status?

The command line makes it easy to use automated scripts.

Thks

**Comment by vongosling** [comment]
DLedger is a more advanced ha model in RocketMQ, also it could reback to the leader/replica model for compatibility. you could implement this feature. I'd like to follow up on your pr.

**Comment by XiaoyiPeng** [comment]
Hi, @iamqq23ue  @vongosling  @duhenglucky 

I have submitted a PR #3746 , you can help to review, whether it meets your needs.
