### ISSUE TITLE
The consumer Connection query result is displayed on the page as unfriendly.

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#3696]
When using the consumerConnection mqadmin command to query consumer connections, the query result is displayed on the page as unfriendly.
![image](https://user-images.githubusercontent.com/18254437/148148502-252e25e8-fbbb-40d7-8230-4d37b684434c.png)

**Comment by vongosling** [comment]
I hate logger warn export in our command tools, It could not find the master these years. Would you like to fix it in this pr.

**Comment by zhangjidi2016** [comment]
OK，I will solve this problem later.
