### ISSUE TITLE
[Code Style] Fix check style for branch: 5.0.0-alpha

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq#3702]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
![image](https://user-images.githubusercontent.com/46882838/148187257-8d80eafb-a747-448e-9ab1-877ad5491bb9.png)

- What did you expect to see?
Can pass the check correctly

- What did you see instead?
`[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default-cli) on project rocketmq-common: Too many files with unapproved license: 2 `

2. Please tell us about your environment:
- MacOS 
- 5.0.0-alpha

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
```
Files with unapproved licenses:

  src/test/java/org/apache/rocketmq/common/statictopic/TopicQueueMappingUtilsTest.java
  src/test/java/org/apache/rocketmq/common/statictopic/TopicQueueMappingTest.java
```

**Comment by vongosling** [comment]
Thanks @cserwen .

@duhenglucky @dongeforever Code is over than... Pls, pay more attention to @cserwen suggestion. we don't want to see any negative reviews about our next architecture.
