### ISSUE TITLE
Support Topic Level ConsumeQueue/BatchConsumeQueue

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq#3704]
Based on PR #3671, I hope that can choose to use ConsumeQueue or BatchConsumeQueue at the Topic level.
![image](https://user-images.githubusercontent.com/30995057/148189295-8d07da7b-a069-417c-adbd-d4911167e13c.png)

When the user creates a Topic, specify the Queue type (Single/Batch), ConsumeQueue uses dense index, and BatchConsumeQueue uses sparse index, so as to meet the needs of different scenarios in the same cluster.

**Comment by Erik1288** [comment]
I'm working on it.

**Comment by vongosling** [comment]
This is a very impressive optimization we have discussed two years ago, pls come on.

**Comment by odbozhou** [comment]
The pr #3712 may solve this issue.
https://github.com/apache/rocketmq/pull/3712
