### ISSUE TITLE
[RIP-26] [Feature] Both CQ and BCQ need to be supported in DefaultMessageStore.

### ISSUE THREAD

**Issue by Erik1288** [apache/rocketmq#3708]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Both CQ and BCQ need to be supported in DefaultMessageStore.

2. Provide any additional detail on your proposed use case for this feature.
* ). Remove StreamMessageStore
* ). Make DefaultMessageStore support both BCQ and CQ.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
- [Refactor CQ and BCQ loading process]: unify loading process.
- [add CorrectLogicOffsetService): add CorrectLogicOffsetService to periodically correct min logic offset.

**Comment by Git-Yang** [comment]
Link https://github.com/apache/rocketmq/issues/3704

**Comment by vongosling** [comment]
@Git-Yang You could link it in the pr. Actually, pr and issue are mutually linked if you notice the GitHub toolbar on the right side.

**Comment by RongtongJin** [comment]
All Merged
