### ISSUE TITLE
FlushRealTimeService Issue

### ISSUE THREAD

**Issue by Black-Mamba24** [apache/rocketmq#371]
**BUG REPORT**

1. Please describe the issue you observed:
![image](https://user-images.githubusercontent.com/11400154/42877599-d5418118-8abc-11e8-8a18-d7d24d06f484.png)

- What did you do (The steps to reproduce)?
async flush disk code, lastFlushTimestamp is not useful, It's obvious..

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by vongosling** [comment]
Thanks @Black-Mamba24 .It is obvious that you mentioned is not a bug.

**Comment by Black-Mamba24** [comment]
@vongosling sorry, i got it,,thanks
