### ISSUE TITLE
[Feature] More Precise Range Definition about minOffsetInQueue and maxOffsetInQueue.

### ISSUE THREAD

**Issue by Erik1288** [apache/rocketmq#3714]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

In the current implementation,
If there's only 0 in a queue, the result of Range will be [minOffsetInQueue: 0, maxOffsetInQueue: 1)
即: 左闭右开的整数区间

Similarly
if 0, 1 in a queue，the result of Range will be [minOffsetInQueue: 0, maxOffsetInQueue: 2)
if 0, 1, 2 ... 9 in a queue，the result of Range will be [minOffsetInQueue: 0, maxOffsetInQueue: 10)

But，
If nothing in a queue, the result of Range will be [minOffsetInQueue: 0, maxOffsetInQueue: 0).
So just looking at the minOffsetInQueue, there's no way to tell the difference between having 0 in a queue and having no data in a queue.

I propose to follow [minOffsetInQueue: close, maxOffsetInQueue: open) definition. If there is no data in a queue, minOffsetInQueue returns -1.

2. Provide any additional detail on your proposed use case for this feature.

minOffsetInQueue definition and existing unit-test will be changed.

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by Kvicii** [comment]
@Erik1288 @duhenglucky Has this feature been voted on?

**Comment by dongeforever** [comment]
@Erik1288 You could raise a discuss in the dev mailing list.

BTW,  this is not a feature, more like a  bug.
