### ISSUE TITLE
[RIP-27] [Feature] Auto batch in producer

### ISSUE THREAD

**Issue by guyinyou** [apache/rocketmq#3717]
1. Please describe the feature you are requesting.
Messages are sent in batches with very good throughput performance, but currently the business end needs to be packaged manually by itself, and the experience is not good enough.

2. Provide any additional detail on your proposed use case for this feature.
To realize the automatic message packaging function, the business side only needs to simply call the sending interface of a single message to realize the throughput of batch sending.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
nice-to-have

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by RongtongJin** [comment]
refer https://github.com/apache/rocketmq/wiki/RIP-27-Auto-batching-in-producer
