### ISSUE TITLE
producer send async is Deprecated, why in 4.9.2 version it is already exist

### ISSUE THREAD

**Issue by ztyandjw** [apache/rocketmq#3760]
version: 4.9.2

DefaultMQProducerImpl#send(final Message msg, final MessageQueue mq, final SendCallback sendCallback, final long timeout)

/**
     * It will be removed at 4.4.0 cause for exception handling and the wrong Semantics of timeout. A new one will be
     * provided in next version
     *
why this function is already exist,  whitch function could i use, when i use the producer to send async message.

**Comment by duhenglucky** [comment]
@ztyandjw The community is discussing how to simplify the API, mailing list address: https://lists.apache.org/thread/460ttogv9645pkdlnb5q7x8nktdny15r , any suggestions are welcome.
