### ISSUE TITLE
发送异步消息api废弃，为何没有找到新的api

### ISSUE THREAD

**Issue by ztyandjw** [apache/rocketmq#3763]
发送异步消息api废弃 显示4.4.0会移除该方法，可是在4.9.2最新版也没找到最新的方法？请问如果使用异步方法发送消息，该用哪个func？

    /**
     *** It will be removed at 4.4.0 cause for exception handling and the wrong Semantics of timeout. A new one will be**
     * provided in next version
     *
     * @param msg
     * @param sendCallback
     * @param timeout the <code>sendCallback</code> will be invoked at most time
     * @throws RejectedExecutionException
     */
    @Deprecated
    public void send(final Message msg, final SendCallback sendCallback, final long timeout)
        throws MQClientException, RemotingException, InterruptedException {
        final long beginStartTime = System.currentTimeMillis();
        ExecutorService executor = this.getAsyncSenderExecutor();
        try {
            executor.submit(new Runnable() {
                @Override
                public void run() {
                    long costTime = System.currentTimeMillis() - beginStartTime;
                    if (timeout > costTime) {
                        try {
                            sendDefaultImpl(msg, CommunicationMode.ASYNC, sendCallback, timeout - costTime);
                        } catch (Exception e) {
                            sendCallback.onException(e);
                        }
                    } else {
                        sendCallback.onException(
                            new RemotingTooMuchRequestException("DEFAULT ASYNC send call timeout"));
                    }
                }

            });
        } catch (RejectedExecutionException e) {
            throw new MQClientException("executor rejected ", e);
        }

    }

**Comment by duhenglucky** [comment]
@ztyandjw 现在社区正在讨论API 的优化：https://lists.apache.org/thread/460ttogv9645pkdlnb5q7x8nktdny15r ，在社区达成一致前应该不会删除这个API，如果删除的话肯定会给出推荐：）
