### ISSUE TITLE
about MQClientAPIImpl improvement

### ISSUE THREAD

**Issue by Kvicii** [apache/rocketmq#3785]
hi there.
In MQClientAPIImpl, I see a lot about switch...case code blocks, Is this a preparation for the follow-up or can it be completely improved?

**Comment by duhenglucky** [comment]
@Kvicii please feel free to start a discussion with your design, any optimizations to the code are welcome

**Comment by Kvicii** [comment]
@duhenglucky hi, I think it is possible to merge these code blocks,and I will provide a PR later

**Comment by Kvicii** [comment]
@duhenglucky Does our PR need to be checked out from the develop branch?

**Comment by tianliuliu** [comment]
> I wi

yes, PR based on the develop branch

**Comment by Kvicii** [comment]
[ISSUE#3785](https://github.com/apache/rocketmq/pull/3793)
