### ISSUE TITLE
rocketmq broker IP修改后 原来的topic 没有了！

### ISSUE THREAD

**Issue by wanglixiang90** [apache/rocketmq#3791]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:
rocketmq broker IP修改后 原来broker  内的 topic 没有了，希望broker修改IP不影响原有的topic 配置
- What did you do (The steps to reproduce)?
broker IP修改后 原来broker  内的 topic 没有了
- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:
rocketmq 4.8.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ShannonDing** [comment]
topics and messages store are both related brokerIP, it is better not to change the broker ip.

**Comment by duhenglucky** [comment]
@wanglixiang90 更换IP 不会导致topic 丢失，可以看下 topics.json 文件是否还存在？另外用的是dledger 模式还是 ms 模式？
