### ISSUE TITLE
[RIP-29] Optimize RocketMQ NameServer

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq#3792]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Nameserver is a very important component in RocketMQ cluster, which is used for route discovery. At present, the nameserver is stateless and lightweight, but it still bears a certain amount of pressure especially when the cluster reaches a certain scale. So I want to optimize the nameserver in RocketMQ 5.0.

2. Provide any additional detail on your proposed use case for this feature.

I want to optimize the nameserver from the following aspects

- By separating the broker registration thread pool and the topic route info acquisition thread pool, we can ensure that different types of requests will not affect each other.
- Optimize topic routing cache to speed up topic routing acquisition, reduce nameserver CPU pressure.
- Unregister brokers in batches to speed up the broker offline.

Refer to [wiki page](https://github.com/apache/rocketmq/wiki/RIP-29-Optimize-RocketMQ-NameServer)

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

 nice-to-have

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by Cczzzz** [comment]
> I want the re-election time to affect sequential message sending.Proactively push when the broker role changes

我希望可以减少因为选举对顺序消息发送者的不可用时间，比如nameserver主动通知客户端，或者broker 推送。
因为在顺序消息存在的情况下，升级和重启服务时非常困难的。

**Comment by RongtongJin** [comment]
> > I want the re-election time to affect sequential message sending.Proactively push when the broker role changes
> 
> 我希望可以减少因为选举对顺序消息发送者的不可用时间，比如nameserver主动通知客户端，或者broker 推送。 因为在顺序消息存在的情况下，升级和重启服务时非常困难的。

IMO, it is a very good suggestion to reduce the recovery time of failure through nameserver reverse notification, but it may not be included in this RIP. We can open another issue or RIP to do this.

**Comment by gendway** [comment]
brokerIP1=127.0.0.1
namesrvAddr=127.0.0.1:9876
