### ISSUE TITLE
we need description of deprecated methods and classes

### ISSUE THREAD

**Issue by Kvicii** [apache/rocketmq#3794]
hello all, 
In the code, I found a lot of deprecated classes and methods, but some without adding @deprecated documentation or description,This is the code specification we have to abide by

**Comment by xiongwu1** [comment]
for example?

**Comment by Kvicii** [comment]
@xiongwu1 for example, DefaultMQPullConsumer we need use `@deprecated`

**Comment by Kvicii** [comment]
@xiongwu1 like this. [ISSUE-3794](https://github.com/apache/rocketmq/pull/3796)
