### ISSUE TITLE
DefaultMQProducerImpl code improvement

### ISSUE THREAD

**Issue by Kvicii** [apache/rocketmq#3797]
hi all, 
The DefaultMQProducerImpl class has some code that can be optimized, I will provide a PR later.

**Comment by Kvicii** [comment]
abount the checkTransactionState API, it seems that we should remove the calls to the checkListener method and TransactionCheckListener, should we?

**Comment by caigy** [comment]
@Kvicii Looking forward to more detailed description of this improvement

**Comment by Kvicii** [comment]
@caigy As I said before, I think these invalid calls should be removed. For some verbose methods, we should do refactoring to ensure code readability.

**Comment by Kvicii** [comment]
@caigy I'm thinking about this right now, if you can tell me when this kind of code can be removed, I'll ignore the question

**Comment by Kvicii** [comment]
[PR-3809](https://github.com/apache/rocketmq/pull/3809)
