### ISSUE TITLE
[RIP-31] Support RocketMQ BrokerContainer

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq#3798]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Currently, a RocketMQ process has only one broker. However, the slave costs fewer resources than the master. So I want to provide a new BrokerContainer mode, in which multiple brokers can be added or removed to a BrokerContainer process and reuse some resources such as the transport layer. And it can improve the utilization of a single node. So I would like to start an RIP to support RocketMQ BrokerContainer.

2. Provide any additional detail on your proposed use case for this feature.

Refer to [wiki](https://github.com/apache/rocketmq/wiki/RIP-31-Support-RocketMQ-BrokerContainer)

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

nice-to-have

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by complone** [comment]
@RongtongJin Hello, here are some examples based on testcontainer, do you want to introduce something similar to KafkaContainer for user brokers to run in containers to reduce losses?

https://github.com/apache/flink/commit/ce9cfced5df0b557625018d7267bae5fcd04f40c

**Comment by RongtongJin** [comment]
> @RongtongJin Hello, here are some examples based on testcontainer, do you want to introduce something similar to KafkaContainer for user brokers to run in containers to reduce losses?
> 
> [apache/flink@ce9cfce](https://github.com/apache/flink/commit/ce9cfced5df0b557625018d7267bae5fcd04f40c)

Nope, this RIP has nothing to do with container like docker. It is a RocketMQ native container that can add multiple brokers in one process.

**Comment by cserwen** [comment]
Hi, I have added some code to support Container in `DLedger` mode. Can I submit a pr directly under this issue?:-D @RongtongJin

**Comment by RongtongJin** [comment]
> Hi, I have added some code to support Container in `DLedger` mode. Can I submit a pr directly under this issue?:-D @RongtongJin

Of course!
