### ISSUE TITLE
console dashboard Broker 5min trend  data question

### ISSUE THREAD

**Issue by 18205097282** [apache/rocketmq#3800]
![image](https://user-images.githubusercontent.com/53631755/151275650-21934f23-44ba-494f-9de7-854d13f497b5.png)
请问本页面的Broker 5min trend的数值是如何计算的，我研究了一个星期了，无论带入怎么样的数值都算不出来这个结果，非常疑惑。
恳请大佬解答。
有大佬 @duhengforever 回答是
broker's message count (broker total message count/5 min trend)
请问什么是broker's message count
什么是broker total message count
或者是别的什么计算公式？

**Comment by caigy** [comment]
It is calculate by the metric `getTotalTps`, which shows the tps of _getMessage_ call.

1. When `org.apache.rocketmq.store.DefaultMessageStore#getMessage` is called, `getMessageTimesTotalFound` or `getMessageTimesTotalMiss` is incremented. 
2. `org.apache.rocketmq.store.StoreStatsService#sampling` is executed every second, and tag the current `getMessageTimesTotalFound`  or  `getMessageTimesTotalMiss` with current timestamp, and put them in `getTimesFoundList` or `getTimesMissList` separately. 
3. So each list contains a time series record of the number of _getMessage_ operation, and each the timestamp between two consecutive item is about 1 second. The interval is NOT precise, because the generation of record is triggered by scheduled service in step 2. 
4. If you get the last X items in the list, sum the number of call times and divide the result by X, you can get the `getTotalTps` in the last X seconds.

**Comment by 18205097282** [comment]
不好意思&nbsp; 再麻烦您一下
您说把最后X个数值相加处以X 就得到最后X时间内的getTotalTps。



我的这段曲线是新建的broker。仅仅只在10:40处消费了2个message，其他时间均没有消费也没有生产消息。 为何之后它会一直有大于0的值呢？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月27日(星期四) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] console dashboard 页面疑问 (Issue #3800)





 
It is calculate by the metric getTotalTps, which shows the tps of getMessage call.
  
When org.apache.rocketmq.store.DefaultMessageStore#getMessage is called, getMessageTimesTotalFound or getMessageTimesTotalMiss is incremented.
 
org.apache.rocketmq.store.StoreStatsService#sampling is executed every second, and tag the current getMessageTimesTotalFound  or  getMessageTimesTotalMiss with current timestamp, and put them in getTimesFoundList or getTimesMissList separately.
 
So each list contains a time series record of the number of getMessage operation, and each the timestamp between two consecutive item is about 1 second. The interval is NOT precise, because the generation of record is triggered by scheduled service in step 2.
 
If you get the last X items in the list, sum the number of call times and divide the result by X, you can get the getTotalTps in the last X seconds.
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ni-ze** [comment]
This chart is show average tps of broker. But it does has some problem. 

The result is calculated following formula

```
brokerTps = [(10s avg tps of broker) + (1min avg tps of broker) + (10min avg tps of broker)]/3
```

but obviously， it is not incorrect for 5min trend.

**Comment by 18205097282** [comment]
@ni-ze 
![image](https://user-images.githubusercontent.com/53631755/151287747-3c12dd17-941d-4a1a-a036-7df763726574.png)
您好，我这段曲线仅仅只在10:40处消费了2个message，其他时间均没有消费也没有生产消息。 
为何之后它会一直有大于0的值呢？
按照您的
brokerTps = [(10s avg tps of broker) + (1min avg tps of broker) + (10min avg tps of broker)]/3
公式，10分钟后，它的值应该回归到0呀

**Comment by ni-ze** [comment]
> @ni-ze ![image](https://user-images.githubusercontent.com/53631755/151287747-3c12dd17-941d-4a1a-a036-7df763726574.png) 您好，我这段曲线仅仅只在10:40处消费了2个message，其他时间均没有消费也没有生产消息。 为何之后它会一直有大于0的值呢？ 按照您的 brokerTps = [(10s avg tps of broker) + (1min avg tps of broker) + (10min avg tps of broker)]/3 公式，10分钟后，它的值应该回归到0呀

这个不必在意，客户端没有消息发送，broker自身也有很小的tps，因为这个tps是统计store层的，不是统计client接口请求的。有定时任务检查事务半消息topic RMQ_SYS_TRANS_HALF_TOPIC是否有消息，会查询store这里会产生tps

**Comment by 18205097282** [comment]
@ni-ze 
大佬您好，请问您说的客户端没有消费消息，broker自身也有很小的tps。
这个broker本身很小的tps会随着topic的增多而增多吗？我们的系统中有500个topic，每日消费消息数大约是6万个，但broker 5min trend值一直在400左右，请问这正常吗？

**Comment by 18205097282** [comment]
@ni-ze 
大佬，我好想理解了算法公式了，最后一个问题，什么是MissTPS 和FoundTPS呀

**Comment by caigy** [comment]
> @ni-ze 大佬您好，请问您说的客户端没有消费消息，broker自身也有很小的tps。 这个broker本身很小的tps会随着topic的增多而增多吗？我们的系统中有500个topic，每日消费消息数大约是6万个，但broker 5min trend值一直在400左右，请问这正常吗？

@18205097282 这个指标是基于`org.apache.rocketmq.store.DefaultMessageStore#getMessage`的调用次数计算的，如果这个指标一直在400，反映出来的情况是一直持续在消费消息，这个是否与你们系统的情况相符？此外，由于一条消息可能被多个消费组消费，“每日消费消息数大约是6万个”是指消费被消费的总次数，还是待消费的消息条数？

**Comment by caigy** [comment]
> @ni-ze 大佬，我好想理解了算法公式了，最后一个问题，什么是MissTPS 和FoundTPS呀

简单理解是从MessageStore查到消息是Found，否则是Miss，具体判断逻辑可以看看`org.apache.rocketmq.store.DefaultMessageStore#getMessage`

**Comment by 18205097282** [comment]
@caigy @ni-ze  “每日消费消息数大约是6万个”指代消息被消费总数，反应在参数中是todayConsumeCount和yesterdayConsumeCount。
我就很疑惑 指标是400  俺400*60*24 每天应该是差不多60W条消息被消费，  但实际情况只有6万

**Comment by ni-ze** [comment]
从存储中查询消息，如果能找到就算在FoundTPS中，找不到就算在MissTPS中。

> @ni-ze 大佬您好，请问您说的客户端没有消费消息，broker自身也有很小的tps。 这个broker本身很小的tps会随着topic的增多而增多吗？我们的系统中有500个topic，每日消费消息数大约是6万个，但broker 5min trend值一直在400左右，请问这正常吗？

broker自身带的tps几乎没有影响，只有0.0几。正常不正常不是很好估算，每日消息数6万，可能被不同groupId消费了很多次，还可能6万消息在很短时间内消费的tps就很高。图上的broker 5min trend本身也不是很准确。

**Comment by caigy** [comment]
> @caigy @ni-ze “每日消费消息数大约是6万个”指代消息被消费总数，反应在参数中是todayConsumeCount和yesterdayConsumeCount。 我就很疑惑 指标是400 按400*60*24 每天应该是差不多60W条消息被消费， 但实际情况只有6万
@18205097282 可以看下stats.log中'Stats In One Minute'的记录，这里有按分钟统计的指标可供印证。

**Comment by 18205097282** [comment]
@ni-ze 
我查了，我的指标是400，基本上全是MissTPS 造成的，FoundTPS值很小。

“从存储中查询消息，如果能找到就算在FoundTPS中，找不到就算在MissTPS中。”
When org.apache.rocketmq.store.DefaultMessageStore#getMessage is called, getMessageTimesTotalFound or getMessageTimesTotalMiss is incremented.

对不起，我没有听懂，因为找一次，MissTPS或FoundTPS其中一个必+1,
也就是两者之和 TotalTPS必+1。那我的指标值不就是恒等于DefaultMessageStore#getMessage的调用次数了吗？

**Comment by odbozhou** [comment]
> 

这个展示的数据正如标题Broker 5min trend，主要是看broker消费tps数据趋势的，可以帮助我们查看broker是否有突发流量，broker流量是否平稳正常等，一般不用这个数据计算消息量，因为这个broker数据趋势是通过 消费到消息请求的tps + 没有消费请求tps计算的，所以即使没有消息，也会有拉取消息的请求，即使没有消息可以拉取到，也会有tps。如果对详细的消费感兴趣可以看一下客户端消费消息的逻辑，这更有助于了解这些数据。

**Comment by ni-ze** [comment]
> @ni-ze 我查了，我的指标是400，基本上全是MissTPS 造成的，FoundTPS值很小。
> 
> “从存储中查询消息，如果能找到就算在FoundTPS中，找不到就算在MissTPS中。” When org.apache.rocketmq.store.DefaultMessageStore#getMessage is called, getMessageTimesTotalFound or getMessageTimesTotalMiss is incremented.
> 
> 对不起，我没有听懂，因为找一次，MissTPS或FoundTPS其中一个必+1, 也就是两者之和 TotalTPS必+1。那我的指标值不就是恒等于DefaultMessageStore#getMessage的调用次数了吗？

是等于getMessage调用次数，但是不等于你消息的条数，比如两个groupId都把6万各消息消费一遍，那么getMessage也被调用了12万次，totalTPS也是12万
