### ISSUE TITLE
[poll] Commit consume offset with specified MessageQueue

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq#3804]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Commit consume offset with specified MessageQueue

2. Provide any additional detail on your proposed use case for this feature.

when we use DefaultLitePullConsumer, we commit consume offset to broker, but there is only one commit api : commitSync, it will commit all MessageQueue you subscribe/assign. However, in streams scene, we need commit offset of specified MQ.

add commit api like:

```java
commitSync(Map<MessageQueue, consumeOffset>)
```
3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

must-have

**Comment by ni-ze** [comment]
I will add a pr to solve this.

**Comment by zhouxinyu** [comment]
Could please provide more details about you mentioned streams scene? Actually, we need pay more cautious when adding new APIs in rocketmq-client.

**Comment by ni-ze** [comment]
> Could please provide more details about you mentioned streams scene? Actually, we need pay more cautious when adding new APIs in rocketmq-client.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/31175234/154059272-9d3e4ee2-1b5d-4709-9898-2058547a92d1.png">

state data in streams is partitioned, and sometimes only one of the MessageQueue offset will be commit.
such as only commit MQ0 or MQ1.
