### ISSUE TITLE
Broker stat getTotalTps

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#3805]
The getTotalTps return the broker's pull request  count in broker stat command . Why not return the broker's pull message count?
When call DefaultMessageStore's getMessage method , at the end of method, totalCount will increase 1 no matter how many messages is found.
```java
if (GetMessageStatus.FOUND == status) {
            this.storeStatsService.getGetMessageTimesTotalFound().add(1);
        } else {
            this.storeStatsService.getGetMessageTimesTotalMiss().add(1);
        }
```

I wonder if it can change to message count , or add a new response param to show message pull trend?

**Comment by Kvicii** [comment]
@coder-zzzz I think it should be counted as an optimization.this should be correct

**Comment by caigy** [comment]
`getTotalTps` indicates how busy the broker serves the pull request, which is based on **request**, and it is different from the number of messages found, which is based on **response**. So I think they are two different metrics.

**Comment by coder-zzzz** [comment]
@Kvicii @caigy add a new metric maybe a good choice

**Comment by Kvicii** [comment]
@coder-zzzz 
If this metric is really needed, I think it's up to vote, if it's just a small change, it counts as an optimization

**Comment by cserwen** [comment]
I think you are talking about this metric:`BROKER_GET_NUMS`.

**Comment by coder-zzzz** [comment]
> BROKER_GET_NUMS

you are right! Tks
