### ISSUE TITLE
DefaultMQAdminExtImpl#resetOffsetByTimestampOld complexity is too high, the loop nesting is serious

### ISSUE THREAD

**Issue by Kvicii** [apache/rocketmq#3810]
1. Please describe the issue you observed:

DefaultMQAdminExtImpl#resetOffsetByTimestampOld complexity is too high, the loop nesting is serious.

2. Please tell us about your environment:

Java version: 11.0.14
OS name: "mac os x", version: "12.2", arch: "x86_64", family: "mac"

3. Please describe the feature you are requesting.

Refactor this method, use Map instead of List judgment, reduce loop nesting.

**Comment by lizhiboo** [comment]
@Kvicii IMO, change return type from List to Map can not avoid loop nesting, because reset each queue offset of each broker is needed.
