### ISSUE TITLE
DefaultMQProducer#sendKernelImpl  Line760 tranMsg does not need to check for null when using Boolean.parseBoolean()

### ISSUE THREAD

**Issue by LemonFish873310466** [apache/rocketmq#3812]
Location: src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java  #sendKernelImpl Line760

![image](https://user-images.githubusercontent.com/48646884/152484246-3f7a242d-cc19-4338-87dd-ca571a5a6d56.png)

The implementation of parseBoolean is as follows. It internally judge whether it's null.
```java
    public static boolean parseBoolean(String s) {
        return ((s != null) && s.equalsIgnoreCase("true"));
    }
```

**Comment by HScarb** [comment]
You can submit a PR to fix it,

**Comment by Kvicii** [comment]
@LemonFish873310466 
hi, there.
please provide rocketmq version, I fixed it on develop branch.[PR-3813](https://github.com/apache/rocketmq/pull/3813)
