### ISSUE TITLE
upgrade snakeyaml due to CVE

### ISSUE THREAD

**Issue by pjfanning** [apache/rocketmq#3814]
**BUG REPORT**

snakeyaml 1.19 has a serious issue - https://mvnrepository.com/artifact/org.yaml/snakeyaml - an entity expansion vulnerability

**Comment by Kvicii** [comment]
@pjfanning thanks for your report,
@dongeforever we need upgrade it.

**Comment by pjfanning** [comment]
I submitted https://github.com/apache/rocketmq/pull/3815
