### ISSUE TITLE
upgrade guava due to CVE

### ISSUE THREAD

**Issue by pjfanning** [apache/rocketmq#3818]
**BUG REPORT**

Current pom.xml has guava 19.0. This jar has 2 security vulnerabilities - https://mvnrepository.com/artifact/com.google.guava/guava/19.0

Can we upgrade to v31.0.1-jre?

**Comment by caigy** [comment]
Upgrading Guava is OK, but it seems that there is no reference to Guava in RocketMQ.

**Comment by pjfanning** [comment]
@caigy rocketmq-filter seems has a guava dependency and appears to use guava code (imports like com.google.common.cache.Cache). 

https://github.com/apache/rocketmq/blob/develop/filter/pom.xml#L41

https://github.com/apache/rocketmq/blob/develop/filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParser.java#L21
