### ISSUE TITLE
ch.qos.logback.core.joran.spi.JoranException: Could not open [/**/rocketmq/conf/logback_namesrv.xml

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#3823]
**BUG REPORT**

1. Please describe the issue you observed:

I want to debug code, when I config ROCKETMQ_HOME and copy logback_namesrv.xml to conf directory, after start nameserver 

ch.qos.logback.core.joran.spi.JoranException: Could not open [/**/rocketmq/conf/logback_namesrv.xml

I expect I can start nameserver success

**Comment by RongtongJin** [comment]
The log configuration file must be in java.ext.dirs or classpath.

**Comment by Oliverwqcwrw** [comment]
I have configured the environment variables ROCKETMQ_HOME and I copy log configuration file into conf

**Comment by Oliverwqcwrw** [comment]
I follow the RocketMQ Tech Insider tutorial

**Comment by Oliverwqcwrw** [comment]
I know the problem because I wrote conf as config,thank you
