### ISSUE TITLE
Removing unused class file

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq#3836]
see: [MQHelper](https://github.com/apache/rocketmq/blob/develop/client/src/main/java/org/apache/rocketmq/client/MQHelper.java)

![image](https://user-images.githubusercontent.com/31175234/153203456-97c389e4-d75f-46ca-b47f-17979b97a84e.png)

Nowhere  use this class, I think it should be removed.

**Comment by RishiKumarRay** [comment]
@ni-ze @lizhiboo is there anything else we have to do alongwith removing this public class MQHelper {
    public static void resetOffsetByTimestamp(
        final MessageModel messageModel,
        final String consumerGroup,
        final String topic,
        final long timestamp) throws Exception {
        resetOffsetByTimestamp(messageModel, "DEFAULT", consumerGroup, topic, timestamp);
    }

**Comment by ni-ze** [comment]
I think not.

**Comment by RishiKumarRay** [comment]
the issues says remove class file ? do we have to remove whole file? or the above class only?

**Comment by ni-ze** [comment]
remove whole file.

**Comment by RishiKumarRay** [comment]
@ni-ze can you please review this? i hope i did it correctly

**Comment by caigy** [comment]
`MQHelper` may be used by external users of rocketmq-client, you'd better also provide alternative solution after `MQHelper` is removed.

**Comment by ni-ze** [comment]
@RishiKumarRay @caigy I think we can add @deprecated on this class, then removed after several versions.

**Comment by RishiKumarRay** [comment]
@ni-ze so do i restore the file and add @deprecated

**Comment by ni-ze** [comment]
ok, add @Deprecated is ok.

**Comment by RishiKumarRay** [comment]
@ni-ze please check this PR , i had to close previous one due to some problem. Thanks
