### ISSUE TITLE
how to add broker smoothly in a running dledger cluster?

### ISSUE THREAD

**Issue by qq958905365** [apache/rocketmq#3840]
hello guys,
    I want to add a broker to my running dledger cluster,  and the cluster can't restart.  I try
to use mqadmin with updateBrokerConfig to update dLegerPeers, I can see dLegerPeers is already update to every broker,  but the new broker can't work, the logs show me  "WARN NettyServerPublicExecutor_1 - [BUG] [HandleVote] remoteId=n3 is an unknown member".
could anybody help me?

**Comment by dongeforever** [comment]
currently, it is not able to add broker to a dledger group dynamically.  You need to change the dledger configuration and restart all the brokers in the group.

**Comment by dongeforever** [comment]
@qq958905365 Could you describe the detailed use case? Why do need to add a broker to a running cluster?
In fact, I used to think this op is not practical. 
It is better to fix the replica number during the deployment.

**Comment by yiduwangkai** [comment]
maybe i can try to do it
