### ISSUE TITLE
4.8.0版本，在创建group之后使用API查看以确认group是否已创建

### ISSUE THREAD

**Issue by ahrtolia** [apache/rocketmq#3842]
4.8.0版本在未创建topic的情况下先创建group，此时调用mqadmin运维工具怎么查看这个group是否存在
已知可以在服务器上通过查看store/config/subscriptionGroup.json查看，不知道有没有封装好的API可以直接查看。

**Comment by cserwen** [comment]
https://github.com/apache/rocketmq-dashboard  You can deploy this service to manage your cluster.
