### ISSUE TITLE
[RIP-33] Active push when the broker role changes

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#3843]
Active push when the broker role changes，reduce the impact on sequential message producers.
When the broker role sends changes, such as re-election，The nameserver will actively send rpc requests to the client, so that the client no longer relies on the rotation training to perceive.

**Comment by ltamber** [comment]
Can we give more details about this RIP ? Additionally, RIP-32 may occupied by #3824

**Comment by dongeforever** [comment]
@Cczzzz Do you mean the metadata discovery time is too long when the broker role changes?

**Comment by Cczzzz** [comment]
> @Cczzzz Do you mean the metadata discovery time is too long when the broker role changes?

yes,now max is 30s

**Comment by RongtongJin** [comment]
Hi, @Cczzzz RIP-33 has occupied by [RocketMQ MQTT](https://github.com/apache/rocketmq/wiki/RIP-33-RocketMQ-MQTT), RIP-34 has occupied by [Support quorum write and adaptive degradation in master slave architecture](https://github.com/apache/rocketmq/wiki/RIP-34-Support-quorum-write-and-adaptive-degradation-in-master-slave-architecture). If you want to start a RIP, you should start a [DISCUSS] thread on the Apache RocketMQ dev mailing list firstly. You can refer https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal

**Comment by Cczzzz** [comment]
> Hi, @Cczzzz RIP-33 has occupied by [RocketMQ MQTT](https://github.com/apache/rocketmq/wiki/RIP-33-RocketMQ-MQTT), RIP-34 has occupied by [Support quorum write and adaptive degradation in master slave architecture](https://github.com/apache/rocketmq/wiki/RIP-34-Support-quorum-write-and-adaptive-degradation-in-master-slave-architecture). If you want to start a RIP, you should start a [DISCUSS] thread on the Apache RocketMQ dev mailing list firstly. You can refer https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal

ok
