### ISSUE TITLE
actively switch matser and forward messages to the new master

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#3858]
The purpose is to solve the broker restart update under the sequential message.The master can actively downgrade to slave after receiving the command.And after the new master is elected, and the client perceives the new master,forward messages to the new master。
只关注于dledger 模式，master-slave 还不支持角色切换
目的是解决顺序消息生产的问题下broker 重启更新的问题。如果要重启broker 总要不可避免出现发送失败，对顺序消息的生产者很不友好，我发现不可用时间主要由  等待逻辑队列的构建和客户端轮训的时间，最坏可能大于1分钟。
解决方案：
        1.broker 接受到命令后 进行dledger 的重新选举，（短暂不可用直到raft 日志相同）
        2.raft 协议选举完成感知新leader
        3.之后直到生产者客户端感知之前，客户端依然会发生消息到原master
        4.此时原master 将消息转发到新leader
这样对于顺序消息的发送者的不可用时间只有raft 的选举时间

**Comment by XiaoyiPeng** [comment]
Looking forward to your PR.

**Comment by XiaoyiPeng** [comment]
After the election, members of the cluster should also synchronize data with the leader and perform **TRUNCATE** or **APPEND** diff entry to ensure data consistency.
Only after data synchronization, the cluster can accept write requests from clients.
