### ISSUE TITLE
4.3事务消息回查功能

### ISSUE THREAD

**Issue by zangyk** [apache/rocketmq#386]
测试了一下4.3事务消息回查功能，
如果一个producer本地事务状态是UNKNOW，过一会可以收到回查调用，
但是如果把这个producer杀掉了，再重启这个producer收不到回查调用呐，而且同一个producerGroup的其他producer也收不到回查调用。
看之前的介绍是可以回查同一producerGroup的其他producer。如果本身不支持回查同一producerGroup的其他producer，那事务回查的高可用就基本没意义了吧！

**Comment by suclogger** [comment]
代码实现是在每次查询时取同一producerGroup下可用producer回查，极端情况producer异常退出channel任然被broker持有导致回查失败，下一次回查会路由到不同producer上。可以观察broker端是否有类似“Check transaction failed because invoke producer exception”的错误日志来确认是否请求到了异常的channel上。
另外最好贴一下你的相关代码实现和配置，最好有日志输出便于大家分析。

**Comment by zangyk** [comment]
运行的代码就是http://rocketmq.apache.org/docs/transaction-example/上提供的，查看后台日志有输出
WARN Transaction-msg-check-thread - Check transaction failed, channel is null. groupId=producerGroup1

**Comment by suclogger** [comment]
@zangyk 这个日志输出表明当前producerGroup1下没有活跃的消费者。你提到的：

>同一个producerGroup的其他producer也收不到回查调用。

这个不成立啊。如果确实启动了多个producer，检查下producerGroup是否设置正确了。

**Comment by zangyk** [comment]
大概知道什么原因了，producer在start()后，必须发一条消息，本地MQClientInstance类通过topic获得该topic的路由信息，知道对应哪些broker，broker上才能注册这个producer到相应的producerGroup下，才能收到回查消息。如果只是start(),而不发送一条消息，这个producer是收不到回查消息的。这种处理方式也不知道好不好，如果业务上真有start后，很长时间没有其他消息的情况，是不是就收不到之前消息的回查信息了？

**Comment by suclogger** [comment]
@zangyk producer在broker端的注册并不需要通过发送消息，而是通过发送心跳包的方式。

**Comment by zangyk** [comment]
MQClientInstance中是通过topic从nameserver上确定对应哪些的broker的，如果不发消息，MQClientInstance中调用MQProducerInner的getPublishTopicList(),中就没有这个topic的值，获取不到对应的broker，发心跳时也就不会给这些broker发心跳。
也有一种其他处理方法是：producer在start前，设置producer.setCreateTopicKey("topic");这样即使不发消息，MQClientInstance也能知道topic对应的broker，向他们发送心跳，可以在broker注册producer信息，向它发回查消息。

**Comment by vongosling** [comment]
实在不想打断大家 :-)Issue的目的是用来做Issue Report和 feature request的，大家讨论可否订阅RocketMQ user邮件列表，里面有更多的小伙伴对事务消息充满了好奇。总之，非常感谢大家对事务消息的青睐，在事务消息之上，我们还可以做一些更好玩的探索，也欢迎大家在user列表里讨论。
