### ISSUE TITLE
When I use multi-threading to produce message, I lost some message by one consumer

### ISSUE THREAD

**Issue by kengan** [apache/rocketmq#3866]
I setup rocketmq with single node
I use 2 thread to produce message, each thread send 10 messages 
on the other hand, I use a thread to consume the message and I found that I can not get all message and always lost some message

I use  DefaultMQProducer  to send message as following:
 **private DefaultMQProducer producer=
 SendResult sendResult =producer.send(mqMessage, 60000);**

I use  the following code to comsume the messasge:

 consumer.setMessageModel(MessageModel.CLUSTERING);
 consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_LAST_OFFSET);
 consumer.setMaxReconsumeTimes(3);
 consumer.setConsumeMessageBatchMaxSize(50);

 consumer.registerMessageListener(new MessageListenerConcurrently() {
                @Override
                public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> messagelist, ConsumeConcurrentlyContext consumeConcurrentlyContext) {
                      //do some job

                }
            });

Can you help me, Thank you very much

**Comment by ni-ze** [comment]
Looking forward to providing more details.

**Comment by SchopenhauerZhang** [comment]
it seem like batch size config questions。you can see https://github.com/apache/rocketmq/issues/1451。
