### ISSUE TITLE
What is the naming convention for  produceGroupName?

### ISSUE THREAD

**Issue by PEIYANGXINQU** [apache/rocketmq#3867]
If I set the produceGroupName like '192.168.1.1:9889-abcd',It will cause the :**MQClientException   The producer service state not OK, START_FAILED**. If I only set the produceGroupName like uuid,it is ok.So I curious about the naming convention for   produceGroupName.

**Comment by HScarb** [comment]
```
[192.168.1.1:9889-abcd] contains illegal characters, allowing only ^[%|a-zA-Z0-9_-]+$
```
`:` is illegal

The validate logic is in `DefaultMQProducerImpl#checkConfig()`

https://github.com/apache/rocketmq/blob/develop/common/src/main/java/org/apache/rocketmq/common/topic/TopicValidator.java#L62-L82

**Comment by PEIYANGXINQU** [comment]
收到，谢谢！
