### ISSUE TITLE
Load indexfile from abnormal abort may lose index data

### ISSUE THREAD

**Issue by HScarb** [apache/rocketmq#3868]
In IndexService#load
```java
                    IndexFile f = new IndexFile(file.getPath(), this.hashSlotNum, this.indexNum, 0, 0);
                    f.load();

                    if (!lastExitOK) {
                        if (f.getEndTimestamp() > this.defaultMessageStore.getStoreCheckpoint()
                            .getIndexMsgTimestamp()) {
                            f.destroy(0);
                            continue;
                        }
                    }

                    log.info("load index file OK, " + f.getFileName());
                    this.indexFileList.add(f);

```

* `f.getEndTimestamp()` indicates file's last write timestamp
* `indexMsgTimestamp` in `StoreCheckpoint` indicates  indexfile last flush timestamp

Consider a situation that index file last write timestamp is later than flush timestamp, but first write timestamp is earlier than flush timestamp, what will happen is that the file with some valid data will be destroy and some index data will be lost.

![image](https://user-images.githubusercontent.com/10664298/154814185-0f415404-379e-4cdf-8bd7-f57b68ae2371.png)

Is this design like so or it is a bug?

**Comment by WJL3333** [comment]
i think you are right. the current recover logic only cover consumer queue, the index service recovery is not involved.

**Comment by absolute8511** [comment]
Any fix is going on in plan for this?
