### ISSUE TITLE
如何对启用ssl的rocketmq进行压侧

### ISSUE THREAD

**Issue by lsw21** [apache/rocketmq#3871]
rocketmq环境启用ssl，现在想对该环境进行压侧对比性能，发现最新版本的benchmark脚本，比如producer.sh，也不支持ssl访问？
这样的话，只能自己写代码进行压侧？谢谢指点！

**Comment by ShannonDing** [comment]
1.在客户端启动时，增加java启动参数 "-Dtls.enable=true"

**Comment by ShannonDing** [comment]
2. setUseTLS(true);
