### ISSUE TITLE
消息转换成Half消息时Queue都被设置成0，是BUG吗？

### ISSUE THREAD

**Issue by dbl-x** [apache/rocketmq#388]
TransactionalMessageBridge#parseHalfMessageInner 200行，替换消息属性时，消息的Topic被替换成内部的Half消息的Topic，QueueId被设置成0，这样所有事物消息都被写入了同一个Q，这里是不是手误写错了？

Half Topic的Queue和Op Topic的Queue应该是一一对应的。

**Comment by vongosling** [comment]
ping @duhengforever

**Comment by duhengforever** [comment]
@dbl-x Here is a trade-off in design, under the existing checking design, single queue is a better choice, but we also leave a margin for the extension, so in the scan method ,we considered the case of multi queues.

**Comment by dbl-x** [comment]
How does single queue model guarantee performance, is there performance data?

**Comment by vongosling** [comment]
@dbl-x If you have any other question, please use our user email list. As you see from our issue template, it is not a suitable place to discuss user's question in here, thank you for understanding :-)
