### ISSUE TITLE
inner class DefaultLitePullConsumerImpl.ConsumeRequest may be 'static'

### ISSUE THREAD

**Issue by wangdi761** [apache/rocketmq#3883]
inner class DefaultLitePullConsumerImpl.ConsumeRequest may be 'static'

**Comment by lizhiboo** [comment]
@wangdi761 ConsumeRequest is only used in DefaultLitePullConsumerImpl. In which case should make it static?

**Comment by ShannonDing** [comment]
> @wangdi761 ConsumeRequest is only used in DefaultLitePullConsumerImpl. In which case should make it static?

best to keep it in the status quo.
