### ISSUE TITLE
关于VIP_CHANNEL疑问

### ISSUE THREAD

**Issue by xiaohei88** [apache/rocketmq#3889]
**BUG REPORT**

1. Please describe the issue you observed:

### 问题描述
生产者通过VIP通道发送消息，假如，每天发送100条，量不大。服务端有个AllIdleTimeoutTask任务，判断通道是否空闲，如果120秒没使用，就关闭了。主通道因为有心跳每30秒一次，刷新lastWriteTime值，所以主通道基本上不会关闭。但是vip通道没有心跳，所以如果发送量不大，超过时间就会关闭。

### 疑问
假如生产者通过vip通道发送消息，请求过来了，但是还没来得及刷新lastWriteTime或者lastReadTime值，AllIdleTimeoutTask这个时候正好将通道关闭了。
客户端报错，超时。wait response on the channel <:10909> timeout, 10000(ms)。服务端日志正好是10秒之前有个closeChannel: close the connection to remote address。
会有以上我说的这个问题么

2. Please tell us about your environment:
rocketmq 4.3.0

4. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

**Comment by panzhi33** [comment]
消息发送是不走vip的，而且高版本已经默认把vipChannelEnabled 这个给关闭了，都走10911了

**Comment by ShannonDing** [comment]
use default port 10911.

**Comment by ShannonDing** [comment]
link #1510
