### ISSUE TITLE
Can I register multiple broker clusters with the same group of nameservers? Can I view multiple clusters on the rocketmq dashboard? I found no change after selection

### ISSUE THREAD

**Issue by sha-dow90** [apache/rocketmq#3892]
The resource of our servers is abundant, so we hope to build multiple clusters on the same three servers. If I use the same group of nameservers, the broker groups I see on the rocketmq-dashboard are not distinguished according to the "brokerclustername". They are mixed together. Although multiple cluster names can be seen on the console, the page does not change after selection, Moreover, the broker was shown to be an unexpected cluster
![image](https://user-images.githubusercontent.com/33504756/155692525-035f1942-413a-4b38-a9e4-b30eafb2158e.png)

**Comment by panzhi33** [comment]
This is distinguished by brokerClusterName, maybe your configuration is wrong.
It is recommended to use brokerClusterName-brokerName as the naming format of brokerName for easy viewing

**Comment by liuliangmao** [comment]
不同brokerClusterName的broker应该注册到不同的nameserver集群吗
