### ISSUE TITLE
Bump Junit4 to Junit 5.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/rocketmq#3902]
Bump Junit4 to Junit5 can bring us a lot of benefits.

**Comment by duhenglucky** [comment]
@GOODBOY008 would you like to submit a PR to polish it ?

**Comment by GOODBOY008** [comment]
@duhenglucky Yes,I am willing to polish it. Please assgin this issue to me.

**Comment by GOODBOY008** [comment]
@duhenglucky About  `assert` api, I think we can use `org.assertj:assertj-core:3.21.0`, it supplys a lot of powerful Assertions.

**Comment by acmday** [comment]
@GOODBOY008 I hope we can do it together
