### ISSUE TITLE
Support brokerName in request protocol

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq#3905]
**FEATURE REQUEST**

1. Support `brokerName` in request protocol.
2. `brokerName` is a higher-level abstraction than `brokerAddress` and should be taken in request.
3. Related components should know request-target by `brokerName` such as logic queue extension, envoy-like cloud-native gateway, or even more separate computing and storage to decouple computing from current broker logic.
4. Detail request code: `PULL_MESSAGE`, `UPDATE_CONSUMER_OFFSET`, `QUERY_CONSUMER_OFFSET`, `SEARCH_OFFSET_BY_TIMESTAMP`, `GET_MIN_OFFSET`, `GET_MAX_OFFSET`.

**Comment by ni-ze** [comment]
BrokerAddress can be used as a router, I do not get why do you need brokerName.

**Comment by duhenglucky** [comment]
@drpmma In favor of this recommendation, the entire Remoting layer is currently IP oriented. Using broker names instead of IP can better hide the underlying state of the broker, especially the abstraction of logical resources brought by logical queues and other features.

**Comment by lizhanhui** [comment]
+1 for the change. IP-centered strategy suffers a lot in the era of cloud and container orchestration. We need logical representation to adapt to this trend.

**Comment by chenzlalvin** [comment]
Not only brokerName, the queueId also need abstraction, unbind with specific physical node

**Comment by drpmma** [comment]
Now that `bname` is supported in RpcRequestHeader, related RPC can use this field to implement.
