### ISSUE TITLE
Mark stream-related request by RequestType

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq#3906]
1. Plan to add a RequestType in remoting protocol to indicate stream requests including requests driven by `PullConsumer` and `LitePullConsumer`.
2. Stream is an important part of rocketmq and it is not marked and distinguished with the messaging-related requests by now. It is helpful for observability and other features to mark it explicitly

**Comment by ni-ze** [comment]
I am sorry, I think we can put a key value pair in properties of Message,  then we know what business the message comes from. Adding business attributes into remote protocol  is not recommended.

**Comment by lizhanhui** [comment]
@drpmma Would you mind offering your use case story? Looks you and @ni-ze  are talking about two completely different things.
