### ISSUE TITLE
[RIP-7] Support multi-directory storage in DLedger.

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq#3914]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Multi-directory storage has been supported in 4.9.2, but it only supports master-slave deployment mode. We should also support this feature in DLedger deployment mode.

2. Provide any additional detail on your proposed use case for this feature.
Refer to this pr https://github.com/apache/rocketmq/pull/3357 to implement it.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
Should-have.
5. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [x] [Task-1](https://github.com/openmessaging/dledger/issues/118): Make [DLedger](https://github.com/openmessaging/dledger) support mult-directory storage.
- [x] Task-2: Upgrade DLedger dependencies and adapt it. https://github.com/apache/rocketmq/pull/4122

**Comment by Jason918** [comment]
> We can combine this feature with RIP-31, because if a server has 12 disks, it is impossible for us to deploy 12 brokers. We can use this feature to allocate a few disks to each broker, so that each node of a group can be utilized and It can also ensure that a broker has enough space to use.

This motivation LGTM.

**Comment by RongtongJin** [comment]
Merged
