### ISSUE TITLE
Requesthousekeepingservice thread leak（release-4.9.2）

### ISSUE THREAD

**Issue by minxiangli** [apache/rocketmq#3923]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
1.run this demo

`public void test() throws InterruptedException {
    for(int i = 0; i < 100; i++) {
        for (int j = 0; j < 20; j++) {
            CompletableFuture.runAsync(()->{
                DefaultMQProducer producer = new     DefaultMQProducer("please_rename_unique_group_name");
                producer.setNamesrvAddr("localhost:9876");
                try {
                    producer.start();
                } catch (MQClientException e) {
                    e.printStackTrace();
                }finally {
                    producer.shutdown();
                }
            });
        }
    }
    Thread.sleep(1000*60*60*5);
}
`

- What did you see instead?
![image](https://user-images.githubusercontent.com/39690875/156505715-c9ec5b94-7b62-493d-9f66-3634e95a4209.png)
![image](https://user-images.githubusercontent.com/39690875/156505795-75d5d2ce-4c6a-4531-bce6-d78e7f0562e4.png)
![image](https://user-images.githubusercontent.com/39690875/156505994-5faa3965-d9c6-4213-9c97-73db5818dcd9.png)

2. Please tell us about your environment:
jre : 1.8
os: mac os
rocketmq-version : release-4.9.2

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
![image](https://user-images.githubusercontent.com/39690875/156506304-973f6033-eb16-45fb-bf27-984c9b936415.png)
![image](https://user-images.githubusercontent.com/39690875/156506421-574d3485-1013-42a7-90e9-ae545576d5ca.png)

 scheduledExecutorService.scheduleAtFixedRate() and scheduledExecutorService.shutdown() are not synchronous methods。
 You can't guarantee that there is only one “RequestHouseKeepingService”。

**Comment by panzhi33** [comment]
can see #3639

**Comment by RongtongJin** [comment]
Has been fixed in RocketMQ 4.9.3
