### ISSUE TITLE
 producer may blocked until timeout when broker server crashed

### ISSUE THREAD

**Issue by qsrg** [apache/rocketmq#3929]
rocketmq:4.4.0、4.9.0
I find when broker server crashed，the sync producer will blocked until timeout in some times，then throws RemotingTimeoutException: wait response on the channel ...

```
//org.apache.rocketmq.remoting.netty.NettyRemotingAbstract#invokeSyncImpl   
            // broker 异常宕机可能会导致生产者等待响应直到超时
            RemotingCommand responseCommand = responseFuture.waitResponse(timeoutMillis);
            if (null == responseCommand) {
                if (responseFuture.isSendRequestOK()) {
                    throw new RemotingTimeoutException(RemotingHelper.parseSocketAddressAddr(addr), timeoutMillis,
                        responseFuture.getCause());
                } else {
                    throw new RemotingSendRequestException(RemotingHelper.parseSocketAddressAddr(addr), responseFuture.getCause());
                }
            }

```
The message has send to broker, when producer `waitResponse` the broker crashed at the same time， cause producer  blocked in `waitResponse` until timeout 。In this case, producer can't retry. I think it's better to wake up producer's  waiting state let it has enough time to retry  when the broker crashed.

**Comment by ni-ze** [comment]
No, It's not a problem, message will be resend to other broke in method DefaultMQProducerImpl#sendDefaultImpl.

**Comment by qsrg** [comment]
@ni-ze as there is no time left，sendDefaultImpl will break to resend

**Comment by ni-ze** [comment]
> 

yeah. retry to other messageQueue.

**Comment by qsrg** [comment]
@panzhi33 @RongtongJin

**Comment by ni-ze** [comment]
You can set a send message timeout by:
```java
producer.setSendMsgTimeout();

//or
producer.send(msg, sendTimeout);
```

**Comment by qsrg** [comment]
> You can set a send message timeout by:
> 
> ```java
> producer.setSendMsgTimeout();
> 
> //or
> producer.send(msg, sendTimeout);
> ```

org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl#sendDefaultImpl
```
            for (; times < timesTotal; times++) {
//...
                        if (timeout < costTime) {
                            callTimeout = true;
                            break;
                        }
```
the timeout parameter will be passed to the method `nvokeSyncImpl` and exhausted in `responseFuture.waitResponse `，no matter how much timeout setted，so producer  can't retry

**Comment by ni-ze** [comment]
It does might happen, If an RemotingTimeoutException occurs on the first send, will not retry. An exception was thrown to the client, It's up to you how to handle it. If client retry to other messageQueue will break timeout semantics.

**Comment by qsrg** [comment]
@ni-ze I don't agree with you,  I think it's better to wake up producer's waiting state let it has enough time to retry when the broker crashed

**Comment by fengjianjun1** [comment]
我感觉大部分是中国的吧，打点汉字吧   看着舒服~~

**Comment by wangazhang** [comment]
> 我感觉大部分是中国的吧，打点汉字吧 看着舒服~~

english is better ,the official recommended

**Comment by francisoliverlee** [comment]
IMO
one broker crashed, it would be better for producers immediately to retry anthoer broker after broker response with crash error, not block.
how `responseFuture.waitResponse(timeoutMillis)`  does maters

**Comment by qsrg** [comment]
I'll fix it later
