### ISSUE TITLE
rocketMQTemplate.sendAndReceive(), MQClientException: CODE: 10007  DESC: create reply message fail, requestMessage error, property[CLUSTER] is null.

### ISSUE THREAD

**Issue by ToDropBombs** [apache/rocketmq#3930]
springboot集成rocketmq，使用rocketMQTemplate.sendAndReceive()，会报错，error：MQClientException: CODE: 10007  DESC: create reply message fail, requestMessage error, property[CLUSTER] is null， 提示缺少【CLUSTER】

RocketMQReplyListener方法可以接收消息：
![企业微信截图_16463878001936](https://user-images.githubusercontent.com/24791893/156741893-8a2af42f-2e39-49e1-9deb-17b5bb751e88.png)
但是reply的时候会报错：
![企业微信截图_16463878961487](https://user-images.githubusercontent.com/24791893/156742064-db636304-040b-41cb-ad99-50485b044a7f.png)

测试部署环境：docker部署的单ns和broker，请问【CLUSTER】是从哪里来的？

**Comment by ToDropBombs** [comment]
还是说这个应答reply的功能只能在集群部署环境才生效

**Comment by RongtongJin** [comment]
你好，请问使用是服务端和客户端版本是？

**Comment by 1autodidact** [comment]
I encountered a similar problem and solved it with my own exploration

### Environment
```
 <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.2.1</version>
</dependency

 <dependency
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.1.1</version>
</dependency>
```
### code
```
rocketMQTemplate.sendAndReceive(MQTopic.QUESTION_TOPIC,question, new RocketMQLocalRequestCallback() {
            @Override
            public void onSuccess(Object message) {
                log.error("消息发送成功" + JSONObject.toJSONString(message));
            }

            @Override
            public void onException(Throwable e) {
                log.error("消息发送失败",e);

            }
        });
```

```
@Component
@RocketMQMessageListener(topic = "question_topic",consumerGroup = "question_consumer")
@Slf4j
public class QuestionConsumer implements RocketMQReplyListener<Question, Question> {
    @Resource
    QuestionMapper questionMapper;
    @Autowired
    private RocketMQTemplate rocketMQTemplate;
    @Override
    public Question onMessage(Question message) {
        questionMapper.insert(message);
        log.error( "线程名称：{}" +"message {}",Thread.currentThread().getName(),JSONObject.toJSONString(message));
        return message;
    }
}
```

### Solved Problem
rocketmq-spring-boot-starter version is okay for both 2.11 and 2.21

**The most important thing is that the installed version of rocketmq needs to be 4.7.1 (linux install the 4.7.1 version of rockemq
)**
![image](https://user-images.githubusercontent.com/41795715/187061535-8da0b4df-bff8-4e04-bfe6-9ddc5441d5c7.png)

I use docker to install docker pull apache/rocketmq:4.7.1
After adjusting the version of the docketmq installation, the cluster attribute is the brokerClusterName configuration in broker.conf

### How to use docker install rocketmq？
(https://www.cnblogs.com/d1012181765/p/15603378.html)

### conclusion
rockemq package version is the most import
@ToDropBombs @RongtongJin @duhenglucky

**Comment by ToDropBombs** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 1autodidact** [comment]
@duhenglucky @RongtongJin The bug can Mark resolved？

**Comment by ToDropBombs** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
