### ISSUE TITLE
Run request reply in the MAC os12 system, and the consumer will time out when returning the result

### ISSUE THREAD

**Issue by luky116** [apache/rocketmq#3933]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
  Run request reply in the MAC os12 system, and the consumer will time out when returning the result

- What is expected to see?
The consumer can normally return the result to generate this

- What did you see instead?
The consumer reply failed
![image](https://user-images.githubusercontent.com/38887641/156917706-353ea965-f5ee-4ed2-b66d-d38ac0236a10.png)

3. Please tell us about your environment:
    MAC OS 12

5. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
I ran the following example：
https://github.com/apache/rocketmq/tree/develop/example/src/main/java/org/apache/rocketmq/example/rpc

**Comment by jasondeng1997** [comment]
我也看看

**Comment by jasondeng1997** [comment]
![image](https://user-images.githubusercontent.com/76831112/156918084-30c71280-31f9-4f68-8bac-bd1cc0c364f5.png)

**Comment by jasondeng1997** [comment]
改成配置的服务器，也会报链接为空失败，是我开了vpn吗

**Comment by jasondeng1997** [comment]
vpn关掉也有这个问题

**Comment by drgnchan** [comment]
did you make a breakpoint at `ResponseConsumer.java`?

**Comment by guyinyou** [comment]
There may be a problem with my computer itself, my error is not the same as yours. 
Only throw timeout and no other information.
<img width="1177" alt="FCB6D747-FB2B-4ED9-A33F-7A32F3B569D0" src="https://user-images.githubusercontent.com/36399867/156984215-b213111a-6038-4d5d-87d6-b69a20facad5.png">

**Comment by maxid** [comment]
broker.conf need add brokerIP setting
brokerIP1=公网IP(all consumer will use brokerIP1)
brokerIP2=内网IP
hope rocketmq team can support rocket-client  use ip1 or ip2 option

**Comment by ni-ze** [comment]
I reproduce this bug, root cause is blocked when broker send message to producer. The blocking code is as fellow:
![image](https://user-images.githubusercontent.com/31175234/156995063-bbc550e3-1c30-4719-8b1a-c2e3125f9f78.png)
There are relationships with bornHost and storeHost of reply message.
```xml
bornHost=/127.0.0.1:59653, storeHost=/127.0.0.1:10911
``` 
will be blocked.

```xml
bornHost=127.0.0.1:59653, storeHost=127.0.0.1:10911
``` 
will not.

**Comment by ni-ze** [comment]
I start RocketMQ and nameserver producer and consumer in one machine.

**Comment by ni-ze** [comment]
![image](https://user-images.githubusercontent.com/31175234/157003460-daee1a19-3a23-4533-963d-1631ee0291ea.png)
Your producer is restarted, channel was removed in broker. Consumer receive the message before the restart, so broker can not found the channel.

**Comment by ni-ze** [comment]
> I reproduce this bug, the root cause is that producer is blocked when it receive a reply message . The blocking code is as fellow: ![image](https://user-images.githubusercontent.com/31175234/156995063-bbc550e3-1c30-4719-8b1a-c2e3125f9f78.png) There are relationships with bornHost and storeHost of reply message.
> 
> ```
> bornHost=/127.0.0.1:59653, storeHost=/127.0.0.1:10911
> ```
> 
> will be blocked.
> 
> ```
> bornHost=127.0.0.1:59653, storeHost=127.0.0.1:10911
> ```
> 
> will not.

```xml
Consumer Started.
ConsumeMessageThread_please_rename_unique_group_name_1 Receive New Messages: [MessageExt [brokerName=broker-a, queueId=0, storeSize=291, queueOffset=1, sysFlag=0, bornTimestamp=1646706163408, bornHost=/127.0.0.1:64310, storeTimestamp=1646706163423, storeHost=/127.0.0.1:10911, msgId=7F00000100002A9F000000000000ABF8, commitLogOffset=44024, bodyCRC=198614610, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='RequestTopic', flag=0, properties={MIN_OFFSET=0, REPLY_TO_CLIENT=30.250.200.36@78996#328339814781694, MAX_OFFSET=2, CONSUME_START_TIME=1646706163449, UNIQ_KEY=1EFAC824349418B4AAC22646A2CF0000, CLUSTER=DefaultCluster, TTL=3000, CORRELATION_ID=adabf809-ba1a-4187-a6ba-2bbba81439a2}, body=[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100], transactionId='null'}]] 
handle message: MessageExt [brokerName=broker-a, queueId=0, storeSize=291, queueOffset=1, sysFlag=0, bornTimestamp=1646706163408, bornHost=/127.0.0.1:64310, storeTimestamp=1646706163423, storeHost=/127.0.0.1:10911, msgId=7F00000100002A9F000000000000ABF8, commitLogOffset=44024, bodyCRC=198614610, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='RequestTopic', flag=0, properties={MIN_OFFSET=0, REPLY_TO_CLIENT=30.250.200.36@78996#328339814781694, MAX_OFFSET=2, CONSUME_START_TIME=1646706163449, UNIQ_KEY=1EFAC824349418B4AAC22646A2CF0000, CLUSTER=DefaultCluster, TTL=3000, CORRELATION_ID=adabf809-ba1a-4187-a6ba-2bbba81439a2}, body=[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100], transactionId='null'}] 
reply to 30.250.200.36@78996#328339814781694 , SendResult [sendStatus=SEND_OK, msgId=1EFAC824348718B4AAC22646A3070000, offsetMsgId=7F00000100002A9F000000000000AD1B, messageQueue=MessageQueue [topic=DefaultCluster_REPLY_TOPIC, brokerName=broker-a, queueId=0], queueOffset=14] 

```
I change my location from home to  work place, then I can not reproduce this block. example seems work right.
