### ISSUE TITLE
broker busy

### ISSUE THREAD

**Issue by Mark110513** [apache/rocketmq#3948]
RocketMQ使用的版本是：4.9.2

nameserver部署了 3 个节点
broker 部署了 5 台物理机，每台 1 主 1 从，dledge集群
机子配置：3台（16 核 128 G内存） + 2台（16 核 64 G内存）

【broker】配置文件：
brokerClusterName = RaftCluster
brokerName=39.3-broker0
listenPort=30911
namesrvAddr=10.254.39.1:9876;10.254.39.2:9876;10.254.39.3:9876
storePathRootDir=/data/rocketmq-4.9.2/dledger/store/node00
storePathCommitLog=/data/rocketmq-4.9.2/dledger/store/node00/commitlog
enableDLegerCommitLog=true
dLegerGroup=group-10.254.39.3
dLegerPeers=n30-10.254.39.3:40911;n31-10.254.39.3:40912;n32-10.254.39.3:40913

dLegerSelfId=n30

brokerIP1=10.254.39.3

deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

#发送消息线程等待时间，默认200ms
waitTimeMillsInSendQueue=400

#发送消息的最大线程数，默认1
sendMessageThreadPoolNums=16
#使用可重入锁
useReentrantLockWhenPutMessage=true

#开启临时存储池
transientStorePoolEnable=true
#开启Slave读权限（分担master 压力）
slaveReadEnable=true
#关闭堆内存数据传输
transferMsgByHeap=false
#开启文件预热
warmMapedFileEnable=true

【jvm配置】仅调整了堆内存
...
JAVA_OPT="${JAVA_OPT} -server -Xms20g -Xmx20g"
...

每台机子上都执行过 rocketmq-4.9.2/bin/os.sh，改了内核相关参数

接口压测的时候遇到的问题：（该接口无db读写操作，无其他复杂业务，仅查redis和rocketmq发消息）
1、吞吐量上不去，生产者用sync发送消息，吞吐量只有3000多
2、日志很多报错信息
    ①、[TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 402ms, size of queue: 92
    ②、[PCBUSY_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 357ms, size of queue: 19
    ③、Connection reset by peer

请帮忙看下是哪里的问题

**Comment by cserwen** [comment]
看起来不是DLedger部署模式的配置文件，或许你可以参考一下这个配置文件去测试 https://github.com/apache/rocketmq/tree/develop/distribution/conf/dledger

**Comment by cserwen** [comment]
sendMessageThreadPoolNums 设置有点小了，请求队列里的请求处理不完，超时了

**Comment by Mark110513** [comment]
sendMessageThreadPoolNums 设置为 16、32、64、90，测试结果都有上述问题

**Comment by duhenglucky** [comment]
waitTimeMillsInSendQueue=400 这个配置的有点小，另外可以同步增加queue size 的大小
warmMapedFileEnable=true 这个参数关掉
useReentrantLockWhenPutMessage 这个可以用回自旋锁，同步降低线程数，可以保持默认
transferMsgByHeap 这个建议保持默认
另外关注下磁盘的表现，stats.log 中的时间分布，丁老师的文章也可以看看： https://www.cnblogs.com/dingwpmz/p/12104702.html

**Comment by Mark110513** [comment]
> waitTimeMillsInSendQueue=400 这个配置的有点小，另外可以同步增加queue size 的大小 warmMapedFileEnable=true 这个参数关掉 useReentrantLockWhenPutMessage 这个可以用回自旋锁，同步降低线程数，可以保持默认 transferMsgByHeap 这个建议保持默认 另外关注下磁盘的表现，stats.log 中的时间分布，丁老师的文章也可以看看： https://www.cnblogs.com/dingwpmz/p/12104702.html


调整后的broker配置：
brokerClusterName = RaftCluster
brokerName=39.3-broker0
listenPort=30911
namesrvAddr=10.254.39.1:9876;10.254.39.2:9876;10.254.39.3:9876
storePathRootDir=/data/rocketmq/rocketmq-4.9.2/sh/dledger/store/node00
storePathCommitLog=/data/rocketmq/rocketmq-4.9.2/sh/dledger/store/node00/commitlog
enableDLegerCommitLog=true
dLegerGroup=group-10.254.39.3
dLegerPeers=n30-10.254.39.3:40911;n31-10.254.39.3:40912;n32-10.254.39.3:40913
## must be unique
dLegerSelfId=n30
sendMessageThreadPoolNums=16

brokerIP1=10.254.39.3

deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

#发送消息线程等待时间，默认200ms
waitTimeMillsInSendQueue=60000

#发送队列线程容量 
sendThreadPoolQueueCapacity=100000

#发送消息的最大线程数，默认1
#sendMessageThreadPoolNums=16
#使用可重入锁
#useReentrantLockWhenPutMessage=true

#开启临时存储池
transientStorePoolEnable=true
#开启Slave读权限（分担master 压力）
slaveReadEnable=true
#关闭堆内存数据传输
#transferMsgByHeap=false
#开启文件预热
#warmMapedFileEnable=true


出现以下报错信息：
[PCBUSY_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 967ms, size of queue: 19
[REJECTREQUEST]system busy, start flow control for a while
