### ISSUE TITLE
dledger cluster

### ISSUE THREAD

**Issue by Mark110513** [apache/rocketmq#3952]
在4台机子上搭建了一个dledger集群，RaftNode02、RaftNode03、RaftNode05、RaftNode06，每个broker组是1主2从，共12个broker
接口压测结果集群的吞吐量只有3000+，仅留一个broker组吞吐量也是3000+，集群的吞吐量为啥上不去？

【broker】配置
【broker-n0.conf】
brokerClusterName = RaftCluster
brokerName=RaftNode03
listenPort=30911
namesrvAddr=10.254.39.1:9876;10.254.39.2:9876;10.254.39.3:9876
storePathRootDir=/data/rocketmq-4.9.2/dledger/store/node00
storePathCommitLog=/data/rocketmq-4.9.2/dledger/store/node00/commitlog
enableDLegerCommitLog=true

dLegerGroup=RaftNode03
dLegerPeers=n0-127.0.0.1:40911;n1-127.0.0.1:40912;n2-127.0.0.1:40913
dLegerSelfId=n0

sendMessageThreadPoolNums=16

brokerIP1=10.254.39.3

deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

#发送消息线程等待时间，默认200ms
waitTimeMillsInSendQueue=60000

#开启Slave读权限（分担master 压力）
slaveReadEnable=true

#发送队列线程容量 
sendThreadPoolQueueCapacity=100000

【broker-n1.conf】
...
storePathRootDir=/data/rocketmq-4.9.2/dledger/store/node01
storePathCommitLog=/data/rocketmq-4.9.2/dledger/store/node01/commitlog
dLegerSelfId=n1
...

【broker-n2.conf】
...
storePathRootDir=/data/rocketmq-4.9.2/dledger/store/node02
storePathCommitLog=/data/rocketmq-4.9.2/dledger/store/node02/commitlog
dLegerSelfId=n2
...

**Comment by chenzlalvin** [comment]
You can provide the cluster information screenshots of pressure test and the Broker statistics log.

**Comment by Mark110513** [comment]
![image](https://user-images.githubusercontent.com/98000952/157573512-afe45f42-6025-4f4c-ad1e-43f92f58e765.png)

[stats.log](https://github.com/apache/rocketmq/files/8219665/stats.log)

**Comment by Mark110513** [comment]
![image](https://user-images.githubusercontent.com/98000952/157579067-4e1bf4ec-be4f-4cad-9427-0609c4e878a8.png)
![image](https://user-images.githubusercontent.com/98000952/157579404-74069a40-89b1-411a-bf86-0e83743425a4.png)
[stats (39.2).log](https://github.com/apache/rocketmq/files/8219906/stats.39.2.log)
[stats (39.3).log](https://github.com/apache/rocketmq/files/8219907/stats.39.3.log)
[stats (39.5).log](https://github.com/apache/rocketmq/files/8219908/stats.39.5.log)
[Uploading stats (39.6).log…]()

**Comment by HScarb** [comment]
Try to use rocketmq benchmark to test your TPS.
