### ISSUE TITLE
Fix Spelling mistakes -- 4.9.X版本

### ISSUE THREAD

**Issue by allen1916** [apache/rocketmq#3960]
下列是阅读源码时发现的一些拼写错误，建议修正。
（1）org.apache.rocketmq.client.impl.consumer.ConsumeMessageService：
submitConsumeRequest方法中，dispathToConsume --》dispatchToConsume

（2）org.apache.rocketmq.client.impl.consumer.ConsumeMessageOrderlyService：
submitConsumeRequest方法中，dispathToConsume --》dispatchToConsume

（3）org.apache.rocketmq.client.impl.consumer.ProcessQueue：
makeMessageToConsumeAgain方法中，makeMessageToCosumeAgain --》makeMessageToConsumeAgain
fillProcessQueueInfo方法中，setDroped --》setDropped

（4）org.apache.rocketmq.client.impl.factory.MQClientInstance：
sendHeartbeatToAllBroker方法中，this.mQClientAPIImpl.sendHearbeat --》this.mQClientAPIImpl.sendHeartbeat

（5）org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl：
checkTransactionState方法中，LocalTransactionState.UNKNOW --》LocalTransactionState.UNKNOWN
processTransactionState方法中，case UNKNOW --》case UNKNOWN
sendMessageInTransaction方法中，LocalTransactionState.UNKNOW --》LocalTransactionState.UNKNOWN
endTransaction方法中，case UNKNOW --》case UNKNOWN

（6）org.apache.rocketmq.client.impl.MQAdminImpl：
fetchPublishMessageQueues方法中，Unknow why --》Unknown why
fetchSubscribeMessageQueues方法中，Unknow why --》Unknown why

（7）org.apache.rocketmq.client.impl.MQClientAPIImpl：
sendMessageAsync方法中，unknow reseaon --》unknown reason
sendHearbeat方法中 --》sendHeartbeat方法

（8）org.apache.rocketmq.client.producer.LocalTransactionState：
LocalTransactionState枚举中，UNKNOW --》UNKNOWN

（9）org.apache.rocketmq.common.protocol.body.ConsumerRunningInfo：
analyzeProcessQueue方法中，pq.isDroped() --》pq.isDropped()

（10）org.apache.rocketmq.common.protocol.body.ProcessQueueInfo：
private boolean droped; --》private boolean dropped;
isDroped() --》isDropped()
setDroped(boolean droped) --》setDropped(boolean dropped)

（11）org.apache.rocketmq.common.protocol.ResponseCode：
TRANSACTION_STATE_UNKNOW --》TRANSACTION_STATE_UNKNOWN

（12）org.apache.rocketmq.remoting.netty.FileRegionEncoder：
encode方法中，msg.transfered() --》msg.transferred()

（13）org.apache.rocketmq.store.ConsumeQueue：
truncateDirtyLogicFiles方法中，参数phyOffet --》phyOffset

（14）org.apache.rocketmq.example.transaction.TransactionListenerImpl：
executeLocalTransaction方法中，LocalTransactionState.UNKNOW --》LocalTransactionState.UNKNOWN
checkLocalTransaction方法中，LocalTransactionState.UNKNOW --》LocalTransactionState.UNKNOWN

**Comment by panzhi33** [comment]
would you like to submit a PR to polish it ?

**Comment by duhenglucky** [comment]
@allen1916 maybe more PRs are needed to polish these typos, because some of these PRs may bring compatibility issues, I will close this big issue first and please feel free to create a separate issue for each PR.
