### ISSUE TITLE
.Net RocketMQ.Client is a port of java version with 1:1 its functionality

### ISSUE THREAD

**Issue by leeveel** [apache/rocketmq#3961]
.Net RocketMQ.Client is a port of java version with 1:1 its functionality
[https://github.com/leeveel/RocketMQ.Client](https://github.com/leeveel/RocketMQ.Client)

功能对齐版本：version 4.9.3
进度（90%）： 
第一阶段：翻译工作 -- 已完成！ 
第二阶段：查漏补缺和调试 -- 进行中.......

寻求志同道合的朋友来完善它。

**Comment by aaron-ai** [comment]
Great work! Happy to see more users from community get involved in polyglot client development.

At the same time, we are planning to implement a brand new C# client based on gRPC, more details will be revealed recently, welcome to stay tuned.

**Comment by slqd3781** [comment]
期待
