### ISSUE TITLE
Use wrong offset when deliver in ScheduleService

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq#3966]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

Send 32 delay messages with delay level = 4 and wait to deliver them to the real queue

- What is expected to see?

The offset of delay level = 4 should be 32

- What did you see instead?

The offset of delay level = 4 less than  32

2. Please tell us about your environment:

Mac OS

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by HScarb** [comment]
I find the reason.
In async deliver mode, update offsetTable with wrong offset.

![image](https://user-images.githubusercontent.com/10664298/158060708-1750d8d6-a48f-4e6e-ae06-f1df196e3004.png)
![image](https://user-images.githubusercontent.com/10664298/158060717-74765594-9da0-4ff4-9d44-d032a609bd89.png)

![image](https://user-images.githubusercontent.com/10664298/158061324-7c25b632-59b1-4a08-b732-9ccd8bd34ae0.png)
![image](https://user-images.githubusercontent.com/10664298/158061382-1cd8858e-913f-4506-8a5f-6525a1a4aafc.png)
