### ISSUE TITLE
[Performance] RemotingCommand decodeCommandCustomHeader optimize

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/rocketmq#3968]
with the patch. the jmh test can be improved 1.2x faster.

origin:
Benchmark                                       Mode  Cnt     Score      Error   Units
RemotingCommandJMHTest.testDecodeCustomHeader  thrpt    6  6147.080 ± 1126.856  ops/ms

after:
Benchmark                                       Mode  Cnt      Score      Error   Units
RemotingCommandJMHTest.testDecodeCustomHeader  thrpt    6  14516.081 ± 2859.019  ops/ms

**Comment by WJL3333** [comment]
@RongtongJin @areyouok @odbozhou hope this optimization works as test. can you take a look?
