### ISSUE TITLE
same brokerName in diffrent cluster

### ISSUE THREAD

**Issue by Jacob-Jay** [apache/rocketmq#3991]
https://github.com/apache/rocketmq/blob/c1aeca291ea686a2b7f01ffec30132f5a370a2ab/namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java#L58

when there are same Name  broker  in diffrent cluster,the pre broker in other cluster will be overwrite

**Comment by panzhi33** [comment]
would you like to submit a PR to polish it ?

**Comment by ni-ze** [comment]
If the two clusters are not related, use different namesrv is better. Otherwise, a different broker name is recommended.

**Comment by Jacob-Jay** [comment]
> If the two clusters are not related, use different namesrv is better. Otherwise, a different broker name is recommended.

yes,it's correct to use different namesrv or different  broker name ,but the code make me or others  confused.

**Comment by odbozhou** [comment]
In what usage scenarios does this problem occur?
