### ISSUE TITLE
Some code optimizations about BrokerContainerStartup 

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq#3992]
**BUG REPORT**

1. Please describe the issue you observed:

- Some optimizations about `BrokerContainerStartup.class`

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
- replace `"c"` with static field `BROKER_CONTAINER_CONFIG_OPTION`, others too.
- rename `brokerConfig` to `containerConfig`
- remove boolean param of  createBrokerContainer which is useless.

**Comment by RongtongJin** [comment]
Merged
