### ISSUE TITLE
Move CI/CD to GitHub Actions.

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#3998]
GitHub Actions may be a better CI/CD tools, which gets good practice in [rocketmq-client-cpp](https://github.com/apache/rocketmq-client-cpp/tree/main), and it is simpler for java.

**Comment by duhenglucky** [comment]
@aaron-ai Very good suggestion, there is a RIP that will be discussed on the mailing list recently, including E2E testing, daily builds, etc. Welcome to participate

**Comment by vongosling** [comment]
Good to see we could embrace new CI/CD architecture. As heng said, we could discuss its possibility and make a detailed transfer plan. You know, We've done a lot of work to adapt to the original architecture, and we hope that future upgrades will be smooth and always housekept by our committers.
