### ISSUE TITLE
Fix the warn log  input in command tools

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#4000]
![image](https://user-images.githubusercontent.com/18254437/158929025-0ec5456c-076d-42b5-b72d-e5f94b24c70e.png)

**Comment by ni-ze** [comment]
Can you provider a screenshot to illustrate result?

**Comment by zhangjidi2016** [comment]
> Can you provider a screenshot to illustrate result?

![image](https://user-images.githubusercontent.com/18254437/159109831-42748df8-1a3e-4331-b0ef-c4b6691c4713.png)
