### ISSUE TITLE
Index file space wasted

### ISSUE THREAD

**Issue by xingxingbei** [apache/rocketmq#4011]
Location：org.apache.rocketmq.store.index.IndexFile#putKey
code:
 int absIndexPos =
                    IndexHeader.INDEX_HEADER_SIZE + this.hashSlotNum * hashSlotSize
                        + this.indexHeader.getIndexCount() * indexSize;
where [this.indexHeader.getIndexCount() ] is initialized to 1
Are the first 20 bytes unused, or am I understanding this wrong?

**Comment by panzhi33** [comment]
yes,the first 20 bytes unused.you can look at the code here, there is an invalidIndex, so it starts from 1
![image](https://user-images.githubusercontent.com/29321745/159417232-fd75c284-f07f-48d5-a495-75e694dbb6fd.png)

**Comment by xingxingbei** [comment]
Thanks Reply. 0 is used as the initial value in the slot, so data is stored from 1.
