### ISSUE TITLE
Because there is no print exception, I can not see the detailed error message

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#4018]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

In `org.apache.rocketmq.broker.processor.AdminBrokerProcessor#resumeCheckHalfMessage 
catch (Exception e) {
            log.error("Exception was thrown when putting message back to RMQ_SYS_TRANS_HALF_TOPIC.");
            response.setCode(ResponseCode.SYSTEM_ERROR);
            response.setRemark("Exception was thrown when putting message back to RMQ_SYS_TRANS_HALF_TOPIC.");`

Because there is no print exception, I can not see the detailed error message
- What is expected to see?
print exception

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by panzhi33** [comment]
would you like to submit a PR to polish it ?

**Comment by Oliverwqcwrw** [comment]
yes

**Comment by Oliverwqcwrw** [comment]
I have submitted the PR #4022
