### ISSUE TITLE
where is C++ and Golang client sdk ?

### ISSUE THREAD

**Issue by carr123** [apache/rocketmq#402]
i learned that  rocketmq support java c++ golang client. 
so, where can i get  the C++ and Golang client sdk ?

**Comment by duhengforever** [comment]
@lizhanhui

**Comment by Liberxue** [comment]
![image](https://user-images.githubusercontent.com/5831248/44445304-0697c800-a613-11e8-869f-4588cc288cb3.png)

see https://github.com/apache/rocketmq-externals
