### ISSUE TITLE
acl not work after changed

### ISSUE THREAD

**Issue by francisoliverlee** [apache/rocketmq#4025]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

### 1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
  - build from 4.9.3 source codes
  - enable acl and deploy with 1 namesrv, 1 broker ( use default acl files)
  - produce message with ak=RocketMQ, sk=12345678 , send messages to topic `topicB`
  - send ok
  - update ACL for `topicB` using `./mqadmin updateAclConfig -c rocketmq-cluster-1 -a RocketMQ -s 12345678 -t 'topicB=DENY' -n 127.0.0.1:9876`
  - produce message again, send fail. we expect this.
  - update ACL for `topicB` using `./mqadmin updateAclConfig -c rocketmq-cluster-1 -a RocketMQ -s 12345678 -t 'topicB=PUB|SUB' -n 127.0.0.1:9876`, error would come out
  > RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.InternalThreadLocalMap).
  > RocketMQLog:WARN Please initialize the logger system properly.
  > org.apache.rocketmq.tools.command.SubCommandException: UpdateAccessConfigSubCommand command failed
  > at org.apache.rocketmq.tools.command.acl.UpdateAccessConfigSubCommand.execute(UpdateAccessConfigSubCommand.java:180)
  > at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:146)
  > at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:97)
  > Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: java.lang.NullPointerException, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:648)
  > For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
  > at org.apache.rocketmq.client.impl.MQClientAPIImpl.createPlainAccessConfig(MQClientAPIImpl.java:328)
  > at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.createAndUpdatePlainAccessConfig(DefaultMQAdminExtImpl.java:205)
  > at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.createAndUpdatePlainAccessConfig(DefaultMQAdminExt.java:175)
  > at org.apache.rocketmq.tools.command.acl.UpdateAccessConfigSubCommand.execute(UpdateAccessConfigSubCommand.java:170)
  > ... 2 more
### What is expected to see?
acl changed success

### What did you see instead?
exception comes

### Please tell us about your environment:
RocketMQ 4.9.3
mac os M1

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

5. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by yuz10** [comment]
is it the same as https://github.com/apache/rocketmq/issues/3887 ?

**Comment by duhenglucky** [comment]
@francisoliverlee Would you like to do a test with the develop branch？
