### ISSUE TITLE
Cluster mode offset issue

### ISSUE THREAD

**Issue by xu-weize** [apache/rocketmq#4039]
The RocketMQ version I am using is 4.5.0, and I am asking about progress in a consumer cluster mode:

1. When the consumer synchronizes the offset to the Broker, it randomly selects a Broker (Master or Slave);
  code:
  FindBrokerResult findBrokerResult = this.mQClientFactory.findBrokerAddressInAdmin(mq.getBrokerName()); (MQClientInstance#findBrokerAddressInAdmin);

3. When the consumer starts, it will perform dynamic heavy load to the Broker side to pull and cancel the offset of the consumption point, which is also a randomly selected Broker. So the question is: how to ensure that the pulled offset is the latest consumer synchronized to the Broker? If the pulled Broker offset is 0, doesn't it have to be re-consumed every time?

**Comment by ni-ze** [comment]
The latest code, in branch develop, submit offset to master broker only.

**Comment by HScarb** [comment]
See #3605
