### ISSUE TITLE
请问MessagingAccessPointFactory在哪个jar包里引入的

### ISSUE THREAD

**Issue by duguyue** [apache/rocketmq#404]
final MessagingAccessPoint messagingAccessPoint = MessagingAccessPointFactory.getMessagingAccessPoint("openmessaging:rocketmq://IP1:9876,IP2:9876/namespace");

**Comment by Hellojungle** [comment]
@duguyue Issue only used for bug report and new feature request, please subscribe our mailing list, and there are so many members will help you.
