### ISSUE TITLE
Make storePathCommitLog base on storePathRootDir

### ISSUE THREAD

**Issue by HScarb** [apache/rocketmq#4048]
Currently `storePathCommitLog` and `storePathRootDir` are separately defined.

https://github.com/apache/rocketmq/blob/develop/store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java#L28-L35

If I only set `storePathRootDir`, the `storePathCommitLog` will not change, so I must set it explicitly.

It's better to make `storePathCommitLog` base on `storePathRootDir`

**Comment by Git-Yang** [comment]
Merged
