### ISSUE TITLE
Master power off may cause consumeQueue diff from commitLog

### ISSUE THREAD

**Issue by yufeng629** [apache/rocketmq#405]
if there are some messages, all of then had flushed to commit log, but no dispatch to consumeQueue, at that moment ,the Master Broker power off, when the Master restart, those message will never dispatch to consumeQueue, because the reputFromOffset property of the ReputMessageService was set to the maxOffset of the last MappedFile when the DefaultMessageStore start
![image](https://user-images.githubusercontent.com/15260012/44012251-5339716a-9ef0-11e8-8843-b1c123f6507a.png)
if this sitution is true, it will cause message lost

**Comment by yufeng629** [comment]
之前提问时描述可能描述的不够好，在这里再补充下：在RocketMQ4.3.0中，消息保存到commitLog之后，并不是马上就同步数据到对应的index和comsumeQueue，而是通过另外一个服务线程ReputMessageService定时的从CommotLog同步数据到comsumeQueue，假设生产者使用同步写的方式发送了100条消息到commitLog,当ReputMessageService同步到第60条消息的时候Broker突然断电了，一段时间之后，Broker又重启了，那剩下的未同步的40条消息是否还会继续同步到comsumeQueue？？我看了源码好像并未发现有这个机制

**Comment by ymwneu** [comment]
那剩下的未同步的40条消息会继续同步到consumeQueue。
如果是断电恢复，启动broker时会调用CommitLog#recoverAbnormally，里面会通过this.defaultMessageStore.doDispatch(dispatchRequest);往comsumeQueue补数据。
