### ISSUE TITLE
NullPointerException if broker master is down when tracking message detail

### ISSUE THREAD

**Issue by shudo1219** [apache/rocketmq#406]
When tracking message detail on our monitor platform, we meet a problem:
it will throw a NullPointerException if broker master is down.
We trace  into the code and find the problem:
tools/admin/DefaultMQAdminExtImpl.java
line 844  String addr = brokerData.getBrokerAddrs().get(MixAll.MASTER_ID);
line 845  if (**addr**.equals(RemotingUtil.socketAddress2String(msg.getStoreHost()))) {
                   if (next.getValue().getConsumerOffset() > msg.getQueueOffset()) {
                       return true;
                   }
               }
If broker master is down, addr will be null and hence throw the exception mentioned above.
Broker slave also has the consume offset, we might need to ask salve for offset or return false if only slave is alive.

**Comment by Hellojungle** [comment]
Thanks for your suggestion, and maybe you can make a pull request to help solve this issue.
