### ISSUE TITLE
ACL is extremely uncomfortable to use

### ISSUE THREAD

**Issue by 2775468731** [apache/rocketmq#4064]
ACL is extremely uncomfortable to use

Can it be optimized? A very good product. Why is authentication so poor

**Comment by duhenglucky** [comment]
@2775468731 very good suggestions, can you describe a few issues you encountered or features you would like to add?can you add my WeChat: rocketmq666? Or you can directly describe it in Chinese. The enhancement of ACL features is the next focus of the community. 也可以用中文描述下，ACL 的优化，易用性提升是接下来社区的重点
