### ISSUE TITLE
mqadmin delete group success，prometheus can still see the data of groups that have been deleted

### ISSUE THREAD

**Issue by hmthoo** [apache/rocketmq#4069]
promsql 
```
label_replace(sum(rocketmq_producer_offset by (topic) - on(topic) group_right sum(rocketmq_consumer_offset by (topic,group) > 100, "consumer", "$1", "group", "(.*)")
```

![image](https://user-images.githubusercontent.com/42607426/160788150-7f4d4433-0b46-4239-9c86-71bfd30e2f41.png)
![image](https://user-images.githubusercontent.com/42607426/160788235-ed3cb2bd-b78b-478f-a607-ea5a623199f9.png)
<img width="953" alt="image" src="https://user-images.githubusercontent.com/42607426/160788652-0ee40690-10a8-4332-943b-d126d7cc4cc7.png">

**Comment by lizhiboo** [comment]
@hmthoo Is prometheus statistics history data?
