### ISSUE TITLE
Make the init-method of `AsyncTraceDispatcher.traceProducer` more readable

### ISSUE THREAD

**Issue by dugenkui03** [apache/rocketmq#4087]
```java
    private DefaultMQProducer getAndCreateTraceProducer(RPCHook rpcHook) {
        DefaultMQProducer traceProducerInstance = this.traceProducer;
        if (traceProducerInstance == null) {
            traceProducerInstance = new DefaultMQProducer(rpcHook);
            // _INNER_TRACE_PRODUCER-${group}-${type}-${counter}
            traceProducerInstance.setProducerGroup(genGroupNameForTrace());
            traceProducerInstance.setSendMsgTimeout(5000);
            traceProducerInstance.setVipChannelEnabled(false);
            // The max size of message is 128K
            traceProducerInstance.setMaxMessageSize(maxMsgSize - 10 * 1000);
        }
        return traceProducerInstance;
    }
```

Now, `#getAndCreateTraceProducer` is only invoked by constroctor for initializing `traceProducer`.

Even though `#getAndCreateTraceProducer` is invoked elsewhere, `traceProducer` is already initialized when `AsyncTraceDispatcher` instance is cteated, `#getAndCreateTraceProducer` just return the created traceProducer and `#getTraceProducer` is more clearly.

**Comment by tsunghanjacktsai** [comment]
Hi,

I'm a bit confused about why you closed this PR then, it's a reasonable change and I thus reopen another PR to improve it. Thx for your previous work :-)

**Comment by dugenkui03** [comment]
> Hi @dugenkui03,
> 
> I'm a bit confused about why you closed this PR then, it's a reasonable change and I thus reopen another PR to improve it. Thx for your previous work :-)

@tsunghanjacktsai Thanks for finishing this work.

I deleted fork by mistake, and lots of pr were closed automatically.
