### ISSUE TITLE
发送消息时经常报超时

### ISSUE THREAD

**Issue by chenld** [apache/rocketmq#409]
```
822392] WARN  RocketmqClient - sendKernelImpl exception, resend at once, InvokeID: 3069993624175247149, RT: 3000ms, Broker: MessageQueue [topic=****_BUSINESS, brokerName=broker-b, queueId=4]
org.apache.rocketmq.remoting.exception.RemotingTimeoutException: wait response on the channel <10.*.*.*:10909> timeout, 3000(ms)
 at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:386)
 at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:369)
```
配置是双主双从,  从报异常来看是发送成功了,  但没收到应答,  现在经常报超时,  发送到应答等待时间超过1s的很多, 请问下如果排查这个问题,  怎么入手,  要看服务端那些日志?

**Comment by duhengforever** [comment]
@chenld please check the broker.log to make sure the server side have been received this request, and check store.log to check whether error logs appeared.
And issue only used for bug report and new feature request, please subscribe our mailing list, and there are so many member will help you.

**Comment by Ah39** [comment]
grep notify in store.log , this may cause by the lock , or mmap . The new version dont have the lock ,but have the CAS with one thread.  May because of  only have 1 thread ,the thread is busy .
