### ISSUE TITLE
Thread safe of `ServiceState`

### ISSUE THREAD

**Issue by dugenkui03** [apache/rocketmq#4096]
**BUG REPORT**

- There is a  `#getServiceState()` method existed in `DefaultMQPullConsumerImpl`, as well as`DefaultMQPushConsumerImpl`, application will get a wrong state by `#getServiceState()` if another thread haven't finish the `#start()` but already set state to `ServiceState.START_FAILED`;
- Make the read and write of `serviceState` much safer  both in `DefaultMQProducerImpl` and `DefaultMQAdminExtImpl`.

**Comment by lwclover** [comment]
这个我们之前在生产遇到过。哈哈，看这个[pr](https://github.com/apache/rocketmq/issues/3066)

**Comment by dugenkui03** [comment]
> pr#3066

@lwclover 谢谢Thanks♪(･,･)ﾉ老铁，我看看。
