### ISSUE TITLE
docker image question

### ISSUE THREAD

**Issue by liruhui** [apache/rocketmq#4116]
Rockermq doesn't have docker image?

**Comment by MatrixHB** [comment]
You can pull this image
https://hub.docker.com/repository/docker/apache/rocketmq

If you have any experience about rocketmq cluster startup mode with docker and k8s operator, welcome to share with us in this issue.
https://github.com/apache/rocketmq/issues/3549

**Comment by xialinlin** [comment]
Get a docker installation tutorial
