### ISSUE TITLE
send batch message

### ISSUE THREAD

**Issue by fengxueyun** [apache/rocketmq#4149]
send batch orderLyMessage

**Comment by fengxueyun** [comment]
I want to send messages in batches, and implement queue segmentation according to a certain attribute, so as to realize the implementation order of the same value of the attribute, that is, the sequential consumption when consuming

**Comment by panzhi33** [comment]
org.apache.rocketmq.client.producer.DefaultMQProducer#send(java.util.Collection<org.apache.rocketmq.common.message.Message>, org.apache.rocketmq.common.message.MessageQueue)
See if this method meets your needs

**Comment by lwclover** [comment]
You can use the solution @panzhi33 mentioned. In the batch, You can not have delay messages.

In addition, if you want to guarantee absolute order when consuming, you need to implement MessageListenerOrderly,

There is a risk use MessageListenerOrderly that if one message is not consumed, it will block the consumption of subsequent messages.
