### ISSUE TITLE
No further information for "execute the pull request exception"

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#4158]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
when shutdown a consumer, see the exeption below:
![image](https://user-images.githubusercontent.com/14816818/162975427-305a1d50-289c-4f48-a6a1-aa3104ec6461.png)

- What is expected to see?
show fail reason in exception

- What did you see instead?
no further information in exception

3. Please tell us about your environment:

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

5. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by lwclover** [comment]
Lack of 'caused by'  exception fragments, can you paste it?

**Comment by lwclover** [comment]
Because the exception information is not complete.
I think it's possible that the application is closing when it sends the pull request so it closes the channel, and then sends the pull request using the closed channel
