### ISSUE TITLE
Is  FlushConsumeQueueService necessary？

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#4159]
version 4.9.1

From the ReputMessageService code, we can finally locate the following code。 “this.fileChannel.write(ByteBuffer.wrap(data));” is already possible to write data to disk, why do we need FlushConsumeQueueService?
————————————————————————————————————————————
public boolean appendMessage(final byte[] data) {
    int currentPos = this.wrotePosition.get();

    if ((currentPos + data.length) <= this.fileSize) {
        try {
            this.fileChannel.position(currentPos);
            this.fileChannel.write(ByteBuffer.wrap(data));
        } catch (Throwable e) {
            log.error("Error occurred when append message to mappedFile.", e);
        }
        this.wrotePosition.addAndGet(data.length);
        return true;
    }

    return false;
}
——————————————————————————————————————

**Comment by panzhi33** [comment]
fileChannel.write does not directly write ByteBuffer data to disk

**Comment by iamqq23ue** [comment]
yes，I know that data is written to the system cache first, but eventually it is written to disk.And FlushConsumeQueueService is also executed asynchronously。
If it's to ensure data is written to disk, why not use filechannel.force.&nbsp;


Or write to mappedbytebuffer like commitlog.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月13日(星期三) 中午1:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Is  FlushConsumeQueueService necessary？ (Issue #4159)





 
fileChannel.write does not directly write ByteBuffer data to disk

**Comment by panzhi33** [comment]
Every time the data is written, it will be forced, and the disk io pressure will be relatively large, so it needs to be changed to this asynchronous。
and 5.0 has been modified to mappedbytebuffer

**Comment by lizhimins** [comment]
对于索引来说每次写入的数据量小但是更新频繁，用 mmap 确实会更好，还有 commitlog 应该用 filechannel。

**Comment by lizhimins** [comment]
个人认为这里主要是避免 os 积累太多的脏页导致 io 抖动
