### ISSUE TITLE
who to save msg offset on k8s

### ISSUE THREAD

**Issue by xunianchong** [apache/rocketmq#4160]
application deply on k8s , now i redeploy the application, alway receive the history msg.  Consumer send msg by MessageModel of CLUSTERING ,   how do I save  the msg offset ? how can  i set the InstanceName? tank you

**Comment by lwclover** [comment]
> deply

You need to use a fixed consumerGroup name.

**Comment by xunianchong** [comment]
DefaultMQPushConsumer consumer =
                new DefaultMQPushConsumer("BB");
        consumer.setInstanceName("AA");

We need to use a fixed  InstanceName or  a fixed consumerGroup name?  consumerGroup is fixed?

**Comment by lwclover** [comment]
> DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("BB"); consumer.setInstanceName("AA");
> 
> We need to use a fixed InstanceName or a fixed consumerGroup name? consumerGroup is fixed?
DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("BB");
Yes, the consumerGroup 'BB' need a Fixed name.

**Comment by lwclover** [comment]
> DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("BB"); consumer.setInstanceName("AA");
> 
> We need to use a fixed InstanceName or a fixed consumerGroup name? consumerGroup is fixed?

Yes, the consumerGroup 'BB' need a Fixed name.

**Comment by lwclover** [comment]
InstanceName is optional unless multiple consumers are started within a process

**Comment by pingww** [comment]
Observe the offset submission record in the RMQ client log
