### ISSUE TITLE
Illegal reflective access by org.apache.rocketmq.store.MappedFile$1 rocketmq-store-4.9.3.jar

### ISSUE THREAD

**Issue by tigerxie** [apache/rocketmq#4161]
sh bin/mqbroker -n localhost:9876
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.rocketmq.store.MappedFile$1 (file:/Users/xiexiaohu/github/mq/rocketmq-4.9.3/lib/rocketmq-store-4.9.3.jar) to method java.nio.DirectByteBuffer.attachment()
WARNING: Please consider reporting this to the maintainers of org.apache.rocketmq.store.MappedFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by HScarb** [comment]
Can you provide more logs such as
broker.log
store.log

**Comment by ni-ze** [comment]
I check on branch release-4.9.3 source code. There is no problem.
```xml
1. mvn -Prelease-all -DskipTests clean install -U
2. cd ~/distribution/target/rocketmq-4.9.4-SNAPSHOT/rocketmq-4.9.4-SNAPSHOT
3. sh  bin/mqnamesrv
4.  sh bin/mqbroker -n localhost:9876
5. send message and success.
```

**Comment by MatrixHB** [comment]
What's your JDK version？ You can use jdk 1.8 and try again.

**Comment by zuochongchong** [comment]
This problem occurs when using JDK11 , Use JDK1.8 to solve the problem.
