### ISSUE TITLE
the note in DefaultMQProducerImpl confused

### ISSUE THREAD

**Issue by yang2yang** [apache/rocketmq#4162]
I see the note in DefaultMQProducerImpl.java may not exactly。bacause the version is larger than 4.4.0，but it is not removed。it may be confused。
![image](https://user-images.githubusercontent.com/11631097/163341030-7271e319-2304-410e-9f2a-a9fe7d4b660d.png)

**Comment by lwclover** [comment]
> I see the note in DefaultMQProducerImpl.java may not exactly。bacause the version is larger than 4.4.0，but it is not removed。it may be confused。 ![image](https://user-images.githubusercontent.com/11631097/163341030-7271e319-2304-410e-9f2a-a9fe7d4b660d.png)

I think the method really needs to be optimized, and I am considering doing it.

**Comment by lwclover** [comment]
The thread pool serves as a buffer, and I don't think the timeout should be calculated for the phase sent to the thread pool
