### ISSUE TITLE
About the ScheduleMessageService#messageTimeup method

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#4164]
In the `ScheduleMessageService#messageTimeup` method, when converting a delayed message into a normal message, can `REAL_TOPIC` and `REAL_QID` be removed without saving them in `msgInner` ?
![image](https://user-images.githubusercontent.com/43363120/163390071-5e7e9fd2-2b49-4864-8334-7e78d3dc0bbb.png)

**Comment by HScarb** [comment]
IMO it's ok to remove these properties.
Instead of removing them after setting into msgInner, it is better to not set them into msgInner from line 315.

**Comment by BurningCN** [comment]
> IMO it's ok to remove these properties. Instead of removing them after setting into msgInner, it is better to not set them into msgInner from line 315.

OK, thanks

**Comment by BurningCN** [comment]
The additional properties are useful for debugging.
