### ISSUE TITLE
Question about MappedFileQueue#deleteExpiredFileByOffset method

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#4174]
Considering that `MappedFile` is not necessarily full, should it be replaced with `mappedFile.getWrotePosition()-unitSize`?
![image](https://user-images.githubusercontent.com/43363120/163550501-77d00d38-1278-497b-82f7-395460438dec.png)

**Comment by HScarb** [comment]
The last file is not full and in write state, other files in front of last file are already full.
So for these files, wrotePosition equals mappedFileSize
