### ISSUE TITLE
Is there a limit to the number of tags?

### ISSUE THREAD

**Issue by itlidaye** [apache/rocketmq#4177]
Is there a limit to the number of tags?

Will the same topic 1000/10000 tags affect performance?

**Comment by hill007299** [comment]
Depending on your consumption patterns, whether there will be a lot different tag subscription ?

**Comment by pingww** [comment]
A large number of different tags is not recommended. A large number of different tags can mean a large number of different subscribers. A larger number of subscribers can have an impact on broker performance.

**Comment by lwclover** [comment]
> A large number of different tags is not recommended. A large number of different tags can mean a large number of different subscribers. A larger number of subscribers can have an impact on broker performance.

I've done this in a production environment before and it does have an impact on performance.

**Comment by wojiushimogui** [comment]
> > A large number of different tags is not recommended. A large number of different tags can mean a large number of different subscribers. A larger number of subscribers can have an impact on broker performance.
> 
> I've done this in a production environment before and it does have an impact on performance.

all is pull consumption, topic has many tags, consumers only pay attention to a small number of tags,  why is there a performance impact? Can you tell me the specific reason?
In my opinion, the message is matched directly on the server side according to the hashCode, and then directly matched on the consumer side according to the plaintext of the tag, which has nothing to do with the number of tags.
