### ISSUE TITLE
Prevent int overflow in `TraceContext`

### ISSUE THREAD

**Issue by dugenkui03** [apache/rocketmq#4181]
#### MINOR IMPORVEMENT

Minor improvement to prevent int overflow in `TraceContext`.

#### Describe in Chinese

对 `TraceContext` 中`#compareTo(TraceContext)` 方法进行优化避免后续可能支持超长周期定时消息或者开发者魔改开发时触发 int 溢出问题。

https://mp.weixin.qq.com/s/JSjaF--EPRZHgI1037hJ-w 也提到了部分开发者会定制”任意时间，超长生命周期“的定时消息。

**Comment by RongtongJin** [comment]
Merged
