### ISSUE TITLE
When the reportSlaveMaxOffset method fails...

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#4183]
When `reportSlaveMaxOffset` fails, we should end the current loop immediately, no need to perform subsequent processes
![image](https://user-images.githubusercontent.com/43363120/164172100-45f79fc3-401d-41fa-b10e-efd2d734517c.png)

**Comment by ni-ze** [comment]
It is better to prove why previous version is wrong.

**Comment by RongtongJin** [comment]
Merged
