### ISSUE TITLE
Will message loss occur in the dledger cluster

### ISSUE THREAD

**Issue by LittleBoy18** [apache/rocketmq#4191]
所有从节点都没有和master节点同步完成，此时master节点宕机，选举出来的从节点应该会有消息丢失的情况吧？

**Comment by RongtongJin** [comment]
不会的，DLedger模式遵从raft协议，选出来从节点一定有committed的所有消息

**Comment by hzh0425** [comment]
Dledger cluster 是 raft 协议的, 选举出来的 leader 一定会包含所有 committed 的消息.
你说的情况可能出现在: Leader 刚 append 一些消息, 还没来得及同步到 followers, 就 shutdown 了. 
这种情况下, 这些没有被 committed 的消息, 即使丢失了也没有关系. 
因为这些没有 committed 的消息在 leader shutdown 之前不会被消费者消费到.
