### ISSUE TITLE
[ISSUE-2706] The official website shows that it has been solved, but it has not been modified.

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#4196]
Did something go wrong?

**Comment by hzh0425** [comment]
Can you provide the detailed context ?

**Comment by iamqq23ue** [comment]
> Can you provide the detailed context ?

https://github.com/apache/rocketmq/issues/2706。This issue still exists。

But on the official website, it shows that this issue has been resolved, is it a mistake? https://rocketmq.apache.org/release_notes/release-notes-4.9.3/

**Comment by ltamber** [comment]
> 

this issue once closed and reopen again,  I guess the issue status was closed when release RocketMQ 4.9.3.

**Comment by iamqq23ue** [comment]
Does the community have any plans to resolve this issue?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月24日(星期天) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] [ISSUE-2706] The official website shows that it has been solved, but it has not been modified. (Issue #4196)





   
this issue once closed and reopen again,  I guess the issue status was closed when release RocketMQ 4.9.3.

**Comment by iamqq23ue** [comment]
ISSUE-2706 This bug still exists. Not sure if the community has a plan to fix it
