### ISSUE TITLE
使用acl功能，关于版本的选择

### ISSUE THREAD

**Issue by lsw21** [apache/rocketmq#4199]
从这里了解到https://github.com/apache/rocketmq/issues/3922 同时自己也做了测试，
使用最新稳定版4.9.3的acl功能，每次编辑plain_acl.yml文件后需要重启broker，
这样的话，是否就不能使用该版本，或者有其他规避方法吗？

**Comment by duhenglucky** [comment]
@lsw21 https://github.com/apache/rocketmq/pull/3927 这个PR 针对这个问题进行了一些修复，帮忙一起再重新review一下，新版本即将发布，可以先用develop分支本地打包试下，欢迎反馈
