### ISSUE TITLE
 Is UNKNOW a spelling mistake?

### ISSUE THREAD

**Issue by samz406** [apache/rocketmq#4200]
**BUG REPORT**
this class enum 
`public enum LocalTransactionState {
    COMMIT_MESSAGE,
    ROLLBACK_MESSAGE,
    UNKNOW,
}
`
UNKNOW maybe spelling mistake，I think is UNKNOWN. If it is a spelling mistake. I can fix

**Comment by lwclover** [comment]
I think it's a spelling mistake.

**Comment by pingww** [comment]
I also think so , it's a mistake

**Comment by hzh0425** [comment]
Maybe you can create a pr to change it?

**Comment by samz406** [comment]
> Maybe you can create a pr to change it?

need committer confirm
