### ISSUE TITLE
Why message trace of consume type do not have storeHost attribute?

### ISSUE THREAD

**Issue by xhrg** [apache/rocketmq#4201]
https://github.com/apache/rocketmq/blob/develop/client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java

when  SubBefore  and  SubAfter，not append bean.getStoreHost()，why，thanks

**Comment by lizhiboo** [comment]
IMO, we do not concern message stored in which broker in the consume scenario.

**Comment by xhrg** [comment]
not append bean.getStoreHost() or getClientHost()

**Comment by xhrg** [comment]
@lizhiboo not append bean.getStoreHost() or getClientHost()

If there is no storeHost, there should have clientHost

**Comment by cserwen** [comment]
> 
This method is used in here.
https://github.com/apache/rocketmq/blob/2bd9059016448ebcb0bb1cf64ed944eba98bb38e/client/src/main/java/org/apache/rocketmq/client/trace/TraceView.java#L48

The storeHost and clientHost was set in here.
![image](https://user-images.githubusercontent.com/46882838/165009967-934b0d82-b41b-4866-81f4-58a1bbb01e26.png)
