### ISSUE TITLE
about TransientStorePool

### ISSUE THREAD

**Issue by HHoflittlefish777** [apache/rocketmq#4202]
In the class 'TransientStorePool',Rocketmq use native method mlock to lock memory,but when I clone Rocketmq and run in the Windows  10 environment,it report error message as follows:Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'mlock'.I guess there is no mlock method in msvcrt.dll,so I use tool to test it，there did not have mlock method！And others computer have no such method ,Is something error in my  msvcrt.dll or in the Rocketmq code?

**Comment by hzh0425** [comment]
可能该方法只在 linux 环境下支持?

**Comment by HHoflittlefish777** [comment]
如果只在在linux环境下支持，为什么LibC接口的第一行
LibC INSTANCE = (LibC) Native.loadLibrary(Platform.isWindows() ? "msvcrt" : "c", LibC.class);

**Comment by HScarb** [comment]
I tested this method, it worked on Linux and dit not work on Windows.
```java
LibC INSTANCE = (LibC) Native.loadLibrary(Platform.isWindows() ? "msvcrt" : "c", LibC.class);
```
This is a default JNA usage of C library for binding C functions to java interface, but `mlock` and `madvise` not exist on windows

**Comment by HHoflittlefish777** [comment]
I agree with you,but this line of code'LibC INSTANCE = (LibC) Native.loadLibrary(Platform.isWindows() ? "msvcrt" : "c", LibC.class);' means it can work in the windows.If it can cause divergence，I think hava  a change in rocketmq is a good idea.

**Comment by lwclover** [comment]
> java.lang.UnsatisfiedLinkError

`LibC INSTANCE = (LibC) Native.loadLibrary(Platform.isWindows() ? "msvcrt" : "c", LibC.class);`

My os is Windows 10. The line can be executed normally.

**Comment by lwclover** [comment]
> I agree with you,but this line of code'LibC INSTANCE = (LibC) Native.loadLibrary(Platform.isWindows() ? "msvcrt" : "c", LibC.class);' means it can work in the windows.If it can cause divergence，I think hava a change in rocketmq is a good idea.

`LibC INSTANCE = (LibC) Native.loadLibrary(Platform.isWindows() ? "msvcrt" : "c", LibC.class);`

My os is Windows 10. The line can be executed normally.

**Comment by HHoflittlefish777** [comment]
It's strange,I can't run it in my window ,also my friend,and the contributor name HScarb replied me "I tested this method, it worked on Linux and dit not work on Windows."Do some window has the c method mlock some haven't？it's confused.

**Comment by hzh0425** [comment]
I have tested this method on both win10 and win11, but it doesn't work.

**Comment by leeveel** [comment]
windows 上面应该是kernel32.dll的VirtualLock才对吧？

**Comment by djl394922860** [comment]
mark this question , wait for answer

**Comment by zhouxinyu** [comment]
mlock is a system call of Linux, it seems that the Windows platform has an alternative function: https://docs.microsoft.com/zh-cn/windows/win32/api/memoryapi/nf-memoryapi-virtuallock?redirectedfrom=MSDN
