### ISSUE TITLE
Will resetOffset definitely take effect?

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#4206]
After resetOffset, whether the offset will be modified if there is a response from the previous request. Let resetOffset not take effect。

DefaultMQPushConsumerImpl#361

                        case NO_NEW_MSG:
                        case NO_MATCHED_MSG:
                            pullRequest.setNextOffset(pullResult.getNextBeginOffset());

                            DefaultMQPushConsumerImpl.this.correctTagsOffset(pullRequest);

                            DefaultMQPushConsumerImpl.this.executePullRequestImmediately(pullRequest);

offset will be overwritten？

**Comment by Zanglei06** [comment]
pushConsumer is paused for a while when resetOffset, I remember pause for 10 seconds.

**Comment by lwclover** [comment]
> overwritten

Can you give more information？

**Comment by ni-ze** [comment]
resetOffset send a message to let client drop processQueue and suspend client. If client send a before suspend and broker receive it after reset, it does will overwitten. It happen with a very small probability, you can reset offset again if that happen.
