### ISSUE TITLE
Why two sets of logs were established, The InnerLogger and Slf4jLoggerFactory

### ISSUE THREAD

**Issue by a626411464** [apache/rocketmq#4207]
I have a problem . why two sets of logs were established, The InnerLogger and Slf4jLoggerFactory . thanks

**Comment by lwclover** [comment]
do you think it should be built on demand?

**Comment by HScarb** [comment]
+1
I have the same doubt

**Comment by MatrixHB** [comment]
InnerLoggerFactory is used for client logging, Slf4jLoggerFactory is used for modules in RocketMQ. As slf4j log configuration file may conflict with other logging system, InnerLoggerFactory is used to solve this probelm for client.

Answerd by the author in [ROCKETMQ-367](https://github.com/apache/rocketmq/pull/224)
