### ISSUE TITLE
OFFSET_OVERFLOW_BADLY will lead to consumption from begin, a large number of repeated consumption

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#4215]
version  4.9.3
In  DefaultMessageStore.java ，There is the following code：

else if (offset > maxOffset) {
                status = GetMessageStatus.OFFSET_OVERFLOW_BADLY;
                if (0 == minOffset) {
                    nextBeginOffset = nextOffsetCorrection(offset, minOffset);
                } else {
                    nextBeginOffset = nextOffsetCorrection(offset, maxOffset);
                }

It can be seen that if minOffset=0.Consumption will start from 0.This can lead to repeated consumption of data for several days.

I suggest modifying to:。

else if (offset > maxOffset) {
                status = GetMessageStatus.OFFSET_OVERFLOW_BADLY;
                nextBeginOffset = nextOffsetCorrection(offset, maxOffset);

If it's ok i can submit a pr .

**Comment by ltamber** [comment]
it seem that have been fixed in [here](https://github.com/apache/rocketmq/blob/5.0.0-beta/store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java#L702) in branch 5.0.0-beta

**Comment by iamqq23ue** [comment]
> it seem that have been fixed in [here](https://github.com/apache/rocketmq/blob/5.0.0-beta/store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java#L702) in branch 5.0.0-beta

@ltamber 5.0.0 seems to have changed a lot, we still plan to use version 4.9 for now.

**Comment by ltamber** [comment]
> 

then you can cherry-pick it from 5.0.0 to 4.9.3 and submit a pr :)

**Comment by RongtongJin** [comment]
Merged
