### ISSUE TITLE
mqbroker.xml 文件的用途是什么

### ISSUE THREAD

**Issue by kyvli** [apache/rocketmq#422]
bin目录下 mqbroker.xml mqnamesrv.xml mqfiltersrv.xml这些文件是什么作用？设置jvm参数吗？jvm参数不是在runbroker.sh里面设置的吗？

**Comment by vongosling** [comment]
请忽略这里的文件

**Comment by rex-ma-2015** [comment]
这三个文件建议在以后的版本里去掉，我今天也是琢磨了好久就是找不到使用的地方。
