### ISSUE TITLE
Delete repeated calls in MQClientInstance.start

### ISSUE THREAD

**Issue by lwclover** [apache/rocketmq#4223]
Delete repeated calls 'this.defaultMQProducer.getDefaultMQProducerImpl().start(false)' in MQClientInstance.start, It triggers a Heartbeat call and an extra timer.

**Comment by ni-ze** [comment]
This defaultMQProducer is necessary for message sending back to broker.
and  **start** method will not invoke  MQClientInstance#start, because it's parameter is false.
and It is a producer, so heat heat and scheduled task should have like other normal producer.

This is my opinion.

**Comment by lwclover** [comment]
> This defaultMQProducer is necessary for message sending back to broker. and **start** method will not invoke MQClientInstance#start, because it's parameter is false. and It is a producer, so heat heat and scheduled task should have like other normal producer.
> 
> That is my opinion.

This line:
this.defaultMQProducer.getDefaultMQProducerImpl().start(false).

**Comment by ni-ze** [comment]
> > This defaultMQProducer is necessary for message sending back to broker. and **start** method will not invoke MQClientInstance#start, because it's parameter is false. and It is a producer, so heat heat and scheduled task should have like other normal producer.
> > That is my opinion.
> 
> I mean this line in MQClientInstance#start: this.defaultMQProducer.getDefaultMQProducerImpl().start(false).

yeah, I watched your pr.

**Comment by MatrixHB** [comment]
You said "repeated" call, but I don't get it. Where is another call for `this.defaultMQProducer.getDefaultMQProducerImpl().start(false)`?  
--------------------
你提到了“重复调用”，但是重复调用start的地方在哪里呀？这里的producer.start 起来是为了consumer客户端可以将消费失败的消息发送回broker，并没有重复吧？

**Comment by lwclover** [comment]
DefaultMQProducer starts as follows:
DefaultMQProducer.start() -> DefaultMQProducerImpl.start() -> DefaultMQProducerImpl.start(true) -> MQClientInstance.start() -> DefaultMQProducerImpl.start(false).
In  DefaultMQProducerImpl.start(false) call 

```
this.mQClientFactory.sendHeartbeatToAllBrokerWithLock();
RequestFutureHolder.getInstance().startScheduledTask(this);
```
DefaultMQProducerImpl.start(true) call again.
