### ISSUE TITLE
[Feature] Support Producer relate metric report.

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/rocketmq#4228]
like `GET_CONSUMER_RUNNING_INFO` we can add new rpc like `GET_PRODUCER_RUNNING_INFO` to support producer internal metric report.

**Comment by WJL3333** [comment]
@duhenglucky @RongtongJin what do you think guys ?

**Comment by lizhiboo** [comment]
@WJL3333 what do u want get by GET_PRODUCER_RUNNING_INFO ? producer configuration？

**Comment by duhenglucky** [comment]
> like `GET_CONSUMER_RUNNING_INFO` we can add new rpc like `GET_PRODUCER_RUNNING_INFO` to support producer internal metric report.

@WJL3333 Sorry to reply you later:), _GET_CONSUMER_RUNNING_INFO_  aims to obtain the consumption status of consumers, especially the status of the consumption thread, to help users find the reason for the accumulation of messages, to help them better optimize the code and improve the consumption speed. So I'm thinking, what do we expect from this _GET_PRODUCER_RUNNING_INFO_  new command？
