### ISSUE TITLE
RocketMQ not support for install on mac with homebrew

### ISSUE THREAD

**Issue by techwnn** [apache/rocketmq#4232]
In fact, there is no material for installation on mac. 
On the opposite, Kafka provide official support for install on mac with homebrew. another sample is opensearch provide official support for homebrew, as replacement for elasticsearch, opensearch's action is quick.

I think this is important for a top level project and friendly for new beginners with mac.

**Comment by duhenglucky** [comment]
@TechAilurus Great suggestion, would you like to implement this feature？

**Comment by TechAilurus** [comment]
> o implement this feat

yeah I want to, but I am powerless for this currently.

I'm new beginners on backend service, so I have too much frameworks to learn.
