### ISSUE TITLE
Retrying policy may caused the data skew while  failing to consume message?

### ISSUE THREAD

**Issue by Chasun-fhd** [apache/rocketmq#4249]
Hey, i'm trying to use retrying policy when i failed to consume message. But i found that almost all retrying messages are wrote to one of broker in the cluster. maybe data skew occurred.

After digging into the source code, i found the default value of retryQueueNums in SubscriptionGroupConfig is 1 。is it reason which causing the data skew ? And it seems like only in the Admin Client can modify this parameter. but worried about the consequence if i did so。

wish for replying ... ^.^

**Comment by ni-ze** [comment]
Which broker received retry message is decided by brokerName of retry message. Usually, message may come from different  broker, so retry message send to different broker, not just only one broker.

**Comment by Chasun-fhd** [comment]
well, it seems like they are all delivered to the same broker. i don't know why this happened, And recently  i found another problem,  some of brokers in the cluster, queue bound to it cannot be consumed by client, event if add new consumer or reboot my service while connecting to the brokers.  Any possible reasons or directions for me  to figure it out..  more detail, event restart these problem brokers. the problem is still there.

**Comment by ni-ze** [comment]
which version is the broker? Maybe some error is appeared in your client log. Broker log also need to check.

**Comment by Chasun-fhd** [comment]
ok, thks， i will check.   

And i also want to ask another question,  they two problem seems to cause  the same behavior。  when some of pods crashes down for a while in k8s cluster due to vm problem。then recovered, application worked fine, but the message in this broker become more and more,  cost a very long time to catch up the offset as other broker.  Event increasing quantities of pods ,  it just cannot solve the message accumulation. Is there any possible or better solutions about this .  We already encountered this problem several times.

**Comment by ni-ze** [comment]
> 
I can not answer your question directly, it need deeper analyze base on more details.
