### ISSUE TITLE
message filter

### ISSUE THREAD

**Issue by mushang8923** [apache/rocketmq#427]
4.2版本里还能开到filtersrv目录，4.3版本里filtersrv目录已经不见了，通过shell脚本看到的还是启动的FiltersrvStartup,bin目录下所有的exe文件都不见了，是不是有什么改动？

**Comment by vongosling** [comment]
目前不支持发布二进制文件以及filtersrc特性。请仔细阅读issue模板，如果有问题，欢迎大家订阅邮件列表然后发邮件到user mail list，http://rocketmq.apache.org/about/contact/

**Comment by mushang8923** [comment]
@dongeforever 配置filterServerNums这种方式根本就不需要了，配置上去就会报错？broker里的filtersrv是不是也不需要了

**Comment by dongeforever** [comment]
对的，不要配置filterServerNums。

**Comment by mushang8923** [comment]
@dongeforever 
filter sqlConsumer写的有语法错误
  MessageSelector.bySql("(TAGS is not null and TAGS in ('TagA', 'TagB'))" +
                    "and (a is not null and a between 0  3)"));

**Comment by lemonzone2010** [comment]
> @dongeforever
> filter sqlConsumer写的有语法错误
> MessageSelector.bySql("(TAGS is not null and TAGS in ('TagA', 'TagB'))" +
> "and (a is not null and a between 0 3)"));
> 要用这个sqlfilter还要增加配置enablePropertyFilter=true 吧

需要

**Comment by lemonzone2010** [comment]
> 对的，不要配置filterServerNums。

message filterclass 这种不支持了。消费者中方法也没有去除呀，应该在release note 说明下。
