### ISSUE TITLE
错误: 找不到或无法加载主类 Files\Sybase\mysql-connector-java-5.1.7-bin.jar

### ISSUE THREAD

**Issue by MrJiangxh** [apache/rocketmq#432]
rocketmq-all-4.3.0-bin-release版本
windows7 64位
cmd下运行mqnamesrv正常启动
cmd下运行mqbroker报以下错误
错误: 找不到或无法加载主类 Files\Sybase\mysql-connector-java-5.1.7-bin.jar

**Comment by duhengforever** [comment]
@MrJiangxh Please check the environment，Rocketmq does not have a dependency on mysql.
