### ISSUE TITLE
Update consumer core pool size

### ISSUE THREAD

**Issue by yhhazr** [apache/rocketmq#4334]
@Override
    public void updateCorePoolSize(int corePoolSize) {
        if (corePoolSize > 0
            && corePoolSize <= Short.MAX_VALUE
            && corePoolSize < this.defaultMQPushConsumer.getConsumeThreadMax()) {
            this.consumeExecutor.setCorePoolSize(corePoolSize);
        }
    }
corePoolSize < this.defaultMQPushConsumer.getConsumeThreadMax()  Should this be corePoolSize <= this.defaultMQPushConsumer.getConsumeThreadMax(),it can not update to max thread number

**Comment by hzh0425** [comment]
but the default max thread is 'ConsumeThreadMax()'

**Comment by yhhazr** [comment]
If i want to update the core size greater than the old value, how to use it?
defaultMQPushConsumer.setConsumeThreadMax(newValue + 1);
defaultMQPushConsumer.updateCorePoolSize(newValue);
??

**Comment by ni-ze** [comment]
> 

It can not update core size greater than the old one, once you set it before consumer start,
```java
defaultMQPushConsumer.setConsumeThreadMax(value);
```

**Comment by cserwen** [comment]
> If i want to update the core size greater than the old value, how to use it? defaultMQPushConsumer.setConsumeThreadMax(newValue + 1); defaultMQPushConsumer.updateCorePoolSize(newValue); ??

@yhhazr The consumeThreadMax is the value of `maximumPoolSize` of thread Pool. You can update the core size to a value less than consumeThreadMax. But the maximumPoolSize cannot be updated, the sdk does not provide a method to update this value.
