### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by fll666888** [apache/rocketmq#4339]
版本4.9.2   发送事务消息后，回查出现了问题，报空指针
![image](https://user-images.githubusercontent.com/105038780/168985497-9715f835-c605-47a3-9fab-b21987ecd83f.png)

**Comment by lizhiboo** [comment]
@fll666888 do u set    producer.setExecutorService(executorService)?

**Comment by fll666888** [comment]
> @fll666888你设置 producer.setExecutorService(executorService) 吗？

设置了
![image](https://user-images.githubusercontent.com/105038780/169002224-dead59a9-5830-4f26-b170-e1d61d9bced7.png)

**Comment by fll666888** [comment]
> @fll666888 do u set producer.setExecutorService(executorService)?

![image](https://user-images.githubusercontent.com/105038780/169003341-5b26bc52-d148-4f10-8579-2b803615c571.png)
但是断点到这个地方是为null

**Comment by duhenglucky** [comment]
客户端也是4.9.2 吗？

**Comment by fll666888** [comment]
> 客户端也是4.9.2 吗？

是的
![image](https://user-images.githubusercontent.com/105038780/169010061-31bad7ee-19db-4107-95d8-828ab22c4d7f.png)

![image](https://user-images.githubusercontent.com/105038780/169009945-e698adbf-0e2a-4a55-ad59-18eff92d8091.png)

**Comment by fll666888** [comment]
> can you provide your demo for reproduce this question?

可以

**Comment by fll666888** [comment]
> can you provide your demo for reproduce this question?

**Comment by fll666888** [comment]
> can you provide your demo for reproduce this question?



> can you provide your demo for reproduce this question?

**Comment by fll666888** [comment]
> can you provide your demo for reproduce this question?
[demo.zip](https://github.com/apache/rocketmq/files/8723176/demo.zip)

**Comment by fll666888** [comment]
> can you provide your demo for reproduce this question?
[demo.zip](https://github.com/apache/rocketmq/files/8723177/demo.zip)

**Comment by fll666888** [comment]
> can you provide your demo for reproduce this question?

一个是项目，一个是数据库

**Comment by lizhiboo** [comment]
@fll666888 u can refer following code
```java
        TransactionListener transactionListener = new TransactionListenerImpl();
        TransactionMQProducer producer = new TransactionMQProducer("please_rename_unique_group_name");
        ExecutorService executorService = new ThreadPoolExecutor(2, 5, 100, TimeUnit.SECONDS, new ArrayBlockingQueue<Runnable>(2000), new ThreadFactory() {
            @Override
            public Thread newThread(Runnable r) {
                Thread thread = new Thread(r);
                thread.setName("client-transaction-msg-check-thread");
                return thread;
            }
        });

        producer.setExecutorService(executorService);
        producer.setTransactionListener(transactionListener);
        producer.start();

        String[] tags = new String[] {"TagA", "TagB", "TagC", "TagD", "TagE"};
        for (int i = 0; i < 10; i++) {
            try {
                Message msg =
                    new Message("TopicTest1234", tags[i % tags.length], "KEY" + i,
                        ("Hello RocketMQ " + i).getBytes(RemotingHelper.DEFAULT_CHARSET));
                SendResult sendResult = producer.sendMessageInTransaction(msg, null);
                System.out.printf("%s%n", sendResult);

                Thread.sleep(10);
            } catch (MQClientException | UnsupportedEncodingException e) {
                e.printStackTrace();
            }
        }
```

**Comment by fll666888** [comment]
> @fll666888 u can refer following code
> 
> ```java
>         TransactionListener transactionListener = new TransactionListenerImpl();
>         TransactionMQProducer producer = new TransactionMQProducer("please_rename_unique_group_name");
>         ExecutorService executorService = new ThreadPoolExecutor(2, 5, 100, TimeUnit.SECONDS, new ArrayBlockingQueue<Runnable>(2000), new ThreadFactory() {
>             @Override
>             public Thread newThread(Runnable r) {
>                 Thread thread = new Thread(r);
>                 thread.setName("client-transaction-msg-check-thread");
>                 return thread;
>             }
>         });
> 
>         producer.setExecutorService(executorService);
>         producer.setTransactionListener(transactionListener);
>         producer.start();
> 
>         String[] tags = new String[] {"TagA", "TagB", "TagC", "TagD", "TagE"};
>         for (int i = 0; i < 10; i++) {
>             try {
>                 Message msg =
>                     new Message("TopicTest1234", tags[i % tags.length], "KEY" + i,
>                         ("Hello RocketMQ " + i).getBytes(RemotingHelper.DEFAULT_CHARSET));
>                 SendResult sendResult = producer.sendMessageInTransaction(msg, null);
>                 System.out.printf("%s%n", sendResult);
> 
>                 Thread.sleep(10);
>             } catch (MQClientException | UnsupportedEncodingException e) {
>                 e.printStackTrace();
>             }
>         }
> ```

之前就试过了，我的demo已经上传了，你可以试一下

**Comment by lizhiboo** [comment]
@fll666888 两个demo里面只有一个sql

**Comment by fll666888** [comment]
> @fll666888 两个demo里面只有一个sql
这是项目的链接 https://github.com/fll666888/demo.git

**Comment by fll666888** [comment]
> @fll666888 两个demo里面只有一个sql

是我哪个地方配置有问题吗？

**Comment by caigy** [comment]
@fll666888 Is it in `com.example.demo.controller.RocketmqController#transactionSendMessage`? It seems that the producer is a local variable in this method, which will be cleared after the method exits. So you may find that messages could be sent normally, but the recheck process (occurred after the method exited) was failed for related objects were not alive.
You may hold the producer in a static filed and try again.

**Comment by fll666888** [comment]
> @fll666888 Is it in `com.example.demo.controller.RocketmqController#transactionSendMessage`? It seems that the producer is a local variable in this method, which will be cleared after the method exits. So you may find that messages could be sent normally, but the recheck process (occurred after the method exited) was failed for related objects were not alive. You may hold the producer in a static filed and try again.

试过了，还是进程异常
![1653360228(1)](https://user-images.githubusercontent.com/105038780/169938194-a1f947bc-3dfb-40cc-80d3-069429f0b9cd.png)
![1653359815](https://user-images.githubusercontent.com/105038780/169938274-b19a25b0-b8ae-4828-9003-bafc0d5dcc54.jpg)

**Comment by lizhiboo** [comment]
> 

官方trx demo能跑通吗？

**Comment by fll666888** [comment]
> > 
> 
> 官方trx demo能跑通吗？

你好，我已经找到问题了，producerGroup重复产生导致的问题，非常感谢大家的帮助！
