### ISSUE TITLE
how to get all group infos?

### ISSUE THREAD

**Issue by sighting33** [apache/rocketmq#4342]
1.consumer group
2.product group

Is there any api about group Info?

**Comment by yangjava** [comment]
in rocketmq dashboard

1.consumer group


`   @Override
    public List<GroupConsumeInfo> queryGroupList(boolean skipSysGroup) {
        Set<String> consumerGroupSet = Sets.newHashSet();
        try {
            ClusterInfo clusterInfo = mqAdminExt.examineBrokerClusterInfo();
            for (BrokerData brokerData : clusterInfo.getBrokerAddrTable().values()) {
                SubscriptionGroupWrapper subscriptionGroupWrapper = mqAdminExt.getAllSubscriptionGroup(brokerData.selectBrokerAddr(), 3000L);
                consumerGroupSet.addAll(subscriptionGroupWrapper.getSubscriptionGroupTable().keySet());
            }
        }
        catch (Exception err) {
            throw Throwables.propagate(err);
        }
        List<GroupConsumeInfo> groupConsumeInfoList = Lists.newArrayList();
        for (String consumerGroup : consumerGroupSet) {
            groupConsumeInfoList.add(queryGroup(consumerGroup));
        }
        if (!skipSysGroup) {
            groupConsumeInfoList.stream().map(group -> {
                if (SYSTEM_GROUP_SET.contains(group.getGroup())) {
                    group.setGroup(String.format("%s%s", "%SYS%", group.getGroup()));
                }
                return group;
            }).collect(Collectors.toList());
        }
        Collections.sort(groupConsumeInfoList);
        return groupConsumeInfoList;
    }`

**Comment by sighting33** [comment]
> 
we dont use dashboard. use rocketmq client only .

**Comment by yangjava** [comment]
public class MQClientInstance {
    .....
    private final ConcurrentMap<String/* group */, MQProducerInner> producerTable = new ConcurrentHashMap<String, MQProducerInner>();
    private final ConcurrentMap<String/* group */, MQConsumerInner> consumerTable = new ConcurrentHashMap<String, MQConsumerInner>();
    private final ConcurrentMap<String/* group */, MQAdminExtInner> adminExtTable = new ConcurrentHashMap<String, MQAdminExtInner>();

**Comment by cserwen** [comment]
> we dont use dashboard. use rocketmq client only .

@sighting33 You can refer to `getAllSubscriptionGroup` of `DefaultMQAdminExt` to get All groups.
https://github.com/apache/rocketmq/blob/82a48be00a6d9def14abb871a40cb68cf8a041e9/tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java#L504

In fact, some access to metadata can be achieved through DefaultMQAdminExt. RocketMQ Dashboard is implemented using it.
