### ISSUE TITLE
[Docs] Refactor Rocketmq documentation

### ISSUE THREAD

**Issue by complone** [apache/rocketmq#4343]
At present, because [rocketmq-site](https://github.com/apache/rocketmq-site) does not display according to the version number released by rocketmq, when users use it, they do not know whether a configuration item has been upgraded. Refer to [kafka-site](https://github.com/apache/kafka-site) and [pulsar-site](https://github.com/apache/pulsar-site)。. Currently decided to refactor the 4.x version of the documentation

The work to be done in the first stage is as follows

1. Organize the configuration documents of the broker and client modules, and confirm with the community
2. Confirm the unit test of the broker and the client, and run the example. Locating and explaining key classes
3. Organize the documentation of nameserver

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by LXPWing** [comment]
Cool I want to try it

**Comment by complone** [comment]
> Cool I want to try it

The tasks are being split recently, and it is expected that the specific sub-tasks will be improved before next Friday

**Comment by complone** [comment]
According to the current release order of rocketmq, the documents of four versions of ```4.6```, ```4.7```, ```4.8``` and ```4.9``` are sorted at this stage.
1. The official website homepage document is re-divided into five guide items: Quickstart , Configuration , Performance , Operations and API Docs
Refer to the initial version of kafka (0.7) [documentation](https://kafka.apache.org/07/documentation.html)
Give an example of producer and consumer, and update the histogram of throughput comparison according to the stress test results
