### ISSUE TITLE
你好，我找遍你们文档，我也没看到日志说明。现在打印不出日志呢？我就不说英语了，你应该看懂中文。

### ISSUE THREAD

**Issue by YuHangZM** [apache/rocketmq#4351]
大哥，这个是怎么回事呢？怎么解决？
![image](https://user-images.githubusercontent.com/22367283/169434255-b967fd53-9705-4de8-b183-be8da1f80529.png)
![image](https://user-images.githubusercontent.com/22367283/169434309-2054d65c-ecba-4ec4-9fae-b4d59e3f80b3.png)
![image](https://user-images.githubusercontent.com/22367283/169434334-5dd78588-72ea-499d-972f-d3b915662463.png)

**Comment by XiaoyiPeng** [comment]
This problem doesn't seem to have anything to do with rocketmq!
Please make sure: 

The VM argument should be   `-Dlog4j.configuration=file:#DIRECTORY_PATH#/${your_log4j_path_dir}/log4j.properties`, for example on Windows: 

> `-Dlog4j.configuration=file:C:\Users\me\log4j..properties`

**Comment by YuHangZM** [comment]
你说的这种方法我不接受，请解释说明，这种方式为什么不行？ 是我配置的不对么？ 请使用 中文回答

**Comment by YuHangZM** [comment]
你总不能学习一个框架，我就看一下源码吧，都是中国人，别拽啦。用中文

**Comment by YuHangZM** [comment]
> This problem doesn't seem to have anything to do with rocketmq! Please make sure:
> 
> The VM argument should be `-Dlog4j.configuration=file:#DIRECTORY_PATH#/${your_log4j_path_dir}/log4j.properties`, for example on Windows:
> 
> > `-Dlog4j.configuration=file:C:\Users\me\log4j..properties`



> This problem doesn't seem to have anything to do with rocketmq! Please make sure:
> 
> The VM argument should be `-Dlog4j.configuration=file:#DIRECTORY_PATH#/${your_log4j_path_dir}/log4j.properties`, for example on Windows:
> 
> > `-Dlog4j.configuration=file:C:\Users\me\log4j..properties`
大姐，能详细解释下么？现在有什么问题？别说英文啦。虽然我能看懂

**Comment by YuHangZM** [comment]
唉，还是自己看源码吧，垃圾回复。

**Comment by YuHangZM** [comment]
唉，知道咋回事了。看个打印日志问题还得看个源码，艹蛋。文档垃圾一样
