### ISSUE TITLE
shell script: set supported JVM options according to current JDK version 

### ISSUE THREAD

**Issue by walking98** [apache/rocketmq#436]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
when startup mqnamesvr or run mqadmin with my JDK8 env, it always raises some unnecessary VM warning like the following:
```  
$ ./bin/mqnamesrv -n 127.0.0.1:9876
Java HotSpot(TM) 64-Bit Server VM warning: Using the DefNew young collector with the CMS collector is deprecated and will likely be removed in a future release
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
...
```

```
sh mqadmin updateTopic -b 127.0.0.1:10911 -t TopicA
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
...
```  

- What did you expect to see?

It will be good if the shell script can skip the deprecated VM options depending on the different JDK version.

2. Please tell us about your environment:

MacBook + JDK8

**Comment by vongosling** [comment]
Do you still have in the current version?
