### ISSUE TITLE
Does RocketMQ support -Dfastjson.parser.safeMode=true  to circumvent fastjson vulnerability?

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#4360]
version:4.9.1
fastjson1.2.80 reported a deserialization vulnerability again. I would like to ask if it is possible to set -Dfastjson.parser.safeMode=true to circumvent this vulnerability.
Can Rocketmq support safemode?

Or is it supported to upgrade to fastjson 1.2.83.

**Comment by sunxi92** [comment]
fastjson security_update_20220523:https://github.com/alibaba/fastjson/wiki/security_update_20220523
fastjson_safemode:https://github.com/alibaba/fastjson/wiki/fastjson_safemode

**Comment by odbozhou** [comment]
Fastjson 1.2.68 and above version support
-Dfastjson.parser.safeMode=true Security hardening.
The fastjson version currently used by rocketmq 4.9.1 is 1.2.76
Therefore, this method is supported for security reinforcement.
 You can do security reinforcement according to the instructions and precautions in the official fastjson document.

**Comment by iamqq23ue** [comment]
@odbozhou thanks for the reply. Setting -Dfastjson.parser.safeMode=true should circumvent security holes. 

What I want to know is, will it cause compatibility issues with rocketmq?

**Comment by inkinworld** [comment]
> @odbozhou thanks for the reply. Setting -Dfastjson.parser.safeMode=true should circumvent security holes.
> 
> What I want to know is, will it cause compatibility issues with rocketmq?

Yes, that's the key point. We are not sure wheather rocketmq use autoType fearure.
The most reliable way is upgrade the dependency jar file.

https://github.com/alibaba/fastjson/wiki/security_update_20220523#32-safemode%E5%8A%A0%E5%9B%BA

**Comment by iamqq23ue** [comment]
> > @odbozhou thanks for the reply. Setting -Dfastjson.parser.safeMode=true should circumvent security holes.
> > What I want to know is, will it cause compatibility issues with rocketmq?
> 
> Yes, that's the key point. We are not sure wheather rocketmq use autoType fearure. The most reliable way is upgrade the dependency jar file.
> 
> https://github.com/alibaba/fastjson/wiki/security_update_20220523#32-safemode%E5%8A%A0%E5%9B%BA

upgrade the dependency jar file  also may have compatibility issues.And in the future, fastjson may still have security breach that need to be upgraded.

**Comment by odbozhou** [comment]
The use of autoType was not found. The latest code has been upgraded to fastjson to 1.2.83, and no compatibility has been found yet.
