### ISSUE TITLE
2022 Alibaba Summer of Code

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#4370]
2022 Alibaba Summer of Code
---
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly in open source software development. Under the guidance of the mentor in the Alibaba open source project, students can experience software development in the real world. Alibaba Summer of code will begin from May 30th to September 1st. Students can use the summertime to participate in the open source project and work with the core members of the project.

What you can get?
---
On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation;

- Get a scholarship from Alibaba;

- Obtain an open source contributor certificate;

- Get a fast pass of Alibaba Internship/recruitment;

- Get your code adopted and used by the open source project！

Our Mentor
---
- Li Wei,[@francisoliverlee](https://github.com/francisoliverlee),Apache RocketMQ Committer
- Nicholas Jiang,[@SteNicholas](https://github.com/SteNicholas),Apache RocketMQ Committer
- Cheng Junjie,Apache RocketMQ Committer

Apply Now!
---
- You can click on this link to apply directly:
     1. [Apache RocketMQ Connect Sink to Apache Doris](https://github.com/apache/rocketmq-connect/issues/146)
    2. [Implement of Apache RocketMQ Flink Catalog](https://github.com/apache/rocketmq-flink/issues/32)
    3. [Implement of Apache RocketMQ Streams dispatching system ](https://github.com/apache/rocketmq-streams/issues/159)
- Upload your CV and project proposal via ASOC 2022 official website：[ASOC2022](https://opensource.alibaba.com/asoc2022)

Timeline⏳
---
![image](https://user-images.githubusercontent.com/16487356/170170630-b5988aa9-447a-4247-af42-e8bb540a73c6.png)

Contact us!
---
If you have any questions, visit the event website:[ASOC2022](https://opensource.alibaba.com/asoc2022)
Email address: opensource@alibaba-inc.com

**Comment by ShannonDing** [comment]
More features, https://shimo.im/docs/Ee32MjM69Vu9OQA2. ,and the task list will be updated from time to time.

**Comment by TheR1sing3un** [comment]
> More features, https://shimo.im/docs/Ee32MjM69Vu9OQA2. ,and the task list will be updated from time to time.

Hello，whether the projects in the documents you mentioned will eventually go online to asoc ？

**Comment by ShannonDing** [comment]
> > More features, https://shimo.im/docs/Ee32MjM69Vu9OQA2. ,and the task list will be updated from time to time.
> 
> Hello，whether the projects in the documents you mentioned will eventually go online to asoc ？

Some topics will be officially selected by ASOC2022, and the remaining topics will be keep open in the community, which can be completed by students interested in.

**Comment by azhsmesos** [comment]
> 更多功能，https://shimo.im/docs/Ee32MjM69Vu9OQA2。，并且任务列表会不时更新。
文档中的内容目前可以提issue认领吗

**Comment by ShannonDing** [comment]
> > 更多功能，[https://shimo.im/docs/Ee32MjM69Vu9OQA2。，并且任务列表会不时更新。](https://shimo.im/docs/Ee32MjM69Vu9OQA2%E3%80%82%EF%BC%8C%E5%B9%B6%E4%B8%94%E4%BB%BB%E5%8A%A1%E5%88%97%E8%A1%A8%E4%BC%9A%E4%B8%8D%E6%97%B6%E6%9B%B4%E6%96%B0%E3%80%82)
> > 文档中的内容目前可以提issue认领吗

非常欢迎， 题目列表中的可选题目都可以通过直接提交issue到对应repo。

**Comment by insist777** [comment]
@ShannonDing Hi, What topics have not been done in this document?

**Comment by ShannonDing** [comment]
See you next year.
