### ISSUE TITLE
Let's migrate to SpotBugs

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#4374]
Actually FindBugs is deprecated and no longer maintained, [SpotBugs](https://spotbugs.github.io/index.html) is a successor of FindBugs, and enforcing static FindBugs/SpotBugs checks during compilation might be a good proposal ?

**Comment by aaron-ai** [comment]
This may not be a problem, more like a proposal, there are currently some mistakes in the RocketMQ code that SpotBugs can scan, should we tackle it now？or a pull request may make it more clearly. @ShannonDing 
cc @zhouxinyu @lizhanhui

**Comment by lizhanhui** [comment]
@aaron-ai It's good to migrate to SpotBugs now that FindBugs is not maintained anymore.
