### ISSUE TITLE
广播消费时消费点位问题

### ISSUE THREAD

**Issue by baigod** [apache/rocketmq#438]
问题： 我创建了一个消费监听，代码如下

```java
// 创建消费实例
@Bean(initMethod = "start", destroyMethod = "shutdown")
public DefaultMQPushConsumer rocketMQUserCudConsumer() throws MQClientException {
    DefaultMQPushConsumer consumer = new DefaultMQPushConsumer(rocketMQProperties.getConsumerId());
    consumer.setNamesrvAddr(rocketMQProperties.getNamesrv());
    consumer.setMessageModel(MessageModel.BROADCASTING); // 广播消费
    consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_FIRST_OFFSET);

    consumer.subscribe(“T_MATCH_SIGNAL_DEV”, "*");
    consumer.registerMessageListener(new MessageListenerConcurrently() {
        @Override
        public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs, ConsumeConcurrentlyContext context) {
            //do something
            LOGGER.info("{} consume_success", topic);
            return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
        }
    });
    return consumer;
}
```

在测试环境测试时，都正常消费并打印日志
![image](https://user-images.githubusercontent.com/23446974/44891184-8824df80-ad10-11e8-9e74-14d7b474a6aa.png)

但是在rocketmq-console里显示消费点位（consumerOffset） 都是0，看起来像是全部堆积的样子
![image](https://user-images.githubusercontent.com/23446974/44891212-b1de0680-ad10-11e8-86e6-42f7542f7eed.png)

请问这是属于bug还是正常的？

PS: 我用的rocketmq版本 4.3.0 , rocketmq部署在centos7.3

**Comment by baigod** [comment]
图片显示不出来，我补一下图
![image](https://user-images.githubusercontent.com/23446974/44891304-2022c900-ad11-11e8-8321-33425c1917a1.png)

![image](https://user-images.githubusercontent.com/23446974/44891316-2fa21200-ad11-11e8-94d3-3e4cfe27b339.png)

**Comment by duhengforever** [comment]
@baigod As your code shows, the mode you are using is the broadcast consumption mode,  so the above situation is normal.
    If you have more questions about RocketMQ, please subscribe [mailing list](https://rocketmq.apache.org/about/contact/), and send email for help, there are more community developers will help you.
