### ISSUE TITLE
版本4.9.2 参数transactionCheckMax和transactionCheckInterval在broker.conf中配置，不起作用

### ISSUE THREAD

**Issue by fll666888** [apache/rocketmq#4381]

**Comment by ni-ze** [comment]
If your format likes:
```xml
transactionCheckInterval=29*1000
```
this setting will not take effect.

```xml
public void setTransactionCheckInterval(long transactionCheckInterval) {
        this.transactionCheckInterval = transactionCheckInterval;
    }
```
Above code is the set method of BrokerConfig, configuration item in broker.conf must has same type with the method parameter, that is to say, transactionCheckInterval can not be something like 29*1000, 29000 is ok.

Can you add a note for everyone's attention in broker.conf or somewhere alse?

**Comment by fll666888** [comment]
> If your format likes:
> 
> ```
> transactionCheckInterval=29*1000
> ```
> 
> this setting will not take effect.
> 
> ```
> public void setTransactionCheckInterval(long transactionCheckInterval) {
>         this.transactionCheckInterval = transactionCheckInterval;
>     }
> ```
> 
> Above code is the set method of BrokerConfig, configuration item in broker.conf must has same type with the method parameter, that is to say, transactionCheckInterval can not be something like 29*1000, 29000 is ok.
> 
> Can you add a note for everyone's attention in broker.conf or somewhere alse?

![image](https://user-images.githubusercontent.com/105038780/170616056-90f98571-3632-4238-ac12-cfc705dd4637.png)
已测过，还是不起作用

**Comment by ni-ze** [comment]
我测试过，可以的

**Comment by fll666888** [comment]
> 我测试过，可以的

![image](https://user-images.githubusercontent.com/105038780/170619389-4869420e-7782-4748-b970-dde71a3dcba5.png)
这个之前我都试过了

**Comment by fll666888** [comment]
> 我测试过，可以的

![1653623452611](https://user-images.githubusercontent.com/105038780/170625828-2af43266-fbc0-4c9f-b70b-1ffeea930baf.jpg)

**Comment by ni-ze** [comment]
![image](https://user-images.githubusercontent.com/31175234/170904335-663db1a8-9a95-4612-a7a7-e3b38aded997.png)
![image](https://user-images.githubusercontent.com/31175234/170904356-326287fb-9185-4b84-96cb-202eba563006.png)
