### ISSUE TITLE
启动异常，断点查看后发现delayOffset.json加载解析异常（复现场景未知，，）

### ISSUE THREAD

**Issue by Lychengit** [apache/rocketmq#4398]
![image](https://user-images.githubusercontent.com/90435449/171313465-dbe97e43-b64e-4739-974b-91b85fd2f7f4.png)

加载delayOffset.json时发现如下图的现象，导致解析异常。

![image](https://user-images.githubusercontent.com/90435449/171314432-356deeff-7f19-42aa-8be4-28657f2e0680.png)

附件
[delayOffset.zip](https://github.com/apache/rocketmq/files/8810542/delayOffset.zip)

**Comment by duhenglucky** [comment]
是在windows 上面么？有没有用编辑器打开过这个文件，然后选择了不同的编码方式保存？可以看下最后的修改时间
