### ISSUE TITLE
当前RocketMQ版本在部署架构上支持一Master多Slave，但只有BrokerId=1的从服务器才会参与消息的读负载。

### ISSUE THREAD

**Issue by 5087999223** [apache/rocketmq#4402]
当前RocketMQ版本在部署架构上支持一Master多Slave，但只有BrokerId=1的从服务器才会参与消息的读负载。如果是一主多从， 其它BrokerId>1的Slave是用来干什么的呢？是为了主、和BrokerId=1的Slave都不可用时才从BrokerId>1的Slave读取消息？

**Comment by ShannonDing** [comment]
你好，咨询类的问题可以通过邮件组https://rocketmq.apache.org/about/contact/ 或者直接到开发者交流群中讨论，钉钉群：21982288。
