### ISSUE TITLE
Log Retention

### ISSUE THREAD

**Issue by jothipandiyanjp** [apache/rocketmq#441]
Whether its possible to delete history message by time like log retention in Kafka?.

I want to delete old messages (let's say I want to keep only last 10 days records), Is this possible to achieve in rocketmq.?

Expecting: Time_To_Live concept per message or topic

**Comment by RongtongJin** [comment]
I think you can set the parameters in the broke’s config file. There are two parameters related to it, **fileReservedTime** means how long the message will be saved on the disk, its unit is hour, and the timeout message is automatically deleted, the default value is 48 hours, **deleteWhen** means when the delete action is performed , the default value of 04 indicates 4 am.

**Comment by jothipandiyanjp** [comment]
I found this link.. https://issues.apache.org/jira/browse/ROCKETMQ-133?jql=project%20%3D%20ROCKETMQ%20AND%20text%20~%20%22delete%22


It explains that TTL will be released in the 5.0.0 version...
Is any way to achieve this now...?
Because in the topics, message sizes are constantly growing...
ex: TOPIC X has total offset  -> 2578690
      TOPIC Y has total offset -> 631980

@RongtongJin 
As u mentioned above, default time would be 48 hours but still, messages are not deleted from the topic. Is there any other way to apply TTL functionality...
