### ISSUE TITLE
重试机制配合死信队列

### ISSUE THREAD

**Issue by ZhengJiaH** [apache/rocketmq#4412]
rocketmq 我这边设置了消费者最大重试次数是1。 正常会有两次投递（一次正常投递，一次再次投递），两次失败就会进入死信队列，我这边也在消费死信队列

理想情况下：生产者投递之后，消费者消费失败两次，进入死信队列，另外一个消费者消费死信队列

实际情况：消费者被投递一次之后就会直接进入死信队列
有可能是什么原因引起的呢？

**Comment by duhenglucky** [comment]
看下是否是使用了顺序消费，如果是顺序消费，是直接进入死信队列的

**Comment by ZhengJiaH** [comment]
你好，我看了一下代码，我这边没有用顺序消费，我把消费死信队列的消费者注释掉进可以投递两次，打开只能投递一次然后直接进入死信队列里面了

正常消费者相关配置：
![1654435247528](https://user-images.githubusercontent.com/43920762/172052578-7efbdd2b-0599-4ae5-9790-39db1d373abe.jpg)
![1654435320021](https://user-images.githubusercontent.com/43920762/172052619-b54e12db-988e-4fb1-940f-25108f7e95a9.jpg)
![1654435358366](https://user-images.githubusercontent.com/43920762/172052657-16f8b0af-d7bc-4407-bcef-ff43f33cf538.jpg)

但是消费死信队列之后将直接投递到死信队列里面了：
正常消费者 ：
![1654435536769](https://user-images.githubusercontent.com/43920762/172052782-fee35d5a-3390-4a2a-a762-bf1fb65a4059.jpg)
![1654435571930](https://user-images.githubusercontent.com/43920762/172052802-664d1675-cefe-4478-87c6-994c0605aaee.jpg)
死信队列消费者：
![1654435616902](https://user-images.githubusercontent.com/43920762/172052896-67203083-805e-49d6-aee3-c50c31e856fd.jpg)
消息是从死信队列里面消费的，但是ui界面的死信队列也没显示这个条消息
![1654435689387](https://user-images.githubusercontent.com/43920762/172053025-52b799df-1a24-49bc-9fe7-a136385082eb.jpg)

是我这边其他配置有问题吗？

**Comment by ZhengJiaH** [comment]
我找到原因了，是我配置的问题，不小心把两个消费者搞成一个消费组了，重新搞一下就正常了
