### ISSUE TITLE
It looks like the correct code was commented out.

### ISSUE THREAD

**Issue by 10Zico10** [apache/rocketmq#4418]
![image](https://user-images.githubusercontent.com/15681734/172105279-7c544a64-e2ed-4fb5-8b49-9cc7790201d1.png)

**Comment by HScarb** [comment]
These codes are moved to client to decrease the load of server.
See https://github.com/apache/rocketmq/blob/develop/client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java#L412-L424
