### ISSUE TITLE
how do i solve "broker busy"

### ISSUE THREAD

**Issue by xunianchong** [apache/rocketmq#4425]
error content : "publish topic:top-save-log error:CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 209ms, size of queue: 0"
![image](https://user-images.githubusercontent.com/16568795/172307409-ff22bf12-ea2e-417f-bef7-7c81efb13f6d.png)
![image](https://user-images.githubusercontent.com/16568795/172307423-b96bf17d-4875-469d-9607-cc041ebc8e9e.png)
![image](https://user-images.githubusercontent.com/16568795/172307444-5cfb6dc8-c7e7-44d0-af84-74f4256bcab3.png)

how cao i do ?  thank you!

**Comment by Cczzzz** [comment]
configure transientStorePoolEnable = true

**Comment by HScarb** [comment]
This log means the waiting time of the send requests waiting in request queue is beyond max waiting time (200ms).
You can try set transientStorePoolEnable=true to decrease the pressure of Page Cache

**Comment by MatrixHB** [comment]
Or, you can increase the waiting time limit in send request queue.

`sh mqadmin updateBrokerConfig -b {brokerIP:port} -k waitTimeMillsInSendQueue -v 3000`

**Comment by cserwen** [comment]
@xunianchong  If you are using the master-slave deployment mode, it is a good choice to turn on transientStorePoolEnable, but if it is in raft mode, this parameter has no effect. You need to first determine whether it is data synchronization (network) or the problem of slow pagecache writing.

**Comment by mxsm** [comment]
you can see this blog [broker busy issue](https://blog.ljbmxsm.com/middlewares/rocketmq/issue/broker-busy-issue/). This blog analyzes the reasons from the source code and the solution is given
