### ISSUE TITLE
Design and Implement transaction message escape of RIP 32

### ISSUE THREAD

**Issue by 6U-U9** [apache/rocketmq#4427]
Design of transaction message escape
When dealing with transaction message normally, **transactionalMessageCheckService** checks half messages in **RMQ_SYS_TRANS_HALF_TOPIC**,  calls **putBackHalfMsgQueue** to rewrite messages still need to check back to message queue of **RMQ_SYS_TRANS_HALF_TOPIC** , and updates consume offset.
When slave acts master, its **transactionalMessageCheckService** will start, but its **EndTransactionProcessor** will not accept any message tries to end a transaction such as commit or rollback. The running **transactionalMessageCheckService** will check transaction message and send any message needs check to a living master. **RMQ_SYS_TRANS_HALF_TOPIC** is also a topic not allowed to send in topic validator.So first wrap them in their origin topic with transaction check time, and send it to other master broker. Messages will bring its properties, such as **PROPERTY_TRANSACTION_CHECK_TIMES** , so master broker received these message is not going to check the transaction message for another **TRANS_CHECK_MAX_TIME**.
When the master broker recovers, it will be in pre-online progress before it is launched. It reversely obtains the metadata of the slave, especially the consumer offset of **RMQ_SYS_TRANS_HALF_TOPIC**. Thus the recovered master broker will not check the message which has escaped.
In terms of time, a transaction has to be checked twice before commit or rollback, which may cause a delay up to 120 second.
In terms of data volume, if a large number of transaction messages on the broker is waiting on the broker , remote escape will cause large data flow within the cluster

事务消息逃逸机制设计
在正常处理事务消息时，**transactionalMessageCheckService**检查半消息队列**RMQ_SYS_TRANS_HALF_TOPIC**中的半消息，并调用**putBackHalfMsgQueue**将检查到的并且仍需进行检查的消息写入半消息队列**RMQ_SYS_TRANS_HALF_TOPIC**中，并更新消费位置。
Slave代理Master时，**transactionalMessageCheckService**将启动。**transactionalMessageCheckService**将检查到的事务消息通过EscapeBridge向其他的Master逃逸。逃逸过程中为了避免半消息**RMQ_SYS_TRANS_HALF_TOPIC**不可写的限制，首先将半消息用原Topic包装，此时消息仍携带**PROPERTY_TRANSACTION_CHECK_TIMES**等属性，然后再投递到远程主节点上。收到消息的主节点将消息放入半消息队列**RMQ_SYS_TRANS_HALF_TOPIC**等待检查。
在主节点恢复后，通过预上线机制获取从节点的**RMQ_SYS_TRANS_HALF_TOPIC**队列的消费位点，更新主节点自己的**RMQ_SYS_TRANS_HALF_TOPIC**队列的消费位点，将不再检查已经逃逸的事务消息。
时间上一条事务消息需要经过slave的transactionalMessageCheckService和逃逸到的master的transactionalMessageCheckService两次检查才能完成提交，延时最多120秒。数据量上如果该broker上有大量的事务消息等待检查，远程逃逸会造成集群内部会有较大数据流转。

**Comment by hzh0425** [comment]
Good job, however, But does your contribution overlap with this issue? https://github.com/apache/rocketmq/issues/4408

**Comment by 6U-U9** [comment]
Add some details about escape mechanism of message which shall be discarded
Actually it's like the remote message escape mechanism. When discarding messages, Rocket MQ puts messages into **RMQ_SYS_TRANS_CHECK_MAX_TIME_TOPIC**, which is a not allowed to send topic in topic validator. For the remote escape of these messages, first wrap them in their origin topic with transaction check time, and send it to other master broker. As messages bring **PROPERTY_TRANSACTION_CHECK_TIMES** with them, master broker received these message first put them into half topic queue and discard them in next check.

更新应丢弃消息的逃逸机制的说明
应丢弃的消息逃逸机制和正常消息的逃逸机制相似。为了避免**RMQ_SYS_TRANS_CHECK_MAX_TIME_TOPIC**远程不可写的限制，首先将半消息用原Topic包装，此时消息仍携带**PROPERTY_TRANSACTION_CHECK_TIMES**属性，然后再投递到远程主节点上。收到消息的主节点将消息放入半消息队列**RMQ_SYS_TRANS_HALF_TOPIC**等待检查，在下一次检查中，将消息丢弃。
