### ISSUE TITLE
同一个consumerGroup不同的topic 报错

### ISSUE THREAD

**Issue by yuaneg** [apache/rocketmq#443]
rocketmq 版本是 4.3.0
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 24  DESC: the consumer's subscription not exist

**Comment by duhengforever** [comment]
请保持同一个consumer group拥有同样的订阅信息，[参考](https://rocketmq.apache.org/docs/best-practice-consumer/)

**Comment by CharlesSong** [comment]
但是如何使多个实例的consumer处于同一个consumer Group呢？
