### ISSUE TITLE
Implement a consume command with the PushConsumer

### ISSUE THREAD

**Issue by dongeforever** [apache/rocketmq#444]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
  Run the consumeMessage in the command line

- What did you expect to see?
  Expect the offset to be submitted, that is, I could get the consumer progress.
- What did you see instead?
  The consumerProgress will get nothing, unless I consume the message via the code.

2. Please tell us about your environment:
   4.3.0 and 4.3.1

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
  The consumeMessage command should act as the PushConsumer.And the current consumeMessage command may be renamed to pullMessage, which act as the PullConsumer.

  BTW, the current consumeMessage has a bug, the '-g' option is not parsed.

**Comment by duhengforever** [comment]
Fixed: https://github.com/apache/rocketmq/pull/440
