### ISSUE TITLE
Question about this.lock(mq) in updateProcessQueueTableInRebalance method

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#4451]
Because the `put` operation occurs after the `lock`, and the `lock` method will not be able to obtain the `processQueue` and `setLocked(true)`
So it can only be locked by timed tasks (`lockMQPeriodically`)

![image](https://user-images.githubusercontent.com/43363120/173189770-ae8784b7-d086-4d8e-bad1-f6b77ede1a38.png)

**Comment by MatrixHB** [comment]
When executing `if (isOrder && !this.lock(mq))`, the main purpose is to lock the messageQueue in the server-side, `processQueue.setLocked(true);` is secondary.
![image](https://user-images.githubusercontent.com/23614576/173732924-a8bac67e-b1ee-4805-965e-4a39b8a6e27a.png)

**Comment by ni-ze** [comment]
拉取数据前需要rebalance，rebalance之后才能拉取数据,也就是说在拉取消息之前有已经锁定了，调用了processQueue.setLocked(true)方法，在消费数据时自然就不会延迟。这个有延迟的定时任务是周期性去broker端锁定，防止锁定过期

**Comment by BurningCN** [comment]
> 拉取数据前需要rebalance，rebalance之后才能拉取数据,也就是说在拉取消息之前有已经锁定了，调用了processQueue.setLocked(true)方法，在消费数据时自然就不会延迟。这个有延迟的定时任务是周期性去broker端锁定，防止锁定过期

最上面的截图，顺序消费模式，第一次在rebalance的时候会执行`this.lock(mq)`，但是无法置`processQueue.setLocked(true)`，因为取不到`processQueue`（`processQueue`的存入是在`this.lock(mq)`之后的）

**Comment by BurningCN** [comment]
在`rebalance`的时候，`this.lock(mq)`执行之后，`mq`在`broker`是锁定的，但是`processQueue.isLocked`还是`false`，然后接着执行`this.processQueueTable.putIfAbsent(mq,pq);`此时table才有了此entry。

这样定时任务`ConsumeMessageOrderlyService#lockMQPeriodically`再次执行lock的时候才能拿到processQueue（前面的entry）并置为locked。而`lockMQPeriodically`第一次执行是在1s后

**Comment by ni-ze** [comment]
是的，代码的确是这样，processQueueTable中的processQueue.setLocked(true);方法需要等到定时任务才能调用，可以提个pr试试怎么改下看
