### ISSUE TITLE
[Discuss] Resolve the Callback Hell 

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#4458]
The existing codebase contains many callbacks, obscuring overall readability, bringing much overhead to new developers and development maintenance. 

At the language level, Java has provided CompletableFuture, which is so expressive that neat and simplified solutions are possible. Refer to [folly future](https://github.com/facebook/folly/blob/main/folly/docs/Futures.md) and [this blog](https://tech.meituan.com/2022/05/12/principles-and-practices-of-completablefuture.html) to see a potential difference.

Additionally, with future-style of code, sync and async APIs are implemented in a unified way.

Shall RocketMQ progressively refactor callback hell to Future-based styles?

Opinions are welcome.

**Comment by tsunghanjacktsai** [comment]
Second this. As a contributor who recently start to read the code in detail, I often found the original style of callback code is quite annoyed. The usage of CompletableFuture might erase this kind of obscurity to some extent.

**Comment by lizhanhui** [comment]
Dismissed
