### ISSUE TITLE
where is the isOrderTopic used?

### ISSUE THREAD

**Issue by mahaitao617** [apache/rocketmq#4462]
public class TopicPublishInfo {
    private boolean orderTopic = false;
    private boolean haveTopicRouterInfo = false;
    private List<MessageQueue> messageQueueList = new ArrayList<MessageQueue>();
    private volatile ThreadLocalIndex sendWhichQueue = new ThreadLocalIndex();
    private TopicRouteData topicRouteData;

    public boolean isOrderTopic() {
        return orderTopic;
    }

    public void setOrderTopic(boolean orderTopic) {
        this.orderTopic = orderTopic;
    }

**Comment by tsunghanjacktsai** [comment]
Hi @mahaitao617 ,

As far as I know, TopicPublishInfo#isOrderTopic() hasn't been used in the current RocketMQ. However, I suggest we could keep it for a while to ensure that there isn't any usage within the other version and would not affect the future development. But thx for your notice :-)
