### ISSUE TITLE
indexFile flush question

### ISSUE THREAD

**Issue by liuzongliang0202** [apache/rocketmq#4463]
Only when the rocketmq indexfile is full can the disk be flushed. If the indexfile is not full, may the data in the indexfile be lost after normal exit? For example, after rocketmq exits normally, pagcache fails to refresh the disk in time after power failure. (I don't see the Shutdown Logic of rocketmq flush indexfile)

**Comment by liuzongliang0202** [comment]
i think ,This can be modified like as follows
 
`
// class  IndexService
 public void shutdown() {
        if (!indexFileList.isEmpty()) {
            final IndexFile indexFile = indexFileList.get(indexFileList.size() - 1);
            long indexMsgTimestamp = indexFile.getEndTimestamp();
            indexFile.flush();
            this.defaultMessageStore.getStoreCheckpoint().setIndexMsgTimestamp(indexMsgTimestamp);
        }
    }
`

**Comment by liuzongliang0202** [comment]
i think ,This can be modified like as follows

//class IndexService 

 public void shutdown() {
        if (!indexFileList.isEmpty()) {
            final IndexFile indexFile = indexFileList.get(indexFileList.size() - 1);
            long indexMsgTimestamp = indexFile.getEndTimestamp();
            indexFile.flush();
            this.defaultMessageStore.getStoreCheckpoint().setIndexMsgTimestamp(indexMsgTimestamp);
        }
    }

**Comment by liuzongliang0202** [comment]
i think ,This can be modified like as follows

//class IndexService

 public void shutdown() {
        if (!indexFileList.isEmpty()) {
            final IndexFile indexFile = indexFileList.get(indexFileList.size() - 1);
            long indexMsgTimestamp = indexFile.getEndTimestamp();
            indexFile.flush();
            if (indexMsgTimestamp > 0) {
                this.defaultMessageStore.getStoreCheckpoint().setIndexMsgTimestamp(indexMsgTimestamp);
            }
        }
    }

**Comment by liuzongliang0202** [comment]
i think ,This can be modified like as follows

//class IndexService

` public void shutdown() {
        if (!indexFileList.isEmpty()) {
            final IndexFile indexFile = indexFileList.get(indexFileList.size() - 1);
            long indexMsgTimestamp = indexFile.getEndTimestamp();
            indexFile.flush();
            if (indexMsgTimestamp > 0) {
                this.defaultMessageStore.getStoreCheckpoint().setIndexMsgTimestamp(indexMsgTimestamp);
            }
        }
    }`

**Comment by liuzongliang0202** [comment]
i think ,This can be modified like as follows

//class IndexService

    public void shutdown() {
        if (!indexFileList.isEmpty()) {
            final IndexFile indexFile = indexFileList.get(indexFileList.size() - 1);
            long indexMsgTimestamp = indexFile.getEndTimestamp();
            indexFile.flush();
            if (indexMsgTimestamp > 0) {
                this.defaultMessageStore.getStoreCheckpoint().setIndexMsgTimestamp(indexMsgTimestamp);
            }
        }
    }

**Comment by liuzongliang0202** [comment]
i think ,This can be modified like as follows

//class IndexService

    public void shutdown() {
        if (!indexFileList.isEmpty()) {
            final IndexFile indexFile = indexFileList.get(indexFileList.size() - 1);
            long indexMsgTimestamp = 0;
            if (indexFile.isWriteFull()) {
                indexMsgTimestamp = indexFile.getEndTimestamp();
            }
            indexFile.flush();
            if (indexMsgTimestamp > 0) {
                this.defaultMessageStore.getStoreCheckpoint().setIndexMsgTimestamp(indexMsgTimestamp);
            }
        }
    }

**Comment by tsunghanjacktsai** [comment]
Hi @liuzongliang0202 ,

This is a good question. There are two different types of recovery strategies in RocketMQ to deal with the normal and abnormal exit of the broker, respectively. This enables the consistency between the CommitLog and the ConsumeQueue/IndexFile.

According to your problem, which would be determined as an abnormal exit since the broker is down while the dispatching task (handled by ReputMessageService) from CommitLog to IndexFile haven't been completed. An abnormal exit could be judged by whether the abort file created whenever the broker starts exists as it would be removed whenever the broker ends up normally.

After the broker restarts, the loading process of DefaultMessageStore will discover the abort file and execute the corresponding recovery strategy. FYI, the recovery logic is inside the CommigLog#recoverAbnormally().

Welcome to RocketMQ community BTW :-)

**Comment by liuzongliang0202** [comment]
hello @tsunghanjacktsai 
Well, as you said. when the broker is normal exit, the last indexFile has not write full, it can not be flushed by hand, since indexService shutdown method is empty. if abort file is deleted, but indexFile's  bytebuffer pagcache fails to refresh the disk in time after power failure. 
After the broker restarts, the loading process of DefaultMessageStore will normal recover and execute the CommigLog#recoverNormally

**Comment by shy-share** [comment]
so this bug does exists，you can new a pr @liuzongliang0202 ,@tsunghanjacktsai do you think that

**Comment by liuzongliang0202** [comment]
OK, I will new a pr soon. Thank you for your answer

**Comment by liuzongliang0202** [comment]
OK, I will new a pr soon. Thank you for your answer @shy-share

**Comment by tsunghanjacktsai** [comment]
@liuzongliang0202 Have seen your PR now. Sorry for the late response and that I did not understand your problem in the first place. Anyway, appreciate your contribution :-)

**Comment by liuzongliang0202** [comment]
@tsunghanjacktsai  It doesn't matter. Maybe there's something wrong with my expression
