### ISSUE TITLE
Reset consumer offset(s) by the specified offset

### ISSUE THREAD

**Issue by tsunghanjacktsai** [apache/rocketmq#4470]
The issue was inspired by our Chinese developer community. 

For resetting the consumption progress, RocketMQ only provides a single way (MQAdminExt#resetOffsetByTimestamp() & MQAdminExt#resetOffsetByTimestampOld) to update the offset to the specified position.

However, this might be not that precise and convenient sometimes and the developers may need another method such as directly resetting the consumption progress through the specified offset.

**Comment by hzh0425** [comment]
Looking forward to this feature~

**Comment by coder-zzzz** [comment]
https://github.com/apache/rocketmq/issues/2267
same as this one
