### ISSUE TITLE
standard JSON dont compat with go client

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#4471]
https://github.com/apache/rocketmq-client-go/issues/845

**BUG REPORT**

 in https://github.com/apache/rocketmq/pull/4432 , the response of GET_ROUTEINFO_BY_TOPIC is changed, for example, the new format is:
`{"brokerDatas":[{"brokerAddrs":{"0":"127.0.0.1:10911"}]}`
the old is:
`{"brokerDatas":[{"brokerAddrs":{0:"127.0.0.1:10911"}]}`

the following go code in https://github.com/apache/rocketmq-client-go/blob/master/internal/route.go#L561
```
func (routeData *TopicRouteData) decode(data string) error {
	res := gjson.Parse(data)
	err := jsoniter.Unmarshal([]byte(res.Get("queueDatas").String()), &routeData.QueueDataList)

	if err != nil {
		return err
	}

	bds := res.Get("brokerDatas").Array()
	routeData.BrokerDataList = make([]*BrokerData, len(bds))
	for idx, v := range bds {
		bd := &BrokerData{
			BrokerName:      v.Get("brokerName").String(),
			Cluster:         v.Get("cluster").String(),
			BrokerAddresses: make(map[int64]string, 0),
		}
		addrs := v.Get("brokerAddrs").String()
		strs := strings.Split(addrs[1:len(addrs)-1], ",")
		if strs != nil {
			for _, str := range strs {
				i := strings.Index(str, ":")
				if i < 0 {
					continue
				}
				id, _ := strconv.ParseInt(str[0:i], 10, 64)
				bd.BrokerAddresses[id] = strings.Replace(str[i+1:], "\"", "", -1)
			}
		}
		routeData.BrokerDataList[idx] = bd
	}
	return nil
}
```
in `id, _ := strconv.ParseInt(str[0:i], 10, 64)`  , if broker id is 1, then `str[0:i]` is `"\"1\""`, and `strconv.ParseInt("\"1\"")` will always be 0
so the producer will send message to slave.

I have submit a pull request in rocketmq-client-go, https://github.com/apache/rocketmq-client-go/pull/846, but I think we should also be compatable with the old versions of go client.

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by duhenglucky** [comment]
@yuz10 good catch， would you like to submit a PR to temporarily change back to the previous way to ensure compatibility with old clients?

**Comment by lizhanhui** [comment]
The go code posted here is manually parsing strings bit by bit, which itself is error-prone. This is not the supposed way of deserializating JSON

**Comment by yuz10** [comment]
> @yuz10 Should create an issue to the go-sdk, making it compatible with standard JSON. For the ops, upgrade client first then the server. Let name server generate invalid JSON would cause C++ client coredump from time to time.

I have submit an pull request in go sdk, but there is a compatability problem

**Comment by lizhanhui** [comment]
@yuz10 Let's make things work this way
For clients prior to V4_9_3, generate  JSON as before unless its request header explicitly accepts standard JSON only;
For clients released in the future, aka, version >= V4_9_3,  respond with standard JSON

**Comment by dongeforever** [comment]
@yuz10 It is suggested to use the explicit header field "acceptStandardJsonOnly" instead of relying on the version code.
