### ISSUE TITLE
RIP-42 Support Schema Registry

### ISSUE THREAD

**Issue by ferrirW** [apache/rocketmq#4479]
1. Please describe the feature you are requesting.
Schema registry is used to manage schema for all rocketmq topic's. when producer send message with a fixed schema, users no longer need to serialize messages to bytes themselves, instead the new producer with schema will do this job in the background. The process is the same for consumers. So, this feature solves the problem of type-safe and application extension.

2. Provide any additional detail on your proposed use case for this feature.
Detailed proposal refer to: https://shimo.im/docs/Ee32MWDG1WFmKRA2

Welcome any discussion on this proposal.

**Comment by MatrixHB** [comment]
We create a new repo named "rocketmq-schema-registry". Welcome review and comments. 
The pull request is: [RIP 42](https://github.com/apache/rocketmq-schema-registry/pull/1)
