### ISSUE TITLE
Can RocketMQ support KQueue on the mac platform?

### ISSUE THREAD

**Issue by skasj** [apache/rocketmq#4492]
Can KQueue be supported on the mac platform? Looks like only a small amount of code needs to be added:
RemotingUtil.class
![image](https://user-images.githubusercontent.com/37142750/174722281-db45cde0-decb-49e7-b901-8efccf4c7379.png)
![image](https://user-images.githubusercontent.com/37142750/174727951-40290286-2e23-46cf-b109-4d468c432c57.png)

NettyRemotingServer.class
![image](https://user-images.githubusercontent.com/37142750/174722312-8ed908b6-ada2-4d4f-83ea-35cc975c5918.png)
![image](https://user-images.githubusercontent.com/37142750/174722440-fa9206ee-82b0-48ef-9a0a-8c3259a6bc61.png)
![image](https://user-images.githubusercontent.com/37142750/174722698-77ed713b-eb69-45a1-a929-96d8d893a803.png)

**Comment by lizhanhui** [comment]
Of course...Yes. 

Netty created a dedicated transport module for KQueue for BSD-family OS, including FreeBSD and OpenBSD, which still take up markets in the [traffic-intensive nodes](https://papers.freebsd.org/2019/fosdem/looney-netflix_and_freebsd/). 

So, do not confine KQueue to Mac only, expose it to BSD-family, please.

**Comment by skasj** [comment]
@lizhanhui Thank you for your guidance, I will try it out

**Comment by lizhanhui** [comment]
@skasj Your contribution is welcome...Looking forward to your pull request.

**Comment by Oliverwqcwrw** [comment]
I notice the jdk can return appropriate `SelectorProvider` 
such as Mac

> 
public static Selector open() throws IOException {
        return SelectorProvider.provider().openSelector();
    }
provider = sun.nio.ch.DefaultSelectorProvider.create();

public static SelectorProvider create() {
        return new KQueueSelectorProvider();
    }

and window can return WindowsSelectorProvider, so it is necessary whether  to adapt different platform @skasj @lizhanhui
