### ISSUE TITLE
Is there api can get all the tags under the topic

### ISSUE THREAD

**Issue by hyperleoon** [apache/rocketmq#4495]
Is there api can get all the tags under the topic?

**Comment by HScarb** [comment]
Tags are message property, there are no such API.
You can find mqadmin commands here 
https://github.com/apache/rocketmq/blob/develop/docs/cn/operation.md#2-mqadmin%E7%AE%A1%E7%90%86%E5%B7%A5%E5%85%B7

**Comment by cserwen** [comment]
Tags are only stored in messages, there is no global place to store all tags of a topic, so only consumers can specify tags for filtering and consumption
