### ISSUE TITLE
Can support set subscriptionData with ASSIGN SubscriptionType in DefaultLitePullConsumer

### ISSUE THREAD

**Issue by hyperleoon** [apache/rocketmq#4497]
![image](https://user-images.githubusercontent.com/39700308/174957811-40667ade-80a5-4c85-9f26-4a39b38a5ef3.png)

**Comment by ferrirW** [comment]
Current SusscriptionType will be auto set when user call [DefaultLitePullConsumer.assign() ](https://github.com/apache/rocketmq/blob/316d32a006ea49ed806aa965890c917020c426c2/client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java#L269)

does this solve your problem？

**Comment by hyperleoon** [comment]
> Current SusscriptionType will be auto set when user call [DefaultLitePullConsumer.assign() ](https://github.com/apache/rocketmq/blob/316d32a006ea49ed806aa965890c917020c426c2/client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java#L269)
> 
> does this solve your problem？

Our business scenario requires a preview of the five most recent or earliest messages for a certain tag under a certain topic. So I try to use` org.apache.rocketmq.client.consumer.DefaultLitePullConsumer#seekToBegin` and `org.apache.rocketmq.client.consumer. DefaultLitePullConsumer#seek` api , but `seek` doesn't seem to work with `org.apache.rocketmq.client.consumer.LitePullConsumer#subscrib`e, resulting in the inability to customize subExpression. I tried to rewrite `org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl#assign` to support custom subExpressions under ASSIGN SubscriptionType：
![image](https://user-images.githubusercontent.com/39700308/176070098-ae519a08-c16e-4d34-b86e-178a60240775.png)
This seems to work.But I'm not sure if this causes other problems and why it's not natively supported.
