### ISSUE TITLE
Questions about the legal judgment of indexCount

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#4505]
The notation here should be `<=`, because `indexCount` starts counting from 1

![image](https://user-images.githubusercontent.com/43363120/175256359-eb3b5582-c0bc-4a16-a588-b4a8e761ac71.png)

或者我觉得indexCount应该从0计数，如果从1计数的话，可以看到如下代码逻辑，导致少使用了一个IndexEntry的空间
Or I think the indexCount should be counted from 0. If it is counted from 1, you can see the following code logic, resulting in an indexEntry space not being used

![image](https://user-images.githubusercontent.com/43363120/175265540-49e4d4d4-6353-45b6-a900-c78c7b272e76.png)

**Comment by HScarb** [comment]
IMO you're right, `indexCount` should start from 0.
The first index of the file was designed to be a invalid index, but I don't know why.

**Comment by BurningCN** [comment]
多谢，从你的描述我想了下从1计数的原因是这样的。
当`putKey`方法触发，某个`slot`被第一次命中的时候，该`slot`本身的值就是`0`。如果`indexCount`从`0`计数的话，当`this.mappedByteBuffer.getInt(absSlotPos)`返回`0`的时候，无法确认返回的`0`是表示【从来没有过`key`落在该`slot`上】，还是表示【之前已经有一个`indexCount=0`的`indexEntry`落到了该`slot`上】。

Thanks a lot. From your description, I think the reason for counting from 1 is like this.
When the putKey method is triggered and a slot is hit for the first time, the value of the slot itself is 0. If indexCount counts from 0, when this `this.mappedByteBuffer.getInt(absSlotPos)` returns 0, it is not possible to confirm whether the returned 0 means that [no key has ever landed on the slot] or that [an indexEntry with indexCount=0 has previously landed on the slot].
