### ISSUE TITLE
The response code for QUERY_CONSUMER_OFFSET is QUERY_NOT_FOUND instead of PULL_NOT_FOUND

### ISSUE THREAD

**Issue by dongeforever** [apache/rocketmq#4506]
![image](https://user-images.githubusercontent.com/8434428/175257854-cf49a6fa-e42e-4c42-8e60-fd149310243b.png)

This is a typo and a bug.

This BUG only affects the 5.0.0-ALPHA, and only affect the new consumers in some cases.

**Comment by lizhanhui** [comment]
Close as the pull request has been merged.
