### ISSUE TITLE
message trace throws exception

### ISSUE THREAD

**Issue by thezp** [apache/rocketmq#4507]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
1.use DefaultMQPushConsumer as consumer with enableMsgTrace set to true
![image](https://user-images.githubusercontent.com/7849032/175265153-ee20c650-04a7-4316-b3b2-1c4c9df4f1c9.png)
2.set consumeMessageBatchMaxSize to 100
![image](https://user-images.githubusercontent.com/7849032/175265245-c90c7745-8399-456d-b31b-d4ed458045d4.png)
3.pull 1000 msgs at one time
![image](https://user-images.githubusercontent.com/7849032/175265453-0babd88e-ca88-43dc-ae0b-1b9f516033da.png)
- What is expected to see?
the message trace ability is ok
- What did you see instead?
following exxception is thrown
![image](https://user-images.githubusercontent.com/7849032/175265854-accc7508-f77d-4d1e-9935-93dabea8c636.png)
2. Please tell us about your environment:
version:4.9.3
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
in org.apache.rocketmq.client.trace.AsyncTraceDispatcher class the traceProducer's maxMessageSize is set to 118K as following:
![image](https://user-images.githubusercontent.com/7849032/175272245-ffc0616e-1d1f-4dae-b619-7179dedcbb00.png)
and when the flushData method is invoked, sometimes when the buffer is bigger than traceProducer.getMaxMessageSize() it will invoke the producer's send method to send trace message to broker
![image](https://user-images.githubusercontent.com/7849032/175272474-e6832082-65c3-4274-bd81-246ab647119a.png)
and before the producer prepare to send the message it will check the message's size, then the exception will occure

steps to fix it:
1.change the maxMessageSize of traceProducer to 128K
![image](https://user-images.githubusercontent.com/7849032/175268661-6c68d04e-fb02-43a1-a1a9-1adce4bb238e.png)
2.change the lower bound to 118K and leave 10K for the trace message
![image](https://user-images.githubusercontent.com/7849032/175269108-3bdc8747-9ce2-4ef5-adff-515b49f47b86.png)

attached file is the test case of this exception
[DefaultMQConsumerWithTraceBugTest.zip](https://github.com/apache/rocketmq/files/8966004/DefaultMQConsumerWithTraceBugTest.zip)

**Comment by ShannonDing** [comment]
Welcome to create a PR to fix it.

**Comment by PansonPanson** [comment]
it seems that you hava commit and fix  this issue,  you can close this issue.
