### ISSUE TITLE
Question about the semantics of the RemotingCommand flag

### ISSUE THREAD

**Issue by xiaoheng1** [apache/rocketmq#4510]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/12539730/175555877-922e7c4d-8b9e-4896-8a6e-50ac6dff58ae.png">

see https://github.com/apache/rocketmq/blob/master/docs/cn/design.md#22-%E5%8D%8F%E8%AE%AE%E8%AE%BE%E8%AE%A1%E4%B8%8E%E7%BC%96%E8%A7%A3%E7%A0%81

The flag here should contain two meanings, one is to distinguish between oneWay and ordinary RPC, and the other is to distinguish between request and response, so whether the document here needs to be modified？

**Comment by lizhiboo** [comment]
@xiaoheng1 got catch, can u submit a pr to fulfill this?
