### ISSUE TITLE
The reason why RocektMQ stores messages and Kafka stores messages differently

### ISSUE THREAD

**Issue by November22** [apache/rocketmq#4512]
RocketMQ实现消息存储与消费是使用单个rocketmq.log存储所有真实的消息，使用consumequeue来做消息的索引提升消费速度。
  Kafka单个topic使用多个parttion来存储消息，并直接通过parttion消费。
这两种方式在实际的生产者写入以及消费端消费上性能有差异吗？RocektMQ最初这么实现的原因是？
真心求解，期待回复。
----from translate google----
RocketMQ implements message storage and consumption by using a single rocketmq.log to store real messages, and using consumequeue to index messages to improve consumption speed.
A single topic in Kafka uses multiple partitions to store messages and consume them directly through partitions.
Are there differences between the two methods in actual producer writing and consumer consumption?
Sincerely, looking forward to reply.

**Comment by djl394922860** [comment]
rocketmq相比于kafka在非常多的topic场景下有优势，具体性能对比我记得貌似官方有文章解读
