### ISSUE TITLE
Set aclEnable=true in broker.conf, but acl looks like doesn't work

### ISSUE THREAD

**Issue by ChenAllen0305** [apache/rocketmq#4524]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
- edit conf/broker.conf with aclEnable=true
- didn't change conf/acl/plain_acl.yml (just have two accounts : RocketMQ and rocketmq2)
- start broker and specify config file( change the name of broker and it work, I can see the broker name actually changed)
- create producer with RPCHook with account "RocketMQ" and set group value "groupA", and try to send message with topic "topicA"

- What is expected to see?
this producer should be send message unsuccessfully, and report permission error

- What did you see instead?
this producer send message successfully

2. Please tell us about your environment:
rocketmq-4.9.3

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
when check ACL by using getAccessConfigSubCommand, it can give the accounts details:
globalWhiteRemoteAddresses: [10.0.0.*, 192.168.0.*, 10.0.0.*, 192.168.0.*]

accounts:
  accessKey         : RocketMQ
  secretKey         : 12345678
  whiteRemoteAddress:
  admin             : false
  defaultTopicPerm  : DENY
  defaultGroupPerm  : SUB
  topicPerms        : [topicA=DENY, topicB=PUB|SUB, topicC=SUB]
  groupPerms        : [groupA=DENY, groupB=PUB|SUB, groupC=SUB]

  accessKey         : rocketmq2
  secretKey         : 12345678
  whiteRemoteAddress:
  admin             : true
  defaultTopicPerm  :
  defaultGroupPerm  :
  topicPerms        :
  groupPerms        :

**Comment by lizhiboo** [comment]
@ChenAllen0305 maybe globalWhiteRemoteAddress contains your client ip, check defaultAclFile for global white remote address.

**Comment by ChenAllen0305** [comment]
> 

Yes, the globalWhiteRemoteAddress contains my client ip.
I retry with deleting my local client ip in globalWhiteRemoteAddress, and acl works.
So it means the ip address in globalWhiteRemoteAddress doesn't need to check the acl account?

**Comment by caigy** [comment]
> > 
> 
> Yes, the globalWhiteRemoteAddress contains my client ip. I retry with deleting my local client ip in globalWhiteRemoteAddress, and acl works. So it means the ip address in globalWhiteRemoteAddress doesn't need to check the acl account?

@ChenAllen0305 Yes, clients from `globalWhiteRemoteAddress` always pass ACL check. You could find more details [here](https://github.com/apache/rocketmq/blob/develop/docs/cn/acl/user_guide.md).

**Comment by ChenAllen0305** [comment]
> > > 
> > 
> > 
> > Yes, the globalWhiteRemoteAddress contains my client ip. I retry with deleting my local client ip in globalWhiteRemoteAddress, and acl works. So it means the ip address in globalWhiteRemoteAddress doesn't need to check the acl account?
> 
> @ChenAllen0305 Yes, clients from `globalWhiteRemoteAddress` always pass ACL check. You could find more details [here](https://github.com/apache/rocketmq/blob/develop/docs/cn/acl/user_guide.md).

Thanks, I got it.
