### ISSUE TITLE
RocketMQListener generic

### ISSUE THREAD

**Issue by novicate** [apache/rocketmq#4535]
```
abstract class BaseMQ<T> implements RocketMQListener<T> {
}

@RocketMQMessageListener(topic=xxx, consumerGroup=xxx)
class Consumer extends BaseMQ<Entity> {
}
```

I'm going to use the BaseMQ class to provide template methods, but it throws exception:

```
Caused by: java.lang.RuntimeException: parameterType:T of onMessage method is not supported
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.getMethodParameter(DefaultRocketMQListenerContainer.java:499)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.afterPropertiesSet(DefaultRocketMQListenerContainer.java:319)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
```

**Comment by Oliverwqcwrw** [comment]
Hi @novicate ,

there have three advises and hope these can help you
1. abstract class can not be definition to static
2. extend should be extends
3. The Consumer should `Override` onMessage method

 Have a great day!

**Comment by novicate** [comment]
I'm sorry for my poor spelling.
What I'm trying to say is: 
    If I configure like this, my project won't start.

public class BaseRocketMQConsumer<T> implements RocketMQListener<T> {
    @Override
    public void onMessage(T message) {
        beforeConsume();
        doConsume();
        afterConsume();
    }
}

@RocketMQMessageListener(topic=xxx, consumerGroup=xxx)
public class ConsumerA extends BaseRocketMQConsumer<Entity> {
}

**Comment by Oliverwqcwrw** [comment]
Could you please provide more detailed log about application starting?

**Comment by caizhenghao** [comment]
I met this exception too. After I read the code in DefaultRocketMQListenerContainer.getMethodParameter,I think it not a bug but a problem in usage.I change my code and avoid this problem.I hope it can be helpful.

public abstract class AbstractBaseListener<T> implements RocketMQListener<MessageExt> {
    private final Type msgBodyType;

    public AbstractBaseListener() {
        Type typeAbstractListener = this.getClass().getGenericSuperclass();
        Type[] actualTypeArguments = ((ParameterizedType) typeAbstractListener).getActualTypeArguments();
        if (Objects.nonNull(actualTypeArguments) && actualTypeArguments.length > 0) {
            msgBodyType = actualTypeArguments[0];
        } else {
            throw new IllegalStateException("can not explain the object");
        }
    }

    @Override
    public void onMessage(MessageExt messageExt) {
        String bodyStr = new String(messageExt.getBody(), Charset.forName("UTF-8"));
        Object msgBody;
        if (msgBodyType == String.class) {
           msgBody = bodyStr;
        } else {
           msgBody = JSON.parseObject(bodyStr, msgBodyType);
        }
       doConsume((T) msgBody);
  }
}

@RocketMQMessageListener(topic=xxx, consumerGroup=xxx)
public class ConsumerA extends AbstractBaseListener<Entity> {

}

**Comment by QingXSummer** [comment]
I had the same problem。

**Comment by enson16855** [comment]
I had the same problem。
