### ISSUE TITLE
the description of getAclConfig command  is inaccurate

### ISSUE THREAD

**Issue by meateggmilk** [apache/rocketmq#4550]
1. adjust some description
2. remove blank setting to make same as actual setting
![image](https://user-images.githubusercontent.com/87265072/177049000-6dcd84e9-e688-4e44-ace8-f303d4d6853f.png)

**Comment by lizhiboo** [comment]
@meateggmilk IMO, print blank is friendly if this config is not set.

**Comment by Oliverwqcwrw** [comment]
> @meateggmilk IMO, print blank is friendly if this config is not set.

+1

**Comment by caigy** [comment]
> @meateggmilk IMO, print blank is friendly if this config is not set.

+1

**Comment by lizhiboo** [comment]
@meateggmilk thanks for your contribution, i will close this issue, if have any other questions, you can open a new one.
