### ISSUE TITLE
Is the operation here unnecessary?

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#4559]
Is the operation here unnecessary?

![image](https://user-images.githubusercontent.com/43363120/177278769-8b3ae0de-0695-4547-9a51-f59a31cd4fab.png)

**Comment by MatrixHB** [comment]
`logicsMsgTimestamp` will persist to the checkpoint file. When doing `recoverAbnormally`, we will start to recover the last file and get the first message in the last file. If its storage timestamp is less than `min(logicsMsgTimestamp, phyMsgTimestamp)` in the checkpoint, it means that this file needs to be recovered.

**Comment by tsunghanjacktsai** [comment]
Hi @MatrixHB ,

Thx for your explanation. But I believe @HScarb knew the effect of `logicsMsgTimestamp`. I guess he refers to whether the logics of these two statements are necessary. IMO, it only gets the logicsMsgTimestamp from the checkpoint and set the identical thing back to it without any change. It didn't make any sense doing so.

**Comment by BurningCN** [comment]
> Hi @MatrixHB ,
> 
> Thx for your explanation. But I believe @BurningCN knew the effect of `logicsMsgTimestamp`. I guess he refers to whether the logics of these two statements are necessary. IMO, it only gets the logicsMsgTimestamp from the checkpoint and set the identical thing back to it without any change. It didn't make any sense doing so.

Yes, that's what I meant to say

**Comment by MatrixHB** [comment]
> Hi @MatrixHB ,
> 
> Thx for your explanation. But I believe @BurningCN knew the effect of `logicsMsgTimestamp`. I guess he refers to whether the logics of these two statements are necessary. IMO, it only gets the logicsMsgTimestamp from the checkpoint and set the identical thing back to it without any change. It didn't make any sense doing so.

Thanks, I got it. What actually makes sense is in` ConsumeQueue#putMessagePositionInfoWrapper`
