### ISSUE TITLE
When did rocketmq support PHP

### ISSUE THREAD

**Issue by CrazyZard** [apache/rocketmq#456]
When will PHP extensions be available

**Comment by duhengforever** [comment]
@ShannonDing

**Comment by vongosling** [comment]
PHP is a special language, if rocketmq support, we must consider using the muti-thread lib in php. So, IMO, It would be a long journey for the language, any contributor would like to contribute?

**Comment by ShannonDing** [comment]
Please referring https://github.com/apache/rocketmq-externals/tree/master/rocketmq-client-php
