### ISSUE TITLE
How many queues can a topic have

### ISSUE THREAD

**Issue by 418545106** [apache/rocketmq#4564]
请问一下在使用到rocketmq的分区顺序消费时，1个topic下能够拥有最多多少queue，有官方推荐的最大queue数量或者最优数量吗，假设现在需要1w以上或者10w的queue会导致异常吗？

**Comment by lizhiboo** [comment]
@418545106 use mqadmin updatetopic command create default 8 queues. IMO, set too large is meaningless.

**Comment by 418545106** [comment]
> @418545106 use mqadmin updatetopic command create default 8 queues. IMO, set too large is meaningless.

in IoT case, i need send command to device, for example i have a thousand devices , commands between devices are asynchronous, at the same time commands within a device are synchronous, how can i achieve this. my first idea is use Partitioned message ordering one device has own queue.
CN: 在物联网的例子中，假如有1千台设备，设备之间的命令是异步下发的，但是单台设备的命令又是同步的，此时想到的实现方法就是使用分区顺序消费的方法，topic下建立每台设备所属的queue.

**Comment by hill007299** [comment]
物联网场景可以考虑使用 MQTT (https://github.com/apache/rocketmq/wiki/RIP-33-RocketMQ-MQTT)，轻量队列参考这个 [LMQ](https://github.com/apache/rocketmq/wiki/RIP-28-Light-message-queue-(LMQ)) 后续我们也会推出RocketMQ的百万级队列存储引擎。

IoT scenarios can consider using [MQTT,](https://github.com/apache/rocketmq-mqtt)  and we will also launch million-level queue storage engine for RocketMQ in the future
