### ISSUE TITLE
no auth module producer/consumer when connect to broker

### ISSUE THREAD

**Issue by yixinwei** [apache/rocketmq#457]
hi， commiters,
when i view rocketmq docs and search around web, i  found that there is no auth when NEW producer or consumer to brokers, how could i protect my production environment(providing internet ip access), just with firewall?

**Comment by duhengforever** [comment]
@yixinwei This feature has been request in the [issue](https://github.com/apache/rocketmq/issues/403), and we are so glad to see some of your suggestions, designs and even pull a request.
