### ISSUE TITLE
Use docker to start RocketMq

### ISSUE THREAD

**Issue by Cocowwy** [apache/rocketmq#4570]
When I use 
`$ docker run -it --net=host --mount source=/tmp/store,target=/home/rocketmq/store apache/rocketmq ./mqbroker -n localhost:9876`. 
to start Broker

Will report an error：
`docker: Error response from daemon: create /tmp/store: "/tmp/store" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path`

**Comment by caigy** [comment]
The following command works. Maybe you could refer to documents of docker for more information.
`docker run -it --net=host --mount type=bind,source=/tmp/,target=/home/rocketmq/store apache/rocketmq ./mqbroker`

**Comment by ltamber** [comment]
the `source` argument should be a `volume` name default, unless you specified the `type` argument

**Comment by OneCodeMonkey** [comment]
Directly use `-v ` param will be fine:
`docker run -it --net=host -v /tmp/store:/home/rocketmq/store --name=rocketmqBroker apache/rocketmq ./mqbroker -n localhost:9876`
