### ISSUE TITLE
Call equals() to compare different types

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#4579]
**BUG REPORT**

1. Please describe the issue you observed:

In `org.apache.rocketmq.acl.plain.PlainPermissionManager#updateAccessConfig`

> 
for (Map.Entry<String, PlainAccessResource> entry : accountMap.entrySet()) {
                    if (entry.getValue().equals(plainAccessConfig.getAccessKey())) {
                        PlainAccessResource plainAccessResource = buildPlainAccessResource(plainAccessConfig);
                        accountMap.put(entry.getKey(), plainAccessResource);
                        break;
                    }
                }

- What did you do (The steps to reproduce)?

- What is expected to see?

compare same types

- What did you see instead?

3. Please tell us about your environment:

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by lizhiboo** [comment]
@Oliverwqcwrw good catch!
