### ISSUE TITLE
Maybe it can put same MessageQueue

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#4581]
**BUG REPORT**

1. Please describe the issue you observed:

In `org.apache.rocketmq.broker.transaction.queue.TransactionalMessageServiceImpl#getOpQueue`

> private MessageQueue getOpQueue(MessageQueue messageQueue) {
        MessageQueue opQueue = opQueueMap.get(messageQueue);
        if (opQueue == null) {
            opQueue = new MessageQueue(TransactionalMessageUtil.buildOpTopic(), messageQueue.getBrokerName(),
                messageQueue.getQueueId());
            opQueueMap.putIfAbsent(messageQueue, opQueue);
        }
        return opQueue;

    }

When multiple threads execute getOpQueue() concurrently, maybe it can put same MessageQueue

- What did you do (The steps to reproduce)?

- What is expected to see?

- What did you see instead?

3. Please tell us about your environment:

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by lizhiboo** [comment]
@Oliverwqcwrw It seems that TransactionalMessageServiceImpl.check() is only called by TransactionalMessageCheckService, and TransactionalMessageCheckService is a scheduled task. Maybe no need to concern concurrency problem.

**Comment by Oliverwqcwrw** [comment]
Thanks for your reply,
Agree with, it do not need to concern about concurrency problem now,  But we can avoid some unpredictable problems if we have multithreaded calls in the future
