### ISSUE TITLE
[Task] fulfill PlainPermissionManager test case

### ISSUE THREAD

**Issue by lizhiboo** [apache/rocketmq#4585]
Currently, some methods in PlainPermissionManager do not have the corresponding test case in PlainPermissionManagerTest. such as
createAclAccessConfigMap, updateAclConfigFileVersion, updateGlobalWhiteAddrsConfig, deleteAccessConfig.
Does anyone want to fulfill it?

**Comment by ShahRishi** [comment]
Hi! I would love to help out for this. This is my first time working on an open source project. Is there a reference I can consult for building these test cases?

**Comment by lizhiboo** [comment]
> Hi! I would love to help out for this. This is my first time working on an open source project. Is there a reference I can consult for building these test cases?

Great, u can refer PlainPermissionManagerTest, it already contains some test case, and u can just add these test case in PlainPermissionManagerTest.

**Comment by lizhiboo** [comment]
@ShahRishi https://rocketmq.apache.org/docs/pull-request/
this article maybe helpful.

**Comment by ShahRishi** [comment]
Thank you!

**Comment by ShahRishi** [comment]
Sorry, this is a bit advanced for me. I think it will be better if someone else does this task, ask I'm not making too much progress.
