### ISSUE TITLE
Can rocketmq thread pool add a "bottom-up" scheme to catch exceptions

### ISSUE THREAD

**Issue by liuzongliang0202** [apache/rocketmq#4587]
In BrokerController#initialize(), it will create many business thread pools. can we add "bottom-up" scheme to catch exceptions for business thread pools?

for example, class 'org.apache.rocketmq.common.ThreadFactoryImpl'

    @Override
    public Thread newThread(Runnable r) {
        Thread thread = new Thread(r, threadNamePrefix + this.threadIndex.incrementAndGet());
        thread.setDaemon(daemon);
        thread.setUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            @Override
            public void uncaughtException(Thread t, Throwable e) {
                log.error("Uncaught exception in thread '" + t.getName() + "':", e);
            }
        });
        return thread;
    }

**Comment by lizhiboo** [comment]
@liuzongliang0202 Good catch! Do u willing to submit a pr to make it perfect?
