### ISSUE TITLE
Only when the force method call is successful , that can the flushedPosition be updated

### ISSUE THREAD

**Issue by Inuyasha-Monster** [apache/rocketmq#4588]
### 1、Please describe the issue you observed:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/12888788/178465277-23dee3ad-b9b8-44a2-9064-a116d1483da1.png">

### 2、Please tell us about your environment:
branch：develop
### 3、Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
as title , If it's a problem, I'll fix it ....etc

**Comment by djl394922860** [comment]
I thought about it again, maybe I'm wrong, because the next time the force method call is successful, the flushedPosition will be updated normally...
