### ISSUE TITLE
Upgrading RocketMQ version without downtime

### ISSUE THREAD

**Issue by jothipandiyanjp** [apache/rocketmq#459]
We are running Rocketmq cluster in production.
I need to upgrade RocketMQ version from 4.2.0 to 4.3.0 without Rocketmq cluster downtime. 
Is this achievable?? If so please share any links related to version migration so that I can follow it...

**Comment by Hellojungle** [comment]
It will be better to ask with a email after subscribe mailing lists; https://rocketmq.apache.org/about/contact/

**Comment by vongosling** [comment]
@jothipandiyanjp Sorry, we could not provide the similar manual as you said. RocketMQ has complete backward compatibility. So, you could do it as you update your broker from 4.x to 4.2.0. Any problem please let me know, and hope to see your sound in the user email list. This is not a correct place for your question :-)
