### ISSUE TITLE
About the url of released zip file, and it's folder structure after unzip it.

### ISSUE THREAD

**Issue by huanwei** [apache/rocketmq#460]
I'm working on the Dockerfile for new RocketMQ release 4.3.0 and 4.3.1. But I found two issues:

## 1)About the url of released zip file
Before release 4.3.1, we can get the released zip file via:
```
https://dist.apache.org/repos/dist/release/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip
```
But I was not able to get release for 4.3.1:
```
https://dist.apache.org/repos/dist/release/rocketmq/4.3.1/rocketmq-all-4.3.1-bin-release.zip
```
```
Not Found

The requested URL /repos/dist/release/rocketmq/4.3.1/rocketmq-all-4.3.1-bin-release.zip was not found on this server.
```

## 2)About it's folder structure after unzip it
Before release 4.3.1, the zip file name is `rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip`, for release 4.3.1, the zip file becomes `rocketmq-rocketmq-all-4.3.1.zip`, I found the folder structure also different with releases 4.3.0 and 4.2.0, after unzip them.

These two issues will make confuse for a long-term Dockerfile maintenance. So can we `solid` the release url and filename, and the files structure? I mean at least to make them keep the same since release 4.2.0.

**Comment by duhengforever** [comment]
@huanwei Hi，we haven‘t released RocketMQ 4.3.1 and the file name just named as you want, as you can see:
![image](https://user-images.githubusercontent.com/39583243/45357583-3d04a980-b5f9-11e8-8050-54d235bb719c.png)
