### ISSUE TITLE
Out of memory: Kill process 

### ISSUE THREAD

**Issue by running-ball** [apache/rocketmq#4604]
OS：3.10.0-1127.el7.x86_64 CentOS Linux release 7.8.2003 (Core)
8C 16G  
swapoff 
rocketmq version:V4_3_1
2 master 2slave async mode
check /var/log/message
error:Jul 13 15:55:12 rocketmq-3 kernel: Out of memory: Kill process 2395 (java) score 908 or sacrifice child
![image](https://user-images.githubusercontent.com/24563036/178888519-d83afa61-3909-4fea-ad0d-f55909c516f5.png)

![image](https://user-images.githubusercontent.com/24563036/178888714-ef6f776f-87a6-4734-b32f-219d19fea03c.png)

**Comment by running-ball** [comment]
![image](https://user-images.githubusercontent.com/24563036/178910606-4fde1805-2201-41c0-8c0b-d382ab1618e6.png)
see....again a again

**Comment by running-ball** [comment]
![image](https://user-images.githubusercontent.com/24563036/178910736-eb203817-dc87-43dd-84b6-62a249722cd7.png)
console

**Comment by lizhiboo** [comment]
@running-ball IMO, machine memory is insufficient, so linux core killed it. Have a try to set rocketmq-3's broker memory to 4g.
