### ISSUE TITLE
Trace for LitePullConsumer may not work correctly

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq#4606]
**BUG REPORT**

1. Please describe the issue you observed:
Trace message are built when PullTaskImpl finishes executing.
https://github.com/apache/rocketmq/blob/b136f9bb6725867dcc5d00798addd0de7382ffb3/client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java#L952
But in fact the message is only stored in the local cache, and only when `poll()` is called, the user's program will actually consume the messages, so I think the traces message should be built in `poll()`
https://github.com/apache/rocketmq/blob/b136f9bb6725867dcc5d00798addd0de7382ffb3/client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java#L542
Will there be any problem with the implementation here? @zhangjidi2016

**Comment by zhangjidi2016** [comment]
Good catch，Could you submit a PR to solve this issue？

**Comment by cserwen** [comment]
> Good catch，Could you submit a PR to solve this issue？

@zhangjidi2016  Ok, I will fix it.
