### ISSUE TITLE
Purge filterserv related code in client

### ISSUE THREAD

**Issue by duhengforever** [apache/rocketmq#461]
**BUG REPORT**

1. Please describe the issue you observed:

-Since RocketMQ has been removed filterserv module, so related code in client should be purged to avoid user confusion

2. Please tell us about your environment:
-4.3.x

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Purge filterserv related code in client

**Comment by RongtongJin** [comment]
In addition to purging related code in client, you also need to purge the code in example module including [org.apache.rocketmq.example.filter.Consumer/Producer](https://github.com/apache/rocketmq/blob/edf97032e4cba0f593f46a212f7a06899a220a9c/example/src/main/java/org/apache/rocketmq/example/filter/Consumer.java#L30), which is more likely to mislead users.
