### ISSUE TITLE
What is the real usefulness of TopicConfig#isOrder?

### ISSUE THREAD

**Issue by BurningCN** [apache/rocketmq#4614]
The only thing I found to use at the moment is the following, can someone explain? thanks.
At the same time I have some doubts about the real usefulness of `TopicConfig#topicSysFlag`

![image](https://user-images.githubusercontent.com/43363120/179175966-f5359e21-3a41-468d-a498-3b1f5618472e.png)
![image](https://user-images.githubusercontent.com/43363120/179176620-450fdfd9-bdae-4bba-a095-928e2c4dd015.png)

**Comment by tsunghanjacktsai** [comment]
Hi @BurningCN ,

Well, this is definitely an interesting thing to discuss. There were some questions from the community about the usage of ordered topics in RocketMQ these days as well. IMO, these kinds of variables, including the topicSysFlag as you pointed out, that are not really utilized in the code of RocketMQ, are mostly used as signs in some cases.

For instance, I'd like to build an e-commerce order system and need to create a bunch of topics. Some of the topics would need the ordered messages as the info of an order needs to be under the identical topic. To satisfy such kinds of scenarios, those topics would be marked as “ordered” and supplied with sharding keys. In this case, the "isOrder" variable would come into play.

But this is just my two cents, I sometimes would also be confused with those kinds of variables that did not have the actual effect in the codebase. You're also welcome to give your opinions as well.

**Comment by BurningCN** [comment]
> 

thank you very much
