### ISSUE TITLE
No route info of this topic

### ISSUE THREAD

**Issue by zhangzhefang-github** [apache/rocketmq#463]
com.alibaba.rocketmq.client.exception.MQClientException: No route info of this topic, TopicA
See https://github.com/alibaba/RocketMQ/issues/44 for further details.

https://github.com/alibaba/RocketMQ/issues/44  is not exsit!!

**Comment by Richard-biz** [comment]
Hi There.
      We are  using the RocketMq 4.2.0 version, Using "IKVM" we are converted the jar to dll and we are Using in C# ,Now As per your Update am upgrading to 4.2.0 to 4.3.1 using the same methodology in "IKVM" , But This time i am facing issue , Same as its in Above mention issue,May i  know how to Solve this issue  and could you tell me this issue from Jar dependency or Some other RocketMQ Issue.
And while conversion time we are noted some of the class not found error in "IKVM" for your Reference i attached the Screen Shot of it, have a Look once and Let me know.(IKVM version-ikvmbin-8.1.5717.0)
![image](https://user-images.githubusercontent.com/20609857/45816245-aa4ec380-bcf8-11e8-883c-ebdb050c8aa5.png)

**Comment by ShannonDing** [comment]
close issue due to old version.
