### ISSUE TITLE
Fields in a "MessageExtBatch" class should either be transient or serializable

### ISSUE THREAD

**Issue by Hellojungle** [apache/rocketmq#464]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
None
- What did you expect to see?
MessageExtBatch is implements of Serializable, but the ByteBuffer encodedBuff is not serializable
- What did you see instead?
None
2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
common/src/main/java/org/apache/rocketmq/common/message/MessageExtBatch.java

**Comment by dongeforever** [comment]
It seems have no defect.
Could you give some tests to show how this problem will affect the results.
