### ISSUE TITLE
MQClientInstance 中为什么 consumerTable 的key设置成 group ，而不是topic + group ? 

### ISSUE THREAD

**Issue by gongchangyou** [apache/rocketmq#4656]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:
![image](https://user-images.githubusercontent.com/2409053/180220959-c4dc6f07-ef52-420b-a736-68a4a589af65.png)
当我给两个 topic设置相同 的group时 ，抛异常 
Caused by The consumer group[group] has been created before, specify another name please

而我的本意不是要使用同一个consumer ，消费两个topic. 单纯就是写错group了。

 想咨询一下 设计的想法，为什么 MQClientInstance 中的consumerTable 的key是group， 而不是 topic+group. 这样就能区分 不同的topic + 相同的group了，对应的是两个不同的consumer。

- What did you do (The steps to reproduce)?

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by cserwen** [comment]
> 想咨询一下 设计的想法，为什么 MQClientInstance 中的consumerTable 的key是group， 而不是 topic+group. 这样就能区分 不同的topic + 相同的group了，对应的是两个不同的consumer。

事实上，一个消费组的所有实例应该订阅相同的Topic，如果不同实例订阅的Topic不相同，服务端保存的订阅关系会被频繁修改，会导致消费实例消费到其他Topic的消息。正确的方法应该是使用不同的消费组去订阅不同的Topic。

In fact, all instances of a consumer group should subscribe to the same topic. If the topics subscribed by different instances are different, the subscription relationship saved by the server will be frequently modified, which will cause the consumer instance to consume messages from other topics. The correct way should be to use different consumer groups to subscribe to different topics.

**Comment by gongchangyou** [comment]
我大概可以猜到 broker中的 游标 是根据group来标记的。 那如果设计成 根据 topic +group 来标记，是否连 订阅关系一致原则也不用提了。因为不同的topic +相同group的 consumer 本身就是不同组，自然不会共享游标了。
