### ISSUE TITLE
[Docs]DLedger quick start document optimize

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#4673]
As following:
![image](https://user-images.githubusercontent.com/15797831/180593994-45c749fe-9bb6-45e8-91bb-340b65a3bc95.png)
openmessaging-storage-dledger project was renamed dledger. so command shoud modify and avoid misunderstandings. 
```shell
git clone https://github.com/openmessaging/dledger.git

cd dledger

mvn clean install -DskipTests
```
doc path : https://github.com/apache/rocketmq/blob/develop/docs/cn/dledger/quick_start.md

**Comment by RongtongJin** [comment]
@mxsm Good catch! Could you submit a pull request to fix the issue?

**Comment by mxsm** [comment]
> @mxsm Good catch! Could you submit a pull request to fix the issue?

I will submit a pull request to fix the issue
