### ISSUE TITLE
why not use ConcurentHashMap in class RouteInfoManager?

### ISSUE THREAD

**Issue by PansonPanson** [apache/rocketmq#4676]
I'm confused if there are some performance and  safety consideration 
![image](https://user-images.githubusercontent.com/16064908/180608918-51b77080-b2a1-40bc-a52a-a79c3abf49dc.png)

**Comment by PansonPanson** [comment]
It seems has been optimized in  5.0 beta.

**Comment by PansonPanson** [comment]
It seems that this code snippet was optimized in 5.0 beta.

**Comment by hill007299** [comment]
RocketMQ 5.0 has been optimized for this
