### ISSUE TITLE
Potential NPE

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#4682]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

In `org.apache.rocketmq.namesrv.routeinfo.RouteInfoManager#registerBroker(java.lang.String, java.lang.String, java.lang.String, long, java.lang.String, java.lang.Long, java.lang.Boolean, org.apache.rocketmq.common.protocol.body.TopicConfigSerializeWrapper, java.util.List<java.lang.String>, io.netty.channel.Channel)`

> 
     boolean isOldVersionBroker = enableActingMaster == null;
     brokerData.setEnableActingMaster(!isOldVersionBroker && enableActingMaster);

if `enableActingMaster` is null, `!isOldVersionBroker && enableActingMaster` will cause NPE

- What is expected to see?

It can not cause  NPE

- What did you see instead?

It will cause NPE when `enableActingMaster` is null

2. Please tell us about your environment:

develop

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by RongtongJin** [comment]
@Oliverwqcwrw Good catch!
