### ISSUE TITLE
Avoiding multiple resizing by replacing iterative put with putAll .

### ISSUE THREAD

**Issue by PansonPanson** [apache/rocketmq#4685]
![image](https://user-images.githubusercontent.com/16064908/180655638-aa30de50-3696-49bc-809a-4c8587fb86e3.png)

**Comment by Oliverwqcwrw** [comment]
IMO, This constructor seems does not appear to be called concurrently

**Comment by PansonPanson** [comment]
> IMO, This constructor seems does not appear to be called concurrently

remove redundant code or fix it
