### ISSUE TITLE
NamesrvStartup code optimize

### ISSUE THREAD

**Issue by zhangleiouc** [apache/rocketmq#4705]
![image](https://user-images.githubusercontent.com/6259525/181410911-f3327a38-7f73-4f8d-bc52-22718d8ddde1.png)
![image](https://user-images.githubusercontent.com/6259525/181411057-d5c76d17-8f52-4281-afbb-04e54220fdae.png)
NamesrvStartup.nettyServerConfig use default port 9876,why  the class NettyServerConfig filed listenPort default value is 8888.
can change the  filed listenPort default value to 9876 and there does't need to execute nettyServerConfig.setListenPort(9876)  in NamesrvStartup.parseCommandlineAndConfigFile

**Comment by xhrg** [comment]
Nettyserverconfig is used not only for namesrv, but also for brokers
