### ISSUE TITLE
MQ broker start may cost many time because of recover consumer queue file 

### ISSUE THREAD

**Issue by Ah39** [apache/rocketmq#472]
**FEATURE REQUEST**

 if have the broker have many consumerqueue , recover  consume queue from file may  cost many time.
For example A Broker have thousands of consumerqueue file.

**Comment by wlliqipeng** [comment]
Recovery time does have much to do with the number of files. If it's a minute level, it should be normal.
If you have usual questions, please go to the mailing list，next time.

**Comment by Ah39** [comment]
ok , thanks

**Comment by vongosling** [comment]
I will appreciate @Ah39 engagement in the community if you could raise your question in the user email list. Issue is not the correct place for your request, please read the issue template, looking forward to your question in the email list :-)
