### ISSUE TITLE
Transaction message delayed

### ISSUE THREAD

**Issue by viktorzhong** [apache/rocketmq#474]
I'm trying the transaction example on the website, the executeLocalTransaction method returns COMMIT_MESSAGE every time. 
```java
    @Override
    public LocalTransactionState executeLocalTransaction(Message msg, Object arg) {
        return LocalTransactionState.COMMIT_MESSAGE;
    }
```
The issue is the messages are delayed about 30s(on broker), I'm using 4.3.1 and 2m2s.
Is there any tip about this?

**Comment by duhengforever** [comment]
This indeed a bug, but it has been fixed in the master/develop branch of
Apache/rocketmq repo, but we have't update maven repository, you can
checkout source code and build it, or use the old version 4.3.0 instead.

viktorzhong <notifications@github.com> 于2018年9月23日周日 下午9:44写道：
