### ISSUE TITLE
ReplicasManager constructor has redundant code

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#4741]
![image](https://user-images.githubusercontent.com/15797831/182022545-1d5bb2c3-2b49-4a46-a0f6-419435571b8b.png)
```java
 final BrokerConfig brokerConfig = brokerController.getBrokerConfig();
```
as shown above code can be removed.

**Comment by RongtongJin** [comment]
@mxsm Good catch! Go ahead.
