### ISSUE TITLE
DLedgerController create DLedgerServer not check controllerDLegerPeers and controllerDLegerSelfId result in throw NullPointerException

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#4745]
When start Controller，only set ROCKETMQ_HOME, as following pictrue:
![image](https://user-images.githubusercontent.com/15797831/182029187-18848db8-74b1-4d83-aeaf-76a2d05c9b53.png)
then project throws a  **java.lang.NullPointerException** :
![image](https://user-images.githubusercontent.com/15797831/182029248-be16da60-a0f2-4ff1-b4a6-c6eb27f282f9.png)
why? Because ControllerConfig class attribute **controllerDLegerPeers**  is null, but this attribute cannot be null. in ControllerConfig class has three attributes:

- controllerDLegerGroup
- controllerDLegerPeers
- controllerDLegerSelfId
if not config in file,  they will be null. when we create DLedgerServer controllerDLegerPeers and controllerDLegerSelfId  must have a value. so when we create DLedgerServer  must check.
![image](https://user-images.githubusercontent.com/15797831/182029743-fa0230e0-6b9f-495a-b189-3cd4672791e7.png)

**Comment by RongtongJin** [comment]
@mxsm Could you help optimize this issue?

**Comment by mxsm** [comment]
> @mxsm Could you help optimize this issue?

I will submit a PR  optimize this issue
