### ISSUE TITLE
ControllerConfig.enableControllerInNamesrv attribute should move to NamesrvConfig

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#4748]
![image](https://user-images.githubusercontent.com/15797831/182032110-cc25b6bb-b572-4575-835f-c6686b3474a5.png)
Controller as a plugin, Whether it can be embedded in container Namesrv depends on the container. instead of depends on controller plugin。 So ControllerConfig.enableControllerInNamesrv attribute should move to NamesrvConfig

**Comment by RongtongJin** [comment]
@mxsm Good idea! Just do it!

**Comment by mxsm** [comment]
> @mxsm Good idea! Just do it!

I will submit a PR to do it
