### ISSUE TITLE
After producer shutdown, can't callback checkLocalTransaction method.What should I do in production?

### ISSUE THREAD

**Issue by wangweifan** [apache/rocketmq#475]
---------------------------------producer ---------------------------------------------
@Test
    public void sendTransactionMQ() throws MQClientException, UnsupportedEncodingException, InterruptedException {
        TransactionListener transactionListener = new TransactionListenerImpl();
        TransactionMQProducer producer = new TransactionMQProducer(TRANSACTION_MQ_PRODUCER_GROUP_NAME);
        ExecutorService executorService = new ThreadPoolExecutor(2, 5, 100, TimeUnit.SECONDS, new ArrayBlockingQueue<Runnable>(2000), new ThreadFactory() {
            @Override
            public Thread newThread(Runnable r) {
                Thread thread = new Thread(r);
                thread.setName("client-transaction-msg-check-thread");
                return thread;
            }
        });
        producer.setNamesrvAddr("127.0.0.1:9876");
        producer.setExecutorService(executorService);
        producer.setTransactionListener(transactionListener);
        producer.start();
        Message msg = new Message("testMq", "TagA", "KEYi", ("Hello RocketMQ ").getBytes(RemotingHelper.DEFAULT_CHARSET));
        SendResult sendResult = producer.sendMessageInTransaction(msg, null);
        System.out.printf("%s%n", sendResult);
        producer.shutdown();
    }
---------------------------------producer ---------------------------------------------

------------------------------------------consumer--------------------------------------------
public static void main(String[] args) throws InterruptedException, MQClientException {

        //设置消费者组名
        DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("transaction_mq_consumer");
        //设置Consumer第一次启动是从队列头部开始消费还是队列尾部开始消费<br>
        consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_FIRST_OFFSET);
        //指定nameServer的地址
        consumer.setNamesrvAddr("127.0.0.1:9876");
        //指定订阅的topic及tag表达式
        consumer.subscribe("testMq", "*");

        consumer.registerMessageListener(new MessageListenerConcurrently() {
            @Override
            public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                                                            ConsumeConcurrentlyContext context) {
                for (MessageExt msg : msgs) {
                    System.out.println(String.format("Custome2 message [%s],tagName[%s]",
                            new String(msg.getBody()),
                            msg.getTags()));
                }
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
                //return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            }
        });
        //启动消费者实例
        consumer.start();
        System.out.println("Consumer Started.");
    }
------------------------------------------consumer--------------------------------------------

**Comment by wangweifan** [comment]
After producer shutdown, don't callback checkLocalTransaction method.What should I do in production?

**Comment by duhengforever** [comment]
@wangweifan In production, a cluster with same producerGroup is recommended, when a producer shutdown, broker will check for other surviving producers with the same producerGroup，and if there are no any surviving producers, broker will continue check after producer startup, so you need to be idempotent on both the producer side and the consumer side.

**Comment by duhengforever** [comment]
And the issue is used for bug report or feature request，If you are just asking for help,  you can use the mailing lists：https://rocketmq.apache.org/about/contact/
