### ISSUE TITLE
The 1005 lines in DefaultMQProducerImpl  not return localTransactionState !!!!!!

### ISSUE THREAD

**Issue by wangweifan** [apache/rocketmq#476]
LocalTransactionState localTransactionState = LocalTransactionState.UNKNOW;
            Throwable localException = null;
            switch(sendResult.getSendStatus()) {
            case SEND_OK:
                try {
                    if (sendResult.getTransactionId() != null) {
                        msg.putUserProperty("__transactionId__", sendResult.getTransactionId());
                    }

                    String transactionId = msg.getProperty("UNIQ_KEY");
                    if (null != transactionId && !"".equals(transactionId)) {
                        msg.setTransactionId(transactionId);
                    }

                    if (null != localTransactionExecuter) {
                        localTransactionState = localTransactionExecuter.executeLocalTransactionBranch(msg, arg);
                    } else if (transactionListener != null) {
                        this.log.debug("Used new transaction API");
                        transactionListener.executeLocalTransaction(msg, arg);
                    }

                    if (null == localTransactionState) {
                        localTransactionState = LocalTransactionState.UNKNOW;
                    }

                    if (localTransactionState != LocalTransactionState.COMMIT_MESSAGE) {
                        this.log.info("executeLocalTransactionBranch return {}", localTransactionState);
                        this.log.info(msg.toString());
                    }
                } catch (Throwable var10) {
                    this.log.info("executeLocalTransactionBranch exception", var10);
                    this.log.info(msg.toString());
                    localException = var10;
                }
                break;
            case FLUSH_DISK_TIMEOUT:
            case FLUSH_SLAVE_TIMEOUT:
            case SLAVE_NOT_AVAILABLE:
                localTransactionState = LocalTransactionState.ROLLBACK_MESSAGE;
            }

            try {
                this.endTransaction(sendResult, localTransactionState, localException);
            } catch (Exception var9) {
                this.log.warn("local transaction execute " + localTransactionState + ", but end broker transaction failed", var9);
            }

**Comment by duhengforever** [comment]
@wangweifan this bug has been resolved in this [PR](https://github.com/apache/rocketmq/pull/450), you can download source code and build in your environment.

**Comment by vongosling** [comment]
@duhengforever Could help to assign the concrete version of the pr that you have merged?
