### ISSUE TITLE
No error message is logged in catch block

### ISSUE THREAD

**Issue by zyx333** [apache/rocketmq#4766]
It's better to print error message here for the convenience of debugging.

https://github.com/apache/rocketmq/blob/0d1eec2b9ca5ac8e19190e96cb29d7191d14dbe5/store/src/main/java/org/apache/rocketmq/store/CommitLog.java#L533-L537

**Comment by zyx333** [comment]
#4767 solved in this PR

**Comment by RongtongJin** [comment]
There is no need to print logs here, because rocketmq master-slave replication is is based on streams rather than messages , so it is common to dispatch half messages. If you print logs here, there will be a lot of dirty logs.

**Comment by zyx333** [comment]
get it.
