### ISSUE TITLE
多条事务消息,最后一次提交

### ISSUE THREAD

**Issue by breakenknife** [apache/rocketmq#477]
最近在整合db事务和rocketmq, 一个db事务中可能会发送多条事务消息(prepare)并写表,想在提交db完后,再顺序提交mq.  如果mq提交失败,则依赖回查.
最近看到4.3.1的事务消息demo,都是基于一条消息的, 请问如何在发送多条事务消息之后,一次提交?

**Comment by duhengforever** [comment]
@breakenknife 你好，可以自己把本地事务包装为一条事务消息，本地管理多个分支事务的一致性，事务消息暂时对多分支事务没有支持。另外，如果有问题烦请订阅邮件列表:https://rocketmq.apache.org/about/contact/ ,issue 用来做bug report或者是feature request.
另外推荐暂时使用4.3.0版本的客户端，4.3.1版本稍有问题，我们后续发布新版本解决该问题。

**Comment by lanjiexin** [comment]
@duhengforever 目前Rocketmq支持多分支事务了吗？或者你这边有什么推荐吗关于此场景？谢谢！
