### ISSUE TITLE
MappedFile fileFromOffset Assignment error

### ISSUE THREAD

**Issue by ycy1991** [apache/rocketmq#4773]
**BUG REPORT**

1. Please describe the issue you observed:
NumberFormatException
![image](https://user-images.githubusercontent.com/16506338/182754021-3c656574-91bd-459c-92c9-fe29cc28d20f.png)
- What is expected to see?
I think when initializing a file, the initial offset should be zero
- What did you see instead?

**Comment by panzhi33** [comment]
The initial offset is 0, what's the problem? org.apache.rocketmq.common.UtilAll#offset2FileName

**Comment by ycy1991** [comment]
- OK, I see. I didn't read the complete code
