### ISSUE TITLE
delay offset becomes negative after topic is re-created

### ISSUE THREAD

**Issue by freedom-Li** [apache/rocketmq#4774]
version：4.7

View the offset consumption through the console as follows：
![image](https://user-images.githubusercontent.com/2167809/182780725-cddecf1a-a31f-4cd8-b879-59eb8a382be1.png)

storeerr.log:
![image](https://user-images.githubusercontent.com/2167809/182781173-bea07842-ccff-4bf1-bbe7-d5be64b268ab.png)

After deleting the topic and rebuilding for a period of time, the above scenario will be reproduced, and the master node has not been down.  Please advise what may be the cause of this problem.

**Comment by RongtongJin** [comment]
In version 4.x, after the topic is deleted, the metadata of consumer offset will not be deleted, which may be the reason why the offset is negative.

**Comment by freedom-Li** [comment]
> In version 4.x, after the topic is deleted, the metadata of consumer offset will not be deleted, which may be why the offset is negative.

I have tried deleting all client rocketmq folders and clearing all data on the broker node, and found that after running for a while, the offset value will be negative, and there is a probability that a very small negative value will appear.

**Comment by freedom-Li** [comment]
If the offset is negative, some data will not be consumed normally. What is the solution to this situation?

**Comment by lizhanhui** [comment]
@freedom-Li Could you provide the exact operational steps performed?  RocketMQ uses an eventual-consistency strategy when managing resources to achieve better performance.  Specific and detailed operation steps are necessary for a reliable analysis.

**Comment by freedom-Li** [comment]
> @freedom-Li Could you provide the exact operational steps performed? RocketMQ uses an eventual-consistency strategy when managing resources to achieve better performance. Specific and detailed operation steps are necessary for a reliable analysis.

1. Pause all java applications (nodes involving mq operations)
2. Pause all mq nodes (including namserver), console
3. Delete the rocketmq store directory, rocketmqlogs directory, and data directory (specified by the storePathRootDir property)
4. Delete all rocketmq directories in the consumer
5. Restart the rocketmq node and start the console
6. Log in to the console, rely on the add/update button in the topic menu item, and manually create a topic, as shown in the following figure:
![1660120530293](https://user-images.githubusercontent.com/2167809/183856345-cd4ffb0f-602b-4abe-9ba7-2c10624d68fe.jpg)

7. After creating all topics in turn, start all applications.
8. Manually test a small amount of data to send and consume offsets are normal. A few days after the business is put into use normally, when the production and consumption of a topic increases to 5-6 times the daily amount, one or more broker consumption queues will have negative offset values.
