### ISSUE TITLE
Query messages based on start time and end time

### ISSUE THREAD

**Issue by xhrg** [apache/rocketmq#4777]
https://github.com/apache/rocketmq-dashboard

https://github.com/apache/rocketmq-dashboard/blob/master/src/main/java/org/apache/rocketmq/dashboard/service/impl/MessageServiceImpl.java#L256

Link above

According to the time query message, the classes used are @deprecated，Is there any elegant way to query message according to time

如上链接，rocketmq-dashboard项目中根据时间查询消息，使用的api都是@deprecated，请问有比较优雅的方式，可以根据开始，结束时间查询消息吗

**Comment by xhrg** [comment]
I did some research. It seems that defaultlitepullconsumer can

我大概看了下，好像 DefaultLitePullConsumer.java 类可以做到该功能

**Comment by duhenglucky** [comment]
@xhrg 推荐直接使用Admin客户端，而不是使用Consumer中使用的相关的admin 的API :)
