### ISSUE TITLE
Client deserializes server return ElectMasterResponseHeader, ElectMasterResponseHeader attribute value of brokerMemberGroup is null

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#4794]
**BUG REPORT**

1. Please describe the issue you observed:

when I send CONTROLLER_ELECT_MASTER to controller, then controller process is complete and return RemotingCommand 
![image](https://user-images.githubusercontent.com/15797831/183280806-c7117c4a-6e22-4b7f-9f6e-84de4baac700.png)
ElectMasterResponseHeader brokerMemberGroup attribute is not null. but Client get response and ElectMasterResponseHeader,  brokerMemberGroup attribute  is null  after deserialization
![image](https://user-images.githubusercontent.com/15797831/183280980-8a5934d0-83f7-4421-ac6a-b832494a2361.png)

- What is expected to see?

I'm expected to see brokerMemberGroup is not null

- What did you see instead?

in fact I see ElectMasterResponseHeader attribute brokerMemberGroup is null after deserialization

2. Please tell us about your environment:

branch: develop

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

CommandCustomHeader have custom attribute  like: ElectMasterResponseHeader attribute brokerMemberGroup that instacne of BrokerMemberGroup, Not a Java-defined type like Long, String and so on. the basic type.
Why does this happen? when server need return the response the CommandCustomHeader's attributes will be put into a map, name as map key, and attribute value as map value. the CommandCustomHeader   is not serialized
![image](https://user-images.githubusercontent.com/15797831/183281602-0fc21d48-a620-4d72-9eb4-90a53233d70a.png)

- Question
RemotingCommand CustomHeader is not support custom type serialization? if so why?

**Comment by RongtongJin** [comment]
If you want to get the brokerMemberGroup, I suggest putting the contents in the body like the registerBroker or getReplicainfo API.

**Comment by mxsm** [comment]
> Hi @mxsm If you want to get the brokerMemberGroup, I suggest putting the contents in the body like the registerBroker or getReplicainfo API.

Good Idea
