### ISSUE TITLE
The brokerRole is always SYNC_MASTER when enableControllerMode=true

### ISSUE THREAD

**Issue by steven-wal** [apache/rocketmq#4799]
Hi community, I have a question, but I can't find the place to ask. it's possible  with `GitHub Discussions`?
The question is: when with `enableControllerMode`, the brokerRole property(ASYNC_MASTER or SYNC_MASTER) in broker's conf, it's not working anymore?
https://github.com/apache/rocketmq/blob/ce274265db8af73e28624ecc1fc98cc984658844/broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java#L186
As shown above, The master always SYNC_MASTER.

**Comment by RongtongJin** [comment]
> Hi community, I have a question, but I can't find the place to ask. it's possible with `GitHub Discussions`? The question is: when with `enableControllerMode`, the brokerRole property(ASYNC_MASTER or SYNC_MASTER) in broker's conf, it's not working anymore?
> 
> https://github.com/apache/rocketmq/blob/ce274265db8af73e28624ecc1fc98cc984658844/broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java#L186
> 
> 
> As shown above, The master always SYNC_MASTER.

Yes, when enableControllerMode = true, the master role will be fixed to SYNC_MASTER, and follow the replica management mechanism of SyncStateSet. For details, please refer to https://shimo.im/docs/N2A1Mz9QZltQZoAD#anchor-04gE

**Comment by steven-wal** [comment]
I will read the RIP more details. Respect your patient answers.

**Comment by runnningbean** [comment]
how can i set brokerRole=ASYNC_MASTER
