### ISSUE TITLE
Should need change broker role immediately when broker inactive?

### ISSUE THREAD

**Issue by Stevenzall** [apache/rocketmq#4800]
In a distributed environment, the network partitions always sad. If the master broker register to 3 nameserver nodes, sometimes it has a network partion probelm with the leader namesrv, but send heartbeat  normally with other namesrv nodes. In such cases, we need change broker role immediately? Or should we check the broker status on other namesrvs?
https://github.com/apache/rocketmq/blob/ce274265db8af73e28624ecc1fc98cc984658844/controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java#L106

**Comment by RongtongJin** [comment]
@Stevenzall This is a good issue, How to solve the unnecessary handover jitter under the asymmetric network partition. In the current implementation, the broker role will be changed immediately if network partition occurs between the master broker and the leader controller. Do you are interested in proposing a more detailed plan to solve this problem?

**Comment by Stevenzall** [comment]
@RongtongJin I'm just starting to get familiar with the project. If I have a good idea, i will give a little proposing, really happy contributting to community.

**Comment by lizhanhui** [comment]
This looks like an already well-defined case in terms of Paxos, Raft, and other well-known consensus algorithms.

**Comment by TheR1sing3un** [comment]
IMO, in this case: 

- three nameSrvs with controller mode
  - controller-master
  - controller-follower-1
  - controller-follower-2
- three master/slave mode brokers
  - broker-master
  - broker-slave1
  - broker-slave2

occurs network partition like this:
![image](https://user-images.githubusercontent.com/87409330/184607149-71c6f6b1-723b-48ca-8918-c72c7eeeb30b.png)

In this case, broker-master can't connect to controller-master becasue of the network partition. But it stay in same partition with brokers and controller-follower1 and controller-follower2. So when the controller-master find that broker-master is inavtive. It will propose an ElectMasterEvent, however the controller-master also can't connet to his followers, so controller-master fali to append this event by dledger(raft). So in this case, the master in brokers will not change!

**Comment by lizhimins** [comment]
It is recommended to use raft for service discovery due to it enforces a stronger degree of coherency to reduce the number of states that must be considered.
