### ISSUE TITLE
DefaultLitePullConsumerImpl cannot continue to use the seek method after customizing the MessageQueueListener

### ISSUE THREAD

**Issue by sunxiaojian** [apache/rocketmq#4805]
RocketMQ verison ： 4.7.0 

1.  The seek method in DefaultLitePullConsumerImpl defaults to the rebrance method. However, if I want to customize the MessageQueueListener, it seems that I cannot use the seek method. The subscription partition in AssignedMessageQueue cannot be reset because the AssignedMessageQueue variable in DefaultLitePullConsumerImpl is not public. Can you consider adding a method to get this information? When customizing MessageQueueListener, you can continue to use the seek method

default MessageQueueListener :
![image](https://user-images.githubusercontent.com/6446530/183816174-addb39f5-e22f-4f8a-a0e6-a1d38f39b411.png)
seek method :
![image](https://user-images.githubusercontent.com/6446530/183816293-c74be012-8d41-479c-bf4a-203d2b64d689.png)

2.  Now setMessageQueueListener must be overwritten after the subscribe method, otherwise it will be overwritten by default, which is easy to cause confusion
  
![image](https://user-images.githubusercontent.com/6446530/183816777-70a87022-5d9f-4a84-9681-2140950d3a61.png)

**Comment by RongtongJin** [comment]
Hi @sunxiaojian You can add a public method to get the AssignedMessageQueue.

**Comment by sunxiaojian** [comment]
> Hi @sunxiaojian You can add a public method to get the AssignedMessageQueue.

OK

Another question is whether an interface can be added to submit the offset specified by the MessageQueue
Let DefaultLitePullConsumerImpl.updateConsumeOffset is open in DefaultLitePullConsumer

![image](https://user-images.githubusercontent.com/6446530/184275110-c386b2c7-2e58-4592-951f-c4a5a217d4e7.png)

**Comment by ni-ze** [comment]
> Member

Maybe DefaultLitePullConsumer.commit(final Set<MessageQueue> messageQueues, boolean persist)  can meet your needs.

**Comment by sunxiaojian** [comment]
> > Member
> 
> Maybe DefaultLitePullConsumer.commit(final Set messageQueues, boolean persist) can meet your needs.

DefaultLitePullConsumer.commit can't specify offset.  I provided PR for support. Can you review it?
https://github.com/apache/rocketmq/pull/4820
