### ISSUE TITLE
there may be a bug in pop consumer mode.

### ISSUE THREAD

**Issue by fujian-zfj** [apache/rocketmq#4806]
BUG REPORT

There may be another problem in HA mode, when we put ck or ack message to store, SLAVE_NOT_AVAILABLE and FLUSH_SLAVE_TIMEOUT are considered to be successfully synchronized to slave.
![image](https://user-images.githubusercontent.com/10379042/183844097-b5798df4-9692-4c62-b21b-5ff33e553648.png)

**Comment by RongtongJin** [comment]
@fujian-zfj Good catch! Only PUT_ OK is real write success when we put CK or ACK into the store in pop mode.

**Comment by guyinyou** [comment]
niubility!

**Comment by lizhimins** [comment]
mark
