### ISSUE TITLE
Broker Controller Deploy change IP,admin CLI getSyncStateSet  info Is not correct

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#4808]
**BUG REPORT**

1. Please describe the issue you observed:

Start Namesrv(Controller as plugin-IP：192.168.3.21), then register broker：
![1](https://user-images.githubusercontent.com/15797831/183942071-1a20019d-bec7-4f18-a0ce-e94da6caa91a.jpg)
```shell
sh bin/mqadmin getSyncStateSet -a 192.168.3.21:9878 -b mxsm
```
the result is ok. then shutdown broker. and change broker deployed host ip
![image](https://user-images.githubusercontent.com/15797831/183942871-79d2b685-a670-46df-9b6d-c18fc8739866.png)

```shell
sh bin/mqadmin getSyncStateSet -a 192.168.3.21:9878 -b mxsm
```
![image](https://user-images.githubusercontent.com/15797831/183943001-510396dc-3d9e-4738-aec1-9bb5eeb7a082.png)
The result does not correspond to the reality
- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:
environment: develop branch
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by RongtongJin** [comment]
Hi @mxsm, this is a known issue. The current controller uses IP as the unique identity of the broker, which causes this problem. Now, @hzh0425  has started to solve this issue. We can review this PR together. #4672

**Comment by mxsm** [comment]
> Hi @mxsm, this is a known issue. The current controller uses IP as the unique identity of the broker, which causes this problem. Now, @hzh0425 has started to solve this issue. We can review this PR together. #4672

OK
