### ISSUE TITLE
how to set user property “CHECK_IMMUNITY_TIME_IN_SECONDS” 

### ISSUE THREAD

**Issue by naah69** [apache/rocketmq#481]
[transaction in rocketMQ document](http://rocketmq.apache.org/docs/transaction-example/)
In the Usage Constraint of this article,it mentions `CHECK_IMMUNITY_TIME_IN_SECONDS`.
but i can't find the method to set user property in TransactionMQProducer and DefaultMQProducer.

**Comment by naah69** [comment]
## BUG
1. `PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS` is not available.
2. `transactionMsgTimeout` is not available.

i use `PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS` in java  and `transactionMsgTimeout` in broker.conf ;

PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS:
![image](https://user-images.githubusercontent.com/25682169/46240480-c62e2580-c3da-11e8-9da7-e525da5e6d04.png)

broker.conf: 
![image](https://user-images.githubusercontent.com/25682169/46240486-e1009a00-c3da-11e8-8755-414ccbffd5d8.png)

console.log:
![image](https://user-images.githubusercontent.com/25682169/46240500-2b821680-c3db-11e8-859d-9a5f1cf6c84e.png)

**Comment by duhengforever** [comment]
@naah69 thanks for your partition, all transactional message check interval all limited by "transactionCheckInterval" parameter of broker, and this value default is 60 seconds,  you can set this parameter to a suitable value .

**Comment by ymwneu** [comment]
As @duhengforever says, param "transactionCheckInterval" controls transactional message check interval. "PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS" or "transactionTimeout"(not "transactionMsgTimeout", document mistake) determines the period when half message first sent to first check localTransaction.

**Comment by vongosling** [comment]
I would like to appreciate your @naah69 engagement in the community if you could raise your question in the user email list. Issue is not the correct place for your request, please read the issue template, looking forward to your question in the email list :-)
