### ISSUE TITLE
word spell check

### ISSUE THREAD

**Issue by fujian-zfj** [apache/rocketmq#4810]
There are several typos in code.
Like TIMER_WHELL_TTL_DAY in class TimerMessageStore.

**Comment by meateggmilk** [comment]
why oldest code revert this change?

**Comment by lizhanhui** [comment]
@meateggmilk Because it is changing from one typo to another.

**Comment by lizhanhui** [comment]
Read this reference to see parlance should be used:  http://www.cs.columbia.edu/~nahum/w6998/papers/sosp87-timing-wheels.pdf
