### ISSUE TITLE
Failover questions when the client sends asynchronously

### ISSUE THREAD

**Issue by zhaowenshuai011** [apache/rocketmq#4812]
rocketmq-client：4.9.4

<img width="997" alt="WechatIMG99" src="https://user-images.githubusercontent.com/41977714/184309356-02619d06-5c25-49d6-b6c9-e0b2d6e15eee.png">

Personal opinion, when the exception is caught and failover, the timeout needs to be reset, otherwise, if the first request times out, the subsequent failover logic will not be executed, is it more reasonable? On this premise, the request timeout, setSendLatencyFaultEnable and setRetryTimesWhenSendAsyncFailed parameters will make sense.

**Comment by lizhanhui** [comment]
The current timeout brings about a lot of questions,  Let's fix it in a new way.
