### ISSUE TITLE
Optimize the elect policy in HAControler mode

### ISSUE THREAD

**Issue by TheR1sing3un** [apache/rocketmq#4813]
1. Now we just randomly(the first one in syncStateSet) elect a master when the controller proposes an ElectMaster event.
2. We can design an interface to elect the master, and we can execute our own strategy like a plugin.
3. We provide a default elect policy to elect master.
    - We add more inforamtion in haertbeat packet, such as maxOffset, epoch and confitmOffset.
    - We elect a master in syncStateSet first, and we prefer the candidate with higher epoch or higher maxOffset(when the epoch is equal).
    - If the enableElectUnCleanMaster == true, we can elect a master in all replicas when we elect nothing from syncStateSet. We elect a master(also with higher epoch and maxOffset) from all replicas.

**Comment by RongtongJin** [comment]
Merged
