### ISSUE TITLE
Why not get data from commitLog in batches when checking transaction messages?

### ISSUE THREAD

**Issue by RapperCL** [apache/rocketmq#4827]
When the transaction message is checked back, why not get data from commitLog in batches, but only get one piece at a time for processing, and then get another one for processing
![image](https://user-images.githubusercontent.com/44110731/184792055-11752595-31d8-4711-b385-7e34610ea74f.png)
![image](https://user-images.githubusercontent.com/44110731/184792072-d4f78110-4825-47cd-8620-73d6e0c8bd35.png)

**Comment by hill007299** [comment]
For most transaction messages, they are in the committed state and will be found in the remove map。 Only a small number of transaction messages in the prepare（half） state will go to this logic（get half msg and check back）, and the check back of transaction messages itself is carried out one by one. If batch check back is used, the code logic will become very complicated

**Comment by RapperCL** [comment]
> For most transaction messages, they are in the committed state and will be found in the remove map。 Only a small number of transaction messages in the prepare（half） state will go to this logic（get half msg and check back）, and the check back of transaction messages itself is carried out one by one. If batch check back is used, the code logic will become very complicated

Yes, but I think we can actually get it in batches and iteratively check

**Comment by hill007299** [comment]
If in doubt, consider reopening it and continuing the conversation
