### ISSUE TITLE
How to set the message load balance consumption in RocketMQ with more than one client?

### ISSUE THREAD

**Issue by PEIYANGXINQU** [apache/rocketmq#4828]
There are two Rocket MQ clients, both of which belong to the same consumption group. How to set the message load balance consumption? It seems that one client has more consumption messages and the other has less, and the consumption is uneven.

**Comment by lizhanhui** [comment]
Consumers of the same consumer group are expected to have exactly the same subscriptions, aka, the same set of topics with the same filter expressions. 

Now we are having two major clients 4.x and 5.x.
For 4.x, load-balancing is conducted at the granularity of **message-queue**. For FIFO messages where messages are published to queues of their choice, it would be possible that some queues have more messages than others. As a result, some consumer clients are more loaded than others. Note, non-FIFO messages may also go through a queue-selector when publishing, skew in load is also possible. Use consumerProgress command in the admin toolset to inspect if this is the case.

For [5.x](https://github.com/apache/rocketmq-clients), load-balancing is done at a finer granularity, aka loads are averaged at the message-group tier(for standard messages, each one is a distinct message group, conceptually). You are expecting to have very fair loads among all consumer clients regardless of the publishing approach.

**Comment by PEIYANGXINQU** [comment]
收到，谢谢！

**Comment by lizhanhui** [comment]
@PEIYANGXINQU I would close this issue as your concern should have been clarified. Feel free to re-open it if you had follow-up ones.
