### ISSUE TITLE
Suggestion of commit0 method in MappedFile

### ISSUE THREAD

**Issue by maoyiyong-svg** [apache/rocketmq#4829]
在org.apache.rocketmq.store.MappedFile#commit0中使用“this.fileChannel.write(byteBuffer);”导致没有利用文件内存映射机制，导致写入效率降低。
原因：
在MappedFile对象实例化的时候就会实例化fileChannel和MappedByteBuffer，完成之后在finally中可以直接关闭fileChannel，之后的数据读写应该使用MappedByteBuffer，通过文件内存映射来操作。
![image](https://user-images.githubusercontent.com/62745186/185017246-044241e1-5703-434b-a8e8-5946d66af6ae.png)
此处建议使用mappedByteBuffer进行数据写入。
![image](https://user-images.githubusercontent.com/62745186/185020982-007dbe10-ad61-45e3-99e7-670b93aef5e4.png)

**Comment by RongtongJin** [comment]
@maoyiyong-svg 你好，MappedFile commit方法是在transientStorePoolEnable开启后使用的，其作用时将消息数据从RocketMQ自己管理的堆外内存写入到文件中（后面再由flush线程刷到磁盘），所以代码中出现了writeBuffer中的数据写到fileChannel中，实际上当开启transientStorePoolEnable后，写消息数据都是先写入到writeBuffer而非到内存映射的mappedByteBuffer（若不开启transientStorePoolEnable则是直接写到内存映射文件中）。
