### ISSUE TITLE
consumeMessageDirectly时没有把UserProperty的内容发送过去

### ISSUE THREAD

**Issue by yufeng629** [apache/rocketmq#483]
当调用AdminBrokerProcessor的consumeMessageDirectly方法时，并没有把生产者端在发送消息时设置在UserProperty的内容一起转发给消费者

**Comment by duhengforever** [comment]
@yufeng629 麻烦描述一下场景，这个api，一般用于指定消费，可以用sh bin/mqadmin queryMsgById -i 以及sh bin/mqadmin queryMsgById -i xx -g xx -d xx来查看区别，另外，如果有问题请订阅我们的邮件列表，在里面提问就好了: https://rocketmq.apache.org/about/contact/

**Comment by yufeng629** [comment]
就是在发送消息的时候我通过 message.putUserProperty("myProperty", "1000"); 设置了一个值，然后调用AdminBrokerProcessor的consumeMessageDirectly这个方法的时候是成功通知到了消费者，但是消费者那边通过message.getUserProperty("myProperty")来取值的时候返回了一个NULL值
