### ISSUE TITLE
mqadmin consumeProgress got 'N/A' in ClientIP column when using DefaultLitePullConsumer(java)

### ISSUE THREAD

**Issue by kelly6** [apache/rocketmq#4830]
**BUG REPORT**

1. Please describe the issue you observed:

- start a DefaultLitePullConsumer same as the example using subscribe mode.
- run cmd `mqadmin consumeProgress -g ... -n ... -s true`

-  expect to see '192.168.x.x@.....' in ClientIP column

- I got 'N/A' which DefaultPushConsumer is fine.

2. Please tell us about your environment:
    broker version: 4.9.4
    client version: 4.9.4

3. I'm not sure what's going wrong, liteConsumer.getClientIP() getInstanceName() is correct. what should I set to get this work?

**Comment by francisoliverlee** [comment]
as i know, DefaultLitePullConsumer doest report its client to broker
and DefaultPushConsumer does. [here is a doc for your consideration](https://mp.weixin.qq.com/s?__biz=Mzg4NDUzMzcwMQ==&mid=2247483946&idx=1&sn=d55e6ce58e597fcb1dcf3bd7477c8a66)

**Comment by YangJodie** [comment]
> **BUG REPORT**
> 
> 1. Please describe the issue you observed:
> 
> * start a DefaultLitePullConsumer same as the example using subscribe mode.
> * run cmd `mqadmin consumeProgress -g ... -n ... -s true`
> * expect to see '192.168.x.x@.....' in ClientIP column
> * I got 'N/A' which DefaultPushConsumer is fine.
> 
> 2. Please tell us about your environment:
>    broker version: 4.9.4
>    client version: 4.9.4
> 3. I'm not sure what's going wrong, liteConsumer.getClientIP() getInstanceName() is correct. what should I set to get this work?

DefaultLitePullConsumer/DefaultPullConsumer implement only the functionality necessary for pull message. Consumer managment like offset query or direct push is not available.

**Comment by kelly6** [comment]
Thanks for your reply.  According to the article

**Comment by kelly6** [comment]
Thanks for your reply.

**Comment by kelly6** [comment]
Thanks for your reply.

According to the article _DefaultMQPushConsumer_ implemented its own _ConsumerRunningInfo_.
I'm wondaring is there an easy way to override _ConsumerRunningInfo_ for _DefaultMQPullConsumer_ ?
