### ISSUE TITLE
Exception in Windows Environment

### ISSUE THREAD

**Issue by a-tony** [apache/rocketmq#4831]
版本：4.9.4
启动nameserver和broker后，发了不超过10条消息，报错，这也太不稳定太不靠谱了吧，磁盘日志文件也删了，还是报错，而且我的磁盘空间很大，还有几百G的空间，为什么报这个错？这不是乱报错么
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL:  0.91 CQ:  0.91 INDEX: -1.00], messages are put to the slave, message store has been shut down, etc. BROKER: 192.168.142.1:10911
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/

**Comment by RongtongJin** [comment]
> the broker's disk is full



> 版本：4.9.4 启动nameserver和broker后，发了不超过10条消息，报错，这也太不稳定太不靠谱了吧，磁盘日志文件也删了，还是报错，而且我的磁盘空间很大，还有几百G的空间，为什么报这个错？这不是乱报错么 Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 14 DESC: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL: 0.91 CQ: 0.91 INDEX: -1.00], messages are put to the slave, message store has been shut down, etc. BROKER: 192.168.142.1:10911 For more information, please visit the url, http://rocketmq.apache.org/docs/faq/

你好，从报错日志上看，Commitlog和ConsumeQueue的所在磁盘占用超过了91%，此时根据RocketMQ内部保护机制会对MessageStore禁写，默认RocketMQ数据存储在{user.home}/store目录下，或者根据storePathRootDir的配置进行存储，你可以查看该目录下的磁盘空间。
