### ISSUE TITLE
Some Junit test failed when use windows system

### ISSUE THREAD

**Issue by coder-zzzz** [apache/rocketmq#4833]
some junit test is based on linux file system, but failed when use windows.

If they need to be fixed? 

![image](https://user-images.githubusercontent.com/62043001/185084117-4f0f6655-713f-42a7-b6e0-0d5ab1bfe508.png)

**Comment by lizhanhui** [comment]
Resources should be loaded using ClassLoader, instead of concatenating paths manually.

**Comment by vongosling** [comment]
Use the Path and Paths classes, or use the JUnit TemporaryFolder class to create a test fixture that is automatically set up and torn down. @coder-zzzz would you like to try pr for this improvement?

**Comment by coder-zzzz** [comment]
@vongosling ok

**Comment by lizhanhui** [comment]
@coder-zzzz  We are also in the process of making existing test cases hermetic. If you want to fix these flaky tests on Windows, ensure the following guidelines are also followed: https://bazel.build/reference/test-encyclopedia#test-interaction-filesystem
