### ISSUE TITLE
Add a cli command to transfer leadership in controllers

### ISSUE THREAD

**Issue by TheR1sing3un** [apache/rocketmq#4835]
1.Add a cli command to transfer leadership in controllers.
2.This command can transfer leadership when the cluster occurs the asymmetric network partition, to avoid unnecessary master replacement.(situation like this : https://github.com/apache/rocketmq/issues/4800, we can transfer the leadership)
3.More flexible to deal the problem about controller~

**Comment by TheR1sing3un** [comment]
If this issue is necessary, please assign it to me~

**Comment by TheR1sing3un** [comment]
> Hi @TheR1sing3un, It seems that the function of #4798 is duplicated.

It seems like they are different, one is a command to elect master in brokers, another is a commadn to transfer leadership in controllers(controllers is a raft cluster)

**Comment by TheR1sing3un** [comment]
> 



> > Hi @TheR1sing3un, It seems that the function of #4798 is duplicated.
> 
> It seems like they are different, one is a command to elect master in brokers, another is a commadn to transfer leadership in controllers(controllers is a raft cluster)

I want to add this command to transfer leadership from controller-master to its controller-follower(based on the leadertransfer feature in dledger)

**Comment by RongtongJin** [comment]
> > 
> 
> > > Hi @TheR1sing3un, It seems that the function of #4798 is duplicated.
> > 
> > 
> > It seems like they are different, one is a command to elect master in brokers, another is a commadn to transfer leadership in controllers(controllers is a raft cluster)
> 
> I want to add this command to transfer leadership from controller-master to its controller-follower(based on the leadertransfer feature in dledger)

Could you explain the usage scenario again? It would be better to have a example.

**Comment by TheR1sing3un** [comment]
![WechatIMG16](https://user-images.githubusercontent.com/87409330/185161030-c9f04154-4471-4e8a-b2c8-c958441bc0cd.jpeg)
backgroud: 
- in asymmetric network partition,
- controller-leader can connect to other controller-followers
- all brokers can connect to two controller-follower, but can't connect to controller-leader
- because the network in controllers is normal, so the controller-leader is always leader
- because none of brokers can send hearbeat to controller-master, so the master can't elect any new master in brokers
- so now the cluster lose the HA

**Comment by RongtongJin** [comment]
> > > > 
> > > 
> > > 
> > > > > Hi @TheR1sing3un, It seems that the function of #4798 is duplicated.
> > > > 
> > > > 
> > > > It seems like they are different, one is a command to elect master in brokers, another is a commadn to transfer leadership in controllers(controllers is a raft cluster)
> > > 
> > > 
> > > I want to add this command to transfer leadership from controller-master to its controller-follower(based on the leadertransfer feature in dledger)
> > 
> > 
> > Could you explain the usage scenario again? It would be better to have an example.
> 
> In this case, this command may be helpful. ![WechatIMG16](https://user-images.githubusercontent.com/87409330/185161030-c9f04154-4471-4e8a-b2c8-c958441bc0cd.jpeg) backgroud:
> 
> * in asymmetric network partition,
> * controller-leader can connect to other controller-followers
> * all brokers can connect to two controller-follower, but can't connect to controller-leader
> * because the network in controllers is normal, so the controller-leader is always leader
> * because none of brokers can send hearbeat to controller-master, so the controller-leader can't elect any new master in brokers
> * so now the cluster lose the HA

In this case, it seems that it would be better to go offline the controller-leader directly.

**Comment by TheR1sing3un** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > > Hi @TheR1sing3un, It seems that the function of #4798 is duplicated.
> > > > > 
> > > > > 
> > > > > It seems like they are different, one is a command to elect master in brokers, another is a commadn to transfer leadership in controllers(controllers is a raft cluster)
> > > > 
> > > > 
> > > > I want to add this command to transfer leadership from controller-master to its controller-follower(based on the leadertransfer feature in dledger)
> > > 
> > > 
> > > Could you explain the usage scenario again? It would be better to have an example.
> > 
> > In this case, this command may be helpful. ![WechatIMG16](https://user-images.githubusercontent.com/87409330/185161030-c9f04154-4471-4e8a-b2c8-c958441bc0cd.jpeg) backgroud:
> > 
> > * in asymmetric network partition,
> > * controller-leader can connect to other controller-followers
> > * all brokers can connect to two controller-follower, but can't connect to controller-leader
> > * because the network in controllers is normal, so the controller-leader is always leader
> > * because none of brokers can send hearbeat to controller-master, so the controller-leader can't elect any new master in brokers
> > * so now the cluster lose the HA
> 
> In this case, it seems that it would be better to go offline the controller-leader directly.

yep！I get it！
