### ISSUE TITLE
No route info of this topic, TopicTest

### ISSUE THREAD

**Issue by nickevin** [apache/rocketmq#484]
- OS: macOS High Sierra
- version: 4.3.1, and run command
    - nohup sh bin/mqnamesrv &
    - nohup sh bin/mqbroker -n localhost:9876 autoCreateTopicEnable=true &
- just copy code [Send Messages Asynchronously example](https://rocketmq.apache.org/docs/simple-example/) to IDE
- run and throws **No route info of this topic, TopicTest**
- I have already create topic: TopicTest, see [snaphost](https://i.loli.net/2018/10/01/5bb21f01005b2.png)

**Comment by nickevin** [comment]
I have changed the version **4.3.1** to **4.2.0** will be OK. What is wrong with the latest version.

```
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client</artifactId>
    <version>4.2.0</version>
</dependency>
```

**Comment by duhengforever** [comment]
@nickevin it has no relation with client version, and this pr will give your answer: https://github.com/apache/rocketmq/pull/479

**Comment by nickevin** [comment]
@duhengforever  I appreciate it.
