### ISSUE TITLE
The request method of DefaultMQProducerImpl in version 4.9.4 cannot receive the response data.

### ISSUE THREAD

**Issue by zd46319** [apache/rocketmq#4841]
After upgrading to version 4.9.4, I found that when I called the _**request(Message msg,long timeout)**_ method, I received the requested msg data instead of the response data.
I debugged the code and found that in version 4.9.3, the assignment of the response is in the processReplyMessage method of the ClientRemotingProcessor, and the value is the msg of the response.
However, in version 4.9.4, the assignment of the response is done in the SendCallback method, and the value is **the msg of the request**.

I found the corresponding commit: https://github.com/apache/rocketmq/commit/1f71c39c54f6414900e571babe5f5f579ed08078#diff-1f24d88a472681b751458795afb485cdb91b45e6621e214bbee0848d1d888bfb
,and not sure if this processing logic is correct

**Comment by RongtongJin** [comment]
@zd46319 IMO, it is indeed a bug. Hi, @li-xiao-shuang Could you explain the reason for the revision?

**Comment by RongtongJin** [comment]
@zd46319 Could you submit a pull request to fix the issue？
