### ISSUE TITLE
Add consumer type check when call consumeMessageDirectly

### ISSUE THREAD

**Issue by YangJodie** [apache/rocketmq#4858]
**Description：**
consumeMessageDirectly method should check the consumer type because this method only works in push consumer type.

**Detailed changes:**

1. Add check for QueryMsgByUniqueKeySubCommand and QueryMsgByIdSubCommand.
2. Add type checking when call the org.apache.rocketmq.client.impl.factory.MQClientInstance#consumeMessageDirectly.

**Comment by lizhanhui** [comment]
@YangJodie Will it be better to have this check applied on the broker side now that brokers already have client type information through heartbeats?
