### ISSUE TITLE
Enable github action caching for build acceleration.

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#4879]
Enable github action caching for build acceleration and avoid maven repo connection timeout.

![image](https://user-images.githubusercontent.com/19537356/186363714-b923b2c4-b01e-4c03-b9cb-796efb537beb.png)

related link: https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/

**Comment by lizhanhui** [comment]
What if one of the dependencies is of SNAPSHOT? Will the cache get updated complying with Maven practice?

**Comment by aaron-ai** [comment]
> What if one of the dependencies is of SNAPSHOT? Will the cache get updated complying with Maven practice?

Nice question!

Cache of java-setup aims to make caching to work out of box without manual configuration. The format of the used cache key is `setup-java-${{ platform }}-${{ packageManager }}-${{ fileHash }}`. So the default configuration could not make sure the latest snapshot jar is downloaded. java-setup makes is possible to define the cache key by ourselves, but it seems could not to satisfy the needs you mentioned above easily.

On the other side, could we assume that there should not be snapshot in master/develop branch?

More details:
1. https://github.com/actions/setup-java#caching-packages-dependencies
2. https://github.com/actions/setup-java/issues/255

**Comment by lizhanhui** [comment]
> On the other side, could we assume that there should not be snapshot in master/develop branch?

Okay... If there is no better alternatives, I am fine with the current solution.
