### ISSUE TITLE
The nameserver process failed after start

### ISSUE THREAD

**Issue by a-tony** [apache/rocketmq#4893]
![QQ截图20220826085447](https://user-images.githubusercontent.com/30425455/186793788-34f4f274-4b40-44a5-a99a-4763535097f3.png)

**Comment by RongtongJin** [comment]
Could you provide the version you used？

**Comment by duhenglucky** [comment]
> 

是不是因为没有后台运行导致的，可以试下用下面的命令运行：
nohup sh bin/mqnamesrv &
nohup sh bin/mqbroker -n localhost:9876 &
