### ISSUE TITLE
把循环index的类型由long改为int，让循环前放置Safepoint，效果会不会比Thread.sleep(0)更好？

### ISSUE THREAD

**Issue by somePeopleFireAndWood** [apache/rocketmq#4902]
如题
MappedFile 类，507~527行这个循环，把循环的i、j改成long类型。删除掉522行的Thread.sleep(0)。
![修改](https://user-images.githubusercontent.com/31239424/186868037-eb6bb37b-0b78-4e0f-8a6b-07c129d0abc3.png)

这么改，关于gc方面的优化，效果会不会更好？代码看着也会更加优雅

**Comment by fuyou001** [comment]
虽然是sleep 0，但因操作系统时钟精度原因，实际会sleep 几毫秒，不同的系统，精度可能值会不一样；
删除之后，就没有sleep的效果了；

**Comment by foxeatsspicy** [comment]
> 虽然是sleep 0，但因操作系统时钟精度原因，实际会sleep 几毫秒，不同的系统，精度可能值会不一样； 删除之后，就没有sleep的效果了；

请问为什么要有sleep的效果呢？没有sleep的效果不是更好吗？
另外还有的问题是，如果追求sleep的效果，sleep(0)有没有可能被jit优化啊？

**Comment by francisoliverlee** [comment]
@foxeatsspicy can you make a test code ?

**Comment by shy-share** [comment]
> @foxeatsspicy can you make a test code ?

 @francisoliverlee  the person doesn't seem to exist，page is 404

**Comment by Yong0724** [comment]
safepoint，安全点。

**Comment by lizhanhui** [comment]
> 虽然是sleep 0，但因操作系统时钟精度原因，实际会sleep 几毫秒，不同的系统，精度可能值会不一样； 删除之后，就没有sleep的效果了；

No. It is not true. The intention of sleep(0) is to introduce safe points. When there is an ongoing GC, this thread will take fewer milliseconds to reach a safe point. This would be helpful if the available memory runs low.  See https://stackoverflow.com/questions/67232199/how-to-reduce-time-taken-on-threads-reaching-safepoint-sync-state

**Comment by lizhanhui** [comment]
@duhenglucky The pull request is not completed yet. Need more insights involved.

**Comment by linlinjie** [comment]
continuing to pay attention

**Comment by gmshake** [comment]
> > 虽然是sleep 0，但因操作系统时钟精度原因，实际会sleep 几毫秒，不同的系统，精度可能值会不一样； 删除之后，就没有sleep的效果了；
> 
> @fuyou001
> 
> No. It is not true. The intention of sleep(0) is to introduce safe points. When there is an ongoing GC, this thread will take fewer milliseconds to reach a safe point. This would be helpful if the available memory runs low. See https://stackoverflow.com/questions/67232199/how-to-reduce-time-taken-on-threads-reaching-safepoint-sync-state

Maybe `Thread.yield()` is more clear for the usage?

**Comment by kimmking** [comment]
实际上，这里的改动无效：for循环里有方法调用，就不存在这个问题。方法调用栈退出的地方，是可以加check safepoint的。

for循环退不出的场景，也可以通过-XX:+UseCountedLoopSafepoints解决，不需要改代码。
