### ISSUE TITLE
关于rocketMq的消息推送，java查询问题

### ISSUE THREAD

**Issue by xiaozaiyuji** [apache/rocketmq#491]
rocketMq有没有办法查询相应的topic，queue中的消费者的未消费的消息数量的方法？如果没有，有没有添加的计划。

**Comment by duhengforever** [comment]
@xiaozaiyuji 可以使用 mqadmin 的consumerProgress 命令来查看对应的消费位点以及diff

**Comment by Chuenfai** [comment]
Yes of course. Command `mqadmin statsAll` and command `mqadmin consumerProgress` will help you, column `Accumulation` in 1st cmd and column `diff` in 2nd cmd is about the number of undelivered messages.
