### ISSUE TITLE
console dashboard页面疑问,

### ISSUE THREAD

**Issue by icc99** [apache/rocketmq#493]
![image](https://user-images.githubusercontent.com/16347552/47134445-4a3f4300-d2df-11e8-8067-82ce5782077d.png)
这张图没看懂, Topic 5min trend是什么意思, 看到一个时间点已经超过1万5, 对应的broker 5 min trend 才不到400, 
请问broker 5 min trend  和  Topic 5min trend分别是什么意思

**Comment by duhengforever** [comment]
@icc99 
broker's message count (broker total message count/5 min trend)
topic's message count（topic total message count/5 min trend）

And this issue tab only used for bug report and feature request, please use mailing list for help: https://rocketmq.apache.org/about/contact/
