### ISSUE TITLE
How to be a professional distributed system engineer ?

### ISSUE THREAD

**Issue by vongosling** [apache/rocketmq#494]
Some guys always ask me how to be an eligible or top committer in distributed system fields. There is an ancient Chinese saying that it is better to travel 10,000 miles than to read 10,000 books. Here, I would like to first share how to combine reality with daily coding, and improve your professional degree through tens of thousands of volumes of good books, and become a top programmer. The following readings are my preferred references, please feel free to sink in them.

#### [Distributed Systems: Concepts and Design (5th Edition)](https://www.amazon.com/Distributed-Systems-Concepts-Design-5th/dp/0132143011/ref=sr_1_6?s=books&ie=UTF8&qid=1539845327&sr=1-6&keywords=distributed+system)

**Comment by XiaoZYang** [comment]
How about adding the book *Distributed Systems: Concepts and Design* to the list? And [here](http://www.gecg.in/papers/ds5thedn.pdf) is available pdf version.

**Comment by zhisheng17** [comment]
mark and then download , last see

**Comment by wtopps** [comment]
Thank you!!!~

**Comment by Gvinaxu** [comment]
mark

**Comment by KevinHe666** [comment]
> Thank you!!!~

**Comment by kevindang8719** [comment]
### nice

**Comment by Mengw** [comment]
nice and mark

**Comment by dchack** [comment]
Thanks for your share!

**Comment by vinqin** [comment]
mark

**Comment by kiddingYang** [comment]
Thanks
