### ISSUE TITLE
Fix the logic when deal with a write_event with empty events(the log need to be appended by DLedger)

### ISSUE THREAD

**Issue by TheR1sing3un** [apache/rocketmq#4959]
> DLedgerController.ControllerEventHandler#run()

![image](https://user-images.githubusercontent.com/87409330/187713599-c5dd92d9-440c-4740-8b35-4434d3bc2a43.png)

If a write_event has been processed and responsed with empty events(DLedger log), we shouldn't ingore it, we must regard it as a read event because this event has accessed the controller state machine

**Comment by Oliverwqcwrw** [comment]
Hello @TheR1sing3un 
The theme and the PR changes don't match, I guess

It should be

Fix the logic when deal with a `write_event` with empty events(the log need to be appended by DLedger)

**Comment by TheR1sing3un** [comment]
> Hello @TheR1sing3un 
> The theme and the PR changes don't match, I guess
> 
> It should be
> 
> Fix the logic when deal with a `write_event` with empty events(the log need to be appended by DLedger)

Yes！Thks！
