### ISSUE TITLE
Document questions about ConsumeQueue

### ISSUE THREAD

**Issue by azhsmesos** [apache/rocketmq#4962]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/65518067/187828797-f39d2b03-956e-449a-a2f8-fb8adffaced8.png">

今天在讨论时有人说官网说 consumer queue这个概念，我看了一下给的链接，我感觉这儿表述不清晰容易给人带来误解吧

**Comment by lizhanhui** [comment]
这个地方明显写的不准确
