### ISSUE TITLE
Suggestions on setting the disk flushing mode at the message level

### ISSUE THREAD

**Issue by SpinSi** [apache/rocketmq#4976]
是否考虑支持多种消息刷盘方式，例如让消息设定本条消息的刷盘方式。
仅仅是个建议。

**Comment by RongtongJin** [comment]
当前如果单条message设置了setWaitStoreMsgOK为false，则不管设置何种刷盘方式和备机同步策略，该条消息无需等待刷盘以及备机同步即可向客户端返回写入成功。

**Comment by SpinSi** [comment]
good ths

**Comment by SpinSi** [comment]
默认是 true 是吧
