### ISSUE TITLE
Rockemtq 4.9.1 Configuring ACL The consumer fails to receive messages

### ISSUE THREAD

**Issue by zhoushuai1119** [apache/rocketmq#4992]
One of my consumers subscribes to several topics, such as TopicTest and TopicTestV2；

Plain acl. Yml configuration TopicTest PUB, TopicTestV2 is PUB | SUB

The producer sends a message to TopicTest and TopicTestV2, but the consumer does not receive a message. Theoretically, TopicTestV2 receives a message. It is normal that TopicTest does not have the PUB permission. But why isn't TopicTestV2 getting any messages?

![QQ图片20220904151244](https://user-images.githubusercontent.com/29701159/188302173-c3c2508a-c469-448b-82ea-689fd5d67d61.png)
![QQ图片20220904151251](https://user-images.githubusercontent.com/29701159/188302178-dbfb1100-74b1-4724-b431-a821edb9b02c.png)
![QQ图片20220904151257](https://user-images.githubusercontent.com/29701159/188302182-736863ad-bd05-46da-8883-a9cd700d79fb.png)

**Comment by caigy** [comment]
What is consumer group you set? Have you granted the consumer group with `SUB` privilege?

**Comment by zhoushuai1119** [comment]
I didn't grant the consumer group sub privilege before. I used the default consumer group privilege defaultgroupperm: pub | sub. However, I set the consumer group pub | sub, and still can't receive any messages. I set both topictest and topictestv2 to pub | sub can receive messages

**Comment by zhoushuai1119** [comment]
> What is consumer group you set? Have you granted the consumer group with `SUB` privilege?

I didn't grant the consumer group sub privilege before. I used the default consumer group privilege defaultgroupperm: pub | sub. However, I set the consumer group pub | sub, and still can't receive any messages. I set both topictest and topictestv2 to pub | sub can receive messages

**Comment by drpmma** [comment]
It's about HEART_BEAT validation. See https://github.com/apache/rocketmq/blob/a1bfe1afce40c08083cae770b777aa2c9067479d/acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessValidator.java#L95  

In your case, consumer subscribes TopicTest and TopicTestV2 whose HEART_BEAT rpc will contain these two topic which need SUB permission. Thus acl will reject HEAT_BEAT, so TopicTestV2 cannot get any message. In other word, TopicTestV2 is influenced by TopicTest.

**Comment by zhoushuai1119** [comment]
> HEART_BEAT

OK, thank you. If I want to realize that a consumer group subscribes to multiple topics, but the permissions of each topic are different. Permissions are not affected. Is there a good implementation plan?

**Comment by drpmma** [comment]
> > HEART_BEAT
> 
> OK, thank you. If I want to realize that a consumer group subscribes to multiple topics, but the permissions of each topic are different. Permissions are not affected. Is there a good implementation plan?

I'm afraid not. HEART_BEAT is the RPC composed of all the subscription topics. You can use the mode that a group subscribes to a topic instead.
