### ISSUE TITLE
Transaction Message only check 5 times instead of 15 when executeLocalTransaction is UNKNOW

### ISSUE THREAD

**Issue by zhangdp-taozi** [apache/rocketmq#500]
According by document: "In order to avoid a single message being checked too many times and lead to half queue message accumulation， we limited the number of checks for a single message to 15 times by default". But i test transaction message when executeLocalTransation is UNKOWN, it only check 5 times, not 15 times, and its interval time is 1 minute. is that an issue? btw, rocketmq version is 4.3.0

**Comment by duhengforever** [comment]
@zhangdp-taozi RocketMQ version 4.3.0 default value is set to 5 times, and you can change this value in config file to 15 or another value as you need, and this doc is based on the latest version, its default changed to 15 times.
