### ISSUE TITLE
[feature] Add echo server to check service status

### ISSUE THREAD

**Issue by ShadowySpirits** [apache/rocketmq#5028]
At present, rocketmq lacks means to quickly detect network connectivity and service status. SRE usually suggest user ping broker or name server ip, or telnet their port. But sometimes this way doesn't work out. eg. icmp is allowed but tcp not, or tcp connection can be established but following packets cannot be processed.

Therefore, broker and name server needs to provide a way to detect whether the service is currently available. And it should be as simple as possible. OS build-in command is enough, don't bother users to install additional tools.

The example is as follows:

<img width="339" alt="Snipaste_2022-09-08_11-38-53" src="https://user-images.githubusercontent.com/32436597/189037252-4c4532d8-ddd4-41bd-a045-c2741227ea9a.png">

**Comment by ShadowySpirits** [comment]
@lizhanhui please have a look

**Comment by aarushisoni** [comment]
Hi my name is Aarushi Soni . I want to contribute to this issue . Is this issue still open ? I am first time contributor . Please guide me through this process.@lizhanhui

**Comment by ShadowySpirits** [comment]
> Hi my name is Aarushi Soni . I want to contribute to this issue . Is this issue still open ? I am first time contributor . Please guide me through this process.@lizhanhui

@aarushisoni I have submitted a pr #5029 to implement this feature. Can you help review it?
