### ISSUE TITLE
不同消费组订阅同一个topic 

### ISSUE THREAD

**Issue by hangzhouljp** [apache/rocketmq#5035]
单机rocketmq 不同消费组 订阅同一个topic 一个webGroup 一个colGroup 一起共存了一段时间 后来将webGroup订阅代码删除了 只留一个colGroup为啥 webGroup组中会有消息堆积 我并没有在从控制台删除webGroup

**Comment by caigy** [comment]
1. `webGroup` will NOT be deleted if your subscription code is removed.
2. Because `webGroup` still exists, without consuming any messages, it presents like the consumption of `webGroup` is accumulated.

**Comment by hangzhouljp** [comment]
单机rocketmq 不同消费组 订阅同一个topic  会消费同一个到同一条消息吗

**Comment by lizhanhui** [comment]
@hangzhouljp 多个consumer groups，订阅了相同的topic，那些topic里面的消息会fan-out到每一个group。也就是说，每个group都会收到一个copy。同一个group内的多个consumer，做load-balancing。

**Comment by hangzhouljp** [comment]
我在rocketmq控制台已经把组删除了 为啥topic下仍然线上改组呢

**Comment by hangzhouljp** [comment]
> 单机rocketmq 不同消费组 订阅同一个topic 会消费同一个到同一条消息吗




> @hangzhouljp 多个consumer groups，订阅了相同的topic，那些topic里面的消息会fan-out到每一个group。也就是说，每个group都会收到一个copy。同一个group内的多个consumer，做load-balancing。

**Comment by hangzhouljp** [comment]
那它的这种行为是在生产的时候发生的好事消费的时候发生的 why在那个时候发生

**Comment by yanfeiliou** [comment]
How to deal with this problem?

**Comment by shadowofmoo** [comment]
> 我在rocketmq控制台已经把组删除了 为啥topic下仍然显示该组呢

相同的疑问 有啥新进度吗？
