### ISSUE TITLE
Add markdown lint workflow

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#5038]
Markdown is a lightweight markup language for creating formatted text, but there are various implementations. 

To unify the specs of our docs, a markdown lint workflow is essential. An example could be referred here: https://github.com/apache/rocketmq-clients/blob/master/.github/workflows/markdown_lint.yml

**Comment by selectbook** [comment]
hi, can i hava a try?

**Comment by aaron-ai** [comment]
> hi, can i hava a try?


That's great!  I assigned it to you.

**Comment by shy-share** [comment]
> Markdown is a lightweight markup language for creating formatted text, but there are various implementations.
> 
> To unify the specs of our docs, a markdown lint workflow is essential. An example could be referred here: https://github.com/apache/rocketmq-clients/blob/master/.github/workflows/markdown_lint.yml

just copy this file?

**Comment by aaron-ai** [comment]
@shy-share Hi, you also need to fix the style in existing markdown files to pass the markdown-link check.

**Comment by shy-share** [comment]
> @shy-share Hi, Thanks your attetion, the existing markdown files are also need to be fixed to pass the markdown-lint check.

@aaron-ai  I've learned so far that this is an npn tool that requires a style file, this should be the same as in the link, so just use npn to fix it automatically? Still don't quite understand how it's going to work.

**Comment by aaron-ai** [comment]
It seems that markdownlint could fix some basic errors, but not all. markdownlint is more concerned with style checking.

I'am not sure whether there is some errors you need to fix it manually. anyway, just fix it and pass the check.

**Comment by Abhijeetmishr** [comment]
@aaron-ai @Oliverwqcwrw can I pick this Up ?

**Comment by aaron-ai** [comment]
@Abhijeetmishr Of course, I assigned it to you.

**Comment by Abhijeetmishr** [comment]
> @aaron-ai I am aware on markdown file but what exactly we have to change/update ? Can you please explain a bit if possible ?
> 
> Regards

@aaron-ai @Oliverwqcwrw I will appreciate any help/hints.

**Comment by AayushSaini101** [comment]
Hi @aaron-ai Please assign this issue to me
