### ISSUE TITLE
Broker startup error

### ISSUE THREAD

**Issue by a4363220** [apache/rocketmq#5042]
系统：centos7.9
jdk：11.0.6
rocketmq：4.9.4

启动namesrv没有问题，启动broker出现了以下问题，并且以上环境在之前宕机之前没有问题，是宕机之后再使用脚本启动出现如下提示：
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.rocketmq.store.MappedFile (file:/opt/frame/rocketmq-all-4.9.4-bin-release/lib/rocketmq-store-4.9.4.jar) to method java.nio.DirectByteBuffer.attachment()
WARNING: Please consider reporting this to the maintainers of org.apache.rocketmq.store.MappedFile
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.rocketmq.store.MappedFile (file:/opt/frame/rocketmq-all-4.9.4-bin-release/lib/rocketmq-store-4.9.4.jar) to method java.nio.DirectByteBuffer.attachment()
WARNING: Please consider reporting this to the maintainers of org.apache.rocketmq.store.MappedFile
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by a4363220** [comment]
补充说明，我的物理机原本是32g内存，升级到64g内存然后进行了重启之后，再次启动就出现了上述问题，百般无奈之下我将有关rocketmq的数据文件全部删除，再次尝试启动broker居然启动成功了，我是采取dledger模式进行运行的，是源于我升级物理机配置重启时导致rocketmq日志文件损坏？

**Comment by mxsm** [comment]
> 补充说明，我的物理机原本是32g内存，升级到64g内存然后进行了重启之后，再次启动就出现了上述问题，百般无奈之下我将有关rocketmq的数据文件全部删除，再次尝试启动broker居然启动成功了，我是采取dledger模式进行运行的，是源于我升级物理机配置重启时导致rocketmq日志文件损坏？

how about use jdk1.8?

**Comment by a4363220** [comment]
> > 补充说明，我的物理机原本是32g内存，升级到64g内存然后进行了重启之后，再次启动就出现了上述问题，百般无奈之下我将有关rocketmq的数据文件全部删除，再次尝试启动broker居然启动成功了，我是采取dledger模式进行运行的，是源于我升级物理机配置重启时导致rocketmq日志文件损坏？
> 
> how about use jdk1.8? you can see this issue #4161

您好，切换到1.8我没有尝试过，或许是可以解决此问题，但是我想了解的是，4.9.4这个版本是目前对jdk11的支持还不成熟么？
期间我还发现了一个问题，当我用dledger模式启动出现上述错误时，我尝试运行普通单机的broker时，也是能够正常启动的，
这个就让我有些不解了。

**Comment by RongtongJin** [comment]
> > > 补充说明，我的物理机原本是32g内存，升级到64g内存然后进行了重启之后，再次启动就出现了上述问题，百般无奈之下我将有关rocketmq的数据文件全部删除，再次尝试启动broker居然启动成功了，我是采取dledger模式进行运行的，是源于我升级物理机配置重启时导致rocketmq日志文件损坏？
> > 
> > 
> > how about use jdk1.8? you can see this issue #4161
> 
> 您好，切换到1.8我没有尝试过，或许是可以解决此问题，但是我想了解的是，4.9.4这个版本是目前对jdk11的支持还不成熟么？ 期间我还发现了一个问题，当我用dledger模式启动出现上述错误时，我尝试运行普通单机的broker时，也是能够正常启动的， 这个就让我有些不解了。

是指dledger模式无法启动，但非dledger模式可以启动吗？另外，是否规格升级后替换过jdk版本？

**Comment by ni-ze** [comment]
https://stackoverflow.com/questions/50251798/what-is-an-illegal-reflective-access
看起来是jdk高版本不允许这种非法反射访问。
