### ISSUE TITLE
The Broker logger replaced by ClientLogger.

### ISSUE THREAD

**Issue by echooymxq** [apache/rocketmq#5043]
Some `MessageQueueStrategy` use broker logger to log.
https://github.com/apache/rocketmq/blob/f8bf7bd38b11ca025c5795a8e4a03bd577f47273/broker/src/main/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessor.java#L66-L67

But `ClientLogger.getLog()` cause all the broker log output to rocketmq_client.log.
https://github.com/apache/rocketmq/blob/f8bf7bd38b11ca025c5795a8e4a03bd577f47273/client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AbstractAllocateMessageQueueStrategy.java#L30

**Comment by lizhanhui** [comment]
@aaron-ai Is there a plan to replace the homemade logging with shaded slf4j + logback?

**Comment by aaron-ai** [comment]
> @aaron-ai Is there a plan to replace the homemade logging with shaded slf4j + logback?

A draft pull request will be proposed recently. Welcome to review.
