### ISSUE TITLE
Some test error

### ISSUE THREAD

**Issue by azhsmesos** [apache/rocketmq#5050]
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/65518067/189530111-ffd9f92e-4dd0-400e-9211-15a47ac727f1.png">
when upstream, there is some test case error every time. Should fix it？

**Comment by caigy** [comment]
@azhsmesos It would be grateful if you find the cause and fix it.

**Comment by mxsm** [comment]
@azhsmesos  of course, you can submit PR to fix it

**Comment by tsunghanjacktsai** [comment]
I guess it failed due to something wrong with our CI built with Windows & MacOS. Hope you could help us find the reason. Thx.

**Comment by lizhanhui** [comment]
> I guess it failed due to something wrong with our CI built with Windows & MacOS. Hope you could help us find the reason. Thx.
@tsunghanjacktsai 
No. It is not something wrong with the CI, it's the test code that is not portable.

**Comment by lizhanhui** [comment]
@azhsmesos  You are welcome to figure out issues with the failing test cases... Actually, I have been fixing them for a while. Filter pull requests with Infra Improvement Project, and you would see a few resolved similar issues.
