### ISSUE TITLE
In controller mode, the variable 'isIsolated' is always true, which cause heartbeat between borker and controller will never happen.

### ISSUE THREAD

**Issue by zhouchunhai** [apache/rocketmq#5053]
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/111631755/189607598-201401f8-656e-47fb-bd5f-6a5037234905.png">
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/111631755/189607737-715d24ca-620c-4b98-bebd-9c96f65b82a7.png">  
As shown in picture and described in the title, heartbeat between borker and controller will never happen.

**Comment by RongtongJin** [comment]
https://github.com/apache/rocketmq/blob/f8bf7bd38b11ca025c5795a8e4a03bd577f47273/broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java#L290-L314

The isIsolated will be false after the broker register to the controller success.

**Comment by zhouchunhai** [comment]
ok, thanks for explanation.
