### ISSUE TITLE
Namesrv's TBW102 topic is not consistent with the broker's autoCreateTopic configuration

### ISSUE THREAD

**Issue by nowinkeyy** [apache/rocketmq#5055]
**BUG REPORT**

1. Please describe the issue you observed:

The broker starts with autoCreateTopic=true. After the broker is registered with namesrv, namesrv's TBW102 topic contains the broker's routing information ( correct ) .

However, the broker crashed and reboot with autoCreateTopic=false. Namesrv's TBW102 topic still contains the broker's routing information ( wrong ) .

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

I think autoCreateTopic information should be updated in namesrv whenever the broker starts registering with namesrv to update the TBW102 topic.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

Because namesrv fails to update TBW102, when the producer sends messages to uncreated themes, it will get the wrong TBW102 route from namesrv, which may send messages to brokers with autoCreateTopic=false, resulting in an error return from the broker 
[ CODE: 17  DESC: topic[TopicTest] not exist, apply first please! ]. It's not reasonable or elegant !

**Comment by drpmma** [comment]
It's recommended not to use autoCreateTopic in the production environment. It may lose topic validation when a typo occurs.

**Comment by nowinkeyy** [comment]
> It's recommended not to use autoCreateTopic in the production environment. It may lose topic validation when a typo occurs.

Thank you for your recommendation and i approve your point. But i still want to solve it. :)

**Comment by Knowden** [comment]
I think the root case is that rocketmq not support modify broker topic config by manual modify config file because that register_broker event will not remove some not-existed topic route info from route table.

**Comment by Knowden** [comment]
If you edit topicConfig.json manually and reboot broker, there will be the same problem 🤔

**Comment by nowinkeyy** [comment]
> If you edit topicConfig.json manually and reboot broker, there will be the same problem 🤔

If topicConfig is modified, i think the broker shoudl register the new topic again after reboot. I'll check the code that reads the autoCreateTopic configuration and registerTopicToNamesrv method.

**Comment by Knowden** [comment]
> > If you edit topicConfig.json manually and reboot broker, there will be the same problem 🤔
> 
> If topicConfig is modified, i think the broker shoudl register the new topic again after reboot. I'll check the code that reads the autoCreateTopic configuration and registerTopicToNamesrv method.

right, but the old topic route info will not be removed by this way.

**Comment by complone** [comment]
In fact, to solve the problem of automatic creation (autoCreateTopicEnable) from RocketMQ 4.3.0, Rocketmq provides a topicKey to specify the default topic, as shown in the following code:

```
DefaultMQProducer producer = new DefaultMQProducer("please_rename_unidcque_group_name");
//Set the key value of automatic topic creation
producer.setCreateTopicKey("AUTO_CREATE_TOPIC_KEY");
```

**Comment by nowinkeyy** [comment]
> In fact, to solve the problem of automatic creation (autoCreateTopicEnable) from RocketMQ 4.3.0, Rocketmq provides a topicKey to specify the default topic, as shown in the following code:
> 
> ```
> DefaultMQProducer producer = new DefaultMQProducer("please_rename_unidcque_group_name");
> //Set the key value of automatic topic creation
> producer.setCreateTopicKey("AUTO_CREATE_TOPIC_KEY");
> ```
>
> After the instance information of namesrv is registered, you can solve the above problem by setting the topicKey



> In fact, to solve the problem of automatic creation (autoCreateTopicEnable) from RocketMQ 4.3.0, Rocketmq provides a topicKey to specify the default topic, as shown in the following code:
> 
> ```
> DefaultMQProducer producer = new DefaultMQProducer("please_rename_unidcque_group_name");
> //Set the key value of automatic topic creation
> producer.setCreateTopicKey("AUTO_CREATE_TOPIC_KEY");
> ```
> 
> After the instance information of namesrv is registered, you can solve the above problem by setting the topicKey

```
private String createTopicKey = TopicValidator.AUTO_CREATE_TOPIC_KEY_TOPIC;
public static final String AUTO_CREATE_TOPIC_KEY_TOPIC = "TBW102";
```
Your idea seems to be just to change the TBW102 topic something else. If use TBW102, the broker does't need to register the topic in advance. If use setCreateTopicKey(), the broker must register the topic in advance then producer could send messages to the broker( it mens autoCreateTopic is invalid ).  **This is my simple test out, if there is a mistake, please point out.**

**Comment by nowinkeyy** [comment]
To sum up, i think the issue was caused by improper operation. Since changing the autoCreateTopic=false configuration of broker.conf does not remove TBW102 topic from the broker, so the broker still registers TBW102 topic for namesrv. It is also incorrect to delete topics from topics.json. Neither of these is the right to delete a topic. Instead, use dashboard or mqadmin.

My bad first issue 😭 😭 😭 

Time to close it.
