### ISSUE TITLE
The machine has a mechanical hard disk, and the random reading is slow, but the machine memory is large. How to set parameters to improve the reading speed.

### ISSUE THREAD

**Issue by imgoby** [apache/rocketmq#5074]
The machine has a mechanical hard disk, and the random reading is slow, but the machine memory is large. How to set parameters to improve the reading speed.

**Comment by drpmma** [comment]
RocketMQ uses the mmap mechanism which will automatically load related commitlog files or consume queue files into memory if it's enough.
