### ISSUE TITLE
sendDefaultImpl call timeout

### ISSUE THREAD

**Issue by SoftwareKing** [apache/rocketmq#508]
when app start finish，first send message
![image](https://user-images.githubusercontent.com/6858857/47770173-57b1ef80-dd19-11e8-8a54-966fea9b0e22.png)

**Comment by ymwneu** [comment]
You can check your timeout setting or broker network situation. I suggest you debug into the source code, and found out the problem by yourself.
In addition, issue is only for:
1. Bug report;
2. Feature request;
For FQA, you can subscribe mailing lists in http://rocketmq.apache.org/about/contact/ and ask question by mail.
