### ISSUE TITLE
TIMEOUT_CLEAN_QUEUE

### ISSUE THREAD

**Issue by XTUxiongda** [apache/rocketmq#5088]
`[TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 201ms, size of queue: 46`

I have an incomprehensible problem and hope to get help.
The above mentioned errors I encountered should be caused by the quick failure mechanism of the broker.
But I saw the monitoring at that time, and the disk IO did not change significantly, and the amount was small, so I never figured out the reason。
Moreover, the frequency of this error is very high recently. I don't know how to troubleshoot it. I hope to give some suggestions

**Comment by ShadowySpirits** [comment]
According to my experience, I provide you with some advice:

1. check "putMessageDistributeTime" in store.log. if many messages are stored for longer than 10ms, maybe your disk has performance problem.
2. check disk write latency
3. set transientStorePoolEnable to false
4. check broker gc stats

**Comment by RongtongJin** [comment]
> According to my experience, I provide you with some advice:
> 
> 1. check "putMessageDistributeTime" in store.log. if many messages are stored for longer than 10ms, maybe your disk has performance problem.
> 2. check disk write latency
> 3. set transientStorePoolEnable to false
> 4. check broker gc stats

Or you can try to increase the value of the waitTimeMillsInSendQueue parameter appropriately.

**Comment by XTUxiongda** [comment]
> 2\. latency
why set transientStorePoolEnable to false?
Isn't it possible to improve performance by setting transientStorePoolEnable to true?
Is it just that this will increase the probability of losing messages? Am I right? 
I'm currently false. Do I want to set it to true? Is this OK?

**Comment by XTUxiongda** [comment]
> 2\. latency
why set transientStorePoolEnable to false?
Isn't it possible to improve performance by setting transientStorePoolEnable to true?
Is it just that this will increase the probability of losing messages? Am I right? 
I'm currently false. Do I want to set it to true? Is this OK?

**Comment by ShadowySpirits** [comment]
IMO, transientStorePool will cache some messages to reduce read/write races. But it will add IO latency at the same time.
