### ISSUE TITLE
Backoff strategy when channel is not writable

### ISSUE THREAD

**Issue by guyinyou** [apache/rocketmq#5094]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
#5066 

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by guyinyou** [comment]
now:

![image](https://user-images.githubusercontent.com/36399867/190545797-95077cda-bc02-4b3d-b6b4-a73a3a84c5a5.png)
---
---
---
---
new:

![image](https://user-images.githubusercontent.com/36399867/190544830-14942ca1-5438-4d26-83f1-29a9d0abd322.png)

**Comment by guyinyou** [comment]
@fuyou001 @RongtongJin @zhouxinyu 

This is my current idea, let's see if there is a better solution

**Comment by Knowden** [comment]
It's seems like using @rety annotation in spring framework. I wonder in which case the channel will be not writable 🤔

**Comment by fuyou001** [comment]
From the point of view of stability, I suggest keeping the logic as it is, in benchmark case, consumer is not one instance;
if we change , the code will complex

**Comment by guyinyou** [comment]
> From the point of view of stability, I suggest keeping the logic as it is, in benchmark case, consumer is not one instance, if we change , the code will complex

During testing, it will appear as long as the tps of a single consumer reaches the threshold.

In my last benchmark, the production rate finally stabilized at 40w-50wtps, a single consumer reaching 6w-7wtps will trigger the current limit, when I use 4 consumers, there will still be some queues that cannot be consumed and accumulated.

**Comment by fuyou001** [comment]
> > From the point of view of stability, I suggest keeping the logic as it is, in benchmark case, consumer is not one instance, if we change , the code will complex
> 
> During testing, it will appear as long as the tps of a single consumer reaches the threshold.
> 
> In my last benchmark, the production rate finally stabilized at 40w-50wtps, a single consumer reaching 6w-7wtps will trigger the current limit, when I use 4 consumers, there will still be some queues that cannot be consumed and accumulated.

As a comparison， you can set netty highwatermark   higher value  in benchmark,for eg 4M.

**Comment by lizhanhui** [comment]
The throttling mechanism provided by Netty should suffice. I do not see a reason to complicate it. Further, caching data in RetryTaskQueue instead of the application/network buffer is not a good idea.

**Comment by RongtongJin** [comment]
IMO, the key is not how to adjust the highwatermark, but we should not directly return null when the channel is not writable, which results in clients pull timeout and default is 30s.

**Comment by lizhimins** [comment]
Maybe is not a good idea, the backoff strategy will occupy more heap memory.

**Comment by ShadowySpirits** [comment]
IMO, The reason for dropping responses when the channel is not writable is caching too many responses that may cause OOM. Therefore, we shouldn't introduce a retry mechanism. The alternative is to drop response immediately and return system busy when the channel is writable. In this way client could request again instead of waiting long polling.
