### ISSUE TITLE
rocketmq option -p can not print config items

### ISSUE THREAD

**Issue by ShawnShoper** [apache/rocketmq#512]
I download the lastest binary 4.3.0 . I use the commad './mqnamesrv -p' to print config items, but nothing to print,  then i download the source code,I found the code 'MixAll.printObjectProperties(null, namesrvConfig)'  the target logger is null . I also went to see broker's code,the target logger is 'console'.
so i couldn't konw your mean,why the namesrv's target logger is null.

**Comment by ymwneu** [comment]
It's indeed a bug.
