### ISSUE TITLE
Make tests in ACL module pass on Windows

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#5126]
We have a few tests that do NOT work on Windows and MacOS. This ticket is used to track fix of Windows compatibility issues

**Comment by tsunghanjacktsai** [comment]
Would you mind also do it for Mac OS?

**Comment by lizhanhui** [comment]
Let's focus on the ACL module for this ticket. 

Store module has a large number of failing test cases on Windows.  Resolving them in a dedicated thread would be appropriate.

**Comment by lizhanhui** [comment]
> Would you mind also doing it for Mac OS? It is quite annoying that our CI cannot pass recently.

Yes, I am planning to fix them in the near future.
