### ISSUE TITLE
ROCKETMQ consumption can't be traced back

### ISSUE THREAD

**Issue by 2259289435** [apache/rocketmq#513]
After the ROCKETMQ consumer starts up, how to re-consume through CLIENT without using the CLI command line.

**Comment by ymwneu** [comment]
We can't re-consume through client. 
In addition, issue is only for:
1. Bug report;
2. Feature request;
For FQA, you can subscribe mailing lists in http://rocketmq.apache.org/about/contact/ and ask question by mail.

**Comment by ymwneu** [comment]
Maybe you can try pull consumer to re-consume message.  Or you can propose a PR to contribute your code.
In addition, issue is only for:
1. Bug report;
2. Feature request;
For FQA, I suggest you subscribe mailing lists in http://rocketmq.apache.org/about/contact/ and ask question by mail.
