### ISSUE TITLE
Use the latest rocketmq version as example in readme file.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#5130]
Update rocketmq version.
![image](https://user-images.githubusercontent.com/16487356/191255088-186c8607-5900-47db-a725-b4c18e7bd957.png)

**Comment by mxsm** [comment]
Hi @ShannonDing  I want to try

**Comment by security00** [comment]
assign to me

**Comment by ShannonDing** [comment]
> please assigned it to me, thanks

Welcome.
