### ISSUE TITLE
Use StandardCharsets.UTF_8 as default charset in oneway producer demo.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#5133]
Same as #5132 

https://github.com/apache/rocketmq/blob/develop/example/src/main/java/org/apache/rocketmq/example/simple/OnewayProducer.java

**Comment by selectbook** [comment]
please assign it tovme

**Comment by selectbook** [comment]
please assign it to me

**Comment by ShannonDing** [comment]
> please assign it to me

welcome.
