### ISSUE TITLE
Remove useless pull consumer example.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#5134]
just remove PullConsumerTest.java file.
https://github.com/apache/rocketmq/blob/develop/example/src/main/java/org/apache/rocketmq/example/simple/PullConsumerTest.java

**Comment by azhsmesos** [comment]
please assigned it to me, i want to try it.

**Comment by ShannonDing** [comment]
> please assigned it to me, i want to try it.

welcome.

**Comment by azhsmesos** [comment]
> > please assigned it to me, i want to try it.
> 
> welcome.

https://github.com/apache/rocketmq/pull/5137 it's my pull request
