### ISSUE TITLE
Format ERROR_MESSAGE string in commandUtil class.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#5135]
try to change ERROR_MESSAGE from
```
private static final String ERROR_MESSAGE = "Make sure the specified clusterName exists or the name server " +
        "connected to is correct.";
```
to
```
private static final String ERROR_MESSAGE = "Make sure the specified clusterName exists or the name server connected to is correct.";
```
![image](https://user-images.githubusercontent.com/16487356/191269433-6bbb2322-3fa9-4b05-9c24-4adbed0f19e7.png)

https://github.com/apache/rocketmq/blob/develop/tools/src/main/java/org/apache/rocketmq/tools/command/CommandUtil.java

**Comment by islongfei** [comment]
please assigned it to me, i want to try it.

**Comment by ShannonDing** [comment]
> please assigned it to me, i want to try it.

welcome.
