### ISSUE TITLE
SubCommand seems not required to be declared again as a parameter type.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#5136]
maybe `new ArrayList<>(); `is OK.
```
protected static final List<SubCommand> SUB_COMMANDS = new ArrayList<SubCommand>();

```
https://github.com/apache/rocketmq/blob/develop/tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java

**Comment by Aaron-TangCode** [comment]
please assigned it to ,thanks!!!

**Comment by Aaron-TangCode** [comment]
please assigned it to me ,thanks!!!

**Comment by RapperCL** [comment]
please assigned it to me, i want to try it.

**Comment by alexcao2018** [comment]
Please assigned it to me, i want to try it.

**Comment by ShannonDing** [comment]
> Please assigned it to me, i want to try it.

Great, have a try to #5138.

**Comment by RapperCL** [comment]
> > Please assigned it to me, i want to try it.
> 
> Great, have a try to #5138.

https://github.com/apache/rocketmq/pull/5141/files

**Comment by RapperCL** [comment]
> please assigned it to me, i want to try it.

https://github.com/apache/rocketmq/pull/5141/files

**Comment by RapperCL** [comment]
> > please assigned it to me, i want to try it.
> 
> https://github.com/apache/rocketmq/pull/5141/files

new pr:
https://github.com/apache/rocketmq/pull/5143
