### ISSUE TITLE
Do not throw exception in order producer demo.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#5138]
UnsupportedEncodingException should not be throw out in main function.
```
public static void main(String[] args) throws UnsupportedEncodingException 
```
https://github.com/apache/rocketmq/blob/develop/example/src/main/java/org/apache/rocketmq/example/ordermessage/Producer.java

**Comment by alexcao2018** [comment]
Please assigned it to me, i want to try it.

**Comment by Aaron-TangCode** [comment]
Please assigned it to me, thanks!!

**Comment by ShannonDing** [comment]
> Please assigned it to me, i want to try it.

welcome, pls create a PR after you fix it.

**Comment by alexcao2018** [comment]
fixed #5138.

**Comment by alexcao2018** [comment]
Having reviewed the other code like this, I also found some issue like this, https://github.com/apache/rocketmq/blob/develop/example/src/main/java/org/apache/rocketmq/example/simple/AsyncProducer.java

**Comment by alexcao2018** [comment]
Fixed all code in example package like this.

**Comment by lizhanhui** [comment]
> UnsupportedEncodingException should not be throw out in main function.

What is the rational behind this decision?
