### ISSUE TITLE
[why method checkForbidden has no implementation ]

### ISSUE THREAD

**Issue by mahaitao617** [apache/rocketmq#5160]
public void executeCheckForbiddenHook(final CheckForbiddenContext context) throws MQClientException {
        if (hasCheckForbiddenHook()) {
            for (CheckForbiddenHook hook : checkForbiddenHookList) {
                hook.checkForbidden(context);
            }
        }
    }
why method checkForbidden has no implementation?

**Comment by RongtongJin** [comment]
Hi, @mahaitao617 This is a hook, which can be used for secondary development based on the RocketMQ kernel. So the hook may not be implemented in the kernel.
