### ISSUE TITLE
heartbeat question

### ISSUE THREAD

**Issue by niushihao** [apache/rocketmq#5173]
What is the purpose of producers and consumers sending heartbeats to brokers through timed tasks?

Because I have seen that IdleStateHandler based on netty has been used, and I have not seen what to do after the heartbeat based on scheduled tasks fails.

![image](https://user-images.githubusercontent.com/16152296/191887274-b41bcc1b-8b38-4874-969b-255ad6e4a6c3.png)

**Comment by niushihao** [comment]
version:4.6.0

**Comment by lizhanhui** [comment]
The rationale is two-fold:
1, From the management perspective, we need to keep the connections alive to know the survival clients. Without this knowledge, a lot of administrative actions will not be possible.
2, Load balancing algorithm adopted by RocketMQ depends on alive consumers of a specific group.

**Comment by niushihao** [comment]
Since the custom heartbeat task is very important, is it possible to remove the IdleStateHandler, I am confused about using these two at the same time
