### ISSUE TITLE
Support domain resolution to obtain the nameserver address

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq#5180]
Currently, the address of the NameServer is resolved in the form of splitting ";".
In the k8s environment, we can deploy it in single deployment.
We need to support domain resolution to obtain the NameServer address.

目前对 NameServer 的地址是以分割 ";" 的形式进行解析的，在 k8s 环境中，由于 NameServer 水平对等无状态，我们可以采用 deployment 的形式部署，需要支持域名解析来获取地址。

**Comment by lizhanhui** [comment]
This feature is pretty tricky... Java has a lot of related bugs, which may impact this feature negatively
To name a few
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6247501
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8274692

**Comment by lizhimins** [comment]
I make this feature optional and off by default, and emphasize the points needing attention in the config. Users need to understand its side effects when they enable a feature-gate like k8s.

**Comment by lizhimins** [comment]
@RongtongJin @odbozhou @dongeforever Do you have a better idea?

**Comment by xdkxlk** [comment]
> Though this is a very commonly used technique, shared by many popular products, say [grpc](https://github.com/grpc/grpc/blob/master/doc/naming.md), [envoy](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery). This feature is pretty tricky for Java applications because Java has a lot of related bugs, which may impact this feature negatively if JDK is not carefully chosen To name a few https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6247501 https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8274692

How did grpc-java solve this kind of problem?

**Comment by lizhimins** [comment]
![image](https://user-images.githubusercontent.com/22487634/192239583-05157f44-7497-4f5f-913b-efaaf46536da.png)

> How did grpc-java solve this kind of problem?

grpc use InetAddress.getAllByName(host) to get list

**Comment by lizhimins** [comment]
![image](https://user-images.githubusercontent.com/22487634/192262586-b89f268a-e60d-4637-8dc0-dea0d9fe3947.png)
