### ISSUE TITLE
Rocketmq-Spring Upgrade support for RocketMQ 5.x

### ISSUE THREAD

**Issue by kpioneer123** [apache/rocketmq#5183]
**FEATURE REQUEST**
I am using Aliyun RocketMQ 5 and hope Rocketmq-Spring(https://github.com/apache/rocketmq-spring)  to support RocketMQ 5.x

**Comment by zongtanghu** [comment]
Maybe, you can put forward a feature issue to the rocketmq-spring github site.

**Comment by ShannonDing** [comment]
link https://github.com/apache/rocketmq-spring/issues/488
