### ISSUE TITLE
Read Commitlogs concurrently to speed up generation of the consumeQueue

### ISSUE THREAD

**Issue by nowinkeyy** [apache/rocketmq#5184]
**Detailed introduction**
[scheme.pdf](https://github.com/apache/rocketmq/files/9702251/reput.pdf)

**Problem description：**

When the message production traffic is heavy, the ConsumeQueue messages are generated slowly, resulting in a delay in message consumption.

**The solution：**

The CommitLog messages are processed concurrently to generate ConsumeQueue messages

**Comment by azhsmesos** [comment]
I want to use fork-join to generate different consumequeues in parallel，can I try it？

**Comment by nowinkeyy** [comment]
> I want to use fork-join to generate different consumequeues in parallel，can I try it？

I've got a specific idea, and I'll share it later. 😄

**Comment by nowinkeyy** [comment]
@RongtongJin @aaron-ai  @lizhanhui @mxsm @Oliverwqcwrw  ❤️ ❤️ 
Excuse me, can you help me see if the plan is suitable? Or do i need make a RIP? 

**The old way**
![reput-old](https://user-images.githubusercontent.com/72536832/193395959-99b86489-21c4-4250-995b-d7b4db91b121.png)

**The new way**
![reput-new](https://user-images.githubusercontent.com/72536832/193395962-f5e6b176-a08d-47d9-b373-3e1732ff6d17.png)

**Comment by azhsmesos** [comment]
> @RongtongJin @aaron-ai @lizhanhui @mxsm @Oliverwqcwrw ❤️ ❤️ Excuse me, can you help me see if the plan is suitable? Or do i need make a RIP?
> 
> **The old way** ![reput-old](https://user-images.githubusercontent.com/72536832/193395959-99b86489-21c4-4250-995b-d7b4db91b121.png)
> 
> **The new way** ![reput-new](https://user-images.githubusercontent.com/72536832/193395962-f5e6b176-a08d-47d9-b373-3e1732ff6d17.png)

Currently, the bottleneck is that reading Commitlog files is single-threaded. In fact, consumerQueue can generate different commitlog files in parallel and without locking. In the figure, MSG table needs to be locked , so we can replace it with ThreadLocal. Reading a commitLog file builds consumerQueue by reading offsets from the ThreadLocal of the current thread.
Do you think it is possible to use ThreadLocal to store the offset of MSG？ It supports lock-free operations.

**Comment by nowinkeyy** [comment]
> > @RongtongJin @aaron-ai @lizhanhui @mxsm @Oliverwqcwrw ❤️ ❤️ Excuse me, can you help me see if the plan is suitable? Or do i need make a RIP?
> > **The old way** ![reput-old](https://user-images.githubusercontent.com/72536832/193395959-99b86489-21c4-4250-995b-d7b4db91b121.png)
> > **The new way** ![reput-new](https://user-images.githubusercontent.com/72536832/193395962-f5e6b176-a08d-47d9-b373-3e1732ff6d17.png)
> 
> Currently, the bottleneck is that reading Commitlog files is single-threaded. In fact, consumerQueue can generate different commitlog files in parallel and without locking. In the figure, MSG table needs to be locked , so we can replace it with ThreadLocal. Reading a commitLog file builds consumerQueue by reading offsets from the ThreadLocal of the current thread. Do you think it is possible to use ThreadLocal to store the offset of MSG？ It supports lock-free operations.

In fact, the specific implementation of this MAG table has not been decided, and I intend to avoid the situation of locking. ThreadLocal can be a good idea.

**Comment by nowinkeyy** [comment]
> In fact, the specific implementation of this MAG table has not been decided, and I intend to avoid the situation of locking. ThreadLocal can be a good idea.

IMO, the MSG table needs to be shared globally, so Threadlocal is not a good idea. And msg written to CQ cannot be concurrent (obviously concurrency errors), so the thread needs to acquire CQ's lock first. Because access is serialized for a single CQ, the MSG table request from this thread does not conflict with the requests from reputMessageService and other threads. So MSG table may be lock-free.

**Comment by Oliverwqcwrw** [comment]
Hello @nowinkeyy , 

Good idea, there I have two small tips,

1. Could you give a more detailed description of your new scheme, as everyone may have a different understanding of the picture

2. Whether the new scheme affects the sequential consumption of messages in a queue

**Comment by nowinkeyy** [comment]
Hi @Oliverwqcwrw , thank you for your advice! 😄 

 The new scheme could ensures the sequential consumption of messages in a queue. And i will show you a detailed description of the schema.

**Comment by nowinkeyy** [comment]
> Hi @Oliverwqcwrw , thank you for your advice! 😄
> 
> The new scheme could ensures the sequential consumption of messages in a queue. And i will show you a detailed description of the schema.

I add a Detailed introduction [reput.pdf](https://github.com/apache/rocketmq/files/9702266/reput.pdf)

**Comment by byj520-lang** [comment]
This idea sounds like a good idea.

**Comment by lizhanhui** [comment]
Hi @nowinkeyy  Glad to see your attempts. I advise you to create a RIP, where we can formally define this problem and discuss potential solutions.  I am glad to act as shepherd. 

Actually, we can make writes of consume-queue concurrent since slot of each entry has already been sequentially allocated. 
We only need to record the position prior to which there would be no empty slots and consumer may consume messages up to.

Further, writing to commit log itself may also be made concurrent. Refer MySQL 8.0 which writes to WAL are already concurrent https://dev.mysql.com/blog-archive/mysql-8-0-new-lock-free-scalable-wal-design/

**Comment by nowinkeyy** [comment]
Hi @lizhanhui 
I am very honored to create a rip under your leadership.

> Actually, we can make writes of consume-queue concurrent since slot of each entry has already been sequentially allocated.
We only need to record the position prior to which there would be no empty slots and consumer may consume messages up to.

I agree with your idea. And I've already written part of the code, so I may provide more details. Please tell me how to write a correct rip, shepherd.

**Comment by lizhanhui** [comment]
@nowinkeyy We have a RIP guide [here](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). It also contains a template. You may also check out existing RIPs to see how it should be written.

**Comment by nowinkeyy** [comment]
Hi @lizhanhui 
I have a first version of RIP ready, but I don't know how to upload it to the wiki, it seems I don't have permission to change the page. After uploading RIP to wiki, I will send [DISCUSSION][RIP] to dev@rocketmq.apache.org. Then I think the other optimization point you proposed to me (concurrent commitLog writes) is quite different from my current optimization design. I plan to design a RIP separately. What do you think?

If there is anything wrong with my RIP creation process, please correct me.

**Comment by lizhanhui** [comment]
@nowinkeyy Could you check if sending pull-request to https://github.com/apache/rocketmq.wiki.git works or not? You may, alternatively, send the patch to me and I would add it to the wiki repository.

**Comment by nowinkeyy** [comment]
> @nowinkeyy Could you check if sending pull-request to https://github.com/apache/rocketmq.wiki.git works or not? You may, alternatively, send the patch to me and I would add it to the wiki repository.

I git clone https://github.com/apache/rocketmq.wiki.git and git push my RIP, it can;t push. I don't know how to pull-request to https://github.com/apache/rocketmq.wiki.git. 😢

**Comment by ShadowySpirits** [comment]
Hi @nowinkeyy,

I read your proposal and have some questions.

1. Under normal circumstances, the messages of same queue are ordered in the commitLog. So your improvement is just to execute the dispatcher asynchronously? It seems that the batch write you describe will not work in most cases.
2. I don't see anything about recovering from fault in your proposal. eg. Where to start rebuilding cq after broker is down and restart.

**Comment by nowinkeyy** [comment]
Hi @ShadowySpirits , thank you very much for your reply!

> Under normal circumstances, the messages of same queue are ordered in the commitLog. So your improvement is just to execute the dispatcher asynchronously? It seems that the batch write you describe will not work in most cases.

The core of this optimization is to process dispatchRequest concurrently, so that different cq can be written at the same time, and even the same cq can be written at limited time (this needs more thought). The proposal has been updated. Now I use batch update commit-position instead of batch write messages. 

> I don't see anything about recovering from fault in your proposal. eg. Where to start rebuilding cq after broker is down and restart.

It is true that I have given less consideration to this aspect, and I prefer to follow the original thinking.

**the updated proposal**

![image](https://user-images.githubusercontent.com/72536832/196021365-adaad7bb-87bc-470b-b3f0-cfaa1c2de1d1.png)
![image](https://user-images.githubusercontent.com/72536832/196021377-7feab792-3dda-425d-940b-065d9c361bee.png)

**Comment by ShadowySpirits** [comment]
> The core of this optimization is to process dispatchRequest concurrently

Maybe a better way is to make the dispatch method asynchronous.

```java
public interface CommitLogDispatcher {
    CompletableFuture<DispatchResult> dispatch(final DispatchRequest request);
}
```

So we don't need complex data structure to cache messages, we just need to handle futures.

**Comment by nowinkeyy** [comment]
> Maybe a better way is to make the dispatch method asynchronous.

I get your idea. It seems like a good idea. 👍  The ReptMessageService thread can process futures to get the dispatch run result, so as to update reputFromOffset, retry or not, etc.

**Comment by cserwen** [comment]
Looking forward to this feature very much. By the way, how is the progress of it? @nowinkeyy

**Comment by nowinkeyy** [comment]
> 

Part of it is done, but it is still being improved. See #5552 for more details.

**Comment by Dr-wgy** [comment]
https://heapdump.cn/article/6344684

in our production environment commitLog dispatch comsume queue and index slowly 

```
16:48:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 0 bytes
16:49:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 195011090 bytes
16:50:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 503128527 bytes
16:51:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 820827985 bytes
16:52:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 1119154950 bytes
16:53:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 1371931476 bytes
16:54:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 1627376302 bytes
16:55:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 1895197916 bytes
16:56:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 2172267528 bytes
16:57:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 2431757827 bytes
16:58:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 2710935695 bytes
16:59:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 2992111923 bytes
17:00:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 3265533055 bytes
17:01:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 3713616179 bytes
17:02:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 4121989447 bytes
17:03:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 4506883955 bytes
17:04:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 4831540126 bytes
17:05:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 5153375631 bytes
17:06:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 5477330907 bytes
17:07:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 5827133856 bytes
17:08:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 6174273510 bytes
17:09:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 6509742357 bytes
17:10:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 6848652654 bytes
17:11:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 7150862926 bytes
17:12:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 7432869470 bytes
17:13:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 7699771035 bytes
17:14:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 7948980439 bytes
17:15:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 8202390118 bytes
17:16:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 8125492927 bytes
17:17:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 7519621856 bytes
17:18:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 6779058147 bytes
17:19:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 5989943481 bytes
17:20:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 5039680763 bytes
17:21:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 4333049451 bytes
17:22:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 3563592630 bytes
17:23:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 851804170 bytes
17:24:02 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 1975 bytes
```

**Comment by nowinkeyy** [comment]
@Dr-wgy 
Hi, which version are you using, this optimization was added in rocketmq-all-5.1.0.

**Comment by Dr-wgy** [comment]
> @Dr-wgy Hi, which version are you using, this optimization was added in rocketmq-all-5.1.0.

4.7.1

**Comment by nowinkeyy** [comment]
> > @Dr-wgy Hi, which version are you using, this optimization was added in rocketmq-all-5.1.0.
> 
> 4.7.1

Versions prior to 5.1.0 did have this issue, and updating your version should alleviate the problem.

**Comment by Dr-wgy** [comment]
> > > @Dr-wgy Hi, which version are you using, this optimization was added in rocketmq-all-5.1.0.
> > 
> > 
> > 4.7.1
> 
> Versions prior to 5.1.0 did have this issue, and updating your version should alleviate the problem.


`    private boolean enableBuildConsumeQueueConcurrently = false;
`
enableBuildConsumeQueueConcurrently = true

**Comment by nowinkeyy** [comment]
> ` private boolean enableBuildConsumeQueueConcurrently = false;` enableBuildConsumeQueueConcurrently = true right？

yes, you are right.

**Comment by Dr-wgy** [comment]
if generate consumequeue slowly, Is it possible that it is blocked by index file generation  (when index file has been read or write)

**Comment by Dr-wgy** [comment]
if generate consumequeue slowly, Is it possible that it is blocked by index file generation  (when index file has been read or write)

**Comment by Dr-wgy** [comment]
> > ` private boolean enableBuildConsumeQueueConcurrently = false;` enableBuildConsumeQueueConcurrently = true right？
> 
> yes, you are right.

if generate consumequeue slowly, Is it possible that it is blocked by index file generation  (when index file has been read or write)
