### ISSUE TITLE
Should truncate the commitLog base on confirmOffset?

### ISSUE THREAD

**Issue by lanlanbaby** [apache/rocketmq#5209]
Hi Community, i have a silly question, when a slave broker will changing to master and  the slave's confirmOffset get from old master. It will recalculate the confirmOffset when `AutoSwitchHAService#changeToMaster`, buf if the slave maxOffset > confirmOffset(this broker replicates relatively fast and the confirmOffset is the one that takes the smallest value of all syncStateSets ), In this case, will it cause the inconsistent messages? should we truncate the commitLog between confirmOffset to maxOffset?

Hope all your helps.

**Comment by mxsm** [comment]
Hi @lanlanbaby   you can see this document: https://github.com/apache/rocketmq/wiki/RIP-44-Support-DLedger-Controller
section ConfirmOffset.

**Comment by lanlanbaby** [comment]
> Hi @lanlanbaby you can see this document: https://github.com/apache/rocketmq/wiki/RIP-44-Support-DLedger-Controller section ConfirmOffset.
Thanks your reply, i have readed the RIP before ask the question.

**Comment by mxsm** [comment]
> > Hi @lanlanbaby you can see this document: https://github.com/apache/rocketmq/wiki/RIP-44-Support-DLedger-Controller section ConfirmOffset.
> 
> Thanks your reply, i have readed the RIP before ask the question.

In Controller Model Broker config `allAckInSyncStateSet=true` , confirmOffset of all broker the is the same. this case not need to  truncate log.

**Comment by lanlanbaby** [comment]
> In Controller Model Broker config `allAckInSyncStateSet=true` , confirmOffset of all broker the is the same. this case not need to truncate log.

I know it's all the same about confirmOffset , because it determined by master and transfer to slave. What i asking is should we truncate the commitLog between confirmOffset to maxOffset when it's maxOffset > confirmOffset before the slave changing to master.

**Comment by lanlanbaby** [comment]
@RongtongJin would you help me understand the design idea?

**Comment by RongtongJin** [comment]
Hi @lanlanbaby, it will not truncate the slave's commitLog between confirmOffset to maxOffset before the slave changing to master.
First, the transfer of confirmOffset is delayed, if the commitLog between confirmOffset to maxOffset is truncated, messages may be lost.
In addition, we only guarantee that messages will not be lost. Messages between confirmOffset to maxOffset are uncertain (no ack to clients),  so it doesn't matter if these messages exist.

**Comment by echooymxq** [comment]
> Hi @lanlanbaby, it will not truncate the slave's commitLog between confirmOffset to maxOffset before the slave changing to master. First, the transfer of confirmOffset is delayed, if the commitLog between confirmOffset to maxOffset is truncated, messages may be lost. In addition, we only guarantee that messages will not be lost. Messages between confirmOffset to maxOffset are uncertain (no ack to clients), so it doesn't matter if these messages exist.

@RongtongJin , There should compute confirmOffset first and truncate invalid message? because the current dispatch behind data is reputFromOffset to confirmOffset, Maybe we should compute confirmOffset to maxOffset? Not sure if I'm right about this.
https://github.com/apache/rocketmq/blob/368d12516d102fa0161e2f2c4248c73d2d221024/store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java#L114-L117

**Comment by lizhimins** [comment]
Messages between these two offset may confirmed by master, so slave should compute confirmOffset to maxOffset first.

当一条日志被传输到 Follower，Follower 确认收到这条消息，主再把这条日志应用到自己的状态机时，通知客户端和通知所有的 follower 去 commit 这条日志这两件事是并行的，假如 leader 先回复 client 处理成功，此时 leader 宕机，由于其他 follower 的确认位点 confirm offset 一般会略低于 leader，中间这段未决日志还没应用到 follower 的状态机上，这时就出现了状态机不一致的情况，即已经写入 leader 的数据丢失了。所以当备切换为主的时候，直接截断，意味着客户端已经发送到服务端的消息丢失了，正确的水位应该被提升 max offset。但是备还没有收到 confirm 的 event，这个行为相当于要提交了未决消息。事实上新 leader 会遵守 "Leader Completeness" 的约定，切换时任何副本都不会删除也不会更改旧 leader 未决的 entry。新 leader 在新的 term 下，会直接应用一个较大的版本将未决的 entry 一起提交，这里副本组主备节点的行为共同保证了复制状态机的安全性。

**Comment by echooymxq** [comment]
@lizhimins @RongtongJin  Controller模式下应该不太涉及到日志状态机，我提出的疑问是：当前的代码实现，分发领先(dispatchBehind)是用confirmOffset减reputFromOffset，在切换时如果不先把confirmOffset重置到maxOffset，比如reputFromOffset=confirmOffset < maxOffset时，那truncateInvalidMsg相当于有问题了，我的理解在truncateInvalidMsg前后都应该计算一下confirmOffset。

**Comment by lizhimins** [comment]
> @lizhimins @RongtongJin Controller模式下应该不太涉及到日志状态机，我提出的疑问是：当前的代码实现，分发领先(dispatchBehind)是用confirmOffset减reputFromOffset，在切换时如果不先把confirmOffset重置到maxOffset，比如reputFromOffset=confirmOffset < maxOffset时，那truncateInvalidMsg可能就有问题了，我的理解是在truncateInvalidMsg前后都应该计算一下confirmOffset。

是的，这个和我的理解一致
- truncate 前 fix confirmOffset = maxOffset 是为了 apply unconfirmed log，这样才能不丢已提交的消息
- truncate 后 fix confirmOffset 是为了让主备对齐
