### ISSUE TITLE
Spotbugs is not compatible with latest JDK

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#5213]
> java version "18.0.1.1" 2022-04-22
>Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
>Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.2.2:spotbugs (spotbugs) on project rocketmq-logging: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:4.2.2:spotbugs failed: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rocketmq-logging

**Comment by aaron-ai** [comment]
It seems the latest spotbugs fixed this issue, but I am confused about that `SecurityManager` does not appear in the logging module.
