### ISSUE TITLE
Consumer offset of LMQ's topics were updated failed.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#5214]
In RocketMQ 4.9.3，the interface updateConsumerOffset does not check whether the topic exists or not. But in RocketMQ 5.0 do the check. LMQ's topic will not register to namesv， so it will throw error when save offset in rocketmq-mqtt.

https://github.com/apache/rocketmq-mqtt/issues/150

@DongyuanPan

**Comment by DongyuanPan** [comment]
I have created an issue yesterday. #5200
this issue can be closed
