### ISSUE TITLE
The use of the message queue allocation strategy AllocateMessageQueueStrategy in Rocketmq-client needs to be optimized

### ISSUE THREAD

**Issue by RapperCL** [apache/rocketmq#5232]
now，rocketmq provides 6 different allocation strategies，Use the AllocateMessageQueueAveragely strategy by default；
**Not so good for the use of strategies：**
**1 Hardcoded as the default AllocateMessageQueueAveragely policy**
org.apache.rocketmq.client.consumer.DefaultMQPushConsumer
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/44110731/193049441-b8c18ecd-cceb-41f6-ae14-dfc6fd58195f.png">
org.apache.rocketmq.client.consumer.DefaultLitePullConsumer
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/44110731/193049733-9ae4182c-5a8d-4a20-8126-c27a1ecc9f7f.png">

**2 Difficult to switch** 
If the user wants to modify other policies, then the user needs to modify the source code，If the user wants to modify other strategies, then the user needs to modify the source code, usually through the setAllocateMessageQueueStrategy method
 
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/44110731/193053522-92880030-9874-426d-911f-ab4bd858e346.png">

**3 Difficult to expand**
  If users want to implement their own allocation strategy, they also need to modify the source code

I want to know why it is not implemented through the spi mechanism here?
This avoids hard coding and improves usability and scalability.
And I want to solve this problem through the spi mechanism, I don't know if it is possible.

**Comment by chuanskqi** [comment]
you are a good rapper

**Comment by codersfarm** [comment]
Maybe, it's not a good idea. Consumer can setAllocateMessageQueueStrategy();
`DefaultLitePullConsumer litePullConsumer = new DefaultLitePullConsumer(MixAll.DEFAULT_CONSUMER_GROUP);
        litePullConsumer.setAllocateMessageQueueStrategy();
`
 For users , it will make trouble for users if it is implemented by other way.

**Comment by RapperCL** [comment]
> 

I know, I mentioned in point 2, this needs to modify the source code, the scalability is not good

**Comment by RapperCL** [comment]
> Maybe, it's not a good idea. Consumer can setAllocateMessageQueueStrategy();
> AllocateMessageQueueStrategy is Intreface , you can implement it by yourself
> `DefaultLitePullConsumer litePullConsumer = new DefaultLitePullConsumer(MixAll.DEFAULT_CONSUMER_GROUP); litePullConsumer.setAllocateMessageQueueStrategy(); `
> For users , it will make trouble for users if it is implemented by other way.

If use spi mechanisms, then only need to modify the RMQ corresponding configuration file, or by providing in current RMQ ServiceProvider. LoadClass, only load the first class, in this way, we can directly in the current project to add the corresponding configuration class can, need not modify the source code

**Comment by codersfarm** [comment]
@RapperCL Look this class "org.apache.rocketmq.common.utils.ServiceProvider"

**Comment by RapperCL** [comment]
> @RapperCL Look this class "org.apache.rocketmq.common.utils.ServiceProvider" and acl moudle.

Yes, I know. Now I am waiting for the reply from the community students. If possible, I will carry out the next step
