### ISSUE TITLE
Broker may lost messages in extreme condition

### ISSUE THREAD

**Issue by JosephChanChan** [apache/rocketmq#5235]
There a problem when mapfile flush message to disk. 
details see: https://github.com/apache/rocketmq/issues/3129

The measures bellow:

- message property: MessageConst.PROPERTY_WAIT_STORE_MSG_OK to true
- broker config : flushDiskType=FlushDiskType.SYNC_FLUSH

It can't ensure a message could be flush to disk. the flushedPosition would updated to writePosition even if a error was occurred. then return a PUT_OK result to producer in GroupCommitService.doCommit function

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/19208259/193216122-dd6d80dd-598e-4e16-ad2a-043b4985708c.png">

there some messages will be lost if power off now, and the producer has been received a ok response.

**Comment by codersfarm** [comment]
In most case, the data in pageCache , it is safe.
When the message is in MappedByteBuffer or FileChannel, RocketMQ think the message is safe. 
Java Program call flush(), then system flush data from pageCache to disk( it  only depends  on system)

**Comment by codersfarm** [comment]
broker config : flushDiskType=FlushDiskType.SYNC_FLUSH，should user "this.mappedByteBuffer.force()"
![image](https://user-images.githubusercontent.com/38873832/193392979-27b02a84-b4ae-4355-bc47-bb69da617818.png)

MappedByteBuffer force():
![image](https://user-images.githubusercontent.com/38873832/193393047-a7dd34e5-37d2-4a6d-90a7-bb0c12a756c1.png)
