### ISSUE TITLE
word error in doc for chinese at : 文档/生产者/基本概念  => "可以支持不用的应用场景"  should be  => "可以支持不同的应用场景"

### ISSUE THREAD

**Issue by taopanwoaini** [apache/rocketmq#5240]
word error in doc for chinese at : 文档/生产者/基本概念  => "可以支持不用的应用场景"  should be  => "可以支持不同的应用场景" ; 

The great difference between the two words is easy to cause misunderstanding;

两个词意思相差比较大, 容易造成误解;

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/32383665/193831934-3ba90f3f-ac19-47a1-9051-103b7e6aa854.png">

**Comment by nowinkeyy** [comment]
Nice, you can go to RocketMQ-site and ask for an issue and PR.

**Comment by taopanwoaini** [comment]
ok, 好的;

**Comment by nowinkeyy** [comment]
I found the place. [url](https://github.com/apache/rocketmq-site/blob/new-official-website/docs/02-%E7%94%9F%E4%BA%A7%E8%80%85/04concept1.md) This might help you.

**Comment by taopanwoaini** [comment]
thinks , 谢谢;
