### ISSUE TITLE
[Optimizate] offsetMap incremental build

### ISSUE THREAD

**Issue by kaori-seasons** [apache/rocketmq#5241]
When the current [RIP-30](https://github.com/apache/rocketmq/wiki/RIP-30-Support-Compaction-topic) does compaction, it needs to build an offsetMap. Currently, it needs to scan all message constructions, but in fact, it only needs to scan the last end point to the latest compaction position.

1. It is necessary to set a certain threshold for the storage of offset in memory, and build a secondary index after arrival

2. At this time,  base on ``` CopyAndWriteList```, if there is a request to read the offset, it will be refreshed according to the secondary index

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by complone** [comment]
cc @ltamber @duhengforever
