### ISSUE TITLE
[Optimizate] Exception scene optimization during recover

### ISSUE THREAD

**Issue by kaori-seasons** [apache/rocketmq#5242]
In [RIP-30](https://github.com/apache/rocketmq/wiki/RIP-30-Support-Compaction-topic), in the case of broker downtime, when recovering from offset, there are some abnormal edge cases that are not considered and need to be optimized

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by complone** [comment]
cc @ltamber @duhengforever

**Comment by lizhimins** [comment]
Can you describe these cases in detail

**Comment by complone** [comment]
> Can you describe these cases in detail

This is an improvement point for RIP-30, I'm working on it, will discuss with @ltamber
