### ISSUE TITLE
有小伙伴要买阿里云的服务器的吗？新用户购买贼便宜，最低99一年，参团购买https://m.aliyun.com/act/team1111/#/share?params=N.FF7yxCciiM.gr5x2rst

### ISSUE THREAD

**Issue by eicky** [apache/rocketmq#526]
有小伙伴要买阿里云的服务器的吗？新用户购买贼便宜，最低99一年，参团购买https://m.aliyun.com/act/team1111/#/share?params=N.FF7yxCciiM.gr5x2rst

**Comment by vongosling** [comment]
@eicky 这里不是发广告的地方。你的一言一行，是面向全球开发者的。
