### ISSUE TITLE
Rocketmq version 5.0.0 When I create a topic, which parameter of mqadmin updateTopic specifies the message type?

### ISSUE THREAD

**Issue by tianshimoyi** [apache/rocketmq#5261]

**Comment by xdkxlk** [comment]
You can use `-a ` to add the `message.type` attribute when updateTopic

For example:
`mqadmin updatetopic -n {NameSrvAddr} -t {YourTopic} -c {YourCluster} -a +message.type=FIFO`

The value of `message.type` can be `TRANSACTION`, `FIFO`, `DELAY` or `NORMAL`

**Comment by wwwwfw** [comment]
thank you! Solved my problem.
