### ISSUE TITLE
Start Broker failed to load the configuration file broker.conf

### ISSUE THREAD

**Issue by macdreaming** [apache/rocketmq#5267]
Deployment environment:
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-125-generic x86_64)
deploy rocketmq-5.0.0

Start Broker：
![image](https://user-images.githubusercontent.com/8703425/194979984-91451d4d-47e0-414c-8fb8-f08cb983c3b0.png)

problem：
Start Broker failed to load the configuration file broker.conf，View that the output log namesrvAddr value is empty,

![image](https://user-images.githubusercontent.com/8703425/194979801-11903cb4-2613-4164-89b6-f4d896ebb5d0.png)

![image](https://user-images.githubusercontent.com/8703425/194979752-4eed6b90-2bc9-4fd6-9874-b34bbcf14ff9.png)

![image](https://user-images.githubusercontent.com/8703425/194979738-30b3d334-02da-47ee-a444-69fa9a6eef84.png)

**Comment by lizhanhui** [comment]
After attempting to reproduce, I identify two minor issues. 

Could you please put -c /path/to/conf/file BEFORE -n xxx, and try again?

**Comment by macdreaming** [comment]
> 在尝试重现之后，我发现了两个小问题。
> 
> 你能把 -c /path/to/conf/file 放在 -n xxx 之前，然后再试一次吗？

Thanks, I'm trying!

**Comment by macdreaming** [comment]
> After attempting to reproduce, I identify two minor issues.
> 
> Could you please put -c /path/to/conf/file BEFORE -n xxx, and try again?
I tried to restart, but the problem was not solved, and the configuration file was still not loaded.
![image](https://user-images.githubusercontent.com/8703425/194985476-5d701686-dbb3-44a8-a80b-e5ee2c3a084a.png)

**Comment by macdreaming** [comment]
The deployment is normal in the Windows environment, and the configuration file is loaded normally.
![image](https://user-images.githubusercontent.com/8703425/194986875-96a24ee5-2dde-4f5f-985f-7a0cbc89d608.png)
![image](https://user-images.githubusercontent.com/8703425/194986922-6832b469-cdf2-4fb8-81fb-3212e987d12f.png)

**Comment by xdkxlk** [comment]
I have submitted a PR to fix this. Could you please review my PR?

**Comment by macdreaming** [comment]
> I have submitted a PR to fix this. Could you please review my PR?

Thank you so much. I have modified the mqbroker execution script to: while [$# - gt 0]; now the service is running normally, thank you again;

**Comment by oniubi** [comment]
> > I have submitted a PR to fix this. Could you please review my PR?
> 
> Thank you so much. I have modified the mqbroker execution script to: while [$# - gt 0]; now the service is running normally, thank you again;

I also encountered this problem,refer to the issue here, It has been solved. Thank you
