### ISSUE TITLE
AddWritePermSubCommandTest uses fixed port that may not be available

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#5276]
Tests in error: 
org.apache.rocketmq.tools.command.namesrv.AddWritePermSubCommandTest.testExecute(org.apache.rocketmq.tools.command.namesrv.AddWritePermSubCommandTest)
  Run 1: AddWritePermSubCommandTest.testExecute » Bind Address already in use
  Run 2: AddWritePermSubCommandTest.after:50 NullPointer

**Comment by lizhanhui** [comment]
Observed in https://github.com/apache/rocketmq/actions/runs/3224766162/jobs/5278048038

**Comment by echooymxq** [comment]
@lizhanhui In RocketMQ, There are others tests also use fixed port. Has the community considered using [testcontainer](https://github.com/testcontainers/testcontainers-java) to Integration Test ? 😯

**Comment by lizhanhui** [comment]
For test cases, best to use OS pick-up available port.
