### ISSUE TITLE
RocketMQ support two consumergroup with one client consume same topic?

### ISSUE THREAD

**Issue by j2gg0s** [apache/rocketmq#5287]
RocketMQ support two consumergroup with one client consume same topic?
Will there be any side effect?

**Comment by chenzlalvin** [comment]
Please refer to the doc https://rocketmq.apache.org/zh/docs/%E9%A2%86%E5%9F%9F%E6%A8%A1%E5%9E%8B/09subscription

**Comment by j2gg0s** [comment]
two consumergroup in one process(one rocketmq client) subscribe same topic, this can work right?
