### ISSUE TITLE
Admin Command issues

### ISSUE THREAD

**Issue by Black-Mamba24** [apache/rocketmq#530]
The issue tracker is **ONLY** used for bug report and feature request. Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
Trying to prepare open source user guide, Run clusterRT/checkMsgSendRT/updateBrokerConfig found issue.

- What did you expect to see?
clusterRT/checkMsgSendRT should see RT when amount is 1
updateBrokerConfig should see update messageDelayLevel normally

- What did you see instead?
clusterRT/checkMsgSendRT when amount is 1 return NaN
updateBrokerConfig messageDelayLevel change to "1s" ,the value after first blank is missing

2. Please tell us about your environment:
Linux Centos

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by ymwneu** [comment]
The first problem "clusterRT/checkMsgSendRT when amount is 1 return NaN" is indeed a bug, when amount is 1. I suggest you can propose a PR to fix it.
But i can't understand your second question, can you provide more details?

**Comment by Black-Mamba24** [comment]
ps. I think -n ip:port only support one namesrv addr, ";" in Linux Command Line is the end of command, the description should update

**Comment by Black-Mamba24** [comment]
ps. I read the code, the reason to drop the first request is reasonable, not to calculate connection time, but I will try a better way.

**Comment by ymwneu** [comment]
I tried command ./mqadmin updateBrokerConfig -k messageDelayLevel -v "1s 2s", found it can work normally.
![image](https://user-images.githubusercontent.com/8936633/48113432-cbae4380-e295-11e8-90c7-f65bfea410ec.png)
![image](https://user-images.githubusercontent.com/8936633/48113438-d49f1500-e295-11e8-9b56-90a4ce2d7364.png)

**Comment by Black-Mamba24** [comment]
@ymwneu you are right, my version is 4.2.0
