### ISSUE TITLE
There is no acl folder in the default conf directory, and the acl permission file cannot be read.

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#5301]
**There is no acl folder in the default conf directory, and the acl permission file cannot be read.**

![image](https://user-images.githubusercontent.com/18254437/195514293-d5792974-2b12-4990-9faa-0f29106e6272.png)
![image](https://user-images.githubusercontent.com/18254437/195514377-89b566c8-4c51-4184-866f-72928e33840e.png)

**Comment by echooymxq** [comment]
IMHO, it's behavior normal, because there are no other acl files, there is certainly no need to read. it should be created manually when there are have more acl files?🤔️

**Comment by caigy** [comment]
There are two valid locations of ACL config files: https://github.com/apache/rocketmq/blob/develop/docs/cn/acl/RocketMQ_Multiple_ACL_Files_%E8%AE%BE%E8%AE%A1.md#1-acl%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%AD%98%E5%82%A8%E8%B7%AF%E5%BE%84

For compatibility, `conf/plain_acl.yml` remains as default ACL config file in distribution. If uses want to define multiple config files, they should put them in `conf/acl/`.

**Comment by zhangjidi2016** [comment]
> IMHO, it's behavior normal, because there are no other acl files, there is certainly no need to read. it should be created manually when there are have more acl files?🤔️

You may not understand the meaning of this issue. The default acl file path set in the code is {ROCKETMQ_HOME}/conf/acl, but the conf directory after the installation package is decompressed does not have this directory, and the broker cannot read the acl file after acl is enabled
