### ISSUE TITLE
Authentication cannot be performed for sending batch messages

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq#5303]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
**Enable acl and send batch messages，set the topic pub and sub permission is deny**

- What is expected to see?
**Failed to send the message because there is no permission**

- What did you see instead?
**Send success**

2. Please tell us about your environment:
**5.0.1-SNAPSHOT**

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by codersfarm** [comment]
ACL modle belongs to you

**Comment by codersfarm** [comment]
The broker upgrade 5.0，acl modle should not forget
