### ISSUE TITLE
executeSendMessageHookAfter not get the result

### ISSUE THREAD

**Issue by lemonzone2010** [apache/rocketmq#531]
**BUG REPORT**
Please describe the issue you observed:
- I can't get code and errorMsg in SendMessageContext when running SendMessageProcessor.executeSendMessageHookAfter

Please tell us about your environment:
- 4.3.1

Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

I have checked the code.  **SendMessageProcessor.handlePutMessageResult** always returns null.
```java
     if (sendOK) {
            //xxxxxx
            return null;
       } 
```
So the code **response != null**  is false all the time.

```java
    public void executeSendMessageHookAfter(final RemotingCommand response, final SendMessageContext context) {
        if (hasSendMessageHook()) {
            for (SendMessageHook hook : this.sendMessageHookList) {
                try {
                    if (response != null) {
                      //xxxxx
                        context.setCode(response.getCode());
                        context.setErrorMsg(response.getRemark());
                    }
                    hook.sendMessageAfter(context);
                } catch (Throwable e) {
                    // Ignore
                }
            }
        }
    }
```

**Comment by lemonzone2010** [comment]
[PR #533 ](https://github.com/apache/rocketmq/pull/533)

**Comment by ymwneu** [comment]
I checked the code, found
`if (sendOK) {
            //xxxxxx
           doResponse(ctx, request, response);
            //xxxxxx
            return null;
 } `
method doResponse had already processed the response. 
In addition, feature SendMessageHook seems to be deprecated, i found no where use this hook in broker.

**Comment by lemonzone2010** [comment]
> I checked the code, found
> `if (sendOK) {`
> ` //xxxxxx`
> ` doResponse(ctx, request, response);`
> ` //xxxxxx`
> ` return null;`
> `}`
> method doResponse had already processed the response.
> In addition, feature SendMessageHook seems to be deprecated, i found no where use this hook in broker.

- The method doResponse doesn't affect the SendMessageHook running.
- I added some SendMessageHook in broker for tracing message,then i found this issue. Close it if you're sure SendMessageHook will be deprecated

**Comment by ymwneu** [comment]
I have  seen your PR, i think it will cause a response send twice.

**Comment by ymwneu** [comment]
My mistake, i am not sure SendMessageHook will be deprecated.
I think in method executeSendMessageHookAfter, if response equals null, it means the message has been sent successful, so there is no need to set error message.
