### ISSUE TITLE
improving SDK topic route availability, when namsrv  restart

### ISSUE THREAD

**Issue by fuyou001** [apache/rocketmq#5322]
- What did you do (The steps to reproduce)?

sdk send message thrown topic not exists Exception,when namesrv restart and  broker register topic unfinished

ps:
     the feature was released  three years ago in  aliyun RocketMQ.

**Comment by complone** [comment]
Can you give the relevant log error information?

**Comment by fuyou001** [comment]
> Can you give the relevant log error information?

you can get TOPIC_NOT_EXIST response code and error msg is：No topic route info in name server for the topic

**Comment by complone** [comment]
> > Can you give the relevant log error information?
> 
> you can get TOPIC_NOT_EXIST response code and error msg is：No topic route info in name server for the topic

thanks

**Comment by lizhanhui** [comment]
Close as its PR is merged.
