### ISSUE TITLE
When introducing Rockemq Dledger on the official website, there is no explanation of the difference between "rapid deployment and cluster deployment", which is easy to misunderstand

### ISSUE THREAD

**Issue by wps123456** [apache/rocketmq#5329]
When introducing Rockemq Dledger on the official website, there is no explanation of the difference between "rapid deployment and cluster deployment", which is easy to misunderstand
**1：For my questions**
When setting up the Rocketmq ledger, there are two methods introduced on the official website, one is "Dledger fast setting up（Dledger快速搭建）",the other is "Dledger cluster setting up（Dledger集群搭建）".
The first one needs to download and package the source code of the ledger, and the second one does not. My question is: 1: What are the differences between the two? Are they the same? 2: If only the second step is followed, is it feasible not to download the source code of the Dledger？ 3：What is the purpose of installing the ledger? I took a look at bin/dimmer/fast try sh。 When you execute start all, you still use three configuration files.
**2：Answer from Apache RocketMQ Community**
1）.    The "Dledger fast setup（DLedger快速搭建）" part introduced the way while you would like to quick-start or test the DLedger mode of RocketMQ locally. In other words, fast-try.sh will launch the nodes within three different processes on your local machine (as you could see in the doc, the addresses of those three nodes are the same but have different ports). This is available for the developers who have the needs of debugging or trying DLedger mode efficiently.
For the “DLedger Cluster setup (DLedger集群搭建)” part, it is for someone who wants to build the cluster of RocketMQ running DLedger mode in production environment (different machines) if the cluster requires the fail-over ability provided by Raft.
In brief conclusion, the first part is for someone who wants to quick-try the DLedger mode locally, and the second part is for someone who would like to run RocketMQ with DLedger mode in the actual production environment (e.g., in RocketMQ cluster).
2).    Of course, you could run the second step independently without downloading the source release of DLedger project since the RocketMQ project has already involved the DLedger dependency in the library.
3).   Those three files are the configuration for you to quick-launch the nodes locally. It is more likely for the testing purpose. I guess the doc just want to show how to get the DLedger project and build it, but it seems like there is no need for installing it separately. This might be a problem of our documentation, which you are welcome to propose a GitHub issue for it.

**I suggest adding this part of the introduction to the document to facilitate other community members to understand Rocketmq ledger mode**

**Comment by RongtongJin** [comment]
@wps123456 Good idea. Could you submit a PR to [this repo](https://github.com/apache/rocketmq-site) to fix the issue?

**Comment by wps123456** [comment]
ok，I will propose a Mr




ヤ艾枫o.--
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] When introducing Rockemq Dledger on the official website, there is no explanation of the difference between "rapid deployment and cluster deployment", which is easy to misunderstand (Issue #5329)





 
@wps123456 Good idea. Could you submit a PR to this repo to fix the issue?

**Comment by wps123456** [comment]
the doc has changed 

https://github.com/apache/rocketmq-site/pull/341
