### ISSUE TITLE
How to use Rocketmq Ledger cluster mode for spring boot？

### ISSUE THREAD

**Issue by onejimmyboy** [apache/rocketmq#5330]
Rocketmq Ledger is a highly available cluster. When the master node fails, the slave node will become the master. I want to know when the Rocketmq Ledger cluster has been set up. How to configure the cluster using spring boot.
When the following configurations are used, sending messages is normal when all three nodes are normal.
When the master node is shut down, one of the remaining two nodes becomes the master node. But the producer stops sending messages. At this time, you need to restart the spring boot service to use the 2-node cluster normally.
If the spring boot project is not restarted after the master is down, continue to complete the generation
![Uploading image.png…]()

**Comment by wps123456** [comment]
The rocketmq version is 4.8.0

**Comment by wps123456** [comment]
the spring boot configure:
server:
  port: 8080
rocketmq:
  name-server: xxxx1:9876;xxxx2:9876;xxxx3:9876;
  producer:
    group: group1
    access-key: test001
    secret-key: Admin@123
    retryNextServer: true

**Comment by wps123456** [comment]
when I use rocketmq 5.0 ,the error always exists. The error info about spring boot project is：
RocketmqRomoting：closeChannel: close the connection to remote address[] result: true
