### ISSUE TITLE
Resolve the unstable unit tests

### ISSUE THREAD

**Issue by echooymxq** [apache/rocketmq#5331]
Hi community, as we see, the rocketmq unit tests running in github actions is often unstable. Especially, there are many asynchronous assertion timeout tests and often timeout at different os environment. so i want to open the issue to tracking these types of problems and resolve it. Looking forward to hearing your suggestions.

**Comment by tsunghanjacktsai** [comment]
Hi @echooymxq ,

Great idea. Our CI has been unstable for a while, and definitely need someone to fix it. You could separate this issue into several sub-issues to solve them one by one.

**Comment by lizhanhui** [comment]
Great to see you are about to enhance the quality of test cases.

**Comment by lizhanhui** [comment]
@tsunghanjacktsai  As for "Our CI has been unstable for a while", It's not the CI that is unstable... the test cases are actually the root cause and should be the place where efforts should be invested.

**Comment by BiggerBrain** [comment]
> I also believe that the quality of rocketmq unit testing needs to be improved, and I would love to be a part of that effort

**Comment by codersfarm** [comment]
Good idea @echooymxq
