### ISSUE TITLE
Doucument 5.0 QuickStart seems not a newest  one

### ISSUE THREAD

**Issue by MumfordSons** [apache/rocketmq#5335]
**I am a new user of rocketMQ and following official document build my test project. there are some errors confused me**
**1. create topic by myadmin**
![image](https://user-images.githubusercontent.com/45234194/196136535-b3fe53ce-7127-4e6c-a0aa-99dce789d9e7.png)
**the result show help info..**
![image](https://user-images.githubusercontent.com/45234194/196136888-47a82d2c-e0b1-4330-a65e-a1a21f94181e.png)
**need to assign broker address**
![image](https://user-images.githubusercontent.com/45234194/196137428-e4361a24-c0ab-4f9a-ab5b-e0f9c4c2976d.png)

**2. java project example, some exception are:**
![image](https://user-images.githubusercontent.com/45234194/196138831-9a64b0e5-3f7d-4a80-b647-d1e13bf20c12.png)

**Comment by Oliverwqcwrw** [comment]
Hello @MumfordSons ,

This error will be reported if proxy is not enabled at startup,

you can use this command to to try it

`nohup sh bin/mqbroker -n localhost:9876 --enable-proxy &`

**Comment by MumfordSons** [comment]
![image](https://user-images.githubusercontent.com/45234194/196314643-305863c8-32f8-4e17-8322-a1ffe2e70fbe.png)


> Hello @MumfordSons ,
> 
> This error will be reported if proxy is not enabled at startup,
> 
> you can use this command to try it
> 
> `nohup sh bin/mqbroker -n localhost:9876 --enable-proxy &`

**Comment by MumfordSons** [comment]
> Hello @MumfordSons ,
> 
> This error will be reported if proxy is not enabled at startup,
> 
> you can use this command to try it
> 
> `nohup sh bin/mqbroker -n localhost:9876 --enable-proxy &`

thanks. i typed a wrong proxy address😂
