### ISSUE TITLE
Two instance consumers in the same machine will both consume message in the mode of CLUSTERING.

### ISSUE THREAD

**Issue by zhangdp-taozi** [apache/rocketmq#534]
There is a consumer in my application, I start this application twice with different ports, then there are two instance of application, and there are two consumers in the same machine. But the message is consumed in both consumers, but the consumers are set to CLUSTERING mode. 
I checked in the rocketmq-console, the two consumers have same customerid.

**Comment by vongosling** [comment]
This is normal behavior if you use the same consumer id @zhangdp-taozi please follow the issue template and read carefully, this is not the rational place for user question. Any question, please send to RocketMQ user [email-list](http://rocketmq.apache.org/about/contact/). Thanks for your comprehension.

**Comment by vongosling** [comment]
If you could be careful of the code of the RocketMQ parts - how to create a instanceId, you will find the answer. As for consumerId, you could set the same consumerid to assemeble a cluster to consume together;
