### ISSUE TITLE
[RIP-48] Support server-side offset management in broadcast consumption mode

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq#5348]
doc: https://github.com/apache/rocketmq/wiki/RIP-48-Enhance-server-side-offset-management-ability

pr: https://github.com/apache/rocketmq/pull/5349 Support server-side offset management in broadcast consumption mode

**Comment by ni-ze** [comment]
what is the different between this and [pr-5349](https://github.com/apache/rocketmq/pull/5349),
the same rip with two parts?
