### ISSUE TITLE
How to optimize storage jitter problem when rocketmq deployed on server with HHD disk.

### ISSUE THREAD

**Issue by liuliuwd** [apache/rocketmq#535]

**Comment by ymwneu** [comment]
I suggest you provide more detail, and ask this question by using mailing list.
http://rocketmq.apache.org/about/contact/

**Comment by dongeforever** [comment]
@liuliuwd Make sure there is enough memory, and make more data on page cache. BTW, enable the storeTransientPool could be a help.
