### ISSUE TITLE
[RIP 51] Task2: Add notification mechanism for pop orderly.

### ISSUE THREAD

**Issue by xdkxlk** [apache/rocketmq#5365]
RIP Link: https://github.com/apache/rocketmq/wiki/RIP-51-Pop-orderly-improvement#add-notification-mechanism-for-pop-orderly

**Comment by lizhanhui** [comment]
> We can use an in-memory timer to record the time at which the lock is released. When the time is up, check to see if there is a message that can be pulled and if so, wake up the pending long polling request.

I do not see the reason why an in-memory timer is required. Once a previous pop request that holds the lock completes, why not simply dispatch a task to check if there is an await pop request held in the chain... On the completion of on request, fire a second in consecutive.
