### ISSUE TITLE
Is proxy useful when my client use rocketmq-client instead of rocketmq-client-java?

### ISSUE THREAD

**Issue by daigoopautoy** [apache/rocketmq#5368]
I want to use rocketmq 5.0, and I see [quickstart](https://rocketmq.apache.org/zh/docs/quickStart/02quickstart) recommend I use `org.apache.rocketmq.rocketmq-client-java` for my client. I find it connect to proxy instead of namesrv but is losts many feature compare with `org.apache.rocketmq.rocketmq-client`, such as `DefaultMQProducer#setSendLatencyFaultEnable`,`DefaultMQPushConsumer#setConsumeFromWhere`, `DefaultMQPushConsumer#setMessageModel`. 

If I use `org.apache.rocketmq.rocketmq-client`, client will connect to namesrv like 4.x, I want to know Is proxy useful on this condition?

**Comment by xdkxlk** [comment]
Support remoting protocol in rocketmq proxy module is in progress

**Comment by daigoopautoy** [comment]
> Support remoting protocol in rocketmq proxy module is in progress

sorry, i don't know your mean. I guess some features likes `DefaultMQProducer#setSendLatencyFaultEnable`,`DefaultMQPushConsumer#setConsumeFromWhere`, `DefaultMQPushConsumer#setMessageModel` on client in 4.x have already transformed to proxy in 5.x and I should use proxy to administer all clients?
