### ISSUE TITLE
is this necessary to call fileWatchService's shutdown method twice?

### ISSUE THREAD

**Issue by thezp** [apache/rocketmq#5372]
there are two places in BrokerController.java that fileWatchService's shutdown method is called :
line 1276:1278
<img width="427" alt="image" src="https://user-images.githubusercontent.com/7849032/196996621-54a7fd5b-ad3c-4f8b-a398-ebf5c3e86973.png">
and line 1357:1359
<img width="423" alt="image" src="https://user-images.githubusercontent.com/7849032/196996798-f8b82c77-482b-43df-85dd-36c5794a2d18.png">
i think the second call is unnecessary because the second call will do nothing as variable started is false in ServiceThread
<img width="932" alt="image" src="https://user-images.githubusercontent.com/7849032/197003701-a571e2b4-84be-469a-8997-a25c02be5cdb.png">
so we can delete line 1357:1359 safely

**Comment by nowinkeyy** [comment]
I agree with you.
