### ISSUE TITLE
NameSrv does not output the bindaddress when starting

### ISSUE THREAD

**Issue by xiaoyifang** [apache/rocketmq#5373]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
When start the NameSrv process ,the output in the console does not include the bind address

- What is expected to see?

- What did you see instead?
"The Name Server boot success. serializeType=JSON"

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

expected result :
the NameSrv can output the bindaddress for investigation .

**Comment by mxsm** [comment]
Hi @xiaoyifang  before you submit a pr that  you can create issue for it. you can see this doc that PR how to link issue.
https://docs.github.com/cn/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue.  when the pr is megered then the issue linked closed automatic.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/197319365-79046895-7447-442f-9a1a-13d2fb14c4c7.png)
 
I do not have the permission to link the PR.

**Comment by mxsm** [comment]
> ![image](https://user-images.githubusercontent.com/105986/197319365-79046895-7447-442f-9a1a-13d2fb14c4c7.png)
> 
> I do not have the permission to link the PR manually.
> 
> and I changed the commit message to connect with this issue still has no effect.

Before you submit PR first

**Comment by xiaoyifang** [comment]
I indeed create the PR first then this very issue next.

I think maybe next time I'll create the issue first.
