### ISSUE TITLE
countDownLatch.await in necessary in queryMessage

### ISSUE THREAD

**Issue by codersfarm** [apache/rocketmq#5380]
![1](https://user-images.githubusercontent.com/38873832/197331742-5a4e64b9-48c7-4fa8-bddc-868cacc02eca.png)

In MQAdminImpl.class, queryMessage method, `CountDownLatch countDownLatch = new CountDownLatch(brokerAddrs.size());` the size  is brokerAddrs.size(),

![2022-10-22_165833](https://user-images.githubusercontent.com/38873832/197331095-931e1261-0704-4935-90da-aabc004d5125.png)

And countDownLatch countDown  finally.If some broker failed, it should catch exception, why need this method  below `boolean ok = countDownLatch.await(timeoutMillis * 4, TimeUnit.MILLISECONDS);`

**Comment by nowinkeyy** [comment]
The ```finally{}``` will executes whether or not it catches the exception, the method ```boolean ok = countDownLatch.await(timeoutMillis * 4, TimeUnit.MILLISECONDS);``` just used to block thread until countdownLatch goes to zero. If some broker failed, the countdownLatch cann't return to zero, the method ```await()``` will time out and the thread will log.warn.

**Comment by codersfarm** [comment]
The countDownLatch‘s size equals brokerAddrs.size(),  `finally{}` is in for loop(loop size equals brokerAddrs.size())，when for loop executes the countDownLatch goes zero whether the broker failed or not. Is this right? 

- if true, the method `boolean ok = countDownLatch.await(timeoutMillis * 4, TimeUnit.MILLISECONDS);` maybe no use.
- if false, even if the broker failed and countDownLatch>=1, the method will execute 24 seconds. for users query message by eByUniqKey

> The `finally{}` will executes whether or not it catches the exception, the method `boolean ok = countDownLatch.await(timeoutMillis * 4, TimeUnit.MILLISECONDS);` just used to block thread until countdownLatch goes to zero. If some broker failed, the countdownLatch cann't return to zero, the method `await()` will time out and the thread will log.warn.

**Comment by nowinkeyy** [comment]
Hi @codersfarm ,
IMO, I think the countDownLatch will goes zero whether the broker failed or not. And i think the purpose of this ```await()``` method is to wait for the for loop to complete so that the ```queryResultList``` results  of querying all brokers can be retrieved.
 The ```queryResultList``` is incomplete without the ```await()``` method waiting for the completion of the for loop.

![image](https://user-images.githubusercontent.com/72536832/197370650-ab0054d9-0fa0-4f12-866b-8e422c8758d0.png)
![image](https://user-images.githubusercontent.com/72536832/197370613-da5dc0cd-b067-496b-b361-3db9743cd994.png)

**Comment by codersfarm** [comment]
Thanks

**Comment by codersfarm** [comment]
Thanks. Main thead is blocked by countDownLatch  until sub thead complete. The countDownLatch will goes zero, `countDownLatch.await(timeoutMillis * 4, TimeUnit.MILLISECONDS)` execute immediately. The query `this.mQClientFactory.getMQClientAPIImpl().queryMessage(addr, requestHeader, timeoutMillis * 3` is `timeoutMillis * 3`,and the `countDownLatch.await` is `timeoutMillis * 4`.
![2022-10-24_090335](https://user-images.githubusercontent.com/38873832/197429810-3535156a-d1cf-4f51-bee6-3e1c22e528b4.png)
![2022-10-24_090408](https://user-images.githubusercontent.com/38873832/197429813-d20b5e6d-9416-45df-bb69-629bd973af66.png)

**Comment by codersfarm** [comment]
Thanks. Main thead is blocked by countDownLatch until sub thead complete. The countDownLatch will goes zero, countDownLatch.await(timeoutMillis * 4, TimeUnit.MILLISECONDS) execute immediately. The query this.mQClientFactory.getMQClientAPIImpl().queryMessage(addr, requestHeader, timeoutMillis * 3 is timeoutMillis * 3,and the countDownLatch.await is timeoutMillis * 4.
2022-10-24_090335
2022-10-24_090408

> Hi @codersfarm , IMO, I think the countDownLatch will goes zero whether the broker failed or not. And i think the purpose of this `await()` method is to wait for the for loop to complete so that the `queryResultList` results of querying all brokers can be retrieved. The `queryResultList` is incomplete without the `await()` method waiting for the completion of the for loop.
> 
> ![image](https://user-images.githubusercontent.com/72536832/197370650-ab0054d9-0fa0-4f12-866b-8e422c8758d0.png) ![image](https://user-images.githubusercontent.com/72536832/197370613-da5dc0cd-b067-496b-b361-3db9743cd994.png)
