### ISSUE TITLE
Variable of LatencyFaultToleranceImpl#whichItemWorst does not present the worst item

### ISSUE THREAD

**Issue by jasonjavaYY** [apache/rocketmq#5404]
the source code in rocketMQ is as follows:
Collections.sort(tmpList);
final int half = tmpList.size() / 2;
if (half <= 0) {
     return tmpList.get(0).getName();
} else {
     final int i = this.whichItemWorst.incrementAndGet() % half;
     return tmpList.get(i).getName();
}
According to the sorting rule of FaultItem, the last item in the tmpList is the worst, But the method returns a random element in the first half of the array.

The steps to reproduce
1、run the follow code:
atencyFaultToleranceImpl impl = new LatencyFaultToleranceImpl();
impl.updateFaultItem("a",10000,10000);
impl.updateFaultItem("b",20000,10000);
impl.updateFaultItem("c",30000,10000);
impl.updateFaultItem("d",40000,10000);
System.out.println(impl.pickOneAtLeast());
2、expected to see:
return "d", because "d" is the worst item.
3、the real output instead:
return "a" or "b".

**Comment by codersfarm** [comment]
Maybe the  variable `whichItemWorst`  name is ambiguous. i think. The method `LatencyFaultToleranceImpl#pickOneAtLeast` select one  broker from `faultItemTable` for current thread, because the client will retry send messages if send fail.

**Comment by jasonjavaYY** [comment]
I agree with you, but the variable name should be corrected to avoid ambiguity
