### ISSUE TITLE
Orderly message backlog problem help

### ISSUE THREAD

**Issue by noseew** [apache/rocketmq#5405]
When using orderly consumption, message backlog occurs occasionally, and subsequent messages are not consumed. Restart the consumption application to take effect.

Under the same topic, there is no problem with other machines and other queues. It only occurs in some queues of some machines. Both machines and queues are episodic.

No log of consumption failure was found, and no consumption thread was found that has been running. Occurred in the production line environment, but not in the test environment;

May I ask how to rectify this situation? Thanks for the directions

Rocketmq version 4.7.0
JDK version 1.8

**Comment by shy-share** [comment]
Hi, @noseew The background you give is too little to determine what problems are caused, usually it is difficult to troubleshoot occasional bugs, only the stable recurrence of bugs will be easier to solve.
