### ISSUE TITLE
The offset of PopReviveGroup unable to move forward when there are more ack than ck

### ISSUE THREAD

**Issue by xdkxlk** [apache/rocketmq#5408]
The steps to reproduce
1. Send some messages
2. Pop messages normally from broker, and for each message all ack more than two times
3. Not to pop any more messages

We will see, the consumer offset of CID_RMQ_SYS_REVIVE_GROUP cannot move to the max offset because there will be no matching ck in the future
And this problem will be more obvious when set enablePopBufferMerge to true
As a result, resources have been wasted to repeatedly pull the messages in PopReviveTopic

**Comment by lizhanhui** [comment]
Nice catch
