### ISSUE TITLE
TransactionalMessageBridge.writeOp Duplicate recording of metrics data 

### ISSUE THREAD

**Issue by RapperCL** [apache/rocketmq#5415]
In the putMessageReturnResult method, the relevant data has been recorded, and the result is repeated in the writeOp method.
![image](https://user-images.githubusercontent.com/44110731/198508045-28745cb7-ce06-407d-8044-1c4d9cd692ba.png)
![image](https://user-images.githubusercontent.com/44110731/198508132-519c420e-84b8-4e50-a2fa-1cf98d8584ab.png)

**Comment by RongtongJin** [comment]
@RapperCL Good catch!
