### ISSUE TITLE
consumeExecutor use LinkedBlockingQueue which is not bounded as param of ThreadPoolExecutor

### ISSUE THREAD

**Issue by xiaobing395845388** [apache/rocketmq#5417]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:
in this case,consumeThreadMin work as coresize, and consumeThreadMax does work and my cause oom error in high flow

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by xiaobing395845388** [comment]
in this case,consumeThreadMin work as coresize, and consumeThreadMax does work and my cause oom error in high flow

**Comment by nowinkeyy** [comment]
Hi @xiaobing395845388 ,
IMO, you mean unbounded ```LinkedBlockingQueue```, and ```consumeThreadMax```  is too small resulting in OOM.
My suggestion is to increase the value of ```consumeThreadMax``` to speed up message processing and decrease the value of ```pullThresholdForQueue``` to reduce the number of messages cached by the client.

**Comment by shy-share** [comment]
> Hi @xiaobing395845388 , IMO, you mean unbounded `LinkedBlockingQueue`, and `consumeThreadMax` is too small resulting in OOM. My suggestion is to increase the value of `consumeThreadMax` to speed up message processing and decrease the value of `pullThresholdForQueue` to reduce the number of messages cached by the client.

@xiaobing395845388  Indeed, LinkedBlockingQueue is suitable for situations where producing messages and consuming messages are about the same, and when you produce messages significantly faster than you consume them, it naturally leads to oom

**Comment by pipi18** [comment]
Consumer use `LinkedBlockingQueue ` may trigger flow control to  aviod OOM.  When messages are greater or equal than 1000, or the  the memory is greater 100M.

**Comment by xiaobing395845388** [comment]
> 



> > Hi @xiaobing395845388 , IMO, you mean unbounded `LinkedBlockingQueue`, and `consumeThreadMax` is too small resulting in OOM. My suggestion is to increase the value of `consumeThreadMax` to speed up message processing and decrease the value of `pullThresholdForQueue` to reduce the number of messages cached by the client.
> 
> @xiaobing395845388 Indeed, LinkedBlockingQueue is suitable for situations where producing messages and consuming messages are about the same, and when you produce messages significantly faster than you consume them, it naturally leads to oom
In this case, consumeThreadMax does no work if use LinkedBlockingQueue , consumeThreadMIn is the corePoolSize in the api of "ThreadPoolExecutor"
you say"producing messages and consuming messages are about the same", we cannot controll this in product env

**Comment by fuyou001** [comment]
@xiaobing395845388 ,what's your application JVM arguments about jvm  memory setting?

if you want to avoid oom ,you can set DefaultMQPushConsumer  arguments

```
org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#pullThresholdForTopic
org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#pullThresholdForQueue
org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#pullThresholdSizeForTopic
```

**Comment by lizhanhui** [comment]
@fuyou001 How about making these configurable items heuristic, say, adjust them according to JVM heap size on start-up?

**Comment by lizhanhui** [comment]
We essentially need a smarter back-pressure mechanism to protect against memory thrashing.

**Comment by xiaobing395845388** [comment]
The key point that i want to express is not 'oom' but only 'consumeThreadMin 'works as corepoolsize, param 'consumeThreadMax 'does not work

**Comment by sunheyi6** [comment]
> The key point what i want to express is not 'oom' but only 'consumeThreadMin 'works as corepoolsize, param 'consumeThreadMax 'does not work我想表达的关键点不是'oom'而是只有'consumeThreadMin'作为corepoolsize起作用，param'consumeThreadMax'不起作用

Will it be because the consumer's workload is insufficient to require additional threads, so consumeThreadMax does not take effect?
