### ISSUE TITLE
When first Store message  mappedFile is null ，Concurrency create will more one mappedFile

### ISSUE THREAD

**Issue by jiangxinlingdu** [apache/rocketmq#542]
**BUG REPORT**

1. Please describe the issue you observed:

When first Store message  mappedFile is null ，Concurrency create will more one mappedFile.

- What did you do (The steps to reproduce)?
  
when startup mqnamesvr and broker and producer send message

- What did you expect to see?

one commitlog like file name: 00000000000000000000

- What did you see instead?

![](https://user-images.githubusercontent.com/6373972/48544999-e02ab580-e8ff-11e8-81c3-ce43cdaf3303.png)
![](https://user-images.githubusercontent.com/6373972/48545051-fcc6ed80-e8ff-11e8-98fd-3c1404f560b3.png)

2. Please tell us about your environment:

rocketmq-release-4.3.2

**Comment by ymwneu** [comment]
In fact, it's not a bug. 
The method "getLastMappedFile(final long startOffset)" will invoke "getLastMappedFile()" again before create a new mappedFile.

**Comment by jiangxinlingdu** [comment]
> In fact, it's not a bug.
> The method "getLastMappedFile(final long startOffset)" will invoke "getLastMappedFile()" again before create a new mappedFile.

ok

**Comment by ymwneu** [comment]
If the switch "transientStorePoolEnable" is on && the flushType equals "ASYNC_FLUSH" && broker is master && transientStorePool buffer is enough, broker will create two mappedFiles. For more information, you can see "AllocateMappedFileService#putRequestAndReturnMappedFile".

**Comment by jiangxinlingdu** [comment]
> If the switch "transientStorePoolEnable" is on && the flushType equals "ASYNC_FLUSH" && broker is master && transientStorePool buffer is enough, broker will create two mappedFiles. For more information, you can see "AllocateMappedFileService#putRequestAndReturnMappedFile".

i see

**Comment by jiangxinlingdu** [comment]
> Under normal circumstances, the broker will create two mappedFiles in advance. For more information, you can see "AllocateMappedFileService#putRequestAndReturnMappedFile".

Thanks!

**Comment by jiangxinlingdu** [comment]
Thank you very much for your response. I wish rocketmq better and better.
