### ISSUE TITLE
mqbroker: 48: [[: not found 

### ISSUE THREAD

**Issue by dyrnq** [apache/rocketmq#5423]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
```bash
sh -c "${ROCKETMQ_HOME}/bin/broker -c ${ROCKETMQ_HOME}/conf/broker.conf"
```
- What is expected to see?
start broker
- What did you see instead?
```bash
mqbroker: 48: [[: not found
```
2. Please tell us about your environment:
ubuntu 20.04 [rocketmq-all-5.0.0-bin-release.zip](https://dlcdn.apache.org/rocketmq/5.0.0/rocketmq-all-5.0.0-bin-release.zip)
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

bin/broker has a `#!/bin/sh` shebang but use [[ in line 48 "while [[ $# -gt 0 ]]; do"

**Comment by RongtongJin** [comment]
@dyrnq IIRC, the bug has been fixed in this [PR](https://github.com/apache/rocketmq/pull/5269).

**Comment by lizhanhui** [comment]
Close as duplicated
