### ISSUE TITLE
What is the jar package name of StatusRuntimeException

### ISSUE THREAD

**Issue by jasonjavaYY** [apache/rocketmq#5428]
When I execute mvn package, an error is reported in the GrpcClientChannel Class because StatusRuntimeException cannot be found. However, I have imported all the jar packages of grpc. I want to know what the jar package name of StatusRuntimeException is~

**Comment by shy-share** [comment]
> 

Hi, @jasonjavaYY This problem can be solved by looking at the source code.

`package io.grpc;

import javax.annotation.Nullable;

public class StatusRuntimeException extends RuntimeException {
  private static final long serialVersionUID = 1950934672280720624L;
  private final Status status;
  private final Metadata trailers;
  private final boolean fillInStackTrace;`

**Comment by jasonjavaYY** [comment]
Thank you  so much. I have solved the problem, because the pom file of grpc-netty-shaded is incorrect, the jar of grpc-api has not been introduced.
