### ISSUE TITLE
消息重试后不知道为啥，就是不进入我的死信队列

### ISSUE THREAD

**Issue by shenmiren0002** [apache/rocketmq#5439]
各位大佬，能帮我看看我重复消费后，连死信队列都没生成

![image](https://user-images.githubusercontent.com/72213250/199026961-93cac351-929b-4a0e-a030-8a2b5da0af56.png)
![image](https://user-images.githubusercontent.com/72213250/199027121-dd791316-f778-453f-aedc-3eccef1d2e17.png)
![image](https://user-images.githubusercontent.com/72213250/199027157-1ae5bb44-f0ec-4a49-b2fa-d60bfdb14f5f.png)

**Comment by mxsm** [comment]
@shenmiren0002  Whether you can provide more information? RocketMQ version, source code and so on

**Comment by mxsm** [comment]
@shenmiren0002 I use rocketmq5.0 and rocketmq-spring version 2.2.2
```java
    <dependency>
      <groupId>org.apache.rocketmq</groupId>
      <artifactId>rocketmq-spring-boot-starter</artifactId>
      <version>2.2.2</version>
    </dependency>
```
broker.conf
![image](https://user-images.githubusercontent.com/15797831/199198819-ff231313-0fab-4232-9f36-cacce7fd676c.png)

consume code:
```java
package com.github.mxsm.rocketmq;

import org.apache.rocketmq.spring.annotation.RocketMQMessageListener;
import org.apache.rocketmq.spring.core.RocketMQListener;
import org.springframework.stereotype.Service;

@Service
@RocketMQMessageListener(topic = "mxsm",consumerGroup = "mxsm")
public class HelloConsume implements RocketMQListener<String> {
    @Override
    public void onMessage(String s) {
        throw new IllegalArgumentException("test");
    }
}
```
result after 16 times :
![image](https://user-images.githubusercontent.com/15797831/199199289-98c7a12e-dde9-4078-bd31-77be41ba0d25.png)

I think you can adjust broker config :
```properties
messageDelayLevel=1s 5s
```
 messageDelayLevel implication you can see the document of official website.

you can check the code of you.

**Comment by mxsm** [comment]
@shenmiren0002 you create DefaultMQPushConsumer as bean that can't automatic injection. you can see the rocketmq-spring-boot-starter source code, if you want to setting you can use RocketMQMessageListener annotation to do this.

**Comment by shenmiren0002** [comment]
thank you so much .I have solved it after I deleted queue and install a new queue.

> @shenmiren0002 you create DefaultMQPushConsumer as bean that can't automatic injection. you can see the rocketmq-spring-boot-starter source code, if you want to setting you can use RocketMQMessageListener annotation to do this.

thank you so much.I have solved it after I deleted queue and created a new queue
