### ISSUE TITLE
[code]is the refcount's  set value correct?

### ISSUE THREAD

**Issue by xiaoyifang** [apache/rocketmq#5440]
https://github.com/apache/rocketmq/blob/a62b70bc25423c1d7e18043e32af427d29ef9ac4/store/src/main/java/org/apache/rocketmq/store/ReferenceResource.java#L50-L51

should ` this.refCount.set(-1000 - this.getRefCount());` be 
` this.refCount.set(-1000 + this.getRefCount());`

**Comment by nowinkeyy** [comment]
IMO, the set operation mainly sets the ```refCount``` to negative so that cleanupOver can be forced after a timeout. So if you use +, the ```refCount``` might still be positive. (The way I understand it, it's probably better to just make ```refCount``` negative)

**Comment by jasonjavaYY** [comment]
I aggre with you, but the code is really confusing and may be misunderstood as "-1000" has special meaning.

> IMO, the set operation mainly sets the `refCount` to negative so that cleanupOver can be forced after a timeout. So if you use +, the `refCount` might still be positive. (The way I understand it, it's probably better to just make `refCount` negative)
