### ISSUE TITLE
A queue is not consumed

### ISSUE THREAD

**Issue by XTUxiongda** [apache/rocketmq#5441]
![image](https://user-images.githubusercontent.com/38322373/199156522-af819d38-63ef-4bbf-a557-2e4fde8644cb.png)
It is true that messages have been piling up in this topic. However, this time, it is found that queue1 has always been in and out without consumption, and diffTotal has been increasing.
What causes this? Is there any recommended solution?
rocketMQ version : 4.7.0

**Comment by pipi18** [comment]
The consumer is `ConsumeMessageOrderlyService`? if true, you should find which method is blocked
