### ISSUE TITLE
NPE occurs when the instance username and password are not set

### ISSUE THREAD

**Issue by supercym** [apache/rocketmq#5442]
I use 5.0 sdk but refer to how 4.0 is used (like here: https://help.aliyun.com/document_detail/446709.html)

When my instanceUsername and password are both null and I access the Alibaba Cloud MQ instance from vpc, there is an NPE.

![image](https://user-images.githubusercontent.com/25047893/199169275-25f365bb-22b2-442d-a9c1-75e995927eac.png)

**Comment by aaron-ai** [comment]
Nice catch!
