### ISSUE TITLE
The RocketMQ Product White Paper

### ISSUE THREAD

**Issue by zongtanghu** [apache/rocketmq#545]
1.What is the purpose of the change
Some days ago,I was very proud to be able to write some parts of the developer user guide for rocketmq.The guide is very helpful to those developer.But I think it is very necessary to provide rocketmq product white paper for advertising rocketmq.

2.Brief changelog
I think I can write a rocketmq production white paper for community.

**Comment by vongosling** [comment]
@zongtanghu Is it the same thing as we doing in RIP-9?

**Comment by zongtanghu** [comment]
@vongosling Year,it is the same as RIP-9.
