### ISSUE TITLE
[Question]MappedFileQueue#checkSelf not needs return boolean? 

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#5455]
When load CommitLog, CommitLog#load
![image](https://user-images.githubusercontent.com/15797831/199460763-ac17e88e-bfe7-4927-b9cf-ff383a4a3aef.png)

The mappedFileQueue will execute checkSelf method, but this method return void.
![image](https://user-images.githubusercontent.com/15797831/199461139-10b8828d-7c33-49e5-a705-0c61e81d6622.png)
if execute `if (cur.getFileFromOffset() - pre.getFileFromOffset() != this.mappedFileSize)`  condition, only print error log. Instead of break check and return false.
**I'm not sure if there's something wrong with that logic?**

**Comment by pipi18** [comment]
In dledger modle `MmapFileList#checkSelf()` will return boolean value, the method only check files' size is damaged or not.
![2022-11-03_145811](https://user-images.githubusercontent.com/38873832/199663226-58d3aeb1-af41-458b-afa6-d2d716ee7eee.png)

If the corresponding file in commitLog or consumerQueue is manually damaged，the broker should start  and the find the last file which is not damaged

**Comment by mxsm** [comment]
@pipi18  thanks for you explain
