### ISSUE TITLE
Flaky test case: TransactionDataManagerTest

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#5461]
java.lang.AssertionError
	at org.apache.rocketmq.proxy.service.transaction.TransactionDataManagerTest.testWaitTransactionDataClear(TransactionDataManagerTest.java:114)

TransactionDataManagerTest.testWaitTransactionDataClear:114

https://github.com/apache/rocketmq/actions/runs/3382741348/jobs/5617967358

**Comment by azhsmesos** [comment]
In fact, I also have questions, some cases local install successful, but running github ci will report errors.
