### ISSUE TITLE
RocketMQ 4.9.2 unsupport subscribe 2 topic with 1 consumer group in 2 process

### ISSUE THREAD

**Issue by zhanxuefeng** [apache/rocketmq#5473]
I subscribe 2 topic with 1 consumer group in 2 process
when a process upload the SubscrptionData to broker, the broker will remove SubscriptionData uploaded in other process

`code in ConsumerGroupInfo#updateSubscription`

subscribe 2 topic with 1 consumer group in 1 process is ok

is this a bug?

**Comment by Advanceo** [comment]
Are you subscribing to different topics in the two processes?

**Comment by Advanceo** [comment]
Inconsistent subscription relationships can cause this problem

**Comment by zhanxuefeng** [comment]
> Are you subscribing to different topics in the two processes?

yes, 2 diff topics

**Comment by pipi18** [comment]
A lot of same problem: Inconsistent subscription relationships. Look at this:  https://rocketmq.apache.org/zh/docs/4.x/bestPractice/21subscribe/
