### ISSUE TITLE
[New Feature]Is there any producer machine statistic data in plan?

### ISSUE THREAD

**Issue by wegod** [apache/rocketmq#5478]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
There are some consumer machine level stats data now provided in exporter, such as rocketmq_client_consumer_pull_tps, rocketmq_client_consume_ok_msg_tps, rocketmq_client_consume_rt, those record in consumer machines. 

But unfortunately, I didn't find similar stats data in producer machines. So I want to ask is there a plan that you will add similar data statistic in producer machine level?

2. Provide any additional detail on your proposed use case for this feature.
We need producer machine level statistic data to monitor which machine is working wrong maybe cause by task job or dirty data, then we can location fault quickly.

Yes, we can also add data point in each producer business code, but we have many business project, and use different data point tools, so we want to monitor data in one place. And we are building a super view that conclude dashboard, exporter and admin tools.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
very-very-nice-to-have

**Comment by ShadowySpirits** [comment]
Do you have any proposal? We are developing metrics for rocketmq, feel free to discuss spec in #5366.
