### ISSUE TITLE
Is there a way to customize client host in trace data?

### ISSUE THREAD

**Issue by redlsz** [apache/rocketmq#5497]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
A way to customize producer/consumer client host in trace data.

2. Provide any additional detail on your proposed use case for this feature.
TraceBean does have field clientHost,
<img width="961" alt="image" src="https://user-images.githubusercontent.com/103550934/200807403-92d07daf-0a49-4225-909b-45a786f3d8c7.png">

but it is ignored when encoing trace context to transfer string.
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/103550934/200807950-725331f4-04df-4620-ac87-3a1e2c39858c.png">

And finally using born host of message as client host when decoding transfer string to trace view.
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/103550934/200808422-e228c0e1-c635-44e5-a22e-7e519fed489c.png">

In our deployment architecture, there is a proxy, which is actually the rocketmq remoting client, between user client and broker. And what we want is user client ip could be shown in trace view.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by echooymxq** [comment]
#5395
