### ISSUE TITLE
Why DefaultLitePullConsumer poll always return only one message?

### ISSUE THREAD

**Issue by linqh1** [apache/rocketmq#5498]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
```
        DefaultLitePullConsumer pullConsumer = new DefaultLitePullConsumer("testGroup");
        pullConsumer.setNamesrvAddr(consumerProperties.getNameserver());
        pullConsumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_FIRST_OFFSET);
        pullConsumer.setPullBatchSize(20);
        pullConsumer.setPullThreadNums(10);
        pullConsumer.setAutoCommit(true);
        pullConsumer.subscribe(consumerProperties.getTopic(), SubscriptionData.SUB_ALL);
        pullConsumer.start();
        
        while(true) {
            List<MessageExt> msgs = pullConsumer.poll();
            Thread.sleep(60000);
        }
```
with the above setings, `poll `method **always return 1 message**;

- What is expected to see?
pullConsumer.poll() return more than 1 messaage.

- What did you see instead?
When msgs is not empty, its size() is alway1

2. Please tell us about your environment:
RocketMQ version: 4.6.1
jar version: 4.6.1

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
I used `DefaultMQPushConsumer` to consume message with group name: **testGroup** before
Today I change to use `DefaultLitePullConsumer` to consume message with same group name(**testGroup**), and then I run into this problem.

**Comment by linqh1** [comment]
And I change to use a new group name: newTestGroup, and then pullConsumer.poll() return more than 1 message !!!

**Comment by pipi18** [comment]
Is it order messge?

**Comment by linqh1** [comment]
> Is it order messge?

I'm not sure, the producer just call method:
`public SendResult send(Message msg)`

The temporary solution is that consumer call `poll()` multiple times until pulled enough message or elapse some time(eg: 10 seconds)

**Comment by cserwen** [comment]
If it has a lag, then you can get more than one messages when polling. If there is no lag and the producer only sends one message at a time, then poll may only get 1 message. @linqh1

**Comment by yateng817** [comment]
我目前也遇到了一样的问题，请问已经解决了吗，只要队列里的消息被消费完后续poll就只能拉取到一条消息，重启项目又能拉取到多条
