### ISSUE TITLE
Namesrv cannot start at JDK 9 environment

### ISSUE THREAD

**Issue by AlexMasonQi** [apache/rocketmq#550]
When I use command "nohup sh bin/mqnamesrv &" to start the namesrv, it appears errors as follows:

Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCMSCompactAtFullCollection'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

My JDK version is 11.0.1，it seems that the latest rocketmq version is not compatible with my JDK version(the latest JDK version), but I can build success the source code.

**Comment by jackwener** [comment]
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCMSCompactAtFullCollection'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by umm233** [comment]
My JDK version is 12.0.1, start the mqnamesrv also get the same error:
```
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCMSCompactAtFullCollection'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by LimLeeSpirit** [comment]
Anyone solved this problem...?
I am using java version "11.0.2" 2019-01-15 LTS. start the 
`nohup sh bin/mqnamesrv get the same erro:`
get the same error:
`Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCMSCompactAtFullCollection'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

**Comment by LimLeeSpirit** [comment]
> When I use command "nohup sh bin/mqnamesrv &" to start the namesrv, it appears errors as follows:
> 
> Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> Unrecognized VM option 'UseCMSCompactAtFullCollection'
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> 
> My JDK version is 11.0.1，it seems that the latest rocketmq version is not compatible with my JDK version(the latest JDK version), but I can build success the source code.

Hi bro, have you succeeded to start the namesrv via the source code?

**Comment by leonezhu** [comment]
using JDK 1.8  every  thing is OK ,   delete  your JDK  9  11  12  13.   i also meet this  error when i  using JDK 13

**Comment by seasidesky** [comment]
CMS Garbage Collector was deprecated in jdk 9 and was removed in jdk14
if you are using jdk 9+, use other Garbage Collector like G1
