### ISSUE TITLE
Invert dependency between remoting and common module

### ISSUE THREAD

**Issue by ShadowySpirits** [apache/rocketmq#5502]
It is usually understood that the `common` module is the fundamental dependency for other modules and should not depend on other modules in the project. But in RocketMQ `common` module depends on `remoting` module, which looks weird and is an obstacle to the expansion of remoting. So I want to invert the dependency between `remoting` and `common` module to make `common` module really common.

**Comment by aaron-ai** [comment]
+1, Nice proposal.

**Comment by mxsm** [comment]
@ShadowySpirits  Good Idea, **`common`** module use remoting `RemotingSerializable` , `RemotingUtil` and some annotations. if we  invert the dependency between remoting and common module, should consider the scope of influence and incompatibility problem.

**Comment by ShadowySpirits** [comment]
> @ShadowySpirits Good Idea, **`common`** module use remoting `RemotingSerializable` , `RemotingUtil` and some annotations. if we invert the dependency between remoting and common module, should consider the scope of influence and incompatibility problem.

Thanks for your advice. The detailed changes are listed in #5503, could you please help review this pr?
