### ISSUE TITLE
Question : How do I create TOPIC of type DELAY?

### ISSUE THREAD

**Issue by TO-21** [apache/rocketmq#5506]
### 请教一下，我该如何创建类型为DELAY的主题呢?
我查阅了5.0的文档，但是不知道如何创建 用于延迟消息的主题，似乎在文档中找不到对这块的描述。
使用console 或 rmqadmin updateTopic命令创建的主题类型为normal
会导致类型不匹配的异常
```
java.lang.IllegalArgumentException: Current message type not match with topic accept message types, topic=TOPIC_DEVICE_EVENT_ALARM, actualMessageType=DELAY, acceptMessageTypes=[NORMAL]
```

我尝试用自动创建的方式来创建DELAY类型的主题
配置了broker.conf，开启了 自动创建主题 autoCreateTopicEnable=true
可能是由于通过proxy 的原因，抛如下异常，主题无法被自动创建
```
DESC: No topic route info in name server for the topic: TOPIC_DELAY_BIZ_TEST
```

**Comment by CHENYGITHUB** [comment]
sh bin/mqadmin updatetopic -n localhost:9876 -t topic_name -c DefaultCluster -a +message.type=DELAY
参数说明：
-a,--attributes <arg>       attribute(+a=b,+c=d,-e)
-c,--clusterName <arg>      create topic to which cluster
-t,--topic <arg>            topic name

**Comment by pipi18** [comment]
5.0的官方文档，还有很多完善之处，欢迎参与补充。

**Comment by drpmma** [comment]
See this doc for more information.

English: https://github.com/apache/rocketmq/blob/develop/docs/en/Example_CreateTopic.md

中文： https://github.com/apache/rocketmq/blob/develop/docs/cn/Example_CreateTopic.md

**Comment by fuyou001** [comment]
@TO-21  done

**Comment by ZhengJiaH** [comment]
想问一下,我现在是一个集群，多个节点，修改messageType的话，只需要在一个节点执行一下，nameserver就会同步，还是我需要在每一个都需要执行一下
