### ISSUE TITLE
consumer offset larger than broker offset

### ISSUE THREAD

**Issue by aluomaidi** [apache/rocketmq#551]
**BUG REPORT**
1. Please describe the issue you observed:
    - When use ./mqadmin consumerProgress cmd  query consumer progress，the conusmer offset is lagger than broker offset on one broker.Another broker is all right.

2. Please tell us about your environment:
     -  java 1.7,centos 7,rocketmq 3.2,rocketmq has 3 master 0 slaver

3. Other information 
   - We delete the topic info on that broker.The operation is stop the broker and remove the topic/group infomation，then restart the broker.
   - We do not restart the consumer client and  consumer client occurs repeat consumption.

**Comment by ShannonDing** [comment]
close due to too long, please reopen it if there is still a problem.
