### ISSUE TITLE
Proxy  8081 port  already in use. How to Modify a Port？

### ISSUE THREAD

**Issue by kutouziUk** [apache/rocketmq#5517]
nohup sh bin/mqbroker -n localhost:9876 --enable-proxy &
![image](https://user-images.githubusercontent.com/54654629/201516400-73e48271-6e83-4098-bd00-7230214266f2.png)

**Comment by mxsm** [comment]
Hi @kutouziUk  you can use -pc to set Proxy config file path and use `grpcServerPort` properties to set proxy port.

**Comment by kutouziUk** [comment]
ok thank you. Is the grpcServerPort parameter described in the official document? I haven't seen the official document

**Comment by mxsm** [comment]
> ok thank you. Is the grpcServerPort parameter described in the official document? I haven't seen the official document

It doesn't seem to be in the documentation.

**Comment by kutouziUk** [comment]
ok

**Comment by xiaodaweic** [comment]
> 
能具体说一下grpcServerPort怎么设置吗？ 我找不到在哪里设置。

**Comment by kutouziUk** [comment]
> > 
> 
> 能具体说一下grpcServerPort怎么设置吗？ 我找不到在哪里设置。

 -pc指定配置文件位置 ，配置文件里面配置grpcServerPort=端口号

**Comment by xiaodaweic** [comment]
> 

能发一下具体命令吗？我在是nohup sh mqnamesrv 、nohup sh mqbroker 、nohup sh mqproxy的时候加-pc这个参数都没有启动成功。

**Comment by xiaodaweic** [comment]
> 
配置文件里面配置中配置是grpcServerPort=8082时启动mqproxy [报语法错误。如图：
![1](https://user-images.githubusercontent.com/52072784/203008366-bf41153b-1970-4487-b3ad-72c8168021a4.jpg)
![2](https://user-images.githubusercontent.com/52072784/203008401-a0f3c464-3446-40d1-88cb-a6856935a69e.jpg)

**Comment by kutouziUk** [comment]
> 

官方配置你看一下，我记得我当初那样配置成功了
![image](https://user-images.githubusercontent.com/54654629/203015491-950fd504-a29a-4f1d-89c4-c3960bec7963.png)

**Comment by xiaodaweic** [comment]
好的，谢谢。已经启动成功了，要json格式才行能运行成功。{"grpcServerPort":8082}
