### ISSUE TITLE
[Discussion] Support tiered storage for RocketMQ

### ISSUE THREAD

**Issue by hzh0425** [apache/rocketmq#5518]
Hi, teams!
At present, we store all topic data on the local disk of the Broker. If the amount of business data is very large, it may not be possible to store the full amount of data. 
BTW, We prefer to store some old historical data on cheap disks, such as s3, and store the newer data on the local disk of the Broker.
So should we let RocketMQ support tiered storage?
Thanks to the storage features of RocketMQ, it should not be difficult to support tiered storage.

**Comment by hzh0425** [comment]
Like [Kip--Kafka Tiered storage](https://cwiki-vm6.apache.org/confluence/display/KAFKA/KIP-405%3A+Kafka+Tiered+Storage)

**Comment by nowinkeyy** [comment]
Hi @hzh0425 
I think there was a discussion about that earlier, #5418

**Comment by lizhanhui** [comment]
@ShadowySpirits Would you please share the roadmap or insights?

**Comment by ShadowySpirits** [comment]
Hi @hzh0425 @azhsmesos. We do have plans for tiered storage on our roadmap. But the relationship between tiered storage and compact topic also needs to be discussed. These two approaches have the same goal: both are to extend the message storage time and are suitable for different situations. We should decide how to evolve the storage of RocketMQ to be more suitable for the current architecture and positioning.

**Comment by hzh0425** [comment]
Cool, is there any channel to discuss this feature? @ShadowySpirits @lizhanhui

**Comment by ShadowySpirits** [comment]
> Cool, is there any channel to discuss this feature? @ShadowySpirits @lizhanhui

We will submit a rip later.

**Comment by ShadowySpirits** [comment]
@hzh0425 @azhsmesos @lizhanhui I have submitted the [RIP-57](https://github.com/apache/rocketmq/wiki/RIP-57-Tiered-storage-for-RocketMQ) to implement tiered storage for RocketMQ. We can discuss it in [mail list](https://lists.apache.org/thread/nzp123b2syv719sznnt74kjbth5m6rto).

**Comment by azhsmesos** [comment]
> @hzh0425 @azhsmesos @lizhanhui I have submitted the [RIP-57](https://github.com/apache/rocketmq/wiki/RIP-57-Tiered-storage-for-RocketMQ) to implement tiered storage for RocketMQ. We can discuss it in [mail list](https://lists.apache.org/thread/nzp123b2syv719sznnt74kjbth5m6rto).

Cool! Is it already under development?

**Comment by ShadowySpirits** [comment]
@azhsmesos Yeah. I'll open a new issue and submit the first pr later this week.
