### ISSUE TITLE
what's diff between rocketmq-client and rocketmq-client-java on 5.0.0 version 

### ISSUE THREAD

**Issue by ilovedumplings** [apache/rocketmq#5525]
[in the](https://rocketmq.apache.org/zh/docs/quickStart/02quickstart)
int the rocket mq 5.0.0 quick start , it use rocketmq-client-java
i wanna know what's diff between rocketmq-client-java and rocketmq -client 

      <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
            <version>5.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client-java</artifactId>
            <version>5.0.0</version>
        </dependency>

thanks.

**Comment by aaron-ai** [comment]
`rocketmq-client-java` is the gRPC/protobuf-based SDK, while `rocketmq-client` is the remoting-based SDK.

They works by different communication protocols, and `rocketmq-client-java` adopts the brand new APIs and is recommended.

**Comment by ilovedumplings** [comment]
> `rocketmq-client-java` is the gRPC/protobuf-based SDK, while `rocketmq-client` is the remoting-based SDK.
> 
> They works by different communication protocols, and `rocketmq-client-java` adopts the brand new APIs and is recommended.

thanks.

i also wanna know both them support customized delay queue(int 24 hours) ??

**Comment by aaron-ai** [comment]
@ilovedumplings  you mean delay message? Of course!

**Comment by ilovedumplings** [comment]
> @ilovedumplings you mean delay message? Of course!

yeah yeah yeah ,thanks !big man !!!

in rocketmq-client  i wanna use delay message
can i use this : ⬇
org.apache.rocketmq.common.message.Message

    public void setDelayTimeSec(long sec) {
        this.putProperty(MessageConst.PROPERTY_TIMER_DELAY_SEC, String.valueOf(sec));
    }
    public void setDelayTimeMs(long timeMs) {
        this.putProperty(MessageConst.PROPERTY_TIMER_DELAY_MS, String.valueOf(timeMs));
    }
    public void setDeliverTimeMs(long timeMs) {
        this.putProperty(MessageConst.PROPERTY_TIMER_DELIVER_MS, String.valueOf(timeMs));
    }

**Comment by ilovedumplings** [comment]
> @ilovedumplings you mean delay message? Of course!

因为我看rocket-mq-client的,似乎没有调用PROPERTY_TIMER_DELIVER_MS/PROPERTY_TIMER_DELAY_SEC 这几个参数的地方

**Comment by ilovedumplings** [comment]
sorry . i use wrong version of broker ....shit....
