### ISSUE TITLE
I want to creat delay topic on 5.0

### ISSUE THREAD

**Issue by xiaobing0508** [apache/rocketmq#5530]
What should I do?

**Comment by mxsm** [comment]
@xiaobing0508 #5506  you can see this issue.
See this doc for more information.

English: https://github.com/apache/rocketmq/blob/develop/docs/en/Example_CreateTopic.md

中文： https://github.com/apache/rocketmq/blob/develop/docs/cn/Example_CreateTopic.md

**Comment by xiaobing0508** [comment]
@mxsm THX
