### ISSUE TITLE
Logging isolation of broker container is hacky

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#5531]
Current solution of logging isolation is hacky: https://github.com/apache/rocketmq/blob/develop/docs/cn/BrokerContainer.md#%E6%97%A5%E5%BF%97%E5%8F%98%E5%8C%96

Maybe we should try [logback MDC](https://logback.qos.ch/manual/mdc.html)

**Comment by lizhanhui** [comment]
Contextual logging is much preferred over the hacking logging library. Those who have experience in programming Go/Rust would be fully clear about how awesome and convenient it is to have a contextual logging feature.
