### ISSUE TITLE
How to view the message.type attribute of a Topic？

### ISSUE THREAD

**Issue by kutouziUk** [apache/rocketmq#5538]
The FIFO attribute was specified when the Topic was created
![image](https://user-images.githubusercontent.com/54654629/202610778-475bce43-a285-426d-a54f-5634152d403c.png)
The attribute is not displayed in the query result
`sh bin/mqadmin topicRoute -b localhost:9016 -n localhost:9015 -t TTLK`
![image](https://user-images.githubusercontent.com/54654629/202611298-345e368d-939a-432e-b25c-82494dc4dd0c.png)
and dashboard  can't query this information either
![image](https://user-images.githubusercontent.com/54654629/202611606-1b30a364-2a92-4657-bb49-583f0264ec9c.png)

**Comment by zhouxinyu** [comment]
Good catch, the related tools are incomplete, feel free to assign this issue to yourself if you want.

**Comment by The-Gamer-01** [comment]
I would like to give it a try, can you assign this issue to me

**Comment by Oliverwqcwrw** [comment]
> I would like to give it a try, can you assign this issue to me

done

**Comment by Abhijeetmishr** [comment]
@Oliverwqcwrw @zhouxinyu Can I pick this up ?

**Comment by Oliverwqcwrw** [comment]
Hi @The-Gamer-01 , Since you haven't submitted PR for a long time, I'm going to assign this task to @Abhijeetmishr . You are also welcome to revise other issues, And welcome to the community @Abhijeetmishr

**Comment by Abhijeetmishr** [comment]
> Hi @The-Gamer-01 , Since you haven't submitted PR for a long time, I'm going to assign this task to @Abhijeetmishr . You are also welcome to revise other issues, And welcome to the community @Abhijeetmishr

@Oliverwqcwrw Thank you Oliver, Will definitely check other issues also which needs update.
Regards

**Comment by Abhijeetmishr** [comment]
@zhouxinyu @kutouziUk @Oliverwqcwrw I think QueueData Class doesnot have this field (message.type) 
![image](https://user-images.githubusercontent.com/43075376/223767682-6cdf6877-d644-4955-9eff-abea2f065755.png).
Correct me if I'm going in wrong direction.
 Regards

**Comment by Oliverwqcwrw** [comment]
> @zhouxinyu @kutouziUk @Oliverwqcwrw I think QueueData Class doesnot have this field (message.type) ![image](https://user-images.githubusercontent.com/43075376/223767682-6cdf6877-d644-4955-9eff-abea2f065755.png). Correct me if I'm going in wrong direction. Regards

<img width="610" alt="image" src="https://user-images.githubusercontent.com/31796988/223885138-c23dd9bf-b984-42b2-8ab7-575a5e590b86.png">
Please take a look at the TopicConfig query interface, add a messageType to the return value and display it on the page

The dashboard repository is here [rocketmq-dashboard](https://github.com/apache/rocketmq-dashboard)

[Example_CreateTopic.md](https://github.com/apache/rocketmq/blob/develop/docs/en/Example_CreateTopic.md)

**Comment by Abhijeetmishr** [comment]
> > @zhouxinyu @kutouziUk @Oliverwqcwrw I think QueueData Class doesnot have this field (message.type) ![image](https://user-images.githubusercontent.com/43075376/223767682-6cdf6877-d644-4955-9eff-abea2f065755.png). Correct me if I'm going in wrong direction. Regards
> 
> <img alt="image" width="610" src="https://user-images.githubusercontent.com/31796988/223885138-c23dd9bf-b984-42b2-8ab7-575a5e590b86.png">
> 
> Please take a look at the TopicConfig query interface, add a messageType to the return value and display it on the page
> The dashboard repository is here [rocketmq-dashboard](https://github.com/apache/rocketmq-dashboard)
> 
> [Example_CreateTopic.md](https://github.com/apache/rocketmq/blob/develop/docs/en/Example_CreateTopic.md)

@Oliverwqcwrw as far as my understanding change is required in both the places:-
1. in the query result 
2. on the dashboard as well

**Comment by Abhijeetmishr** [comment]
@Oliverwqcwrw @zhouxinyu The attribute is not displayed in the query result
![image](https://user-images.githubusercontent.com/43075376/223925442-e430a6a0-a2e5-4f3e-a52d-000ac3a29753.png)
can anyone point out which controller is responsible for this ?

**Comment by Oliverwqcwrw** [comment]
> @Oliverwqcwrw @zhouxinyu The attribute is not displayed in the query result ![image](https://user-images.githubusercontent.com/43075376/223925442-e430a6a0-a2e5-4f3e-a52d-000ac3a29753.png) can anyone point out which controller is responsible for this ?

<img width="302" alt="image" src="https://user-images.githubusercontent.com/31796988/223928621-be0b44b0-ba0b-4436-9a78-7bd168a053a2.png">
You can find it int the `topics.json`

**Comment by Abhijeetmishr** [comment]
> > > @zhouxinyu @kutouziUk @Oliverwqcwrw I think QueueData Class doesnot have this field (message.type) ![image](https://user-images.githubusercontent.com/43075376/223767682-6cdf6877-d644-4955-9eff-abea2f065755.png). Correct me if I'm going in wrong direction. Regards
> > 
> > 
> > <img alt="image" width="610" src="https://user-images.githubusercontent.com/31796988/223885138-c23dd9bf-b984-42b2-8ab7-575a5e590b86.png">
> > Please take a look at the TopicConfig query interface, add a messageType to the return value and display it on the page
> > The dashboard repository is here [rocketmq-dashboard](https://github.com/apache/rocketmq-dashboard)
> > [Example_CreateTopic.md](https://github.com/apache/rocketmq/blob/develop/docs/en/Example_CreateTopic.md)
> 
> @Oliverwqcwrw as far as my understanding change is required in both the places:-
> 
> 1. in the query result
> 2. on the dashboard as well

@Oliverwqcwrw Sorry for asking again but i am not able to connect the dots.

**Comment by Abhijeetmishr** [comment]
@Oliverwqcwrw
 Please take a look at the TopicConfig query interface, add a messageType to the return value and display it on the page
for this I have to check in rocketMq/dashboard ?

**Comment by Oliverwqcwrw** [comment]
> ```
>  @Override
>     public List<TopicConfigInfo> examineTopicConfig(String topic) {
>         List<TopicConfigInfo> topicConfigInfoList = Lists.newArrayList();
>         TopicRouteData topicRouteData = route(topic);
>         for (BrokerData brokerData : topicRouteData.getBrokerDatas()) {
>             TopicConfigInfo topicConfigInfo = new TopicConfigInfo();
>             TopicConfig topicConfig = examineTopicConfig(topic, brokerData.getBrokerName());
>             **BeanUtils.copyProperties(topicConfig, topicConfigInfo);**
>             topicConfigInfo.setBrokerNameList(Lists.newArrayList(brokerData.getBrokerName()));
>             topicConfigInfoList.add(topicConfigInfo);
>         }
>         return topicConfigInfoList;
>     }
> ```
> 
> we are copying topicConfig to TopicConfigInfo so I have added the messageType to TopicConfigInfo
> 
> ```
>     /** topicConfig */
>     private String topicName;
>     private int writeQueueNums;
>     private int readQueueNums;
>     private int perm;
>     private boolean order;
>     **private String  messageType**;   
> ```
> 
> @Oliverwqcwrw Do we have to update anything in TopicConfig also in rocketMq repo ?

<img width="907" alt="image" src="https://user-images.githubusercontent.com/31796988/224585898-295dfdbf-6197-4d07-8a69-8f9cdcd60757.png">
IMO, We do not need to modify the rocketmq repository

The latest version of topicConfig has attributes. We need to upgrade rocketmq-common in dashboard

**Comment by Abhijeetmishr** [comment]
@Oliverwqcwrw I have raised a PR for this in rocketmq-dashboard but I am getting some build error that I have fixed and report 
[](https://github.com/apache/rocketmq-dashboard/issues/149)
but none has responded yet.
Is there any forum and chat group where I can get response faster for any issue related to Apache community?

**Comment by Oliverwqcwrw** [comment]
> @Oliverwqcwrw I have raised a PR for this in rocketmq-dashboard but I am getting some build error that I have a fix and I have reported [link](https://github.com/apache/rocketmq-dashboard/issues/149) but none has responded yet. Is there any forum and chat group where I can get response faster for any issue related to Apache community?

Hello @Abhijeetmishr ,
I have assigned the issue to you [# 149](https://github.com/apache/rocketmq-dashboard/issues/149)

**Comment by Abhijeetmishr** [comment]
@Oliverwqcwrw Please check this when you are available.
