### ISSUE TITLE
OrderMsgBroadCastIT test passed while the RMQBroadCastConsumers received nothing

### ISSUE THREAD

**Issue by Hellojungle** [apache/rocketmq#557]
The issue tracker is **ONLY** used for bug report and feature request. Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
Prints the timeout information in the waitForMessageConsume function and run the testTwoConsumerSubTag test.
- What did you expect to see?
Test finish without timeout information
- What did you see instead?
![image](https://user-images.githubusercontent.com/18479517/48899578-efbf7680-ee8a-11e8-8250-e7e2ecbcfaff.png)
And actually the RMQBroadCastConsumers received nothing.
2. Please tell us about your environment:
Mac os 64bit
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
rocketmq_client.log:
![image](https://user-images.githubusercontent.com/18479517/48899783-796f4400-ee8b-11e8-8d36-9e0ba0797b57.png)

**Comment by ShannonDing** [comment]
close due to too long, please reopen it if there is still a problem.
