### ISSUE TITLE
When to start the broker using the [ --enable-proxy ] parameters, how to modify the port number 8081 using by netty?

### ISSUE THREAD

**Issue by zooah212** [apache/rocketmq#5570]
When to start the broker using the [ --enable-proxy ] parameters, how to modify the port number 8081 using by netty?

**Comment by mxsm** [comment]
@zooah212  you can see this [document](https://rocketmq.apache.org/docs/deploymentOperations/15deploy#%E5%90%AF%E5%8A%A8-proxy) or this ISSUE #5517

**Comment by zooah212** [comment]
> 
Thanks
