### ISSUE TITLE
MappedFile#warmMappedFile there may be code that doesn't work

### ISSUE THREAD

**Issue by jianglianggithub** [apache/rocketmq#5571]
org.apache.rocketmq.store.MappedFile#warmMappedFile
文件预热
1.会给每个page 写入一个假值0 
2.然后使用mlock来让liunx不被swap
3. madvise 让系统先读取一些数据出来

这里有个问题 如果1只是为了预先读取一些数据出来避免后续出现缺页中断的话，mlock本身就会触发缺页中断处理了
如果不是的话就是之所以put是因为mlock可能不生效有些页是cow的，但是在创建内存映射mmap的时候指定了 MapMode.READ_WRITE
在这个mode下是不会发生cow的所以我觉得这个for 循环put 一个假值好像是没啥用

**Comment by jianglianggithub** [comment]
@Oliverwqcwrw 您好过去很久了，我看到ISSUE 4902 里面说了一些相关的东西，比如红帽的文档那个链接 看了下貌似没解决我得疑问，

**Comment by Oliverwqcwrw** [comment]
@jianglianggithub 我的理解是mlock在锁定内存的时候，操作系统会确保物理内存足够来容纳这个区域，因此在使用mlock时，不会触发缺页中断。但如果内存不足，操作系统将无法保证所有被mlock锁定的内存都可以驻留在物理内存中，这时会出现一定的概率触发缺页中断。
所以我觉得这块预热是OK的
