### ISSUE TITLE
If the producer sends the same request twice to commit transaction (RequestCode.END_TRANSACTION),  will it cause the same half messages be store in the real topic twice?

### ISSUE THREAD

**Issue by bjsfdx2004** [apache/rocketmq#5574]
### branch 4.9.x

producer 发送了事务消息，在 broker 回调 producer 进行 check local transaction 时候
通过模拟的方法让 producer 同时发出两个相同的 commit transaction 请求(RequestCode.END_TRANSACTION)

1. 是否会导致相同的 half message 被取出两次，向用户的  real topic 进行两次重复的消息投递？
2. 消费端是否会受到重复的消息？
3. 如果 broker 端不会进行重复的投递，请问在源码的什么地方处理的这段逻辑？

**Comment by black-06** [comment]
1. There will be multiple duplicate messages in real topic (only offset is different)
2. So consumer will also repeatedly consume

dashboard:
![image](https://user-images.githubusercontent.com/50364282/216217295-c4905227-84de-4071-811d-cca9e0a56bba.png)

consumer:
![image](https://user-images.githubusercontent.com/50364282/216217504-f22e7320-af36-41bb-87ec-4df97568c1ea.png)

**Comment by bjsfdx2004** [comment]
> 1. There will be multiple duplicate messages in real topic (only offset is different)
> 
>     2. So consumer will also repeatedly consume
> 
> 
> dashboard: ![image](https://user-images.githubusercontent.com/50364282/216217295-c4905227-84de-4071-811d-cca9e0a56bba.png)
> 
> consumer: ![image](https://user-images.githubusercontent.com/50364282/216217504-f22e7320-af36-41bb-87ec-4df97568c1ea.png)

thank you

**Comment by bjsfdx2004** [comment]
多谢了，明白了
