### ISSUE TITLE
Add brokerConfig which will not validate system topic when update topic

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq#5595]
validateSystemTopicWhenUpdateTopic

https://github.com/apache/rocketmq/blob/1cdcce1988e927e4f705f67c8c9683888c0606cf/broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java#L415-L419

**Comment by francisoliverlee** [comment]
你好， 添加brokerConfig和update topic怎么关系的呢， 可以举例说明下嘛？

**Comment by ShadowySpirits** [comment]
> 你好， 添加brokerConfig和update topic怎么关系的呢， 可以举例说明下嘛？

我理解这个 pr 的用意是给用户一个选择：是否允许使用 mqadmin 创建/修改系统 topic

**Comment by drpmma** [comment]
@francisoliverlee @ShadowySpirits 


> > 你好， 添加brokerConfig和update topic怎么关系的呢， 可以举例说明下嘛？
> 
> 我理解这个 pr 的用意是给用户一个选择：是否允许使用 mqadmin 创建/修改系统 topic
