### ISSUE TITLE
[TIMEOUT_CLEAN_QUEUE] period in queue: 3002ms

### ISSUE THREAD

**Issue by a13794479495** [apache/rocketmq#560]
The issue tracker is **ONLY** used for bug report and feature request. Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
in production environment，we set up an 2m-2s-sync rocketmq cluster,currently,the tps < 100;
however,the message producer occasionally appears [TIMEOUT_CLEAN_QUEUE] everyday,as follows:
![mq1](https://user-images.githubusercontent.com/18589654/48933986-3ec5e400-ef3d-11e8-9f7d-5eae8a68db6b.png)
I find out some  solutions forexample #348  and adjust rocketmq cluster's config:
waitTimeMillsInSendQueue 200ms ->3000ms
sendMessageThreadPoolNums  1 ->16
useReentrantLockWhenPutMessage false -> true
but producer still appears the exception:
![2](https://user-images.githubusercontent.com/18589654/48934399-de37a680-ef3e-11e8-94b7-671e011ad0c1.png)
the message after reachs the broker wait for so long time in queue,why?please help!

2. Provide any additional detail on your proposed use case for this feature.
rocketmq cluster：2m-2s-sync
flush disk: async flush
other rocketmq cluster's config: default
server num: 4
OS: centos 7，8 core 32G
hard disk: SSD
other application on linux：redis(redis has closed data persistence)
server's memory is enough.
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ymwneu** [comment]
In the case you describe, i think the problem may be in the master-slave synchronization.
If the network between master and slave is unstable, this problem will occur occasionally.

**Comment by a13794479495** [comment]
@ymwneu thanks，I will test  the stability of the network!

**Comment by a13794479495** [comment]
@ymwneu the rocketmq cluster deployed in ali cloud,I test the server's network,it's stable，do you think there exist any other possible cause ? or maybe i should adjust the cluster to 2m-2s-async ？

**Comment by vongosling** [comment]
@a13794479495 Yep, I strongly recommend you use 1m-1s-async model.

**Comment by a13794479495** [comment]
@vongosling OK,thanks!

**Comment by cxfmichael** [comment]
http://mail-archives.apache.org/mod_mbox/rocketmq-users/201706.mbox/%3CCANMLrBiA3_YVzYKrW+UAYGEtYmdAmK7GYO+DutEMOMJEZDdrow@mail.gmail.com%3E
