### ISSUE TITLE
How to quickly deploy RocketMQ 5.0 on k8s?

### ISSUE THREAD

**Issue by john1337** [apache/rocketmq#5612]
rocketmq5.0如何快速的部署在k8s上，试用了[RocketMQ Operator](https://github.com/apache/rocketmq-operator#deploy-rocketmq-operator)，使用的是helm.sh的RocketMQ Operator，失败告终，没有自己去编译RocketMQ Operator，请问社区能否做些什么能在k8s快速的部署rocketmq，虽说rocketmq没有使用zookeeper，但是高可用集群也是好几个组件需要部署，使用起来完全没有kafka方便

**Comment by francisoliverlee** [comment]
目前我了解到没有快速的方式。我也在探索[RocketMQ Operator](https://github.com/apache/rocketmq-operator#deploy-rocketmq-operator)或者自己整yaml
也可以分享下你的做法。

**Comment by drpmma** [comment]
Could you please share your error information here?

**Comment by drpmma** [comment]
It's about RocketMQ 5.0 proxy deployment in K8s or just broker and namesrv.

**Comment by caigy** [comment]
@john1337 Could you provide more failure information when using rocketmq-operator? Actually  rocketmq-operator does not depend on helm.

**Comment by john1337** [comment]
> @john1337 Could you provide more failure information when using rocketmq-operator? Actually rocketmq-operator does not depend on helm.
错误信息如下：
error: unable to recognize "https://operatorhub.io/install/stable/rocketmq-operator.yaml": no matches for kind "Subscription" in version "operators.coreos.com/v1alpha1"

**Comment by john1337** [comment]
> Could you please share your error information here?

错误信息如下：
error: unable to recognize "https://operatorhub.io/install/stable/rocketmq-operator.yaml": no matches for kind "Subscription" in version "operators.coreos.com/v1alpha1"

**Comment by caigy** [comment]
@john1337 I've tried deploying rocketmq-opertor as directions on [OperatorHub](https://operatorhub.io/operator/banzaicloud-kafka-operator), but all works well:
```
# curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/install.sh | bash  v0.22.0
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/olmconfigs.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operatorconditions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/olmconfigs.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operatorconditions.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com condition met
namespace/olm created
namespace/operators created
serviceaccount/olm-operator-serviceaccount created
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager created
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm created
olmconfig.operators.coreos.com/cluster created
deployment.apps/olm-operator created
deployment.apps/catalog-operator created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view created
operatorgroup.operators.coreos.com/global-operators created
operatorgroup.operators.coreos.com/olm-operators created
clusterserviceversion.operators.coreos.com/packageserver created
catalogsource.operators.coreos.com/operatorhubio-catalog created
Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...
deployment "olm-operator" successfully rolled out
deployment "catalog-operator" successfully rolled out
Package server phase: Installing
Package server phase: Succeeded
deployment "packageserver" successfully rolled out
# 
# kubectl create -f https://operatorhub.io/install/banzaicloud-kafka-operator.yaml
subscription.operators.coreos.com/my-rocketmq-operator created
# kubectl get csv -n operators
NAME                      DISPLAY             VERSION   REPLACES                  PHASE
rocketmq-operator.0.3.0   RocketMQ Operator   0.3.0     rocketmq-operator.0.2.1   Succeeded
```

You should check if `Subscription` was installed successfully in your environment.

**For deploying RocketMQ 5.0:**

- If you just want to update versions of name servers or brokers to 5.x, just update the docker image. 
- If you want to deploy new modules in 5.x, you can use `apache/rocketmq-operator:0.4.0-snapshot`, which has not been published to OperatorHub yet:
  - Clustering with new DLedger Controller: Pls deploy [Controller](https://github.com/apache/rocketmq-operator/blob/master/example/rocketmq_v1alpha1_console_cr.yaml) first and specify `clusterMode` as `CONTROLLER` for `Broker` cr.
  - Proxy mode: It's still under development, you can refer this [pr](https://github.com/apache/rocketmq-operator/pull/134) for details.

**Comment by drpmma** [comment]
Close for now, feel no hesitate to reopen this issue if needed.
