### ISSUE TITLE
[OPTIMIZATION] Change the broker default value configuration of 'useServerSideResetOffset'

### ISSUE THREAD

**Issue by cryptoya** [apache/rocketmq#5613]
```
<groupId>org.apache.rocketmq</groupId>
<artifactId>rocketmq-client-java</artifactId>
<version>5.0.2</version>
```
broker.conf: `useServerSideResetOffset=false`

`org.apache.rocketmq.tools.admin.DefaultMQAdminExt#resetOffsetByTimestamp(java.lang.String, java.lang.String, long, boolean)` is not work

![image](https://user-images.githubusercontent.com/102146039/204480238-03b4fd26-4d9d-42f0-8e71-67f33bb1b779.png)
`org.apache.rocketmq.broker.client.net.Broker2Client#resetOffset(java.lang.String, java.lang.String, long, boolean, boolean)`
**offsetTable value is incorrect**
![image](https://user-images.githubusercontent.com/102146039/204480225-0ea119e8-e06d-45bb-875e-41c28ca9a085.png)

broker.conf:  `useServerSideResetOffset=true` 
![image](https://user-images.githubusercontent.com/102146039/204483539-0c60f3f0-12ac-46f4-86c1-f0f9570a499e.png)

**Comment by francisoliverlee** [comment]
> ```
> <groupId>org.apache.rocketmq</groupId>
> <artifactId>rocketmq-client-java</artifactId>
> <version>5.0.2</version>
> ```
> 
> broker.conf: `useServerSideResetOffset=false`
> 
> `org.apache.rocketmq.tools.admin.DefaultMQAdminExt#resetOffsetByTimestamp(java.lang.String, java.lang.String, long, boolean)` is not work
> 
> ![image](https://user-images.githubusercontent.com/102146039/204480238-03b4fd26-4d9d-42f0-8e71-67f33bb1b779.png) `org.apache.rocketmq.broker.client.net.Broker2Client#resetOffset(java.lang.String, java.lang.String, long, boolean, boolean)` **offsetTable value is incorrect** ![image](https://user-images.githubusercontent.com/102146039/204480225-0ea119e8-e06d-45bb-875e-41c28ca9a085.png)
> 
> broker.conf: `useServerSideResetOffset=true` ![image](https://user-images.githubusercontent.com/102146039/204483539-0c60f3f0-12ac-46f4-86c1-f0f9570a499e.png)

同意。rocketmq-client-java 5.0.2是grpc client，利用proxy，通过pop访问的broker。
pop消费时拉取消息的位点是broker管理的，也只能用broker端位点重置，默认打开配置觉得合理。

**Comment by lizhimins** [comment]
At that time, the switch was not turned on by default to carefully evaluate the impact of servic-side offset management on ha implementation. @RongtongJin @mxsm Can u help evaluate it?

**Comment by lizhanhui** [comment]
Reset Offset operation, among other operational tasks, should be replicated among replica peers in order to survive node failures.

**Comment by echooymxq** [comment]
> At that time, the switch was not turned on by default to carefully evaluate the impact of server-side offset management on ha implementation. @RongtongJin @mxsm Can u help evaluate it?

@lizhimins Why might there be an impact? if the slave read enable ??🤔️
