### ISSUE TITLE
[OPTIMIZATION] record pre putMessageDistributeTime

### ISSUE THREAD

**Issue by hujie6** [apache/rocketmq#5615]
version: 
   rocketmq 4.8.0
   rocketmq-exporter

Q: when i use rocketmq exporter to collect rocketmq cluster metrics（collection period is one minute）, i find that the putMessageDistributeTime of broker is not correct by calling fetchBrokerRuntimeStats. And then i reviewed StoreStatsService, putMessageDistributeTime could be initialized every minute when calling printTps method. if exporter's collection time is different from StoreStatsService printTps time, user will get incorrect putMessageDistributeTime.

how to fix:
we should record old putMessageDistributeTime when init putMessageDistributeTime every time. when calling fetchBrokerRuntimeStats to get putMessageDistributeTime, we should return the old putMessageDistributeTime.

**Comment by hujie6** [comment]
I had optimized it, and i got correct putMessageDistributeTime. maybe i can submit a pull request if possible

**Comment by ShadowySpirits** [comment]
PR is welcome! And we introduce new metrics for RocketMQ, see [RIP-46](https://github.com/apache/rocketmq/wiki/RIP-46-Observability-improvement-for-RocketMQ) and [Spec](https://github.com/apache/rocketmq/issues/5366) please.

**Comment by lizhimins** [comment]
Nice

**Comment by hujie6** [comment]
> PR is welcome! And we introduce new metrics for RocketMQ, see [RIP-46](https://github.com/apache/rocketmq/wiki/RIP-46-Observability-improvement-for-RocketMQ) and [Spec](https://github.com/apache/rocketmq/issues/5366) please.

i find rocketmq 5.0 had fixed this bug. this issue
