### ISSUE TITLE
AutoSwitchHATest is flaky on MacOSX

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#5620]
testChangeRoleManyTimes(org.apache.rocketmq.store.ha.autoswitch.AutoSwitchHATest)  Time elapsed: 60.991 sec  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.rocketmq.store.ha.autoswitch.AutoSwitchHATest that uses org.apache.rocketmq.store.DefaultMessageStore, org.apache.rocketmq.store.DefaultMessageStoreint, intint was not fulfilled within 30 seconds.
	at org.apache.rocketmq.store.ha.autoswitch.AutoSwitchHATest.checkMessage(AutoSwitchHATest.java:195)
	at org.apache.rocketmq.store.ha.autoswitch.AutoSwitchHATest.testChangeRoleManyTimes(AutoSwitchHATest.java:310)

See 
https://github.com/apache/rocketmq/actions/runs/3581437719/jobs/6024498750

testChangeRoleManyTimes(org.apache.rocketmq.store.ha.autoswitch.AutoSwitchHATest)  Time elapsed: 55.804 sec  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.rocketmq.store.ha.autoswitch.AutoSwitchHATest that uses org.apache.rocketmq.store.DefaultMessageStore, org.apache.rocketmq.store.DefaultMessageStoreint, intint was not fulfilled within 30 seconds.
	at org.apache.rocketmq.store.ha.autoswitch.AutoSwitchHATest.checkMessage(AutoSwitchHATest.java:195)
	at org.apache.rocketmq.store.ha.autoswitch.AutoSwitchHATest.testChangeRoleManyTimes(AutoSwitchHATest.java:310)

https://github.com/apache/rocketmq/actions/runs/3552475420/jobs/6024183011

**Comment by lizhanhui** [comment]
@RongtongJin New test failures are observed, mainly on MacOSX platform. Please have a look.

**Comment by lizhanhui** [comment]
@RongtongJin Another issue, this test case costs 200+seconds, any possible to accelerate it?

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/641819/204749397-6b077e02-52b7-4ce4-92e9-815f6fd0c644.png">

**Comment by RongtongJin** [comment]
> @RongtongJin New test failures are observed, mainly on MacOSX platform. Please have a look.

Okay, let me see
