### ISSUE TITLE
[ISSUE] RAT reports some files with unapproved license

### ISSUE THREAD

**Issue by walking98** [apache/rocketmq#563]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

The following files need to exclude for the check list:

11 Unknown Licenses

*****************************************************

Files with unapproved licenses:

  rocketmq/.github/ISSUE_TEMPLATE/issue_template.md
  rocketmq/.github/PULL_REQUEST_TEMPLATE.md
  rocketmq/.travis.yml
  rocketmq/remoting/src/test/resources/certs/badServer.key
  rocketmq/remoting/src/test/resources/certs/badClient.key
  rocketmq/remoting/src/test/resources/certs/client.key
  rocketmq/remoting/src/test/resources/certs/server.key
  rocketmq/CONTRIBUTING.md
  rocketmq/broker/src/test/resources/META-INF/service/org.apache.rocketmq.broker.transaction.TransactionalMessageService
  rocketmq/broker/src/test/resources/META-INF/service/org.apache.rocketmq.broker.transaction.AbstractTransactionalMessageCheckListener
  rocketmq/distribution/bin/README.md

*****************************************************

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

You can verify this with the mvn cmd:
mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle

**Comment by vongosling** [comment]
@walking98 Some files does not need license check, so ignore it.
