### ISSUE TITLE
一个消费服务，两个节点，消息总是被其中一个节点获取到，这些消息是存放在同一个队列上的

### ISSUE THREAD

**Issue by linux-lpx** [apache/rocketmq#5630]
![image](https://user-images.githubusercontent.com/15316382/205004541-69148668-0c7f-40e2-a5a3-d8f3a50e236d.png)

消费模式是这样的
```
@RocketMQMessageListener(topic = MyProducer.TOPIC_NAME,
        consumerGroup = MyProducer.CONSUMER_GROUP_IN_ORDER,
        messageModel = MessageModel.CLUSTERING,
        consumeMode = ConsumeMode.ORDERLY,
        maxReconsumeTimes = 3, // 重试三次
        selectorExpression = "tag_order")
```

**Comment by RongtongJin** [comment]
@linux-lpx 队列数是多少，如果是1的话那只有一个消费者被消费到。否则队列会负载均衡到对应consumer上，参考https://github.com/apache/rocketmq/blob/develop/docs/cn/design.md#42-consumer%E7%9A%84%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1

**Comment by linux-lpx** [comment]
谢谢，懂了
