### ISSUE TITLE
ratio is never set

### ISSUE THREAD

**Issue by Jacob-Jay** [apache/rocketmq#5632]
messageStoreConfig's default role is  ASYNC_MASTER ,and -c config is parse and use after this part ,so is it never set ratio?

https://github.com/apache/rocketmq/blob/31a7edd618d70c62ad2bdfcda187c16ff7cfd37e/broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java#L100-L103

**Comment by fuyou001** [comment]
what 's your mean

**Comment by ni-ze** [comment]
brokerRole in MessageStoreConfig will be changed at the broker role change.

**Comment by Jacob-Jay** [comment]
> 

i mean that  the code in if block will never execute

**Comment by ni-ze** [comment]
> > 
> 
> i mean that the code in if block will never execute

 BrokerRole need specify in broker.conf if you want to deploy a master-salve cluster.
