### ISSUE TITLE
queryMessageByUniqKey：CODE: 208  DESC: query message by key finished, but no message

### ISSUE THREAD

**Issue by bootstrapupload** [apache/rocketmq#5636]
error info：
org.apache.rocketmq.client.exception.MQClientException: CODE: 208  DESC: query message by key finished, but no message.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQAdminImpl.queryMessage(MQAdminImpl.java:444)
	at org.apache.rocketmq.client.impl.MQAdminImpl.queryMessageByUniqKey(MQAdminImpl.java:281)
	at org.apache.rocketmq.client.impl.MQAdminImpl.queryMessageByUniqKey(MQAdminImpl.java:287)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.viewMessage(DefaultMQAdminExtImpl.java:351)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.viewMessage(DefaultMQAdminExt.java:559)
rocketmq version：4.9.4
brokerConfig：aclEnable=true
execute queryMessageByUniqKey()，aclEnable = true and MQClientAPIImpl#queryMessage 
RemotingCommand addExtField _UNIQUE_KEY_QUERY，because Client generating acl Signature by RemotingCommand，
but Server parses RemotingCommand，exclude extField "_UNIQUE_KEY_QUERY"，result in Server signature is not equals Client

Server code：PlainAccessValidator#
// Content
        SortedMap<String, String> map = new TreeMap<String, String>();
        for (Map.Entry<String, String> entry : request.getExtFields().entrySet()) {
            if (!SessionCredentials.SIGNATURE.equals(entry.getKey())
                && **!MixAll.UNIQUE_MSG_QUERY_FLAG.equals(entry.getKey())**) {
                map.put(entry.getKey(), entry.getValue());
            }
        }

**Comment by ni-ze** [comment]
IMO, Code in PlainAccessValidator has nothing to do with this question, take a look at you client log may be give you more info.

**Comment by bootstrapupload** [comment]
> IMO, Code in PlainAccessValidator has nothing to do with this question, take a look at you client log may be give you more info.

If aclEnable is set to false,query message by key is normal, and aclEnable is true, i modify the local code, it is normal
So I guess it has something to do with PlainAccessValidator

![image](https://user-images.githubusercontent.com/26431303/206107600-a1873611-64c1-433f-b976-9c96299626a8.png)

**Comment by TickFairy** [comment]
> this is error info，“CODE: 208 DESC: query message by key finished, but no message” is from client，not the server， the server returns the following information ![image-20221207155956482](https://user-images.githubusercontent.com/26431303/206125360-fff29aca-b6d3-4ac1-8a82-2351e83a488e.png)

Have you solved this problem? I have the same problem.

**Comment by TickFairy** [comment]
![image](https://github.com/user-attachments/assets/e5cbf817-38d7-429c-adb3-afcb41e79165)

**Comment by TickFairy** [comment]
![image](https://github.com/user-attachments/assets/98d40781-0a66-4ee1-ad7b-e42772294894)
