### ISSUE TITLE
TimerMessageProducer.java delay doesn't work at all 

### ISSUE THREAD

**Issue by john1337** [apache/rocketmq#5646]
example目录下的TimerMessageProducer.java没有起到任何延迟效果，
            Message message = new Message(TOPIC, ("Hello scheduled message " + i).getBytes(StandardCharsets.UTF_8));
            // This message will be delivered to consumer 10 seconds later.
            //message.setDelayTimeSec(System.currentTimeMillis()/1000+10);
            // The effect is the same as the above
            // message.setDelayTimeMs(10_000L);
            // Set the specific delivery time, and the effect is the same as the above
            message.setDeliverTimeMs(System.currentTimeMillis() + 60_000L);

感觉rocketmq的示例文档质量欠缺啊，给的示例代码也不能工作，需要加强啊

**Comment by RongtongJin** [comment]
> TimerMessageProducer

服务端是用的5.0以上的版本吗？任意时间的定时消息需要服务端为5.0版本，并且broker配置timerWheelEnable为true。

**Comment by john1337** [comment]
> > TimerMessageProducer
> 
> @john1337 服务端是用的5.0以上的版本吗？任意时间的定时消息需要服务端为5.0版本，并且broker配置timerWheelEnable为true。
不知具体怎么配置，rocketmq使用文档的维护可见太差，新用户都不知道怎么用，怎么配置

**Comment by zhiliatom** [comment]
立即发送成功， 延迟效果是从消费端观察到的

**Comment by john1337** [comment]
> 立即发送成功， 延迟效果是从消费端观察到的

消费端立即就受到数据了，根本就没延迟，我在5.0 rocketmq broker.conf增加了brokerTimerWheelEnable = true这个配置，不知是不是brokerTimerWheelEnable这个配置参数根本不对，因为我在rocketmq官方文档上也没找到任何相关信息

**Comment by zhiliatom** [comment]
> 

1. 检查服务端时间和客户端是否不一致，
2. 部分相关文档：https://rocketmq.apache.org/zh/docs/featureBehavior/02delaymessage

**Comment by mxsm** [comment]
@john1337 看一下Broker是否用的5.0的版本

**Comment by fuyou001** [comment]
> rocketmq使用

请检查broker 中的参数brokerTimerWheelEnable是否为true，如果启动修改了参数，需要重启才生效。

**Comment by mxsm** [comment]
> > TimerMessageProducer
> 
> @john1337 服务端是用的5.0以上的版本吗？任意时间的定时消息需要服务端为5.0版本，并且broker配置timerWheelEnable为true。

timerWheelEnable 这个应该不需要配置，我看代码默认就是true
![image](https://user-images.githubusercontent.com/15797831/205796543-a48d3991-249f-4dc8-8a4d-5f1291d9bd81.png)

**Comment by mxsm** [comment]
> > 立即发送成功， 延迟效果是从消费端观察到的
> 
> 消费端立即就受到数据了，根本就没延迟，我在5.0 rocketmq broker.conf增加了brokerTimerWheelEnable = true这个配置，不知是不是brokerTimerWheelEnable这个配置参数根本不对，因为我在rocketmq官方文档上也没找到任何相关信息

这个参数应该是 `timerWheelEnable` 而不是 `brokerTimerWheelEnable`

**Comment by RongtongJin** [comment]
> timerWheelEnable

是的，应该是`timerWheelEnable`

**Comment by john1337** [comment]
> 消费端立即就受到数据了，根本就没延迟，我在5.0 rocketmq broker.conf增加了brokerTimerWheelEnable = true这个配置，不知是不是brokerTimerWheelEnable这个配置参数根本不对，因为我在rocketmq官方文档上也没找到任何相关信息

我现在rocketmq是部署在本地测试的

**Comment by john1337** [comment]
> > timerWheelEnable
> 
> 是的，应该是`timerWheelEnable`

还是不行

**Comment by john1337** [comment]
> > rocketmq使用
> 
> 请检查broker 中的参数brokerTimerWheelEnable是否为true，如果启动修改了参数，需要重启才生效。
> 
> @john1337

重启过rocketmq broker还是无效

**Comment by mxsm** [comment]
@john1337  你是通过代码打包还是通过官网下载的,如果是代码打包检查一下打包的分支。或者截图一下你的部署版本通过admin的 clusterList 命令查看一下

**Comment by RongtongJin** [comment]
![image](https://user-images.githubusercontent.com/21963954/205839235-12908cb4-dfd1-4eec-a960-401c70a08a07.png)
@john1337 I tried it on my mac, and it is ok.

**Comment by john1337** [comment]
> @john1337 你是通过代码打包还是通过官网下载的,如果是代码打包检查一下打包的分支。或者截图一下你的部署版本通过admin的 clusterList 命令查看一下： 命令查询如下： `bin/mqadmin clusterList -n 127.0.0.1:9876` ![image](https://user-images.githubusercontent.com/15797831/205845003-816482a5-8a5b-4b6c-8f2b-bbd976cb61f5.png) ![image](https://user-images.githubusercontent.com/15797831/205845038-f62a2224-d25f-44eb-90ab-8e884bd1d5ca.png) 我在本地windows部署namesrv, broker部署在wsl上，develop分支也是没有问题的

使用的就是rocketmq这个仓库的实例，如图所示：
![image](https://user-images.githubusercontent.com/11956341/205848815-c1bbe20c-c271-470f-a826-086e1c74c495.png)

**Comment by mxsm** [comment]
> bin/mqadmin clusterList -n

使用这个命令bin/mqadmin clusterList -n xxx   看一下Broker版本， release-5.0.0使用的生产者代码和消费者代码是没有问题的。延迟消息主要是看Broker版本，Broker 5.0.0才支持 如果你是4.x版本是不支持的

**Comment by john1337** [comment]
> @john1337
> 
> > bin/mqadmin clusterList -n xxxx
> 
> ![image](https://user-images.githubusercontent.com/15797831/205851654-015f6544-d410-4079-81c8-8efb3b6ac65d.png)
> 
> 使用这个命令bin/mqadmin clusterList -n xxx 看一下Broker版本， release-5.0.0使用的生产者代码和消费者代码是没有问题的。延迟消息主要是看Broker版本，Broker 5.0.0才支持 如果你是4.x版本是不支持的

从https://dlcdn.apache.org/rocketmq/5.0.0/rocketmq-all-5.0.0-bin-release.zip上下载的rocketmq，使用上述命令执行结果如下：
![image](https://user-images.githubusercontent.com/11956341/205899016-c31bfddb-fd64-46a7-9675-82c919c721ab.png)
这是啥情况，竟然是4.9.3版本，有些无语
