### ISSUE TITLE
rocketmq-externals/rocketmq-spark plugin bug

### ISSUE THREAD

**Issue by my0113** [apache/rocketmq#565]
https://github.com/apache/rocketmq-externals/blob/master/rocketmq-spark/src/main/scala/org/apache/spark/sql/rocketmq/CachedRocketMQProducer.scala the CachedRocketMQProducer.scala code line number 60 and 70 bug
![image](https://user-images.githubusercontent.com/24773118/49136278-22062380-f324-11e8-9622-64bc7cbacde3.png)。

line number 60 ：
    CacheBuilder.class method for build(loader) required paramter is CacheLoader<? super K1, V1> loader

line number 70 ：
    update to 
![image](https://user-images.githubusercontent.com/24773118/49136506-c25c4800-f324-11e8-9e56-0c61fcb6ee64.png)

**Comment by duhengforever** [comment]
@my0113 thanks for your issue and it seems indeed is a bug, but we hope that you can propose this issue in the external repo(https://github.com/apache/rocketmq-externals), and welcome to pull a request to fix the bug.
