### ISSUE TITLE
proxy service didn't started 

### ISSUE THREAD

**Issue by jamescheng16** [apache/rocketmq#5653]
**BUG REPORT**

1. Please describe the issue you observed:
proxy didn't start.
java client can't send message.
shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.16.18.147:8081
But dashboard run correctly. can search and send message

- What did you do (The steps to reproduce)?
- user start broker command
`nohup sh bin/mqbroker -n localhost:9876 --enable-proxy &`

- What is expected to see?
- java client send and receive message

- What did you see instead?
port 8081 didn't open 
`lsof -i  | grep 8081`

2. Please tell us about your environment:
version rocketmq-all-5.0.0-bin-release
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by mxsm** [comment]
@jamescheng16 
#5511 
this bug has fixed and release the next version. You can build from the development branch's source code

**Comment by drpmma** [comment]
> @jamescheng16 #5511 this bug has fixed and release the next version. You can build from the development branch's source code

This issue may not has a connection with #5511 because this bug just occurs in develop branch and has not been released in 5.0.0.

@jamescheng16 Please provide logs like ~/logs/rmq-proxy/default.log for more information.

**Comment by jamescheng16** [comment]
there is no ~/logs/rmq-proxy/ at path ~/logs

**Comment by jamescheng16** [comment]
![Screenshot 2022-12-13 at 11 08 04](https://user-images.githubusercontent.com/4263914/207217128-ccd95d40-3c7b-43cb-867f-529df07f3838.png)

**Comment by ShadowySpirits** [comment]
> @jamescheng16 #5511 this bug has fixed and release the next version. You can build from the development branch's source code

It's not true because metrics aren't included in 5.0.0.

**Comment by drpmma** [comment]
> there is no ~/logs/rmq-proxy/ at path ~/logs
