### ISSUE TITLE
ssl certificate signed with weak hash algorithm

### ISSUE THREAD

**Issue by Minamoto575** [apache/rocketmq#5664]
I use RocketMQ  4.8.0 in docker, with a port 9876, but there is a security problem —— "ssl certificate signed with weak hash algorithm"，how can I resolve it ?

**Comment by Oliverwqcwrw** [comment]
The signature algorithm used in the SSL certificate does not meet the IETF requirements. Therefore, you need to re-create the SSL certificate, ensure that the signature algorithm and key length of the SSL certificate meet the IETF requirements, and replace the SSL certificate of the affected software based on the affected software.
