### ISSUE TITLE
v5.0.0  Seriously uneven distribution of queues when a single thread sends synchronous messages with SendLatencyFault Enable

### ISSUE THREAD

**Issue by mz0113** [apache/rocketmq#5672]
prerequisite：
1. **single** thread **sync** send message in one topic using while(true) with Infinite loop to send near 100000 messages
2. **defaultMQProducer().setSendLatencyFaultEnable(true)**
3. rocketmq-client v5.0.0 (actually 4.9.x has also this problem)
4. this topic has 2 brokers , each broker has 24 queues can be sended. so ,total 2*24 = 48 queues

result：
1.Uneven distribution of queue ， Most(almost half) messages are distributed on queue 0

**This is the sed result , i print them to console :** 
![0873dc90f5c1ee04007779749c29d23](https://user-images.githubusercontent.com/42512469/206608856-706dcba1-f0cb-496e-8e51-ed08b18b4eb0.png)

**Code in red box  to find a  messagequeue to send,  i think this is the problem, the code below the red box has never been executed in this test i can sure cause i make breakpoint**
![317239184f2724629b7532cd4c41fda](https://user-images.githubusercontent.com/42512469/206608954-b0f80830-de6d-496b-8fa2-100b00d8c23e.png)

**There is a problem in this picture. I have marked it with a red line ， why there is two [idc1-broker-b queueId=2] item?  but this is not a Seriously problem cause the unevent distribution ,i have restart my aplication many times and the duplicated messagqueue disapperd ,but still have unevent distribution result**
![348862157c15db800557e0807ef9e06](https://user-images.githubusercontent.com/42512469/206609317-bab16d63-028a-47cc-a243-1b84633c04b1.png)

**Comment by francisoliverlee** [comment]
如果设置sendLatencyFaultEnable=true，则selectOneMessageQueue()方法才会走你红框中的逻辑。我使用了5.0.0分支，发送代码如下：
![image](https://user-images.githubusercontent.com/5908412/206714466-f4368876-1a94-43e0-bb24-55ad10a61c2c.png)

发送结果每个queue相对比较均匀，没有出现你的情况。 截图如下：

![image](https://user-images.githubusercontent.com/5908412/206714383-cec7cc41-dd85-4d53-95bc-2454b5d6f553.png)

**Comment by mz0113** [comment]
1. 启动2个broker ， 每个broker上配置24个queue

**Comment by xiaoyifang** [comment]
@mz0113  Can you show the code about how do you set the `SendLatencyFaultEnable` parameter

**Comment by mz0113** [comment]
@xiaoyifang @francisoliverlee 
我觉得这个复现的可能前提条件是broker压力较大，导致for循环会跑多次时候造成的巧合。应该从概率论角度来分析，单纯随便找个场景想复现可能有难度。

关于我设置 SendLatencyFaultEnable ， 没动什么其他配置，就仅仅producer.setSendLatencyFaultEnable(true) 把它启用了。
橙红色圈画出来的位置.我看了，pos小于0没出现过，但是pos很大概率值会是24。而pos=24恰巧是messageQueueList中的queueNum=0的那个queue。所以我发送后的截图中近乎一半消息都是发到queue0去了。

我还是觉得这个场景或许得从概率论角度来分析，在broker压力较大时候，for循环会执行多次。甚至和queue的数量也有关系，比如我的queue是48条，而pos大概率是24.正好是queueNum=0的这个queue。
为了验证，我把源码这里算pos的加了日志，根据日志打印情况，显示for循环会执行差不多3-10次之间把。

**Comment by xiaoyifang** [comment]
> 我觉得这个复现的可能前提条件是broker压力较大，导致for循环会跑多次时候造成的巧合

should be this reason.

when enabled `SendLatencyFaultEnable `   ,rocketmq would try to skip the problemed broker (I think the implementation has some issue，will discuse in following) for a period of time, So when brokera has been put into the `faultItemTable`, `selectOneMessageQueue` would try to skip this broker.

![image](https://user-images.githubusercontent.com/105986/208358604-6bd27b17-a1ef-4b22-88ac-202294d3ee9c.png)



Now ,The problem should be changed into why `brokera` has been put into the `faultItemTable`(method latencyFaultTolerance.isAvailable is using this),

`faultItemTable` is updated in three places , briefly browsing them ,I can see only the following invoke place is ok.

![image](https://user-images.githubusercontent.com/105986/208359156-10c442bb-0122-4a5a-8020-78dcfbee0931.png)

the other 2 places have little meaning.
like this ,
![image](https://user-images.githubusercontent.com/105986/208359558-56cb4321-6271-42fa-b237-22dc5ff94714.png)


someone should check this logic.

**Comment by xiaoyifang** [comment]
And ,this PR https://github.com/apache/rocketmq/pull/5718  should fixed the unevenly distributed issue.

but still need someone to check the `faultItemTable` logic.

**Comment by mz0113** [comment]
@xiaoyifang 你的推断我觉得没有问题，brokera被暂时规避掉后，ThreadlocalRandom随机出来的index值如果<24，那么从0-24都是brokera的queue都会被skip掉。一直循环，直到下一个可用的broker一定是broker-b。此时pos就被累加成24，即 brokerb-queue-0

**Comment by mz0113** [comment]
@xiaoyifang faultItemTable并不是存放故障的broker，它其实维护了所有的broker的状态。之所以这么做，是因为有时候发送延迟较大，尽管发送成功了。此时也会依照预设值将其规避不同时长。比如发送时延如果达到500ms，就规避10秒，达到1000ms，就规避30秒。这样来降低这台broker的压力。

**Comment by xiaoyifang** [comment]
en ,应该是这样的设计。

不过这样的话，容易造成其他问题。可能会造成短时间内，所有broker都不可用。对吞吐量应该影响比较大。

比较好的做法是faultItemTable只存有故障的，进行规定时长内规避，其他正常的broker可以按照响应时间 筛选，
比如 brokera 时延 10ms， brokerb 100ms ,挑选命中brokera的概率可以比brokera高个10倍。

**Comment by Abhijeetmishr** [comment]
@francisoliverlee can I pick this up ?
