### ISSUE TITLE
Performance comparison between RocketMQ 5.0 and kafka

### ISSUE THREAD

**Issue by john1337** [apache/rocketmq#5680]
不知rocketmq5.0的性能与kafka性能比较如何，是否有对应的测试数据

**Comment by drpmma** [comment]
RocketMQ 5.0 itself does not introduce differences on the broker side, so you can reference the original performance report.


As for the proxy, there is no performance data for now. But it's an optional component both in `Cluster` and `Local` mode. `Cluster` mode should be compared with Kafka proxy-like components while `Local` mode introduces an extra protocol translation, so its performance is slightly lesser than the original broker.
