### ISSUE TITLE
Why use pullconsumer can't pull message?

### ISSUE THREAD

**Issue by towardsvast** [apache/rocketmq#5683]
1. The client has been registered, and there are still messages in the queue.But can't pull message! 
2. view config
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/112958315/206838259-e684f864-f0bb-4261-b92f-8ebdf0ada921.png">
3. view console
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/112958315/206838312-94a713ac-a138-44f4-af6a-d6450d169c14.png">

**Comment by ni-ze** [comment]
Please check that the order of execution is as follows:

1. create topic.
2. send message.
3. consume message.

**Comment by fuyou001** [comment]
@towardsvast please  provide  consuemrprogress -g gid   command result.
