### ISSUE TITLE
partitionally ordered message question

### ISSUE THREAD

**Issue by davidpdw** [apache/rocketmq#569]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

1、双主双从结构，两个master上面都有TestTopic

2、使用局部顺序消息特性

```
Message msg = new Message("TestTopic", tags[i % tags.length], "KEY" + i,
                    ("Hello RocketMQ " + i).getBytes(RemotingHelper.DEFAULT_CHARSET));
            SendResult sendResult = producer.send(msg, new MessageQueueSelector() {
            @Override
            public MessageQueue select(List<MessageQueue> mqs, Message msg, Object arg) {
                Integer id = (Integer) arg;
                int index = id % mqs.size();
                return mqs.get(index);
            }
            }, orderId);
```

3、首先发送一条消息，orderID=123456，假设第一条消息发送到broker-a的队列里面。在发送下一条orderID=123456的消息之前关闭broker-a的master节点和slave节点，这个时候在发送消息，消息就会发送到broker-b的队列里面了，这样消息就不能发送到一个队列里面了，严格局部顺序就不能保证了

- What did you expect to see?

严格的消息顺序，像broker-a只有master节点宕机时，后续消息发送直接快速失败，而不是直接发送到另一个master

- What did you see instead?

当broker-a的主从都宕机时，就会出现发送到broker-b，这样就不能保证严格消息顺序

2. Please tell us about your environment:

rocketmq 4.3.0
2 namesrv 2 master 2 slave

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

或者是设计时就考虑到这种情况，只是RocketMQ不保证严格的顺序消息，在消费端还是要做一定的顺序判断处理

**Comment by AnyOSR** [comment]
想要保证严格的顺序性，只能单producer，单messagequeue，单consumer吧

**Comment by davidpdw** [comment]
@AnyOSR 局部顺序是不需要保证单messageQueue的，只需要保证发送到一个messageQueue里面就行了吧，你说的是全局顺序的情况吧

**Comment by AnyOSR** [comment]
> @AnyOSR 局部顺序是不需要保证单messageQueue的，只需要保证发送到一个messageQueue里面就行了吧，你说的是全局顺序的情况吧

所谓的局部顺序是指，发送到某一个messageQueue的消息顺序消费，且只能被一个consumer消费？
