### ISSUE TITLE
[Discuss] Producer and consumer add a strategy to connect to NameServer 

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#5698]
Producers and consumers connecting to NameServer to obtain routing information are random, and data is obtained by randomly selecting a NameServer from the given NameServer list for connection. This situation has the following disadvantages:

1. The better machines deployed by NameServer cannot exert all their machine performance, while the poorer machines may connect to many, causing the service to crash.
2. Cannot specify a NameServer for connection (except for configuring a single NameServer address). 

Therefore, it is considered to add a strategy pattern for selecting a NameServer for connection in the client (producer and consumer). The developer can choose or implement the strategy to select the NameServer for connection. The following strategies can be considered:

1. Random strategy: randomly select a NameServer for connection (current mode).
2. Specified strategy: specify a specific NameServer for connection.
3. Polling strategy: the current application's clients select from the given NameServers on their own.
4. NameServer minimum client connection strategy: obtain the current NameServer with the minimum number of client connections for connection.

Other strategies can be added in the future.

**Comment by lizhimins** [comment]
In general, the configuration of NameServer should be the same and should be hidden behind the load balancing service. At this time, the server maintainer can select random, polling, minimum connections and other policies on the server. This centralized management is more conducive to operation and maintenance.
