### ISSUE TITLE
[code issue] the use of CountDownLatch2

### ISSUE THREAD

**Issue by xiaoyifang** [apache/rocketmq#5710]
background:
the CountDownLatch2 is only used in ServiceThread .
it is a reimplementation of CountDownLatch and offered a new method reset.

I think the CountDownLatch2 can be replace with java `Condition` class for the following reasons:
1, CountDownLatch does not offer reset ,as it was designed according to the javadoc ,
![image](https://user-images.githubusercontent.com/105986/208000791-4cdd1ed8-9037-4bce-9e64-ad03594ba32a.png)
2, the `waitForRunning`'s behavior in the ServiceThread is indefinite in  some worst cases.
the code is in the ServiceThread. and the reset in used in `waitForRuning`.
https://github.com/apache/rocketmq/blob/aa7a442505ac012d1bc61b89bf10c41646a15005/common/src/main/java/org/apache/rocketmq/common/ServiceThread.java#L129-L141

in multithread environment.
![image](https://user-images.githubusercontent.com/105986/208002112-cad2d8e5-6a9d-44cd-a9e3-98108191e9d7.png)

the execution order will have different result ,and in the worst cases ,  `waitForRunning` will have to wait some extra `interval` more millionseconds.

A critical section(lock etc.) maybe better involved.

**Comment by drpmma** [comment]
> the `waitForRunning`'s behavior in the ServiceThread is indefinite in some worst cases.

There is indeed a concurrent issue on `waitPoint`, but it will not lead to indefinite waiting.

```java
protected void waitForRunning(long interval) { 
     if (hasNotified.compareAndSet(true, false)) { 
         this.onWaitEnd(); 
         return; 
     } 
  
     // 1. execute wakeup() here will cause a extra waiting

     waitPoint.reset(); 
  
    // 2. execute wakeup() here will lead to immediate wakeup without waiting

     try { 
         waitPoint.await(interval, TimeUnit.MILLISECONDS); 
     } catch (InterruptedException e) { 
         log.error("Interrupted", e); 
```

As the annotation below, the `wakeup()` invocation before `waitPoint.reset()` will cause a extra waiting while `wakeup()` execution after `waitPoint.reset()` will lead to immediate wakeup without waiting.

There is indeed a concurrent issue and do you have the indentation to submit to pr to fix it?

**Comment by xiaoyifang** [comment]
I'll submit a pr later
