### ISSUE TITLE
[code bug] the index++ may reach negative value

### ISSUE THREAD

**Issue by xiaoyifang** [apache/rocketmq#5716]
https://github.com/apache/rocketmq/blob/adb83ca09633b76150fd3dca294803d96a4dfd60/client/src/main/java/org/apache/rocketmq/client/latency/MQFaultStrategy.java#L61-L63

for example 
```
        int index=0x7FFFFFFF;
        for(int i=0;i<10;i++)
        {
            System.out.println(index++) ;//will reach negative;
        }
```

**Comment by ShadowySpirits** [comment]
Nice catch! And this logic changed in #5181, we should review it again.

https://github.com/apache/rocketmq/pull/5181/files#diff-771f2a9ff3067ee7ec67d5282228514e9e709c549eafe34ae7402b279487d656L87-L93

**Comment by xiaoyifang** [comment]
`int index = tpInfo.getSendWhichQueue().incrementAndGet(); ` 
this line is outside the for loop ,will cause unevenly distributed message just like https://github.com/apache/rocketmq/issues/5672#issuecomment-1357085525 discussed.
