### ISSUE TITLE
Unable to enter the dead letter queue after the maximum number of order message consumption failures

### ISSUE THREAD

**Issue by ywagd** [apache/rocketmq#5717]
如下图中，我使用了顺序消费，重试两次。然后重试了两次后，并没有生成死信队列。而是继续重试，重试间隔为1分钟，我设置的重试间隔为5S。
![图片](https://user-images.githubusercontent.com/35673963/208066434-5995c62a-c9bd-446e-9673-4b6bff8034e5.png)

**Comment by ywagd** [comment]
I use 5.0.0 Version

**Comment by xiaoyifang** [comment]
https://blog.51cto.com/u_13626762/4727863

**Comment by RongtongJin** [comment]
Hi @ywagd, I tried with the latest code on my Mac, and nothing you said happened. Or you can elaborate on more detailed steps of reproduced.
