### ISSUE TITLE
The server crash when i do pressure test to send messages

### ISSUE THREAD

**Issue by Cicizz** [apache/rocketmq#572]
The server crash when i do pressure test to send messages.there is some describption  in hs_pid_xxx.log：
Faild to write code dump.Core dumps have been disabled. And the thread is `ReputMessageService`
i don't have any ideas about how to solve this problem.
**Environment:**
JDK1.8  
apache-rocketmq4.3.1
2master-2slave
8cpu and 16g memory
**Test script**
distribution/benchmark

how to solve this problem？thanks。

**Comment by AnyOSR** [comment]
can you give more details about the problem?e.g. the full error information

**Comment by Cicizz** [comment]
@AnyOSR thanks,i have solved  this problem,the problem was caused by a disk problem.
