### ISSUE TITLE
[code smell] System.currentTimeMillis() is a static method ,wrap it as a class method is inconvenient.

### ISSUE THREAD

**Issue by xiaoyifang** [apache/rocketmq#5720]
https://github.com/apache/rocketmq/blob/81e3648e3fcb1995897db3960a4561d6047b696c/common/src/main/java/org/apache/rocketmq/common/SystemClock.java#L19-L22

In order to use SystemClock's `now` method , one has to define SystemClock class instance first ,then use as

`this.systemClock.now()`

suggest to replace the `now` method with a static method or just use `System.currentTimeMillis()` directly

**Comment by ShadowySpirits** [comment]
The current implementation reserves the possibility to use a different clock source, such as using a mock clock source in testing.

There is a similar usage in guava:

```java
  /**
   * Creates (but does not start) a new stopwatch, using the specified time source.
   *
   * @since 15.0
   */
  public static Stopwatch createUnstarted(Ticker ticker) {
    return new Stopwatch(ticker);
  }
```

**Comment by xiaoyifang** [comment]
> the possibility to use a different clock source

then `now` should be wrapped as a static method just as guava did.

**Comment by xiaoyifang** [comment]
I just check the originall rocket source ,there are more than 100 other places which use `System.currentTimeMillis()` directly.

![image](https://user-images.githubusercontent.com/105986/208232077-3b2e11a6-2794-4ba6-9c29-b612036067aa.png)

**Comment by ShadowySpirits** [comment]
> > the possibility to use a different clock source
> 
> then `now` should be wrapped as a static method just as guava did. Guava wraps a class method into a static method which is more reasonable.
> 
> as the possiblity to use a different clock source,is there any neccessary or just a over-design?

I'm just making a guess about the current design. IMO, It is inappropriate to use `System.currentTimeMillis()` in TimerMessageStore. If we can use the mock time source, it would be of great help to our test.

**Comment by xiaoyifang** [comment]
> It is inappropriate to use `System.currentTimeMillis()` in TimerMessageStore

this  can be set as a new issue to deal with.     

> it would be of great help to our test

test friendly is really a good aspect to concern.

**Comment by ShadowySpirits** [comment]
We currently use less precise means of validating delayed messages, which leads to some flaky tests.

https://github.com/apache/rocketmq/blob/81e3648e3fcb1995897db3960a4561d6047b696c/test/src/main/java/org/apache/rocketmq/test/util/VerifyUtils.java#L85-L96

**Comment by xiaoyifang** [comment]
IMO ,I think it(the flaky tests) was not caused by time precision ,it's the nature of  time testing especially when used in unit test.

**Comment by xiaoyifang** [comment]
btw,there are some issue in the above verifyDelay.
![image](https://user-images.githubusercontent.com/105986/208237902-4059d67e-1e71-4796-bf8c-ec35be72a45e.png)
