### ISSUE TITLE
[code disscussion] the use of threadlocal variabe in evenly distributed message logic?

### ISSUE THREAD

**Issue by xiaoyifang** [apache/rocketmq#5729]
https://github.com/apache/rocketmq/blob/81e3648e3fcb1995897db3960a4561d6047b696c/client/src/main/java/org/apache/rocketmq/client/common/ThreadLocalIndex.java#L23-L35

this threadLocal variable `threadLocalIndex` is used in many places and used to evenly distributed the message.

IMO,I think threadlocal variable may not be a good idea,  a global variable(or a class variable) should be more suitable to ensure the messages were distributed evenly globally.

the threadlocal variable will has no problem especially when distibuting a large amount of message,the resulted message will be evenly distributed . But when the messages amount is small and messagequeue is a little bigger , there would be a chance to see the message is unevenly distributed.

![image](https://user-images.githubusercontent.com/105986/208278330-39b37f18-b988-4606-badd-f02523c72b2b.png)

I'm not very familiar with the distibution logic , so plz correct me if I'm wrong.

**Comment by ShadowySpirits** [comment]
It is indeed uneven distribution when the number of messages is low. But it doesn't matter. IMO, only the uneven distribution of a large number of messages will have an impact on consumption. It may be a better choice to achieve eventual balance with less cost rather than absolute balance with complex consistency logic.

**Comment by xiaoyifang** [comment]
agreed ,

another point is that the threadlocal can be replaced with a class variable. anyway it is not a big deal.
