### ISSUE TITLE
The disk space is enough, but I got "service not available now, maybe disk full" error after i run the program some times

### ISSUE THREAD

**Issue by gesanri** [apache/rocketmq#573]
**BUG REPORT**

1. I've installed the rocketmq in windows, follow the page https://www.jianshu.com/p/4a275e779afa, the nameserver, broke, and rocketmq console hava started rightly
2. I've run a simple producer-consumer example, follow the page https://blog.csdn.net/zhglance/article/details/54962870, I run the RocketMQConsumerTest firstly, and then I run the RocketMQProducerTest, I can get the right result.
3. I stop the RocketMQProducerTest and I start it again(the RocketMQConsumerTest is still running)  , I get the error as below:

org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [402]ms, Topic: MQ-MSG-TOPICS-TEST, BrokersSent: [PC-20170208IHWA, PC-20170208IHWA, PC-20170208IHWA]
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:544)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1069)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1023)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:214)
	at testrocketmq.RocketMQProducer.send(RocketMQProducer.java:47)
	at testrocketmq.RocketMQProducerTest.main(RocketMQProducerTest.java:22)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now, maybe disk full, CL:  0.97 CQ:  0.97 INDEX:  0.97, maybe your broker machine memory too small.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:551)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:353)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:335)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:298)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:696)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:463)
	... 5 more

I've installed the rocketmq in d disk, the total space is 61.7G, and the left space is 29.4G, I've checked the error in google, but all they say is that the space is not enough, I doubt about it as I've almost 50% space left, and if the space is not enough, why I can get the right result first time

And I have tried that, If I restart the broker, the program can run rightly again for about 5 or 6 times, and then the error happen again

**Comment by Ah39** [comment]
free -g , memory check ?

**Comment by gesanri** [comment]
> free -g , memory check ?

I've pointed out that, I'm running in windows, not linux

**Comment by KKsmall** [comment]
May I ask if your problem has been solved? I have the same test problem as you

**Comment by 812406210** [comment]
> > free -g , memory check ?
> 
> I've pointed out that, I'm running in windows, not linux

me too, i also install in win10, it also exist this problem ,  i want to handle this problem ,but  it isn't works . please  tell me how to resolve it ? thanks

**Comment by KANLON** [comment]
i have the same problem too, run in win10, rocketmq version : 4.5.2

**Comment by duhenglucky** [comment]
We will try to reproduce the above problem on Windows. Can you provide some server-side logs?

**Comment by wanchenqi** [comment]
This question still alive and haven't been resolved yet.......

**Comment by lenozhi** [comment]
you just do that:
1. mqbroker.cmd -c  broker.conf ,  borker.conf in ROCKETMQ_HOME/conf 
2. in broker.conf, you can set diskMaxUsedSpaceRatio = 99,  the default value is 75.

and i have a question, in  class MessageStoreConfig,  the property diskMaxUsedSpaceRatio is not decorated by @ImportantField.
what's means @ImportantField? i just find some code:

```
        if (onlyImportantField) {
                        Annotation annotation = field.getAnnotation(ImportantField.class);
                        if (null == annotation) {
                            continue;
                        }
                    }

                    if (logger != null) {
                        logger.info(name + "=" + value);
                    } else {
                    }
                }
            }

```
 just for log? i dont' know.

**Comment by HScarb** [comment]
Can you provide broker logs and broker config? And what version of RocketMQ do you use?
Maybe you set your store path to C:\ and C:\ is almost full.
The config `diskMaxUsedSpaceRatio` indicates RocketMQ's max disk usage roatio, which default is 75.
Check your store path config and if the store disk is almost full

**Comment by HScarb** [comment]
> you just do that:
> 
> 1. mqbroker.cmd -c  broker.conf ,  borker.conf in ROCKETMQ_HOME/conf
> 2. in broker.conf, you can set diskMaxUsedSpaceRatio = 99,  the default value is 75.
> 
> and i have a question, in class MessageStoreConfig, the property diskMaxUsedSpaceRatio is not decorated by @ImportantField. what's means @ImportantField? i just find some code:
> 
> ```
>         if (onlyImportantField) {
>                         Annotation annotation = field.getAnnotation(ImportantField.class);
>                         if (null == annotation) {
>                             continue;
>                         }
>                     }
> 
>                     if (logger != null) {
>                         logger.info(name + "=" + value);
>                     } else {
>                     }
>                 }
>             }
> ```
> 
> just for log? i dont' know.

I guess the `@ImportantField` is for logging important fields.

when calling `MaxAll.printObjectProperties(final InternalLogger logger, final Object object, final boolean onlyImportantField)`, if you set `onlyImportantField` as `true`, it will only log the `@ImportantField` annotated fields of the `object`

**Comment by wz2cool** [comment]
meet the same problem in win 10

**Comment by jeffchanjunwei** [comment]
meet the same problem in centos. & 4.2.0 version
