### ISSUE TITLE
Why I config the brokerIP1, and restart the broker,the brokerIP1 not change

### ISSUE THREAD

**Issue by SuYong1** [apache/rocketmq#5737]
This is the step I config the brokerIP1
1，edit the config file：conf/broker.conf
2，add a pulic IP(My AliCloud host public IP) as brokerIP1： brokerIP1=xx.xx.xx.xx
3，save config file and restart broker process：nohup ./bin/mqbroker -c ./conf/broker.conf -n xx.xx.xx.xx:9876 &
The broker boot sucessfully

But the problem is:
The brokerIP1 in nameServer is still the Intranet IP.Not the public IP I set in broker.conf
How can I set the brokerIP1 force.

The operation system is Ubuntu 22.04.1 LTS
The public IP is not shown in network cards

**Comment by SuYong1** [comment]
I have read the source code of rocketmq 5.0
This method:org.apache.rocketmq.common.BrokerConfig#setBrokerIP1
is not called in the start method in rocketmq?
![image](https://user-images.githubusercontent.com/20244320/208559985-51357e7a-997f-496b-9aae-48bcedce2baf.png)


So,in the start method : org.apache.rocketmq.broker.BrokerStartup#main
The brokerIP! will only be initialized by this method : org.apache.rocketmq.common.utils.NetworkUtil#getLocalAddress ?
![image](https://user-images.githubusercontent.com/20244320/208560236-cbe66f39-baf7-4998-a1e2-0f512906fb6b.png)

**Comment by SuYong1** [comment]
I switch the rocketmq version to 4.8,this problem solved

![1671506194393](https://user-images.githubusercontent.com/20244320/208573301-df5243c1-a2c0-4dbd-8372-525bf98cccda.png)

**Comment by Oliverwqcwrw** [comment]
problem is solved
