### ISSUE TITLE
[code optimization] simplify the method updateFaultItem

### ISSUE THREAD

**Issue by xiaoyifang** [apache/rocketmq#5738]
https://github.com/apache/rocketmq/blob/e77d0673f8f96c7aff3a2252d79f87952539c7e4/client/src/main/java/org/apache/rocketmq/client/latency/LatencyFaultToleranceImpl.java#L30-L49

the logic is to update the existed one or ,put the new item.

and can be simpilified into 
pseudocode:
```
var item  = new FaultIem();
init(item)
put(name,item)

```

**Comment by xiaoyifang** [comment]
original code is ok.

**Comment by HScarb** [comment]
Your code create a new `FaultItem` every time, I think it's not necessary when old item exists.

**Comment by xiaoyifang** [comment]
> Your code create a new FaultItem every time, I think it's not necessary when old item exists.

update the old existed item is a little complex in concurrent situations as the original code just did. 
the code did create new item every time ,but the GC should ease the trouble at last. 

At last I think your concern is reasonable
