### ISSUE TITLE
关于RocketMQ消息存储的几点问题

### ISSUE THREAD

**Issue by hutu92** [apache/rocketmq#574]
最近将RocketMQ的底层存储源码逐行看了一遍，发现了如下几个问题，希望能逐个解答一下或者修复该问题（如果我是对的话）。谢谢:two_hearts:。

**1.关于锁synchronized的使用问题；**

https://github.com/apache/rocketmq/blob/1bedba8cbcef32554d2dc80f2a340ea686d68ba9/store/src/main/java/org/apache/rocketmq/store/CommitLog.java#L1069

https://github.com/apache/rocketmq/blob/1bedba8cbcef32554d2dc80f2a340ea686d68ba9/store/src/main/java/org/apache/rocketmq/store/CommitLog.java#L1136

我认为上述两处的synchronized是完全没有必要的。减少没必要的锁的使用会增加性能:smile:。

**2. 睡眠时间不合理，可能会造成正在处理的消息响应失败；**

https://github.com/apache/rocketmq/blob/1bedba8cbcef32554d2dc80f2a340ea686d68ba9/store/src/main/java/org/apache/rocketmq/store/CommitLog.java#L1131

GroupCommitService此处的睡眠时间是否合理？

因为是同步刷盘策略，设置时间过短，在shutdown时，可能会造成正在处理的消息（eg，正在执行appendMessages的消息）来不及刷盘，进而响应失败（FLUSH_DISK_TIMEOUT）。

是否可以采用其它方式？或者适当延长下时间？10毫秒是不是太短了。

**3. 可能会造成消息丢失；**

https://github.com/apache/rocketmq/blob/1bedba8cbcef32554d2dc80f2a340ea686d68ba9/store/src/main/java/org/apache/rocketmq/store/CommitLog.java#L943-L947

CommitRealTimeService此处没有第2点中提到的sleep机制。这里是采用尝试10次commit。

举个简单的场景：

1. A 在执行appendMessages；
2. B 在执行appendMessages；
3. 在B执行完appendMessages，还未来得及通知CommitRealTimeService，与此同时shutdown；
4. 注意，A还未执行完appendMessages；
4. 按照上述代码逻辑，会尝试10次commit，在第1次时就能将B消息commit，并结束循环；
5. A 执行完appendMessages；

**问题就在于A消息不会被commit了，A消息丢失。但给客户端返回的响应就是OK:anger:。**

相同的，**FlushRealTimeService异步刷盘也有类似问题。**

**4. sleep(0)的问题**

https://github.com/apache/rocketmq/blob/1bedba8cbcef32554d2dc80f2a340ea686d68ba9/store/src/main/java/org/apache/rocketmq/store/MappedFile.java#L507

-XX:+ConvertSleepToYield 这个参数默认就是 true，如果 sleep 0 的话会转换成 yield

但是 **ConvertSleepToYield 设为 false 时，会进行 sleep，且 sleep 的最小时间是 1 ms**，也就是说 ConvertSleepToYield 为 false 时，哪怕是 sleep 0 实际上跟 sleep 1 是一样的。**这样的话，并不会让出线程的时间片。**

我个人认为 RocketMQ 应改为 Thread.yield 处理。或许sleep(0)有其它的意图？

**5.commitLog写满时，消息的处理问题**

https://github.com/apache/rocketmq/blob/1bedba8cbcef32554d2dc80f2a340ea686d68ba9/store/src/main/java/org/apache/rocketmq/store/CommitLog.java#L1091-L1096

同步刷盘策略下，正常消息刷盘时，依赖第二次循环将`flushOK`置为true。但是如果当消息A写入时发现commitLog已经写满，则消息A会被写入下一个commitLog。当前待刷盘的commitLog会有两个。

A消息通知刷盘服务执行刷盘，第一次循环刷盘（刷入第一个commitLog的末尾数据）时`flushOK = CommitLog.this.mappedFileQueue.getFlushedWhere() >= req.getNextOffset();`肯定为false，第二次刷盘（刷入消息A）时`flushOK = CommitLog.this.mappedFileQueue.getFlushedWhere() >= req.getNextOffset();`也肯定是false，需要第三次循环来将`flushOK`置为true。

所以上述场景下，`flushOK`为false。但实际消息A已经刷盘成功了。

**Comment by vongosling** [comment]
@hutu92 感谢你的问题，考虑到社区对issue的定位，你的问题我们将在邮件里展开讨论

**Comment by chenzuyibao** [comment]
@archessay 想问下《5.commitLog写满时，消息的处理问题》这个是怎么处理了，我是在for循环结束后再此判断flushOK的值。我看最新的版本也没有改动这个地方，那这个地方是如何定义处理了呢？谢谢！！
