### ISSUE TITLE
[code discussion] Should the method UtilAll.getIP() return a localhost ?

### ISSUE THREAD

**Issue by RagingSpud** [apache/rocketmq#5740]
https://github.com/apache/rocketmq/blob/72786535067310b79138e8ae4509851d85d35b95/common/src/main/java/org/apache/rocketmq/common/UtilAll.java#L604-L619

This method basically traversal network interfaces and find a non-private ip.And if failed to find one, fall back to the whatever ip it found in the first netInterface, which in my setting is localhost(from lo0).
It is used to create unique id, so this is no good behavior right ? 
How about let the lan ip have a higher priority than localhost ?

**Comment by ShadowySpirits** [comment]
Agree, and `isInternalIP` function should return `true` when ip is 127.0.0.1. Will you submit a pr to improve this?

**Comment by RagingSpud** [comment]
> Agree, and `isInternalIP` function should return `true` when ip is 127.0.0.1. Will you submit a pr to improve this?
I am willing to try.
