### ISSUE TITLE
RemotingCommand static code is wrong

### ISSUE THREAD

**Issue by xiaorongZheng** [apache/rocketmq#5742]
org.apache.rocketmq.remoting.protocol.RemotingCommand
static {
        final String protocol = System.getProperty(SERIALIZE_TYPE_PROPERTY, System.getenv(SERIALIZE_TYPE_ENV));
        if (!isBlank(protocol)) {
            try {
                serializeTypeConfigInThisServer = SerializeType.valueOf(protocol);
            } catch (IllegalArgumentException e) {
                throw new RuntimeException("parser specified protocol error. protocol=" + protocol, e);
            }
        }
    }
uncorrect use with SerializeType#valueof method，The protocol type should change to byte

**Comment by mxsm** [comment]
Hi @xiaorongZheng  SerializeType#valueof paramter is string that this method is enum method, you can custom a enum has the valueof (String xxx) method. So this code is correct. 

```java
    public static SerializeType valueOf(byte code) {
        for (SerializeType serializeType : SerializeType.values()) {
            if (serializeType.getCode() == code) {
                return serializeType;
            }
        }
        return null;
    }
```
The above code was used in the following place.
```java
//RemotingCommand#getProtocolType
    public static SerializeType getProtocolType(int source) {
        return SerializeType.valueOf((byte) ((source >> 24) & 0xFF));
    }
```
