### ISSUE TITLE
Slave's store.log has many invalid log outputs in master-slave deploy mode

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq#5748]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

![image](https://user-images.githubusercontent.com/21963954/208847636-ca45fcd4-e11d-49f7-bc2d-f19d3e142b84.png)

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

#5611 add new log output
![image](https://user-images.githubusercontent.com/21963954/208847973-9a56df76-d2f2-401e-a494-794cd33398ed.png)

However, the current master-slave is stream-based replication, so the slave's reputMessageService thread will parse half messages, and logs should not be output at this time

**Comment by lizhimins** [comment]
In my opinion, errors should not be ignored when writing messages, which will increase the complexity of troubleshooting. May temporarily keep consistent with the original implementation works well.
