### ISSUE TITLE
while not use FileChannel.write()? rocketmq use mmap file write , may cause use a lot of share memory 

### ISSUE THREAD

**Issue by Ah39** [apache/rocketmq#575]
here  is a test for FileChannel.write() , and mmap file write
https://github.com/jkreps/valencia/blob/master/src/test/java/valencia/TestLinearWritePerformance.java
what,s more , MaxDirectMemorySize dont work for memory hold by mmap file .

**Comment by Ah39** [comment]
![image](https://user-images.githubusercontent.com/2367243/49436622-86c5f000-f7f4-11e8-88ce-332e7483bc24.png)
![image](https://user-images.githubusercontent.com/2367243/49436639-8c233a80-f7f4-11e8-935f-bc823e7e852a.png)

**Comment by duhengforever** [comment]
@Ah39 Compared with FileChannel, MMAP can write to the page cache directly, but FileChannel and use directbuffer need to write to  memory first, then write to the page cache. so RocketMQ has an advantage when writing a lot of small data into a file.

**Comment by Ah39** [comment]
@duhengforever but the rocketmq may hold 100G even more SHR memory .
**how to control the memory use by rocketmq ,by mmap file ??**

![image](https://user-images.githubusercontent.com/2367243/49513011-96b00380-f8ca-11e8-9cfd-4338ed7b53f5.png)

**Comment by duhenglucky** [comment]
> @duhengforever but the rocketmq may hold 100G even more SHR memory .
> **how to control the memory use by rocketmq ,by mmap file ??**
> 
> ![image](https://user-images.githubusercontent.com/2367243/49513011-96b00380-f8ca-11e8-9cfd-4338ed7b53f5.png)

Maybe using the dio in the future will be a good choice,  memory management is entirely done by the application layer.
