### ISSUE TITLE
RocketMQ version release roadmaps?

### ISSUE THREAD

**Issue by Stevenzall** [apache/rocketmq#5750]
Hi Community, I would like to know the approximate plan for the release of the next version. According to the previous release cycle, 4.9.5 and 5.0.1 should be released soon. I want to know when this can become a reality? and Proxy support for Remoting protocol is already a big feature to release as a minor version.

**Comment by Stevenzall** [comment]
@Oliverwqcwrw any ideas?

**Comment by lizhimins** [comment]
We have a lot of pr since last released, Hoped you can pay attention to this question. @drpmma

**Comment by Stevenzall** [comment]
@lizhimins Yes, it has been three months since the last release and we have also submitted many RIPs features. IMO, it's time to discuss the release of version 5.0.1 and 4.9.5. I hope to see the latest version released by the end of the year or early in the new year.
