### ISSUE TITLE
Performance drops dramatically in controller mode when transientStorePoolEnable=true

### ISSUE THREAD

**Issue by riki-wang** [apache/rocketmq#5751]
1. Problem
   Broker在自动故障转移模式下，设置transientStorePoolEnable=true导致benchmark性能测试急剧下降
   - transientStorePoolEnable=true测试性能
      ![image](https://user-images.githubusercontent.com/23468936/208872480-d84413b5-4d64-4278-a56c-ba6069122521.png)

   - transientStorePoolEnable=false测试性能
     ![image](https://user-images.githubusercontent.com/23468936/208872822-c22ff63b-bcc3-48da-8f7c-df3e72a98326.png)

2. Environment
    - RocketMQ 5.0 1Master-1Slave Dledger Controller Mode
    - broker配置
    ```
      brokerClusterName = DefaultCluster
      brokerName = broker-a
      brokerId = -1
      deleteWhen = 04
      fileReservedTime = 12
      enableControllerMode = true
      namesrvAddr = 10.110.150.106:9876;10.110.150.107:9876;10.110.150.108:9876
      controllerAddr = 10.110.150.106:59878;10.110.150.107:59878;10.110.150.108:59878
      allAckInSyncStateSet = true

      flushDiskType = ASYNC_FLUSH

      transientStorePoolEnable=true
      transientStorePoolSize=3

      listenPort = 59011

      storePathRootDir=/home/data/rocketmq/broker-a/store
      storePathIndex=/home/data/rocketmq/broker-a/store/index
      storeCheckpoint=/home/data/rocketmq/broker-a/store/checkpoint
      abortFile=/home/data/rocketmq/broker-a/store/abort
      storePathCommitLog=/home/data/rocketmq/broker-a/store/commitlog
      storePathConsumerQueue=/home/data/rocketmq/broker-a/store/consumequeue
      storePathEpochFile=/home/data/rocketmq/broker-a/store/storePathEpochFile
    ```

**Comment by mxsm** [comment]
Hi @riki-wang 
![image](https://user-images.githubusercontent.com/15797831/209035409-ba8ec056-0ac4-457c-a825-83eb510a8dfc.png)
![image](https://user-images.githubusercontent.com/15797831/209035472-a20cecd4-4613-4d70-a4ce-df0bbf85b7d2.png)
Little performance impact

**Comment by riki-wang** [comment]
> Hi @riki-wang ![image](https://user-images.githubusercontent.com/15797831/209035409-ba8ec056-0ac4-457c-a825-83eb510a8dfc.png) ![image](https://user-images.githubusercontent.com/15797831/209035472-a20cecd4-4613-4d70-a4ce-df0bbf85b7d2.png) Little performance impact
首次启动会有这个问题

**Comment by mxsm** [comment]
> > Hi @riki-wang ![image](https://user-images.githubusercontent.com/15797831/209035409-ba8ec056-0ac4-457c-a825-83eb510a8dfc.png) ![image](https://user-images.githubusercontent.com/15797831/209035472-a20cecd4-4613-4d70-a4ce-df0bbf85b7d2.png) Little performance impact
> > 首次启动会有这个问题，而且是要在controller模式下，1master-1slave

我试下首次启动，我上面的模式就是Controller的A-HA的自主切换模式。
![image](https://user-images.githubusercontent.com/15797831/209038223-956961bd-796b-4a24-9106-1cbff405386d.png)

**Comment by mxsm** [comment]
@riki-wang 
![image](https://user-images.githubusercontent.com/15797831/209039139-979de2ea-780c-455e-9df5-32559ff38734.png)

![image](https://user-images.githubusercontent.com/15797831/209039937-b9b9aa4d-a974-4f97-ad16-7e29df373354.png)

When first start on controller model, broker has performance impact. 
I will try to find it and fix.
thanks for you catch.

**Comment by RongtongJin** [comment]
Hi @riki-wang, the issue of enabling transientStorePool in controller mode is still fixed in #5722 . After the repair is completed, we can continue to test.

**Comment by riki-wang** [comment]
> 

本来是准备给生产环境引入自动故障转移的，就突然测出这个性能bug了

**Comment by riki-wang** [comment]
> Hi @riki-wang, the issue of enabling transientStorePool in controller mode is still fixed in #5722 . After the repair is completed, we can continue to test.


本来是准备给生产环境引入自动故障转移的，就突然测出这个性能bug了

**Comment by RongtongJin** [comment]
@riki-wang PR #5722 has fixed it. You can try this PR code.

**Comment by Oliverwqcwrw** [comment]
close as fixed

**Comment by riki-wang** [comment]
Rocketmq v5.1.0 still has this issue
