### ISSUE TITLE
msg may be null

### ISSUE THREAD

**Issue by xiaoyifang** [apache/rocketmq#5766]
https://github.com/apache/rocketmq/blob/646d04f42524636ad09364af2a67fa8ab8b6b8fa/client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java#L83-L108

![image](https://user-images.githubusercontent.com/105986/209419871-a59d5522-100c-4199-b0a8-74ed74f0933f.png)

![image](https://user-images.githubusercontent.com/105986/209419985-073f5738-8441-458d-a919-26e4c77a0985.png)

**Comment by Oliverwqcwrw** [comment]
IMO, This is just an ide check, which is not null from a business logic point of view

Please let me know if I am missing something.

**Comment by xiaoyifang** [comment]
`msg = msgTreeMap.firstEntry().getValue();` this line may return null ,though in reality it is not possible.
and if exception is throw ,  `msg` may still be null

and the logic is a little complex ,I think it can be rewrite with a more readable code.
