### ISSUE TITLE
back-incompatible the RequestCode(`REGISTER_TOPIC_IN_NAMESRV`) with `217` value

### ISSUE THREAD

**Issue by TheNorthMemory** [apache/rocketmq#5768]
1. Please describe the issue you observed:

There was described the `217` code as `GET_KV_CONFIG_BY_VALUE` label, see [here](https://github.com/apache/rocketmq-client-cpp/blob/master/src/protocol/MQProtos.h#L98-L100)

```c++
  GET_KV_CONFIG_BY_VALUE = 217,
```

But since `5.0.0-beta`,  the RequestCode(`217`) may be reusable as `REGISTER_TOPIC_IN_NAMESRV`

https://github.com/apache/rocketmq/blob/ec5d3236f65786be7dde712dda5f5ee152d0dce6/remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestCode.java#L133

Those two kind of `RemotingCommand` operations looks like incompatible, the one `GET_KV_CONFIG_BY_VALUE` mostly same as fetching and another `REGISTER_TOPIC_IN_NAMESRV` sames to pushing.

It's suggest that toggle the `REGISTER_TOPIC_IN_NAMESRV` code to another one for the back compatible.

**Comment by leizhiyuan** [comment]
It seems only be defined in cpp api

there is no use in cpp now。https://github.com/search?q=repo%3Aapache%2Frocketmq-client-cpp+GET_KV_CONFIG_BY_VALUE&type=code

**Comment by TheNorthMemory** [comment]
> It seems only be defined in cpp api
> 
> there is no use in cpp now。https://github.com/search?q=repo%3Aapache%2Frocketmq-client-cpp+GET_KV_CONFIG_BY_VALUE&type=code

please take a look at this one [[rocketmq-client-nodejs](https://github.com/apache/rocketmq-client-nodejs)](https://github.com/apache/rocketmq-client-nodejs)
> This official Node.js client is a lightweight wrapper around [rocketmq-client-cpp](https://github.com/apache/rocketmq-client-cpp), a finely tuned CPP client.

**Comment by leizhiyuan** [comment]
I see

**Comment by Abhijeetmishr** [comment]
@TheNorthMemory @leizhiyuan @Oliverwqcwrw can I pick this up ?

**Comment by TheNorthMemory** [comment]
> @TheNorthMemory @leizhiyuan @Oliverwqcwrw can I pick this up ?

Sure, I'm not good at JAVA and glad to see it is solved.

**Comment by Oliverwqcwrw** [comment]
> @TheNorthMemory @leizhiyuan @Oliverwqcwrw can I pick this up ?

Sure, I assigned it to you :-)

**Comment by Abhijeetmishr** [comment]
@leizhiyuan @Oliverwqcwrw @Oliverwqcwrw are we planning to implement rocketmq-client-sdk for scala just asking if in case ?

**Comment by Oliverwqcwrw** [comment]
> @leizhiyuan @Oliverwqcwrw @Oliverwqcwrw are we planning to implement rocketmq-client-sdk for scala just asking if in case ?

cc @aaron-ai

**Comment by TheNorthMemory** [comment]
@Abhijeetmishr  

1. The `REGISTER_TOPIC_IN_NAMESRV` was added on 5.0+ version, but there were a lot of historic versions from 3.x to 4.x. In my opinion, toggle the one `REGISTER_TOPIC_IN_NAMESRV` to another code shall be a good choice. 
2. see https://github.com/ali-sdk/ali-ons/blob/master/lib/protocol/request_code.js#L108

**Comment by Abhijeetmishr** [comment]
@TheNorthMemory 
In all the places except rocketmq we are using this 
> // Namesrv gets all server ip information through project
> exports.GET_KV_CONFIG_BY_VALUE = 217;

but in rocketmq we are using this 
> // for registering topic 
> public static final int REGISTER_TOPIC_IN_NAMESRV = 217;

So you are suggesting to create different code for this **REGISTER_TOPIC_IN_NAMESRV**

Thanks!

**Comment by TheNorthMemory** [comment]
Searching the github with [**GET_KV_CONFIG_BY_VALUE with language Java**](https://github.com/search?l=Java&q=GET_KV_CONFIG_BY_VALUE&type=Code), there were a lots of `public static final int GET_KV_CONFIG_BY_VALUE = 217;` definitions on the rocketmq previous versions.  The `GET_KV_CONFIG_BY_VALUE` is not a new `RequestCode`, It was already exists.

I think the code **217** was inappropriated mapping to `REGISTER_TOPIC_IN_NAMESRV` since **5.0.0-beta** and sugguest that creating a new code, eg: something like `1217` for the `REGISTER_TOPIC_IN_NAMESRV`.

@Abhijeetmishr

**Comment by Oliverwqcwrw** [comment]
IMO, we will mainly maintain [rocketmq-clients](https://github.com/apache/rocketmq-clients) in the future. Is it necessary to solve this compatibility problem

**Comment by Abhijeetmishr** [comment]
> IMO, we will mainly maintain [rocketmq-clients](https://github.com/apache/rocketmq-clients) in the future. Is it necessary to solve this compatibility problem

@Oliverwqcwrw should i close this ?
