### ISSUE TITLE
4.4.0 causes heap memory to soar rapidly, but 4.8.0 no such problem

### ISSUE THREAD

**Issue by qq31715879** [apache/rocketmq#5773]
The server version is 4.3.0

use 4.4.0 jar
`<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-spring-boot-starter</artifactId>
    <version>2.0.2</version>
</dependency>`

jvm  heap memory increases rapidly, and consumption is delayed, and the consumption speed is seriously reduced.

but client jar version gradle to 4.8.0, the problem disappears.
`<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-spring-boot-starter</artifactId>
    <version>2.2.0</version>
</dependency>`

hope big guy help analyze.

**Comment by drpmma** [comment]
Maybe the better idea is to upgrade the client version in `rocketmq-spring-boot-starter`. 
Because there are a lot of bug fixes between 4.4.0 and 4.8.0, therefore, it's difficult to analyze detail issue.

**Comment by qq31715879** [comment]
> Maybe the better idea is to upgrade the client version in `rocketmq-spring-boot-starter`. Because there are a lot of bug fixes between 4.4.0 and 4.8.0, therefore, it's difficult to analyze detail issue.

okok
