### ISSUE TITLE
SQL Filtering supports `/`

### ISSUE THREAD

**Issue by maqingxiang** [apache/rocketmq#5774]
Here we have the scenario where the message properties are named with `/`, e.g. `a/b/c`. To filter those attributes, we're eager on the enhancement of SQL filterting that is able to handle special characters such as `/`.

We've tried defining `/` in the `ID` of `org.apache.rocketmq.filter.parser.SelectorParser` but it didn't worked as expected, the error message is like
Caused by: com.alipay.sofa.sofamq.org.shade.apache.rocketmq.client.exception.MQClientException: CODE: 23  DESC: org.apache.rocketmq.filter.parser.TokenMgrError: Lexical error at line 1, column 3.  Encountered: "b" (98), after : "/"

**Comment by maqingxiang** [comment]
@aaron-ai @mxsm could you please help to check it.

**Comment by tsunghanjacktsai** [comment]
Hey @maqingxiang , would you like to provide the complete sql expression (or maybe a sample) that you used to filtered messages on the consumer side? Or better provide a use case for us to reproduce the error you had faced.
