### ISSUE TITLE
[code optimization] Repeated empty string check for proxy module.

### ISSUE THREAD

**Issue by yx9o** [apache/rocketmq#5776]
Hi Community,
The latest is learning the proxy module, and found that there are some problems with repeated empty string checks.
E.g:
org.apache.rocketmq.proxy.grpc.v2.common.GrpcValidator#validateTopic(java.lang.String)
org.apache.rocketmq.client.Validators#checkTopic
![image](https://user-images.githubusercontent.com/12792261/209742326-ef78db05-0b19-4a2b-aa85-de440df78c22.png)
![image](https://user-images.githubusercontent.com/12792261/209742344-cd697ad7-c433-4f43-a374-bcade530aaea.png)

org.apache.rocketmq.proxy.grpc.v2.common.GrpcValidator#validateConsumerGroup(java.lang.String)
org.apache.rocketmq.client.Validators#checkGroup
![image](https://user-images.githubusercontent.com/12792261/209742444-5ce503e4-aae7-4516-8926-d14b86ffd6b8.png)
![image](https://user-images.githubusercontent.com/12792261/209742460-9605963c-71c3-4686-b7e7-d0544d54f0e9.png)

I think duplicate checks should be removed.

**Comment by Oliverwqcwrw** [comment]
merged
