### ISSUE TITLE
RocketMQ compaction topic does not support tombstone messages 

### ISSUE THREAD

**Issue by sunxiaojian** [apache/rocketmq#5779]
RocketMQ compaction topic needs to support clearing useless messages

**Comment by fuyou001** [comment]
could you  describle  the scenar

**Comment by ltamber** [comment]
Actually if the value part of the message is null or empty, the message will not retain in the compaction process.
the code is [here](https://github.com/apache/rocketmq/blob/develop/store/src/main/java/org/apache/rocketmq/store/kv/CompactionLog.java#L329)

**Comment by sunxiaojian** [comment]
> Actually if the value part of the message is null or empty, the message will not retain in the compaction process. the code is [here](https://github.com/apache/rocketmq/blob/develop/store/src/main/java/org/apache/rocketmq/store/kv/CompactionLog.java#L329)

It seems that DefaultMQProducer does not support sending messages with empty value

**Comment by sunxiaojian** [comment]
@fuyou001 Are you dealing with this problem ？
