### ISSUE TITLE
[Feature] Support for large message chunked transfer 

### ISSUE THREAD

**Issue by hzh0425** [apache/rocketmq#5799]
Apache RocketMQ, like all messaging systems, imposes a size limit on each message sent to a broker. This prevents the load per message from exceeding the maxMessageSize set in the broker, which defaults to 4 MB.

However, in application scenarios such as image processing and audio processing, many users need RocketMQ clients to send large messages to brokers. You can achieve this by adjusting maxMessageSize. However, this approach can cause many problems. For example, if a client publishes a 100 MB message, and the broker allows storing the message to disk, the broker will spend a lot of IO resources processing the message. This will affect broker flushing performance and cause a backlog of messages.

Therefore, when RocketMQ sends large messages, in addition to increasing the value of maxMessageSize, we can also support the 'message chunking' function.
Through message chunking, producers can split large messages into multiple chunks according to maxMessageSize, and send each chunk to the broker as a normal message. The consumer will then assemble these chunked messages back into the original message.

For example:
![image](https://user-images.githubusercontent.com/58988019/210167460-fad531a2-02bb-4ee7-91c3-f671a3174e5c.png)

*Therefore, it's time to discuss whether 'message chunking' should be supported or not.*

**Comment by mxsm** [comment]
IMO, large message  is mostly not needed, In most cases prefer to upload to SSO first and send the data address through MQ.The benefit of this is that the MQ can send messages more efficiently and the MQ can store less large objects, which is mostly used for storage such as SSO.

**Comment by hzh0425** [comment]
> IMO, large message is mostly not needed, In most cases prefer to upload to SSO first and send the data address through MQ.The benefit of this is that the MQ can send messages more efficiently and the MQ can store less large objects, which is mostly used for storage such as SSO.

I don't think it's a good solution to store the 'message itself' with the help of an external system:
1. In some scenarios (not audio and video), the size of the message body has exceeded 'maxMessageSize', and we cannot separate the message and store it in other systems. Although such scenarios are rare, it does not mean that there are no such scenarios.
2. The message system itself is a storage engine, and we don't want to use an additional external system to store messages.
