### ISSUE TITLE
为什么自己搭建的rocketmq不能创建顺序消费、延时消费的TOPIC类型，而阿里云的rocketmq可以创建？

### ISSUE THREAD

**Issue by linux-lpx** [apache/rocketmq#5827]
![2clg8f8Ddm](https://user-images.githubusercontent.com/15316382/210734220-c4d02d14-9cd4-4138-a972-a52a1c5311c8.jpg)
![5d76d8f7-ef87-46c4-8472-7ca228329391](https://user-images.githubusercontent.com/15316382/210734256-b5021e2e-ccad-4e8e-88f5-b490600c3430.jpeg)

**Comment by fuyou001** [comment]
not support yet. you can use mqadmin tools create delay topic

**Comment by linux-lpx** [comment]
can you give a sample？I don't know which argument to use
![image](https://user-images.githubusercontent.com/15316382/210919384-911b426d-ccce-4d0b-a3f6-26a8c23db679.png)

**Comment by RongtongJin** [comment]
> can you give a sample？I don't know which argument to use ![image](https://user-images.githubusercontent.com/15316382/210919384-911b426d-ccce-4d0b-a3f6-26a8c23db679.png)

```
# default
sh mqadmin updateTopic -n <nameserver_address> -t <topic_name> -c <cluster_name>
# normal topic
sh mqadmin updateTopic -n <nameserver_address> -t <topic_name> -c <cluster_name> -a +message.type=NORMAL
# fifo topic
sh mqadmin updateTopic -n <nameserver_address> -t <topic_name> -c <cluster_name> -a +message.type=FIFO
# delay topic
sh mqadmin updateTopic -n <nameserver_address> -t <topic_name> -c <cluster_name> -a +message.type=DELAY
# transaction topic
sh mqadmin updateTopic -n <nameserver_address> -t <topic_name> -c <cluster_name> -a +message.type=TRANSACTION
```
