### ISSUE TITLE
codecov url in README is incorrect

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#5829]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

<img width="457" alt="image" src="https://user-images.githubusercontent.com/31796988/210742597-e7aa4369-4ea4-4135-9d7b-bfdc25de5248.png">

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by mahaitao617** [comment]
i want to try fix it,pls assign to me,ths

**Comment by Oliverwqcwrw** [comment]
Welcome! @mahaitao617
