### ISSUE TITLE
RocketMQ Client can't run in GraalVM environment

### ISSUE THREAD

**Issue by steverao** [apache/rocketmq#5835]
**Which Component**
eg. RocketMQ

**Describe what problem you have encountered**
RocketMQ Client support run in GraalVM environment. it can't run now. You can reproduce this issue by following these steps：
Prerequisites Start RocketMQ broker and nameserver

1. Download the Spring Cloud Alibaba project, switch to the 2022.x branch, enter the `rocketmq-broadcast-producer-example` module, enter the pom.xml file, add below dependency and plugin.
 ```
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>fastjson</artifactId>
    <version>2.0.22</version>
</dependency>

<plugin>
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
  <configuration>
    <classesDirectory>${project.build.outputDirectory}</classesDirectory>
    <metadataRepository>
      <enabled>true</enabled>
    </metadataRepository>
    <requiredVersion>22.3</requiredVersion>
    <buildArgs>
      --initialize-at-build-time=org.apache.commons.logging.LogFactoryService
    </buildArgs>
  </configuration>
  <executions>
    <execution>
      <id>add-reachability-metadata</id>
      <goals>
        <goal>add-reachability-metadata</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```
3. Execute `mvn clean -Pnative spring-boot:run`. After the application starts, it will scan the code dynamic properties. After about 10 seconds, stop the application through control+C, and there will be a `META-INF.native` in the resources directory. image directory, there will be a static configuration file corresponding to the dynamic properties of the code below. You need to enter the `reflect-config.json` file to delete the corresponding item of `org.springframework.integration.config.ConverterRegistrar$IntegrationConverterRegistration`.
4. Execute `mvn clean -Pnative native:compile` to build the native image. If it goes well, it will be built successfully, and then `target/rocketmq-broadcast-producer-example` should start the application and the problem should be reproduced.
![image](https://user-images.githubusercontent.com/25423978/210939807-16d8a57b-80de-4964-832f-e46adfb08672.png)

**Comment by ShadowySpirits** [comment]
It seems like your client can not connect to the nameserver. Please try `nc 127.0.0.1 9876 -zv` to check if the nameserver is running.

**Comment by steverao** [comment]
> It seems like your client can not connect to the nameserver. Please try `nc 127.0.0.1 9876 -zv` to check if the nameserver is running.

No, I confirm that the nameserver and broker is running, I can send message in general method.

**Comment by lizhanhui** [comment]
@steverao The auto-scan of the reflection classes should be incomplete, check out the log output, there should be some ClassNotFound exceptions raised.

**Comment by lizhimins** [comment]
Check the client log

**Comment by steverao** [comment]
> ClassNotFound

yes, there are a lot of relevant ClassNotFound warning logs when I use `mvn clean -Pnative native:compile` to compile the demo, it's hard to find which one cause the sending message error. Do you have any suggestion to help me solve it?
![image](https://user-images.githubusercontent.com/25423978/213239619-725c5b42-9169-48ca-a1d5-3887ad1fa6cb.png)

**Comment by ouyanggan** [comment]
hello，man  I have same problem with you ,Do you have solve your problem?
