### ISSUE TITLE
[code discussition] Should the method queryAssignment request again?

### ISSUE THREAD

**Issue by WonderMing13** [apache/rocketmq#5836]
![image](https://user-images.githubusercontent.com/31891548/210945126-113b6be5-0545-4622-8cb7-6e2a15164e3d.png)

1. the method **tryQueryAssignment** and the method **getRebalanceResultFromBroker** both request to the broker to execute the queryAssignment method

Why not pass the result returned by the method tryQueryAssignment to the method getRebalanceResultFromBroker, which can reduce a network request

**Comment by ni-ze** [comment]
If the result is the same, I think it's not need to request twice.

**Comment by RongtongJin** [comment]
> ![image](https://user-images.githubusercontent.com/31891548/210945126-113b6be5-0545-4622-8cb7-6e2a15164e3d.png)
> 
> 1. the method **tryQueryAssignment** and the method **getRebalanceResultFromBroker** both request to the broker to execute the queryAssignment method
> 
> Why not pass the result returned by the method tryQueryAssignment to the method getRebalanceResultFromBroker, which can reduce a network request

I think this is really an enhancement, could you submit a pull request to polish it ？

**Comment by WonderMing13** [comment]
> > ![image](https://user-images.githubusercontent.com/31891548/210945126-113b6be5-0545-4622-8cb7-6e2a15164e3d.png)
> > 
> > 1. the method **tryQueryAssignment** and the method **getRebalanceResultFromBroker** both request to the broker to execute the queryAssignment method
> > 
> > Why not pass the result returned by the method tryQueryAssignment to the method getRebalanceResultFromBroker, which can reduce a network request
> 
> I think this is really an enhancement, could you submit a pull request to polish it ？

ok , I will try to fix
