### ISSUE TITLE
Failed to examine pop consumer group status/progress/connection, no topic route for retry topic

### ISSUE THREAD

**Issue by HScarb** [apache/rocketmq#5844]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

  1. Use pop consume API `MQClientAPIImpl.popMessageAsync` to pop a message from topic
  2. Use MQAdmin consumerProgress/consumerStatus/consumerConnection command to examine pop consumer stats

- What is expected to see?

Consumer stats returns properly

- What did you see instead?

```log
MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: %RETRY%cid-test
```

![image](https://user-images.githubusercontent.com/10664298/211361348-54c8ea78-cd8b-48b5-83cc-d6817cbfecb1.png)

2. Please tell us about your environment:

Rocketmq 5.0.1-snapshot, latest develop branch

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

`consumerProgress/consumerStatus/consumerConnection`
These three commands both build and examine route info for normal retry topic of pop consumer, that's where the exception raises, as pop consumer won't create a normal retry topic.

![image](https://user-images.githubusercontent.com/10664298/211362280-a02b4786-fce4-4712-86af-345b60d51563.png)

---

I didn't come up with a perfect solution for this issue, but I have several approches

  1. Build a dummy retry topic when a consumer call pop API for the first time.
  2. Catch the exception raised by `examineTopicRouteInfo`, so the MQAdmin commands would execute without exception

**Comment by ni-ze** [comment]
IMO, I think neither are good solution. Use retry topic just want to find the broker address. Maybe we can solution like this:
```java
Collection<BrokerData> values = this.examineBrokerClusterInfo().getBrokerAddrTable().values();
        for (BrokerData value : values) {
            String addr = value.selectBrokerAddr();
            if (StringUtils.isNotBlank(addr)) {
                ConsumerConnection result = this.mqClientInstance.getMQClientAPIImpl().getConsumerConnectionList(addr, consumerGroup, timeoutMillis);
                if (result != null) {
                    return result;
                }
            }
        }
```

**Comment by ShadowySpirits** [comment]
The broker creates the retry topic automatically when a consumer first sends a heartbeat.

see ClientManageProcessor#heartBeat:

https://github.com/apache/rocketmq/blob/a68078fef8315a0deeae32af42a029ccd2fa76a4/broker/src/main/java/org/apache/rocketmq/broker/processor/ClientManageProcessor.java#L112-L117

**Comment by RongtongJin** [comment]
> 1. MQClientAPIImpl.popMessageAsync

It seems that MQClientAPIImpl.popMessageAsync was directly called, resulting in no heartbeat being sent and no retry topic being created.

**Comment by xdkxlk** [comment]
The command like `consumerProgress` can set the topic name to avoid this problem by `-t`, in the short term.
