### ISSUE TITLE
mqAdmin does not work in 5.0.0 quick start document

### ISSUE THREAD

**Issue by lyingfromyou** [apache/rocketmq#5855]
![image](https://user-images.githubusercontent.com/24619864/211535500-ffff9d52-a20f-4bb2-b2cf-c8d2e468abdc.png)

![image](https://user-images.githubusercontent.com/24619864/211535453-915136d6-6111-494f-9910-61d0e5ae10a8.png)

**Comment by lyingfromyou** [comment]
需要添加 -b 或 -c 参数, 希望文档能补全

**Comment by mxsm** [comment]
@lyingfromyou  欢迎贡献提交PR, 你可以在[RocketMQ官网](https://github.com/apache/rocketmq-site)提交PR进行修复完善文档！

**Comment by RongtongJin** [comment]
I submit a pr https://github.com/apache/rocketmq-site/pull/434

**Comment by Oliverwqcwrw** [comment]
close as  merged
