### ISSUE TITLE
rocket mq 5.0 ubuntu 环境下broker启动不读取配置文件

### ISSUE THREAD

**Issue by wentao1994** [apache/rocketmq#5857]
操作系统：ubuntu
rockertmq版本： 5.0
问题描述： 在ubuntu下,用默认脚本启动broker不会读取配置文件
脚本路径：rocketmq-all-5.0.0/bin/mqbroker
问题行数：48
<img width="476" alt="image" src="https://user-images.githubusercontent.com/19541731/211706726-34ebaefe-dee5-4e15-aa18-c3fecf92ec56.png">

**Comment by ShadowySpirits** [comment]
What version of ubuntu are you using? And try `bash mqbroker` to get around this problem.

**Comment by mxsm** [comment]
Hi @wentao1994 this issue has fixed #5267

**Comment by wentao1994** [comment]
My problem was solved。 thx～～
