### ISSUE TITLE
What's the situation of RocketMQ 5.0 in a production environment?

### ISSUE THREAD

**Issue by Stevenzall** [apache/rocketmq#5873]
Hi, I want to know if there are any companies using version 5.0 in production? How does it compare in stability to the version 4.9.4 LTS? Have you come across any pitfalls?

**Comment by lollipopjin** [comment]
Hi，Stevenzall.  RocketMQ 5.0 with proxy mod has been put into production in Alibaba Cloud since mid-August 2022，and it now serving more and more users.
