### ISSUE TITLE
The consumer's subscription not latest?

### ISSUE THREAD

**Issue by jiangxinlingdu** [apache/rocketmq#588]
**BUG REPORT**

1. Please describe the issue you observed:
![image](https://user-images.githubusercontent.com/6373972/49638408-077a2b80-fa43-11e8-9bde-75f99eeff94c.png)
in my dev environment  happen org.apache.rocketmq.client.exception.MQBrokerException: CODE: 25  DESC: the consumer's subscription not latest  

in rocketmq 4.3.2  have also been happen 

- What did you do (The steps to reproduce)?
consumer restart node   or add consumer node  or remove consumer node 

- What did you expect to see?
log not this :org.apache.rocketmq.client.exception.MQBrokerException: CODE: 25  DESC: the consumer's subscription not latest

- What did you see instead?

![image](https://user-images.githubusercontent.com/6373972/49638408-077a2b80-fa43-11e8-9bde-75f99eeff94c.png)

2. Please tell us about your environment:

rocketmq4.1   and rocketmq4.3.2

**Comment by duhenglucky** [comment]
@jiangxinlingdu this will not cause any more fault, but those logs indeed will confuse users, and we will review your PR ASAP.

**Comment by 971287765zy** [comment]
1
