### ISSUE TITLE
Wrong variable name In MessageStoreConfig.class

### ISSUE THREAD

**Issue by lihao7264** [apache/rocketmq#5882]
version:4.9.4/5.0/other version
wrong variableName:destroyMapedFileIntervalForcibly
It should not be called destroyMapedFileIntervalForcibly, but  destroyMappedFileIntervalForcibly.
![image](https://user-images.githubusercontent.com/39001289/212457968-2fca03c6-f12e-4d96-a8ca-d3a234d9e94a.png)

**Comment by mxsm** [comment]
@lihao7264  Good catch! Welcome to contribute. you can submit a PR to fixed it

**Comment by mxsm** [comment]
@lihao7264  #5919  This PR has fixed it
