### ISSUE TITLE
testPutMessagePositionInfo_buildCQRepeatedly method run error

### ISSUE THREAD

**Issue by shy-share** [apache/rocketmq#5890]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:
![image](https://user-images.githubusercontent.com/50973219/212631687-e9ef46f3-f957-49bd-a704-12ea32741490.png)

- What did you do (The steps to reproduce)?
 run directly
- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ShadowySpirits** [comment]
In my test, the error you describe is caused by the introduction of the following dependency:

```xml
<!-- store/pom.xml -->
<!-- Required by DLedger -->
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <scope>test</scope>
</dependency>
```

And shaded log dependency `rocketmq-logback-classic` woks well.

<img width="2408" alt="image" src="https://user-images.githubusercontent.com/32436597/212801047-2ed55d3a-33b6-43e5-8301-d1bafa2d5fbc.png">

**Comment by ShadowySpirits** [comment]
IMO, deleting `slf4j-api` is more reasonable.

**Comment by shy-share** [comment]
> IMO, deleting `slf4j-api` is more reasonable.

11:20:45,597 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.3.4-rocketmq
11:20:45,611 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.LoggerContext[default] - Found resource [rmq.logback-test.xml] at [file:/D:/java/rocketmq/store/target/test-classes/rmq.logback-test.xml]
11:20:45,773 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE]
11:20:45,773 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender]
11:20:45,831 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:20:45,831 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:20:45,831 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:20:45,831 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.rocketmq] to ERROR
11:20:45,832 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [org.apache.rocketmq] to false
11:20:45,832 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[org.apache.rocketmq]
11:20:45,832 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to ERROR
11:20:45,832 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[ROOT]
11:20:45,832 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.DefaultProcessor@646007f4 - End of configuration.
11:20:45,833 |-INFO in org.apache.rocketmq.common.logging.JoranConfiguratorExt@481a15ff - Registering current configuration as safe fallback point

does not appear to be the result of normal operation

**Comment by ShadowySpirits** [comment]
There is indeed a problem if we delete `sl4j-api`. And this problem not only happened in the test but also happened in the production environment.

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/32436597/212804583-c584bbbc-4c5b-4004-a493-abbce3bfcfe9.png">

We should discuss this in dledeger community to change `sl4j-api` to `rocketmq-logback-classic`.

cc @aaron-ai

**Comment by aaron-ai** [comment]
@shy-share I will fix it.

We will add a bridge to take over the logging of SLF4j by the shaded SLF4j, then `slf4j-api` could be easily introduced.

**Comment by mxsm** [comment]
> IMO, deleting `slf4j-api` is more reasonable.

DLedger needs  `slf4j-api`, should fix it in DLedger project
