### ISSUE TITLE
有没有最新的RocketMQ开发指南？

### ISSUE THREAD

**Issue by ylh23y** [apache/rocketmq#592]
有没有最新的RocketMQ开发指南，如果有在那里找到？

**Comment by wlliqipeng** [comment]
RocketMQ Developer's Guide will be released this month. Please pay attention to RocketMQ's official website.

**Comment by vongosling** [comment]
@ylh23y Please do not open the issue to request some problem. If you have any question, please send to our user [email list](http://rocketmq.apache.org/about/contact/). (Notice: subscribe it before send)

**Comment by ylh23y** [comment]
谢谢
