### ISSUE TITLE
[RIP-57] Add example tiered storage backend service provider

### ISSUE THREAD

**Issue by ShadowySpirits** [apache/rocketmq#5923]
link to #5754 

As stated in the title, this issue aims to add a POSIX provider for tiered storage. It transfers message data from the default store directory to the mount point of storage medium for tiered storage. This provider is fully functional but for demonstration purposes only.

**Comment by lizhimins** [comment]
There is a widely use of filePath in the rocketmq project. The rename operation which not only brings compatibility issues but also conflicts with the naming style of the rocketmq project. It is recommended to revert this change.
