### ISSUE TITLE
The getSyncStateSet command can display whether the replica is online

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq#5936]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

The getSyncStateSet command can display whether the replica is online

![image](https://user-images.githubusercontent.com/21963954/215239006-2749721b-2861-4b80-9dcf-9cc96747f8b8.png)

**Comment by lilongfeisama** [comment]
if a broker offline，this command even won't show it。
Do you mean that  record the info of the offline broker?

**Comment by mahaitao617** [comment]
pls assign to me,thanks

**Comment by mahaitao617** [comment]
#5958

**Comment by mahaitao617** [comment]
#5958
