### ISSUE TITLE
Does rocket support multi-replica? 

### ISSUE THREAD

**Issue by hepyu** [apache/rocketmq#594]
Does rocket support multi-replica? like kafka. 

If supported, Is there some doc to introduce this feature? I didn't find anything in github and apache-rocket official website.

**Comment by dongeforever** [comment]
@hepyu Currently，you could use the master-slave architecture, which may need to change broker role manually, and a raft-based commitlog will come in the near future.

**Comment by hepyu** [comment]
3Q~
