### ISSUE TITLE
Exceptions Occurred when the transientStorePoolEnable=true parameter was added to controller mode broker configuration

### ISSUE THREAD

**Issue by liuxin638507** [apache/rocketmq#5960]
broker-n0.conf and broker-n0.conf 添加transientStorePoolEnable=true参数发送消息异常
![image](https://user-images.githubusercontent.com/32058132/215925125-8daf783c-20ed-45ef-9920-ad51a8cc28b4.png)

export NAMESRV_ADDR=localhost:9876
sh bin/tools.sh org.apache.rocketmq.example.quickstart.Producer
![image](https://user-images.githubusercontent.com/32058132/215925260-61e67a5e-0565-4026-954d-18db584e7deb.png)

**Comment by RongtongJin** [comment]
Hi @liuxin638507, this issue has been fixed in #5722. You can try it with the latest develop branch.
