### ISSUE TITLE
Is there DeleteUnusedStats duplicate?

### ISSUE THREAD

**Issue by zhiliatom** [apache/rocketmq#5969]
When invoke DELETE_TOPIC, I found there do deleteUnusedStats twice, one occurs on  `deleteTopics(Sets.newHashSet(requestHeader.getTopic()))`, so I wonder is that intentional or a bug
![image](https://user-images.githubusercontent.com/87265072/216351942-36fb15f9-278f-48fd-8c6f-a2d7c42f1207.png)

**Comment by ShadowySpirits** [comment]
It is indeed a duplicate. @lizhimins PTAL

**Comment by lizhimins** [comment]
It seems duplicated, can you help fix this problem with a pr.

**Comment by zhiliatom** [comment]
> It seems duplicated, can you help fix this problem with a pr.

of course
