### ISSUE TITLE
Remove more system topic for getUserTopicConfig api.

### ISSUE THREAD

**Issue by dingshuangxi888** [apache/rocketmq#5975]
There is more system topic in rocketmq system. 

1. topic of broker's hostname.
2. topic name start with rmq_sys_

The api getUserTopicConfig is not remove all of these topics.

**Comment by drpmma** [comment]
Good catch. Do you have the willing to submit a pr to fix this?

**Comment by socutes** [comment]
@drpmma Can the task be assigned to me?
