### ISSUE TITLE
[DISSCUSS] Use github disscussion to ask and answer questions

### ISSUE THREAD

**Issue by ShadowySpirits** [apache/rocketmq#5982]
Issue is designed for the bug tracker, not the questions. We should migrate question discussion to a specific place. [GitHub discussion](https://docs.github.com/en/discussions) is a collaborative communication forum for the community. It's a better place for communication and announcement. See [Homebrew](https://github.com/Homebrew/discussions/discussions) for example.

cc @RongtongJin @aaron-ai @lollipopjin @zhouxinyu @lizhanhui

**Comment by aaron-ai** [comment]
@ShadowySpirits Nice proposal! 

I created a jira ticket to track this issue: https://issues.apache.org/jira/browse/INFRA-24021.

**Comment by aaron-ai** [comment]
GitHub discuss has been enabled.

**Comment by ShadowySpirits** [comment]
> GitHub disscussion has been enabled.

How about adding a pined issue to announce this and guide users to ask questions in GitHub discussion?

**Comment by aaron-ai** [comment]
> > GitHub disscussion has been enabled.
> 
> How about adding a pined issue to announce this and guide users to ask questions in GitHub discussion?

Good idea!
