### ISSUE TITLE
Is there any changlog I can see?

### ISSUE THREAD

**Issue by litttlefisher** [apache/rocketmq#599]
When I want to upgrade，many people will ask me why. If there do not have enough reason, I cannot persuade people in my company. 
I need some new feature or big bug fix.
Otherwise we use the version which is before incubate.
I want to upgrade to the new version and use the version of springboot.

**Comment by aCoder2013** [comment]
maybe this can help
https://rocketmq.apache.org/dowloading/releases/

**Comment by litttlefisher** [comment]
Thank you.
