### ISSUE TITLE
mqbroker: 48: [[: not found 

### ISSUE THREAD

**Issue by bjsiyong** [apache/rocketmq#6006]
从 https://rocketmq.apache.org/download 上面下载了 5.0.0 的 Binary。   
add 到 linux 后，使用 ./mqbroker 启动broker时出现： mqbroker: 48: [[: not found 的提示语。     
检查了一下 mqbroker  源代码，发现48行是：  
`while [[ $# -gt 0 ]]; do`    
这种格式的代码与sh不兼容，但是与bash兼容。所以，所以需要把 mqbroker   第一行改为 #!/bin/bash 就可以修复此bug啦。

**Comment by mxsm** [comment]
> 从 https://rocketmq.apache.org/download 上面下载了 5.0.0 的 Binary。 add 到 linux 后，使用 ./mqbroker 启动broker时出现： mqbroker: 48: [[: not found 的提示语。 检查了一下 mqbroker 源代码，发现48行是： `while [[ $# -gt 0 ]]; do` 这种格式的代码与sh不兼容，但是与bash兼容。所以，所以需要把 mqbroker 第一行改为 #!/bin/bash 就可以修复此bug啦。

@bjsiyong 这bug在develop开发分支已经修复！ 如果想体院Rocketmq5的功能，可以用develop分支进行打包！

**Comment by bjsiyong** [comment]
建议把所有shell脚本的第一行都换成bash呀，这个就不会出现很多莫名其妙的问题了！

**Comment by elenacliu** [comment]
在尝试rocketmq 5.0版本的时候遇到了同样的问题。
后果是会导致broker启动时的config出现问题（因为48行之后的条件判断出错了），但broker依然会boot success。然后尝试用mqadmin更新topic的时候就会报错，说cluster name出错了，找了很久才发现是这个问题。
