### ISSUE TITLE
Why use spinlocks by default？

### ISSUE THREAD

**Issue by Cicizz** [apache/rocketmq#601]
Hello.
When I upgrade rocketmq version 3.2.6 to 4.31,I found some configuration defaults changed
`useReentrantLockWhenPutMessage=false`
`sendMessageThreadPoolNums=1`
`sendThreadPoolQueueCapacity=10000`
but when I was doing a send message performance test,I found the TPS is very low and cpu is high.so I changed the configuration:
`useReentrantLockWhenPutMessage=true`
`sendMessageThreadPoolNums=32`
`sendThreadPoolQueueCapacity=100000`
I wonder why use this default configuration?

** The machine configuration **
8cpu and 16g memory and 300g disk

**Comment by jayixl** [comment]
agree that enable 'useReentrantLockWhenPutMessage' and change sendMessageThreadPoolNums to "16 + 4 * core" will highly improve the throughput. And we found many "CODE: 2 DESC: [TIMEOUT_CLEAN_QUEUE]" exceptions using default configuration.

**Comment by duhenglucky** [comment]
@Cicizz use spinlock can reduce context switch as you mentioned and can use fewer threads to obtain a relatively high throughput. but the issue only used to bug report or feature request,  so if you have similar questions in the later, please send to our user [mailing list](http://rocketmq.apache.org/about/contact/). (Notice: subscribe it before send)
