### ISSUE TITLE
rocketmq的tcp/ip协议和http协议有什么区别

### ISSUE THREAD

**Issue by ttr5966** [apache/rocketmq#6014]
rocketmq的阿里云版本，腾讯版本都有区分tcp和http协议，但是tcp协议是应用层，http协议是传输层，这两种有什么区别呢，是http协议可以根据ip地址发送消息，而tcp/ip只是服务器内部的区别吗

**Comment by ShadowySpirits** [comment]
tcp 指的是 RocketMQ 的 Remoting 协议

http 指的是基于 pop 消费模式实现的无状态协议，对应 5.0 新推出的 grpc client + proxy，参见 [RIP-39](https://shimo.im/docs/gXqmeEPYgdUw5bqo)

**Comment by ttr5966** [comment]
好的，多谢，我自己去看一下
