### ISSUE TITLE
MQAdminExt#deleteSubscriptionGroup only delete consumer

### ISSUE THREAD

**Issue by XTUxiongda** [apache/rocketmq#6016]
MQAdminExt#deleteSubscriptionGroup method can only delete consumer,  but the corresponding subscription relationship and consumption progress are not cleared.

eg：
i invoke MQAdminExt#deleteSubscriptionGroup method，I really can't find it on the consumer page of dashboard
But when I query the consumption progress of the consumer group on the topic page, the consumer group is still
![image](https://user-images.githubusercontent.com/38322373/217515981-9e9322d3-6a78-4ec2-8766-c7b02114afeb.png)

Is there any way I can clean up this subscription relationship and consumption progress? I didn't find the corresponding API in mqAdmin

I can't understand why to delete consumerGroup manually. The consumption progress of this consumer group will continue to be maintained instead of associated deletion

**Comment by Oliverwqcwrw** [comment]
Try this
`void deleteSubscriptionGroup(final String addr, String groupName,
        boolean removeOffset) throws RemotingException, MQBrokerException,
        InterruptedException, MQClientException;`

**Comment by XTUxiongda** [comment]
> Try this `void deleteSubscriptionGroup(final String addr, String groupName, boolean removeOffset) throws RemotingException, MQBrokerException, InterruptedException, MQClientException;`

deleteSubscriptionGroup(brokerAddr, groupName, true);
i use the method in org.apache.rocketmq.client.impl.MQClientAPIImpl

before i invoke,the status  is
![image](https://user-images.githubusercontent.com/38322373/217693031-ba57c25b-e5ec-4ac8-bc3c-d0e2271b4dc4.png)
![image](https://user-images.githubusercontent.com/38322373/217693102-b418829c-46ac-47a9-a9c5-564e2e0fc746.png)
It can be found on the consumer page, and the corresponding consumption progress also exists

after i invoke, the status is
![image](https://user-images.githubusercontent.com/38322373/217693410-098e3e2c-a172-434b-b5b3-85b8bea51df6.png)
![image](https://user-images.githubusercontent.com/38322373/217693492-041b3129-e090-43c9-b167-e28b6deb3f54.png)
I can't find it on the consumer page, but the corresponding consumption progress still exists

**Comment by ShadowySpirits** [comment]
@XTUxiongda Please check your Broker version. This feature is released in 4.9.0, see [this commit](https://github.com/apache/rocketmq/commit/46459426801d582b5ef71c8a3e38267ccd6caad9).
