### ISSUE TITLE
Is the develop part the latest development branch, why is it so different from release-5.0.0?

### ISSUE THREAD

**Issue by weihubeats** [apache/rocketmq#6017]
Is the develop part the latest development branch, why is it so different from release-5.0.0?

**Comment by drpmma** [comment]
Release-5.0.1 is prepared to release.

**Comment by Stevenzall** [comment]
> Our community is active and it's been a while since release-5.0.0 is released, and release-5.0.1 is prepared to release.

Really, this month?

**Comment by ShadowySpirits** [comment]
> > Our community is active and it's been a while since release-5.0.0 is released, and release-5.0.1 is prepared to release.
> 
> Really, this month? @drpmma

The proposal for releasing Apache RocketMQ 5.0.1 is now discussed in the mailing list. Please subscribe to the mailing list to see detail and participate in voting.
