### ISSUE TITLE
4.7.0 & 4.9.4 tps no change

### ISSUE THREAD

**Issue by sqtce** [apache/rocketmq#6025]
aliyun Machine configuration:32c，128G，1T(ssd)，4master，4.7.0 & 4.9.4 The pressed tps stabilized at about 10w

broker-a.properties
maxMessageSize=65536
flushCommitLogLeastPages=4
flushConsumeQueueLeastPages=2
flushCommitLogThoroughInterval=10000
flushConsumeQueueThoroughInterval=60000
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
checkTransactionMessageEnable=false
maxTransferCountOnMessageInMemory=1000
transientStorePoolEnable=true
warmMapedFileEnable=false
pullMessageThreadPoolNums=128
slaveReadEnable=true
transferMsgByHeap=true
waitTimeMillsInSendQueue=1000
serverSelectorThreads=16
serverWorkerThreads=32

System parameters also refer to: bin/os.sh  The file is optimized

**Comment by guyinyou** [comment]
Whether the disk usage and network usage have reached the bottleneck？

**Comment by sqtce** [comment]
> Whether the disk usage and network usage have reached the bottleneck？

IO: written_bytes_total max:41.60 MB/s

Network：transmit_bytes_total：max: 938.04 Mb/s

Maximum network bandwidth of the machine: 6G

**Comment by guyinyou** [comment]
> 

6Gb/s or 6Gbps?

**Comment by sqtce** [comment]
> 6Gb/s or 6Gbps?
6 Gbps

**Comment by guyinyou** [comment]
That should be the bottleneck of the network, 6Gbps is about 900Mb/s

**Comment by sqtce** [comment]
> 

upload  max: 938.04 Mb/s
download max:491.74Mb/s
