### ISSUE TITLE
nameserver startup script is not compatible with MacOS

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#6026]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/19537356/218042774-9859baef-b1cd-41dd-afb7-b714d43ca286.png">

**Comment by francisoliverlee** [comment]
当前的dev分支我尝试了下， 报错如下：
![image](https://user-images.githubusercontent.com/5908412/218365013-f1373381-8a53-47e5-b585-7a165487ed1d.png)

原因是JAVA_HOME路径中有空格，导致执行java -jar的时候java二进制找不到
![image](https://user-images.githubusercontent.com/5908412/218365113-4a130154-e9e9-4ec1-a719-e27f5caa4b6a.png)

处理办法：在安装java的时候， 不要全部路径中不要包含空格，特别是mac和windows。
比如：
![image](https://user-images.githubusercontent.com/5908412/218365346-b0d37997-4f2a-4d8e-a9d9-afc74acea391.png)

**Comment by Oliverwqcwrw** [comment]
> 你的这种报错namesrv代码是什么版本， java是什么版本呢？以下是我用最新的dev分支尝试的问题。
> 
> 我使用的namesrv版本：当前dev分支 java：
> 
> ```
> java version "1.8.0_202"
> Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
> Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
> ```
> 
> ## 当前的dev分支我尝试了下， 报错如下：
> ![image](https://user-images.githubusercontent.com/5908412/218365013-f1373381-8a53-47e5-b585-7a165487ed1d.png)
> 
> ## 原因是JAVA_HOME路径中有空格，导致执行java -jar的时候java二进制找不到
> ![image](https://user-images.githubusercontent.com/5908412/218365113-4a130154-e9e9-4ec1-a719-e27f5caa4b6a.png)
> 
> ## 处理办法：在安装java的时候， 不要全部路径中不要包含空格，特别是mac和windows。
> 比如使用这种路径是ok的： ![image](https://user-images.githubusercontent.com/5908412/218365346-b0d37997-4f2a-4d8e-a9d9-afc74acea391.png)

I meet the same problem,

I have noticed that the find_java_home function is currently fetching the system directory's java. When I customize the JAVA_HOME environment variable, I am still fetching the system java directory. I think the user-defined directory should have a higher priority
