### ISSUE TITLE
 Ordered Message Document Picture Error ?

### ISSUE THREAD

**Issue by BlackChen277** [apache/rocketmq#6027]
[Order Message](https://rocketmq.apache.org/docs/featureBehavior/03fifomessage/)

![image](https://user-images.githubusercontent.com/5126487/218057083-42ac32cd-d428-4776-b5ad-b4b5ec911f65.png)

Maybe it should be here Log3<-Log2<-Log1 ,right?

**Comment by mxsm** [comment]
Hi @BlackChen277  official website has submitted pr to fix it. apache/rocketmq-site#399. @RongtongJin  can you merge this pr

**Comment by RongtongJin** [comment]
> Hi @BlackChen277 official website has submitted pr to fix it. [apache/rocketmq-site#399](https://github.com/apache/rocketmq-site/pull/399). @RongtongJin can you merge this pr

Done
