### ISSUE TITLE
Tiered storage on slave

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#6071]
Hi, teams!
Currently the we have only local file tiered storage implementation, if we implement OSS/S3 tiered storage, the master and slave write to the same file on OSS/S3, I think only master should write to OSS/S3, Is there any design about this?

**Comment by ShadowySpirits** [comment]
Tiered storage should be only enabled in the master. But the compatibility of tiered storage and HA needs more discussion, such as tiered storage should not upload data beyond the confirmed offset and how to quickly enable tiered storage when the slave broker promotes to master.

**Comment by RongtongJin** [comment]
> Tiered storage should be only enabled in the master. But the compatibility of tiered storage and HA needs more discussion, such as tiered storage should not upload data beyond the confirmed offset and how to quickly enable tiered storage when the slave broker promotes to master.


I think this can be considered. The new version of HA has the concept of confirm offset. In addition, we can complete enable tiered storage during role switching, just as we handle timing messages.
