### ISSUE TITLE
Does the docker image of Rocketmq 5.0 not publish to hub.docker.com

### ISSUE THREAD

**Issue by john1337** [apache/rocketmq#6076]
请问rocketmq:5.0版本的docker镜像没发布到hub.docker.com吗

**Comment by mxsm** [comment]
@john1337  现在暂时没有发布5.0的版本镜像到Docker Hub, 如果需要5.0的镜像可以自行打包镜像。可以参照https://github.com/apache/rocketmq-docker 这个项目的打包对打包的Dockerfile进行修改。
