### ISSUE TITLE
Optimize the timer implementation in Remoting

### ISSUE THREAD

**Issue by socutes** [apache/rocketmq#6105]
Timer is a common and effective tool for timing tasks. java provides several Timer tools, such as java.util.Timer and ScheduledThreadPoolExecutor.but these tools are flawed in execution efficiency.
In the scenario of high concurrency and high traffic flow processing. some subtle performance differences, often have the effect of amplification, resulting in serious performance degradation.
Therefore, you are advised to replace scheduled task scheduling [java.util.Timer](https://github.com/apache/rocketmq/issues/java.util.Timer) with [io.netty.util.HashedWheelTimer](https://github.com/apache/rocketmq/issues/io.netty.util.HashedWheelTimer) in Remoting.
In addition, a piece of code that has been commented out is deleted

**Comment by zhouxinyu** [comment]
Good catch. I assigned this issue to you, feel free to cancel it if you are not available for this issue.
