### ISSUE TITLE
Unexpected back-check of transaction message in RocketMQ 5.0

### ISSUE THREAD

**Issue by mz0113** [apache/rocketmq#6107]
<img width="1675" alt="d0489fe9cfc93f6e723c59c0db726979" src="https://user-images.githubusercontent.com/42512469/219828524-1b396602-4549-4b15-8625-b61aa81663b4.png">

问题描述：
    1.发送端发送事务消息后，等待broker发起回查 ， 然后broker于1分钟左右正常发起回查，应用给与事务已提交的响应，broker也收到了这个响应，见上图。但是broker依然发起下一次回查 ， 最终查了15次后消息被回滚掉了。但是看下来不是必现，概率大概10%左右会失败。一部分消息是回查了七八次以后成功了，有的查了15次失败了。问题发生有一天内多次发生。
    2. 目前mq用的是开源版本，容器化部署，一主一从 。使用cotroller模式进行主从切换。 主从异步刷盘同步复制。但是看了服务器日志，主从切换未发生过，服务运行一直都正常。

最新进展：
   3. 目前确认是启用堆外缓存导致的问题，关掉就正常了。好奇堆外缓存看代码是间隔200ms就会提交一次到fileChannel，怎么还会有这个问题呢。。

**Comment by RongtongJin** [comment]
#5722 修复了controller模式下与开启堆外内存不兼容的问题，建议后续升级到5.1.0版本。但从你的描述上来看，事务消息的回查似乎与该修复无关。

**Comment by fuyou001** [comment]
@Focus-rth

**Comment by Focus-rth** [comment]
1. 尝试一段时间未复现，可以给下完整的transaction.log?
