### ISSUE TITLE
RocketMQ causes the timezone issue of JsonFormat

### ISSUE THREAD

**Issue by xuchenchen** [apache/rocketmq#6114]
项目中引入rocketmq后导致，原有jackson的JsonFormat注解timezone时区出现问题，导致插入数据库的时间总是多8小时,我移除rocketmq的maven依赖后就可以正常使用JsonFormat转换时间也正常了，请问rocketmq这块有对jackson的默认参数做改动吗？
：
<dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>jackson-core</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jackson-databind</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>jackson-core</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by RongtongJin** [comment]
> 项目中引入rocketmq后导致，原有jackson的JsonFormat注解timezone时区出现问题，导致插入数据库的时间总是多8小时,我移除rocketmq的maven依赖后就可以正常使用JsonFormat转换时间也正常了，请问rocketmq这块有对jackson的默认参数做改动吗？ ： org.apache.rocketmq rocketmq-spring-boot-starter jackson-core com.fasterxml.jackson.core jackson-databind com.fasterxml.jackson.core org.apache.rocketmq rocketmq-spring-boot jackson-core com.fasterxml.jackson.core com.fasterxml.jackson.core jackson-databind

没有特殊改动，请问你用的是rocketmq-spring哪一个版本？

**Comment by xuchenchen** [comment]
版本是<version>2.0.4</version>，发现与jackson-databind相关的目前都受到 影响，以前都正常的(我反复试了下去掉rocketmq的maven依赖测出的结果是 只要是去掉rocketmq依赖就正常，引入后就会导致jackson-databind序列化的问题)，框架本身是从ruoyi版本改造来的。

**Comment by xiaoyifang** [comment]
最好来个可以重现的，最小化例子。  比如 一个main方法，里面json序列化。

**Comment by RongtongJin** [comment]
> 版本是2.0.4，发现与jackson-databind相关的目前都受到 影响，以前都正常的(我反复试了下去掉rocketmq的maven依赖测出的结果是 只要是去掉rocketmq依赖就正常，引入后就会导致jackson-databind序列化的问题)，框架本身是从ruoyi版本改造来的。

可以尝试一下更新到最新版本，我没记错的话后面的版本修过一些jackson序列化的问题
