### ISSUE TITLE
Fix flaky test in tiered storage

### ISSUE THREAD

**Issue by ShadowySpirits** [apache/rocketmq#6123]
I have implemented a mock FileSegment called MemoryFileSegment for testing purposes. However, in some unit cases, it needs to disable the file size check. Currently, there is a static variable checkSize that controls this logic, which can lead to unexpected behavior when testing concurrently.

**Comment by francisoliverlee** [comment]
可以讲解下什么情况下会导致 “ unexpected behavior”嘛？

**Comment by ShadowySpirits** [comment]
我们的 CI 会并行执行单元测试，所以用静态变量控制是否检查文件大小会有并发问题
