### ISSUE TITLE
How to shutdown consumer when it once receive msg.

### ISSUE THREAD

**Issue by xgj1988** [apache/rocketmq#613]
How to shutdown consumer when it once receive msg.

**Comment by duhenglucky** [comment]
@xgj1988 you can shut down the consumer by invoking the shutdown() method in another thread. and if you have similar questions in the later, please send to our user [mailing list](http://rocketmq.apache.org/about/contact/). (Notice: subscribe it before send)

**Comment by chenglongzjg** [comment]
> @xgj1988 you can shut down the consumer by invoking the shutdown() method in another thread. and if you have similar questions in the later, please send to our user [mailing list](http://rocketmq.apache.org/about/contact/). (Notice: subscribe it before send)

why another thread ?
