### ISSUE TITLE
Is there some stats for producer like ConsumerRunningInfo for consumer?

### ISSUE THREAD

**Issue by hepyu** [apache/rocketmq#616]
RT.

I found the stats for consumer, but no stats for producer, does it exist?

**Comment by hepyu** [comment]
If I want to stats for producer like consumerRunningInfo, is there some interface to impl it ?

**Comment by Cicizz** [comment]
@hepyu  
This project can help you to manage rocketmq:
https://github.com/sohutv/sohu-tv-mq

**Comment by hepyu** [comment]
> @hepyu
> This project can help you to manage rocketmq:
> https://github.com/sohutv/sohu-tv-mq

I mean if exist code level to print producer stats in the producer client, like class ConsumerRunningInfo in the consumer-client.
Is there some one?
