### ISSUE TITLE
request-reply return sended message

### ISSUE THREAD

**Issue by 1024cainiao** [apache/rocketmq#6166]
env:
rocketmq-client:4.9.4

question:
use org.apache.rocketmq.client.producer.DefaultMQProducer#request(org.apache.rocketmq.common.message.Message, long)
Unable to receive the message returned by the consumer, And received a message from producer.
Find by the source code, 
![image](https://user-images.githubusercontent.com/40590277/220815861-2b9d49c2-cfc9-405c-8a04-d127a3b92af3.png)
The code in the red box is wrong.

Request overloaded method in the same class, Only the following are available.
org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl#request(org.apache.rocketmq.common.message.Message, org.apache.rocketmq.client.producer.MessageQueueSelector, java.lang.Object, org.apache.rocketmq.client.producer.RequestCallback, long)
![image](https://user-images.githubusercontent.com/40590277/220816602-165bc72c-ef5b-4473-bbe3-253168683c37.png)

**Comment by Oliverwqcwrw** [comment]
Hello @1024cainiao ,
 PR #4896  fixed this issue
