### ISSUE TITLE
CONSUME_FROM_LAST_OFFSE and CONSUME_FROM_TIMESTAMP doesn't work 

### ISSUE THREAD

**Issue by flackyang** [apache/rocketmq#617]
The issue tracker is **ONLY** used for bug report and feature request. Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
使用一个新的消费组消费指定topic中的消息，不需要历史信息，指定CONSUME_FROM_LAST_OFFSE或者CONSUME_FROM_TIMESTAMP

- What did you expect to see?
从最新的offset开始消费或者从指定的时间点开始消费

- What did you see instead?
消费了全部的历史消息

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by scarletyoung** [comment]
Have the same problem.
A new consumer group will request offset from broker(MessageMode is CLUSTERING), and if the first record of the topic is in commitlog file, then the broker will return 0 and consumer will consume from the start.

**Comment by ToDoBest** [comment]
Have the same problem.
consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_LAST_OFFSET);
I don't want to receive the history message, but I receive all

**Comment by fantasygg** [comment]
Have the same problem.

**Comment by francisoliverlee** [comment]
@flackyang @scarletyoung @kevinwang0224 
consumer rule : consumers always want latest messages more than old ones.

check how many messages in your topic's queues. found there's a trick, RocketMQ thinks if there're not manay messages, you would get all messages. even if you set CONSUME_FROM_LAST_OFFSE

**Comment by yidaimi** [comment]
Is the issue fixed? or have any work arround solution? I have the same problem in 4.7.0
