### ISSUE TITLE
5.1.0 Dledger和controller疑问

### ISSUE THREAD

**Issue by Hoxxx** [apache/rocketmq#6170]
看文档看得有点晕，这两个组件做的事是相同的？
三节点，想做一个高可用、异步复制的mq集群，是不是用Dledger就够了？

**Comment by aaron-ai** [comment]
Let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see [Q&A Guidelines](https://github.com/apache/rocketmq/issues/6153).
