### ISSUE TITLE
slave brokerActive false and slave does not seem to synchronize the master commitlog

### ISSUE THREAD

**Issue by weihubeats** [apache/rocketmq#6177]
**BUG REPORT**

1. Please describe the issue you observed:
- rocketmq verison: rocketmq 5.0
Through the official script deployed a master and a slave, the dashboard can see two brokers, but the slave node broker brokerActive is false, the slave does not seem to synchronize the master commitlog, what is the reason for this?
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/42484192/221342076-8fae6b7d-eb2d-4d18-99e8-1dae51483bdf.png">
<img width="911" alt="image" src="https://user-images.githubusercontent.com/42484192/221342085-2b7adb25-235c-4f86-a8d9-449c977b9030.png">

- What did you do (The steps to reproduce)?
slave brokerActive is true and synchronize the master commitlog

**Comment by RongtongJin** [comment]
Hi @weihubeats It is normal for brokerActive to be false. You can see ~/logs/rocketmqlogs/store.log why the slave is not synchronized. In addition, plz ask questions in Github Discussion, see https://github.com/apache/rocketmq/issues/6153.
