### ISSUE TITLE
It does not take effect when acl is enabled in the proxy 

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#6185]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

<img width="809" alt="image" src="https://user-images.githubusercontent.com/31796988/221388532-37f6bb67-2f2c-48c1-8201-838eb3cdf6d0.png">

It has no spi file

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by drpmma** [comment]
It appears that the commit 1116de4f93f965d68463b0477fede8df7dda011b (ISSUE #5295) changed the behavior of the ServiceProvider in a way that caused this issue.

**Comment by drpmma** [comment]
It is possible that the commit could have caused the merging issue, and the service loader in proxy acl is not taken into consieration.

**Comment by Oliverwqcwrw** [comment]
> It appears that the commit [1116de4](https://github.com/apache/rocketmq/commit/1116de4f93f965d68463b0477fede8df7dda011b) (ISSUE #5295) changed the behavior of the ServiceProvider in a way that caused this issue.

It seems to have this problem all the time.
