### ISSUE TITLE
When deleting accessKey, can you add the function of clearing all accessKeys

### ISSUE THREAD

**Issue by onejimmyboy** [apache/rocketmq#6200]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) or [github discussions](https://github.com/apache/rocketmq/discussions) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
    At present, the ACL function only supports a single accesskey when deleting accesskeys,

2. Provide any additional detail on your proposed use case for this feature.
   featuresupporting ACL function

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
   Add the case where the accesskey field is "*". When the accesskey is "*", it means that the current user needs all the accesskeys.
   You need to modify deleteAccessConfig to judge the accessKey value. If it is "*", clear the accessKeyTable, give accounts null, and 
    update the yml file. like this:
![image](https://user-images.githubusercontent.com/57432151/221545030-d1b6f64e-b04b-47c1-b92f-cc32764d8cf1.png)

5. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by wps12345** [comment]
At the same time, modify the prompt information in the command

**Comment by Oliverwqcwrw** [comment]
Is it risky to give the user a function to delete all accesskeys?

**Comment by wps12345** [comment]
> Is it risky to give the user a function to delete all accesskeys?

In my opinion, as long as it is deleted, there are risks. Deleting one is the same as clearing all. Let's add a description in help. If you delete it one by one, it will be troublesome.
