### ISSUE TITLE
LitePullConsumer support async pull message

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq#6205]
branch：develop

LitePullConsumer uses org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl#pull to get messages from the server. I found that the CommunicationMode in pullSyncImpl is SYNC. For DefaultPullConsumer, it supports both synchronous and asynchronous pull messages . In DefaultLitePullConsumer#pullThreadNums = 20 for client default configuration, and if the number of partitions/queues assigned to the client is greater than 20 at this time, since the client's long polling has not been returned by the server, it is assumed that the message is sent to a partition without long polling on the broker, and the message will be delayed at this time.

suggest：LitePullConsumer support async pull message, using asynchronous communication to get messages.

The above is what I found after reading the code. Is this the behavior correct?

**Comment by RongtongJin** [comment]
> branch：develop
> 
> LitePullConsumer uses org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl#pull to get messages from the server. I found that the CommunicationMode in pullSyncImpl is SYNC. For DefaultPullConsumer, it supports both synchronous and asynchronous pull messages . In DefaultLitePullConsumer#pullThreadNums = 20 for client default configuration, and if the number of partitions/queues assigned to the client is greater than 20 at this time, since the client's long polling has not been returned by the server, it is assumed that the message is sent to a partition without long polling on the server, and the message will be delayed at this time.
> 
> suggest：LitePullConsumer support async pull message, using asynchronous communication to get messages.
> 
> The above is what I found after reading the code. Is this the behavior correct?

Good catch! Could you subbmit a pull request to fix the issue?

**Comment by lizhimins** [comment]
Does anyone want to try

**Comment by Ceilzcx** [comment]
> Does anyone want to try?

I want to try. but  I don't know if I understood this correctly,  just change the value of input parameter to async for pullKernelImpl method？

**Comment by Abhijeetmishr** [comment]
@lizhimins @RongtongJin Can I work on this ?

**Comment by lizhimins** [comment]
Thanks, we have three impl now. I will review them.
