### ISSUE TITLE
when set autoCreateSubscriptionGroup  false,consumerTable still add the group 

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq#6213]
**BUG REPORT**

1. Please describe the issue you observed:
when set autoCreateSubscriptionGroup be false, maybe users expect that no group relation can be find in broker. but now we can see som infomation like consumerTable, which will  generate some metrics (which not expected)

- What did you do (The steps to reproduce)?

<img width="904" alt="image" src="https://user-images.githubusercontent.com/2684384/222030912-7365796e-6014-4b78-ad68-f3fa7c634ec8.png">

- What is expected to see?

do not put group to consumerTable

- What did you see instead?

even consumerData.getGroupName() does not exist in broker, we still put it to consumerTable

3. Please tell us about your environment:

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

5. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by lizhimins** [comment]
应该是个 bug，注册 consumer 的时候需要判断一下

**Comment by leizhiyuan** [comment]
> 应该是个 bug，注册 consumer 的时候需要判断一下

ok,那我来改一下
