### ISSUE TITLE
Slave node does not work

### ISSUE THREAD

**Issue by xcfuu** [apache/rocketmq#6217]
![image](https://user-images.githubusercontent.com/29519964/222089567-494a9304-8572-4a14-9f23-6711f1d24875.png)

![image](https://user-images.githubusercontent.com/29519964/222089120-bce18bb6-43c8-4812-9d59-00a62a1a8c7e.png)

No error found in the log

**Comment by ShadowySpirits** [comment]
Please ask questions in [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see https://github.com/apache/rocketmq/issues/6153.
