### ISSUE TITLE
ReceiptHandleProcessor message renewal strategy optimization

### ISSUE THREAD

**Issue by socutes** [apache/rocketmq#6232]
ReceiptHandleProcessor messages renew for one minute at a time. It is necessary to optimize the renewal time into a retreat strategy to reduce the number of renewals.
Normally, a message will be ack within a few hundred milliseconds to a few seconds after consumption is complete. If no ack message is received within 1 minute, the client is faulty and cannot ack normally.
At this point, if you follow the fixed renewal for one minute, in extreme cases, if there are a large number of messages that need to be renewed, you will experience performance problems.                           
The current maximum renewal time is determined by the renewMaxTimeMillis configuration item. The default value is 3 hours.
There are two strategies to choose from:  
1.Set a retreat time group. 1min, 3min, 5min, 10min, 30min, 1hour. Maximum 1hour
2.The minimum is 1min, and the accumulation is carried out according to the index of 2 (unit of second). It can take the class ExponentialRetryPolicy

**Comment by mxsm** [comment]
@socutes  give more information about strategy

**Comment by socutes** [comment]
> 

Yes, I'll fill in the details later

**Comment by zhouxinyu** [comment]
Thanks @socutes for your contribution, looking forward to your detailed strategy.

**Comment by xdkxlk** [comment]
> The policy has been updated, please help to confirm the policy
> 
> CC @xdkxlk @drpmma @zhouxinyu

I think strategy one is better.

**Comment by socutes** [comment]
> > The policy has been updated, please help to confirm the policy
> > CC @xdkxlk @drpmma @zhouxinyu
> 
> I think strategy one is better.

ok
