### ISSUE TITLE
Removed the ForwardRequestProcessors class that is not being used

### ISSUE THREAD

**Issue by socutes** [apache/rocketmq#6235]
org.apache.rocketmq.broker.processor.ForwardRequestProcessor in module Broker, does not appear to be used.
Would like to initiate a discussion to see if it can be removed.

Removed the ForwardRequestProcessors class that is not being used

**Comment by socutes** [comment]
CC @Oliverwqcwrw @zhouxinyu

**Comment by Oliverwqcwrw** [comment]
Hello @socutes ,
Let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see https://github.com/apache/rocketmq/issues/6153.

**Comment by socutes** [comment]
> Hello @socutes , Let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see #6153.

After discussion, this class can be removed. I will submit a PR to fix it.

https://github.com/apache/rocketmq/discussions/6274
