### ISSUE TITLE
Compile version: diff version in diff modules

### ISSUE THREAD

**Issue by liukun4515** [apache/rocketmq#625]
In the root pom, we use `1.7` as compile version.
why we use the `1.6` in some module, such as [logging](https://github.com/apache/rocketmq/blob/master/logging/pom.xml)?

**Comment by lemonzone2010** [comment]
Ask this question by using mailing list.
http://rocketmq.apache.org/about/contact/

**Comment by duhenglucky** [comment]
@liukun4515 RocketMQ client runs with the user's code，so In order to ensure that the lower version can be used normally for users' code, it is still 1.6 in the logging.
and @lemonzone2010 comment, Ask this question by using the mailing list. http://rocketmq.apache.org/about/contact/

**Comment by liukun4515** [comment]
thanks!
@lemonzone2010 @duhenglucky
