### ISSUE TITLE
v5.0.0 Pop消费模式下,很多消息显示重试次数达上千次

### ISSUE THREAD

**Issue by mz0113** [apache/rocketmq#6258]
现象: 
consumer.getReconsumeTimes() 返回值几百到几千之间 , 如图 . 正常应该是默认的16次, 但是这个Topic就很奇怪
消费模式为并发消费,POP模式

![image](https://user-images.githubusercontent.com/42512469/223104812-a267289a-6457-4c53-8c1c-e4796a47e724.png)

**Comment by mxsm** [comment]
Hi @mz0113 Let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see https://github.com/apache/rocketmq/issues/6153.
