### ISSUE TITLE
Client dependency conflict, cause NoClassDefFoundError. Require for shaded client

### ISSUE THREAD

**Issue by HScarb** [apache/rocketmq#6264]
I run into an issue identical to https://blog.51cto.com/u_15127641/2875028
In rocketmq_client.log:
```log
java.lang.NoClassDefFoundError:Could not initialize class org.apache.rocketmq.common.message.MessageClientIDSetter
```
And it is caused by package conflict.

---

These issues will appear since Rocketmq clients share the same package with users' service.
It would be better to have a shaded client, which dependencies are in an individual package.

Ref: https://github.com/apache/pulsar/blob/master/pulsar-client-shaded/pom.xml

**Comment by aaron-ai** [comment]
RocketMQ 5.x client provides the shaded jar. which you could refer to [here](https://github.com/apache/rocketmq-clients/tree/master/java).

**Comment by GoodAjman** [comment]
Dependency conflicts
commons-validator
![image](https://github.com/apache/rocketmq/assets/39800460/63de45c0-40a7-4fa5-ab68-e8bda0c9bad4)
