### ISSUE TITLE
Whether any time delay of 5.0.0 can be merged into the 4.9.x branch？

### ISSUE THREAD

**Issue by onejimmyboy** [apache/rocketmq#6275]
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) or [github discussions](https://github.com/apache/rocketmq/discussions) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
The current 5.0 version supports any length of delay, is it considered to be supported in the 4.9.x version? How feasible is it? Is there such a case？
2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ShadowySpirits** [comment]
Let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see #6153.

**Comment by yiduwangkai** [comment]
> Let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see #6153.

Our company has incorporated the precision delay feature into 4.9.4 and has been running in production for over 3 months，I can provide this pr

**Comment by wps12345** [comment]
> > Let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see #6153.
> 
> Our company has incorporated the precision delay feature into 4.9.4 and has been running in production for over 3 months，I can provide this pr
可以留一个邮箱地址吗？咨询咨询

**Comment by wps12345** [comment]
如果在4.9.4版本合入了这个，那用springboot使用的时候，在pom文件中引用的依赖使用4.9.4还是5.0.0？


ヤ艾枫o.--
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 中午12:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] Whether any time delay of 5.0.0 can be merged into the 4.9.x branch？ (Issue #6275)





  
Let's move to GitHub Discussion, see #6153.
  
Our company has incorporated the precision delay feature into 4.9.4 and has been running in production for over 3 months，I can provide this pr

**Comment by yiduwangkai** [comment]
> 如果在4.9.4版本合入了这个，那用springboot使用的时候，在pom文件中引用的依赖使用4.9.4还是5.0.0？ ヤ艾枫o.-- ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/rocketmq" ***@***.***&gt;; 发送时间:&nbsp;2023年3月8日(星期三) 中午12:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apache/rocketmq] Whether any time delay of 5.0.0 can be merged into the 4.9.x branch？ (Issue #6275) Let's move to GitHub Discussion, see #6153. Our company has incorporated the precision delay feature into 4.9.4 and has been running in production for over 3 months，I can provide this pr — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

引入4.9.4和5.0.0都可以，不过5.0的litepull客户端访问旧版broker不可以

**Comment by drpmma** [comment]
Hi @onejimmyboy, we have no plans to merge the accurate delay code from 5.0.
The 4.9.x branch will not introduce new features, only necessary bug fixes will be merged.

RocketMQ 5.0 introduce new features by the new module as proxy and container which means you can use it in the totally same way as RocketMQ 4.9 or any other preceding version.

In other words, RocketMQ 5.0 is just another 4.10 version if you don't need these new modules.
