### ISSUE TITLE
[GSoC] RocketMQ TieredStore Integration with HDFS

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq#6282]
### GSoC
Google Summer of Code is a global, online program focused on bringing new contributors into open source software development. GSoC Contributors work with an open source organization on a 12+ week programming project under the guidance of mentors. https://summerofcode.withgoogle.com/

### Apache RocketMQ and HDFS

-  Apache RocketMQ is a cloud native messaging and streaming platform, making it simple to build event-driven applications. 
-  Hadoop Distributed File System (HDFS) is a distributed file system designed to store and manage large data sets across multiple servers or clusters. HDFS provides a reliable, scalable, and fault-tolerant platform for storing and accessing data that can be accessed by a variety of applications running on the hadoop cluster. 

### Background

High-speed storage media, such as solid-state drives (SSDs), are typically more expensive than traditional hard disk drives (HDDs). To minimize storage costs, the local data disk size of a rocketmq broker is often limited. HDFS can store large amounts of data at a lower cost, it has better support for storing and retrieving data sequentially rather than randomly. In order to preserve message data over a long period or facilitate message export, the RocketMQ project previously introduced a tiered storage plugin. Now it is necessary to implement a storage plugin to save data on hdfs.

### Relevant Skills

- Interest in messging middleware and distributed storage system
- Java development skills
- Having a good understanding of rocketmq and hdfs models

Anyways, the most important relevant skill is motivation and readiness to learn during the project!

### Tasks

- understand the basic concepts and principles in distributed systems
- provide related design documents
- develop one that uses hdfs as the backend storage plugin to store rocketmq message data
- write effective unit test code
- *suggest improvements to the tiered storage interface
- *what ever comes in your mind further ideas are always welcome

### Learning Material

- RocketMQ HomePage (https://rocketmq.apache.org/) **Github**: https://github.com/apache/rocketmq
- RocketMQ Tiered Storage Design (https://github.com/apache/rocketmq/wiki/RIP-57-Tiered-storage-for-RocketMQ)
- HDFS HomePage (https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HdfsUserGuide.html)

### Name and contact information

- Mentor: Zhimin Li, Apache RocketMQ Committer, [[lizhimin@apache.org](mailto:lizhimin@apache.org)](mailto:lizhimin@apache.org)
- Mailing List: [[dev@rocketmq.apache.org](mailto:dev@rocketmq.apache.org)](mailto:dev@rocketmq.apache.org)
- Website: https://rocketmq.apache.org/ and https://hadoop.apache.org/

**Comment by nowinkeyy** [comment]
Is this task newly added? I did not see this task on gsoc. [gsoc-ideas-lisy](https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2023+Ideas+list)

**Comment by lizhimins** [comment]
> Is this task newly added? I did not see this task on gsoc. [gsoc-ideas-list](https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2023+Ideas+list)

You can view this link https://issues.apache.org/jira/browse/COMDEV-506

**Comment by nowinkeyy** [comment]
Can i find this task on gsoc later? I'm interested in it.

**Comment by lizhimins** [comment]
ok, I'll contact you

**Comment by mhdsysy** [comment]
Hi, i would love to do this task if it is still available.
I am a cs Graduate with 3 years of experience and currently doing my masters.

Thanks in advance.

**Comment by khac** [comment]
hi! if is this an open issue, Can I take this? Is the idea here to store rabbitmq messages on hdfs?

**Comment by golden-yang** [comment]
@lizhimins  Hello, I find this issue is closed as completed status. How do I use this feature?
