### ISSUE TITLE
Some questions about RocketMQ Transactional Message

### ISSUE THREAD

**Issue by zhuwt1996** [apache/rocketmq#629]
1.When I use rocketmq transactional message ,I find though I return LocalTransactionState.ROLLBACK_MESSAGE when I excute the LocalTransaction,the consumer will still consume the message sometimes.I wonder why it happened?

2.When I send a message in a Service class,and in the LocalTransaction I save a object to the database,then some exceptions happened  in the Service class,why I cannot successfully do the insert management?
英语水平有限，就是说我在service层发送了一条消息，在执行本地事务的时候我进行了插入操作，service层发送完消息以后出现了异常，这也使得我的插入操作失败，我想知道为什么？

**Comment by duhenglucky** [comment]
@zhuwt1996 第一个问题，有没有相关的日志来说明一下这个问题呢？rollback的消息应该不会再被消费的，你是不是在console的网页上看到的，那个是因为console网页有些问题。第二个问题，你是不是使用了spring的@transaction注解，抛出异常倒是数据库回滚，后续建议使用RocketMQ的[邮件列表](https://rocketmq.apache.org/about/contact/)来反应问题，里面有很多小伙伴回答问题，也有助于我们沉淀下来。

**Comment by zhuwt1996** [comment]
@duhenglucky 你好，感谢回复，请问发送邮件的地址是这个吗：users-subscribe@rocketmq.apache.org我发送完在Archive里面刷新没找到我的邮件。第一个问题我的疑问点在于：当返回rollback_meaage时，是重新执行一次本地事务还是直接将prepare消息删除掉呢？
然后第二个问题，我重新描述一下：
当我在service层（加了@Transactional）发送了一条事务消息，然后service层又有事务相关的操作，我想请问这时候service层的事务与事务消息里面的本地事务是不是同一事务，会不会影响彼此的执行，执行的顺序又是怎样的呢？

**Comment by 3EDCKenneth** [comment]
我也遇到同样问题，事物消息，有时候 生产者返回0和2，消费端也能收到消息
