### ISSUE TITLE
wrong message  body 

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#6327]
The consumer received the wrong message content，cause the parsing to fail。
We observed the message content stored in the broker，Found that the body is not correct. After printing it into a string, it is found that the content is the same as Properties 。
Most of the cases are normal, there may be only 1 message like this in a few days。

broker 4.9.4
client 4.7.0

消息内容不正确导致解析失败，消息发送的是pb类型 。消费者解析pb失败了，然后控制台查询消息内容发现这条消息的格式和其他完全不一样。观察发现好像是把Properties 里面的内容填到body 里面了，里面的内容基本和Properties 一样。
应该不是客户端使用的方式问题，问题好久可能几个月才出现一次，而且boby里面包括了一些skywalking trace 等内容显然不是手动放的

messageBody

"0-VGhyZWFkL29yZy5hcGFjaGUuc2t5d2Fsa2luZy5hcG0udG9vbGtpdC50cmFjZS5SdW5uYWJsZVdyYXBwZXIvcnVu-bXEtbmFtZXNydi5ibHVlaGVsaXg6OTg3NjttcS1uYW1lc3J2LXMuYmx1ZWhlbGl4Ojk4NzY=\\u0002sw8-x\\u00010-1678684524171\\u0002uber-trace-id\\u00010000000000000000edd8eeecefbd3f6b%3A73fcece68e0b3f25%3A0%3A1\\u0002traceparent\\u000100-0000000000000000edd8eeecefbd3f6b-73fcece68e0b3f25-01\\u0002sw8\\u00011-MDAwMDAwMDA"

![image](https://user-images.githubusercontent.com/32947555/224654407-1007e396-ed26-415e-b7be-c40de80b849c.png)

感觉非常奇怪

**Comment by echooymxq** [comment]
跟下skywalking agent的代码，看下是不是skywalking插件的问题？

**Comment by Cczzzz** [comment]
问题是几个月会出现一次，完全不知道从哪查起

**Comment by leizhiyuan** [comment]
看这里你已经有uniqkey了，可以从commitlog中查一下这条消息，是不是现在commitlog就是错的

如果是，那感觉应该是skywalking 可能做了什么增强。可以跟一下skywalking的变更记录。是不是有相关的fix

**Comment by fuyou001** [comment]
MQ是不会对消息内容做任何修改。
你可以通过mqadmin 工具，来查询下这个消息；或直接使用一个新的订阅来消费这个消息，然后对比消息内容是否变更了。
