### ISSUE TITLE
Why can’t i find the class in the src-code presenting to the web  of 'https://rocketmq.apache.org/zh/docs/'(rocketmq5.x), such as `ClientServiceProvider `, `MessageBuilder`.

### ISSUE THREAD

**Issue by kcl-co** [apache/rocketmq#6338]
Why can’t i find the class in the src-code presenting to in the web  of 'https://rocketmq.apache.org/zh/docs/', such as `ClientServiceProvider `, `MessageBuilder`.

**Comment by kcl-co** [comment]
I cant find these class in the branch master and release 5.1.0

**Comment by RongtongJin** [comment]
> Why can’t i find the class in the src-code presenting to in the web of 'https://rocketmq.apache.org/zh/docs/', such as `ClientServiceProvider `, `MessageBuilder`.

The code is in here https://github.com/apache/rocketmq-clients. In additon, it would be better ask questions in [Github discusstion](https://github.com/apache/rocketmq/discussions).

**Comment by kcl-co** [comment]
@RongtongJin OK，Thanks！

**Comment by kcl-co** [comment]
@RongtongJin Can we think that the rocketmq-client module of rocketmq-all will move to the new project rocketmq-client  and the rocketmq-all is only used for rocketmq server after rocketmq5.x?
