### ISSUE TITLE
Local SyncStatSet will not sync to remote value with a same epoch.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#6342]
**BUG REPORT**
When SyncStatSet changes in local, it should be merge to the remote value and then update the epoch.
See the logs below, the local SyncStatSet and the remote have different values with a same epoch.

![image](https://user-images.githubusercontent.com/16487356/224933453-dc9edddf-da97-4e3b-acb3-5e36250590e5.png)

**Comment by ShannonDing** [comment]
Maybe we should use remote values instead of adding local brokerID to SyncStateSet to update the new sync state.

![image](https://user-images.githubusercontent.com/16487356/224936285-24dc6564-0a22-4097-accf-59a506c5a3e9.png)

**Comment by GenerousMan** [comment]
I would like to give it a try, can you assign this issue to me？

**Comment by RongtongJin** [comment]
![image](https://user-images.githubusercontent.com/21963954/224942783-a95028a6-cf14-4de9-8d27-53e6e79bc6b7.png)
注意如果都采用远端的值，这个方法需要优化，shrink这里遍历的是已经存在的连接，但此时备连接还没有连上来，导致备没有shrink。

**Comment by ShannonDing** [comment]
> shrink

Try to shrink the sync state set when it is just started.
