### ISSUE TITLE
consumeQueueExt directory not deleted when deleting topic

### ISSUE THREAD

**Issue by redlsz** [apache/rocketmq#6343]
**BUG REPORT**

1. Please describe the issue you observed:

Set enableConsumeQueueExt to true.
After topic deletion,  the enableConsumeQueueExt file is deleted, but consumeQueueExt directory not.
<img width="677" alt="image" src="https://user-images.githubusercontent.com/103550934/224937230-2de98b12-0d28-40ff-95dc-0a2f75bca520.png">

And the cause is:
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/103550934/224938493-40d78851-733e-46ec-8ae3-468770389d34.png">

**Comment by fuyou001** [comment]
How would you fix it?

**Comment by leizhiyuan** [comment]
maybe. change getStorePathConsumeQueue() to getStorePathConsumeQueueExt()
