### ISSUE TITLE
The cpu100% problem: occurs when the traffic is heavy and the number of Consumerqueues is small.

### ISSUE THREAD

**Issue by azhsmesos** [apache/rocketmq#6350]
There is a problem with the online environment: 
Background of the question: 
- We had two topics online, with 12 partitions in total, and the traffic at that time was about 20w+. According to load balancing, the traffic of a consumerQueue was roughly 2w 
- When peak traffic is reached, our machines in all 12 partitions are experiencing cpu100% 
- After we increased the number of partitions to 120, the cpu usage dropped 
- We suspect that the number of partitions is too small, but analyzing the logic of consumerQueue, we feel that this should be an IO problem, and the cpu usage should not be full 

Question: 
- For this question, I would like to ask if there are any investigation directions in the community. It is not easy to repeat

**Comment by fuyou001** [comment]
what's version you used?

**Comment by fuyou001** [comment]
@azhsmesos 
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by francisoliverlee** [comment]
@azhsmesos  请提供
1. 请压缩后提供，broker.log, broker_default.log, remoting.log, stats.log, store.log. 一般在：~/logs/rocketmqlogs
2. broker配置文件

**Comment by azhsmesos** [comment]
Thanks for the community's answer. Now we have basically found the problem. Thanks!
