### ISSUE TITLE
where define brokerLogDir path with version 5.1.0

### ISSUE THREAD

**Issue by zuoHx580** [apache/rocketmq#6355]
![image](https://user-images.githubusercontent.com/45234194/225279839-7eed1a05-9186-46eb-9c16-8c272bab1702.png)

![image](https://user-images.githubusercontent.com/45234194/225280220-85f0bf56-ad69-4e83-8a42-8a0a7cf44c0e.png)

**Comment by redlsz** [comment]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/103550934/228467684-3f778a27-0d89-4fbd-a9ad-ae6d3ea23055.png">

This property has been set in broker startup, but seems not in proxy. You can add a jvm option -DbrokerLogDir=xxx.
