### ISSUE TITLE
Before executing the executeHook method，consumerGroup field of FilterMessageContext should be assigned. 

### ISSUE THREAD

**Issue by stchenlucas** [apache/rocketmq#6363]
The following code, which is located in PullAPIWrapper may contain a bug

``` java
  if (this.hasHook()) {
                FilterMessageContext filterMessageContext = new FilterMessageContext();
                filterMessageContext.setUnitMode(unitMode);
                filterMessageContext.setMsgList(msgListFilterAgain);
                this.executeHook(filterMessageContext);
            }

```
Before executing the executeHook method，consumerGroup field should be assigned. 
Otherwise, in the subsequent filtering logic, this field will be empty

**Comment by stchenlucas** [comment]
Consider adding filterMessageContext.setConsumerGroup(consumerGroup); 


if (this.hasHook()) {
                FilterMessageContext filterMessageContext = new FilterMessageContext();
                filterMessageContext.setUnitMode(unitMode);
                filterMessageContext.setConsumerGroup(consumerGroup);
                filterMessageContext.setMsgList(msgListFilterAgain);
                this.executeHook(filterMessageContext);
            }

**Comment by ShadowySpirits** [comment]
Agree, seems the field `consumerGroup` and `mq` in `FilterMessageContext` may be used but never assigned. And please notice `FilterMessageContext` is used in both `DefaultMQPushConsumerImpl#processPopResult` and `PullAPIWrapper#processPullResult`.

Will you submit a pr to fix it?
