### ISSUE TITLE
proxy module monitoring indicators are improved

### ISSUE THREAD

**Issue by socutes** [apache/rocketmq#6367]
Current proxy module monitoring indicators are not perfect, need to improve the monitoring indicators for connection, time, thread several dimensions.
After discussion, the development will follow the discussion content.

Discussion address: 
https://github.com/apache/rocketmq/discussions

**Comment by ShadowySpirits** [comment]
Are you interested in contributing more metrics to the proxy? First, we need to implement these metrics mentioned in #5366. And let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see #6153.

**Comment by socutes** [comment]
> Are you interested in contributing more metrics to the proxy? First, we need to implement these metrics mentioned in #5366. And let's move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see #6153.

get

**Comment by Abhijeetmishr** [comment]
@ShadowySpirits @socutes I am interested in this and like to learn more about the issue.
