### ISSUE TITLE
how to config the proxy port 

### ISSUE THREAD

**Issue by bearTao** [apache/rocketmq#6368]
我使用的是crontroller模式部署的nameserver，并使用local的部署方式部署broker和proxy。
我已正常启动crontroller，在A机子broker命令启动：sh /root/rocketmq-all-5.1.0-bin-release/bin/mqproxy -n '192.168.162.22:39876;192.168.162.23:39876;192.168.162.24:39876'   -pc /root/rocketmq-all-5.1.0-bin-release/conf/2m-2s-async-Controller/proxyConfig.json   -bc /root/rocketmq-all-5.1.0-bin-release/conf/2m-2s-async-Controller/broker-a.properties  -pm local 
**但是A机子已经跑起了一个broker+proxy，需要指定proxy端口**。
报错：find an unexpect err.java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:8081
相关配置文件：
```shell 
[root@slave1 ~]# cat  /root/rocketmq-all-5.1.0-bin-release/conf/2m-2s-async-Controller/proxyConfig.json 
{
  "serverSocketPort": 28081
}
[root@slave1 ~]# cat /root/rocketmq-all-5.1.0-bin-release/conf/2m-2s-async-Controller/broker-a.properties
brokerClusterName=DefaultCluster
brokerName=broker-a
deleteWhen=04
fileReservedTime=48
flushDiskType=ASYNC_FLUSH
#Broker 对外服务的监听端口
listenPort=30911
#存储路径
storePathRootDir=/data/rokcetmq_data_new_controller/
#commitLog 存储路径
storePathCommitLog=/data/rokcetmq_data_new_controller/commitlog
#消费队列存储路径存储路径
storePathConsumeQueue=/data/rokcetmq_data_new_controller/consumequeue
#消息索引存储路径
storePathIndex=/data/rokcetmq_data_new_controller/index
#checkpoint 文件存储路径
storeCheckpoint=/data/rokcetmq_data_new_controller/checkpoint
#abort 文件存储路径
abortFile=/data/rokcetmq_data_new_controller/abort
#Name service 地址
namesrvAddr=192.168.162.22:39876;192.168.162.23:39876;192.168.162.24:39876
#controlle service 地址
controllerAddr=192.168.162.22:9878;192.168.162.23:9868;192.168.162.24:9858
enableControllerMode=true
proxyMode=local
nameSrvAddr=192.168.162.22:39876;192.168.162.23:39876;192.168.162.24:39876
```

**Comment by socutes** [comment]
grpcServerPort=***

**Comment by bearTao** [comment]
> This parameter is configured using grpcServerPort. The default value is 8081. For example: grpcServerPort=9765
but i use  this parameter  dose not work  .like 
{
	"grpcServerPort":9765
}

**Comment by mxsm** [comment]
@bearTao  你如果还是需要部署在同一台机器上面，Broker的端口也需要进行修改不单单只有proxy的端口
