### ISSUE TITLE
different topics with the one consumergroup

### ISSUE THREAD

**Issue by sky-syk** [apache/rocketmq#637]
is there any problemes that one consumerGroup  consume different topis?

**Comment by Zanglei06** [comment]
it is absolutely ok with one group consume many topics.

**Comment by Zanglei06** [comment]
> is there any problemes that one consumerGroup consume different topis?

it is absolutely ok to consume multiple topics in one group.

**Comment by duhenglucky** [comment]
@sky-syk you can subscribe multi topics in one consumer group，but please keep subscription info consistent in the same consumer group.  if you have questions about rocketmq, please subscribe to our mailing list and send your question to our email: https://rocketmq.apache.org/about/contact/

**Comment by sky-syk** [comment]
thanks @Zanglei06 @duhenglucky
