### ISSUE TITLE
dashboard和命令行工具mqadmin查看生产者列表错误

### ISSUE THREAD

**Issue by zhangliweixyz** [apache/rocketmq#6371]
使用rocketmq dashboard查看生产者列表的时候，选择topic并输入生产者组名，查询返回了所有topic的生产者，并没有限制topic。
命令行工具mqadmin也存在同样的问题

**Comment by zhangliweixyz** [comment]
rocketmq version: 4.9.3
rocketmq-dashboard version: rocketmq-dashboard-1.0.0
topic: t-aaa  t-bbb
producergroup: p-test
mqadmin command: ./mqadmin producerConnection -g p-test -n localhost:9876 -t t-aaa
                                    ./mqadmin producerConnection -g p-test -n localhost:9876 -t t-bbb
我用生产者组p-test，只往t-aaa这一个topic里发消息了，但是用t-bbb查询也返回了这个生产者地址。
这是dashboard返回结果
![image](https://user-images.githubusercontent.com/70928799/225586361-8f0a9941-57d9-4d2c-a3f9-e5386fe35ece.png)
![image](https://user-images.githubusercontent.com/70928799/225586428-e9ba1826-98a8-4a56-b319-71636546c702.png)
这是mqadmin命令行返回结果：
![image](https://user-images.githubusercontent.com/70928799/225586906-55b47f66-2e9a-4406-8fc7-815388ea808c.png)

**Comment by zhangliweixyz** [comment]
https://github.com/apache/rocketmq/blob/0f878b515703e160b3ef095059ffb6f90a7f7f4a/tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java#L653
![image](https://user-images.githubusercontent.com/70928799/225588795-d9fc5651-9bac-4760-b68f-60c5491d56ce.png)
我在查看源码的时候，发现在调用getProducerConnectionList这个函数的时候，并没有传入topic，怀疑在获取生产者列表的时候并没有限制到具体的topic

**Comment by ShadowySpirits** [comment]
Unlike Kafka, the RocketMQ producer can send messages to any topic without prior specification. The broker is unable to identify producers that sent messages to the topic for now.

**Comment by zhangliweixyz** [comment]
ok, I understand, thanks
