### ISSUE TITLE
Why NettyRemotingClient not execute RPCHook#doAfterResponse in invokeAsync ?

### ISSUE THREAD

**Issue by wqliang** [apache/rocketmq#6379]
In `NettyRemotingClient#invokeSync`,  it will do `RPCHook#doAfterResponse` after complete invoking. 
https://github.com/apache/rocketmq/blob/4e0a723d225c0fb62bc764ead54f1267f9da2bfc/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java#L533

Why `invokeAsync` not do `RPCHook#doAfterResponse` ? Are there any considerations ？or a bug?
Maybe it should do `RPCHook#doAfterResponse` in callback ?
If this is a bug, I would like to  pull a request to fix it.

**Comment by lizhanhui** [comment]
It's a bug. Pull requests are welcome
