### ISSUE TITLE
Migrate logging related artifact to an independent apache repository.

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#6385]
We intend to create a brand new repository, maybe called rocketmq-logging?

**Comment by RongtongJin** [comment]
> We intend to create a brand new repository, maybe called rocketmq-logging?

I think it is a good idea. We can disscuss in Github Discussions.

**Comment by aaron-ai** [comment]
see https://github.com/apache/rocketmq/discussions/6526
