### ISSUE TITLE
what's used for about unitMode of clientConfig?

### ISSUE THREAD

**Issue by hepyu** [apache/rocketmq#639]
RT, I checked code, but have no idea what's it used for.

**Comment by duhenglucky** [comment]
@hepyu This config used for Unitized deployment，but now, we haven't used this setting to do some real work. and issue only used for bug report or feature request, if you have some question, please subscribe our mailing list and send your question to our email: https://rocketmq.apache.org/about/contact/

**Comment by zzw19990414** [comment]
亲，广播模式本地存储报错了，怎么设置自己的路径？
