### ISSUE TITLE
[GSoC] Make RocketMQ support higher versions of Java

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#6391]
We aim to update the RocketMQ codebase to support newer versions of Java in a cross-compile manner. The goal is to enable RocketMQ to work with Java17, while maintaining backward compatibility with previous versions of Java. This will involve identifying and updating any dependencies that need to be changed to support the new Java versions, as well as testing and verifying that the new version of RocketMQ works correctly. With these updates, users will be able to take advantage of the latest Java features and performance improvements. We hope that the community can come together to support this task and make RocketMQ a more versatile and powerful middleware system.

Specifically, this issue has been added to the [GSoC ideas list](https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2023+Ideas+list#GSoC2023Ideaslist-GSoCMakeRocketMQsupporthigherversionsofJava). You can refer to it here and we welcome community developers to apply. For more information about GSoC, please visit the official website.

**Comment by lizhimins** [comment]
Can you describe it more clearly? The impact of this tool is relatively broad

**Comment by Abhijeetmishr** [comment]
@aaron-ai @Oliverwqcwrw 
## Dear Project Mentor,

I am Abhijeet from India and I am excited to apply for the RocketMQ project as a part of GSoC. I have professional experience working with Java and Scala and I am well-versed in the modern paradigm of Java and functional programming. I have been contributing to RocketMQ for the past month and I am interested in open-source software development, as I find it rewarding to solve challenging problems that support the community.

I am particularly interested in the project that aims to update the RocketMQ codebase to support newer versions of Java in a cross-compile manner. I believe that this is a crucial project that will enable RocketMQ users to take advantage of the latest Java features and performance improvements while maintaining backward compatibility with previous versions of Java.

Regarding my approach to the project, I would begin by analyzing the existing codebase and identifying any dependencies that need to be changed to support the new Java versions. I would then proceed to update these dependencies while ensuring backward compatibility with previous versions of Java. I would also test and verify that the new version of RocketMQ works correctly and is stable. Throughout the project, I would work closely with the community to gather feedback and suggestions for improvement.

I have relevant experience in Java programming and software development, and I have been actively contributing to RocketMQ for the past month. I have also worked on several open-source projects in the past, which has helped me develop my skills in software development and collaborating with other developers.

I am available full-time for the duration of the GSoC program, and I am committed to completing the project within the given timeline. I would also be happy to collaborate with other developers in the community to ensure the success of the project.

Thank you for considering my proposal. Please let me know if you have any questions or if there are any additional details I can provide.

Sincerely,
Abhijeet
