### ISSUE TITLE
BrokerConfig.maxDelayTime is never used and easily confused with MessageStoreConfig.timerMaxDelaySec

### ISSUE THREAD

**Issue by caigy** [apache/rocketmq#6400]
`BrokerConfig.maxDelayTime` is never used in 4.x and 5.x version, maybe it was designed for controlling the longest delay time for delayed messages. However, when delayed messages with arbitrary delay was supported, `MessageStoreConfig.timerMaxDelaySec` has been adopted. 

Users may be confused the two configurations and also mis-configure `BrokerConfig.maxDelayTime` without any effects.

IMO `BrokerConfig.maxDelayTime` can be removed safely.

**Comment by lizhimins** [comment]
If you want to modify the parameter name, please clearly annotate it in the comments.
