### ISSUE TITLE
ShutdownHookMQTrace causes the process to fail to exit quickly when the consumer shutdown

### ISSUE THREAD

**Issue by ShirleyVera** [apache/rocketmq#6403]
I'm using the client version 4.9.3, and I've added message trace for both producer and consumer

I added shutdownhook to the project to complete the graceful exit of the project, which includes producer and consumer stops. However, the process cannot exit quickly during execution. The maximum duration is one minute. The stack information shows that the thread is blocked for a long time, causing the process to exit after about a minute.

How can I quickly shut down the MQ client

![stack](https://user-images.githubusercontent.com/92452450/226252455-bd06bc6c-0263-44c0-b3f7-4754f4aa6b29.jpg)

**Comment by lizhimins** [comment]
The graceful shutdown of a client involves several steps, such as notifying the server to remove the load balancing lock, asynchronously pushing the trace, etc. Can you confirm if the trace part is slow here?
