### ISSUE TITLE
发送事务消息，发出多条一样的消息！

### ISSUE THREAD

**Issue by ncl911** [apache/rocketmq#642]
版本4.3.0
重现场景：
在transactionlistener的executeLocalTransaction返回unknown，然后在checkLocalTransaction流程打上断点，卡住回查，待它多次回查时，再放开断点，发现发出了多条一样的消息，消息id也一样。
prepare消息topic同一条消息数量
![image](https://user-images.githubusercontent.com/23656622/50480600-d83e5500-0a17-11e9-9712-d1dc49226a72.png)
真实topic中同一消息数量
![image](https://user-images.githubusercontent.com/23656622/50480625-06239980-0a18-11e9-954d-a6efc0fbe2fd.png)

导致一条消息发送了多次，消费者也消费了多次
想知道为什么每次回查都要往prepare topic中放一条unknown消息，之前的消息已经存在，不应该是去更新消息状态之类的吗？？

**Comment by duhenglucky** [comment]
@ncl911 欢迎参与到rocketmq社区中,prepare消息每次后移是为了保证位点前进的同时，没有被确认的prepare消息能够保证得到回查响应，而且在队列存储中，永远只有append 操作，所以需要将prepare消息写到下一个位置后发送回查消息，另外，issue只用做bug report 以及feature request，所以咨询类的问题请使用邮件列表：https://rocketmq.apache.org/about/contact/

**Comment by ncl911** [comment]
明白 ，但是发出了多条一样的消息算不算bug？

**Comment by ncl911** [comment]
@duhenglucky 明白，但是发出了多条一样的消息算不算bug？？

**Comment by duhenglucky** [comment]
@ncl911 为了保证消息不丢失只能选择重复，因为消息不丢不重是做不到的。
