### ISSUE TITLE
SystemClock.now() is affected by NTP time synchronization, which can cause inaccuracies in the result of isOSPageCacheBusy().

### ISSUE THREAD

**Issue by dcais** [apache/rocketmq#6448]
SystemClock.now() is affected by NTP time synchronization, which can cause inaccuracies in the result of isOSPageCacheBusy().

**Comment by lizhanhui** [comment]
You are right. Definitely, this is a bug. Welcome to file a pull request to fix

**Comment by lizhanhui** [comment]
Use a **monotonic clock**, instead of a `system clock`, to measure the duration elapsed.

**Comment by socutes** [comment]
Can anyone fix this problem? You can assign it to me.

**Comment by dcais** [comment]
> You are right. Definitely, this is a bug. Welcome to file a pull request to fix

OK, i'm already fixed it in my company's fork.  try to file a pull request recently
