### ISSUE TITLE
The HA switch is not triggered when the broker disk I/O load is continuously high.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq#6468]
By simulating the failure of the injected disk load, the current disk usage reaches 99% .
as shown in the following figure:
![image](https://user-images.githubusercontent.com/16487356/227460707-6e0063d2-c2a9-4fd8-9e3c-70699c83e701.png)

![image](https://user-images.githubusercontent.com/16487356/227460754-1311f353-632d-4211-a8c8-4c3c7c0677d4.png)

we can find that the sending of messages continues to fail, and the delay of successfully sent messages also increases.

![image](https://user-images.githubusercontent.com/16487356/227461197-a9562da5-6e98-4797-8507-c5aad1914e94.png)

as shown in the figure, after a manual switch, the message is sent successfully and the failure rate decreases.

**Comment by ShannonDing** [comment]
From the current implementation, The controller module mainly depends on the heartbeats between the broker and the controller to determine whether the broker status is normal. However, if the broker disk has a problem, the Heartbeat can still be sent to the controller module. In this case, the Controller does not determine that the broker node is abnormal, which triggers a new election and a HA switching.

**Comment by GenerousMan** [comment]
Yes, in such cases, triggering automatic switching can make things better. 
I think it is possible to add health check in the master: When some fatal exceptions (such as IOException caused by disk problems) occur, the master can report to the controller and elect a new master——just as kafka did. Some non-fatal abnormal states may be recorded, which will contribute to the observability of HA.

**Comment by ShannonDing** [comment]
Should we consider another scenario at the same time?

When network jitter occurs, network reconnection may be triggered. In this case and in the view of the controller module, the broker channel will change.
when the controller detects that the old channel is closed, it will directly kick the broker out of the brokerLiveTable and trigger a re-election. 

At this point, the broker may reconnect quickly. Is it necessary to do a HA switching?

**Comment by ShannonDing** [comment]
> Should we consider another scenario at the same time?
> 
> When network jitter occurs, network reconnection may be triggered. In this case and in the view of the controller module, the broker channel will change. when the controller detects that the old channel is closed, it will directly kick the broker out of the brokerLiveTable and trigger a re-election.
> 
> At this point, the broker may reconnect quickly. Is it necessary to do a HA switching?

maybe we can open another issue to discuss this situation.

**Comment by DongyuanPan** [comment]
It does appear to be a problem. Need a clear rule to determine whether the machine is offline. we can discuss this rule

**Comment by DongyuanPan** [comment]
@RongtongJin @ShannonDing

**Comment by echooymxq** [comment]
I think it's a good idea to implement a health check endpoint on the broker side. Then  the brokerIsActive is nolong check the heartbeat,but invoke the endpoint. the endpoint is as simple as the heartbeat, just return the status health or not.  When elect the broker from the syncStateSet, it should also invoke it to check whether the broker is health before can be elelct as Master.
> At this point, the broker may reconnect quickly. Is it necessary to do a HA switching?

IMO, it't not neccssary. what more, The current controller has three places to trigger the election:
1. The broker channel closed.
2. The BrokerHeartbeatManager scanNotActiveBroker
3. The DLedgerController scanInactiveMasterAndTriggerReelect.

I think just the scanInactiveMasterAndTriggerReelect is  enough, In the current implementation, it is easy to have a concurrent election problem.

**Comment by RongtongJin** [comment]
> I think it's a good idea to implement a health check endpoint on the broker side. Then the brokerIsActive is no longer check the heartbeat,but invoke the endpoint. the endpoint is as simple as the heartbeat, just return the status health or not. When elect the broker from the syncStateSet, it should also invoke it to check whether the broker is health before can be elelct as Master.
> 
> > At this point, the broker may reconnect quickly. Is it necessary to do a HA switching?
> 
> IMO, it't not neccssary. what more, The current controller has three places to trigger the election:
> 
> 1. The broker channel closed.
> 2. The BrokerHeartbeatManager scanNotActiveBroker
> 3. The DLedgerController scanInactiveMasterAndTriggerReelect.
> 
> I think just the scanInactiveMasterAndTriggerReelect is enough, In the current implementation, it is easy to have a concurrent election problem.

Good suggestion. I also believe that disconnecting the channel should not immediately trigger the election.

**Comment by RongtongJin** [comment]
@ShannonDing @GenerousMan @DongyuanPan @echooymxq I agree with you. I think that switching is necessary when there are fatal I/O issues (such as disk corruption or abnormally high I/O).
However, we also need to give users a switch because if the disk is normal but the traffic itself is large, resulting in continuously high I/O, the switch will further affect the stability of the cluster.
In addition, switching standards and threshold settings is very challenging.

**Comment by ShannonDing** [comment]
> @ShannonDing @GenerousMan @DongyuanPan @echooymxq I agree with you. I think that HA switching is necessary when there are fatal I/O issues (such as disk corruption or abnormally high I/O). However, we also need to give users a optional switch because if the disk is normal but the traffic itself is large, resulting in continuously high I/O, the HA switch will further affect the stability of the cluster. In addition, HA switching standards and threshold settings is very challenging.

yes, let's clarify the HA switching rules and triggering thresholds.

**Comment by ShannonDing** [comment]
> I think it's a good idea to implement a health check endpoint on the broker side. Then the brokerIsActive is no longer check the heartbeat,but invoke the endpoint. the endpoint is as simple as the heartbeat, just return the status health or not. When elect the broker from the syncStateSet, it should also invoke it to check whether the broker is health before can be elelct as Master.
> 
> > At this point, the broker may reconnect quickly. Is it necessary to do a HA switching?
> 
> IMO, it't not neccssary. what more, The current controller has three places to trigger the election:
> 
> 1. The broker channel closed.
> 2. The BrokerHeartbeatManager scanNotActiveBroker
> 3. The DLedgerController scanInactiveMasterAndTriggerReelect.
> 
> I think just the scanInactiveMasterAndTriggerReelect is enough, In the current implementation, it is easy to have a concurrent election problem.

In fact, what we hope is that when the master fails, re-election can be triggered timely and quickly to ensure a timely switchover between the master and slave nodes. However, we don't want to trigger frequent HA switches due to small jitters.
Therefore, it is necessary to do regularly scanning node status actively and  do a passively trigger re-election by node abnormal events. What is important is that we may need to clarify the threshold and conditions for HA switch, as well as the timing for triggering re-election.
