### ISSUE TITLE
proxy cluster mode send heart beat to broker error when I enableAcl, the Error: No accessKey is configured

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6486]
Myenv:

jdk:1.8
rocketmqversion:5.0.0
prox mode: cluster
enableAcl: true

What happened:

I'm at tool.yml and palin_ Acl.yml is configured with ak/sk, but the proxy sends heartbeat reports to the broker without setting aksk

Error message:

2023-03-27 21:12:31 WARN MQClientFactoryScheduledThread - send heart beat to broker[rocketmq-cluster-broker-0 0 10.244.19.25:10911] failed
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:618) BROKER: 10.244.194.140:10911
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendHeartbeat(MQClientAPIImpl.java:1389)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBroker(MQClientInstance.java:548)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBrokerWithLock(MQClientInstance.java:464)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.lambda$startScheduledTask$4(MQClientInstance.java:302)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by xdkxlk** [comment]
You can try setting the `enableAclRpcHookForClusterMode` to true in ProxyConfig to see if it resolves the issue. For more information, please refer to #6079 and #5944.

**Comment by fengcharly** [comment]
For proxy, I used the code from the develop branch. **I has already setted enableAclRpcHookForClusterMode =true**, then I get the error:
2023-03-27 21:12:31 WARN MQClientFactoryScheduledThread - send heart beat to broker[rocketmq-cluster-broker-0 0 10.244.19.25:10911] failed
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:618) BROKER: 10.244.194.140:10911
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendHeartbeat(MQClientAPIImpl.java:1389)
at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBroker(MQClientInstance.java:548)
at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBrokerWithLock(MQClientInstance.java:464)
at org.apache.rocketmq.client.impl.factory.MQClientInstance.lambda$startScheduledTask$4(MQClientInstance.java:302)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by fengcharly** [comment]
> You can try setting the `enableAclRpcHookForClusterMode` to true in ProxyConfig to see if it resolves the issue. For more information, please refer to #6079 and #5944.



> For proxy, I used the code from the develop branch. **I has already setted enableAclRpcHookForClusterMode =true**, then I get the error:
> 2023-03-27 21:12:31 WARN MQClientFactoryScheduledThread - send heart beat to broker[rocketmq-cluster-broker-0 0 10.244.19.25:10911] failed
> org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:618) BROKER: 10.244.194.140:10911
> For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
> at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendHeartbeat(MQClientAPIImpl.java:1389)
> at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBroker(MQClientInstance.java:548)
> at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBrokerWithLock(MQClientInstance.java:464)
> at org.apache.rocketmq.client.impl.factory.MQClientInstance.lambda$startScheduledTask$4(MQClientInstance.java:302)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

For proxy, I used the code from the develop branch. I has already setted enableAclRpcHookForClusterMode =true, then I get the error:
2023-03-27 21:12:31 WARN MQClientFactoryScheduledThread - send heart beat to broker[rocketmq-cluster-broker-0 0 10.244.19.25:10911] failed
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:618) BROKER: 10.244.194.140:10911
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendHeartbeat(MQClientAPIImpl.java:1389)
at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBroker(MQClientInstance.java:548)
at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBrokerWithLock(MQClientInstance.java:464)
at org.apache.rocketmq.client.impl.factory.MQClientInstance.lambda$startScheduledTask$4(MQClientInstance.java:302)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by francisoliverlee** [comment]
> > You can try setting the `enableAclRpcHookForClusterMode` to true in ProxyConfig to see if it resolves the issue. For more information, please refer to #6079 and #5944.
> 
> > For proxy, I used the code from the develop branch. **I has already setted enableAclRpcHookForClusterMode =true**, then I get the error:
> > 2023-03-27 21:12:31 WARN MQClientFactoryScheduledThread - send heart beat to broker[rocketmq-cluster-broker-0 0 10.244.19.25:10911] failed
> > org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:618) BROKER: 10.244.194.140:10911
> > For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
> > at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendHeartbeat(MQClientAPIImpl.java:1389)
> > at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBroker(MQClientInstance.java:548)
> > at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBrokerWithLock(MQClientInstance.java:464)
> > at org.apache.rocketmq.client.impl.factory.MQClientInstance.lambda$startScheduledTask$4(MQClientInstance.java:302)
> > at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> > at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> > at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> > at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> > at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> > at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 
> For proxy, I used the code from the develop branch. I has already setted enableAclRpcHookForClusterMode =true, then I get the error: 2023-03-27 21:12:31 WARN MQClientFactoryScheduledThread - send heart beat to broker[rocketmq-cluster-broker-0 0 10.244.19.25:10911] failed org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:618) BROKER: 10.244.194.140:10911 For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendHeartbeat(MQClientAPIImpl.java:1389) at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBroker(MQClientInstance.java:548) at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBrokerWithLock(MQClientInstance.java:464) at org.apache.rocketmq.client.impl.factory.MQClientInstance.lambda$startScheduledTask$4(MQClientInstance.java:302) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

设置enableAclRpcHookForClusterMode=true后，需要添加acl文件： $ROCKETMQ_HOME/conf/tools.yml。这样proxy会使用conf/tools.yml中的acl配置。
配置类似
![image](https://user-images.githubusercontent.com/5908412/228417488-4e202df9-43e2-4140-8476-3493e2ee640a.png)

**Comment by fengcharly** [comment]
> > > You can try setting the `enableAclRpcHookForClusterMode` to true in ProxyConfig to see if it resolves the issue. For more information, please refer to #6079 and #5944.
> > 
> > 
> > > For proxy, I used the code from the develop branch. **I has already setted enableAclRpcHookForClusterMode =true**, then I get the error:
> > > 2023-03-27 21:12:31 WARN MQClientFactoryScheduledThread - send heart beat to broker[rocketmq-cluster-broker-0 0 10.244.19.25:10911] failed
> > > org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:618) BROKER: 10.244.194.140:10911
> > > For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
> > > at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendHeartbeat(MQClientAPIImpl.java:1389)
> > > at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBroker(MQClientInstance.java:548)
> > > at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBrokerWithLock(MQClientInstance.java:464)
> > > at org.apache.rocketmq.client.impl.factory.MQClientInstance.lambda$startScheduledTask$4(MQClientInstance.java:302)
> > > at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> > > at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> > > at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> > > at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> > > at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> > > at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> > 
> > 
> > For proxy, I used the code from the develop branch. I has already setted enableAclRpcHookForClusterMode =true, then I get the error: 2023-03-27 21:12:31 WARN MQClientFactoryScheduledThread - send heart beat to broker[rocketmq-cluster-broker-0 0 10.244.19.25:10911] failed org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:618) BROKER: 10.244.194.140:10911 For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendHeartbeat(MQClientAPIImpl.java:1389) at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBroker(MQClientInstance.java:548) at org.apache.rocketmq.client.impl.factory.MQClientInstance.sendHeartbeatToAllBrokerWithLock(MQClientInstance.java:464) at org.apache.rocketmq.client.impl.factory.MQClientInstance.lambda$startScheduledTask$4(MQClientInstance.java:302) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 
> 设置enableAclRpcHookForClusterMode=true后，需要添加acl文件： $ROCKETMQ_HOME/conf/tools.yml。这样proxy会使用conf/tools.yml中的acl配置。 配置类似 ![image](https://user-images.githubusercontent.com/5908412/228417488-4e202df9-43e2-4140-8476-3493e2ee640a.png)

thanks，it works
