### ISSUE TITLE
Consumer setPullInterval is not working when pullInterval > 120 seconds

### ISSUE THREAD

**Issue by Cicizz** [apache/rocketmq#653]
**BUG REPORT**

1. Please describe the issue you observed:
  I use pushConsumer to consume messages,I need to consume slowly,so I check the code of consumer,and I find 2 methods to solve it,and one of them is 
  ` consumer.setPullInterval(10*60*1000); `,but I find when pullInterval is over 120 seconds,the consumer will continue pull messages from broker every 120 seconds.

2. Please tell us about your environment:
  rocketmq3.2.6，4.3.0，4.3.1

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
  I find this problem was caused by ` RebalanceImpl.updateProcessQueueTableInRebalance()`

  when rebalance happend，the process queue will check this queue whether  pull expired or not，and the default queue pull expire time is 120 seconds, if queue pull expired，then will remove this queue from this consumer and create a new process queue to consume this message queue,and create a pull request of this queue to pull messages from broker,so pullInterval is not working when pullInterval  > 120 seconds.I think when check the queue pullExpired ,should also check the pullInterval.

  maybe it is not a BUG,but is also  confused,

**Comment by dongeforever** [comment]
@Cicizz 120 seconds is quite long enough. If you still want to slow the consuming speed, you may need to do some throttle in the MessageListener.

**Comment by Cicizz** [comment]
OK,thanks

**Comment by CarpenterLee** [comment]
Alibaba open source flow control framework [Sentinel](https://github.com/alibaba/Sentinel) fits your needs fine. It's *A lightweight flow-control library providing high-available protection and monitoring*. See [限流 匀速器](https://github.com/alibaba/Sentinel/wiki/%E9%99%90%E6%B5%81---%E5%8C%80%E9%80%9F%E5%99%A8) .
