### ISSUE TITLE
Replace guava LoadingCache with caffeine LoadingCache in proxy service

### ISSUE THREAD

**Issue by redlsz** [apache/rocketmq#6535]
1. Please describe the issue you observed:

In proxy ClusterMetadataService, we use guava LoadingCache to cache topicConfig and subscriptionGroupConfig
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/103550934/229716347-6cd9fcb3-984c-453f-9583-5a935cfeae9e.png">

In proxy TopicRouteService, we use caffeine LoadingCache to cache topic MessageQueueView
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/103550934/229715551-40cd7cf0-525c-42ba-8632-6be1df474026.png">

Factually, we may replace guava cache with caffeine, which is compatible and performs better.

**Comment by anurag-sachan** [comment]
![Screenshot 2023-04-05 at 18 16 40 (2)](https://user-images.githubusercontent.com/100314097/230085034-3cce4e30-92f1-45d1-9e86-76c6df8e373c.png)
 
I am trying to change caching of ClusterMetadataService from guava to caffeine. Can anyone help me with the logic/ code thats required here!

**Comment by Abhijeetmishr** [comment]
@Oliverwqcwrw I like to work on this. Please assign me.

**Comment by redlsz** [comment]
Also offer an optimization pr, please take a look. @Oliverwqcwrw @aaron-ai

**Comment by Abhijeetmishr** [comment]
> Also offer an optimization pr, please take a look. @Oliverwqcwrw @aaron-ai

@redlsz should i close my PR ?

**Comment by Oliverwqcwrw** [comment]
> > Also offer an optimization pr, please take a look. @Oliverwqcwrw @aaron-ai
> 
> @redlsz should i close my PR ?

Let's review @redisz's PR. review is also a contribution to the community. Thank you again for your contribution to the community

**Comment by Abhijeetmishr** [comment]
> > > Also offer an optimization pr, please take a look. @Oliverwqcwrw @aaron-ai
> > 
> > 
> > @redlsz should i close my PR ?
> 
> Let's review @redisz's PR. review is also a contribution to the community. Thank you again for your contribution to the community

@Oliverwqcwrw Thank you. Sure Let's get review that.
