### ISSUE TITLE
Cannot automatically create a topic when connecting to rocketmq proxy。

### ISSUE THREAD

**Issue by DuanxianshengGO** [apache/rocketmq#6540]
rockermq version：5.1.0
client version：v5.0.1-rc1-golang

Description：Cannot automatically create a topic when connecting to rocketmq proxy，but it is normal when connecting to rocketmq nameServer.
error：startUp err=failed to get topic route data result from remote during client startup, clientId=DuaneDuan-pc@27680@0@gjs28493ae, topics=[testTopic2], err=CODE: TOPIC_NOT_FOUND, MESSAGE: CODE: 17  DESC: No topic ro
ute info in name server for the topic: testTopic2

broker config:   autoCreateTopicEnable=true

proxy config: {
  "enableFlowControl": true,
  "enableFlowLimitAction": true,
  "autoCreateTopicEnable": true,
  "grpcClientProducerBackoffInitialMillis": 5,
  "grpcClientProducerBackoffMaxMillis": 1000,
  "grpcClientProducerBackoffMultiplier": 5,
  "longPollingReserveTimeInMillis": 1000,
  "maxMessageGroupSize": 64,
  "maxMessageSize": 4194304,
  "maxUserPropertySize": 16384,
  "metricCollectorMode": "proxy",
  "namesrvAddr": "10.1.60.44:9876;10.1.60.45:9876;10.1.60.52:9876",
  "rocketMQClusterName": "DefaultCluster",
  "transactionHeartbeatBatchNum": 1,
  "userPropertyMaxNum": 128,
  "remotingAccessAddr": "10.1.60.82"
}

**Comment by drpmma** [comment]
The behavior of the auto-create topic is an outdated design and it is strongly not recommended for production. So there is no plan to implement it in the Proxy module.

**Comment by DuanxianshengGO** [comment]
> The behavior of the auto-create topic is an outdated design and it is strongly not recommended for production. So there is no plan to implement it in the Proxy module.

Thanks for the answer.
