### ISSUE TITLE
Property acquisition error

### ISSUE THREAD

**Issue by zhihaooooo** [apache/rocketmq#6549]
rocketmq-rocketmq-all-5.0.0/client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java

Line 150 should be getBackPressureForAsyncSendSize

``
if (defaultMQProducer.getBackPressureForAsyncSendNum() > 1024 * 1024) {
            semaphoreAsyncSendSize = new Semaphore(Math.max(defaultMQProducer.getBackPressureForAsyncSendNum(),1024 * 1024), true);
        } else {
            semaphoreAsyncSendSize = new Semaphore(1024 * 1024, true);
            log.info("semaphoreAsyncSendSize can not be smaller than 1M.");
        }
``

**Comment by Oliverwqcwrw** [comment]
duplicated with #6536
