### ISSUE TITLE
does rocketmq support node.js connections?

### ISSUE THREAD

**Issue by cnyet** [apache/rocketmq#6563]
I realise that RocketMQ does work with client sdk includes java, C++, go, it isn't clear whether nodejs is supported and no related demo.

at present, my project is a backend service developed by nodejs, it doed or doesn't consume rocketmq topic?

expect to a reply. thanks.

**Comment by HScarb** [comment]
You can take a loot at https://github.com/apache/rocketmq-client-nodejs.
And nodeJs gRPC client are working in progress https://github.com/apache/rocketmq-clients/

**Comment by cnyet** [comment]
I have already tried the rocket-client-nodejs module, but it reported a fatal error that 'CProducer.h' file not found when I runed that npm install.

what's wrong?
