### ISSUE TITLE
query new topic first message fail,but message list have message

### ISSUE THREAD

**Issue by xox9001** [apache/rocketmq#657]
英语水平比较差，感谢你的阅读。
=====
rocketmq version: 4.3.2 (namesrv,broker)
=====
process：
1、create new topic
2、use golang client send no key and no tag and has delay level message
3、open rocketmq-console-ng，go MESSAGE PAGE, select created topic, show topic message by time(default), in message list,only 1 message,i call it #1, #1 message is OK.

But, click #1 message detail ,alert exception.
use #1 msgId search  in rocketmq-console-ng page,tips no message.
But,producer push more message,after #1 msg, other msg is normal。

 Chinese ================= BUG 还原：
1、创建一个新的TOPIC
2、使用 golang 客户端(by https://github.com/apache/rocketmq-client-go)提交一条没有key 没有tag 并且延迟等级任意（这里我设置的是1）的消息。
3、打开RocketMq-Console-Ng，根据topic查看消息列表，这条消息可以列出，但是点击消息详情，却提示失败，检查RocketMq-Console-Ng的runtime log ,提示消息查找完成，但是没有消息返回。
使用 mqadmin 查询这条 msgID，却提示连接broker 失败，正确broker IP：192.168.31.152 在回显中被显示为 152.31.168.192:5664,尴尬。

**Comment by xox9001** [comment]
> msg := fmt.Sprintf("Hello RocketMQ-%d", i)
> 		msgT := new(rocketmq.Message)
> 		msgT.Topic = "orderlyTest"
> 		msgT.Body = "msg,I:"+strconv.Itoa(i)
> 		msgT.DelayTimeLevel = 1
> 		//msgT.Keys = strconv.Itoa(i)
> 		//msgT.Tags = "test"
> 		//result,err := producer.SendMessageSync(msgT)
> 		selector := queueSelectorByOrderID{}
> 		result,err := producer.SendMessageOrderly(msgT,selector,4,3)

**Comment by ShannonDing** [comment]
close due to time too long, if this issue still occurs on the latest version, please reopen this issue again.
