### ISSUE TITLE
 NullPointerException when pop message from light message queue

### ISSUE THREAD

**Issue by HScarb** [apache/rocketmq#6576]
Pop message from LMQ will return `messageExt` of the original topic.
When building its POP_CK in the client, a NullPointerException will occur in `MQClientAPIImpl#processPopResponse()`.
Because LMQ only has 1 queue, but the original topic has several queues, it will cause an error when getting the original topic's msgQueueOffset from LMQ's msgOffsetInfo.

![image](https://user-images.githubusercontent.com/10664298/231120310-d8646dac-11e9-4313-b976-c7723cac2311.png)
![image](https://user-images.githubusercontent.com/10664298/231123864-6eeaf581-bf5c-428d-bc62-12ab4255f513.png)

client version: 5.1.0

**Comment by pingww** [comment]
Indeed, currently LMQ does not support POP

**Comment by lzkisok** [comment]
请问目前LMQ支持POP模式了吗？

**Comment by lepdou** [comment]
请问目前LMQ支持POP模式了吗？
