### ISSUE TITLE
In Rocketmq5.0 controller mode, I only deployed one broker and unexpectedly displayed it as being selected as a slave node

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6586]
In Rocketmq5.0 controller mode, I only deployed one broker and unexpectedly displayed it as being selected as a slave node

**Comment by Oliverwqcwrw** [comment]
Delete the DLedgerController directory, epochFileCheckpoint, epochFilecheckpoint.bak files and try deploying them

**Comment by fengcharly** [comment]
> Delete the DLedgerController directory, epochFileCheckpoint, epochFilecheckpoint.bak files and try deploying them

Thank you, it has taken effect
