### ISSUE TITLE
DefaultMessagestore start hang

### ISSUE THREAD

**Issue by lvxiao1** [apache/rocketmq#6593]
When I start the broker, the log for registering namesrv doesn't print. When I use jstack to check, I found that the main thread has been running on FileChannelImpl.trylock, and the status is not blocked. This situation has been going on for two days. What could be the reason for this?
![微信图片_20230414172608](https://user-images.githubusercontent.com/13183021/232006844-70ac469f-0e19-40bd-90e6-54bdd6bac4c2.png)

deployment to k8s
operator: rocketmq-broker:4.5.0-alpine-operator-0.3.0

**Comment by HScarb** [comment]
It seems stuck on the lock operation when getting the lock of the Rocketmq `store` folder.
Try to check the store folder, '{user.home}/store` by default.

**Comment by lvxiao1** [comment]
> It seems stuck on the lock operation when getting the lock of the Rocketmq `store` folder. Try to check the store folder, '{user.home}/store` by default.
@HScarb  it is deployed on k8s, and the mounted directories are all isolated from each other, so the lock files will not be read by multiple brokers.  The current confusion is that FileChannelImpl. trylock is non-blocking, and if the lock already exists, it will immediately cause an exception or return null.  However, in reality, it has been blocked on this method.
