### ISSUE TITLE
ACL PlainPermissionChecker.check confusion

### ISSUE THREAD

**Issue by miles-ton** [apache/rocketmq#6594]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/77013030/232286712-fe9ff484-9a53-4738-8602-05f5c0a2b294.png" />

1. i found a very confused code segment in PlainPermissionChecker.check, dose the firs segment in frame above want  to indicate that the admin have any permission and don't need verification? 
if that's the case, why still go through the verification when ownedPermMap isn't null?

3. what does 'isGroup' do, is it the duplicated code for the second and third red frame?

**Comment by francisoliverlee** [comment]
1.  agree with you, if admin, it could stop to do verification
2. retry topic does not have any acl in files, if resource is a retry topic, it check the default group's acl

**Comment by miles-ton** [comment]
> 1. agree with you, if admin, it could stop to do verification
> 2. retry topic does not have any acl in files, if resource is a retry topic, it check the default group's acl

thanks for your explanation, i will give out a PR to fix 1

**Comment by drpmma** [comment]
Good catch! I will assign this issue to you.
