### ISSUE TITLE
Broker dynamically perceives the expansion and contraction of nameserver

### ISSUE THREAD

**Issue by charlienss** [apache/rocketmq#6599]
I hope the broker dynamically perceives the expansion and contraction of nameserver，except for the static HTTP method，can support it？

**Comment by drpmma** [comment]
Could you please share more about your thoughts or reasons?

**Comment by fengcharly** [comment]
> Could you please share more about your thoughts or reasons?

At the beginning, I was planning to deploy a static HTTP service like this. Although I solved the problem of dynamically updating routes, I found that I had changed the broker configuration and still needed to restart it to take effect. Compared to the expansion and contraction scenarios of nameserver, there are still many cases where the configuration has not been changed, so there is no need to spend more resources deploying an HTTP static server, It's better to restart now, and the statefulset's rolling upgrade strategy can also prevent service unavailability

**Comment by fengcharly** [comment]
I think it's possible to see if the broker supports dynamic routing by default, as this is necessary in k8s. Additionally, it would be great if all broker configurations support dynamic routing
