### ISSUE TITLE
How should I create a topic if I do not enable the console in the k8s deployment environment

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6603]
How should I create a topic if I do not enable the console in the k8s deployment environment

I see this issu：https://github.com/apache/rocketmq/issues/6540，and I also encountered the same confusion

Do I have to deploy Rocketmq console？

I think this is very unreasonable, or it's okay to provide a method that can create a topic through proxy

**Comment by superhx** [comment]
you could create a topic create RocketMQ Admin Tools https://rocketmq.apache.org/docs/deploymentOperations/02admintool

**Comment by fengcharly** [comment]
> you could create a topic by RocketMQ Admin Tools https://rocketmq.apache.org/docs/deploymentOperations/02admintool

The Admin Tool can only be executed in the pod, and I think it would be more reasonable to integrate relevant functions into the proxy

**Comment by drpmma** [comment]
> 

The admin tool, of course, can be executed anywhere, it connects to the broker and nameserver and only depends on the network topology.

**Comment by fengcharly** [comment]
> > 
> 
> The admin tool, of course, can be executed anywhere, it connects to the broker and nameserver and only depends on the network topology.

Can it connect to proxy？I need performance pressure test data in this area.

**Comment by aaron-ai** [comment]
Please see https://github.com/apache/rocketmq/issues/6153

**Comment by fengcharly** [comment]
> Please see #6153

thanks,I will take it

**Comment by drpmma** [comment]
close because it's in the discussion #6638
