### ISSUE TITLE
msgGetTotalTodayNow far greater than msgPutTotalTodayNow

### ISSUE THREAD

**Issue by codecodesam** [apache/rocketmq#6608]
I deployed a RocketMQ, created a consumer group, a Topic, and enabled a simple program to consume and produce. The program is a singleton, there is only one consumer in the consumer group, and the consumption code is very simple, which is to output information to the console

I installed dashboard and found msgGetTotalTodayNow far greater than msgPutTotalTodayNow

<img width="890" alt="image" src="https://user-images.githubusercontent.com/89377053/232692582-a1d3f9cf-e365-4154-baac-901cb5a0eae6.png">

**Comment by anurag-sachan** [comment]
Isn't it normal, is making changes here necessary? if yes, let me know I'll create PR

**Comment by codecodesam** [comment]
> You should close this PR, if we want data for finance market for 6 hours for every second it will be 21600. At least for msgGetTotalTodayNow value LGTM

I don't quite understand what you mean

**Comment by Oliverwqcwrw** [comment]
@codecodesam ,
Which version do you use?

**Comment by ni-ze** [comment]
the messages may be get by different consumer group.

**Comment by codecodesam** [comment]
> @codecodesam , Which version do you use?

latest

**Comment by codecodesam** [comment]
> the messages may be get by different consumer group.

only one

**Comment by drivebyer** [comment]
The issue persists. In some cases, the msgPutTotalTodayNow and msgGetTotalTodayNow values are still not correct.
