### ISSUE TITLE
请教个如何广播模式下不重复消费的问题

### ISSUE THREAD

**Issue by MrZbb** [apache/rocketmq#6614]
我们现在开发有个需求，子节点会订阅生产者广播消息，然后做一些长时间的任务操作。子节点会有扩容缩容的情况，那么如何保证广播模式下每个子节点都是从最新的消费位点消费。
以下是个例子：
假如现在子节点有10个，那么子节点运行期间，是基本不会重复消费的，但是这个时候突然要求其中的一个子节点先不用了关闭，因为广播模式下offset是在消费者本地文件存储的，然后过了一段时间后，又希望这个节点启用，那这个时候这个节点就会把停用的这段时间的没有接收的消息重新消费一次。但是期望的这个节点从最新的开始消费。我想到一种投机取巧的方式是在应用每次启动的时候，删除消费者本地offsets文件，这样是不是可以保证子节点每次都是消费最新的，但是这样的话会不会跟rocketmq广播模式的设计理念有违背，求大佬指导，还是说这种需求下就不应该用rocketmq

**Comment by aaron-ai** [comment]
Please try using [GitHub Discussions](https://github.com/apache/rocketmq/discussions) to ask questions. Refer to [this](https://github.com/apache/rocketmq/issues/6153).
