### ISSUE TITLE
I found that changing the broker's palin_ Acl. yaml has no effect, but changing proxy's plain_ Acl.yaml can take effect, accessed through proxy in the k8s environment

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6626]
I found that changing the broker's palin_ Acl. yaml has no effect, but changing proxy's plain_ Acl.yaml can take effect, accessed through proxy in the k8s environment

**Comment by xdkxlk** [comment]
Proxy and broker have their own ACL configuration file. If accessed through proxy, the ACL configuration of proxy takes effect for the client.
