### ISSUE TITLE
GitHub issue template improvement plan

### ISSUE THREAD

**Issue by aaron-ai** [apache/rocketmq#6629]
There are currently a few "issues" with the RocketMQ issue template, and I believe it is necessary to take a series of actions to improve it. Here are some of the problems:

1. The issue template is overly lengthy, making it difficult for people to have the patience to read through. This leads to the issue template becoming merely a formality.
2. We have already initiated an initiative urging users to ask questions in [GitHub discussions](https://github.com/apache/rocketmq/discussions). However, some issues still do not follow the corresponding guidelines. Can we somehow circumvent this in the issue template?
3. It would be even better if multiple language versions could be provided, allowing non-native English-speaking developers to better understand our intentions of the issue specification(although I think the more universal English language is still worth encouraging).

These are some of my thoughts, and I welcome more people to join in.

**Comment by miles-ton** [comment]
yeap, current issue template too bloated to see, we should make it cleaner. we should provide multiple issue templates for different kind of issue instead of trying use one template to describe all of them. three most common issue type may be bug, polish and new feature issue.

**Comment by RongtongJin** [comment]
Good idea. The current template content is too redundant, and there are no other options besides Bug Reports and Features. 

Regarding the third point, I suggest maintaining an English template to maintain consistency (if the template is in Chinese, would it cause more issues or pull requests to be written in Chinese? Alternatively, maybe we could writeother languages in Discussions as there are more questions, but try to keep issues and pull requests in English as much as possible).

**Comment by ShadowySpirits** [comment]
Maintaining multiple issue templates is a good idea. In this way, we can add labels to different kinds of issues automatically, and then do some special work for these issues such as guiding users to ask questions in GitHub discussion.

**Comment by drpmma** [comment]
+1, and the pr template is also needed to update, see #5353
