### ISSUE TITLE
When I Maven installed this project, an error was reported。an error is that response must be non-null but is marked as nullable

### ISSUE THREAD

**Issue by wwx412775** [apache/rocketmq#6639]
[ERROR] High: response must be non-null but is marked as nullable [org.apache.rocketmq.remoting.netty.NettyRemotingAbstract] At NettyRemotingAbstract.java:[lines 219-231] NP_PARAMETER_MUST_BE_NONNULL_BUT_MARKED_AS_NULLABLE
[INFO] 

To see bug detail using the Spotbugs GUI, use the following command "mvn spotbugs:gui"

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache RocketMQ 5.1.1-SNAPSHOT ..................... SUCCESS [  8.889 s]
[INFO] rocketmq-common 5.1.1-SNAPSHOT ..................... SUCCESS [01:01 min]
[INFO] rocketmq-remoting 5.1.1-SNAPSHOT ................... FAILURE [ 28.522 s]
[INFO] rocketmq-client 5.1.1-SNAPSHOT ..................... SKIPPED
[INFO] rocketmq-store 5.1.1-SNAPSHOT ...................... SKIPPED
[INFO] rocketmq-tiered-store 5.1.1-SNAPSHOT ............... SKIPPED
[INFO] rocketmq-srvutil 5.1.1-SNAPSHOT .................... SKIPPED
[INFO] rocketmq-filter 5.1.1-SNAPSHOT ..................... SKIPPED
[INFO] rocketmq-acl 5.1.1-SNAPSHOT ........................ SKIPPED
[INFO] rocketmq-broker 5.1.1-SNAPSHOT ..................... SKIPPED
[INFO] rocketmq-tools 5.1.1-SNAPSHOT ...................... SKIPPED
[INFO] rocketmq-controller 5.1.1-SNAPSHOT ................. SKIPPED
[INFO] rocketmq-namesrv 5.1.1-SNAPSHOT .................... SKIPPED
[INFO] rocketmq-proxy 5.1.1-SNAPSHOT ...................... SKIPPED
[INFO] rocketmq-container 5.1.1-SNAPSHOT .................. SKIPPED
[INFO] rocketmq-test 5.1.1-SNAPSHOT ....................... SKIPPED
[INFO] rocketmq-distribution 5.1.1-SNAPSHOT ............... SKIPPED
[INFO] rocketmq-openmessaging 5.1.1-SNAPSHOT .............. SKIPPED
[INFO] rocketmq-example 5.1.1-SNAPSHOT .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:39 min
[INFO] Finished at: 2023-04-23T23:13:18+08:00
[INFO] Final Memory: 77M/844M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.2.2:check (check) on project rocketmq-remoting: failed with 1 bugs and 0 errors  -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rocketmq-remoting

![Snipaste_2023-04-23_23-24-44](https://user-images.githubusercontent.com/25542662/233848786-afa4ebe5-2230-45a7-ac1d-13dbf9b93d95.png)

**Comment by drpmma** [comment]
Could you please provide your command? It's `mvn clean install`?

**Comment by ShadowySpirits** [comment]
I run `mvn spotbugs:gui` but do not reproduce your problem. Additionally, the param response of `writeResponse` function indeed could be null, it would be appropriate to add @Nullable.

**Comment by wwx412775** [comment]
it happened when I used idea for Maven clean。yes，I think we need to delete @Nullable。For developers, this is unfriendly encoding。

**Comment by wwx412775** [comment]
i run maven install。 this error happens。
![Snipaste_2023-04-24_22-31-52](https://user-images.githubusercontent.com/25542662/234028819-0738e88f-cf9e-4897-a63f-bb58d0b3f878.png)

**Comment by drpmma** [comment]
I can not reproduce your error. Maybe you can try 'mvn clean' before install command.

**Comment by Seven-Hc** [comment]
> it happened when I used idea for Maven clean。yes，I think we need to delete @nullable。For developers, this is unfriendly encoding。

I have the same problem as you. I deleted @nullable and it worked. But I don't know why.
