### ISSUE TITLE
RemotingUtil has a logic bug

### ISSUE THREAD

**Issue by jackxy** [apache/rocketmq#664]
is this a bug ?
https://github.com/apache/rocketmq/blob/master/remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java#L170

https://github.com/apache/rocketmq/blob/master/remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java#L176

when you set configureBlocking is true ,but you set configureBlocking to false final

the expect value is false, so you can delete the line 170

**Comment by ymwneu** [comment]
Notice the line 175. When configureBlocking is true, the connect() will blocking until the connection established or timeout. But if configureBlocking is false, we should use socketChannel#finishConnect() to check whether the connection is established, it will bring additional work. So, i think in line 170, it make sure the  socketChannel is blocking before connect() is invoked.

**Comment by duhenglucky** [comment]
@jackxy as @ymwneu comment, this is a tradeoff in implementation, and could I close this issue first? if you have more question about this, please feel free to reopen it, and it would be nice if you can discuss it on our mailing list: https://rocketmq.apache.org/about/contact/
