### ISSUE TITLE
The default listenPort of the broker in Rocketmq is 6888, which is not 10911 on the official document, resulting in abnormal communication between services

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6642]
The default listenPort of the broker in Rocketmq is 6888, which is not 10911 on the official document, resulting in abnormal communication between services

**Comment by RongtongJin** [comment]
> The default listenPort of the broker in Rocketmq is 6888, which is not 10911 on the official document, resulting in abnormal communication between services

If you are not starting the broker in Container mode (which is often not the case), the default port for startup is 10911 and the parameter used is listenePort in NettyServerConfig.
https://github.com/apache/rocketmq/blob/14ad16b0d5e5ac770cf00660d8570d74a0a8a150/broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java#L89

**Comment by fengcharly** [comment]
> > The default listenPort of the broker in Rocketmq is 6888, which is not 10911 on the official document, resulting in abnormal communication between services
> 
> @fengcharly If you are not starting the broker in Container mode (which is often not the case), the default port for startup is 10911 and the parameter used is listenePort in NettyServerConfig.
> 
> https://github.com/apache/rocketmq/blob/14ad16b0d5e5ac770cf00660d8570d74a0a8a150/broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java#L89
> 
> In addition, it is recommended to discuss such issues in the github discussion

I understand. If my broker is started in the docker (of course, only one broker is started in one docker), 6888 is actually my docker port number
