### ISSUE TITLE
Why is the topic no longer supporting '|' ?

### ISSUE THREAD

**Issue by KitherRunner** [apache/rocketmq#6653]
Topic Pattern change：

RocketMQ 4.x rocket-client： 
	
	// 重复的校验逻辑
	org.apache.rocketmq.client.Validators#checkTopic
	org.apache.rocketmq.common.topic.TopicValidator#validateTopic： ^[%|a-zA-Z0-9_-]+$

RocketMQ 5.x rocket-client-java：

	org.apache.rocketmq.client.java.message.MessageBuilderImpl#TOPIC_PATTERN： ^[%a-zA-Z0-9_-]+$

What is the reason for not supporting `|` ?

**Comment by chenzlalvin** [comment]
Version 5.0 has converged the use of special characters and recommends the use of regular characters. % is an exception because it has already been used for system isolation.
