### ISSUE TITLE
Consumer rebalance problem when using docker container

### ISSUE THREAD

**Issue by vancefantasy** [apache/rocketmq#667]
**BUG REPORT**

1. Please describe the issue you observed:

docker环境下，2个不同的consumer实例，生成的clientId是重复的，进而导致rebalance的结果混乱。（经过debug发现获取到的ip是一样的，怀疑跟rancher网络有关）

2. Please tell us about your environment:

rocketmq client "4.3.0"
java version "1.8.0_181"
Docker version "18.09.0"

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

建议：改进ClientConfig类中instanceName的生成规则

**Comment by huanwei** [comment]
What's the current generation rule in ClientConfig class? And how to reproduce it?

**Comment by vancefantasy** [comment]
@huanwei 

clientId:

     public String buildMQClientId() {
        StringBuilder sb = new StringBuilder();
        sb.append(this.getClientIP());
        sb.append("@");
        sb.append(this.getInstanceName());
        if (!UtilAll.isBlank(this.unitName)) {
            sb.append("@");
            sb.append(this.unitName);
        }
        return sb.toString();
    }

instanceName:

    private String instanceName = System.getProperty("rocketmq.client.name", "DEFAULT");

    public void changeInstanceNameToPID() {
        if (this.instanceName.equals("DEFAULT")) {
            this.instanceName = String.valueOf(UtilAll.getPid());
        }
    }

在docker环境下（使用host模式），clientIp和pid都是一样的。当然clientIp也一样的确切原因还没完全确认，[可能和引入Rancher有关](https://github.com/rancher/rancher/issues/5499)。

<img width="154" alt="wx20190112-180557 2x" src="https://user-images.githubusercontent.com/42924205/51071992-c48c2300-1694-11e9-8b4b-c949f446e0a5.png">

https://github.com/apache/rocketmq/pull/668

**Comment by caigy** [comment]
I encountered the same problem. Under _HOST_ networking mode, all dockers managed by Rancher are with the same docker0 IP, which is 172.17.0.1.  Thus, RemotingUtil.getLocalAddress() always returns "172.17.0.1" for those dockers, which leads to collision between consumers with the same pid, if using default "IP@pid" clientId. 

- RocketMQ client Version: 4.3.2
- Rancher Version: 1.16.10
- Docker Version: 18.09.5

**Comment by vongosling** [comment]
@huanwei This is a known problem in the docker container if we deploy mutl-docker containers in the one machine.

**Comment by duhenglucky** [comment]
@caigy @huanwei if used Rancher to manage container, all docker will always return  "172.17.0.1" when getLocalAddress, not only in bridge model, but also in host model, so I think it may be an issue caused by Rancher,  so you can temporarily solve this problem by setting the instanceName.

**Comment by huanwei** [comment]
That's known issue caused by Rancher container network. Setting different instanceName should solve this problem, just as @duhenglucky suggested.

**Comment by haycco** [comment]
Which version have been solved, I also meeting the same problem.

**Comment by maixiaohai** [comment]
Has this be fixed?

**Comment by Aaron-TangCode** [comment]
除了通过手动自定义instanceName外，RocketMQ会做什么来兼容吗？还是不考虑兼容了？

**Comment by Git-Yang** [comment]
I would like a more general way to completely solve the problem of instance conflicts.  https://github.com/apache/rocketmq/issues/3680
