### ISSUE TITLE
Enhance getting PID

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#6671]
### Before Creating the Enhancement Request

- [x] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

use reflection to improve compatibility with Android Platform which does not support JMX extensions to get PID

### Motivation

![image](https://user-images.githubusercontent.com/15797831/235365252-5f49be1c-9ad2-40cd-b801-1d0f83da64a7.png)

### Describe the Solution You'd Like

use reflection to improve compatibility with Android Platform which does not support JMX extensions to get PID

**Comment by ferrirW** [comment]
Is there any more detailed of compatibility error information on Android Platform?

**Comment by mxsm** [comment]
> Is there any more detailed of compatibility error information on Android Platform?

The ManagementFactory class is not available on the Android platform. [It is part of the java.lang.management API, which is used for managing and monitoring the Java VM](https://stackoverflow.com/questions/12462215/managementfactory-from-java-lang-management-in-android)[](https://stackoverflow.com/questions/12462215/managementfactory-from-java-lang-management-in-android)[](https://stackoverflow.com/questions/19595814/android-add-java-lang-management-api). [Android’s Dalvik VM is not a Java VM](https://stackoverflow.com/questions/19595814/android-add-java-lang-management-api)[](https://stackoverflow.com/questions/19595814/android-add-java-lang-management-api)

**Comment by caigy** [comment]
Did you run RocketMQ client in Android?

**Comment by ni-ze** [comment]
could I ask what is the scene to be used？

**Comment by mxsm** [comment]
> could I ask what is the scene to be used？

To collect logs from some Android apps and send them to the server in a simple way without having to build an entire logging platform. Using MQ is a good choice at this time, and the client can directly integrate Rocketmq’s Client to achieve this. Most companies have existing MQ services.

**Comment by mxsm** [comment]
> Did you run RocketMQ client in Android?

@caigy Send some log information from Android apps through Rocketmq’s Client.

**Comment by caigy** [comment]
@caigy Generally it may be more appropriate to use `rocketmq-mqtt` in mobile devices so that you can use more lightweight mqtt clients. Furthermore, RokcetMQ Nameserver may not handle tons of connections from mobile devices.

**Comment by mxsm** [comment]
> @caigy Generally it may be more appropriate to use `rocketmq-mqtt` in mobile devices so that you can use more lightweight mqtt clients. Furthermore, RokcetMQ Nameserver may not handle tons of connections from mobile devices.

It is definitely not possible to use the client directly in a production environment. At the time, I encountered this problem again and submitted this PR to fix it for better compatibility.
