### ISSUE TITLE
[Enhancement] Unused Code

### ISSUE THREAD

**Issue by nikam14** [apache/rocketmq#6684]
### Before Creating the Enhancement Request

- [x] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

location - acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
line - 147
screenshot - 
![rocketmq](https://user-images.githubusercontent.com/55378196/235850429-2f821aa5-3a4d-4602-b8bd-b078ae43c672.PNG)
this code not used or unnecessary . 

### Motivation

to improve code quality

### Describe the Solution You'd Like
remove the if block.

### Describe Alternatives You've Considered
no alternatives

### Additional Context
no  additional context

**Comment by mxsm** [comment]
@nikam14  welcome submit a pr to fix it
