### ISSUE TITLE
Remove ClientManageProcessor#heartBeat repeat judgment

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#6686]
### Before Creating the Enhancement Request

- [x] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

![image](https://user-images.githubusercontent.com/15797831/235952505-a795391b-c1bf-4191-bf4c-16665fba0d8d.png)
Repeat judgment

### Motivation

Remove repeat judgment

### Describe the Solution You'd Like

Remove repeat judgment

### Describe Alternatives You've Considered

Remove repeat judgment

### Additional Context

no more

**Comment by imzs** [comment]
Great. It's not only about repetitive judgement, this can reduce useless cpu & mem usage.
