### ISSUE TITLE
ConcurrentModificationException occurred when querying producer connection list

### ISSUE THREAD

**Issue by wqliang** [apache/rocketmq#670]
I got a ConcurrentModificationException when querying producer connection list by tools. 
ProducerManage.getGroupChannelTable() clones a new copy of groupChannelTable, in which the key is group name and the value is a HashMap. (see link 1) The values in the result HashMap are still the same reference of HashMap in "groupChannelTable". While retrieving the result HashMap, there may be a ConcurrentModificationException when the original groupChannelTable changes at the same time. (see link 2)

link 1: https://github.com/apache/rocketmq/blob/795eae6f44587eaaf770571160a604a953fa8716/broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java#L56

link 2:
https://github.com/apache/rocketmq/blob/d4d02b5e017ebf8c7d3405516264645280cf57fa/broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java#L631

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
query the producer connection list by tools while there is producer-client disconnecting or new producer connecting.

- What did you see instead?
ConcurrentModificationException occurred

2. Please tell us about your environment:
rocketmq-4.3.0

**Comment by zongtanghu** [comment]
This issue has already been resolved by the link: https://github.com/apache/rocketmq/pull/1412
