### ISSUE TITLE
ProcessQueue class cleanExpiredMsg method 

### ISSUE THREAD

**Issue by zangyk** [apache/rocketmq#674]
ProcessQueue class cleanExpiredMsg method, MessageAccessor.getConsumeStartTimeStamp maybe return null，Long.parseLong() will throw exception

**Comment by ymwneu** [comment]
I think you are right. But it only occur in extreme condition, and has no effect on other logic. If you are interest in this, i suggest you propose a PR to optimize it.

**Comment by ShannonDing** [comment]
close due to time too long.
