### ISSUE TITLE
ConsumeMessageConcurrentlyService ConsumeThreadNum question

### ISSUE THREAD

**Issue by zangyk** [apache/rocketmq#675]
this.consumeRequestQueue = new LinkedBlockingQueue<Runnable>();

  this.consumeExecutor = new ThreadPoolExecutor(
            this.defaultMQPushConsumer.getConsumeThreadMin(),
            this.defaultMQPushConsumer.getConsumeThreadMax(),
            1000 * 60,
            TimeUnit.MILLISECONDS,
            this.consumeRequestQueue,
            new ThreadFactoryImpl("ConsumeMessageThread_"));
consumeRequestQueue 是 LinkedBlockingQueue,  设置最大线程个数应该不起作用。

**Comment by ShannonDing** [comment]
close due to time too long.
