### ISSUE TITLE
spring  DefaultRMQConsumer bind  more topic ，the listeners consumed model is concurrence or  serial？

### ISSUE THREAD

**Issue by sky-syk** [apache/rocketmq#676]
![image](https://user-images.githubusercontent.com/18712087/50889537-2cdbca00-1433-11e9-9d03-51a9bc2355dc.png)
topicBind1 and topicBind2 listeners is concurrence or  serial？

**Comment by vongosling** [comment]
@sky-syk It depends on your bean implementation. BTW, we have released the spring boot starter for RocketMQ, I would like to recommend to use it. https://github.com/apache/rocketmq-spring
