### ISSUE TITLE
[Bug] isEnableBatchPush can not be changed since the setter name is wrong

### ISSUE THREAD

**Issue by absolute8511** [apache/rocketmq#6800]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

4.9.x 

### Describe the Bug

isEnableBatchPush can not be changed since the setter name is wrong

### Steps to Reproduce

1. add `isEnableBatchPush=true` in the broker.properties config
2. use `enableDLegerCommitLog=true`
3. saw batch push is not enabled in dledger mode and the var isEnableBatchPush in MessageStoreConfig  still false

using test to reproducer
```Java
@Test
    public void testBrokerControllerConfigInit() throws Exception {
        Properties properties = new Properties();
        properties.setProperty("isEnableBatchPush", "true");
        MessageStoreConfig messageStoreConfig = new MessageStoreConfig();
        MixAll.properties2Object(properties, messageStoreConfig);
        assertThat(messageStoreConfig.isEnableBatchPush()).isTrue();
    }

```

### What Did You Expect to See?

isEnableBatchPush should be changed after set  `isEnableBatchPush=true` in the broker.properties config

### What Did You See Instead?

isEnableBatchPush did not change in the MessageStoreConfig

**Comment by cserwen** [comment]
Actually, set `enableBatchPush` as true can work.
