### ISSUE TITLE
The file retention duration configuration field and source code of the broker on the official website are inconsistent

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6802]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

5.0.0

### JDK Version

1.8

### Describe the Bug

![4af2b86e35e65248b56e333175e28271](https://github.com/apache/rocketmq/assets/35131874/95f37448-dc18-43ce-847c-7ff307f97532)
![465ce2b9d5604e978c12237d97818062](https://github.com/apache/rocketmq/assets/35131874/6d74b4e0-fb0e-4915-adb1-0c64e000693a)

The file retention duration configuration field and source code of the broker on the official website are inconsistent

### Steps to Reproduce

View the source code and official website

### What Did You Expect to See?

Modify the configuration fields on the official website

### What Did You See Instead?

The file retention duration configuration field and source code of the broker on the official website are inconsistent

**Comment by sherlock-lin** [comment]
I think the "fileReservedTime" in the source code is correct, while the "fileReserverdTime" in the documentation is wrong and should be fixed for the documentation,Please provide the address of the document

**Comment by fengcharly** [comment]
> I think the "fileReservedTime" in the source code is correct, while the "fileReserverdTime" in the documentation is wrong and should be fixed for the documentation,Please provide the address of the document

https://rocketmq.apache.org/zh/docs/bestPractice/01bestpractice/#broker-%E9%85%8D%E7%BD%AE

**Comment by RongtongJin** [comment]
Fixed in https://github.com/apache/rocketmq-site/pull/562
