### ISSUE TITLE
[Bug] BrokerHeartbeatExecutorService ExecutorService name error

### ISSUE THREAD

**Issue by xiaochangbai** [apache/rocketmq#6819]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

mac m2

### RocketMQ version

laster

### JDK Version

jdk11

### Describe the Bug

<img width="1021" alt="image" src="https://github.com/apache/rocketmq/assets/38645977/cc5bfa9e-f69c-4e09-b642-6a3dd1f4561a">

### Steps to Reproduce

<img width="1021" alt="image" src="https://github.com/apache/rocketmq/assets/38645977/cc5bfa9e-f69c-4e09-b642-6a3dd1f4561a">

### What Did You Expect to See?

<img width="1021" alt="image" src="https://github.com/apache/rocketmq/assets/38645977/cc5bfa9e-f69c-4e09-b642-6a3dd1f4561a">

### What Did You See Instead?

<img width="1021" alt="image" src="https://github.com/apache/rocketmq/assets/38645977/cc5bfa9e-f69c-4e09-b642-6a3dd1f4561a">

**Comment by Oliverwqcwrw** [comment]
Close as merged
