### ISSUE TITLE
isolateLogEnable can't work in Local Proxy Mode

### ISSUE THREAD

**Issue by francisoliverlee** [apache/rocketmq#6854]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos 7

### RocketMQ version

rocketmq 5.1.0

### JDK Version

open jdk 8

### Describe the Bug

isolateLogEnable = true, this would separate broker logs with in BrokerStartup.java
```
System.setProperty("brokerLogDir", brokerConfig.getBrokerName() + "_" + brokerConfig.getBrokerId());
```

but in Local Proxy Mode, proxy start broker without exec those codes

### Steps to Reproduce

nohup sh bin/mqbroker -c conf/broker1.conf -pc conf/rmq-proxy1.json --enable-proxy > proxy1.out &
nohup sh bin/mqbroker -c conf/broker2.conf -pc conf/rmq-proxy2.json --enable-proxy > proxy2.out &

start 2 proxy with broker,  check the brokers dir

### What Did You Expect to See?

every broker has its own log dir

### What Did You See Instead?

brokerLogDir_IS_UNDEFINED

**Comment by drpmma** [comment]
> ```
> System.setProperty("brokerLogDir", brokerConfig.getBrokerName() + "_" + brokerConfig.getBrokerId());
> ```

This code should be executed in org.apache.rocketmq.proxy.ProxyStartup#createBrokerController

![image](https://github.com/apache/rocketmq/assets/20906038/113b58bf-bf4f-457f-b7af-fe85cec6cab8)

**Comment by drpmma** [comment]
Close for no more replay or comments, please feel free to reopen it if you have any other thoughts.
