### ISSUE TITLE
Delete unmeaningful code MessageDecoder.decodeMessageId(msgId); as the code-optimization

### ISSUE THREAD

**Issue by xiangwangcheng** [apache/rocketmq#687]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

Upon on the tools module, the method DefaultMQAdminExtImpl#viewMessage(String topic, String msgId)  (code below)

```
    @Override
    public MessageExt viewMessage(String topic,
        String msgId) throws RemotingException, MQBrokerException, InterruptedException, MQClientException {
        try {
            MessageDecoder.decodeMessageId(msgId);
            return this.viewMessage(msgId);
        } catch (Exception e) {
            log.warn("the msgId maybe created by new client. msgId={}", msgId, e);
        }
        return this.mqClientInstance.getMQAdminImpl().queryMessageByUniqKey(topic, msgId);
    }
```

I dont see any meaning of _MessageDecoder.decodeMessageId(msgId);_. No variables used to receive the returning values. And the following codes in MQAdminImpl#viewMessage(String msgId) does process the code 
`messageId = MessageDecoder.decodeMessageId(msgId);`

So I think it can be deleted as the code-optimization .

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by lemonzone2010** [comment]
MessageDecoder.decodeMessageId(msgId)  just checks msgId format. If no exception, msgId is just messageId format.Message will be queried by `this.viewMessage(msgId)`. Otherwise it's UniqKey and message will be queried by `queryMessageByUniqKey(topic, msgId)`

**Comment by xiangwangcheng** [comment]
@lemonzone2010  Yeah, I understand what you said. But `messageId = MessageDecoder.decodeMessageId(msgId);` is also invoked inside `this.viewMessage(msgId)` method:

 ```
   public MessageExt viewMessage(
        String msgId) throws RemotingException, MQBrokerException, InterruptedException, MQClientException {

        MessageId messageId = null;
        try {
            messageId = MessageDecoder.decodeMessageId(msgId);
        } catch (Exception e) {
            throw new MQClientException(ResponseCode.NO_MESSAGE, "query message by id finished, but no message.");
        }
        return this.mQClientFactory.getMQClientAPIImpl().viewMessage(RemotingUtil.socketAddress2String(messageId.getAddress()),
            messageId.getOffset(), timeoutMillis);
    }
```
So, I still think it is redundant.

**Comment by xiangwangcheng** [comment]
@lemonzone2010  Just delete the code `MessageDecoder.decodeMessageId(msgId);`. 
I will submit a PR.
