### ISSUE TITLE
[Bug] ConcurrentHashMapUtils fails to solve the loop bug in JDK8.

### ISSUE THREAD

**Issue by leeyiyu** [apache/rocketmq#6879]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Mac  OS 13.0

### RocketMQ version

branch: (develop|tag 5.1.1) version: 5.1.1

### JDK Version

jdk8

### Describe the Bug

[ConcurrentHashMapUtils](https://github.com/apache/rocketmq/blob/develop/common/src/main/java/org/apache/rocketmq/common/utils/ConcurrentHashMapUtils.java) 中提供的computeIfAbsent方法没有解决jdk8的循环问题，复现代码如下

```
@Test
    public void computeIfAbsent() {
        ConcurrentHashMap<String, String> map = new ConcurrentHashMap<>();
//        map.computeIfAbsent("AaAa", key->map.computeIfAbsent("BBBB",key2->"42"));
        ConcurrentHashMapUtils.computeIfAbsent(map, "AaAa", key -> map.computeIfAbsent("BBBB", key2 -> "42"));
    }
```

**Comment by dingshuangxi888** [comment]
I understand that it's not necessary to use it that way, and there aren't any use cases for it currently.
