### ISSUE TITLE
MappedFileQueue load may cause the large file blank

### ISSUE THREAD

**Issue by Ah39** [apache/rocketmq#688]
https://github.com/apache/rocketmq/blob/2b692c912d18c0f9889fd73358581bcccf37bbbe/store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java#L147-L177

**load function , setWrotePosition and setCommittedPosition set the mappedFileSize .
but last write , wrotePosition may smaller than mappedFileSize**

**if fileChannel.map 64k , but only write 100 byte , the file length is 64k , and the wrotePosition and commitedPosition not 100 , but is 64k**

**Comment by jacky1193610322** [comment]
会在recover函数里面进行修复的

**Comment by Ah39** [comment]
but it is not a good design . what if recover dont work right , may cause the message loss

**Comment by jacky1193610322** [comment]
> but it is not a good design . what if recover dont work right , may cause the message loss

如果是这样就是个bug了，但是我们讨论的前提是没有bug，要不然讨论就没有意义了，recover，并没有改变文件的大小，只是修正接下来要准备写入的位置，整个文件还是那么大，只不过是从中间开始写

**Comment by Ah39** [comment]
need a checkpoint  save the commited offset , when next start can recovery from the checkpoint offset . Increase the restart speed with a lot of  consumer queue file .

**Comment by jacky1193610322** [comment]
checkpoint已经有了

**Comment by jacky1193610322** [comment]
如果每个topic的consume queue都保存offset的话, 那么1万个topic,每个topic假设4个队列,那么需要至少4万个long, 那么这部分的写肯定是随机写了，这样有可能会影响性能，并且现在的正常情况下扫描文件，大部分情况是为了预热,当然也有文件校验的设计在里面。

**Comment by jacky1193610322** [comment]
你说的先放在内存，然后定时刷盘，从技术上是可以的，反正已经有了很多元数据的刷盘，多一个也是没有问题的，我认为，我说的随机写，是指如果还是用mmap的方式来更新，至于scan耗时的问题，如果不在启动的时候读进来，那么就会在真正发送和消费消息的时候去读，那么假如在scan的过程中需要发10分钟，那么读取的总时间还是10分钟，那么在发送和消费消息的时候，这10分钟就会散落在发送和消费消息的过程中，那么就会造成消息有波动，所以我认为提前预热是可以的，但是也许把恢复和预热分开，这样设计会更好。

**Comment by jacky1193610322** [comment]
如果保存了每个concume queue的offset，那么这个offset还是不一定能用，因为consume offset最终还是要索引到commitlog,假如commitlog 没有对应的数据，那么consume queue保存的这个offset也没有意义，所以最终就算有了这个offset，还是要根据commitlog来修复一遍，因为他们不是一起刷盘的。

**Comment by Ah39** [comment]
you dont undstand , when shutdown normally , dont need with scan when next start . 
Commit log have a dispatch offset , consumer queue have a offset for write position . 

commit log ( commited_offset itself ,dispatch_success_offset )
consumer queue ( commited_offet itself )

**Comment by ShannonDing** [comment]
close due to time too long,  any questions you can reopen it again.
