### ISSUE TITLE
[Enhancement] DefaultHeartBeatSyncerTopic should as system topic.

### ISSUE THREAD

**Issue by echooymxq** [apache/rocketmq#6886]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

This topic will be use notify the consumer register or unregister event on proxy. As a important communication mechanisms within the Proxy, we shouldn't expose it.

### Motivation

<img width="1919" alt="image" src="https://github.com/apache/rocketmq/assets/19860963/4cd2c479-acc4-458f-adb2-2b50cf0188a3">

<img width="1912" alt="image" src="https://github.com/apache/rocketmq/assets/19860963/f3e61def-7c31-439d-95ea-2fd4a318d39c">

### Describe the Solution You'd Like

1. Rename the topic name, and add to the system topic.
2. Remove the proxy heartbeatSyncerTopicName config option.

### Describe Alternatives You've Considered

No

**Comment by drpmma** [comment]
The broker has a validation about system topic creation and the proxy cannot create system topic by default. So it's designed to be a user topic.

See org.apache.rocketmq.common.BrokerConfig#validateSystemTopicWhenUpdateTopic

**Comment by echooymxq** [comment]
@drpmma I see, about the topic as a user topic, i am a little refuse, How about we adding a list of system topics that are will be not validated.

**Comment by drpmma** [comment]
> @drpmma I see, but about the topic as a user topic, i am a little refuse, How about we adding a list of system topics that are will be not validated.

The semantics of the "system topic" have actually changed here. Previously, "system topics" were limited to the Broker itself. However, the introduction of the Proxy has brought about a need for external system creation. It may be beneficial to associate the behavior of creating and modifying system topics with ACL.
