### ISSUE TITLE
Method DLedgerCommitLog.putMessages(MessageExtBatch) not implemented

### ISSUE THREAD

**Issue by gchaoxue** [apache/rocketmq#690]
Method `org.apache.rocketmq.store.dledger.DLedgerCommitLog.putMessages(MessageExtBatch)` is not implemented.

I built the new dledger-implemented rocketmq from branch _store_with_dledger_ and wanted to try the new HA solution. But the client keeps getting "**MQBrokerException: CODE: 13  DESC: the message is illegal**" when I try to send a batch of messages. After debugging and making sure that there is nothing wrong with the client code, I read the server-side code and found that the batch-message putting method of `DledgerCommitLog` is under development and it is returning error code of `MESSAGE_ILLEGAL`.

```
package org.apache.rocketmq.store.dledger;

public class DLedgerCommitLog extends CommitLog {
    @Override
    public PutMessageResult putMessages(final MessageExtBatch messageExtBatch) {
        return new PutMessageResult(PutMessageStatus.MESSAGE_ILLEGAL, null);
    }
}
```

**Comment by yufeng629** [comment]
i meet the same  problem，when will support this future @vongosling

**Comment by wendyxiao** [comment]
I meet the same problem,when will support this future @vongosling   , thanks ~

**Comment by TerrellChen** [comment]
I've done this.
This feature relies on dledger, and the PR has been submited.

https://github.com/openmessaging/openmessaging-storage-dledger/issues/64

**Comment by RongtongJin** [comment]
> I've done this.
> This feature relies on dledger, and the PR has been submited.
> 
> [openmessaging/openmessaging-storage-dledger#64](https://github.com/openmessaging/openmessaging-storage-dledger/issues/64)

Hi @TerrellChen  I will review the pr ASAP.

**Comment by scvzerng** [comment]
i meet the same problem，when will support this future @RongtongJin
