### ISSUE TITLE
Sometimes failure to delete commitlog when run test case in DefaultMessageStoreTest

### ISSUE THREAD

**Issue by maxiaoguang64** [apache/rocketmq#691]
![tim 20190116141111](https://user-images.githubusercontent.com/6637227/51229802-9eb69500-1998-11e9-8181-7e40a8920193.png)

**Comment by duhenglucky** [comment]
@maxiaoguang64 Could you please submit a PR to fix it？

**Comment by maxiaoguang64** [comment]
@duhenglucky Yes, I will.

**Comment by liangyuanpeng** [comment]
Is  solved?

**Comment by maxiaoguang64** [comment]
no, is a long time no response!
