### ISSUE TITLE
[Enhancement] Extract the interval of fetchNameServerAddr

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq#6910]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

The task of the Broker to discover the NameServer is performed by BrokerOuterAPI#fetchNameServerAddr at an interval of 2 minutes. The registration interval in BrokerController#registerBrokerAll is 10 seconds. 

If the address of the NameServer changes, the Broker may not be able to discover the new NameServer and register with it in a timely manner. It is suggested to extract the interval of fetchNameServerAddr as a parameter for the Broker.

### Motivation

The task of the Broker to discover the NameServer is performed by BrokerOuterAPI#fetchNameServerAddr at an interval of 2 minutes. The registration interval in BrokerController#registerBrokerAll is 10 seconds.

### Describe the Solution You'd Like

 It is suggested to extract the interval of fetchNameServerAddr as a parameter for the Broker.

### Describe Alternatives You've Considered

None

**Comment by totalo** [comment]
hi i want to do this. thx

**Comment by lizhimins** [comment]
Suggest set default interval to 10 secones like registerBrokerAll()

**Comment by WindSearcher** [comment]
can i try it？
