### ISSUE TITLE
[Bug] Proxy Set CUSTER Mode - Consumer Group Not Online

### ISSUE THREAD

**Issue by Magician-Sun** [apache/rocketmq#6950]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos 7.9

### RocketMQ version

branch: rocketmq-5.1.1
commit e244ebb

### JDK Version

java version "1.8.0_261"

### Describe the Bug

Proxy Set CUSTER Mode
The consumer connects to the proxy for consumption, and the dashboard displays an abnormal message: CODE: 206 DESC: the consumer group [test] not online

### Steps to Reproduce

Deploying a controller cluster
Proxy Set CUSTER Mode
Consumer end consumes through proxy

### What Did You Expect to See?

trackType  ： CONSUMED

### What Did You See Instead?

trackType  ： NOT_ONLINE
CODE:206 DESC:the consumer group[test] not online

**Comment by zzc1989wz** [comment]
cause dashboard request broker to query its empty consumerTable when clients sync the consumerGroup info to consumerTable in proxy by heartbeat method
