### ISSUE TITLE
[Bug] Pop Message can not support ROCKETMQ serialize type

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq#6953]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

mac

### RocketMQ version

5.x

### Describe the Bug

<img width="961" alt="image" src="https://github.com/apache/rocketmq/assets/2684384/ee95fb59-e4da-4ff7-814a-837ec307906e">

```
    public static final int POP_MESSAGE = 200050;
    public static final int ACK_MESSAGE = 200051;
    public static final int PEEK_MESSAGE = 200052;
    public static final int CHANGE_MESSAGE_INVISIBLETIME = 200053;
    public static final int NOTIFICATION = 200054;
    public static final int POLLING_INFO = 200055;
```

After getting the pop, the code of this command became too large. For example, pop message 200050 would be converted to 3442.

Switching from JSON to RocketMQ's own protocol for ROCKETMQ_SERIALIZE_TYPE=ROCKETMQ becomes useless.

### Steps to Reproduce

set ROCKETMQ_SERIALIZE_TYPE=ROCKETMQ

then run pop message

### What Did You Expect to See?

right

### What Did You See Instead?

org.apache.rocketmq.client.exception.MQBrokerException: CODE: 3  DESC:  request type 3442 not supported

### Additional Context

no

**Comment by lizhimins** [comment]
In theory, a good transport layer should not care about communication protocol, and they should be flexible and interchangeable. I suggest abandoning rocketmq serialization.
