### ISSUE TITLE
[Doc] docs/cn/operation.md Format problem

### ISSUE THREAD

**Issue by wanyaoasiainfo** [apache/rocketmq#6962]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

docs/cn/operation.md Format problem

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mxsm** [comment]
@wanyaoasiainfo  Welcome submit pr to fix
