### ISSUE TITLE
[Doc] The field name in the Prometheus exporter parameter description in the observable section of the Apache RocketMQ document is incorrect

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6966]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

The field name in the Prometheus exporter parameter description in the observable section of the Apache RocketMQ document is incorrect,As follows.
MetricGrpcExporterTimeOutInMills should be changed to metricsPromExporterHost:
![image](https://github.com/apache/rocketmq/assets/35131874/7d22af54-b239-488c-94c9-c05b46cf99e4)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xdkxlk** [comment]
Please create this issue in [apache/rocketmq-site](https://github.com/apache/rocketmq-site).

**Comment by fengcharly** [comment]
> Please create this issue in [apache/rocketmq-site](https://github.com/apache/rocketmq-site).

ok
