### ISSUE TITLE
[Bug] pull message result maybe data wrong

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq#6979]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

4.9.7 sdk  push consumer + 5.0.0 proxy+5.0.0 broker

### RocketMQ version

4.9.7 sdk  push consumer + 5.0.0 proxy+5.0.0 broker

### JDK Version

1.8

### Describe the Bug

client log

```
2023-06-30 19:43:57,910 WARN RocketmqClient - [BUG] pull message result maybe data wrong, nextBeginOffset: 2947 firstMsgOffset: 9223372036854775807 prevRequestOffset: 2954
```

proxy log, which I added in org.apache.rocketmq.proxy.remoting.activity.PullMessageActivity
```
13086:2023-06-30 19:43:57 INFO NettyClientWorkerThread_1 - pull offset monitor,clientHost=10.0.0.3:35702,topic=test,group=x,bname=broker-1-1,queueId=2,queueOffset=2949,commitOffset=2946,maxOffset=2952,nextBeginOffset=2952
13093:2023-06-30 19:43:57 INFO NettyClientWorkerThread_1 - pull offset monitor,clientHost=10.0.0.3:35702,topic=test,group=x,bname=broker-1-1,queueId=2,queueOffset=2954,commitOffset=2954,maxOffset=2947,nextBeginOffset=2947
13095:2023-06-30 19:43:57 INFO NettyClientWorkerThread_2 - pull offset monitor,clientHost=10.0.0.3:35702,topic=test,group=x,bname=broker-1-1,queueId=2,queueOffset=2947,commitOffset=2954,maxOffset=2954,nextBeginOffset=2954
```

I print responseHeader.getMaxOffset(),just take a look ,the. maxOffset

In a very short period of time, it is not possible for the maxOffset to be smaller than the previous one. The disk is not exceeding the limit, nor is there any penalty for cleaning.

### Steps to Reproduce

just run normal case long time

### What Did You Expect to See?

no

### What Did You See Instead?

maxOffset smaller than before

### Additional Context

fix

<img width="798" alt="image" src="https://github.com/apache/rocketmq/assets/2684384/937d33cb-3f6f-4b2c-94df-70393fe3baef">

_No response_

**Comment by ferrirW** [comment]
Wouldn't it be more reasonable to modify the map so that it won't be overwritten?
