### ISSUE TITLE
[Feature] sync ProducerManager state for proxy & producer conncetion command

### ISSUE THREAD

**Issue by lyx2000** [apache/rocketmq#6980]
### Is Your Feature Request Related to a Problem?

In RocketMQ 5.0, we have `HeartbeatSyncer` to sync the state in `ConsumerManager`, like connection, client sub etc. Thus we can get all consumer connection in the cluster only from a single proxy. However, the `ProducerManager` does not have the boardcast sync mechanism, which means the state in `ProducerManager` is separate from other proxy. 
Not only that, in RocketMQ 5.0, we cancelled the concept producer group, causing problems for users when they want to figure out the Producer connection of a certaion topic.

### Describe the Solution You'd Like

Add boardcast sync mechanism for `ProducerManager`.
Add two requestcode and other method & command
GET_PRODUCER_CONNECTION_LIST_BY_TOPIC = 330;
QUERY_TOPIC_PRODUCE_BY_WHO = 331;

### Describe Alternatives You've Considered

-

### Additional Context

-

**Comment by tobehardest** [comment]
I want to do this, can you assign it to me？
