### ISSUE TITLE
2n-2m-2s-sync

### ISSUE THREAD

**Issue by lihanfeng1024** [apache/rocketmq#6986]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

linux redhat 8.4

### RocketMQ version

5.1.3

### JDK Version

jdk8

### Describe the Bug

Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: Can't modify topic or subscription group from slave broker, please execute it from master broker.

### Steps to Reproduce

内网搭建，无法提供环境

### What Did You Expect to See?

怎么解决

### What Did You See Instead?

Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: Can't modify topic or subscription group from slave broker, please execute it from master broker.

**Comment by RongtongJin** [comment]
> ### Before Creating the Bug Report
> * [x]  I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).
> * [x]  I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.
> * [x]  I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.
> 
> ### Runtime platform environment
> linux redhat 8.4
> 
> ### RocketMQ version
> 5.1.3
> 
> ### JDK Version
> jdk8
> 
> ### Describe the Bug
> Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1 DESC: Can't modify topic or subscription group from slave broker, please execute it from master broker.
> 
> ### Steps to Reproduce
> 内网搭建，无法提供环境
> 
> ### What Did You Expect to See?
> 怎么解决
> 
> ### What Did You See Instead?
> Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1 DESC: Can't modify topic or subscription group from slave broker, please execute it from master broker.
> 
> ### Additional Context
> _No response_

更新topic或订阅组似乎请求到了slave broker。clsuterList命令执行结果是什么

**Comment by RongtongJin** [comment]
此外，建议类似问题先去https://github.com/apache/rocketmq/discussions提问

**Comment by huxiyu** [comment]
看下是否有broker的master的服务挂了或这台网络不通
