### ISSUE TITLE
[Bug] RocketMQ's docker container, version 5.1.3 starts with no permission error

### ISSUE THREAD

**Issue by gzvincen** [apache/rocketmq#6995]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

macOS Monterey  12.3.1 (21E258)
2.3 GHz 八核Intel Core i9

### RocketMQ version

5.1.3

### JDK Version

https://hub.docker.com/layers/apache/rocketmq/5.1.3/images/sha256-5db5b9a59a009c4f4f617fff946cb8479c0b1e3e71c3fe7217eaeb97690d3519?context=explore

### Describe the Bug

https://hub.docker.com/layers/apache/rocketmq/5.1.3/images/sha256-5db5b9a59a009c4f4f617fff946cb8479c0b1e3e71c3fe7217eaeb97690d3519?context=explore
RocketMQ's docker container, version 5.1.3 starts with no permission error.
error msg: docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./docker-entrypoint.sh": permission denied: unknown.

My guess is that the user does not have execution permission on the file， need to change the following code in the dockerfile: ENTRYPOINT ["./docker-entrypoint.sh"]

### Steps to Reproduce

just run the rocketmq docker container: docker run -it --net=host apache/rocketmq:5.1.3 ./mqnamesrv

### What Did You Expect to See?

The rocketmq container runs successfully

### What Did You See Instead?

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./docker-entrypoint.sh": permission denied: unknown.

### Additional Context

test

**Comment by DongyuanPan** [comment]
Yes, the docker image has bugs, the docker file has some errors
fix in https://github.com/apache/rocketmq-docker/pull/84
