### ISSUE TITLE
客户端连接 k8s rocketmq 集群问题

### ISSUE THREAD

**Issue by super-lzb** [apache/rocketmq#6998]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

OS：("CentOS 7.9.2009")

### RocketMQ version

4.9.7

### JDK Version

1.8

### Describe the Bug

k8s 自定义镜像部署 rocketmq 集群，把 namesrv:9876 暴露出去，但是 namesrv 返回的 broker ip 是 k8s 集群内ip，外部客户端可以连接 namesrv，但是发送消息不成功：org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [9024]ms, Topic: test, BrokersSent: [broker-b, broker-b, broker-b]

### Steps to Reproduce

1. producer.setNamesrvAddr("${宿主机ip}:${k8s暴露的namesrv端口}") 
2. java 客户端访问 k8s 内部mq集群，连接正常但是发送消息时报错：org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [9024]ms, Topic: test, BrokersSent: [broker-b, broker-b, broker-b]

### What Did You Expect to See?

希望可以通过外部客户端访问 k8s 集群内 namesrv 并可以成功发送消息到 broker

### What Did You See Instead?

无

### Additional Context

无

**Comment by RongtongJin** [comment]
1.利用5.x proxy方式，可以只对外暴露proxy接入点
2.如果用4.x nameserver的方式，需要有能力从外面连接到broker，可以采用node ip方式

**Comment by RongtongJin** [comment]
此外，由于这类问题不属于bug，建议先去[Github Discussion](https://github.com/apache/rocketmq/discussions)讨论。
