### ISSUE TITLE
Potential Concurrent Risk in RouteInfoManager

### ISSUE THREAD

**Issue by ZhangShenao** [apache/rocketmq#700]
The method scanNotActiveBroker() in RouteInfoManager : 
`
public void scanNotActiveBroker() {
        Iterator<Entry<String, BrokerLiveInfo>> it = this.brokerLiveTable.entrySet().iterator();
        while (it.hasNext()) {
            Entry<String, BrokerLiveInfo> next = it.next();
            long last = next.getValue().getLastUpdateTimestamp();
            if ((last + BROKER_CHANNEL_EXPIRED_TIME) < System.currentTimeMillis()) {
                RemotingUtil.closeChannel(next.getValue().getChannel());
                it.remove();
                log.warn("The broker channel expired, {} {}ms", next.getKey(), BROKER_CHANNEL_EXPIRED_TIME);
                this.onChannelDestroy(next.getKey(), next.getValue().getChannel());
            }
        }
    }` 
Is there any Concurrent Risk when it.remove() without lock?

**Comment by zhhlovely** [comment]
修改不会报错，如果是新增或者删除的话，这个迭代会报错。 这里不加锁很大的原因在于10S执行一次很频繁的，如果这个时候真的有添加的话报错的话也没事儿。我感觉应该更多的考虑是扫描发现不可用的概率非常低。

**Comment by ZhangShenao** [comment]
这里是否可以考虑使用ConcurrentHashMap?

**Comment by ZhangShenao** [comment]
> 修改不会报错，如果是新增或者删除的话，这个迭代会报错。 这里不加锁很大的原因在于10S执行一次很频繁的，如果这个时候真的有添加的话报错的话也没事儿。我感觉应该更多的考虑是扫描发现不可用的概率非常低。

这里是否可以考虑使用ConcurrentHashMap?

**Comment by ymwneu** [comment]
迭代过程中，如果HashMap中元素有增或删，确实会直接报错，并影响下次调度。由于执行得不频繁，并且broker机器变化也不频繁，因此很少会报错。这块代码确实需要优化一下，做个try catch或者使用ConcurrentHashMap，都可以解决问题。
