### ISSUE TITLE
[Bug]Version 5.1.1, storage failure may cause message loss issues

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#7016]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

suse linux 

### RocketMQ version

5.1.1

### JDK Version

1.8

### Describe the Bug

Simulate the scenario of file system readonly, sending messages is still SEND_ OK. At this point, if a server restart is performed, it will result in message loss.

To avoid message loss, the architecture of a single node broker master cannot be used。

### Steps to Reproduce

1,Simulate the scenario of file system readonly,
2,sending messages

### What Did You Expect to See?

send message  and client can get error message when file system readonly

### What Did You See Instead?

 client can not get error message when file system readonly。

**Comment by RongtongJin** [comment]
Additionally, it is suggested to ask such questions on Github Discussion.

**Comment by iamqq23ue** [comment]
Thanks reply.My configuration is SYNC_FLUSH。I infer that it is because RocketMQ has always had this issue and did not prompt the client when there was a storage failure（The timeout of disk flushing can be detected, but the failure of disk flushing cannot be detected）.&nbsp; In version 4.9， I submitted an issue and had fixed myself, and recently tested version 5.1.1 and found that the problem still exists.




自诩天才
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月13日(星期四) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] [Bug]Version 5.1.1, storage failure may cause message loss issues (Issue #7016)





 
Additionally, it is suggested to ask such questions on Github Discussion.
