### ISSUE TITLE
[Bug]When a single computer room is isolated from the network, it may cause message loss.

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#7017]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

suse linux

### RocketMQ version

5.1.1

### JDK Version

1.8

### Describe the Bug

The architecture consists of three data centers, three brokers, one master, and two slaves. Three controllers are also one for each data center (the same as the nameserver).

Simulate the isolation of the broker master and one controller network from the brokers and controllers of the other two data centers.

During network failures, it can be observed that two broker masters will appear, and when the network is restored, the original master will become a slave.

However, messages sent to the original master during network failures will be lost.

### Steps to Reproduce

1,Simulate the isolation of the broker master and one controller network from the brokers and controllers of the other two data centers.
2,send message to the original master

### What Did You Expect to See?

Sending a message to the original master that has been quarantined should result in an error

### What Did You See Instead?

Sending a message to the original master that has been quarantined did not report an error

**Comment by RongtongJin** [comment]
Hi @iamqq23ue,  I have previously simulated a similar scenario, but it seems that this situation did not occur (assuming that allAckInSyncStateSet is enabled). This is because the SyncStateSet on the original master broker cannot be updated at this time, and messages sent to this master broker will fail to be send successfully.

**Comment by RongtongJin** [comment]
Additionally, it is suggested to ask such questions on Github Discussion.

**Comment by iamqq23ue** [comment]
Thank you for your reply. I will test it.


自诩天才
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月13日(星期四) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] [Bug]When a single computer room is isolated from the network, it may cause message loss. (Issue #7017)





 
Hi @iamqq23ue,  I have previously simulated a similar scenario, but it seems that this situation did not occur (assuming that allAckInSyncStateSet is enabled). This is because the SyncStateSet on the original master broker cannot be updated at this time, and messages sent to this master broker will fail to be send successfully.

**Comment by iamqq23ue** [comment]
hi @RongtongJin ,when allAckInSyncStateSet is true,tps will significantly decrease.
in my case,tps  dropped from 30000 to 3000.

I only have one slave.

**Comment by iamqq23ue** [comment]
The performance issue has been resolved in the latest version 5.1.3
