### ISSUE TITLE
[Bug] PoP caused broker memory leak 

### ISSUE THREAD

**Issue by fuyou001** [apache/rocketmq#7031]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

all

### RocketMQ version

all

### JDK Version

all

### Describe the Bug

all

### Steps to Reproduce

This issues is difficult to reproduce

### What Did You Expect to See?

no

### What Did You See Instead?

no

### Additional Context

no

**Comment by leizhiyuan** [comment]
Can I ask what the scenario is like?

Is it caused by the client restart, and the ck map in the server memory not being cleared? Is it because of repeated additions?
