### ISSUE TITLE
Messages become unread when one of masters stops

### ISSUE THREAD

**Issue by LuciferInLove** [apache/rocketmq#704]
Hello. I have a cluster-configured RocketMQ docker deployment. There are 3 broker sets in one cluster: 3 masters and 3 slaves with the same brokerClusterName and different brokerName for every set in configs. All masters are in SYNC mode. When I stop any master broker, messages become unread and consumers read messages again. Why does it happen?

RocketMQ version 4.3.0

**Comment by LuciferInLove** [comment]
When producer send message, I see it in all brokers, but with different MAX_OFFSET

**Comment by ShannonDing** [comment]
closed due to time too long.
