### ISSUE TITLE
WaitNotifyObject class has a wake up bug

### ISSUE THREAD

**Issue by chicc999** [apache/rocketmq#705]
As described in #287 ，

https://github.com/apache/rocketmq/blob/3d56841fcc0cb9666307396d549343379a56b45c/store/src/main/java/org/apache/rocketmq/store/ha/WaitNotifyObject.java#L64-L77

In line 70 , “value = true” can't change the value in the entry。

**Comment by hdchen** [comment]
LGTM：）
