### ISSUE TITLE
[Bug]  schedule CQ offset invalid. offset=77, cqMinOffset=0, cqMaxOffset=74, queueId=1

### ISSUE THREAD

**Issue by weihubeats** [apache/rocketmq#7077]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

mac os(linux)

### RocketMQ version

5.1.0

### JDK Version

jdk8

### Describe the Bug

2023-07-25 10:33:49 ERROR BrokerControllerScheduledThread1 - schedule CQ offset invalid. offset=77, cqMinOffset=0, cqMaxOffset=74, queueId=1
2023-07-25 10:33:50 ERROR BrokerControllerScheduledThread1 - correct delay offset [ delayLevel 2 ] from 77 to 74

in reality
![image](https://github.com/apache/rocketmq/assets/42484192/dfe19282-6e84-4f54-867d-6f13d1b8d8e7)

Offset corrections were made here
![image](https://github.com/apache/rocketmq/assets/42484192/0fb97ac3-4793-4e75-a68d-d94ed0fadedf)
But it doesn't refresh to delayOffset.json

Then re-added in the delayOffset.json file for a corrective override
![image](https://github.com/apache/rocketmq/assets/42484192/6964457e-2ef6-4d65-8f20-12779755043a)

### Steps to Reproduce

1. star broker slave
2. delete store file

### What Did You Expect to See?

no error

### What Did You See Instead?

error
2023-07-25 10:33:49 ERROR BrokerControllerScheduledThread1 - schedule CQ offset invalid. offset=77, cqMinOffset=0, cqMaxOffset=74, queueId=1
2023-07-25 10:33:50 ERROR BrokerControllerScheduledThread1 - correct delay offset [ delayLevel 2 ] from 77 to 74

**Comment by RongtongJin** [comment]
why delayOffset.json will reload? It seems that the two images are duplicated

**Comment by weihubeats** [comment]
This is because SlaveSynchronize calls syncDelayOffset to synchronise delayed messages.
![image](https://github.com/apache/rocketmq/assets/42484192/657cd810-1fe4-422a-9554-9a0eb0960fff)

![image](https://github.com/apache/rocketmq/assets/42484192/b78de66b-3b99-443a-b88f-906eb9492753)

**Comment by RongtongJin** [comment]
@weihubeats Good catch! I don't think the slave broker should fix the delayOffset, which also leads to many error logs being printed.

**Comment by RongtongJin** [comment]
@weihubeats Are you interested in fixing it?

**Comment by weihubeats** [comment]
Sure, I'll try to fix a version of it and ask for your help then!

**Comment by SchopenhauerZhang** [comment]
catch it
