### ISSUE TITLE
[Bug] It was found that the rocketmq broker node will generate a new port based on the port listen listening on by minus 2, which cannot be customized.

### ISSUE THREAD

**Issue by Cairry** [apache/rocketmq#7083]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

docker

### RocketMQ version

4.9.3

### Describe the Bug

It was found that the rocketmq broker node will generate a new port based on the port listen listening on by minus 2, which cannot be customized.

### Steps to Reproduce

Specify a port at will, such as: 30910, then the broker node will generate a port such as 30908, what is this port used for? How to modify

### What Did You Expect to See?

I would like to customize this port

### What Did You See Instead?

Specify a port at will, such as: 30910, then the broker node will generate a port such as 30908, what is this port used for? How to modify

### Additional Context

<img width="747" alt="image" src="https://github.com/apache/rocketmq/assets/115769353/1f46d024-cbf7-48dd-869b-7d0c9f980bd4">

**Comment by onejimmyboy** [comment]
单机版的rocketmq，启动的时候也会生成3个端口，默认是10909 10911 10912，每个端口有不同的含义，

**Comment by Cairry** [comment]
你好：
&nbsp; &nbsp; &nbsp; 还有一个问题，rocketmq dledger 新扩容的broker组无法生产消息和处理消息，各项配置都是OK。
如果我是新部署的集群，并且该集群没有生产过消息，是个纯净的集群。当我扩容新的broker组后，开始生产消息，新的组是可以生产消息和处理消息。
版本：4.9.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/rocketmq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/rocketmq] [Bug] It was found that the rocketmq broker node will generate a new port based on the port listen listening on by minus 2, which cannot be customized. (Issue #7083)





 
单机版的rocketmq，启动的时候也会生成3个端口，默认是10909 10911 10912，每个端口有不同的含义，
