### ISSUE TITLE
[Enhancement] Need to show the confirmation message when the user creates topic of the same name

### ISSUE THREAD

**Issue by AayushSaini101** [apache/rocketmq#7100]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Currently, We can able to create the same topic by having a similar name again and again without any kind of confirmation message. This will cause problems and lost of the configuration of the older topic of the RocketMQ. 
![image](https://github.com/apache/rocketmq/assets/60972989/655f78ce-685f-4a62-a0e8-ae4dfd050613)
loss

### Motivation

It will cause a lot of issues to suppose by mistake new topic is created of the same name, the older topic configuration will be lost.

### Describe the Solution You'd Like

We can provide a confirmation message whenever the user tries to create a topic of the same name.

### Describe Alternatives You've Considered

Don't allow the user to create the topic of the same name

**Comment by AayushSaini101** [comment]
@xiaoyifang @jimjag Can you please check this issue? if this is valid to work I can start working on it

**Comment by francisoliverlee** [comment]
api should have a certain response, you are welcome to work it out.

**Comment by AayushSaini101** [comment]
Thank you @francisoliverlee

**Comment by AayushSaini101** [comment]
Hi, @francisoliverlee How can I debug the changes? Can you please tell
