### ISSUE TITLE
[Feature] Some Hooks in Rocketmq can support the form of SPI

### ISSUE THREAD

**Issue by shirenchuang** [apache/rocketmq#7128]
### Is Your Feature Request Related to a Problem?

 If I want to customize SendMessageHook, only through the following form

```java
       DefaultMQProducer producer = new DefaultMQProducer(groupName, new SzzProducerRPCHook(), true, null);
        producer.setNamesrvAddr(DEFAULT_NAMESRVADDR);
       // My meesageHook
        producer.getDefaultMQProducerImpl().registerSendMessageHook(new SzzMessageHook());
```

This method is not very convenient to expand, hope to support the form of SPI to support

### Describe the Solution You'd Like

Load the custom HOOK through SPI;

Of course, not only SendMessageHook is considered, I think most of some HOOKs need to support the form of SPI

### Describe Alternatives You've Considered

SPI

### Additional Context

I want to do some business processing when sending messages;

**Comment by francisoliverlee** [comment]
which kind of SPI you need

**Comment by shirenchuang** [comment]
For example, SendMessageHook supports SPI



---Original---
From: "tiger ***@***.***&gt;
Date: Mon, Aug 7, 2023 23:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/rocketmq] [Feature] Some Hooks in Rocketmq can supportthe form of SPI (Issue #7128)




 
which kind of SPI you need

**Comment by yx9o** [comment]
Hi @shirenchuang , any specific plans? I want to be involved.

**Comment by shirenchuang** [comment]
> 晚点有空的时候, 我会整理一下所有的Hook

**Comment by shirenchuang** [comment]
> 
When I am free later, I will sort out all the Hooks
