### ISSUE TITLE
rocketmq在使用起来比kafka要复杂

### ISSUE THREAD

**Issue by john1337** [apache/rocketmq#7137]
### Is Your Feature Request Related to a Problem?

rocketmq在使用起来比kafka要复杂，比如主从节点的切换：rocketmq需要额外的配置，kafka却自动完成，不需要引入Dledger之类的中间件，另外一个就是rocketmq在k8s的部署，也没有像kafka那么完善的支持，比如helm.sh官网上rocketmq必须通过rocketmq operator，但是kafka却有bitnami kafka可以使用

### Describe the Solution You'd Like

rocketmq易用性希望得到提升，文档完善些

### Describe Alternatives You've Considered

rocketmq易用性希望得到提升，文档完善些

**Comment by RongtongJin** [comment]
@john1337 主从切换不需要引入额外的中间件，Dledger只是一个jar包。主从切换可以参考https://github.com/apache/rocketmq/blob/develop/docs/cn/controller/quick_start.md。
RocketMQ相比于Kafka 切换能力是可选的，而不是必须的。文档方面会继续完善。

**Comment by john1337** [comment]
> @john1337 主从切换不需要引入额外的中间件，Dledger只是一个jar包。主从切换可以参考[https://github.com/apache/rocketmq/blob/develop/docs/cn/controller/quick_start.md。](https://github.com/apache/rocketmq/blob/develop/docs/cn/controller/quick_start.md%E3%80%82) RocketMQ相比于Kafka 切换能力是可选的，而不是必须的。文档方面会继续完善。

另外咨询个问题，我使用rocketmq-docker项目里面rocketmq-k8s-helm如何才能把broker注册地址端口改为对外地址，因为我需要在k8s集群外部访问这个broker

**Comment by john1337** [comment]
> @john1337 主从切换不需要引入额外的中间件，Dledger只是一个jar包。主从切换可以参考[https://github.com/apache/rocketmq/blob/develop/docs/cn/controller/quick_start.md。](https://github.com/apache/rocketmq/blob/develop/docs/cn/controller/quick_start.md%E3%80%82) RocketMQ相比于Kafka 切换能力是可选的，而不是必须的。文档方面会继续完善。

现在我都不知道通过什么设置使得部署在k8s里的rocketmq broker被外部访问，rocketmq-broker这个项目也基本没人回答

**Comment by SchopenhauerZhang** [comment]
我身边同事也这么说，但是我个人觉得RocketMQ broker端还行，当然也可能我对kafka了解太少了(:-。
不过说到"k8s里的rocketmq broker被外部访问",我遇到过类似的（我没有选择k8s部署，因为我觉得RocketMQ k8s的部署目前还不太成熟），解决方式是brokerIP= 设置为主机IP而不是127.xxx这种（通过非k8s部署的时候默认启动的broker地址为127.0.0.1:10911），所以你可以试试，虽然我不保证能解决你的问题。
如果你能提高你的启动参数、配置文件、日志什么的，可能对于问题定位、排查更有效。

**Comment by john1337** [comment]
已解决，https://blog.csdn.net/john1337/article/details/132412838
