### ISSUE TITLE
[Bug] Due to limitations of opentelemetry,  the metrics data may be lost.

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq#7140]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Due to limitations of opentelemetry, when there is a large amount of data for a certain metric, the metrics data may be lost.

### RocketMQ version

master

### JDK Version

8

### Describe the Bug

<img width="687" alt="image" src="https://github.com/apache/rocketmq/assets/2684384/7c138b82-e6a6-40a8-a2ef-162b51d2a32d">

### Steps to Reproduce

create topic * group > 2000

### What Did You Expect to See?

metrics data

### What Did You See Instead?

metrics data lost 

### Additional Context

https://github.com/open-telemetry/opentelemetry-java/pull/3831

in high version ,there add a method can be changed , but it is not public method ,need to reflect to change

**Comment by ShadowySpirits** [comment]
The limitation of the 2000 serials is too small. However, instead of using the inner API via reflection, could we request the Opentelemetry community to expose this API?

**Comment by leizhiyuan** [comment]
> open-telemetry/opentelemetry-java#3831

They have added the corresponding interface, but it is not yet open. It is mentioned in the comments that this is an experimental API. It may be officially released in the future.

**Comment by leizhiyuan** [comment]
fiexed in https://github.com/apache/rocketmq/pull/7196
