### ISSUE TITLE
Which one is the official rocketmq client?

### ISSUE THREAD

**Issue by thousmile** [apache/rocketmq#7148]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

The official website case uses rocketmq-client-java . 
But rocketmq-client updates more frequently and is consistent with rocketmq broker version ！！！ 
how should i choose？？？

```xml
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client-java</artifactId>
</dependency>
```
![image](https://github.com/apache/rocketmq/assets/28520524/0c9044bc-67cf-4bc6-a77e-ec02b05750c9)
```xml
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client</artifactId>
</dependency>
```
![image](https://github.com/apache/rocketmq/assets/28520524/6e301d91-cc1d-46d4-8824-080a246a88a7)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by leizhiyuan** [comment]
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client-java</artifactId>
</dependency>

is for grpc protocal, you can think it is only for rocketmq5 broker + proxy 

<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client</artifactId>
</dependency>

this is for rockemeq broker, for remoting protocal


they are official rocketmq clients
