### ISSUE TITLE
consumer qps slow down when producer qps is high

### ISSUE THREAD

**Issue by reachfish** [apache/rocketmq#715]
broker and client are located in the same server with a ssd disk.  test on 1 topic which contians 8 message queue, and msg size is 200B.  when producer qps is 4w+,  consumer's qps is also 4w+.  But when producer's qps increase to 12w+,  consumer's qps quickly slow down to 6~8k.  

broker config:  maxTransferCountOnMessageInMemory=40; maxTransferCountOnMessageInDisk=30

would you help me ~

**Comment by ymwneu** [comment]
I think, first you can check the broker's log, to make sure whether the dispatch is behind the commit log too much.
