### ISSUE TITLE
[Enhancement] Optimize the display format of admin

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq#7166]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Optimize the display format of admin

### Motivation

Optimize the display format of admin
![image](https://github.com/apache/rocketmq/assets/21963954/48524657-4d41-4541-b715-2c991ddfcbc6)

### Describe the Solution You'd Like

Optimize the display format of admin

### Describe Alternatives You've Considered

No

**Comment by yx9o** [comment]
Hi @RongtongJin , any specific plans? Can I participate?

**Comment by yx9o** [comment]
<img width="737" alt="image" src="https://github.com/apache/rocketmq/assets/12792261/7291e23b-1266-4ca2-9e6a-776c3e9d7aa2">
Hi @RongtongJin , is this ok?

**Comment by yx9o** [comment]
<img width="709" alt="image" src="https://github.com/apache/rocketmq/assets/12792261/99161a5a-9464-4cf0-a9b6-360c5ea43f11">

Hi @RongtongJin , I noticed some formatting issues with commandDesc:
1. Some parts have no terminator
2. Some initial letters are not capitalized
Do they need to be adjusted together?

**Comment by RongtongJin** [comment]
> <img alt="image" width="709" src="https://user-images.githubusercontent.com/12792261/260293328-99161a5a-9464-4cf0-a9b6-360c5ea43f11.png">
> Hi @RongtongJin , I noticed some formatting issues with commandDesc:
> 
> 1. Some parts have no terminator
> 2. Some initial letters are not capitalized
>    Do they need to be adjusted together?

Good catch! Suggest adjusting together.
