### ISSUE TITLE
updateTopicPerm need to check all related brokers config

### ISSUE THREAD

**Issue by superheizai** [apache/rocketmq#718]
**BUG REPORT**

1. Please describe the issue you observed:

   updateTopicPerm on a broker in a cluster with 2 brokers. The first step is to update topic perm to 2, it succeed. Then update it to 6, failed.

 Because I have 2 brokers,  when update one of them to 2,  the 2 brokers perm will be 2&6.  The implementation will take only the first  one's perm to check if it can be updated. 

           TopicRouteData topicRouteData = defaultMQAdminExt.examineTopicRouteInfo(topic);
            assert topicRouteData != null;
            List<QueueData> queueDatas = topicRouteData.getQueueDatas();
            assert queueDatas != null && queueDatas.size() > 0;
            QueueData queueData = queueDatas.get(0);

  
2. Please tell us about your environment:
     
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by duhenglucky** [comment]
@superheizai This is really a place can be optimized, because in the following code it only checked the topic's perm config of the first broker whether same as the perm value to be set, so could you pull a request to polish this implementation? we are happy to help you to complete this PR.

**Comment by superheizai** [comment]
ok, I will make a PR for it

**Comment by superheizai** [comment]
@duhenglucky would you please help to review the pr,  https://github.com/apache/rocketmq/pull/727.
Thanks a lot.

**Comment by ShannonDing** [comment]
#727 under reviewed.
