### ISSUE TITLE
[Bug] 消费者在消息还在处理时下线（interrupted by signal 2: SIGINT）；原消息的offset未标记为已消费，同时processConsumeResult会发送一条重试消息；服务不断自动重启的情况下，重复消息成倍数增长

### ISSUE THREAD

**Issue by liuyuan007** [apache/rocketmq#7182]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

OS：Mac os  or Linux

### RocketMQ version

rocketmq-client：4.8.0及以上（自己用的4.8.0版本，最新版本也未看到相关解决代码）

### JDK Version

JDK11

### Describe the Bug

1、集群模式，消费者在未完成某个消息消费时，发生下线或重启（优雅关机），且在消费代码存在业务异常的情况下；会出现消息offoffset上报服务端为：未消费（offset未后移），同时ConsumeMessageConcurrentlyService#processConsumeResult处理时又会发送一条sendMessageBack重试消息给服务端。
这个时候就出现了重复消息了，在服务不断重启的情况下，重复消息成倍数（1,2,4,8,16,32...）增长。

2、根本原因
1）org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl#shutdown(long)无法让程序严格按代码顺序退出。
2）消息处理和offset更新是两个线程，无法保证offset值强一致。

3、演示
对源码加了System.out.println();打印
截图1：更新远程offset，但offset更新为未消费（offset值未变）
![image](https://github.com/apache/rocketmq/assets/30384521/51f2b536-5ded-46da-b344-e685ed2e2ba2)
截图2：发送重试消息
![image](https://github.com/apache/rocketmq/assets/30384521/6fb13c86-a8ce-4948-9fc2-6577d8b7334a)
完整log看附件。
[异常分析.log](https://github.com/apache/rocketmq/files/12334047/default.log)

第一次重启时服务收到的消息：
消费者收到消息：messageId=AC18000200073E3ABC88454B7D810895，message=MessageExt [brokerName=broker-a, queueId=4, storeSize=215, queueOffset=1152, sysFlag=0, bornTimestamp=1692010575233, bornHost=/172.24.0.2:60834, storeTimestamp=1692010575236, storeHost=/192.168.21.7:10911, msgId=C0A8150700002A9F0000002C82AEC7D5, commitLogOffset=191171053525, bodyCRC=532952986, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='TOPIC_BPM_PROCESS_INSTANCE_EVENT', flag=0, properties={MIN_OFFSET=887, MAX_OFFSET=1153, 
消费者收到消息：messageId=AC18000200073E3ABC88454B7D810895，message=MessageExt [brokerName=broker-a, queueId=0, storeSize=387, queueOffset=984, sysFlag=0, bornTimestamp=1692010575233, bornHost=/172.24.0.2:60834, storeTimestamp=1692010592205, storeHost=/192.168.21.7:10911, msgId=C0A8150700002A9F0000002C82AEE0F1, commitLogOffset=191171059953, bodyCRC=532952986, reconsumeTimes=1, preparedTransactionOffset=0, toString()=Message{topic='TOPIC_BPM_PROCESS_INSTANCE_EVENT', flag=0, properties={MIN_OFFSET=0, REAL_TOPIC=%RETRY%PG_WMS_INVENTORY_ADJUST_LIUYUAN, ORIGIN_MESSAGE_ID=C0A8150700002A9F0000002C82AEC7D5, RETRY_TOPIC=TOPIC_BPM_PROCESS_INSTANCE_EVENT, MAX_OFFSET=985, CONSUME_START_TIME=1692011914251, UNIQ_KEY=AC18000200073E3ABC88454B7D810895, WAIT=false, DELAY=3, TAGS=PG_WMS_INVENTORY_ADJUST, REAL_QID=0}, body=[109, 101, 115, 115, 97, 103, 101, 66, 111, 100, 121], transactionId='null'}]

第二次重启时服务收到的消息：
消费者收到消息：messageId=AC18000200073E3ABC88454B7D810895，message=MessageExt [brokerName=broker-a, queueId=4, storeSize=215, queueOffset=1152, sysFlag=0, bornTimestamp=1692010575233, bornHost=/172.24.0.2:60834, storeTimestamp=1692010575236, storeHost=/192.168.21.7:10911, msgId=C0A8150700002A9F0000002C82AEC7D5, commitLogOffset=191171053525, bodyCRC=532952986, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='TOPIC_BPM_PROCESS_INSTANCE_EVENT', flag=0, properties={MIN_OFFSET=887, MAX_OFFSET=1153, CONSUME_START_TIME=1692012180052, UNIQ_KEY=AC18000200073E3ABC88454B7D810895, WAIT=true, TAGS=PG_WMS_INVENTORY_ADJUST}, body=[109, 101, 115, 115, 97, 103, 101, 66, 111, 100, 121], transactionId='null'}]
消费者收到消息：messageId=AC18000200073E3ABC88454B7D810895，message=MessageExt [brokerName=broker-a, queueId=0, storeSize=387, queueOffset=984, sysFlag=0, bornTimestamp=1692010575233, bornHost=/172.24.0.2:60834, storeTimestamp=1692010592205, storeHost=/192.168.21.7:10911, msgId=C0A8150700002A9F0000002C82AEE0F1, commitLogOffset=191171059953, bodyCRC=532952986, reconsumeTimes=1, preparedTransactionOffset=0, toString()=Message{topic='TOPIC_BPM_PROCESS_INSTANCE_EVENT', flag=0, properties={MIN_OFFSET=0, REAL_TOPIC=%RETRY%PG_WMS_INVENTORY_ADJUST_LIUYUAN, ORIGIN_MESSAGE_ID=C0A8150700002A9F0000002C82AEC7D5, RETRY_TOPIC=TOPIC_BPM_PROCESS_INSTANCE_EVENT, MAX_OFFSET=987, CONSUME_START_TIME=1692012180090, UNIQ_KEY=AC18000200073E3ABC88454B7D810895, WAIT=false, DELAY=3, TAGS=PG_WMS_INVENTORY_ADJUST, REAL_QID=0}, body=[109, 101, 115, 115, 97, 103, 101, 66, 111, 100, 121], transactionId='null'}]
消费者收到消息：messageId=AC18000200073E3ABC88454B7D810895，message=MessageExt [brokerName=broker-a, queueId=0, storeSize=387, queueOffset=985, sysFlag=0, bornTimestamp=1692010575233, bornHost=/172.24.0.2:60834, storeTimestamp=1692011884610, storeHost=/192.168.21.7:10911, msgId=C0A8150700002A9F0000002C82B1CA69, commitLogOffset=191171250793, bodyCRC=532952986, reconsumeTimes=1, preparedTransactionOffset=0, toString()=Message{topic='TOPIC_BPM_PROCESS_INSTANCE_EVENT', flag=0, properties={MIN_OFFSET=0, REAL_TOPIC=%RETRY%PG_WMS_INVENTORY_ADJUST_LIUYUAN, ORIGIN_MESSAGE_ID=C0A8150700002A9F0000002C82AEC7D5, RETRY_TOPIC=TOPIC_BPM_PROCESS_INSTANCE_EVENT, MAX_OFFSET=987, CONSUME_START_TIME=1692012180090, UNIQ_KEY=AC18000200073E3ABC88454B7D810895, WAIT=false, DELAY=3, TAGS=PG_WMS_INVENTORY_ADJUST, REAL_QID=0}, body=[109, 101, 115, 115, 97, 103, 101, 66, 111, 100, 121], transactionId='null'}]
消费者收到消息：messageId=AC18000200073E3ABC88454B7D810895，message=MessageExt [brokerName=broker-a, queueId=0, storeSize=387, queueOffset=986, sysFlag=0, bornTimestamp=1692010575233, bornHost=/172.24.0.2:60834, storeTimestamp=1692011904610, storeHost=/192.168.21.7:10911, msgId=C0A8150700002A9F0000002C82B1D73C, commitLogOffset=191171254076, bodyCRC=532952986, reconsumeTimes=2, preparedTransactionOffset=0, toString()=Message{topic='TOPIC_BPM_PROCESS_INSTANCE_EVENT', flag=0, properties={MIN_OFFSET=0, REAL_TOPIC=%RETRY%PG_WMS_INVENTORY_ADJUST_LIUYUAN, ORIGIN_MESSAGE_ID=C0A8150700002A9F0000002C82AEC7D5, RETRY_TOPIC=TOPIC_BPM_PROCESS_INSTANCE_EVENT, MAX_OFFSET=987, CONSUME_START_TIME=1692012180090, UNIQ_KEY=AC18000200073E3ABC88454B7D810895, WAIT=false, DELAY=4, TAGS=PG_WMS_INVENTORY_ADJUST, REAL_QID=0}, body=[109, 101, 115, 115, 97, 103, 101, 66, 111, 100, 121], transactionId='null'}]

### Steps to Reproduce

1、集群模式，消费者在未完成某个消息消费时，发生下线或重启（优雅关机），且在消费代码存在业务异常的情况下。
复现代码见下图：
![image](https://github.com/apache/rocketmq/assets/30384521/7809264f-c6f5-4a49-9a02-7061d6c842f2)

### What Did You Expect to See?

1、offset更新为已消费，发送重试消息。
2、或者：offset不更新，不发送重试消息。

### What Did You See Instead?

以下是一种解决方式，但不是很可靠，且awaitTerminationMillisWhenShutdown未开放配置。
![image](https://github.com/apache/rocketmq/assets/30384521/8c57983d-e115-47fc-a959-bae9298c5127)

**Comment by SchopenhauerZhang** [comment]
”消费者在未完成某个消息消费时，发生下线或重启（优雅关机），且在消费代码存在业务异常的情况下；会出现消息offoffset上报服务端为：未消费（offset未后移“
按照我的理解，如果上报失败，消息就会重复下发，这是默认逻辑（这其实和offset没有立即上报而是周期上报有一定关系），不过这种成倍增长我还没有遇到过。是否由于消费者服务反复启停导致呢？感觉需要更多信息才能确定，我试试在我本地（5.0）能否复现。

**Comment by liuyuan007** [comment]
“按照我的理解，如果上报失败，消息就会重复下发，这是默认逻辑（这其实和offset没有立即上报而是周期上报有一定关系），不过这种成倍增长我还没有遇到过。是否由于消费者服务反复启停导致呢？感觉需要更多信息才能确定，我试试在我本地（5.0）能否复现。”
1、offset没有上报确实是原消息会重新下发，关键是消费处理时存在异常情况下，还会发一条重试消息到服务端，这就重复了。
2、是因为消费者在满足“消费者在未完成某个消息消费时，且在消费代码存在业务异常的情况下；”反复启停（非kill -9 ）导致的。
3、这里的offset上报和定时任务上报还没关系，是消费者在JVM退出时，下面截图这两步没有严格严程序逻辑走。
4、5.0应该是一样的可以复现，而且还比较容易复现，像我的截图的例子。
awaitTerminateMillis默认配置为0，默认配置应该不能给0。自己本地200后可以控制下面两个步骤按顺序执行，就不存在成倍重复的问题了。

![image](https://github.com/apache/rocketmq/assets/30384521/8c49c2f0-2ee3-4b61-81d3-74b92a296bef)
