### ISSUE TITLE
[Bug] 5.1版本的 启动Broker+Proxy 模式启动后直接占用了8080端口，导致RocketMQ Dashboard无法启动

### ISSUE THREAD

**Issue by xuanskyer** [apache/rocketmq#7185]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

CentOS Linux release 7.9.2009 (Core)

### RocketMQ version

5.1.3

### JDK Version

java-1.8.0-openjdk-1.8.0.372.b07-1.el7_9.x86_64

### Describe the Bug

按照 https://rocketmq.apache.org/zh/docs/quickStart/01quickstart 快速部署模式。

1. 下载安装Apache RocketMQ 5.1.3 二进制包
2. 启动NameServer ，成功
3. 启动Broker+Proxy，成功。此时发现8080端口已经被监听了：
```
lsof -i:8080
COMMAND   PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
java    25323 root  236u  IPv6 234111338      0t0  TCP *:webcache (LISTEN)
```
4. 后续启动 RocketMQ Dashboard 失败，提示端口占用

### Steps to Reproduce

按照 https://rocketmq.apache.org/zh/docs/quickStart/01quickstart 快速部署模式。

1. 下载安装Apache RocketMQ 5.1.3 二进制包
2. 启动NameServer ，成功
3. 启动Broker+Proxy，成功。此时发现8080端口已经被监听了：
```
lsof -i:8080
COMMAND   PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
java    25323 root  236u  IPv6 234111338      0t0  TCP *:webcache (LISTEN)
```
4. 后续启动 RocketMQ Dashboard 失败，提示端口占用

### What Did You Expect to See?

RocketMQ Broker+Proxy 和 RocketMQ Dashboard的 服务启动不要有冲突

### What Did You See Instead?

RocketMQ Broker+Proxy 和 RocketMQ Dashboard的 服务启动不要有冲突

**Comment by shadowofmoo** [comment]
同样碰到这个问题，阿里出品，必属精品

**Comment by melelee** [comment]
同样碰到这个问题

**Comment by ShenXinKang** [comment]
这个有点坑，官方文档也没写，需要修改配置文件：rmq-proxy.json

**Comment by xuanskyer** [comment]
> 这个有点坑，官方文档也没写，需要修改配置文件：rmq-proxy.json，改成自己想要的端口
> 
> ```
> {
>   "rocketMQClusterName": "DefaultCluster",
>   "grpcServerPort": xxxx,
>   "remotingListenPort": xxxx
> }
> ```

官方文档真的有点一言难尽啊

**Comment by huwxi** [comment]
请教大神们，为什么官方不提供namesrv、broker、proxy这些服务的配置说明呢，有哪些配置项也行啊，我总不能要用这个东西直接去看源码吧？有什么好方法呢？

**Comment by zzps** [comment]
看了一下官方文档，找不到任何服务端的配置文档！！！！

**Comment by kliein** [comment]
你不会给控制台换个端口？
