### ISSUE TITLE
[Bug] Start the consumer first, the producer sends a message to rocketmq and the consumer can't receive it

### ISSUE THREAD

**Issue by zooah212** [apache/rocketmq#7195]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

5.1.3

### JDK Version

1.8

### Describe the Bug

New RocketMQ environment, start the consumer first, the producer sends a message to MQ and the consumer can't receive it. After a few seconds send another message to MQ and the consumer can receives the message. Message Model is Broadcasting, Consume_From_Where is CONSUME_FROM_LAST_OFFSET.
If the producer sends the message first and starts the consumer later, the message will not lost.

### Steps to Reproduce

If the Message Model is Clustering, Consume_From_Where is CONSUME_FROM_LAST_OFFSET, the first message can not receive too, but in the dashboard page the message shows that it has been consumed.

### What Did You Expect to See?

In the new RocketMQ environment, can receive the first message.

### What Did You See Instead?

The first message is missing.

**Comment by mufengCc** [comment]
相同的版本，没有出现你这个问题
