### ISSUE TITLE
[Bug] when I delete unused topic, topic consume queue on the standby node is not deleted synchronously.

### ISSUE THREAD

**Issue by frinda** [apache/rocketmq#7264]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

SUSE Linux Enterprise Server 12 SP5

### RocketMQ version

develop|4.9.x

### JDK Version

JDK 1.8.0_372

### Describe the Bug

In active/standby mode, when I run command 'mqadmin deleteTopic -b xxx -t xxx'  to delete unused topic,  topic consume queue on the standby node is not deleted synchronously

### Steps to Reproduce

1. Deploying the active/standby Mode Environment
2. Send and consume messages with the topic 'test001'  in push mode at the same time, run a while(About two or five minutes)
3. stop producer and consumer, run command ‘mqadmin deleteTopic -b xxx -t test001’ to delete topic 'test001'

### What Did You Expect to See?
Delete all the information about this topic from the active/standby.
![image](https://github.com/apache/rocketmq/assets/9562305/178825ae-80ff-4f19-80da-861f9579d56c)

### What Did You See Instead?
topic consume queue on the standby node is still exist.
![image](https://github.com/apache/rocketmq/assets/9562305/159678e4-044a-4c50-84fc-a8f98f3eb2b2)

**Comment by iamgd67** [comment]
if receate the same name topic and send message, slave will produce log repeatlly
`WARN ReputMessageService - Build  consume queue repeatedly, expectLogicOffset: xxx currentLogicOffset: xxx Topic: xxxx QID: x Diff: -xxxx`

**Comment by frinda** [comment]
> if receate the same name topic and send message, slave will produce log repeatlly `WARN ReputMessageService - Build consume queue repeatedly, expectLogicOffset: xxx currentLogicOffset: xxx Topic: xxxx QID: x Diff: -xxxx`

Yeah

**Comment by frinda** [comment]
> > if receate the same name topic and send message, slave will produce log repeatlly `WARN ReputMessageService - Build consume queue repeatedly, expectLogicOffset: xxx curre

**Comment by iamgd67** [comment]
@frinda  why this issue is closed, fixed my another pr?

**Comment by frinda** [comment]
> @frinda why this issue is closed, fixed my another pr?

My fault, pr didn't change

**Comment by iamgd67** [comment]
no commiter or pmc review...  太难了
