### ISSUE TITLE
[Enhancement] Use JRaft to Implement Controller

### ISSUE THREAD

**Issue by yulangz** [apache/rocketmq#7300]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

The Controller is implemented based on DLedger. DLedger is a raft repository specifically designed for RocketMQ with many optimizations made for CommitLog. However, when implementing Controller, these optimizations are not needed, and DLedger does not support log compression (Snapshot), so more mature raft libraries such as JRaft can be considered.

### Motivation

Compared to DLedger, jRaft is more mature and reliable, and supports snapshot function, which can solve the problem of unlimited log growth.

### Describe the Solution You'd Like

Use JRaft to Implement Controller.

### Describe Alternatives You've Considered

Use other mature Raft libraries.

### Additional Context

RIP: [https://docs.google.com/document/d/1mpzTv1vnWxQwPGsHj6Ng2fK9aL9f6MZFw7ZgvW5284o/edit#heading=h.av2kaasaafu6](https://docs.google.com/document/d/1mpzTv1vnWxQwPGsHj6Ng2fK9aL9f6MZFw7ZgvW5284o/edit#heading=h.av2kaasaafu6)

_No response_

**Comment by vongosling** [comment]
I must clarify one thing, DLedger is not specifically designed for Apache RocketMQ. It is still in the process of continuous evolution.
