### ISSUE TITLE
[Enhancement]  Optimization Method Name

### ISSUE THREAD

**Issue by RapperCL** [apache/rocketmq#7313]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary
**path:** org.apache.rocketmq.tieredstore.provider.TieredStoreTopicBlackListFilter

The method addTopicToWhiteList of this TieredStoreTopicBlackListFilter class should be renamed to addTopicToBlackList
![image](https://github.com/apache/rocketmq/assets/44110731/c1d5757b-a3db-4412-bd4f-e4e309884bd6)

### Motivation

I found that the method name does not match the actual logic of the method

### Describe the Solution You'd Like

Modify Method Name

### Describe Alternatives You've Considered

Modify Method Name

**Comment by shriVATSA54** [comment]
Hii
Can i work on this.
this is my first issue working on I might even not contribute but wanna give a try.

sould i suggest name Optimized Method name here only? or make changes in github ?
