### ISSUE TITLE
 The secretkey in plain_acl.yml is saved in plaintext. Can I change it to ciphertext

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq#7347]
### Is Your Feature Request Related to a Problem?

 The secretkey in plain_acl.yml is saved in plaintext. So theoretically, I can see the unencrypted secretkey from the text.Can I change it to ciphertext

### Describe the Solution You'd Like

Secretkey writes plaintext to a file, and Rocketmq automatically encrypts plaintext into ciphertext.

### Describe Alternatives You've Considered

none

### Additional Context

none

**Comment by leizhiyuan** [comment]
if  users can see you yaml file , maybe he has the way to know the unencrypt method。
