### ISSUE TITLE
[Bug] Master-slave synchronisation creates infinite FlowMonitor threads if a readSocketService exception is created, resulting in OOM.

### ISSUE THREAD

**Issue by weihubeats** [apache/rocketmq#7356]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Ubuntu 22.04.2 LTS

### RocketMQ version

5.1.0

### JDK Version

1.8

### Describe the Bug

Master-slave synchronisation creates infinite FlowMonitor threads if a readSocketService exception is created, resulting in OOM.
![image](https://github.com/apache/rocketmq/assets/42484192/cefeea60-d4e9-4673-9e75-a6cdea6d4cc3)

### Steps to Reproduce

no

### What Did You Expect to See?

Infinite creation of FlowMonitor threads eventually leads to OOM

### What Did You See Instead?

does not create too many FlowMonitor threads

**Comment by RongtongJin** [comment]
Fixed in https://github.com/apache/rocketmq/pull/6227

**Comment by weihubeats** [comment]
Okay. Thank you very much.
