### ISSUE TITLE
[Bug] ExportConfigsCommand NPE

### ISSUE THREAD

**Issue by shirenchuang** [apache/rocketmq#7398]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

MacOS 12.6

### RocketMQ version

release-5.1.3

### JDK Version

jdk11

### Describe the Bug

![image](https://github.com/apache/rocketmq/assets/10442648/a5e25233-10eb-495c-a4bf-b26b8ad73893)

![image](https://github.com/apache/rocketmq/assets/10442648/116de220-2bef-43cf-a935-f43c43e7ab37)

![image](https://github.com/apache/rocketmq/assets/10442648/066e3a73-cc86-4049-aeee-b9383e70ae75)

### Steps to Reproduce

run ExportConfigsCommand

### What Did You Expect to See?

don't throw NPE

### What Did You See Instead?

.

**Comment by joeCarf** [comment]
maybe you can assign this to me, I'd like to fix it.

**Comment by joeCarf** [comment]
BTW, may I ask how you execute terminal commands like `ExportConfigsCommand` when debugging RocketMQ in Idea? Thanks a lot~

**Comment by shirenchuang** [comment]
> BTW, may I ask how you execute terminal commands like `ExportConfigsCommand` when debugging RocketMQ in Idea? Thanks a lot~

直接跑源码debug 或者 执行sh脚本的时候开启远程端口然后再IDEA调试都可以的

**Comment by shirenchuang** [comment]
> BTW，请问`ExportConfigsCommand`在Idea中调试RocketMQ时如何执行终端命令？非常感谢~

你可以在 MQAdminStartup的main方法中添加一些参数

```java
    public static void main(String[] args) {
        String namesrv = "-n=127.0.0.1:9876";
        String clusterName = "-c=szz_cluster_a";

        //导出Broker配置文件
        args = new String[]{"exportConfigs",namesrv,clusterName};
        main0(args, null);

    }

```

**Comment by lizhimins** [comment]
put null 是因为哪个参数没了？

**Comment by joeCarf** [comment]
> put null 是因为哪个参数没了？

filterServerNums

**Comment by joeCarf** [comment]
> > BTW，请问`ExportConfigsCommand`在Idea中调试RocketMQ时如何执行终端命令？非常感谢~
> 
> 你可以在 MQAdminStartup的main方法中添加一些参数
> 
> ```java
>     public static void main(String[] args) {
>         String namesrv = "-n=127.0.0.1:9876";
>         String clusterName = "-c=szz_cluster_a";
> 
>         //导出Broker配置文件
>         args = new String[]{"exportConfigs",namesrv,clusterName};
>         main0(args, null);
> 
>     }
> ```
感谢
