### ISSUE TITLE
[Bug] UtilAllTest#testCalculateFileSizeInPath can't delete testfile 

### ISSUE THREAD

**Issue by shirenchuang** [apache/rocketmq#7406]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

MacOS12

### RocketMQ version

develop

### JDK Version

jdk8

### Describe the Bug

UtilAllTest#testCalculateFileSizeInPath
can't pass test

Because the file was not deleted when the method ended

![image](https://github.com/apache/rocketmq/assets/10442648/488a8cad-a150-40dc-9aae-1380a7519c8c)

### Steps to Reproduce

just run 

### What Did You Expect to See?

.

### What Did You See Instead?

.

**Comment by francisoliverlee** [comment]
it seems https://github.com/apache/rocketmq/blob/develop/common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java#L275 not work

**Comment by shirenchuang** [comment]
> it seems https://github.com/apache/rocketmq/blob/develop/common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java#L275 not work

Please CR when you have time
