### ISSUE TITLE
quension: the benchmark cannot consume

### ISSUE THREAD

**Issue by powerfulsnail** [apache/rocketmq#741]
I use the following command to produce the messages， and then execute another command to consume the messages, but cannot consume any messages, why?

sh producer.sh -n xxx.xxx.xxx.xxx:9876 -t topic_test
sh consumer.sh -n xxx.xxx.xxx.xxx:9876 -t topic_test

**Comment by duhenglucky** [comment]
@powerfulsnail Could you give more information about this, and it would be very nice if you can find the reason about this by dig viewing the client log, it located in the ~/logs/rocketmqlogs/ path.
Besides, ISSUE only used for bug report or feature quest, and please discuss your question about RocketMQ in our mailing list firstly: https://rocketmq.apache.org/about/contact/
