### ISSUE TITLE
[Enhancement] messagetrace config  at server broker

### ISSUE THREAD

**Issue by wash1983** [apache/rocketmq#7417]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

messagetrace 目前是在producer 和consumer中通过enablemessagetrace 参数优由客户端控制，目前已经上了很多业务。能否在不动客户端配置的情况下在服务器端开通messagetrace，统一所有的发送，消费等运送至tracetopic.1是简化客户端的配置和修改程序的风险。2.避免某些客户端漏掉开启而躲过了记录。3.某些业务场景要求所有的都需要开启，这样也能避免客户端故意不开启造成躲过记录

### Motivation

a

### Describe the Solution You'd Like

a

### Describe Alternatives You've Considered

a

### Additional Context

a

**Comment by humkum** [comment]
IMO. Trace message would bring extra message to broker, which would reduce the real produce TPS limit, it should be configured at the client side. Maybe you could change the client side, set the configuration `enableMsgTrace` with `true` by default, and user can set it to false if they didn't need trace message.

**Comment by leizhiyuan** [comment]
Although this functionality can be implemented on the server side, it will lack some information, such as production time data. This can currently only be generated on the client side. The implementation cost is relatively high. Additionally, when consuming ACK, the server only knows the position, and the lack of message IDs will also result in incomplete trace information for consumption.
