### ISSUE TITLE
[Bug] UtilAllTest.testCalculateFileSizeInPath is unstable in Windows

### ISSUE THREAD

**Issue by mureinik** [apache/rocketmq#7418]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

```
$ mvn -v
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: C:\Users\allon\Downloads\apache-maven-3.9.0
Java version: 1.8.0_272, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-8.0.272.10-hotspot\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

### RocketMQ version

branch: develop
Git commit: 4f1b42a7c5557bcadd6b9982a0c9bd876622c69e

### JDK Version

AdoptOpenJDK 1.8.0_272

### Describe the Bug

When building the repo on the machine described above `UtilAllTest.testCalculateFileSizeInPath` fails:

```
Failed tests:
  UtilAllTest.testCalculateFileSizeInPath:242 expected:<0> but was:<5252>
```

### Steps to Reproduce

Run `mvn install`.
I saw the failure on the machine described above, did not try with other machines.

### What Did You Expect to See?

The test should pass

### What Did You See Instead?

The test fails

**Comment by keranbingaa** [comment]
这个就是无法删除为空文件导致的，应该和[ISSUE 7406](https://github.com/apache/rocketmq/issues/7406)是同一个问题
