### ISSUE TITLE
5.x启动Broker+Proxy 命令，希望有win版本的，另外任意时间精度的延时，最大延时时间的完整配置，没在文档中找到

### ISSUE THREAD

**Issue by lb-zy** [apache/rocketmq#7459]
### Search before creation

- [ ] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

错误信息：
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 13  DESC: timer message illegal, the delay time should not be bigger than the max delay 259200000ms; or if set del msg, the delay time should be bigger than the current time BROKER:

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by leizhiyuan** [comment]
set 
timerMaxDelaySec in broker.conf

**Comment by drpmma** [comment]
maxDelayTimeMills in ProxyConfig

**Comment by lb-zy** [comment]
I'll try it all，thank you

**Comment by cyao2q** [comment]
> maxDelayTimeMills in ProxyConfig

![image](https://github.com/apache/rocketmq/assets/10820724/973dd4df-0930-4c37-81f6-760f2d130b0f)
请问这2个配置都要配置吗 我看默认 proxy的启动日志是1天 `"maxDelayTimeMills":86400000`

**Comment by lb-zy** [comment]
我只在broker.conf里配置了，就没报这个错：
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 720
timerMaxDelaySec = 2592000
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

**Comment by cyao2q** [comment]
> 我只在broker.conf里配置了，就没报这个错： brokerClusterName = DefaultCluster brokerName = broker-a brokerId = 0 deleteWhen = 04 fileReservedTime = 720 timerMaxDelaySec = 2592000 brokerRole = ASYNC_MASTER flushDiskType = ASYNC_FLUSH
你这是30天？
fileReservedTime这个是什么意思啊 默认是 48 需要改吗

**Comment by lb-zy** [comment]
> > 我只在broker.conf里配置了，就没报这个错： brokerClusterName = DefaultCluster brokerName = broker-a brokerId = 0 deleteWhen = 04 fileReservedTime = 720 timerMaxDelaySec = 2592000 brokerRole = ASYNC_MASTER flushDiskType = ASYNC_FLUSH
> > 你这是30天？
> > fileReservedTime这个是什么意思啊 默认是 48 需要改吗

fileReservedTime是持久化消息保存周期（单位：小时），超过该周期将被清理，默认48小时，你要是改了最大延时时间，就得跟着改这个

**Comment by cyao2q** [comment]
> > > 我只在broker.conf里配置了，就没报这个错： brokerClusterName = DefaultCluster brokerName = broker-a brokerId = 0 deleteWhen = 04 fileReservedTime = 720 timerMaxDelaySec = 2592000 brokerRole = ASYNC_MASTER flushDiskType = ASYNC_FLUSH
> > > 你这是30天？
> > > fileReservedTime这个是什么意思啊 默认是 48 需要改吗
> 
> ![image](https://private-user-images.githubusercontent.com/30514788/287196993-d5291d0f-62ed-47c7-b925-6a183005b6ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTczNDQsIm5iZiI6MTcwMTQxNzA0NCwicGF0aCI6Ii8zMDUxNDc4OC8yODcxOTY5OTMtZDUyOTFkMGYtNjJlZC00N2M3LWI5MjUtNmExODMwMDViNmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA3NTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzI3YThjYmM0NDAyMGQxZDBiMDllM2E5YjYwNjVmODc4ODhkYjhhMDI5YzYxNGJjNzA5ZjI1N2ZhZGEyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.budDh_lAhLgqGTHSofishtq_8-hu_h5yIe4YxJKN2oQ) 其实这个参数，我也不确定，默认是48小时，如果延时消息超过48小时，会不会也被清理

我现在不清楚是否正常了 发的延时消息也看不到 我简单试试吧

**Comment by yiduwangkai** [comment]
> set timerMaxDelaySec in broker.conf

这个参数改不了，代码里面没有调用

**Comment by yiduwangkai** [comment]
> > set timerMaxDelaySec in broker.conf
> 
> 这个参数改不了，代码里面没有调用

可以改，说错了

**Comment by marksmansj** [comment]
> 我只在broker.conf里配置了，就没报这个错： brokerClusterName = DefaultCluster brokerName = broker-a brokerId = 0 deleteWhen = 04 fileReservedTime = 720 timerMaxDelaySec = 2592000 brokerRole = ASYNC_MASTER flushDiskType = ASYNC_FLUSH

您好，请问你有用到proxy 的路由功能么？例如我有两个idc1、idc2，我希望idc2的mq集群作为idc1 mq集群的热备，然后通过proxy 路由实现idc1 应用访问idc1的mq集群，idc2的应用访问idc2 mq集群。

**Comment by james7whm** [comment]
你好，我用的rocketmq-all-5.2.0-bin-release，加了这两个fileReservedTime = 720
timerMaxDelaySec = 2592000 配置后重启了MQ，但是还是控制台显示的配置没有变化，仍然是259200
![image](https://github.com/user-attachments/assets/8a09021d-dc56-4e84-94a6-ed234028a1f2)

**Comment by lb-zy** [comment]
> 你好，我用的rocketmq-all-5.2.0-bin-release，加了这两个fileReservedTime = 720 timerMaxDelaySec = 2592000 配置后重启了MQ，但是还是控制台显示的配置没有变化，仍然是259200 ![image](https://private-user-images.githubusercontent.com/35658738/363608650-8a09021d-dc56-4e84-94a6-ed234028a1f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU0MTQsIm5iZiI6MTcyNTI2NTExNCwicGF0aCI6Ii8zNTY1ODczOC8zNjM2MDg2NTAtOGEwOTAyMWQtZGM1Ni00ZTg0LTk0YTYtZWQyMzQwMjhhMWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4MTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzM5YWQ4YWEyM2QyMWRkM2ZkYjE4ZDMyNGRhNGFkNDI2OTRlMDc2NzhjY2U5YjRiZGExNzNiNjM5ZmE0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VP8rB-yRcu9ziVE_1MMZtq-2DqrJ5-eYRcwG3nfChUU)

我看你截图，应该选的2主无从配置吧，那新加的配置是加在2m-noslave这个文件下的broker配置里吗

**Comment by james7whm** [comment]
> > 你好，我用的rocketmq-all-5.2.0-bin-release，加了这两个fileReservedTime = 720 timerMaxDelaySec = 2592000 配置后重启了MQ，但是还是控制台显示的配置没有变化，仍然是259200 ![image](https://private-user-images.githubusercontent.com/35658738/363608650-8a09021d-dc56-4e84-94a6-ed234028a1f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU0MTQsIm5iZiI6MTcyNTI2NTExNCwicGF0aCI6Ii8zNTY1ODczOC8zNjM2MDg2NTAtOGEwOTAyMWQtZGM1Ni00ZTg0LTk0YTYtZWQyMzQwMjhhMWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4MTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzM5YWQ4YWEyM2QyMWRkM2ZkYjE4ZDMyNGRhNGFkNDI2OTRlMDc2NzhjY2U5YjRiZGExNzNiNjM5ZmE0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VP8rB-yRcu9ziVE_1MMZtq-2DqrJ5-eYRcwG3nfChUU)
> 
> 我看你截图，应该选的2主无从配置吧，那新加的配置是加在2m-noslave这个文件下的broker配置里吗

只起了一个节点，我改了最外面的配置文件，启动得加上配置文件路径才能生效，之前一直没加路径，谢谢指导
![image](https://github.com/user-attachments/assets/700a84f2-fc3a-4e18-ae01-62b5002d8763)
![2284fd14dbe21a92286b65e4a5e0bd5](https://github.com/user-attachments/assets/b10715e6-9507-4107-8f82-6238dbe8a12a)
