### ISSUE TITLE
[Enhancement] Why is this method marked `Deprecated` and is there a new method that can be replaced?

### ISSUE THREAD

**Issue by wuwen5** [apache/rocketmq#7461]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

https://github.com/apache/rocketmq/blob/2113fa371b9c2bf7c512f8ad234e51c616f1362c/client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java#L1224-L1228

If this is `Deprecated`, how do you replace the following code in the sample? 
Is there an alternative method before it `Deprecated`

https://github.com/apache/rocketmq/blob/2113fa371b9c2bf7c512f8ad234e51c616f1362c/example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingTransactionProducer.java#L46-L55

### Motivation

Remove `@Deprecated` markers 

### Describe the Solution You'd Like

Remove `@Deprecated` markers before new methods are provided

### Describe Alternatives You've Considered

Remove `@Deprecated` markers 

### Additional Context

Suggest adding relevant annotations and alternative solutions for methods marked as `@Deprecated`.

**Comment by leizhiyuan** [comment]
because expose  the getDefaultMQProducerImpl  is not necessary. Unless you need to implement the trace yourself in your demo.

just see the commit
https://github.com/apache/rocketmq/commit/6afe0f84fc216f85b12cb7b3cd3d0d168842d65d#diff-cdd8435ff8a2ddc656c64100a9f53df78ab24de78cd45908d6d6bb10826298d3

**Comment by leizhiyuan** [comment]
now, you can use this method, when delete this method (Incompatible，when show in release note) , there will provide a new method

**Comment by wuwen5** [comment]
#7128

**Comment by sdoqwer1poiu** [comment]
赞同呀，没有新方法前就不应该加这种注解啊
