### ISSUE TITLE
[Bug] dledger集群消息丢失

### ISSUE THREAD

**Issue by LittleBoy18** [apache/rocketmq#7477]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

k8s

### RocketMQ version

4.9.6

### Describe the Bug

部署一套3节点的dledger集群，发送一批消息，将3个broker pod全部重启，发现可以根根offsetMsgId查到消息，但是根据msgId查不到消息

### Steps to Reproduce

1、部署3节点的dledger集群
2、发送一条或者几条消息，记录返回的msgId和offsetMsgId
3、重启所有broker
4、分别根据msgId和offsetMsgId查询消息

根据offsetMsgId查询：
<img width="965" alt="image" src="https://github.com/apache/rocketmq/assets/18388649/f454471b-daf3-44f2-9e8d-1c2313564d98">

根据msgId查询：
<img width="1085" alt="image" src="https://github.com/apache/rocketmq/assets/18388649/caafd3bb-2348-4dcd-9caa-ccfa33f12858">

### What Did You Expect to See?

msgId可以查到消息

### What Did You See Instead?

msgId查不到，offsetMsgId可以查到

**Comment by GenerousMan** [comment]
Hello, I have verified the situation you mentioned. Below are some of my testing processes.

### Verification process
![image](https://github.com/apache/rocketmq/assets/21073949/76845777-596a-4179-b6c1-f657544c5162)

Send a message and save the sending status of one of the messages:
SendResult [sendStatus=SEND_OK, msgId=AC1004C454E75D099F62895F43C403E7, offsetMsgId=AC1004C4000078D300000000001181B9, messageQueue=MessageQueue [topic=TopicTest, brokerName=RaftNode00, queueId=1], queueOffset=999]

Close using the test script and restart.
![image](https://github.com/apache/rocketmq/assets/21073949/e8661483-fad3-4a03-a40e-5e5e4a2cd8cc)

Still able to query:
![image](https://github.com/apache/rocketmq/assets/21073949/359b42cd-c697-4236-8a1c-d56e2f48e322)

Forcefully kill the process after startup and observe the query result:
![image](https://github.com/apache/rocketmq/assets/21073949/91e0ab03-155c-4ab6-a2a7-ee3f1ac9a1de)
![image](https://github.com/apache/rocketmq/assets/21073949/b512a26f-da93-41b1-8898-157fbfaf81ff)

### Preliminary conclusion
After killing the broker with kill -9, it is indeed possible that the msgId cannot be found. The index folder is emptied after restarting, indicating that the recover process cleans up the index files.
![image](https://github.com/apache/rocketmq/assets/21073949/46563582-008c-4f73-94fc-aee6fe19d414)

However, the offsetId can still be found, indicating that the message is not lost and is still in the commit log.
Further investigation is needed to determine the specific cause.

**Comment by LittleBoy18** [comment]
DledgerCommitLog覆写了recover的逻辑，之前的CommitLog的recover逻辑中有重建index的代码
