### ISSUE TITLE
[Bug] Invalid key/value in long polling is not removed from Map

### ISSUE THREAD

**Issue by yx9o** [apache/rocketmq#7481]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

mac

### RocketMQ version

master

### JDK Version

jdk1.8

### Describe the Bug

Invalid Consumer data in `org.apache.rocketmq.broker.longpolling.PullRequestHoldService#pullRequestTable` will not be removed

<img width="929" alt="image" src="https://github.com/apache/rocketmq/assets/12792261/c2cccd3b-2e34-4c18-a676-5d370fb66983">
<img width="1052" alt="image" src="https://github.com/apache/rocketmq/assets/12792261/eb07e894-4dee-4c14-8528-48305b8365e2">

### Steps to Reproduce

1. Start Broker
2. Create a Topic and send a message
3. Start Consumer. When the pull message returns `ResponseCode.PULL_NOT_FOUND`, it will be added to `org.apache.rocketmq.broker.longpolling.PullRequestHoldService#pullRequestTable`
4. But when the `Consumer` is stopped, the data in `org.apache.rocketmq.broker.longpolling.PullRequestHoldService#pullRequestTable` still exists

### What Did You Expect to See?

After `Consumer` is stopped, the matching data in `org.apache.rocketmq.broker.longpolling.PullRequestHoldService#pullRequestTable` is removed

### What Did You See Instead?

After `Consumer` is stopped, the matching data in `org.apache.rocketmq.broker.longpolling.PullRequestHoldService#pullRequestTable` is still there

### Additional Context

We should remove `key` under the condition that `null == mpr || null == mpr.cloneListAndClear()`

**Comment by joeCarf** [comment]
这个未删除的问题会带来哪些影响呢

**Comment by yx9o** [comment]
There may be problems in the following aspects:
1. org.apache.rocketmq.broker.longpolling.PullRequestHoldService#pullRequestTable is getting larger and larger, which may lead to insufficient memory or even OOM
2. Useless traversal and useless acquisition getMaxOffsetInQueue

**Comment by yp969803** [comment]
@lizhanhui What you think?
