### ISSUE TITLE
[Bug] controller metricsExporterType config not working

### ISSUE THREAD

**Issue by iamgd67** [apache/rocketmq#7491]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos 7

### RocketMQ version

5.1.3

### JDK Version

1.8

### Describe the Bug

metricsExporterType=PROM, but no port listens appear

### Steps to Reproduce

just set the config

### What Did You Expect to See?

listen to 5557

### What Did You See Instead?

no port listen

**Comment by Horus-K** [comment]
![image](https://github.com/user-attachments/assets/98732b68-51a6-4cb1-a612-258e5bd7c75a)
Version 5.3.0 doesn't work either

**Comment by Horus-K** [comment]
metricsExporterType = PROM
metricsPromExporterPort = 5557
metricsPromExporterHost = 0.0.0.0    Must be configured to work

**Comment by iamgd67** [comment]
closed by https://github.com/apache/rocketmq/pull/7705

**Comment by xukeawsl** [comment]
为什么按照上面的方法能够正常访问了，但是 proxy.log 里面一直都还是 "metricsExporterType":"DISABLE" 呢
