### ISSUE TITLE
[NameServer启动失败] JDK17启动NameServer时失败 

### ISSUE THREAD

**Issue by PottermoreIron** [apache/rocketmq#7495]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Windows 10
JDK17

### RocketMQ version

5.1.4

### JDK Version

Oracle JDK17

### Describe the Bug

在bin目录下启动mqnamesrv.cmd时报错：
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Steps to Reproduce

在RocketMQ安装目录下启动mqnamesrv.cmd报错

### What Did You Expect to See?

NameServer启动成功，终端输出：The Name Server boot success. serializeType=JSON, address 0.0.0.0:9876

### What Did You See Instead?

Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit

### Additional Context

应该是JDK版本的问题，查询了网上的资料，发现由于GC相关机制的改变，RocketMQ脚本的配置没有配合JDK高版本。我找到了一篇博客http://www.fastrabbit.cn/articles/42.
根据博客修改了cmd，最后NameServer启动成功。但还是希望RocketMQ能支持JDK高版本，毕竟没法保证每个项目都使用JDK8

**Comment by francisoliverlee** [comment]
linux平台的启动脚本已经适配了不同的jdk使用不同的JAVA_OPT, 主要代码体现：
https://github.com/apache/rocketmq/blob/develop/distribution/bin/runserver.sh#L83-L98

windows平台的启动脚本：https://github.com/apache/rocketmq/blob/develop/distribution/bin/runserver.cmd#L30 没有区分， 导致一些jdk启动失败。

可以尝试根据linux平台启动脚本， 修改下windows平台的启动脚本， 欢迎提交PR

**Comment by joeCarf** [comment]
> linux平台的启动脚本已经适配了不同的jdk使用不同的JAVA_OPT, 主要代码体现： https://github.com/apache/rocketmq/blob/develop/distribution/bin/runserver.sh#L83-L98
> 
> windows平台的启动脚本：https://github.com/apache/rocketmq/blob/develop/distribution/bin/runserver.cmd#L30 没有区分， 导致一些jdk启动失败。
> 
> 可以尝试根据linux平台启动脚本， 修改下windows平台的启动脚本， 欢迎提交PR

I would like to submit a pr

**Comment by joeCarf** [comment]
https://github.com/apache/rocketmq/pull/7507 Hi, plz help review this pr. Because I'm poor in Windows cmd files, and do not have env to test it. @francisoliverlee @PottermoreIron
