### ISSUE TITLE
[Enhancement] default clientCallbackExecutorThreads setting cause massive threads

### ISSUE THREAD

**Issue by metaphor** [apache/rocketmq#7499]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

1. a new instance of NettyRemotingClient is created whenever a Consumer started.
2. NettyRemotingClient use NettyClientConfig.clientCallbackExecutorThreads (which is Runtime.getRuntime().availableProcessors() by default) to init the underlying so called callback thread pools.
3. if there is 20 consumers/topics and 8 cores, the application will create 160 threads. most of them are in waiting state.

this causes performance issues (slow startup) and waste of resources( a lot of waiting threads).

### Motivation

predicable resources will make the application stable and resources aware in clould native environment.

### Describe the Solution You'd Like

I am not sure if it's ok to share one underlying netty instance/event loop instead creating new one each time. 

### Describe Alternatives You've Considered

No

### Additional Context

![image](https://github.com/apache/rocketmq/assets/705607/c8a45669-85ab-41ff-838c-6f46318d7967)
![image](https://github.com/apache/rocketmq/assets/705607/a6785331-d845-4204-88c5-c9d7ecc93f3a)
![image](https://github.com/apache/rocketmq/assets/705607/0e0c4935-b5b7-47fe-a61b-58d1241bb37e)

_No response_

**Comment by xiaoxiangyeyu0** [comment]
I have also encountered this situation. How can I solve it
