### ISSUE TITLE
[Bug] Lock granularity issue causing LMQ message loss

### ISSUE THREAD

**Issue by lzkisok** [apache/rocketmq#7511]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Centos 7

### RocketMQ version

RMQ 5.1.4

### JDK Version

JDk 1.8

### Describe the Bug

1，当并发发送两条MQ消息，设置相同的INNER_MULTI_DISPATCH，相当于DefaultMQProducer并发发送了两条同一个LMQ的消息（消息的LMQ相同，内容不同）。
2，当这两条消息被发送到两个的MessageQuene 时，消息的queneId不同，topicQueueKey是topic-queneId，topicQueueLock.lock(topicQueueKey) 是锁各自queneId的，所以两条消息是并发处理的。
3，在两条消息并发处理时，defaultMessageStore.assignOffset(msg) 会同时从QueueOffsetOperator拿到LMQ的queneOffste，这时并发拿到的queneOffst相同，导致两条LMQ消息的INNER_MULTI_QUEUE_OFFSET 相同，LMQ 消息的offset重复
4，LMQ消息的INNER_MULTI_QUEUE_OFFSET相同时，RocketMQ-mqtt无法正常拉取和消费。

### Steps to Reproduce

1，DefaultMQProducer并发发送两条相同LMQ的消息（消息的LMQ相同，内容不同）如：
String secondTopic = "/r7";
setLmq(msg, new HashSet<>(Arrays.asList(TopicUtils.wrapLmq(firstTopic, secondTopic))));
2. 观察RMQ 日志，确定两个消息的MessageQuene不同。
3. mqtt客户端消费，只消费到一条。

### What Did You Expect to See?

在消息并发，且MessageQuene不同时，能正确设置LMQ消息的INNER_MULTI_QUEUE_OFFSET

### What Did You See Instead?

两条LMQ消息的INNER_MULTI_QUEUE_OFFSET 相同，LMQ 消息的offset重复

### Additional Context

![image](https://github.com/apache/rocketmq/assets/24490175/276df455-f274-4155-9350-4a7d1ca6ba34)
如上图：两条消息的INNER_MULTI_QUEUE_OFFSET相同
![image](https://github.com/apache/rocketmq/assets/24490175/27e491d9-8277-48f2-870f-bd172a6da371)
如上图：在DefaultMQProducer并发发送两条相同LMQ的消息（消息的LMQ相同，内容不同），这里的锁，对LMQ不适用。
发送的消息的MessageQuene不同时，defaultMessageStore.assignOffset(msg)是并发执行的，给两条LMQ消息设置了相同的INNER_MULTI_QUEUE_OFFSET

**Comment by RongtongJin** [comment]
There is indeed such a bug, and I also found the same issue when writing this [PR](https://github.com/apache/rocketmq/pull/6571).

**Comment by lzkisok** [comment]
我们看代码找到了一个暂时的解决方式，将同一个LMQ的消息，始终发送到同一个MessageQuene中，让topic+queneid的锁能生效，如图：
![image](https://github.com/apache/rocketmq/assets/24490175/feb00e5e-b631-4ed0-9db6-0eaba7959ef0)
实际使用过程中，可以LMQ可以根据queneId分片，让锁生效
