### ISSUE TITLE
Unit Test unstable?

### ISSUE THREAD

**Issue by Jason918** [apache/rocketmq#752]
**BUG REPORT**

1. Please describe the issue you observed:
run `mvn test` but did not pass, There is the error info: 

> Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 0.012 sec <<< FAILURE! - in org.apache.rocketmq.acl.plain.PlainAccessValidatorTest
> validateConsumeMessageBackTest(org.apache.rocketmq.acl.plain.PlainAccessValidatorTest)  Time elapsed: 0.008 sec  <<< ERROR!
> org.apache.rocketmq.acl.common.AclException: src/test/resources//conf/plain_acl_null.yml file  is not data
> 	at org.apache.rocketmq.acl.plain.PlainAccessValidatorTest.init(PlainAccessValidatorTest.java:46)
> 

2. Please tell us about your environment:
java version "1.8.0_91"
mac os 10.14.2

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
no

**Comment by zongtanghu** [comment]
Actually,it's a issue for acl model if developer don't config the ROCKET_HOME path.I will fix it in a new pr.Thanks, @Jason918
