### ISSUE TITLE
[Bug] 无法启动Broker+Proxy

### ISSUE THREAD

**Issue by HappyAxin** [apache/rocketmq#7520]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [x] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

CentOS 7

### RocketMQ version

5.1.4

### JDK Version

JDK 1.8

### Describe the Bug

正常按步骤启动
![image](https://github.com/apache/rocketmq/assets/46963688/1b3422d2-3e39-46db-a59f-350a3e73e329)
输入测试指令，无法创建消息

### Steps to Reproduce

见上图

### What Did You Expect to See?

应该是成功创建1000条消息，而且启动的proxy日志也正常启动

### What Did You See Instead?

```log
org.apache.rocketmq.client.exception.MQClientException: No route info of this topic: TopicTest
See https://rocketmq.apache.org/docs/bestPractice/06FAQ for further details.
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:842)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1526)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1468)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.sendDirect(DefaultMQProducer.java:681)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:393)
        at org.apache.rocketmq.example.quickstart.Producer.main(Producer.java:78)
```
![image](https://github.com/apache/rocketmq/assets/46963688/b9c6b35e-ff25-48c2-bf5d-9fb1c9408438)

### Additional Context

如果我不用broker+proxy启动，只使用broker启动的话，就可以正常的产生消息和消费消息，不知道是我哪里还没有配置好么？或者是个bug？

**Comment by HappyAxin** [comment]
https://rocketmq.apache.org/zh/docs/bestPractice/06FAQ#4-%E9%94%99%E8%AF%AF的7并不起作用
![image](https://github.com/apache/rocketmq/assets/46963688/0adbca99-e316-4952-a020-ea93ce1e5315)
![image](https://github.com/apache/rocketmq/assets/46963688/5cb814c4-e11f-429a-a3ea-27d1dbcb98e8)

**Comment by francisoliverlee** [comment]
run `bin/mqadmin clusterList -n 127.0.0.1:9876` to check broker and namesrv started or not

**Comment by HappyAxin** [comment]
> run `bin/mqadmin clusterList -n 127.0.0.1:9876` to check broker and namesrv started or not

![image](https://github.com/apache/rocketmq/assets/46963688/4ad8e5ae-44dd-49be-881d-76f0a6dfb1a0)
好像还是不行

**Comment by HappyAxin** [comment]
> run `bin/mqadmin clusterList -n 127.0.0.1:9876` to check broker and namesrv started or not
proxy启动时报错
![image](https://github.com/apache/rocketmq/assets/46963688/c06a6127-a218-4f92-80c3-0f19d448a9f0)

**Comment by HappyAxin** [comment]
> > run `bin/mqadmin clusterList -n 127.0.0.1:9876` to check broker and namesrv started or not
> 
> proxy启动时报错 ![image](https://user-images.githubusercontent.com/46963688/279560801-c06a6127-a218-4f92-80c3-0f19d448a9f0.png)

系统是64位，之前的人装的是32位的Java，版本对不上，修改Java版本就行了

**Comment by lvgitt** [comment]
> run `bin/mqadmin clusterList -n 127.0.0.1:9876` to check broker and namesrv started or not

![Image](https://github.com/user-attachments/assets/da9d3ca4-7324-40fa-93d4-85759aaed8dc)
我遇到了上面同样的问题，运行你给的命令提示这个
