### ISSUE TITLE
[Bug] The interface definition of queryMessage is not clear, and the query result may exceed the maxNum passed.

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq#7526]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

none

### RocketMQ version

4.x, 5.x

### Describe the Bug

When multiple brokers are involved, the internal implementation of this SDK is to query simultaneously and aggregate the results. In this way, each broker may return up to 64 records. Currently, there is no truncation in place for the final result, so it may exceed the parameter setting.

### Steps to Reproduce

review the code

### What Did You Expect to See?

return size <=maxNum

### What Did You See Instead?

return size > maxNum

**Comment by lizhimins** [comment]
There are also some bug with the current local disk Index design, such as filtering when hashing, which results in incorrect number of returned message num.
