### ISSUE TITLE
Does the project not verify the AccessKey at startup?

### ISSUE THREAD

**Issue by zhouixi** [apache/rocketmq#7529]
### Is Your Feature Request Related to a Problem?

spring boot :
`   @Bean
    public Consumer getCommonConsumer()  {
        Consumer consumer;
        try {
            Properties consumerProperties = rocketConfig.getProperties();
            consumerProperties.setProperty(PropertyKeyConst.GROUP_ID, rocketConfig.getCommonGroupId());
            log.info("rocketConfig{}",rocketConfig);
            consumer = ONSFactory.createConsumer(consumerProperties);
            String tags = ConsumerTags.getTags();
            consumer.subscribe(rocketConfig.getTopicsCommon(), tags, commonConsumeListenerHandle);
            consumer.start();
        }catch (Exception e){
            throw new RuntimeException(e);
        }
        return consumer;
}
`

`  RocketConfig
    @Value("${ali.access.key.id}")
    private String aliAccessKeyId;
    @Value("${ali.access.key.secret}")
    private String aliAccessKeySecret;

   public Properties getProperties(){
        Properties producerProperties = new Properties();
        producerProperties.setProperty(PropertyKeyConst.AccessKey, this.aliAccessKeyId);
        producerProperties.setProperty(PropertyKeyConst.SecretKey, this.aliAccessKeySecret);
        producerProperties.setProperty(PropertyKeyConst.NAMESRV_ADDR, this.ONSAddress);
        return producerProperties;
    }
`
Why does spring boot not verify AccessKey and aliAccessKeySecret during startup? It will cause the groupId of Alibaba Cloud rocket console.

Can't find the registered consumer, cause the producer to push the message, the message will always be in mq, will be checked when sent, or am I wrong?

 

### Describe the Solution You'd Like

Check AccessKey and SecretKey at startup to throw an exception ahead of time

### Describe Alternatives You've Considered

Check AccessKey and SecretKey at startup to throw an exception ahead of time

**Comment by humkum** [comment]
There's no permission check when client startup, and permission check only occurred in broker processing rpc request, so permission error would carrying in response, and would print to the log file `~/logs/rocketmqlogs/rocketmq_client.log`. You could find error message in log file to check whether the accessKey and secretKey is correct.As follows:

![image](https://github.com/apache/rocketmq/assets/50660789/c5d8f920-dff9-4808-8e38-115458c91953)
