### ISSUE TITLE
org.apache.rocketmq.client.impl.MQClientAPIImpl#getBrokerClusterAclInfo 获取版本空指针

### ISSUE THREAD

**Issue by liuxugithub** [apache/rocketmq#7533]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos7

### RocketMQ version

5.1.3

### JDK Version

1.8

### Describe the Bug

获取broker中的acl文件版本号抛空指针异常， 响应头里解析的版本字段为空

![image](https://github.com/apache/rocketmq/assets/26819541/cdf7d92b-9095-46c7-9743-92bcedc27888)

### Steps to Reproduce

java.lang.NullPointerException
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerClusterAclInfo(MQClientAPIImpl.java:498)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineBrokerClusterAclVersionInfo(DefaultMQAdminExtImpl.java:303)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineBrokerClusterAclVersionInfo(DefaultMQAdminExt.java:222)

### What Did You Expect to See?

预期得到acl的版本号，同步更新集群的acl文件

### What Did You See Instead?

异常，调整需要重写，很麻烦

**Comment by drpmma** [comment]
https://github.com/apache/rocketmq/blob/00965d8c11833237d5c9cd925664a1c456493cee/acl/src/main/java/org/apache/rocketmq/acl/AccessValidator.java#L70-L76
