### ISSUE TITLE
[Bug] After a consumer unsubscribes from a topic, the message queue consumed by that consumer cannot be reassigned

### ISSUE THREAD

**Issue by daizhenyu** [apache/rocketmq#7556]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

windows11

### RocketMQ version

4.8.0；5.1.0

### JDK Version

jdk8

### Describe the Bug

消费者取消订阅topic后，该消费者消费的消息队列不能被重分配
![image](https://github.com/apache/rocketmq/assets/67902793/0355f9b9-dcf8-41a1-adcc-67c076381cdf)

### Steps to Reproduce

消费者组的其中一个消费者取消订阅topic，其他消费者正常消费，但是取消订阅topic的消费者消费的队列确不会被重平衡给其他消费者。

### What Did You Expect to See?

希望有可以重平衡队列给其他消费者的能力，同时取消订阅的消费者不需要shutdown

### What Did You See Instead?

nothing

**Comment by francisoliverlee** [comment]
try disable consume
![image](https://github.com/apache/rocketmq/assets/5908412/ee357152-3894-4757-8043-48b77a7daa9f)

**Comment by daizhenyu** [comment]
我希望可以从java 客户端处理，目前使用org.apache.rocketmq.client.impl.factory.MQClientInstance#unregisterConsumer方法可以从消费者组移除。
