### ISSUE TITLE
broker重启偶发topic perm权限被修改为4

### ISSUE THREAD

**Issue by LittleBoy18** [apache/rocketmq#7600]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

k8s

### RocketMQ version

5.1.0 dledger模式

### Describe the Bug

<img width="1214" alt="image" src="https://github.com/apache/rocketmq/assets/18388649/ab0105f0-617e-4f6e-9361-aae898fd8bc7">
namesrv日志有批量修改了topic perm为4

### Steps to Reproduce

在k8s环境中，使用了远程存储不停的重启broker

### What Did You Expect to See?

topic perm权限为6

### What Did You See Instead?

偶发topic perm全部更改为了4

### Additional Context

<img width="1105" alt="image" src="https://github.com/apache/rocketmq/assets/18388649/7af9cf8f-4cd7-42e3-bbfd-6022167e7e4e">

namesrv注册broker代码中有看到Wipe write的逻辑，但是不太理解这个isPrimeSlave

**Comment by francisoliverlee** [comment]
ref: https://github.com/apache/rocketmq/pull/7661
