### ISSUE TITLE
[Bug] Flaky Test RocksDBMessageStoreTest.testMaxOffset

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#7614]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

CI

### RocketMQ version

CI

### JDK Version

CI

### Describe the Bug

RocksDBMessageStoreTest.testMaxOffset:625 expected:<[3]L> but was:<[1]L>

https://github.com/apache/rocketmq/actions/runs/7083756493/job/19276717683

### Steps to Reproduce

See CI

### What Did You Expect to See?

Test should pass 

### What Did You See Instead?

Test case failed

**Comment by yp969803** [comment]
```
  public void testMaxOffset() throws InterruptedException {
        if (notExecuted()) {
            return;
        }
        int firstBatchMessages = 3;
        int queueId = 0;
        messageBody = storeMessage.getBytes();

        assertThat(messageStore.getMaxOffsetInQueue(messageTopic, queueId)).isEqualTo(0);

        for (int i = 0; i < firstBatchMessages; i++) {
            final MessageExtBrokerInner msg = buildMessage();
            msg.setQueueId(queueId);
            messageStore.putMessage(msg);
        }

        while (messageStore.dispatchBehindBytes() != 0) {
            TimeUnit.MILLISECONDS.sleep(1);
        }

        assertThat(messageStore.getMaxOffsetInQueue(messageTopic, queueId)).isEqualTo(firstBatchMessages);
```

Didn't find anything wrong in this code dont know why the test is failing
