### ISSUE TITLE
[Feature] 何时能开发适配新版本rocketmq  的python sdk？

### ISSUE THREAD

**Issue by wylycool** [apache/rocketmq#7624]
### Is Your Feature Request Related to a Problem?

现在apache在github上的python sdk是rocketmq-client-python 2.0.0，是19年的包，距今已经四五年了，可惜新版rocketmq很多功能和参数都未封装，无法在python中使用，我使用的是python3.11，只能简单的发送和消费任务，这个旧包连重试次数都不能设置，想问是否近期有计划集中更新一波python sdk？

### Describe the Solution You'd Like

封装适配新版rocketmq的python sdk

### Describe Alternatives You've Considered

暂无

**Comment by RongtongJin** [comment]
Please refer to the progress of this [repo](https://github.com/apache/rocketmq-clients).
