### ISSUE TITLE
[Enhancement]  Add return value for sendHeartbeat related method

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq#7642]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

 Add return value for sendHeartbeat related method

### Motivation

 Add return value for sendHeartbeat related method for getting result.

### Describe the Solution You'd Like

 Add return value for sendHeartbeat related method

### Describe Alternatives You've Considered

No

**Comment by aryan19926** [comment]
is this issue open?
