### ISSUE TITLE
[Bug] Incorrect result otlp collect when send delay message

### ISSUE THREAD

**Issue by zhiliatom** [apache/rocketmq#7658]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

contos 7

### RocketMQ version

5.1.5.SNAPSHOT

### JDK Version

jdk8

### Describe the Bug

![image](https://github.com/apache/rocketmq/assets/87265072/747e7c50-6d50-4de1-a946-b920497daef0)
send 1000 messages to the topic "test", and message typs incorrect

### Steps to Reproduce

1) send delay message
msg.setDelayTimeMs(3000);
2) search by prometheus

### What Did You Expect to See?

message type is "delay"

### What Did You See Instead?

message type is "normal"

**Comment by leizhiyuan** [comment]
when get message type in brokermetrics, there losts PROPERTY_TIMER_DELAY_MS
