### ISSUE TITLE
[Enhancement] slave sync acl

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq#7672]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

slave sync acl

### Motivation

slave sync acl

### Describe the Solution You'd Like

slave sync acl

### Describe Alternatives You've Considered

slave sync acl

### Additional Context

org.apache.rocketmq.broker.slave.SlaveSynchronize#syncAll

```
 this.syncTopicConfig();
        this.syncConsumerOffset();
        this.syncDelayOffset();
        this.syncSubscriptionGroupConfig();
        this.syncMessageRequestMode();

        if (brokerController.getMessageStoreConfig().isTimerWheelEnable()) {
            this.syncTimerMetrics();
        }
```

is there any reason we do not sync acl config?

**Comment by cserwen** [comment]
Maybe it's because the adminClient will send RPC requests to all Brokers to update the acl config.

**Comment by leizhiyuan** [comment]
> Maybe it's because the adminClient will send RPC requests to all Brokers to update the acl config.

Hmm, currently we also create the full amount during creation. However, upon further thought, it seems reasonable that it should be synchronized here as well.

**Comment by cserwen** [comment]
+1在 2023年12月27日，20:23，Lei Zhiyuan ***@***.***> 写道：﻿

Maybe it's because the adminClient will send RPC requests to all Brokers to update the acl config.

Hmm, currently we also create the full amount during creation. However, upon further thought, it seems reasonable that it should be synchronized here as well.
