### ISSUE TITLE
[Bug] The bornTime is not set when using the popMessage API in cluster mode.

### ISSUE THREAD

**Issue by dingshuangxi888** [apache/rocketmq#7686]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

develop

### JDK Version

Java 11

### Describe the Bug

The bornTime is not set when using the popMessage API in cluster mode, So it will cause "timeout too much" error. And will never receive any messages.

![image](https://github.com/apache/rocketmq/assets/5010921/5d698a5c-b9d4-499e-9c14-757720fbce67)

### Steps to Reproduce

Use gRPC client to receive  message by Proxy, you can not receive any messages.

### What Did You Expect to See?

When using the gRPC client to receive messages, it will return correctly.

### What Did You See Instead?

When using the gRPC client to receive messages, it will return correctly.

**Comment by YalikWang** [comment]
Why was this commit reverted?
