### ISSUE TITLE
The default topic permission does not read from the configuration file, but directly   from the code.

### ISSUE THREAD

**Issue by glinggit** [apache/rocketmq#769]
Line 133 in PlainPermissionLoader.java does not read the variable values in the configuration file.
The code is:
byte ownedPerm = isGroup ? needCheckedAccess.getDefaultGroupPerm() :
needCheckedAccess.getDefaultTopicPerm();

**Comment by zongtanghu** [comment]
Firstly,you should put forward a issue according to issue's template.
