### ISSUE TITLE
[Bug] can't open controller metricsExporter

### ISSUE THREAD

**Issue by baijun44** [apache/rocketmq#7697]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

OS: ubuntu 22.04

### RocketMQ version

rocketmq 5.1.4

### JDK Version

openjdk 1.8

### Describe the Bug

add a config "metricsExporterType = PROM" for controller, but it doesn't work.I read source file(ControllerConfig) and found this field 'metricsExporterType' has no 'set method' by passing String type parameter.

### Steps to Reproduce

1.add a config "metricsExporterType = PROM"
2.start controller
3.open localhost:5557

### What Did You Expect to See?

can open localhost:5557

### What Did You See Instead?

can't open localhost:5557

**Comment by RongtongJin** [comment]
@baijun44 Could you submit a PR to fix the issue？

**Comment by baijun44** [comment]
> @baijun44 Could you submit a PR to fix the issue？

Yes! I will.

**Comment by baijun44** [comment]
@RongtongJin Please help me review.Thanks!

**Comment by iamgd67** [comment]
dumplicate to #7491
