### ISSUE TITLE
[Bug] There was an issue when changing from 2 master and 4 slave to 1 master and 4 slave

### ISSUE THREAD

**Issue by TickFairy** [apache/rocketmq#7704]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

CentOs 7.9
k8s 1.24
docker 20.10.16

### RocketMQ version

5.1.3

### Describe the Bug

controller模式 2主4从 切换为1主4从配置从节点因为broker meta 冲突无法加入

### Steps to Reproduce

1. 启用controller 模式
2. 启动2主4从  broker-0 和 broker-1，两个配置文件只有brokerName的区别
broker-0 主和从的配置文件如下
broker-0.conf    
```
  brokerIP1=xxxx
  brokerId=-1
  brokerRole=Slave
  brokerName=broker-0
```
broker-1 主和从的配置文件如下
broker-1.conf

```
  brokerIP1=xxxx 
  brokerId=-1
  brokerRole=Slave
  brokerName=broker-1
```
3. 启动后运行正常
4. 调整broker-1.conf的brokerName=broker-0，也就是移除一个主节点将他们都设置为broker-0的从节点，重启后查看broker.log报错
The brokerName: broker-1 in broker metadata is different from brokerName: broker-0 in broker config

### What Did You Expect to See?

启动命令指定了brokerConfig，但contoller没有重新设置brokerId ，而且时报和boker metada冲突，这里broker meta 不会根据brokerconfig更新？

### What Did You See Instead?

-

**Comment by RongtongJin** [comment]
需要清理store， 特别是这个~/store/brokerIdentity，这个标识了controller 分配 broker 的身份，如果改变后需要清理。
