### ISSUE TITLE
[Doc] Documentation Related 文档描述“队列数暂不支持修改” 是不是有问题？

### ISSUE THREAD

**Issue by lancemmt** [apache/rocketmq#7706]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

在 [这个](https://rocketmq.apache.org/zh/docs/domainModel/03messagequeue/#%E8%A1%8C%E4%B8%BA%E7%BA%A6%E6%9D%9F) 文档中，有如下描述：

> 每个主题下会由一到多个队列来存储消息，每个主题对应的队列数与消息类型以及实例所处地域（Region）相关，队列数暂不支持修改。

其中的 “队列数暂不支持修改” 是不是有问题？这个队列数应该是支持修改的吧？

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by drpmma** [comment]
支持修改的
