### ISSUE TITLE
A question about MessageSysFlag . What if I need a type for example A type value is 16 ?

### ISSUE THREAD

**Issue by Ah39** [apache/rocketmq#772]
https://github.com/apache/rocketmq/blob/46ac065446de5a53e8cc3f8a010b9fe6147e9d53/common/src/main/java/org/apache/rocketmq/common/sysflag/MessageSysFlag.java#L20-L33

what should do I do , if I need add new type.
And getTransactionValue why & TRANSACTION_ROLLBACK_TYPE ?? 
what is reason for ( & TRANSACTION_ROLLBACK_TYPE )

**Comment by ymwneu** [comment]
Every bit has it's specific meaning. Method getTransactionValue only concern the third and fourth bits, so the method & TRANSACTION_ROLLBACK_TYPE.

**Comment by Ah39** [comment]
if I add a new type == 0x4 << 3 ( 16 ) , 
the new type dont work right ( return flag & TRANSACTION_ROLLBACK_TYPE )
what the real meaning of  ( return flag & TRANSACTION_ROLLBACK_TYPE )

**Comment by ymwneu** [comment]
> if I add a new type == 0x4 << 3 ( 16 ) ,
> the new type dont work right ( return flag & TRANSACTION_ROLLBACK_TYPE )
> what the real meaning of ( return flag & TRANSACTION_ROLLBACK_TYPE )

If you want a new bit to express a new mean, just check the specific bit.  Method getTransactionValue only concern the third and fourth bits, there is nothing to do with your new bit.
