### ISSUE TITLE
[Bug] windows上broker启动失败 缺少引号

### ISSUE THREAD

**Issue by scwlkq** [apache/rocketmq#7731]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

windows

### RocketMQ version

4.9.4

### JDK Version

11

### Describe the Bug

![image](https://github.com/apache/rocketmq/assets/89067331/47390994-174d-4cd4-8468-c99b1588e18c)

### Steps to Reproduce

类似namesvr.cmd 对runbroker.cmd的命令加上英文引号set "JAVA_OPT=%JAVA_OPT% -cp "%CLASSPATH%""
![image](https://github.com/apache/rocketmq/assets/89067331/1717ba1b-b0e2-42a8-b9f5-a0f3b850654c)

### What Did You Expect to See?

提个pr解决一下

### What Did You See Instead?

专门针对windows系统的二进制文件？

**Comment by humkum** [comment]
You can check whether your RocketMQ_HOME contains spaces

**Comment by scwlkq** [comment]
> You can check whether your RocketMQ_HOME contains spaces

I have checked and there are no spaces. In fact, I encountered this problem when searching and found many blogs like this, so I thought it might be a small bug

**Comment by Camio1945** [comment]
@RongtongJin @scwlkq 你们是不是只改了 else 分支，没有改 [if 分支](https://github.com/apache/rocketmq/blob/551c8c3d0da588ec8c358f3e1b5494031ca153d4/distribution/bin/runbroker.cmd#L47)？我的 if 分支报了同样的错。
