### ISSUE TITLE
[Enhancement] Simplify code checks using Optional in ClientRequestProcessor#getRouteInfoByTopic method

### ISSUE THREAD

**Issue by mxsm** [apache/rocketmq#7747]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

![image](https://github.com/apache/rocketmq/assets/15797831/fea08cdd-369d-4ef8-83d1-4ed1d2ae7283)

### Motivation

 Simplify code checks using Optional in ClientRequestProcessor#getRouteInfoByTopic method

### Describe the Solution You'd Like

 Simplify code checks using Optional 

### Describe Alternatives You've Considered

Simplify the code.

**Comment by ChineseTony** [comment]
@mxsm  hello, I think it's can write to 
```
  boolean standardJsonOnly = Boolean.TRUE.equals(requestHeader.getAcceptStandardJsonOnly());
  if (request.getVersion() >= MQVersion.Version.V4_9_4.ordinal() || standardJsonOnly) {
```
