### ISSUE TITLE
make mqadmin usage information more friendly to user

### ISSUE THREAD

**Issue by husterxsp** [apache/rocketmq#776]
When I run `sh bin/mqadmin updateTopic -t topicA `, I’m confused because i get  

```shell
usage: mqadmin updateTopic [-b <arg>] [-c <arg>] [-h] [-n <arg>] [-o <arg>] [-p <arg>] [-r <arg>] [-s <arg>] -t <arg> [-u <arg>] [-w <arg>]
```

The usage tell me that I just need to set `-t` option, but I don't know why it doesn't run successfully.

So I look the source code `UpdateTopicSubCommand.java`，and I find that one of  `-b` and `-c` should be required.

So I think 

https://github.com/apache/rocketmq/blob/46ac065446de5a53e8cc3f8a010b9fe6147e9d53/tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicSubCommand.java#L45-L52

should be changed to 

```java
// UpdateTopicSubCommand.java
OptionGroup optionGroup = new OptionGroup();

Option opt = new Option("b", "brokerAddr", true, "create topic to which broker");
optionGroup.addOption(opt);

opt = new Option("c", "clusterName", true, "create topic to which cluster");
optionGroup.addOption(opt);

optionGroup.setRequired(true);
options.addOptionGroup(optionGroup);
```

After change, the usage will be

```shell
usage: mqadmin updateTopic -b <arg> | -c <arg>  [-h] [-n <arg>] [-o <arg>] [-p <arg>] [-r <arg>] [-s <arg>] -t <arg> [-u <arg>] [-w <arg>]
```

**Comment by ymwneu** [comment]
You're right! I think you can propose a pull request to fix it.
