### ISSUE TITLE
[Bug] setStartDetectorEnable Not effective

### ISSUE THREAD

**Issue by louyaning** [apache/rocketmq#7813]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos6.6

### RocketMQ version

5.1.4-release

### JDK Version

java version "1.8.0_121"

### Describe the Bug

setStartDetectorEnable(true) 不生效，并不能开启探活检测

### Steps to Reproduce

   ```
        DefaultMQProducer defaultMQProducer = new DefaultMQProducer("testProducer", true);
        defaultMQProducer.setNamesrvAddr(nameServer);
        defaultMQProducer.setProducerGroup("testProducer");
        defaultMQProducer.setSendMsgTimeout(3000);
        defaultMQProducer.setSendLatencyFaultEnable(true);
        defaultMQProducer.setStartDetectorEnable(true);
        defaultMQProducer.setRetryTimesWhenSendFailed(2);
        defaultMQProducer.setInstanceName("testProducer");
        defaultMQProducer.start();```


### What Did You Expect to See?

`startDetectorEnable` 被设置成 `true` 

### What Did You See Instead?

`startDetectorEnable` 还是`false`

### Additional Context

临时解决方案 在new DefaultMQProducer 时先执行
 System.setProperty("com.rocketmq.startDetectorEnable","true");
这样可能会把不想开启的生产端也开启。

**Comment by leizhiyuan** [comment]
是个bug，mqFaultStrategy 这个在DefaultMQProducerImpl 的构造函数中初始化，这时候setStartDetectorEnable 这个值还没有。所以后续再设置的时候，已经没用了。
