### ISSUE TITLE
[Bug] mqAdmin consumerProgress execute error: No topic route info in name server for the topic: %RETRY%xxx

### ISSUE THREAD

**Issue by Yelijah** [apache/rocketmq#7830]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

macos 13.2.1  cpu:x86_64

### RocketMQ version

server version: 5.1.4
java client version: 5.0.5

### JDK Version

openjdk version "1.8.0_265"

### Describe the Bug

i create a topic , a consumeGroup by admintool and  a consumer by java client. 
The consumer can accept message successfully, but i can't use ./mqadmin consumerProgress to query the consume process. Here is the error:
```
./bin/mqadmin consumerProgress -n 192.168.250.2:9876 -g fifoRetryConsumerGroup -s true
org.apache.rocketmq.tools.command.SubCommandException: ConsumerProgressSubCommand command failed
	at org.apache.rocketmq.tools.command.consumer.ConsumerProgressSubCommand.execute(ConsumerProgressSubCommand.java:262)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:165)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:115)
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: %RETRY%fifoRetryConsumerGroup
See https://rocketmq.apache.org/docs/bestPractice/06FAQ for further details.
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:2041)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:2012)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineTopicRouteInfo(DefaultMQAdminExtImpl.java:590)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineConsumeStats(DefaultMQAdminExtImpl.java:436)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineConsumeStats(DefaultMQAdminExt.java:307)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineConsumeStats(DefaultMQAdminExt.java:300)
	at org.apache.rocketmq.tools.command.consumer.ConsumerProgressSubCommand.execute(ConsumerProgressSubCommand.java:116)
	... 2 more
```

### Steps to Reproduce

step 1: create a topic and consumeGroup by mqadmin:
```
./bin/mqadmin updateTopic -c standalone -t fifoTopic -o true -n 127.0.0.1:9876 -a +message.type=FIFO
./bin/mqadmin updateSubGroup -n 127.0.0.1:9876 -c standalone -g fifoConsumerGroup -o true
```
step 2: create a consumer by java client
```java
        PushConsumer consumer = provider.newPushConsumerBuilder()
                .setConsumerGroup(consumerGroup)
                .setClientConfiguration(clientConfiguration)
                .setConsumptionThreadCount(1) 
                .setSubscriptionExpressions(Collections.singletonMap(topic, new FilterExpression()))
                .setMessageListener(new MessageListener() {
                    private final Random random = new Random();
                    @Override
                    public ConsumeResult consume(MessageView messageView) {
                        CommonUtils.log("receive msg:%s", messageView);
                        CommonUtils.sleep(random.nextInt(5));
                        if (retryMsg != null && ByteBufferUtils.toString(messageView.getBody()).startsWith(retryMsg)) {
                            CommonUtils.log("consume failed msg:%s", messageView);
                            return ConsumeResult.FAILURE;
                        }
                        return ConsumeResult.SUCCESS;
                    }}
                ).build();
        Thread.sleep(3600 * 1000);
        consumer.close();
```

step 3: mqadmin consumerProgress -n 192.168.250.2:9876 -g fifoRetryConsumerGroup

### What Did You Expect to See?

I want the commad consumerProgress can be executed successfully.

### What Did You See Instead?

the commad consumerProgress error

**Comment by Yelijah** [comment]
> Try using `mqadmin consumerProgress -n 192.168.250.2:9876 -g fifoRetryConsumerGroup -t fifoTopic`

The error didn't change:
```
./bin/mqadmin consumerProgress -n 192.168.250.2:9876 -g fifoRetryConsumerGroup -t fifoTopic
org.apache.rocketmq.tools.command.SubCommandException: ConsumerProgressSubCommand command failed
	at org.apache.rocketmq.tools.command.consumer.ConsumerProgressSubCommand.execute(ConsumerProgressSubCommand.java:262)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:165)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:115)
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: %RETRY%fifoRetryConsumerGroup_fifoTopic
See https://rocketmq.apache.org/docs/bestPractice/06FAQ for further details.
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:2041)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:2012)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineTopicRouteInfo(DefaultMQAdminExtImpl.java:590)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineConsumeStats(DefaultMQAdminExtImpl.java:436)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineConsumeStats(DefaultMQAdminExt.java:307)
	at org.apache.rocketmq.tools.command.consumer.ConsumerProgressSubCommand.execute(ConsumerProgressSubCommand.java:118)
	... 2 more
```

**Comment by leizhiyuan** [comment]
This is because there has been no failure yet, so the retry topic has not been generated. However, when querying, it will definitely search for the pop retry.

<img width="818" alt="image" src="https://github.com/apache/rocketmq/assets/2684384/1451d6f7-89dd-4c78-abaa-087710276171">

**Comment by leizhiyuan** [comment]
```
public TopicRouteData getTopicRouteInfoFromNameServer(final String topic, final long timeoutMillis,
        boolean allowTopicNotExist) throws MQClientException, InterruptedException, RemotingTimeoutException, RemotingSendRequestException, RemotingConnectException {
        GetRouteInfoRequestHeader requestHeader = new GetRouteInfoRequestHeader();
        requestHeader.setTopic(topic);
        RemotingCommand request = RemotingCommand.createRequestCommand(RequestCode.GET_ROUTEINFO_BY_TOPIC, requestHeader);

        RemotingCommand response = this.remotingClient.invokeSync(null, request, timeoutMillis);
        assert response != null;
        switch (response.getCode()) {
            case ResponseCode.TOPIC_NOT_EXIST: {
                if (allowTopicNotExist) {
                    log.warn("get Topic [{}] RouteInfoFromNameServer is not exist value", topic);
                }

                break;
            }
            case ResponseCode.SUCCESS: {
                byte[] body = response.getBody();
                if (body != null) {
                    return TopicRouteData.decode(body, TopicRouteData.class);
                }
            }
            default:
                break;
        }

        throw new MQClientException(response.getCode(), response.getRemark());
    }

```

if allowTopicNotExist is true, maybe we shoud not throw 

        throw new MQClientException(response.getCode(), response.getRemark());

**Comment by RongtongJin** [comment]
> ```
> public TopicRouteData getTopicRouteInfoFromNameServer(final String topic, final long timeoutMillis,
>         boolean allowTopicNotExist) throws MQClientException, InterruptedException, RemotingTimeoutException, RemotingSendRequestException, RemotingConnectException {
>         GetRouteInfoRequestHeader requestHeader = new GetRouteInfoRequestHeader();
>         requestHeader.setTopic(topic);
>         RemotingCommand request = RemotingCommand.createRequestCommand(RequestCode.GET_ROUTEINFO_BY_TOPIC, requestHeader);
> 
>         RemotingCommand response = this.remotingClient.invokeSync(null, request, timeoutMillis);
>         assert response != null;
>         switch (response.getCode()) {
>             case ResponseCode.TOPIC_NOT_EXIST: {
>                 if (allowTopicNotExist) {
>                     log.warn("get Topic [{}] RouteInfoFromNameServer is not exist value", topic);
>                 }
> 
>                 break;
>             }
>             case ResponseCode.SUCCESS: {
>                 byte[] body = response.getBody();
>                 if (body != null) {
>                     return TopicRouteData.decode(body, TopicRouteData.class);
>                 }
>             }
>             default:
>                 break;
>         }
> 
>         throw new MQClientException(response.getCode(), response.getRemark());
>     }
> ```
> 
> if allowTopicNotExist is true, maybe we shoud not throw
> 
> ```
>     throw new MQClientException(response.getCode(), response.getRemark());
> ```

Agreed, but if any modifications are made here, it is necessary to sort out all the called places to see if there are compatibility issues.

**Comment by RongtongJin** [comment]
> ```
> public TopicRouteData getTopicRouteInfoFromNameServer(final String topic, final long timeoutMillis,
>         boolean allowTopicNotExist) throws MQClientException, InterruptedException, RemotingTimeoutException, RemotingSendRequestException, RemotingConnectException {
>         GetRouteInfoRequestHeader requestHeader = new GetRouteInfoRequestHeader();
>         requestHeader.setTopic(topic);
>         RemotingCommand request = RemotingCommand.createRequestCommand(RequestCode.GET_ROUTEINFO_BY_TOPIC, requestHeader);
> 
>         RemotingCommand response = this.remotingClient.invokeSync(null, request, timeoutMillis);
>         assert response != null;
>         switch (response.getCode()) {
>             case ResponseCode.TOPIC_NOT_EXIST: {
>                 if (allowTopicNotExist) {
>                     log.warn("get Topic [{}] RouteInfoFromNameServer is not exist value", topic);
>                 }
> 
>                 break;
>             }
>             case ResponseCode.SUCCESS: {
>                 byte[] body = response.getBody();
>                 if (body != null) {
>                     return TopicRouteData.decode(body, TopicRouteData.class);
>                 }
>             }
>             default:
>                 break;
>         }
> 
>         throw new MQClientException(response.getCode(), response.getRemark());
>     }
> ```
> 
> if allowTopicNotExist is true, maybe we shoud not throw
> 
> ```
>     throw new MQClientException(response.getCode(), response.getRemark());
> ```

![image](https://github.com/apache/rocketmq/assets/21963954/bdd7c3fb-41af-4116-b4d1-e0256dc49e5f)
The exception is caught here, so if `-t` is added, at least there will be a route.

**Comment by Yelijah** [comment]
> > ```
> > public TopicRouteData getTopicRouteInfoFromNameServer(final String topic, final long timeoutMillis,
> >         boolean allowTopicNotExist) throws MQClientException, InterruptedException, RemotingTimeoutException, RemotingSendRequestException, RemotingConnectException {
> >         GetRouteInfoRequestHeader requestHeader = new GetRouteInfoRequestHeader();
> >         requestHeader.setTopic(topic);
> >         RemotingCommand request = RemotingCommand.createRequestCommand(RequestCode.GET_ROUTEINFO_BY_TOPIC, requestHeader);
> > 
> >         RemotingCommand response = this.remotingClient.invokeSync(null, request, timeoutMillis);
> >         assert response != null;
> >         switch (response.getCode()) {
> >             case ResponseCode.TOPIC_NOT_EXIST: {
> >                 if (allowTopicNotExist) {
> >                     log.warn("get Topic [{}] RouteInfoFromNameServer is not exist value", topic);
> >                 }
> > 
> >                 break;
> >             }
> >             case ResponseCode.SUCCESS: {
> >                 byte[] body = response.getBody();
> >                 if (body != null) {
> >                     return TopicRouteData.decode(body, TopicRouteData.class);
> >                 }
> >             }
> >             default:
> >                 break;
> >         }
> > 
> >         throw new MQClientException(response.getCode(), response.getRemark());
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if allowTopicNotExist is true, maybe we shoud not throw
> > ```
> >     throw new MQClientException(response.getCode(), response.getRemark());
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/21963954/305904578-bdd7c3fb-41af-4116-b4d1-e0256dc49e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODQ3ODQsIm5iZiI6MTcwOTg4NDQ4NCwicGF0aCI6Ii8yMTk2Mzk1NC8zMDU5MDQ1NzgtYmRkN2MzZmItNDFhZi00MTE2LWI0ZDEtZTAyNTZkYzQ5ZTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3NTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZWUxNGVjZWYyMmViOTZkZWYyNDM5MjdjMTRmN2VkNGNlN2RmMGZmYTU3MTc4OWFjZDdjNzQwNTg3MGM5YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6TRNTSZfMmaXMf66Qffkf7CETuAk35diJjmtikcZpD8) The exception is caught here, so if `-t` is added, at least there will be a route.

The error happened whether use -t or not.

**Comment by Yelijah** [comment]
It works well by add "-t topicName"

**Comment by chenjing1294** [comment]
```
./mqadmin consumerConnection -n IP:9876  -g GROUP
```
Always generates %RETRY%{GROUP}_{TOPIC}, never %RETRY%{GROUP}

An error will still be reported, and no -t is available.

**Comment by inetkiller** [comment]
@chenjing1294 我们也观察到rocketmq创建的重试topic的名称是%RETRY%{GROUP}_{TOPIC}这种规则，但是官方文档上描述的应该是%RETRY%{GROUP}。你查到这个问题的原因了吗？

**Comment by longchangfeng** [comment]
the same question not fixed or answered util now
