### ISSUE TITLE
[Bug] Exception when pop messages with multiple LMQ indexes

### ISSUE THREAD

**Issue by redlsz** [apache/rocketmq#7848]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

all

### RocketMQ version

develop

### Describe the Bug

NumberFormatException is thrown when pop messages with multiple LMQ indexes.

<img width="1012" alt="image" src="https://github.com/apache/rocketmq/assets/103550934/e679f718-0732-4066-9e4b-a332d4e6dc63">

### Steps to Reproduce

/

### What Did You Expect to See?

/

### What Did You See Instead?

/

**Comment by redlsz** [comment]
<img width="1188" alt="image" src="https://github.com/apache/rocketmq/assets/103550934/397440df-9c83-4026-abb8-7b38baa7de09">

The property PROPERTY_INNER_MULTI_DISPATCH and PROPERTY_INNER_MULTI_QUEUE_OFFSET may be strings containing multiple elements splitted by comma.

eg:
PROPERTY_INNER_MULTI_DISPATCH="%LMQ%lmq1,%LMQ%lmq2,%LMQ%lmq3"
PROPERTY_INNER_MULTI_QUEUE_OFFSET="1,2,3"

**Comment by leizhiyuan** [comment]
You can submit a pull request to fix this issue.
