### ISSUE TITLE
[Enhancement] if语句优化

### ISSUE THREAD

**Issue by 3424672656** [apache/rocketmq#7858]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

在梳理生产者发送消息时发现org.apache.rocketmq.client.impl. Producer的sendDefaultImpl方法中 resetIndex参数只在selectOneMessageQueue选择队列时配备，并且对后续无影响。
![image](https://github.com/apache/rocketmq/assets/125714719/77c90535-859d-4f17-a9c4-57d190a2abd5)

### Motivation

提高代码便洁度，友好度

### Describe the Solution You'd Like

所以有一个想法：可以把下面selectOneMessageQueue方法的参数resetIndex改为times!=0,代码便洁一点，（内存与性能同样好一点点）
如下：
![image](https://github.com/apache/rocketmq/assets/125714719/76fb8b82-df09-4a68-859d-ba2cc3ff6323)

### Describe Alternatives You've Considered

代码美观的同时稍微节省了它的if判断以及内存开销

**Comment by leizhiyuan** [comment]
I don't think the new modification is more aesthetically pleasing, it doesn't seem necessary to make such changes.
