### ISSUE TITLE
document too simple

### ISSUE THREAD

**Issue by xornono** [apache/rocketmq#786]
document too simple.
Documents are too few, can write detailed points, many principles, mqadmin also did not explain, configuration documentation, really bad, ah, the same MQ, look at kafka official documents.

**Comment by zongtanghu** [comment]
@xornono could you please adjust the issue template firstly?And then,some parts of rocketmq document are in the develop branch,you can look at it.

**Comment by LGerry** [comment]
I agree, too simple...
