### ISSUE TITLE
[Enhancement]  Add constructor for ProxyTopicRouteData

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq#7875]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add construtor for ProxyTopicRouteData

### Motivation

Add construtor for ProxyTopicRouteData

### Describe the Solution You'd Like

Add construtor for ProxyTopicRouteData

### Describe Alternatives You've Considered

No

**Comment by supervate** [comment]
If I deploy multi proxy-server and using different port.
e.g p1:8080,p2:8081,p3:8082
Here have a problem that when client call the p1's api to get the topic route info.
This constructor will replace all broker's address port to current proxy's port, like this:
p1:8080,p2:8080,p3:8080.
