### ISSUE TITLE
[Bug] Bug title logback.xml Incorrect configuration

### ISSUE THREAD

**Issue by heihei180** [apache/rocketmq#7879]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

ubutun 20

### RocketMQ version

dev

### JDK Version

openjdk 17

### Describe the Bug

this file  `example/src/main/resources/logback.xml` config the log file path is error.

line 23 and line 26.
like this: 
```xml

        <file>/Users/xiweng.yy/logs/nacos/perf.log</file>
        
        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <fileNamePattern>/Users/xiweng.yy/logs/nacos/perf.log.%i</fileNamePattern>
            <maxIndex>${JM.LOG.RETAIN.COUNT:-7}</maxIndex>
        </rollingPolicy>
```

i think should use 

```xml
        <file>${user.home}/logs/nacos/perf.log</file>
        
        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <fileNamePattern>${user.home}/logs/nacos/perf.log.%i</fileNamePattern>
            <maxIndex>${JM.LOG.RETAIN.COUNT:-7}</maxIndex>
        </rollingPolicy>

```

### Steps to Reproduce

run `com.alibaba.nacos.example.App#main` 

### What Did You Expect to See?

modify the log file 's path.

### What Did You See Instead?

use ${user.home} or another.

**Comment by joeCarf** [comment]
I'd like to check this out

**Comment by leizhiyuan** [comment]
<img width="623" alt="image" src="https://github.com/apache/rocketmq/assets/2684384/49cf0ac7-9ca0-4300-93ec-85b5512a6b7c">

it seems there is not config file in example path
