### ISSUE TITLE
[Bug] the topicRouter is not updated when delete topic in broker

### ISSUE THREAD

**Issue by 1782935682** [apache/rocketmq#7884]
### Before Creating the Bug Report

- [x] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

1

### RocketMQ version

release-5.2.0

### JDK Version

1.8

### Describe the Bug

The topicRouter is not updated when I delete a topic in the broker

org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl#deleteTopicInBroker

<img width="1142" alt="image" src="https://github.com/apache/rocketmq/assets/49970811/859d1696-c4bf-4653-88c6-d1b28020fca4">

<img width="1011" alt="image" src="https://github.com/apache/rocketmq/assets/49970811/8621d34e-6ea3-46fb-9804-91b377ea8478">

### Steps to Reproduce

1. create topic
2. delete topic in broker
3. query topic router

### What Did You Expect to See?

the topicRouter shoud be updated when delete topic in broker

### What Did You See Instead?

1

**Comment by xzwb** [comment]
How do you create and delete topics?

**Comment by 1782935682** [comment]
> How do you create and delete topics? dashboard or mqadmin or sdk？ I want to try to reproduce this issue

1.create with dashboard，create topic on cluster
<img width="1218" alt="image" src="https://github.com/apache/rocketmq/assets/49970811/54f71e3e-a32f-4827-9210-2f32f761a551">

2.use sdk , delete topic in one broker

org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl#deleteTopicInBroker;



        DefaultMQAdminExt mqAdminExt = new DefaultMQAdminExt(new AclClientRPCHook(new SessionCredentials("ak", "sk")), 20000);
        String name = UUID.randomUUID().toString();
        mqAdminExt.setInstanceName(name);
        mqAdminExt.setNamesrvAddr(DEFAULT_NAMESRVADDR);
        mqAdminExt.start();
        System.out.println("delete before");
        System.out.println("topicRouter" + ": " + JSON.toJSONString(mqAdminExt.examineTopicRouteInfo(TOPIC), true));
        mqAdminExt.deleteTopicInBroker(Collections.singleton(broker01), TOPIC);
        System.out.println("delete after");
        System.out.println("topicRouter" + ": " + JSON.toJSONString(mqAdminExt.examineTopicRouteInfo(TOPIC), true));

**Comment by xzwb** [comment]
ok iwill try

**Comment by xzwb** [comment]
i reproduce this issue, but i find when I restart my broker this topic has been deleted, i guess broker have some schedule to delete topic

**Comment by xzwb** [comment]
yes rocketmq delete topic Only the topic data in memory will be deleted

**Comment by leizhiyuan** [comment]
你需要继续调用 deleteTopicInNameServer

**Comment by 1782935682** [comment]
会删除topic全部路由，不能删除指定broker的路由

![LC}MTF47V)}W20S 0 1$C{I](https://github.com/apache/rocketmq/assets/49970811/6d153635-03c8-4776-a095-60cbbe7a070b)

**Comment by leizhiyuan** [comment]
你这个问题，还可以通过打开

在broker打开，enableSingleTopicRegister这个配置。
在ns 打开deleteTopicWithBrokerRegistration 这个配置来解决。可以看下这块代码。
