### ISSUE TITLE
服务端的配置文档是一点都没有吗

### ISSUE THREAD

**Issue by zzps** [apache/rocketmq#7900]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

服务端的配置文档是一点都没有吗

### RocketMQ version

服务端的配置文档是一点都没有吗

### Describe the Bug

服务端的配置文档是一点都没有吗

### Steps to Reproduce

服务端的配置文档是一点都没有吗

### What Did You Expect to See?

服务端的配置文档是一点都没有吗

### What Did You See Instead?

服务端的配置文档是一点都没有吗

**Comment by RongtongJin** [comment]
https://rocketmq.apache.org/zh/docs/4.x/parameterConfiguration/02server
这里有一些
