### ISSUE TITLE
[Doc] 文档中单词拼接错误

### ISSUE THREAD

**Issue by zzzzzhangyanqiu** [apache/rocketmq#7949]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

在[普通消息发送](https://rocketmq.apache.org/zh/docs/4.x/producer/02message1) 中，3.1部分的下述文本有错误：`同步发送等待结果最后返回SendResult，SendResut包含实际发送状态还包括SEND_OK`，SendResut应该是SendResult

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by leizhiyuan** [comment]
你可以点击页面的
<img width="268" alt="image" src="https://github.com/apache/rocketmq/assets/2684384/44ca04e2-3a98-4410-94c1-8a8a72f0e908">

编辑此页，然后pr进行对应的修改

https://github.com/apache/rocketmq-site/blob/new-official-website/docs/02-producer/02message1.md

**Comment by zzzzzhangyanqiu** [comment]
好的，我已经提交了相应的[PR](https://github.com/apache/rocketmq-site/pull/630)，这个Issues可以关闭了
