### ISSUE TITLE
[Bug] Don't set default auth metadata provider

### ISSUE THREAD

**Issue by dingshuangxi888** [apache/rocketmq#7955]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

develop

### JDK Version

JDK11

### Describe the Bug

Don't set default auth metadata provider

### Steps to Reproduce

Don't set default auth metadata provider

### What Did You Expect to See?

Don't set default auth metadata provider

### What Did You See Instead?

Don't set default auth metadata provider

**Comment by cserwen** [comment]
Can you describe the impact of this issue in more detail? @dingshuangxi888
