### ISSUE TITLE
跪求详细文档！

### ISSUE THREAD

**Issue by DouFuJuShi** [apache/rocketmq#8011]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

跪求详细文档！
跪求详细文档！！
跪求详细文档！！！

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by RongtongJin** [comment]
所有文档都在 https://rocketmq.apache.org/ 和 https://github.com/apache/rocketmq/tree/develop/docs，也可以找互联网上的其他文档，如果碰到具体问题，可以在提相关的issue

**Comment by hong539** [comment]
Where can I found Server Configuration for RocketMQ 5.X ?
Because I only found [4.x version docs](https://rocketmq.apache.org/docs/4.x/parameterConfiguration/02server/)
