### ISSUE TITLE
[Bug] Fix authentication context build for no extFields

### ISSUE THREAD

**Issue by dingshuangxi888** [apache/rocketmq#8046]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

develop

### JDK Version

Java8

### Describe the Bug

HEAT_BEAT api has not extFields, but then authentication has a check

### Steps to Reproduce

start producer/consumer without ak/sk

### What Did You Expect to See?

If an api has not extFields, then authentication context builder will pass

### What Did You See Instead?

If an api has not extFields, then authentication context builder will pass

**Comment by cserwen** [comment]
If the client sets ak/sk, then all request headers will have ak/sk information, including heartbeats.

If ak/sk is not set on the client, these configurations should also be turned off on the server. So this maybe not a bug
```
authenticationEnabled=false
authorizationEnabled=false
```
