### ISSUE TITLE
MessageSelector.bySql can support key word 'LIKE'?

### ISSUE THREAD

**Issue by sycoral** [apache/rocketmq#811]
**FEATURE REQUEST**

When I using rocketmq 4.4.0 filter by message with SQL92，but not support key word 'LIKE'. In my case, the producer produces a message and can specify any number of consumers, but the same message can only be consumed once by one of the consumers. An example of the method is as follows:
```
msg1.putUserProperty("a", ",c1,c2,c3,");
msg2.putUserProperty("a", ",c1,c2,");
......
c2.subscribe("TopicTest", MessageSelector.bySql("a like '%,c2,%'");
```

**Comment by vongosling** [comment]
No, AFAIK, some guys are drafting the improvment. If you have any idea, please send to dev email list.
