### ISSUE TITLE
[Enhancement] remove unused boolean flag

### ISSUE THREAD

**Issue by miles-ton** [apache/rocketmq#8150]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

In ProcessQueue class, we get a `consuming` boolean flag, but it is just used to get and set in class inner, and don't have any meaningful function.

![image](https://github.com/apache/rocketmq/assets/77013030/cede24e9-4cb7-4f3a-933e-ba8dd282dbe4)
![image](https://github.com/apache/rocketmq/assets/77013030/e41194b8-0629-4d18-9aec-984a15c23718)
![image](https://github.com/apache/rocketmq/assets/77013030/767b7b8c-0f99-41a2-9514-654ab246dc2e)
![image](https://github.com/apache/rocketmq/assets/77013030/6a1a892b-c698-457b-b3b6-dfa17d695033)

### Motivation

simplify code

### Describe the Solution You'd Like

remove that `consuming`

### Describe Alternatives You've Considered

none

**Comment by drpmma** [comment]
The consuming flag is actually used inside ProcessQueue class which is not consistent with your description.
