### ISSUE TITLE
Prompt info can be Polished? setNamesrvAddr method parameter error

### ISSUE THREAD

**Issue by hsogoo** [apache/rocketmq#818]
在集群模式下setNamesrvAddr方法中设置nameserver列表中分割符为“,”，此时发送消息失败，会提示org.apache.rocketmq.client.exception.MQClientException: No route info of this topic,在排查问题时走了很多弯路，希望提示nameserver列表参数错误。

**Comment by vongosling** [comment]
感谢你的建议，这个地方接下来社区考虑优化下，也欢迎你提PR帮助我们解决。
