### ISSUE TITLE
[Enhancement] Optimize DefaultMQPushConsumer construction method

### ISSUE THREAD

**Issue by yx9o** [apache/rocketmq#8227]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

I found a duplicate structure in the constructor.
<img width="984" alt="image" src="https://github.com/apache/rocketmq/assets/12792261/c55635f4-d610-4cdf-890e-a0f20b936091">

### Motivation

To reduce code duplication and improve code reusability.

### Describe the Solution You'd Like

We can let one constructor call another constructor, and finally perform the actual assignment operation only in one constructor.

### Describe Alternatives You've Considered

In each constructor, directly call the most complete constructor.

**Comment by ShannonDing** [comment]
link #8262
