### ISSUE TITLE
[Doc]   fix 'meesage' typo in user_guide.md

### ISSUE THREAD

**Issue by liuzc9** [apache/rocketmq#8245]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

./mqadmin sendMessage -m true --topic some-topic-name -n 127.0.0.1:9876 -p "your meesgae content"
this 'your meesage content' typo.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yx9o** [comment]
Fixed by #8244.

**Comment by leizhiyuan** [comment]
you can close this issue if it has been done
