### ISSUE TITLE
[Enhancement] format proxy log watermark output

### ISSUE THREAD

**Issue by zhiliatom** [apache/rocketmq#8291]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

currently, proxy watermark output is messy
![image](https://github.com/apache/rocketmq/assets/87265072/5753b10e-f4de-464a-937b-3a3d577073d0)

### Motivation

format

### Describe the Solution You'd Like

format
![image](https://github.com/apache/rocketmq/assets/87265072/2bf46432-68d9-4f62-bf8e-de32b0f23424)

### Describe Alternatives You've Considered

null

**Comment by elysium-w** [comment]
@zhiliatom I have great intrest about this issue,could you assign it to me?
