### ISSUE TITLE
[Enhancement] optimize some code format or style

### ISSUE THREAD

**Issue by supervate** [apache/rocketmq#8298]
### Before Creating the Enhancement Request

- [x] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

optimize some code format or style

#8262 本Issue 参与阿里天池大赛活动

### Motivation

optimize some code format or style

### Describe the Solution You'd Like

optimize some code format or style

### Describe Alternatives You've Considered

nope

**Comment by ShannonDing** [comment]
link #8262
