### ISSUE TITLE
[Enhancement] Add more test coverage for DefaultMQProducer

### ISSUE THREAD

**Issue by yx9o** [apache/rocketmq#8300]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add more tests.
<img width="1551" alt="image" src="https://github.com/apache/rocketmq/assets/12792261/4b944eaa-7e8e-4316-9fb1-16a50cfd2de4">

### Motivation

Add more tests.

### Describe the Solution You'd Like

Add more tests.

### Describe Alternatives You've Considered

No

**Comment by ShannonDing** [comment]
link #8262
