### ISSUE TITLE
[Enhancement] Add more test coverage for DefaultMQProducerImpl

### ISSUE THREAD

**Issue by yx9o** [apache/rocketmq#8324]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add more tests.
<img width="1575" alt="image" src="https://github.com/apache/rocketmq/assets/12792261/9ab35bdd-788f-40aa-a2fb-fce2ec652298">

### Motivation

Add more tests.

### Describe the Solution You'd Like

Add more tests.

### Describe Alternatives You've Considered

No

**Comment by ShannonDing** [comment]
link #8262
