### ISSUE TITLE
[Enhancement] Add more test coverage for nameserver

### ISSUE THREAD

**Issue by tanXiang003** [apache/rocketmq#8345]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add more test coverage for nameserver

### Motivation

Add more test coverage for nameserver

### Describe the Solution You'd Like

Add more test coverage for nameserver

### Describe Alternatives You've Considered

No

**Comment by ShannonDing** [comment]
link #8262
