### ISSUE TITLE
examineConsumeStats for DefaultMQAdminExtImpl will onley check master

### ISSUE THREAD

**Issue by superheizai** [apache/rocketmq#835]
- What did you do (The steps to reproduce)?
   1. enable consume from slave
   2. consume from days ago, which will lead the consumer consuming from slave
   3. use consumerProgress to check the latency
- What did you expect to see?
    want to see  the current latency

- What did you see instead?

   no change, because it will only check the master's consumer status

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ymwneu** [comment]
I checked the current implementation: 
1. If the master is alive, consume offset will always commit to master broker. ConsumerProgress command queries offset from the master.
2. If the master is down, consume offset will commit to the slave broker with minimum id. In this situation, consumerProgress command will pick a random slave to query offset. We should do some optimize in this case. 

So, if you are the first case, check whether offset commit failed or other problems. If you are in the second case, it's the problem of the current implementation.

**Comment by superheizai** [comment]
> I checked the current implementation:
> 
> 1. If the master is alive, consume offset will always commit to master broker. ConsumerProgress command queries offset from the master.
> 2. If the master is down, consume offset will commit to the slave broker with minimum id. In this situation, consumerProgress command will pick a random slave to query offset. We should do some optimize in this case.
> 
> So, if you are the first case, check whether offset commit failed or other problems. If you are in the second case, it's the problem of the current implementation.

Another condition for case 1 is I have enabled slave. When read for messages for days ago, master will give suggestion broker id for client to pull from. Client PullAPIWrapper will check suggestion brokerId for each pull. And  PullMessageProcessor will commit offset.
It seems different with your description? Would you please help to check  again?

**Comment by ymwneu** [comment]
PullMessageProcessor will not commit offset if the current broker is slave, you can check PullMessageProcessor for more detail.

**Comment by ymwneu** [comment]
MQClientInstance will commit offset with a fixed rate, you can see MQClientInstance#persistAllConsumerOffset().

**Comment by superheizai** [comment]
thks,will check
