### ISSUE TITLE
[Bug] Fix CLIENT_REGISTER behavior in ConsumerManager#registerConsumer

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq#8352]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

No need

### RocketMQ version

5.1.0

### Describe the Bug

The ConsumerGroupEvent CLIENT_REGISTER means that the client of this consumer is new registered. So the callConsumerIdsChangeListener CLIENT_REGISTER should be called when updateChannel return true.

https://github.com/apache/rocketmq/blob/3aa5d1936f1162afefccdf03fcc55bf0f7ee642c/broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerGroupEvent.java#L33-L36

https://github.com/apache/rocketmq/blob/3aa5d1936f1162afefccdf03fcc55bf0f7ee642c/broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerGroupInfo.java#L135-L166

### Steps to Reproduce

No need

### What Did You Expect to See?

The ConsumerGroupEvent CLIENT_REGISTER should be called when a new client is registered.

### What Did You See Instead?

The ConsumerGroupEvent CLIENT_REGISTER is called when a new group is first registered.

**Comment by wuyoudexiao** [comment]
it is useful
