### ISSUE TITLE
[Enhancement] Add more test coverage for AdminBrokerProcessor

### ISSUE THREAD

**Issue by tanXiang003** [apache/rocketmq#8372]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

add more tests 

### Motivation

add more tests

### Describe the Solution You'd Like

add more tests

### Describe Alternatives You've Considered

no

**Comment by ShannonDing** [comment]
link #8262
