### ISSUE TITLE
class 'MessageListenerOrderly' documentation comments describe the problem。

### ISSUE THREAD

**Issue by gnehcgnaw** [apache/rocketmq#838]
Single instance consumer is one queue,on thread ;but the default number of threads for multiple instances is 20. 
I don't know if my understanding is right.

**Comment by ymwneu** [comment]
1. The format of issue should reference to the RocketMQ template.
2. Issue is only for bug report or feature request. You can ask your question via mailing list.
3. I think the "one queue, one thread" means a queue can't be consume concurrently. There's nothing to do with the thread number. The consumeExecutor is used to execute the consume request of different consume queue.

**Comment by gnehcgnaw** [comment]
@ymwneu A queue can't be consume concurrently ，but a queue can be many thread consumer , I don't know if I understand it right .
