### ISSUE TITLE
[Bug] Message at the end of a file may never be uploaded if last commit failed

### ISSUE THREAD

**Issue by bxfjb** [apache/rocketmq#8409]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Any

### RocketMQ version

develop

### JDK Version

1.8

### Describe the Bug

Current tiered storage will call `FileSegment#commitAsync` actively if the appended file is full, but ignoring the commit result, which may cause the last part of messages will never be uploaded.
![2024-07-19 17-14-12屏幕截图](https://github.com/user-attachments/assets/3d172b59-657d-4640-8b22-ade43ddcc357)

### Steps to Reproduce

Running broker and enable tiered storage, waiting until the last part of a commit log file is commit and failed.

### What Did You Expect to See?

Messages that failed to be committed should be committed again.

### What Did You See Instead?

The messages will not be commit ever.

**Comment by lizhimins** [comment]
Good catch
