### ISSUE TITLE
request ，namesrv consistency

### ISSUE THREAD

**Issue by beijixiongzzj** [apache/rocketmq#841]
If there is a connection problem between a broker and a namesrv in the cluster. Cleared up in namesrv obsolescence logic. If the client program gets routeinfo through this namesrv, it will use different message Queue calculation logic from other clients. If multiple clients under the same topic appear and consume the same message Queue at the same time, the repeated consumption of messages will occur. How to solve this problem

**Comment by ymwneu** [comment]
1. The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). 
2. In the current implementation, we suggest consumer client deal with idempotent in business code
to solve repeat consumption problem.
