### ISSUE TITLE
[Enhancement] Add more test coverage for DefaultMQPushConsumerImpl

### ISSUE THREAD

**Issue by yx9o** [apache/rocketmq#8411]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add more tests.

### Motivation

Add more tests.

### Describe the Solution You'd Like

Add more tests.

### Describe Alternatives You've Considered

No

**Comment by ShannonDing** [comment]
link #8262

**Comment by yx9o** [comment]
> link #8262

OK, I didn't pay attention to this issue before, but I saw this RIP: https://github.com/apache/rocketmq/wiki/RIP-10-RocketMQ-Unit-Test

I will quote #8262 later.
