### ISSUE TITLE
[Enhancement] add more test coverage for broker.PeekMessageProcessor

### ISSUE THREAD

**Issue by TanXiang7o** [apache/rocketmq#8495]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

![image](https://github.com/user-attachments/assets/771e7d77-9b15-4d27-b906-cf3eb5858c7d)
add more test coverage

### Motivation

add more test coverage

### Describe the Solution You'd Like

add more test coverage

### Describe Alternatives You've Considered

add more test coverage

**Comment by ShannonDing** [comment]
link #8262
