### ISSUE TITLE
[Enhancement] Fix workflow Coverage failure due to testProduceAccumulator_sync()

### ISSUE THREAD

**Issue by imzs** [apache/rocketmq#8499]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

https://github.com/apache/rocketmq/actions/workflows/coverage.yml
Most of the recent Coverage workflow tasks failed at ProduceAccumulatorTest#testProduceAccumulator_sync(), it's necessary to fix it.

![image](https://github.com/user-attachments/assets/4cda6bba-4a99-47b1-9bd7-011360baf006)

https://github.com/apache/rocketmq/actions/runs/10229250411/job/28302677991
https://github.com/apache/rocketmq/actions/runs/10242303444/job/28331811381
https://github.com/apache/rocketmq/actions/runs/10250136206/job/28355136628
https://github.com/apache/rocketmq/actions/runs/10251927612/job/28361102144
https://github.com/apache/rocketmq/actions/runs/10251005385/job/28358033934
https://github.com/apache/rocketmq/actions/runs/10241255714/job/28329267351

### Motivation

.

### Describe the Solution You'd Like

Tests run: 3, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.264 sec <<< FAILURE! - in org.apache.rocketmq.client.producer.ProduceAccumulatorTest
testProduceAccumulator_sync(org.apache.rocketmq.client.producer.ProduceAccumulatorTest)  Time elapsed: 0.133 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
expected: 175
 but was: 37

### Describe Alternatives You've Considered

.

**Comment by ShannonDing** [comment]
could you pls submit a PR to fix it.

**Comment by imzs** [comment]
> could you pls submit a PR to fix it.

Chair Ding, as I've tested, 1000ms may not be enough.

**Comment by ShannonDing** [comment]
> testProduceAccumulator_sync

OK, let‘s reset it to 3s and let countDownLatch await 5s.
