### ISSUE TITLE
[Doc] Documentation Related, [5.x] Ordered Message Document might be outdated.

### ISSUE THREAD

**Issue by UnclePi979** [apache/rocketmq#8516]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

Document: [Ordered Message Code Example](https://rocketmq.apache.org/docs/featureBehavior/03fifomessage/#example)

My rocketmq-client version is 5.1.0
```xml
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client</artifactId>
    <version>5.1.0</version>
</dependency>
```

It seems that these classes and methods do not exist.
<img width="988" alt="image" src="https://github.com/user-attachments/assets/121440a8-b8cd-482c-b04b-d9677d5196ee">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by UnclePi979** [comment]
btw, can messages be ensured to be ordered in the queue if the topic type is not **FIFO**?

**Comment by yx9o** [comment]
Hi @UnclePi979 , it seems that you have encountered problems with sequential messages, but your example does not seem to be correct. You can refer to:https://github.com/apache/rocketmq/blob/develop/example/src/main/java/org/apache/rocketmq/example/ordermessage/Producer.java

**Comment by UnclePi979** [comment]
> Hi @UnclePi979 , it seems that you have encountered problems with sequential messages, but your example does not seem to be correct. You can refer to:https://github.com/apache/rocketmq/blob/develop/example/src/main/java/org/apache/rocketmq/example/ordermessage/Producer.java

Thanks @yx9o, the example you provided is helpful for me. (btw, can messages be ensured to be ordered in the queue if the topic type is not **FIFO** in this example? :-).

**Comment by yx9o** [comment]
Yes, the order of messages is only related to the sending method and the queue selected when sending. Please refer to the example above.
