### ISSUE TITLE
[Enhancement] Add a retry mechanism to the unit test pipeline

### ISSUE THREAD

**Issue by chi3316** [apache/rocketmq#8544]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Introduce a retry mechanism in the unit test pipeline to automatically retry failed unit tests a limited number of times, reducing manual intervention and improving the reliability of CI builds

### Motivation

- Currently, the unit test pipeline occasionally fails due to intermittent test issues, leading to unnecessary build failures. These failures require manual retries, which can be time-consuming and inefficient. This enhancement would contribute to smoother CI/CD operations, benefiting both the project and the community by increasing build reliability and reducing manual workload.
- This task is part of the RocketMQ community's assignments under the OSPP activity, as detailed in the [OSPP2024](https://summer-ospp.ac.cn/org/prodetail/24ee30103?list=org&navpage=org)

### Describe the Solution You'd Like

The solution involves implementing a retry logic within the CI pipeline that triggers a limited number of retries when a unit test fails. The retry mechanism would only be activated under specific conditions, such as test failures, to prevent unnecessary re-runs. This can be achieved by utilizing conditional steps in the workflow file to rerun the tests if a failure is detected.

### Describe Alternatives You've Considered

- Manual Retries: Continue with the current process where developers manually trigger retries, but this is inefficient and prone to delays.
- Test Flakiness Detection: Implement a mechanism to identify and fix flaky tests; however, this is a longer-term solution that requires additional resources.

**Comment by ShannonDing** [comment]
link #8262
