### ISSUE TITLE
[Enhancement] Increase the code test coverage for ControllableOffset

### ISSUE THREAD

**Issue by syhleo** [apache/rocketmq#8547]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add ControllableOffset tests.

### Motivation

Add ControllableOffset tests.

### Describe the Solution You'd Like

Add ControllableOffset tests.

### Describe Alternatives You've Considered

null

### Additional Context

null

**Comment by ShannonDing** [comment]
link #8262
