### ISSUE TITLE
[Bug] Bug title Rocketmq5.3.0 reports an error after configuring IPV6

### ISSUE THREAD

**Issue by htxxy1015** [apache/rocketmq#8549]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos7.8

### RocketMQ version

rocketmq5.3.0

### JDK Version

JDK1.8

### Describe the Bug

 rocketmq5.3.0，brokerIP1配置为IPV6，即brokerIP1=fd00::1:7a，当推完数据到mq后，再查看mq状态时报错。
broker.conf:
![image](https://github.com/user-attachments/assets/32ccd439-e7ae-42f9-80ec-0e2e2565ea79)

报错截图：
![image](https://github.com/user-attachments/assets/a062808a-c5d5-4f96-8bef-3f94eb8fe846)

### Steps to Reproduce

rocketmq5.3.0，brokerIP1配置为IPV6，即brokerIP1=fd00::1:7a，当推完数据到mq后，再查看mq状态时报错。

### What Did You Expect to See?

有解决方案

### What Did You See Instead?

有解决方案

**Comment by leizhiyuan** [comment]
这个错误看着是服务端返回的，去broker的日志里面，看看服务端的报错消息是哪一行

**Comment by htxxy1015** [comment]
@leizhiyuan 
broker.log日志看起来没有啥问题
![image](https://github.com/user-attachments/assets/856d73b5-274e-4917-9973-b87e7b3f6e65)
但在remote.log却存在报错信息。
![image](https://github.com/user-attachments/assets/66f9f6b8-4144-436d-9ffb-c7035d9bbd07)


PS：目前就是在broker.conf配置brokerIP1=ipv6地址，生产和消费数据后，查看改mq状态就会提示该报错
当brokerIP1=ipv4地址，这种情况就不会出现

**Comment by leizhiyuan** [comment]
应该是这行代码没有考虑ipv6的情况

```
    @Override
    public long getEarliestMessageTime() {
        long minPhyOffset = this.getMinPhyOffset();
        if (this.getCommitLog() instanceof DLedgerCommitLog) {
            minPhyOffset += DLedgerEntry.BODY_OFFSET;
        }
        final int size = MessageDecoder.MESSAGE_STORE_TIMESTAMP_POSITION + 8;
        return this.getCommitLog().pickupStoreTimestamp(minPhyOffset, size);
    }
```

这里的是56+8

 public long pickupStoreTimestamp(final long offset, final int size) {
        if (offset >= this.getMinOffset() && offset + size <= this.getMaxOffset()) {
            SelectMappedBufferResult result = this.getMessage(offset, size);
            if (null != result) {
                try {
                    int sysFlag = result.getByteBuffer().getInt(MessageDecoder.SYSFLAG_POSITION);
                    int bornhostLength = (sysFlag & MessageSysFlag.BORNHOST_V6_FLAG) == 0 ? 8 : 20;
                    int msgStoreTimePos = 4 + 4 + 4 + 4 + 4 + 8 + 8 + 4 + 8 + bornhostLength;
                    return result.getByteBuffer().getLong(msgStoreTimePos);
                } finally {
                    result.release();
                }
            }
        }

        return -1;
    }

里面如果是ipv4，获取的是56:56+8（long）
如果是ipv6，就会越界，要获取68:68+8

**Comment by woaishixiaoxiao** [comment]
The `validator.isValidInet6Address` function only supports standard IPv6 addresses. In contrast, `NetworkUtil.getLocalAddress()` returns bracketed IPv6 addresses (e.g., `[2001:db8::1]`) that may include Linux-specific scope IDs (e.g., `[fe80::1%eth0]`).
