### ISSUE TITLE
[Bug] ACL创建提示成功但查询获取不到

### ISSUE THREAD

**Issue by TickFairy** [apache/rocketmq#8550]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos 7

### RocketMQ version

4.9.4

### JDK Version

1.8

### Describe the Bug

我连续创建两条数据 admin12345 和 admin123456 ，但是 admin123456 并未成功

![image](https://github.com/user-attachments/assets/5c00e0f7-3334-4691-9bdc-cb8763873f45)

另外 我指定白名单 地址 1.1.1.1;2.2.2.2 提示校验失败

![image](https://github.com/user-attachments/assets/47da24f6-d14f-45de-bbdf-4214d8bd0303)

再次创建却提示成功，实例 查询也查询不到
![image](https://github.com/user-attachments/assets/9b668985-ea02-4249-ac61-cec2c655dcd0)

### Steps to Reproduce

如图

### What Did You Expect to See?

期望是都可以查询到

### What Did You See Instead?

期望是都可以查询到

**Comment by TickFairy** [comment]
根据源码看  多个白名单地址是分号分隔还是 逗号？这一点比较奇怪

![image](https://github.com/user-attachments/assets/190bc9da-de25-485f-ae04-1b35165b3147)

**Comment by TickFairy** [comment]
@leizhiyuan 哥 帮我看一下 求你了

**Comment by yx9o** [comment]
@TickFairy 你好，这里应该是使用逗号，你可以提pr修复下文档。

**Comment by yx9o** [comment]
嗨 @TickFairy 问题都解决了吗。

**Comment by TickFairy** [comment]
> 嗨 @TickFairy 问题都解决了吗。

多谢 ， 确实改成逗号，一切看起来正常了，至于出现偶尔保存不上的问题，我删除已经存在 的用户 （其中白名单分号分割填写），也没有再出现了，不过比较奇怪 ，rocketmq api 并不会报错，我觉得是问题，但问题到此， 我关闭此单吧
