### ISSUE TITLE
bindAddress的作用是什么？官方文档没有找到该参数的用法

### ISSUE THREAD

**Issue by codepkgs** [apache/rocketmq#8583]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

文档：https://rocketmq.apache.org/docs/4.x/bestPractice/01bestpractice/#broker-configuration

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ryanliuyao61** [comment]
bindAddress是底层netty网络监听用的，默认是0.0.0.0，默认配置再NettyServerConfig.Java中。这意味着服务器会监听所有可用的网络接口。这对于有多网卡（即多个网络接口）的系统来说非常有用，因为它允许服务器同时在所有网络接口上接收连接，而不需要为每个接口单独配置。
这个配置有区别于BrokerIP1，BrokerIP1是Broker注册到nameserver上供proxy或sdk连接的实际地址。在代码BrokerController.java中doRegisterBrokerAll中的getBrokerAddr使用。
所以需要保证netty监听正确，bindAddress可以不做配置或者配置称和IP1一致
