### ISSUE TITLE
[Bug] storeTimestamp与bornTimestamp差值偶现超900ms

### ISSUE THREAD

**Issue by sltjav** [apache/rocketmq#8639]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

物理机
linux centos
CPU：96c，启动内存32g，磁盘：nvme卡

### RocketMQ version

4.9.7

### JDK Version

openjdk1.8

### Describe the Bug

**偶现发送消息耗时升高，产生毛刺（300ms-1.2s）**
排查过程，抓包发现请求已经到达Broker网卡，且在RequestTask的run()方法第一行中，打印createTimestamp-bornTimestamp差值发现耗时已经升高，说明耗时就发生在从网卡读消息，到netty走完pipeline并交给SendMessageProcessor的过程中：

**补充**
1.未触发Flow control报错
2.pagecache写入监控的putMessageEntireTimeMax最大只有几十ms
3.gc的pause时长<1ms，没有fullgc
4.TCP的receive和send Q偶有突刺，最大<2M

**Broker相关配置项：**
serverSelectorThreads=16
serverWorkerThreads=32
sendMessageThreadPoolNums=32

transientStorePoolEnable=true
transferMsgByHeap=false

### Steps to Reproduce

不确定，可能现象是生产tps脉冲增高，且消息体较大2-4KB。

### What Did You Expect to See?

耗时毛刺（300ms-1.2s）的可能原因，以及后续如何优化

### What Did You See Instead?

生产的max耗时远高于日常

**Comment by humkum** [comment]
```不确定，可能现象是生产tps脉冲增高，且消息体较大2-4KB。```

怀疑的因素可以先排除下

**Comment by lizhimins** [comment]
看下网卡多队列和 irq

**Comment by leosqin** [comment]
> 看下网卡多队列和 irq

Thanks! You are right
