### ISSUE TITLE
[Doc] ACL2.0怎么使用，文档呢？

### ISSUE THREAD

**Issue by ALIFED** [apache/rocketmq#8694]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

broker开启了acl2.0，proxy也配置了，console dashabord 也能正常使用，但是使用rocketmq-client-java:5.0.7版本的java sdk，用户名和密码配置的都是对的，但是神奇般的提示认证失败？why？

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by dingshuangxi888** [comment]
先参考下这个文档：https://mp.weixin.qq.com/s/g_CUAXrzQ1TQhIDrhX-zkw

**Comment by dingshuangxi888** [comment]
麻烦发一下配置信息，我这边看下

**Comment by ALIFED** [comment]
已经解决了，研究了好久。。。。。

**Comment by ZongZihao** [comment]
> 已经解决了，研究了好久。。。。。

想问下你的rocketmq是哪个版本？ 我这里开启了acl2.0之后一直无法消费消息
