### ISSUE TITLE
Redundant Config in RemotingUtil?

### ISSUE THREAD

**Issue by ZhangShenao** [apache/rocketmq#870]
The method connect in is as follows:
`public static SocketChannel connect(SocketAddress remote, final int timeoutMillis) {
        SocketChannel sc = null;
        try {
            sc = SocketChannel.open();
            sc.configureBlocking(true);
            sc.socket().setSoLinger(false, -1);
            sc.socket().setTcpNoDelay(true);
            sc.socket().setReceiveBufferSize(1024 * 64);
            sc.socket().setSendBufferSize(1024 * 64);
            sc.socket().connect(remote, timeoutMillis);
            sc.configureBlocking(false);
            return sc;
        } catch (Exception e) {
            if (sc != null) {
                try {
                    sc.close();
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        }

        return null;
    }`
Since we are using a non-blocking mode , why config blocking true in advance?

**Comment by ymwneu** [comment]
Notice the code:
 `sc.socket().connect(remote, timeoutMillis);`
Config blocking can make sure connect established after the connect method return.

**Comment by ZhangShenao** [comment]
> Notice the code:
> `sc.socket().connect(remote, timeoutMillis);`
> Config blocking can make sure connect established after the connect method return.

Thanks for your explanation.
