### ISSUE TITLE
suggest about rocketmq client

### ISSUE THREAD

**Issue by hwind001** [apache/rocketmq#873]
I read some sources of the rocketmq client . I find the client that contain some api which can use to modify broker config or get broker config . I think this is risk for the broker . I suggest separate the api about client and manage .

**Comment by ymwneu** [comment]
I think just separate the api of client and management can't solve the risk of broker thoroughly. Set ACL can help control the authority of modify broker config. I found the latest version RocketMQ is already support ACL.

**Comment by hwind001** [comment]
I think separate the api of client ,simplify the api of client that business apply . The ACL should modify the files , not conveniently .

**Comment by zongtanghu** [comment]
Hi @hwind001 ,RocketMQ 4.4.0 version has already supported the acl feature,You can try it in you developping enviroment.If you meet any problem in trying acl feature,you can find me to resolve it.Thank you!
