### ISSUE TITLE
[Doc] Fix typo

### ISSUE THREAD

**Issue by luozongle01** [apache/rocketmq#8798]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

<img width="978" alt="image" src="https://github.com/user-attachments/assets/5e2f01a3-80f5-432b-b66b-dbfc2a6aac0c">
<img width="877" alt="image" src="https://github.com/user-attachments/assets/db31508b-8f72-4340-ae26-6df5c58c4d86">
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/3b2cd2b9-6783-4216-9559-c985a2936a1c">
<img width="724" alt="image" src="https://github.com/user-attachments/assets/bbe807af-700b-4f1c-ad54-5e1b3972819d">
<img width="581" alt="image" src="https://github.com/user-attachments/assets/5afa24df-3bae-4330-8d05-51586c576fdc">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by kshamakapre** [comment]
I would like to submit the PR. @luozongle01 Please assign this to me.
