### ISSUE TITLE
[Enhancement] LanguageCode does not have nodejs 

### ISSUE THREAD

**Issue by panzhi33** [apache/rocketmq#8870]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

LanguageCode does not have nodejs 

### Motivation

LanguageCode does not have nodejs 

### Describe the Solution You'd Like

LanguageCode does not have nodejs ，need to increase

### Describe Alternatives You've Considered

LanguageCode does not have nodejs ，need to increase。
![image](https://github.com/user-attachments/assets/d4431f2f-7ed9-4b17-a99f-2a76dca4c9ff)
node js grpc

The language of node js grpc sdk currently uses http

**Comment by zhaohai666** [comment]
指给我

**Comment by zhaohai666** [comment]
#853
