### ISSUE TITLE
[Bug] Benchmark java17 version exception

### ISSUE THREAD

**Issue by hakusai22** [apache/rocketmq#8898]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

linux

### RocketMQ version

rocketmq-all-5.2.0-bin-release/benchmark

### JDK Version

java version "17.0.11" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing)

### Describe the Bug

- The jvm parameters in the stress test runclass.sh are outdated. I use the java17 version and an exception occurs
```bash
benchmark]# Unrecognized VM option 'PermSize=128m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### Steps to Reproduce

sh producer.sh -h

### What Did You Expect to See?

success

### What Did You See Instead?

error

**Comment by hexueyuan** [comment]
You can manually modify benchmark’s startup script benchmark/runclass.sh. 

In your case, you should change '-XX:PermSize=128m -XX:MaxPermSize=320m' to '-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m'.

The PermSize option was used in Java 7 and earlier to set the initial size of the permanent generation space. However, starting from Java 8, this option was replaced by Metaspace.

**Comment by hakusai22** [comment]
> You can manually modify benchmark’s startup script benchmark/runclass.sh.
> 
> In your case, you should change '-XX:PermSize=128m -XX:MaxPermSize=320m' to '-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m'.
> 
> The PermSize option was used in Java 7 and earlier to set the initial size of the permanent generation space. However, starting from Java 8, this option was replaced by Metaspace.

yes, After I modified the jvm parameters, it ran successfully
```
JAVA_OPT="${JAVA_OPT} -server -Xms1g -Xmx1g -Xmn256m "
JAVA_OPT="${JAVA_OPT} -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=70"
JAVA_OPT="${JAVA_OPT} -verbose:gc -Xlog:gc*:file=${GC_LOG_DIR}/rmq_run_class_gc_%p_%t.log:time,uptime,level,tags -XX:+PrintGCDetails"
JAVA_OPT="${JAVA_OPT} -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:+PerfDisableSharedMem"
JAVA_OPT="${JAVA_OPT} -cp ${CLASSPATH}"
```

**Comment by hakusai22** [comment]
Is it possible to select appropriate parameters according to the java version? Java8 as the dividing line or abandon the original jvm parameters?

**Comment by hexueyuan** [comment]
> Is it possible to select appropriate parameters according to the java version? Java8 as the dividing line or abandon the original jvm parameters?

The [fix](https://github.com/apache/rocketmq/commit/e281697b8e07cfe77eb26ffa46ac76ba3eca75de) has been submitted to the develop branch, by adding an 'IgnoreUnrecognizedVMOptions' parameter, JVM parameters that are not recognized in higher versions are ignored, not perfect but useful.
