### ISSUE TITLE
[Bug] proxy local mode send message failed

### ISSUE THREAD

**Issue by VictoryAnn** [apache/rocketmq#8904]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

windows11

### RocketMQ version

5.3.1

### JDK Version

1.8

### Describe the Bug

本地部署了两个local proxy，proxy1,proxy2，当作两个分片，其中proxy1创建topic: 1a，另外一个proxy2创建topic: 2b，客户端地址配置两个proxy的地址，写其中一个topic，比如 1a ，可能会失败，当请求到的proxy2的时候，客户端会报错，获取topicroute失败，导致无法发送消息。

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/4c2406c5-a06a-46fe-b8b0-d2d360e67f2b)
![image](https://github.com/user-attachments/assets/d4ed77ac-50a8-4bef-8eca-f625d1ba3ff1)

### What Did You Expect to See?

正常应该能获取到topicRoute，因为proxy获取路由是从nameserver获取的。

### What Did You See Instead?

客户端获取路由失败，终止发送消息。

**Comment by dyrnq** [comment]
由于 Local 模式下 Proxy 和 Broker 是同进程部署，Proxy本身无状态，因此主要的集群配置仍然以 Broker 为基础进行即可。[参考](https://rocketmq.apache.org/zh/docs/deploymentOperations/01deploy/#local%E6%A8%A1%E5%BC%8F%E9%83%A8%E7%BD%B2)

那么两个**broker**是什么关系啊?

**Comment by VictoryAnn** [comment]
> 由于 Local 模式下 Proxy 和 Broker 是同进程部署，Proxy本身无状态，因此主要的集群配置仍然以 Broker 为基础进行即可。[参考](https://rocketmq.apache.org/zh/docs/deploymentOperations/01deploy/#local%E6%A8%A1%E5%BC%8F%E9%83%A8%E7%BD%B2)
> 
> 那么两个**broker**是什么关系啊?

考虑local模式下，broker 可能会扩容，broker 扩容后有多个分片，然后创建topic可以指定broker ，就会出现现在这种情况，这个场景是预期内的吗？

**Comment by dyrnq** [comment]
Proxy本身无状态的,确实如此啊

**Comment by VictoryAnn** [comment]
所以，local 模式下，只能本地proxy 访问本地的broker 吗？我看源码proxy 是从nameserver 获取topic路由，理论上是可以转发到其他切片上？

**Comment by dyrnq** [comment]
不确定local模式下会不会脸上namesrv,试下从broker剥离分开部署proxy,因为单独部署proxy会配置namesrvAddr这个参数

**Comment by dyrnq** [comment]
- <https://github.com/apache/rocketmq/tree/develop/proxy#cluster-mode>
- <https://github.com/apache/rocketmq/tree/develop/proxy#local-mode>

看以上2图,能看出点端倪来

**Comment by VictoryAnn** [comment]
> * https://github.com/apache/rocketmq/tree/develop/proxy#cluster-mode
> * https://github.com/apache/rocketmq/tree/develop/proxy#local-mode
> 
> 看以上2图,能看出点端倪来

这个图有点疑问，就是client需要先获取所有topic路由，用了proxy和broker 同一个进程的话，获取到的路由地址会被proxy替换成proxy的端口，然后根据对应topic所在的proxy，客户端会选择对应的proxy地址去send message。但是现状看起来是客户端获取topic路由的时候，由于topic不在当前broker上，导致路由信息返回的message type 为 0，客户端获取不到topic路由。
![image](https://github.com/user-attachments/assets/c0f73832-eb86-40c9-8e03-cb17469e7426)

**Comment by dyrnq** [comment]
确实如此了，那得要求client自行判断了

**Comment by VictoryAnn** [comment]
那现在的问题就是，客户端从proxy获取路由报错，Message type is not specified，是不是proxy提供的获取路由接口存在问题？期望是，proxy会返回全量的topicRoute，并且返回内容可以被客户端正确解析。

**Comment by dyrnq** [comment]
> 那现在的问题就是，客户端从proxy获取路由报错，Message type is not specified，是不是proxy提供的获取路由接口存在问题？期望是，proxy会返回全量的topicRoute，并且返回内容可以被客户端正确解析。

这样比较好

**Comment by dyrnq** [comment]
https://rocketmq.io/course/deploy/rocketmq_learning-gvr7dx_awbbpb_ogr2blaw8vy3tv14/?spm=0.29160081.0.0.630d5342Dzuczv#33-proxy-%E6%9C%AC%E5%9C%B0%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F

根据以下图片,即使是Local也像是路由了

![这是图片](https://img.alicdn.com/imgextra/i2/O1CN016e6MZr27D3F7UeVNU_!!6000000007762-0-tps-1464-825.jpg)

**Comment by dyrnq** [comment]
Caused by: java.lang.IllegalArgumentException: Message type is not specified
also see <https://github.com/apache/rocketmq/issues/8546>

**Comment by dyrnq** [comment]
- [proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/LocalMetadataService.java](https://github.com/apache/rocketmq/blob/rocketmq-all-5.3.1/proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/LocalMetadataService.java)

- [proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/ClusterMetadataService.java](https://github.com/apache/rocketmq/blob/rocketmq-all-5.3.1/proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/ClusterMetadataService.java)

对比以上代码，发现LocalMetadataService确实没有通过Namesrv请求路由信息，你是从哪里看到过Local模式有能获取路由信息的表述吗？ @VictoryAnn

**Comment by VictoryAnn** [comment]
> * [proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/LocalMetadataService.java](https://github.com/apache/rocketmq/blob/rocketmq-all-5.3.1/proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/LocalMetadataService.java)
> * [proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/ClusterMetadataService.java](https://github.com/apache/rocketmq/blob/rocketmq-all-5.3.1/proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/ClusterMetadataService.java)
> 
> 对比以上代码，发现LocalMetadataService确实没有通过Namesrv请求路由信息，你是从哪里看到过Local模式有能获取路由信息的表述吗？ @VictoryAnn
是获取topic路由的接口。getTopicRouteForProxy
> * [proxy/src/main/java/org/apache/rocketmq/proxy/service/route/LocalTopicRouteService.java](https://github.com/apache/rocketmq/blob/rocketmq-all-5.3.1/proxy/src/main/java/org/apache/rocketmq/proxy/service/route/LocalTopicRouteService.java)

**Comment by dyrnq** [comment]
嗯，对比了下这俩类的getTopicRouteForProxy方法
唯一的区别就是grpcPort和requestHostAndPortList


```java
        return new ProxyTopicRouteData(topicRouteData, grpcPort); // grpcPort是不带IP的啊，他过不去另外的机器啊
```

```java
        return new ProxyTopicRouteData(topicRouteData, requestHostAndPortList);
```

**Comment by VictoryAnn** [comment]
我看是从这里cache获取的，cache是从nameserver获取的，proxy只是替换了端口（这里也存疑，cluster部署可能端口都是一致的，不会有问题。如果像local部署，不同的代理端口不同是不是也有问题？），不需要去访问其他机器。
![image](https://github.com/user-attachments/assets/77565e77-69ff-490c-9604-ec0128dcf31a)

**Comment by dyrnq** [comment]
grpcPort等同于仅仅包含了一个元素的List<Address>，所以相当于又过滤了？

**Comment by dyrnq** [comment]
还是把proxy从 broker拆分部署吧，这个是没有问题的。入口不从namesrv，元信息就获取不到，local模式怪怪的。

**Comment by VictoryAnn** [comment]
> 还是把proxy从 broker拆分部署吧，这个是没有问题的。入口不从namesrv，元信息就获取不到，local模式怪怪的。

local这块是感觉怪怪的，还有一个疑问点，local部署下，如果client不去获取topicRoute，直接sendmessage proxy是不是会自己转到其他的proxy，那这样client似乎没必要获取topicRoute？尽管是cluster，客户端连代理的话，有必要获取topicRoute吗？这是为了兼容nameserver的访问方式吗，还是有其他考量？

**Comment by dyrnq** [comment]
第一个回答不了（非官方人员:( ）
第二个（作为用户）感觉有必要，毕竟proxy和namesrv类似的入口能力，像你这样划分topic的话，确实proxy需要知道topic具体落地到那个broker上，有点类似nginx的动态配置，比如/hello --->upstream 到后端，那么后端必须得能承接 /hello的访问，所以不管是namesrv或者proxy 都得做到这个匹配能力，不然用户得自己配置（提供配置入口，感觉也没必要）？

**Comment by VictoryAnn** [comment]
个人感觉，topic路由相关的应该在proxy内部做掉，proxy的角色也是对外屏蔽掉broker和nameserver，proxy外层加负载均衡即可。

**Comment by dyrnq** [comment]
嗯，唯一的区分就是local Proxy怎么定义了，按道理这里的local proxy的这个`叫法`有点让人`误解`，如果要是叫 broker 提供grpc协议入口会更合适。 

即这个broker提供grpc协议又提供remoting协议。

这个和grpc的这个提供能力的叫法有关系，分离部署就叫proxy，合并启动就叫只负责自个的grpc。

**Comment by dyrnq** [comment]
所以我怀疑local proxy 是用 grpc over remoting 替代了一个假设的存在（即原生的grpc能力）

**Comment by VictoryAnn** [comment]
> 嗯，唯一的区分就是local Proxy怎么定义了，按道理这里的local proxy的这个`叫法`有点让人`误解`，如果要是叫 broker 提供grpc协议入口会更合适。
> 
> 即这个broker提供grpc协议又提供remoting协议。
> 
> 这个和grpc的这个提供能力的叫法有关系，分离部署就叫proxy，合并启动就叫只负责自个的grpc。

赞同，所以提供local这种部署模式 目的有点模糊，官方的资料给的都是跟cluster部署没什么区别，主要可以降低延迟，但实际分析下来，又给人感觉local仅仅是broker的替身。

**Comment by dyrnq** [comment]
> > 嗯，唯一的区分就是local Proxy怎么定义了，按道理这里的local proxy的这个`叫法`有点让人`误解`，如果要是叫 broker 提供grpc协议入口会更合适。
> > 即这个broker提供grpc协议又提供remoting协议。
> > 这个和grpc的这个提供能力的叫法有关系，分离部署就叫proxy，合并启动就叫只负责自个的grpc。
> 
> 赞同，所以提供local这种部署模式 目的有点模糊，官方的资料给的都是跟cluster部署没什么区别，主要可以降低延迟，但实际分析下来，又给人感觉local仅仅是broker的替身。






如果local proxy 等同于只给broker提供grpc的能力，那么入口就还得是namesrv，以效仿于remoting的形式获取topic和grpc broker的关联路由关系。

不过好像rocketmq-v5的客户端还不支持endpoints写namesrv

```bash
ClientConfiguration clientConfiguration = ClientConfiguration.newBuilder()
            .setEndpoints(endpoints)
```

**Comment by VictoryAnn** [comment]
### 先说结论：local mode 当前节点的proxy只能发送到本地的broker中，cluster mode则proxy可以进行全局topic的路由。
（小声蛐蛐：local proxy的proxy概念有点误导常规对proxy的理解）

先用客户端尝试一下 指定proxy地址，选择当前分片上不存在的topic，看是否会转发到另外一个分片。
![image](https://github.com/user-attachments/assets/f8fe5e38-e87c-4ff4-b38d-3bd009dc7b50)
![image](https://github.com/user-attachments/assets/28baf92f-cbb1-4074-ad46-9f2fbadeafed)


这里可以看到客户端发送消息失败。
![image](https://github.com/user-attachments/assets/02272891-6a4f-40d4-b9af-1a696f96b989)

跟踪客户端代码继续看，发现客户端报错是从proxy获取topicRoute报错，还没有走到sendMessage那一步，跟踪proxy代码，发现如下：
LOCAL 模式下 获取topicRoute只从本地获取，所以客户端获取不到topic路由，然后终止发送消息。
![image](https://github.com/user-attachments/assets/3734e836-6c66-4cd7-87d1-a50f7e04acf9)

CLUSTER模式下 是从topicCache中获取路由信息，topicCache是从nameserver获取的路由信息。
![image](https://github.com/user-attachments/assets/f3ddafe1-4d02-479c-b252-36b9c0a4332d)
![image](https://github.com/user-attachments/assets/d66d1db9-10da-4366-aa6f-2e981589c9e3)


这个时候怀疑是不是proxy本身可以转发，但是由于客户端的缺陷或者是proxy提供route的api的问题导致无法发送成功。
接下来，试一下直接调用grpc的sendmessage接口
![image](https://github.com/user-attachments/assets/6c0e34e6-8bf3-4f0a-975d-653837aa4aa5)
![image](https://github.com/user-attachments/assets/6d425a80-c996-4160-9f76-aef100c5c684)


```
# grpc 调用接口 6666端口对应的broker-a 可以正常发送消息到broker-a的topic
grpcurl -H 'client-id: astest' -plaintext -d '{"messages":[{"topic":{"name":"astest-1a"},"system_properties":{"tag":"messageTagA","keys":"messageKeyA","message_id":"0102427869DB29BF80074C8F3D00000001","body_encoding":"IDENTITY","message_type":"NORMAL","born_host":"BIH-L-56328ZZZ","queue_id":1},"body":"VGhpcyBpcyBhIG5vcm1hbCBtZXNzYWdlIGZvciBBcGFjaGUgUm9ja2V0TVEK"}]}' 10.242.108.86:6666 apache.rocketmq.v2.MessagingService.SendMessage

# grpc 调用接口 5555端口对应的broker-b 发送消息到broker-a的topic报错
grpcurl -H 'client-id: astest' -plaintext -d '{"messages":[{"topic":{"name":"astest-1a"},"system_properties":{"tag":"messageTagA","keys":"messageKeyA","message_id":"0102427869DB29BF80074C8F3D00000001","body_encoding":"IDENTITY","message_type":"NORMAL","born_host":"BIH-L-56328ZZZ","queue_id":1},"body":"VGhpcyBpcyBhIG5vcm1hbCBtZXNzYWdlIGZvciBBcGFjaGUgUm9ja2V0TVEK"}]}' 10.242.108.86:5555 apache.rocketmq.v2.MessagingService.SendMessage
```
![image](https://github.com/user-attachments/assets/6e0fcac6-a2e4-4fd9-8648-11e216ab75fb)

看下源码的逻辑
![image](https://github.com/user-attachments/assets/78e642a6-9ffe-4dfb-80d3-3141b7fcf1b6)

local mode 获取topic route是从broker controller中获取的，所以获取不到，但是cluster mode 是从topicCache（从nameserver获取的）获取，这也证明了 local mode 只能发送到本地的队列，不能转发到其他proxy local 的队列。(包括获取topic 之后，获取topic的message queue也一样，proxy local都是从本地获取)
![image](https://github.com/user-attachments/assets/87ce006a-38ef-4881-b6a4-47f7996e4b75)
![image](https://github.com/user-attachments/assets/f78b4802-7f50-4a8f-8b2a-66af725f4dcd)
