### ISSUE TITLE
[Bug] RocketMQ 5.3.x return success while update user password or status but nothing got changed.

### ISSUE THREAD

**Issue by caton-wang** [apache/rocketmq#8925]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Ubuntu20.04

### RocketMQ version

5.3.0/5.3.1

### JDK Version

OpenJDK 1.8.0_342

### Describe the Bug

RocketMQ 5.3.0/5.3.1 update user password or update user type or disable user all return success, but none get changed. Still the same as before.
![rocketmq 5 3 0 update user password bug](https://github.com/user-attachments/assets/95ac2ac9-68c3-44c2-9678-538f9680816e)

### Steps to Reproduce

[[ broker.conf ]]

brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
namesrvAddr= 192.168.57.10:9876
listenPort = 10911
authenticationEnabled = true
authenticationProvider = org.apache.rocketmq.auth.authentication.provider.DefaultAuthenticationProvider
initAuthenticationUser = {"username":"rocketmq","password":"12345678"}
innerClientAuthenticationCredentials = {"accessKey":"rocketmq","secretKey":"12345678"}
authenticationMetadataProvider = org.apache.rocketmq.auth.authentication.provider.LocalAuthenticationMetadataProvider
authorizationEnabled = true
authorizationProvider = org.apache.rocketmq.auth.authorization.provider.DefaultAuthorizationProvider
authorizationMetadataProvider = org.apache.rocketmq.auth.authorization.provider.LocalAuthorizationMetadataProvider

reproduce everytime when update user password and user status。

### What Did You Expect to See?

Update user password and status successfully。

### What Did You See Instead?

return success, but got nothing changed.

**Comment by caton-wang** [comment]
修改几次可以从rocksdb事务日志中看到几次修改记录，但是日志里面的内容记录并没有进行任何修改。

![b9ebfe7480d2e5648fb2a448572b991](https://github.com/user-attachments/assets/bb6cd9b6-9701-43e5-bfcb-fa5b28ccfbf7)

**Comment by dingshuangxi888** [comment]
非常感谢捕获了这个BUG，我已经提交PR修复该问题

**Comment by caton-wang** [comment]
收到，非常感谢！
