### ISSUE TITLE
[Bug] Update User doesn‘t work

### ISSUE THREAD

**Issue by TickFairy** [apache/rocketmq#8952]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Cetos7.9

### RocketMQ version

5.3.1

### JDK Version

openjdk 11

### Describe the Bug

mqadmin update User doesn't work

### Steps to Reproduce

1. create User test-1
![image](https://github.com/user-attachments/assets/d6d41646-3639-44de-97d9-4fb274ccda93)
2. list Users 
![image](https://github.com/user-attachments/assets/79d0b9fc-3211-48b4-b894-49a9f82b6b3b)
3. update user disable

![image](https://github.com/user-attachments/assets/b7ffe214-b834-4878-9cbc-b1ee358f55a1)

4. list User
![image](https://github.com/user-attachments/assets/6552e5fa-d2d0-411a-b624-cd1c6b509bc2)

### What Did You Expect to See?

禁用用户无效，并且修改密码、类型等也无用

### What Did You See Instead?

期望能够修改成功

**Comment by TickFairy** [comment]
@dingshuangxi888 哥哥 此问题能确认吗

**Comment by dingshuangxi888** [comment]
已经提交PR了，最新develop分支已经修复
https://github.com/apache/rocketmq/pull/8926

**Comment by TickFairy** [comment]
ok 咱们会发布新版本吗

**Comment by universefeeler** [comment]
退订













在 2024-11-19 18:27:00，"TickFairy" ***@***.***> 写道：

ok 咱们会发布新版本吗
