### ISSUE TITLE
负载均衡的实际效果和官方文档不对应

### ISSUE THREAD

**Issue by jiao-duan** [apache/rocketmq#9004]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

MacOS

### RocketMQ version

5.2.0

### JDK Version

1.8

### Describe the Bug

官方文档的描述是5.X版本以后是消息级别的负载：![image](https://github.com/user-attachments/assets/e9212464-afe1-4f77-81d6-52234ca38d20)
源码版本为：
![image](https://github.com/user-attachments/assets/b3d5a59b-b22d-4639-a61a-6d9e07cc3965)
源码中PushConsumer使用的还是AllocateMessageQueueAveragely负载均衡类 
![image](https://github.com/user-attachments/assets/e2550be0-1841-4970-b8f8-7b460bce2bc9)
实际使用和测试都发现，超过队列数以后得消费者都不会被分配对应的队列，那此时不是还是队列粒度的负载均衡么？为何官方文档提到的是消息粒度的？

### Steps to Reproduce

`List<String> cidAll = Arrays.asList("cid-1", "cid-2", "cid-3", "cid-4", "cid-5", "cid-6", "cid-7");
        List<MessageQueue> mqAll = Arrays.asList(
            new MessageQueue("topic", "broker-a", 0),
            new MessageQueue("topic", "broker-a", 1),
            new MessageQueue("topic", "broker-a", 2),
            new MessageQueue("topic", "broker-a", 3)
        );

        List<MessageQueue> testallocate = testallocate("group-1", "cid-7", mqAll, cidAll);
        System.out.println(testallocate);`
以上是简单的测试用例，发现后面的消费者都是没有分配队列的

### What Did You Expect to See?

我希望看到的是符合官方文档中提到的消息级别的负载均衡

### What Did You See Instead?

无

**Comment by jiao-duan** [comment]
应该相信官方文档描述还是相信实际实验效果和源码？

**Comment by yiduwangkai** [comment]
需要设置消费模式为pop消费

**Comment by jiao-duan** [comment]
官方文档说的默认的push和pull都支持啊
