### ISSUE TITLE
PrintMessageByQueueCommand may not print the right msgs 

### ISSUE THREAD

**Issue by pigpdong** [apache/rocketmq#903]
**BUG REPORT**

1. Please describe the issue you observed:
* What did you do (The steps to reproduce)?
PrintMessageByQueueCommand with the option -d -e
* What did you expect to see?
  print the right msglist
* What did you see instead?
 the -e may get a max offset,but consumer.pull(mq, subExpression, offset, 32); this code may return the msg which bigger than the maxoffset

and the option -d -d describe as a string like End timestamp[currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]  but acturally it need a long 
timestamp = Long.parseLong(value);

1. Please tell us about your environment:
   None.
2. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
   None

**Comment by ymwneu** [comment]
A good ISSUE.
Two problems:
1. -d can accept both "yyyy-MM-dd#HH:mm:ss:SSS" or long style timestamp. Look PrintMessageByQueueCommand#timestampFormat for more detail.
2. Your PR have a bug, i have already given my comment.

**Comment by ymwneu** [comment]
The max offset problem, i suggest you optimize method "PrintMessageByQueueCommand#calculateByTag" and "PrintMessageByQueueCommand#printMessage" to filter the messages which exceed the max offset.
