### ISSUE TITLE
[Bug] tiered store  ConstructIndexFile ConcurrentModificationException

### ISSUE THREAD

**Issue by wangshaojie4039** [apache/rocketmq#9069]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [x] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

linux

### RocketMQ version

devlop|5.3.x

### JDK Version

jdk1.8

### Describe the Bug

    public CompletableFuture<Void> commitAsync(FlatFileInterface flatFile) {
        return flatFile.commitAsync().thenAcceptAsync(success -> {
            if (success) {
                if (storeConfig.isMessageIndexEnable()) {
                    flatFile.getDispatchRequestList().forEach(
                        request -> constructIndexFile(flatFile.getTopicId(), request));
                }
                flatFile.release();
            }
        }, storeExecutor.bufferCommitExecutor);
    }
-------------------------------------------
I found this issue while conducting stress testing on tieredstore. When the TPS reached 100000, the Messenger Dispatcher # ConstructIndexFile call threw an exception
”java.util. ConcurrentModificationException“

### Steps to Reproduce

Tested again, it still appears, as shown in the screenshot below

### What Did You Expect to See?

Index construction without errors

### What Did You See Instead?

--

**Comment by humkum** [comment]
you can submit a pr to fix this bug
