### ISSUE TITLE
If consumer attachQueue after startup, can't receive messages

### ISSUE THREAD

**Issue by xingkudu** [apache/rocketmq#932]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
rocketmq openmessage impl PullConsumer example：
 pullconsumer attachqueue after startup
- What did you expect to see?
receive message
- What did you see instead?
that can't receive message
2. Please tell us about your environment:
none
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
none

**Comment by ymwneu** [comment]
I have tested this example, i found it can receive message normally. Make sure you set the right nameserver address in your environment variables.
