### ISSUE TITLE
The difference value between broker offset and consumer offset is not zero after reseting offset

### ISSUE THREAD

**Issue by ssssssnake** [apache/rocketmq#951]
"sh mqadmin resetOffsetByTime -g consumerGroup -t topic -s now"

After the above command is executed, the difference value between broker offset and consumer offset is 1, should it be expected to be 0?

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/13062159/53610344-6b0c9300-3c05-11e9-95f9-eaae3cb87905.png">

**Comment by ymwneu** [comment]
It's really a problem, i have proposed a PR to fix it.
